### ISSUE TITLE
Update attributes in callbacks not taking effect

### ISSUE THREAD

**Issue by satb** [go-gorm/gorm#111]
Hi,

First of all, thank you so much for creating this library. 

Question:

I am trying to update the updated_at timestamp in the BeforeCreate callback. The callback is getting called, but even though I set the attribute in the callback, it won't take effect. There seems to be very little documentation on the callbacks

```
func (r *BaseModel) BeforeCreate() error {
    fmt.Println("BEFORE Create")
    r.CreatedAt = time.Now()
    r.UpdatedAt = r.CreatedAt
    fmt.Println("Updated at =", r.UpdatedAt)
    return nil
}
```

The database struct is like this

```
type BaseModel struct{
   CreatedAt   time.Time
  UpdatedAt   time.Time
}
type Company struct {
    BaseModel
    name string
}
```

The BEFORE Create line prints. The UpdatedAt is not being set. How do I know? Because I get an error back from gorm since on my database I have a constraint for updated_at to not be null.

Even if you have another way to set the UpdatedAt, I would like to know what is the way to set attributes from the callbacks.

Thanks for helping.

**Comment by amrnt** [comment]
@jinzhu I have the same issue...

```go
type BaseModel struct {
	ID        string     `json:"id" sql:"type:uuid;primary_key;default:uuid_generate_v4()" gorm:"primary_key"`
	GID       string     `json:"gid" sql:"type:varchar(100);unique_index" gorm:"column:gid"`
        // ...
}

func (m *BaseModel) BeforeCreate() (err error) {
	m.GID = "XXXstring"
	return
}

type User struct {
	core.BaseModel
        // ...
}

u := &User{...}

```

that callback doesn't fire when `db.Create(u)`
