### ISSUE TITLE
Is it possible to prefix the sql statement columns with a pg schema name?

### ISSUE THREAD

**Issue by debugging** [go-gorm/gorm#113]
On a per query basis, would it be possible to prefix the column names that get generated in the sql statements with a schema name (for postgres)?

It would be cool to be able to dynamically select which schema you want the call to go to?

example, say your postgres tables look like:

customer1.users
customer2.users

When I make a db call, I can choose which schema to use.

Possible?

**Comment by haymps** [comment]
I'm updating 10K rows using go routines and it seems as if the search_path gets lost.  I tried updating the search_path within the routine I was calling with go f(x), but it still was getting lost.  I'm switching to the db.Table for now.

`	
{	
   go DeleteDP(db, deliveredPrice, client)
}


func DeleteDP(db *gorm.DB, deliveredPrice DeliveredPrice, client)  {
	db.Exec("SET search_path TO " + client)
	db.Delete(&deliveredPrice)
}
`

**Comment by dvaldivia** [comment]
@haymps did you found a solution around this?

**Comment by gangming** [comment]
gorm.Open("postgres", "dbname=YourDB search_path=YourSearchPath")
