### ISSUE TITLE
Check if connections is closed

### ISSUE THREAD

**Issue by KLIM8D** [go-gorm/gorm#114]
Hi,
I couldn't find the feature, to check if the database connection is closed. Does this exist?
If not could you add a function to check if the DB connection is already closed?

**Comment by liuxiaoming0** [comment]
I use the GORM in my project,but happen a bug, socket too many.

   when  socket connection timeout , will GORM  close the socket ?  but I guess GORM have doing nothing about it.

Is there some Interface or method to close the socket (timeout)?
