### ISSUE TITLE
Use indexed ? (or named parameters) in query to refer to same value multiple times

### ISSUE THREAD

**Issue by karlgrz** [go-gorm/gorm#1144]
Greetings!

Let me preface with my happiness using gorm in production! It's been, for the most part, a pleasing experience.

One annoyance I have is with the way ? is used in where clauses for parameter replacement. 

There are times where I have the same parameter value that needs to go in multiple places in a single where clause, specifically when I have stupid date values that can possibly be null. For example:

```
query.Where("((? between mytable.startdate and mytable.enddate) OR (? >= mytable.startdate and mytable.enddate is null))", created, created)
```

It would be great to be able to just do something like this:

```
query.Where("((?{0} between mytable.startdate and mytable.enddate) OR (?{0} >= mytable.startdate and mytable.enddate is null))", created)
```

This is a nitpick, but it would clean up that method call just a bit.

Thanks for the great work!

**Comment by danhardman** [comment]
Named parameters would be good

**Comment by karlgrz** [comment]
@danhardman agreed, named parameters would well, also.

**Comment by smithaitufe** [comment]
Please what is the state of named parameters at the moment as requested in this issue?

**Comment by MichaelSnowden** [comment]
Any update?
