### ISSUE TITLE
能根据struct得到tablename吗

### ISSUE THREAD

**Issue by guotie** [go-gorm/gorm#119]
如题，谢谢

**Comment by axiaoxin** [comment]
db.Table("deleted_users").Count(&count) 在获取表的记录数的时候 因为通过TableName设置了表名，不想把查询代码的表名写死，这里可能需要有一个获取model表名的方法

**Comment by james70s** [comment]
比如你要从csv中导入数据，csv的文件名与表名对应，比如"users.csv"、"roles.csv"...
假如你有一个从csv中导入数据的实现，FixtrueFromCSV(&User, &Role...)，往函数中传递的是Struct，期待通过&User得到表名去加载对应的csv文件，这时候就需要用到表名。

@jinzhu

**Comment by wuzekang** [comment]
之前的版本可以这样获取表名 db.NewScope(options.Interface).TableName()， 新版本有什么替代方案吗？ @jinzhu

**Comment by birdycn** [comment]
我也有这个问题

**Comment by birdycn** [comment]
如何通过传入model struct获取与gorm一致的表名？

当然可以自己写个函数，但是后期调整的时候，可能就遇到了需要调整gorm和自己写的函数，还是不够方便，希望gorm能暴露出一个接口，传入model获取表名
