### ISSUE TITLE
Accept context args to db functions which spawn scopes

### ISSUE THREAD

**Issue by ansel1** [go-gorm/gorm#1231]
The idea would be to have alternate versions of the db functions which ultimate create the scopes and execute the sql.  These versions would accept a context arg first, following google's conventions for using golang contexts.  For example, FirstWithCtx(), DeleteWithCtx() etc.  Perhaps there is a cleaner way to do that, like a db.WithContext() function.

The purpose of carrying the context around would be to have it available in callback functions, where it could be used to enhance logging, trace execution times (with opentracing/zipkin/monkit etc), or perhaps carry some authentication context or user id to the callbacks.

**Comment by captncraig** [comment]
This would be a great addition. Really any way to create a scope that carries arbitrary data for callbacks. If I could just do `db.NewScope(model).SetData(ctx)` or whatever, I could pull that data out in my callbacks. I also want this to do profiling on begin/end query. The individual profiler is linked to each http request context.

**Comment by ansel1** [comment]
looks like go1.8 has some context support in the database package as well.  Haven't looked at it in detail yet, but adds more weight to the idea.

**Comment by captncraig** [comment]
Could this be done now with callbacks and db.Get/Set?

`db.Set("ctx",myCtx).Find(&obj)`

and in callback:

`ctx, ok := scope.Get("ctx")`

Seems to work for me. I set up two callbacks for before and after query:

```
gorm.DefaultCallback.Query().Before("gorm:query").Register("myPreQuery", myPre)
gorm.DefaultCallback.Query().After("gorm:query").Register("myPostQuery", myPost)
```

and I appear to be able to pull the context in both.

**Comment by jinzhu** [comment]
I am thinking about this, possible to add an API like this.

`db.Context(ctx).Find(&obj)`

also in callbacks, you could access the context with another API or Field

**Comment by ansel1** [comment]
That's probably the least disruptive way to add the support.  I guess it fits with gorm's general design.  Two other perspectives:

1. go guys prefer context be passed as function args, not as struct attributes.  Probably the "purest" approach would be adding variants of all the functions which execute queries:

        db.FindWithCtx(ctx, &obj)

2. when go guys retrofitted contexts into http, they did something like you suggested, storing the context in an immutable private attribute of the request struct, but the naming convention was different:

        req = req.WithContext(ctx)

**Comment by smacker** [comment]
I would love to have `WithContext` method. It will allow to get rid of wrapper that takes values from context and puts it in gorm using `db.Set`.

**Comment by ansel1** [comment]
I'm going to hack at this a bit.  I'm leaning toward adding variants of the terminal functions which take a context, i.e. `FirstWithCtx(...)`.  I know it's a lot more API, but it's more in the preferred style of the standard lib.  I think it will also make it easier to migrate a codebase to using the newer, context variants, since you can do a simple search&replace.

**Comment by remohammadi** [comment]
Is @captncraig 's workaround usable to call `1.8` with-context variants of execute/... of the `db.DB()` (`*sql.DB`)? Reading the source code of gorm, I didn't found a way to do that. As I've understood, the actual query is called on a `sqlCommon` instance, which does not allow context to be passed.

Do you accept pull request on this issue? Is there an agreement on the approach? `FirstWithCtx` is more golang-ish, but on the other hand `WithContext` is more gorm-ish! Personally, I prefer the `WithContext` approach (a little more than the other).

(My use case: I have a function with multiple queries which a context with deadline is passed to, and I want to apply the remaining time as timeout on these queries. Using the `1.8` with-context variants make the code more readable, so much more readable!)

**Comment by remohammadi** [comment]
[[WIP] Utilize go1.8 context support in database/sql](https://github.com/remohammadi/gorm/commit/b86b336ebe7540efb53c5cb1bb46adf28c7abc50)

I've tried my best to keep compatibility with go 1.7 and below. I would greatly appreciate it if you kindly give me some feedback on my approach.

**Comment by theduke** [comment]
@jinzhu any movement on this?

**Comment by pjebs** [comment]
@jinzhu any movement on this?

**Comment by remohammadi** [comment]
I can fix the conflict and update to work with `1.9`, if you're ok with the approach of the changeset.
@jinzhu

**Comment by swojtasiak** [comment]
Really important feature. It's a blocker for us at the moment. Nice to know that it will be supported in near future.

**Comment by xmirya** [comment]
To whoever interested: https://github.com/xmirya/gorm "master" branch adds `(*gorm.DB).WithContext(context.Context)` to the API that does the thing. The "rename" branch of the same repository renames the internal imports, so it can be used as-is with some vendor package management tool like `glide` (by setting `version: ` to that branch head commit hash).

This can't be considered a non-API-breaking change as the public `SQLCommon` interface was updated/switched to contextified versions of `database/sql` APIs (so all 3rd-party implementations of `SQLCommon` are not guaranteed to work - though i believe whoever directly passes `SQLCommon` to GORM actually passes `database/sql.DB` where those methods are implemented). For that reason i'm not submitting a PR, though the code can naturally be pulled/merged for v2.0 if suitable

**Comment by emirb** [comment]
Can we get https://github.com/xmirya/gorm/commit/38f5f04f50fe986720e3d77477835ec5dc3b8fe5 merged to upstream?

**Comment by jirfag** [comment]
+1 to issue. As a workaround you can use trick we use: wrap `sql.DB` with `context.Context` and make `gorm.DB` from the wrapped one. Our code is [here](https://github.com/golangci/golangci-api/blob/master/internal/shared/db/gormdb/sql.go#L35)

**Comment by zhaogaolong** [comment]
I have a method change logger in http service.

```
var Store *gorm.DB

func init(){
	db, _:= gorm.Open("mysql", connParams)
	Store = d
}

func GetDB() *gorm.DB {
	db := Store.New()
	db.SetLogger(HaveContextFieldLogger)
	return db
}

```
This solution solves the problem of log tracking for HTTP requests。

**Comment by THaGKI9** [comment]
any update on this topic?

**Comment by emirb** [comment]
@jinzhu It has been almost 2 and a half years since this issue has been opened and a fix is rather easy. Any ETA?

**Comment by tzvatot** [comment]
+1

**Comment by jeffizhungry** [comment]
+1

**Comment by doucheng** [comment]
+1

**Comment by gpopovic** [comment]
+1

**Comment by oourfali** [comment]
+1

**Comment by nimrodshn** [comment]
+1

**Comment by rawsyntax** [comment]
+1

**Comment by tkvw** [comment]
Any update on this issue? It's closed and should be fixed in the 2.0 milestone, but I don't see any progress?

**Comment by awkj** [comment]
very need add context and follow traceid when a http request arrive

**Comment by awkj** [comment]
> I have a method change logger in http service.
> 
> ```
> var Store *gorm.DB
> 
> func init(){
> 	db, _:= gorm.Open("mysql", connParams)
> 	Store = d
> }
> 
> func GetDB() *gorm.DB {
> 	db := Store.New()
> 	db.SetLogger(HaveContextFieldLogger)
> 	return db
> }
> ```
> 
> This solution solves the problem of log tracking for HTTP requests。

your logger struct is 
type GormLogger struct{
     Ctx context.Context
}
every http request arrive 

db.GetDB(ctx)

Good Idea

**Comment by jontonsoup** [comment]
this leaves a huge blind spot for us in monitoring

**Comment by umarrasydan** [comment]
No update on this at all?

**Comment by danielgatis** [comment]
Guys, I solve this problem with the following approach:
Every method in the public API has two versions, with context and without context.

my 10 cents:
https://github.com/jinzhu/gorm/pull/2829

**Comment by hairyhenderson** [comment]
Any updates @jinzhu? Seems like this has stalled, is there a reason not to go ahead with this?

**Comment by gharia** [comment]
Is this merged/closed? Any docs on how to use it? 
cc: @jinzhu

**Comment by fatih** [comment]
@jinzhu can we please at least get a response on what you think about this? I don't think people demand any work. But being clear and honest with you upcoming plans will make it easier for everyone. I can easily assume that there are many people here who would just use a fork if you would say "no, I don't plan to work on this". So for the sake of transparency, I would like to see you to share your intentions. I think everyone would appreciate it.

**Comment by jinzhu** [comment]
@fatih it will be supported in the coming v2 (refer the pinned issue)

**Comment by fatih** [comment]
Thank you @jinzhu 

For everyone else, here is the pinned issue: https://github.com/jinzhu/gorm/issues/2886

**Comment by mitar** [comment]
Updated link: https://github.com/go-gorm/gorm/issues/2886
