### ISSUE TITLE
Union Queries

### ISSUE THREAD

**Issue by bwiggs** [go-gorm/gorm#1303]
Is it possible to write union queries using the gorm sql builder? I couldn't find any docs or issues on the subject.

**Comment by kikihakiem** [comment]
Any update on this? Or is there any workaround? Thanks.

**Comment by tekkamanendless** [comment]
I've found that the easiest way is just to use `.Joins("UNION ?", someHandle.QueryExpr())`.

**Comment by tjgillies** [comment]
I do `db.Raw("? UNION ?", q1.QueryExpr(), q2.QueryExpr())`

**Comment by nuczzz** [comment]
Raw(`sql`) + Scan() maybe useful, for example:

`
type RawInfo struct{
        OrderSn string
        Money   float64
}

var list []RawInfo 

if err := db.Raw(`
	SELECT
		order_sn,
		money
	FROM
		(
			(SELECT
				order_sn,
				sett_amt AS money,
				create_time
			FROM
				table_a
			WHERE
				type='1'
			)
			UNION (
				SELECT
					bill_no AS order_sn,
					amount AS money,
					create_time
				FROM
					table_b
				WHERE
					type='1'
			)
			UNION (
				SELECT
					bill_no AS order_sn,
					money,
					trans_time AS create_time
				FROM
					table_c
				WHERE
					type='1'
			)
		) AS temp
	ORDER BY
		create_time DESC
	LIMIT
		10`).Scan(&list).Error; err != nil {
    //todo
}
`

**Comment by jchavannes** [comment]
Combining multiple of the suggestions above, the following worked well for me:

```go
.Table("a").
.Joins("JOIN ((?) UNION DISTINCT (?)) bc ON (bc.a_id = a.id)",
	db.Select("a_id").Table("b").QueryExpr(),
	db.Select("a_id").Table("c").QueryExpr()).
```
