### ISSUE TITLE
Wrong SQL generated for Preload

### ISSUE THREAD

**Issue by AndreLesa** [go-gorm/gorm#1339]
Currently using GORM to connect to two databases: POSTGRES AND sqlite (using a code switch to choose which one to use). I have a 2 database tables defined in my schema that look like this:

    type TableClient struct { 
        Model
        Synchronised bool
        FacilityID string `gorm:"primary_key"`
        Age                       int
        ClientSexID               int  
        MaritalStatusID           int
        SpecificNeeds             []TableOptionList`gorm:"many2many:options_specific_needs"`
    }

    type TableOptionList struct {
        ID        int `gorm:"primary_key"`
        Name    string
        Value   string
        Text    string
        SortKey int
      }
    

Previously, I would preload related table with code like this: 

    var dbClient TableClient
    Db.Where("facility_id = ? AND client_id = ? AND id = ?;", URLFacilityID, URLClientID, URLIncidentID).
       Preload("ClientSex").
       Preload("MaritalStatus").
       Preload("CareTakerRelationShip").
       Preload("HighestLevelOfEducation").
       Preload("Occupation").
       Preload("SpecificNeeds").
       First(&dbClient)

Now that lookup fails with a syntax error and when I look at the SQL generated, it shows the following SQL is generated:

    SELECT * FROM "table_option_lists" INNER JOIN "options_specific_needs" ON       "options_specific_needs"."table_option_list_id" = "table_option_lists"."id" WHERE (("options_specific_needs"."table_client_id","options_specific_needs"."table_client_facility_id") IN (('one','LS034')))

Pasting that into the sqlite console also fails with the same error: (near ",": syntax error)

**Comment by jinzhu** [comment]
Hello,

Could you provide a script following https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md#executable-script-template that could reproduce your issue?

**Comment by AndreLesa** [comment]
I have issue a pull request for that bug.

**Comment by jinzhu** [comment]
Copied the script from PR, pull request is used for fix things, not submit runnable script ;)

Seems like this is a hard to fix issue, it might take some time, let me think about this, for now, maybe just don't use sqlite for composite primary key...

```go
package main

import (
	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/lib/pq"
	_ "github.com/mattn/go-sqlite3"
)

var Db *gorm.DB

func init() {
	var err error
	Db, err = gorm.Open("sqlite3", "test.db")
	if err != nil {
		panic(err)
	}
	Db.LogMode(true)
}

func main() {
	facilityID := "LS342"
	clientID := "222017"

	type TableOptionList struct {
		ID   int `gorm:"primary_key"`
		Name string
	}

	type TableClient struct {
		gorm.Model
		FacilityID    string            `gorm:"primary_key"`
		ClientID      string            `gorm:"primary_key"`
		SpecificNeeds []TableOptionList `gorm:"many2many:options_specific_needs;ForeignKey:facility_id,id"`

		Client   TableOptionList
		Facility TableOptionList
	}
	Db.AutoMigrate(&TableClient{})
	Db.AutoMigrate(&TableOptionList{})

	var newClient TableClient
	Db.FirstOrCreate(&newClient, TableClient{FacilityID: facilityID, ClientID: clientID})

	Db.Model(&newClient).Association("SpecificNeeds").Append([]TableOptionList{TableOptionList{ID: 1, Name: "Lusaka"}})

	//Test with standard Preload - wrong SQL that won't work on Sqlite because
	//of the IN statement
	var DbClient TableClient
	Db.Where("facility_id = ? AND client_id = ?", facilityID, clientID).
		Preload("SpecificNeeds").
		First(&DbClient)

	//Try with custom SQL - instead it runs the custom SQL then appends the bad
	//SQL too with an AND statement.
	var DbClient2 TableClient
	Db.Where("facility_id = ? AND client_id = ?", facilityID, clientID).
		Preload("SpecificNeeds", func(s *gorm.DB) *gorm.DB {
		return s.Where(
			`SELECT *
			FROM "table_option_lists"
			INNER JOIN "options_specific_needs"
			ON "options_specific_needs"."table_option_list_id" = "table_option_lists"."id"
			WHERE ("options_specific_needs"."table_client_facility_id" = ? AND "options_specific_needs"."table_client_id" = ?)`, facilityID, clientID)
	}).
		First(&DbClient2)
}
```
