### ISSUE TITLE
Creating a database connection fails on database reboot

### ISSUE THREAD

**Issue by sholmesy** [go-gorm/gorm#1348]
Issue:

- We have a mysql database on a server.
- On rebooting the server, we start up the mysql service.
- After the mysql service is up and running, we boot up our other services, some of which use gorm and depend on the mysql database.
- Even though the mysql service is up and running, there is a delay between the service becoming available, and the database being available to accept incoming connections.
- The services using gorm will fail to connect (because of the issue above), and explicitly close the DB connection. Note this only happens when connecting with gorm, and not when connecting with other services that use the generic sql.DB connection.

I've tracked this down to the `Gorm.Open(...)`

```	
if err == nil {
	// Send a ping to make sure the database connection is alive.
	if err = db.DB().Ping(); err != nil {
		db.DB().Close()
	}
}
```

I'm not sure if this is correct behaviour. The gorm DB connection shouldn't explicitly close because the database connection isn't responding to a ping, or perhaps this should be configurable? It is quite common for databases to not be available when a service is attempting to connect to them. It is worth noting that the default sql lib doesn't suffer this problem.

Removing that code above fixes are issue.

**Comment by CraigChilds94** [comment]
:+1:

**Comment by LPfan88** [comment]
👍 
I have the same issue.

**Comment by jhgaylor** [comment]
I'm not a very experienced gopher, so maybe this is all handled transparently in database/sql... but!

If I provide the db host using dns, it would be cool for gorm to reconnect if the ip changes. In the real world, my database service process will die. I expect this and will restart it. It would be cool if gorm would reconnect. 

Would this be reasonable to bite off for a new contributor?

**Comment by pedroceles** [comment]
I'm having the exact same problem.
I don't exactly have a concrete opinion on whether an error should be returned if ping fails.
However I strongly disagree with closing the connection since it renders it useless for future use (if db access is reestablished)

**Comment by dgorohov** [comment]
https://github.com/jinzhu/gorm/blob/master/main.go#L91

I think the error must be returned back to the client if `Ping()` has failed. Like this:

```
	// Send a ping to make sure the database connection is alive.
	if d, ok := dbSQL.(*sql.DB); ok {
		if err = d.Ping(); err != nil {
		       d.Close()
                       return db, err // at least like this
		}
	}
	return
```
I am using GORM with AWS lambdas, but sometimes on a certain level of load, when several lambdas are running (perhaps that's the case) I could get a bind error from the SQL driver (`listen tcp 127.0.0.1:56016: bind: address already in use`)
