### ISSUE TITLE
What is the intention of quoting table names?

### ISSUE THREAD

**Issue by canthefason** [go-gorm/gorm#135]
We were setting table names with schemas prepended like schemaName.tableName and 
now it is resulted with 'pq: relation "schemaName.tableName" does not exist' error.
Probably it must be quoted as "schemaName"."tableName", but before that we are curious about what was the reason for quoting table names?

**Comment by 331299** [comment]
@jinzhu I met the same problem when I insert into postgres.I found the Quote function in the common_dialect.go will be used in postgresql.go, and common_dialect.go#Quote function is not right. Hope to fix it.
