### ISSUE TITLE
Support for more column types

### ISSUE THREAD

**Issue by calvinchengx** [go-gorm/gorm#142]
gorm doesn't support postgis geometry column types yet.

What's the best way to go about implementing support for geometry or geography column types?

**Comment by nferruzzi** [comment]
I created a small module out of this, just in case someone else need it https://github.com/nferruzzi/gormGIS

**Comment by timendez** [comment]
@calvinchengx how did you implement it incorrectly? I am having the same issue

**Comment by benguild** [comment]
I found that this did not work correctly with MySQL, FYI, because in order for MySQL to parse a coordinate from a `string` it needs to be wrapped in the "GeomFromText" function.

Unfortunately, it seems like you have to drop down to raw SQL to create or update these rows with MySQL.

**Comment by napalm684** [comment]
I will second the comment from @benguild something changed in MySQL versions is my suspicion with Point() data.  This solution doesn't work, I will probably drop down to storing as float columns so I can continue using GORM.

**Comment by jaanauati** [comment]
Hi, i'm implementing a `GeoPoint` field, @calvinchengx, I'm following your implementation and although i'm able to fetch data from the database and points are decode properly to pairs (lat,long) (via Scan method), I am having issues with inserting and updating data, in this case the values in the inserts/updates  are getting surrounded with single quotes, see:
```
INSERT  INTO `product_location` (`created_at`,`updated_at`,`deleted_at`,`product_id`,`coordinates`) 
VALUES 
('2019-07-10 09:28:43.18475','2019-07-10 09:28:43.18475',
NULL,'
7bd3bde0-96ae-11e9-af65-9265421abe6c', 
'POINT(-60.1239, -20.001)'
)
```

Notice that `'POINT(-60.1239, -20.001)'`  should actually be `POINT(-60.1239, -20.001)` for mysql.
Do u have any advices/directions?

**Comment by benguild** [comment]
I just went back and checked, and found that we resorted to dropping down to raw SQL for working with `POINT(...)`.

**Comment by jaanauati** [comment]
so it seems like i'll have to tackle this with raw saw.... thank you @benguild.
