### ISSUE TITLE
[Feature Request] "REPLACE INTO"

### ISSUE THREAD

**Issue by dweidenfeld** [go-gorm/gorm#1492]
Would it be possible to add a REPLACE INTO query?

So e.g.
```golang
db.Replace(&user)
```
instead of
```golang
db.Delete(&user)
db.Create(&user)
```

**Comment by JeffPHP** [comment]
Any plans for this feature request?

In the meantime, is there any possible workaround consisting in modifying the SQL query on-the-fly (replace "INSERT INTO" by "REPLACE INTO") after it has been generated by Save() and just before it's fired ?

**Comment by jinzhu** [comment]
You could use https://gorm.io/docs/create.html#Upsert-On-Conflict to achieve the same goal

**Comment by JeffPHP** [comment]
Thanks, I did not notice the "UpdateAll: true", which was what I was looking for!

**Comment by jinzhu** [comment]
Just added this `Option`, need to use the master branch to try it.

**Comment by JeffPHP** [comment]
Dear @jinzhu ,

It seems like the "UpdateAll: true" option does not update fields marked as "Default:Null" (i.e pointers in Golang) : 

type User struct {
	gorm.Model
// Won't be updated
	ProfileID *uint64 `gorm:"index:idx_profile_id;column:profile_id;type:bigint unsigned;default:null" json:"profile_id"`
// Will be updated
	UserID uint64 `gorm:"uniqueIndex;column:user_id;type:bigint;default:0" json:"user_id"`
}

Moreover, is there a way to update only entry fields that are not set to default  ?
