### ISSUE TITLE
Preventing from SQL injections

### ISSUE THREAD

**Issue by cihangir** [go-gorm/gorm#152]
Hello,
i want to open a debate for preventing from SQL injections, 

0) What we have in the package for prevention/filtering?
1) Should gorm handle `prevention`?
2) if so, what should be done in the gorm?
3) How to implement the features? (if required)

**Comment by banks** [comment]
> @vhakulinen yes, it will escape queries to avoid SQL injection

Sorry to resurrect a dead thread but I've just started using a project based on this and picked up on escaping. Reading the source code, it seems like Gorm does not do correct escaping at all.

The `DB.Quote()` methods says it "escapes" but in practice it does two incorrect things (as far as I can see):
 1. it [assumes strings with period are identifiers](https://github.com/jinzhu/gorm/blob/e5432b14d2f28ad759d8d6262c1f8a167d517f73/scope.go#L72) and quotes segments separately (what about a random string with periods in like... a sentence or two? 
 2. the actual "escape" is done by dialect which [defaults to just wrapping the input with double quotes](https://github.com/jinzhu/gorm/blob/2a1463811ee1dc85d168fd639a2d4251d030e6e5/dialect_common.go#L38) which is not "escaping" at all. For example if the literal before calling Quote is `hello"; DROP TABLE users;` only the hello part will be the final literal and injection is possible

Further, at least with Postgres, the "safe" mechanism with placeholders, seems to do the same thing:

**Comment by banks** [comment]
Partial self-correction:

It seems that prepared bindings are safe at least e.g. Postgres https://github.com/jinzhu/gorm/blob/master/dialect_postgres.go#L23.

What confused me above is that `db.LogMode(true)` _seems_ to be printing a collapsed version of the SQL which is incorrectly escaped while sending a properly prepared statement to postgres.

The `db.Quote` method seems from internal use to only be intended for quoting identifiers in which case I'm wrong that it's incorrect, however the docs clearly say it's for "escaping strings" which _is_ incorrect as it's only useful for identifiers AND assumes they are already well-formed identifiers. It's still unsafe to pass user input through this even as an identifier it seems.

**Comment by ermik** [comment]
The single quote issue described by @banks is quite confusing, the LogMode should print debug-ready queries that could be copy-pasted into DB management tool or used as raw SQL elsewhere.

**Comment by kwk** [comment]
> SELECT COUNT(DISTINCT bar) FROM "foobar"  WHERE (foo = 'don't')

@banks I was struggling with a similar problem yesterday. For escaping single quotes we do escape the input manually for postgres (the only backend we're running on):

```go
func sanitize(text string) string {
	return strings.NewReplacer("'", "''" /*We have more here*/).Replace(text)
}

foo := "don't"
db = opts.DB.Begin().
	Table("foobar").
	Select("COUNT(DISTINCT bar)").
	Where("foo = ?", sanitize(foo)).
	Count(&total).
	Commit()
```

Should generate:

```sql
SELECT COUNT(DISTINCT bar) FROM "foobar"  WHERE (foo = 'don''t')
```

**Comment by joyride9999** [comment]
@cihangir 
For html escaping im using something as the code below. Im guessing this could be integrated also into the library

type User struct {
	Id			sql.NullInt64	`gorm:"column:id;primary_key;"`
	Email      	string 			`gorm:"column:email;unique_index;type:varchar(100)" json:"email" escape:""`
}

func (u *User) BeforeCreate() (err error) {
	return Sanitize(u)
}

func (u *User) BeforeUpdate() (err error) {
	return Sanitize(u)
}

func Sanitize(obj interface{}) error {

	t := reflect.TypeOf(obj).Elem()
	v := reflect.ValueOf(obj).Elem()

	for i := 0; i < t.NumField(); i++ {

		field := t.Field(i)

		if _, ok := field.Tag.Lookup("escape"); ok {
			switch v.Field(i).Interface().(type) {
			case string:
				v.Field(i).SetString(html.EscapeString(v.Field(i).String()))
			}
		}
	}
	return nil
}
 =====
If you want something more generic you can have also ...


func HtmlEscape(scope *gorm.Scope) {
	Sanitize(scope.Value)
}

db.Callback().Create().Before("gorm:create").Register("html_escaper", HtmlEscape)
db.Callback().Create().Before("gorm:update").Register("html_escaper", HtmlEscape)
