### ISSUE TITLE
Reflect error with slices of pointers

### ISSUE THREAD

**Issue by ernestoalejo** [go-gorm/gorm#158]
UPDATE: See my other comment below
# 

When using Find() on a slice of structs without the DeletedAt property.

The problem is this line:
  https://github.com/jinzhu/gorm/blob/master/scope.go#L121

Now it says:

``` go
return nil, reflect.New(data.Type().Elem()).Elem().FieldByName(name).IsValid()
```

and it needs one more Elem() there before creating the new value:

``` go
return nil, reflect.New(data.Type().Elem().Elem()).Elem().FieldByName(name).IsValid()
```

Example triggering the error:

``` go
package main

type User struct {
  Test int
}

func main() {
  db := ....start db here....
  users := []*User{}
  db.Find(&users)
}
```

And the error says: "reflect: call of reflect.Value.FieldByName on ptr Value".

I'm opening this issue first instead of a pull request because I started using the library today and don't know if that change has side effects elsewhere.

**Comment by Tom29** [comment]
@ernestoalejo  I see we now can use slice of pointers on gorm, but someone please tell me which receiver should be, slice of struct or pointer is good practice?
