### ISSUE TITLE
Using too many connections with transactions from multiple Go-routines causes lock-up

### ISSUE THREAD

**Issue by benguild** [go-gorm/gorm#1669]
### What version of Go are you using (`go version`)?
1.6.4

### Which database and its version are you using?
MySQL 5.7

### What did you do?

I noticed that if you set the MySQL connection count to a low amount (say 4) then launch 4 Go-routines and open transactions on all of them, the program seems to just lock-up.

I'm not sure what the expected behavior in this case should be, but if I set the connection count to be *at least* the number of Go-routines, it runs fine... as the connections cycle while the system loops through Go-routines, etc.

Has anyone else run into this issue?

**Comment by fatal10110** [comment]
Same here :(

**Comment by fatal10110** [comment]
So the reason was that we executed a query outside of transaction, while the current transaction was acting, so it goes to the pool, and asks a new connection for that query. If you have a pool of X connections, and X gorutines(each gorutines holds its own connection then) opened a transaction, then tries to evaluate a query  outside of transaction, it needs a new coonection, so it will wait for a connection forever(lock)

**Comment by jinzhu** [comment]
Hi, Could anyone post a runnable code that could reproduce the issue?

**Comment by DearMadMan** [comment]
@duguying Hi, 你所遇到的问题最终解决了吗？这个问题是由什么引起的？

**Comment by duguying** [comment]
@DearMadMan 还没解决，暂时没时间去研究gorm，猜测应该是某个地方导致连接池泄露

**Comment by guoyucheng** [comment]
@DearMadMan 最近我也遇到这个问题了，产生原因：开始事务后没 commit 或者Rollback，导致连接一直在等待。解决办法增加commit或者Rollback就可以了。

**Comment by duguying** [comment]
@guoyucheng 不是的，我说的绝对带commit和rollback了。正常提交了事物也会连接数增加。你没遇到可能是没有触发或者是并发量不够。

**Comment by duguying** [comment]
怀疑有可能与mysql驱动有关，我补充一下我的mysql驱动版本，所在项目目前不由我维护了
```json
{
	"ImportPath": "----",
	"GoVersion": "go1.10",
	"GodepVersion": "v79",
	"Deps": [
		{
			"ImportPath": "github.com/go-sql-driver/mysql",
			"Comment": "v1.3-2-g2e00b5c",
			"Rev": "2e00b5cd70399450106cec6431c2e2ce3cae5034"
		},
		{
			"ImportPath": "github.com/jinzhu/gorm",
			"Comment": "v1.9.1",
			"Rev": "6ed508ec6a4ecb3531899a69cbc746ccf65a4166"
		},
		{
			"ImportPath": "github.com/jinzhu/gorm/dialects/mysql",
			"Comment": "v1.9.1",
			"Rev": "6ed508ec6a4ecb3531899a69cbc746ccf65a4166"
		},
		{
			"ImportPath": "github.com/jinzhu/inflection",
			"Rev": "74387dc39a75e970e7a3ae6a3386b5bd2e5c5cff"
                },
                ....
	]
}
```

**Comment by helperShang** [comment]
开发几周了，现在压测报出这个问题，内心千万个艹，只有换其他orm了！

**Comment by josephGuo** [comment]
是不是链式api设计带来的问题？有没有抛弃链式调用的计划？
