### ISSUE TITLE
.Raw not working on parameters with $

### ISSUE THREAD

**Issue by andymok221** [go-gorm/gorm#1695]
### What version of Go are you using (`go version`)?
1.9

### Which database and its version are you using?
Postgres 9.6

### What did you do?
`row := db.Raw("SELECT * FROM users WHERE username = ?", "user$1").Row()` will be translated to `SELECT * FROM users WHERE username = "user"`, the `$1` disappears. 
I wonder if I am using the raw query wrongly or `$1` is being treated as a prepared statement parameter.

**Comment by kylycht** [comment]
Same problem, [bcrypt](https://godoc.org/golang.org/x/crypto/bcrypt) produced password gets cut off or completely blank
e.g. 
```golang
password :="$2a$10$F5qTiDJDNPrP6/eUUEL5dT4jsan3OBFQ1.xIcbioXq"
```
```sql
UPDATE "accounts" 
SET "password" = '/eUUEL5dT4jsan3OBFQ1.xIcbioXq'  
WHERE "accounts"."deleted_at" IS NULL AND "accounts"."id" = 78
```
