### ISSUE TITLE
suggest "TIMESTAMP"  change to "DATETIME"

### ISSUE THREAD

**Issue by xjjrocker** [go-gorm/gorm#1786]
```go
case reflect.Struct:
			if _, ok := dataValue.Interface().(time.Time); ok {
				sqlType = "TIMESTAMP" //here
			}
```
建议默认time.time自动存储为DATETIME而不是TIMESTAMP
timestamp所能存储的时间范围为：'1970-01-01 00:00:01.000000' 到 '2038-01-19 03:14:07.999999'。
datetime所能存储的时间范围为：'1000-01-01 00:00:00.000000' 到 '9999-12-31 23:59:59.999999'。

**Comment by lockp111** [comment]
改成datetime的话，你要怎么处理时区问题呢？timestamp格式是带时区的

**Comment by Niraj-Fonseka** [comment]
Is anyone working on this ?

**Comment by ckcfcc** [comment]
严重支持，TIMESTAMP范围太小了，还有20年就强制过期了。

**Comment by itcuihao** [comment]
> 严重支持，TIMESTAMP范围太小了，还有20年就强制过期了。

首先我们先弄清楚它为什么范围小呢，是因为timestamp 仅仅只有4字节，而datetime 需要8个字节，从空间效率上考虑，优先选择这个。
另外一个timestamp是带有utc的时间格式，跳到维基百科了解下[协调世界时](https://zh.wikipedia.org/wiki/%E5%8D%8F%E8%B0%83%E4%B8%96%E7%95%8C%E6%97%B6)
