### ISSUE TITLE
db.Table("deleted_users").CreateTable(&User{}) User模型的索引不会构建在deleted_users表上

### ISSUE THREAD

**Issue by fightingforbing** [go-gorm/gorm#1791]
type User struct{
   phone int `gorm:"index:phone"`
}
执行
db.Table("deleted_users").CreateTable(&User{})时
deleted_users表会创建，但是索引会建立在user表上。
看源码发现scope.go创建索引时使用NewDB（）函数会把search结构体的值赋值为nil。

**Comment by zhongguo168a** [comment]
我再使用Save()的时候也遇到这样的问题，首先Update语句的表示正确的，但Select语句表示错误的
