### ISSUE TITLE
Can't use many2many with save_associations:false?

### ISSUE THREAD

**Issue by jerbob92** [go-gorm/gorm#1803]
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Which database and its version are you using?
MySQL 5.7.21

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

type FirstTable struct {
	gorm.Model
	SecondTables []SecondTable `gorm:"many2many:secondtables;save_associations:false"`
}

type SecondTable struct {
	gorm.Model
}

func init() {
	var err error
	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
        db.AutoMigrate(&SecondTable{})
	db.AutoMigrate(&FirstTable{})
}

func main() {
	second_item := SecondTable{}
	db.Create(&second_item)

	first_item := FirstTable{
		SecondTables: []SecondTable{
			second_item,
		},
	}

	db.Create(&first_item)
}
```

When you run the code above, no record is created into the table "secondtables", when you remove save_associations:false, the record is created, but also the second_item record is update, which is something you probably don't want.

**Comment by mr-burnse** [comment]
Running into this as well...did you ever figure out a resolution?

**Comment by serayuzgur** [comment]
Hi, same issue , any update ?

**Comment by jerbob92** [comment]
I think I just accepted this "flaw".
