### ISSUE TITLE
Can I use []map[string]interface{}{}  in  Find method?

### ISSUE THREAD

**Issue by alphayan** [go-gorm/gorm#1806]
Can I use this code to get the sql value?
```
m:=[]map[string]interface{}{}
db.Table("test").Find(&m)
```

**Comment by emirb** [comment]
Can you provide more information about the use-case? You have to have a corresponding struct that the SQL result set will be unmarshalled into.

**Comment by rebider** [comment]
it dosen't work

**Comment by rebider** [comment]
type  Test struct{
 Id int64
Name string
}
m:=[]Test
db.Table("test").Find(&m)//it work

m:=[]map[string]interface{}
db.Table("test").Find(&m)//it dosen't wokr

**Comment by rebider** [comment]
how to get query result without buid struct modul
