### ISSUE TITLE
Gorm ignores UTF8MB4 character set in connection string when creating tables

### ISSUE THREAD

**Issue by enahs** [go-gorm/gorm#1811]
It seems like gorm ignores the value provided for the character set in the connection and simply defaults to UTF8 when creating tables. This causes issues when trying to insert emojis into varchar columns.

### Which database and its version are you using?
Mysql Server version: 5.7.19 Homebrew

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

var db *gorm.DB

type User struct {
	ID        int64
	FirstName string
	LastName  string
}

func init() {
	var err error
	// NOTE THE CHARACTER SET!!!!!!!!
	// this seems to be ignored by createTable
	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8mb4,utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	if err := db.CreateTable(&User{}).Error; err != nil {
		panic(err)
	}
	// UTF8 strings. works as expected
	you := &User{
		FirstName: "Bob",
		LastName:  "Smith",
	}
	if err := db.Create(you).Error; err != nil {
		panic(err)
	}
	// UTF8MB4 strings. does not work
	me := &User{
		FirstName: "🔫",
		LastName:  "💯",
	}
	if err := db.Create(me).Error; err != nil {
		fmt.Println(err)
	}

}

```

**Comment by enahs** [comment]
this is really just a reproducible version of  https://github.com/jinzhu/gorm/issues/1328

**Comment by enahs** [comment]
after poking around more in the source code, there is a way to do this that isn't documented. 
scope's createTable method checks for a gorm:table_options value on the scope which allows you to augment the create table statement. It would be good to add a mention to table_options in the documentation and perhaps include this as an example.

```go
tx.Set("gorm:table_options", "CHARSET=utf8mb4").AutoMigrate(&user{})
```

**Comment by CraigChilds94** [comment]
@jinzhu I agree that there should be a way to set it by default. or use the value passed into the connection string.

**Comment by ithinco** [comment]
After adding charset params `db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8mb4,utf8&parseTime=True")` and change the table's charset to utf8mb4, I solved the problem of `incorrect string value` when storing unicode in mysql.
