### ISSUE TITLE
Support multicolumn primary keys in postgres

### ISSUE THREAD

**Issue by colegleason** [go-gorm/gorm#182]
I would like to create a composite primary key.

**Comment by alaingilbert** [comment]
Do you have any example ? I can't find a way to create a multiple columns primary key.

**Comment by jinzhu** [comment]
Hi All,

Just improved composite primary key support for gorm, please checkout https://github.com/jinzhu/gorm#composite-primary-key

**Comment by alaingilbert** [comment]
Thanks ! That's appreciated :)

**Comment by egeozcan** [comment]
How do I make a many-to one connection to the entity with a composite id? For example, in the documentation, you have,

    type Product struct {
        ID           string `gorm:"primary_key"`
        LanguageCode string `gorm:"primary_key"`
    }

So how can I make it work on the following case:

    type Campaign struct {
        AssociatedProduct Product
    }

Would this work? I'd appreciate any pointers. Thanks.
