### ISSUE TITLE
gorm使用，连接db报错 

### ISSUE THREAD

**Issue by lz1988** [go-gorm/gorm#1822]
[mysql] 2018/03/30 11:27:22 packets.go:36: unexpected EOF
[mysql] 2018/03/30 11:27:22 connection.go:311: invalid connection
[mysql] 2018/03/30 11:42:32 packets.go:36: unexpected EOF
[mysql] 2018/03/30 11:42:32 connection.go:311: invalid connection
[mysql] 2018/03/30 12:20:17 packets.go:36: unexpected EOF
[mysql] 2018/03/30 12:20:17 connection.go:311: invalid connection
[mysql] 2018/03/30 13:02:30 packets.go:36: unexpected EOF
[mysql] 2018/03/30 13:02:30 connection.go:311: invalid connection
[mysql] 2018/03/30 13:06:19 packets.go:36: unexpected EOF

**Comment by lz1988** [comment]
packets.go

**Comment by scofier** [comment]
问题解决了么？

**Comment by hyacinthus** [comment]
我在升级了一次后也遇到了这个问题
后台日志大量出现 
[mysql] 2018/06/21 23:36:51 packets.go:36: unexpected EOF
(invalid connection)

虽然重试之后就连上了

但是会有影响 一部分比例的请求会失败

不知道怎么才能保持长连接

**Comment by hyacinthus** [comment]
后来我设置了服务器参数解决了。 就是服务器单方面关闭了连接。
但是比较诡异的是之前没这个问题，在我最近升级了一次后才出现的。
也许是mysql客户端改了什么默认参数吧。

**Comment by lvzhihao** [comment]
应该是连接重试的逻辑代码改动过了吧，我去掉服务中间的lb就没这些问题，lb基本都不会支持长连接，超时主动断开后就出现异常eof了。之前代码会尝试重连，现在会直接报错。

**Comment by lz1988** [comment]
如果设置了SetConnMaxLifetime，实际的使用当中是否有效？

**Comment by lz1988** [comment]
不使用SetMaxIdleConns，那么连接池的意义就不大了。

**Comment by lz1988** [comment]
这个参数给了值，依旧还是会报错

**Comment by hyacinthus** [comment]
只要客户端的时间短于服务器的时间就可以的，你需要检查下服务器上是多久超时。

**Comment by lvzhihao** [comment]
你先要确认你服务端的idle超时是多少，然后设置一个比它小的值就不会有问题的。

王瑞华 <notifications@github.com> 于2018年8月16日周四 上午11:49写道：

**Comment by lz1988** [comment]
设置db.DB().SetConnMaxLifetime(60 * time.Second) 时间，但是还是会提示连接丢失的情况。

**Comment by lvzhihao** [comment]
你要看你服务器的空闲超时设置多少，然后设置一个比服务器超时小的数值即可，我例子里的60秒只是个参考，具体情况要按你的生产环境来。

mawubian <notifications@github.com> 于2018年8月17日周五 下午5:41写道：

**Comment by lz1988** [comment]
如果按照你说的，应该不会出现连接丢失的情况

**Comment by lvzhihao** [comment]
数据库是直连的嘛，中间有LB或中间件嘛？我目前在生产环境下设置这个值是有效的，你可以具体看下哪个环节出了问题。

mawubian <notifications@github.com> 于2018年8月20日周一 下午8:31写道：

**Comment by lz1988** [comment]
数据库是直接连接，没有使用中间件，我怀疑每次在获取db的时候，需要ping下，看下连接是否有效，否则重连。

**Comment by lz1988** [comment]
好像mysql driver貌似也有类似的问题
https://github.com/go-sql-driver/mysql/issues/257#issuecomment-53886663

**Comment by lvzhihao** [comment]
我最上面已经说过了，这个就是mysql驱动的问题，和gorm没关系的。以前mysql驱动会自动重连，现在会返回err，你可以尝试设置一个更小的值，或者换回老版本的驱动。
mawubian <notifications@github.com> 于2018年8月22日周三 上午9:34写道：

**Comment by wangxf1987** [comment]
我的解决办法如下：
数据库做了lb，用nginx做的，策略如下：
`stream {
    upstream galera_cluster {
        server    172.19.146.xx:3306;
        server    172.19.146.xx:3306;
        server    172.19.146.xx:3306;

        zone tcp_mem 64k;
        zone tcp_backend 64k;
        zone tcp_servers 64k;
        least_conn;
    }
    server {
        listen       33306;
        proxy_pass   galera_cluster;
        proxy_timeout 300s;
        proxy_connect_timeout 300s;
    }
}`

代码里，初始化连接时，设置：
`db.DB().SetConnMaxLifetime(5 * time.Second)`

再次回测，暂时未发现问题复现，持续跟踪中。。。。。。

**Comment by vmstar** [comment]
有结论么

**Comment by m9rco** [comment]
有结论么

**Comment by lz1988** [comment]
&nbsp;没有哦，怀疑是那个参数设置的坑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shaowei Pu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 下午3:41
收件人:&nbsp;"jinzhu/gorm"<gorm@noreply.github.com&gt;;
抄送:&nbsp;"513245459"<513245459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jinzhu/gorm] gorm使用，连接db报错  (#1822)




有结论么

**Comment by m9rco** [comment]
我通过重连解决连该问题，虽然不是很好 。。。

**Comment by lz1988** [comment]
这个还是配置参数的问题，不过我现在监控，有时候第一次请求，会丢失连接，但是比之前好很多


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shaowei Pu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 上午9:27
收件人:&nbsp;"jinzhu/gorm"<gorm@noreply.github.com&gt;;
抄送:&nbsp;"513245459"<513245459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jinzhu/gorm] gorm使用，连接db报错  (#1822)




我通过重连解决连该问题，虽然不是很好 。。。

**Comment by Awezome** [comment]
很是诡异，把SetConnMaxLifetime设置了小于wait_timeout的时间，且SetMaxIdleConns设为0，线上还是出现了一个  invalid connection 错误日志。

```
db.DB().SetConnMaxLifetime(3 * time.Second)
db.DB().SetMaxIdleConns(0)
```

```
mysql> show variables like 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 10    |
+---------------+-------+
```

**Comment by lz1988** [comment]
试试这样，目前没有出现这个错误信息


#最大空闲连接数

maxidleconns&nbsp;=&nbsp;500
#&nbsp;最大连接数
maxopenconns&nbsp;=&nbsp;500
#&nbsp;最大生存时间
maxlifetime&nbsp;=&nbsp;0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Raymon Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 中午12:57
收件人:&nbsp;"jinzhu/gorm"<gorm@noreply.github.com&gt;;
抄送:&nbsp;"513245459"<513245459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jinzhu/gorm] gorm使用，连接db报错  (#1822)




很是诡异，把SetConnMaxLifetime设置了小于wait_timeout的时间，且SetMaxIdleConns设为0，线上还是出现了一个  invalid connection 错误日志。
 db.DB().SetConnMaxLifetime(3 * time.Second) db.DB().SetMaxIdleConns(0)  mysql&gt; show variables like 'wait_timeout'; +---------------+-------+ | Variable_name | Value | +---------------+-------+ | wait_timeout  | 10    | +---------------+-------+

**Comment by Awezome** [comment]
> 试试这样，目前没有出现这个错误信息 #最大空闲连接数 maxidleconns&nbsp;=&nbsp;500 #&nbsp;最大连接数 maxopenconns&nbsp;=&nbsp;500 #&nbsp;最大生存时间 maxlifetime&nbsp;=&nbsp;0
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Raymon Zhang"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月23日(星期天) 中午12:57 收件人:&nbsp;"jinzhu/gorm"<gorm@noreply.github.com&gt;; 抄送:&nbsp;"513245459"<513245459@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [jinzhu/gorm] gorm使用，连接db报错 (#1822) 很是诡异，把SetConnMaxLifetime设置了小于wait_timeout的时间，且SetMaxIdleConns设为0，线上还是出现了一个 invalid connection 错误日志。 db.DB().SetConnMaxLifetime(3 * time.Second) db.DB().SetMaxIdleConns(0) mysql&gt; show variables like 'wait_timeout'; +---------------+-------+ | Variable_name | Value | +---------------+-------+ | wait_timeout | 10 | +---------------+-------+ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

SetConnMaxLifetime 也设置成0？0就是不过期吧

**Comment by shallowclouds** [comment]
go-sql-driver 已经在 1.5.0 （[https://github.com/go-sql-driver/mysql/pull/934](https://github.com/go-sql-driver/mysql/pull/934)）版本修复了这个问题，但是gorm对这个的包装依然使用的是 1.4.1 版本，大家可以尝试自己导入最新的 go-sql-driver ，不使用 gorm 预先包装的 dialect（其实这个包装也就是帮你导入了go-sql-driver）。
```golang
import _ "github.com/go-sql-driver/mysql"
```

**Comment by donng** [comment]
@shallowclouds gorm 确实 gorm 只是帮忙导入而已，所以只需要更新 1.4.1 版本 的 go-sql-driver 就可以了，替换导入并无本质区别。
```
go get -u github.com/go-sql-driver/mysql
```

**Comment by donng** [comment]
楼上说的是对的，虽然 gorm 在 master 分支已经更新了 go-sql-driver 版本到 1.50，但是默认下载的 tag 版本下依旧是 1.4.1。
我这里只是更新了 go-sql-driver 没有替换导入方式，毕竟使用了 gorm 作为 ORM，就要尽量保证一致性。
```
go get -u github.com/go-sql-driver/mysql
```

**Comment by nik-hil** [comment]
Faced the same issue. I m updating/inserting over 250k records in 4 min. These values worked for me.
```
	sqlDB.SetMaxIdleConns(50)
	sqlDB.SetMaxOpenConns(50)
	sqlDB.SetConnMaxLifetime(time.Minute * 2)
```
