### ISSUE TITLE
INSERT is generated correctly by SELECT could not find it

### ISSUE THREAD

**Issue by sandyleo26** [go-gorm/gorm#1836]
During unit test on circle ci, I can see `INSERT` generated correctly to insert record and no error returned. But why subsequent `SELECT` can't find the inserted record? Also, the `AfterCreate` callback is printing the right thing. And the postgres container doesn't report error related to these.

I have several tests running in serial using the same pattern: create an record, asserting something and then delete it from the database. The failure randomly occurs at any unit test case. 

For example,
```
[2018-04-10 06:03:59]  [2.33ms]  INSERT INTO "company" ("created_at","updated_at","deleted_at","user_id","name","group","....

[31.00ms]  INSERT INTO "address" ("created_at","updated_at","deleted_at","unit_number","street_number","street_name","address2","suburb","state....

AfterCreate => &{{16 2018-04-10 06:03:59.751974214 +00......

[2018-04-10 06:03:59]  [2.21ms]  DELETE FROM "company"  WHERE (user_id IN ('110'))
AfterDelete => &{{0 0001-01....
```

My model is like this:

```
type Company struct {
	gorm.Model     `json:"-"`
	UserID          int            `json:"-"`
	Name            string         `json:"name"`
	Group           string         `json:"group"`
	CRMID          string         `json:"crmID"`
	Address        common.Address `json:"address" gorm:"polymorphic:Owner;"`
	GUIDID         uuid.UUID      `json:"guidID"`
}

type Address struct {
	gorm.Model   `json:"-"`
	UnitNumber   string  `json:"unitNumber"`
	StreetNumber string  `json:"streetNumber"`
	StreetName   string  `json:"streetName"`
	Address2     string  `json:"address2"`
	Suburb       string  `json:"suburb"`
	State        string  `json:"state"`
	Postcode     string  `json:"postcode"`
	Country      string  `json:"country"`
	Lat          float32 `json:"lat"`
	Lng          float32 `json:"lng"`
	FriendlyName string  `json:"friendlyName"`
	GoogleID     string  `json:"googleId"`
	OwnerID      int     `json:"-"`
	OwnerType    string
}
```
I've got no clue to pursue so any feedback is appreciated. Thanks.

go version: 1.9
postgres version: 10.1

**Comment by Rambatino** [comment]
In here: http://doc.gorm.io/associations.html#has-one

It references the fact that you need the inverse relationship id:

``` golang
// User has one CreditCard, UserID is the foreign key
type User struct {
    gorm.Model
    CreditCard   CreditCard
}

type CreditCard struct {
    gorm.Model
    UserID   uint
    Number   string
}
```
Thus have you tried adding `CompanyID     uint  `json:"-"`` to common.Address?

**Comment by sandyleo26** [comment]
The Address is shared by other tables. For example, People, Team etc. It uses OwnerID and OwnerType to distinguish the source. For example, a company will have OwnerType as "company" and its the company id as OwnerID.
