### ISSUE TITLE
Where boolean not building expected SQL query

### ISSUE THREAD

**Issue by koalalorenzo** [go-gorm/gorm#1857]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.9.4 linux/amd64

### Which database and its version are you using?
`sqlite3` on `:memory:"

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```
err = database.Where(&models.Tier{Hidden: false}).Find(&tl).Error
```

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("sqlite3", ":memory:")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type Book struct {
	Name   string
	Hidden bool 
}


func main() {
	tl := []Book{}
	db.Where(&Book{Hidden: false}).Find(&tl).Error
}
```

The SQL generated when running this is:
```
[2018-04-18 20:27:14]  [1.11ms]  SELECT * FROM "tiers"
```

While it should be something different. 😮

**Comment by mychaelgo** [comment]
@koalalorenzo  have you try  ?
```go
db.Where(map[string]interface{}{"Hidden": false)
```

**Comment by penguinpowernz** [comment]
@koalalorenzo any luck?
