### ISSUE TITLE
.Limit(-1).Offset(0) 问题

### ISSUE THREAD

**Issue by phonegapX** [go-gorm/gorm#1859]
err = DB.Where("level < ? OR id = ?", user.Level, user.ID).Order("id").Limit(-1).Offset(0).Find(&users).Error
上面的语句报错：near "OFFSET": syntax error

输出sql:SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((level < '99' OR id = '1')) ORDER BY "id" OFFSET 0

**Comment by joey-chan** [comment]
同样的问题
求大佬指导

**Comment by phonegapX** [comment]
同求～～～

**Comment by yangmv** [comment]
同求
