### ISSUE TITLE
cannot update time.Time when useing map[string]interface{} to update table

### ISSUE THREAD

**Issue by luowei-D** [go-gorm/gorm#1860]
### What version of Go are you using (`go version`)?
go version go1.9.3 darwin/amd64

### Which database and its version are you using?
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
This is the struct of item in the database
```go
type Item struct {
	gorm.Model
	ArrivalDate   time.Time     `gorm:"column:arrival_date;" json:"arrival_date,omitempty"`
}
```
i use ```gomap[string]interface{} ```to update the arrival_date, like this :
```go
item := map[string]interface{}{"arrival_date": "2018-02-06T07:33:21Z"}
```
i use  the code to update 
```go
db.Client.Debug().Model(&oldItem).Updates(item).Error
```
and this is the debug info in the database
```
UPDATE `items` SET `arrival_date` = '2018-02-05 07:02:21', `updated_at` = '2018-04-20 11:48:21'  WHERE `items`.`deleted_at` IS NULL AND `items`.`id` = '9'  
```
as you can see the update sql use the old arrival_date instead of the new one to update the database

**Comment by ppmoon** [comment]
Did you fixed this issue ? I have the same problem
