### ISSUE TITLE
select not returning value

### ISSUE THREAD

**Issue by haruhinoshana** [go-gorm/gorm#1862]
hi i have a problem on my gorm simple select statement i cant retrive that data...
im using gorm mysql

![image](https://user-images.githubusercontent.com/20079961/39098211-e0b50a22-4699-11e8-99b5-1d14e186e588.png)

heres my function model

func GetUserByKey(u *User,key string) (err error) {
	fmt.Println(u)

	Config.DB.LogMode(true)
	if err := Config.DB.Debug().Select("*").Where(&User{Api_key: key}).First(&User{}).Error; err != nil {
		return err
	} else {
		return err
	}
	
}

**Comment by dongshimou** [comment]
you don't need `Select("*")`.
the gorm use `select *` in sql by default.

**Comment by haruhinoshana** [comment]
i done revising the code with the suggestion above but it still returning nil i dont know wheres the issue.

![image](https://user-images.githubusercontent.com/20079961/39129735-d1add168-473d-11e8-9ab8-598f1bb8a6ab.png)

1 row affected but it always return nil


heres my model page

package Models

import (
	"../Config"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

func GetUserByUsername(u *User,username string) (err error) {
	fmt.Println(u)
	Config.DB.LogMode(true)
	if err := Config.DB.Debug().Where("username = ?", username).First(u).Error; err != nil {
		return err
	}
	return nil
}

func GetUserByKey(u *User,key string) (err error) {
	fmt.Println(u)

	Config.DB.LogMode(true)
	if err := Config.DB.Debug().Model(&User{}).Where("api_key = ?", key).First(&User{}).Error; err != nil {
		return err
	}
	return nil
	
}

the query about is working fine but my 2nd query dont.

heres my controller 

func IdologyRequest(c *gin.Context) {
		var form Models.IdologyFields
		var user Models.User
		//username := c.PostForm("user")
		if err := c.ShouldBind(&form); err == nil {
			//call model
			x := Models.GetUserByKey(&user,form.Api_key)
			fmt.Println(x)
			if x != nil {
				ApiHelpers.RespondJSON(c, 200, user,"Sucessfully login.")
			} else {	
				ApiHelpers.RespondJSON(c, 400, x,"Invalid key.")
			}
		} else {
			//c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			ApiHelpers.RespondJSON(c, 400, form,err.Error())
		}	
}

**Comment by athishsreeram** [comment]
I am facing same issue

**Comment by ReEchoPaff** [comment]
Config.DB.Debug().First(u, User{Api_key: key})  
u is *User type value.
