### ISSUE TITLE
Feature request: defaults for CreatedAt and UpdatedAt fields

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [go-gorm/gorm#1877]
I am using Postgresql for my project and noticed that fields `CreatedAt` and `UpdatedAt` created like this:

    created_at timestamp with time zone,
    updated_at timestamp with time zone

Which is very inconvenient as neither `created_at` nor `updated_at` not filled with current timestamp when inserting row. What i suggest, is to change field definitions to:

    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp

Also, probably create trigger for update of `updated_at` field, when any value is changed.

**Comment by a7a2** [comment]
U can set "DEFAULT:now()"

**Comment by GrigoriyMikhalkin** [comment]
@a7a2 Yes, that's what I do now. What i propose is to set this tag by default.
