### ISSUE TITLE
Support bulk inserts of a slice of objects

### ISSUE THREAD

**Issue by colegleason** [go-gorm/gorm#188]
I'm using gorm to populate my DB with a bunch of info from a file. It would be awesome, for performance reasons, if I could insert a whole slice with one `INSERT` SQL statement.

**Comment by calebthompson** [comment]
@jinzhu for Postgres, which uses positional arguments rather than `?` for inserts, how do you recommend we build the bulk insert statement?

**Comment by Fxlr8** [comment]
@calebthompson have a look at python/django orm, they already have this feature
