### ISSUE TITLE
Can't get `updatedAt` to update

### ISSUE THREAD

**Issue by nickoneill** [go-gorm/gorm#1884]
I'd like to take advantage of the automatic created and updated fields in gorm but I can't seem to get them to update properly.

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Which database and its version are you using?
mysql 5.6.35

### Models:

```
// Model is the same as gorm's default, but I think I might change it in the future
type Model struct {
	ID        uint       `json:"id" gorm:"primary_key"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"-"`
	DeletedAt *time.Time `json:"-" sql:"index"`
}

type SQLIssue struct {
	models.Model // this is in a different file in my project, hence the namespace
	GroupID     uint `gorm:"column:groupID"`
	Name        string
	Description string
	Script      string
	Active      bool
	ContactType string `gorm:"column:contactType"`
}
```

Creation is OK, both `createdAt` and `updatedAt` fields get the correct time.

I've tried updating both with this:
`db.Table("newissues").Where(&sqlutil.SQLIssue{Model: models.Model{ID: issueID}}).Updates(map[string]interface{}{"Name": title, "Description": description, "Script": script, "ContactType": phonebankType})`

as well as this style:
`db.Table("newissues").Where(&sqlutil.SQLIssue{Model: models.Model{ID: issueID}}).Updates(sqlutil.SQLIssue{Name: title, Description: description, Script: script, ContactType: phonebankType})`

But I'm unable to get the `updatedAt` column time to update accordingly, even though the data is updated. I thought one of the benefits of gorm was not having to manually update the `updatedAt` column - and this is definitely what the docs suggest.

What am I doing wrong here?

**Comment by a7a2** [comment]
CreatedAt          time.Time `json:"createdAt" gorm:"type:timestamp(6) with time zone;column:createdAt"`
	UpdatedAt          time.Time `json:"updatedAt" gorm:"type:timestamp(6) with time zone;column:updatedAt;default:null"`


Is work on postgres.

**Comment by nickoneill** [comment]
@a7a2 OK, I'm using the suggested model in the docs in a vanilla setup. If this doesn't work for some _specific_ reason, I'd love to know how to fix it and improve the docs so more people don't run into this.

**Comment by vabshere** [comment]
I'm facing the same issue
@nickoneill  please tell me if you were able to somehow solve it. [This](https://github.com/jinzhu/gorm/issues/1884#issuecomment-386950184) didn't work for me.
