### ISSUE TITLE
Question: is there any way to ignore associations on Query? 

### ISSUE THREAD

**Issue by munirehmad** [go-gorm/gorm#1885]
### What version of Go are you using (`go version`)?
1.10

### Which database and its version are you using?
PgSQL

I have defined model with Many Relations but I only want to return the Model with "some" associations that I specified with db.Preload() while Querying.

Right now It returns ALL the Associations with 0 values. Which translates into bloated JSON.

**Comment by tsal** [comment]
@munirehmad - if you're using JSON encoding tags in your models, you should be able to specify the "omitempty" JSON tag to drop them from JSON object.

**Comment by munirehmad** [comment]
@tsal I tried but it doesn't omit models that I didn't Preload.

For example: If a model has a belongs to relation and ID identifying the parent model but i don't preload and add `json:",omitempty"` it still gets into JSON with all 0 values including ID.

**Comment by birdycn** [comment]
i have same quetion

**Comment by tsal** [comment]
If you don't care if the data is present or not, you can use the special `-` name tag:

```
type PersonModel struct {
  SomeAssociation []SomeModel `json:"-"`
}
```

this should remove it from the generated JSON object.
