### ISSUE TITLE
Can't create uuid primary key in Postgres

### ISSUE THREAD

**Issue by parserpro** [go-gorm/gorm#1887]
Hi! When i am trying to create table with uuid PK, gorm produce table with integer PK.

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Which database and its version are you using?
Postgres 9.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```
 package main

 import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
 )

 // Organisation -
 type Organisation struct {
	gorm.Model
	id        string `gorm:"type:uuid;primary_key;default:uuid_generate_v4()"`
	Name      string
	State     int8
	Actual    bool
	Previous  string `gorm:"type:uuid"`
	Next      string `gorm:"type:uuid"`
	Permanent string `gorm:"type:uuid"`
	Inn       string
	Kpp       string
	Www       []string `gorm:"type:text[]"`
	Forms     []string `gorm:"type:text[]"`
 }

 func main() {
	db, err := gorm.Open("postgres", "host=127.0.0.1 port=9920 user=gorm dbname=gorm password=gorm sslmode=disable")

	if err != nil {
		fmt.Printf("Error! %s", err)
	}

	defer db.Close()

	db.AutoMigrate(&Organisation{})
 }


```

**Comment by dvaldivia** [comment]
Experiencing the same with postgres 10, it just won't migrate at all if a uuid is being used for primary key

**Comment by gstvg** [comment]
First, gorm.Model embedded field already contains a field ID with `gorm:"primary_key"`. 
Then, your id field is unexported. Gorm know about it´s existence, but cant set its value, so it just ignore it. That´s is imposed by reflection package.
With id as Id, i think that ID from gorm.Model would conflict with Id from your code, cause both will be named "id". If not, your code would create a table with composite primary key int from gorm.Model and uuid from your code.

**Comment by samuelralak** [comment]
1. Make sure that `uuid-ossp` extension is added to your schema. You can add it by running the following the following statement:
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
```

2. You can set the ID column type in your table as uuid like so:
```
CREATE TABLE users (
    id uuid DEFAULT uuid_generate_v4() NOT NULL
);
```
  *you can set the above in an alter statement as well if table is already created

3. Go ahead and define your model
```
 type User struct {
	gorm.Model
	id        string `gorm:"type:uuid;primary_key;default:uuid_generate_v4()"`
}
```

4.  Set Primary Key field value in a BeforeCreate callback. You can refer to the gorm documentation [here](http://doc.gorm.io/crud.html#setting-primary-key-in-callbacks)  
```
// BeforeCreate set Model's primary key value to uuid
// http://doc.gorm.io/crud.html#setting-primary-key-in-callbacks
func (user *User) BeforeCreate(scope *gorm.Scope) error {
	id, err := uuid.NewV4()

	if err != nil {
		fmt.Printf("Something went wrong: %s", err)
		return err
	}

	scope.SetColumn("ID", id)
	return nil
}
```

Not sure if am allowed to post this here but if it helps you could skim through the code in this Repo [GolangKe API](https://github.com/GolangKE/forum-api) to see how am doing it. The Project is fairly new and the README isn't detailed yet 😅 

**DISCLAIMER** Am very new to Go and actively learning.

**Comment by penguinpowernz** [comment]
Thanks for this @samuelralak we should add documentation somewhere.

**Comment by l3njo** [comment]
Check out [this answer](https://stackoverflow.com/a/56945790/9787021) on StackOverflow. I find that approach to be quite useful.
