### ISSUE TITLE
get all 0 when gets decimal field value from mysql

### ISSUE THREAD

**Issue by youtwo123** [go-gorm/gorm#1890]
#when i use gorm to gets decimal field value from mysql，whatever this struct dield type is float32，float64 or shopspring/decimal，it gets all 0

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### Which database and its version are you using?
mysql 5.6.23

### Models：

```
package main

import (
	"log"
	"github.com/shopspring/decimal"
)

func main() {
	month := "201805"
	t := "2018-05-07"
	companyUser, _ := CompanyUserRepo.GetDaily(month, t)
	for _, cu := range companyUser {
		log.Println(cu.Ks3Storage)
	}
}

type CompanyUser struct {
	Ks3Storage float64  // or float32 or decimal.Decimal
}

var CompanyUserRepo = new(CompanyUser)

func (*CompanyUser) GetDaily(month string,
	date string) ([]*CompanyUser, error) {

	var cs []*CompanyUser
	table := "company_user_201805"
	err := db.LogMode(true).Table(table).Where("stat_date=?",
		date).Find(&cs).Error
	if err != nil {
		return nil, err
	}
	return cs, nil
}
```

then output is always 0，whatever the real value is.

What am I doing wrong here ?  Or how I should do ？

**Comment by youtwo123** [comment]
@jinzhu ，please!

**Comment by limoli** [comment]
@jinzhu Confirm that it would be nice and useful having this support!
