### ISSUE TITLE
怎么支持 time.Time 的别名

### ISSUE THREAD

**Issue by aixiaoxiang** [go-gorm/gorm#1892]
我想重新定义golang 标准库里面的time.Time 格式化，定义之后发现gorm 新增数据的时候会忽略我定义的字段。

//-----------1
type JsonTime time.Time

func (this JsonTime) MarshalJSON() ([]byte, error) {
	var stamp = fmt.Sprintf("\"%s\"", time.Time(this).Format("2006-01-02 15:04:05"))
	return []byte(stamp), nil
}

func (ct *JsonTime) UnmarshalJSON(b []byte) (err error) {
	s := strings.Trim(string(b), "\"")
	ctv, _ := time.Parse("2006-01-02", s)
	*ct = JsonTime(ctv)
	return
}

//-----------2
type XXX struct{
    Cretime     JsonTime
}

是 gorm只支持标准的内置类型吗？

**Comment by timeloveboy** [comment]
同有疑问，希望官方尽快fix

**Comment by lonelv** [comment]
请问你们找到解决办法了没？

**Comment by lonelv** [comment]
我找到了解决办法https://github.com/jinzhu/gorm/issues/1611#issuecomment-329654638

**Comment by axiaoxin** [comment]
@lonelv 没看到这个解决办法是什么意思？能否解释一下
