### ISSUE TITLE
Another UpdatedAt field use case

### ISSUE THREAD

**Issue by miton18** [go-gorm/gorm#1893]
### What version of Go are you using (`go version`)?
go version go1.10.1 darwin/amd64

### Which database and its version are you using?
PostgreSQL 10

Example data model:

```go
type Student struct {
    ID                         uuid.UUID     `json:"id" gorm:"column:student_id"`
    Name                   string            `json:"name"`
    DateOfPassage   time.time      `json:"dateOfPassage" gorm:"date_of_passage"`
    CreatedAt            time.Time     `json:"createdAt" gorm:"created_at"`
    UpdatedAt           time.Time     `json:"createdAt" gorm:"created_at"`
    DeletedAt            time.Time     `json:"createdAt" gorm:"created_at"`
}
```

Every time I update a field in this model, Gorm update the UpdatedAt field, in most of the case it is a good thing.

Now, for exemple every time a student enter in the room I want to update the DateOfPassage field to now.
Gorm also update the UpdatedAt field... I don't want. Is there a way to prevent that?

Why I don't want to use the field UpdatedAt as DateOfPassage:
- I have lots of property like that in a real use case
- I want to keep the field UpdatedAt for user's modifications (Ex: when he change his Name)

**Comment by gstvg** [comment]
use 
`db.Model(&student).UpdateColumn("date_of_passege", date)`
This function execute update without calling callbacks. The code that update UpdatedAt field with time.Now is just a default gorm callback.
