### ISSUE TITLE
调用db.Create方法会在生成的sql语句中包含空字符串列

### ISSUE THREAD

**Issue by zjkyz8** [go-gorm/gorm#1902]
根据文档描述：
NOTE all fields having zero value, like 0, '', false or other zero values won't be saved into database but will use its default value, it you want to avoid this, consider to use pointer type or scaner/valuer, eg:

当某个field为空字符串时，db.Create生成的insert语句不会包含这个字段，但是现在生成的sql中是包含这个字段的。

在代码中， callback_create.go中

`
func createCallback(scope *Scope) {
	if !scope.HasError() {
		defer scope.trace(NowFunc())

		var (
			columns, placeholders        []string
			blankColumnsWithDefaultValue []string
		)

		for _, field := range scope.Fields() {
			if scope.changeableField(field) {
				if field.IsNormal {
					if field.IsBlank && field.HasDefaultValue {
						blankColumnsWithDefaultValue = append(blankColumnsWithDefaultValue, scope.Quote(field.DBName))
						scope.InstanceSet("gorm:blank_columns_with_default_value", blankColumnsWithDefaultValue)
					} else if !field.IsPrimaryKey || !field.IsBlank {
						columns = append(columns, scope.Quote(field.DBName))
						placeholders = append(placeholders, scope.AddToVars(field.Field.Interface()))
					}
				} else if field.Relationship != nil && field.Relationship.Kind == "belongs_to" {
					for _, foreignKey := range field.Relationship.ForeignDBNames {
						if foreignField, ok := scope.FieldByName(foreignKey); ok && !scope.changeableField(foreignField) {
							columns = append(columns, scope.Quote(foreignField.DBName))
							placeholders = append(placeholders, scope.AddToVars(foreignField.Field.Interface()))
						}
					}
				}
			}
		}
......
`
语句} else if !field.IsPrimaryKey || !field.IsBlank { 条件应当是&&的关系吧，否则空的不包含默认值且不是主键的字段会被生成到语句中

**Comment by yeaze** [comment]
遇到同样的问题，同问

**Comment by yalay** [comment]
+1

**Comment by sun-wenming** [comment]
@zjkyz8  请问解决了吗？有什么好的方案可以分享吗？

**Comment by liaosimin** [comment]
if field.IsBlank && field.HasDefaultValue {
看代码，只要这个条件符合就会跳过blank字段。所以在tag里加个default应该能解决：
type Animal struct {
    ID   int64
    Name string `gorm:"default:'galeone'"`
    Age  int64
}
