### ISSUE TITLE
How to get SQL lines such as scope.SQL or SQL lines actually executed to database

### ISSUE THREAD

**Issue by Croton-D** [go-gorm/gorm#1908]
My program use SQLite as database and several computers run the same progaram at the same time.When the master computer executes some SQL lines,it should send them to other computers so that all computers can make same data.
Thus I need to get the SQL lines.now I can see them only in logs or in debug infomation but I can not get and store them. 
How can I get them?

**Comment by mwm5945** [comment]
Sounds like you might want to consider a distributed DB like CockroachDB. You can still use GORM and the Postgres PQ driver.  [Here's their documentation on using Cockroach and GORM](https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb-gorm.html)

**Comment by sergolius** [comment]
@Croton-D, I have similar issue.
There is method `QueryExpr` of `*DB ` what returns `*expr`. This object includes `expr`(SQL) and it's `args`. I guess it's what we need, but it's private.
The shortest way it to make public "SQL expression" (https://github.com/jinzhu/gorm/blob/master/utils.go#L61)

**Comment by dahaisoft** [comment]
> @Croton-D, I have similar issue.
> There is method `QueryExpr` of `*DB ` what returns `*expr`. This object includes `expr`(SQL) and it's `args`. I guess it's what we need, but it's private.
> The shortest way it to make public "SQL expression" (https://github.com/jinzhu/gorm/blob/master/utils.go#L61)
> 
> p.s. Unfortunately: #427

The same problem
