### ISSUE TITLE
怎样获取最终实际执行的sql语句（用于保存在string变量中进行分发给别的计算机）

### ISSUE THREAD

**Issue by Croton-D** [go-gorm/gorm#1909]
背景：程序使用sqlite数据库，多台计算机同时运行。一台有数据库操作，需要将sql语句发送给其他各台。
目前能在log和debug信息里看到实际产生出来的sql语句。但是不能获取出来。
问题：有什么办法或者接口能获取每次最终执行的sql语句？

**Comment by Torwang1** [comment]
遇到过类似问题: 多个数据副本, 由于网络不通, 只能通过离线的sql脚本重做来达到同步.

`func UpdateCallback(scope *gorm.Scope) {

    fmt.Printf("sql:%s\n", scope.SQL)
    fmt.Printf("sqlvars: %v\n", scope.SQLVars)

    return
}`

这样可以获取到:
`sql:UPDATE `option` SET `value` = ?  WHERE `option`.`option` = ?
sqlvars: [[{"Label":"3.3.0","Value":"3.3.0"},{"Label":"3.3.1","Value":"3.3.1"},{"Label":"3.3.2","Value":"3.3.2"}] global.version.list]`
