### ISSUE TITLE
Auto preload does not work with many to many relationships

### ISSUE THREAD

**Issue by filippo-veneri** [go-gorm/gorm#1914]
When there are two entities (E and F in the example below) in a many2many relationship, the entities related to F (G in the exmaple) are not auto-preloaded.
The problem seems to be in the function handleManyToManyPreload:
* it uses DB.Rows() to fetch related entities, which does to fire query callbacks;
* it explicitly calls callCallbacks(scope.db.parent.callbacks.queries), but sets a flag that effectivly "disables" query callbacks execution;

This prevents entities from being auto-preloaded beyond a many2many  relationship.

```go
package main

import (
    "encoding/json"
    "fmt"
    "os"

    "github.com/jinzhu/gorm"
    _ "github.com/jinzhu/gorm/dialects/mssql"
    _ "github.com/jinzhu/gorm/dialects/mysql"
    _ "github.com/jinzhu/gorm/dialects/postgres"
    _ "github.com/jinzhu/gorm/dialects/sqlite"
)

type E struct {
    ID uint `gorm:"primary_key"`
    Fs []*F `gorm:"many2many:M2M_E_F"`
}

type F struct {
    ID  uint `gorm:"primary_key"`
    GID uint
    G   *G
}

type G struct {
    ID uint `gorm:"primary_key"`
}

var db *gorm.DB

func init() {
    var err error
    db, err = gorm.Open("sqlite3", "test.db")
    // db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
    // db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
    // db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
    if err != nil {
        panic(err)
    }
    db.LogMode(true)
}

func main() {
    db.DropTableIfExists(&E{}, &F{}, &G{}, "M2M_E_F")
    if err := db.AutoMigrate(&E{}, &F{}, &G{}).Error; err != nil {
        panic(err)
    }

    model := E{
        ID: 1,
        Fs: []*F{
            &F{ID: 1, G: &G{ID: 1}},
            &F{ID: 2, G: &G{ID: 2}},
        },
    }

    if err := db.Save(&model).Error; err != nil {
        panic(err)
    }

    e := E{}
    if err := db.Set("gorm:auto_preload", true).First(&e, 1).Error; err != nil {
        panic(err)
    }

    b, err := json.Marshal(e)
    if err != nil {
        panic(err)
    }
    os.Stdout.Write(b)

    if e.Fs[0].G == nil {
        fmt.Println("\nfailed")
    } else {
        fmt.Println("\nsuccess")
    }
}

**Comment by mwm5945** [comment]
Im encountering the same thing--do you have a work around?

**Comment by filippo-veneri** [comment]
We have worked around this problem by explicitly calling Preload where needed. In my example, you should replace:
```
db.Set("gorm:auto_preload", true).First(&e, 1)
```
with:
```
db.Set("gorm:auto_preload", true).Preload("Fs.G").First(&e, 1)
```

**Comment by mwm5945** [comment]
i ended up forking and deleting the [line that you reference originally](https://github.com/jinzhu/gorm/blob/77eb925ea09471b7082d9d5749b2c96be726eac2/callback_query_preload.go#L331). Works like a charm now!

**Comment by filippo-veneri** [comment]
Beware the loops... your model allows for circular relationships, so you must implement some logic to prevent loops.
If you modify the model in my example as follows:
```
// ...
type F struct {
	ID  uint `gorm:"primary_key"`
	GID uint
	G   *G
	EID uint
	E   *E
}
// ...
	model := E{
		ID: 1,
		Fs: []*F{
			&F{ID: 1, G: &G{ID: 1}, E: nil},
			&F{ID: 2, G: &G{ID: 2}, EID: 1},
		},
	}
// ...
```
You'll se that preload never stops.
The solution would be to bake loop detection in gorm itself.

**Comment by LaysDragon** [comment]
I encounter same situation,a recursive B struct also have a many2many to a A struct,while query B struct you can preloading all A Data under B Data.but preloading not working for A struct's field....
that really make me headache.
For now gorm only allow recursive preloading via auto preloading,that pretty a limit while you encounter the situation that aoto preloading is not working or you just don't want to use the autoloading since it bring too much data.
And there is no way to tell gorm how to manually fetch and loading the specified field I need....:(
