### ISSUE TITLE
HasMany how to add a new record of foreign table?

### ISSUE THREAD

**Issue by jinfagang** [go-gorm/gorm#1915]
Hi, I wanna add a new record to a foreign table, this is the struct:

```
type User struct {
	gorm.Model
	// an user account is the only way to find him
	UserAcc string  `json:"user_acc"`
	// user can have many history sessions
	UserSessions []Session `json:"user_sessions"`
}


// A Session is a chat with someone or some group
type Session struct{
	gorm.Model
	// UserID is the foreign key
	UserID int `json:"user_id"`
	Target string `json:"target"`
	TargetName string `json:"target_name"`
	LastMsg string `json:"last_msg"`
	LastTime time.Time `json:"last_time"`
}
```

As you can see, I want save a new session into user, I am writting this code:

```
user := models.User{}
	if !DB.Find(&user, "user_addr = ?", sendMsg.Sender).RecordNotFound() {
		// found that user, update it's session
		DB.Model(&user).Update({"sessions": sess})
	}
```
But, how to update it actually? (the code can not be run)

**Comment by gstvg** [comment]
if !DB.Find(&user, "user_addr = ?", sendMsg.Sender).RecordNotFound() {
		// found that user, update it's session
		DB.Model(&user).Associotions("UserSessions").Append(sess)
               //or
                user.UserSessions = append(user.UserSession, sess)
                db.Save(&user)
	}
