### ISSUE TITLE
How to setup beforeFind callback?

### ISSUE THREAD

**Issue by viettranme** [go-gorm/gorm#1919]
I would like to add additional filters for each SELECT query but it seems there's no beforeFind callback in gorm. 

Why is beforeFind not supported? Is there any way to workaround this?

Thanks

**Comment by gstvg** [comment]
You can use Scopes.

func AmountGreaterThan1000(db *gorm.DB) *gorm.DB {
    return db.Where("amount > ?", 1000)
}

dbWithAdditionalFIlters := db.Scopes(AmountGreaterThan1000)

dbWithAdditionalFIlters.Where("user_id = ?", userID).Find(&transaction)
//SELECT * FROM transactions WHERE amount > 1000 AND user_id = 123
