### ISSUE TITLE
table name with underscore

### ISSUE THREAD

**Issue by dunods** [go-gorm/gorm#1930]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.9

### Which database and its version are you using?
postgre

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
how to write class for table that has underscore
example 
table name: freelance_talents
how to define it 
type FreelanceTalent struct {

}
and how to declare it as array var:
var ftalents []FreelanceTalent

cause what i got was and error 
 cannot use ftalents (type []FreelanceTalent) as type string in argument to c.String

realy need some help

**Comment by gstvg** [comment]
Default table naming handler would already mapped  FreelanceTalent <-> freelance_talents.

For custom naming:
func (Freelance) TableName() string {
    return "freelance_talents"
}

Last error needs more info, sorry

**Comment by ademozay** [comment]
Fixed with #2040
