### ISSUE TITLE
Can I use join instead of preload to save a query?

### ISSUE THREAD

**Issue by Niondir** [go-gorm/gorm#1938]
Model:

```
type Model struct {
	Id        int64     `gorm:"type:bigserial;primary_key" json:"id"`
	CreatedAt time.Time `sql:"DEFAULT:NOW()" json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type AppInstance struct {
	Model
	AppId string `gorm:"unique_index"` // user readable id that can't change but identifies an app
}

type Datasource struct {
	Model
	App    *AppInstance `gorm:"foreignkey:id;association_foreignkey:AppID" json:"app"`
	AppID  int64        `gorm:"type:bigserial" json:"appId"`
}
```

`db.Debug().Model(&model.Datasource{}).Joins("left join app_instance on app_instance.id = datasource.app_id").Find(&datasources, where).Error`

leads to:

`SELECT "datasource".* FROM "datasource" left join app_instance on app_instance.id = datasource.app_id `

All information to fill the "App" field on the `Datasource` are available in the result set, but are not used to fill the struct. Is there a way to do so?

**Comment by dalu** [comment]
I would also like to know that. I think this lib is abandoned.
A v2 probably exists but not for the public.

Probably have to use Scan but that really beats the purpose of an ORM

**Comment by dalu** [comment]
Ok scratch that. the issue is, in the case of postgres, postgres,
which returns or rather does not return table names in their results. How should gorm know which struct it should associate results with if there is no table name? So it picks the first, or only supplied result target and maps result fields to it. The rest is discarded.

**Comment by sgon00** [comment]
No. I think you can NOT do it up to now (1.9.10). Refer to #1436
