### ISSUE TITLE
How does grom get the total number of records while using the limit query？

### ISSUE THREAD

**Issue by Torijing** [go-gorm/gorm#1953]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

go1.10.1 linux/amd64
### Which database and its version are you using?
mysql

grom 如何使用limit查询的同时取得总的记录数？类似db查询时可以使用：SELECT SQL_CALC_FOUND_ROWS name, email FROM users WHERE name LIKE ‘a%’ LIMIT 10;
SELECT FOUND_ROWS();
谢谢大佬们，欢迎围观~
# ****

**Comment by jianyuanhao** [comment]
同想知道 解决了吗？

**Comment by iHDJ** [comment]
我也想知道

**Comment by cicirise** [comment]
any body who knows it ?
