### ISSUE TITLE
How can I suppress a "duplicate entry" error on "Create()"

### ISSUE THREAD

**Issue by nallown** [go-gorm/gorm#1964]
Do you have any idea how I can suppress the error that comes from the `.Create()` function?

When I create two duplicate table entries, the database throws a "duplicate entry" error and I want to suppress this error.

### What version of Go are you using (`go version`)?
go version go1.10.3 windows/amd64

### Which database and its version are you using?
MariaDB 10.1

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
package db

import (
	"fmt"
	"strings"
	"math/rand"

	"github.com/gosimple/slug"
	"github.com/jinzhu/gorm"
)

type AnimeSlug struct {
	gorm.Model
	Slug    string `gorm:"Type:varchar(255);Column:slug;NOT NULL;unique"`
	AnimeID uint   `gorm:"Type:int(10) unsigned;Column:anime_id;NOT NULL"`
}

type Anime struct {
	gorm.Model
	Title       string `gorm:"Type:varchar(255);Column:title;NOT NULL"`
	Season      int    `gorm:"Type:int(11);Column:season;NOT NULL;DEFAULT:0"`
	Description string `gorm:"Type:mediumtext;Column:description;NOT NULL"`
	Slugs       []AnimeSlug
	Slug        AnimeSlug
}

func (anime *Anime) AfterCreate(scope *gorm.Scope) (err error) {
	newSlug := slug.Make(anime.Title)

	// This code intentionally creates two slugs for the Anime to reproduce the problem
	scope.DB().Create(&AnimeSlug{
		AnimeID: anime.ID,
		Slug:    newSlug,
	})

	created := false
	count := 1

	for !created {
		// This throws a "duplicate entry" error
		// FIXME: this error needs to be suppressed
		err := scope.DB().Create(&AnimeSlug{
			AnimeID: anime.ID,
			Slug:    newSlug,
		}).Error

		if err == nil {
			created = true
		} else if strings.Contains(err.Error(), "1062") {
			count = count + 1
			newSlug = slug.Make(fmt.Sprintf("%s-%d", anime.Title, count))
		} else {
			panic(err)
		}
	}

	return
}
```

**Comment by eugene710899989** [comment]
get the same error when there are many insert tasks

**Comment by nallown** [comment]
I fixed this by doing a `select` query for the details before I created the new database entry. And if there's already a result for the user then I don't create it, I instead update it. This won't work all the time but it works if you do simple `insert` statements.

Otherwise use something like `create or update` statements.
