### ISSUE TITLE
Preload + Selecting specific fields in the preloaded objects doesn't work

### ISSUE THREAD

**Issue by phev8** [go-gorm/gorm#1965]
I wonder if it is possible to preload only selected fields of nested database objects with gorm. Right now, I am trying to do it like this:

```go
db.Preload("Children",` func(db *gorm.DB) *gorm.DB {
    return DB.Select("id")
}).First(&labelset, id)
```

The result is then:
```json
{
    "ID": 1,
    "CreatedAt": "2018-06-29T11:32:21.293892+02:00",
    "UpdatedAt": "2018-06-29T11:32:21.293892+02:00",
    "DeletedAt": null,
    "description": "Root test",
    "parent_id": 0,
    "children": []
}
```

If I replace the "id" with "*", I get:

```json
{
    "ID": 1,
    "CreatedAt": "2018-06-29T11:32:21.293892+02:00",
    "UpdatedAt": "2018-06-29T11:32:21.293892+02:00",
    "DeletedAt": null,
    "description": "Root test",
    "parent_id": 0,
    "children": [
        {
           "ID": 2,
           "CreatedAt": "2018-06-29T11:32:38.639568+02:00",
           "UpdatedAt": "2018-06-29T11:32:38.639568+02:00",
           "DeletedAt": null,
           "description": "Child test",
           "parent_id": 1,
           "children": null
        }
    ]
}
```

Actually, I would like to have something in between, where I can select the fields in the children array (e.g. the id only).

Any idea, if this is possible, or what am I doing wrong?

### What version of Go are you using (`go version`)?
Running  go1.9.2 darwin/amd64

### Which database and its version are you using?
SQLITE

**Comment by yuys** [comment]
Must select foreignkey: return db.Select("id, parent_id")

**Comment by phev8** [comment]
That comes much closer to what I wanted. I can omit most of the other attributes when converting to json, while they are null. Still have the 'parent_id' then populated, but that's better than having also everything else.
Thank you.

**Comment by jemmycalak** [comment]
have same problem

**Comment by filipesilvaa** [comment]
@phev8 In my case, a column name from Preload table was wrong and as @yuys said, must to select the foreignkey... to debug it (to know how your query is going) just set `db.LogMode(true)` before query command or at begging of opened connection (if you wanna to track everything)
