### ISSUE TITLE
How to determine final database field name

### ISSUE THREAD

**Issue by baptistedonaux** [go-gorm/gorm#1974]
Currently, we define `type struct` model. I have a use case and I would like know what is the field name used in database.

```
type User struct {
    CreatedAt time.Time
}
```
Final field name will be `created_at` but I can't found no method in Gorm to found this.

**Comment by ermik** [comment]
1. `created_at` is automatic CamelCase->snake_case conversion that gorm performs. 
2. `gorm.Model` uses CreatedAt as one of it's fields.
3. If you do not embed it on `User` — you will not have an issue.

Also, look at how you can use annotations to set the column name yourself:
```
CreatedAt time.Time `sql:"column:creation_date;"`
```

**Comment by baptistedonaux** [comment]
I would like determine (with a internal Gorm method), the field name generated.

```
CreatedAt time.Time `sql:"column:creation_date;"`
UpdatedAt time.Time
```
Field name given will be `creation_date` and `updated_at`.

Your internal method to determine final field name to use in database is it public ?

**Comment by iAbdullah** [comment]
I don't know if you found the answer or not. but this what I found.

You can user `Scope` For example:

```golang
userScope := db.NewScope(User{})
createdAtField, ok := userScope.FieldByName("CreatedAt")
fieldName := createdAtField.DBName
```
