### ISSUE TITLE
Is enum supported?

### ISSUE THREAD

**Issue by dangkaka** [go-gorm/gorm#1978]
I can't find it now

https://github.com/jinzhu/gorm/issues/628
it was supported in the past, right?

**Comment by qshuai** [comment]
Yeah. Refer to the following example:
```
type Ecosystem string

const (
	Production Ecosystem = "production"
	TestSystem Ecosystem = "testsystem"
)

func (e *Ecosystem) Scan(value interface{}) error {
	*e = Ecosystem(value.([]byte))
	return nil
}

func (e Ecosystem) Value() (driver.Value, error) {
	return string(e), nil
}

// model define
Ecosystem        Ecosystem `json:"ecosystem" sql:"type:ENUM('production', 'testsystem')"`
```

**Comment by paqio** [comment]
getting 
`pq: type "enum" does not exist`
Any solutions?

**Comment by Entrio** [comment]
same here, a whole quest to find an answer

**Comment by AlexThurston** [comment]
Anyone find an answer to this?

**Comment by antegulin** [comment]
+1?

**Comment by friend0** [comment]
I'm not able to use enums in postgres. @qshuai the above example is non-op

**Comment by qshuai** [comment]
The sample works for me, but in mysql. postgres have not been tested.

**Comment by friend0** [comment]
Hmm, it would be good to get another pg user to verify, but looks like this may be missing functionality? I could maybe take a look at a PR if someone else can verify it's not user error

**Comment by MithunMJ** [comment]
Getting the same error, ```pq: type "enum" does not exist```

**Comment by atoami** [comment]
Is there any updates for this issue?
We need to resolve this issue ASAP.

**Comment by sillygod** [comment]
For postgresql, you should define the type in the struct tag as the following

ex.

```
type XXX struct {
	Platform            DevicePlatform      `gorm:sql:"type:platform"`
}
```

`platform` is a `data type` as enum in my case. You should use the data type instead of `type:ENUM(...` in the struct tag.

**Comment by atoami** [comment]
@sillygod Can you upload full example please?
Thanks.

**Comment by sillygod** [comment]
> @sillygod Can you upload full example please?
> For instance, with enum of platform("ios", "android").
> Thanks.

Hi @atoami, I have to say if you want to use the gorm's auto migration with the enum in PostgreSQL, it will not works. However, you can perform CRUD with enum in PostgreSQL.

First, let's prepare the database, I create the enum manually.

```
CREATE TYPE phone_model AS ENUM (
	'unknown',
	'sony',
	'pixel');
``` 

Then define the example model.

```
type phoneModel string

const (
	sony  phoneModel = "sony"
	pixel phoneModel = "pixel"
)

func (p *phoneModel) Scan(value interface{}) error {
	*p = phoneModel(value.([]byte))
	return nil
}

func (p phoneModel) Value() (driver.Value, error) {
	return string(p), nil
}

type Phone struct {
	gorm.Model
	Name       string
	PhoneModel phoneModel `sql:"type:phone_model"`
}

func (Phone) TableName() string {
	return "phone"
}
```

The key point is to use `sql:"type:phone_model"` instead. You will get `pq: type "enum" does not exist` if you try to use `sql:"enum('unknown', 'sony', 'pixel')"`.

Because the enum is defined at first, you can use gorm's AutoMigration to create table  here.

```
db.AutoMigrate(&Phone{})
```

Finally, you can test about inserting a new row.

```
if err := db.Create(&Phone{
    Name:       "alice",
    PhoneModel: sony,
}).Error; err != nil {
    panic(err)
}
```

**Comment by ykchong45** [comment]
I found on a [Chinese site](https://www.cnblogs.com/jiujuan/p/12676195.html) that the following syntax works for **MySQL** enum type definition:
`gorm:"type:enum('published', 'pending', 'deleted');default:'pending'"`

**Comment by bluebrown** [comment]
> I found on a [Chinese site](https://www.cnblogs.com/jiujuan/p/12676195.html) that the following syntax works for **MySQL** enum type definition: `gorm:"type:enum('published', 'pending', 'deleted');default:'pending'"`

This didnt work for me. I stumm got type enum does not exist.

**Comment by nielvid** [comment]
> I found on a [Chinese site](https://www.cnblogs.com/jiujuan/p/12676195.html) that the following syntax works for **MySQL** enum type definition: `gorm:"type:enum('published', 'pending', 'deleted');default:'pending'"`

This works for me in mysql

**Comment by Linchin** [comment]
Why does this type definition start with lower case? Is it because we don't want this type to be public?

```
type phoneModel string
```

**Comment by ilhm-rai** [comment]
for postgresql declare this syntax before auto migration
```
db.Debug().Exec(`
	DO $$ BEGIN
		CREATE TYPE enum_name AS ENUM ('value1', 'value2');
	EXCEPTION
		WHEN duplicate_object THEN null;
	END $$;`)

db.Debug().AutoMigrate(...)
```

**Comment by yangyang5214** [comment]
If  enum is generated by protoc, can use this plugin  

https://github.com/yangyang5214/protoc-gen-gorm-serializer .

```
# task.proto
syntax = "proto3";

enum TaskStatus {
  Unknown = 0;
  Running = 1;
  Exiting = 2;
  Pending = 3;
}


# gen gorm-serializer.pb.go
protoc --proto_path=.  --go_out=paths=source_relative:. --gorm-serializer_out=paths=source_relative:.  task.proto

# use 
type Task struct {
	gorm.Model
	Name   string
	Status example.TaskStatus `gorm:"type:int"`
}
```

**Comment by abishz17** [comment]
`sql:"type:enum('Published', 'Pending', 'Deleted');default:'Pending'"` 
This tag works perfectly with gorm's automigrate in postgres.

**Comment by nkbhasker** [comment]
I have recently done something like this with Atlas.

Define enum
`type GenderEnum string

const (
	MALE   GenderEnum = "MALE"
	FEMALE GenderEnum = "FEMALE"
)

func (e *GenderEnum) Scan(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("invalid str")
	}
	*e = GenderEnum(str)

	return nil
}

func (e GenderEnum) Value() (interface{}, error) {
	return string(e), nil
}
`
Define model with enum field

`type User struct {
	gorm.Model
	Name   string
	Email  string
	Gender *enums.GenderEnum `gorm:"type:gender"`
}`

Create a migration script with enums and models
`package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	_ "ariga.io/atlas-go-sdk/recordriver"
	"ariga.io/atlas-provider-gorm/gormschema"
	"github.com/nkbhasker/go-gorm-atlas-example/models"
)

func main() {
	sb := &strings.Builder{}
	loadEnums(sb)
	loadModels(sb)

	io.WriteString(os.Stdout, sb.String())
}

func loadEnums(sb *strings.Builder) {
	enums := []string{
		`CREATE TYPE gender AS ENUM (
			'MALE',
			'FEMALE'
		);`,
	}
	for _, enum := range enums {
		sb.WriteString(enum)
		sb.WriteString(";\n")
	}
}

func loadModels(sb *strings.Builder) {
	models := []interface{}{
		&models.User{},
	}
	stmts, err := gormschema.New("postgres").Load(models...)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}
	sb.WriteString(stmts)
	sb.WriteString(";\n")
}
`
Create atlas file 

`data "external_schema" "gorm" {
  program = ["go", "run", "./migrate.go"]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "docker://postgres/16/dev"
  migration {
    dir = "file://migrations"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}`

Link to example repository [go-gorm-atlas-example](https://github.com/nkbhasker/go-gorm-atlas-example)

**Comment by nkbhasker** [comment]
I have recently done something like this with Atlas.

Define enum
```
type GenderEnum string
const (
	MALE   GenderEnum = "MALE"
	FEMALE GenderEnum = "FEMALE"
)

func (e *GenderEnum) Scan(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("invalid str")
	}
	*e = GenderEnum(str)

	return nil
}

func (e GenderEnum) Value() (interface{}, error) {
	return string(e), nil
}
```

Define model with enum field

```
type User struct {
	gorm.Model
	Name   string
	Email  string
	Gender *enums.GenderEnum `gorm:"type:gender"`
}
```

Create a migration script with enums and models
```
func main() {
	sb := &strings.Builder{}
	loadEnums(sb)
	loadModels(sb)

	io.WriteString(os.Stdout, sb.String())
}

func loadEnums(sb *strings.Builder) {
	enums := []string{
		`CREATE TYPE gender AS ENUM (
			'MALE',
			'FEMALE'
		);`,
	}
	for _, enum := range enums {
		sb.WriteString(enum)
		sb.WriteString(";\n")
	}
}

func loadModels(sb *strings.Builder) {
	models := []interface{}{
		&models.User{},
	}
	stmts, err := gormschema.New("postgres").Load(models...)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}
	sb.WriteString(stmts)
	sb.WriteString(";\n")
}
```
Create an atlas.hcl file 

```
data "external_schema" "gorm" {
  program = ["go", "run", "./migrate.go"]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "docker://postgres/16/dev"
  migration {
    dir = "file://migrations"
  }

  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```

Link to example repository [go-gorm-atlas-example](https://github.com/nkbhasker/go-gorm-atlas-example)
