### ISSUE TITLE
Make common/bundled dialects public

### ISSUE THREAD

**Issue by majelbstoat** [go-gorm/gorm#1979]
Gorm is great when working with supported databases. However, it's much harder to write a custom dialect than it needs to be. I need to write a custom dialect for redshift. This is 95% the same as postgres, but needs special support around a couple of things, for instance lack of `RETURNING` support.

Ideally, I would do:

```go
type Redshift struct {
  gorm.Postgres
}

func (s Redshift) LastInsertIDReturningSuffix(tableName, key string) string {
  return ""
}
```

And be done. However, because `postgres` is not public, I have to reimplement every single part of the dialect. And what's worse, postgres itself composes `commonDialect` which is also not public, so I have to reimplement all of those methods too.

Making dialects public would allow us to make minimal modifications and react to future database products without requesting gorm support for them. cf. https://github.com/jinzhu/gorm/issues/1816, https://github.com/jinzhu/gorm/issues/1572.

**Comment by pedromorgan** [comment]
All makes sense, and just some renaming correct ?
