### ISSUE TITLE
created_at,update_at not same as my local time for postgreSQL

### ISSUE THREAD

**Issue by guptamisha** [go-gorm/gorm#2000]
I tried using loc=Local, but it did not work for me. 
db, err := gorm.Open("postgres", "host=localhost port=5432 user=postgres dbname=safex password=postgres sslmode=disable parseTime=True loc=Local"

**Comment by mykytanikitenko** [comment]
You need a gorm.NowFunc

**Comment by pedromorgan** [comment]
is this a bug ?
