### ISSUE TITLE
updates not working for bool values

### ISSUE THREAD

**Issue by sym3tri** [go-gorm/gorm#202]
When applying updates gorm appears to omit golang 'zero-values' from the update struct. In the case of boolean fields this means `true` values will update the db record to `true` as expected, however `false` values are omitted from the sql statement all-together. The net result is that you can set any boolean value to `true`, but afterwards you can never set it to `false` again.

**Comment by jeberly** [comment]
I know this is an old ticket, but has it been solved other than those options mentioned above?
