### ISSUE TITLE
cockroachdb transactions

### ISSUE THREAD

**Issue by ernezt** [go-gorm/gorm#2045]
Hi,

We're using gorm together with cockroachdb. When multiple reads and writes hit the database at the same time, sometimes transactions fail and are not retried. This results in the following error:

```
pq: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): \"sql txn\" id=c2c225c3 key=/Table/5625/1/\"aap\"/0 rw=true pri=0.00935500 iso=SERIALIZABLE stat=PENDING epo=0 ts=1533209057.273505045,1 orig=1533209057.205717428,0 max=1533209057.205717428,0 wto=false rop=false seq=4
```

Since cockroachdb requires some sort of client side retry logic, it would be nice if we would be able to run the transaction that is created by gorm using the [crdb library](https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go), by implementing the Tx interface it provides and wrapping it with ExecuteInTx. Is there a way to do this right now? For now i've resorted to turning off transactions completely. Of course this is less than ideal.

```go
db.Callback().Create().Remove("gorm:begin_transaction")
db.Callback().Update().Remove("gorm:begin_transaction")
db.Callback().Delete().Remove("gorm:begin_transaction")
```

Thanks!

**Comment by kamushadenes** [comment]
:+1:

**Comment by prashant182** [comment]
Is there a plan to support this feature? It will be really nice to have this, as many of our production code in GORM and we might need to switch to crdb just so that we can avoid transactions failure.

**Comment by RJPercival** [comment]
Is this something that'd require a CockroachDB dialect?

**Comment by RJPercival** [comment]
Looking into this, it seems you'd have to do something like `gorm.Open("postgres", cockroachDB)`, where `cockroachDB` implements `gorm.SQLCommon` using [crdb](https://github.com/cockroachdb/cockroach-go/tree/master/crdb).
