### ISSUE TITLE
Get output parameter after executing stored procedure

### ISSUE THREAD

**Issue by RadhikaBhat** [go-gorm/gorm#2053]
How can I fetch output parameter after executing a stored procedure.

          outparam :=""
          query := "set nocount on; exec [sp_runme] '" + param1 + "'"
	 rows, execErr := dbConn.Query(query)
	 if err != nil {
		fmt.Println("error",err)
	}
	rows, err := statement.Query(query)
	if err != nil {
		fmt.Println("error",err)
	}
	for rows.Next() {
		err := rows.Scan(&outparam)
		if err != nil {
		fmt.Println("error",err)
		}
         fmt.println("output param",outparam)

Thanks in advance!!

**Comment by Aleyr** [comment]
I'm having the same issue

**Comment by Entrio** [comment]
Are there any news on this?
