### ISSUE TITLE
Running Raw query with separate Where produces wrong sql (bracket)

### ISSUE THREAD

**Issue by primus11** [go-gorm/gorm#2056]
Running raw query with separate condition adds closing bracket ')' after raw query. Closing bracket also seems to be missing for Where.

### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Which database and its version are you using?
sqlite3

### Please provide a complete runnable program to reproduce your issue. 

*edited
```
func TestSeparateConditionWithRaw(t *testing.T) {
	user1 := User{Name: "arandomuser"}
	DB.Save(&user1)

	DB.LogMode(true)
	defer DB.LogMode(false)
	// Outputs:
	// select id, name from users where 1=1) AND (name = 'arandomuser' ORDER BY "users"."id" ASC LIMIT 1

	var user2 User
	DB.Raw("select id, name from users where 1=1").
		Where("name = ?", "arandomuser").
		First(&user2)

	if user1.Id != user2.Id {
		t.Errorf("Wrong data returned")
	}
}
```

### Similar/related

- https://github.com/jinzhu/gorm/issues/1214
- https://github.com/jinzhu/gorm/commit/f2fe351aa05655c528b139a3d28c519fcea9d429

**Comment by primus11** [comment]
I don't know if this was ever supposed to be used this way but if it can be done then I can't see any reason why not. Below fixes this:

```
func (scope *Scope) CombinedConditionSql() string {
	joinSQL := scope.joinsSQL()
	whereSQL := scope.whereSQL()

	if scope.Search.raw {
		// moved to scope.whereSQL()
		// whereSQL = strings.TrimSuffix(strings.TrimPrefix(whereSQL, "WHERE ("), ")")
	}

	return joinSQL + whereSQL + scope.groupSQL() +
		scope.havingSQL() + scope.orderSQL() + scope.limitAndOffsetSQL()
}


func (scope *Scope) whereSQL() (sql string) {
	...
	for index, clause := range scope.Search.whereConditions {
		if sql := scope.buildCondition(clause, true); sql != "" {
			if scope.Search.raw && index == 0 {
				andConditions = append(andConditions,
					strings.TrimSuffix(strings.TrimPrefix(sql, "("), ")"))
			} else {
				andConditions = append(andConditions, sql)
			}
		}
	}
	...
	} else if len(combinedSQL) > 0 {
		if scope.Search.raw {
			sql = combinedSQL
		} else {
			sql = "WHERE " + combinedSQL
		}
	}
	return
```

**Comment by thejdavid** [comment]
+1

**Comment by berk-can** [comment]
I think using Raw and Where Order by etc. are necessary but I mainly use Raw for joining tables, and I would rather to use Where instead of unnecessary and complex function writing that will combine them also Where takes care of sql injection etc. also this function may be deprecated if we use scope etc. and we may have problem after updates so please consider offically supporting Raw, Where, Order By, Limit etc

**Comment by thejdavid** [comment]
Why is it closed? Support Ed in V2?

**Comment by jinzhu** [comment]
`Raw` is not expected to work with `GORM API`, check out http://v2.gorm.io/docs/sql_builder.html, I will update the document to make it clear

Thank you.
