### ISSUE TITLE
Question: How to concat two OR query with AND?

### ISSUE THREAD

**Issue by tempura-shrimp** [go-gorm/gorm#2059]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.9.1

### Which database and its version are you using?
PG

I wish to achieve something like
 
```
SELECT * FROM "stories"  WHERE "stories"."deleted_at" IS NULL AND ( x = '10' OR y = '11' ) AND ( z = '12' OR a = '13')
```

from document I can only chain query like:

```
query1 := DB.Where("x", 10).Or("y", 11)
query2 := DB.Where("z", 12).Or("a", 13)

```

but i cannot concat query1 and query2, is there any way to achieve this?

**Comment by weidongyao** [comment]
I think it's a bug of Gorm to do this, the combination of and&or will be useless. Maybe splicing sql  is a way to solve this problem, but not elegant. If getting new idea, please  keep me informed. Thanks.

**Comment by jhartman86** [comment]
@lincanli wondering this exact same thing and have a question on StackOverflow: https://stackoverflow.com/questions/53213551/how-to-build-where-query-with-grouped-ors

**Comment by jhartman86** [comment]
@lincanli @weidongyao Solving this was a necessity for me, so had to build something. Posting back here in case this helps anyone else out in the future.

[This gist](https://gist.github.com/jhartman86/0f102614a8c7078044ffe70513fe3adb) has code for programmatically building a nested WHERE clause with any number of nested AND/OR (...) groups, returning a struct that contains the generated SQL, and a slice of values - so its usable for passing to `gorm.db.Where()`. It's not the prettiest thing ever, but it does work, and it's really flexible. 

Example:
```
where := build(constraints{
	{col: `alpha`, val: 1},
	{
		operator: "OR",
		groupOR: constraints{
			{col: `bravo`, val: 2},
			{
				operator: "AND",
				groupOR: constraints{
					{col: `charlie`, val: 3},
					{col: `delta`, val: `game on`},
				},
			},
		},
	},
})

// where.Query = (alpha = ? OR (bravo = ? AND (charlie = ? OR delta = ?)))
// where.Values = []interface{1, 2, 3, `game on`}

// Usage with GORM:
var t thing
db.Where(where.Query, where.Values...).Find(&t)
// Executes: SELECT * FROM `things` WHERE (alpha = 1 OR (bravo = 2 AND (charlie = 3 OR delta = 'game on')))
```

cc: @jinzhu : would something like this, such that WHERE statements can be composed by passing in a specific recursive type, be open for consideration to a PR?

**Comment by liepumartins** [comment]
Also looking for such feature, grouping where conditions is a must for ORM, if not a deal-breaker.
This approach works well: https://laravel.com/docs/5.8/queries#parameter-grouping

**Comment by jadczakd** [comment]
Had similar issued today ended up doing :
`Db.Model(&model{}).Select("select string").Where("exists(?)", tx.SubQuery()).Group("type")
`
which is far from perfect but does the job
