### ISSUE TITLE
custom TableName works incorrect via Find queries

### ISSUE THREAD

**Issue by zergu1ar** [go-gorm/gorm#2066]
When we have custom TableName function for model with logic, we have invalid results via Find methods, Create method works correctly

```go
type User struct {
    Role string
} // default table name is `users`

func (u User) TableName() string {
    if u.Role == "admin" {
        return "admin_users"
    } else {
        return "users"
    }
}
...
var users []User
db.Where(User{Role:"admin"}).Find(&users)
```
This queries should find into table "admin_users", but uses "users"

**Comment by danielzheng** [comment]
same issue here...

**Comment by eyasliu** [comment]
the variable u, all fields are default values

**Comment by dan-j** [comment]
Nothing after nearly 2 years?

I've just hit this, it seems that if you provide a struct, it clones the `Scope` which loses the `.Table("custom_table_name")` set on the previous scope.

https://github.com/jinzhu/gorm/blob/master/scope.go#L583-L597

A workaround is to use a `map[string]interface{}` or `string` where statement.
