### ISSUE TITLE
how to split table with gorm?

### ISSUE THREAD

**Issue by seaguest** [go-gorm/gorm#2074]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```
I want split my user table by country.
since I know its country in each request,I know which table to query, is is possible in gorm right now?

if I specify the table name in select/create operation, will it wotk?

```

**Comment by zergu1ar** [comment]
use db.Table("tableName").Find...
