### ISSUE TITLE
update with multi relative columns and their exec order just sort by column name

### ISSUE THREAD

**Issue by goldengoat** [go-gorm/gorm#2075]
update table set col1 = col1 + 1, col2 = col1;

exec sql just like that, mysql use the new value of col1 when to calculate the col2 value, however in the gorm, according to the https://github.com/jinzhu/gorm/pull/1734, the update sql with map in golang, sort by the column name, so the origin order is replaced, it cause problem.

**Comment by seaguest** [comment]
did you try EXPR?

**Comment by goldengoat** [comment]
yes, i tried, but the point is mysql have a exec order with relative columns, but  in the gorm or golang, the map has no order, so the exec result is not the same as raw sql
