### ISSUE TITLE
Postgresql: read connection reset by peer

### ISSUE THREAD

**Issue by richzw** [go-gorm/gorm#2081]
### What version of Go are you using (`go version`)?
1.10.3

### Which database and its version are you using?
postgresql 9.6.3

```go

// db   connection 
	conn = "host=localhost port=5432 dbname=postg sslmode=disable"
	db, err := gorm.Open("postgres", conn)

       	db.DB().SetConnMaxLifetime(time.Minute * 5)
	db.DB().SetMaxIdleConns(5)
	db.DB().SetMaxOpenConns(7)
```

Originally, I did not set the following config 

```
       	db.DB().SetConnMaxLifetime(time.Minute * 5)
	db.DB().SetMaxIdleConns(5)
	db.DB().SetMaxOpenConns(7)
```

Occasionally, the following error comes up `read tcp x.x.x.x:57752->x.x.x.x:5432: read: connection reset by peer` .

I thought it is caused by the closed channel by postgresql server reused by gorm client again, so I add the above connection  pool config. However, the above error comes up again.

Is there anything wrong when I set the connection pool? or anything am I missing?

**Comment by ceo** [comment]
same here

**Comment by weters** [comment]
I am also seeing this issue. I'm using Pg 11.1 and Go 1.11.2.

**Comment by demas** [comment]
I have the same issue:

```
[2019-01-21 16:57:02]  [1.86ms]  SELECT ......
[1 rows affected or returned ]

(/go/src/web-services/datastore/techplace.go:81) 
[2019-01-21 18:20:04]  read tcp 10.81.74.132:51416->10.81.74.68:5432: read: connection reset by peer 

(/go/src/web-services/datastore/techplace.go:81) 
[2019-01-21 18:20:04]  [1.96ms]  SELECT .....  
[0 rows affected or returned ]
```

If I rerun the last query again I'll receive one row. 
It looks as if the connection is broken, but the driver does not return an error, but says that there are no rows.

**Comment by openkengboy** [comment]
I have the same issue

**Comment by zuoRambo** [comment]
vote for the issue

**Comment by efrengarcial** [comment]
+1

**Comment by rafareyes7** [comment]
+1

**Comment by rynslmns** [comment]
+1

**Comment by quangpn88** [comment]
+1

**Comment by yangzj** [comment]
same
