### ISSUE TITLE
When will gorm implement local cache and redis cache? It is a very important feature. Thanks.

### ISSUE THREAD

**Issue by CHCP** [go-gorm/gorm#2083]
When will gorm implement local cache and redis cache? It is a very important feature. Thanks.

**Comment by raghuvanshy** [comment]
This is a feature that would really help me as well. How would one go about doing it though?
Do we maintain a copy of the data in the redis/local cache at all times, while interacting with it via our own sql layer?

Am looking to contribute to gorm, not sure where to start though.

**Comment by jjhesk** [comment]
me too..

**Comment by inliquid** [comment]
Do not mess cache and database layers. It would be really bad decision. There are a lot of other important and high priority issues. Leave GORM without it, please.

**Comment by CHCP** [comment]
@inliquid Why is it a bad decision using cache in GORM, would you like to give some reason? Are there any other ways to improve performance? Thanks.

**Comment by jinzhu** [comment]
there are some plugins that can do the job, GORM won't support it by itself. for example: https://github.com/8treenet/gcache
