### ISSUE TITLE
Support all index types: UNIQUE, FULLTEXT and SPATIAL

### ISSUE THREAD

**Issue by lastzero** [go-gorm/gorm#2087]
### What version of Go are you using (`go version`)?

1.11 linux/amd64

### Which database and its version are you using?

MySQL 8

### Problem

Since `addIndex()` currently uses a bool flag for unique, it is not possible to use other types such as FULLTEXT or SPACIAL (see [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/create-index.html)).

```go
func (scope *Scope) addIndex(unique bool, indexName string, column ...string) {
	if scope.Dialect().HasIndex(scope.TableName(), indexName) {
		return
	}

	var columns []string
	for _, name := range column {
		columns = append(columns, scope.quoteIfPossible(name))
	}

	sqlCreate := "CREATE INDEX"
	if unique {
		sqlCreate = "CREATE UNIQUE INDEX"
	}

	scope.Raw(fmt.Sprintf("%s %v ON %v(%v) %v", sqlCreate, indexName, scope.QuotedTableName(), strings.Join(columns, ", "), scope.whereSQL())).Exec()
}
```

### Possible Solution

A solution (that breaks the API) could be to change the argument from bool to string, so that you can pass whatever index type you want:

```go
func (scope *Scope) addIndex(indexType string, indexName string, column ...string) {
	if scope.Dialect().HasIndex(scope.TableName(), indexName) {
		return
	}

	var columns []string
	for _, name := range column {
		columns = append(columns, scope.quoteIfPossible(name))
	}

	sqlCreate := "CREATE INDEX"
	if indexType != "" {
		sqlCreate = "CREATE " + indexType + " INDEX"
	}

	scope.Raw(fmt.Sprintf("%s %v ON %v(%v) %v", sqlCreate, indexName, scope.QuotedTableName(), strings.Join(columns, ", "), scope.whereSQL())).Exec()
}
```

**Comment by buildscientist** [comment]
👍 for this issue getting resolved. For the time being I am having to rely on raw SQL to implement this during db migration. 

 Instead of modifying addIndex - I would add functionality to the dialect package. For example - @lastzero is requesting MySQL specific field indices and I'm requesting Postgres (in this case a GIN index for jsonb fields) specific indices.
