### ISSUE TITLE
[IMPROVEMENT] the gorm transaction implementation is really urgly

### ISSUE THREAD

**Issue by aceyin** [go-gorm/gorm#2089]
here is the official example:

> func CreateAnimals(db *gorm.DB) err {
        // Note the use of tx as the database handle once you are within a transaction
        tx := db.Begin()
        defer func() {
            if r := recover(); r != nil {
              tx.Rollback()
         }
        }()
        if tx.Error != nil {
                return err
        }
        if err := tx.Create(&Animal{Name: "Giraffe"}).Error; err != nil {
             tx.Rollback()
             return err
         }
        if err := tx.Create(&Animal{Name: "Lion"}).Error; err != nil {
             tx.Rollback()
             return err
        }
        return tx.Commit().Error
}

from the example above we know: for each database operation, we need to check if it is succeed, if not we should rollback the transaction manually.

so there are lot of code like this `if err := tx.Create(xxx).Error; err != nil `. that's really really very bad experience.

if the transaction control can be refactor to the style like bellow, it will be great:

---
func CreateAnimals(){
     err := gorm.Transactional(function (tx *gorm.DB){
         tx.Create(&xxx)
        tx.Update(&yyy)
        tx.Delete(&zzz)
     })
}

the `Transactional` function would like this:

func Transactional(action func(t *gorm.DB)) error {
      var err error
      tx := DB.Begin()
      action(tx)
      if err = tx.Error; err != nil {
          tx.Rollback()
          return err
      }
      if err = tx.Commit().Error; err != nil {
         return err
      }
      return nil
}

But when i write my codes like the example above, i found the transaction can not work properly, i am struggling to find out the reason, but seems it not so easy, the DB, Scope, Tx objects been passed to too many functions and i am very confuse who is who...

Hope you - gorm team - can improve gorm in the coming milestone

**Comment by liorokman** [comment]
You can do something like this with golang's defer:

```go

type Transaction struct {
    once sync.Once
    rollback bool
    tx *gorm.DB
}

func (t *Transaction) Close() {
  once.do(func() { 
     if t.rollback {
        t.tx.Rollback()
     } else {
        t.tx.Commit()
     }
  }
}

func (t *Transaction) Fail() {
    t.rollback = true
}

func NewTransaction(db *gorm.DB) (*gorm.DB, *Transaction) {
   return Transaction{tx: db}
}
```

And with the above you can change the code to this:

```go
func CreateAnimals(){
   conn, tx := NewTransaction(db.Begin())
   defer tx.Close()

   if err := conn.Create(&xxx).Error; err != nil {
      tx.Fail()
   }
      if err := conn.Update(&yyy); err != nil {
      tx.Fail()
   }
   if err := conn.tx.Delete(&zzz); err != nil {
      tx.Fail()
   }
})
}
```

If you want something cleaner, then wait until golang 2.0 is released, with its [improved error handling](https://go.googlesource.com/proposal/+/master/design/go2draft-error-handling-overview.md).

**Comment by aceyin** [comment]
@liorokman  thanks, currently i am doing the same thing a little bit like what you did. here are my codes:

![image](https://user-images.githubusercontent.com/482266/45524010-d94bcd80-b7fe-11e8-819c-c2ebf57c389a.png)

but i think this is just a compromise solution, because there still a lot of unnecessary `if` block - which make the codes doesn't look too good.

and  furthermore, there is no transaction transitive management in GORM, i think if GORM can support this, it would be a great ORM framework.

**Comment by imdatngo** [comment]
For anyone who comes across this, here is my modified version of @vertazzar's solution which handles the panic inside `fn` just in case, to make sure the transaction is rolled back.

```go
type InTransaction func(tx *gorm.DB) error

func Transaction(db *gorm.DB, fn InTransaction) (err error) {
	tx := db.Begin()
	if tx.Error != nil {
		return tx.Error
	}
	defer func() {
		if r := recover(); r != nil {
			switch x := r.(type) {
			case string:
				err = fmt.Errorf(x)
			case error:
				err = x
			default:
				err = fmt.Errorf("Unknown panic: %+v", x)
			}
		}
		if err != nil {
			tx.Rollback()
		} else {
			err = tx.Commit().Error
		}
	}()
	return fn(tx)
}
```

**Comment by imdatngo** [comment]
Update: The transaction block has been added to Gorm via this PR #2767  🎉

**Comment by kunal-epifi** [comment]
@imdatngo Thank you sharing the code. I guess we can do error handling in rollback as well.

```
type InTransaction func(tx *gorm.DB) error

func Transaction(db *gorm.DB, fn InTransaction) (err error) {
	tx := db.Begin()
	if tx.Error != nil {
		return tx.Error
	}
	defer func() {
		if r := recover(); r != nil {
			switch x := r.(type) {
			case string:
				err = fmt.Errorf(x)
			case error:
				err = x
			default:
				err = fmt.Errorf("Unknown panic: %+v", x)
			}
		}
		if err != nil {
			err = tx.Rollback().Error
		} else {
			err = tx.Commit().Error
		}
	}()
	return fn(tx)
}
```

**Comment by imdatngo** [comment]
@kunal-epifi yeh, that should be fine. I just cannot think of any ways that a rollback can be failed :D

**Comment by imdatngo** [comment]
To @kunal-epifi and everyone that using the custom `Transaction` block right here above:

This code block will kick you in the ass at some points, or it did already!? :)
```golang
		if err != nil {
			err = tx.Rollback().Error
		}
```
Because that will **overwrite** the `err` that returned from the `fn()` or from `recover()`, with `DB.Error` from the `Rollback()` func, which is `nil` anyway!

Please use the official `Transaction` function instead: https://github.com/jinzhu/gorm/blob/7180bd0f27d167f18c253c32d548c7de3adc6b0d/main.go#L533
