### ISSUE TITLE
[Question] Is there any way to handle JSON type using gorm mysql dialect?

### ISSUE THREAD

**Issue by kunallanjewar** [go-gorm/gorm#2113]
I'm basically looking to perform some opertaion on JSON data inside mysql, 
listed here https://dev.mysql.com/doc/refman/5.7/en/json.html?ff=nopfpls
Is this supported by gorm or for now do I simply use raw sql query for this.

Thanks!
Kunal

**Comment by weidongyao** [comment]
I also want to solve this problem, maybe gorm is not a good solution for json in short term.

**Comment by huytx0909** [comment]
Did you find an answer for this or do we need to raw query this?

**Comment by kunallanjewar** [comment]
Nope, I ended up not using gorm.

**Comment by zaquestion** [comment]
There's a workaround presented here: https://github.com/jinzhu/gorm/issues/1935
