### ISSUE TITLE
RecordNotFound should not be the part of public API

### ISSUE THREAD

**Issue by gnomeby** [go-gorm/gorm#2116]
RecordNotFound should not be the part of public API because of two reasons: 
* it doesn't work correctly for Raw SQL.
* we can use RowsAffected 

If RecordNotFound is the part of public API then it will mislead developers that are tries to find something similar in a suggestion list of IDE. 

### What version of Go are you using (`go version`)?
1.10.3

### Which database and its version are you using?
PostgreSQL 10

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	init()
	if db.Raw("SELECT 1 AS one WHERE FALSE").RecordNotFound() {
		fmt.Println("success")
	} else {
		fmt.Println("failed")
	}
}
```

**Comment by jinzhu** [comment]
Removed from v2
