### ISSUE TITLE
Key columns are incremented from zero value even if "auto_increment" is set to false

### ISSUE THREAD

**Issue by liorokman** [go-gorm/gorm#2135]
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.10.4 linux/amd64
```

### Which database and its version are you using?

```
$sqlite3 db.sqlite 
SQLite version 3.25.2 2018-09-25 19:08:10
```
### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "db.sqlite")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type ExampleTable struct {
	Key int64 `gorm:"auto_increment:false;primary_key;not null;default:0"`
}

func main() {

	db.AutoMigrate(&ExampleTable{})

	val := ExampleTable{
		Key: 0,
	}
	
	db.Save(&val)

	if val.Key != 0 {
                fmt.Printf("Auto_increment set to false, but key was incremented regardless")
                fmt.Printf("failed.\n")
        }
}
```

**Comment by givanfp** [comment]
I'm having the same issue, did you find a solution?

**Comment by liorokman** [comment]
No solution in gorm.

I restructured my code to have an additional field which I have a unique index on, and I have an extra (ugly) primary key which is basically useless, due to this gorm bug.

**Comment by canselcik** [comment]
I'm having the same issue.

**Comment by jonas0616** [comment]
After observation, if the field tag does not contain `type:` and the field is primary key, gorm add auto_increment automatically. I'm not sure if it is related to this issue.
Therefore, maybe you can manually specify the data type by adding `gorm:"type:bigint"` to workaround this issue.
