### ISSUE TITLE
Why do you write "0 rows affected or returned" when "Count"?

### ISSUE THREAD

**Issue by Azunyan1111** [go-gorm/gorm#2136]
~This sentence was created by Google translate~

Since I want to know the total number of users I wrote while looking at document

http://gorm.io/docs/query.html#Count

I ran the following code
```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	var count int
	db.Model(&User{}).Count(&count)
}

type User struct {
	gorm.Model
	Name string
}
```
Then results like this came back
```sh
[2018-10-16 01:24:44]  [0.98ms]  SELECT count(*) FROM `reports`  WHERE `reports`.`deleted_at` IS NULL  
[0 rows affected or returned ] 
```
Oh my god! can not get the count!
But "Sequel Pro" is outputting results!
WTF.....

Two hours later...
I confirmed that I could get by log.print the variable "count"

Why gorm is written as "[0 rows affected or returned]"?
When "count" is executed in "Sequel Pro", "1 rows affected or returned" is displayed
Database is not detailed but is this display correct?

**Comment by cuiweixie** [comment]
interesting!
