### ISSUE TITLE
BeforeUpdate 和 BeforeDelete 无效，时间依然被 time.Time 覆盖

### ISSUE THREAD

**Issue by mooncool** [go-gorm/gorm#2137]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go v1.11.1

### Which database and its version are you using?
MySQL 5.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
type Group struct {
	//gorm.Model
	ID        int64
	GroupId   int64
	GroupType int64
	Name      string
	Creator   string
	CreatedAt int64
	UpdatedAt *sql.NullInt64
	DeletedAt *sql.NullInt64
}

func (Group) TableName() string {
	return "group"
}

func (group *Group) BeforeCreate(scope *gorm.Scope) error {
	scope.SetColumn("CreatedAt", time.Now().Unix())

	return nil
}

func (group *Group) BeforeUpdate(scope *gorm.Scope) error {
	scope.SetColumn("UpdatedAt", time.Now().Unix())

	return nil
}

func (group *Group) BeforeDelete(scope *gorm.Scope) error {
	scope.SetColumn("DeletedAt", time.Now().Unix())

	return nil
}
```
但是Update和Delete的时候，都是这样的时间：
SET deleted_at='2018-10-17T20:30:53+08:00'

请问，该如何解决？

**Comment by pengshaomin** [comment]
看看源码， sql解析，有问题自己动手了，作者基本不回复的

**Comment by mooncool** [comment]
@pengshaomin 我后来手动用update替代了软删……不用那个callback机制了
