### ISSUE TITLE
Fatal connection to database

### ISSUE THREAD

**Issue by wahyuhadi** [go-gorm/gorm#2139]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.11

### Which database and its version are you using?
MYSQL

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package config

import (
	"log"
	"os"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

var gormConn *gorm.DB

// get connection database
func GetDatabaseConnection() *gorm.DB { // Check Connection Status
	if gormConn != nil && gormConn.DB() != nil && gormConn.DB().Ping() == nil {
		return gormConn
	}
	conn, err := gorm.Open(os.Getenv("DB_DIALECT"), os.Getenv("DB_CONNECTION")) // Connection to database
	if err != nil {
		log.Fatal("Could not connect to the database") // stop connection
	}
	conn.LogMode(true)

	gormConn = conn
	return gormConn
}

........
func GetAll(ctx iris.Context) {

	type User struct {
		ID        int64         `json:"id" gorm:"primary_key"`
		Role      string        `json:"role,omitempty" gorm:"not null; type:ENUM('admin', 'user', 'root')"`
		Email     string        `json:"email" gorm:"not null; size:255"`
		CreatedAt *time.Time    `json:"createdAt,omitempty"`
		UpdatedAt *time.Time    `json:"updatedAt,omitempty"`
		DeletedAt *time.Time    `json:"deletedAt,omitempty" sql:"index"`
		Profile   model.Profile `json:"profile"` // Get from model->Profile
	}

	var (
		users  []User // [] for array result
		result iris.Map
	)
        db := config.GetDatabaseConnection()
	defer db.Close()
	err := db.Find(users).Error // execute query
	if err != nil {
		result = iris.Map{
			"error":  "true",
			"status": iris.StatusBadRequest,
			"result": nil,
		}
	} else {
		result = iris.Map{
			"error":  "false",
			"status": iris.StatusOK,
			"result": users,
			"count":  len(users),
		}
	}

	ctx.JSON(result)
	return
}
```

database fatal connection (Could not connect to the database) when i test with wrk 
'wrk -c500 -t 4 --latency -d 60s http://localhost:3000/v1/user'

error   '2018/10/17 23:29:24 Could not connect to the database'

**Comment by vertazzar** [comment]
first of, GetDatabaseConnection might have race condition, i would advise setting up the db connection in main() as a global variable

second, you obviously did not set your environment variables "DB_DIALECT"  "DB_CONNECTION"

which should look like this

export DB_DIALECT="mysql"
export DB_CONNECTION="user:password@tcp(127.0.0.1)/db?parseTime=true&charset=utf8mb4"
