### ISSUE TITLE
SubQuery SQL Error

### ISSUE THREAD

**Issue by g10guang** [go-gorm/gorm#2152]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

```sh
➜  awesomeProject go version    
go version go1.11.1 darwin/amd64
```

### Which database and its version are you using?

```sh
mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.7.20-0ubuntu0.16.04.1 |
+-------------------------+
```

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Gorm version:

```
* commit 742154be9a26e849f02d296073c077e0a7c23828 (HEAD -> master, origin/master, origin/HEAD)
| Author: Iskander (Alex) Sharipov <iskander.sharipov@intel.com>
| Date:   Sun Oct 7 03:49:37 2018 +0300
|
|     rewrite if-else chain as switch statement (#2121)
|
|     From effective Go: https://golang.org/doc/effective_go.html#switch
|
|     > It's therefore possible—and idiomatic—to write an if-else-if-else chain as a switch.
|
|  association.go | 7 ++++---
|  1 file changed, 4 insertions(+), 3 deletions(-)
|
```

My code:

```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"time"
)

type User struct {
	gorm.Model
	Name string `gorm:"default:'g10guang'"`
	Age  int    `gorm:"default:100"`
}

func main() {
	url := fmt.Sprintf("%v:%v@(%v:%v)/%v?charset=utf8&parseTime=True&loc=Local",
		"username", "password", "127.0.0.1", "3306", "goweb")
	db, err := gorm.Open("mysql", url)
	if err != nil || db == nil {
		fmt.Println(err)
	}
	db.SingularTable(true)

	db.AutoMigrate(&User{})

	users := make([]*User, 0)

	fmt.Println(db.Where("age < ?", db.Table("user").Select("AVG(age)").QueryExpr()).Find(&users).QueryExpr())

}
```

output:

```
➜  awesomeProject go run main.go
&{SELECT * FROM `user`  WHERE `user`.`deleted_at` IS NULL AND ((age < SELECT AVG(age) FROM `user`  )) []}
```

I try it in mysql console. SQL Error happens.

I think the correct SQL is:

```sql
SELECT * FROM `user`  WHERE `user`.`deleted_at` IS NULL AND (age < (SELECT AVG(age) FROM `user` ))
```

Thanks.

**Comment by markelog** [comment]
On the docs site - http://gorm.io/docs/query.html#SubQuery
Result is also would be incorrect - 
```sql
SELECT * FROM "branches"  WHERE "branches"."deleted_at" IS NULL AND ((amount > SELECT AVG(amount) FROM "orders"  WHERE (state = 'paid')))
```

:/

**Comment by gq-tang** [comment]
I have the same problem

**Comment by penguinpowernz** [comment]
@gq-tang also with mysql?

**Comment by gq-tang** [comment]
> @gq-tang also with mysql?

yes

**Comment by randallmlough** [comment]
@gq-tang, @penguinpowernz: 
I have sub queries working using this method... 
```
var somevalue = 1
row := db.Select("something").Table("first_table").Where("exists(?)", db.Select("a_relationship_to_something").Model(&SecondTable{}).Where("id = ?", somevalue).QueryExpr()).Row()
	row.Scan(&id)
```
I've tested this with `row()`, `rows()`, `first()`, and `find()`. You can also use both `.Table()` and `.Model()` interchangeably as shown in the example. 

May be worth updating the docs to this method if worthy

**Comment by renevall** [comment]
@g10guang can you try with Subquery() instead of QueryExpr()

**Comment by g10guang** [comment]
> @g10guang can you try with Subquery() instead of QueryExpr()

I quit my job. So I cannot replay this bug.

**Comment by hobbsgoblin** [comment]
> @g10guang can you try with Subquery() instead of QueryExpr()

Thanks, this worked for me. [Query/SubAuery docs](http://gorm.io/docs/query.html#SubQuery) should be updated as the given example does not work and SubQuery() is not mentioned anywhere outside godoc.

**Comment by codus-me** [comment]
**docs**
code:

> db.Where("amount > ?", DB.Table("orders").Select("AVG(amount)").Where("state = ?", "paid").QueryExpr()).Find(&orders)

expected:

> SELECT * FROM "orders"  WHERE "orders"."deleted_at" IS NULL AND (amount > (SELECT AVG(amount) FROM "orders"  WHERE (state = 'paid')));

got: (not work)

> &{SELECT * FROM `user`  WHERE `user`.`deleted_at` IS NULL AND ((age < SELECT AVG(age) FROM `user`  )) []}

**PART II**
code:

> db.Where("amount > (?)", DB.Table("orders").Select("AVG(amount)").Where("state = ?", "paid").QueryExpr()).Find(&orders)

got: (work)

> SELECT * FROM `user`  WHERE `user`.`deleted_at` IS NULL AND ((age < (SELECT AVG(age) FROM `user`  )))
