### ISSUE TITLE
Soft delete causes postgres errors

### ISSUE THREAD

**Issue by abramovic** [go-gorm/gorm#216]
Getting this error whenever we try to update the model: 
(pq: invalid input syntax for type timestamp with time zone: "-0001-12-31T16:07:02-07:52:58") 

No errors when I remove DeletedAt

**Comment by boonep** [comment]
Any update on this, experiencing the same postgresql issue with a "0001-12-31 16:07:02-07:52:58 BC" date instead of null.  Thanks!

**Comment by jinzhu** [comment]
@boonep you should use `*time.Time` if possible to have zero value.

**Comment by boonep** [comment]
@jinzhu Perfect.  Thanks so much!
