### ISSUE TITLE
how to disable default(ID) primary key?

### ISSUE THREAD

**Issue by PearceDuan** [go-gorm/gorm#2165]
### What version of Go are you using (`go version`)?
`go version go1.11 linux/amd64`

### Which database and its version are you using?
`mysql-5.7.23`

as title, in fact, no need any primary key in my table

**Comment by baocaixiong** [comment]
define youself `BaseModel`
```go
type MyModel struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time `sql:"index"`
}

type logicModel struct {
    MyModel
}
```
