### ISSUE TITLE
GORM Oracle Query Results Scanning issue

### ISSUE THREAD

**Issue by ssilvan** [go-gorm/gorm#2169]
### What version of Go are you using (`go version`)?
go version go1.11 linux/386

### Which database and its version are you using?
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

### We created our Oracle dialect called "goracle"
[goracle.zip](https://github.com/jinzhu/gorm/files/2558301/goracle.zip)

package main

import (
    "fmt"
    "github.com/jinzhu/gorm"
    _ "github.com/jinzhu/gorm/dialects/goracle"
)

type Product struct {
  gorm.Model
  Code string
  Price uint
}

//Simple program to test GORM on Oracle DB
func main() {
  fmt.Println("opening connection to oracle...")
  db, err := gorm.Open("goracle", "user/xxxxx@xxxxx.xxxx.xxxxx.com:1111/dbname AS SYSDBA")
  if err != nil {
    fmt.Println(err)
    panic("failed to connect database")
  }
  fmt.Println("Connection opened...")
  db.LogMode(true)
  defer db.Close()

  var products Product

  rows, err := db.Model(&Product{}).Find(&products).Rows() 
  defer rows.Close()

  for rows.Next() {
    var (
      id   int
      created_at string
      deleted_at  string
      updated_at string
      code string
      price  int
    )
    if err := rows.Scan(&id,&created_at,&deleted_at,&updated_at,&code, &price); err != nil {
      panic(err)
    }
    fmt.Printf("Scan to variables: %d create :%s delete %s update %s code %s  price %d\n", id,created_at , deleted_at,updated_at,code, price)

    db.ScanRows(rows, &products)
    fmt.Printf("Scan to structure: %+v\n", products)
  }

### Output
[2018-11-07 08:16:36]  [29.99ms]  SELECT * FROM products  WHERE products.deleted_at IS NULL  
[4 rows affected or returned ] 
Entering LimitAndOffsetSQL function...
LimitAndOffsetSQL: 

[2018-11-07 08:16:36]  [14.14ms]  SELECT * FROM products  WHERE products.deleted_at IS NULL  
[0 rows affected or returned ] 
Scan to variables: 1 create :2018-11-05T11:59:52-08:00 delete 2018-11-05T11:59:52-08:00 update 0001-01-01T00:00:00Z code Product 1  price 5900
Scan to structure: {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:<nil>} Code: Price:0}
Scan to variables: 2 create :2018-11-05T11:59:52-08:00 delete 2018-11-05T11:59:52-08:00 update 0001-01-01T00:00:00Z code Product 2  price 2100
Scan to structure: {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:<nil>} Code: Price:0}
Scan to variables: 3 create :2018-11-05T11:59:52-08:00 delete 2018-11-05T11:59:52-08:00 update 0001-01-01T00:00:00Z code Product 3  price 2650
Scan to structure: {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:<nil>} Code: Price:0}
Scan to variables: 5 create :2018-11-05T11:59:52-08:00 delete 2018-11-05T11:59:52-08:00 update 0001-01-01T00:00:00Z code Product 5  price 4230
Scan to structure: {Model:{ID:0 CreatedAt:0001-01-01 00:00:00 +0000 UTC UpdatedAt:0001-01-01 00:00:00 +0000 UTC DeletedAt:<nil>} Code: Price:0}

### Summary
As you can see from the above result, if we scan the results directly to our variables they are populated correctly, but if instead we use the Products structure it retrieves an empty structure instead. The same is true for all the methods of querying the DB.

**Comment by ponomarenko-v** [comment]
Hi @ssilvan!  Your solution helped me a lot to work with Oracle. I hope for a quick fix issue with the structures. It will be great to make your solution work as well.
@jinzhu I hope that you will add this dialect to the master branch, after the correction. It is very useful.

**Comment by ssilvan** [comment]
Hi @ponomarenko-v ,
In order to get the structures populated correctly, you can use the the file I am attaching here.

The issue was found on line 498 of the jinzhu/gorm/scope.go file
Replace this file with the attached one, using the goracle.go dialect plus this fix all the interactions with your Oracle Database should work fine now.

Hope this helps you! Let me know how it goes.

Thanks,
Sergio
[scope.zip](https://github.com/jinzhu/gorm/files/3005662/scope.zip)
