### ISSUE TITLE
How gorm can set a custom column name in field tag which containing '.'

### ISSUE THREAD

**Issue by KiraSi** [go-gorm/gorm#2172]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

go1.10
### Which database and its version are you using?

psql (9.5.14, server 9.6.10)
### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
I want to customize the column name as fellow
```
type HistoryTest struct {
	ID    string 
	CustomProperty float64 `gorm:"column:'hcho.place.value'"`
	CreatedAt      time.Time
}
```
However when I execute the Create() method, the column name "hcho.place.value" is convert as "hcho"."place"."value". I want the column name as "'hcho.place.value".

**Comment by Cinojose** [comment]
I am having the same problem. How did you fixed this ?
