### ISSUE TITLE
锁表存在问题， Exec(lock tables) 类操作，

### ISSUE THREAD

**Issue by af913337456** [go-gorm/gorm#2189]
如下，事务后直接锁表，锁表处语句直接阻塞死。

T.tx = T.mysql.Db.Begin()
	err = T.tx.Error
	if err != nil {
		return fmt.Errorf("启动事务失败 %s",err.Error())
	}
	err = T.mysql.Db.Exec("" +
		" lock tables " +
		" movesay_trade write," +
		" movesay_user_coin write," +
		" movesay_finance write").Error
T.tx.Raw(select..被锁的表..)  ----------- 这里卡死

**Comment by af913337456** [comment]
@jinzhu  希望解决这类问题

**Comment by hyacinthus** [comment]
你锁表也要用tx锁啊。。这tx和db是两个client，肯定卡死啊。

**Comment by GFZRZK** [comment]
hello，请问一下这个问题解决了吗？同样遇到一个使用tx进行锁表的时候就阻塞住的问题。。
