### ISSUE TITLE
Is it possible to allow update NULL value to foreign key? 

### ISSUE THREAD

**Issue by Scott-Chen** [go-gorm/gorm#2202]
It was work before this. #1988 

What version of Go are you using (go version)?
1.11.1

Which database and its version are you using?
MySQL 5.6

```
type A Struct  {
    ID     int64      `gorm:"primary_key;AUTO_INCREMENT;not null"`
    BID *int64     `sql:"DEFAULT:NULL"`
    B .   B              `gorm:"save_associations:false;association_save_reference:false"`
}
type B Struct {
    ID        int64       `gorm:"primary_key;AUTO_INCREMENT;not null"`
    Name string
}
```

```
var a A
if err := db.First(&a, "id = ?", 1).Error; err != nil {
    return
}
a.BID = nil
if err := db.Save(&a).Error; err != nil {
    return
}
```

**Comment by penguinpowernz** [comment]
So do you mean to say that you could set BID to null before? And now it does not work @Scott-Chen ?

**Comment by Scott-Chen** [comment]
@penguinpowernz  Yes, that's right.

**Comment by a2htray** [comment]
I got this problem, in some cases, the foreign key field may be null

**Comment by a2htray** [comment]
After testing, I want a simple solution to resolve this. Just use `Updates` method to update the specific column. 

It works.

**Comment by ThatsAMorais** [comment]
If I understand the issue being described by OP, it may be the same one to which I am trying to find a workaround...

A model has a foreign key relationship to another model, where model A has *B and BID string columns. They are null initially and this is fine. However, once the value has been assigned, it cannot be cleared.

I have tried 
 * `Updates(&A)`
 * `Updates(map[string]interface{}{"b":nil}`
 * Selecting the specific field with `Select`
 * `UpdateColumns`
 * `Models(original).Save(copiedThenUpdated)`

When trying to set the BID field to "" or nil I see `pq: invalid input syntax for type uuid: ""` and if I attempt to only overwrite *B the change is ignored.

The ONLY way to perform the update is through raw SQL
