### ISSUE TITLE
how to set time.Time default loc and format after query

### ISSUE THREAD

**Issue by heweixi** [go-gorm/gorm#2211]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.10.3 windows/amd64

### Which database and its version are you using?
'10.1.18-MariaDB'

### Which version of gorm using
v1.9.1

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

when want get gorm query time.Time format as "2018-12-07T10:02:25Z" by default is "2018-12-07T18:02:25+08:00"
how can set time loc and format after query before return

**Comment by sha2nkprasad** [comment]
We are also facing the same issue with Aurora DB.

**Comment by heweixi** [comment]
> We are also facing the same issue with Aurora DB.
can try by this: https://github.com/jinzhu/gorm.io/issues/99
