### ISSUE TITLE
FirstOrCreate: How to check if it's first or new?

### ISSUE THREAD

**Issue by 0xbkt** [go-gorm/gorm#2229]
### What version of Go are you using (`go version`)?
go version go1.11.2 linux/amd64

### Which database and its version are you using?
PostgreSQL 9.6.10

---

I don't like running two queries explicitly and I would prefer using `FirstOrCreate` to check if the data was created before or is being created now. However I don't see such an option in Gorm and wonder if there is a workaround.

**Comment by 0xbkt** [comment]
Applied a quick fix for now here where `Attrs` method helps me merge the given struct with my own `user` variable if the record is not found. Besides `Attrs`, `Assign` can also be used to merge in all cases, regardless it exists or not.

```golang
db.Attrs(User{BeingCreatedNow: true}).FirstOrCreate(&user, &user)
```

**Comment by amaurybrisou** [comment]
`func (user *User) AfterCreate(scope *gorm.Scope) error {
	scope.SetColumn("New", true)
	return nil
}

I prefer using hooks`

**Comment by penguinpowernz** [comment]
Are we happy with this workaround?

**Comment by 0xbkt** [comment]
@penguinpowernz I'm not. I wish there was a method or property to show it explicitly.

**Comment by cuiyuan** [comment]
this problem should be solved explicitly
