### ISSUE TITLE
moul.io/zapgorm: go.uber.org/zap logger driver for gorm

### ISSUE THREAD

**Issue by moul** [go-gorm/gorm#2230]
Hi @jinzhu,

I made a small utility that allows to quickly link `gorm` with the [zap](https://go.uber.org/zap) logger:

    https://github.com/moul/zapgorm

Do you think I should open a pull request somewhere on your repo: in documentation or somewhere else?

**Comment by moul** [comment]
FYI, I've also made a [zapgorm2](https://github.com/moul/zapgorm2) version for gorm v2 :)

**Comment by jinzhu** [comment]
Hello @moul 

Yes, let's add to https://gorm.io/community.html 

Thank you.
