### ISSUE TITLE
How to pass transaction to functions

### ISSUE THREAD

**Issue by LingboAdmin** [go-gorm/gorm#2231]
### What version of Go are you using (`go version`)?
1.11.2

### Which database and its version are you using?
Mysql 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
My problem is how to pass transaction as a parameter to other functions and once there is an error in any function, rollback all operations.

I try the following way

```go
func main() error {
       tx = db.Begin()
     	if tx.Error != nil {
		return tx.Error
	}
       	if err := funcA(someParam, tx); err != nil {
		tx.Rollback()
		return err
	}
       	if err := funcB(someParam, tx); err != nil {
		tx.Rollback()
		return err
	}

       return tx.Commit().Error
}

func funcA(x someParam, tx *gorm.DB) error {
       (some code)
       return tx.Create(obj).Error
}

func funcB(x someParam, tx *gorm.DB) error {
       (some code)
       return tx.Create(obj).Error
}
```
But sadly I ended up with a weird memory error in runtime. What is the proper way to pass tx as a parameter ? Since `funcA` and `funcB` may be used for mulitple times, I wish to keep the code concise. Thanks for your help.

**Comment by hclcsx** [comment]
Hello, I have encountered the same problem.Have you solve this and how?

**Comment by noragem** [comment]
I have the same problem here. It seems when pass transaction to functions will conflict with Update function. It's always updated `updated_at ` field, not update changed fields

**Comment by joint-song** [comment]
I think you can wrap once yourself like this below:
```go
func main() error {
        err := inTransaction(func(tx *gorm.DB) error ) {
            if err := funcA(x, tx); err != nil {
                return err
            }
             return funcB(x, tx)
        }
        // resolve error
}

func funcA(x someParam, tx *gorm.DB) error {
       (some code)
       return tx.Create(obj).Error
}

func funcB(x someParam, tx *gorm.DB) error {
       (some code)
       return tx.Create(obj).Error
}

func inTransaction(f func(tx *gorm.DB) error) error {
    tx := db.Begin()
    err := f(tx)
    if err != nil {
        tx.Rollback()
        return err
    }
    return tx.Commit()
}
```

**Comment by pengdafu** [comment]
I don't know if there is such an implementation:
```go
db.WithContext(ctx).Transaction(func (tx *sql.Tx) {
  tx.Create(...)
  otherFunc(ctx)
})

func otherFunc(ctx context.Context) {
  db.WithContext(ctx).Transaction(func (tx *sql.Tx) {
    tx.Create(...)
  })
}
```

`tx` of the two functions are equal
