### ISSUE TITLE
look me

### ISSUE THREAD

**Issue by airplayx** [go-gorm/gorm#2235]
query := DB.Table(TP+"total").Select(TP+"total.id,sum(day_price) as total_price").
		Joins("left join "+TP+"store as store on store.id = "+TP+"total.store_id").
		Joins("left join "+TP+"channel as cha on cha.id = "+TP+"total.channel_id").
		Where(TP+"total.day_time between ? and ?", TimeStart, TimeEnd).
		Having("total_price>0").
		Group(TP + "total.store_id," + TP + "total.is_valid," + TP + "total.day_time,cha.id").
		Count(&info)
	if query.Error != nil && query.Error != gorm.ErrRecordNotFound {
		log.Error(query.Error)
	}

// SELECT count(*) FROM ( SELECT count(*) as name  FROM `pro_total` left join pro_store as store on store.id = pro_total.store_id left join pro_channel as cha on cha.id = pro_total.channel_id WHERE  (pro_total.day_time between '1545235200' and '1545753600') GROUP BY pro_total.store_id,pro_total.is_valid,pro_total.day_time,cha.id ) AS count_table HAVING (total_price>0)

tell me why?

**Comment by penguinpowernz** [comment]
Tell you went what @bingoladen? Please add more detail or issue will be closed.

**Comment by bingoladen** [comment]
'count'and'having' appear in the wrong place...

SELECT count(_) FROM ( SELECT count(_) as name FROM `pro_total` left join pro_store as store on store.id = pro_total.store_id left join pro_channel as cha on cha.id = pro_total.channel_id WHERE (pro_total.day_time between '1545235200' and '1545753600') GROUP BY pro_total.store_id,pro_total.is_valid,pro_total.day_time,cha.id ) AS count_table **HAVING** (total_price>0)

**Comment by penguinpowernz** [comment]
Please provide what SQL you expect to see. Please edit your comments to use the code wrapper formatting.

**Comment by stevenkitter** [comment]
the between and seems to be a bug to gorm
