### ISSUE TITLE
the raw method does not work when the field in SQL statement is uppercase

### ISSUE THREAD

**Issue by greymanking** [go-gorm/gorm#2237]
### Which database and its version are you using?
SQLite 3

```go

package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var dbg gorm.DB

func init() {
	db, err := gorm.Open("sqlite3", "./data.sqlite3")
	if err != nil {
		panic("failed to connect database, reason:" + err.Error())
	}
	dbg = *db
}

func QueryTitleIDMax() uint {

	type Max struct{ M uint }
	var max Max

	if e := dbg.Raw("SELECT MAX(id) as M FROM records").Scan(&max).Error; e != nil {
		fmt.Println(e)
	}

	return max.M
}

func main() {
	fmt.Println("query result", QueryTitleIDMax())
}
```

the function QueryTitleIDMax always returns 0.

the case is that if u replace "as M" with "as m", it works correctly. I use the mattn go-sqlite3 library to do the same job and it works every time no matter "as M" or "as m". It cost me a whole day to debug this and made me quite confused. I think u may fix it if there is nothing difficult to deal with.
Thanks.

**Comment by liepumartins** [comment]
I can confirm, this happens also with `jinzhu/gorm/dialects/mssql`
