### ISSUE TITLE
更新后Create_Time也更新了

### ISSUE THREAD

**Issue by chunshand** [go-gorm/gorm#2241]
执行更新 我更新了 Update_Time 字段 但是 Create_Time也更新了
```
	AssistantLogerr := DB.Debug().Model(&Model.AssistantLog{}).Where(&Model.AssistantLog{
		AssistantID:    req.Token,
		UserHomeWorkID: req.UserHomeWorkID,
	}).Updates(&Model.AssistantLog{
		State:       AssistantLogState,
		Update_Time: time.Now(),
	}).Error
```

打印出来的sql语句是
···
UPDATE `assistant_logs` SET `state` = '1', `update_time` = '2019-01-02 15:04:56'  WHERE (`assistant_logs`.`user_home_work_id` = '348c258e-95bf-4fa7-660b-a25f1d8b79ad') AND (`assistant_logs`.`assistant_id` = 'userToken')  
[1 rows affected or returned ] 
···

**Comment by baocaixiong** [comment]
检查你的Create_Time字段是否带了 `ON UPDATE CURRENT_TIMESTAMP` 操作

**Comment by airplayx** [comment]
最新的版本v1.9.12 修正了这个问题
