### ISSUE TITLE
gorm怎么添加外键

### ISSUE THREAD

**Issue by lbtsm** [go-gorm/gorm#2243]
我想请问下，我想创建一个外键，最终在SQL中展示出：

`CONSTRAINT `constraintName` FOREIGN KEY (`orgID`) REFERENCES `organization` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION`

使用ForeignKey ; AssociationForeignKey是无效的，ForeignKey ; AssociationForeignKey在文旦中创建外键和关联外键的。是我理解有误吗？

结构体以及tag如下：
```
type RightsUser struct {
     OrgID                  int                     `gorm:"index:Rights_Users_FK1_idx"`
     Organization       Organization     `gorm:"ForeignKey:id;AssociationForeignKey:orgID"`
}
```
```
type Organization struct {
     ID int `gorm:"column:id;primary_key;auto_increment"`
}
```
请各路大神，帮忙解答下

**Comment by zhaoWork** [comment]
目前我了解到的，可以使用
db.Model(&module.AdRightsUser{}).AddForeignKey()函数来添加外键
但是有没有方法，使用tag的形式，来添加外键呢？

**Comment by linuxMengfan** [comment]
你好 我也碰到了 这个问题 请问你最后是怎么解决的？ @zhaoWork

**Comment by zhaoWork** [comment]
请看我的第二个回答

**Comment by zhaoWork** [comment]
@linuxMengfan

**Comment by danix9009** [comment]
请问现在是怎么解决的，我按官网的方式添加tag也是添加不了

**Comment by TaceyWong** [comment]
文档中没提这回事，总以为自己写错了。。。。希望文档能说一句

**Comment by TaceyWong** [comment]
> 请问现在是怎么解决的，我按官网的方式添加tag也是添加不了

我认为使用tag的话gorm还不支持，官网说的那个只是在代码中查询时产生的逻辑关系，但是建表时没什么卵用~~~~
