### ISSUE TITLE
.First().Order().Related() uses wrong order-clause

### ISSUE THREAD

**Issue by crazywako** [go-gorm/gorm#2246]
### What version of Go are you using (`go version`)?
GO 1.11

### Which database and its version are you using?
MariaDB 10.3.

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
type JournalEntry struct {
	ID                uint64             `json:"id"`
	Lines             []JournalEntryLine `json:"journalEntryLines,omitempty" gorm:"ForeignKey:JournalEntryId"`
}
type JournalEntryLine struct {
	ID                 uint64    `json:"id"`
	JournalEntryId     uint64    `json:"entryId" gorm:"not null"`
	Order              int       `json:"order"`
}
var je JournalEntry
id := 9167

db.First(&je, id).Order("order").Related(&je.Lines)



// Also this produces the same error
db.First(&je,id).Related(&je.Lines)
```

[2019-01-04 09:51:23]  Error 1054: Unknown column 'journal_entries.id' in 'order clause'
SELECT * FROM `journal_entry_lines`  WHERE (`journal_entry_lines`.`id` = 9167) AND (`journal_entry_id` = '9167') ORDER BY `journal_entries`.`id` ASC,`order`,`journal_entry_lines`.`id` ASC LIMIT 1

Following appears on ORDER-clause `journal_entries`.`id` ASC which it didn't do before Jan 2 2019 commits.

**Comment by randomjunk** [comment]
This issue is caused by this commit: https://github.com/jinzhu/gorm/pull/2179
