### ISSUE TITLE
can't preload field

### ISSUE THREAD

**Issue by jpincas** [go-gorm/gorm#2259]
I've just started getting this error for multiple entities, but I'm having a nightmare pinning down how to fix it.

Last night, it happened after I added a 'has many' relationship to an existing entity.  After 2 hours, I was able to solve it simply by reordering the order in which migrations were specified with db.Automigrate()`, but I'll admit theres a chance that's was an illusory fix.

Everything was fine until I just added another `has many` relationship to another entity and I'm getting the message again, but no amount of moving migrations around will fix it.

In both cases, the entity I added the `has many` relation to is NOT the one mentioned in the error message. (E.g. I added `Orders[]` to `Customer`, and the message I got was `can't preload field Item for core.PurchaseOrderLine`) - seemingly unrelated.

I should stress that it is DEFINITELY the addition of the `has many` field that causes the error - if I remove it, the error stops.

Any suggestions highly appreciated.

**Comment by inliquid** [comment]
It's not "anonymous" it's "embedded". You embed `LineCommon` into `Line` structure. Same behavior with GORM will be achieved by using `gorm:"embedded"` struct tag. 

Just use this instead:
```
type Line struct {
  LineCommon LineCommon
}
```
in this case you are not embedding `LineCommon` struct. This is expected, idiomatic, and expected result with both Go and GORM.

**Comment by jpincas** [comment]
Using a named struct field wouldn't give me the functionality I want - I'll use the `gorm:"embedded"` tag.  Thanks.

**Comment by jpincas** [comment]
```
type Line struct {
  LineCommon gorm:"embedded"
}
```
didn't work for me.  I'm back to unnesting the fields.

**Comment by inliquid** [comment]
Of course it didn't work, it's same as embedding. Read carefully.

**Comment by jpincas** [comment]
I did read carefully.  I'm not sure what advice you are giving me.  I can't use a named field struct as I need to be able to access `LineCommon`'s methods.  I can't find any documentation for `gorm:embedded`so I'm not sure what it does or where to use it.

**Comment by inliquid** [comment]
The point was to explain you what is happening and how it works. This struct tag not documented, but it's easy to find in the code: https://github.com/jinzhu/gorm/blob/0fd395ab37aefd2d50854f0556a4311dccc6f45a/embedded_struct_test.go#L24

**Comment by jpincas** [comment]
OK - lets try to simplify, as I think we are not understanding each other.  Look at my second comment (`Line/LineCommon`).  I have about 20 types, all structured like this - with the `gorm.Model` and other related fields embedded.  Up until a few days ago, no problems at all.  So from that, I undestand that it should 'just work', because, well, it does.

A few days ago, I added a `has many` relationship to one of those types, and I started getting preload errors ON ANOTHER type.  I solved it by shifting around the order of the migrations.  A few days later, some thing.  The only way I've managed to completely solve it is by `de-embedding` (like the 3rd example in my comment).

I'm just trying to alert that there might be a subtle bug here, although I can completely understand that I haven't provided nearly enough information to track it down.

**Comment by Bipus** [comment]
```
type Line struct {
  LineCommon []LineCommon `gorm:"ForeignKey:ItemID"`
}

type LineCommon struct {
  gorm.Model
  ItemID uint
  Item Item
}
```

**Comment by rmsubekti** [comment]
i have same issue when trying to preload Company field on User Struct
```
type User struct {
  gorm.Model
  Name       string
  CompanyID  uint
  Company    Company `gorm:"PRELOAD:true"` // preloaded <---------
  Role       Role                           // preloaded                        
}

db.Set("gorm:auto_preload", true).Find(&users)                     <----------
```
i got this message:
**can't preload field Company for models.User**
the Company struct was

```
type Company struct {
  gorm.Model
  Name       string
  Users       []User `gorm:"ForeignKey:CompanyID"`
}
```

is there any solution for this?

**Comment by Hao-Wu** [comment]
> 

@jpincas I am confronted with the exactly same trouble, do you find a solution? or else I have to DeNest the model struct, which I am trying to avoid.
