### ISSUE TITLE
why Omit is not used in select.

### ISSUE THREAD

**Issue by cyyever** [go-gorm/gorm#2262]
I want to exclude some columns when selecting.

**Comment by lincanli** [comment]
+1 here, really needed

**Comment by Tang8330** [comment]
@jinzhu ^^

**Comment by jinzhu** [comment]
Should be possible, let me implement it in v2.

**Comment by Tang8330** [comment]
That's awesome. Thanks so much and thanks for providing a super useful lib :)

**Comment by ibamibrhm** [comment]
@jinzhu any update about this feature? Does it already implemented or soon in v2?

**Comment by m430** [comment]
+1, I hope the Omit can use in select, please.
