### ISSUE TITLE
Can I select which schema to connect?

### ISSUE THREAD

**Issue by zhb1207** [go-gorm/gorm#2267]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.11.4 linux/amd64

### Which database and its version are you using?
Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64) 
	Nov 30 2018 12:57:58 
	Copyright (C) 2017 Microsoft Corporation
	Express Edition (64-bit) on Linux (Ubuntu 16.04.3 LTS)                                                                                 

After the mssql is successfully connected, I use 
` var user User
db.Table("TestSchema.User").Find(&user)
fmt.Println(user)`

The "TestSchema" is not the default schema(which is dbo), and I got no result although there are some rows in the User table. So, my question is that: Can the GORM switch between the different schema? Or did I use it in a wrong way?

**Comment by tsiutsiu** [comment]
@zhb1207 Same issue here with mssql! Have you found any solution to it?

Cheers
