### ISSUE TITLE
Preloading should only query unique values

### ISSUE THREAD

**Issue by tobias-kuendig** [go-gorm/gorm#2271]
I've got a `TimeEntry` entity. Each `TimeEntry` belongs to a `Person`.

If I use the following code to query the table:

```go
s.db.Preload("Person").Order("start DESC").Find(&result);
```

The following query is generated:

```sql
SELECT * FROM "people"  WHERE ("id" IN ('3','3','2','1','1','1','1','1','2','2','1','3','3','3','3','1','3','3','2','2','2','3','1','3','2','3','1','2','3','3','2','1','3','3','3','3','1','3','3','3','1','3','3','3','1','3'));
```

GORM should only include unique values when preloading relationships.

**Comment by foresx** [comment]
Hi, do you find a way to solve this problem?

**Comment by tobias-kuendig** [comment]
I did not!

**Comment by foresx** [comment]
Thank you.

**Comment by foresx** [comment]
@jinzhu 老哥，这个到底是我们写法出问题了还是说是框架本身没处理，能给个准确的回复么？打扰你了
