### ISSUE TITLE
Update Issue: association's fields are all updated.

### ISSUE THREAD

**Issue by wjh000123** [go-gorm/gorm#2275]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
`go1.11.2 darwin/amd64`

### Which database and its version are you using?
`mysql@5.7`

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"time"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

// User ...
type User struct {
	ID        uint       `gorm:"primary_key" json:"id,omitempty"`
	CreatedAt *time.Time `json:"-"`
	UpdatedAt *time.Time `json:"-"`
	DeletedAt *time.Time `sql:"index" json:"-"`

	Tags []*Tag

	Name   string
	Phone  string
	Gender int64
}

// Tag ...
type Tag struct {
	ID        uint       `gorm:"primary_key" json:"id,omitempty"`
	CreatedAt *time.Time `json:"-"`
	UpdatedAt *time.Time `json:"-"`
	DeletedAt *time.Time `sql:"index" json:"-"`

	UserID uint
	Key    string
	Value  string
}

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)

	db.AutoMigrate(&User{}, &Tag{})
}

func main() {

	user := User{
		Name:   "name",
		Phone:  "123123123",
		Gender: 1,
		Tags: []*Tag{
			&Tag{
				Key:   "A",
				Value: "aaa",
			},
			&Tag{
				Key:   "B",
				Value: "bbb",
			},
		},
	}
	// insert initial data
	db.Save(&user)

	user1 := User{
		ID: 1,
                Name: "another name",
		Tags: []*Tag{
			&Tag{
				ID:  1,
				Key: "A1",
			},
		},
	}
	db.Model(&user1).Update(user1)
}
```

### Expected
1. only `Name` of user(id=1) need be updated to `another name`
2. only `Key` of tag(id=1) need be updated to `A1`

### Actual
1. it's ok.
2. all other fields are updated to zero value.

**Comment by JRascagneres** [comment]
@wjh000123 Don't suppose you found a solution to this? I'm having this issue

**Comment by JRascagneres** [comment]
Looking into whether I can make this change now but its a large codebase to understand. Would be great if @jinzhu could take a look. Looks like a pretty big bug
