### ISSUE TITLE
get all 0 when scan result into []int64 slice

### ISSUE THREAD

**Issue by Tom-Kail** [go-gorm/gorm#2277]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.9.7 darwin/amd64

### Which database and its version are you using?
MySQL 8.0.13

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
        "fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mysql", "root:123456@tcp(ip:3306)/test?charset=utf8mb4")
	if err != nil {
		panic(err)
	}
	//defer db.Close()
}
func ReturnIDZeroDemo(){
	ids := make([]int64, 0)
	err := db.Raw(`select id from users limit 10`).Scan(&ids).Error
	if err != nil {
		fmt.Println("query rows", err, ids)
		return
	} else {
		fmt.Println("ids:", ids)
		return
	}
}
func main() {
	ReturnIDZeroDemo()
}

```

**Comment by ysqi** [comment]
Query single column from a model as a map, if you want to query multiple columns, you should use Scan instead . http://gorm.io/docs/query.html#Pluck

```go


var ages []int64
db.Find(&users).Pluck("age", &ages)

var names []string
db.Model(&User{}).Pluck("name", &names)

db.Table("deleted_users").Pluck("name", &names)

// Requesting more than one column? Do it like this:
db.Select("name, age").Find(&users)

```
