### ISSUE TITLE
RecordNotFound error when Find returns an empty list

### ISSUE THREAD

**Issue by tstranex** [go-gorm/gorm#228]
I just upgraded the latest master branch. It seems that the behaviour of Find has changed when it returns an empty list with mysql.

Example:
var obj_list []Obj
err := gorm.Where("completed=true").Find(&obj_list).Error

If the result is an empty list (len(obj_list) == 0), then err is set to gorm.RecordNotFound. Previously it was nil.

This seems like the wrong behaviour: an empty list is generally not an error; it's often an expected result. Is this new behaviour intentional? I would suggest reverting back to the old behaviour if possible.

**Comment by maple-leaf** [comment]
I dont know, but seems lastest gorm throw error when query result is empty. And message is `record not found`.


The code:

```
import (
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
)
func main() {
    // connecting db and more...
    panicOnErr(db.Find(&user, "id = ?", id).Error)    // OR panicOnErr(db.First(&user, id).Error)
}
func panicOnErr(err error) {
	fmt.Println(err)
	if err != nil {
		panic(err)
	}
}
```

And  debug output:

```
[2017-02-22 12:05:37]  [1.74ms]  SELECT * FROM `users`  WHERE `users`.`deleted_at` IS NULL AND ((id = '8'))
record not found

```

**Comment by jinzhu** [comment]
@maple-leaf Find a slice won't return error, bug find a struct will.

**Comment by maple-leaf** [comment]
@jinzhu I will temporary use slice instead. But hope this can be fixed soon. 😄  Btw, this is a amazing project. 👍
