### ISSUE TITLE
Customize SQL.open for AWS X-Ray?

### ISSUE THREAD

**Issue by dhanson358** [go-gorm/gorm#2288]
AWS X-Ray has some auto-instrumentation features in the Go SDK I'm curious about using in conjunction with Gorm.

Their technique calls for using a custom sql.Open (replaced by xray.SQL), then the rest of the process is the same.  This is their example:

```
func main() {
  db := xray.SQL("postgres", "postgres://user:password@host:port/db")
  row, _ := db.QueryRow("SELECT 1") // Use as normal
}
```

I'm trying to find a pattern what would let me overide this with Gorm.open, but I'm at a loss so far.  Is there some way to inject my open logic around calling sql.Open?

**Comment by eoeac** [comment]
I had the same problem

**Comment by jakubknejzlik** [comment]
Judging from the code it should be possible to use it this way:
```
_db := xray.SQL("postgres", "postgres://user:password@host:port/db")
db, err := gorm.Open(u.Scheme, _db)
```

see: https://github.com/jinzhu/gorm/blob/master/main.go#L78

**Comment by jakubknejzlik** [comment]
Oh, nevermind. It requires QueryRowContext issue, which may be related to long existing issues:
https://github.com/jinzhu/gorm/issues/1807
https://github.com/jinzhu/gorm/issues/1231
