### ISSUE TITLE
db.Table() cannot be used in FirstOrInit()

### ISSUE THREAD

**Issue by alleninshell** [go-gorm/gorm#2293]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.10.5 windows/amd64

### Which database and its version are you using?
MySQL 8.0.11 Community GPL

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

db.Table("user").FirstOrInit(&user, User{Name: "non_existing"})
// (Error 1054: Unknown column 'users.name' in 'where clause')

**Comment by romanitalian** [comment]
#### Hot fix

> implement "TableName"

 
Example:

```golang
type UsersEntity struct {
    gorm.Model
    ID        uint   `gorm:"primary_key"`
    Name      string `gorm:"type:varchar(255)"`
    CreatedAt time.Time
    UpdatedAt time.Time
}

// function "TableName" is called from gorm source:
// 
// github.com/jinzhu/gorm/scope.go 
//    "buildCondition" -> "newScope.QuotedTableName()" -> "TableName() / .tableName"
//
func (UsersEntity) TableName() string {
    return "users"
}
```

**Comment by romanitalian** [comment]
Implement "TableName" function for your struct

**Comment by romanitalian** [comment]
Because You are using "where" and not implement function "TableName" gorm get table name from default way (for where object).

## I found 2 solutions:
Use:
1. or add method "TableName":
```golang
func (UsersEntity) TableName() string {
   return "users"
}
```

2. or **do not use** second parameter: "FirstOrInit(FIRST, SECOND)"
```golang
user := User{Name: "non_existing"}
db.Table("user").FirstOrInit(&user)
```

**Comment by romanitalian** [comment]
I suppose issue is in this peace of source "gorm" code:

github.com/jinzhu/gorm/scope.go

```golang
func (scope *Scope) buildCondition(clause map[string]interface{}, include bool) (str string) {
        ...
	case interface{}:
		var sqls []string
		newScope := scope.New(value)

		if len(newScope.Fields()) == 0 {
			scope.Err(fmt.Errorf("invalid query condition: %v", value))
			return
		}
		scopeQuotedTableName := newScope.QuotedTableName()
        ...
```

Table name is lost in this operation:
```golang
newScope := scope.New(value)
```
