### ISSUE TITLE
Create foreign key constraint between references

### ISSUE THREAD

**Issue by cihangir** [go-gorm/gorm#23]
Starting with your example;

```
type User struct {
        Id                int64     // Id: Primary key
       ................
        Emails            []Email       // Embedded structs
        BillingAddress    Address       // Embedded struct
        BillingAddressId  sql.NullInt64 // Embedded struct's foreign key
        ShippingAddress   Address       // Embedded struct
        ShippingAddressId int64         // Embedded struct's foreign key
        IgnoreMe          int64 `sql:"-"`
}
```

you are not creating foreign key constraints between two tables(User-Address), this is useful for data integrity.

**Comment by metral** [comment]
has a solution to this been discovered? its been almost 1 year

**Comment by codingrogue** [comment]
Not working for me either. I mean the "type:int REFERENCES parentTable(id)" thing.

**Comment by prateek-tolexo** [comment]
Hi, How about providing the ability to define Foreign References in the struct definition. 

Similar to: 
db.Model(&User{}).AddForeignKey("city_id", "cities(id)", "RESTRICT", "RESTRICT")

Therefore, if we want to define the foreign key, we can have it in a function which uses the schema from struct and adds constraints via statements like below before it is imported : 
db.Model(&User{}).AddForeignKey("city_id", "cities(id)", "RESTRICT", "RESTRICT")

**Comment by TheChuckster** [comment]
This is a pretty serious problem, as anyone using an ORM would expect proper abstraction of foreign keys with constraint. Has there been any progress at all since the last update?

**Comment by khatribharat** [comment]
```go
type Address {
 ID string `gorm:"primary_key"`
}

type User struct {
    BillingAddressId string `sql:"type:varchar REFERENCES addresses(id)"`
}
```
Note the use of plural name `addresses` when defining the foreign key constraint. 

works for me with gorm [v1.0](https://github.com/jinzhu/gorm/releases/tag/v1.0) and PostgreSQL `9.6.3`

**Comment by chrisjpalmer** [comment]
Here's a way I found to do it. The process is not automatic and you must call a function manually but its a good solid solution:


```
type User struct {
	gorm.Model
	Username string
	Email string
	Profiles []Profile       `gorm:"many2many:user_profiles;"`
	Groups []Group        `gorm:"many2many:user_groups;"`
}

type Profile struct {
	gorm.Model
	ProfileName string
}

type Group struct {
	gorm.Model
	GroupName string
}

func UserExample1(db *gorm.DB) {
	db.AutoMigrate(&User{})
	db.AutoMigrate(&Group{})
	db.AutoMigrate(&Profile{})

	Many2ManyFIndex(db, &User{}, &Profile{})
	Many2ManyFIndex(db, &User{}, &Group{})
}

func Many2ManyFIndex(db *gorm.DB, parentModel interface{}, childModel interface{}) {
	table1Accessor := ReduceModelToName(parentModel)
	table2Accessor := ReduceModelToName(childModel)

	table1Name := inflection.Plural(table1Accessor)
	table2Name := inflection.Plural(table2Accessor)

	joinTable := fmt.Sprintf("%s_%s", table1Accessor, table2Name)

	db.Table(joinTable).AddForeignKey(table1Accessor+"_id", table1Name+"(id)", "CASCADE", "CASCADE")
	db.Table(joinTable).AddForeignKey(table2Accessor+"_id", table2Name+"(id)", "CASCADE", "CASCADE")
	db.Table(joinTable).AddUniqueIndex(joinTable+"_unique", table1Accessor+"_id", table2Accessor+"_id")
}

func ReduceModelToName(model interface{}) string {
	value := reflect.ValueOf(model)
	if value.Kind() != reflect.Ptr {
		return ""
	}

	elem := value.Elem()
	t := elem.Type()
	rawName := t.Name()
	return gorm.ToDBName(rawName)
}

```

This would set the foreign indexes for the join table and add a unique index to the join table so that duplicate joins are not possible.

**Comment by koenig-dominik** [comment]
A even better solution is to use the built in method "TableName(*db)"

```go
type User struct {
   ID uint `gorm:"primary_key;AUTO_INCREMENT"`
   Referrer *User `gorm:"save_associations:false"`
   ReferrerID uint
}

func Migrate(db *gorm.DB) {
   db.AutoMigrate(&User{})
   userTableName := db.NewScope(&User{}).GetModelStruct().TableName(db)
   db.Model(&User{}).AddForeignKey("referrer_id", userTableName + "(id)", "RESTRICT", "RESTRICT")
}
```

**Comment by roobre** [comment]
@jinzhu @xming 

> why not use ALTER TABLE for the constraints? After all CREATE TABLE.

> For above two structs, they relied each other, and for postgres, you can't create any references if the referred table doesn't exist.

Correct me if I'm wrong, but this problem could be approached from different angles depending on which backend is being used. So, wouldn't be possible to insert references for yet to exist tables on databases which support it (mysql, sqlite?) and fall back to alter table and add the references afterwards for postgres? As long as the user calls `DB.AutoMigrate()` with all their models at once it shouldn't be a problem, I think.
