### ISSUE TITLE
[ASK] what is the best practice to create file helper for Open Database Connection?

### ISSUE THREAD

**Issue by okisetiawan0101** [go-gorm/gorm#2300]
### What version of Go are you using (`go version`)?
1.10.1

### Which database and its version are you using?
mariadb

What is the best practice to create single database file helper for Open Database Connection?
1. Open database connection once using singleton pattern, and never close it for **every HTTP request**?
Or
2. **every HTTP request** always open database connection and close it?

I am so confused

**Comment by albertonaperijr** [comment]
Based on my research while exploring golang, the first one is the best practice.
See this stackoverflow [answer](https://stackoverflow.com/a/30959543/5023394).

**Comment by inliquid** [comment]
@albertonaperijr concerning this answer, unlike `sql.Open`, `gorm.Open` does call `Ping`.
