### ISSUE TITLE
Foreign key constraint fail in recursive table

### ISSUE THREAD

**Issue by MohamedBRH** [go-gorm/gorm#2303]
### What version of Go are you using (`go version`)?
go version go1.11.4

### Which database and its version are you using?
MySQL 5.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
I am trying to add a foreign key in recursive Table and enable onDelete onUpdate CASCADE mode to delete all children when parent is deleted (same with update)
```go
package main

import (
  "github.com/jinzhu/gorm"
  _ "github.com/jinzhu/gorm/dialects/mysql"
)

type User struct {
  gorm.Model
  Name string 
  Child   *User `gorm:"Foreignkey:Parent"` 
  Parent uint
}
  
func main() {
  db, err := gorm.Open("mysql", "root@/testdb")
  if err != nil {
    panic("failed to connect database")
  }
  defer db.Close()
 
  // Migrate the schema
  db.AutoMigrate(&User{})
  db.Model(&User{}).AddForeignKey("parent","users(id)","CASCADE","CASCADE")

  // Create
  u := User{Name: "Parent", Child: &User{Name:"Child"}}  
  db.Save(&u)
  
}
```

![capture](https://user-images.githubusercontent.com/26926657/53236876-a3f0b900-3695-11e9-9c7c-9837dd232caa.PNG)

![capture3](https://user-images.githubusercontent.com/26926657/53237465-131add00-3697-11e9-9b93-5ec868bc0bae.PNG)

And here is the error mesage :

![capture2](https://user-images.githubusercontent.com/26926657/53236974-d8647500-3695-11e9-9972-a4df7b5e9243.PNG)

**Comment by MohamedBRH** [comment]
@jinzhu can you give an idea on how to do that ? Thanks.

**Comment by Scott-Chen** [comment]
@MohamedBRH 
Try this.

```
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type User struct {
	gorm.Model
	Name   string
	Child  *User `gorm:"Foreignkey:Parent"`
	Parent *uint
}

func main() {
	db, err := gorm.Open("mysql", "root@/testdb")
	if err != nil {
		panic("failed to connect database")
	}
	defer db.Close()

	// Migrate the schema
	db.AutoMigrate(&User{})
	db.Model(&User{}).AddForeignKey("parent", "users(id)", "CASCADE", "CASCADE")

	// Create
	u := User{Name: "Parent"}
	db.Save(&u)

	u2 := User{Name: "Child", Parent: &u.ID}
	db.Save(&u2)
}
```

**Comment by MohamedBRH** [comment]
Hi Scott,
Thank you it works but only with onDelete cascade, with onUpdate the same issue it won't allow me to modify the primary key of a parent record.

**Comment by Scott-Chen** [comment]
@MohamedBRH 
It appears as if this is not permitted in innodb.
[https://dev.mysql.com/doc/refman/5.6/en/innodb-foreign-key-constraints.html](url)

`
If ON UPDATE CASCADE or ON UPDATE SET NULL recurses to update the same table it has previously updated during the cascade, it acts like RESTRICT. This means that you cannot use self-referential ON UPDATE CASCADE or ON UPDATE SET NULL operations. This is to prevent infinite loops resulting from cascaded updates. A self-referential ON DELETE SET NULL, on the other hand, is possible, as is a self-referential ON DELETE CASCADE. Cascading operations may not be nested more than 15 levels deep.
`

**Comment by MohamedBRH** [comment]
@Scott-Chen 
You're right, thank you I apreciate your help
