### ISSUE TITLE
Association.Replace() doesn't delete associated entities

### ISSUE THREAD

**Issue by avarabyeu** [go-gorm/gorm#2309]
### What version of Go are you using (`go version`)?
1.12

### Which database and its version are you using?
Postgres v9

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
Basically, the issue has already been commented in the source code
https://github.com/jinzhu/gorm/blob/master/association.go#L113 
`// has_one or has_many relations, set foreign key to be nil (TODO or delete them?)`
Are there any plans to introduce association removal?

**Comment by matramos** [comment]
I'm having the same problem. When I want to replace an association, is no "easy" way to delete the non existing ones.
 Is there a way besides the solution of this issue?
