### ISSUE TITLE
when sql with  alias name the value lose when map to struct

### ISSUE THREAD

**Issue by fcodetop** [go-gorm/gorm#2315]
scope.go file,line 494 
```go
for fieldIndex, field := range selectFields {
			if field.DBName == column {
					if field.Field.Kind() == reflect.Ptr {
					values[index] = field.Field.Addr().Interface()
				} else {
					reflectValue := reflect.New(reflect.PtrTo(field.Struct.Type))
					reflectValue.Elem().Set(field.Field.Addr())
					values[index] = reflectValue.Interface()
					resetFields[index] = field
				}
```

this condition "if field.DBName == column" may retrun a bug.
when we use a sql with alias name like this `select columna as b from table`
and struct define like this
```go
type  s struct{
        b string
} 
```
the value of struct field "b" was losed when map sql value .
So the condition ought to be `if field.DBName == column || field.Name == column`
@jinzhu

**Comment by huacnlee** [comment]
Do you use `db.Execute("select columna as b from table").Find(&result)` ?

**Comment by fcodetop** [comment]
when the field had no grom tag ,the struct will be a zero value.
when I taged the field like this:
`type Activity struct {
	ID        uint64 `gorm:"column:Id"`
	Title       string `gorm:"column:title"`
	Description string `gorm:"column:description"`
}`
it works well.
