### ISSUE TITLE
Is there a problem with the version golang1.12?

### ISSUE THREAD

**Issue by chenqgp** [go-gorm/gorm#2320]
When I updated the version to go-1.12, all statements like this:
    ```
    var token Tokens
    ```
    ```
    db.Debug().Where("token = ?", t).First(&token)
    ```

reported this error:

"runtime error: invalid memory address or nil pointer dereference"

the go version used before it was 1.9.2

### Which database and its version are you using?
MySQL version is 5.6

**Comment by deslum** [comment]
1. What is equal variable t?
2. Does t value exist in the database?
3.Show full code

**Comment by deslum** [comment]
Please use issue template https://github.com/jinzhu/gorm/blob/0fd395ab37aefd2d50854f0556a4311dccc6f45a/.github/ISSUE_TEMPLATE.md
