### ISSUE TITLE
order if joined index of multiple columns 多列联合索引顺序问题

### ISSUE THREAD

**Issue by qiuker521** [go-gorm/gorm#2323]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

go 1.10 & go 1.11.4

### Which database and its version are you using?
sqlite3

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
	"log"
	"os"
)

var db *gorm.DB

type Post struct {
	ID       uint64 `gorm:"index:idx_uploader_id"`
	Uploader string `gorm:"not null;size:64;default:'';index:idx_uploader_id"`
	Content  string `gorm:"not null;size:655250;default:''"`
}


func main() {
	var err error
	os.Remove("posts.db")
	db, err = gorm.Open("sqlite3", "posts.db")
	db.Debug()
	db.LogMode(true)
	if err != nil {
		log.Fatalln(err)
	}

	db.AutoMigrate(&Post{})
}
```

it aways generate:

```
[2019-03-11 16:22:06]  [3.93ms]  CREATE INDEX idx_uploader_id ON "posts"("id", "uploader")
```

but i want is 

```
idx_uploader_id(uploader,id)
```

the generate columns of `create index` sql is in bad order, is there any to solve it?
总是生成错误顺序的索引，有没有办法解决这个问题？

**Comment by qiuker521** [comment]
same as:

How can you control the order of the keys in the index?  For instance I believe this will be an index of `name, code`.  What if you wanted it to be `code, name`?

_Originally posted by @jchavannes in https://github.com/jinzhu/gorm/issues/961#issuecomment-433243723_

**Comment by qiuker521** [comment]
`db.Model(XX).AddIndex("idx_uploader_id", "uploader", "id")` 
can solve this question, but is not the way i want =

**Comment by soogoo** [comment]
```go
type Post struct {
	Uploader string `gorm:"not null;size:64;default:'';index:idx_uploader_id"`
	ID       uint64 `gorm:"index:idx_uploader_id"`
	Content  string `gorm:"not null;size:655250;default:''"`
}
```
try this

**Comment by qiuker521** [comment]
change the order of the field is a solution, but not satisfactory.

改变顺序确实能解决问题，但是…好像不尽如人意吧…
