### ISSUE TITLE
Stuck with a simple many_to_many join

### ISSUE THREAD

**Issue by chrisgreg** [go-gorm/gorm#2339]
Having an issue with a super simple Gorm query on a simple many_to_many relationship, I have 3 tables:

```
type Product struct {
ID          uint         `gorm:"unique"  json:"id"`
Name        string       `gorm:"name"  json:"name"`
Ingredients []Ingredient `gorm:"many2many:product_ingredients;"  json:"ingredients"`
}

type Ingredient struct {
ID   uint   `gorm:"unique" json:"id"`
Name string `gorm:"name" json:"name"`
}
```
(And a joining table)

I want to query where the ingredient name is a certain thing:

I can get general queries with all data doing this:

`db.Debug().Preload("Ingredients").Limit(limit).Offset(offset).Find(&products)
`
But trying to do something like this
`db.Debug().Preload("Ingredients").Limit(limit).Offset(offset).Where(Ingredient{Name: "Chicken"}).Find(&products)`

Gives me
Error 1054: Unknown column 'ingredients.name' in 'where clause'

Anyone able to help?

**Comment by zaneli** [comment]
Is this what you want to do?
http://gorm.io/docs/preload.html#Custom-Preloading-SQL

```go
	db.Debug().Preload("Ingredients", func(db *gorm.DB) *gorm.DB {
		return db.Where(Ingredient{Name: "Chicken"})
	}).Limit(limit).Offset(offset).Find(&products)
```

```
(/Users/zaneli/go/src/github.com/zaneli/gorm/scope.go:1045)
[2019-05-11 21:37:52]  [1.09ms]  SELECT * FROM `products`   LIMIT 1 OFFSET 0
[1 rows affected or returned ]

(/Users/zaneli/go/src/github.com/zaneli/gorm/scope.go:1045)
[2019-05-11 21:37:52]  [1.25ms]  SELECT * FROM `ingredients` INNER JOIN `product_ingredients` ON `product_ingredients`.`ingredient_id` = `ingredients`.`id` WHERE (`ingredients`.`name` = 'Chicken') AND (`product_ingredients`.`product_id` IN (1))
```
