### ISSUE TITLE
 help wanted: how to create indexes on jsonb?

### ISSUE THREAD

**Issue by vegh1010** [go-gorm/gorm#2347]
So I'm trying to create index on posgresql for Subject struct as jsonb but it's creating it wrongly. Am I doing something wrong?

```
type User struct {
	ID                uint        `gorm:"primary_key"`
	Subject      Subject `gorm:"type:jsonb"`
}

type Subject struct {
	Name            string `gorm:"index:idx_subject_name"`
	Description   string `gorm:"index:idx_subject_description"`
	Note              string `gorm:"index:idx_subject_note"`
}

After migration, it created this index.

CREATE INDEX index:idx_subject_name
    ON public.user USING btree
    (subject)
    TABLESPACE pg_default;
```

**Comment by buildscientist** [comment]
@vegh1010 The postgres [docs](https://www.postgresql.org/docs/9.6/datatype-json.html) provide more details - but basically you need to be using a GIN index type for jsonb fields.

Gorm doesn't support creating GIN indices (or really anything other than a btree based index) - the full issue is described in #2087

**Comment by buildscientist** [comment]
@vegh1010 

I ended up using raw SQL queries - here's a handy helper method I put together to create jsonb GIN indices: 

```go
 func AddGinIndex(tableName,fieldName string) {
 	indexName := "idx_" + tableName + "_" + fieldName
 	createIndexStatement := fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s ON %s USING gin (%s)",indexName,tableName,fieldName)
 	dbHandle.Exec(createIndexStatement)
 }
```
Couple of items to note: 

1. You can use this when after you call gorm.DB.CreateTable() or gorm.DB.AutoMigrate() as the `IF NOT EXISTS` clause prevents Postgres from creating the index if it already exists. 
1. The `IF NOT EXISTS` clause was introduced in Postgres v9.5. 

/cc @jinzhu - you can probably close out this issue now.

**Comment by vegh1010** [comment]
@buildscientist thanks

**Comment by basebandit** [comment]
@buildscientist works like a charm.
