### ISSUE TITLE
Table name  is reset to default values ?

### ISSUE THREAD

**Issue by JyinZ** [go-gorm/gorm#2350]
https://github.com/jinzhu/gorm/blob/8b07437717e71c2ff00602ae19f8353ba10aafbb/scope.go#L591

Table name is reset to default value when i use `.Table(not_default_table_name)` and `.Where(&MyDbStruct{DbField:whereCondition})`

**Comment by zaneli** [comment]
same as https://github.com/jinzhu/gorm/issues/2433#issuecomment-491241163 ?
