### ISSUE TITLE
about the created_at time zone

### ISSUE THREAD

**Issue by superwf** [go-gorm/gorm#236]
When created new record, the created_at insert value is 2014-09-30 00:58:27, and my computer local time is 2014-09-30 08:58:27, the time zone should be +8
Is there a method can set the time zone, like gorm.SetTimeZone("Shanghai"), or gorm.SetTimeZone(+8)?

**Comment by xiaoshengaimm** [comment]
the same question!! 
I think the golang time package is the most difficult package to use ....

**Comment by vutung7193** [comment]
you miss "&loc=Local" parameter when connect database. And it causes my above problem.

**Comment by phluan** [comment]
@vutung7193 I believe not every database adapters have this option. At least not for Postgres
