### ISSUE TITLE
Create or Update is not returning updated value

### ISSUE THREAD

**Issue by avinassh** [go-gorm/gorm#2367]
### What version of Go are you using (`go version`)?

```
go version go1.11.5 darwin/amd64
```

### Which database and its version are you using?

```
postgres (PostgreSQL) 11.2
```

### Please provide a complete runnable program to reproduce your issue.

Following are my table details:

```go
type Room struct {
	PK        string `sql:"size:255;not null;"gorm:"primary_key"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time

	LastSentMessageSeq int64
	RoomID             string `sql:"size:255;not null;"gorm:"unique_index:rooms_room_id_client_id"`
	User               User
	UserID             string `sql:"size:255;not null"`
	Client             Client
	ClientID           string `sql:"size:255;not null"gorm:"unique_index:rooms_room_id_client_id"`
}
```

I am trying to update or create operation. Following is my code: 

```go
var room = Room{ClientID: clientID, RoomID: roomID, UserID: usedID}
err := ws.db.Set("gorm:insert_option", "ON CONFLICT (room_id, client_id) DO UPDATE SET last_sent_message_seq = rooms.last_sent_message_seq + 1").Create(&room).Error
log.Println(room)
```

However, when I print the `room` object, it does not have the updated value for the field `last_sent_message_seq`. But I can see it is doing upsert operation, i.e. it creates a new row if it does not exist or updates the value of `last_sent_message_seq` in the database.

**Comment by DoubleLuck** [comment]
```go
newRoom := ws.db.Set("gorm:insert_option", "ON CONFLICT (room_id, client_id) DO UPDATE SET last_sent_message_seq = rooms.last_sent_message_seq + 1").Create(&room).Value.(*Room)
```

Just from my memory. 
If this doesn't work, please tell me and I will figure it out on my pc.

**Comment by evityuk** [comment]
@DoubleLuck 
It doesn't. 
According to sources, there's no assignment to Value fiield, neither there's no sql's `[returning clause](https://www.postgresql.org/docs/9.5/dml-returning.html)` generated by GORM or written inside `insert_option` field, which afterwards should be:
1. added to insert_option's "parent" query
2. parsed inside GORM and assigned to corresponding fields of model according to ORM responsibility.

The nil-able **Value** field is only get assigned in [a](https://github.com/jinzhu/gorm/blob/master/main.go#L182) [few](https://github.com/jinzhu/gorm/blob/master/main.go#L489) [places](https://github.com/jinzhu/gorm/blob/master/main.go#L774). 

Also be aware of *lack of support* of **returning clause** for sqlite engine(see [UPSERT docs](https://www.sqlite.org/lang_UPSERT.html)), which prevents from full support of upsert functionality on GORM side across all supported databases.
 
Possible workarounds can be found at:
 - sqlite_ecto [docs](https://github.com/jazzyb/sqlite_ecto/wiki/Sqlite.Ecto's-Pseudo-Returning-Clause)
 - SO [answer](https://stackoverflow.com/questions/15277373/sqlite-upsert-update-or-insert/38463024#38463024)

**Comment by DoubleLuck** [comment]
> @DoubleLuck
> It doesn't.
> According to sources, there's no assignment to Value fiield, neither there's no sql's `[returning clause](https://www.postgresql.org/docs/9.5/dml-returning.html)` generated by GORM or written inside `insert_option` field, which afterwards should be:
> 
> 1. added to insert_option's "parent" query
> 2. parsed inside GORM and assigned to corresponding fields of model according to ORM responsibility.
> 
> nil-able **Value** field is only get assigned in [a](https://github.com/jinzhu/gorm/blob/master/main.go#L182) [few](https://github.com/jinzhu/gorm/blob/master/main.go#L489) [places](https://github.com/jinzhu/gorm/blob/master/main.go#L774).
> 
> Also be aware of _lack of support_ of **returning clause** for sqlite engine(see [UPSERT docs](https://www.sqlite.org/lang_UPSERT.html)), which prevents from full support of upsert functionality on GORM side across all supported databases.
> 
> Possible workarounds can be found at:
> 
> * sqlite_ecto [docs](https://github.com/jazzyb/sqlite_ecto/wiki/Sqlite.Ecto's-Pseudo-Returning-Clause)
> * SO [answer](https://stackoverflow.com/questions/15277373/sqlite-upsert-update-or-insert/38463024#38463024)

Thank you for this!

**Comment by DoubleLuck** [comment]
@evityuk 
Thank you for this. It's really helpful.
