### ISSUE TITLE
当where 条件里有浮点数时查询结果为空

### ISSUE THREAD

**Issue by huguijian** [go-gorm/gorm#2369]
db.Where("test_id=? AND kda=1", msg["test_id"]).First(&kdaTable) fmt.Println(kdaTable) 这个是有结果的

db.Where("test_id=? AND kda=0.4", msg["test_id"]).First(&kdaTable) fmt.Println(kdaTable)这个是没有内容kda这个条件改成小点就不行了。 数据库里是有这条记录的。

**Comment by fwhezfwhez** [comment]
postgres测试是有结果的
