### ISSUE TITLE
Case insensitive .Where() queries

### ISSUE THREAD

**Issue by aaronn** [go-gorm/gorm#2377]
Are case-insensitive queries in gorm possible? For example, if I had a db.Where("key = ?") query, could ABXY match an input of abxy?

**Comment by fwhezfwhez** [comment]
this refers to your database.
if your database is case sensitive, then ABXY doesn't match abxy, otherwise do

**Comment by pdkproitf** [comment]
@aaronn you can use `ILIKE` in your query. 

`WHERE("name ILIKE ?", 'abc')`
