### ISSUE TITLE
How do I add a field to a many2many table and use it?

### ISSUE THREAD

**Issue by birdycn** [go-gorm/gorm#2387]
```
type Student struct {
ID int
Name string
Courses []Course `gorm:"many2many:student_courses;"`
}

type Course struct {
ID int
Name string
}
```

and I will get a table"student_courses,and if have three columns:"id,student_id,course_id"

and do i add a coulmn"score" in this table?and update it's value  by the gorm?

**Comment by yp2800** [comment]
The same issue. How to add extra field to middle table.

**Comment by jimanvlad** [comment]
+1 Interested in adding metadata to a many2many table.

**Comment by jimanvlad** [comment]
Based on the accepted answer [here](https://stackoverflow.com/questions/46576571/go-gorm-how-to-express-many2many-with-additional-columns), it looks like creating a structure using both names works in creating the additional column:

```
type StudentCourse struct {
	Score uint
}
```

However, it is then unclear to me how to populate this column.
```
f1 := Student{
		Model:     gorm.Model{ID:1},
		Name:      "Student 1",
		Courses:     []Course{
			{
				Model: gorm.Model{ID:1},
				Name:  "Economics",
			},
			{
				Model: gorm.Model{ID:2},
				Name:  "Maths",
			},
		},
	}

db.Save(&f1)
```

The code above creates the corresponding many2many data in `student_courses` but not sure where in the code above I can add the score...
