### ISSUE TITLE
Create doesn't create associated items

### ISSUE THREAD

**Issue by skliarovartem** [go-gorm/gorm#2394]
```
type Request struct {
	BaseModel
	ItemID        uint      `json:"-"`
	Item          TradeItem `gorm:"foreignkey:ItemID;"`
	Item2ID uint             `json:"-"`
	Item2   VesselNomination `gorm:"foreignkey:Item2ID;"`
}

type Item struct {
	BaseModel
}

type Item2 struct {
	BaseModel
}
```

When I do something like
```
r := &Request{}
i := &Item1{}
i2 := &Item2{}
r.Item = *i
r.Item2 = *i2
db.Create(r)
```
It creates Request, Item, but doesn't create Item2. 
I've simplified objects, so they have more fields. Sometimes Create creates all associated objects, but sometimes just part of them.
Is there any logic or rule, when object will be created automatically for sure?
Many thanks!

**Comment by rickiey** [comment]
I had the same problem. But some of them work normally.
