### ISSUE TITLE
How to use dynamic column in Where

### ISSUE THREAD

**Issue by xesai** [go-gorm/gorm#2406]
Hello, how to use dynamic column name query?

Like: db.Where("? = ?", columnName, value)

This is not safe: db.Where("\""+gorm.ToColumnName(columnName)+"\""+" = ?", value)

**Comment by YahuiAn** [comment]
@xesai 
Have you found a solution?I also need this feature.

**Comment by YahuiAn** [comment]
```golang
DB.Where(gorm.ToColumnName(field)+" = ?", value).First(&user)
```
I think this method can
