### ISSUE TITLE
how to get the LastInsertId after calling Exec

### ISSUE THREAD

**Issue by badoet** [go-gorm/gorm#242]
how to get the LastInsertId after calling Exec?
in another word how to grab sql.Result after calling Exec

**Comment by stevenkitter** [comment]
@badoet how do you solve this problem??

**Comment by badoet** [comment]
@stevenkitter see the answer above. you cant use custom sql query. im not using this library anymore.
i switched to https://github.com/go-pg/pg

**Comment by t2wu** [comment]
Yeah there is a possibility that to get spatial data working with this library in MySQL I have to use the raw SQL with exec. But then I run into this problem.
