### ISSUE TITLE
Bug: Provided `.Table()` not respected

### ISSUE THREAD

**Issue by aryzing** [go-gorm/gorm#2433]
Hi there, using 
Go: go1.12.3 linux/amd64
Postgres: docker image postgres:10.2

Given the following code below, the `.Table("features")` setting is respected in the `Create` method, but not in the `Read` method. To make the `Read` method work, I had to implement the `TableName()` method on `FeatureFlagModel`. The error reported by the postgres database is:

```
pq: missing FROM-clause entry for table "feature_flag_models"
```

The code:

```go
type Repository struct {
	db *gorm.DB
}

type FeatureFlagModel struct {
	ID    string `gorm:"column:id;type:uuid;primary_key"`
	Name  string `gorm:"column:name"`
	Value bool   `gorm:"column:value"`
}

func NewRepository(config *postgres.ClientConfig) (*Repository, error) {
	db, err := postgres.ConnectClientWithRetry(config, dbTimeout, dbRetryAttempts)
	if err != nil {
		return nil, err
	}

	return &Repository{db: db}, nil
}

func (r Repository) Create(name string, value bool) (id string, err error) {
	id = uuid.NewV4().String()
	err = r.db.Table("features").Create(&FeatureFlagModel{ID: id, Name: name, Value: value}).Error
	if err != nil {
		return "", err
	}
	return id, nil
}

func (r Repository) Read(id string) (*FeatureFlagModel, error) {
	featureFlag := &FeatureFlagModel{}
	// ERROR! this next line throws error described above
	err := r.db.Table("features").Where(&FeatureFlagModel{ID: id}).First(featureFlag).Error
	if err != nil {
		return nil, err
	}
	return featureFlag, nil
}
```

**Comment by zaneli** [comment]
I think this is valid processing.

```sql
SELECT * FROM `features`  WHERE (`feature_flag_models`.`id` = 'f877b279-2d17-422f-80e0-480e9c36113b') ORDER BY `features`.`id` ASC LIMIT 1
```

* `SELECT * FROM features`
respected `.Table("features")`.
* `WHERE (feature_flag_models.id = '...')`
not respected `.Table("features")`, but this query made by `.Where(&FeatureFlagModel{ID: id})`, it is unrelated to `.Table("features")`.
* `ORDER BY features.id`
respected `.Table("features")`.

I think you might as well implement the `TableName()`, or `.Where("id = ?", id)`.
