### ISSUE TITLE
many2many use select return []

### ISSUE THREAD

**Issue by fitan** [go-gorm/gorm#2437]
### What version of Go are you using (`go version`)?

go version go1.10.1 linux/amd64
### Which database and its version are you using?
sqllite

![image](https://user-images.githubusercontent.com/34503273/57072984-2dfe7300-6d12-11e9-96fe-4aea726bb59b.png)
![image](https://user-images.githubusercontent.com/34503273/57073004-466e8d80-6d12-11e9-8631-147b4f35b978.png)

its dont have field name. but sql is good.  

![image](https://user-images.githubusercontent.com/34503273/57073068-8170c100-6d12-11e9-9dfe-35525bde8b68.png)

![image](https://user-images.githubusercontent.com/34503273/57073089-90f00a00-6d12-11e9-99fb-dcd46d96b13b.png)

**Comment by xiansongbai** [comment]
try .find(&u)

**Comment by fitan** [comment]
> u := new([]User)

![image](https://user-images.githubusercontent.com/34503273/57188045-f0c0fd80-6f2a-11e9-9116-881ed13b20c8.png)

its  slice.    many2many

**Comment by fitan** [comment]
![image](https://user-images.githubusercontent.com/34503273/57606870-6f0d4780-759c-11e9-8df2-7bba64b596b6.png)
Does it not support this way of writing?

**Comment by friedpig** [comment]
You can fix it with `db.Select ("name,user_id ")`

**Comment by fitan** [comment]
> 你可以修复它 `db.Select ("name,user_id ")`

ths,   I found a solution.  I modified the source code

![image](https://user-images.githubusercontent.com/34503273/57768812-fbf00680-773e-11e9-8d4d-129f57abfef2.png)

This may not be a good way to do it.
