### ISSUE TITLE
Update() query may not be executed

### ISSUE THREAD

**Issue by alex-telpis** [go-gorm/gorm#2449]
`err := db.Debug().Model(&User{}).Update("nonexistent-column-or-typo", "value").Error`

Expected: query error, since "nonexistent-column-or-typo" does not exist.
Got: the whole query is not executed

**Comment by DarcyNing** [comment]
without addtional settings like table name change , you should make sure your table users has a column named "nonexistent-column-or-typo", then you can try again.
