### ISSUE TITLE
Feature Request: Connection switching for multiple databases

### ISSUE THREAD

**Issue by hareku** [go-gorm/gorm#2456]
I request to implement connection switching for multiple databases.
It's like Rails 6 ActiveRecord feature.
https://github.com/rails/rails/pull/34052

In the case of gorm, I think it maybe above this code.
```user.go
type User struct {}

func (User) WritingDBName() string {
  return "user_writing_db"
}
func (User) ReadingDBName() string {
  return "user_reading_db"
}
```

If I can implement this feature, is it possible to merge?

**Comment by stevenkitter** [comment]
Very good idea, I prefer to this too.
