### ISSUE TITLE
Unique constraint for multiple columns?

### ISSUE THREAD

**Issue by qmn1711** [go-gorm/gorm#2459]
### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Which database and its version are you using?
PostgreSQL 10.8

I can't create unique constraint for multiple columns with gorm.
```
type Language struct {
	ID   int
	Name string `gorm:"unique:uq_name_code"`
	Code string `gorm:"unique:uq_name_code"` 
}
```
Run the code above will throw error: `panic: pq: syntax error at or near "uq_name_code"`

From https://github.com/jinzhu/gorm/issues/961 I know there is a way to create UNIQUE INDEX but I do need a UNIQUE constraint only for using it with `ON CONFLICT` upsert query.

Please support this case, thanks!

**Comment by abhishek246** [comment]
Hello @qmn1711 ,  

please  `unique_index` instead of `unique`
`gorm:"unique_index:uq_name_code"`

Thank You

**Comment by qmn1711** [comment]
Hi @abhishek246,
Thank for your response but as I mentioned I do know there is `unique_index` but in my case I need `unique` constraint only. `unique_index` won't work in `ON CONFLICT upsert query`

**Comment by nelsonn3c** [comment]
Also, if you have multiple tables whith same keys (example id, time, value) and same constraint pairs (like, time_value pair), there will be thrown a error when using unique_index:

> "pq: relation "time_value" already exists" not being applied"

**Comment by youncccat** [comment]
@qmn1711 Hey~ have u resolve this problem, I have the same problem

**Comment by qmn1711** [comment]
not yet, I had to workaround by sql
