### ISSUE TITLE
Delete related records in has many relationship

### ISSUE THREAD

**Issue by jrozner** [go-gorm/gorm#2463]
Given the following types:

```go
type User struct {
  gorm.Model
  Flags []Flag
}

type Flag struct {
  gorm.model
  Name string
  UserID int
}
```
I want to be able to remove all of a user's flags. Assuming user is the already returned user record in a User type I'm using:

```go
db.Model(&user).Related(&user.Flags).Delete(&user.Flags)
```

But the generated query is:

```sql
UPDATE flags SET deleted_at = '...' WHERE deleted_at IS NULL
```
rather than
```sql
UPDATE flags SET deleted_at = '...' WHERE deleted_at IS NULL and user_id IN (...)
```

In order to get the correct query I need to use something like:
```go
db.Model(&user).Preload("Flags").Where("user_id = ?", user.ID).Delete(&user.Flags)
```

Am I doing something wrong?

**Comment by mwei0210** [comment]
any update on this?

**Comment by hobbsgoblin** [comment]
I would like to know this as well

**Comment by jerlam06** [comment]
The lack of documentation (and details in the documentation) for Gorm is very frustrating, there is too much "guess how to do" involved. So far, I have spent days trying to achieve some "simple" actions, such as the one from the OP, but I always end up using a very non efficient workaround.

**Comment by hykuan** [comment]
I am using the following command to delete flag records that associated to user,
but you can't only delete user and preserve the related flag in this case.

```
db.AutoMigrate(&User{}, &Flag{})
db.Model(&Flag{}).AddForeignKey("user_id", "users(id)", "CASCADE", "SET DEFAULT")
// this will also delete associated flag records
db.Delete(&user)
```
