### ISSUE TITLE
自己拼接SQL count 和 scan 问题

### ISSUE THREAD

**Issue by axetroy** [go-gorm/gorm#2468]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

go version go1.12.5 darwin/amd64

### Which database and its version are you using?

postgres

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

func main() {
  tx.Raw(sql).Count(&total).Scan(&list).Error
}
```

```sql
SELECT COUNT(*) as transfer_log FROM "transfer_log_cny" WHERE  ("deleted_at" IS NULL OR "deleted_at"='0001-01-01 00:00:00')
UNION
SELECT COUNT(*) as transfer_log FROM "transfer_log_usd" WHERE  ("deleted_at" IS NULL OR "deleted_at"='0001-01-01 00:00:00')
UNION
SELECT COUNT(*) as transfer_log FROM "transfer_log_coin" WHERE  ("deleted_at" IS NULL OR "deleted_at"='0001-01-01 00:00:00')
LIMIT 10
```

自己拼接的 SQL 语句.

当 `SELECT COUNT(*)` 时, `tx.Raw(sql).Count(&total).Scan(&list)` 能正确统计数据量, 但是 scan 映射不了数据
当 `SELECT *` 时, `tx.Raw(sql).Count(&total).Scan(&list)` 不能统计数据量， 但能正确映射数据

不知道是哪里错了，有没有经历过的

所以目前我只能分开两条SQL去查询

**Comment by sunsmiles** [comment]
+1

**Comment by tony84727** [comment]
> 当 SELECT * 时, tx.Raw(sql).Count(&total).Scan(&list) 不能统计数据量， 但能正确映射数据

I guess `list` is a slice. If you can get the rows, you should be able to use `len(list)` to get the count.

**Comment by 1486327116** [comment]
u can use .Scan().RowsAffected,the  return val is int64（your count_num）

**Comment by itcuihao** [comment]
@axetroy @sunsmiles 需要将list定义为结构体类型，
```
type Count struct{
Count int `json:"count"`
}
var list Count
Scan(&list)
```

**Comment by pax0** [comment]
+1

**Comment by pax0** [comment]
我分开去查的也有问题
https://github.com/jinzhu/gorm/issues/2724
