### ISSUE TITLE
字段重复

### ISSUE THREAD

**Issue by sootma** [go-gorm/gorm#2474]
嵌套结构体，字段重复：
 type PO struct{
    Id        int64
    Name string
    UpdatedBy int64
    DomainId  int64 
}

 type VO struct{
    PO
    Id        int64 `json:",string"`
    UpdatedBy int64 `json:",string"`
    DomainId  int64 `json:"-"`
}
db.Table("table_po").Create(&VO{Id:111, Name:'xinglin', UpdatedBy:88888, DomainId:88888})
生产的sql是：
insert into table_po(id, name, updated_by, domain_id, updated_by, doamin_id) values(111, 'xinglin',0,0, 88888,88888)

其中, updated_by, domain_id重复了，造成insert 错误

**Comment by aixiaoxiang** [comment]
你认为都这样赋值了  UpdatedBy:88888, DomainId:88888 当然会产生那样的sql 语句， 
想忽略字段应该使用  `grom:-`

**Comment by sootma** [comment]
1. PO是用工具自动生成的，我不想每次都去改动它，所有，用VO去扩展它，目的是覆盖PO的定义
2. 这样做，生成的json是没有问题的，能够按照VO的设置正确生成，没有domainId, 并且id, 与upbdateBy也都是string
3. 我如果在VO中加上grom:-忽略domainId, sql中的确是不生成VO的domainId, 但它会生成PO的domainId, 而PO.domainId是0值，这样结果不正确。

我的需求：
1. 不改动PO
2. 生成sql时，先取最近的struct （如VO）生成field, 然后再取其扩展的struct(PO), 如果已有相同的field存在（如domainId）,则应该忽略PO的相同的字段
因为golang的定义也是用扩展的字段覆盖其组合的相同字段。
