### ISSUE TITLE
Writing/reading binary data using GORM

### ISSUE THREAD

**Issue by krishnavaltix** [go-gorm/gorm#2482]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.10.4

### Which database and its version are you using?
MYSQL 5.6.39

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
I am writing a binary object to database, this does not seem to work if I return array of bytes
What is the best practice writing/reading binary data using GORM

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
// Scan scans bytes into Properties
func (i *Properties) Scan(value interface{}) error {
        buf, ok := value.([]byte)
	if !ok {
		return errors.New("Bytes expected")
	}
<snip actual unmarshal code>
}

// Value marshals value to bytes
func (i *Properties) Value() (driver.Value, error) {
       var buf = []byte
	<snip marshal code that write to buf>
	return buf, err
}

// Profile - DB representation for profile
type Profile struct {
	Properties *Properties `sql:"not null" gorm:"size:32000"`
}
```

**Comment by gi-yt** [comment]
@krishnavaltix did you find a solution to this?
