### ISSUE TITLE
[BUG] concurrent query may cost diriver bad connection

### ISSUE THREAD

**Issue by chnzrb** [go-gorm/gorm#2486]
var (
	Db            *gorm.DB
)
func init() {
     ......
	Db.DB().SetMaxOpenConns(500)
	Db.DB().SetMaxIdleConns(100)
	Db.DB().SetConnMaxLifetime(7200)
}
func GetGameOne(id int) (*Game, error) {
	data := &Game{}
	err := Db.Where(&Game{Id: id}).First(&data).Error
	return data, err
}

func Test() {
	for i:=0; i< 1000; i++ {
		go func(jj int) {
			_, err := models.GetGameOne(1)
			utils.CheckError(err, fmt.Sprintf("i:%d", jj))
		}(i)
	}
}

run function Test()  may cost error => diriver:bad connection

**Comment by tedli** [comment]
@chnzrb 
Have a look at #2547 .
I have the same problem, sometimes 'bad connection', sometimes 'network is unreachable'.
