### ISSUE TITLE
can't preload self-referencing association

### ISSUE THREAD

**Issue by schecterdamien** [go-gorm/gorm#2496]
### What version of Go are you using (`go version`)?
go version go1.11.1 darwin/amd64

### Which database and its version are you using?
PostgreSQL 10.4 on x86_64-apple-darwin17.5.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.1), 64-bit

### code

```go

type Category struct {
	ID uint `gorm:"primary_key"`
	Name string `gorm:"size:50"`
	Parent *Category `gorm:"ForeignKey:ParentID"`
	ParentID uint
}

var testCategory []Category
db.Debug().Preload("Parent").Where("id = ?", 12).Find(&testCategory)
fmt.Println(testCategory)
```
I get result print as `{12 高效办公 <nil> 16}`。。I can't get parent information，but it exist，ParentID is 16.  the generated sql is 
```
SELECT * FROM "si_category"  WHERE (id = 12)

SELECT * FROM "si_category"  WHERE ("parent_id" IN (12))
```
for second sql what i expect is `SELECT * FROM "si_category"  WHERE ("parent_id" IN (16))`

is there something wrong?

**Comment by a7i** [comment]
You want to use

```
db.Debug().Preload("Parent", "`parent_id` = ?", 12).Find(&testCategory)
```

**Comment by a7i** [comment]
I believe your field tag may be incorrect

```
Parent *Category `gorm:"foreignkey:ID;association_foreignkey:ParentID"`
```
