### ISSUE TITLE
How to support 2 belongsTo relationships on a model that shouldn't be belongsToMany

### ISSUE THREAD

**Issue by kennetpostigo** [go-gorm/gorm#2498]
### What version of Go are you using (`go version`)?
go version go1.12.5 darwin/amd64

### Which database and its version are you using?
PostgreSQL 11.3

### Description
I'm migrating our services to use Gorm instead of Sequelize from Javascript and i'm trying to figure out how to port a specific part but I can't quite figure out the semantics of if this exists or is possible in Gorm. So here's some code:

```js
Game.belongsTo(Team, { as: "home" }); // Will add teamId to Game model as "home"
Game.belongsTo(Team, { as: "away" }); // Will add teamId to Game model as "away"
```

What this does is create a relationship between these two models `Game` and `Team`. Where the reference will be put on Game for `home` and `away` that are of Team models, and Team will be left untouched, as in have no idea that it is referenced by a Game. Idk how to accomplish this in Gorm because from the examples in Gorm of a belongsTo association I couldn't figure out how to create two of these relationships on Game for both to determine which is `home` and which is `away`:

```go
//Belongs To =========================
type Team struct {
  gorm.Model
  Name string
  ...
}

// `Game` belongs to `Team`, `TeamID` is the foreign key
type Game struct {
  gorm.Model
  TeamID int // How do I support HomeTeamID and AwayTeamID
  Team   Team // HomeTeam and AwayTeam
  Name   string
  ...
}
```

Is this possible in Gorm and can anyone explain the changes I should make to make this possible?

**Comment by yuanagain** [comment]
Also interested in this.

**Comment by kennetpostigo** [comment]
@jinzhu sorry to bug you, but anyway you might be able to clarify this?
