### ISSUE TITLE
Reducing DB connection usage with Transaction

### ISSUE THREAD

**Issue by badoet** [go-gorm/gorm#253]
To my understanding or at least my impressions,
calling:
db.Find(...) // find a
db.Find(...) // find b
db.Find(...) // find c

will result to 3 db connection being used up
and i also notice that using transaction db.Begin() will limit the connection to the transaction connection that is being declared.

so meaning
tx := db.Begin()
tx.Find(...) // find a
tx.Find(...) // find b
tx.Find(...) // find c

this will just use 1 db connection for the select query, is this true?
and since its a select query, we dont really need to call tx.Commit() at the end right?

cheers

**Comment by totoleo** [comment]
@jinzhu  i see a doc [here](http://go-database-sql.org/surprises.html), which say the DB of database/sql will open a new connection for query
