### ISSUE TITLE
AUTO_INCREMENT触发全表扫描

### ISSUE THREAD

**Issue by CharmingZhou** [go-gorm/gorm#2535]
查看gorm源码，如果数据模型中使用了"AUTO_INCREMENT"但未使用"PRIMARY_KEY"的tag, 那么在Create的时候会调用Scan方法触发全表扫描。在数据量很大的情况下，很容易导致CPU 100%。

请教一下，数据模型使用了AUTO_INCREMENT的tag，为什么会触发全表扫描，是为了查询相应字段的最大值吗？

**Comment by hackfengJam** [comment]
- [callback_create.go:173](https://github.com/jinzhu/gorm/blob/59408390c2dce9ca8b48fae08937213e72b24f9a/callback_create.go#L173) 注释上说，是需要扫一遍，把默认值设置回去
