### ISSUE TITLE
GORM Count(*) returns 0

### ISSUE THREAD

**Issue by AbhilashGopalakrishna** [go-gorm/gorm#2538]
### What version of Go are you using (`go version`)?
1.12.4

### Which database and its version are you using?
MySQL 5.7.24

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	
	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
      err := db.Table(db+"."+tb).Where("? >= ?", columnname, date+" 00:01:00").Count(&cnt)
	if err != nil {
		Error.Println(err.Error.Error())
	}
	fmt.Println("The Count is \n", cnt)
}
```

**Problem Statement**

- _Problem 1_

I am getting a 0 when trying to retrieve the count.
The query expression is perfect, by which I assume that the query being built is correct.

However, the result is 0 irrespective of the query.

- _Problem 2_

I am required to specify the db name in the Table clause as  `Table(dbname.tbname)`

This isn't required in the any other queries and is required only when using Count()

What might I be missing?

**Update 1**

The following works.
But this is as per my understanding using the result as *sql.Row and then retrieving  the result using scan.

But I don't understand,why  `...Count(&count)` is giving a run time error?

**Comment by pax0** [comment]
+1

**Comment by pygmalion666** [comment]
+1
