### ISSUE TITLE
Nil error with DefaultCallback

### ISSUE THREAD

**Issue by RNiveau** [go-gorm/gorm#2544]
Hi,

With this commit https://github.com/jinzhu/gorm/commit/8b127471f1679b468cc13c5736fa401e16f664d1#diff-6a4cdb31ba172474c25dc7609d662f39
You introduce a logger in Callback but you don't initialize it in the DefaultCallback.

So a call to this for example raise a nil error 
gorm.DefaultCallback.Update().Replace

**Comment by fishbullet** [comment]
The same error here raised 
`gorm.DefaultCallback.Create().Remove('callback')`

**Comment by zaneli** [comment]
Fixed by #2742 .
It will probably be fixed in the next version.
