### ISSUE TITLE
when db connection close, gorm not reconnect to mysql

### ISSUE THREAD

**Issue by lyfunny** [go-gorm/gorm#2558]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.12

### Which database and its version are you using?
mysql

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
DefaultDB, err = gorm.Open("mysql", util.AppConfig.DBConf["flx-config"])
	if err != nil {
		util.BhAlarm(util.BH_LOG_DB, err, "op db conn err.")
	}
	DefaultDB = DefaultDB.Debug()
	DefaultDB.DB().SetMaxIdleConns(10)
	DefaultDB.DB().SetMaxOpenConns(100)
	DefaultDB.DB().SetConnMaxLifetime(time.Hour)
```

After the program runs for a period of time, the gorm reports an error, the database is closed, and then no data can be read from the database. use netstat finds that there is no connection to the database, but use mysql-client in command line can  successfully connected to mysql and query data , why the gorm is not reconnected to mysql  ?

**Comment by whutwxn** [comment]
I meet this question again

**Comment by melonwool** [comment]
meet this question again

**Comment by victormongi** [comment]
Mee too..

**Comment by xdxiaodong** [comment]
Mee too..

**Comment by narrowizard** [comment]
try to update `github.com/go-sql-driver/mysql` package.
