### ISSUE TITLE
db.NewRecord() always true

### ISSUE THREAD

**Issue by zhangguanzhang** [go-gorm/gorm#2566]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.12.6

### Which database and its version are you using?
mysql 5.7.26

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"os"
)


type Machines struct {
	//设备标签名
	DeviceLabel string	`gorm:"column:DeviceLabel;"`

	//专有网口mac地址
	IPMIMac string `gorm:"size:17;column:IPMIMac;unique"`

	*KSHeader
	gorm.Model
}

type KSHeader struct {
	SerialNumber string `gorm:"size:20;column:SerialNumber;"`
	Arch	string 	`gorm:"size:7;column:Arch"`

}

func main() {

	db, err := gorm.Open("mysql", "root:zhangguanzhang@tcp(192.168.123.210:3306)/z?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		fmt.Println(err)
		os.Exit(2)
	}
	defer db.Close()


	db.AutoMigrate(&Machines{})

	ins := Machines{
		IPMIMac: "9c:e8:95:d8:3c:cc",
		KSHeader: &KSHeader{Arch:"x86_64",},
	}

	if db.NewRecord(ins) {
		fmt.Println(1)
		db.Create(&ins)
	} else {
		fmt.Println(0)
	}

}
```
before run:
```
mysql> select * from machines;
ERROR 1146 (42S02): Table 'z.machines' doesn't exist
```
after the first run , program print 1
run again,it print this:
```
1

(C:/Users/guanzhang/go/src/test/test3.go:55) 
[2019-07-18 14:59:32]  Error 1062: Duplicate entry '9c:e8:95:d8:3c:cc' for key 'IPMIMac' 

Process finished with exit code 0
```
It seemd that `db.NewRecord()` always return true

**Comment by zhangguanzhang** [comment]
simple show this：
```
fmt.Println(db.NewRecord(ins))
db.Create(&ins)
fmt.Println(db.NewRecord(ins))
```
out
```
true
true
```

**Comment by zhangguanzhang** [comment]
我找到原因了，放在最前面继承就ok。。。
```
type Machines struct {

	gorm.Model
....
```
@jinzhu

**Comment by dedifferentiator** [comment]
Run into the same problem, looks like the thing is that in docs `db.NewRecord(user) // => return "false" after "user" created` although in code
```
func (s *DB) NewRecord(value interface{}) bool {
	return s.NewScope(value).PrimaryKeyZero()
}
```
it just check primary key without query to a database, so should be made one of two:
1.Change docs

**Comment by dedifferentiator** [comment]
Run into the same problem, looks like the thing is that in docs `db.NewRecord(user) // => return "false" after "user" created` although in code
```
func (s *DB) NewRecord(value interface{}) bool {
	return s.NewScope(value).PrimaryKeyZero()
}
```
it just checks primary key without querying to a database, so should be made one of two:
1. Change docs
2. Change function so it will query value from db.

**Comment by dedifferentiator** [comment]
I would like to try to solve this issue, need just some help with managing callbacks in gorm. Could anyone guide me in first contribution?

**Comment by mskmemory** [comment]
I have two question. First,  When `db.NrewRecord(user)` returns false, does it mean that the primary key is blank?   Second, ``// => returns ` true ` as primary key is blank`` is this statement itself correct ?

**Comment by dedifferentiator** [comment]
@mskmemory `db.NewRecord()` checks if a primary key field equal to a zero value of its type. About your second question, I'm not really sure why do we need a function for what could be written in a single if comparison, but I must agree that docs do not explain this moment really well, I wasn't sure about what `db.NewRecord()` does before I saw [this comment](https://github.com/jinzhu/gorm/issues/1044#issuecomment-270656775) by jinzhu in one of the issues.
