### ISSUE TITLE
how to coding  about  Transactions ?

### ISSUE THREAD

**Issue by cpj555** [go-gorm/gorm#2571]
![image](https://user-images.githubusercontent.com/19289096/61577727-128b5300-ab1e-11e9-8724-94ee62029242.png)

i want to use  Transactions  like this, but the gorm  have to use the new clone  tx ,in the fact,it is hard to coding ,i want in the service call the funtion in the model

![image](https://user-images.githubusercontent.com/19289096/61577792-e58b7000-ab1e-11e9-95bc-a504c2afd4f0.png)

**Comment by kimjayson** [comment]
i used the new tx cover the old one.
