### ISSUE TITLE
use interface{} as query destination

### ISSUE THREAD

**Issue by SherL0cked** [go-gorm/gorm#2576]
Hi, issue was first mentioned in https://github.com/jinzhu/gorm/issues/857 and jinzhu provided a workaround as below.
``` go
package main

import (
    _ "github.com/go-sql-driver/mysql"
    "github.com/jinzhu/gorm"
)

type Foo struct {
    gorm.Model
    Name string
}

var db *gorm.DB

func find(v interface{}) {
    db.Debug().Find(v)
}

func main() {
    var err error
    db, err = gorm.Open("mysql", "gorm:gorm@/gorm?charset=utf8&parseTime=True&loc=Local")
    if err != nil {
        panic(err)
    }

    db.AutoMigrate(&Foo{})

    var x1 = []Foo{}
    find(&x1)
}
```

_Originally posted by @jinzhu in https://github.com/jinzhu/gorm/issues/857#issuecomment-186724632_

However when I assign `x1` as datatype `interface{}`, it won't work. 
> ```go
> func main() {
>     var err error
>     db, err = gorm.Open("mysql", "gorm:gorm@/gorm?charset=utf8&parseTime=True&loc=Local")
>     if err != nil {
>         panic(err)
>     }
> 
>     db.AutoMigrate(&Foo{})
> 
>     var x1 interface{} = []Foo{}
>     find(&x1)  // ERROR: unsupported destination, should be slice or struct 
> }
> ```
Is there anyway we can dynamically evaluate those variables in the GORM query?

Thanks

**Comment by atombender** [comment]
This is very annoying. We have an application where we frequently have to construct slices dynamically, leading to problems like this:

```go
// Model interface shared by all model types
type Model interface{}

// Banana is a model
type Banana struct {
  ID string
}

func newSlicePtr(modeltype Model, length, cap int) interface{} {
	slice := reflect.MakeSlice(reflect.SliceOf(reflect.TypeOf(modeltype)), length, cap)
	v := reflect.New(slice.Type())
	v.Elem().Set(slice)
	return v.Elem().Interface()
}

func newSlice(modeltype Model, length, cap int) interface{} {
	slice := reflect.MakeSlice(reflect.SliceOf(reflect.TypeOf(modeltype)), length, cap)
	v := reflect.New(slice.Type())
	v.Elem().Set(slice)
	return v.Interface()
}

func doThings(modeltype Model) {
  // This works, because newSlicePtr() returns a *[]Banana
  modelsByPtr := newSlicePtr(modeltype, 0, 10)
  db.Where("thing").Find(modelsByPtr)

  // This does NOT work, because newSlicePtr() returns a []Banana
  models := newSlice(modeltype, 0, 10)
  db.Where("thing").Find(models)
}

func main() {
  doThings(&Banana{})
}
```

I would also love it if you could simply override Gorm's assumptions about typing. I'd like to be able to do this:

```
// This would load bananas, describe the models var being a slice of interface{}
var models []interface{}
db.Type(&Banana{}).Where("something").Find(&models)
```

**Comment by gatspy** [comment]
Direct binding `[] interface {}`, table name cannot be obtained. 
debug log info:
```
select * from ``
```
