### ISSUE TITLE
Wrong sql generated by gorm

### ISSUE THREAD

**Issue by mkloveyy** [go-gorm/gorm#2583]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.12

### Which database and its version are you using?
mysql 5.7.23

Wrong sql generated by gorm as follows:
```
rspQuery := "SELECT * FROM (SELECT created_at, detail, user, release_id, 
level FROM actions UNION ALL SELECT created_at, detail, user, release_id,
 level FROM deployment_logs ORDER BY created_at) a"

db.Engine.Raw(rspQuery).Where("release_id = ? AND level = ?", releaseID, releaseLogReq.Level)
```
Error:
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND (release_id = ? AND level = ?' at line 1
SELECT * FROM (SELECT created_at, detail, user, release_id, level FROM actions UNION ALL SELECT created_at, detail, user, release_id, level FROM deployment_logs ORDER BY created_at) a) AND (release_id = 31 AND level = 1
```

**Comment by sswanv** [comment]
I don't understand why the way to use Raw, but also Where, from a code point of view, this is obviously a bug.

**Comment by mkloveyy** [comment]
@sswanv I want to join two different log model into one return. So do you have any good idea? thx!

**Comment by dre2004** [comment]
I don't think this is a bug with GORM, I think you need to review your SQL or use an appropriate struct to bind the request to.

The error you've posted is from the mysql driver, saying your query has an error. If you were to write out the whole query you would get something like 

`SELECT * FROM (SELECT created_at, detail, user, release_id, 
level FROM actions UNION ALL SELECT created_at, detail, user, release_id,
 level FROM deployment_logs ORDER BY created_at) a WHERE release_id = ? and level = ?`

Try and run that query from a mysql client and you'll probably see the same error there. You have 1 main query and two sub queries and the field names are ambiguous (SQL when you are specifying release_id in your where clause there are three potential places it could be looking for a field named release_id so it would error just on that.

If you want to join two models I would approach it by either using RAW SQL and handle the output yourself (once you figure out the query). Or use the the association mode.

`db.Model(&Log1).Association("foreign_key").Find(&Log2)`

See http://jinzhu.me/gorm/associations.html#association-mode
