### ISSUE TITLE
请教如何判断错误信息为：主键冲突/唯一性冲突

### ISSUE THREAD

**Issue by zltgo** [go-gorm/gorm#2594]
如题，目前只有一个IsRecordNotFoundError()函数可以判断错误类型，对于唯一性冲突类
的错误，该如何判断？

目前只知道sqlite3返回的是“UNIQUE constraint failed”，
判断是否包含该字符串能否通用其他数据库，还有更专业的判断方法么？

望大神们不吝赐教！

**Comment by avakarev** [comment]
You can rely on driver-specific errors instead, like in this example: https://github.com/mattn/go-sqlite3/issues/244#issuecomment-147408246, just use `sqlite3.ErrConstraintUnique` instead of `sqlite3.ErrBusy`, check all available errors here https://github.com/mattn/go-sqlite3/blob/master/error.go

**Comment by zltgo** [comment]
thank you！

**Comment by kimjayson** [comment]
我用的很low的方法strings.contains('duplicate')，也解决了~

**Comment by cszichao** [comment]
I implemented a simple `isUniqueConstraintError` using @avakarev solution on mysql.

```golang

const (
	MySQLErrDupEntry            = 1062
	MySQLErrDupEntryWithKeyName = 1586
)

func isUniqueConstraintError(err error) bool {
	if sqliteErr, ok := err.(sqlite3.Error); ok {
		if sqliteErr.ExtendedCode == sqlite3.ErrConstraintUnique ||
			sqliteErr.ExtendedCode == sqlite3.ErrConstraintPrimaryKey {
			return true
		}
	} else if mysqlErr, ok := err.(*mysql.MySQLError); ok {
		if mysqlErr.Number == MySQLErrDupEntry ||
			mysqlErr.Number == MySQLErrDupEntryWithKeyName {
			return true
		}
	}
	return false
}
```
