### ISSUE TITLE
How can you modify existing rows and tables?

### ISSUE THREAD

**Issue by chriskarani** [go-gorm/gorm#2598]
I have an existing PSQL database that already has user data inside, how can I access that data from GORM and manipulate it? 
at the moment when I try to use db.Find() I get the error ` zero-length delimited identifier at or near """"`

**Comment by whosamhughes** [comment]
@xrisyz, I'm not sure what issue you're having, but I could suggest the following:

We also have an existing database that doesn't fit GORM's expected defaults.
1. Have you created functions received by your Gorm types that specify the tablename? For our "Userz" table, mapped by a "Owner{}" type,  I must include:

```
type Owner {
  //fields
}

func (Owner) TableName() string{
  return "userz"
}
```

2. Have you specified the field name as Go expects it?

```
type Owner {
   Id int `gorm:"column:user_id"`
  UserId `gorm:"column:user_id;primary_key;auto_increment"`
  FirstName string `gorm:"column:user_firstname"`
  Lastname string `gorm:"column:user_lastname"`
  //additionalfields
}

```

**Comment by tamoyal** [comment]
I also have this issue:
```go
type Lesson struct {
	BaseModel
	Id        int64
	Slug      string `gorm:"not null"`
	TopicId   int64  `gorm:"not null"`
	Title     string `gorm:"not null"`
	Version   int64  `gorm:"not null"`
	Prompts   []Prompt
	Questions []Question
}
```

And I update with:
```go
result := db.Update(lesson)
if result.Error != nil {
    panic(result.Error)
}
```

which produces:
```
panic: pq: zero-length delimited identifier at or near """"
```

Logging the query shows:

```sql
UPDATE "" SET "created_at" = '2020-04-16 02:14:29', "id" = 14, "slug" = 'repaso_1', "title" = 'Repaso 1', "topic_id" = 3, "updated_at" = '2020-04-16 02:14:29', "version" = 1
```

So it seems the table name is not getting picked up. My table name is `lessons` and it's a pretty straightforward setup for that model. Any idea what this might be?

**Comment by tamoyal** [comment]
This is because I need to use `Save` not `Update`. I wonder if returning a better error here would be the right decision. Sorry for the report when it ended up being my misuse! Maybe not bad to keep here in case someone else does the same thing
