### ISSUE TITLE
rollback is not working in database transactions 

### ISSUE THREAD

**Issue by ravishankarsrrav** [go-gorm/gorm#2603]
**go version go1.12.7 windows/amd64**
````
        // open database connection
	instance, err := db.GetDB().GetConnection()
	if err != nil {
		return err
	}
	// database transaction begin
	tx := instance.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// return if it is error
	if err := tx.Error; err != nil {
		return err
	}
	log.Println(tx)

	err = tx.Create(&common.Namespace{
		Status: "Active",
		Name:   "rav",
	}).Error
	if err != nil {
		tx.Rollback()
		return err
	}
	err = tx.Create(&common.Namespace{
		Status: "Active",
		Name:   "rav",
	}).Error
	if err != nil {
		tx.Rollback()
		return err
	}
	// commit the transaction
	return tx.Commit().Error
````

**Comment by ravishankarsrrav** [comment]
// open database connection
	instance, err := db.GetDB().GetConnection()
	if err != nil {
		return err
	}
	// database transaction begin
	tx := instance.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// return if it is error
	if err := tx.Error; err != nil {
		return err
	}
	log.Println(tx)

	err = tx.Create(&common.Namespace{
		Status: "Active",
		Name:   "rav",
	}).Error
	if err != nil {
		tx.RollbackUnlessCommitted()
		return err
	}
	err = tx.Create(&common.Namespace{
		Status: "Active",
		Name:   "rav",
	}).Error
	if err != nil {
		tx.RollbackUnlessCommitted()
		return err
	}
	// commit the transaction
	return tx.Commit().Error

**Comment by lyfunny** [comment]
i meet the same issue
