### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by mcandre** [go-gorm/gorm#2629]
Hi,

I am currently using upper.io as my ORM for Go projects. However, I occasionally experience MySQL server disconnects around a workload of 100K record insertions over 30 seconds, and would like to know if gORM would perform better. Could gORM produce benchmarks for reliable operations on the order of 1MTPS?

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/issues/3055
