### ISSUE TITLE
Enable sqlite3 extensions

### ISSUE THREAD

**Issue by navono** [go-gorm/gorm#2638]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
> go version go1.12.9 windows/amd64

### Which database and its version are you using?
> gorm v1.9.10

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

I want to enable `sqlite_userauth` in sqlite3, and the default registed `sqlite3` in `gorm` does not supported(empty extensions). So I try to register `sqlite3_with_extensions` with `sqlite_userauth` extension.

```go
package main

import (
	"github.com/jinzhu/gorm"
	"database/sql"
	"github.com/mattn/go-sqlite3"
)

var db *gorm.DB

func main() {
	sql.Register("sqlite3_with_extensions", &sqlite3.SQLiteDriver{
		Extensions: []string{
			"sqlite_userauth",
		},
	})

	db, err = gorm.Open("sqlite3_with_extensions",
		fmt.Sprintf("config.db?_auth&_auth_user=%s&_auth_pass=%s&_auth_crypt=sha256", "admin", "123456"))

	db.DB().SetMaxIdleConns(3)
	db.LogMode(true)
}
```

But `gorm` seems not support this initialized sqlite, it throw:
> `sqlite3_with_extensions` is not officially supported, running under compatibility mode.

How can I use extensions in gorm?

**Comment by lVlayhem** [comment]
Maybe 

> db, err = gorm.Open("sqlite3", "sqlite3_with_extensions",
		fmt.Sprintf("config.db?_auth&_auth_user=%s&_auth_pass=%s&_auth_crypt=sha256", "admin", "123456"))
