### ISSUE TITLE
Default values override assigned values

### ISSUE THREAD

**Issue by PaulSonOfLars** [go-gorm/gorm#2645]
### What version of Go are you using (`go version`)?
1.12.9

### Which database and its version are you using?
postgresql 11.3

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type TestStruct struct {
	gorm.Model
	Text string
	BooleanValue bool `gorm:"default:true"`
}

func main() {
	db.AutoMigrate(&TestStruct{})
	if db.Error != nil {
		panic(err)
	}

        text := "test string"

        // Check database for item with text "test string". If it doesnt exist, create a new one. Assign boolean value "false" to BooleanValue field.
        err := db.Where(TestStruct{Text: text}).Assign(map[string]interface{}{"text": text, "boolean_value": false}).FirstOrCreate(&TestStruct{}).Error
         if err != nil {
               panic(err)
         }

        var value TestStruct
         value, db.First(&value, "text = ?", text).Error

         // expected: BooleanValue has been set to 'false'
         // result: BooleanValue is left at default value 'true'
	if value.BooleanValue {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```

When using default values, gorm uses the default value over the assigned value.
The above example expects the BooleanValue field to be set to false, but instead is found to be true.

**Comment by PaulSonOfLars** [comment]
Related issue: https://github.com/jinzhu/gorm/issues/1607
Is there no way to force the update of go "nil" values, even using maps? I thought maps were meant to be the workaround for structs being unable to distinguish between default and specified values. And given it works as expected on a row update, but not on creation, this seems like strange behaviour.

It's worth noting this issue only happens when the row does NOT exist before execution; running this a second time updates the BooleanValue field as expected

**Comment by MyYellowBlanket** [comment]
The map didn't. It seems the assigned value by `.Assign` is only used for updating the matched records when using `Assign` with `FirstOrCreate`. 

```go
// https://github.com/jinzhu/gorm/blob/v1.9.12/main.go#L424-L437
func (s *DB) FirstOrCreate(out interface{}, where ...interface{}) *DB {
	c := s.clone()
	if result := s.First(out, where...); result.Error != nil {
		if !result.RecordNotFound() {
			return result
		}
		return c.NewScope(out).inlineCondition(where...).initialize().callCallbacks(c.parent.callbacks.creates).db
	} else if len(c.search.assignAttrs) > 0 {
		return c.NewScope(out).InstanceSet("gorm:update_interface", c.search.assignAttrs).callCallbacks(c.parent.callbacks.updates).db
	}
	return c
}
```
