### ISSUE TITLE
Preload function generates query with duplicated keys.

### ISSUE THREAD

**Issue by victorKochkarev** [go-gorm/gorm#2648]
If there are multiple entities with the reference to the same entity, Preload function is generating SQL query with duplicated keys.
Here is an example:
```
SELECT * FROM `market`  WHERE (`id` IN (193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193))
```

**Comment by mewis** [comment]
I am also experiencing this.
I have version 1.9.13

`gormDb.Preload("Interest").Find(&leadInterests)` results in
`SELECT * FROM `interests`  WHERE (`id` IN (5,3,1,1,4,3,2,2,4,4,3,2,3,3,2,4,2,3,3,5,3,5,3,5,4,1,3,4,5,5,5,5,1,3,5,2,4,4,4,3,3,2,1,2,3,4,2,2,1,5,3,2,1,1,2,1,5,2,4,4,4,2,4,2,5,3,2,3,4,3,1,3,2,2,2,3,1,2,5,5,4,1,3,4,4,4,4,5,5,2,2,1,4,1,5,2,5,2,1,5,2,4,3,2,3,2,5,4,4,5,4,2,5,2,5,5,4,2,1,2,4,4,5,3,5,4,1,2,1,5,4,2,1,4,1,4,5,5,1,2,1,3,2,1,5,5,1,2,1,5,2,5,4,4,3,5,4,4,5,3,5,1,1,5,1,2,3,1,5,1,1,4,4,2,5,3,2,1,3,3,2,2,4,1,4,5,4,5,3,4,2,3,4,2,4,2,5,2,3,2,5,1,3,1,2,4,5,2,4,3,5,4,3,5,1,3,2,1,3,3,5,4,2,3,1,4,4,3,1,1,3,3,3,4,2,2,4,2,3,1,1,2,1,3,2,2,5,4,1,5,5,4,2,5,4,1,1,4,1,4,2,2,1,1,5,5,1,3,4,2,4,4,4,1,2,3,1,2,5,5,3,3,4,5,4,3,3,1,1,1,2,1,1,2,4,2,5,3,4,1,3,2,3,2,4,1,5,5,5,5,2,1,4,5,4))`

This becomes un usable very quickly as I run out of placeholders.

I looked into the solution above but wee that `h := fmt.Sprint(result...)` is always unique.
