### ISSUE TITLE
Create()时grom会多调一次select

### ISSUE THREAD

**Issue by wangyxcv** [go-gorm/gorm#2651]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go1.12.6 windows/amd64

### Which database and its version are you using?
mysql  Ver 14.14 Distrib 5.7.26, for Win64 (x86_64)

开了gorm.debug()看到的sql语句
![image](https://user-images.githubusercontent.com/33677023/64422977-ecbf0b00-d0d7-11e9-8811-ac847fdbd0e2.png)
我的代码
![image](https://user-images.githubusercontent.com/33677023/64419911-8682ba00-d0d0-11e9-82e8-08f82cbae279.png)
我的表结构
![image](https://user-images.githubusercontent.com/33677023/64419939-95696c80-d0d0-11e9-844f-fadbdf4a534f.png)

153行就只有一条create语句，但是多了一条SELECT "id" FROM "file_part_records"记录，非常耗时，这是bug吗？我要如何避免？

我写了个demo，也有相同问题
```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

type User struct {
	ID      uint32 `gorm:"AUTO_INCREMENT"`
	Name string
	Test string
	Test2 string
}
func init() {
	db, _ = gorm.Open("sqlite3", "test.db")
	if !db.HasTable(&User{}) {
		db.CreateTable(&User{})
	}

}

func main() {
	testUser := User{Name:"aaa",Test:"test"}
	err := db.Debug().Create(&testUser).Error
	fmt.Println(err)
}
```
程序结果：
![image](https://user-images.githubusercontent.com/33677023/64422911-c8fbc500-d0d7-11e9-9137-09277e629f9c.png)

**Comment by SoulSu** [comment]
把 ID 的 tag 改成 `gorm:"primary"` 就不会再查询了。
