### ISSUE TITLE
how can one preview migrations without running them?

### ISSUE THREAD

**Issue by zallarak** [go-gorm/gorm#2660]
I thought log mode would just log queries. Instead it runs and logs the query. Is there a way to just log a query? The main use case would be previewing migrations before running them.

### What version of Go are you using (`go version`)?
go1.12.7 linux/amd64

### Which database and its version are you using?
postgresql 9

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Ideally, this only logs and doesn't actually run the migrations.

```go
package main

import (
        "github.com/username/project/module"
)

// Ideally, this only logs and doesn't actually run the migrations.
func EchoMigrate() {
        db.Db.LogMode(true)
        db.Db.AutoMigrate(&User{}, &Dog{})
        db.Db.LogMode(false)
}

```

**Comment by zaneli** [comment]
PostgreSQL seems to be able to roll back DDL.
I haven't actually tried this, but maybe works fine.
```go
tx := db.Begin()
tx.AutoMigrate(&User{}, &Dog{})
tx.Rollback()
```

On MySQL or so on will not work because of not supported roll back DDL.
