### ISSUE TITLE
Using db.First() with MYSQL generates wrong SQL syntax

### ISSUE THREAD

**Issue by sidagrawal** [go-gorm/gorm#2665]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.
I receive 
```Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Key = ?) ORDER BY `some_table`.`key` ASC LIMIT 1' at line 1```
when I try to use the First method to get a table record in MYSQL. This works just fine when using SQLite.

### What version of Go are you using (`go version`)?
go version go1.12.5 linux/amd64

### Which database and its version are you using?
mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64)

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"time"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

type SomeTable struct {
	Key       string `gorm:"PRIMARY_KEY"`
	Value     string
	UpdatedAt time.Time
}

func main() {
	var err error

	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")

	if err != nil {
		panic(err)
	}
	db.LogMode(true)
	db = db.AutoMigrate(SomeTable{})
	insertRecord := SomeTable{Key: "some key", Value: "some value", UpdatedAt: time.Now()}
	db.Create(&insertRecord)
	var record SomeTable
	err = db.First(&record, "Key = ?", "some key").Error
}
```

**Comment by zaneli** [comment]
`Key` is reserved words in  MySQL.
https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-K

**Comment by icearith** [comment]
> `Key` is reserved words in MySQL.
> https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-K

you save me in the pool

**Comment by yoadwo** [comment]
I had the same issue, #2469. TLDR:
I think that while GORM may want to encourage us not to use reserved words in our db schemas, it is sometimes just not up to the current developer to decide; it should therefore allow wrapping of column names by backticks. btw it is already implemented in the mssql driver..
