### ISSUE TITLE
`Table and Where` sql is not predicted

### ISSUE THREAD

**Issue by zhyq0826** [go-gorm/gorm#2678]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.12

### Which database and its version are you using?

5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

DB.Table("domain").Where(2).Update(Domain{Name: "name"}) -->  UPDATE `domain` SET `name` = 'name'  WHERE (`domain`.`` = 2)

**Comment by TestMsr** [comment]
in where clause it should be  .Where("domain=?",2)
