### ISSUE TITLE
Database does not save

### ISSUE THREAD

**Issue by deeprobin** [go-gorm/gorm#2683]
With this function i want to save my "Entry": https://github.com/DeepRobin/thunderbin/blob/master/main.go#L25

BeforeCreate will be also called. 
But there are no changes in my database. And also no errors.

**Comment by zaneli** [comment]
Did an error occur in `db.Begin()` or `tx.Commit()`?
http://gorm.io/docs/transactions.html

```go
func CreateEntry(db *gorm.DB, content string) *Entry {
	entry := &Entry{Content: content}
	tx := db.Begin()
	if err := tx.Error; err != nil {
		// handle error
	}

	...

	if err := tx.Commit().Error; err != nil {
		// handle error
	}
	return entry
}
```

**Comment by DeepRobin** [comment]
There is no error :/ (the function does not end)

**Comment by zaneli** [comment]
> (the function does not end)

Hmm...?

Will it succeed when without transaction?
```go
func CreateEntry(db *gorm.DB, content string) *Entry {
	entry := &Entry{Content: content}
	if err := db.Create(entry).Error; err != nil {
		panic(err)
		return nil
	}
	return entry
}
```

Will it succeed on using cli directly?
```sql
START TRANSACTION;
INSERT INTO `entries` (`content`) VALUES ('content');
COMMIT;
```
