### ISSUE TITLE
Enhancement: Asynchronous operations

### ISSUE THREAD

**Issue by mcandre** [go-gorm/gorm#2684]
Hi,

My application's needs would be better served with options for asynchronous queries. For example, I want to confirm that a `TRUNCATE` query has been received by the database, without blocking for the full 3-5 seconds that the query takes to complete.

**Comment by ilearnio** [comment]
This should be reopened. As with a release of v2 (well it's actually 1.20.0) gorm still doesn't support async / non-blocking operations. And nobody is talking about it on the entire internet. WTF, this is a terrible design approach!
