### ISSUE TITLE
Documentation for querying based on nested associations

### ISSUE THREAD

**Issue by Gradecak** [go-gorm/gorm#2686]
### What version of Go are you using (`go version`)?
1.12

### Which database and its version are you using?
mysql 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

The documentation isn't to clear when it comes to querying by nested associations. For example, consider following structure. 
```go
// User has one Profile and belongs to many Institutions
type User struct {
  ID uint
  Institutions []*Institution `gorm:"many2many:institution_users"`
  Profile *Profile `gorm:"foreignkey:id"`
}

// Institution has many Users
type Institution struct {
  ID uint
  Users []*User `gorm:"many2many:institution_users;foreignkey:id;"`
}

type Profile struct {
   ID uint
   Name string
}
```

How would you generate a query that fetches all `Users` in an `Institution` where `Profile.Name`  = `"jinzhu"`?

My current approach is to make a query, using nested preloads, and then using a for-loop filter out all instances of User where Profile preload fails. eg

```go
//make query
db.Model(&Institution{ID:3}).
     Preload("Users").
     Preload("Users.Profile", &Profile{Name:"jinzhu"}).
     Find(institution)

//filter accounts where Preload("Users.Profile") failed
for _, u := range institution.Users{
  if  u.Profile != nil {
    x = append(x, u)
  }
}

```
However, this seems like a very inefficient way of executing this query. Is this a limitation of using Selects on Preload instead of Joins, or is it a case of missing documentation for how to carry out such a query?

**Comment by qmn1711** [comment]
I've the same situation with you. Filtering on go is very inefficient way with large data

**Comment by MurtadhaS** [comment]
Anyone has any idea of how to do this right?

**Comment by GiancarlosIO** [comment]
😢
