### ISSUE TITLE
[Question] Any way to use ROW_NUMBER() with ORM queries?

### ISSUE THREAD

**Issue by shackra** [go-gorm/gorm#2688]
I have the following raw query which comes helpful for pagination:

```
var QuerySubs = `SELECT * FROM (SELECT
 ROW_NUMBER() OVER (ORDER BY created_at DESC) AS
   RowNum, *
   FROM mytable) AS RowConstrainResult
  WHERE RowNum > ?
  AND RowNum <= ?
  ORDER BY RowNum;`
```
Now, I don't know a lot about SQL but I cannot figure a way to translate my raw query into an ORM query, the reason for this is that it would be cleaner and more palatable in case of needing to modify the query to use on other table. The bit I think Gorm is missing is `ROW_NUMBER() OVER`, not sure if with the current API available the query can be translated or not.

**Comment by go-sk** [comment]
me too
