### ISSUE TITLE
How to use sql NOW() as default value for the column when db.Create() using struct

### ISSUE THREAD

**Issue by badoet** [go-gorm/gorm#269]
How to use sql NOW() as default value for the column when db.Create() using struct

**Comment by miparker** [comment]
This works for me:

TimeCreated   time.Time `gorm:"default:CURRENT_TIMESTAMP"`

**Comment by franklingu** [comment]
how about ON UPDATE CURRENT_TIMESTAMP?

**Comment by andrey-bobryshev-90poe** [comment]
@franklingu you can use `BeforeSave` hook for that https://gorm.io/docs/hooks.html
