### ISSUE TITLE
Extra where 1 <> 1 in many2many

### ISSUE THREAD

**Issue by kalelc** [go-gorm/gorm#2693]
I have two models (structs). `User` and `Group`. Those models have many to many relationships.

When I try to create query `db.Unscoped().Model(&group).Related(&users, "Users")` this returns:

`SELECT users.* FROM users INNER JOIN user_groups ON user_groups.owner_id = users.id WHERE (1 <> 1)`.

The entities are:

```
type Group struct {
	gorm.Model
	ID    uint   `json:"id"`
	Name  string `json:"name"`
	Users []User `gorm:"many2many:user_groups;association_jointable_foreignkey:owner_id"`
}
```

```
type User struct {
...
Groups                    []Group `gorm:"many2many:user_groups;association_jointable_foreignkey:group_id"`
}

```

Handler

```
users := []models.User{}
group := models.Group{}

db.Unscoped().Model(&group).Related(&users, "Users")

```

I don't know the reason because the query includes `WHERE (1 <> 1)`.

Regards.

**Comment by nuclearthinker** [comment]
hi @kalelc, is this bug resolved?

I get similar bug, it is very confusing. please suggest the solution if you already got the solution.
thanks.

**Comment by kalelc** [comment]
Hello @nuclearthinker 

The bug has not resolved, I have fixed the problem removing `gorm.Model` from Group Struct:

```
type Group struct {
    ID    uint   `json:"id"`
    Name  string `json:"name"`
    Users []User `gorm:"many2many:user_groups;association_jointable_foreignkey:owner_id"`
}
```

Also, I have changed the query in handler to `db.Model(&group).Related(&users)`

Regards.
