### ISSUE TITLE
gorm return results after sqlite db file is deleted from disk

### ISSUE THREAD

**Issue by iamthadiyan** [go-gorm/gorm#2695]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.11.2 linux/amd64

### Which database and its version are you using?
github.com/mattn/go-sqlite3, version 1.10.0

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
Code used to open DB :
`DB, err = gorm.Open("sqlite3", "file.db")`

When application (API server) is running, queries are working correctly. But then I deleted the DB file `file.db` from the disk. When I issued the next request, I was expecting gorm to fail the query saying that db file not found. But from gorm logs, I can see that the queries are succeeding as before.

Why is this so?

**Comment by aneeskA** [comment]
I figured out the reason. This is nothing to do with gorm or sqlite options. But to do with linux file system. When a file is deleted, the file handle is still active and reads happen as usual. The file is deleted only after all open handles are closed.
