### ISSUE TITLE
Save nested Structs as Postgres JSONB

### ISSUE THREAD

**Issue by ilzheev** [go-gorm/gorm#2704]
### What version of Go are you using (`go version`)?
`go version go1.13 darwin/amd64`

### Which database and its version are you using?
PostgreSQL 11.5

**transaction.go**
```golang
type FTransaction struct {
	TxID        string                `json:"txId" gorm:"primary_key;unique;not null"`
	Inputs      []*InputOutput `json:"inputs"`
	Outputs     []*InputOutput `json:"outputs"`
}

type InputOutput struct {
	Address     string `json:"address"`
	Amount      int64  `json:"amount"`
}
```

**Database**
```sql
CREATE TABLE f_transactions(
    tx_id VARCHAR(64) UNIQUE NOT NULL,
    inputs JSONB,
    outputs JSONB,
    CONSTRAINT f_transactions_tx_id_key PRIMARY KEY(tx_id)
);
```

**db.go**
```golang
func (c *Context) CreateFTransaction(ftx *model.FTransaction) error {

	if err := c.db.FirstOrCreate(&ftx).Error; err != nil {
		return err
	}
	return nil

}
```

**What works:**
– Database entry created

**What doesn't work:**
– `inputs` & `outputs` fields are saved as `NULL`

**Question:**
I want to store inputs & outputs of transaction as JSONB fields into Postgres DB.
Is it possible with GORM?

I tried `gorm:"json"`, `sql:"json"`, `sql:"json"` – no success.

Will be appreciated for help.
Thank you!

**Comment by pyzworld** [comment]
me too~

**Comment by sswanv** [comment]
You can implement the interface `driver.Valuer` to convert the structure to the value actually stored in the database, and implement the interface` driver.Scanner` to read the database value into the structure.
For gorm, implementing `driver.Scanner` is the only way to mark fields of type struct as normal, of course, except for the built-in type` time.Time`.

```golang
type InputOutputs []*InputOutput

func (j InputOutputs) Value() (driver.Value, error) {
	content, err := json.Marshal(j)
	if err != nil {
		return nil, err
	}
	return content, err
}

func (j *InputOutputs) Scan(value interface{}) error {
	if value == nil {
		*j = nil
		return nil
	}
	s, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("Invalid Scan Source")
	}
	if err := json.Unmarshal(s, j); err != nil {
		return err
	}
	return nil
}
```

gorm related source code can be found here: [➡️](https://github.com/jinzhu/gorm/blob/master/model_struct.go#L222-L234)

**Comment by bumberboy** [comment]
@sswanv do you use any gorm tags with that?

**Comment by Freeaqingme** [comment]
@bumberboy no, no tags required for @sswanv's solution.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/datatypes
