### ISSUE TITLE
Multiple primary key bugs

### ISSUE THREAD

**Issue by q2000f** [go-gorm/gorm#2705]
I define struct and use AutoMigrate create table but find error "Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key"
```
type Item struct {
	ID    uint64 `gorm:"column:ID;primary_key"`
	PlayerID uint64 `gorm:"column:PlayerID;primary_key"`
	Class  uint32 `gorm:"column:Class"`
	Num   uint64 `gorm:"column:Num"`
}

err := db.AutoMigrate(&Item{}).Error
if err != nil {
       log.Println(err)
}
```
I check log and found **ID** and **PlayerID** define AUTO_INCREMENT:
CREATE TABLE `TableItem` (`ID` bigint unsigned **AUTO_INCREMENT**,`PlayerID` bigint unsigned **AUTO_INCREMENT**,`Class` int unsigned,`Num` bigint unsigned , PRIMARY KEY (`ID`,`PlayerID`))

**Comment by Lilahamstern** [comment]
@q2000f You can only have one PK key per table. If you want other columns to be unique you will need to add that attribute to it.

To get playerID unique and auto_incremented you need to remove primary_key and add unique;auto_increment. See example below: 
`
type Item struct {
	ID    uint64 `gorm:"column:id;primary_key"`
	PlayerID uint64 `gorm:"column:player_id;unique;auto_increment"`
	Class  uint32 `gorm:"column:class"`
	Num   uint64 `gorm:"column:num"`
}
`
