### ISSUE TITLE
Please help answer a question

### ISSUE THREAD

**Issue by fifsky** [go-gorm/gorm#2707]
https://github.com/jinzhu/gorm/blob/1bca5dbdd9e8913c2fb825f2d824ed6b0435c65d/main.go#L536

In this line of code, tx itself implements the SQLCommon interface, so why force it to an interface and then assert?

```
// This will not result in an error
c.db = tx
```

Hope you can answer my doubts, thank you!

**Comment by ppacher** [comment]
Because it just doesn't work if tx is a non-interface type already.
https://play.golang.org/p/V-NjpgQNFEn

Try to run that one and it will error with 
```
./prog.go:36:7: invalid type assertion: a.(Stringer) (non-interface type A on left)
```
even though `a` implements the interface.
