### ISSUE TITLE
是否有相应方法，只打印sql，不执行数据库操作

### ISSUE THREAD

**Issue by anotherGoogleFan** [go-gorm/gorm#2708]
如题。

需求可能有点奇怪，如下：
因为程序执行导入数据过慢，所以想仅仅使用gorm打印出要执行的语句，而不要实际执行。
然后通过mysql load file的方式将打印出的sql语句直接用数据库执行。

**Comment by ya0yy** [comment]
这个感觉可以跟进源码断点调试，因为打印sql和执行sql肯定不是同一行代码

**Comment by lrita** [comment]
自定义一种 [`SQLCommon`](https://github.com/jinzhu/gorm/blob/179760d8343ed15cbb9f071ca824bc35ee7784bb/interface.go#L9-L14) 即可，gorm会将`SQLCommon`交给执行，届时你就获得对应的sql
