### ISSUE TITLE
belongs to problem

### ISSUE THREAD

**Issue by xxjwxc** [go-gorm/gorm#2710]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
v1.12

### Which database and its version are you using?
master

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

i user demo on(https://gorm.io/docs/belongs_to.html#Foreign-Key) user "Foreign Key" it not work 
code write.

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	 db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type User struct {
	gorm.Model
	Name string
}

type Profile struct {
	gorm.Model
	Name      string
	User      User `gorm:"foreignkey:UserRefer"` // 使用 UserRefer 作为外键
	UserRefer uint
}

func main() {
	var p Profile
	orm.Find(&p)
	orm.Model(&p).Related(&p.User) // but i use: orm.Model(&p).Related(&p.User,"UserRefer") it work int 
	fmt.Println(p)
}
```
and get the err:
invalid association []

**Comment by xxjwxc** [comment]
and "Association ForeignKey" has the same problem

**Comment by xxjwxc** [comment]
and  i try has one "Association ForeignKey" . the same problem

https://gorm.io/docs/has_one.html#Association-ForeignKey

**Comment by rhugga** [comment]
Did you ever figure this out? I can't get any form of ForeignKey working. Tried every possible relationship type with very basic, dumbed down examples.

**Comment by xxjwxc** [comment]
Not yet，can use the default way

**Comment by qqaimh** [comment]
me too

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt
i'm woking to this tools . so need to using

**Comment by suxinmian** [comment]
如果不是看到这个issue,我想我今晚都睡不着，一直在想为什么这个简单的官方例子都我走不通，而且在官方文档，百度，google都没有提出问题，真不可以思议，原来还真是个bug
