### ISSUE TITLE
Bug with gorm tags

### ISSUE THREAD

**Issue by MasterchiefCC** [go-gorm/gorm#2718]
type Users struct {
	ID          int       `gorm:"primary_key;auto_increment;column:id;type:int(10) unsigned;not null" json:"id"`
}
when I declear a model with type and auto increment, the auto increment not going to add on create table.

CREATE TABLE `tbUsers` (
  `id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

**Comment by sirius1024** [comment]
try put auto_increment after type:int(10);
```go
type Users struct {
    ID int gorm:"primary_key;column:id;type:int(10);auto_increment;unsigned;not null" json:"id"
}
```
