### ISSUE TITLE
如何实现访问器 getter？

### ISSUE THREAD

**Issue by imageslr** [go-gorm/gorm#2723]
你好，我想请问如何实现访问器？比如我现在有一个用户模型 User，它有一个一对多关系 Books。我希望在 User 的结构体中增加一个 `book_numbers` 字段，表示 Books 的数量：

```go
type User struct {
  Name string `json:"name"`
  Books []Book `json:"books"`
  BookNumbers int `json:"book_numbers"`
}
```

我希望 BookNumbers 字段能在 User 被转为 JSON 的时候**自动**算出来，就好像 [Eloquent的访问器](https://xueyuanjun.com/post/8213)一样。比如我可以定义一个这样的方法：
```go
func (u *User) getBookNumbers() int {
  return len(u.Books)
}
```

我现在的做法是每个 User 实例都单独为其设置 `BookNumbers`，这个工作挺麻烦的。不知道有没有其他优雅的方式实现？

我知道 gorm 提供一个 Scanner 和 Valuer 接口，可以设置某个字段为 JSON 格式。这个也算是我理解的“修改器 Setter”和“访问器 Getter”了。

**Comment by ipfans** [comment]
实现`json.Marshaler`接口

**Comment by imageslr** [comment]
感谢，我会去试一试
