### ISSUE TITLE
[request] Map model to table name

### ISSUE THREAD

**Issue by akamensky** [go-gorm/gorm#2727]
### What version of Go are you using (`go version`)?
1.13.3

### Which database and its version are you using?
Postgresql

### Info

Currently a model is hardwired into a single table with a specific name. That is fairly often not the case with many applications, i.e. in my use case I dynamically create tables which ALL have the same structure. It would make a lot of sense to have ability to create models manually by providing struct and table name.

Right now I have to resort to using raw sql for that data and manually scan values into struct, which is quite painful.

**Comment by xs23933** [comment]
```go
type Abc struct {
   // Same field
   Name string `gorm:"size:64" json:"name"`
   // Different fields
   OtherField string `gorm:"-" json:"some"` 
   OtherField2 string `gorm:"-" json:"some2" ` // custom table store filed . 
}

abc := new(Abc)
// use  Table custom set u table
DB.Table("customTable").Where("some").Find(&abc)

```
