### ISSUE TITLE
gorm association_autoupdate:false

### ISSUE THREAD

**Issue by hlbj510** [go-gorm/gorm#2731]
i used db.set("gorm:association_autoupdate",false).create(&user)  in my project
it did't work ,as well as db.set("gorm:association_autocreate",false).create(&user)
it always update/create association when i create an user.
can any body help me?

**Comment by tanweerdev** [comment]
This worked for me(dont tell gorm foreign key. it started magically updating language again if you add foreign key in the gorm tags)

`Language *language_schema.Language `gorm:"association_autoupdate:false;association_autocreate:false" json:"language,omitempty"``
