### ISSUE TITLE
How can i get the user id after i create/save it.

### ISSUE THREAD

**Issue by snowdream** [go-gorm/gorm#2732]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.12.5 darwin/amd64

### Which database and its version are you using?
pg

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go

// User User
type SafeUser struct {
	Model

	Mobile   string     `json:"mobile,omitempty" gorm:"not null;unique_index"`
	Username string     `json:"username,omitempty"`
	Roles    []string   `json:"roles" gorm:"type:text[]"`
	Avatar   string     `json:"avatar,omitempty"`
	Status   int        `json:"status" gorm:"SMALLINT"`
	Sex      int        `json:"sex" gorm:"SMALLINT"`
	Name     string     `json:"name,omitempty"`
	Nickname string     `json:"nickname,omitempty"`
	Birthday *time.Time `json:"birthday,omitempty"`
}

type User struct {
	*SafeUser
	Password string `json:"password"`
}



		var safeUser models.SafeUser
		safeUser.Mobile = data.Mobile

		user := models.User{SafeUser: &safeUser, Password: hash}
		err = servers.Db.Save(&user).Error
```

i need get the user id after save.

**Comment by aplsup** [comment]
Hi, you can do something like
`
saveResult := servers.Db.Save(&user)
saveResult.Value.(*models.User).ID // This is the generate id
`

**Comment by xs23933** [comment]
I usually use it like this
```go

type User struct {
   ID uint `gorm:"primary_key" `json:"id"`
   ...
}

func (m *User) Save() error {
   servers.Db.Save(m).Error
}

user := new(User)
if err := user.Save(); err != nil {
   process some error
}

log.Printf(user.ID) // Saved id

```
