### ISSUE TITLE
order by using related in has many relationship not working

### ISSUE THREAD

**Issue by abdulrehmank** [go-gorm/gorm#2736]
### What version of Go are you using (`go version`)?
go version go1.12.6 darwin/amd64

### Which database and its version are you using?
5.7.25 - MySQL Community Server

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

type User struct {
  gorm.Model
  CreditCards []CreditCard
}

type CreditCard struct {
  gorm.Model
  ExpiryDate
  Number   string
  UserID  uint
}

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	var user User
	var creditCards CreditCard
	db.Model(&user).Related(&creditCards).Order("expiry_date")
}
```
How can I get all credit cards sorted with expiry date of a user in case of HasMany Relationship?

**Comment by yushine** [comment]
Same question. Any answers?
