### ISSUE TITLE
many2many got UNIQUE fields in associated table

### ISSUE THREAD

**Issue by fishjar** [go-gorm/gorm#2747]
### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
type Base struct {
	ID        uuid.UUID  `json:"id" gorm:"primary_key;unique;not null"` // here is an 'unique'
}

type User struct {
    Base
    Name         string     `json:"name"`
    Roles        []*Role    `json:"roles" gorm:"many2many:user_role;"`
}

type Role struct {
    Base
    Name         string     `json:"name"`
}
```

Create table will executeing sql statements

```sql
CREATE TABLE "user_role" ("role_id" blob NOT NULL UNIQUE,"user_id" blob NOT NULL UNIQUE, PRIMARY KEY ("role_id","user_id"))
```
Should the `UNIQUE` be removed?

**Comment by ItsLeeOwen** [comment]
I've confirmed that the created join table inherits constraints defined on the source models, the UNIQUE constraint on the ID field gets carried over to the join table's column.  When removed the join table was no longer generated with UNIQUE constraints on it's column.
