### ISSUE TITLE
gorm怎么在struct的tag语句支持utf8mb4_general_ci？

### ISSUE THREAD

**Issue by thisloving** [go-gorm/gorm#2753]
我转换sql为struct
CREATE TABLE `t_change_name` (
	`index` INT(11) NOT NULL AUTO_INCREMENT,
	`old_name` CHAR(32) NOT NULL COLLATE 'utf8mb4_general_ci',
	`new_name` CHAR(32) NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`index`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=645
;

转换：
type t_change_name struct {
	Index int `gorm:"primary_key"` 
	OldName string `gorm:"column:old_name; type:char(32)"`	
	NewName  string `gorm:"column:new_name; type:char(32)"` 
}

请问各位，我在怎么在转化后的struct的tag中支持utf8mb4_general_ci？

**Comment by qicmsg** [comment]
```
// 为模型 `User` 创建表
db.CreateTable(&User{})

// 创建表时会追加 “ENGINE=InnoDB” 到 SQL 语句中。
db.Set("gorm:table_options", "ENGINE=utf8mb4_general_ci").CreateTable(&User{})

```
[官方文档,数据迁移](https://gorm.io/zh_CN/docs/migration.html)
