### ISSUE TITLE
ForeignKey relationships aren't being credited, no errors thrown.

### ISSUE THREAD

**Issue by rhugga** [go-gorm/gorm#2761]
### What version of Go are you using (`go version`)?
1.12.9

### Which database and its version are you using?
Mysql 8.0.13.

I've tried every approach to a foreign key relation in the docs and none of them work. The tables get created without errors but no foreign key relationships get created.

I am wanting a "has one" relationship.

```go
type Volumes struct {
	RowId            int64  `gorm:"type:bigint(20) unsigned auto_increment;primary_key"`
	Id                    string  `gorm:"type:varchar(40);unique;not null"`
	VirtualMachineID VirtualMachines `gorm:"foreignkey:VMID"`
	CreatedAt        time.Time
	DeletedAt        time.Time
	UpdatedAt      time.Time
}

type VirtualMachines struct {
	RowId       int64  `gorm:"type:bigint(20) unsigned auto_increment;primary_key"`
	Id          string `gorm:"type:varchar(40);unique;not null"`
	VMID        string `gorm:"type:varchar(40)"`
	CreatedAt   time.Time
	DeletedAt   time.Time
	UpdatedAt   time.Time
}
```

**Comment by moqmar** [comment]
The "foreignkey" field specifies in which field the primary key of the referenced row is being stored *in the same struct*:

```go
type Volumes struct {
	VirtualMachine VirtualMachines `gorm:"foreignkey:VirtualMachineID"`
	VirtualMachineID string
}
```

Also, it doesn't create a foreign key constraint in the database at all, that must unfortunately be done manually during setup:
```go
mydb.Model(&Volumes{}).AddForeignKey("virtual_machine_id", "virtual_machines(vmid)", "cascade", "cascade")
```

IMO, this is documented pretty poorly, and foreign keys should be created automatically in the database, but it seems to work if you figured that out. :)

**Comment by rhugga** [comment]
So you can only create a foreign key agains the primary key of the referenced table?

**Comment by moqmar** [comment]
That actually works, and is called an `Association ForeignKey`, you just have to use `gorm:"association_foreignkey:Id"` - also see http://gorm.io/docs/belongs_to.html#Association-ForeignKey.

The problem is that everything you described exists in Gorm, somewhere, somehow. It's IMO just that the tag names are not exactly intuitive, and the documentation is all over the place, and just not exhaustive enough for what it can do. The best thing is to just read & understand it completely, and to check the code for the rest. :neutral_face:

**Comment by rhugga** [comment]
I think I figured out my model. It gets created in mysql correctly. (I manually create my foreign keys). I need to right code to query some data and see if it's working as intended. Probably gonna wait till Monday and salvage my weekend.
