### ISSUE TITLE
Support MySQL 8, time type transformation 

### ISSUE THREAD

**Issue by niaiwomattt** [go-gorm/gorm#2770]
go version: 1.13
database: MySQL 8
issue:
1. support MySQL 8, time type transformation 
2. binary type gorm tag.
Similar
```json
UUID  `gorm: "type:binary:size(16)"` 
```

**Comment by xs23933** [comment]
id use binary search and index , low query. Not recommended， 
my project  UUID `gorm:"type:char(36)"`
