### ISSUE TITLE
db.Model((*Student)(nil)).Query(...)  panic, is it a bug?

### ISSUE THREAD

**Issue by sdghchj** [go-gorm/gorm#2773]
```
type Student struct{
    Name string
}

db.Model((*Student )(nil)).Query(...)   // panic reflect: call of reflect.Value.MethodByName on zero Value

```

I know the correct way is as 
```
db.Model(&Student{ }).Query(...)
```

But, I just want to get a table name from Student type, is there any need  to create an object and get it's address ?

I found [code https://github.com/jinzhu/gorm/blob/master/scope.go#L252](https://github.com/jinzhu/gorm/blob/master/scope.go#L252) here as :
```
func (scope *Scope) CallMethod(methodName string) {
	if scope.Value == nil {
		return
	}

	if indirectScopeValue := scope.IndirectValue(); indirectScopeValue.Kind() == reflect.Slice {
		for i := 0; i < indirectScopeValue.Len(); i++ {
			scope.callMethod(methodName, indirectScopeValue.Index(i))
		}
	} else {
		scope.callMethod(methodName, indirectScopeValue)
	}
}

func (scope *Scope) callMethod(methodName string, reflectValue reflect.Value) {
	// Only get address from non-pointer
	if reflectValue.CanAddr() && reflectValue.Kind() != reflect.Ptr {
		reflectValue = reflectValue.Addr()
	}

        // the following line panic 
	if methodValue := reflectValue.MethodByName(methodName); methodValue.IsValid() {
		...
		}
	}
}

```

I suggest correct the CallMethod function (only line 252) as following:
```
func (scope *Scope) CallMethod(methodName string) {
	if scope.Value == nil {
		return
	}

	if indirectScopeValue := scope.IndirectValue(); indirectScopeValue.Kind() == reflect.Slice {
		for i := 0; i < indirectScopeValue.Len(); i++ {
			scope.callMethod(methodName, indirectScopeValue.Index(i))
		}
	} else {
		scope.callMethod(methodName, reflect.ValueOf(scope.Value))
	}
}
```

**Comment by imdatngo** [comment]
There is a simple way to get the table name from your struct:
```golang
tableName := db.NewScope(&Student{}).TableName()
```

What is the `Query()` though?

**Comment by sdghchj** [comment]
> There is a simple way to get the table name from your struct:
> 
> ```go
> tableName := db.NewScope(&Student{}).TableName()
> ```
> 
> What is the `Query()` though?

sorry,I mean NewScore() just want to get a table name from its argument,there is no need to create a object.

**Comment by imdatngo** [comment]
Then it's not possible I think.

Just curious, what is your use-case with that? It seems odd to me... are you just trying to avoid creating new instance of Student? c'mon, it's not that bad creating such a small one :D

**Comment by sdghchj** [comment]
@imdatngo 
why not possible?
Yes, I am just trying to avoid creating new instance, and Stuent is just an example I give. In many actual cases, ORM objects are not as simple as Student here. is it really not too bad in go? Maybe.  I was a c++er before.
