### ISSUE TITLE
Is anyone using this with Mysql? Pulling our hair out.

### ISSUE THREAD

**Issue by rhugga** [go-gorm/gorm#2790]
I just want to know if anyone here is successfully using this with Mysql 8 and using foreign keys? We have tried till we are blue in the face to get this working and we can't. gorm complains we are violating the fkey constraint yet the SQL works perfectly fine outside of gorm.

Way too much code to post, way too many permutations to list here. Just wanna know if we need to cut our losses and move on or if anyone can confirm this works with mysql.

**Comment by wdepril** [comment]
Hi rhugga.  We are using gorm successfully with mysql 8.0.16 including foreign keys/indexes/functions
