### ISSUE TITLE
Is this a bug ?

### ISSUE THREAD

**Issue by YangKian** [go-gorm/gorm#2796]
### What version of Go are you using (`go version`)?

go 1.13

### Which database and its version are you using?

Mysql 8.0

```go
//here is my struct
type Task struct {
    Id int
    Book string
    CreateTime time.Time `gorm:"column:create_time"`
}

func SelectTasks(start, end time.Time) []time.Time {
	var tasks []time.Time

	res := db.Table("task").Where("create_time BETWEEN ? AND ?", start, end).Pluck("DISTINCT(create_time) ", &tasks)

	if res.RecordNotFound() {
		log.Println("get RecordNotFound err")
	}
	log.Printf("SelectTasks find %d result", len(tasks))
	return tasks
}

func main() {

    ...
    //here omit the connection operation to mysql database
    
	start, _ := time.ParseInLocation("2006-01-02 15:04:05", "2019-11-25 00:00:00", time.Local)
	end, _ := time.ParseInLocation("2006-01-02 15:04:05", "2019-12-02 00:00:00", time.Local)
    
	res := models.SelectTasks(start, end)
    
	for _, v := range res {
		fmt.Println(v)
	}
}
```

I have create a table named `task`，When I use `Pluck` combined with `Where` to select the data in the time durations, I get the following result:

![image-20191206223701812](https://user-images.githubusercontent.com/45479280/70331524-95693c00-187a-11ea-8f51-fb5e154af0c5.png)

the number of `rows affected or returned` are wrong, I get five result, not zero.

And when I try to select data in a duration which not include in my database, the error detect also not work . Here is an example:

```go
func main() {

    ...
    //here omit the connection operation to mysql database
    
    //I modify the start and end time, and make sure there are no related data in my database
	start, _ := time.ParseInLocation("2006-01-02 15:04:05", "2019-12-25 00:00:00", time.Local)
	end, _ := time.ParseInLocation("2006-01-02 15:04:05", "2019-12-26 00:00:00", time.Local)
    
	res := SelectTasks(start, end)
    
	for _, v := range res {
		fmt.Println(v)
	}
}
```

The example should have to print `get RecordNotFound err`，but it not

![image-20191206224344155](https://user-images.githubusercontent.com/45479280/70331554-a3b75800-187a-11ea-9f8c-f6d1a5b541b5.png)

Are these conditions bugs?

**Comment by zaneli** [comment]
> When I use Pluck combined with Where to select the data in the time durations, I get the following result: ...

I think maybe a bug. I try to fix it. #2800. 

> The example should have to print `get RecordNotFound err`，but it not ...

No, It's a specification.
Please search on the issue track.
#228 #898

**Comment by YangKian** [comment]
> > When I use Pluck combined with Where to select the data in the time durations, I get the following result: ...
> 
> I think maybe a bug. I try to fix it. #2800.
> 
> > The example should have to print `get RecordNotFound err`，but it not ...
> 
> No, It's a specification.
> Please search on the issue track.
> #228 #898

Got it, thank you very much :)
