### ISSUE TITLE
我想了解table()和model()的不同，再问题中找到了一个历史，但是中文文档中似乎并没有找到描述

### ISSUE THREAD

**Issue by ruyi84** [go-gorm/gorm#2805]
对不起，因为英语实在不是很好使用了中文提问，对此很抱歉。
在历史中找到了
## 关于db.Model和db.Table
db.Table()参数为database表名，以此来操作数据
使用db.Model()前需要先将database表与struct结构关联起来，然后就可以使用struct对象操作数据

还有一个中文文档的地址，但是在里面并没有找到相关描述，是否是因为中文文档中没有相关说明

**Comment by sdghchj** [comment]
Table()仅仅是指定表名。
Model()通过传入的对象不仅可以确定表名，在建表时它也指定了各字段属性，在删、改、查时如果对象有id字段且不为空，则操作只针对以id值为主键值的对象。

**Comment by ruyi84** [comment]
> Table()仅仅是指定表名。
> Model()通过传入的对象不仅可以确定表名，在建表时它也指定了各字段属性，在删、改、查时如果对象有id字段且不为空，则操作只针对以id值为主键值的对象。

这几天我也看了一下，使用model（）是根据结构体去映射一样，如果存在gorm.model还会去添加deleted_at is null的条件

**Comment by sswanv** [comment]
具体的表名获取规则：[Here](https://github.com/jinzhu/gorm/blob/master/scope.go#L314-L328)

**Comment by xs23933** [comment]
简单来说， table 可以强制订制表、view等用只要 struct 有这些字段都可以强制指定到相关表上， 缺点是改结构体表名加 prefix 都不会同步


model 都优点上面兄弟说都很清楚了， 则可同步各种数据包括统一修改表名啥到

**Comment by jeckii** [comment]
Hey guys, I've found a issue. I can only use the Table.Scan to get the struct model. I dont konw the difference of these functions.

golang version is 1.12.9
mysql version is 8.0.18
the code is as shown below:

var user User

DB.Table("user"). Select("id,name,password"). Where("name = ?", name). Scan(&user) // successfull

DB.Take(&user, "name = ?", name) // all fields is null

DB.First(&user, "name = ?", name) // all fields is null

**Comment by jeckii** [comment]
Hey guys, I've found a issue. I can only use the Table.Scan to get the struct model. I dont konw the difference of these functions.

golang version is 1.12.9
mysql version is 8.0.18
the code is as shown below:

var user User

DB.Table("user"). Select("id,name,password"). Where("name = ?", name). Scan(&user) // successfull

DB.Take(&user, "name = ?", name) // all fields are null

DB.First(&user, "name = ?", name) // all fields are null

**Comment by sdghchj** [comment]
> Hey guys, I've found a issue. I can only use the Table.Scan to get the struct model. I dont konw the difference of these functions.
> 
> golang version is 1.12.9
> mysql version is 8.0.18
> the code is as shown below:
> 
> var user User
> 
> DB.Table("user"). Select("id,name,password"). Where("name = ?", name). Scan(&user) // successfull
> 
> DB.Take(&user, "name = ?", name) // all fields are null
> 
> DB.First(&user, "name = ?", name) // all fields are null

First you must set the table name:
```
DB.Table("user").Take(&user, "name = ?", name) 
DB.Table("user").First(&user, "name = ?", name)
```

**Comment by jeckii** [comment]
> > Hey guys, I've found a issue. I can only use the Table.Scan to get the struct model. I dont konw the difference of these functions.
> > golang version is 1.12.9
> > mysql version is 8.0.18
> > the code is as shown below:
> > var user User
> > DB.Table("user"). Select("id,name,password"). Where("name = ?", name). Scan(&user) // successfull
> > DB.Take(&user, "name = ?", name) // all fields are null
> > DB.First(&user, "name = ?", name) // all fields are null
> 
> First you must set the table name:
> 
> ```
> DB.Table("user").Take(&user, "name = ?", name) 
> DB.Table("user").First(&user, "name = ?", name)
> ```

I tried to do it. But that doesn't work. I think the problem is the mapping of  the model. Because SQL on the log is no problem, and log shows "1 rows affected or returned".

**Comment by jeckii** [comment]
Thanks guys, I've found out the cause of the problem. Because of the field name is upper case in my database. But the convention of gorm is that the names of columns should be lower case if I use the model instead of table.  I am so sorry i ignore it when i used the framework @sdghchj.
