### ISSUE TITLE
出现大量time_wait问题

### ISSUE THREAD

**Issue by ONG-YA** [go-gorm/gorm#2809]
var db    *gorm.DB

func init() {
	if db != nil {
		return
	}
	var err error
	if db, err = gorm.Open(conf.DbDriverName, conf.DbUserName+":"+conf.DbPwd+conf.DbUrl); db == nil || err != nil {
		msg := fmt.Sprintf("init_db_err\t%v", err)
		panic(msg)
	}
	db.SingularTable(true)
	db.LogMode(true)
	db.DB().SetMaxIdleConns(100)
	db.DB().SetMaxOpenConns(1000)
}

使用出现大量time_wait，看到客户端会不断的关闭连接，感觉是没有复用，请问是什么参数要设置或者是写法有误吗？

**Comment by Atevens** [comment]
同问，出现一样问题，大量sleep连接

**Comment by xjqxz2** [comment]
同问，服务已经因为该问题挂了好几次了！急需解决！

**Comment by Atevens** [comment]
> 同问，服务已经因为该问题挂了好几次了！急需解决！
可以看下事务是否存在未提交，查询语句里面rows.next(){}里面是否存在提前break位置，以及open连接只有一次，这几个方面看一下

**Comment by aixiaoxiang** [comment]
time_wait 出现在主动关闭链接的一方.

**Comment by aixiaoxiang** [comment]
对于SetMaxIdleConns 与  SetMaxOpenConns  

参考 https://github.com/go-sql-driver/mysql/issues/991

**Comment by bobohume** [comment]
对于SetMaxIdleConns 与 SetMaxOpenConns 设置下就好了，不过，mysql的长连接，默认有个timeout时间，假如，groutinue太多，会出现，很多groutine在等着mysql idle，会出现timeout时间一到，就报错了。尽量控制下mysql groutinue的数量。还有就是select一个超级大的表，没有索引，也会出现，尽量避免就好了
