### ISSUE TITLE
access old field and new values in AfterUpdate

### ISSUE THREAD

**Issue by ammmir** [go-gorm/gorm#2813]
I'd like to perform an action when updating a column value (e.g., updating an external resource with the new value) and need access to both old and new values. Is there a way to accomplish this within gorm?

```go
func (f *Foo) AfterUpdate(tx *gorm.DB) (err error) {
        oldValue := ??? // how to get this?
        newValue := f.Field
        return myapi.Something(oldValue, newValue)
}
```

**Comment by Pastel001** [comment]
gorm V2 just can get whether the column change or not，but how to get the old and new value？
thank you
