### ISSUE TITLE
 how to execute a stored procedure and capture its result  in mysql using GORM in golang

### ISSUE THREAD

**Issue by bhavyasree96** [go-gorm/gorm#2814]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.11
### Which database and its version are you using?
mysql

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	if /* failure condition */ {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```

**Comment by bhavyasree96** [comment]
when I tried using this:   
**err:= db.Find("exec [procedure_name] ?",input)**
it is throwing the following error:

**exec [procedure_name] ? unsupported destination, should be slice or struct**

**Comment by zaneli** [comment]
http://gorm.io/docs/sql_builder.html#Run-Raw-SQL

Please try to use `db.Raw("exec [procedure_name] ?", input).Scan(&result)`.

**Comment by kevinjrdan** [comment]
> 
> 
> http://gorm.io/docs/sql_builder.html#Run-Raw-SQL
> 
> Please try to use `db.Raw("exec [procedure_name] ?", input).Scan(&result)`.


I do the same thing. But i got a default output
{{0 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC <nil>}      false}

What else i can do?

**Comment by zaneli** [comment]
@kevinjrdan 
Please provide a complete code.

What is your `result` struct difinision?
What value do your procedure to return?
What value do you expect to bind?
Does an error have occurred?

```go
if err := db.Raw("exec [procedure_name] ?", input).Scan(&result).Error; err != nil {
  // check error
}
```

**Comment by zjjt** [comment]
Hi @zaneli i do have the same issue running 
`if err:=db.Raw(exec dbo.proc).Scan(&prod).Error;err!=nil{
return err
}`
The prod variable is a slice of *product which type product is a struct with Id string and Name string. The procédure when executed in sql server returns two columns Id and Name unfortunately when executing my code I get a runtime error nil pointer dereference. And I don’t seem to find where the issue is.Please help me

**Comment by zaneli** [comment]
@zjjt 

Sorry, I don't have SQL Server.
I tried MySQL.

* MySQL definition
```sql
mysql> create table users (id int, name varchar(256));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into users values (1, 'test');
Query OK, 1 row affected (0.00 sec)

mysql> select id, name from users where id = 1;
+------+------+
| id   | name |
+------+------+
|    1 | test |
+------+------+
1 row in set (0.00 sec)

mysql> create procedure test_procedure(IN target_id INT)
    -> select id, name from users where id = target_id;
Query OK, 0 rows affected (0.01 sec)

mysql> call test_procedure(1);
+------+------+
| id   | name |
+------+------+
|    1 | test |
+------+------+
1 row in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)
```

* Go code
```go
targetID := 1
var result struct {
	ID int
	Name string
}
if err := db.Raw("call test_procedure(?)", targetID).Scan(&result).Error; err != nil {
	return err
}
fmt.Printf("result: id=%d, name=%s\n", result.ID, result.Name)
```

* Execution result
```sh
[2020-05-17 13:16:32]  [3.20ms]   call test_procedure(1)
[1 rows affected or returned ]
result: id=1, name=test
```

It's works fine to me.

**Comment by stevenkitter** [comment]
@zaneli 
How can I `create procedure test_procedure` by gorm.

**Comment by zaneli** [comment]
@stevenkitter 
Why do you create by gorm?
I created by MySQL Command Line Client.

Maybe you can create using `db.Raw("...")`.
I have never tried it.

Anyway, please try it once for yourself.
