### ISSUE TITLE
how to get right rowsAffected when execute multi update sql

### ISSUE THREAD

**Issue by laijiawei** [go-gorm/gorm#2817]
sql = `update user set name='a' where id=1;
	  update user set name='b' where id=2;`

rowsAffected:=util.DB.Exec(sql).RowsAffected

after execute sql,the rowsAffected is 1

I want rowsAffected  is 2,how to do it?

**Comment by zaneli** [comment]
Maybe you must be done manually.
For example, execute another SQL.
```sql
select count(*) from user where id in (1, 2);
```
