### ISSUE TITLE
Is gorm operate table's column name directly?

### ISSUE THREAD

**Issue by wahello** [go-gorm/gorm#2818]
Like [this](http://gorm.io/docs/conventions.html#Specifying-The-Table-Name), 

```
type User struct {
  gorm.Model
  Name string
}
```
```
// Create `deleted_users` table with struct User's definition
db.Table("deleted_users").CreateTable(&User{})
var deleted_users []Userdb.Table("deleted_users").Find(&deleted_users)
//// SELECT * FROM deleted_users;
db.Table("deleted_users").Where("name = ?", "jinzhu").Delete()
//// DELETE FROM deleted_users WHERE name = 'jinzhu';

```
### The question is gorm is operate table's column name directly?  Like
`db.Table("deleted_users").Where("name = ?", "jinzhu").Delete()` the where clause `name = ?` 
if User struct defined like: 
```
type User struct {
  gorm.Model
  Name string `gorm:"column:n"`
}
```
### How to use Where clause? Which is right?
`db.Table("deleted_users").Where("name = ?", "jinzhu").Delete()` the where clause `name = ?` 
or 
`db.Table("deleted_users").Where("n = ?", "jinzhu").Delete()` the where clause ` n = ?`

**Comment by zaneli** [comment]
That doesn't make any sense...

What is real column name?
You should set it.

`db.Table("deleted_users").Where("... = ?", "jinzhu").Delete()` this code doesn't use `User` struct,
so `User` struct's tag doesn't matter.

**Comment by sdghchj** [comment]
"n = ? " is right

**Comment by zaneli** [comment]
@sdghchj 
Incorrect.

If first without tag

```go
type User struct {
  gorm.Model
  Name string
}

db.Table("deleted_users").CreateTable(&User{})
```

and after that append tag,

```go
type User struct {
  gorm.Model
  Name string `gorm:"column:n"`
}
```
"name = ? " is right.

So I've said it once but I'll say it again, you should set real column name.
`User` struct's tag doesn't matter.

**Comment by sdghchj** [comment]
@zaneli I mean CreateTable also use 
```
type User struct {
  gorm.Model
  Name string `gorm:"column:n"`
}
```
in this case, "n = ? " is right
