### ISSUE TITLE
Scan all rows into slice

### ISSUE THREAD

**Issue by rafa-acioly** [go-gorm/gorm#2823]
### What version of Go are you using (`go version`)?
1.12

### Which database and its version are you using?
postgres 12

```go
func (s *Repository) Find(sku, sellerID, campaignCode string) (prices []SellingPrice, err error) {
	err = s.db.Debug().
		Where("column1 = ? AND column2 = ? and column3 = ?", sku, sellerID, campaignCode).
		Find(&MyModel{}).
		Scan(&prices).
		Error

	return
}
```

The first `Debug` says:
> SELECT * FROM "my_model"  WHERE "my_model"."deleted_at" IS NULL AND ((column1 = '123' AND column2 = 'xpto' and column3 = '0'))  
> [2 rows affected or returned ] 

But the `scan` only scan 1 row:
> SELECT * FROM "my_model"  WHERE "my_model"."deleted_at" IS NULL AND "my_model"."id" = 11 AND ((column1 = '123' AND column2 = 'xpto' and column3 = '0'))  
> [1 rows affected or returned ]

**Comment by jasondavindev** [comment]
You must pass the interface as an slice:

```
s.db.Debug()
  .Where("column1 = ? AND column2 = ? and column3 = ?", sku, sellerID, campaignCode)
  .Find(&[]MyModel{})
  .Scan(&prices)
```
