### ISSUE TITLE
sql: database is closed while connection works with sqlx

### ISSUE THREAD

**Issue by sevaho** [go-gorm/gorm#2825]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

Everything works fine when running locally but when I run a dockerized program on Kuberentes and I get the following error:

```
dial tcp 127.0.0.1:5432: connect: connection refused
(/app/main.go:39) 
[2019-12-29 18:52:56]  sql: database is closed 
```

When I add sqlx (https://github.com/jmoiron/sqlx) as dependency and open a connection as well everything is working fine.

So there must be something wrong with the connection to postgresql that Gorm is using.

(/app/main.go:39) 
### What version of Go are you using (`go version`)?

go version go1.13.5 linux/amd64

### Which database and its version are you using?

postgresql 11

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"net/http"

	"fmt"

	"github.com/gin-gonic/gin"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	// "github.com/jmoiron/sqlx"
)

var db *gorm.DB

func Healthz(c *gin.Context) {
	c.PureJSON(http.StatusOK, gin.H{})
}

func setupRouter() *gin.Engine {
	r := gin.Default()

	r.GET("/healthz", Healthz)
	return r
}

func GetDB() *gorm.DB {
	return db
}

func Setup() {
	var err error
	cfg := "postgresql://foo:bar@localhost:5432/postgres?sslmode=disable"

	// if I uncomment the following everything works fine
	// _, err = sqlx.Connect("postgres", cfg)
	// if err != nil {
	// 	  log.Fatalln(err)
	// }
	db, err = gorm.Open("postgres", cfg)
	db.LogMode(true)

	if err != nil {
		fmt.Print(err)
	}
}

func main() {
	Setup()
	GetDB()

	r := setupRouter()
	r.Run(":5000")
}
```

**Comment by DFrancis84** [comment]
How come you don't just put the connection into the main function? You also need to do a `defer db.Close()` at the end of where ever you create the db connection.

**Comment by sevaho** [comment]
@DFrancis84 Does not work, tried to add defer. I have the connection in a global variable so I can access it from anywhere

**Comment by kirill-kostenetskyi** [comment]
@sevaho have you found the reason?  The weirdest thing that this works fine under the docker on the Windows machine. I have absolutely the same issue.

**Comment by sevaho** [comment]
No not yet :/
