### ISSUE TITLE
Increment a database field by 1 in GORM

### ISSUE THREAD

**Issue by Turing-Chu** [go-gorm/gorm#2830]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.13.4 darwin/amd64

### Which database and its version are you using?
mysql  Ver 8.0.18 for macos10.14 on x86_64 (MySQL Community Server - GPL)

### Question

I find that mysql can update one column with increment(you can find at [Increment a database field by 1](https://stackoverflow.com/questions/2762851/increment-a-database-field-by-1))

then does GORM support it with Update method? or just only use db.Exec with raw mysql query ?

**Comment by jasondavindev** [comment]
I think Gorm doesn't support it yet and I don't encourage to write raw query for simple.

For now, a simple example:

```go
model := &User{Name: "lerolero"}
db.FirstOrCreate(&User{}, model)
db.Model(model).Update("logins", gorm.Expr("logins + ?", 1))
```

It's time to create ```Upsert``` method.
