### ISSUE TITLE
why ping the connection when gorm.Open()?

### ISSUE THREAD

**Issue by DarthPestilane** [go-gorm/gorm#2836]
```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
        // why ping the connection inside the Open function ?
	gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
}

func main() {
	//
}
```

Why ping the connection inside the Open function. Maybe we just wanted to register an database service and get the dao but not to connect it then.

**Comment by Bogdaan** [comment]
"ping after open" -  does not look as expected behavior.

This behavior lead to infrastructure issues:
we always ping databases that we don't use

**Comment by DarthPestilane** [comment]
@Bogdaan unexpected behavior? Not agreed since everyone has different situation, we can't define the very expected behavior. What I mean is GORM should not take over the ping action within Open. It should leave it to developers.

**Comment by Bogdaan** [comment]
Why this behaviour is strange:
1. database/sql doesn't ping after open. 
2. Ping and Open is two operations (SRP)

I explore this issue, when i deploy code to k8s with proxysql sidecar. Sidecar with database connection starts after Open, therefore only native database/sql works fine.

**Comment by DarthPestilane** [comment]
That's exactly what I mean. 

> database/sql doesn't ping after open.

If you take a look at the source code, you'll see that gorm pings the connection inside the `gorm.Open`:

```go
	// Send a ping to make sure the database connection is alive.
	if d, ok := dbSQL.(*sql.DB); ok {
		if err = d.Ping(); err != nil && ownDbSQL {
			d.Close()
		}
	}
	return
```

I don't think this is a good design pattern.
