### ISSUE TITLE
How to define polymorphic Association ownerid as uniqid?

### ISSUE THREAD

**Issue by du86796922** [go-gorm/gorm#2837]
如何自定义多态的关联OwnerId ，为  Uniqid	  ？
How to define polymorphic Association ownerid as uniqid?
### What version of Go are you using (`go version`)?
go 1.13
### Which database and its version are you using?
mysql 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```go
package main
type Production struct {
	Id        uint `gorm:"primary_key"`
	Uniqid	  string //index 
	Item I `gorm:"polymorphic:Owner"`
}
type Workspace struct {
	Id        uint `gorm:"primary_key"`
	Uniqid	  string //index 
	Item Item `gorm:"polymorphic:Owner;"`
}
type Item struct {
	Id        uint `gorm:"primary_key"`
	Uniqid	  string //index 
	//OwnerId   int
	OwnerType string
}
```

**Comment by keenJR** [comment]
I have the same question

**Comment by keenJR** [comment]
use foreignkey:Uniqid;association_foreignkey:Uniqid in Item struct
