### ISSUE TITLE
How to use many to many of struct in differenct package?

### ISSUE THREAD

**Issue by blxzfb307** [go-gorm/gorm#2850]
I use gorm in a web application and I divide the pacage according to the module. I want to define the struct and the handler function in a same package but it is an import cycle occurs. How can I use the many to many relation in this case?

For example, there are use and language in different package.

**user.go**
```go
type User struct {
    gorm.Model
    Languages         []language.Language `gorm:"many2many:user_languages;"`
}
```
**language.go**
```go
type Language struct {
    gorm.Model
    Name string
    Users             []user.User `gorm:"many2many:user_languages;"`
}
```

**Comment by yeqown** [comment]
1. Why not put all your `Model` into one package? because them are in the same usage
2. This is not an issue about `gorm`, but your project structure

**Comment by blxzfb307** [comment]
> 1. Why not put all your `Model` into one package? because them are in the same usage
> 2. This is not an issue about `gorm`, but your project structure

1. Putting them into `model` package is dividing the code by layer (MVC) which I have tried and it will have a huge package `model`, so I want to divede the code by responsibility this time. It means that a pacage shoud include the model, router, handler and so on.
2. I want to know whether `gorm` has considered this problem and what is the best practice of the web application project structure.

**Comment by yeqown** [comment]
> > 1. Why not put all your `Model` into one package? because them are in the same usage
> > 2. This is not an issue about `gorm`, but your project structure
> 
> 1. Putting them into `model` package is dividing the code by layer (MVC) which I have tried and it will have a huge package `model`, so I want to divede the code by responsibility this time. It means that a pacage shoud include the model, router, handler and so on.
> 2. I want to know whether `gorm` has considered this problem and what is the best practice of the web application project structure.

in my opinion, the import cycle  is the issue related to `go` language, gorm may not consider this ~ 
here is a link to my application structure: [https://github.com/yeqown/micro-server-demo](https://github.com/yeqown/micro-server-demo) , hope this could provide any help, and any suggestions are welcome
