### ISSUE TITLE
Turn off callback registration logging

### ISSUE THREAD

**Issue by NilsJPWerner** [go-gorm/gorm#2856]
The gorm update from v1.9.11 to v1.9.12 has led to all callback registrations getting logged like: 

```
[info] registering callback `dd-trace-go:before_create` from /Users/nilswerner/Code/Golang/service/app/services/persistence/postgres/utilities.go:32
```

I can't turn it off using `db.LogMode(false)` and I feel like it should be off by default.

I'm on: `github.com/jinzhu/gorm v1.9.12`

**Comment by Yoone** [comment]
Getting the same issue here. The log mode is ignored by the callback logger, but it shouldn't be.

![image](https://user-images.githubusercontent.com/2976044/74024339-f22fc280-49a1-11ea-85d2-12be4636ac75.png)

**Comment by Yoone** [comment]
Getting the same issue here. The log mode is ignored by the callback logger, but it shouldn't be.

**Comment by mecavity** [comment]
Likewise

**Comment by Yoone** [comment]
I implemented a work-around on our end which consists in re-declaring the `nopLogger` and setting it as the default one.

```go
type nopLogger struct{}

func (nopLogger) Print(values ...interface{}) {}

// ...

db.LogMode(false)
db.SetLogger(nopLogger{}) // Preventing callback logs from being displayed
```

**Comment by NilsJPWerner** [comment]
Is this fixed in v2?
