### ISSUE TITLE
Allow callback registration for `Exec`

### ISSUE THREAD

**Issue by jonas0616** [go-gorm/gorm#2858]
I am instrumenting the code with opentracing. The library I used is [smacker
/opentracing-gorm](https://github.com/smacker/opentracing-gorm), which take the advantages of gorm callbacks to add the trace points.

Nevertheless, the `Exec` queries are not reported to the tracing backend. After some lookup, it seems that gorm does not implement the callbacks of `Exec`. Therefore smacker/opentracing-gorm is unable to add trace point to it. It would be great if it supports callbacks on all the queries.

**Comment by NilsJPWerner** [comment]
+1

**Comment by butalso** [comment]
+1

**Comment by jinzhu** [comment]
Added to V2.
