### ISSUE TITLE
Updates don't work

### ISSUE THREAD

**Issue by birkirb** [go-gorm/gorm#286]
The updates as presented in the readme don't work.
If I do: 

``` Go
// Update an existing struct
db.First(&user)
user.Name = "jinzhu 2"
user.Age = 100
db.Save(&user)
```

The generated update statement will update all columns.

So does this

``` Go
db.Model(&user).Update("name", "hello")
```

and this does nothing:

``` Go
db.Model(&user).Updates(User{Name: "hello", Age: 18})
```

I should note that all of these would be happening in a Method on user, such as 

``` Go
func (u *User) UpdateStuff(...) 
```

I'm having to fall back on `db.Exec("UPDATE ... ")`  to get the right behaviour, which kinda defeats the point.

**Comment by natdm** [comment]
Is this still the case that Updates updates all fields instead of non-blank fields?

The doc states: 
```// Update multiple attributes with `struct`, will only update those changed & non blank fields
db.Model(&user).Updates(User{Name: "hello", Age: 18})```

But this code: 
```go
func (d *DB) UpdateBidder(b Bidder) error {
	if err := d.DB.Model(&Bidder{}).Updates(b).Error; err != nil {
		return err
	}
	d.cache.NewPre("bidder_id").Set(int(b.ID), b)
	return nil
}
```
Updates all fields to blank, except any populated ones.

**Comment by Jasonjiang27** [comment]
When I debug I found that if the value is nil value, it did not work. Such as the value is 0 or false. Why?
