### ISSUE TITLE
New v2 version should update import path

### ISSUE THREAD

**Issue by ipfans** [go-gorm/gorm#2871]
### What version of Go are you using (`go version`)?
go 1.13.7

### Which database and its version are you using?
MySQL/PostgreSQL

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

As code new upcoming version have some different APIs. If it become to v2.0, it should be update import path to `github.com/jinzhu/gorm/v2` to better go module support.

**Comment by jinzhu** [comment]
We decided to use the import path `gorm.io/gorm` instead of `github.com/jinzhu/gorm/v2`

Thank you for your report.
