### ISSUE TITLE
Registering hook after removing one with same name yield error

### ISSUE THREAD

**Issue by Djolivald** [go-gorm/gorm#2874]
When adding a hook with the same name as one that has just been removed we get a "duplicated hook warning". As the previous hook is removed I'd expect to be able to register a new hook with the same name.

### What version of Go are you using (`go version`)?
go version go1.13.6 windows/amd64

### Which database and its version are you using?
postgres

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	)

func main() {

	DB, err := gorm.Open("postgres", "host=postgres port=5432 user=gorm dbname=gorm password=gorm sslmode=disable")
	if err != nil {
		panic(err)
	}
	hookName := "myHook"
	DB.Callback().Create().After("gorm:create").Register(hookName, func(scope *gorm.Scope) {
		fmt.Println("gorm::create hook")
	})
	DB.Callback().Create().After("gorm:create").Remove(hookName)
	DB.Callback().Create().After("gorm:create").Register(hookName, func(scope *gorm.Scope) {
		fmt.Println("second gorm::create hook")
	})
}

```
Output:
```
go run ./main.go

[2020-02-04 09:03:26][info] registering callback `myHook` from C:/Users/DorianJolivald/Projects/SBG/GoPlayground/main.go:16
[2020-02-04 09:03:26][info] removing callback `myHook` from C:/Users/DorianJolivald/Projects/SBG/GoPlayground/main.go:19
[2020-02-04 09:03:26][info] registering callback `myHook` from C:/Users/DorianJolivald/Projects/SBG/GoPlayground/main.go:20
[2020-02-04 09:03:26][warning] duplicated callback `myHook` from C:/Users/DorianJolivald/Projects/SBG/GoPlayground/main.go:20
```

**Comment by rtbsolutions** [comment]
same issue here,
looks like callbacks not being removed on Remove()

or better provide clear example of Register() and Remove() usage
