### ISSUE TITLE
Remove dashes from uuid field as a primary key when query to database

### ISSUE THREAD

**Issue by laihoangdung** [go-gorm/gorm#2876]
I am using UUID as the primary key for tables in my project
When I save a new object, I need to remove dashes in UUID before the object is saved to the database

How to gorm auto-remove dashes in UUID field before query to Database.

You can see an example below:

Current query:
 SELECT * FROM `students`  WHERE `students`.`deleted_at` IS NULL AND ((user_id = '03770dfa-07ac-4163-ae39-1e81ced2a5e7')) ORDER BY `students`.`id` ASC LIMIT 1

Expected query:
 SELECT * FROM `students`  WHERE `students`.`deleted_at` IS NULL AND ((user_id = '03770dfa07ac4163ae391e81ced2a5e7')) ORDER BY `students`.`id` ASC LIMIT 1

**Comment by Numline1** [comment]
I don't think there's any need to make gorm do this? You can easily do that in Go, just use
``` uuid := strings.Replace("03770dfa-07ac-4163-ae39-1e81ced2a5e7", "-", "", -1) ```, the resulting `uuid` var value will be ``` 03770dfa07ac4163ae391e81ced2a5e7 ```, then run your query with your newly stripped UUID.

**Comment by laihoangdung** [comment]
But it has some troubles with queries later when We use Preload().
