### ISSUE TITLE
How to configure lock_timeout in gorm?

### ISSUE THREAD

**Issue by yangjinsay** [go-gorm/gorm#2893]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.13.6 linux/amd64

### Which database and its version are you using?
postgresql-12

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	"time"
)

func main() {
	db, err := gorm.Open("postgres", "host=database user=postgres dbname=testdb sslmode=disable password=123456")
	if err != nil {
		panic("failed to connect database")
	}
	defer db.Close()

	db.Create(&Product{Code: "L1", Price: 1000})

	db.InstantSet("db:lock_timeout", 1000)
	db.InstantSet("gorm:query_option", "FOR UPDATE")

	tx := db.Begin()
	var p Product
	err = tx.First(&p, 1).Error
	if err != nil {
		tx.Rollback()
		return
	}

	v, e := db.Get("lock_timeout")
	fmt.Println(v, e)
	go func() {
		// read
		fmt.Println("read start")
		var product Product
		db.First(&product, 1) //
		fmt.Println(product)
		fmt.Println("read end.")
	}()

	time.Sleep(time.Second * 5)
	fmt.Println("commit.")
	tx.Commit()
	time.Sleep(time.Second * 1)
}

type Product struct {
	gorm.Model
	Code  string
	Price uint
}

```
i tried to configure this way but it didn't work.

**Comment by yangjinsay** [comment]
👎

**Comment by th-lange** [comment]
Have a look here:
https://github.com/jinzhu/gorm/issues/1009
