### ISSUE TITLE
Duplicate key error for many to many associations

### ISSUE THREAD

**Issue by tahsinrahman** [go-gorm/gorm#2895]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
`go version go1.13.7 darwin/amd64`

### Which database and its version are you using?
`psql (PostgreSQL) 12.2`

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

var db *gorm.DB

// User has and belongs to many languages, use `user_languages` as join table
type User struct {
	Id        uint64
	Languages []Language `gorm:"many2many:user_languages;"`
}

type Language struct {
	Id   uint64
	Name string `gorm:"unique"`
}

func init() {
	var err error
	db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)

	db.AutoMigrate(&User{}, &Language{})
}

func main() {
	if err := db.Create(&User{
		Languages: []Language{
			{
				Name: "a",
			},
			{
				Name: "b",
			},
		},
	}).Error; err != nil {
		panic(err)
	}

	if err := db.Create(&User{
		Languages: []Language{
			{
				Name: "b",
			},
			{
				Name: "c",
			},
		},
	}).Error; err != nil {
		panic(err)
	}
}
```

```

[2020-02-20 15:48:29]  [0.81ms]  INSERT INTO "languages" ("name") VALUES ('b') RETURNING "languages"."id"  
[0 rows affected or returned ] 

[2020-02-20 15:48:29]  pq: duplicate key value violates unique constraint "languages_name_key" 
```

**Comment by ItsLeeOwen** [comment]
I've confirmed that the created join table inherits constraints defined on the source models, in my case a UNIQUE constraint was on my ID field.  When removed the join table was no longer generated with UNIQUE constraints on it's columns.
