### ISSUE TITLE
./../jinzhu/gorm/schema/field.go:271:45: fieldValue.IsZero undefined (type reflect.Value has no field or method IsZero)

### ISSUE THREAD

**Issue by icobani** [go-gorm/gorm#2898]
I m geting this error during build docker.

./../jinzhu/gorm/schema/field.go:271:45: fieldValue.IsZero undefined (type reflect.Value has no field or method IsZero)

anybody know anything ?

**Comment by renomarx** [comment]
Bcause of this: https://github.com/jinzhu/gorm/issues/2899

**Comment by SulanthaM** [comment]
I fixed this by updating go to 1.13, but dont know if it fixed a root cause.

**Comment by earie12** [comment]
> I fixed this by updating go to 1.13, but dont know if it fixed a root cause.

after we updated go we got another issue ; cannot use "mysql" (type string) as type gorm.Dialector in argument to gorm.Open:
        string does not implement gorm.Dialector (missing BindVar method)

**Comment by SulanthaM** [comment]
I think the issue is with go get.  I assume it downloads master branch with the changes made with gorm_v2.
I actually solved all the issues by using glide install.
Glide takes 1.9.12 as the version.

Afterwards, all the issues was gone.
________________________________

**Comment by wizofaus** [comment]
master branch has been restored as default, you'll need to clean the github.com/jinzhu directory and re-run go get.
