### ISSUE TITLE
Add option to allow check unique constraint (duplicate) errors

### ISSUE THREAD

**Issue by lafriks** [go-gorm/gorm#2903]
Currently there is only `RecordNotFound` error check. Would be great if there was a way to check also unique errors as for different databases errors are different. Ideally it would be great if error would contain also column name in question.

**Comment by dineshsprabu** [comment]
@jinzhu It will be useful if you add support for Error Codes https://www.postgresql.org/docs/10/errcodes-appendix.html
I want to handle all `Integrity Violation` together in a similar way.

**Comment by lafriks** [comment]
Please reopen, still needed

**Comment by gutakk** [comment]
> @jinzhu It will be useful if you add support for Error Codes https://www.postgresql.org/docs/10/errcodes-appendix.html
> I want to handle all `Integrity Violation` together in a similar way.

I found a workaround. You can check it out [here](https://github.com/go-gorm/gorm/issues/3499#issuecomment-730116632)

**Comment by loeffel-io** [comment]
+1

**Comment by AyoobMH** [comment]
+1

**Comment by phanirithvij** [comment]
+1

**Comment by dankobgd** [comment]
I don't even understand why the gorm/driver/postgres doesn't even expose original pgx.
So i could just check if error is pgx.PgError...
Right now i need to install pgx manally just to do this stupid check or am i missing something??

**Comment by weisttl** [comment]
+1

**Comment by johnbailon** [comment]
I use this:

```go
func IsDuplicateKeyError(err error) bool {
	duplicate := regexp.MustCompile(`\(SQLSTATE 23505\)$`)
	return duplicate.MatchString(err.Error())
}
```
