### ISSUE TITLE
Is there any way to auto add tracking time for some columns?

### ISSUE THREAD

**Issue by adzimzf** [go-gorm/gorm#2919]
I know that `GORM` already supports auto-track time for columns `CreatedAt`, `UpdateAt`. But, in my case I use old database which the columns name for time tracking are `CreatedTime` and `UpdateTime`. Is there any way to add an auto time track for those columns without changing the column name?
### What version of Go are you using (`go version`)?
1.10

### Which database and its version are you using?
DB: postgres
Gorm Version: 1.9.12

**Comment by fishyww** [comment]
@adzimzf  Change the red box CreatedAt to CreatedTime, or you can customize the method to replace the registered callback function.
![image](https://user-images.githubusercontent.com/51019225/82798981-e19d4c80-9eab-11ea-860c-905f7cf3f73e.png)
