### ISSUE TITLE
Clickhouse support

### ISSUE THREAD

**Issue by staticmukesh** [go-gorm/gorm#2929]
Is there any plan to add Clickhouse support? Can PR be raised for the support?

**Comment by jakesyl** [comment]
I'd be interested in this as well

**Comment by jinzhu** [comment]
Yes, it would be cool to support it to GORM v2, refer https://github.com/go-gorm for example.

DM me if you are interested

**Comment by lihaotian0607** [comment]
I'd be interested in this as well

**Comment by X6789** [comment]
I am looking forward to his support for clickhouse

**Comment by iqDF** [comment]
@jinzhu  I will take this issue this week as discussed in our internal chat.

**Comment by daodao2007** [comment]
> Is there any plan to add Clickhouse support? Can PR be raised for the support?

https://github.com/daodao2007/clickhouse，Support v2

**Comment by iqDF** [comment]
> > Is there any plan to add Clickhouse support? Can PR be raised for the support?
> 
> [https://github.com/daodao2007/clickhouse](https://github.com/daodao2007/clickhouse%EF%BC%8CSupport) v2
Nice

**Comment by iqDF** [comment]
I tried implemented a clickhouse support for gorm here. I'm still testing some migrator methods on several clickhouse versions:
- 19.14
- 20.3
- 20.7
- 20.8

See my work here: https://github.com/iqDF/clickhouse

**Comment by jinzhu** [comment]
Hello @iqDF @daodao2007 

Thank you for your contribution, I have create a clickhouse repo https://github.com/go-gorm/clickhouse based on @iqDF's implementation.

Please contribute to that repo, thank you.
