### ISSUE TITLE
MySQL-Go Bit conversion problem

### ISSUE THREAD

**Issue by ashkan90** [go-gorm/gorm#2930]
## What version of Go are you using (`go version`)?
--  Go 1.13.1 windows/amd64

### Which database and its version are you using?
-- MySQL v4.9.0.1

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
-- 
```
type Services struct {
	ID          uint   `gorm:"primarykey;autoincrement"`
	Active      bool `gorm:"type:bit"`
}
|id | active| 
___________|
|1  | true   | //  copied from DataGrip

func main() {

       var transaction model.Transactions


	db.Db.Where(model.Transactions{
		ServiceID: 1,
	}).Find(&transaction)

}

```
So here's expected way of data is:

``` { 1 true } ```

Actual return data is:
``` { 1 false } ```

I can see a problem which says "`sql: Scan error on column index 5, name "active": sql/driver: couldn't convert "\x01" into type bool`" when i turn debug mode on.

I searched its solution and it's easy to implement also i want to mention that i've not ever opened source code of gorm. so i can't say it's easy as same they did but it should be fixed as soon as possible.

Here's other people's solution for this problem.
[MySQL's bit type maps to which Go type?](https://stackoverflow.com/questions/47535543/mysqls-bit-type-maps-to-which-go-type)

**Comment by chaseSpace** [comment]
666
