### ISSUE TITLE
Potentially incorrect result returned when using OR

### ISSUE THREAD

**Issue by bogdan-kovalev** [go-gorm/gorm#2931]
I have the following scenario in my unit test:
1. I have a fake model:
```
type FakeModel struct {
	gorm.Model
	Name string
}
```
2. In the unit test, I'm adding one instance of the `FakeModel` into the db:
```
// create db
db, err := gorm.Open("sqlite3", "test.db")
db.AutoMigrate(&FakeModel{})

// add one instance
db.Create(&FakeModel{Name: "FM1"})
```
3. Then I try to fetch it and the result is confusing:
```
// First, get all - this works as expected
var result1 []FakeModel
db.Where(&FakeModel{}).Find(&result1)
// result1 contains the fake model "FM1"

// Then get all or not existing "FM2"
var result2 []FakeModel
db.Where(&FakeModel{}).Or(&FakeModel{Name: "FM2"}).Find(&result2)
// Here I expect that the result will contain the fake model FM1, because of `Where(&FakeModel{})`
// But it actually returns nothing, len(result) == 0
```

My question is why the following condition:
`Where(&FakeModel{}).Or(&FakeModel{Name: "FM2"})`
behaves like: `Where(&FakeModel{Name: "FM2"})` ?
Isn't it a bug?

**Comment by MaxInertia** [comment]
@bogdan-kovalev Did you resolve this? I am having a similar problem.

Both of these are failing for me.

```
db.Where("name = ?", "FM1").Or("name = ?", "FM2").Find(&result)

db.Where("name = ? OR name = ?", "FM1", "FM2").Find(&result)
```

Running the query that is displayed when using debug mode (with `db.Debug()`) does return the expected result. So is gorm ignoring results that are returned in certain cases? or is it not displaying the query that is actually being run?

**Comment by jinzhu** [comment]
yes, this is bug, which has been fixed in V2.
