### ISSUE TITLE
auto_preload suppresses custom SQL preloading

### ISSUE THREAD

**Issue by davidahall** [go-gorm/gorm#2943]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.13.7 (gorm 1.9.12)

### Which database and its version are you using?

postgres

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```
package main

import (
	"github.com/google/uuid"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type header struct {
    ID      uuid.UUID `gorm:"column:header_id;primary_key"`
    Name    string    `gorm:"column:header_name"`
	Details []detail  `gorm:"foreignkey:HeaderID"`
}

type detail struct {
	HeaderID    uuid.UUID `gorm:"column:header_id;primary_key"`
	LineNumber  uint32    `gorm:"column:line_num;primary_key;auto_increment:false"`
	Description string    `gorm:"column:detail_txt"`
}

func main() {
	db, _ := gorm.Open("postgres", "host=localhost port=5432 user=postgres dbname=sandbox password=p05Tgr352 sslmode=disable")
	defer db.Close()
	
	db = db.Set("gorm:auto_preload", true)
	
	db.AutoMigrate(&header{})
	db.AutoMigrate(&detail{})

	id := uuid.New()
	
	hdr := header{
		ID:      id,
		Name:    "Sample",
		Details: []detail{
			{ HeaderID: id, LineNumber: 1, Description: "line 1" },
			{ HeaderID: id, LineNumber: 2, Description: "line 2" },
			{ HeaderID: id, LineNumber: 3, Description: "line 3" },
		},
	}

	db.Create(&hdr)

	db.LogMode(true)

	hdr2 := header{	ID: id	}
	db.Preload("Details", func(db *gorm.DB) *gorm.DB {
    	return db.Order( "details.line_num asc")
    }).First(&hdr2)
}
```

output:
(U:/Documents/PortfolioManager/gormPreload.go:49)
[2020-03-20 14:36:56]  [2.00ms]  SELECT * FROM "headers"  WHERE "headers"."header_id" = 'f35d4e2c-9218-45ec-b91e-a33cbded829b' ORDER BY "headers"."header_id" ASC LIMIT 1
[1 rows affected or returned ]

(U:/Documents/PortfolioManager/gormPreload.go:49)
[2020-03-20 14:36:56]  [0.97ms]  SELECT * FROM "details"  WHERE ("header_id" IN ('f35d4e2c-9218-45ec-b91e-a33cbded829b')) ORDER BY "details"."header_id" ASC
[3 rows affected or returned ]

Note that the custom SQL was not included in the order clause for reading the details table.  During the invocation of db.First, when the code is looping through the callbacks, in the preload callback, we pass through the search.Preload function (search.go:114) which finds the preload associated with the custom SQL, but skips it because the column name matches (line 117) 

```
114 func (s *search) Preload(schema string, values ...interface{}) *search {
115 	var preloads []searchPreload
116 	for _, preload := range s.preload {
117 		if preload.schema != schema {
118 			preloads = append(preloads, preload)
119 		}
120 	}
121 	preloads = append(preloads, searchPreload{schema, values})
122 	s.preload = preloads
123 	return s
124 }
```

workaround

The best work around seems to be to not attempt to use auto_preload for this table, which feels like a shame because this structure is farily common so auto_preload should be supported.

**Comment by nikandlv** [comment]
Same issue here
