### ISSUE TITLE
Can we use jinzhu gorm without prepared statement features

### ISSUE THREAD

**Issue by samplise** [go-gorm/gorm#2955]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.11.4

### Which database and its version are you using?
MySQL 5.6.25

### My Question
Our databasese do not support prepared statement features for security concerns. Can we still use jinzhu gorm in this case? Will the performance affected if we do not use prepared statement features?

**Comment by jinzhu** [comment]
Yes, just don't enable it when initialize.
