### ISSUE TITLE
Duplicate entry 'xxx' for key 'PRIMARY'' error

### ISSUE THREAD

**Issue by hwk42** [go-gorm/gorm#2961]
i use v1.9.8 version for mysql. when using Create method to insert entity in the code,it get ' Duplicate entry 'xxx' for key 'PRIMARY'' error.And I try to check the insert sql,find that there is primary key field with value,but my code has not specified any value for the field.what happen?

**Comment by rhernandez-itemsoft** [comment]
me too.
![image](https://user-images.githubusercontent.com/4327356/84412530-ffb9bb00-abd4-11ea-9c7d-b2a7beba64da.png)


![image](https://user-images.githubusercontent.com/4327356/84412567-0fd19a80-abd5-11ea-884b-61b5325c38bc.png)

![image](https://user-images.githubusercontent.com/4327356/84412612-1d872000-abd5-11ea-9a70-a7e0ad092d20.png)


![image](https://user-images.githubusercontent.com/4327356/84412655-2bd53c00-abd5-11ea-9d92-f7c2f3c10473.png)
