### ISSUE TITLE
Connection reset by peer using Postgresql driver 

### ISSUE THREAD

**Issue by rafareyes7** [go-gorm/gorm#2963]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.13
### Which database and its version are you using?

Postgresql 11

I have the following connection settings.

```go
// NewConnection ...
func NewConnection() (*gorm.DB, error) {
	config := getConfig()
        connStr := "host=xx.xx.xx port=5432 user=chavista-hatter dbname=my-db password=abc sslmode=verify-ca sslrootcert=/path/to/rcert sslcert=/path/to/cert sslkey=/path/to/key connect_timeout=0"
	db, err := gorm.Open("postgres", conn)
	if err != nil {
		return nil, err
	}

	db.DB().SetMaxOpenConns(25)
	db.DB().SetMaxIdleConns(25)
	db.DB().SetConnMaxLifetime(5 * time.Minute)

	db.SingularTable(true)

	if config.LogQueries {
		db = db.Debug()
	}

	return db, nil
}
```
I get a connection in the main class and inject that connection into a repository class that executes the queries through Gorm (ORM)

main.go
```go
db, err := database.NewConnection()
    if err != nil {
        panic(fmt.Sprintf("failed to connect database --> %v", err))
    }
    fmt.Println("database connection established successfully")

defer db.Close()

customerRepo := customer.NewRepository(db)
```
repository.go
```go
type repository struct {
    db *gorm.DB
}

//NewRepository 
func NewRepository(db *gorm.DB) Repository {
    return &repository{
        db: db,
    }
}

func (r *repository) Register(customer *models.Customer) (string, error) {

    err := r.db.Create(&customer).Error
    if err != nil {
        return "", err
    }

    return customer.key, nil
}
```

**Problem**
I send over 500k request (INSERTS) to the db which have 512 connections available and after a few minutes the following error starts to come up repeatedly in postgresql's log: 

```
unexpected EOF on client connection with an open transaction 
could not receive data from client: Connection reset by peer 
```
Any help?

**Comment by rynslmns** [comment]
@rafareyes7 did you ever resolve the issue? We are experiencing the same issue.

**Comment by rafareyes7** [comment]
> @rafareyes7 did you ever resolve the issue? We are experiencing the same issue.

Hi @rynslmns 

We had a bottleneck on the cloud vendor Postgres instance, so we increase the instance storage and the problem got fixed.
