### ISSUE TITLE
 Duplicate entry for update 

### ISSUE THREAD

**Issue by yogesh-reddy** [go-gorm/gorm#2971]
: Error 1062: Duplicate entry '1' for key  
i am getting this error on update 
{1 SKU1 change USD Servers 10 Market Asia}
this is my db entry 
{1 SKU2 change USD Servers 10 Market Asia}
 here i chnages it to sku2 and calling update (did not change my primary key)
db.Model(model.ListPrice{}).Updates(&lp)
is throwing i think update should not throw this error it should update against PK

**Comment by jmburges** [comment]
Hi @yogesh-reddy,

It's a bit hard to understand your question. Would you mind reformatting the code and the question by copy-pasting the below text into a new comment and respond with your answers to the questions?

Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?


### Which database and its version are you using?


### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	if /* failure condition */ {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```
