### ISSUE TITLE
db.Table("...").Find(&...) No data found using this method

### ISSUE THREAD

**Issue by wuyuancai** [go-gorm/gorm#2980]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.14.1 windows/amd64
github.com/jinzhu/gorm v1.9.12

### Which database and its version are you using?
MySQL 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	// db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}
type Goods struct{
    Id int
    Name string
    ...
}
func main() {
        var goods []Goods
	db.Table("tb_goods").Where(&Goods{Id: 1}).Find(&goods)
}
```
[2020-04-15 22:35:29]  [13.00ms]  SELECT * FROM `tb_goods`  WHERE (`goods`.`id` = 2)  
[0 rows affected or returned ] 

but MySQL has 1 row ， because WHERE (`goods`.`id` = 2)

**Comment by adam-buckley** [comment]
It's not clear in your example but does your Goods struct have a [gorm.Model declared](https://gorm.io/docs/models.html)?

**Comment by adam-buckley** [comment]
Also check if it works with just:
```go
db.First(&goods, 1) // replace 1 with whatever your ID is
```

You may also need to specify your table name on the struct since your table is "tb_goods" and not just "goods":
```go
func (Goods) TableName() string {
  return "tb_goods"
}
```
