### ISSUE TITLE
Comment with Postgres Issue

### ISSUE THREAD

**Issue by tjuliuyou** [go-gorm/gorm#2982]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

go version go1.13 linux/amd64
### Which database and its version are you using?
postgres 12.1

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go

type Item struct {
	ItemID string `json:"group_id" gorm:"type:char(36); comment:'item ID';primary_key"`
	Name    string `json:"name" gorm:"unique_index:idx_item_name;type:varchar(255); comment:'条目名'"`
	Remark  string `json:"remark" gorm:"type:varchar(255); comment:'备注'"`
}

```

Error output

```output
[35m(/model/model.go:29)[0m 
[33m[2020-04-17 09:39:22][0m  [36;1m[0.73ms][0m  CREATE TABLE "items" ("item_id" char(36) COMMENT 'item ID',"name" varchar(255) COMMENT '条目名',"remark" varchar(255) COMMENT '备注',PRIMARY KEY ("group_id"))  
[36;31m[0 rows affected or returned ][0m 

[35m(/model/model.go:29)[0m 
[33m[2020-04-17 09:39:22][0m  [36;1m[0.11ms][0m  CREATE UNIQUE INDEX idx_item_name ON "items"("name")   
[36;31m[0 rows affected or returned ][0m 

[35m(model/model.go:29)[0m 
[33m[2020-04-17 09:39:22][0m [31;1m pq: syntax error at or near "COMMENT" [0m
```

I lookup postgres docs , create table with comment should like this:

```sql
CREATE TABLE "items" (
"item_id" char(36),
"name" varchar(255),
"remark" varchar(255),
PRIMARY KEY ("group_id")
)  
COMMENT ON COLUMN "items"."item_id" IS 'item ID';
COMMENT ON COLUMN "items"."name" IS  '条目名';
COMMENT ON COLUMN "items"."remark" IS '备注';
```

PS. current tag `COMMENT` worked on mysql, but failed with postgresql

**Comment by gonzalezlrjesus** [comment]
When declaring a model, only supported tags can be added and **comments** are not included. Here you can see the list of what is supported: 
[https://gorm.io/docs/models.html#Supported-Struct-tags](https://gorm.io/docs/models.html#Supported-Struct-tags)

If you want to include it you can declare the model without the comments and after having stored an object or a table you can use **the SQL builder** to add them: 

```
package main

import (
	"log"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type item struct {
	ItemID string `json:"group_id" gorm:"type:char(36);primary_key"`
	Name   string `json:"name" gorm:"unique_index:idx_item_name;type:varchar(255);"`
	Remark string `json:"remark" gorm:"type:varchar(255); "`
}

func main() {
	db, err := gorm.Open("postgres", "host=localhost port=5432 user=postgres dbname=test sslmode=disable password=11111111")
	if err != nil {
		log.Fatal("Error! DB: ", err)
	}
	defer db.Close()

	db.AutoMigrate(&item{})

	// COMMENT ON TABLE - RAW SQL
	db.Debug().Exec("COMMENT ON TABLE items IS 'test-table-comment';")

	// COMMENT ON COLUMN - RAW SQL
	db.Debug().Exec("COMMENT ON COLUMN items.name IS 'test-column-comment';")
}

```
![to repo-comments](https://user-images.githubusercontent.com/33332802/86746341-fe7b8280-c008-11ea-839d-2fedc424720e.png)
