### ISSUE TITLE
使用钩子BeforeUpdate更新updated_at字段不能自己定义为时间戳

### ISSUE THREAD

**Issue by JayenLee** [go-gorm/gorm#2992]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.13.8
### Which database and its version are you using?
mysql5.0

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
// BeforeUpdate 更新之前
func (b *Models) BeforeUpdate(tx *gorm.Scope) {
	//b.UpdatedAt=time.Now().Unix()

	tx.SetColumn("updated_at", time.Now().Unix())
        tx.SetColumn("created_at", time.Now().Unix())
}
```
在更新数据的时候，正常应该是updated_at是用时间戳的方式更新，但是我在终端查看sql语句的时候，发现updated_at我自己这边定义的并没有生效而是还是使用gorm默认的
生成的sql是这样的
UPDATE `dfb_merchants` SET `created_at` = 1587814809, `password` = '1234123', `updated_at` = '2020-04-25 19:40:09'    
但是created_at是正常的时间戳

**Comment by fishyww** [comment]
> Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.
> 
> ### What version of Go are you using (`go version`)?
> 1.13.8
> 
> ### Which database and its version are you using?
> mysql5.0
> 
> ### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
> Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.
> 
> ```go
> // BeforeUpdate 更新之前
> func (b *Models) BeforeUpdate(tx *gorm.Scope) {
> 	//b.UpdatedAt=time.Now().Unix()
> 
> 	tx.SetColumn("updated_at", time.Now().Unix())
>         tx.SetColumn("created_at", time.Now().Unix())
> }
> ```
> 
> 在更新数据的时候，正常应该是updated_at是用时间戳的方式更新，但是我在终端查看sql语句的时候，发现updated_at我自己这边定义的并没有生效而是还是使用gorm默认的
> 生成的sql是这样的
> UPDATE `dfb_merchants` SET `created_at` = 1587814809, `password` = '1234123', `updated_at` = '2020-04-25 19:40:09'
> 但是created_at是正常的时间戳


源码默认生成时间的如下：
func updateTimeStampForCreateCallback(scope *Scope) {
    if !scope.HasError() {
        now := NowFunc()

        if createdAtField, ok := scope.FieldByName("CreatedAt"); ok {
            if createdAtField.IsBlank {
                createdAtField.Set(now)
            }
        }

        if updatedAtField, ok := scope.FieldByName("UpdatedAt"); ok {
            if updatedAtField.IsBlank {
                updatedAtField.Set(now)
            }
        }
    }
}
var NowFunc = func() time.Time {
    return time.Now()
}

可以根据自己实际需要重写时间戳的回调函数，再调用：db.Callback().Create().Replace() 方法替换掉即可。
