### ISSUE TITLE
AfterSave is called when doing Update

### ISSUE THREAD

**Issue by monzarrugh** [go-gorm/gorm#2996]
AfterSave hook should only be called when I'm doing db.Save() but it's also called when I'm doing db.Update. This is not an expected behavior otherwise what's the points of having these hooks.

**Comment by LonglyCode** [comment]
[gorm update](https://gorm.io/docs/update.html)

> Above updating operations will perform the model’s BeforeUpdate, AfterUpdate method, update its UpdatedAt timestamp, save its Associations when updating, if you don’t want to call them, you could use UpdateColumn, UpdateColumns.

I guess you need `UpdateColumns`.
