### ISSUE TITLE
Using 'group' as column name breaks queries with Where 

### ISSUE THREAD

**Issue by adriendomoison** [go-gorm/gorm#3002]
Go 1.13.7 - Postgres 12.2

Just wanted to report, I had a struct
```
type User struct {
  gorm.Model
  Group uint
  Name uint
}
```
and by doing `DB.Where("group = ?", 1).First(&user)` I was running into `pq: syntax error near group`

Renaming `Group` to `GroupId` made it work.

GORM is awesome ;)

**Comment by LonglyCode** [comment]
This is because the field name uses SQL syntax keywords, not GORM's issue .
please close issue .

**Comment by ppd0705** [comment]
> This is because the field name uses SQL syntax keywords, not GORM's issue . please close issue .

Is there any way to solve this problem if the column can't change name?

**Comment by ppd0705** [comment]
> > This is because the field name uses SQL syntax keywords, not GORM's issue . please close issue .
> 
> Is there any way to solve this problem if the column can't change name?

I found one way:  DB.Raw("SELECT * FROM  \`table_name\` WHERE \`keyword\` = ?",  value).Rows()
