### ISSUE TITLE
How to order by an association field?

### ISSUE THREAD

**Issue by afdecastro879** [go-gorm/gorm#3004]
Hi all! 
I have already search in the issue tracker but no success here we go:

### What version of Go are you using (`go version`)?

go version go1.14.2 darwin/amd64

### Which database and its version are you using?

Postgres 12

### The Question:

I have a simple `belongs to` association:

```go
type User struct {
	gorm.Model
	Email       string
	Password    sql.NullString
	...
}

// Association:
type AnotherUser struct {
	gorm.Model
	User        User
	UserID      int64
}
```

Then I would like to query a list of `AnotherUser` ordering by the email.
I've tried:

```go
var list []AnotherUser
db.Order("email asc").Find(&list)
```
But off course is not finding the field `email` because it does not belong to the `AnotherUser` entity. (even if I preload the query is not a join query)

The queries executed are:
```
SELECT * FROM "another_users"  WHERE "another_users"."deleted_at" IS NULL ORDER BY email asc 
```

Is this kind of ordering something supported by the library?
If not, is there any workaround?

**Comment by LonglyCode** [comment]
Maybe like this?
```golang
var list []AnotherUser
db.Preload("User", func(db *gorm.DB) *gorm.DB {
			db = db.Order("email asc")
			return db
                }).Find(&list)
```

**Comment by foxluqi** [comment]
Is there a way to auto join association table when order by an association field?

**Comment by afdecastro879** [comment]
Regarding this I experienced the following:
- What @LonglyCode mentioned before only works if what you want to order is the downstream list. In this use case that order is useless because the relation is one to one (you will be ordering users by it's email and then joining it to the correspondent AnotherUser)
- The only solution I found to order by an association field is the following:

```golang
var list []AnotherUser
db.Table("another_users").
	Select("another_users.*, users.*").
	Joins("INNER JOIN users ON users.id = another_users.user_id"). // After this you can order by any field
        Order("email asc")
```
The only caveat is that if the two tables you are joining have the same field name you must order using the table name as prefix. E.g. `Order("users.email asc")`

**Comment by dybxin** [comment]
@LonglyCode 

type User struct {
        ID uint64  `json:"id" gorm:"primary_key"`
	Email       string
	Password    sql.NullString
	...
}

// Cat:
type Cat struct {
        ID uint64  `json:"id" gorm:"primary_key"`
	Name        string
	Age      int64
}

//Association
type Association struct {
     UserID uin64 `json:"user_id"`
     CatID uint64 `json:"cat_id"`
     Sort uint `json:"sort"`
}

when user's Preload("Cat")  how to sort by sort?

**Comment by PanithanK** [comment]
> @LonglyCode
> 
> type User struct { ID uint64 `json:"id" gorm:"primary_key"` Email string Password sql.NullString ... }
> 
> // Cat: type Cat struct { ID uint64 `json:"id" gorm:"primary_key"` Name string Age int64 }
> 
> //Association type Association struct { UserID uin64 `json:"user_id"` CatID uint64 `json:"cat_id"` Sort uint `json:"sort"` }
> 
> when user's Preload("Cat") how to sort by field `sort`?

Did you have a solution?

**Comment by slr71** [comment]
I was able to get something like this to work by using a join in the custom preloading SQL function:

```
type Plan struct {
	// The plan identifier
	ID *string `gorm:"type:uuid;default:uuid_generate_v1()" json:"id,omitempty"`

	// The default quota values associated with the plan
	PlanQuotaDefaults []PlanQuotaDefault `json:"plan_quota_defaults,omitempty"`
}

type PlanQuotaDefault struct {
	// The identifier
	ID *string `gorm:"type:uuid;default:uuid_generate_v1()" json:"id,omitempty"`

	// The plan ID
	PlanID *string `gorm:"type:uuid;not null" json:"-"`

	// The default quota value
	QuotaValue float64 `gorm:"not null" json:"quota_value,omitempty"`

	// The resource type ID
	ResourceTypeID *string `gorm:"type:uuid;not null" json:"-"`

	// The resource type
	ResourceType ResourceType `json:"resource_type,omitempty"`

	// The effective date
	EffectiveDate time.Time `json:"effective_date,omitempty"`
}

// ResourceType defines the structure for ResourceTypes.
//
// swagger:model
type ResourceType struct {
	// The resource type ID
	//
	// readOnly: true
	ID *string `gorm:"type:uuid;default:uuid_generate_v1()" json:"id,omitempty"`

	// The resource type name
	//
	// required: true
	Name string `gorm:"not null;unique" json:"name,omitempty"`

	// The unit of measure used for the resource type
	//
	// required: true
	Unit string `gorm:"not null;unique" json:"unit,omitempty"`

	// Indicates whether or not a resource is consumable. That is, whether or not using the resource permanently
	// consumes a portion of the allocation. For example, CPU hours are permanently consumed as soon as they're used,
	// so they would be considered consumable. Conversely, data storage can be reclaimed by removing files form the
	// data store, so data storage is not considered to be consumable.
	Consumable bool `json:"consumable"`
}
```
