### ISSUE TITLE
The created_at and updated_at in the database cannot be automatically updated

### ISSUE THREAD

**Issue by StevyZheng** [go-gorm/gorm#3010]
The created_at and updated_at in the database cannot be automatically updated when a create or update operation is performed using gorm. Can you help analyze and solve it?Thank you!【I wonder if gorm is compatible with the mariadb version???】

version：
golang - 1.14.1
gorm - 1.9.12
mariadb - 10.4.12

Part of the source：

type Rent struct {
	gorm.Model
	Name	string	`gorm:"column:name;size:64;index;default:'';not null;"`
	Comment	string	`gorm:"column:comment;default:'';"`
}

func InitMysql() (err error) {
	dbUrl := fmt.Sprintf("%s:%s@(%s:%d)/%s?charset=utf8&parseTime=True&loc=Local",
		DBConf.DBUser, DBConf.DBPwd, DBConf.DBHost, DBConf.DBPort, DBConf.DBName)
	GDB, err = gorm.Open("mysql", dbUrl)
	if err != nil{
		return err
	}
	GDB.AutoMigrate(&Rent{}, &User{})
	return err
}

func RentAddOne(c *gin.Context) {
	reqRent := reqModel.Rent{}
	if err := c.ShouldBindJSON(&reqRent); err != nil{
		response.ShouldBindFail(c)
	} else {
		if err := GDB.Create(&reqRent).Error; err != nil{
			response.DBFail(c)
		} else {
			response.Ok(c)
		}
	}
}

After the interface call, you can add a record, but the created_at and updated_at properties of the database record are empty values.
![image](https://user-images.githubusercontent.com/12432363/81363079-0906c200-9115-11ea-8315-a1f0c7f3e8bb.png)

**Comment by fishyww** [comment]
> The created_at and updated_at in the database cannot be automatically updated when a create or update operation is performed using gorm. Can you help analyze and solve it?Thank you!【I wonder if gorm is compatible with the mariadb version???】
> 
> version：
> golang - 1.14.1
> gorm - 1.9.12
> mariadb - 10.4.12
> 
> Part of the source：
> 
> type Rent struct {
> gorm.Model
> Name string `gorm:"column:name;size:64;index;default:'';not null;"`
> Comment string `gorm:"column:comment;default:'';"`
> }
> 
> func InitMysql() (err error) {
> dbUrl := fmt.Sprintf("%s:%s@(%s:%d)/%s?charset=utf8&parseTime=True&loc=Local",
> DBConf.DBUser, DBConf.DBPwd, DBConf.DBHost, DBConf.DBPort, DBConf.DBName)
> GDB, err = gorm.Open("mysql", dbUrl)
> if err != nil{
> return err
> }
> GDB.AutoMigrate(&Rent{}, &User{})
> return err
> }
> 
> func RentAddOne(c *gin.Context) {
> reqRent := reqModel.Rent{}
> if err := c.ShouldBindJSON(&reqRent); err != nil{
> response.ShouldBindFail(c)
> } else {
> if err := GDB.Create(&reqRent).Error; err != nil{
> response.DBFail(c)
> } else {
> response.Ok(c)
> }
> }
> }
> 
> After the interface call, you can add a record, but the created_at and updated_at properties of the database record are empty values.
> ![image](https://user-images.githubusercontent.com/12432363/81363079-0906c200-9115-11ea-8315-a1f0c7f3e8bb.png)

According to the part of the code you gave me, I have tried it, and there is no problem as you said

**Comment by fishyww** [comment]
> The created_at and updated_at in the database cannot be automatically updated when a create or update operation is performed using gorm. Can you help analyze and solve it?Thank you!【I wonder if gorm is compatible with the mariadb version???】
> 
> version：
> golang - 1.14.1
> gorm - 1.9.12
> mariadb - 10.4.12
> 
> Part of the source：
> 
> type Rent struct {
> gorm.Model
> Name string `gorm:"column:name;size:64;index;default:'';not null;"`
> Comment string `gorm:"column:comment;default:'';"`
> }
> 
> func InitMysql() (err error) {
> dbUrl := fmt.Sprintf("%s:%s@(%s:%d)/%s?charset=utf8&parseTime=True&loc=Local",
> DBConf.DBUser, DBConf.DBPwd, DBConf.DBHost, DBConf.DBPort, DBConf.DBName)
> GDB, err = gorm.Open("mysql", dbUrl)
> if err != nil{
> return err
> }
> GDB.AutoMigrate(&Rent{}, &User{})
> return err
> }
> 
> func RentAddOne(c *gin.Context) {
> reqRent := reqModel.Rent{}
> if err := c.ShouldBindJSON(&reqRent); err != nil{
> response.ShouldBindFail(c)
> } else {
> if err := GDB.Create(&reqRent).Error; err != nil{
> response.DBFail(c)
> } else {
> response.Ok(c)
> }
> }
> }
> 
> After the interface call, you can add a record, but the created_at and updated_at properties of the database record are empty values.
> ![image](https://user-images.githubusercontent.com/12432363/81363079-0906c200-9115-11ea-8315-a1f0c7f3e8bb.png)

![image](https://user-images.githubusercontent.com/51019225/81781243-69896b00-952a-11ea-9341-0859fab7b40e.png)
29/5000 
According to the part of the code you gave me, I have tried it, and there is no problem as you said
