### ISSUE TITLE
Query using multiple group fields only the last one works

### ISSUE THREAD

**Issue by love666666shen** [go-gorm/gorm#3011]
### What version of Go are you using (`go version`)?
1.13

### Which database and its version are you using?
5.7

MySQL 5.7 Query：select distinct * from sms_contact where user_id = 5006 and is_deleted = 0 group by phone, group_name；

Gorm query: db.Select("distinct * ").Where(map[string]interface{}{"user_id": 5006, "is_deleted": 0}).Group("phone").Group("group_name").Find(&res).Error, result: select distinct * from sms_contact where user_id = 5006 and is_deleted = 0 group by  group_name;

**Comment by fishyww** [comment]
Look at the source code. Multiple assignments for the last time.


type search struct {
	db               *DB
	whereConditions  []map[string]interface{}
	orConditions     []map[string]interface{}
	notConditions    []map[string]interface{}
	havingConditions []map[string]interface{}
	joinConditions   []map[string]interface{}
	initAttrs        []interface{}
	assignAttrs      []interface{}
	selects          map[string]interface{}
	omits            []string
	orders           []interface{}
	preload          []searchPreload
	offset           interface{}
	limit            interface{}
	group            string
	tableName        string
	raw              bool
	Unscoped         bool
	ignoreOrderQuery bool
}


func (s *search) Group(query string) *search {
	s.group = s.getInterfaceAsSQL(query)
	return s
}

**Comment by fishyww** [comment]
> ### What version of Go are you using (`go version`)?
> 1.13
> 
> ### Which database and its version are you using?
> 5.7
> 
> MySQL 5.7 Query：select distinct * from sms_contact where user_id = 5006 and is_deleted = 0 group by phone, group_name；
> 
> Gorm query: db.Select("distinct * ").Where(map[string]interface{}{"user_id": 5006, "is_deleted": 0}).Group("phone").Group("group_name").Find(&res).Error, result: select distinct * from sms_contact where user_id = 5006 and is_deleted = 0 group by group_name;

Look at the source code. Multiple assignments for the last time.

type search struct {
db *DB
whereConditions []map[string]interface{}
orConditions []map[string]interface{}
notConditions []map[string]interface{}
havingConditions []map[string]interface{}
joinConditions []map[string]interface{}
initAttrs []interface{}
assignAttrs []interface{}
selects map[string]interface{}
omits []string
orders []interface{}
preload []searchPreload
offset interface{}
limit interface{}
group string
tableName string
raw bool
Unscoped bool
ignoreOrderQuery bool
}

func (s *search) Group(query string) *search {
s.group = s.getInterfaceAsSQL(query)
return s
}

**Comment by LonglyCode** [comment]
put conditons in one group fucntion:
```golang
db.Group("phone,group_name")
```
`Group` like `Select` function just  assign once.
