### ISSUE TITLE
AfterDelete hook: DeletedAt field is nil

### ISSUE THREAD

**Issue by renomarx** [go-gorm/gorm#3019]
### What version of Go are you using (`go version`)?
go version go1.14.2 linux/amd64

### Which database and its version are you using?
sqlite

### Program reproducing the issue

```go
package main

import (
	"log"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type User struct {
	gorm.Model
	Firstname string
	Lastname  string
}

func (u *User) AfterDelete(tx *gorm.DB) (err error) {
	log.Printf("%+v", u.DeletedAt)
	return
}

func main() {
	db, err := gorm.Open("sqlite3", ":memory")
	if err != nil {
		log.Fatalf("Database connection: %s", err)
	}
	db.AutoMigrate(&User{})

	user := User{
		Firstname: "Rob",
		Lastname:  "Pike",
	}
	db.Create(&user)

	db.Delete(&user)
}

```

**Comment by fishyww** [comment]
> ### What version of Go are you using (`go version`)?
> go version go1.14.2 linux/amd64
> 
> ### Which database and its version are you using?
> sqlite
> 
> ### Program reproducing the issue
> ```go
> package main
> 
> import (
> 	"log"
> 
> 	"github.com/jinzhu/gorm"
> 	_ "github.com/jinzhu/gorm/dialects/sqlite"
> )
> 
> type User struct {
> 	gorm.Model
> 	Firstname string
> 	Lastname  string
> }
> 
> func (u *User) AfterDelete(tx *gorm.DB) (err error) {
> 	log.Printf("%+v", u.DeletedAt)
> 	return
> }
> 
> func main() {
> 	db, err := gorm.Open("sqlite3", ":memory")
> 	if err != nil {
> 		log.Fatalf("Database connection: %s", err)
> 	}
> 	db.AutoMigrate(&User{})
> 
> 	user := User{
> 		Firstname: "Rob",
> 		Lastname:  "Pike",
> 	}
> 	db.Create(&user)
> 
> 	db.Delete(&user)
> }
> ```

The fields of the model act as mappings, and the actual operation DeletedAt field is inside the callback function：    DefaultCallback.Delete().Register("gorm:delete", deleteCallback)

![image](https://user-images.githubusercontent.com/51019225/82190067-067d4700-9923-11ea-891e-8cbd4d581005.png)

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by readygodom** [comment]
up

**Comment by loop0day** [comment]
For someone who is looking for a alternative way to set a field like 'deleted_on' in gorm:v2, the following code could help.
```golang
// Hook 'delete' function in func init
db.Callback().Delete().Replace("gorm:delete", deleteCallback)

func deleteCallback(db *gorm.DB) {
        if db.Error != nil {
                return
        }

        db.Statement.SQL.Grow(100)
        db.Statement.Clauses = make(map[string]clause.Clause)
        db.Statement.AddClauseIfNotExists(clause.Update{Table: clause.Table{Name: clause.CurrentTable}})
        db.Statement.AddClause(clause.Set{
                clause.Assignment{
                        Column: clause.Column{Name: "deleted_on"}, // Change field name to anything you want
                        Value:  time.Now().Unix(),
                },
        })
        db.Statement.BuildClauses = []string{"UPDATE", "SET"}
        db.Statement.Build(db.Statement.BuildClauses...)

        res, err := db.Statement.ConnPool.ExecContext(db.Statement.Context, db.Statement.SQL.String(), db.Statement.Vars...)
        if db.AddError(err) == nil {
                db.RowsAffected, _ = res.RowsAffected()
        }

        log.Printf("SQL: %v\n", db.Statement.SQL.String()) // Like UPDATE `xxx` SET `deleted_on`=xxx
}
```
