### ISSUE TITLE
Enumerated types issue

### ISSUE THREAD

**Issue by bramp** [go-gorm/gorm#302]
I have the following:

``` go
type BufferType string
const (
    Console BufferType = "console"
    Channel BufferType = "channel"
    Conversation BufferType = "conversation"
)

type Buffer struct {
    Bid  int64  `gorm:"primary_key:yes"`
    Type BufferType `sql:"not null;type:ENUM('console', 'channel', 'conversation')"`
    Name string `sql:"size:255;not null"`
}
```

When I try db.Save(buffer), I get the following error:
`sql: converting Exec argument #1's type: unsupported type BufferType, a string)`

Would it be possible to resolve that BufferType is really just a string, and save? I get similar errors if I try and load this struct with db.Find()

**Comment by schickling** [comment]
I had the same issue. The solution of @bramp still gave me an error. The following worked for me:

```go
func (u *BufferType) Scan(value interface{}) error { *u = BufferType(value.([]byte)); return nil }
func (u BufferType) Value() (driver.Value, error)  { return string(u), nil }
```

The difference is using `[]byte` instead of `string`. This stackoverflow thread helped me: http://stackoverflow.com/a/20582504/2418739

**Comment by charneykaye** [comment]
+1 great solution. I wish this was in the GORM docs.

**Comment by mehdy** [comment]
I'm trying to use enum as well but now the problem for me is related to dialect I think.
I've implemented `Scan` and `Value`and for tag I used both `gorm` and `sql` and when I `AutoMigrate` the model I get nothing but `pq: type "enum" does not exist`.
any Idea?
