### ISSUE TITLE
Create is  slow

### ISSUE THREAD

**Issue by felixwan-git** [go-gorm/gorm#3024]
Hi, I'm testing Create is used 100ms avg. 
env: wsl2 for arch   
Is there need any special configuration ?

![image](https://user-images.githubusercontent.com/45676208/82439588-87784200-9acd-11ea-9ff1-a8e62295a91d.png)

**Comment by gqdw** [comment]
mysql ?

**Comment by gqdw** [comment]
改成pipeline了，18分钟30w 数据

**Comment by baderkha** [comment]
i noticed this aswell , i use mysql , I wonder if the package has to do alot of reflections ?

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/issues/3055
