### ISSUE TITLE
gorm sqlite AutoMigrate  syntax error

### ISSUE THREAD

**Issue by wangkechun** [go-gorm/gorm#3032]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.14.2 darwin/amd64

### Which database and its version are you using?
sqlite

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

type Model struct {
	ID uint `gorm:"primary_key;comment:'ID'"`
}

func main() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	if err != nil {
		panic(err)
	}
	err = db.LogMode(true).AutoMigrate(new(Model)).Error
	if err != nil {
		panic(err)
	}
}

```

```
(main.go:20)
[2020-05-29 19:23:18]  near "COMMENT": syntax error

(main.go:20)
[2020-05-29 19:23:18]  [0.24ms]  CREATE TABLE "models" ("id" integer primary key autoincrement COMMENT 'ID' )
[0 rows affected or returned ]
panic: near "COMMENT": syntax error

goroutine 1 [running]:
main.main()
	main.go:22 +0x15f
exit status 2
```

**Comment by song-without-words** [comment]
does sqlite support 'comment'?

**Comment by LonglyCode** [comment]
https://stackoverflow.com/questions/7426205/sqlite-adding-comments-to-tables-and-columns

**Comment by LonglyCode** [comment]
https://stackoverflow.com/questions/7426205/sqlite-adding-comments-to-tables-and-columns
yes，sqlite not support 'comment'  syntax。

**Comment by jinzhu** [comment]
GORM V2 ignored comment when creating table in sqlite
