### ISSUE TITLE
现在是否支持针对mysql 5.7以上json列的支持？json列是个数组

### ISSUE THREAD

**Issue by LoveDollar** [go-gorm/gorm#3033]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
v1.9.12

### Which database and its version are you using?
mysql 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

package models

import (
	"database/sql/driver"
	"encoding/json"
)

type Demo struct {
	id  string
	obj []DemoObj `sql:"TYPE:json"`
}
type DemoObj struct {
	c1 string
	c2 int
	c3 bool
}

func (c DemoObj) Value() (driver.Value, error) {
	b, err := json.Marshal(c)
	return string(b), err
}

func (c *DemoObj) Scan(input interface{}) error {
	return json.Unmarshal(input.([]byte), c)
}

```

**Comment by LoveDollar** [comment]
如果obj只是个简单的struct的时候是可以的，但是当时数组的时候就无法生效了

**Comment by LonglyCode** [comment]
应该用数组实现Scanner和Valuer的interface：

**Comment by LonglyCode** [comment]
应该用数组实现Scanner和Valuer的interface：
```golang
type JsonSlice []interface{}

func (j JsonSlice) Value() (driver.Value, error) {
	b, err := json.Marshal(j)
	return string(b), err
}

func (j *JsonSlice) Scan(value interface{}) error {
	return json.Unmarshal(value.([]byte), &j)
}
```

**Comment by jinzhu** [comment]
https://github.com/go-gorm/datatypes.

**Comment by Kisesy** [comment]
@jinzhu gorm.io/datatypes 地址 404

**Comment by jinzhu** [comment]
是 https://github.com/go-gorm/datatypes

**Comment by Kisesy** [comment]
好吧，但文档例子中写的还是 gorm.io/datatypes
https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft-CN

**Comment by Kisesy** [comment]
还有我用 mysql 驱动，string 类型的字段在数据库中默认是创建为 longtext 类型，就是这样设计的吗

**Comment by jinzhu** [comment]
> 好吧，但文档例子中写的还是 gorm.io/datatypes
> https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft-CN
> 
> 并且 get 时还是会报错的
> 
> ```
> go get github.com/go-gorm/datatypes
> go: github.com/go-gorm/datatypes upgrade => v0.0.0-20200606131850-457073eeaeab
> go get: github.com/go-gorm/datatypes@v0.0.0-20200606131850-457073eeaeab: parsing go.mod:
>         module declares its path as: gorm.io/datatypes
>                 but was required as: github.com/go-gorm/datatypes
> ```

已处理，现在可以 import gorm.io/datatypes 了



> 还有我用 mysql 驱动，string 类型的字段在数据库中默认是创建为 longtext 类型，就是这样设计的吗

这个是因为没有设置字段的 size 导致的数据类型设置为了 longtext ，我个人感觉不太合理，不过还在想怎么设置这个值最好。。。

![image](https://user-images.githubusercontent.com/6843/83973499-6ad76900-a919-11ea-9d36-a598401d278c.png)

**Comment by Kisesy** [comment]
@jinzhu 对，用这种类型也倒是还行，但是有限制，比如无法使用索引，所以确实应该多研究
> BLOB/TEXT column 'name' used in key specification without a key length
