### ISSUE TITLE
在互引用的情况下，要在两个表中都添加/删除关联吗

### ISSUE THREAD

**Issue by lyyhui1314** [go-gorm/gorm#3037]
type Group struct {
	Name string `gorm:"column:name;UNIQUE_INDEX" json:"name"`
	Desc string `gorm:"column:desc" json:"desc"`
        Users []User `gorm:"many2many:users_groups"
}

type User struct {
	Name      string        `gorm:"column:name;UNIQUE_INDEX" json:"name"`
	Desc      string        `gorm:"column:desc" json:"desc"`
       Groups    []Group       `gorm:"many2many:users_groups"`
}

是这样吗
db.Model(&user).Association("Groups").Append([]Group{})
db.Model(&group).Association("Users").Append([]User{})

删除的时候也要删除两次吗

**Comment by jinzhu** [comment]
Only need to add/delete once
