### ISSUE TITLE
I want to not count soft delete data when doing count query

### ISSUE THREAD

**Issue by shixiaofeia** [go-gorm/gorm#3046]
Your issue may already be reported! Please search on the [issue track](https://github.com/go-gorm/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.12.6
### Which database and its version are you using?

mysql
### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/go-gorm/gorm/blob/master/tests/docker-compose.yml) or please provides your config.

```
if err := db.Find(data.Obj).Error; err != nil {
		if err != gorm.ErrRecordNotFound {
			return err
		}
	}
	if err := db.Offset(-1).Count(data.Total).Error; err != nil {
		return err
}


The soft delete was judged during the query, but the count did not judge

SELECT * FROM `role`  WHERE `role`.`deleted_at` IS NULL 
SELECT count(*) FROM `role` 
```

**Comment by jinzhu** [comment]
Test pass. https://github.com/go-gorm/gorm/commit/dbc3f8feb0f57d7a277aac51acfaf0df793df683

**Comment by shixiaofeia** [comment]
> Test pass. [dbc3f8f](https://github.com/go-gorm/gorm/commit/dbc3f8feb0f57d7a277aac51acfaf0df793df683)

I know the problem, my model and find are not the same struct, the find struct does not have the delete_at field, and then there is no stitching in the (scope *Scope) whereSQL() method, what should I do in this case?

**Comment by shixiaofeia** [comment]
But count is no problem, there is a problem with finding

**Comment by jinzhu** [comment]
Use model struct when counting like:

`db.Model(&modelStruct).Offset(-1).Count(data.Total)`

**Comment by shixiaofeia** [comment]
> 计算时使用模型结构，例如：
> 
> `db.Model(&modelStruct).Offset(-1).Count(data.Total)`

There is no problem with the model count, there is a problem with find, he judges that the delete_at field is the find struct I passed, not the model

**Comment by jinzhu** [comment]
If you are using GORM v1, you have to query like this then:

`db.Where("deleted_at IS NULL").Find(data.Obj)`

If you are using GORM v2, you can make it works like:

`db.Model(&modelStruct).Find(data.Obj)`

**Comment by shixiaofeia** [comment]
ok, thank you
