### ISSUE TITLE
Scanning into struct of GORM models

### ISSUE THREAD

**Issue by nickfiacco-bolt** [go-gorm/gorm#3049]
If I have two models with similar fields, and try to use GORM to find into a struct of these two models, there is no way to specify which model the data should be loaded into:

```
type Model1 struct {
    field1 string
    field2 string
}

type Model2 struct {
    field1 string
    field2 string
}

type CompositeStruct struct {
    Model1
    Model2
}

var compositeStruct CompositeStruct
gormdb.Select("model2.*").Find(&compositeStruct)
```

The `compositeStruct` will have `Model1` populated instead of `Model2`, as I would expect.

**Comment by song-without-words** [comment]
use tag to distinguish fields.

**Comment by nickfiacco-bolt** [comment]
If I use column tags, then I’d have to rename all the columns in my query right?

**Comment by jinzhu** [comment]
> If I use column tags, then I’d have to rename all the columns in my query right?
> 
> It would be cool if there was a table tag.

For most DB driver, it doesn't include the table name in the query result, so can't support that...
