### ISSUE TITLE
GORM Quick Start returns error

### ISSUE THREAD

**Issue by g00nix** [go-gorm/gorm#3054]
### What version of Go are you using (`go version`)?
go version go1.14.4 linux/amd64

### Which database and its version are you using?
sqlite

### Please provide a complete runnable program to reproduce your issue.
Example can be found here: https://gorm.io/docs/#Quick-Start

Returns this error:
```
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
```

**Comment by g00nix** [comment]
Fixed with:
```
export CGO_ENABLED=1
export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"
```

However some note should be add to the docs to circumvent current issues with gcc 10.

**Comment by popsUlfr** [comment]
That is not an error, just a warning. SQLite3 compiles fine :)
