### ISSUE TITLE
ErrorCodes support

### ISSUE THREAD

**Issue by tanweerdev** [go-gorm/gorm#3056]
Gorm should have Proper Error codes support (starting with Postgres)
https://www.postgresql.org/docs/10/errcodes-appendix.html
https://www.postgresql.org/docs/12/errcodes-appendix.html

A possible proposal/structure about how to implement Error codes is very much welcome(@jinzhu ) and I will make sure to implement it accordingly

Note: I have years of experience with Ecto/Elixir and medium level experience in Golang world.

**Comment by jinzhu** [comment]
Hello @tanweerdev 

Seems we don't need to do anything, you can use it like:

```go
var pqerr *pq.OpError
if errors.As(err, &pqerr) {
  pqerr.Code.Name()
}
```
Refer 
https://github.com/lib/pq/blob/8ae9eeaa02388a26cd5586023a0c4166c021a83d/error.go#L25-L53
