### ISSUE TITLE
Is it necessary to wrap multiple select operations in a transaction.

### ISSUE THREAD

**Issue by Hanggi** [go-gorm/gorm#3058]
I found a quite popular realword application which using gorm.

[code link](https://github.com/gothinkster/golang-gin-realworld-example-app/blob/master/articles/models.go#L114)
```
tx := db.Begin()
tx.Where(condition).First(&model)
tx.Model(&model).Related(&model.Author, "Author")
tx.Model(&model.Author).Related(&model.Author.UserModel)
tx.Model(&model).Related(&model.Tags, "Tags")
err := tx.Commit().Error
```

I know gorm perform single `create`, `update`, `delete` operations in transactions by default.

But in this code line, there are only select operations.

Are there any benefits wrap multiple section operations in a transaction besides it ensures database data integrity? or something about performance?

**Comment by jinzhu** [comment]
Not necessary, and it could use `Preload` to simplify the code
