### ISSUE TITLE
gorm v2 支持了context，请问如何实现context追踪sql调用

### ISSUE THREAD

**Issue by duguying** [go-gorm/gorm#3059]
gorm v2 支持了context，请问如何实现context追踪sql调用。

我有这么个场景：在gin的context中收集当前请求的所有sql调用语句，并且给接口返回，以便调试追踪。gorm v2支持了context，请问如何实现sql语句追踪

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/blob/master/logger/logger.go#L130
