### ISSUE TITLE
How to elegantly implement conditional batch update in a transaction？

### ISSUE THREAD

**Issue by cnsilvan** [go-gorm/gorm#3065]
### What version of Go are you using (`go version`)?
1.14
### Which database and its version are you using?
mysql 5.7
gorm 0.2.8
```go
package main

import (
      "gorm.io/gorm"
     "gorm.io/driver/mysql"
)

func main() {

tx := orm.Begin()
for _, v := range values {
   updates:=make(map[string]interface{})
   updates[x]=v.xxx
   tx = tx.Model(v).Where("version = ?", v.Version).Updates(updates)
   //the first time was right `update xxxx where version=xxx`
  // but the second time is `update xxxx where version=xxx and version=xxx ....`
  // in gorm v1 , I need to call `tx.New` every time to clear `where condition`


  // Q1: do I need to recall `tx.Begin` after the `tx.New` method is called?

  // Q2: can i use inline condition for updating method(like db.Updates(updates, " xxx= ?", "xxx")))?
}
}
```

**Comment by jinzhu** [comment]
Hi @cnsilvan 

No, we don't have such a method, please use `Where`, thank you.

**Comment by cnsilvan** [comment]
> Hi @cnsilvan
> 
> No, we don't have such a method, please use `Where`, thank you.

but I need to update data conditionally in a loop, this `Where` condition will be passed to the back

**Comment by jinzhu** [comment]
> > Hi @cnsilvan
> > No, we don't have such a method, please use `Where`, thank you.
> 
> Hi @jinzhu
> but I need to update data conditionally in a loop, this `Where` condition will be passed to the back

You can still use the `Where`?

**Comment by cnsilvan** [comment]
tx = tx.Model(v).Where("version = ?", v.Version).Updates(updates)
 in a loop ,the first time was right `update xxxx where version=xxx`
 but the second time is `update xxxx where version=xxx and version=xxx ....`

this is a problem in the v1 version(I solve it with each orm.New). Has v2 changed to no longer pass 'where' conditions by default?

**Comment by cnsilvan** [comment]
> > > Hi @cnsilvan
> > > No, we don't have such a method, please use `Where`, thank you.
> > 
> > 
> > Hi @jinzhu
> > but I need to update data conditionally in a loop, this `Where` condition will be passed to the back
> 
> You can still use the `Where`?
```go
tx = tx.Model(v).Where("version = ?", v.Version).Updates(updates)
```
in a loop ,the first time was right update xxxx where version=xxx
but the second time is update xxxx where version=xxx and version=xxx ....

this is a problem in the v1 version(I solve it with each orm.New). Has v2 changed to no longer pass 'where' conditions by default?

**Comment by jinzhu** [comment]
Hi, need to use the `Session` method in this case, refer

https://github.com/go-gorm/gorm/issues/2886#issuecomment-647196826

**Comment by cnsilvan** [comment]
> Hi, need to use the `Session` method in this case, refer
> 
> [#2886 (comment)](https://github.com/go-gorm/gorm/issues/2886#issuecomment-647196826)

thanks
