### ISSUE TITLE
Is it possible to set offset in ID for a table?

### ISSUE THREAD

**Issue by vincegio** [go-gorm/gorm#3067]
### What version of Go are you using (`go version`)?
go version go1.14.4 linux/amd64

### Which database and its version are you using?
psql (PostgreSQL) 12.3

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
No real issue so I feel this part might be worthless.

My question is about the db model structs and the ID.
The field is such: `ID        uint       gorm:"primary_key" json:"id"` <- (Couldn't have backticks around the tag)

Is it possible to offset this ID so that the first entry in the database begins on a custom number? let's say 18900 (stars in this repo ;))

I know it is possible to do manually, but is it possible through gorm?

**Comment by jinzhu** [comment]
sorry, no general solution for this, but you can `Exec` to run raw SQL
