### ISSUE TITLE
为什么使用db.create后，自动返回 select block_id from  main_block 查询呢，

### ISSUE THREAD

**Issue by Molecular-Future** [go-gorm/gorm#3068]
![image](https://user-images.githubusercontent.com/63218443/85134575-4f505480-b26f-11ea-86f2-7c78e76c2fae.png)
为什么使用db.create后，自动返回 select block_id from  main_block 查询呢，

**Comment by Molecular-Future** [comment]
block_id 是table主键

**Comment by Molecular-Future** [comment]
![image](https://user-images.githubusercontent.com/63218443/85134732-8de60f00-b26f-11ea-9ac3-eb601b39ff06.png)

**Comment by jinzhu** [comment]
What's your model definition?

**Comment by Molecular-Future** [comment]
![image](https://user-images.githubusercontent.com/63218443/85189122-6f6b2c80-b2de-11ea-8cfa-8633730f508c.png)
![image](https://user-images.githubusercontent.com/63218443/85189129-7db94880-b2de-11ea-9305-3ce09201b143.png)

**Comment by Molecular-Future** [comment]
上面是我定义的model。很奇怪为啥db.create 会默认查询一次呢

**Comment by Molecular-Future** [comment]
![image](https://user-images.githubusercontent.com/63218443/85189171-cbce4c00-b2de-11ea-9bf7-2f1ae216640f.png)

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/85215853-cb9e8100-b3b0-11ea-8144-18df48de37ef.png)

due to the wrong tag definition, which  triggers https://github.com/jinzhu/gorm/blob/master/callback_create.go#L177

**Comment by Molecular-Future** [comment]
thanks
