### ISSUE TITLE
Many2Many cross association

### ISSUE THREAD

**Issue by voodoo-dn** [go-gorm/gorm#3069]
Hello. My user can be duplicate or multiaccount of another user.
If user A detected as duplicate of user B, then must be second relation in DB:

```
id | multi_account_id
--------------------
A | B
B | A
--------------------
```

```
type User struct {
    ID            uuid.UUID   `gorm:"primary_key;type:uuid"`
    Duplicates    []*User   `gorm:"many2many:fraud_player_duplicates;association_jointable_foreignkey:duplicate_user_id"`
}
func (p *User) AssignDuplicate(duplicate *User) {
	duplicate.Duplicates = append(duplicate.Duplicates, p)
	p.Duplicates = append(p.Duplicates, duplicate)
}
```
But when I use `db.Save()` - creates infinite loop of inserts.

Could gorm insert many2many cross relation on Save or I must use custom inserts for it?

Thanks.

**Comment by jinzhu** [comment]
GORM v2 should fixed the single table many2many relationship.
