### ISSUE TITLE
raw不生效.也不会报错.但是exec执行成功.结果正确.

### ISSUE THREAD

**Issue by bearcat-panda** [go-gorm/gorm#3077]
go1.13.1
sqlite

strSql := `update blog_token
				set ` + accessToken + ` = "` + accessTokenValue +
		`", ` + refreshToken + `="` + refreshTokenValue +
		`" where user_id = ?`
	
	//Raw 执行语句没有生效.(但是也没有报错)
	if err := initialization.DB.Exec(strSql, id).Error; err != nil {
		seelog.Error(err)
		return err
	}

**Comment by jinzhu** [comment]
Hello,

Could you create a reproducible pull request here? https://github.com/go-gorm/playground

Thank you.
