### ISSUE TITLE
Update statement generation error If there is an inherited structure

### ISSUE THREAD

**Issue by cnsilvan** [go-gorm/gorm#3080]
Hi @jinzhu 
### What version of Go are you using (`go version`)?
go 1.14
### Which database and its version are you using?
mysql 5.7
gorm:0.2.14
### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
package main

import (
	"gorm.io/gorm"
        "gorm.io/driver/mysql"
)
type BaseDB struct {
        CreatedTime *time.Time 
	Version     int32     
}
type User struct {
	BaseDB
	Name    string 
         ......
}
func main() {
    model:=&User{version:12}
   
    db.Model(model).Where("version = ?", 12).Updates(map[string]interface{}{"version":13,"name":"张三"})
   // It will generate sql like this
  //v2: UPDATE `xxx` SET `base_db`="{<nil>  12}",`name`="张三",`version`=13 WHERE version = 12 AND `id` = 1
  // v1: UPDATE `xxx` SET `name`="张三",`version`=13 WHERE version = 12 AND `id` = 1
}
```

**Comment by jinzhu** [comment]
Generated correct SQL for me, 

```go
	type BaseDB struct {
		CreatedTime *time.Time
		Version     int32
	}
	type User struct {
		BaseDB
		Name string
	}
	model := &User{}
	DB.Model(model).Where("version = ?", 12).Updates(map[string]interface{}{"version": 13, "name": "张三"})
```

// UPDATE `users` SET `name`="张三",`version`=13 WHERE version = 12

**Comment by cnsilvan** [comment]
there is a problem with the `Updates map`, the old version will ignore the undeclared value in struct by default, but the new version will panic.

**Comment by jinzhu** [comment]
Havn't panic for me.

![image](https://user-images.githubusercontent.com/6843/85486940-34c70400-b5fe-11ea-985e-18aa0fb3b22e.png)

![image](https://user-images.githubusercontent.com/6843/85486916-2c6ec900-b5fe-11ea-983b-75a5a731498d.png)

**Comment by cnsilvan** [comment]
> Havn't panic for me.
> 
> ![image](https://user-images.githubusercontent.com/6843/85486940-34c70400-b5fe-11ea-985e-18aa0fb3b22e.png)
> 
> ![image](https://user-images.githubusercontent.com/6843/85486916-2c6ec900-b5fe-11ea-983b-75a5a731498d.png)

sorry, I am modifying my description.
you reply so fast! 
Thank you very much!

**Comment by jinzhu** [comment]
This is expected behavior in V2, so you can update columns that not defined. 

If you don't want to include it, you can use:

```go
db.Model(model).Omit("aaaaa").Updates(map[string]interface{}{"version": 13, "name": "张三", "aaaaaa": "aaa"})

// or 

db.Model(model).Select("version", "name").Updates(map[string]interface{}{"version": 13, "name": "张三", "aaaaaa": "aaa"})
```

**Comment by cnsilvan** [comment]
> This is expected behavior in V2, so you can update columns that not defined.
> 
> If you don't want to include it, you can use:
> 
> ```go
> db.Model(model).Omit("aaaaa").Updates(map[string]interface{}{"version": 13, "name": "张三", "aaaaaa": "aaa"})
> 
> // or 
> 
> db.Model(model).Select("version", "name").Updates(map[string]interface{}{"version": 13, "name": "张三", "aaaaaa": "aaa"})
> ```

thanks
