### ISSUE TITLE
Create Unique Index

### ISSUE THREAD

**Issue by efrengarcial** [go-gorm/gorm#3081]
Your issue may already be reported! Please search on the [issue track](https://github.com/go-gorm/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.14

### Which database and its version are you using?
mysq 8.0.20
gorm v0.2.14

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/go-gorm/gorm/blob/master/tests/docker-compose.yml) or please provides your config.

```go
package main

import (
	"log"
	"os"
	"time"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

type User struct {
	Id   int
	Name string    `gorm:"type:varchar(100);index:idx_name,unique"`
	Date time.Time `gorm:"index:idx_name,unique"`
}

var Default = logger.New(log.New(os.Stdout, "\r\n", log.LstdFlags), logger.Config{
	SlowThreshold: 100 * time.Millisecond,
	LogLevel:      logger.Info,
	Colorful:      true,
})

func main() {
	dsn := "root:password@tcp(localhost:3306)/db?charset=utf8&parseTime=True&loc=Local"
	db, _ := gorm.Open(mysql.Open(dsn), &gorm.Config{Logger: Default})

	_ = db.Migrator().DropTable(&User{})

	_ = db.AutoMigrate(&User{})

}

```
expected :

CREATE TABLE `users` (`id` bigint AUTO_INCREMENT,`name` varchar(100),`date` datetime(3) NULL,PRIMARY KEY (`id`),**UNIQUE KEY** idx_name (`name`,`date`))

or 

CREATE TABLE `users` (`id` bigint AUTO_INCREMENT,`name` varchar(100),`date` datetime(3) NULL,PRIMARY KEY (`id`),**UNIQUE INDEX** idx_name (`name`,`date`))

,but I get:

 CREATE TABLE `users` (`id` bigint AUTO_INCREMENT,`name` varchar(100),`date` datetime(3) NULL,PRIMARY KEY (`id`),**INDEX** idx_name (`name`,`date`))

BTW, How can I create an unique index from an existing table: db.Migrator().CreateIndex(??) ?

**Comment by Kisesy** [comment]
```go
type User struct {
	Id   int
	Name string    `gorm:"type:varchar(100);unique_index:idx_name"`
	Date time.Time `gorm:"unique_index:idx_name"`
}
```
