### ISSUE TITLE
运行2次后AutoMigrate生成的关联表有问题

### ISSUE THREAD

**Issue by szaquila** [go-gorm/gorm#3085]
package main

import (
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

type User struct {
	ID          int64        `json:"id" gorm:"primary_key;auto_increment"`
	Username    string       `json:"username" gorm:"column:username;type:varchar(150)"`
	Password    string       `json:"-" gorm:"column:password;type:varchar(128)"`
	Groups      []Group      `json:"groups,omitempty" gorm:"many2many:user_groups"`
	Permissions []Permission `json:"permissions,omitempty" gorm:"many2many:user_permissions"`
}

type Group struct {
	ID          int64        `json:"id" gorm:"primary_key;auto_increment"`
	Name        string       `json:"name" gorm:"column:name;type:varchar(150)"`
	Permissions []Permission `json:"permissions,omitempty" gorm:"many2many:group_permissions"`
	Users       []User       `json:"users,omitempty" gorm:"<-:update;many2many:user_groups"`
}

type Permission struct {
	ID            int64       `json:"id" gorm:"primary_key;auto_increment"`
	ContentTypeID int64       `json:"content_type_id" gorm:"column:content_type_id;type:integer"`
	Codename      string      `json:"codename" gorm:"column:codename;type:varchar(100)"`
	Name          string      `json:"name" gorm:"column:name;type:varchar(255)"`
	ContentType   ContentType `json:"content_type" gorm:"ForeignKey:content_type_id"`
	Checked       bool        `json:"checked,omitempty" gorm:"-"`
}

type ContentType struct {
	ID       int64  `json:"id" gorm:"primary_key;auto_increment"`
	AppLabel string `json:"app_label" gorm:"column:app_label;type:varchar(100)"`
	Model    string `json:"model" gorm:"column:model;type:varchar(100)"`
}

func main() {
	if db, err := gorm.Open(sqlite.Open("db.db3?loc=Asia/Shanghai"), &gorm.Config{}); err == nil {
		db.Exec("PRAGMA auto_vacuum=1;")
		db.Exec("vacuum;")
		db.AutoMigrate(
			User{},
			Group{},
			Permission{},
			ContentType{},
		)
	}
}

代码如上，第一次运行生成的数据库是正确的，第二次运行后group_permissions这个关联表多出了ContentType及Permission的内容

**Comment by jinzhu** [comment]
Hello, 

Could you create a reproducible pull request here? https://github.com/go-gorm/playground 

Thank you.
