### ISSUE TITLE
db.Find returns 0 as id

### ISSUE THREAD

**Issue by simonstumpf** [go-gorm/gorm#3087]
Hi guys, so I'm trying to fetch all results from a table wich works perfectly execept for the ID.
This always returns 0.

Does anybody know why?

`
var rules []Rule 
db.Table("fwrule").Find(&rules)
`

**Comment by jinzhu** [comment]
Hello,

Could you create a reproducible pull request here? https://github.com/go-gorm/playground

Thank you.

**Comment by simonstumpf** [comment]
Nvm i figured it out
I needed to add `gorm:"column:ID; PRIMARY_KEY"` to the struct.
