### ISSUE TITLE
Field with gorm:"-" is not set in query

### ISSUE THREAD

**Issue by efrengarcial** [go-gorm/gorm#3089]
Your issue may already be reported! Please search on the [issue track](https://github.com/go-gorm/gorm/issues) before creating one.

To report a bug, your issue *have to* include an [GORM playground pull request link](https://github.com/go-gorm/playground), for general questions, please delete below line.

## GORM Playground Link: https://github.com/go-gorm/playground/pull/6

**Comment by jinzhu** [comment]
Hello @efrengarcial 

Please refer: 
https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#field-permissions-support-readonly-writeonly-createonly-updateonly-ignored

We have introduced field permission support, supports: readonly, writeonly, createonly, updateonly, ignored

We should use `readonly` in this case.

```go
type User struct {
  Name string `gorm:"<-:create"` // allow read and create
  Name string `gorm:"<-:update"` // allow read and update
  Name string `gorm:"<-"`        // allow read and write (create and update)
  Name string `gorm:"->:false;<-:create"` // createonly
  Name string `gorm:"->"` // readonly
  Name string `gorm:"-"`  // ignored
}
```

**Comment by lime008** [comment]
@jinzhu  The read only fields are created with the migration. Is there any way to use the fields in the queries for aggregated values but ignore them in the migrations without creating a duplicate struct for queries?
