### ISSUE TITLE
Query with Group with table name

### ISSUE THREAD

**Issue by efrengarcial** [go-gorm/gorm#3090]
Your issue may already be reported! Please search on the [issue track](https://github.com/go-gorm/gorm/issues) before creating one.

To report a bug, your issue *have to* include an [GORM playground pull request link](https://github.com/go-gorm/playground), for general questions, please delete below line.

## GORM Playground Link: https://github.com/go-gorm/playground/pull/7

2020/06/25 19:01:09 /opt/go/apps/playground/main_test.go:31 no such column: users.name
[0.296ms] [rows:0] SELECT AVG(age) as age, name FROM `users` WHERE name LIKE "subquery_having%" AND `users`.`deleted_at` IS NULL GROUP BY `users.name` HAVING AVG(age) > (SELECT AVG(age) FROM `users` WHERE name LIKE "subquery_having%")

**Comment by jinzhu** [comment]
Hi @efrengarcial 

Thank you for your report, fixed that, please upgrade the database driver to latest version.
