### ISSUE TITLE
Firebird and gorm

### ISSUE THREAD

**Issue by chacalfloripa** [go-gorm/gorm#3091]
Hello, is there any way to use gorm with Firebird database?

Thank you.

**Comment by andytruong** [comment]
You can write custom plugin, they look simple:

- https://github.com/go-gorm/mysql
- https://github.com/go-gorm/sqlite
- https://github.com/go-gorm/postgres

**Comment by Hyejin** [comment]
@andytruong 
Hi, I'm trying to write custom dialect for Firebird 2.0. 
It only supports old-style `LIMIT()`, `OFFSET()` which uses `FIRST <num>` and `SKIP <num>`.
How can I write custom LIMIT and OFFSET clause?
Seems like GORMv1 has `LimitAndOffsetSQL` method in `Dialect` interface but `Dialector` of GORMv2 doesn't.

**Comment by jinzhu** [comment]
Hello @Hyejin 

Check out https://github.com/go-gorm/sqlserver/blob/master/sqlserver.go#L45, there is an example for how to

Thank you

**Comment by r03** [comment]
> @andytruong
> Hi, I'm trying to write custom dialect for Firebird 2.0.
> It only supports old-style `LIMIT()`, `OFFSET()` which uses `FIRST <num>` and `SKIP <num>`.
> How can I write custom LIMIT and OFFSET clauses on my own?
> Seems like GORMv1 has `LimitAndOffsetSQL` method in `Dialect` interface but `Dialector` of GORMv2 doesn't.

You can use [ROWS](https://firebirdsql.org/refdocs/langrefupd20-select.html#langrefupd20-select-rows) instead of FIRST.

**Comment by jianzhiyao** [comment]
Maybe https://github.com/nakagami/firebirdsql can help you
