### ISSUE TITLE
Does not update field changed in Hook when using DB.Updates

### ISSUE THREAD

**Issue by efrengarcial** [go-gorm/gorm#3092]
Your issue may already be reported! Please search on the [issue track](https://github.com/go-gorm/gorm/issues) before creating one.

To report a bug, your issue *have to* include an [GORM playground pull request link](https://github.com/go-gorm/playground), for general questions, please delete below line.

**Comment by jinzhu** [comment]
Thank you for your report, after a few days' thought, I bring back the `SetColumn` method, which should resolve your issue, and we also added a new `Changed` method, please check out https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#use-changed-to-check-fields-changed-or-not

Thank you.

**Comment by efrengarcial** [comment]
Thank you!
