### ISSUE TITLE
2.0是否支持查询后对数据处理?

### ISSUE THREAD

**Issue by lihaotian0607** [go-gorm/gorm#3094]
```
type User struct {
 Avatar string
}
```

在扫描到结构体之后给特定字段的值做处理,例如替换或者追加值 或者为每个结构体加一个回调 可以让自己修改下数据

**Comment by jinzhu** [comment]
`AfterFind`

**Comment by lihaotian0607** [comment]
> `AfterFind`

但是使用`Preload`被关联的对象好像不会执行 `AfterFind`

**Comment by lihaotian0607** [comment]
```go
package models

import (
	"gorm.io/gorm"
	"fmt"
)

type Comment struct {
    db     *gorm.DB 
    Id     int64 
    UserId int64
    User   User
}

type User struct {
    db     *gorm.DB 
    Id     int64
    Avatar string
}

// 这里不会执行
func (m User) AfterFind(db *gorm.DB) error {
    fmt.Println("UserAfterFind")
    m.Avatar = config.ossUrl + m.Avatar
    return nil
}

func (m *Comment) AfterFind(db *gorm.DB) error {
    fmt.Println("CommentAfterFind")
    return nil
}

func (m *Comment) List(){
    var rows []Comment
    m.db.Preload("User").Find(&rows)
}

```

**Comment by jinzhu** [comment]
这边建个可复现的PR https://github.com/go-gorm/playground

**Comment by lihaotian0607** [comment]
> 这边建个可复现的PR https://github.com/go-gorm/playground

https://github.com/go-gorm/playground/pull/10

**Comment by jinzhu** [comment]
不是测试过了么。。。。

**Comment by lihaotian0607** [comment]
> 不是测试过了么。。。。
userAfterFind 没输出
![image](https://user-images.githubusercontent.com/32523475/86124585-fd7cb980-bb0d-11ea-9c92-4b7a4f494212.png)
![image](https://user-images.githubusercontent.com/32523475/86124719-27ce7700-bb0e-11ea-949b-be9b16a15ec8.png)

**Comment by lihaotian0607** [comment]
> 不是测试过了么。。。。

只是提交了个例子,需要重新提交么?

**Comment by jinzhu** [comment]
确实如果slice为指针的情况下有问题，已修复，更新到 v0.2.19
