### ISSUE TITLE
求指定事务级别的api

### ISSUE THREAD

**Issue by fwhezfwhez** [go-gorm/gorm#3095]
暂时没有找到指定事务级别的api，所以使用时，只能这样做:
```go
tran, e := db.DB.DB().BeginTx(context.Background(), &sql.TxOptions{
		Isolation: 2,
})
```

这么做，在处理查询结果时，就只能使用官方的方式:
```go
       var uss = make([]User,0,10)
	for rs.Next() {
		var us User
		dataRs.Scan(us.Name, us.Age, us. ......)
		uass = append(uss, us)
	}
```

这里比较难受的地方，就是Scan里面要按照列顺序指定列，并且表的新增列的操作，会造成这里异常。

所以，我想知道，gorm方便提供指定事务级别的api吗，如果不方便，求一个方法`func RowScan(*sql.Rows ,dest interface{}) `，使用时:
```go
RowScan(rs, &uss)
```

**Comment by fwhezfwhez** [comment]
谢谢！

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/blob/master/finisher_api.go#L383

**Comment by fwhezfwhez** [comment]
emmm,seems my gorm version is lower
