### ISSUE TITLE
Panic when using anonymous structure in query

### ISSUE THREAD

**Issue by efrengarcial** [go-gorm/gorm#3096]
Your issue may already be reported! Please search on the [issue track](https://github.com/go-gorm/gorm/issues) before creating one.

To report a bug, your issue *have to* include an [GORM playground pull request link](https://github.com/go-gorm/playground), for general questions, please delete below line.

**Comment by jinzhu** [comment]
Fixed https://github.com/go-gorm/gorm/commit/9075b33620f14a62680d0c296522243874be2700, thank you for your report.

And we will select only the smaller struct's fields when querying data

```go
var entity = struct {
  ID int64
}{}

 DB.Model(&User{}).Select("id").First(&entity, user.ID) // Select("id") is not necessary
```
