### ISSUE TITLE
Updates() with no ID in the WHERE statement

### ISSUE THREAD

**Issue by rwngallego** [go-gorm/gorm#3097]
This is happening in v1.9.13:

If the struct somehow is empty (not loaded from the DB), it does a dangerous massive UPDATE without an ID in the WHERE statement:

```go
db.LogMode(true)
var brand = catalog.Brand{Name: "Apple"}
db.Model(&brand).Updates(map[string]interface{}{"name": "Apple updated"})
```

```sql
[2020-06-30 21:33:19] [4.71ms] UPDATE "brands" SET "name" = 'Apple updated', "updated_at" = '2020-06-30 21:33:19' WHERE "brands"."deleted_at" IS NULL
[2 rows affected or returned ]
```

See: 2 rows affected. What if you have a bug like this in production and it does a massive UPDATE over thousands of records?

In V2 (0.2.15), it looks like it's correctly handled:

```sql
playground/main_test.go:31 WHERE conditions required
[0.197ms] [rows:0] UPDATE `users` SET `name`="test name",`updated_at`="2020-06-30 22:38:20.992"
```

**Comment by jinzhu** [comment]
GORM V1 has `BlockGlobalUpdate` mode, V2 enabled it by default.

**Comment by rwngallego** [comment]
Thank you @jinzhu. I'm curious, why do you keep this as false in V1?

**Comment by jinzhu** [comment]
Compatibility with an earlier version
