### ISSUE TITLE
Alias keyword "AS" doesn't works in Table func

### ISSUE THREAD

**Issue by blancinot** [go-gorm/gorm#3104]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/23

## Description

Hello,

the alias keyword "AS" doesn't works directly in db.Table().
Tested with gorm v2 (v0.2.19).

```golang
db.Table("sp.my_table AS my_table_alias").Find(&obj)
```

is translated into

```sql
SELECT * FROM "sp"."my_table AS my_table_alias";
```

instead of

```sql
SELECT * FROM "sp"."my_table" AS "my_table_alias";
```

Thx for the great work.

**Comment by jinzhu** [comment]
Hi @blancinot 

Could you describe your use case with this? Thank you.

**Comment by blancinot** [comment]
Sorry for the late response...
I add an use case in the playground: https://github.com/go-gorm/playground/pull/23

**Comment by jinzhu** [comment]
Thank you for your report, fixed.
