### ISSUE TITLE
WithContext timeouts do not work

### ISSUE THREAD

**Issue by ItsLeeOwen** [go-gorm/gorm#3105]
```go
ctx, cancel := context.WithTimeout(context.Background(), time.Second*1)
defer cancel()

return db.WithContext(ctx).Exec("SELECT pg_sleep(10)").Error
```

In the example above I would expect a deadline exceeded error returned, however the full 10 seconds elapse, and no error is returned.

**Comment by ItsLeeOwen** [comment]
If this is an issue with the underlying github/lib/pq library, maybe consider using https://github.com/jackc/pgx

**Comment by jinzhu** [comment]
Switched to pgx as default driver, please upgrade gorm/postgres to v0.2.5
