### ISSUE TITLE
`Updates` 是否需要支持 `slice`

### ISSUE THREAD

**Issue by SmallTianTian** [go-gorm/gorm#3107]
## Your Question

既然已经有了[批量插入](https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft-CN#%E6%89%B9%E9%87%8F%E6%95%B0%E6%8D%AE%E6%8F%92%E5%85%A5)，那是否能统一提供其他批量操作，例如**更新**、**删除**？

**Comment by jinzhu** [comment]
https://v2.gorm.io/docs/update.html#Batch-Updates
https://v2.gorm.io/docs/create.html#Upsert-On-Conflict

**Comment by waiting0729** [comment]
@jinzhu 大佬 网址不能打开呢

**Comment by jinzhu** [comment]
看起来网页重定向坏了，把前面的 v2. 去掉就好

**Comment by rebider** [comment]
如果每个row的更新内容都不一样 ，怎么操作？
