### ISSUE TITLE
Can we import "github.com/go-gorm/gorm" ?

### ISSUE THREAD

**Issue by AbbyDeng** [go-gorm/gorm#3110]
Your Question

Hi Jinzhu, 
in my project I import "github.com/go-gorm/gorm", but when I run gazelle to auto-generate dependencies, it shows:
```
gazelle: finding module path for import github.com/go-gorm/gorm: exit status 1: go: finding module for package github.com/go-gorm/gorm
go: found github.com/go-gorm/gorm in github.com/go-gorm/gorm v1.9.12
go: github.com/go-gorm/gorm: github.com/go-gorm/gorm@v1.9.12: parsing go.mod:
	module declares its path as: github.com/jinzhu/gorm
	        but was required as: github.com/go-gorm/gorm
```

do you suggest import "github.com/go-gorm/gorm" or "github.com/jinzhu/gorm" ? thanks!

**Comment by AbbyDeng** [comment]
I guess we are using the V1, which is "github.com/jinzhu/gorm"

**Comment by jinzhu** [comment]
Yes, we changed the import path for V2, checkout https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft#install
