### ISSUE TITLE
What is the Max Number of Concurrent Queries

### ISSUE THREAD

**Issue by AtakanColak** [go-gorm/gorm#3112]
## Your Question

Hello, I'm wondering about max number of concurrent queries I can do with GORM. It is only said that I can use a DB concurrently but a limit is not specified in docs. If the limit depends on external factors such as network I/O, what would be a pleasant way to measure it? I couldn't find any related entries about this. 

Thank you.

## Expected answer

Answers such as;

1. Hard limit is 100 queries. 
2. Limit depends on **** which you can measure by ****
3. GORM combines concurrent queries into a single packet so dont worry about it. 
4. See this video/doc/post

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm.io/blob/v2/pages/docs/connecting_to_the_database.md#connection-pool
