### ISSUE TITLE
How to use sql query with ? as part of the query

### ISSUE THREAD

**Issue by aditya1808** [go-gorm/gorm#3113]
## Your Question
Hi, im using grom in my current setup
postgresql DB and latest grom.

I have a sql query which has "?" in the query. How do we deal with this in gorm?
We use ? as parameterized query but is there a way to have "?" in the query itself and also use ? for parameterized query?

**db = db.Where("jsonb_path_exists(parameters,? ? (@ == ?))", key, "?",values[0])**  --> this doesnt work

**Comment by jinzhu** [comment]
https://v2.gorm.io/docs/data_types.html#Clause-Expression
