### ISSUE TITLE
Multiple many2many in single struct

### ISSUE THREAD

**Issue by w4-hanggi** [go-gorm/gorm#3114]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

I'm using gorm v0.2.19

```go
type User struct {
	gorm.Model

	RecentlyViewedServices []Service `gorm:"many2many:recently_viewed_services;"`
	FavoriteServices       []Service `gorm:"many2many:favorite_services;"`
}
```

The first many2many is always ignored, the relation table of 'recently_viewed_services' will not be created.
And association for (Association("RecentlyViewedServices")) will update to FavoriteServices.

Is it a bug?
Or I made some mistakes?

Thank you.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/blob/master/tests/multi_primary_keys_test.go
