### ISSUE TITLE
If there are union and soft delete at the same time,  a  SQL syntax will exist. 当我们同时使用union和软删除，将会有语法错误。

### ISSUE THREAD

**Issue by Froyo91** [go-gorm/gorm#3116]
## What version of Go are you using (go version)?
go version go1.14.2

## Which database and its version are you using?
5.7.25-TiDB-v3.0.4

## gorm version
v1.9.11

## my code:
(beacuse i cannot provide the mysql envionment so i just provide the sql string)因为我无法提供sql环境，因此我只是提供了sql语句作为例子
`
err := sqlDB.tiDb.Raw("(select `id`, `name`, `real_name`, `register_ip`, `created_at`, `last_login_ip`, `last_login_at`, `top_id` from `members` where `real_name` = ? and `id` != ?)"+
		" union "+
		"(select `id`, `name`, `real_name`, `register_ip`, `created_at`, `last_login_ip`, `last_login_at`, `top_id` from `members` where `register_ip` = ? and `id` != ?) "+
		"order by `created_at` desc, `id` desc "+
		"limit ? offset ?",
		member.RealName, member.ID, member.RegisterIp, member.ID, pageSize, (page-1)*pageSize).Find(&members).Error
`

And In my table there is column which is "deleted_at". 并且在我的表中有一个 字段是 deleted_at 。
So the sql string above will contain soft delete. 因此上述sql会触发软删除。

## Error
`Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 6 near \"WHERE members.deleted_at IS NULL AND (((select id, name, real_name, register_ip, created_at, last_login_ip, last_login_at, top_id from members where real_name = ? and id != ?) union (select id, name, real_name, register_ip, created_at, last_login_ip, last_login_at, top_id from members where register_ip = ? and id != ?) order by created_at desc, id desc limit ? offset ?)\`

**So there is a extra '('.  
因此多了一个额外的 '('。**
the gorm generates a sql string which has SQL syntax. gorm为我生成的sql有语法错误，多了一个括号。
Please check this. 
Thank you very much.

**Comment by jinzhu** [comment]
it should works https://github.com/go-gorm/gorm/blob/master/tests/sql_builder_test.go#L132 or please create a PR in  https://github.com/go-gorm/playground

**Comment by iHDJ** [comment]
我想问下这个问题最终是怎么解决的，因为我也遇到了相同的问题

**Comment by Froyo91** [comment]
> 我想问下这个问题最终是怎么解决的，因为我也遇到了相同的问题

如果没用到deleted_at字段，就加上Unscoped() 试试吧~
http://gorm.io/zh_CN/docs/delete.html    

// Unscoped 方法可以查询被软删除的记录
db.Unscoped().Where("age = 20").Find(&users)
//// SELECT * FROM users WHERE age = 20;
