### ISSUE TITLE
0值可更新作为一个可选项，而不是强制项

### ISSUE THREAD

**Issue by ssszzzLiiiShuai** [go-gorm/gorm#3117]
## Describe the feature

有的场景下，0值也是需要写入到库里面的。但是db.update 传入 map 代码实在是不美观 ，这样我定义model 也没什么意义了。
还是希望0值更新能够作为一个可选功能，让用户可以通过 db.select([]string{字段列表}).update(model) 来更新。

## Motivation

优化业务逻辑

**Comment by jinzhu** [comment]
https://v2.gorm.io/docs/update.html#Update-Updates
