### ISSUE TITLE
没有解决SQL注入的问题，请问有什么好的方案可以处理吗？

### ISSUE THREAD

**Issue by 380233718** [go-gorm/gorm#3118]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

**Comment by 380233718** [comment]
控制台打印出来的日志是没有解决防注入的，但是实际运行好像不行，所应该解决控制台SQL输出的问题。

**Comment by jinzhu** [comment]
https://v2.gorm.io/docs/security.html
