### ISSUE TITLE
[error] unsupported data type: &[] ([]string)

### ISSUE THREAD

**Issue by chabad360** [go-gorm/gorm#3122]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/20

## Description

I'm attempting to use a data structure that contains a `[]string`, however I get the following error instead:

```
[error] unsupported data type: &[]
```

**Comment by jinzhu** [comment]
Yes, it is known as not supported.

```go
Models are normal structs with basic Go types, pointers/alias of them or custom types implementing Scanner and Valuer interfaces
```

`[]string` is not a basic golang type.

**Comment by jinzhu** [comment]
(as database/sql doesn't support that)

**Comment by chabad360** [comment]
Any suggestions on how to get around that?
