### ISSUE TITLE
how to  select id  field to []int 

### ISSUE THREAD

**Issue by timchenxiaoyu** [go-gorm/gorm#3128]
how to  select id  field to []int

**Comment by timchenxiaoyu** [comment]
// GORM_REPO: https://github.com/go-gorm/gorm.git
// GORM_BRANCH: master
// TEST_DRIVERS: sqlite, mysql, postgres, sqlserver

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/issues/3122#issuecomment-655880129
