### ISSUE TITLE
Association.Clear does not remove rows from db

### ISSUE THREAD

**Issue by raphaelvigee** [go-gorm/gorm#3130]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/22

## Description

Calling `Association().Clear()` or replacing a model association field value and saving does not delete rows from db

**Comment by raphaelvigee** [comment]
To add a bit more details, trying to `Save` source having changed the `Layers` does not delete remove layers (not sure if thats expected)

**Comment by jinzhu** [comment]
Hello @raphaelvigee 

It's hard for me to understand each issue's context, and prepare an environment to test if GORM has an issue, so make sure the project is healthily maintained, we only accept bug reports having a playground pull request link.

Thank you for your understanding.

**Comment by raphaelvigee** [comment]
Hi @jinzhu 

I fully understand. I simply didnt have time yesterday to create the playground PR. Issue has been updated with PR.

**Comment by jinzhu** [comment]
Hello, 

Checked your PR, this is expected behavior, and it is documented,  check out:

`Clear` remove all reference between source & association, won’t delete those associations

http://v2.gorm.io/docs/associations.html#Clear-Associations

Saved with zero associations won't delete associations or I think it will mess up your data

**Comment by raphaelvigee** [comment]
Hum right, if its a strict one to many relationship, deleting the parent should delete the child too, right ?

On a side note, my original problem was cause by me calling `.Model(value).Association("xxx")`, where value was a pointer of a pointer of a value, this would just fail silenty, this should panic.

**Comment by jinzhu** [comment]
> Hum right, if its a strict one to many relationship, deleting the parent should delete the child too, right ?

http://v2.gorm.io/docs/constraints.html#Foreign-Key-Constraint
