### ISSUE TITLE
v2  Scan result to map，how to specify the value type

### ISSUE THREAD

**Issue by cai88112** [go-gorm/gorm#3131]
##  I use map[string]interfacce{} for results,i got the type of value is uint8
I don't create the model
![image](https://user-images.githubusercontent.com/7733194/87112447-65659980-c29e-11ea-91a9-fb132bb75921.png)

![image](https://user-images.githubusercontent.com/7733194/87112422-541c8d00-c29e-11ea-955c-368aa791c849.png)

## 
How can i specify the value type to string or int 
I try to declare map[string]string ,it will panic

**Comment by jinzhu** [comment]
The data type is not controlled by GORM when querying with `map`
