### ISSUE TITLE
hope to recognize the default values

### ISSUE THREAD

**Issue by synuwxy** [go-gorm/gorm#3132]
## Describe the feature

go语言里面的很多默认值十分频繁的涉及到常用的业务值，比如int类型的0，bool类型的false。如果gorm完全不识别这些默认值会导致很多地方必须要做出特殊的处理从而破坏代码可读性。采取指针传入的方式也会有此类问题，这会导致很多业务场景下为了配合gorm强行做的指针转换。

建议gorm识别基础类型的默认值，把对默认值的判断交给用户决定

**Comment by jinzhu** [comment]
https://v2.gorm.io/docs/update.html
