### ISSUE TITLE
support add field

### ISSUE THREAD

**Issue by Turing-Chu** [go-gorm/gorm#3137]
## Your Question

I want to add field if field not in table. 

just find ModifyColumn and find the following code :

```golang
func (s mysql) ModifyColumn(tableName string, columnName string, typ string) error {
	_, err := s.db.Exec(fmt.Sprintf("ALTER TABLE %v MODIFY COLUMN %v %v", tableName, columnName, typ))
	return err
}

```

but it not support add field because it use `MODIFY COLUMN %v`

## Expected answer

you can support add/modify column:

if has column then alter modify column
else alter add column

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/migration.html
