### ISSUE TITLE
Rule   int32 `gorm:"column:rule;default:200"`

### ISSUE THREAD

**Issue by Molecular-Future** [go-gorm/gorm#3140]
## Your Question
model define default:200, db.create(&m), Will automatically query once，

[2020-07-13 11:49:29]  [89.22ms]  SELECT `rule` FROM `evfs_storage`  WHERE (req_id = '0x3d207a1fd830d11c82e77b02db1def9a717d0da8a18ebcf53aa10c4f20cdbbb0')  

![image](https://user-images.githubusercontent.com/63218443/87269283-46b20d80-c4ff-11ea-8a0b-9d92a7f51d01.png)
![image](https://user-images.githubusercontent.com/63218443/87269296-53366600-c4ff-11ea-833c-e613b1d57a97.png)
![image](https://user-images.githubusercontent.com/63218443/87269325-706b3480-c4ff-11ea-948c-2bbb96aa6a04.png)

**Comment by jinzhu** [comment]
V2 won't query that, V1 you can disable this by removing `gorm:force_reload_after_create` from create callbacks

**Comment by Molecular-Future** [comment]
github.com/go-gorm/gorm: github.com/go-gorm/gorm@v0.2.20 这个是2.0地址么

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/wiki/GORM-V2-Release-Note-Draft-CN
