### ISSUE TITLE
How can i  create virtual key and set expression

### ISSUE THREAD

**Issue by elemyin** [go-gorm/gorm#3143]
## Your Question

Excuse me:
i want create virtual key and set expression when i create my table, What should I do?looking forward to your reply, thanks

**Comment by elemyin** [comment]
![1594635694(1)](https://user-images.githubusercontent.com/37828742/87294014-b8a54980-c535-11ea-8e50-6700b7fc0bb5.jpg)

**Comment by jinzhu** [comment]
Hi

You can set its type like:

```go
type User struct {
 Name string `type:"char(41) GENERATED ALWAYS AS (concat(firstname,' ',lastname))"`
}
```

**Comment by elemyin** [comment]
@jinzhu 
ok,I have found it today,thanks
