### ISSUE TITLE
Fork query builder

### ISSUE THREAD

**Issue by raphaelvigee** [go-gorm/gorm#3147]
## Describe the feature

A new `Fork` function should be implemented on `DB` to allow branching the query builder.
It should fork the DB and carry the clauses and context

## Motivation

It would be nice to be able to construct a query builder and fork it to be able to add condition along

https://github.com/go-gorm/playground/pull/25

**Comment by raphaelvigee** [comment]
After loads of headscratching and hairpulling, I think this feature would be equivalent to doing (@jinzhu can you confirm ?):

```
tx.Session(&gorm.Session{
		WithConditions: true,
		PrepareStmt:    tx.PrepareStmt,
		Context:        tx.Statement.Context,
		Logger:         tx.Logger,
		NowFunc:        tx.NowFunc,
	})
```

Adding docs and/or a helper function would be greatly appreciated

**Comment by jinzhu** [comment]
Just use that should works: 

```go
tx = tx.Session(&gorm.Session{
	WithConditions: true,
})
```

**Comment by jinzhu** [comment]
Also, make sure you have checked http://v2.gorm.io/docs/scopes.html ;)

**Comment by raphaelvigee** [comment]
Oh right, maybe this needs docs clarification ? Its not straightforward to know exactly what `WithConditions` does

I check the scope docs, but that doesnt really solve my issue as I'm dynamically building a query.

Thank for your help
