### ISSUE TITLE
unsupported data type: <P>

### ISSUE THREAD

**Issue by raphaelvigee** [go-gorm/gorm#3148]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/26

## Description

`unsupported data type: <P>` when the GC runs between the clause and the finaliser with a new session

**Comment by jinzhu** [comment]
```go
tx = tx.Session(&gorm.Session{})
```

should be 

```go
tx = tx.Session(&gorm.Session{WithConditions: true})
```

**Comment by jinzhu** [comment]
Refer http://v2.gorm.io/docs/method_chaining.html for details
