### ISSUE TITLE
AutoIncrement adds Default 0

### ISSUE THREAD

**Issue by MurrayNick** [go-gorm/gorm#3152]
Choose to ignore and autoclose if you like, but your playground docs are grossly inadequate to understand what you need to report a bug.

Creating a column with an autoIncrement automatically adds default=0, which is an invalid value for an auto-increment column.

Tag:
Id uint32 `gorm:"autoIncrement;primaryKey;not null"`

Results in: 
`CREATE TABLE 'table_name' ('id' int unsigned AUTO_INCREMENT NOT NULL DEFAULT 0,...`

0 is not a valid default value for an auto-increment column and the create table fails.

**Comment by MurrayNick** [comment]
Bounce - bug is ligitimate - Playground instructions are inadequate.

**Comment by MurrayNick** [comment]
To summarise - autoincrement and default should not be used in the same statement, but this library auto appends default = 0.

**Comment by jinzhu** [comment]
Hi @MurrayNick 

Thank you for your report, fixed that.

BTW, just create a PR with the following code would work, it will show the creating SQL in the log, so I can easily get the idea.

Thank you.

```go
func TestGORM(t *testing.T) {
	type AutoIncrement struct {
		Id   uint32 `gorm:"autoIncrement;primaryKey;not null"`
		Name string
	}

	DB.Migrator().CreateTable(&AutoIncrement{})
}
```
