### ISSUE TITLE
Create is not returning the inserted id when not using uint as its type

### ISSUE THREAD

**Issue by lopes-gustavo** [go-gorm/gorm#3153]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

I'm slightly changing the `Create` example.
Changing `ID` from `uint` to `string` make `Create` not return the inserted `ID`.

```golang
type User struct {
	ID    string 
        Name  string
	Age   uint8
}
user := User{Name: "Jinzhu", Age: 18}
_ = db.Create(&user) // pass pointer of data to Create
```
This yields to: `INSERT INTO "users" ("id","name","age") VALUES ('','Jinzhu',18)`

To make it work, I have to "force" a wrong method for `default` tag, like:
```golang
type User struct {
	ID   string `gorm:"default:whatever()"`
	Name string
	Age  uint8
}
```
This yields correctly to `INSERT INTO "users" ("name","age") VALUES ('Jinzhu',18) RETURNING "id"`

I couldn't find a way to set the `DEFAULT` keyword, as gorm will make it a string and try to insert that as `"DEFAULT"`
```golang
type User struct {
	ID   string `gorm:"default:DEFAULT"`
	Name string
	Age  uint8
}
```
This yields to `INSERT INTO "users" ("id","name","age") VALUES ('DEFAULT','Jinzhu',18)`

---------

This is a breaking change, as with v1 `Create` would return the `id` without problems

**Comment by jinzhu** [comment]
Hi @lopes-gustavo 

Just use the real db func that generates default value here?

**Comment by MurrayNick** [comment]
Facing the smae problem. @jinzhu can you give a code example of what you mean by "just use the real db func"?

**Comment by jinzhu** [comment]
@MurrayNick  For example:

```go
type User struct {
	ID   string `gorm:"default:uuid_generate_v3()"`
	Name string
	Age  uint8
}
```

**Comment by lopes-gustavo** [comment]
It does work. It just seems "wrong" since the example in the documentation works seamlessly.
Maybe it's worth mentioning that on the docs? I'm sure a lot of people will face this problem, since this is a breaking change from v1.

**Comment by jinzhu** [comment]
Updated the doc, check it out http://v2.gorm.io/docs/create.html#Default-Values

**Comment by ctrlmaniac** [comment]
I'm having the same issue. Create method does not create an ID. I'm trying your solution but when I migrate the tables it says: `ERROR: function uuid_generate_v3() does not exist (SQLSTATE 42883)`

**Comment by pkpfr** [comment]
>  `ERROR: function uuid_generate_v3() does not exist (SQLSTATE 42883)`

Did you try v4()?  v3 is not commonly used because it uses MD5.  It also requires a namespace.

**Comment by ctrlmaniac** [comment]
yes, it does not exist!
