### ISSUE TITLE
Overridable table alias in statement

### ISSUE THREAD

**Issue by stevefan1999-personal** [go-gorm/gorm#3164]
## Motivation

https://github.com/go-gorm/gorm/blob/e77156980cd74639fefdaf0576785018464a3ca1/statement.go#L84

Here it is incompatible to Oracle SQL dialect which does not allow AS for aliasing (but OK without AS)

## Related Issues

#3156

**Comment by stevefan1999-personal** [comment]
bruh

**Comment by jinzhu** [comment]
Hi @stevefan1999-personal 

What it should be for Oracle?

**Comment by stevefan1999-personal** [comment]
@jinzhu Just empty

`LEFT JOIN Foo as bar` for most SQL dialects but not Oracle (syntax error)

`LEFT JOIN Foo bar` for Oracle but rarely any dialects (perhaps Oracle only)

**Comment by jinzhu** [comment]
Hello @stevefan1999-personal 

Could you please create a PR in https://github.com/go-gorm/playground with Oracle database and the wrong case? Thank you.

Please refer: https://blogs.oracle.com/developers/adventures-in-cicd-1-intro-getting-started-with-github-actions

**Comment by stevefan1999-personal** [comment]
@jinzhu well the problem is I'm not sure if I add new action manifest to the PR should it be ran as well, as you owned the repo you are the only one who could append Github Action runner...apparently from a POLP perspective.

**Comment by jinzhu** [comment]
> @jinzhu well the problem is I'm not sure if I add new action manifest to the PR should it be ran as well, as you owned the repo you are the only one who could append Github Action runner...apparently from a POLP perspective.

It should works if you forked playground repo, and enable GitHub actions in your fork, maybe it is better to do it like this before we finish the integration

**Comment by jinzhu** [comment]
Hello @stevefan1999-personal 

Thank you for your pull request, I tried to run it on my local, seems got this error when initializing, any idea?

```
[error] failed to initialize database, got error ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
2020/07/21 11:04:09 failed to connect database, got error ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help
```

**Comment by stevefan1999-personal** [comment]
@jinzhu ah, bugger, https://github.com/oracle/python-cx_Oracle/issues/92#issuecomment-335593931

**Comment by stevefan1999-personal** [comment]
https://github.com/go-gorm/playground/pull/42 stupid bot
