### ISSUE TITLE
module declares is error

### ISSUE THREAD

**Issue by penhauer-xiao** [go-gorm/gorm#3166]
go: finding module for package github.com/go-gorm/gorm
go: downloading github.com/go-gorm/gorm v0.2.22
go: found github.com/go-gorm/gorm in github.com/go-gorm/gorm v0.2.22
go: github.com/go-gorm/gorm: github.com/go-gorm/gorm@v0.2.22: parsing go.mod:
	module declares its path as: gorm.io/gorm
	        but was required as: github.com/go-gorm/gorm

**Comment by jinzhu** [comment]
Please refer document, use `gorm.io/gorm`
