### ISSUE TITLE
无法获取插入id

### ISSUE THREAD

**Issue by lihaotian0607** [go-gorm/gorm#3171]
### 版本 v0.2.23
> 关联写入的时候也无法写入关联id

### 代码
```go
       row := models.Article{Title: "article1"}

	if err := db.Create(&row).Error; err != nil {
		log.Fatal(err.Error())
		return
	}

	fmt.Println(row.Id)

	var rows = []models.Article{{Title: "article1"}, {Title: "article1"}}

	fmt.Println(rows)

	if err := db.Create(&rows).Error; err != nil {
		log.Fatal(err.Error())
		return
	}

	for _, item := range rows {
		fmt.Println(item.Id)
	}
```
### 数据表数据
![image](https://user-images.githubusercontent.com/32523475/87899205-0ca6b580-ca83-11ea-8277-af028558de59.png)
### 控制台输出
![image](https://user-images.githubusercontent.com/32523475/87899267-4081db00-ca83-11ea-917a-1ff6e15ac913.png)
### 表结构
![image](https://user-images.githubusercontent.com/32523475/87899288-4ecff700-ca83-11ea-93f0-00a590a3cb2c.png)

**Comment by lihaotian0607** [comment]
好像是自己的锅,之前的tag ```gorm:"type: bigint auto_increment  comment '主键'; primary_key"``` 升级到v2就不行了

**Comment by jinzhu** [comment]
> primary_key

现在好用了？没明白。。。

**Comment by lihaotian0607** [comment]
> > primary_key
> 
> 现在好用了？没明白。。。

之前的是: ```gorm:"type: int auto_increment comment '主键'; primary_key"```

改成 ```gorm:"primary_key"` `` 就好用了 !!!

**Comment by jinzhu** [comment]
> > > primary_key
> > 
> > 
> > 现在好用了？没明白。。。
> 
> 之前的是: `gorm:"type: int auto_increment comment '主键'; primary_key"`
> 
> 改成 `gorm:"primary_key"` 就好用了 !!!

应该修复了，再用原来的配置测试下看看吧？

**Comment by lihaotian0607** [comment]
> > > > primary_key
> > > 
> > > 
> > > 现在好用了？没明白。。。
> > 
> > 
> > 之前的是: `gorm:"type: int auto_increment comment '主键'; primary_key"`
> > 改成 `gorm:"primary_key"` 就好用了 !!!
> 
> 应该修复了，再用原来的配置测试下看看吧？

目前没找到确切的问题所在,在我本地和服务器上都会出现,但是用 `playground `去跑测试就不会出现,问题应该不大...

**Comment by jinzhu** [comment]
因为 playground 用的最新的master跑的，只有在这里修复了，等后续再发布个版本应该就可以了

**Comment by lihaotian0607** [comment]
> 因为 playground 用的最新的master跑的，只有在这里修复了，等后续再发布个版本应该就可以了

确实修复了 本地 replace gorm master 没问题!!!
