### ISSUE TITLE
How to use mysql JSON_CONTAINS function in Gorm

### ISSUE THREAD

**Issue by wgjak47** [go-gorm/gorm#3173]
## Your Question
how to use mysql json_contains function in Gorm
if I set like this: 
```
ret := dbutils.SlaveDB(DBName).
		Where("JSON_CONTAINS(sdu_ids, '?', '$')", 100).
		Find(&items)
```

will got 
```
sql: expected 0 arguments, got 1.
```

## Expected answer
the example code for using JSON_CONTAINS with gorm.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/datatypes
