### ISSUE TITLE
GORM ignoring fields / parsing fields wrong

### ISSUE THREAD

**Issue by tiehm** [go-gorm/gorm#3177]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/43

## Description

GORM fails to initialize ```ID uint `gorm:"type:mediumint;unsigned;primary_key;AUTO_INCREMENT;unsigned" json:"ID"``` correctly and does this instead ```CREATE TABLE `settings` (`id` mediumint,`discount_code` varchar(255) NOT NULL,PRIMARY KEY (`id`))```.

**Comment by jinzhu** [comment]
Refer Tags `type` http://v2.gorm.io/docs/models.html#Fields-Tags
