### ISSUE TITLE
Composite struct do not trigger hook

### ISSUE THREAD

**Issue by mai1015** [go-gorm/gorm#3178]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/44

## Description

The composite structure `Company` did not trigger both HOOK properly. UUID did not generate by the hook, but DateTime is generated as expected.

**Comment by jinzhu** [comment]
We will only support Hook methods that can be invoked from the outside model.

For your use case, please check out http://v2.gorm.io/docs/models.html#Auto-Creating-Updating-Time-Unix-Nano-Second
