### ISSUE TITLE
Manually create many to many table failed

### ISSUE THREAD

**Issue by mai1015** [go-gorm/gorm#3179]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/44
on the second commit

## Description

<img width="392" alt="QQ20200721-151346@2x" src="https://user-images.githubusercontent.com/5039212/88096822-40f2a280-cb65-11ea-9ded-d604f43e5f43.png">
Trying to manually create many to many table like this

```go
type User struct {
	gorm.Model
	Name      string
	Age       uint
// ...
}
type UserWork struct {
	User User `gorm:"foreignkey:id;association_foreignkey:uid;primary_key"`
	Work Work `gorm:"foreignkey:id;association_foreignkey:wid;primary_key"`
	CreatedAt time.Time
} // CreatedAt time denote the staring

type Work struct {
	ID   uint   `gorm:"primary_key"`
	Name string `gorm:"size: 30"`
	CreationDateTimeModel
}
```

At runtime, it will generate the following SQL

```sql
CREATE TABLE `user_verification_data` (`created_at` DATETIME NULL , PRIMARY KEY (`user`,`work`))
```

in playground, it causes a segment fault.

**Comment by jinzhu** [comment]
`UserWork` is an invalid model, it doesn't contain any primary key field, refer: http://v2.gorm.io/docs/many_to_many.html#Customize-JoinTable

**Comment by mai1015** [comment]
Thank you very much for your answer.
