### ISSUE TITLE
qor/validations with gorm v2

### ISSUE THREAD

**Issue by L1ghtman2k** [go-gorm/gorm#3180]
## Your Question

Hello,

I am using qor/validations for one of my projects to validate the field of certain structs.

After migrating to gorm v2 it seems like underlying callbacks made in qor/validations could not be used directly in v2. 

Is there a plan to adopt qor/validations for gorm v2, or are there alternative ways of validating structs fields (like how qor/validations used govalidator) or would it be up to users to port the functionality?

**Comment by jinzhu** [comment]
There is a plan, @raven-chen will work on upgrading QOR to gorm v2.

**Comment by lucascarvalho** [comment]
hi @jinzhu, do you have any updates on this?
