### ISSUE TITLE
how to globally disable association_autoupdate on v2?

### ISSUE THREAD

**Issue by moul** [go-gorm/gorm#3181]
On V1, I was able to set a global setting or in a structure tag, on V2 I can't find the best way to do it, I need to use `.Omit("blahblah")` manually on each create/update requests

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/associations.html#Skip-Auto-Create-Update

**Comment by schmittjoh** [comment]
In this regard, I found it quite useful to be able to declare on a model if I want to disable association handling like this:

```
PhoneNumber *PhoneNumber`gorm:"association_autoupdate:false;association_autocreate:false"`
```

From a look through the code base and documentation, it seems like this option is now gone. Is there an alternative or is it intended that this has to be set for each query now?

**Comment by jinzhu** [comment]
You can use https://gorm.io/docs/v2_release_note.html#Field-permissions for this.

**Comment by schmittjoh** [comment]
Thanks for the feedback. I've tried what you suggest. I assume you were referring to the `readonly` setting, i.e.

```
PhoneNumbers []PhoneNumber `gorm:"->"`
```

It seems like the field cannot be preloaded in that case anymore. For example, something like this is not possible:

```
db.Preload("PhoneNumbers").First(&user)
```

What happens here is a "nil pointer dereference" at https://github.com/go-gorm/gorm/blob/0b6ef3cb87b0f27247ac349383b5cded02d00293/callbacks/preload.go#L29 as `rel` is `nil` in that case.

**Comment by jinzhu** [comment]
@schmittjoh fixed, thank you for your report.
