### ISSUE TITLE
Want to add DefaultDeleteAt value for unique index

### ISSUE THREAD

**Issue by Aoi-hosizora** [go-gorm/gorm#3184]
## Playground

https://github.com/go-gorm/playground/pull/46

## Describe the feature

I hope the framework can set a default value for `delete_at` and set a non-null value.

Although I can use like this, but query process will work wrong. So in v1 I wrote a hook: https://github.com/Aoi-hosizora/ahlib-web/blob/master/xgorm/hook.go#L65

```go
DeletedAt gorm.DeletedAt `gorm:"default:'1999-01-01'"`
```

## Motivation

I want to make a `username` field unique(exclude deleted items), so I have to use a composite indexes. But unique index don't support `null` value, so default value of `delete_at` must not be `null`.

```go
type User struct {
	Id        uint64 `gorm:"primarykey"`
	Name      string `gorm:"type:varchar(255);uniqueIndex:uk_name_delete_at"`
	DeletedAt gorm.DeletedAt `gorm:"uniqueIndex:uk_name_delete_at;default:'1999-01-01'"`
	gorm.Model
}
```

**Comment by jinzhu** [comment]
If you are using postgres, you can check out how to use `where` with a unique index. http://v2.gorm.io/docs/indexes.html#Index-Tag

If you are using mysql, checkout `Upsert` http://v2.gorm.io/docs/create.html#Upsert-On-Conflict

Set default value for deleted at field doesn't seem right.

**Comment by Aoi-hosizora** [comment]
@jinzhu But how could I insert a record with a field (unique) value which is duplicated and has deleted? I only know this way (composite unique index).

**Comment by jinzhu** [comment]
Use `Upsert` when duplicate set `deleted_at` to `NULL`

**Comment by Aoi-hosizora** [comment]
@jinzhu Okay, Thx. Although my requirement is different with `Upsert`.

**Comment by DogBaoBao** [comment]
> @jinzhu Okay, Thx. Although my requirement is different with `Upsert`.

I think too. I want make `delete_at` to like `1987-06-05 04-03-02` used as other system, but no config can change this.

**Comment by jinzhu** [comment]
> > @jinzhu Okay, Thx. Although my requirement is different with `Upsert`.
> 
> I think too. I want make `delete_at` to like `1987-06-05 04-03-02` used as other system, but no config can change this.

Just checkout how the soft deleted implemented, and wrap your own one.
