### ISSUE TITLE
gorm.Open

### ISSUE THREAD

**Issue by icobani** [go-gorm/gorm#3190]
Hi i m trying move my **jinzhu/gorm** packet to **go-gorm/gorm** packet. But I think open function is changed.  I used to use it like this.

`DB, err = gorm.Open("postgres", cnnString)`

But now we have new parameters 
func Open(dialector Dialector, config *Config) (db *DB, err error)

I checked [https://gorm.io/docs/](https://gorm.io/docs/) link but it is old version quick start description. Can you share me a sample for open function. It is realy great packet for go and i want to use new packet in my project.

thanks.

**Comment by jinzhu** [comment]
http://v2.gorm.io/
