### ISSUE TITLE
Record not found with Take(), panic with First()

### ISSUE THREAD

**Issue by chabad360** [go-gorm/gorm#3193]
## GORM Playground Link
 
https://github.com/go-gorm/playground/pull/49

## Description

I'm simply trying to read a specific column from a row in the database (postgres in this case), but instead, I get either nothing (from `Take()`) or a panic (from `First()`).

**Comment by jinzhu** [comment]
Please read the document, don't pass a string but pointer of struct to `First`, `Take`


```go
db.First(&User{})
```

**Comment by chabad360** [comment]
I didn't see the docs mention that you can only use a strict, maybe it should be more clear. Also, I'd rather use `First()` over `Scan()`, because `Scan()` doesn't error if a record is not found...

**Comment by chabad360** [comment]
Also, this is not a feasible if I want the the column to be user specified.

**Comment by jinzhu** [comment]
use `db.Where(...).Row().Scan(name)`

**Comment by chabad360** [comment]
Then I can't check for `ErrRecordNotFound`, which is needed if the column is allowed to be null.

**Comment by inewlife** [comment]
same
