### ISSUE TITLE
Feature Request: Scan() and Find() should set DB.Error if no records are returned

### ISSUE THREAD

**Issue by chabad360** [go-gorm/gorm#3194]
## Describe the feature

`Scan()` and `Find()` (and friends) should set `DB.Error` to `ErrRecordNotFound` if no records are found.

## Motivation

Using `Scan()` to read one column from one row is problematic if I want to determine that a record was fetched successfully, because it's possible that a row exists but the column is empty (i.e. checking against the zero value wont work). Using a struct with `First()` is rather silly if I want to read just one column, and is down right not practical if that column is user specified. Checking `DB.RowsAffected` adds (seemingly) extra lines and is redundant as there's an already existing error specifically for this.

## Related Issues

#3193

**Comment by jinzhu** [comment]
designed for this.

**Comment by chabad360** [comment]
> designed for this.

So what do I do?

**Comment by jinzhu** [comment]
I think you might doing something wrong, If you really need this, you could use the following code:

```go
DB.Clauses(RaiseErrorOnNotFound{}).Find(&users)
```

```go
type RaiseErrorOnNotFound struct {
}

func (RaiseErrorOnNotFound) ModifyStatement(stmt *Statement) {
	stmt.RaiseErrorOnNotFound = true
}

func (RaiseErrorOnNotFound) Name() string {
	return ""
}

func (RaiseErrorOnNotFound) Build(clause.Builder) {
}

func (RaiseErrorOnNotFound) MergeClause(*clause.Clause) {
}
```

**Comment by chabad360** [comment]
Why cant `Scan()`, `Find()`, `Pluck()`, etc. just set `ErrRecordNotFound`? It's an already existing error, and it allows me to easily check that I got a result.
