### ISSUE TITLE
Use ENUM type in PGSQL on GO

### ISSUE THREAD

**Issue by arikardnoir** [go-gorm/gorm#3196]
## Your Question

Hi people, how can i use enum type when i create my struct like this.

type Package struct {
ID uuid.UUID gorm:"primary_key;" json:"id"
RecipientName string gorm:"size:255;not null" json:"recipient_name"
ChargeMethod Enum // ENUM with (1, 2, 3) as valid values?
}

## Expected answer

An example how to do it

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/issues/1978#issuecomment-476673540

**Comment by vasilev-gregory** [comment]
> [#1978 (comment)](https://github.com/go-gorm/gorm/issues/1978#issuecomment-476673540)
 
Thank you for your reply, its very useful.
Only thing I coudnt get my head around is why do you need extra functions to scan data, if postgres does everything for you
