### ISSUE TITLE
how to define logger to use context

### ISSUE THREAD

**Issue by hjinbi** [go-gorm/gorm#3201]
### how to define logger to use context

type MyLogger struct {
	*zap.Logger
	Config
	LogLevel
	infoStr, warnStr, errStr            string
	traceStr, traceErrStr, traceWarnStr string
}

func (z *ZapLogger) Printf(msg string, data ...interface{}) {
}
## Expected answer

A logger that can done with context

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/logger.html

**Comment by hjinbi** [comment]
I reimplemented the logger and its implement the following interface
But it not work with context

> // Interface logger interface
type Interface interface {
	LogMode(LogLevel) Interface
	Info(context.Context, string, ...interface{})
	Warn(context.Context, string, ...interface{})
	Error(context.Context, string, ...interface{})
	Trace(ctx context.Context, begin time.Time, fc func() (string, int64), err error)
}

**Comment by hjinbi** [comment]
I reimplemented the logger and its implement the following interface
But it not work with context

> // Interface logger interface
type Interface interface {
	LogMode(LogLevel) Interface
	Info(context.Context, string, ...interface{})
	Warn(context.Context, string, ...interface{})
	Error(context.Context, string, ...interface{})
	Trace(ctx context.Context, begin time.Time, fc func() (string, int64), err error)
}

**Comment by jinzhu** [comment]
Please create a PR on playground that can reproduce your issue
