### ISSUE TITLE
Joins do not work with "has many" relations

### ISSUE THREAD

**Issue by tab1293** [go-gorm/gorm#3205]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/50

## Description

I encounter a panic when trying to run a `Joins` call for a "has many" relation. 

`DB.Joins("Pets").Where("users.id = ?", user.ID).Find(&u)`

The following panic is encountered: 
```
--- FAIL: TestGORM (0.01s)
panic: reflect: call of reflect.Value.Field on slice Value [recovered]
	panic: reflect: call of reflect.Value.Field on slice Value

goroutine 8 [running]:
testing.tRunner.func1(0xc000188300)
	/usr/local/go/src/testing/testing.go:874 +0x69f
panic(0x49926c0, 0xc0001853a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.Field(0x4962460, 0xc0004c60f0, 0x197, 0x0, 0x196, 0x5b3d008, 0x40160b3)
	/usr/local/go/src/reflect/value.go:837 +0x29f
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func6(0x4962460, 0xc0004c60f0, 0x197, 0xc00009e8f8, 0xc00009e928, 0xc00009e928)
	/Users/tom/gorm-playground/gorm/schema/field.go:404 +0x102
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func11(0x4962460, 0xc0004c60f0, 0x197, 0x496eaa0, 0xc00009e928, 0xc00009e928, 0x40635d2)
	/Users/tom/gorm-playground/gorm/schema/field.go:572 +0xa4d
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func8(0x4962460, 0xc0004c60f0, 0x197, 0x4961180, 0xc00009e8f8, 0xc000184cc0, 0xc00009e8f8, 0xc00009e8f8)
	/Users/tom/gorm-playground/gorm/schema/field.go:473 +0x466
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func11(0x4962460, 0xc0004c60f0, 0x197, 0x4961180, 0xc00009e8f8, 0xc00009e8f8, 0xc0004c6000)
	/Users/tom/gorm-playground/gorm/schema/field.go:602 +0x204
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func8(0x4962460, 0xc0004c60f0, 0x197, 0x494c3c0, 0xc00009a138, 0xc000184cc0, 0x40635d2, 0x40f229d)
	/Users/tom/gorm-playground/gorm/schema/field.go:473 +0x466
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func11(0x4962460, 0xc0004c60f0, 0x197, 0x494c3c0, 0xc00009a138, 0x196, 0x2)
	/Users/tom/gorm-playground/gorm/schema/field.go:602 +0x204
gorm.io/gorm.Scan(0xc0004d4380, 0xc0004d2600, 0xc00009e000)
	/Users/tom/gorm-playground/gorm/scan.go:200 +0x3264
gorm.io/gorm/callbacks.Query(0xc0004d2600)
	/Users/tom/gorm-playground/gorm/callbacks/query.go:34 +0x4d8
gorm.io/gorm.(*processor).Execute(0xc000085e00, 0xc0004d2600)
	/Users/tom/gorm-playground/gorm/callbacks.go:100 +0x19d
gorm.io/gorm.(*DB).Find(0xc0004d2600, 0x4958380, 0xc0004c6000, 0x0, 0x0, 0x0, 0xc0004d2600)
	/Users/tom/gorm-playground/gorm/finisher_api.go:107 +0x165
gorm.io/playground.TestGORM(0xc000188300)
	/Users/tom/gorm-playground/main_test.go:37 +0x622
testing.tRunner(0xc000188300, 0x4a4c570)
	/usr/local/go/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x652
FAIL	gorm.io/playground	0.160s
FAIL
```

I see this note in the V2 docs:
> NOTE Join Preload works with one-to-one relation, e.g: has one, belongs to

Is there any intention to support joins for "has many" relations? Is there any way to use a custom preload query to use joins to connect tables that have "has many" relationships? A believe a query like the following would be enough:
```
SELECT  *
FROM users
JOIN pets
ON pets.user_id = users.id
WHERE users.id = 123; 
```

EDIT:
To clarify, I know I can use `Preload` to load the "has many" relations, but this results in an individual query per relation. In production, I am trying to load a large object graph that has many "has many" relationships. It is not very performant to run a query per relation here, I would like to run a single query with multiple joins to load the object graph.

**Comment by jinzhu** [comment]
> I am trying to load a large object graph that has many "has many" relationships. It is not very performant to run a query per relation here, I would like to run a single query with multiple joins to load the object graph.

I think using `Joins` will be slower in this case.

For example, you have `N` users, each of them has `M` pets, `I` credit cards, `J` friends, it will return N*M*I*J records when using `joins` to query, you are encouraged to use `Preloads` in this case, it will generate 4 SQL to load those data but should be faster.

**Comment by pickfire** [comment]
Ah, it also does not work for me. I got:
```
E1229 16:38:20.745899  323501 runtime.go:78] Observed a panic: &reflect.ValueError{Method:"reflect.Value.Field", Kind:0x17} (reflect: call of reflect.Value.Field on slice Value)
```
In my case `Preloads` is less efficient than join, I do want to use `Joins` even though `Preloads` is encouraged since I need it in the same query, I need to use `Where` for it.
