### ISSUE TITLE
Default values not in effect?

### ISSUE THREAD

**Issue by fishyww** [go-gorm/gorm#3206]
code：
package main

import (

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)
type User struct {
	ID   int64
	Name string `gorm:"default:'Alice'"`
	Age  int64  `gorm:"default:'18'"`
}

func main() {
	db, _ := gorm.Open(mysql.Open("xxx@/xxx?charset=utf8&parseTime=True&loc=Local"), &gorm.Config{})
	db.AutoMigrate(User{})
	db.Create(&User{Name: "xxx",})
}
DB：
![image](https://user-images.githubusercontent.com/51019225/88615767-28363f80-d0c5-11ea-89ac-f900a44fa40b.png)

**Comment by jinzhu** [comment]
`Age int64 gorm:"default:18"`

**Comment by fishyww** [comment]
@jinzhu  I set the value to zero, but filled in the default values？

![image](https://user-images.githubusercontent.com/51019225/88616583-16ee3280-d0c7-11ea-973a-7be941d7b05f.png)

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/create.html#Default-Values

**Comment by fishyww** [comment]
thank you~
