### ISSUE TITLE
(sqlite) panic: reflect: call of reflect.Value.Elem on slice Valu

### ISSUE THREAD

**Issue by jessegeens** [go-gorm/gorm#3209]
## GORM Playground Link
Playground:
-
Playground:
https://github.com/go-gorm/playground/pull/51

Gist:
https://gist.github.com/jessegeens/bb95e7a6b180e3a9a47d2b2cb0bcd62a

## Description

When trying to Create a struct that has other embedded structs, GORM panics (v0.2.25)

panic: reflect: call of reflect.Value.Elem on slice Value

goroutine 1 [running]:
reflect.Value.Elem(0x6af6c0, 0xc000206038, 0x197, 0x750820, 0x6af6c0, 0xc000206038)
        /usr/lib/go/src/reflect/value.go:820 +0x1a4
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func3(0x6e9b80, 0xc00020c000, 0x199, 0x4, 0xc000146a18, 0x0)
        /home/jesse/go/pkg/mod/gorm.io/gorm@v0.2.25/schema/field.go:376 +0x1b8
gorm.io/gorm/callbacks.ConvertToCreateValues(0xc000210000, 0xc000220000, 0x11, 0x12, 0xc000202040, 0x1, 0x1)
        /home/jesse/go/pkg/mod/gorm.io/gorm@v0.2.25/callbacks/create.go:283 +0x1a14
gorm.io/gorm/callbacks.Create.func1(0xc00020e000)
        /home/jesse/go/pkg/mod/gorm.io/gorm@v0.2.25/callbacks/create.go:49 +0x1e3
gorm.io/gorm.(*processor).Execute(0xc00005f500, 0xc00020e000)
        /home/jesse/go/pkg/mod/gorm.io/gorm@v0.2.25/callbacks.go:100 +0x21d
gorm.io/gorm.(*DB).Create(0xc0001a1680, 0x6aa3c0, 0xc00020c000, 0x1)
        /home/jesse/go/pkg/mod/gorm.io/gorm@v0.2.25/finisher_api.go:18 +0xa7
main.SetupOrganisation(0x6ff7c7, 0x4, 0xc0001a1680, 0x1, 0x0, 0x0)
        /home/jesse/Code/gorm-bug/main.go:102 +0x30c
main.main()
        /home/jesse/Code/gorm-bug/main.go:54 +0x16a

**Comment by jinzhu** [comment]
Invalid PR for https://github.com/go-gorm/playground/pull/51/files, please fixed and add the link back

Thank you

**Comment by jessegeens** [comment]
Hi, sorry, I updated the PR and now it shows the error in the tests

**Comment by jessegeens** [comment]
The culprit seems to be line 72 in the gist:

GrafanaUsers: []User{},
Using a pointer mitigates the issue:
GrafanaUsers: []*User{},

But I think it would be nice if GORM would return an error instead of throwing a panic and crashing

**Comment by jinzhu** [comment]
The problem is tag `embedded` only accepts `struct` field but not `slice` like `[]GrafUser`, lets returns the error earlier
