### ISSUE TITLE
soft delete not work for me

### ISSUE THREAD

**Issue by DDDrop** [go-gorm/gorm#3210]
## Soft delete not work for me
I updated Gorm to v2, and soft delete doesn't work.

gorm version: 0.2.25

**Comment by jinzhu** [comment]
Have you embedded `gorm.Model`? if you defined your own one, should change `DeletedAt`'s type to `gorm.DeletedAt` like https://github.com/go-gorm/gorm/blob/master/model.go#L14

**Comment by DDDrop** [comment]
thx, it works.
