### ISSUE TITLE
Excuse me，Why can I use the  navicat to run, but use Gorm to report an error？

### ISSUE THREAD

**Issue by arCzWw** [go-gorm/gorm#3211]
mysql 5.17

![image](https://user-images.githubusercontent.com/60876909/88816694-3da78880-d1ef-11ea-864b-5ff418d04a78.png)

![image](https://user-images.githubusercontent.com/60876909/88816889-78112580-d1ef-11ea-84d1-7c0fbe854545.png)

**Comment by jinzhu** [comment]
doesn't support use 1,2 as arguments?
