### ISSUE TITLE
gorm.DB callback rollback

### ISSUE THREAD

**Issue by elemyin** [go-gorm/gorm#3215]
## Your Question

if i use gorm callback,  my function is failed, transaction rollback, but callback is already running, how can i rollback this callback, if func failed, i don`t want use callback

**Comment by jinzhu** [comment]
Check error in your callbacks with 

`db.Error == nil`

**Comment by elemyin** [comment]
![image](https://user-images.githubusercontent.com/37828742/88906196-ba874080-d289-11ea-9dc4-0434e19b1b72.png)
is this db?

**Comment by jinzhu** [comment]
yes

**Comment by elemyin** [comment]
![image](https://user-images.githubusercontent.com/37828742/88909814-29669880-d28e-11ea-9b1e-b9b8c16bdd04.png)
![image](https://user-images.githubusercontent.com/37828742/88909837-32f00080-d28e-11ea-8e79-12339ddc17fa.png)
i wrote an demo, but it`s runing
![image](https://user-images.githubusercontent.com/37828742/88909980-5ca92780-d28e-11ea-9813-552521fe276f.png)

**Comment by elemyin** [comment]
i use gorm v2
