### ISSUE TITLE
Race condition appears when used with channel and count

### ISSUE THREAD

**Issue by ap-in-git** [go-gorm/gorm#3219]
When I use channel and do count . I get race condition but when I put debug in front of query I don't get race condition .
Reproducing link here

https://github.com/go-gorm/playground/pull/60

The race condition didn't appear in v1

**Comment by jinzhu** [comment]
Hello @ap-in-git 

This a known broken change to reduce GC alloc, check out http://v2.gorm.io/docs/method_chaining.html

You can use the following code to avoid the issue.

`queryDb := DB.Joins("left join pets on pets.user_id = users.id ").Session(&Session{WithConditions: true})`
