### ISSUE TITLE
Postgresql: setting charset and parseTime

### ISSUE THREAD

**Issue by cnaize** [go-gorm/gorm#322]
Hello!
I'm trying to connect to my `postgresql` database.
I'm trying:

``` go
gorm.Open("postgres", fmt.Sprintf(`user=%v password=%v dbname=%v
    sslmode=disable ?charset=utf8&parseTime=true`,
    "db_user", "db_pass", "db_name"))
```

and get:

``` go
pq: unrecognized configuration parameter "?charset"
```

With `mysql` everything works.
How to use this params with `postgresql`?

**Comment by faeronsayn** [comment]
@jinzhu I'm getting this error:
```
(sql: Scan error on column index 3: unsupported driver -> Scan pair: []uint8 -> *time.Time) 
```

and in other solutions it is suggested to use parseTime=true, but from this it seems like we can't do this if we're on postgres, which is what I am using. What's the solution for postgres?

**Comment by codepushr** [comment]
Also interested in the postgres solution!

**Comment by producerism** [comment]
I realize this is closed, but I'm also looking for a postgres solution.

**Comment by ctfrancia** [comment]
was there ever a solution?
