### ISSUE TITLE
Count panics or returns error

### ISSUE THREAD

**Issue by pkpfr** [go-gorm/gorm#3220]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/61

## Description

Count panics or returns an error depending on how the API is called.

`DB.Table("users").Where("name = ?", "jinzhu").Select("name").Count(&c)` = Panic
`DB.Table("users").Where("name = ?", "jinzhu").Count(&c)` = Error
`DB.Table("users").Count(&c)` = Error

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
