### ISSUE TITLE
Doing an "or" condition chain

### ISSUE THREAD

**Issue by jmramos02** [go-gorm/gorm#3223]
## Your Question

Hi!

How can i do an "or" condition. i would like to chain multiple `where` conditions in gorm. i can't seem to find anything about it on the docs.

Thanks very much!

## Expected answer

Any links or examples would be great

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/advanced_query.html#Group-Conditions

**Comment by jmramos02** [comment]
Thanks!!!
