### ISSUE TITLE
Do not escape the sql injection methods only in db.Exec

### ISSUE THREAD

**Issue by ap-in-git** [go-gorm/gorm#3227]
I was reading the docs for
 https://v2.gorm.io/docs/security.html#SQL-injection-Methods

I believe it would be better if we escape such syntax in all the cases execpt for db.Exec where we wanna execute something on db.

Maybe create a method to drop from db

If we are building app with dynamic column select the user may execute such type of operation on select .

**Comment by jinzhu** [comment]
We don't escape for those methods as we want to give developers some flexibility to support some features, and I don't think it is a good idea to accept user's input to build the SQL directly.
