### ISSUE TITLE
Is there a way to add a callback for table creation?

### ISSUE THREAD

**Issue by luigi-riefolo** [go-gorm/gorm#3228]
## Your Question

Is there a way to add a callback for table creation?

## Expected answer

I need to find a way to customise the table creation, is there a callback I can use?
Go structs and Gorm tags are not sufficient for my use case, given that I do not control the struct.

**Comment by jinzhu** [comment]
Table creation will call RAW SQL callbacks, but could you let me know your use case, and if we can extend GORM tags to match your requirements

**Comment by luigi-riefolo** [comment]
@jinzhu I need to create a table for a struct that needs to have its field names and types modified before the table creation.
Unfortunately we do not control the struct or the input, but know how to map the fields in the struct to a table.
e.g.
input: struct{A: 1, B: { 2, 3, 4}}
table fields: A_a, B_a, B_b, B_c

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/conventions.html#NamingStrategy
