### ISSUE TITLE
What`s the different between go-gorm/gorm  and jinzhu/gorm?

### ISSUE THREAD

**Issue by hirorogithub** [go-gorm/gorm#3229]
I found two gorm on github, one is go-gorm/gorm  and other is jinzhu/gorm. I think jinzhu is the author of gorm, but ,which package should I import ?

If I use go-gorm/gorm function to query db,then judge the err is jinzhu/gorm ErrRecordNotFound or not ,is it work?
Or I should only import one kind of gorm in my project?

**Comment by jinzhu** [comment]
go-gorm/gorm is GORM V2 -> https://v2.gorm.io
jinzhu/gorm is GORM V1 -> https://v1.gorm.io

**Comment by daodennis** [comment]
It would be beneficial if this was front and center in every readme and docs site as this was very confusing too. Also, there are links to issues in the gormv1 github that do not directly work but if you find the number in this repo it seems to be the same issue. (search this page for 1543: https://blog.depado.eu/post/gorm-gotchas)
