### ISSUE TITLE
Failed using GORM v2 with golang v1.12

### ISSUE THREAD

**Issue by cheavck** [go-gorm/gorm#3230]
I tried to migrate jinzhu/gorm v1 to go-gorm v2 in golang v1.12 project. It is always blocked with the following error messages.

```
../../../go/pkg/mod/gorm.io/gorm@v0.2.20/utils/utils.go:46:30: reflect.ValueOf(val).IsZero undefined (type reflect.Value has no field or method IsZero)
note: module requires Go 1.14
```
I guess GORM v2 is using some golang apis that are incompatible with old golang project and unfortunately my project is running on Google AppEngine Standard that are not compatible with Go 1.13 and higher.

**Comment by jinzhu** [comment]
V2 will only supports v1.13+
