### ISSUE TITLE
Memory corruption when saving a different model

### ISSUE THREAD

**Issue by camiloperezv** [go-gorm/gorm#3231]
## GORM Playground Link

I will try to create a playground for this, for now, I just want to report it to see if there is an easy fix.

This issue occurs on GORM `1.9.15`

## The problem
Gorm has a corrupt memory when it set the PolymorphicValue to a new row.
When we run all the tests together we have 2 different instances of GORM, 
one for the test with a real DB and other with SQL MOCK. If the test of the SQL MOCK, 
`func A` is called before, then all the invoices will have `ContextDetailsType` with the string used in the function `A` to call the table.

Is important to note that the failing test and the function `A` are 
**NOT RELATED AT ALL** they are in the same pkg but the failing test `B` never calls `A`

## Description of the problem

Currently, we have 2 functions. The first function called A()

```
func A(transaction *gorm.DB) {
.
.
.
err := transaction.Select("booking_payment_contexts.*").Table("ANY_NANE_GOES_HERE").
		Joins("left join invoices on invoices.id = credit_note_contexts.origin_id").
		Joins("left join commission_contexts on invoices.context_details_id = commission_contexts.id").
		Joins("left join booking_payment_contexts on booking_payment_contexts.id = commission_contexts.booking_id ").
		Where("credit_note_contexts.id = ?", creditNoteContextID).
		Last(booking).Error
.
.
.

}
```
Also, we tried to remove the Joins to see if there is a problem there but the problem continues happening.
The other method is B()
```
func B(tx *gorm.DB, c InvoiceContext) error {
	return tx.Create(c).Error
}
```

For function A we have unit tests using SQL MOCK like this

```
func TestA(t *testing.T){
    db, mock, err := sqlmock.New()
    assert.NoError(t, err)
    gormDb, err := gorm.Open("postgres", db)
    assert.NoError(t, err)
    defer db.Close()
    .
    .
    .
    mock.ExpectQuery(regexp.QuoteMeta(`SELECT booking_payment_contexts.* FROM "ANY_NANE_GOES_HERE" left join invoices on invoices.id = credit_note_contexts.origin_id left join commission_contexts on invoices.context_details_id = commission_contexts.id left join booking_payment_contexts on booking_payment_contexts.id = commission_contexts.booking_id WHERE (credit_note_contexts.id = $1) ORDER BY "credit_note_contexts"."id" DESC LIMIT 1`)).
        WithArgs(1994).
        WillReturnRows(sqlmock.NewRows([]string{"id", "advertiser_id", "tenant_id"}).AddRow(20020, 100093, 20992))
    .
    .
    .
    assert.NoError(t, mock.ExpectationsWereMet())
}
```

This test works as expected. The problem appears when the tests runs first `TestA` and then the rest of the tests of the module.

We already removed the sqlmock to see if that is the problem but without using the `mock.ExpectationsWereMet` and `mock.ExpectQuery` the 
error still occurs. 

## Debug

After some debug we ended up in the file `go/pkg/mod/github.com/jinzhu/gorm@v1.9.2/scope.go`. There we can see that the value for
the object `structField` in `for _, structField := range scope.GetModelStruct().StructFields {` has `structField.Relationship.PolymorphicValue` equal to `ANY_NANE_GOES_HERE` where `ANY_NANE_GOES_HERE` is the **TABLE NAME** used in function `A()` Which is not called in function B.

## The models

Invoice:
```
type Invoice struct {
	ID                 uint32
	Number             string
	Type               InvoiceType
	ContextDetails     InvoiceContext `gorm:"-"`
	ContextDetailsType string
	ContextDetailsID   uint32
	Recipient          *user.UserHistoryEntry `gorm:"save_associations:false"`
	RecipientID        uint32
	.
    .
    .
}
```

```
type BookingPaymentContext struct {
    .
    .
    .
	ID                     uint32
	MoveInDate             time.Time
	MoveOutDate            *time.Time
	Invoices               []*Invoice `gorm:"polymorphic:ContextDetails"`
	CreatedAt              time.Time
    .
    .
    .
}
```

The function `A()` Uses `BookingPaymentContext` and the funciton `B()` uses `Invoice`

## Personal conclusion.

Seems like GORM is storing somehow the value of .Table() and that value is being used for a reference in other queries. Also, i checked and the memory address from Gorm objects of the tests are completely different

**Comment by jinzhu** [comment]
sorry, we only accept v2 issues here, and only accept PR for V1
