### ISSUE TITLE
Feature Request: Automaticaly truncate time.Time to nearest millisecond or store as bigint in Postgres

### ISSUE THREAD

**Issue by chabad360** [go-gorm/gorm#3232]
## Describe the feature

The PostgreSQL drive should (provide an option to) either truncate/round `time.Time` to millisecond precision or store it as a bigint (unix format).

## Motivation

PostgreSQL's `timestamp` unfortunately doesn't have nanosecond precision, which means that when running tests (to ensure that what went in came out), these tests will always fail, because the timestamp that went in was rounded to the nearest microsecond.

[Test results](https://github.com/go-gorm/playground/pull/63/checks?check_run_id=947049848#step:6:28):
```
 === RUN   TestGORM

2020/08/04 23:10:46 /home/runner/work/playground/playground/main_test.go:14
[3.938ms] [rows:1] INSERT INTO "users" ("created_at","updated_at","deleted_at","name","age","birthday","company_id","manager_id","active") VALUES ('2020-08-04 23:10:46.001','2020-08-04 23:10:46.001',NULL,'jinzhu',0,NULL,NULL,NULL,false) RETURNING "id"

2020/08/04 23:10:46 /home/runner/work/playground/playground/main_test.go:17
[1.231ms] [rows:1] SELECT * FROM "users" WHERE "users"."id" = 1 AND "users"."deleted_at" IS NULL ORDER BY "users"."id" LIMIT 1
    main_test.go:20: time.Equal Failed, result.CreatedAt: 2020-08-04 23:10:46.001471 +0000 UTC, user.CreatedAt: 2020-08-04 23:10:46.001471824 +0000 UTC
--- FAIL: TestGORM (0.01s)
FAIL
FAIL	gorm.io/playground	0.167s
FAIL
```

## Related Issues

https://github.com/go-gorm/playground/pull/63
https://github.com/lib/pq/issues/227
https://github.com/lib/pq/pull/954

**Comment by jinzhu** [comment]
Hello @chabad360 

Thank you for your suggestion, I think this only helpful in testing cases, would not like to slow down the inserting/updating by doing such a job.

In my tests, I will round the time in a helper method.

Thank you.

**Comment by chabad360** [comment]
It's still a problem, saying that it's only helpful for tests may be true, but fact of the matter is that tests are meant to make sure that what you expect to happen happens. It would be nice to at least have the option to do this.

**Comment by jinzhu** [comment]
> It's still a problem, saying that it's only helpful for tests may be true, but fact of the matter is that tests are meant to make sure that what you expect to happen happens. It would be nice to at least have the option to do this.

In your tests cases, you can round the time to make sure the logic.

Also, you could specify the `NowFunc` to round the time in the function.

**Comment by chabad360** [comment]
That would be true except for `CreatedAt`, et al. As they are set automatically by gorm, so I can't truncate them before their sent to the DB.

**Comment by jinzhu** [comment]
Check out `NowFunc` http://v2.gorm.io/docs/gorm_config.html#NowFunc, it matches your requirements

**Comment by chabad360** [comment]
Thanks for that, I think it would make sense to mention that under the Postgres driver, as a warning/suggestion.
