### ISSUE TITLE
Find entries without any many2many relation

### ISSUE THREAD

**Issue by vincegio** [go-gorm/gorm#3234]
## Your Question
I am trying to retrieve some entries from my database, the only issue is that I only want those without a relation set.
Example model:
```
type User struct {
  gorm.Model
  Languages         []*Language `gorm:"many2many:user_languages;"`
}
```

I want to get all Users without any Language.

Tried
```
db.Where(&User{Languages: []*Language{}}})...
```
But got an error of 

> sql: converting argument $1 type: unsupported type []*Language, a slice of ptr 

Also tried
```
db.Where("Languages is NULL")...
```
Far reached as this obviously is invalid.

Without going deep into manually writing SQL code, is there a solution to this?

## Expected answer
I want to retrieve only those without a relation.

**Comment by jinzhu** [comment]
will SubQuery http://v2.gorm.io/docs/advanced_query.html#SubQuery build SQL like `id not in (select user_id from user_languages)`
