### ISSUE TITLE
gorm v2 TableName issue with schemas on create

### ISSUE THREAD

**Issue by MrParano1d** [go-gorm/gorm#3235]
## Your Question

Is this the right place to submit v2 issues?

I've a struct with

```
func (User) TableName() string {
	return "global.logins"
}
```

and it perfectly works with `db.Conn.Find(&users).Where("status = ?", 1)` but not with `db.Conn.Create(&user)`.

On create it throws `relation "logins" does not exist`

I saw in your statement.go file this function:

```
func (stmt *Statement) Parse(value interface{}) (err error) {
	if stmt.Schema, err = schema.Parse(value, stmt.DB.cacheStore, stmt.DB.NamingStrategy); err == nil && stmt.Table == "" {
		if tables := strings.Split(stmt.Schema.Table, "."); len(tables) == 2 {
			stmt.TableExpr = &clause.Expr{SQL: stmt.Quote(stmt.Schema.Table)}
			stmt.Table = tables[1]
			return
		}

		stmt.Table = stmt.Schema.Table
	}
	return err
}
```

When I remove

```
if tables := strings.Split(stmt.Schema.Table, "."); len(tables) == 2 {
    stmt.TableExpr = &clause.Expr{SQL: stmt.Quote(stmt.Schema.Table)}
    stmt.Table = tables[1]
    return
}
```

everything works fine. Why do you split the table name by "." and remove the schema?

## Expected answer

We're using postgres with schemas and can't keep going with gorm v2 without a fix for this.
Can I fix this by changing any gorm configs?

**Comment by jinzhu** [comment]
So your table name contains `.`?

**Comment by MrParano1d** [comment]
The schema is `global` and the table name is `logins`. So I've to write `global.logins` in postgres. But gorm removes `global` from the query and now I get the error `relation "logins" does not exist`.

**Comment by jinzhu** [comment]
this should be tested https://github.com/go-gorm/gorm/blob/master/tests/table_test.go#L17

Please create a reproducible PR and submit a new issue here https://github.com/go-gorm/playground
