### ISSUE TITLE
Allow simpler update syntax

### ISSUE THREAD

**Issue by mitar** [go-gorm/gorm#3238]
## Example

https://github.com/go-gorm/playground/pull/66

## Describe the feature

It is surprising that the correct syntax for the simple update query is:

```
DB.Model(&User{}).Where(&User{Name: "foobar", Age: 32}).Updates(map[string]interface{}{"Active": true})
```

Where ideally the following two should work as well:

```
DB.Where(&User{Name: "foobar", Age: 32}).Updates(map[string]interface{}{"Active": true})
DB.Model(&User{Name: "foobar", Age: 32}).Updates(map[string]interface{}{"Active": true})
```

The issue is also that the error message for the first one is misleading:

```
TestGORM: main_test.go:16: Failed, got error: unsupported data type: map[Active:true]
```

For the second one it is better, but still, why necessary:

```
TestGORM: main_test.go:23: Failed, got error: WHERE conditions required
```

## Motivation

This tripped both me and my coworker.

**Comment by jinzhu** [comment]
1, GORM Need `Model` or `Table` to Update
2, http://v2.gorm.io/docs/update.html#Block-Global-Updates

http://v2.gorm.io/docs/update.html

**Comment by mitar** [comment]
I know. But why. Could this be relaxed please? You get a reference to the model/table in `Where` as well.

And why does `DB.Model(&User{Name: "foobar", Age: 32}).Updates(map[string]interface{}{"Active": true})` noy work? Why I cannot specify both the model and where at once?

So I think the question is more: why there is no way to provide `Model` and `Where` as one?
