### ISSUE TITLE
issues while inserting into a postgres table

### ISSUE THREAD

**Issue by MrParano1d** [go-gorm/gorm#3239]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/67

## Description
As mentioned in https://github.com/go-gorm/gorm/issues/3235 I've issues with using a schema in the table name.

Postgres table names are `schema`.`tablename`

For this test I used `gorm.user`. 

In the logs you can see that gorm is creating this table only with the name `user` and its removing the `gorm` part. That's not how postgres works. The name has to be `gorm.user`, because the schema name is `gorm`.
https://github.com/go-gorm/playground/pull/67/checks?check_run_id=952697266#step:6:23

In our software case the schema is `global` and the table `logins`. When I run a `DB.Create` on this I get a `relation "logins" does not exist` error because gorm is removing the `global` schema.

As mentioned in the origin issue the problem comes from your statement.go

```
func (stmt *Statement) Parse(value interface{}) (err error) {
	if stmt.Schema, err = schema.Parse(value, stmt.DB.cacheStore, stmt.DB.NamingStrategy); err == nil && stmt.Table == "" {
		if tables := strings.Split(stmt.Schema.Table, "."); len(tables) == 2 {
			stmt.TableExpr = &clause.Expr{SQL: stmt.Quote(stmt.Schema.Table)}
			stmt.Table = tables[1]
			return
		}

		stmt.Table = stmt.Schema.Table
	}
	return err
}
```

This if is causing the error

```
if tables := strings.Split(stmt.Schema.Table, "."); len(tables) == 2 {
			stmt.TableExpr = &clause.Expr{SQL: stmt.Quote(stmt.Schema.Table)}
			stmt.Table = tables[1]
			return
		}
```

I need some sort of config in gorm so that this `if` won't be executed. When I remove this lines of code in my GOPATH everything works fine.

**Comment by MrParano1d** [comment]
When I write a ```DB.Find``` it's using the right table name. It's just the ```DB.Create``` which is removing the schema from the table name.

**Comment by jinzhu** [comment]
I think postgres doesn't support syntax like `INSERT INTO "gorm"."users" ...`?

**Comment by MrParano1d** [comment]
![image](https://user-images.githubusercontent.com/7414374/89508136-c5802a80-d7cd-11ea-871e-d7947e006fe3.png)
It does. And when I remove the `if` from `statement.go` it works.. so that's how postgres works. I'm working with it since more than 10 years.

**Comment by MrParano1d** [comment]
We want to switch our PHP backend to Go and Gorm would be the perfect ORM. Just this issue is holding us back.

**Comment by jinzhu** [comment]
Can you test with the `test` branch? my local Postgres server doesn't like this syntax... using docker `postgres:latest`

**Comment by jinzhu** [comment]
> ![image](https://user-images.githubusercontent.com/7414374/89508136-c5802a80-d7cd-11ea-871e-d7947e006fe3.png)
> It does. And when I remove the `if` from `statement.go` it works.. so that's how postgres works. I'm working with it since more than 10 years.

could you let me know your db version?

**Comment by MrParano1d** [comment]
I tested the `test` branch and it's working perfectly now. I tested it with postgres `9.5.4` and `11.6`.

**Comment by jinzhu** [comment]
Fixed， thank you for your report.

**Comment by MrParano1d** [comment]
Yes, it works! Thank you for this great library and your help! :)

**Comment by ehsannm** [comment]
@jinzhu could you please merge test branch with master. We just moved from gorm v1 to this new one. And we have problem with this

**Comment by jinzhu** [comment]
> @jinzhu could you please merge test branch with master. We just moved from gorm v1 to this new one. And we have problem with this

merged it few days ago, have you upgraded to latest version?
