### ISSUE TITLE
SingularTable / Plural smartness add ability  turn off entirely 

### ISSUE THREAD

**Issue by nmccready** [go-gorm/gorm#3241]
## Describe the feature

Ability to disable singular or plural all together. Yes it helps conformity to conventions but in nature without having the option to turn off this "smartness" you run into  lock contentions for having to go back and forth between tables which are named differently.

## Motivation

Working on legacy codebases where not everything is conformed yet.

The current codebase locks the pluralization on and off global wide to the db instance itself and not to a specific table.

**Comment by nmccready** [comment]
To be clear this seems to be only an issue when using `db.Table`.

`db.Table("user") // gets set to users` , would love to accept this verbatim without setting everything globally.

like `db.Table("user", isSingle = true)` or somehow `db.TurnOfSinglePluralSmartness()` 

But using using

```go
type User struct {}
func (User) TableName() string {
	return "user"
}
```

Seems to be the work around.

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/conventions.html#NamingStrategy
