### ISSUE TITLE
Even if I set to 50 for above values, I'm getting Connection Refused. Any complete example to use above code appropriately?

### ISSUE THREAD

**Issue by itsursujit** [go-gorm/gorm#3244]
PR: https://github.com/go-gorm/playground/pull/68
Even if I set to 50 for above values, I'm getting Connection Refused.
Any complete example to use above code appropriately?

I'm not getting it working on v2.

I think I've to revert back to v1.

**Comment by jinzhu** [comment]
The connection pool usage looks good, have you make sure you only `SetupDB` once for your application? not for every request, looks like a bug in your application.
