### ISSUE TITLE
Customized data type will be set to nil if it implements driver.Valuer interface and return nil as driver.Value

### ISSUE THREAD

**Issue by caelansar** [go-gorm/gorm#3248]
### environment
```
gorm version: 0.2.28
go version: 1.14
mysql version 5.7.12
```

### customize data type
```go
type CryptoFieldJsonStorage struct {
	Plaintext *string `json:"plaintext"` // base64 encoded data
	FullHash  *string `json:"full_hash"` // md5 hash
}

type Crypto struct {
	data        []byte
	jsonStorage *CryptoFieldJsonStorage
}

// Implements schema.GormDataTypeInterface interface
func (c *Crypto) GormDataType() string {
	return "crypto"
}

// Implements driver.Scanner
func (c *Crypto) Scan(src interface{}) error {
	source, ok := src.([]byte)
	if !ok {
		return errors.New("invalid data type")
	}

	c.jsonStorage = &CryptoFieldJsonStorage{}
	err := json.Unmarshal(source, c.jsonStorage)
	if err != nil {
		return err
	}

	//if c.jsonStorage.Plaintext != nil {
	//	c.data, err = base64.StdEncoding.DecodeString(*c.jsonStorage.Plaintext)
	//	if err != nil {
	//		return err
	//	}
	//}
	return nil
}

// Implements driver.Valuer
func (c Crypto) Value() (driver.Value, error) {
	if c.data == nil {
		return nil, nil // THIS
	}
	plaintext := base64.StdEncoding.EncodeToString(c.data)
	c.jsonStorage.Plaintext = &plaintext

	md5Hash := md5.Sum(c.data)
	fullHash := hex.EncodeToString(md5Hash[:])
	c.jsonStorage.FullHash = &fullHash

	jsonStorage, err := json.Marshal(c.jsonStorage)
	if err != nil {
		return nil, err
	}
	return jsonStorage, nil
}
```
### user model
```go
type User struct {
	Id   int64
	Name Crypto
        //Name *Crypto
}
```
### user table and test data
```sql
CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `user` (name) VALUES ('{"full_hash": "47bce5c74f589f4867dbd57e9ca9f808", "plaintext": "YWFh"}');
```

## Description
```go
var user User
_ = db.Debug().Table("user").Where("id=?", 1).Find(&user).Error
```
It works as my expectation when using `gorm 1.x`: the `jsonStorage` data is being retained

After I migrate to `gorm 2` and use above code to get user record, the `jsonStorage` data in `User.Name` will be set as nil, although it's value has been assigned in `*Crypto.Scan` method

If change `Name` field in `User` struct from `Crypto` to `*Crypto` type, the `jsonStorage` data in `User.Name` will be retained

I'm not sure if it is a bug, or a deliberate design. Am I missing something? I think we should keep these value that have been scan into customized data type

## GORM Playground Link
PR: https://github.com/go-gorm/playground/pull/69

**Comment by caelansar** [comment]
PR: https://github.com/go-gorm/playground/pull/69

**Comment by jinzhu** [comment]
Hi @caelansar 

Your case should be tested, https://github.com/go-gorm/gorm/blob/39c8d6220b75b5a28dfff6ae88da17485b35dc46/tests/scanner_valuer_test.go#L128

Could you make the PR tests fail if it doesn't work as you expected?

**Comment by caelansar** [comment]
> Hi @caelansar
> 
> Your case should be tested,
> 
> https://github.com/go-gorm/gorm/blob/39c8d6220b75b5a28dfff6ae88da17485b35dc46/tests/scanner_valuer_test.go#L128
> 
> Could you make the PR tests fail if it doesn't work as you expected?

Hi @jinzhu 
I have created a PR https://github.com/go-gorm/gorm/pull/3252 to make tests fail

**Comment by jinzhu** [comment]
Fixed, thank you for yoru report.

**Comment by githubzhaoqian** [comment]
Has this problem been fixed?
I have the same problem.
v1 is ok. but v2 is not the expected outcome. v2 is always nil.

**Comment by githubzhaoqian** [comment]
Update to the latest version everything is ok.
thank you.
