### ISSUE TITLE
Cannot run SHOW TABLES;

### ISSUE THREAD

**Issue by bluemultipass** [go-gorm/gorm#325]
I tried 

```
 db.Exec("SHOW TABLES FROM myDatabase;").Row()
```

but it outputed

```
can't get table name 
```

Is there a way to execute this query?

**Comment by anotherGoogleFan** [comment]
So @johnywith1n can you remember what you have done to solve this? I meet the same problem.

**Comment by johnywith1n** [comment]
@anotherGoogleFan https://gorm.io/docs/sql_builder.html

use `db.Raw`

**Comment by anotherGoogleFan** [comment]
@johnywith1n 
Yes I tried, but faild.
<pre>
	var tableNames []string
	if err := db.Raw("SHOW TABLES").Scan(&tableNames).Error; err != nil {
		panic(err)
	}
	fmt.Println(tableNames)
</pre>
then the code print ...
<pre>
[2019-10-16 11:01:54]  [0.99ms]   SHOW TABLES  
[11 rows affected or returned ] 
[          ]
</pre>

**Comment by vienng** [comment]
Try this
`	var tables []string
	rows, err := sdb.Store.Raw("SHOW TABLES").Rows()
	if err != nil {
		panic(err)
	}

	for rows.Next() {
		var table string
		if err := rows.Scan(&table); err != nil {
			panic(err)
		}

		if table != "schema_migrations" {
			tables = append(tables, table)
		}
	}
       fmt.Println(tableNames)
`
