### ISSUE TITLE
链式查询第二个语句出现两次deleted_at  limit和offset也是公用的

### ISSUE THREAD

**Issue by githubzhaoqian** [go-gorm/gorm#3257]
## GORM Playground Link
gorm.io/driver/mysql v0.3.1
gorm.io/gorm v0.2.29

## Description
func (d *Demo) AllDemo() (data []Demo, err error) {
	var count int64
	err = db.Table(d.TableName()).Limit(1).Offset(1).Find(&data).Count(&count).Error
	fmt.Println(data)
	return
}

2020/08/12 16:51:05 /home/go/src/gofeel/model/demo.go:47
[0.925ms] [rows:0] SELECT * FROM `demo` WHERE `demo`.`deleted_at` IS NULL _LIMIT 1 OFFSET 1_

2020/08/12 16:51:05 /home/go/src/gofeel/model/demo.go:47
[0.187ms] [rows:0] SELECT count(1) FROM `demo` WHERE `demo`.**`deleted_at` IS NULL AND `demo`.`deleted_at` IS NULL** _LIMIT 1 OFFSET 1_

limit 和offset 会公用这个可以接受
但是 count() 出现两次  deleted_at*2 这个让我很意外

**Comment by githubzhaoqian** [comment]
ok
```golang
func (d *Demo) AllDemo() (data []Demo, err error) {
	var count int64
	query:=db.Model(d)
        // [1.123ms] [rows:1] SELECT count(1) FROM `demo` WHERE `demo`.`deleted_at` IS NULL
	query.Session(&gorm.Session{WithConditions: true}).Count(&count)

        //[0.336ms] [rows:0] SELECT * FROM `demo` WHERE `demo`.`deleted_at` IS NULL LIMIT 1 OFFSET 1
	err = query.Limit(1).Offset(1).Find(&data).Error
	fmt.Println(data)
	return
}

```

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/method_chaining.html
