### ISSUE TITLE
Nested WHERE Query on GORM

### ISSUE THREAD

**Issue by mikysetiawan** [go-gorm/gorm#3265]
## Your Question
Hi, I want to make a nested where query like this  **SELECT * FROM table_a WHERE (table_a.name LIKE '%Jack%' OR table_a.tags LIKE '%Human%') AND table_a.published = 1** how can I produce this kind of query using GORM? I already search that in https://gorm.io/ and http://v2.gorm.io but I can't get what I want, even in some comment they said right now GORM is not able to produce this kind of query, is that right?

## Expected answer
I want to know, is GORM can create that kind of query? if yes please explain to me, if can't, can you make some update to produce it in the future?

Best Regards,

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/advanced_query.html#Group-Conditions
