### ISSUE TITLE
Missing association auto update tags

### ISSUE THREAD

**Issue by pielambr** [go-gorm/gorm#3266]
## Description

I have a custom struct with some basic fields, amongst the primary key that I use as a base struct to extend all my other models from ().

There are also two associations in there; one for the user that created the row, and one to track the user that last updated the row.
With v1 of Gorm, I could globally disable that these users were updated anywhere in any other queries using `association_autoupdate:false` (cfr. http://gorm.io/docs/associations.html#Auto-Create-Update)

With v2 I did not find an option in the documentation, except to specify in each and every query to omit those two relationships. Is it just not in the documentation, or is it not a feature anymore at all?

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/associations.html#Skip-Auto-Create-Update

```go
db.Omit(clause.Associations).Create(&user)
```

**Comment by pielambr** [comment]
Yes, so you have to specify it in every query you make against the model? 

```
type BaseModel struct {
	ID         string     `gorm:"primaryKey"`
	CreatedBy  *int64    
	Created    *User      `gorm:"foreignKey:CreatedBy"`
	CreatedAt  time.Time 
	UpdatedBy  *int64  
	Updated    *User      `gorm:"foreignKey:UpdatedBy`
	UpdatedAt  time.Time 
}
```

This is included in every database model used throughout the application, which would imply that as soon as I forget to use `Omit` anywhere, any query can change a user in the database?

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/models.html#Field-Level-Permission
