### ISSUE TITLE
连接db超时

### ISSUE THREAD

**Issue by Molecular-Future** [go-gorm/gorm#3268]
## Your Question
(/Users/camulos/Documents/go/src/cn/grabblock/models/main_block.go:27)
[2020-08-14 15:22:40]  dial tcp xxx.xxx.xxx.xxx:13306: connect: connection timed out

`var err error
	conf := conf.Context.Db

	args := fmt.Sprintf(
		"%s:%s@tcp(%s:%s)/%s?charset=utf8&parseTime=True&loc=Local", conf.Username, conf.Password, conf.Address, conf.Port, conf.Dbname)

	db, err = gorm.Open("mysql", args)

	if err != nil {
		log.Fatalln(err)
	}
	db.DB().SetMaxIdleConns(conf.Maxidleconns)
	db.DB().SetMaxOpenConns(conf.Maxopenconns)
	db.DB().Ping()
	db.SingularTable(true)
	db.LogMode(conf.LogMode)`

请问咱们这数据库插件，使用了连接池吗？如何验证一下建立多少个池子呢？

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/connecting_to_the_database.html#Connection-Pool
