### ISSUE TITLE
Queries using First() and Count()

### ISSUE THREAD

**Issue by botastic** [go-gorm/gorm#3270]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/ 71

## Description

Using First and Count together leeds to some unexpected behaviour (including a silent exit)

**Comment by jinzhu** [comment]
Please make the link runnable and add it back, thank you.

**Comment by botastic** [comment]
I'm not sure what the problem is, but I can run the tests using ./test.sh or go run (of course I got the dependencies before).
