### ISSUE TITLE
关于自动 预加载，可以支持 隐式加载数据？

### ISSUE THREAD

**Issue by ufowiner** [go-gorm/gorm#3273]
## Describe the feature
默认不加载关联数据，当需要关联数据时，自动读取数据到关联目标，
user{
id int
name string
avatars []avatar
}
例如 
user := user{}
 db.find(&user)

我们可以在 获取 user.avatars 时读取数据 ，从数据库加载或内存

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/preload.html
