### ISSUE TITLE
cloudsqlpostgres seems to be removed in Gorm V2.

### ISSUE THREAD

**Issue by lennycampino** [go-gorm/gorm#3274]
Hello can you please add the cloudsqlpostgres dialect to Gorm V2?

In V1 I was able to just open a connection with specifying the dialect and the dsn like:
gorm.Open("cloudsqlpostgres", dsn)

but now thats not working anymore.

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/connecting_to_the_database.html#Customize-Driver-1
