### ISSUE TITLE
unique_index is not work

### ISSUE THREAD

**Issue by blakejia** [go-gorm/gorm#3279]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/77

## Description

go version:  go1.14.7
gorm v2: 0.2.31
db: postgresql 12.4

``` golang
type TestTable struct {
	Address string `gorm:"unique_index:address_type_user"`
	Type    string `gorm:"unique_index:address_type_user"`
}

```

```golang
error1 := db.AutoMigrate(
	TestTable{},
)
```

``` sql
select count(*) from pg_indexes where tablename='test_tables';
```

count is 0;
this unique_index is not worked.

**Comment by jinzhu** [comment]
Hi

http://v2.gorm.io/docs/indexes.html#uniqueIndex

The tag name should be `unique_index`
