### ISSUE TITLE
mssql  intert data （mssql 插入数据） 

### ISSUE THREAD

**Issue by HenryStreeter** [go-gorm/gorm#3281]
## Your Question
insert data to mssql , the SQL will becombined with 'OUTPUT Inserted.' , causes a conflict with the trigger.

## The document you expected this should be explained

If the DML statement contains no With the OUTPUT clause of the INTO clause, the target table 'Table_Name' of the statement cannot have any enabled triggers
## Expected answer

How to cancel 'OUTPUT Inserted.'

**Comment by jinzhu** [comment]
Won't include the `OUTPUT Inserted.` if you are using a struct has no primary key or default values fields,
