### ISSUE TITLE
Incorrect SQL generated for Postgres Join with Where clause

### ISSUE THREAD

**Issue by LuaKT** [go-gorm/gorm#3285]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/79

## Description

When trying to use a where clause on a joined table using Postgres the incorrect SQL is generated. 
In the playground example the following SQL is generated for Postgres

```sql
SELECT "pets"."id","pets"."created_at","pets"."updated_at","pets"."deleted_at","pets"."user_id","pets"."name","pets"."pet_type_id","PetType"."id" AS "PetType__id","PetType"."created_at" AS "PetType__created_at","PetType"."updated_at" AS "PetType__updated_at","PetType"."deleted_at" AS "PetType__deleted_at","PetType"."type" AS "PetType__type" FROM "pets" LEFT JOIN "pet_types" AS "PetType" ON "pets"."pet_type_id" = "PetType"."id" WHERE PetType.Type = 'Cat' AND "pets"."deleted_at" IS NULL
```
Which generated the error
```
ERROR: missing FROM-clause entry for table "pettype" (SQLSTATE 42P01)
```

Quoting the  `WHERE` statement resolves it:

```sql
... WHERE "PetType"."Type" = 'Cat' ...
```

**Comment by jinzhu** [comment]
GORM won't quote string conditions like this: https://github.com/go-gorm/playground/pull/79/files#diff-53618cae32e23ae47e1c35f10da92654R20

**Comment by LuaKT** [comment]
Hmm ok, so the solution is to manually quote like this?

```go
DB.Joins("PetType").Find(&result, "\"PetType\".\"Type\" = ?", "Cat")
```

This seems pretty messy and also means we can't use the same queries for Postgres and Mysql

Thank you

**Comment by jinzhu** [comment]
DB.Joins("PetType").Find(&result, clause.Eq{Column: clause.Column{Table: "PetType", Name: "Type"}, Value: "Cat"})

**Comment by LuaKT** [comment]
I will use that, thank you
