### ISSUE TITLE
"more than one primary key" with embedded struct containing field named "ID"

### ISSUE THREAD

**Issue by ashutkul** [go-gorm/gorm#3286]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/80

## Description

I am embedding a base struct that contains a field called id. This base struct is embedded with a prefix (say base_) in a new struct. The new struct already has a primary key.

```
type Company struct {
	ID   int
	Name string
}

type Corp struct {
        gorm.Model
        Base Company `gorm:"embedded;embeddedPrefix:company_"`
}
```

The ID field from Company struct gets renamed as company_id (which is correct), but it is also carrying the "primary key" label. Thus Corp table creation fails with "more than one primary key" error.

The problem is that the schema for Company gets ID as primary key (because no other field has primary key), but with embeddedPrefix, the primary key selection logic needs to treat the field as company_id, not id.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
