### ISSUE TITLE
How to query a many2many relationship with a Where clause on the association?

### ISSUE THREAD

**Issue by lopes-gustavo** [go-gorm/gorm#3287]
## Your Question

I have the following entities:

```go
type User struct {
  ID     string
  Name   string
  Groups []Groups `gorm:"many2many:users_groups"`
}

type Groups struct {
  ID   string
  Name string
}
```

I know I can `preload` the groups using 

```go
var users []Users
db.Preload("Groups").Find(&users)
```

And I can also filter Users using

```go
var users []Users
db.Preload("Groups").Where("name IN ?", []string{"name1", "name2"}).Find(&users)
```
This will bring all the User that have name equals "name1" or "name2"

But I cannot filter Users based on Groups

```go
var users []Users
db.Preload("Groups", "name IN ?", []string{"groupname"}).Find(&users)
```

I expect it to bring all Users that have Group Name equal "groupname"

How can I achieve this using database only? (my database is big and I cannot load all users into memory and filter it in the application)

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/preload.html#Custom-Preloading-SQL

**Comment by jinzhu** [comment]
> I expect it to bring all Users that have Group Name equal "groupname"

You need to use join in this case

**Comment by lopes-gustavo** [comment]
But how can I do that?

If I use `.Join`, I'll end up with repeated values...
And the only way I could imagine using `Join` is mapping the rows myself into the entities.
But if I have to map myself the rows into the models, there's no point in using an ORM.

Is there a way to do that automatically that I'm not seeing?

Someone suggested [in this StackOverflow question](https://stackoverflow.com/questions/63475885/how-to-query-a-many2many-relationship-with-a-where-clause-on-the-association-wit) to use Join inside the `Preload`, but that simply filter the association, instead of the main model.

**Comment by take** [comment]
@lopes-gustavo were you able to find the solution for this problem? 👀 I'm having the same problem

**Comment by lopes-gustavo** [comment]
No, sorry.
I ended up using `Join` and mapping the rows myself.
Not the best solution, but it worked in the timeframe we had

**Comment by genofire** [comment]
With using `Join` i got duplicated entries of `User` if the `User` has both Groups in the `Join(, WHERE)`

**Comment by or-shek** [comment]
you can use:
db.Preload("Groups", "name IN (?)", []string{"name1", "name2"}).Find(&users)

**Comment by genofire** [comment]
@or-shek it also just filter the Groups, not the users (by there groups)

**Comment by Goxiaoy** [comment]
db.Joins("JOIN user_groups on user_groups.user_id = users.id JOIN groups on user_groups.group_id = groups.id AND groups.name in ? ", []string{"name1", "name2"})

**Comment by the25x8** [comment]
You may fetch users by group names very easily:
`db.Preload("Groups").Where("id IN (SELECT user_id FROM users_groups WHERE name IN ?)", []string{"name1", "name2"})`

**Comment by cendiastian** [comment]
> db.Joins("JOIN user_groups on user_groups.user_id = users.id JOIN groups on user_groups.group_id = groups.id AND groups.name in ? ", []string{"name1", "name2"}).Group("users.id")

this is works! but you need to preload before join, coz when i test your code, my many to many field still null, thanks anyway @Goxiaoy

**Comment by genofire** [comment]
I got it working with **INNER** join.

**Comment by yuseferi** [comment]
I've provided a solution with inner join : 
https://stackoverflow.com/questions/63475885/how-to-query-a-many2many-relationship-with-a-where-clause-on-the-association-wit/73797763#73797763

**Comment by whyayala** [comment]
> db.Joins("JOIN user_groups on user_groups.user_id = users.id JOIN groups on user_groups.group_id = groups.id AND groups.name in ? ", []string{"name1", "name2"}).Group("users.id")

This worked. Thanks a lot.

**Comment by itaranto** [comment]
> I've provided a solution with inner join : https://stackoverflow.com/questions/63475885/how-to-query-a-many2many-relationship-with-a-where-clause-on-the-association-wit/73797763#73797763

Your solution has the right approach but it has a small mistake:

```patch
 var users []Users
 db.Preload("Groups").
 Joins("inner join user_groups ug on ug.user_id = user.id ").
-Joins("inner join groups g on g.id= ug.user_id ").
+Joins("inner join groups g on g.id= ug.group_id ").
 Where("g.name IN ?", []string{"name1", "name2"}).Find(&users)
```

**Comment by yuseferi** [comment]
Hey @itaranto , I don't remember. it's been a long time since we are not using GORM. but thank you for your attention. btw, why do you have makefile? :D
