### ISSUE TITLE
How to create a Non Database column i want the column in struct but not in database

### ISSUE THREAD

**Issue by khanakia** [go-gorm/gorm#3288]
## Your Question
```
type Entity struct {
	ID       uint   `json:"id",gorm:"primary_key"`
	Key      string `json:"key",gorm:"unique;not null"`
	Value    string `json:"value"`
	TypeName string `json:"__typename"` // ignore this field

}
```
I have struct above and i do not want the `TypeName` column to be created in database. I want this column on Struct level only not on database. 

So how to prevent `TypeName` to be created in database ?

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/models.html#Field-Level-Permission

ignored fields won't be created when using GORM Migrator

**Comment by khanakia** [comment]
How can i have default value set for the column `TypeName` and i still want to ignore this column. So i want to set fixed value for this column always
