### ISSUE TITLE
Create UNIQUE INDEX on many2many incorrectly

### ISSUE THREAD

**Issue by StephanoGeorge** [go-gorm/gorm#3294]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/81

## Description

According to the log, gorm tried to
```sql
CREATE UNIQUE INDEX "idx_t01_t02_binds_name1" ON "t01_t02_binds" ("name1")
CREATE UNIQUE INDEX "idx_t01_t02_binds_name2" ON "t01_t02_binds" ("name2")
```
But it shouldn't be UNIQUE, or it's not many2many.

**Comment by StephanoGeorge** [comment]
Hi @jinzhu , can gorm create index but not unique?

**Comment by jinzhu** [comment]
Hi @StephanoGeorge 

It is better to create a composited index in this case, I think maybe you should change `Name` as the primary key to create a composited primary key(index) or customize the join table to create indexes as you want. http://v2.gorm.io/docs/many_to_many.html#Customize-JoinTable

**Comment by StephanoGeorge** [comment]
OK thanks, but I meant:
```sql
CREATE INDEX "idx_t01_t02_binds_name1" ON "t01_t02_binds" ("name1")
CREATE INDEX "idx_t01_t02_binds_name2" ON "t01_t02_binds" ("name2")
```
Because it is still very frequent to search for related objects based on the primary key of an object, like:
```sql
select name2 from t01_t02_binds where name1 = '1'
```
But If you think this is unnecessary(I can customize the association table to specify the index), that's it.

**Comment by jinzhu** [comment]
Hi, I think it is better to use the `name` column as primary key, if it is defined as the primary key, databases will create the index for it by default.

---

BTW, you can create create `unique index` with tag `index` like `index:",unique"`, so we can't not include the `index` tag when creating the join table.
