### ISSUE TITLE
How to use Limit,Offset,Order using Raw SQL ?

### ISSUE THREAD

**Issue by thaitanloi365** [go-gorm/gorm#3295]
## Describe the feature
How can use this query: `db.Raw("SELECT * FROM users").Limit(10).Offset(1).Scan(&users)`

Thanks you.

**Comment by jinzhu** [comment]
GORM won't change raw SQL

**Comment by nmccready** [comment]
> GORM won't change raw SQL

Why the heck not? This worked great in older gorm? If this will never work than `Limit` or `Offset` should at the very least throw Errors or add errors to the chain.
