### ISSUE TITLE
When Associated, the primary key is sometimes 0

### ISSUE THREAD

**Issue by StephanoGeorge** [go-gorm/gorm#3296]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/85

## Description

According to the output, the primary key of T02s are sometimes 0, but they should always be positive number.

And the last output on my postgres db (new table) is:
```
{
    "ID": 1,
    "Name": "1",
    "T02s": [
        {
            "ID": 6,
            "Name": "1-1"
        },
        {
            "ID": 0,
            "Name": "1-2"
        },
        {
            "ID": 0,
            "Name": "1-3"
        }
    ]
}
```

**Comment by StephanoGeorge** [comment]
Hi @jinzhu , can you check the last output in postgresql test? It maybe a bug.

**Comment by jinzhu** [comment]
I don't get it, can you make the tests fail with your expectation?

**Comment by StephanoGeorge** [comment]
@jinzhu
Oh sorry, I just closed the PR, it's open now.
Please check https://github.com/go-gorm/playground/pull/85/checks?check_run_id=1021939550#step:6:114

**Comment by jinzhu** [comment]
> Hi @jinzhu , can you check the last output in postgresql test? It maybe a bug.

Hi, yes, it seems a bug that we can't fix, it will happen when you are using a `unique` column and it gets conflicted when inserting ;(

But we should be able to avoid the issue if defined `name` as the primary key.

**Comment by StephanoGeorge** [comment]
Oh thanks 👍🏻️
