### ISSUE TITLE
Best way to create a record with many to many(many2many) associations via API

### ISSUE THREAD

**Issue by take** [go-gorm/gorm#3297]
Hi thanks for the awesome library! 😄 

I have one question, I want to create a record(lets say `User` in this case) which will be associated with a many2many model( `Card` in this case) via REST API.

The json will be something like this:

```javascript
{
  "user": {
    "name": "EpicName",
    "card_ids": [1, 4, 8]
  }
}
```

`Card` master data will be prepared beforehand, and the user will select the ones they own, so the data sent via the client will be `Card` 's primary key Array.

controller will be something like below(gin in this case):

```golang
type createParams struct {
	User models.User
}

func CreateUser(c *gin.Context) {
	var params createParams
	c.Bind(&params)

	user := params.User
	db.Create(&user)

	c.String(http.StatusCreated, "")
}
```

and the models as below:

```golang
type User struct {
	ID        uint
	name  string
	Cards []Card `gorm:"many2many:user_cards;"`
}

type Card struct {
	ID       uint
	name string
}
```

The problem in this case is that `user_cards` table data wont be created since `User` only has `#Cards` instead of `#CardIDs`

I guess this is a situation where most of the application encounters, and wondered how people are implementing this 🤔

**Comment by jinzhu** [comment]
You can use the `card_ids` to prepare cards data like `[]Card{{ID:1}, {ID: 4}}` and GORM will create the join table with those data.

Or you create the join table data by yourself with the card ids, refer: http://v2.gorm.io/docs/many_to_many.html#Customize-JoinTable

**Comment by take** [comment]
@jinzhu 

thanks for the reply! btw `[]Card{{ID:1}, {ID: 4}}` will try to create `cards` data if it doesn't exist right? :eyes: 

I guess the latter(creating join table data with the card ids) will be better 👍

**Comment by jinzhu** [comment]
> btw []Card{{ID:1}, {ID: 4}} will try to create cards data if it doesn't exist right? 👀

Yes, it will use `Upsert`
