### ISSUE TITLE
Does gorm's usage of protobuf/gogo @ v1.0.0 force me to use protobuf/gogo in my entire project at this version?

### ISSUE THREAD

**Issue by daodennis** [go-gorm/gorm#3300]
Hi,

I'm new as to what versions of my dependencies I need for compilation of my protobuf and how that changes in production runtime. 

I use gorm and grpc-gateway, it also requires I install proto-gen-go, do they need to be the same versions I use with gorm? maybe there Is there a project that uses gorm and grpc-gateway I can look at?

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/issues/3301#issuecomment-679050371
