### ISSUE TITLE
Create multiple row in a single query

### ISSUE THREAD

**Issue by maeglindeveloper** [go-gorm/gorm#3303]
Hi everyone, 

I'm wondering if there is a way to insert multiple record in a single request using gorm ?
I know that we can use `Exec` with a standard SQL query, but I would like to know if there is something easier to use 👍 
Thanks ;) !

**Comment by jinzhu** [comment]
GORM V2 support this, http://v2.gorm.io/docs/create.html#Batch-Insert

**Comment by maeglindeveloper** [comment]
@jinzhu thanks for the answer.
Is GORM V2 already available ?
