### ISSUE TITLE
Many2many association creation

### ISSUE THREAD

**Issue by raziel2244** [go-gorm/gorm#3305]
## Your Question

So I created my models and set up a many2many association, but when I create the objects and store them it's not creating all of the expected associations. 

Here is a minimal copy:
```
type Image struct {
  ID uuid.UUID
  Name string
}

type Animal struct {
  ID uuid.UUID
  Name string
  Images []*Image `gorm:"many2many:animal_images;"`
}

func main() {
  ...
  img := &Image{Name: "My Image"}
  db.Create(img)

  a1 := &Animal{
    Name: "My Animal 1",
    Images: []*Images{img}
  }
  db.Create(a1)

  a2 := &Animal{
    Name: "My Animal 2",
    Images: []*Images{img}
  }
  db.Create(a2)
  ...
}
```
After which I'm left with a record for each of them in the database, but the link table contains only one record for a1 to the image, not a2.

To make it clear, I'm trying to use the same image for both animals but it isn't linking to the second animal. What am I doing wrong?

## The document you expected this should be explained

A brief example on the many2many page for creating objects with associations would be fantastic, not just how to declare them.

http://gorm.io/docs/many_to_many.html

## Expected answer

How do I get the Image to be linked to both Animals, as far as I could see this was correct but unfortunately not.

**Comment by jinzhu** [comment]
GORM V2 should fix the issue.

**Comment by raziel2244** [comment]
Should it be fixed in the current v2 release, or in the future? I'm using v2 in this project already.

**Comment by jinzhu** [comment]
Then please create a bug report with a GORM Playground Pull Request Link that can reproduce the bug

**Comment by raziel2244** [comment]
I was using v0.2.28, updated to v0.2.37 and now it works
