### ISSUE TITLE
After upgrade to v0.2.36 got too many clients error

### ISSUE THREAD

**Issue by Hanggi** [go-gorm/gorm#3306]
I upgrade gorm.io/gorm to v0.2.36 and gorm.io/driver/postgres to v.0.2.9

I got `: server error (FATAL: sorry, too many clients already (SQLSTATE 53300))` errors

I don't know why but I tried ty downgrade to 0.2.35 and 0.2.9 for gorm and Postgres,
it works.

Thank you.

**Comment by jinzhu** [comment]
doesn't like a GORM issue, make sure there are no misusage, http://v2.gorm.io/docs/connecting_to_the_database.html#Connection-Pool

**Comment by kateile** [comment]
@Hanggi I get the same error on production, How did you fix it?

**Comment by Hanggi** [comment]
> @Hanggi I get the same error on production, How did you fix it?

Too long ago, I can't remember.

Have you tried increasing the number of connections pool?
