### ISSUE TITLE
sqlite has one 更新时自动保存关联无效

### ISSUE THREAD

**Issue by szaquila** [go-gorm/gorm#3307]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/87

## Description

sqlite创建has one关联，改变关联的数据后保存，再读取时发现关联的数据没有更新成功

**Comment by jinzhu** [comment]
If you changed the association's value, you have to update its value by yourself.  will update the document to describe that

```go
db.Save(&result.Account)
```

**Comment by voodoo-dn** [comment]
@jinzhu Do I correctly understand that gorm v2 do not support saving entities relation?

```
struct A {}
struct B {
 A A
}

db.Save(&B)
```

Does this method will update A and B entities to DB?
