### ISSUE TITLE
hasMany deletion error

### ISSUE THREAD

**Issue by soranoba** [go-gorm/gorm#3308]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/88

## Description

- User have some slice properties
- Company hasMany Users

In this case panic will occur if we try to delete.
Expected to be able to delete without panic.

This issue occurs when trying to compare structs that cannot be compared.

> Slice, map, and function values are not comparable.

https://golang.org/ref/spec#Comparison_operators

Structs with these cannot be compared and will crash at [here](https://github.com/go-gorm/gorm/blob/84dbb36d3bd91a5e7b3c1ee5a617ea923a4098d2/callbacks/delete.go#L44).

**Comment by jinzhu** [comment]
Fixed, thank you for your report, but better to use `&user` when deleting
