### ISSUE TITLE
unknown field ID in struct literal

### ISSUE THREAD

**Issue by khanakia** [go-gorm/gorm#3309]
## Your Question
I have the below code and i want to filter by ID but i cannot it gives error. Please suggest me the solution.

```
type File struct {
	gorm.Model
	FileName string `json:"fileName" gorm:"type:varchar(100)"`
}

var r File
res := db.Find(&r, &File{ID: 1}) // GETTING ERROR unknown field ID in struct literal

```
## The document you expected this should be explained

How to filter by ID ?

## Expected answer

I want to be able to filter by ID

**Comment by vincegio** [comment]
Try `&File{gorm.Model{ID:1}}`

**Comment by khanakia** [comment]
Thank you

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/query.html#Retrieving-with-primary-key

**Comment by khanakia** [comment]
> Try `&File{gorm.Model{ID:1}}`

Was not working anymore today so this is the new format `db.First(&account, &Account{Model: core.Model{ID: accountID}})`

**Comment by khanakia** [comment]
> http://v2.gorm.io/docs/query.html#Retrieving-with-primary-key

@jinzhu this is not working in case of Postgres UUID column

type Account struct {
  ID string `gorm:"type:uuid;default:uuid_generate_v4()"`
}

`db.First(&account, "060cbe89-3d9a-489d-9688-e7c1837983ea")`

ERROR
```
SELECT * FROM "accounts" WHERE 060cbe89-3d9a-489d-9688-e7c1837983ea ORDER BY "accounts"."id" LIMIT 1
ERROR: syntax error at or near "cbe89" (SQLSTATE 42601)
```

This should be the correct query
```
SELECT * FROM "accounts" WHERE "accounts"."id" = '060cbe89-3d9a-489d-9688-e7c1837983ea' ORDER BY "accounts"."id" LIMIT 1
```

**Comment by jinzhu** [comment]
https://gorm.io/docs/query.html#Retrieving-objects-with-primary-key
