### ISSUE TITLE
How to call postgresql functions

### ISSUE THREAD

**Issue by RXDA** [go-gorm/gorm#3311]
## Your Question

For example, I need to call to_timestamp(xxx_field),
```go
type A struct{
    ID int
    Time int
}
```

```sql
insert into A values(id, time) (1, to_timestamp('2020-08-26 15:00:00'));
```
I tried to use gorm.Expr() in valuer, but it failed.
I need a way to all functions, not only to_timestamp, this is just an example, thank you!

**Comment by RXDA** [comment]
some references
https://stackoverflow.com/questions/60520863/working-with-spatial-data-with-gorm-and-mysql/60537524
[#1924]https://github.com/go-gorm/gorm/pull/1924

**Comment by jinzhu** [comment]
Just implemented this feature, thank you for your issue ;)

http://v2.gorm.io/docs/data_types.html#GormValuerInterface

**Comment by RXDA** [comment]
It works, thank you again
