### ISSUE TITLE
How to use foreign key in gorm v2

### ISSUE THREAD

**Issue by tangducthinh456** [go-gorm/gorm#3312]
in gorm v1 I use postgres sql and migrage foreign key from code to database by add .AddForeignKey for example :+1:  
db.Model(&User{}).AddForeignKey("city_id", "cities(id)", "RESTRICT", "RESTRICT")
But when i change to use gorm v2 it does not have AddForeignKey like v1, and I have try to use foreign key by add gorm tags 
`gorm:"foreignKey:column"`,
For example i have 2 struct Student and University and i want 

type Student struct{
	StudentID uint `gorm:"column:student_id; primaryKey;autoIncrement:false"`
	Name string `gorm:"column:name"`
	UniversityID string `gorm:"column:university_id1; foreignKey"`
	University University `gorm:"foreignKey:university_id1;constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
}

type University struct{
	//Student Student `gorm:"foreignKey:StudentID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	UniversityID string `gorm:"column:university_id2; primaryKey;"`
	UniversityName string `gorm:"column:university_name"`
}

 but when it migrate to database,
  DB.Table("universities").AutoMigrate(&University{})
  DB.Table("students").AutoMigrate(&Student{})
table students in database also contains columns of the university object, it means table student(student_id, name, university_id1, university_id2, university_name).
So in v2 gorm is there any way to migrate foreign from code to database like AddForeignKey in v1 ?

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/v2_release_note.html#Migrator
