### ISSUE TITLE
"gorm:save_associations" it is very crusial while migration from gorm1.0 to 2.0

### ISSUE THREAD

**Issue by dkul108** [go-gorm/gorm#3313]
## Describe the feature

where do you lost things like
db.Set("gorm:save_associations", false).Create(&user)

db.Set("gorm:save_associations", false).Save(&user)

## Motivation
"gorm:save_associations" it is very crusial while migration from gorm1.0 to 2.0

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/v2_release_note.html#Associations

**Comment by dkul108** [comment]
thnk you, I'm aware about workaround. But you're offer to write imperative specific code per use case instead of declarative save_assotioations:false in mappings. Do you feel the difference?

**Comment by jinzhu** [comment]
don't get your idea, but you can only use `DB.Omit(clause.Associations).Create(&user)` in V2 to ignore all associations, which is easier & clear than v1?

**Comment by dkul108** [comment]
thank you,
first it is breaking and not backward changes, second simplest even just a CRUD operations have to be splitted in more complicated methods per each use case (e.g I hada a single upsert method and now I'll have a tons of more case specific cases)
(Of couse Im just speaking as a JPA/HIbernate user (for a last 20 yrs) so I'm expect naturally such a kind of things that are commonly used in Java based ORMs, but I'm beleive you will not reinvent better user experience for ORMs now unfortunately)
Would you like me to create a patch PR in order to attempt to return functionality removed? I'm really appreciate for the efforts of yours!

**Comment by jinzhu** [comment]
Have you read my word?

*DB.Omit(clause.Associations).Create(&user)  will ignore ____all____ associations*

**Comment by dkul108** [comment]
we dont need all - but a dozens from hundreds

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/91445979-6c298980-e8a9-11ea-9176-41005145faff.png)

http://v2.gorm.io/docs/models.html#Field-Level-Permission

**Comment by dkul108** [comment]
thank you, will try this and return with a reply

**Comment by dkul108** [comment]
I've got a nil panic error while testing permissions

![image](https://user-images.githubusercontent.com/5530302/91737037-d6df0b80-ebae-11ea-8758-fd8ad82d30e8.png)

**Comment by dkul108** [comment]
looks like a permissions for are for  primitive fields only and not for HasOne(etc)

**Comment by dkul108** [comment]
I mean hasOne with readonly permission crashes on Preload (for the reason unknown it is excluded from Preloads with reason unexpected)
