### ISSUE TITLE
updates更新指定字段问题。

### ISSUE THREAD

**Issue by Angel-zhy** [go-gorm/gorm#3315]
例如： 
      DB.Model(&user).Select("username", "header_img").Updates(model.User{NickName: "zhy11", Username: "admin11", HeaderImg: "11"}).Error
选择更新的字段中，下划线字段不能写在第1个，否则更新结构中全部字段.
更新指定字段：Select("username",  "header_img")
更新全部字段：Select("header_img", "username" )

**Comment by jinzhu** [comment]
fixed, thank you for your report.
