### ISSUE TITLE
Preload self-referential belongs to

### ISSUE THREAD

**Issue by Pourqavam** [go-gorm/gorm#3319]
## GORM Playground Link

[https://github.com/go-gorm/playground/pull/90](https://github.com/go-gorm/playground/pull/90)

## Description
**GORM v0.2.33**

I have a struct like this:
```go
type User struct {
	ID           int32 `gorm:"primaryKey"`
	Name         string
	CreatedBy    *int32
	Creator      *User `gorm:"foreignKey:CreatedBy;references:ID"`
}
```
and 2 rows in my db table:
|  id |  name | created_by  |
|:-:|---|---|
| 1  |  Ali |  null |
| 2  |  Reza | 1  |

When i get user 1 with `Preload("Creator").First(u, 1)` CreatedBy is nil but Creator is user 2.
And when i get user 2 with `Preload("Creator").First(u, 2)` CreatedBy is 1 but Creator is nil.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.

**Comment by chinmayb** [comment]
can this fix be backported to https://github.com/jinzhu/gorm/tree/master ?

**Comment by ShamuhammetYlyas** [comment]
> , thank you for your repo

same problem, did you solve this problem. Please reply if you solved.
