### ISSUE TITLE
dynamic table name

### ISSUE THREAD

**Issue by foxluqi** [go-gorm/gorm#3323]
## Describe the feature

gorm v2 does not support set table name dynamically, I cannot migrate old code from v1 to v2 now.

## Motivation

I have several tables with same data struct, I used to loop these table by change table name and handle with same logic. 

## Related Issues

I would like to know the solution on this case. Thank you!

**Comment by jinzhu** [comment]
http://v2.gorm.io/docs/v2_release_note.html#Table-Name
