### ISSUE TITLE
Do foreign keys work with SQLite?

### ISSUE THREAD

**Issue by gophobic** [go-gorm/gorm#3324]
Thanks for the great project. The method `AddForeignKey()` results in error after migration since it seems when enabling debugging and seeing the SQL command that is translated as `ALTER TABLE "TABLENAME" ADD CONSTRAINT ....` since `ADD CONSTRAINT` is not supported in sqlite in the first place. Since sqlite is very popular so this can't be simply a bug, does that mean that is not supported by gorm?

**Comment by jinzhu** [comment]
sqlite doesn't support create/drop CONSTRAINT after finish creating the table, so we can't support it ;(

**Comment by gophobic** [comment]
@jinzhu thanks, is there anyway to get around this?

**Comment by jinzhu** [comment]
sqlite only support recreate the table to add constraints
