### ISSUE TITLE
Group & Having - Picking the result struct as Table Name

### ISSUE THREAD

**Issue by khanakia** [go-gorm/gorm#3327]
I have Table `ledgers` and i am using one of the example in https://gorm.io/docs/query.html#Group-amp-Having

But as you can see in the log it is taking the `ledger_balances` as table not the `ledgers` and database is giving error as there is no table `ledger_balances` exists.

```
type Ledger struct {
	core.Model
	Amount    float64
	Currency  string
}

type LedgerBalance struct {
	Currency string 
	Total    float64
}

func GetBalance() {
	var result LedgerBalance
	db.LogMode(true)
	db.Model(&Ledger{}).Select("currency, sum(amount) as total").Group("currency").First(&result)
	fmt.Println(result)
}
```

**RESULT**
```
[2020-08-29 07:26:31]  pq: relation "ledger_balances" does not exist 

[2020-08-29 07:26:31]  [0.70ms]  SELECT currency, sum(amount) as total FROM "ledger_balances"   GROUP BY currency LIMIT 1  

[0 rows affected or returned ] 
{ 0}
```

**Comment by suciuvlad** [comment]
@khanakia Shouldn't it be `var result Ledger` instead? Also if the relation doesn't exist, perhaps the table hasn't been created in the db.

**Comment by jinzhu** [comment]
Looks like V1 syntax,  we can't accept V1 issues anymore (but only PR)

Give it a quick test, seems works in V2, if you can reproduce this in V2, please create PR on the playground.

**Comment by khanakia** [comment]
@jinzhu when i do ` go get gorm.io/gorm` it only installs `v1.9.19`
So i think i am using the latest version if not then how do i upgrade the latest version ?

**Comment by jinzhu** [comment]
> @jinzhu when i do ` go get gorm.io/gorm` it only installs `v1.9.19`
> So i think i am using the latest version if not then how do i upgrade the latest version ?

Hi, `v1.9.19` is the RC version of GORM V2, GORM V2 will be released soon.

**Comment by jinzhu** [comment]
Checkout https://gorm.io/docs/v2_release_note.html

**Comment by khanakia** [comment]
@jinzhu thanks the issue fixed but there is another issue now

`SELECT currency, sum(amount) as total FROM "ledgers" WHERE "ledgers"."deleted_at" IS NULL GROUP BY "currency" ORDER BY "ledgers"."id" LIMIT 1`
As you can see the it adding the ID in order by clause so i cannot sum the column

**ERROR**
```
ERROR:  column "ledgers.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ..."deleted_at" IS NULL GROUP BY "currency" ORDER BY "ledgers"....
                                                             ^
SQL state: 42803
Character: 120
```

**Comment by jinzhu** [comment]
this is the expected behaviour when using `First`, you can use `Find`
