### ISSUE TITLE
Getting `driver: bad connection` or `cached plan must not change result type (SQLSTATE 0A000)` or `failed to look up field with name: some_field`

### ISSUE THREAD

**Issue by shackra** [go-gorm/gorm#3335]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/96

## Description

I'm getting funny bugs in Gorm v2 when trying to apply some migrations in a fresh database, I've copied all the related files from my project.

with my full code base I get `driver: bad connection`, with this minimal example I  get `cached plan must not change result type (SQLSTATE 0A000)` and if I uncomment the code in  `pkg/model/v43/migration/v1/migration.go` I get `failed to look up field with name: otros_cargos`

this behavior may be related to the following reports:

- https://github.com/go-gorm/gorm/issues/2547
- https://github.com/go-gorm/gorm/issues/1578 (not even the same database product, but anyway)

**Comment by shackra** [comment]
I'm seeing also bugs on my CI (at Gitlab) that I thought were fixed:

```
2020/08/30 07:48:05 /builds/kuecr/fero/backend/monolith/pkg/model/v42/migration/v11/migration.go:7
[0.208ms] [rows:0] select * from "t_grupo"
2020/08/30 07:48:05 /builds/kuecr/fero/backend/monolith/pkg/model/v42/migration/v11/migration.go:7 pq: syntax error at or near "NOT"
[0.671ms] [rows:0] ALTER TABLE "t_grupo" ALTER COLUMN "correo_electronico" TYPE varchar(60) NOT NULL
```

https://github.com/shackra/playground/blob/2db869382c475b45ae849cf96cfb39f00510cfd1/pkg/model/v42/migration/v11/models.go#L72 is the exact same code as mine in my project but this issue is not triggered in your gorm playground :man_shrugging:

**Comment by jinzhu** [comment]
Hello，could you try to initalize the postgres db with PreferSimpleProtocol，check if the issue will be fixed？

refer https://github.com/go-gorm/postgres

Thank you

**Comment by shackra** [comment]
> Hello，could you try to initalize the postgres db with PreferSimpleProtocol，check if the issue will be fixed？
> 
> refer https://github.com/go-gorm/postgres
> 
> Thank you

Hi!

I did that in this commit https://github.com/go-gorm/playground/pull/96/commits/48b69f5981bf62e3ff543197e71d86529c4810d2 which allows the real bug to show itself: `failed to look up field with name:`

**Comment by shackra** [comment]
my playground fork is fully debugged but I can still reproduce a bug in my project's source code running in `golang:1.14-alpine` :(

```
monolith_1   | 2020-08-30T10:23:59.663010247Z 2020/08/30 04:23:59 /app/monolith/pkg/model/migrator/migrator.go:32
monolith_1   | 2020-08-30T10:23:59.663012227Z [0.096ms] [rows:0] SELECT * FROM "t_migration" WHERE id = '14-prepara la base de datos para comprobantes electrónicos 4.3'
monolith_1   | 2020-08-30T10:23:59.663633055Z
monolith_1   | 2020-08-30T10:23:59.663637215Z 2020/08/30 04:23:59 /go/pkg/mod/gorm.io/driver/postgres@v1.0.0/migrator.go:108
monolith_1   | 2020-08-30T10:23:59.663641985Z [0.473ms] [rows:0] SELECT count(*) FROM information_schema.tables WHERE table_schema =  CURRENT_SCHEMA() AND table_name = 't_otros_cargos' AND table_type = 'BASE TABLE'
monolith_1   | 2020-08-30T10:23:59.692439848Z
monolith_1   | 2020-08-30T10:23:59.692446537Z 2020/08/30 04:23:59 /app/monolith/pkg/model/v43/migration/v1/migration.go:12
monolith_1   | 2020-08-30T10:23:59.692449077Z [28.686ms] [rows:0] CREATE TABLE "t_otros_cargos" ("id" bigserial,"created_at" timestamptz,"updated_at" timestamptz,"deleted_at" timestamptz,"tipo_documento" bigint,"detalle" text,"porcentaje" text,"monto_cargo" text,"documento_id" bigint,PRIMARY KEY ("id"))
monolith_1   | 2020-08-30T10:23:59.697431029Z
monolith_1   | 2020-08-30T10:23:59.697439089Z 2020/08/30 04:23:59 /go/pkg/mod/gorm.io/driver/postgres@v1.0.0/migrator.go:79
monolith_1   | 2020-08-30T10:23:59.697441399Z [4.960ms] [rows:0] CREATE INDEX "idx_t_otros_cargos_deleted_at" ON "t_otros_cargos" ("deleted_at")
monolith_1   | 2020-08-30T10:23:59.698039067Z
monolith_1   | 2020-08-30T10:23:59.698044647Z 2020/08/30 04:23:59 /go/pkg/mod/gorm.io/driver/postgres@v1.0.0/migrator.go:108
monolith_1   | 2020-08-30T10:23:59.698046897Z [0.528ms] [rows:0] SELECT count(*) FROM information_schema.tables WHERE table_schema =  CURRENT_SCHEMA() AND table_name = 't_documento' AND table_type = 'BASE TABLE'
monolith_1   | 2020-08-30T10:23:59.701196835Z
monolith_1   | 2020-08-30T10:23:59.701200705Z 2020/08/30 04:23:59 /app/monolith/pkg/model/v43/migration/v1/migration.go:15
monolith_1   | 2020-08-30T10:23:59.701202755Z [3.108ms] [rows:0] select * from "t_documento"
monolith_1   | 2020-08-30T10:23:59.701248025Z
monolith_1   | 2020-08-30T10:23:59.701251375Z 2020/08/30 04:23:59 /app/monolith/pkg/model/v43/migration/v1/migration.go:15 driver: bad connection
monolith_1   | 2020-08-30T10:23:59.701253415Z [0.003ms] [rows:0] ALTER TABLE "t_documento" ADD "resumen_total_serv_exonerado" text
```

**Comment by jinzhu** [comment]
> my playground fork is fully debugged but I can still reproduce a bug in my project's source code running in golang:1.14-alpine :(

Maybe you are not using the latest postgres driver?

**Comment by jinzhu** [comment]
Seems tests pass right now, the `driver: bad connection` doesn't seems GORM issue, try to upgrade the postgres driver to check if this issue will be fixed.

**Comment by shackra** [comment]
> > my playground fork is fully debugged but I can still reproduce a bug in my project's source code running in golang:1.14-alpine :(
> 
> Maybe you are not using the latest postgres driver?

is that provided by the host operating system which in turn is a implicit dependency for any Go driver package for postgres?

How do I figure which version is the playground running?

**Comment by jinzhu** [comment]
playground using `postgres:latest` https://github.com/go-gorm/playground/blob/master/.github/workflows/tests.yml#L85

GORM tests using https://github.com/go-gorm/gorm/blob/master/.github/workflows/tests.yml#L110

**Comment by shackra** [comment]
for Debian buster (used as base for `postgres:12.4`, `posgres:12`, and `postgres:latest`) odbc-postgresql is version 1:11.00.0000-1, while in Alpine 3.12 (use for `golang:1.14-alpine`) is version 09.06.0410-r1 (built on 2018-11-07), thus is correct to say that this is the culprit?

**Comment by jinzhu** [comment]
so it only fail on v09.06.0410-r1?

**Comment by shackra** [comment]
> so it only fail on v09.06.0410-r1?

so far, it does, yes
