### ISSUE TITLE
named args and chain method doesn't work in raw query

### ISSUE THREAD

**Issue by slowvic** [go-gorm/gorm#3336]
here is my test code.

var list []GroupDto
tx := dao.Db.Raw(`
	select g.id,g.type_id,g.name,g.sort_no,t.code as type_code,t.name as type_name from dm_group g
	inner join dm_type t on t.id = g.type_id
`)
tx.Where("g.type_id = @typeId", sql.Named("typeId", typeId)).Scan(&list)
the where clause is ignored in the generated sql.

tx := dao.Db.Raw(`
	select g.id,g.type_id,g.name,g.sort_no,t.code as type_code,t.name as type_name from dm_group g
	inner join dm_type t on t.id = g.type_id
        where g.type_id = @typeId
`,sql.named("typeId",1)).Scan(&list)
typeId is NULL in the generated sql.

i can understand that Limit,Offset is not supported in raw query ,but Where is different, it's very common to create a dynamic query sql with different Where condition.

**Comment by jinzhu** [comment]
https://gorm.io/docs/sql_builder.html#Named-Argument

RAW SQL doesn't expect to works with any other chain methods

**Comment by slowvic** [comment]
我用中文说吧。
具名参数解析有个小bug，expression.go第97行判断具名参数结尾符号，少判断了“\n”换行符。
写比较长的原生sql时，用""可读性比较差，用····的比较多，这种情况下末尾有换行是很正常的。

**Comment by jinzhu** [comment]
> 具名参数解析有个小bug，expression.go第97行判断具名参数结尾符号，少判断了“\n”换行符。

已修复，感谢
