### ISSUE TITLE
Leave updated_at null on nullable updated_at

### ISSUE THREAD

**Issue by Pourqavam** [go-gorm/gorm#3337]
Hi
Sometimes updated_at used with allow null to be null when the record is first created and filled only if the record was updated.
I think if GORM leave the updated_at null on create if its type is nullable (either by pointer or sql.Null) it's be a good feature.
Thanks

**Comment by jinzhu** [comment]
disable the on create permission https://gorm.io/docs/models.html#Field-Level-Permission

**Comment by Pourqavam** [comment]
@jinzhu 
It can be a normal behavior without tag when the type is nullable. Tnx anyway.
