### ISSUE TITLE
GROM 自定义中间表的关联字段  (Grom customizes the associated fields of the intermediate table)

### ISSUE THREAD

**Issue by febelery** [go-gorm/gorm#3342]
## Your Question

 GROM 多对多关联修改中间表的关联字段,  默认的关联字段是 `xxx_model_id`这样的 , 我想去掉 `_model` 这个前缀

Grom many to many association modifies the associated fields of the intermediate table. The default associated field is `xxx_model_id`,  I want to get rid of this `_model` prefix

**Comment by jinzhu** [comment]
https://gorm.io/docs/gorm_config.html#naming_strategy
