### ISSUE TITLE
Any plans on Scan functionality similar to GormValue?

### ISSUE THREAD

**Issue by pdavid31** [go-gorm/gorm#3343]
## Your Question

Are there any plans for scan functionality similar to GormValue / GormValuerInterface? (see: https://gorm.io/docs/data_types.html#GormValuerInterface)

Example:

```golang
func (p Point) GormScan(_ context.Context, _ *gorm.DB) clause.Expr {
	return clause.Expr{
		SQL:  "ST_AsText(?)",
	}
}
```

Which would produce a Query like:

```sql
SELECT ST_AsText(geom) FROM ...;
```

**Comment by jinzhu** [comment]
Write SQL expression like https://github.com/go-gorm/gorm/blob/0273856e4d9744c98aa42b98d485d726099e9020/chainable_api.go#L119-L122 ?

**Comment by pdavid31** [comment]
This would be one possibility. Another would be to use db.Select("ST_AsText(geom)").Find...
But - correct me if I'm wrong - this would force me to specify the database function with every query to that model.

I was hoping to set a default behaviour on model level and avoid repetition with this.

Another benefit would be a more compact scan function, since I currently have to handle string and byte (EWKB) input, depending on whether the column is queried with or without a function.

**Comment by jinzhu** [comment]
You can use 

```go
clause.Select{ 
 	Distinct:   db.Statement.Distinct, 
 	Expression: clause.Expr{SQL: v, Vars: args}, 
 }
```

the `Vars` of `clause.Expr` support `GormValue` interface

**Comment by jinzhu** [comment]
also checkout use `Scopes` to share commonly logic 

https://gorm.io/docs/scopes.html

**Comment by pdavid31** [comment]
I'm sorry to bother you, but I don't quite understand, where you would use the select clause. (See example below)
The optimal case for me would be to define it with the model, just as the GormValue. The intend is to provide a package with PostGIS features without the user having to use functions other than the vanilla Gorm ones.

```go
type Point struct {
	Lat float64
	Lon float64
}

func (p *Point) String() string {
	return fmt.Sprintf("POINT(%f %f)", p.Lat, p.Lon)
}

// Scan expects a string given by use of PostGIS function ST_AsText when querying
func (p *Point) Scan(val interface{}) error {
	/*
	... string handling
	 */
}

func (p Point) GormDataType() string {
	return "geometry(POINTZ, 4326)"
}

func (p Point) GormValue(_ context.Context, _ *gorm.DB) clause.Expr {
	return clause.Expr{
		SQL:  "ST_PointFromText(?)",
		Vars: []interface{}{p.String()},
	}
}

func (p Point) QueryClauses(field *schema.Field) []clause.Interface {
	return []clause.Interface{
		clause.Select{
			Expression: clause.Expr{
				SQL:  "ST_AsText(" + field.DBName + ") as " + field.DBName,
			},
		},
	}
}
```

Optimal case for the user would then be:

```golang
type User struct {
	Name     string
	Location Point
}

func main() {
	/*
	connecting
	 */

	var users []User
        db.Find(&users)
}

```

**Comment by jinzhu** [comment]
check out https://github.com/go-gorm/gorm/blob/master/soft_delete.go#L27-L52 as example

If no `stmt.Selects` provides, you can get all field db names from `stmt.Schema.DBNames` and includes all of them into the `clause.Select`

If `stmt.Selects` provides, convert the `location` to above one if it is included.

**Comment by pdavid31** [comment]
Ah, I see, thanks for your help!

**Comment by cgetzen** [comment]
Hi @jinzhu, I'm having trouble applying this. To give you a rough idea of what I'm attempting, I'm trying to reverse the EncryptedString example [here](https://gorm.io/docs/data_types.html#Value-based-on-Context).
In this example, we are able to encrypt a model's field as it gets put into the database.
How can we reverse this to decrypt the field as we Scan data out of the database into the struct, using data from `ctx`?

**Comment by Icety** [comment]
You can also add a custom type that supports geom values:
I implemented mine using: [https://github.com/twpayne/go-geom](go-geom)
```

import (
	"database/sql/driver"
	"encoding/hex"
	"github.com/twpayne/go-geom"
	"github.com/twpayne/go-geom/encoding/ewkb"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

// GeomPoint defined GeomPoint data type, need to implements driver.Valuer, sql.Scanner interface
type GeomPoint geom.Point

// Value return geometry point value, implement driver.Valuer interface
func (g GeomPoint) Value() (driver.Value, error) {
	b := geom.Point(g)
	bp := &b
	ewkbPt := ewkb.Point{Point: bp.SetSRID(4326)}
	return ewkbPt.Value()
}

// Scan scan value into geom.Point, implements sql.Scanner interface
func (g *GeomPoint) Scan(value interface{}) error {
	t, err := hex.DecodeString(value.(string))
	if err != nil {
		return err
	}

	gt, err := ewkb.Unmarshal(t)
	if err != nil {
		return err
	}
	p := GeomPoint(*gt.(*geom.Point))
	*g = p

	return nil
}

// GormDBDataType gorm db data type
func (GeomPoint) GormDBDataType(db *gorm.DB, field *schema.Field) string {
	return "geometry(Point, 4326)"
}
```

With in your model then:
```
type City struct {
	Coords          GeomPoint  
}
```
