### ISSUE TITLE
How to use gorm in high QPS environment for MySQL "user defined variables"

### ISSUE THREAD

**Issue by rmgogogo** [go-gorm/gorm#3346]
## Your Question

How to use gorm in high QPS environment for MySQL "user defined variables".

```
UPDATE job_messages
    SET status='running', job_id=(@job_id:=job_id)
    WHERE status='pending' ORDER BY id ASC LIMIT 1;

SELECT @job_id AS JobID;
```

I'm using MySQL 5 for a job queue and used "user defined variables", here **@job_id**.

I expect the two SQLs are executed in the same DB CONNCETION and same SESSION. Otherwise, second query will fetch out the other session's value.

How can I handle it?

I tried following.

1. Multiple gorm.DB object. It means I maintain a gorm.DB pool. It should can work but I want to find other better way.
2. `db.WithContext(ctx)`. From gorm document, it seems handle solve this problem. However via reading gorm codes, I didn't find it well group the two SQLs in one session/connection.

So any suggestions?

**Comment by jinzhu** [comment]
use a transaction might works?

or write code like 
```go
DB.Raw("UPDATE job_messages
    SET status='running', job_id=(@job_id:=job_id)
    WHERE status='pending' ORDER BY id ASC LIMIT 1; SELECT @job_id AS JobID;").Scan(xx)
```

**Comment by rmgogogo** [comment]
> use a transaction might works?
> 
> or write code like
> 
> ```go
> DB.Raw("UPDATE job_messages
>     SET status='running', job_id=(@job_id:=job_id)
>     WHERE status='pending' ORDER BY id ASC LIMIT 1; SELECT @job_id AS JobID;").Scan(xx)
> ```

good idea, will try it. thanks.
Didn't aware we can put multiple SQL into one Raw method.

**Comment by rmgogogo** [comment]
> use a transaction might works?
> 
> or write code like
> 
> ```go
> DB.Raw("UPDATE job_messages
>     SET status='running', job_id=(@job_id:=job_id)
>     WHERE status='pending' ORDER BY id ASC LIMIT 1; SELECT @job_id AS JobID;").Scan(xx)
> ```

It can't work. The Raw only allow one statement.

Error log: 
> Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE job_messages SET status='running', job_id=(@job_id:=job_id) WHERE status=' at line 1
[2.136ms] [rows:0] SET @job_id = -1; UPDATE job_messages SET status='running', job_id=(@job_id:=job_id) WHERE status='pending' ORDER BY id ASC LIMIT 1; SELECT @job_id AS JobID

model:
```
type JobMessage struct {
	ID     int64  `gorm:"column:id; not null; primary_key; AUTO_INCREMENT"`
	JobID  string `gorm:"column:job_id; not null"`
	Status string `gorm:"column:status; not null; type:enum('pending', 'running', 'acked'); default:'pending'"`
}
```
