### ISSUE TITLE
`First()` can not get the ORDER BY field, resulting in incorrect SQL (v1.20.0)

### ISSUE THREAD

**Issue by kingzcheung** [go-gorm/gorm#3349]
## `First()` can not get the ORDER BY field, resulting in incorrect SQL

https://github.com/go-gorm/playground/pull/100

```golang
var data   map[string]interface{}
db.Table("ig_web_problem").Where(map[string]interface{}{"id":1}).First(&data)
```
sql:
```sql
SELECT * FROM `ig_web_problem` WHERE id = 1 ORDER BY `ig_web_problem`. LIMIT 1
```

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm.io/commit/8f4753a8ec831bbd3482dde43092410e778b6051

thank you for your report.
