### ISSUE TITLE
V2版 find to map没有正确的识别数据类型

### ISSUE THREAD

**Issue by puzhengwu** [go-gorm/gorm#3351]
var m []map[string]interface{}
Db.Raw("select * from user").Scan(&m)
for _, item := range m {
		fmt.Println(item["name"].(string))
	}
数据库里name是varchar类型，用.(string)报错interface {} is []uint8, not string
应该是查询时直接用了conn.query而不是先conn.prepare拿到stmt再query,所以没有类型，希望使用&gorm.Config{PrepareStmt: true}后能通过先prepare再query，如是设置false可以直接用query保证性能

**Comment by puzhengwu** [comment]
package main

import (
	"fmt"
	"log"
	
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

func main()  {
	db, err := gorm.Open(mysql.Open("dev:dev@tcp(192.168.10.187:3306)/test?charset=utf8&parseTime=True&loc=Local"), &gorm.Config{PrepareStmt: true})
	if err != nil {
		log.Fatal(err)
	}

	var m []map[string]interface{}
	db.Raw("select * from user").Scan(&m)

	for _, item := range m {
		fmt.Println(item["name"].(string))
	}
}

**Comment by puzhengwu** [comment]
panic: interface conversion: interface {} is []uint8, not string

goroutine 1 [running]:
main.main()
        /Users/larry/work/go/src/gormtest/main.go:20 +0x2b4

Process finished with exit code 2

**Comment by puzhengwu** [comment]
CREATE TABLE `user` (
  `id` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `user` VALUES ('1', 'larry');

**Comment by wleven** [comment]
忘记补充  表里面有6000行数据

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
