### ISSUE TITLE
Do we have any plan to support opentelemetry.

### ISSUE THREAD

**Issue by j2gg0s** [go-gorm/gorm#3355]
Thanks for this wonderful project.

## Describe the feature
Do we have any plan to support trace with [opentelemetry](https://github.com/open-telemetry/opentelemetry-go) .

**Comment by jinzhu** [comment]
I don't have any plan to integrate it, but contributions welcome.

**Comment by j2gg0s** [comment]
Trace with driver may be better than orm, so i migrate [ocsql](https://github.com/opencensus-integrations/ocsql) to [otsql](https://github.com/j2gg0s/otsql) .
otsql wrapped ``database/sql`` and support trace with [opentelemetry](https://github.com/open-telemetry/opentelemetry-go) .

And some example with gorm have supported [here](https://github.com/j2gg0s/otsql/tree/master/example/gorm.io/gorm).

Do you think i should add special config option for gorm/driver/mysql and gorm/driver/postgres.
@jinzhu
