### ISSUE TITLE
Cannot load V1 gorm anymore since "default" branch is empty

### ISSUE THREAD

**Issue by nekodojo** [go-gorm/gorm#3356]
Today I was trying to execute this to download a dependency we need.
  go get github.com/jinzhu/gorm
It looks like "master" is no longer the default branch and "v2" branch is empty except a readme, so I get an error that there are no Go files in that package directory.

Sadly Go has no way to simply get a different tag
  go get github.com/jinzhu/gorm@master  # doesn't work

Here is my painful workaround
	mkdir -p  ~/go/src/github.com/jinzhu/
	(cd  ~/go/src/github.com/jinzhu/ && rm -rf gorm && git clone  --branch master https://github.com/jinzhu/gorm.git)
	go build github.com/jinzhu/gorm
	go install github.com/jinzhu/gorm

I understand that all the focus is on V2 but for those of us who have to use V1 can you set the default branch to something non-empty?  The name doesn't matter, you can make it "v1" as long as it's set as default.

Thanks

**Comment by jinzhu** [comment]
Changed the default branch to master

**Comment by nekodojo** [comment]
Verified working. Thanks for the quick response (and thanks for keeping up the package)
