### ISSUE TITLE
Our Pipeline is getting failed due to  go get gorm.io/gorm

### ISSUE THREAD

**Issue by moodleexpert** [go-gorm/gorm#3360]
Our Pipeline is getting failed due to go get

Can you please check, we are unable to push the changes.

unrecognized import path "gorm.io/gorm/clause": reading https://gorm.io/gorm/clause... 404 Not Found
unrecognized import path "gorm.io/gorm/logger": reading https://gorm.io/gorm/logger... 404 Not Found
unrecognized import path "gorm.io/gorm/schema": reading https://gorm.io/gorm/schema... 404 Not Found
unrecognized import path "gorm.io/gorm/callbacks": reading https://gorm.io/gorm/callba... 404 Not Found
unrecognized import path "gorm.io/gorm/migrator": reading https://gorm.io/gorm/migrat... 404 Not Found

Regards
Nikhil

**Comment by jinzhu** [comment]
doesn't like a GORM issue, check your env

**Comment by moodleexpert** [comment]
We are using Jenkins on K8s... While creating our development build we are facing this  error

Docker file
FROM golang:latest as builder

FROM moogar0880/glide as build

RUN mkdir -p /go/src/pro/procdn/backend

ADD . /go/src/pro/procdn/backend

WORKDIR /go/src/pro/procdn/backend/reporting/

EXPOSE 1236

RUN pwd

RUN go get -v . 

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .


FROM scratch

COPY --from=builder /go/src/pro/procdn/backend/reporting  /app/

WORKDIR /app

EXPOSE 1236

ENTRYPOINT [ "./main" ]



Jenkins Output
Step 11/17 : RUN go get -v .
 ---> Running in bb1eacbff438
[91mgithub.com/dgrijalva/jwt-go (download)
[0m[91mgithub.com/cockroachdb/apd (download)
[0m[91mgithub.com/pkg/errors (download)
[0m[91mgithub.com/jung-kurt/gofpdf (download)
[0m[91mgithub.com/microcosm-cc/bluemonday (download)
[0m[91mgithub.com/chris-ramon/douceur (download)
[0m[91mgithub.com/gorilla/css (download)
[0m[91mFetching https://golang.org/x/net/html?go-get=1
[0m[91mParsing meta tags from https://golang.org/x/net/html?go-get=1 (status code 200)
[0m[91mget "golang.org/x/net/html": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html?go-get=1
get "golang.org/x/net/html": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
[0m[91mParsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
[0m[91mgolang.org/x/net (download)
[0m[91mgithub.com/shopspring/decimal (download)
[0m[91mFetching https://gopkg.in/go-playground/validator.v9?go-get=1
[0m[91mParsing meta tags from https://gopkg.in/go-playground/validator.v9?go-get=1 (status code 200)
[0m[91mget "gopkg.in/go-playground/validator.v9": found meta tag main.metaImport{Prefix:"gopkg.in/go-playground/validator.v9", VCS:"git", RepoRoot:"https://gopkg.in/go-playground/validator.v9"} at https://gopkg.in/go-playground/validator.v9?go-get=1
[0m[91mgopkg.in/go-playground/validator.v9 (download)
[0m[91mgithub.com/go-playground/universal-translator (download)
[0m[91mgithub.com/go-playground/locales (download)
[0m[91mgithub.com/leodido/go-urn (download)
[0m[91mFetching https://gorm.io/driver/mysql?go-get=1
[0m[91mParsing meta tags from https://gorm.io/driver/mysql?go-get=1 (status code 200)
[0m[91mget "gorm.io/driver/mysql": found meta tag main.metaImport{Prefix:"gorm.io/driver/mysql", VCS:"git", RepoRoot:"https://github.com/go-gorm/mysql"} at https://gorm.io/driver/mysql?go-get=1
[0m[91mgorm.io/driver/mysql (download)
[0m[91mgithub.com/go-sql-driver/mysql (download)
[0m[91mFetching https://gorm.io/gorm?go-get=1
[0m[91mParsing meta tags from https://gorm.io/gorm?go-get=1 (status code 200)
[0m[91mget "gorm.io/gorm": found meta tag main.metaImport{Prefix:"gorm.io/gorm", VCS:"git", RepoRoot:"https://github.com/go-gorm/gorm"} at https://gorm.io/gorm?go-get=1
[0m[91mgorm.io/gorm (download)
[0m[91mFetching https://gorm.io/gorm/clause?go-get=1
[0m[91mParsing meta tags from https://gorm.io/gorm/clause?go-get=1 (status code 404)
[0m[91mpackage gorm.io/gorm/clause: unrecognized import path "gorm.io/gorm/clause" (parse https://gorm.io/gorm/clause?go-get=1: no go-import meta tags ())
Fetching https://gorm.io/gorm/logger?go-get=1
[0m[91mParsing meta tags from https://gorm.io/gorm/logger?go-get=1 (status code 404)
[0m[91mpackage gorm.io/gorm/logger: unrecognized import path "gorm.io/gorm/logger" (parse https://gorm.io/gorm/logger?go-get=1: no go-import meta tags ())
Fetching https://gorm.io/gorm/schema?go-get=1
[0m[91mParsing meta tags from https://gorm.io/gorm/schema?go-get=1 (status code 404)
[0m[91mpackage gorm.io/gorm/schema: unrecognized import path "gorm.io/gorm/schema" (parse https://gorm.io/gorm/schema?go-get=1: no go-import meta tags ())
[0m[91mFetching https://gorm.io/gorm/callbacks?go-get=1
[0m[91mParsing meta tags from https://gorm.io/gorm/callbacks?go-get=1 (status code 404)
[0m[91mpackage gorm.io/gorm/callbacks: unrecognized import path "gorm.io/gorm/callbacks" (parse https://gorm.io/gorm/callbacks?go-get=1: no go-import meta tags ())
Fetching https://gorm.io/gorm/migrator?go-get=1
[0m[91mParsing meta tags from https://gorm.io/gorm/migrator?go-get=1 (status code 404)
[0m[91mpackage gorm.io/gorm/migrator: unrecognized import path "gorm.io/gorm/migrator" (parse https://gorm.io/gorm/migrator?go-get=1: no go-import meta tags ())
[0m[91mgithub.com/gorilla/handlers (download)
[0m[91mgithub.com/felixge/httpsnoop (download)
[0m[91mgithub.com/gorilla/mux (download)
[0mThe command '/bin/sh -c go get -v .' returned a non-zero code: 1
