### ISSUE TITLE
How to upgrade from v1's "gorm.ToColumnName(Something)"

### ISSUE THREAD

**Issue by System-Glitch** [go-gorm/gorm#3361]
## Your Question

I am currently migrating my project from GORM v1 to v2. The method `gorm.ToColumnName("Something")` is not there anymore. This function was in charge of converting a struct field name into a column name (snake_case conversion).

This is my use-case. `columnName()` allows to get the database column name for a struct field, taking into account potential overrides. It is now outdated.
```go
func columnName(field *reflect.StructField) string {
	for _, t := range strings.Split(field.Tag.Get("gorm"), ";") { // Check for gorm column name override
		if strings.HasPrefix(t, "column") {
			v := strings.Split(t, ":")
			return strings.TrimSpace(v[1])
		}
	}

	return gorm.ToColumnName(field.Name)
}
```

## The document you expected this should be explained

[Here](https://gorm.io/docs/models.html), or maybe [here](https://gorm.io/docs/migration.html). This is a breaking change that isn't documented in the [release note](https://gorm.io/docs/v2_release_note.html) too.

## Expected answer

Can you please give me pointers towards the function I should be using to update my `columnName()` function? How can I take the global column naming strategy into account too? Is it possible to do it efficiently without parsing the whole model?

**Comment by System-Glitch** [comment]
I found how to do it:
```go
db.Config.NamingStrategy.ColumnName("", field.Name)
```

**Comment by lukaszraczylo** [comment]
@System-Glitch thank you so much for posting the answer!
