### ISSUE TITLE
new db session with PrepareStmt:true config doesn't work

### ISSUE THREAD

**Issue by crazytaxi824** [go-gorm/gorm#3362]
## Description

// 会话模式
`tx := db.Session(&gorm.Session{PrepareStmt: true})`
`fmt.Println(tx.PrepareStmt) `

output: false

**Comment by jinzhu** [comment]
We are not setting the value to the Config, the value won't be used for GORM, so we only changed the `ConnPool`, are you using it for something?

**Comment by crazytaxi824** [comment]
> We are not setting the value to the Config, the value won't be used for GORM, so we only changed the `ConnPool`, are you using it for something?

sorry, i haven't explained the case clearly.

when i do the followings as the doc says:
[https://gorm.io/zh_CN/docs/session.html](https://gorm.io/zh_CN/docs/session.html)

```
// 会话模式
tx := db.Session(&Session{PrepareStmt: true})
tx.First(&user, 1)
tx.Find(&users)
tx.Model(&user).Update("Age", 18)

// returns prepared statements manager
stmtManger, ok := tx.ConnPool.(*PreparedStmtDB)
```

`ok` always `false`, which means type assertion failed. unless I use globally mode:
```
// 全局模式，所有 DB 操作都会 创建并缓存预编译语句
db, err := gorm.Open(sqlite.Open("gorm.db"), &gorm.Config{
  PrepareStmt: true,
})
...
// returns prepared statements manager
stmtManger, ok := db.ConnPool.(*PreparedStmtDB)
```
`ok` is `true` in this case.

**Comment by jinzhu** [comment]
Got it, we only set the value to `db.Statement.ConnPool` but not `db.ConnPool`, just fixed that, thank you for your clarification
