### ISSUE TITLE
how to search fields contains '%' or '_'

### ISSUE THREAD

**Issue by hyhy01** [go-gorm/gorm#3364]
## Your Question
belows datas in database
[`开发a`,`开发b`,`开发_`,`开发%`]
exec
`err = db.Where("ms LIKE concat('%',?,'%')", "开发_").Find(&list).Error`
return
[`开发a`,`开发b`,`开发_`,`开发%`]

## Expected answer
返回
[`开发_`]

**Comment by jinzhu** [comment]
NOT a GORM related question

`Where("ms = ?", "开发_")`

**Comment by hyhy01** [comment]
but i need ‘like’
