### ISSUE TITLE
Panic when using composite primary keys for struct without "ID" field

### ISSUE THREAD

**Issue by ericot** [go-gorm/gorm#3365]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/103

## Description

Creating an association which uses a composite primary key where neither column is named "ID" or "id" causes the library to panic when parsing the schema.

This scenario is common when creating 1-to-many associations where the associated rows don't have any identity. In the playground example we attach "labels" to an user which stores metadata as a key-value pair, and assign the foreign key to be part of the primary key as well.

This appears to be caused by the `Schema.PrioritizedPrimaryField` field being `nil`, which then panics when saving the association. The code that panics can be found [here](https://github.com/go-gorm/gorm/blob/130f24090db2b9862282281f9dd288c2a214a263/callbacks/associations.go#L233).

The field is set [here](https://github.com/go-gorm/gorm/blob/130f24090db2b9862282281f9dd288c2a214a263/schema/schema.go#L179), but this behaviour doesn't seem to align with this [documentation](https://gorm.io/docs/write_plugins.html). According to the documentation `PrioritizedPrimaryField` should be set to the first defined primary key if no field "id" exists.

**Comment by gabstv** [comment]
I updated to fcb666c but the error persisted. I'm using 3 FKs for the primary key:

```go
type GroupRolePermission struct {
	Group      Group      `json:"group" gorm:"primaryKey;foreignKey:Name"`
	Role       Role       `json:"role" gorm:"primaryKey;foreignKey:Name"`
	Permission Permission `json:"permission" gorm:"primaryKey;foreignKey:Name"`
}
```
