### ISSUE TITLE
Primary key of a UUID generates wrong SQL for MySQL

### ISSUE THREAD

**Issue by onetwopunch** [go-gorm/gorm#3366]
According to the [docs](https://gorm.io/docs/query.html), to retrieve an object (User) via the primary key, you simply need:

```
id = "545b555f-2572-4746-9854-a9ae30f4d9fb"
var user User
result := db.First(&user, id)
```

However when I try this against a primary key of a UUID, Gorm generates the wrong SQL statement and an error:

```
Error 1054: Unknown column '545b555f' in 'where clause'
[2.118ms] [rows:0] SELECT * FROM `users` WHERE 545b555f-2572-4746-9854-a9ae30f4d9fb AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1
```

When I update the code to instead be:

```
id = "545b555f-2572-4746-9854-a9ae30f4d9fb"
var user User
result := db.Where("id = ?", id).First(&user)
```

Everything works as expected.

**Comment by jinzhu** [comment]
Hi,

Query with inline condition primary key only works with number

https://gorm.io/docs/query.html#Retrieving-with-primary-key

![image](https://user-images.githubusercontent.com/6843/92064218-a1fdcf00-edcf-11ea-9aca-2d858ddf3c8c.png)
