### ISSUE TITLE
How to rollback or commit in a transaction(some involved questions)?

### ISSUE THREAD

**Issue by mttbx** [go-gorm/gorm#3371]
Here's two questions I don't know.
1. If I use "Default Transaction", how to commit or rollback? (maybe db.commit?)
2. If I use "Transactions by manual", should I rollback if I get an error from commit? And what's the occasion of rollback failure and  how can I prevent dead lock?

**Comment by jinzhu** [comment]
https://gorm.io/docs/transactions.html

> should I rollback if I get an error from commit
 not necessary

**Comment by mttbx** [comment]
I've read about these document. I still don't know how to do the right thing. Can you answer my questions directly?

**Comment by mttbx** [comment]
I don't want to use db.Transaction, it have to convert my error msg to error and convert it back at the next time.

**Comment by mttbx** [comment]
I find db.Transaction is good enough to be useful.
