### ISSUE TITLE
db caches every SQL statement on the Database(postgresql)?

### ISSUE THREAD

**Issue by crazytaxi824** [go-gorm/gorm#3373]
## Your Question

```
func TestPrepareStatement(t *Testing.T){
    db, _ := gorm.Open(postgres.Open(dsn), &gorm.Config{})

    var i Item
    db.Table("item").First(&i)
    t.Log(i)

    type prepareRes struct {
	Name        string    `gorm:"Column:name"`
	Statement   string    `gorm:"Column:statement"`
	PrepareTime time.Time `gorm:"Column:prepare_time"`
	FromSQL     bool      `gorm:"Column:from_sql"`
    }

    // check the pg_prepared_statements table
    var pr []prepareRes
    db.Table("pg_prepared_statements").Scan(&pr)

    t.Logf("%+v\n", pr)
}
```

When i use the same session to check the `pg_prepared_statements` table, there are 2 results:
Name:lrupsc_1_0 Statement:SELECT * FROM "item" ORDER BY "item"."id" LIMIT 1  ...
Name:lrupsc_1_1 Statement:SELECT * FROM "pg_prepared_statements" ...

This means even `PrepareStmt: false` in `gorm.Config{}`, the SQL statements are still cached in Database. 

Is this correct? If i didn't destroy this session, will Postgresql catches more and more statements? 
Thanks guys

**Comment by jinzhu** [comment]
https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL

`PreferSimpleProtocol: true`

**Comment by crazytaxi824** [comment]
Got it. Thanks a lot
