### ISSUE TITLE
Has one relationship does not return related entity

### ISSUE THREAD

**Issue by jLemmings** [go-gorm/gorm#3376]
## Your Question
An entity with an has one relation does not return the referenced entity on query. Entity Depository has one City and one County. Getting the result from the DB does not return the City or County entity. See playground demo: https://github.com/go-gorm/playground/pull/105

## The document you expected this should be explained
https://gorm.io/docs/has_one.html Examples with results would be helpfull to understand the documentation.

## Expected answer
https://github.com/go-gorm/playground/pull/105
Where is the issue in this playground example?

**Comment by jinzhu** [comment]
Hello, V2 doesn't support preload in that way anymore, refer https://gorm.io/docs/preload.html
