### ISSUE TITLE
数据库database is closed问题

### ISSUE THREAD

**Issue by axaxx** [go-gorm/gorm#3377]
## Your Question

当数据库处于关闭状态,启动go程序之后,读取数据的时候报database is closed错误.这个时候即使把数据库服务打开,在访问程序的时候还是报database is closed,gorm不会重新连接数据库.

**Comment by jinzhu** [comment]
works for me

![image](https://user-images.githubusercontent.com/6843/92118918-aa82f380-ee29-11ea-80cd-f04edb0fda5f.png)

![image](https://user-images.githubusercontent.com/6843/92118986-bf5f8700-ee29-11ea-8a91-d77cb8bd4fb6.png)

**Comment by axaxx** [comment]
我发一下我的实验
我在您的代码中做了一个日志
![image](https://user-images.githubusercontent.com/29572463/92194344-063a9480-ee9d-11ea-8bcd-540905904d0e.png)
首先我关闭数据库然后尝试启动go程序.注意:是先关闭数据库,在启动程序顺序不要弄反了
然后它报错了
![image](https://user-images.githubusercontent.com/29572463/92194469-4ef24d80-ee9d-11ea-9315-1153533bc875.png)
而且读取不到数据
![image](https://user-images.githubusercontent.com/29572463/92194614-b27c7b00-ee9d-11ea-9575-9af6ab25a82a.png)
数据库这个时候是链接不上的
![image](https://user-images.githubusercontent.com/29572463/92194508-70ebd000-ee9d-11ea-921a-4976febb9037.png)
然后我打开数据库
![image](https://user-images.githubusercontent.com/29572463/92194558-8e209e80-ee9d-11ea-918e-503bc83095b7.png)
![image](https://user-images.githubusercontent.com/29572463/92194572-937de900-ee9d-11ea-8e93-ac04dc32c1d3.png)
然后我在尝试在程序中读取数据,他仍然获取不到数据,而且没有进行重新连接输出预期的 ---"尝试链接数据库"
![image](https://user-images.githubusercontent.com/29572463/92194711-f1123580-ee9d-11ea-9f2d-136608e40c8c.png)
最后我在数据库连接的状态下重新启动go程序
![image](https://user-images.githubusercontent.com/29572463/92194753-07b88c80-ee9e-11ea-9edd-75f7175272b5.png)
![image](https://user-images.githubusercontent.com/29572463/92194792-156e1200-ee9e-11ea-874f-430aa4a6acb5.png)
![image](https://user-images.githubusercontent.com/29572463/92194838-2d459600-ee9e-11ea-82c6-fc3c8681d99f.png)
没有报错了
建议:我觉得应该在数据库链接失败的时候应该重新连接数据库

**Comment by axaxx** [comment]
我做go开发时间还不长刚刚两个星期,可能提的问题不是很好,请指正

**Comment by axaxx** [comment]
@jinzhu

**Comment by wolking** [comment]
我也出现这个问题
