### ISSUE TITLE
error when execute prepared statement with params.

### ISSUE THREAD

**Issue by crazytaxi824** [go-gorm/gorm#3379]
## Your Question

```
func TestPrepare(t *testing.T) {
	err := DB.Exec(`PREPARE foo (bigint,text) AS INSERT INTO "company" ("id","name") VALUES ($1, $2);`).Error
	if err != nil {
		t.Error(err)
		return
	}

	err = DB.Exec(`EXECUTE foo(102, 'abc')`).Error
	if err != nil {
		t.Error(err)
		return
	}
}
```
SQL statement shows `EXECUTE foo(102, 'abc')`, and Insert successes.

If i change  it to:
```
        err = DB.Exec(`EXECUTE foo(?, ?)`, 102, "abc").Error
	if err != nil {
		t.Error(err)
		return
	}
```
SQL statement shows `EXECUTE foo(102, 'abc')`,
but error: `pq: got 2 parameters but the statement requires 0.`

Am I doing something wrong?
Thanks guys.

**Comment by jinzhu** [comment]
seems caused by `pgx`'s bug, I have fixed it in this pull request. https://github.com/jackc/pgx/pull/816

you can use my fork right now, for example: https://github.com/go-gorm/gorm/blob/dd0d74fad06342a792a1cdc20101a57ee019f447/tests/go.mod#L18
