### ISSUE TITLE
unique index is created when auto migrate run in each time

### ISSUE THREAD

**Issue by foxluqi** [go-gorm/gorm#3381]
## Description
```
type SysUser struct {
	ID       int    `gorm:"primaryKey;autoIncrement"`
	Name     string `gorm:"size:50;not null"`
	Username string `gorm:"size:50;uniqueIndex;not null"`
	Password string `gorm:"type:text;not null"`
	Email    string `gorm:"type:text;"`
	Active   bool   `gorm:"default:false"`
	Audit
}
db.AutoMigrate(
		&SysUser{},
)
```
result in mysql
![unique_index](https://user-images.githubusercontent.com/5027825/92103487-a13a5c80-ee12-11ea-84d6-87e0a25fa76c.png)

**Comment by jinzhu** [comment]
seems works for me or please create playground pr

![image](https://user-images.githubusercontent.com/6843/92105961-3ab73d80-ee16-11ea-9581-0c554c3223b5.png)
![image](https://user-images.githubusercontent.com/6843/92105973-4145b500-ee16-11ea-880f-5e0a51871783.png)

**Comment by foxluqi** [comment]
the unique index seems ok now. But some fields will run command alter every time.
pls check the pr below.
https://github.com/go-gorm/playground/pull/116

**Comment by jinzhu** [comment]
the issue should be fixed on latest master.
