### ISSUE TITLE
[not same as v1] model struct contain `interface{}`

### ISSUE THREAD

**Issue by zzjin** [go-gorm/gorm#3386]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/112

## Description

Use db as k-v store. in such case some colum will diff from eachother. As see on playground one table save different prop values. works well on V1.

Why not just declaring `PropValue` as `datatypes.JSON`: 
It's useful when hidden json impl(for future compress with gz or other marshal method).
for upper caller, just passing struct with needed key and value,and get back key and value using `PropValue.(customstruct)`, no need to care about how db really saved the different struct.
Meanwhile, raw struct field `datatypes.JSON` will lead  caller cannot just get back struct slice.

定义一个表保存不同的数据结构,特定字段支持不同的数据类型,playgroud有具体的使用场景.在v1工作良好.

为什么不直接把`PropValue`字段定义成 `datatypes.JSON`: 
在调用的时候才决定结构类型可以隐藏db层对数据的读写的具体实现(json,是否压缩或者别的序列化方案).
对于调用方来说,set时候直接传入key和value(不同的struct),然后获取的时候也直接拿到key和对应的value.
不需要关心db层内部如何存储的.
如果直接定义成`datatypes.JSON`的话,调用方没法简单的获取接收一个包含了多个数据的数组(需要再定一个struct)

**Comment by jinzhu** [comment]
seems works for me, although the result is `**interface{}{}`

![image](https://user-images.githubusercontent.com/6843/92193803-d17a0d80-ee9b-11ea-9bc2-b4b340f1d714.png)

![image](https://user-images.githubusercontent.com/6843/92193867-f4a4bd00-ee9b-11ea-907d-a36b2e297eb6.png)
