### ISSUE TITLE
Converting NULL to string is unsupported

### ISSUE THREAD

**Issue by flusflas** [go-gorm/gorm#3387]
go-gorm/playground#113

I can't reopen my last issue (https://github.com/go-gorm/gorm/issues/3363), but after the changes made to allow `NULL` as default value, I'm getting `Error: sql: Scan error on column index 0, name "value": converting NULL to string is unsupported` using PostgreSQL. SQLite and MySQL seem to be working.

**Comment by jinzhu** [comment]
Hello @flusflas 

The recommend way is using `pointers` or `sql.NullString` for nullable fields, so I don't really to want to add complexity and slow other normal queries to support this edge and invalid case ;(

But the good news is, you could use `Omit` to omit this field when creating if it is `NULL` to make it works, like:

```go
DB.Omit("Value").Create(&invitation)
```

Thank you

**Comment by flusflas** [comment]
You're right, I wanted to avoid using pointers but I guess it is the way to go. Thanks!
