### ISSUE TITLE
batch insert touch database max parameters

### ISSUE THREAD

**Issue by zzjin** [go-gorm/gorm#3393]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/114

## Description

when use batch insert, and insert big amout with datas,mysql will throw `Prepared statement contains too many placeholders` wondering it's caller's duty to makesure slice not so much.
but it's hard to determin witch real lines to exec due to different struct have fidderent struct colums.
So maybe can faster throw error without real exec it to improve perf.

使用批量插入的时候如果一次性插入的行太多,mysql会报错.比较疑惑是底层还是应该调用方来确认数组不要太大.
但是对于上层来说不同表字段不一样,一次能执行的插入行数量也不一样.

https://github.com/go-gorm/gorm/issues/255#issuecomment-507023750

**Comment by jinzhu** [comment]
I would suggest leave it to the caller as it behaves differently for different databases... but in general, should never pass a too big slice to GORM to create... as GORM will do some additionally work that might cost lots of time you don't really want... like hooks, callbacks...
