### ISSUE TITLE
Preload seems not to work with views

### ISSUE THREAD

**Issue by pioz** [go-gorm/gorm#3394]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/115

## Description

When I query in a view and preload an association that is a view Gorm preload correctly the association only for the one row, all the other rows are the association array empty.

I don't know if this is a real bug or I do something wrong. Need help! :D

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/92228023-c9d95980-eed9-11ea-8c00-e1cc8b978e23.png)

by default, it is using the `ID` field as reference, but this is not true for your cases
