### ISSUE TITLE
Gorm v2 Callbacks

### ISSUE THREAD

**Issue by knusbaum** [go-gorm/gorm#3397]
## Your Question

The `callbacks` type returned by `(db *DB) Callback() *callbacks` (see [here](https://pkg.go.dev/gorm.io/gorm?tab=doc#DB.Callback)) is not exported, meaning none of its methods are documented. In order to figure out how to use it, you have to dig through a bit of code.

Is this intentional? I would expect `callbacks` to be exported from the `gorm` package as `Callbacks`.

**Comment by jinzhu** [comment]
Yes, this is `intentional`, the API is not necessary for most users but only those people who want to hack GORM, and they have to read some GORM code to do the job, also refer: https://gorm.io/docs/write_plugins.html if you want to hack GORM.
