### ISSUE TITLE
panic in second .Create() after setting a key with db.set()

### ISSUE THREAD

**Issue by rgci** [go-gorm/gorm#3398]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/117

## Description

When you do these things in following order:

1. Set key via db.Set()
2. Create a toy
3. Try to create a company

It panics while trying to do number 3. One workaround seems to be, to set the session attribute "WithConditions" to true in step 2. I am unsure though why this is the case.

**Comment by jinzhu** [comment]
https://gorm.io/docs/v2_release_note.html#Method-Chain-Safety-Goroutine-Safety
