### ISSUE TITLE
Why was tx.RollbackUnlessCommitted() removed?

### ISSUE THREAD

**Issue by Robbie-Perry** [go-gorm/gorm#3401]
## Your Question

In GORM 1, tx.RollbackUnlessCommitted() existed to only rollback a transaction if it wasn't already committed. This was useful, to throw into a defer statement.

## The document you expected this should be explained

Couldn't find anything about it in the [GORM 2 changelog](https://gorm.io/docs/v2_release_note.html#Breaking-Changes)

## Expected answer

Is there an equivalent, or is this yet to be added?

**Comment by jinzhu** [comment]
Just added it to the breaking changes.

https://gorm.io/docs/v2_release_note.html#Transactions

**Comment by Robbie-Perry** [comment]
Ok, should be simple enough for me to re-implement it on my end
