### ISSUE TITLE
Automigrate postgres goes in error with default tag

### ISSUE THREAD

**Issue by Valkyrie00** [go-gorm/gorm#3405]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/118

## Description

Automigrate (only with Postgres database) goes in error with default tag.
This problem appears when automigrate running after the table and column already exists.
This problem appear in v1.20.0 branch (last tag for my go modules), i think that problem are already fixed in master branch.
If this is the case, please release a new tag.

**Comment by Valkyrie00** [comment]
As a temporary solution i have forced my go.mod to using master branch

```
require (
	....
	gorm.io/driver/postgres v1.0.0
	gorm.io/gorm v1.20.1-0.20200904110951-d8ddccf1478b
)
```

**Comment by jinzhu** [comment]
Hi @Valkyrie00 

Yes, this should been fixed, we will release a new tag recently
