### ISSUE TITLE
我找不到我错在哪里了，同样的语句，一边可以出结果，一边是错误的。

### ISSUE THREAD

**Issue by weidongbcn** [go-gorm/gorm#3407]
## Your Questio n

![截图_2020-09-06_08-49-25](https://user-images.githubusercontent.com/23153588/92320065-e9c66580-f01e-11ea-97c1-7fb89a2ffac6.png)
![截图_2020-09-06_08-49-59](https://user-images.githubusercontent.com/23153588/92320071-f2b73700-f01e-11ea-85fc-a1f6776c90a9.png)
![截图_2020-09-06_08-50-24](https://user-images.githubusercontent.com/23153588/92320073-006cbc80-f01f-11ea-9a32-f4ff7731eceb.png)
![截图_2020-09-06_08-50-50](https://user-images.githubusercontent.com/23153588/92320076-04004380-f01f-11ea-82a8-c021f934dce8.png)
![截图_2020-09-06_08-51-34](https://user-images.githubusercontent.com/23153588/92320105-30b45b00-f01f-11ea-8fc6-fa2c88eb1d81.png)
这上面的函数没有正常工作。运行结果如下：
![截图_2020-09-06_08-48-42](https://user-images.githubusercontent.com/23153588/92320115-4cb7fc80-f01f-11ea-84c3-1bfd81ac3103.png)

![截图_2020-09-06_08-52-33](https://user-images.githubusercontent.com/23153588/92320122-63f6ea00-f01f-11ea-9473-ba458fa23414.png)
这张图的函数可以正常运行. 结果如下:
![截图_2020-09-06_08-53-00](https://user-images.githubusercontent.com/23153588/92320132-812bb880-f01f-11ea-9726-15f9a8e9c124.png)

我已经花了2天时间爬网了,得不到答案.不得已在发到这里. 请大佬们帮忙,不胜感激.

**Comment by jinzhu** [comment]
Hi,

We only accept V2 issues report right now, but if you are still falling into this issue, can you create a simple reproducible script for it?
