### ISSUE TITLE
Can't create HAS MANY relationship when foreign key AUTO INCREMENTS in parent table (MySQL)

### ISSUE THREAD

**Issue by AdavizeTheFirst** [go-gorm/gorm#3409]
## Description

AutoMigrate throws this error when I use a foreign key that auto increments in it's parent table for HAS MANY relationship with MySQL:
**Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key**

here's my code: 
```
type Person struct {
    ID      uint     `gorm:"primaryKey;type:INT UNSIGNED AUTO_INCREMENT;"`
    Clothes *[]Cloth `gorm:"foreignKey:OwnerID;"`
}

type Cloth struct {
    ClothID uint `gorm:"primaryKey;type:INT UNSIGNED AUTO_INCREMENT;"`
    OwnerID uint `gorm:"index;type:INT UNSIGNED;autoIncrement:false;"` //foreign key
    Color   string
}
```
Then: 
```
db.AutoMigrate(&Person{})
db.AutoMigrate(&Cloth{})
```

AutoMigrate for Cloth struct fails, **OwnerID** as the foreign key shouldn't auto increment. 'autoIncrement:false' doesn't work.
It doesn't give any error with SQLite, but the column will have autoincrement. 

Sorry I could't make it reproducible with gorm playgroud, but here's my go file: https://play.golang.org/p/QLAoY0FzJ6T

**Comment by jinzhu** [comment]
> I could't make it reproducible with gorm playgroud

If can't reproduce this with GORM playground, this might be fixed in latest master/driver

**Comment by AdavizeTheFirst** [comment]
Just added the link to reproduction

**Comment by jinzhu** [comment]
Hi,

Suggest to use the `general` data type and `autoIncrement` tag.

 https://gorm.io/docs/models.html#Fields-Tags

**Comment by drjele** [comment]
hello.

I also have the same problem:

```go
type Email struct {
    /** generic columns */
    Id      int       `gorm:"primaryKey;type:int unsigned auto_increment;not null"`
    Created time.Time `gorm:"type:datetime;not null;default:current_timestamp"`

    /** email columns */
    From    string         `gorm:"type:varchar(128);not null"`
    To      pq.StringArray `gorm:"type:json;not null"`
    Cc      pq.StringArray `gorm:"type:json"`
    Bcc     pq.StringArray `gorm:"type:json"`
    Subject string         `gorm:"type:text;not null"`
    Body    string         `gorm:"type:text;not null"`

    Attachments []*EmailAttachment `gorm:"foreignKey:EmailId"`
}

type EmailAttachment struct {
    /** generic columns */
    Id      int       `gorm:"primaryKey;type:int unsigned auto_increment;not null"`
    Created time.Time `gorm:"type:datetime;not null;default:current_timestamp"`

    EmailId int    `gorm:"type:general;autoIncrement:false"`
    Name    string `gorm:"type:varchar(128);not null"`
    Path    string `gorm:"type:varchar(128);not null"`
}
```

**Comment by exuan** [comment]
> hello.
> 
> I also have the same problem:
> 
> ```go
> type Email struct {
>     /** generic columns */
>     Id      int       `gorm:"primaryKey;type:int unsigned auto_increment;not null"`
>     Created time.Time `gorm:"type:datetime;not null;default:current_timestamp"`
> 
>     /** email columns */
>     From    string         `gorm:"type:varchar(128);not null"`
>     To      pq.StringArray `gorm:"type:json;not null"`
>     Cc      pq.StringArray `gorm:"type:json"`
>     Bcc     pq.StringArray `gorm:"type:json"`
>     Subject string         `gorm:"type:text;not null"`
>     Body    string         `gorm:"type:text;not null"`
> 
>     Attachments []*EmailAttachment `gorm:"foreignKey:EmailId"`
> }
> 
> type EmailAttachment struct {
>     /** generic columns */
>     Id      int       `gorm:"primaryKey;type:int unsigned auto_increment;not null"`
>     Created time.Time `gorm:"type:datetime;not null;default:current_timestamp"`
> 
>     EmailId int    `gorm:"type:general;autoIncrement:false"`
>     Name    string `gorm:"type:varchar(128);not null"`
>     Path    string `gorm:"type:varchar(128);not null"`
> }
> ```

delete Email struct id "auto_increment", use` autoincrement:true;`

gorm Migrator FullDataTypeOf  will be use  Email struct id `int unsigned auto_increment`, This is what caused the problem
