### ISSUE TITLE
AutoMigrate panic

### ISSUE THREAD

**Issue by HelloHaiGG** [go-gorm/gorm#3411]
## GORM Playground Link

I used automigrate to create tables , the models is a slice and item type is interface , panic

For Example:

	for _, model := range models {
		err := dbIns.AutoMigrate(model)
		fmt.Println(err)
	}

**Comment by HelloHaiGG** [comment]
help me,please！

**Comment by ap-in-git** [comment]
for _, model := range models {
	err := dbIns.AutoMigrate(&model)
	fmt.Println(err)
}

This may help

**Comment by HelloHaiGG** [comment]
> for _, model := range models {
> err := dbIns.AutoMigrate(&model)
> fmt.Println(err)
> }
> 
> This may help

model is pointer

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/blob/05794298bd3d87dc8e98de8cde451b19093e2a4a/tests/tests_test.go#L90

**Comment by HelloHaiGG** [comment]
> https://github.com/go-gorm/gorm/blob/05794298bd3d87dc8e98de8cde451b19093e2a4a/tests/tests_test.go#L90

I test
If my models number is greater than 50, it stops executing, there is no panic, just stop
