### ISSUE TITLE
Creating foreign key with migrator

### ISSUE THREAD

**Issue by ap-in-git** [go-gorm/gorm#3413]
Is there options to create a foreign key using automigrate?

**Comment by jinzhu** [comment]
https://gorm.io/docs/v2_release_note.html#Migrator

**Comment by stefanoschrs** [comment]
@jinzhu the link doesn't say much. What if you don't want to use the automatic foreign key creation (using an embedded struct) and you want to add one manually like in V1?

```
// gorm v1
db.AutoMigrate(&TableA{}, &TableB{})
db.Model(TableAB{}).
  AddForeignKey("a_id", "table_a(id)", "CASCADE", "CASCADE").
  AddForeignKey("b_id", "table_b(id)", "CASCADE", "CASCADE")
```

**Comment by zaharidichev** [comment]
@jinzhu Are you going to answer the question or at least update the docs to provide a bit more specificity on the matter. Also can this issue be reopened as it does not look like it has been fully resolved?

**Comment by jinzhu** [comment]
This is already supported in V2.

**Comment by zaharidichev** [comment]
> This is already supported in V2.

@jinzhu What does "this" refer to in this sentence? Can you do `AddForeignKey` in v2? I do not think so. Are there some docs or examples that provide a bit more extensive info on how to setup FKs in V2?

**Comment by jinzhu** [comment]
https://gorm.io/docs/migration.html

**Comment by zaharidichev** [comment]
Hm.. I guess this is how a productive discussion looks like around here ;)
