### ISSUE TITLE
How to create a foreign key to constraint multiple columns

### ISSUE THREAD

**Issue by dirname** [go-gorm/gorm#3414]
## Your Question

How to create a foreign key to constraint multiple columns ? As SQL:

`CONSTRAINT "college" FOREIGN KEY ("collegeId", "collegeName") REFERENCES "college"."college" ("id", "name") ON DELETE RESTRICT ON UPDATE RESTRICT`

**Comment by jinzhu** [comment]
define multiple foreign keys with tag `foreignKey`, `references`

**Comment by dirname** [comment]
I have try

`gorm:"ForeignKey:(collegeId, collegeName)"`

But this is not a correct statement

**Comment by jinzhu** [comment]
https://gorm.io/docs/many_to_many.html#Composite-Foreign-Keys

**Comment by dirname** [comment]
> https://gorm.io/docs/many_to_many.html#Composite-Foreign-Keys

Thanks !

**Comment by isaacwein** [comment]
2 foreignKey like and one references like this `ForeignKey:id,locale;References:idmake a panic `panic: runtime error: index out of range [1] with length 1`
