### ISSUE TITLE
bug? in clause in mysql

### ISSUE THREAD

**Issue by youin729** [go-gorm/gorm#3415]
In GORM Docs,

https://gorm.io/docs/query.html

> // IN
db.Where("name IN ?", []string{"jinzhu", "jinzhu 2"}).Find(&users)
// SELECT * FROM users WHERE name IN ('jinzhu','jinzhu 2');

But practical query is
`SELECT * FROM users WHERE (name IN 'jinzhu','jinzhu 2');`

Its mysql Error
>Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL s
erver version for the right syntax to use near '?,?)

So alternative way of writing
`db.Where("name IN ( ? )", []string{"jinzhu", "jinzhu 2"}).Find(&users)`
`SELECT * FROM users WHERE name IN ( 'jinzhu','jinzhu 2' );`

**Comment by jinzhu** [comment]
`db.Where("name IN ?", []string{"jinzhu", "jinzhu 2"}).Find(&users)`

this is only supported in GORM v2
