### ISSUE TITLE
sqlite file cannot be closed

### ISSUE THREAD

**Issue by johnpoint** [go-gorm/gorm#3416]
## Your Question

sqlite file cannot be closed

```
sqlDB, _ = db.DB()
fmt.Println(sqlDB.Ping())
fmt.Println(sqlDB.Close())
fmt.Println(sqlDB.Ping())
```
output:
```
<nil>
<nil>
sql: database is closed
```
but when I use the `lsof -p` command, I can still see that many database files are opened

**Comment by jinzhu** [comment]
I don't think I can help on anything... if there is a bug maybe open an issue on the sqlite driver issues.
