### ISSUE TITLE
foreign key can not be a string?

### ISSUE THREAD

**Issue by garysdevil** [go-gorm/gorm#3418]
## The document you expected this should be explained

It run success when the type of UserRefer is uinit.
it run fail  when the type of UserRefer is string.
```code
	type CreditCard struct {
		gorm.Model
		Number    string
		UserRefer string
	}
	type User struct {
		gorm.Model
		CreditCards []CreditCard `gorm:"foreignKey:UserRefer"`
	}
	model.DB.Debug().AutoMigrate(&User{})
	model.DB.Debug().AutoMigrate(&CreditCard{})
```
![image](https://user-images.githubusercontent.com/41293784/92396856-51cc9700-f158-11ea-97be-acd7d67106ee.png)

## Expected answer

It can run success when the type of UserRefer is a string.

**Comment by jinzhu** [comment]
It can be a string, but need to be same type with the primary key or it will failed to create the database foreign keys.

But you can skip the database foreign key creation, check out https://gorm.io/docs/migration.html#Auto-Migration
