### ISSUE TITLE
v1 group and  v2 group

### ISSUE THREAD

**Issue by HelloHaiGG** [go-gorm/gorm#3422]
## GORM Playground Link

I use group:

        var roles []*R
	tx := dd.Table("roles").Limit(1000)
	tx.Group("uuid").Scan(&roles)  //sql-1
	tx.Group("uuid_2").Scan(&roles) //sql-2

v1:

sql-1:select * from roles group by uuid limit 1000 
sql-2:select * from roles group by uuid_2 limit 1000

v2:
sql-1: select * from roles group by uuid limit 1000
sql-2:select * from roles group by uuid,uuid_2 limit 1000

why ? 

I want get the same result as V1! Please!

**Comment by jinzhu** [comment]
https://gorm.io/docs/v2_release_note.html#Method-Chain-Safety-Goroutine-Safety
