### ISSUE TITLE
Improper handling of empty ULIDs

### ISSUE THREAD

**Issue by tobiassjosten** [go-gorm/gorm#3427]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/121

## Description

I use [ULID for my IDs](https://github.com/oklog/ulid) and it doesn't seem to play nicely with the latest version of Gorm. The library implements a Valuer, which seems to be working fine (returning null on empty value), but still it won't work for me.

The problem is that Gorm sees an empty ULID and uses its value for INSERT, causing an error with the foreign key constraint for that column.

I'm a bit at loss here, whether it's a problem with Gorm, the ULID library, or simply some interfacing of the two. Maybe you could help point me in a direction for how to fix it?

**Comment by jinzhu** [comment]
`ULID`'s `Value` methods always returns `true`, so we thought it is a valid value, and will inserting with it, if you enabled the database foreign key, it won't pass the constraint check.

you could disable the database foreign key or create like `	DB.Omit("TwoID").Create(&one)`

The `First` doesn't won't work, please check out https://gorm.io/docs/query.html#Retrieving-with-primary-key inline conditions only works with numbers

**Comment by tobiassjosten** [comment]
I guess then the problem is with the `ULID` library. 👍 Thank you so much for taking the time, @jinzhu!
