### ISSUE TITLE
Error in gorm version update

### ISSUE THREAD

**Issue by numa999** [go-gorm/gorm#3428]
## Your Question

```
type Question struct {
	gorm.Model
	FormType   int
	Options    []QuestionOption
	Answers    []Answer
}
type QuestionOption struct {
	gorm.Model
	QuestionID uint
	Name       sql.NullString
	Text       string
}
type FeedbackAnswer struct {
	gorm.Model
	FeedbackID         uint
	FeedbackQuestionID uint
	Value              interface{}
}

func Test() {
    // Connection part omitted

    id := 10
    q := Question{}
    err := db.First(Question{}, id).Error

    // Subsequent processing is omitted
}
```
```
[error] unsupported data type: 0xc0002382e0
```

## The document you expected this should be explained
When I tried to update gorm to v2, the error below happened.
In detail, with all models, errors happened everywhere we use the find function.
No error happend with v1.
Please let me know if you know some possible causes.

There are some build errors in handling the errors, but they are all removed.

## Expected answer
How to update the version of gorm with only the original changes.

**Comment by numa999** [comment]
@jinzhu 
I'm Japanese so I'm not good at English. I am writing a sentence using google translation.
I'm sorry if it's hard to convey.

**Comment by jinzhu** [comment]
```go
 q := Question{}
 err := db.First(&q, id).Error
```
please follow examples here. https://gorm.io/docs/query.html

**Comment by numa999** [comment]
There was a mistake in the sample code.
Actually, I was able to solve it, and there was a place where I did not notice it, and there was a place where it was defined with `interface{}`, so an error occurred.
Thank you for confirmation.
