### ISSUE TITLE
Map[string]interface Update in CamelCase

### ISSUE THREAD

**Issue by andreadragotta** [go-gorm/gorm#3431]
Hi, 

I've a Gorm Model and i want to use map[string]interface key in CamelCase instead of snake_case in the Updates. 
Is possible?

**Comment by andreadragotta** [comment]
no stale

**Comment by jinzhu** [comment]
If you are using GORM v2, we will use map's key as column name, unless pass a struct to `Model`, then GORM will convert map's key following the struct's definition

**Comment by puzhengwu** [comment]
mybatis.configuration.map-underscore-to-camel-case=true

There's a configuration in MyBatics that you can look at
