### ISSUE TITLE
Support returning computed/generated columns

### ISSUE THREAD

**Issue by jhartman86** [go-gorm/gorm#3434]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/124

## Description

With POSTGRES supporting computed/generated columns, it'd be great to have those columns come back in the RETURNING clause, instead of needing to reload the values after a mutation. In schema/schema.go around line 182, it looks like FieldsWithDefaultDBValue property on the schema is what's used to determine what should be generated in the RETURNING clause. If the schema also kept track of computed columns, it looks like a (fairly) easy addition to add the computed columns that should be returned.

**Comment by jinzhu** [comment]
Yes, just add a `default` tag defined like a function, then GORM will load it from the returning for postgres, e.g:

```go
	type exampleWithComputedCols struct {
		gorm.Model
		FirstName string `gorm:"type:varchar;"`
		LastName  string `gorm:"type:varchar;"`
		FullName  string `gorm:"->;type:varchar GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED;default:dummy()"`
	}
```

**Comment by jhartman86** [comment]
@jinzhu thanks for the quick attention to this! However, the `default:dummy()` expression is not allowed by PG, resulting in this error (note: some details removed for brevity):

```
ERROR: both default and generation expression specified for column "series_range_calcd" of table "schedule_slot" (SQLSTATE 42601)
[0.667ms] [rows:0] CREATE	TABLE "schedule_slot"
(
 "id" uuid DEFAULT gen_random_uuid(),
  "start_time" TIMESTAMP WITHOUT time ZONE NOT NULL,
  "series_range_calcd" tsrange GENERATED ALWAYS AS (tsrange(start_time, (start_time + 'P1Y'::interval, '[]')) STORED DEFAULT dummy()
)
```

Relevant struct:
```
Slot struct {
	ID                  typed.UUID `gorm:"primary_key;type:uuid;"`
	ScheduleID  typed.UUID  `gorm:"type:uuid;not null;"`
	StartTime     typed.Time   `gorm:"type:timestamp without time zone;not null;"`
	SeriesRangeCalcd  typed.TSRange  `gorm:"->;type:tsrange GENERATED ALWAYS AS (tsrange(start_time, 'P1Y'::interval, '[]')) STORED;default:dummy()"`
}
```

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm.io/commit/6b655ca9e3b269d921824e0e83b8f5fd6a1c52dc

**Comment by jhartman86** [comment]
@jinzhu thanks for updating the docs. Guessing this does work on other databases potentially?, but with Postgres it still doesn't seem to work.

Relevant SQL error: `ERROR: syntax error at or near ")" (SQLSTATE 42601)`

Relevant struct:
```
Slot struct {
	ID                  typed.UUID `gorm:"primary_key;type:uuid;"`
	ScheduleID  typed.UUID  `gorm:"type:uuid;not null;"`
	StartTime     typed.Time   `gorm:"type:timestamp without time zone;not null;"`
	SeriesRangeCalcd  typed.TSRange  `gorm:"->;type:tsrange GENERATED ALWAYS AS (tsrange(start_time, 'P1Y'::interval, '[]')) STORED;default:(-)"`
}
```

Relevant "table create" syntax generated by GORM:
```
CREATE TABLE "schedule_slotzzzz" (
	"id" uuid DEFAULT gen_random_uuid(), 
-- 	"schedule_id" uuid NOT NULL,
	"start_time" timestamp without time zone NOT NULL,
	"series_range_calcd" tsrange GENERATED ALWAYS AS (tsrange(start_time, start_time+'P1Y'::interval, '[]')) STORED DEFAULT (-),
	PRIMARY KEY ("id")
)
```

Is there potential to re-open this issue and have GORM more formally address GENERATED columns?

**Comment by jhartman86** [comment]
@jinzhu tried your suggestion with the latest version of GORM and it seems to be working. Thanks for the help with this, and next version of GORM is shaping up to be awesome!
