### ISSUE TITLE
when query with SubQuery fail

### ISSUE THREAD

**Issue by zzjin** [go-gorm/gorm#3436]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/125

## Description

when use subQuery sql build fail.

**Comment by jinzhu** [comment]
Sorry, fixed the document, it should be used like

```go
DB.Model(User{}).Where("company_id > (?)", subQuery).Find(&testData).Error;
```
https://github.com/go-gorm/gorm.io/commit/ab9c4bc1191412f206a8139d394c7fe05173ae25
