### ISSUE TITLE
when query with SubQuery logger output sql wrong

### ISSUE THREAD

**Issue by zzjin** [go-gorm/gorm#3437]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/126/checks

## Description

the first output log is wrong param: 
want: `SELECT `id` FROM `companies` WHERE id > 1 AND name <> "asdf"`
actual: `SELECT `id` FROM `companies` WHERE id > 18 AND name <> 1`

**Comment by jinzhu** [comment]
The final SQL looks correct, but the above one should not display in log

 SELECT * FROM `users` WHERE age>18 AND company_id > SELECT `id` FROM `companies` WHERE id > 1 AND name <> "asdf" AND `users`.`deleted_at` IS NULL

**Comment by jinzhu** [comment]
Fixed the output, thank you for your report.
