### ISSUE TITLE
datatypes.json can't create in postgresql

### ISSUE THREAD

**Issue by blakejia** [go-gorm/gorm#3438]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/127

## Description

postgres version : 12.4

``` golang
		type UserWithJSON struct {
			gorm.Model
			Name       string
			Attributes datatypes.JSON
		}
		tx.AutoMigrate(&UserWithJSON{})

		err = tx.Create(&UserWithJSON{
			Name:       "json-1",
			Attributes: datatypes.JSON([]byte(`{"name": "jinzhu", "age": 18, "tags": ["tag1", "tag2"], "orgs": {"orga": "orga"}}`)),
		}).Error

```

![image](https://user-images.githubusercontent.com/9416560/92580449-f4078e80-f2c0-11ea-9e4e-4c909993690e.png)

**Comment by jinzhu** [comment]
https://github.com/go-gorm/datatypes/blob/master/json_test.go

**Comment by blakejia** [comment]
测试出来是 postgres config 里面的 PreferSimpleProtocol 属性导致 datatypes.json 不能正常写入

https://github.com/go-gorm/playground/pull/132

``` golang
		db, err = gorm.Open(postgres.New(postgres.Config{
			DSN: dbDSN,
			PreferSimpleProtocol: true,
		}), &gorm.Config{})

```
