### ISSUE TITLE
Replace Callback、 Update Field Value Failed

### ISSUE THREAD

**Issue by tk-xiong** [go-gorm/gorm#3441]
## Your Question

I cannot update the field value of the currently modified row in a custom callback.
我没法在自定义回调中更新当前修改行的字段值。

## The document you expected this should be explained

`func updateTimeStampForAfterUpdateCallback(db *gorm.DB) {
	if db.Statement.Schema != nil {
		{
			for _, field := range db.Statement.Schema.Fields {
				fieldValue, isZero := field.ValueOf(db.Statement.ReflectValue)
				fmt.Println(
					"After Update: ",
					"fieldName =", field.Name,
					"; fieldValue =", fieldValue,
					"; isZero =", isZero,
				)
			}
			fmt.Println()
		}

		field := db.Statement.Schema.LookUpField("ModifiedOn")
		if field != nil {
			val, isZero := field.ValueOf(db.Statement.ReflectValue)
			if _, ok := val.(int); ok {
				switch db.Statement.ReflectValue.Kind() {
				case reflect.Slice, reflect.Array:
					for i := 0; i < db.Statement.ReflectValue.Len(); i++ {
						var nowTime = time.Now().Unix()
						field.Set(db.Statement.ReflectValue, nowTime)
					}
				case reflect.Struct:
					fmt.Println(
						"After Update: ",
						"fieldName =", field.Name,
						"; fieldValue =", val,
						"; isZero =", isZero,
					)

					var nowTime = time.Now().Unix()
					field.Set(db.Statement.ReflectValue, nowTime)
				}
			}

			fieldValue, isZero := field.ValueOf(db.Statement.ReflectValue)
			fmt.Println(
				"After Update: ",
				"fieldName =", field.Name,
				"; fieldValue =", fieldValue,
				"; isZero =", isZero,
			)
		}

		field2 := db.Statement.Schema.LookUpField("ModifiedOn")
		val2, isZero := field2.ValueOf(db.Statement.ReflectValue)
		fmt.Println(
			"After Update: ",
			"Field2 fieldName =", field2.Name,
			"; fieldValue =", val2,
			"; isZero =", isZero,
		)
	}
	fmt.Println(db.Row())
}
`

LogInfo：

`[xiong@AMDServer ginBlog]$ go run main.go 
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /api/auth                 --> ginBlog/routers/api.GetAuth (3 handlers)
[GIN-debug] GET    /swagger/*any             --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (3 handlers)
[GIN-debug] GET    /api/v1/tags              --> ginBlog/routers/api/v1.GetTags (4 handlers)
[GIN-debug] POST   /api/v1/tags              --> ginBlog/routers/api/v1.AddTag (4 handlers)
[GIN-debug] PUT    /api/v1/tags/:id          --> ginBlog/routers/api/v1.EditTag (4 handlers)
[GIN-debug] DELETE /api/v1/tags/:id          --> ginBlog/routers/api/v1.DeleteTag (4 handlers)
[GIN-debug] GET    /api/v1/articles          --> ginBlog/routers/api/v1.GetArticles (4 handlers)
[GIN-debug] GET    /api/v1/articles/:id      --> ginBlog/routers/api/v1.GetArticle (4 handlers)
[GIN-debug] POST   /api/v1/articles          --> ginBlog/routers/api/v1.AddArticle (4 handlers)
[GIN-debug] PUT    /api/v1/articles/:id      --> ginBlog/routers/api/v1.EditArticle (4 handlers)
[GIN-debug] DELETE /api/v1/articles/:id      --> ginBlog/routers/api/v1.DeleteArticle (4 handlers)
After Update:  fieldName = ID ; fieldValue = 15 ; isZero = false
After Update:  fieldName = CreatedOn ; fieldValue = 0 ; isZero = true
After Update:  fieldName = ModifiedOn ; fieldValue = 0 ; isZero = true
After Update:  fieldName = Name ; fieldValue = edit11 ; isZero = false
After Update:  fieldName = CreatedBy ; fieldValue =  ; isZero = true
After Update:  fieldName = ModifiedBy ; fieldValue = root ; isZero = false
After Update:  fieldName = State ; fieldValue = 0 ; isZero = true

After Update:  fieldName = ModifiedOn ; fieldValue = 0 ; isZero = true
After Update:  fieldName = ModifiedOn ; fieldValue = 1599705971 ; isZero = false
After Update:  Field2 fieldName = ModifiedOn ; fieldValue = 1599705971 ; isZero = false
[GIN] 2020/09/10 - 10:46:11 | 200 |    3.203635ms |   192.168.1.102 | PUT      "/api/v1/tags/15?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJwYXNzd29yZCI6InJvb3QiLCJleHAiOjE1OTk3MTY1MTAsImlzcyI6ImdpbkJsb2cifQ.FuDP_VT1pGxEzyA7JpmZOa0xOA7USVNWgjH4o-AFLYE&name=edit11&modified_by=root"
`

> mysql> SELECT * FROM blog_tag
    -> ;
+----+---------+------------+------------+-------------+-------------+-------+
| id | name    | created_on | created_by | modified_on | modified_by | state |
+----+---------+------------+------------+-------------+-------------+-------+
|  7 | 3       | 1599022723 | root       |           0 |             |     1 |
|  8 | create1 | 1599026312 | root       |           0 |             |     1 |
|  9 | 4       | 1599671111 | root       |           0 |             |     1 |
| 10 | 5       | 1599671217 | root       |           0 |             |     1 |
| 11 | 6       | 1599671277 | root       |           0 |             |     1 |
| 12 | 8       |          0 | root       |           0 |             |     1 |
| 13 | 9       |          0 | root       |           0 |             |     1 |
| 14 | 10      |          0 | root       |           0 |             |     1 |
| 15 | edit11  |          0 | root       |           0 | root        |     1 |
| 16 | 12      |          0 | root       |           0 |             |     1 |
| 17 | 13      |          0 | root       |           0 |             |     1 |
| 18 | 14      |          0 | root       |           0 |             |     1 |
| 19 | 15      |          0 | root       |           0 |             |     1 |
| 20 | 16      |          0 | root       |           0 |             |     1 |
| 21 | 17      |          0 | root       |           0 |             |     1 |
| 22 | 18      |          0 | root       |           0 |             |     1 |
| 23 | 19      |          0 | root       |           0 |             |     1 |
| 24 | 20      |          0 | root       |           0 |             |     1 |
| 25 | 21      |          0 | root       |           0 |             |     1 |
| 26 | 22      |          0 | root       |           0 |             |     1 |
| 27 | 23      |          0 | root       |           0 |             |     1 |
| 28 | 24      |          0 | root       |           0 |             |     1 |
| 29 | 25      |          0 | root       |           0 |             |     1 |
+----+---------+------------+------------+-------------+-------------+-------+
23 rows in set (0.00 sec)

| 15 | edit11 | 0 | root | 0 | root | 1 |
fields modified_on and created_on is zero

**Comment by tk-xiong** [comment]
我把函数代码复制在这里：
I had copy code func updateTimeStampForAfterUpdateCallback To：

https://paste.ubuntu.com/p/gkZvPPkmks/

**Comment by jinzhu** [comment]
https://gorm.io/docs/update.html#Change-Updating-Values

**Comment by tk-xiong** [comment]
thank you so much！！！
十分感谢...

**Comment by tk-xiong** [comment]
不行，不太行。
No, it won't work

我应该修改函数如下：
I modify the function as follows:

```
func updateTimeStampForAfterUpdateCallback(db *gorm.DB) {
    var nowTime = time.Now().Unix()
    db.Statement.SetColumn("ModifiedOn", nowTime)
}
```


但是SetColumn实现如下：
But the SetColumn function implementation as follows:

```
 func (stmt *Statement) SetColumn(name string, value interface{}) {
	if v, ok := stmt.Dest.(map[string]interface{}); ok {
		v[name] = value
	} else if stmt.Schema != nil {
		if field := stmt.Schema.LookUpField(name); field != nil {
			switch stmt.ReflectValue.Kind() {
			case reflect.Slice, reflect.Array:
				field.Set(stmt.ReflectValue.Index(stmt.CurDestIndex), value)
			case reflect.Struct:
				field.Set(stmt.ReflectValue, value)
			}
		} else {
			stmt.AddError(ErrInvalidField)
		}
	} else {
		stmt.AddError(ErrInvalidField)
	}
}

```


这样来看之前的代码也是没问题的，我觉得可能是GORM出问题了。
So the previous code is also fine, I think maybe GORM is the problem.

**Comment by jinzhu** [comment]
`SetColumn` works in hooks methods, if you are defining a callbacks, follow the method to implement it.

**Comment by tk-xiong** [comment]
我现在的主要问题是，我调用了 SetColumn 函数，或者调用 field.Set 函数之后，数据值并没有被写入到Mysql数据库里。

The problem I now face is that after I call the SetColumn function, or the field.set function, the value is not written to the Mysql database.

**Comment by jinzhu** [comment]
It has to be call before changes, it should be covered by tests, if there are any issue, please create PR on playground.

**Comment by tk-xiong** [comment]
我之前实现的方法是这样：
Here's what I did before:
```
db.Callback().Create().Replace("gorm:after_create", updateTimeStampForAfterCreateCallback)
db.Callback().Update().Replace("gorm:after_update", updateTimeStampForAfterUpdateCallback)
```

它应该修改为这样：
That should be changed to this:
```
db.Callback().Create().Replace("gorm:before_create", updateTimeStampForBeforeCreateCallback)
db.Callback().Update().Replace("gorm:before_update", updateTimeStampForBeforeUpdateCallback)
```

OK... 搞定了！
OK... Done!

thanks！
