### ISSUE TITLE
update value with wrong field 

### ISSUE THREAD

**Issue by chenqinghe** [go-gorm/gorm#3442]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/133

## Description
As the test cases in the playground described, first we created a rule and everything is ok. But when update `interval` field with Rule.IntervalStr, something weird happend. the value was not `10s`, but `10000000000` (maybe nanoseconds of 10s). Here are some problems:
1. behaviors of create and update are not the same.
2. which has higher priority used as update field name? struct model field name or specified by tag?

**Comment by jinzhu** [comment]
If you are using gorm v2, the last field will be ignored 

`Interval    time.Duration `gorm:"-"``

**Comment by chenqinghe** [comment]
@jinzhu yes, here is the problem, the field is expected to be ignored, `Rule.IntervalStr` should be used. But the fact is, the `Rule.Interval` field may be used to update `interval` column, because the value of `Rule.IntervalStr` is "10s", but after execute update statement, the value becomes "10000000000".

The situation only produced when use UPDATE statement, CREATE works well.
