### ISSUE TITLE
documentation part for handle empty object when association column is NULL

### ISSUE THREAD

**Issue by Acr0most** [go-gorm/gorm#3445]
## Your Question

Hey there,

i got the problem that i created a model struct like that:

```
type Example struct {
     // id, created, ...
    Element Element
    ElementID int
    Value string
}

type Element struct {
     // id, created, ...
    Value string
}
```
Therefore i have the two tables "examples" and "elements" with the association from `example.element_id` to `element.id`.

Now when i fetch the data and the element_id is not null it works like a charme.
But when i have a NULL Relation it won't find an element object and returns an **empty Element with id 0 and default values**.

## Solution

After hours i found the solution: My "Element"-property needs to be a pointer.

```
type Example struct {
     // id, created, ...
    Element *Element // old: Element Element
    ElementID int
    Value string
}
```

## Expected answer
It was hard to find out - maybe it could be added to your documentation?
Otherwise this ticket could help others with the same problem.

best regards,
Acr0most

**Comment by jinzhu** [comment]
this is the zero value concept for golang, not related to GORM, so maybe not necessary to document it.
