### ISSUE TITLE
Updated at is one second slow

### ISSUE THREAD

**Issue by ap-in-git** [go-gorm/gorm#3446]
https://github.com/go-gorm/playground/pull/134

**Comment by jinzhu** [comment]
precision  https://github.com/go-gorm/mysql/blob/master/mysql.go#L243

**Comment by ap-in-git** [comment]
@jinzhu I am not sure how to disable it while selecting

**Comment by jinzhu** [comment]
check out the above link, you should not set your field's datatype to `datetime`, but something like `datetime(3)` or it will lose the precision.

**Comment by ap-in-git** [comment]
But adding that will create datetime(3) . I don't wanna millisecond precision
