### ISSUE TITLE
The new logger interface is a bit awkward to work with

### ISSUE THREAD

**Issue by zveinn** [go-gorm/gorm#3449]
## Describe the feature

It´s not so much of a feature but a request for change .. 

## Motivation

There are two places in the new logger code that make the new logger interface kind of hard to work with.

NR 1: https://github.com/go-gorm/gorm/blob/70a7bd52ca2bbf64443b7227524e4600997ea1b9/logger/logger.go#L51
Having an interface that has a method which returns the interface it self is quite restrictive when one wants to re-implement the logger. <br/>
This is what my method signature looks like:
```go
func (l GORMLoggerv2) LogMode(level logger.LogLevel) logger.Interface {
	newlogger := l
	newlogger.LogLevel = 1
	return &newlogger
}
```
it needs to have knowledge of the interface from your package, this kind of goes against the idea of being able to full fill the interface without explicit knowledge of the interface it self.<br>
Note: Why does changing the log mode require a new copy of the logger it self ? it feels like the method naming is not really telling the story of what is happening under the hood. 

NR 2: https://github.com/go-gorm/gorm/blob/70a7bd52ca2bbf64443b7227524e4600997ea1b9/logger/logger.go#L29
The log level is just an int .. why can´t it just be an int without it´s own type ? <br>
I am making my own custom gorm logger and when I want to change the log mode from another project I have to also import gorm to be able to input the LogLevel type or if I want to go around it I have to make my own wrapper function, which is not really optimal. 

## The requests
1. Could you change the log level to being just an int ? 
2. Could you change the interface´s dependency on it self ? 

## Final words
I would like to thank you for all the good work you are doing, gorm has served me well through the years :) <3

**Comment by jinzhu** [comment]
> Note: Why does changing the log mode require a new copy of the logger it self ? it feels like the method naming is not really telling the story of what is happening under the hood.

Seems the Name is not that meaning for, but haven't came out a better name ;(

The method needs to returns a copy or it would mess up the default logger when use it with several GORM instances and the `Debug` method

> Could you change the log level to being just an int ?

I don't agree this is a better implementation

**Comment by zveinn** [comment]
> I don't agree this is a better implementation
How is it a better implementation to make a new type for just an int ? I'm having a hard time seeing that. 

> The method needs to returns a copy or it would mess up the default logger when use it with several GORM instances and the Debug method
Why not make a "NewLogger" or "Clone" method then ? If you want, I can make the change my self on a fork and make a pull request ?

**Comment by jinzhu** [comment]
Hi

> How is it a better implementation to make a new type for just an int ? I'm having a hard time seeing that.

Not confusion, hard to broken when compares to use `int` as argument.

> Why not make a "NewLogger" or "Clone" method then ? If you want, I can make the change my self on a fork and make a pull request ?

Maybe you could make your own custom logger works like this? I don't really want to change the logger interface right now, and it seems works well when I develop our company's customized logger.

**Comment by zveinn** [comment]
> Not confusion, hard to broken when compares to use int as argument.

That´s not true, it´s equally easy to break the input even if you type cast the int. In both cases the user either has to guess what the input should be OR go to the documentation to find out. In both cases he will get his answers the same way.

> Maybe you could make your own custom logger works like this? I don't really want to change the logger interface right now, and it seems works well when I develop our company's customized logger.

The whole point is that outside developers should not have to re-implement the methods already in place. You already have a LogMode method which I NEED to implement because of the interface dependency, why would I RE-implement it ? 

Here is a more detailed explination why you should at least think about changing this:
Let´s say I want to make a layer between my application and your package:

APP <> LAYER<> GORM

My LAYER is required to implement your LogMode method and it´s functionality.  If I want to use that method in my APP, which is what would be considered normal, I now have to create a dependency on GORM in my APP. 

And yes, I can just wrap your LogMode method with more code, but that´s not really the optimal way of doing things.

**Comment by jinzhu** [comment]
> My LAYER is required to implement your LogMode method and it´s functionality. If I want to use that method in my APP, which is what would be considered normal, I now have to create a dependency on GORM in my APP.

I don't get why create a dependency on GORM in your APP if implemented in my way, but won't create a dependency in your way.

**Comment by zveinn** [comment]
Because of this method:
```go
// LogMode log mode
func (l *logger) LogMode(level LogLevel) Interface {
	newlogger := *l
	newlogger.LogLevel = level
	return &newlogger
}
```
If I don´t wrap your function with my own function then I have to import GORM/logger in my APP.. outside of my abstraction layer. 

If this method would look like this:
```go
// LogMode log mode
func (l *logger) LogMode(level int) Interface {
	newlogger := *l
	newlogger.LogLevel = level
	return &newlogger
}
```
it would remove the dependency on your package for the input variable. <br/>

Since you are worried about breaking things you can set an upper and lower limit to the log level, like so:
```go
// LogMode log mode
func (l *logger) LogMode(level int) Interface {
	newlogger := *l
	if level < 0 {
		l.LogLevel = 0
	} else if level > 3 {
		 l.LogLevel = 3 
	} else {
		l.LogLevel = level
	}
	return &newlogger
}
```

Preferably, this method should be split into two and the interface changed, like this: 
```go
// Interface 
// This interface describes the requirements for the GORM logger
type Interface interface {
	LogMode(int) 
	Info(context.Context, string, ...interface{})
	Warn(context.Context, string, ...interface{})
	Error(context.Context, string, ...interface{})
	Trace(ctx context.Context, begin time.Time, fc func() (string, int64), err error)
}


// Clone
// Clone the logger instance
func (l *logger) Clone(level int) Interface {
	newlogger := *l
	return &newlogger
}
// LogMode
// Change the LogMode
func (l *logger) LogMode(level int)  {
	if level < 0 {
		l.LogLevel = 0
	} else if level > 3 {
		 l.LogLevel = 3 
	} else {
		l.LogLevel = level
	}
}
```
You could then change your code to call Clone() before log mode whenever you need a new logger. This would remove ALL dependency on GORM when implementing a new logger and there for allowing GORM to be abstracted away from the main APP/program.

**Comment by jinzhu** [comment]
in you wrapper

```go
var Silent = logger. Silent
```

in your application

```go
wrapper.Silent
```

> I would actually like to argue that the LogMode method should not even be a part of the Interface at all. I don´t see why it needs to be:

How can GORM change the log level with `Debug` method then?

**Comment by zveinn** [comment]
> How can GORM change the log level with Debug method then?

Make another interface for the logger object that is more settings oriented instead of printing oriented. One struct can satisfy more then one interface :)
