### ISSUE TITLE
type:time 映射错误

### ISSUE THREAD

**Issue by micodecc** [go-gorm/gorm#3455]
Your Question
gorm版本：v2
mysql版本：8
运行环境：mac，在docker中运行mysql8

我用如下的方式
```go
type Demo struct {
    EndTime time.Time `gorm:"type:time"`  // 这里我原本希望在mysql中的数据类型是time，但实际上是datetime
}
```

我前面发过一个Issue，不过被关了，应该是未表述清楚，因此重新描述一次

**Comment by jinzhu** [comment]
GORM use `time` as general data type, so will convert it using the convention...

https://gorm.io/docs/models.html#Fields-Tags

So maybe you need to change it to something different, like `type:time(3)`...

**Comment by vczyh** [comment]
> Your Question
> gorm版本：v2
> mysql版本：8
> 运行环境：mac，在docker中运行mysql8
> 
> 我用如下的方式
> 
> ```go
> type Demo struct {
>     EndTime time.Time `gorm:"type:time"`  // 这里我原本希望在mysql中的数据类型是time，但实际上是datetime
> }
> ```
> 
> 我前面发过一个Issue，不过被关了，应该是未表述清楚，因此重新描述一次

请问是否解决，我设置`type:time(3)`也不生效

``` 
RunTime       *time.Time `gorm:"type:time(3);column:run_time"`
```

> Scan error on column index 14, name "run_time": unsupported Scan, storing driver.Value type []uint8 into type *time.Time;

**Comment by amazing-gao** [comment]
> > Your Question
> > gorm版本：v2
> > mysql版本：8
> > 运行环境：mac，在docker中运行mysql8
> > 我用如下的方式
> > ```go
> > type Demo struct {
> >     EndTime time.Time `gorm:"type:time"`  // 这里我原本希望在mysql中的数据类型是time，但实际上是datetime
> > }
> > ```
> > 
> > 
> > 我前面发过一个Issue，不过被关了，应该是未表述清楚，因此重新描述一次
> 
> 请问是否解决，我设置`type:time(3)`也不生效
> 
> ```
> RunTime       *time.Time `gorm:"type:time(3);column:run_time"`
> ```
> 
> > Scan error on column index 14, name "run_time": unsupported Scan, storing driver.Value type []uint8 into type *time.Time;

@vczyh it works for me. https://github.com/go-gorm/gorm/issues/958#issuecomment-215434667
