### ISSUE TITLE
Many2Many Ignoring already present record

### ISSUE THREAD

**Issue by napei** [go-gorm/gorm#3462]
## Your Question

Not sure if it's a bug or I'm doing something wrong.

Having a little trouble with many2many not working. I have structs for a Product, and a Category. Products can have many Categories and Categories can be assigned to many Products. An abstraction of this is below.

```go
/* In Database package
  type Base struct {
    ID        uuid.UUID `json:"id" gorm:"primaryKey;type:uuid;uniqueIndex"`
    CreatedAt null.Time `json:"createdAt"`
    UpdatedAt null.Time `json:"updatedAt"`
  }
*/

type Product struct {
  database.Base
  Price int
  Categories []Category `gorm:"many2many:product_categories;"`
}

type Category struct {
  database.Base
  Name string
}
```

I can't get updating/adding a new many2many row working properly. When I pass a category with just a uuid in it, from the JSON provided to my API and use `DB.Model(&product).Association("Categories").Replace(&categories)` Instead of looking up the category by ID GORM creates a new category. 

For example given a JSON input shown below for a product with ID `4a0c1134-bd0d-4e7d-ad43-2be84a59e2d2`, parsed as categories with IDs and sent to `.Associations("Categories").Replace(&categories)` I get the following result. 2 new categories are added, with completely different IDs than I wanted..I've also tried manually creating entities in GO with a specific ID. Below are some screenshots of what happens.

![image](https://user-images.githubusercontent.com/8946502/93015887-6dc0b480-f600-11ea-91c1-8989569a96e7.png)

![image](https://user-images.githubusercontent.com/8946502/93015867-44a02400-f600-11ea-8423-56719fc07ab0.png)

Categories do exist
![image](https://user-images.githubusercontent.com/8946502/93015947-e6c00c00-f600-11ea-9519-78f0365c882e.png)

2 New categories added
![image](https://user-images.githubusercontent.com/8946502/93015933-c7c17a00-f600-11ea-892d-1c00dccdcf54.png)

Many2Many Table
![image](https://user-images.githubusercontent.com/8946502/93015956-f8091880-f600-11ea-8992-39973fea20d7.png)

I'm confused with associations, and how they must be separated apart from `.Updates()` or `.Save()`. I tried passing the category ids into `.Updates()` and it was just ignored.

**What I expect to happen**
`Associations().Replace()` should not create new records if a primary key is provided in the entity/entities that are being appended/replaced/deleted. `.Updates()` should be able to parse category IDs that I give it and update the many2many table. I should be able to associate record together that already exist in the many2many table.

SQL wise it's very simple.

```sql
INSERT INTO "product_categories" ("product_id", "category_id") VALUES ('product-uuid', 'categoryid1'), ('product-uuid', 'categoryid2')
```

Thanks

**Comment by jinzhu** [comment]
> Associations().Replace() should not create new records if a primary key is provided in the entity/entities that are being appended/replaced/deleted. 

GORM will use upsert when saving associations, and it should not change the primary key, I guess maybe you changed the primary key in hooks methods?

Anyway, please create a new issue with reproducible pull request on https://github.com/go-gorm/playground if you can reproduce the issue.

**Comment by napei** [comment]
Thanks for the clarification @jinzhu it was late and I wasn't really focused on what upsert means. Noticing the `ON CONFLICT DO  NOTHING` part made me realise my `BeforeCreate` hook was wrong.

It should be:

```go
type Base struct {
	ID        uuid.UUID `json:"id" gorm:"primaryKey;type:uuid;uniqueIndex;default:uuid_generate_v4()"`
	CreatedAt null.Time `json:"createdAt"`
	UpdatedAt null.Time `json:"updatedAt"`
	DeletedAt null.Time `json:"deletedAt" gorm:"index"`
}

// BeforeCreate -
func (base *Base) BeforeCreate(tx *gorm.DB) error {
	if base.ID == uuid.Nil {
		base.ID = uuid.New()
	}
	now := time.Now()
	base.CreatedAt = null.TimeFrom(now)
	base.UpdatedAt = null.TimeFrom(now)
	return nil
}
```
The key being only assign a new UUID if it's not present. I suppose with `default:uuid_generate_v4()` maybe assignment of the ID is redundant? 

Some of the examples don't really make this too clear in the docs, and upserting isn't fully explained as far as I can see

At https://gorm.io/docs/hooks.html maybe the examples should be changed to safeguard IDs that already exist as my hook does?

Thanks :)
