### ISSUE TITLE
Smart Select Fields does not work

### ISSUE THREAD

**Issue by updogliu** [go-gorm/gorm#3463]
Version: `github.com/jinzhu/gorm v1.9.16`

The example of Smart-Select-Fields documented at [Smart-Select-Fields](https://gorm.io/docs/advanced_query.html#Smart-Select-Fields) seems simply not working.

I failed to make gorm playground work. But the code to reproduce the bug is pretty simple:

```
type Student struct {
	Id   int64 `gorm:"column:id;primary_key;AUTO_INCREMENT"`
	Name string
	Age  int64
}

type NameOnly struct {
	Name string
}

db.Create(&Student{Name: "Ann", Age: 20})

var data []*NameOnly

// Error: Table 'name_only' doesn't exist
db.Model(&Student{}).Where("Name = ?", "Ann").Find(&data)

// Works fine
db.Table("student").Where("Name = ?", "Ann").Find(&data)
```

**Comment by jinzhu** [comment]
smart select is a gorm v2 feature.
