### ISSUE TITLE
AutoMigrate

### ISSUE THREAD

**Issue by jeyldii** [go-gorm/gorm#3464]
## Your Question

Why gorm puts bigint in column ```address_id``` based on this struct field:
```
AddressID      uint       `gorm:"primary_key; autoIncrement:false"`
```

I try to put tag ```type:int/integer/INT``` but no expected results. Also i switched go type in struct field from uint > int.

## The document you expected this should be explained

https://gorm.io/docs/models.html

## Expected answer

How can i resolve this?

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/93037208-794dc300-f674-11ea-8773-0c2e4750ac78.png)
