### ISSUE TITLE
How to get the ID value of the content created in the transaction

### ISSUE THREAD

**Issue by Evangelione** [go-gorm/gorm#3467]
## Your Question

How to get the ID value of the content created in the transaction

## The document you expected this should be explained

github.com/jinzhu/gorm v1.9.11

## Expected answer

![image](https://user-images.githubusercontent.com/24892968/93052462-c3e13680-f698-11ea-978c-ea258f6ec1d1.png)

**Comment by jinzhu** [comment]
not a valid gorm question
