### ISSUE TITLE
Creating a Driver for Data API (Amazon Aurora Serverless)

### ISSUE THREAD

**Issue by asterikx** [go-gorm/gorm#3471]
## Describe the feature

Creating a driver for [Amazon RDS Data Service](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/Welcome.html) (a.k.a. [Data API for Amazon Aurora Serverless](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)).

> This feature enables you to access a MySQL-compatible [or PostgreSQL-compatible] version of an Amazon Aurora Serverless database with a simple API endpoint and without the hassle of managing persistent database connections in your applications. If you use AWS Lambda, the Data API provides a secure way to access the database without the additional overhead for Lambda functions launched in a VPC. Also, the Data API can use database credentials stored in AWS Secrets Manager, eliminating the need to pass credentials in API calls. ([source](https://aws.amazon.com/blogs/database/using-the-data-api-to-interact-with-an-amazon-aurora-serverless-mysql-database/))

## Motivation

While the goal of the Data API to abstract from database connections and eliminate the need for connection pooling in a serverless setup, a `database/sql/driver` wrapper for the Data API would allow us to use Aurora Serverless in the same way as regular MySQL or PostgreSQL databases.
This would allow using the same data access layer code for serverless and on-premise deployments by merely switching the drivers.

---

I have started the implementation of a `database/sql/driver` for the Data API (based on [Clever/rds](https://github.com/Clever/rds/tree/birthday)), but I'm not sure how to integrate it with GORM as GORM provides its very own drivers.

I would like to collect ideas on implementing a driver for the Data API to be used with GORM (and potentially other libraries). Are there any specificities to consider in the case of GORM?

**Comment by jinzhu** [comment]
Hello @asterikx 

GORM should works with the driver if it implements the interface https://github.com/go-gorm/gorm/blob/1d5f910b6e1a377f7f7defadb606a3e9c7a09c01/interfaces.go#L30-L35

Also check out how GORM integrate it with postgres https://github.com/go-gorm/postgres

**Comment by jakubknejzlik** [comment]
Just sharing random find on github of RDS Data API driver: https://github.com/graveyard/rds/tree/birthday . 
Unfortunately it's not officially released and I'm not sure how production ready the code is so take it as an example of implementation.

**Comment by krotscheck** [comment]
I've put some time into building a driver for this- the challenge isn't so much the driver implementation (it's pretty straightforward, as you can wrap a dialector around any `driver.Driver` interface). The challenge is that the RDS Data API does not support ordinal SQL parameters; it only supports named ones. Unfortunately, both of the `Migrators` in the postgres and mysql dialectors use ordinal parameter substitution, and if I taught my driver to convert one into the other, well, I'd be one bug away from an SQL Injection Attack. I have an immediate need for switching the mysql migrator over, so I can put some time towards that if @jinzhu is interested, and have filed https://github.com/go-gorm/mysql/issues/41 to discuss it.
