### ISSUE TITLE
How to mock/test model?

### ISSUE THREAD

**Issue by rafa-acioly** [go-gorm/gorm#3474]
How can i mock the database transactions?

My module is using the `sql.DB` as dependency injection and [`sqlmock`](https://github.com/DATA-DOG/go-sqlmock), it works fine because the database returned from `sqlmock` respect the `sql.DB` interface.
Now i'm trying to go with a ORM to keep the things clean but i could not find any testing technics for `gorm`.

The repository:
```go
type Repository struct {
    db *sql.DB
}

func NewRepository(db *sql.DB) Repository {
    return Repository{db: db}
}

func (r *Repository) Exists(id string) bool {
    stmt, err := r.db.QueryRow(...)
}
```

The test:

```go
func TestFindByID(t *testing.T) {
    db, mock, _ := sqlmock.New()
    repo := NewRepository(db) // inject the mocked database

    exist := repo.Exists("mocked-id")
}
```

**Comment by jinzhu** [comment]
https://gorm.io/docs/connecting_to_the_database.html#Existing-database-connection
