### ISSUE TITLE
Create documentation for testing

### ISSUE THREAD

**Issue by nikolaistraessle** [go-gorm/gorm#3476]
## Your Question
Can the documentation extended with examples how to test and mock this library?

## The document you expected this should be explained

A documentation with examples how this library can be tested and mocked.

**Comment by jinzhu** [comment]
Hi,

I would suggest to real database for testing, but if you want to mock, you could use `sqlmock` with GORM like this https://gorm.io/docs/connecting_to_the_database.html#Existing-database-connection

Also you could use the new `DryRun` mode to check generated SQL.
