### ISSUE TITLE
JSONB Query Error

### ISSUE THREAD

**Issue by EnsPzr** [go-gorm/gorm#3477]
Hello. I want to query a integer based jsonb column. I want to use "?|" operator. This operator is an operator for [jsonb](https://devhints.io/postgresql-json) by postgresql. But ıt seems gorm does not support to use it.

```
dbObj := db.
		Session(&gorm.Session{DryRun: true}).
		Model(&kisiler)
dbObj = dbObj.Where("array_to_json(translate(il_idler::jsonb::text, '[]', '{}')::text[])::jsonb ?| array['58']")
if err := dbObj.Find(&kisiler).Error; err != nil {
	fmt.Println(err.Error())
} else {
	fmt.Println("hata yok")
}
```

![Ekran Resmi 2020-09-16 12 49 00](https://user-images.githubusercontent.com/18161640/93321721-2eba7b00-f81b-11ea-9b05-e5fb9e368db1.png)

**Comment by jinzhu** [comment]
https://github.com/go-gorm/datatypes
