### ISSUE TITLE
raw query with aggregation query can't scan and row affected = 0

### ISSUE THREAD

**Issue by aholicz** [go-gorm/gorm#3478]
I face the problem, While i try to query using 'SUM' statement.

	var b int
	if err := db.Raw(`SELECT SUM(balance) FROM ITEMS`).Scan(&b).Error; err != nil {
		panic(err.Error())
	}

the result of the query is un support type, so I change to sql.NullInt64 still can't parse and got row affected = 0 

later ... I proof by database/sql package 

	var c int64
	err = db.QueryRow('SELECT SUM(balance) FROM ITEMS').Scan(&c)
	if err != nil {
		panic(err.Error())
	}

this statement working link charm.

gorm v 1.20.0 
driver gorm.io/driver/mysql
MySQL version 5.7

**Comment by jinzhu** [comment]
This is fixed on latest master
