### ISSUE TITLE
Is there a way in GORM of preventing duplicates when querying has-many relations?

### ISSUE THREAD

**Issue by Robbie-Perry** [go-gorm/gorm#3479]
## Your Question

Suppose I have a model that looks like this:
```go
type Asset struct {
	ID        int
	Kind      string
	Value     float32
	PersonID  int
}
type Person struct {
	ID      int
	Name    string
	Assets []Asset `gorm:"foreignkey:PersonID;"`
}
```

And suppose the database contains the following data:
```go
{
	Name: "Jinzhu",
	Assets: []Asset{
		{
			Kind: "Cash",
			Value: 10000,
		},
		{
			Kind: "House",
			Value: 1000000,
		},
	},
}
```

Let's say I wanted to perform a query, that has both filters and orders on the fields within assets. If I were to do this:
```go
err = db.
	Preload(clause.Associations).
	Joins("LEFT JOIN assets ON assets.person_id = people.id").
	Where("assets.value > ?", 2000).
	Order("assets.value ASC").
	Find(&people)
```
`people` will end up containing 2 duplicates of the item, since the JOIN resulted in multiple rows returned, one for each `Asset`.

If I were to use `Distinct` on the ID, postgres will give an error, because [for SELECT DISTINCT, ORDER BY expressions must also appear in the select list](https://stackoverflow.com/questions/12693089/pgerror-select-distinct-order-by-expressions-must-appear-in-select-list). In addition, failing to ORDER BY the distinct ID can also drastically slow down the query, as discussed [here](https://stackoverflow.com/questions/53749347/why-does-adding-order-by-drastically-speed-up-query)

## The document you expected this should be explained

[Advanced Query](https://gorm.io/docs/advanced_query.html)

## Expected answer

I'm wondering if there is a clean way of handling this behaviour using GORM.

**Comment by jinzhu** [comment]
Not necessary to have the Join, `Preload` will do the job.

**Comment by Robbie-Perry** [comment]
@jinzhu but without the Join, the query will return the error `missing FROM-clause entry for table "assets"`, as the `Where` and `Order` both reference it.

**Comment by jinzhu** [comment]
don't use left join then https://stackoverflow.com/questions/5706437/whats-the-difference-between-inner-join-left-join-right-join-and-full-join#:~:text=RIGHT%20JOIN%3A%20returns%20all%20rows,missing%20matches%20on%20either%20side.
