### ISSUE TITLE
Dialect-aware variant of Tabler

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [go-gorm/gorm#3481]
## Describe the feature

In some contexts it would be very helpful to have a variant of the `Tabler` interface that models can implement that is dialect aware -- i.e. it can return a different value depending on the dialect in use.

## Motivation

When building an app that uses e.g. PostgreSQL in production but SQLite in testing, models that need their name to be schema-qualified when talking to PostgreSQL can't use that same qualified name when talking to SQLite.

## Related Issues

Haven't found any yet

----

A proposed sketch:
```go
type DialectTabler interface {
  TableName(Dialector) string
}
```

in `schema.Parse`, it would then check for this interface first before falling back on `Tabler`.

A couple potential difficulties with this I see:
* Passing a `Dialector` instance into `schema.Parse` everywhere might be a bit of a yak shave
* A naive attempt at implementing this might introduce a circular dependency between the top level `gorm` package and the `schema` package. This might require moving the definition of the `Dialector` type, or something else creative

**Comment by mgabeler-lee-6rs** [comment]
@jinzhu how am I supposed to provide a playground PR for a _feature request_?

**Comment by jinzhu** [comment]
I would suggest implement the Naming strategy based on the dialector when initialize `gorm.DB`

**Comment by mgabeler-lee-6rs** [comment]
That implies that the Naming strategy has to know info about all the models and their behavior, which produces pretty unclean code. And since the naming strategy gets a candidate table name passed to it, not a model instance, it can't pull information from e.g. custom interfaces the models might implement.

**Comment by jinzhu** [comment]
that's exactly we want to avoid, I received lots of misusage reports about the `TableName` method in v1, maybe this is helpful for you. https://gorm.io/docs/v2_release_note.html#Table-Name
