### ISSUE TITLE
Calling DB.Find() with an ID that doesn't exist, does not return ErrRecordNotFound

### ISSUE THREAD

**Issue by Robbie-Perry** [go-gorm/gorm#3485]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/142

## Description

It doesn't return an error at all, and since that RecordNotFound() method was removed in GORM 2, can't really distinguish between a successful operation, and one where the record is not found.

**Comment by Robbie-Perry** [comment]
Just had a thought: Does ErrRecordNotFound even make sense for Find(), or is it only applicable for methods such as First(), Last(), and Take()?

Can close this issue if so

**Comment by jinzhu** [comment]
> Just had a thought: Does ErrRecordNotFound even make sense for Find(), or is it only applicable for methods such as First(), Last(), and Take()?

Yes, it is only applicable for `First`, `Last`, `Take` https://gorm.io/docs/query.html#Retrieving-a-single-object
