### ISSUE TITLE
Add caching layer of query

### ISSUE THREAD

**Issue by tabvn** [go-gorm/gorm#3489]
Is there way to add new caching layer feature such as Redis cache as long query and also expiration of caching. ?
Thank you.

**Comment by jinzhu** [comment]
```go
func QueryFromCache(db *gorm.DB) {
   if !readFromCache(db) {
      callbacks.Query(db)
   }
}
db.Callback().Query().Replace("gorm:query", QueryFromCache)
```

or override the `Conn` like the `prepared statments`

**Comment by tabvn** [comment]
@jinzhu  thank you, if this is also including into developer document that could be great for other developers would like to integrate with caching layer with Gorm.

**Comment by mikarios** [comment]
Hello,
we have tried to add a caching layer in our system. What we have done is overwrite the gorm:query like so:
`db.Callback().Query().Replace("gorm:query", queryFromCache)`

In queryFromCache what we do is:


```
_, err := cacheService.Get(key, db.Statement.Dest)
if err != nil {
    callbacks.Query(db)

    if db.Statement.Error != nil {
      return
    }

    value := db.Statement.Dest
    _ = cacheService.Set(key, value, config.GetInstance().REDIS.TTL)

    return
}
```
Problem is that if the result is found in cache then the AfterFind hook (and possibly other hooks as well) does not get executed. Is there a reason for this that we haven't found or it's a bug?

**Comment by mikarios** [comment]
We found out that we need to set db.RowsAffected = 1 in order for the AfterFind to be executed...
This is very counter intuitive and confusing. Is this the intended behaviour?

**Comment by kateile** [comment]
Coming from Node JS world [TypeORM](https://github.com/typeorm/typeorm) have a really incredible caching mechanism which is integrated on ORM itself. For instance if you are finding a single document from database the result can be stored on redis/memory so later queries don't hit database until expire time has reached or results are manually invalidated. More can be seen here on [docs](https://typeorm.io/caching#).

@jinzhu I think it will be really helpful if caching functionality is implemented in `gorm` directly.  Maybe you want to reopen this?

**Comment by rts-gordon** [comment]
Support adding Redis and Cache layer for GORM.

**Comment by navicstein** [comment]
https://github.com/Pacific73/gorm-cache

found this library, it pretty much works with redis

**Comment by Goodnessuc** [comment]
@jinzhu please reopen

**Comment by jinzhu** [comment]
https://github.com/go-gorm/caches
