### ISSUE TITLE
Migrator ignores transaction

### ISSUE THREAD

**Issue by betlor5** [go-gorm/gorm#3490]
GORM Playground Link
------------------

go-gorm/playground#144

Description
------------------

After trying around it seems as if the migrator ignores transactions and commits after every opertion. Therefore if it is used for migrations and an error occures the database would be left in an unknown state.

For the test I am running a MariaDB v10.4.6 database. Within that database I have got a "test" schema and a "golang" user which can acces it through a password. My test code to produce the error is as follows:

```
package main

import (
	"fmt"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

var (
	password = "secret"
	port     = 3306
)

type TestData struct {
	Id   int
	Data string
}

func main() {
	dsn := fmt.Sprintf("golang:%v@tcp(localhost:%v)/test", password, port)

	var err error
	var db *gorm.DB
	if db, err = gorm.Open(mysql.New(mysql.Config{DSN: dsn}), &gorm.Config{}); err != nil {
		panic(err)
	}

	tx := db.Begin()
	tx.Migrator().AutoMigrate(&TestData{})
	if err = tx.Rollback().Error; err != nil {
		panic(err)
	}
}

```

After running the program I am finding a "test_data" table, which shouldn't be there.

Please help!

**Comment by betlor5** [comment]
Gorm Playground Link: go-gorm/playground#144

**Comment by jinzhu** [comment]
GORM support that, but mysql doesn't

https://stackoverflow.com/a/4736346
