### ISSUE TITLE
Count failed when find condition has Order() method

### ISSUE THREAD

**Issue by qinxin0720** [go-gorm/gorm#3491]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/145

## Description

go version: 1.15.2
gorm v2: 1.20.1
database: postgres 11

```go
type Person struct {
	ID       string    `gorm:"column:id"`
	Name     string    `gorm:"column:name"`
	CreateAt time.Time `gorm:"column:create_at"`
}

if err := db.AutoMigrate(&Person{}); err != nil {
	log.Panic(err)
}

db.Create(&Person{
	ID:       "1001",
	Name:     "Alice",
	CreateAt: time.Unix(1600480219, 0),
})

db.Create(&Person{
	ID:       "1002",
	Name:     "Bob",
	CreateAt: time.Unix(1600480220, 0),
})

db.Create(&Person{
	ID:       "1003",
	Name:     "Cathy",
	CreateAt: time.Unix(1600480221, 0),
})

var persons []Person
var count int64

res := db.Limit(2).Offset(2).Order("create_at desc").Find(&persons).Limit(-1).Offset(-1).Count(&count)
if res.Error != nil {
	log.Panic(res.Error)
}
log.Println(persons)
log.Println(count)
```

this case will fail on Count() method when find condition has Order() method.

sql error is ERROR: column "people.create_at" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)

**Comment by jinzhu** [comment]
`postgres` doesn't like count with order by like `mysql`, check out the following link might help.

https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety

**Comment by knowlet** [comment]
Workaround, add this before count:
```
delete(tx.Statement.Clauses, "ORDER BY")
```
works for me.
