### ISSUE TITLE
Named Parameter not working with slice

### ISSUE THREAD

**Issue by schmittjoh** [go-gorm/gorm#3494]
Named parameters do not seem to work in combination with slice parameters as in this example:

```
db.Raw("SELECT * FROM users WHERE id IN (@ids)", map[string]interface{}{"ids": []int{1, 2, 3}})
```

This query generates invalid SQL for MySQL (note the double parenthesis in generated SQL):

```
SELECT * FROM users WHERE id IN ((1, 2, 3))
```

It works fine when using unnamed parameters using `?`. The resulting MySQL error is: 
```
Error 1241: Operand should contain 1 column(s)
```

**Comment by jinzhu** [comment]
Hi,

Would suggest you to write it like this:

```go
db.Raw("SELECT * FROM users WHERE id IN @ids", map[string]interface{}{"ids": []int{1, 2, 3}})
```

The style works for normal conditions, for example:

```go
db.Raw("SELECT * FROM users WHERE id IN ?", []int{1, 2, 3})
```

Although the second one compatible with the following style, due to GORM v1 only allow this, we don't want to increase the complexity for named argument to support this.

```go
db.Raw("SELECT * FROM users WHERE id IN (?)", []int{1, 2, 3})
```

Thank you.
