### ISSUE TITLE
How to : GIST/GIN index

### ISSUE THREAD

**Issue by AubSs** [go-gorm/gorm#3495]
Hi, first of all, thank you for your amazing lib !

I'm trying to implement LTREE but I need to create a GIST index on one field (with GORM of course).
I don't find any doc/exemple to do that...

How can I achieve that ?

thx !

**Comment by jinzhu** [comment]
Use tag `index:,type:gist` https://gorm.io/docs/indexes.html#Index-Tag, require postgres driver v1.0.1

**Comment by AubSs** [comment]
Thank you very much ! it's working !
