### ISSUE TITLE
many2many custom foreign does not work

### ISSUE THREAD

**Issue by helmus** [go-gorm/gorm#3497]
## GORM Playground Link

This PR includes the [example from the documentation](https://gorm.io/docs/many_to_many.html), which works in SQL lite but none of the other databases.  
https://github.com/go-gorm/playground/pull/146

This pr is an even more simplified example which only tries to use a custom foreign key, which panics in SQL lite
https://github.com/go-gorm/playground/pull/147

## Description

This breakage is preventing me from upgrading to gorm 2, as this functionality does work in gorm 1 ( using `association_jointable_foreignKey` and `jointable_foreignKey` tags )

**Comment by jinzhu** [comment]
tests pass in your example.

also check out https://gorm.io/docs/associations.html#Association-Tags for the foreign key

**Comment by jinzhu** [comment]
Hi,

I think I get your question, to use a field as database foreign key, `mysql`, `postgres` requires it is a `index`, so the full example should be something like:

![image](https://user-images.githubusercontent.com/6843/93732760-50de3f80-fc05-11ea-8e07-b2fcbd9f86ee.png)

I will update the document, thank you for your report.
