### ISSUE TITLE
Add option to allow check unique constraint (duplicate) errors

### ISSUE THREAD

**Issue by lafriks** [go-gorm/gorm#3499]
Currently there is only RecordNotFound error check. Would be great if there was a way to check also unique errors as for different databases errors are different. Ideally it would be great if error would contain also column name in question.

Ref: #2903

**Comment by jinzhu** [comment]
Our drivers accept pull request to support check those error

**Comment by jinzhu** [comment]
Btw, in this case, I would prefer you to use `Upsert` to do the job.

**Comment by lafriks** [comment]
@jinzhu `Upsert` is not always an option. There could be for example other unique constraints for example if user wants to add email to it's profile that already has added to other profile in such case need to detect such error and display user an explaining error message

**Comment by gutakk** [comment]
I know that this is closed issue but I found a workaround for postgres to check the specific error.
As gorm postgres driver based from [jackc/pgconn](https://github.com/jackc/pgconn), you can do something like this

```go
import "github.com/jackc/pgconn"

result := db.Create(...)
pgError := result.Error.(*pgconn.PgError)
log.Printf(pgError.Code)
```
