### ISSUE TITLE
transactions with sqlite | database locked if there is no explicit commit / rollback

### ISSUE THREAD

**Issue by PricelessRabbit** [go-gorm/gorm#3501]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/149

## Description

Use case:
2 different transactions opened, but one of them not committed or roll-backed

The issue:
If a transaction remains "pending" (no commit and no rollback) for example using transaction in "manual" mode (https://gorm.io/docs/transactions.html#Transactions-by-manual) or for some reasons the deferred db close is not called, The db remains locked until the go process is restarted. 

Real example:
In a server environment like echo, multiple requests are processed. If there is a failure in one of them and for some reason the transaction is not closed properly, all the server becomes useless and to access the db a restart is needed.

I also tried to create different db connection with `gorm.Open` but that not fix the issue. 
Seems that the only way is to Commit or Rollback explicitly, or to defer the RollbackUnlessCommitted function

**Comment by jinzhu** [comment]
Yes, this is required for sqlite, and not something that GORM could resolve.
