### ISSUE TITLE
time.Duration  for  postgresql  AutoMigrate failed 

### ISSUE THREAD

**Issue by gleke** [go-gorm/gorm#3503]
## Description
type SysOperationRecord struct {
	gorm.Model
	Ip           string        `json:"ip" form:"ip" gorm:"column:ip;comment:请求ip"`
	Method       string        `json:"method" form:"method" gorm:"column:method;comment:请求方法"`
	Path         string        `json:"path" form:"path" gorm:"column:path;comment:请求路径"`
	Status       int           `json:"status" form:"status" gorm:"column:status;comment:请求状态"`
	Latency      time.Duration `json:"latency" form:"latency" gorm:"column:latency;comment:延迟"`
	Agent        string        `json:"agent" form:"agent" gorm:"column:agent;comment:代理"`
	ErrorMessage string        `json:"error_message" form:"error_message" gorm:"column:error_message;comment:错误信息"`
	Body         string        `json:"body" form:"body" gorm:"column:body;comment:请求Body"`
	Resp         string        `json:"resp" form:"resp" gorm:"type:longtext;column:resp;comment:响应Body"`
	UserID       int           `json:"user_id" form:"user_id" gorm:"column:user_id;comment:用户id"`
	User         SysUser       `json:"user"`
}

err := db.AutoMigrate(		
		model.SysOperationRecord{},
	)

 failed  :SQLSTATE 42P01

**Comment by jinzhu** [comment]
`time.Duration`  is not supported as `database/sql` doesn't support it, have to implemented the `Scanner`, `Valuer` interface for customized data types.
