### ISSUE TITLE
Update single column (or map update) doesn't work

### ISSUE THREAD

**Issue by oriser** [go-gorm/gorm#3504]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/150

## Description
Updating a single column by `Update` and `UpdateColumn` simply doesn't work. It returns an error: `unsupported data type: map[<col_name>:<col_value>]`. It also happens with `Updates(map[string]interface{}{...})`
This is not matching the function documentation and the official documentation (https://gorm.io/docs/update.html).

**Comment by jinzhu** [comment]
`DB.Model(User{Model: gorm.Model{ID: user.ID}}).Update("name", "foo")`
