### ISSUE TITLE
Unnecessarily updating relationship `updated_at` when using `.Save()`

### ISSUE THREAD

**Issue by ping-localhost** [go-gorm/gorm#3510]
## Your Question

When using `.Save` on a pre-loaded model, it will change all `updated_at`-fields for all it's relations (even if the that relationship model hasn't been changed). 

This to be sounds like a bug, but I wanted to make sure it is first, which is why I'm asking why this is happening.

**Example**:

``` golang
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
)

type User struct {
	gorm.Model
	Name       string
	CreditCard CreditCard
}

type CreditCard struct {
	gorm.Model
	Number string
	UserID uint
}

func main() {
	db, err := gorm.Open("mysql", fmt.Sprintf(
		"%s:%s@%s/%s?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true&multiStatements=true",
		"username",
		"password",
		"host",
		"database"))

	if err != nil {
		panic("failed to connect database: " + err.Error())
	}

	// Create the user + credit card and store it
	if err := db.Save(&User{Name: "Name", CreditCard: CreditCard{Number: "12345"}}).Error; err != nil {
		panic(err.Error())
	}

	// Find and preload the user
	var user *User
	if err := db.Set("gorm:auto_preload", true).First(&user).Error; err != nil {
		panic(err.Error())
	}

	// Change the name
	user.Name = "Other name"

	// Store it again, but now the `updated_at` for credit_card will be changed as well
	if err := db.Save(user).Error; err != nil {
		panic(err.Error())
	}
}
```

Running `db.Save(&user)` will update both the `User`-struct `updated_at`, but also the `CreditCard`-struct `updated_at`.

## The document you expected this should be explained

https://gorm.io/docs/update.html#Save-All-Fields

## Expected answer

I would expect `.Save` (and possibly `.Update` as well) to only change the `updated_at`-time when the relationship model was actually changed.

**Comment by jinzhu** [comment]
GORM v2 fixed that.

**Comment by ping-localhost** [comment]
I must have totally missed that v2 has been released. I'll update my code and check it out. Thank you for the quick reply!

**Comment by ping-localhost** [comment]
Sorry, one more question, where can I find v2 @jinzhu? Is that tag `v1.20.1` on this repo or?
