### ISSUE TITLE
Incorrect statement table when using `auto_preload`

### ISSUE THREAD

**Issue by ping-localhost** [go-gorm/gorm#3511]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/151

## Description

When using `auto_preload: true` the `DB.Statement` is not cleared causing issues with the queries afterwards. Since `DB.Statement.Table` is `users` instead of `languages` (or just empty, which is what happens if you don't `auto_preload`).

I highly expect that this is unwanted behaviour since this doesn't happen in in V1 or with `auto_preload: false`.

**Comment by jinzhu** [comment]
https://gorm.io/docs/v2_release_note.html#Method-Chain-Safety-Goroutine-Safety

And GORM V2 doesn't support `auto_preload: true` anymore, read above link for all breaking changes.

**Comment by ping-localhost** [comment]
I see. It's a bit odd that it can still be set and seems to have an effect but I guess that's a different issue. 🙂

Thank you for your quick responses.

**Comment by jinzhu** [comment]
Read this link https://gorm.io/docs/v2_release_note.html#Method-Chain-Safety-Goroutine-Safety

**Comment by ping-localhost** [comment]
I shall and I'll update my code to accommodate these changes. I'm just saying that it's odd that `Set("gorm:auto_preload", true)` still exists. I would expect it to have no effect or result in an error.
