### ISSUE TITLE
Namer ColumnName - wrong table name when using embedded base model

### ISSUE THREAD

**Issue by Hellysonrp** [go-gorm/gorm#3513]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/152

### Wrong table name on ColumnName
The table name is generated by reflection and saved to the field.
This behavior is implemented here: https://github.com/go-gorm/gorm/blob/f6ed895caffcde0b37d181201a5cadd442b8879e/schema/schema.go#L96

While parsing the field from the base model, `Parse` is called again, but this time `dest` is of the type of the base model:
https://github.com/go-gorm/gorm/blob/68920449f92f24c8b17d90986eb155c251ed8fc7/schema/field.go#L329

If the `ColumnName` function is overridden and uses the table name, the behavior might be unexpected.
In this test, the function was overridden to add a prefix based on the table name.

For example, after running the migration in this test, the users table will be like:

![test_result](https://user-images.githubusercontent.com/5438762/93946234-1d87d780-fd0f-11ea-89cd-31c2855c1c4e.png)

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
