### ISSUE TITLE
Support complexity field with special tag saved as json content.

### ISSUE THREAD

**Issue by j2gg0s** [go-gorm/gorm#3516]
## Describe the feature

In one model, field type may be slice, array, struct or pointer.
Can we support one tag, so:
- before create and updated, this field will be serialized by json.marshaled and saved as bytes.
- after query, value we be deserialized by json.unmarshal and assigned to field.

## Motivation
With [GraphQL](https://graphql.org/) and [Thrift](http://thrift.apache.org/), i generated model from api with some tools.
I don't want to used type alias, such as ``type A []string``, this will break my api.

## Example
I current write application to save my web link, the main object is link. IDL in graphql and golang's object
```graphql
type Link {
  id: ID!
  name: String!
  url: String!
  desc: String
  tags: [Tag!]
  createdAt: Time
  updatedAt: Time
}

scalar Tag
```
```golang
type Link struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	URL       string     `json:"url"`
	Desc      *string    `json:"desc"`
	Tags      []string   `json:"tags" gorm:"type:golang;xjson"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
}
```

## Related PR
I'm trying to support this feature in this pr: https://github.com/go-gorm/gorm/pull/3515 

## Need some advice.
Should we support this feature? And how?

**Comment by jinzhu** [comment]
Implement the `Scanner`, `Valuer`
