### ISSUE TITLE
how to get new stream

### ISSUE THREAD

**Issue by xxjwxc** [go-gorm/gorm#3520]
## Your Question
I want to reuse DB like gorm v1 New() in case:
```
func NewDB(){
	db, _ := gorm.Open(...)
	db.Model(&AAA).Where("aaa = ?", 2)
	CallFunc(db)
}

func CallFunc(db *gorm.DB){
	// select a...
	var bbb BBB
	db.Table("bbb").Where("bbb = ?", 2).Find(&bbb)// in this case aaa = ?  valid
	// in this func how to use db to query BBB  
}
``` 

in gorm v1 i can using gorm.New() to get 

i want 

add one function New() to clone gorm.Statement

now i using one way ：
```
func new(db *gorm.DB) *gorm.DB {
	newDb := db.WithContext(ctx)
	newDb.Statement.Clauses = make(map[string]clause.Clause)
	return newDb
}
```
But I don't think it's the right way to do it

**Comment by xxjwxc** [comment]
With your permission, I will implement this method

**Comment by jinzhu** [comment]
`db.Session(&gorm.Session{})` will do the job.
