### ISSUE TITLE
Support NullString with sqlite?

### ISSUE THREAD

**Issue by Robbie-Perry** [go-gorm/gorm#3521]
## Your Question

I have created a new type defined as  `type MultiString []string`, which implements `Scanner` and `Valuer`, in order to store a slice of strings as a single text column, separated by commas. If the slice is empty, `Value()` returns a `sql.NullString{}`.

This works correctly with the postgres driver. However, using sqlite, it reqturns the following error upon trying to call `db.Create()`:

`sql: converting argument $2 type: non-Value type sql.NullString returned from Value`

Model: 
```go
type Person struct {
	ID      int
	Name    string
	Kids	*MultiString
}
```
SQL generated:
```sql
CREATE TABLE `people` (`id` integer,`name` text,`kids` text,PRIMARY KEY (`id`));
INSERT INTO `people` (`name`,`kids`) VALUES ("Jinzhu",NULL);    // RETURNS ERROR HERE
```

## Expected answer

Is NullString supported in GORM using sqlite?

**Comment by jinzhu** [comment]
Not a GORM related issue, maybe you can ask the sqlite driver team, and `Value` method should return basic golang types, but not another `Scanner`/`Valuer`

**Comment by Robbie-Perry** [comment]
> `Value` method should return basic golang types, but not another `Scanner`/`Valuer`
@jinzhu Hmm, the reason I had `Value` return a `sql.NullString{}` was because I received the following errors when returning only `nil`.
`Value`:
```go
type MultiString []string
func (s MultiString) Value() (driver.Value, error) {
	if s == nil || len(s) == 0 {
		return nil, nil
	}
	return strings.Join(s, ","), nil
}
```
Error output:
```
[error] unsupported data type: &[]
[error] failed to parse value &main.Person{ID:0, Name:"", Kids:(*main.MultiString)(nil)}, got error unsupported data type: &[]
[error] unsupported data type: &[]
[error] unsupported data type: &[]
[error] failed to parse value &main.Person{ID:0, Name:"", Kids:(*main.MultiString)(nil)}, got error unsupported data type: &[]
[error] unsupported data type: &[]
```
