### ISSUE TITLE
db.Scan method question

### ISSUE THREAD

**Issue by caelansar** [go-gorm/gorm#3522]
## Your Question

I found in [this commit]( https://github.com/gogorm/gorm/commit/dbaa6b0ec3f451903c2983fd091c52e5efc60669) the implementation of `db.Scan` has changed, now(v1.20.1) it use **row** processor to execute instead of **query** processor which breaks previous behaviors of `db.Scan` method. I try to add a callback after row, it likes `db.Callback().Row().After("gorm:row").Register("decrypt_data", decryptData)`  but since the `dest` is explicitly specified after call `db.ScanRows` method in `db.Scan`, how can I do some extra work after query(such as decrypt sensitive data)?

**Comment by jinzhu** [comment]
Hello,

Yes, the `Scan` methods should not call `Hooks` methods, so I made the change, it doesn't make sense to have another methods to works exactly like `Find`, any reason that don't use `Find`?

**Comment by caelansar** [comment]
> Hello,
> 
> Yes, the `Scan` methods should not call `Hooks` methods, so I made the change, it doesn't make sense to have another methods to works exactly like `Find`, any reason that don't use `Find`?

No, just want to get a confirmation. I will replace `Scan` method in my legacy code with `Find` method. Thank you for your prompt reply.
