### ISSUE TITLE
cannot parse mysql timestamp type

### ISSUE THREAD

**Issue by latteczy** [go-gorm/gorm#3523]
## Your Question

I try to create a mysql client according to the document. And I have set `parseTime=True` in dsn.  
 
```go
type Cluster struct {
     Id string `gorm:"id"`
     CreateTime time.Time `gorm:"createTime"`
}

dataSourceName := fmt.Sprintf("%s:%s@tcp(%s:%s)/dbname?charset=utf8&parseTime=True", xx ,xx xxx, xxx)
db, err := gorm.Open(mysql.Open(dataSourceName), &gorm.Config{})

var clusters []Cluster
err = db.Table("table").Select("id, createTime").Scan(&clusters).Error
fmt.Println("clusters", clusters)
fmt.Println(err)      // return err is nil
```
The output is 
```
clusters {0c5768e5-6a2f-4676-ace4-89649457e70e 0001-01-01 00:00:00 +0000 UTC}
<nil>
```
The `CreateTime` is always`0001-01-01 00:00:00 +0000 UTC` which is not I expected. I got what I expected when I switched to use `database/sql` instead of `gorm`.
So is there something wrong in my configuration? 
Thanks for your help.

**Comment by latteczy** [comment]
I have added the `Expected answer` in issue.  Do I miss something else ?
@jinzhu

**Comment by jinzhu** [comment]
> I have added the `Expected answer` in issue. Do I miss something else ?
> @jinzhu

it works for me, if you believe there is a bug, please create a PR on playground.
