### ISSUE TITLE
我发现2.0版本太多bug了，expected 4 arguments, got 6

### ISSUE THREAD

**Issue by 599259501** [go-gorm/gorm#3527]
![image](https://user-images.githubusercontent.com/10400768/94239320-3200e580-ff44-11ea-9691-29dc8bd7e480.png)

**Comment by 599259501** [comment]
@name 也会包这个错误

**Comment by jinzhu** [comment]
read the document!

https://gorm.io/docs/v2_release_note.html#Method-Chain-Safety-Goroutine-Safety

**Comment by 599259501** [comment]
我这个没有多个协程在处理呢
