### ISSUE TITLE
Specify custom table name in one to one relation

### ISSUE THREAD

**Issue by adrien3d** [go-gorm/gorm#3529]
I have 2 tables, each one of them containing a reference to the other one (with a one-to-one relationship):

```
type Engine struct {
    ID int64 `json:"id"`
    CarID int64 `json:"car_id"`
    .....
}

type Car struct {
    ID int64 `json:"id"`
    EngineID Engine `json:"engine_id"` 
    .....
}
```

In my PostgreSQL database, I have the following tables and fields:
```
map_engine (table name)
id, car_id
```
```
map_car (table name)
id, engine_id
```

However, when I want to retrieve a list of cars with their engines, gorm tries to look in the `engines` table, and not in the `map_engine` table.

I am currently doing this:
```db.Table("map_car").Preload(clause.Associations).Where("id > 1950").Order("id desc").Find(&cars)```

How can I specify the table name for the second model?

**Comment by luisgomez29** [comment]
@adrien3d  You can set the table name as:

```go
type Engine struct {
	ID    int64 `json:"id"`
	CarID int64 `json:"car_id"`
}

func (Engine) TableName() string {
	return "map_engine "
}

type Car struct {
	ID       int64  `json:"id"`
	EngineID Engine `json:"engine_id"`
}

func (Car) TableName() string {
	return "map_car"
}
```
So your query would be:
```go
db.Preload(clause.Associations).Where("id > 1950").Order("id desc").Find(&cars)

// With debug to see the SQL script in the console
db.Debug().Preload(clause.Associations).Where("id > 1950").Order("id desc").Find(&cars)
```

More information in the link: https://stackoverflow.com/questions/57645143/golang-orm-name-of-table

**Comment by adrien3d** [comment]
Thank you very much @luisgomez29 works like a charm!
