### ISSUE TITLE
DO NOT use SELECT * in SQL queries

### ISSUE THREAD

**Issue by luisgomez29** [go-gorm/gorm#3530]
## Describe the feature

Hi, I have been going through the documentation at https://gorm.io/docs/query.html and found that the queries use SELECT * which is bad practice.

```go
// Get the first record ordered by primary key
db.First (& user)
// SELECT * FROM users ORDER BY id LIMIT 1;
```

Assuming we have a user struct with the following fields:

```go
type User struct {
	ID        uint32    `gorm:"type:serial;primaryKey;auto_increment" json:"id"`
	Username string    `gorm:"not null;size:60;unique" json:"username"`
	Email     string    `gorm:"not null;size:60;unique" json:"email"`
}
```
The above should run a query:

`SELECT "user"."id", "user"."username", "user"."email" FROM "users" AS "user" ORDER BY "user"."id" LIMIT 1;`

## Motivation
We should not use SELECT * in the SQL query anymore. It's always better to use the explicit column list in the SELECT query than a * wildcard. It not only improves the performance but also makes your code more explicit.

**Comment by jinzhu** [comment]
https://gorm.io/docs/advanced_query.html#Smart-Select-Fields
