### ISSUE TITLE
How can i query with gorm and cursor?

### ISSUE THREAD

**Issue by snowdream** [go-gorm/gorm#3531]
## Your Question

How can i query with gorm and cursor?

I mean, I can find with cursor, but not page, limit or offset.

## The document you expected this should be explained

https://github.com/pilagod/gorm-cursor-paginator

## Expected answer

 query with gorm and cursor

**Comment by jinzhu** [comment]
Use the plugin or use `Limit` / `Offset`, both should works and I don't think new API is necessary.

**Comment by jinzhu** [comment]
also refer https://gorm.io/docs/scopes.html#Pagination
