### ISSUE TITLE
use ipv4 as table name in mysql

### ISSUE THREAD

**Issue by kiyonlin** [go-gorm/gorm#3534]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/155

## Description

We now have such a requirement to use ipv4 as the table name, and each table stores this ipv4's information.

Use such SQL statements when querying.
```sql
select * from `ip_db`.`1.1.1.1` limit 0,1000
```

When quoting the table name, the [current processing logic](https://github.com/go-gorm/mysql/blob/master/mysql.go#L167-L181) is to separat it by dots, and each substring is wrapped with a pair of \`\`.

```
1.1.1.1     => `1`.`1`.`1`.`1`
`1.1.1.1`   => ``1`.`1`.`1`.`1``
```

Can we improve the quote processing logic so that the table names that have been used ``are not processed again?

```
1.1.1.1     => `1`.`1`.`1`.`1`
`1.1.1.1`   => `1.1.1.1`
```

**Comment by jinzhu** [comment]
Hi, 

I would suggest write a wrapper to the existing driver, and rewrite the `QuoteTo` methods to do the job. GORM itself won't make the support, thank you.
