### ISSUE TITLE
Can not add primary key

### ISSUE THREAD

**Issue by 00LT00** [go-gorm/gorm#3537]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

My previous struct is :
```go
type Rule struct {
	PType string `gorm:"size:40;uniqueIndex:unique_index"`
	V0    string `gorm:"size:40;uniqueIndex:unique_index"`
	V1    string `gorm:"size:40;uniqueIndex:unique_index"`
}
```
Now, I add primary key for this table like this:
```go
type Rule struct {
	ID    uint
	PType string `gorm:"size:40;uniqueIndex:unique_index"`
	V0    string `gorm:"size:40;uniqueIndex:unique_index"`
	V1    string `gorm:"size:40;uniqueIndex:unique_index"`
}
```
I get a error
```
Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key
```
But my table doesn't have auto column
![image](https://user-images.githubusercontent.com/47566260/94346980-fc065300-0062-11eb-9464-af5ef13cd327.png)
Maybe it was error of Mysql?

**Comment by luisgomez29** [comment]
@00LT00 You can try adding the primaryKey tag:
```go
type Rule struct {
	ID    uint   `gorm:"primaryKey;autoIncrement"`
	PType string `gorm:"size:40;uniqueIndex:unique_index"`
	V0    string `gorm:"size:40;uniqueIndex:unique_index"`
	V1    string `gorm:"size:40;uniqueIndex:unique_index"`
}
```
You can check the tags at https://gorm.io/docs/models.html#Fields-Tags

**Comment by 00LT00** [comment]
@luisgomez29  It's the same error. I know tags. But the `ID unit` is set as the primary key by default. So I think this is not reason for tags.
