### ISSUE TITLE
Why is the string type automatically quoted

### ISSUE THREAD

**Issue by liov** [go-gorm/gorm#3538]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/156

## Description

```go
CreatedAt    string     `gorm:"type:datetime;default:CURRENT_TIMESTAMP"`
```
```go
escaper = ""
case string:
	vars[idx] = escaper + strings.Replace(v, escaper, "\\"+escaper, -1) + escaper
```
I think this is not an uncommon way of writing, but the generated sql will report an error because CURRENT_TIMESTAMP has more quotation marks

**Comment by jinzhu** [comment]
```go
CreatedAt    string     `gorm:"type:datetime;default:CURRENT_TIMESTAMP()"`
```

**Comment by liov** [comment]
> ```go
> CreatedAt    string     `gorm:"type:datetime;default:CURRENT_TIMESTAMP()"`
> ```

还有，mysql datetime默认值可以是0的，default:0也会报错

**Comment by jinzhu** [comment]
最新版本 mysql 的console里直接跑 default 值也用不了0
