### ISSUE TITLE
Can't connect to posgres db

### ISSUE THREAD

**Issue by lethienhoang** [go-gorm/gorm#3539]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
`import (
	"log"
	"my-portfolio-api/config"
	"my-portfolio-api/models"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)`

`db, err := gorm.Open(postgres.New(postgres.Config{
		DSN:        config.DBURL,
		DriverName: config.DBDRIVER,
	}), &gorm.Config{})`

I'm still getting the error "sql: unknown driver \"postgres\" (forgotten import?)". I'm getting error. How to fix it?

**Comment by lethienhoang** [comment]
DBURL = fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable", host, port, user, password, dbname)

**Comment by luisgomez29** [comment]
@lethienhoang You can comment out the DriverName line as you are going to use Gorm's postgres driver:
```go
db, err := gorm.Open(postgres.New(postgres.Config{
		DSN:        config.DBURL,
		//DriverName: "postgres",
	}), &gorm.Config{})
```

Another connection option:
```go
func Connect() *gorm.DB {
	db, err := gorm.Open(postgres.Open(config.DBURL), &gorm.Config{})

	if err != nil {
		log.Fatal(err)
	}
	return db
}
```
https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL

**Comment by leenux** [comment]
same issue,why auto closed by bot?
