### ISSUE TITLE
Postres - Create returns incorrect primary key

### ISSUE THREAD

**Issue by rubensbarreto** [go-gorm/gorm#3541]
Good evening,

In postgres our columns are all CamelCase, therefore we have modeled the type as it follows:

type MonCicloHistorico struct {
	gorm.Model
	ID                  uint      `gorm:"primaryKey;column:ID;autoIncrement"`
	IDCiclo             uint      `gorm:"column:IDCiclo"`
	IDVariavel          uint      `gorm:"column:IDVariavel"`
	IDLocal             uint      `gorm:"column:IDLocal"`
	CodigoPaciente      string    `gorm:"column:CodigoPaciente"`
	CodigoAtendimento   string    `gorm:"column:CodigoAtendimento"`
	CodigoPedidoImg     string    `gorm:"column:CodigoPedidoImg"`
	CodigoItemPedidoImg string    `gorm:"column:CodigoItemPedidoImg"`
	Valor               uint      `gorm:"column:Valor"`
	CriadoEm            time.Time `gorm:"column:CriadoEm"`
	CriadoPor           uint      `gorm:"column:CriadoPor;default:1"`
	AlteradoEm          time.Time `gorm:"column:AlteradoEm"`
	AlteradoPor         uint      `gorm:"column:AlteradoPor;default:1"`
}

type Tabler interface {
	TableName() string
}

// TableName overrides the table name used by User to `profiles`
func (MonCicloHistorico) TableName() string {
	return "sdn_mon_ciclo_historico"
}

As noted, the primary key is uppercase ID, modeled as primary Key with the column defined.

The create statement fails, because it tries to return id instead of ID:
ERROR: column "id" does not exist (SQLSTATE 42703)
[0.119ms] [rows:0] INSERT INTO "sdn_mon_ciclo_historico" ("created_at","updated_at","deleted_at","ID","IDCiclo","IDVariavel","IDLocal","CodigoPaciente","CodigoAtendimento","CodigoPedidoImg","CodigoItemPedidoImg","Valor","CriadoEm","AlteradoEm","CriadoPor","AlteradoPor") VALUES ('2020-09-27 18:52:18.359','2020-09-27 18:52:18.359',NULL,0,1,6,1,'HSL 288600','HSL 3112821','HSL 1186666','HSL 1502055',2754,'2020-09-27 18:52:18.359','0000-00-00 00:00:00',1,1) RETURNING "id"

The code should try to return ID, which is the primary key column name.

**Comment by rubensbarreto** [comment]
When running batch create, the behavior gets even stranger, for example:

dbCommandCenter.Model(&MonCicloHistorico{}).Create([]map[string]interface{}{
			{
				"IDCiclo":             1,
				"IDVariavel":          6,
				"IDLocal":             1,
				"CodigoPaciente":      fmt.Sprint("HSL ", codigoPaciente),
				"CodigoAtendimento":   fmt.Sprint("HSL ", codigoAtendimento),
				"CodigoPedidoImg":     fmt.Sprint("HSL ", codigoPedido),
				"CodigoItemPedidoImg": fmt.Sprint("HSL ", codigoItemPedido),
				"Valor":               minutosAguardando,
				"CriadoEm":            time.Now(),
				"AlteradoEm":          time.Now(),
			},
		})

generates:

ERROR: column "id" does not exist (SQLSTATE 42703)
[0.096ms] [rows:0] INSERT INTO "sdn_mon_ciclo_historico" ("AlteradoEm","CodigoAtendimento","CodigoItemPedidoImg","CodigoPaciente","CodigoPedidoImg","CriadoEm","IDCiclo","IDLocal","IDVariavel","Valor") VALUES ('2020-09-27 19:29:34.771','HSL 3106127','HSL 1501660','HSL 106337','HSL 1186339','2020-09-27 19:29:34.771',1,1,6,4533) RETURNING "id","ID"

It tries to return both id and ID, and it fails since id doesnt exist

**Comment by rezaxd** [comment]
Hello @ratanphayade !
I kinda had a same issue. I could not change the returning field. I used field uid as pk and uuid of its type, but when I tried to insert into table, the query return id and cause error. I just left id be id and just changed its type from int to uuid.
U can handle this by writing query urself. I mean try using raw query in your code.

**Comment by n00el** [comment]
I have the same issue.
Primary key is an uuid, auto generated.
ID          uuid.UUID     `gorm:"type:varchar(191);default:(uuid());primary_key" json:"id"`

Create func returns an empty uuid: ID:00000000-0000-0000-0000-000000000000

**Comment by TN1ck** [comment]
The problem is the `gorm.Model`, it already defines the ID and you can't overwrite that. Just remove it and paste the fields directly into the model it would add:

```
CreatedAt   time.Time    `gorm:"autoCreateTime"`
UpdatedAt   time.Time    `gorm:"autoUpdateTime"`
DeletedAt   gorm.DeletedAt
```
