### ISSUE TITLE
logger 没有开debug，还是打印出sql语句，如何禁用？

### ISSUE THREAD

**Issue by rickiey** [go-gorm/gorm#3544]
![image](https://user-images.githubusercontent.com/34705031/94403398-f2363a00-019f-11eb-9cde-983bcb27d278.png)

**Comment by DogBaoBao** [comment]
you can config Logger when gorm.Open

**Comment by ShangguanHong** [comment]
因为当你没有开启debug模式的时候，gorm底层默认的log级别是Warn，当你的SQL语句执行时间超过了100ms的时候就会触发Warn日志打印，同时错误的SQL语句也会触发。
如果你想要在没有开启debug的时候什么语句也不要打印，那么可以像下面这样设置

db.Logger = logger.Default.LogMode(logger.Silent)

这条语句可以把默认的logger日志级别设置为silent，也就是最低级，GORM无论如何都不会打印出日志了。
