### ISSUE TITLE
How to print SQL when auto migration?

### ISSUE THREAD

**Issue by yufeiminds** [go-gorm/gorm#3545]
## Your Question

When I plan to execute auto migration, we should review the SQL will be executed, how can I do it?

eg. print SQL? execute a dry-run with logging?

## The document you expected this should be explained

https://gorm.io/docs/migration.html

**Comment by jinzhu** [comment]
Hi, this is not possible right now, `DryRun` mode doesn't works with the `AutoMigrate` as it doesn't fetch database information and can't make the upgrade plan

**Comment by yufeiminds** [comment]
Okay, thanks for your reply so quickly. 👍

**Comment by malisper** [comment]
@jinzhu What is the recommended way to make sure a migration will do what I expect it to? I don't want to accidentally run a migration that creates a bunch of tables and indexes that I didn't mean to.
