### ISSUE TITLE
Add a new type of error

### ISSUE THREAD

**Issue by dnlsgv** [go-gorm/gorm#3547]
## Describe the feature

Hi, Sometimes it could be the case of consulting a table that does not exist yet, and the error that gorm would throw would be something like:

```(Error 1146: Table 'database.table' doesn't exist)```

But in the "list" of errors (https://github.com/go-gorm/gorm/blob/master/errors.go) that error does not appear in specific.

It would be great to be able to catch that error like this:

```golang
if err == gorm. ErrRecordNotFound {
//...
//...
}
```
maybe ```gorm.ErrTableNotFound```

or in some similar way

Thank you.

**Comment by jinzhu** [comment]
GORM itself won't parse the those kind of error, but it is ok to add it to driver. refer https://github.com/go-gorm/gorm/pull/3512
