### ISSUE TITLE
How to set the collation of a column?

### ISSUE THREAD

**Issue by raiRaiyan** [go-gorm/gorm#3548]
### How do I set the collation value of a column when migrating? 

The only reference i found in the documentation is about the index collation and not column collation. 

I found another referenece for gorm collation, but this is for an older version: https://stackoverflow.com/questions/29087167/how-can-i-set-collation-of-a-field-to-utf8-general-ci-with-gorm

**Comment by jinzhu** [comment]
This should works.

```go
type User struct {
    gorm.Model
    Name `gorm:"type:VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_general_ci"`
}
```

**Comment by raiRaiyan** [comment]
Thanks. That works.

But changing the type does not trigger auto migrate. I have to explicitly call alter column to change the column type. Is this expected ?
