### ISSUE TITLE
日志打印的执行语句可以执行， 但是会报错

### ISSUE THREAD

**Issue by lqu3j** [go-gorm/gorm#3549]
代码大致如下：
`	
        a := float64(1)
	demo := Demo{}
	if err := db.Where("id = ?", a).Find(&demo); err != nil {
		t.Fatal(err)
	}
`

日志打印的SQL语句如下：
`
SELECT * FROM "demos" WHERE id = 1.000000 AND "demos"."deleted_at" IS NULL
`

报错信息: **cannot convert 1 to Int4**

原因： **https://github.com/jackc/pgtype 不支持类型float64->Int4的转换**

麻烦问一下这个是预料当中的，还是BUG？

**Comment by jinzhu** [comment]
I think this as an issue of pgtype, maybe open an issue there.

Thank you.
