### ISSUE TITLE
使用Raw SQL带@占位符查询的时候，字符串的引号是双引号

### ISSUE THREAD

**Issue by cooppor** [go-gorm/gorm#3551]
## Your Question
见谅，英文水平一般，读基本没问题，表达不了。
使用Raw SQL带@占位符查询的时候，字符串的引号是双引号，就拿MySQL来说，如果是
```
select * from test where stat_date=@stat_date
```
传入的查询参数`stat_date`值是`20200929`是字符类型时，gorm现在1.20.2版本翻译完的sql会是
```
select * from test where stat_date="20200929"
```
同样的程序到兼容MySQL协议的国产数据库Gbase下，翻译后的sql 就执行失败，会把这个`"20200929"`当做是一个字段来处理，会报`1051 Unknown column '20200929' in 'where clause'`。

## Expected answer

如果这个字符串类型值在翻译代入的时候能翻译成`'20200929'`，会不会更好，兼容性会更强或者更通行一些呢。
希望可以考虑一下，再一次感谢你及gorm这么好的库，谢谢。

**Comment by jinzhu** [comment]
处理了下，更新下 mysql driver 应该就可以了

**Comment by cooppor** [comment]
> 处理了下，更新下 mysql driver 应该就可以了

可以了，非常感谢！！！
