### ISSUE TITLE
软删除gorm.DeletedAt可以自定义为时间戳吗

### ISSUE THREAD

**Issue by lanfeng6** [go-gorm/gorm#3552]
现在的gorm.DeletedAt在查询时生成语句为：``deletd_at` IS NULL`
可以考虑加入兼容自定义时间戳设置吗，将语句改为``deleted` = 0`

**Comment by jinzhu** [comment]
自己按照 soft delete 的实现来实现一下吧，GORM 默认不会改成这样子
