### ISSUE TITLE
gorm distinct bug ?

### ISSUE THREAD

**Issue by wuqinqiang** [go-gorm/gorm#3554]
What version of Go are you using (go version)?
go 1.14

What version of Go are you using (gorm version)?
v1.9.16

Which database and its version are you using?
Mysql 5.7

`if err := dao.bundleDb.Db.Model(&wpt_shop.ShopOrder{}).
		Select("distinct(winUserinfoId),userinfoId").
		Where("userinfoId=?", userInfoId).
		Limit(limit).
		Offset(offset).
		Pluck("winUserinfoId", &userIds).Error; err != nil {
	}
	
	logger.Infof("get userIds is:%v",userIds)
	return userIds`

and get userIds is 

<img width="1319" alt="截屏2020-09-30下午4 47 49" src="https://user-images.githubusercontent.com/36129334/94664003-ef248080-033c-11eb-9f95-9cb3b08c4714.png">

why not return 
`[41,8615787]`

**Comment by jinzhu** [comment]
`Pluck("distinct(winUserinfoId)", &userIds)`
