### ISSUE TITLE
How to update associations?

### ISSUE THREAD

**Issue by resotto** [go-gorm/gorm#3559]
## Your Question

There are following model:
```go
type User struct {
  gorm.Model
  CreditCard CreditCard
}

type CreditCard struct {
  gorm.Model
  Number string
  UserID uint
}
```

When I want to update `CreaditCard` info, which has been changed, via User, how do I update them?

**Comment by jinzhu** [comment]
`FullSaveAssociations` mode

https://gorm.io/docs/associations.html#Auto-Create-Update
