### ISSUE TITLE
Is it possible to insert null instead of 0 for nullable foreign keys?

### ISSUE THREAD

**Issue by andrei-dascalu** [go-gorm/gorm#3561]
## Your Question

Hello,

I am wondering if there's a way to make a relationship optional. In mySQL (at least) for example, a field can be an FK but if nullable, then the relationship exists only when the key references a real ID (so, for example, I can insert a NULL there).

In gorm, however, an ID is an uint and if I don't specify its value, gorm tries to insert 0 in a nullable field that's also an FK instead of NULL value.

Is there a way to insert NULL instead of 0 for an uint field?

## Expected answer

I'm wondering if there are some annotations that can help with this (I wasn't able to find any examples in the docs)

Thanks!

**Comment by jinzhu** [comment]
use sql.NullInt64
