### ISSUE TITLE
why when implementing the belongsTo relation returns an associated model value just by doing a find?

### ISSUE THREAD

**Issue by juan55860** [go-gorm/gorm#3569]
Hi guys

There are two structs (service belongs to request):

```go
package Models

type Service struct {
	Id int `json:"id"`
	DomainId int `json:"domain_id"`
	Address string `json:"address"`
	Hint string `json:"hint"`
	City string `json:"city"`
	Latitude float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	RequestId int `json:"request_id"`
	Request Request
}
```

and 

``` go
package Models

type Request struct {
	Id int `json:"id"`
	So string `json:"so"`
	UserEmail string `json:"user_email"`
	Lang string `json:"lang"`
}
```

Now, for the find method 
```go
var service Models.Service
db.Find(&service , 1)
```
the resulset is a service row, but using fiber 2.0.4 with Json method from fiber.Ctx returns this:

```
{
    "id": 1,
    "domain_id": 1,
    "address": "401 Biscayne Blvd",
    "hint": "Bayside Marketplace",
    "city": "Miami",
    "latitude": 25.778333,
    "longitude": -80.186771,
    "request_id": 1,
    "request": {
        "id": 0,
        "so": "",
        "user_email": "",
        "lang": ""
    }
}
```

## Expected answer

is there an output serializer or how can I solve this?

Thank you very much for the help 👍

**Comment by juan55860** [comment]
tested with github.com/jinzhu/gorm  and gorm.io/gorm in fiber 2.0.4 for both cases

**Comment by luisgomez29** [comment]
@juan55860 you can use Preload:
```go
var service Models.Service
db.Preload("Request ").Find(&service , 1)

// If you want to see the SQL query in the console
db.Debug().Preload("Request ").Find(&service , 1)
```

https://gorm.io/docs/preload.html

**Comment by juan55860** [comment]
Hi @luisgomez29, the info is OK, but i need to remove the empty values when use the find function,

By example, actually returns with this code 
```go
var service Models.Service
db.Find(&service , 1)
```

```
{
    "id": 1,
    "domain_id": 1,
    "address": "401 Biscayne Blvd",
    "hint": "Bayside Marketplace",
    "city": "Miami",
    "latitude": 25.778333,
    "longitude": -80.186771,
    "request_id": 1,
    "request": {
        "id": 0,
        "so": "",
        "user_email": "",
        "lang": ""
    }
}
```

I need:

```json
{
    "id": 1,
    "domain_id": 1,
    "address": "401 Biscayne Blvd",
    "hint": "Bayside Marketplace",
    "city": "Miami",
    "latitude": 25.778333,
    "longitude": -80.186771,
    "request_id": 1
}
```

**Comment by luisgomez29** [comment]
@juan55860  You have to define the request field as a pointer so it will be nil and can be omitted:
```go
type Request struct {
	Id        int    `json:"id"`
	So        string `json:"so"`
	UserEmail string `json:"user_email"`
	Lang      string `json:"lang"`
}

type Service struct {
	Id        int     `json:"id"`
	DomainId  int     `json:"domain_id"`
	Address   string  `json:"address"`
	Hint      string  `json:"hint"`
	City      string  `json:"city"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	RequestId int     `json:"request_id"`
	Request   *Request `json:"request,omitempty"` // The field is a pointer
}
```
I hope I have helped!

**Comment by juan55860** [comment]
> @juan55860 You have to define the request field as a pointer so it will be nil and can be omitted:
> 
> ```go
> type Request struct {
> 	Id        int    `json:"id"`
> 	So        string `json:"so"`
> 	UserEmail string `json:"user_email"`
> 	Lang      string `json:"lang"`
> }
> 
> type Service struct {
> 	Id        int     `json:"id"`
> 	DomainId  int     `json:"domain_id"`
> 	Address   string  `json:"address"`
> 	Hint      string  `json:"hint"`
> 	City      string  `json:"city"`
> 	Latitude  float64 `json:"latitude"`
> 	Longitude float64 `json:"longitude"`
> 	RequestId int     `json:"request_id"`
> 	Request   *Request `json:"request,omitempty"` // The field is a pointer
> }
> ```
> 
> I hope I have helped!

Thanks @luisgomez29 it works 👍
