### ISSUE TITLE
Updating relationships / associations

### ISSUE THREAD

**Issue by fwielstra** [go-gorm/gorm#3573]
## Your Question

How do I properly update one-to-many relationships? I feel like I'm missing something.

I'm trying to update a relationship, but I can't seem to get it to work.
I expect that calling `db.Save(&myModel)` will insert OR update the model with all of its relationships; existing relationships (with IDs) get updated, removed ones will be removed, new relationships (without IDs) are inserted.

There is some documentation on updating relationships / associations, but these too do not seem to work (or I do not understand them)

Example code: https://play.golang.org/p/HaHzG3_mU9X

## The document you expected this should be explained

https://gorm.io/docs/update.html
https://gorm.io/docs/associations.html#Replace-Associations

## Expected answer

I want gorm to be smart enough to update relationships on `Save()`, or for documentation to be more clear about this.

**Comment by fwielstra** [comment]
After some digging, it turns out this issue was resolved in the latest version: fixed in c0de3c505176b0fea74c2e09fb9cae7c595b7020, see also #3487, #3506.

I found the solution in the tests, which seem to explain things better than the official docs: https://github.com/go-gorm/gorm/blob/master/tests/update_has_many_test.go

My working example: https://play.golang.org/p/VX0dVnvBcrb

**Comment by mnrce** [comment]
> After some digging, it turns out this issue was resolved in the latest version: fixed in [c0de3c5](https://github.com/go-gorm/gorm/commit/c0de3c505176b0fea74c2e09fb9cae7c595b7020), see also #3487, #3506.
> 
> I found the solution in the tests, which seem to explain things better than the official docs: https://github.com/go-gorm/gorm/blob/master/tests/update_has_many_test.go
> 
> My working example: https://play.golang.org/p/VX0dVnvBcrb

@fwielstra 
I just tested your example, and add a new case to remove existing relationship and add a new one (something like this: `queriedFlow2.Steps[1] = Step{Value: "This ID should be 3"}`)

It looks like `gorm` insert a new `Step` with id `3`, but it doesn't remove the `Step` with id `2`.
How do I make `gorm` to also remove the relationships that's not in the `Steps` slice?
