### ISSUE TITLE
Remove many-to-many relationships via Save

### ISSUE THREAD

**Issue by fwielstra** [go-gorm/gorm#3575]
## Your Question

Using `FullSaveAssociations`, I can save and append to my associations fairly easily.

However, when removing associations, using `Save()` it seems like existing associations are not removed; I would expect this to be the case.

Example: https://play.golang.org/p/A3BAGsKVKv0

## The document you expected this should be explained

https://github.com/go-gorm/gorm/blob/master/tests/associations_many2many_test.go

## Expected answer

for `.Save()` to remove / unlink associations

**Comment by jinzhu** [comment]
We won't support this case, use the `Replace` method in `Associations` mode
