### ISSUE TITLE
Select not working as expected 

### ISSUE THREAD

**Issue by loeffel-io** [go-gorm/gorm#3576]
## Your Question

I want to delete some associations with select: 

```go
func (database *Database) DeleteTeam(connection *gorm.DB, team *makeless_go_model.Team) error {
	return connection.
		Unscoped().
		Select("TeamUsers", "TeamInvitations").
		Delete(team).
		Error
}
```

## The document you expected this should be explained

https://gorm.io/docs/associations.html#Delete-with-Select

## Expected answer

As i understand, all team users and team invitations from team A should be deleted
Current message: `Error 1451: Cannot delete or update a parent row: a foreign key constraint fails (`makeless-test`.`team_invitations`, CONSTRAINT `fk_team_invitations_team` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`))`

Is select not working like this? Thanks!

**Comment by loeffel-io** [comment]
path to models: https://github.com/makeless/makeless-go/tree/feature/lucas/gorm/model

**Comment by jinzhu** [comment]
TeamInvitations is not using soft delete, but the team is using soft delete? the deletion failed to pass the database constraint check.

**Comment by loeffel-io** [comment]
> TeamInvitations is not using soft delete, but the team is using soft delete?

Both of them using the Model (soft delete) ..

**Comment by loeffel-io** [comment]
Everything works as expected! Thanks <3
