### ISSUE TITLE
Errors when custom Valuer returns nil

### ISSUE THREAD

**Issue by Robbie-Perry** [go-gorm/gorm#3577]
## Your Question

I have the following type called `MultiString`, which has a custom `Scanner`/`Valuer` to convert to/from a comma separated string (or nil if empty):

```go
type MultiString []string

func (s *MultiString) Scan(src interface{}) error {
	str, ok := src.(string)
	if !ok {
		return errors.New("failed to scan multistring field - source is not a string")
	}
	*s = strings.Split(str, ",")
	return nil
}

func (s MultiString) Value() (driver.Value, error) {
	if s == nil || len(s) == 0 {
		var nilString *string
		return nilString, nil
	}
	return strings.Join(s, ","), nil
}

// Model
type Person struct {
	ID      int
	Name    string
	Kids	*MultiString
}
```

When I try and call `db.AutoMigrate(&Person{})`, I get the follwoing error output:

```
[error] unsupported data type: &[]
[error] failed to parse value &main.Person{ID:0, Name:"", Kids:(*main.MultiString)(nil)}, got error unsupported data type: &[]
[error] unsupported data type: &[]
[error] unsupported data type: &[]
[error] failed to parse value &main.Person{ID:0, Name:"", Kids:(*main.MultiString)(nil)}, got error unsupported data type: &[]
[error] unsupported data type: &[]
```

## Expected answer

Am I doing something wrong here, or is this a bug?

**Comment by luisgomez29** [comment]
@Robbie-Perry You have to specify the data type for the column, so your model looks like this:
```go
// Model
type Person struct {
	ID      int
	Name    string
	Kids	*MultiString `gorm:"type:text[]"`
}
```

**Comment by Robbie-Perry** [comment]
> @Robbie-Perry You have to specify the data type for the column, so your model looks like this:
> 
> ```go
> // Model
> type Person struct {
> 	ID      int
> 	Name    string
> 	Kids	*MultiString `gorm:"type:text[]"`
> }
> ```

Actually I needed `gorm:"type:text"` as I want the slice to be stored as a single string, but yes, the issue was that I was missing the explicit type declaration. Thanks!
