### ISSUE TITLE
Joins does not working

### ISSUE THREAD

**Issue by AlexandrMoshnyatsckyj** [go-gorm/gorm#3580]
I have
`tx.Preload("File.Stuff").Group("file, created").Select("file, created").Order("created")`
But when i try `tx.Joins("File").Group("file, created").Select("file, created").Order("created")` and i not getting file.
How i can do `tx.Preload("File.Stuff").Group("file, created").Select("file, created").Order("created")` with Joins? Thanks.

**Comment by subanmiao** [comment]
最新版本 joins 配合 select 选择特定字段有问题，麻烦 @jinzhu 看看。
