### ISSUE TITLE
Incorrect quotes breaking Hstore custom type

### ISSUE THREAD

**Issue by JakeHillion2** [go-gorm/gorm#3583]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/167

## Description

Using the hstore type in Postgres is causing issues as it's a custom data type that isn't represented as a string. GORM is adding quotes, which causes Postgres to error. I have been unable to find a workaround for this issue.

Note that this worked in GORM 1.

**Comment by jinzhu** [comment]
Hello,

We switched to https://github.com/jackc/pgx as the default postgres driver, and it doesn't support the `pg.Hstore`, you can checkout the pgx version hstore or use the pg as the postgres driver.

Thank you.
