### ISSUE TITLE
Peer authentication failed for user

### ISSUE THREAD

**Issue by Thor-x86** [go-gorm/gorm#3584]
The current workaround is modifying `pg_hba.conf` as instructed on [this answer](https://stackoverflow.com/questions/18664074/getting-error-peer-authentication-failed-for-user-postgres-when-trying-to-ge). However, in some conditions that is impossible to do. Is there any configuration to force PostgreSQL driver using peer authentication (or UNIX Socket) instead of MD5? Thank you!

**Comment by jinzhu** [comment]
checkout postgres driver pgx supported DSN
