### ISSUE TITLE
ERROR: no schema has been selected to create in (SQLSTATE 3F000)

### ISSUE THREAD

**Issue by Ascendance** [go-gorm/gorm#3586]
Hi. I am facing an extremely furstrating and issue with the 2.0 version of gorm, namely the inability or the lack of docs to explain how to set the search_path when working with postgres databases. 

I have tried: 

```
&gorm.Config{
	NamingStrategy: schema.NamingStrategy{TablePrefix: "hello."},
}
```
when setting up `gorm.Open`. No luck. 

I have tried `ALTER ROLE postgres SET search_path TO name;` on postgres' end. No luck. The schema exists in postgres and pgadmin works just fine. But whenever I tried connecting via gorm, I get: 

`ERROR: no schema has been selected to create in (SQLSTATE 3F000)` with the automigrator:

```
tx.Exec(fmt.Sprintf("SET search_path TO %s", "hello"))
if !tx.Migrator().HasTable(&Users{}) {
	err = tx.Migrator().CreateTable(&Users{})
}
```

I have tried setting `search_path` in the DSN. No luck. 

I have tried just about everything else with no luck. 

Question: Please help me find a reliable way (or docs) to set the schema with gorm 2.0. Thanks. 

Reproduction Steps: 

1. Bring up postgres i.e. `bitnami/postgresql:latest`
2. `docker exec $target /bin/sh -c "export PGPASSWORD=postgres; psql -U postgres -d hello -c 'CREATE SCHEMA hello'"`
3. Try connecting to hello schema via gorm with automigrator.
4. Doesn't work.

**Comment by jinzhu** [comment]
Would you mind to create a reproducible pull request on playground https://github.com/go-gorm/playground , the `TablePrefix` solution is expected to work.
