### ISSUE TITLE
interface{} nullity checks are wrong throughout the project

### ISSUE THREAD

**Issue by AdallomRoy** [go-gorm/gorm#3591]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

See - https://medium.com/@mangatmodi/go-check-nil-interface-the-right-way-d142776edef1
Throughout the code, example: 
https://github.com/go-gorm/gorm/blob/063b1ca0c41740577655ff3b0c524bcbe587a54f/callbacks.go#L78

This causes many bugs, where the check is skipped.

**Comment by jinzhu** [comment]
GORM doesn't expect to accept those arguments and check them by slowing down normal usage, so better check it before use those value as arguments.
