### ISSUE TITLE
how can I retrieve instance of last added item by Exec query

### ISSUE THREAD

**Issue by optimus-su** [go-gorm/gorm#3600]
i have a table with 3 columns: id,c1,c2 . id field is primary key and auto increase. how i can get new id after insert new record?
when i excute this command db.Exec("insert into table(c1,c2)values('val1','val2')")
i do not want to use db.Save() because i have a query insert  dynamically.

**Comment by jinzhu** [comment]
sqlDB, _ := db.DB()
result, _ := sqlDB.Exec("...")
result.LastInsertID()
