### ISSUE TITLE
nil point transfer '<nil>' not transfer NULL 

### ISSUE THREAD

**Issue by blakejia** [go-gorm/gorm#3604]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/179

## Description

``` golang

type UserWithUUID struct {
	ID        uint `gorm:"primarykey"`
	CreatedAt time.Time
	UpdatedAt time.Time

	TestID     *uuid.UUID `gorm:"type:uuid"`
}

value := UserWithUUID{}

createErr := DB.Save(&value).Error

```

sql is 
``` bash
INSERT INTO "user_with_uuids" ("created_at","updated_at","test_id") VALUES ('2020-10-14 02:20:47.3','2020-10-14 02:20:47.3','<nil>') RETURNING "id"
```

```TestID``` nil point transfer ```<nil>```

**Comment by tebrizetayi** [comment]
I would like to take this issue to work on it!

**Comment by jinzhu** [comment]
> I would like to take this issue to work on it!

thank you, most likely it is a logger format issue.

**Comment by tebrizetayi** [comment]
What was expectation @blakejia ?

**Comment by blakejia** [comment]
> What was expectation @blakejia ?

sql is
``` sql
INSERT INTO "user_with_uuids" ("created_at","updated_at","test_id") VALUES ('2020-10-14 02:20:47.3','2020-10-14 02:20:47.3','<nil>') RETURNING "id"
```

this is should be
``` sql
INSERT INTO "user_with_uuids" ("created_at","updated_at","test_id") VALUES ('2020-10-14 02:20:47.3','2020-10-14 02:20:47.3', NULL) RETURNING "id"
```

**Comment by tebrizetayi** [comment]
if type is fmt.Stringer() and  fmt.Sprintf("%v", v) is used , it does not trigger the Stringer() function  of the object.That is why it gives '<nil>' not NULL as we wanted. The case fmt.Stringer is removed from the switch and pushed.
