### ISSUE TITLE
Mock object for testing

### ISSUE THREAD

**Issue by lichcse** [go-gorm/gorm#3608]
Hi team,
I just trying to apply v2 to my project but I cant mock objects like v1 for testing.

The block code below I using in v1.

`
"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"

	// mysql driver
	_ "github.com/go-sql-driver/mysql"

mockDB, mock, err := sqlmock.New()
	if err != nil {
		assert.Equal(t, "Error sqlmock", err.Error())
	}
	db, err := gorm.Open("mysql", mockDB)
	if err != nil {
		assert.Equal(t, "Error gorm init", err.Error())
	}
`

So how can I mock objects when I write unit tests?

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/issues/3565
