### ISSUE TITLE
Use `pq.Array` with `= ANY(?)` for Postgres preloading

### ISSUE THREAD

**Issue by svip** [go-gorm/gorm#3609]
## Describe the feature

Use `pq.Array({ids})` as parameter and `= ANY(?)` SQL syntax instead of `IN (?)` when preloading objects in Postgres.

## Motivation

If one has to preload too many elements, Postgres fails with the following for instance:
`pq: got 82000 parameters but PostgreSQL only supports 65535 parameters`

Additionally, parsing a lot of strings in `IN (...)` is very slow in Postgres, the `= ANY(...)` syntax is much faster, since `IN` can contain a SELECT-statement at any point, whereas `= ANY()` cannot.

It would be a specific enhancement for the Preloader when using Postgres.  I would gladly write the changes myself, if anyone can point me in the right direction.

**Comment by lifegit** [comment]
excuse  me, have you solved it?

**Comment by lifegit** [comment]
> 我最终编写了一个`Preload()`完全忽略 GORM 的预加载器。但它有点与我们自己的类型挂钩，而不是成为其他人的通用替代品。所以为了我自己的目的，我解决了这个问题，但是对于一个 GORM 问题，我没有解决它。

excuse me,Is it convenient for you to give an example？

**Comment by lifegit** [comment]
> I ended up writing a preloader that ignores GORM's `Preload()` entirely. But it's kind of hooked up to our own types rather than being a generic drop-in replacement for others. So for my own purposes, I solved the issue, but for a GORM issue, I did not solve it.

excuse me,Is it convenient for you to give an example？
