### ISSUE TITLE
How to set where condition in customized jointable?

### ISSUE THREAD

**Issue by minionsong** [go-gorm/gorm#3613]
## Your Question

for example, those are structs
```go
type Person struct {
  ID        int
  Name      string
  Addresses []Address `gorm:"many2many:person_addresses;"`
}

type Address struct {
  ID   uint
  Name string
}

type PersonAddress struct {
  PersonID  int
  AddressID int
  SomeField int  // I added to the example of docs.
  CreatedAt time.Time
  DeletedAt gorm.DeletedAt
}
```

Basically, I preloads Person's Addresses like this.
`db.Preload("Addresses").Find(&persons)`

But I want to add the condition such as 
```
SELECT * FROM `person_addresses` WHERE `person_addresses`.`some_field` = 1
or
SELECT * FROM `person_addresses` WHERE `person_addresses`.`created_at` BETWEEN '2000-01-01 00:00:00' AND '2000-01-08 00:00:00'
```

Is there any solution about this? Or should I use `Joins` function?

## The document you expected this should be explained

https://gorm.io/docs/many_to_many.html#Customize-JoinTable

**Comment by jinzhu** [comment]
not possible to add conditions to join table when preloading, maybe query matched `PersonAddress` first, then based on it query the `Addresses`
