### ISSUE TITLE
[sqlserver dialect] Duplicate key row error is skipped

### ISSUE THREAD

**Issue by palestamp** [go-gorm/gorm#3615]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/180

## Description

When using `sqlserver` dialect `Create` method silently fails on duplicate insert - no error returned. Expected result would be for Create method to return relevant error.

In the same time `Create` method works correctly for `postgres` dialect in the same situation.

**Comment by palestamp** [comment]
If I traced it correctly, there is a `rows.Err()` check is missing for this call https://github.com/go-gorm/sqlserver/blob/master/create.go#L118 after rows.Next() sections.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/sqlserver/blob/86e3f937aa20e6d4b7b37569a0e8f9c1bdc79e3b/create.go#L163

Added here. I have checked, the driver doesn't returns any errors in this case, so we can't fixed that ;(

Maybe should open an issue on the sqlserver driver side

Thank you for your report

**Comment by palestamp** [comment]
@jinzhu I debugged driver a bit, it does return an error the problem is it will return error via `rows.Err()` after `rows.Next()` is called at least once. I agree, conventionally it should be returned by `QueryContext` itself.

This can be easily fixed of in `Create` method if we will check `rows.Err()` value after calling `rows.Next()`, it is also recommended in the `database/sql.Rows` docs example.

**Comment by palestamp** [comment]
@jinzhu could you please reopen this issue? This bug is definitely in gorm sqlserver driver.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
