### ISSUE TITLE
rqlite support

### ISSUE THREAD

**Issue by mpe85** [go-gorm/gorm#3618]
## Describe the feature

Support for [rqlite](https://github.com/rqlite/rqlite) database

## Motivation

rqlite is a lightweight distriuted SQL database based upon SQLite. Would be quite nice to use this together with gorm.
There is a Go driver available for it: [gorqlite](https://github.com/rqlite/gorqlite)
Are there any plans to support it?

**Comment by jinzhu** [comment]
We are open to support any databases if anyone could open a pull request and maintain it

**Comment by tebrizetayi** [comment]
Can I take this issue?

**Comment by jinzhu** [comment]
> Can I take this issue, if there is no objection?

yes, that would be great.

**Comment by yxxhero** [comment]
any updates?

**Comment by eaglexiang** [comment]
https://github.com/goki/rqlite
is this helpful?
