### ISSUE TITLE
Begginer example?

### ISSUE THREAD

**Issue by juancer** [go-gorm/gorm#3619]
## Your Question

Hi, I'm starting with go, and I'm starting to use GORM V2. Could be possible to get any full example to connet to the database, get data from the table and iterate with the data in the same file? Right now, I'm trying to iterate with the data, but I only got errors everytime that I try to use options to create the iteration.

## The document you expected this should be explained

I'm looking over the documentation at https://gorm.io/docs/ but I couldn't find this kind of example. Also, in StackOverflow all the questions rigth now are about the v1 of GORM.

## Expected answer

If the answer is already published, please, let me know where I can find it, or, please, send my some example by this way.

Thank you so much!

**Comment by CraigChilds94** [comment]
@juancer 

I agree that maybe the docs should include a nice set of example use cases. One thing that might help you is taking a look at the go docs https://pkg.go.dev/gorm.io/gorm as this will give you a better idea of what the methods are returning, which in turn you could research how to use. 

When returning multiple items from the database you'll need to provide a slice, you can then iterate over this slice using the idiomatic way to do so in GoLang.

Here's some example code, assuming that you've already got the connection code sorted and a table called "users" with a column called "name":

```
type User struct {
  gorm.Model
  Name  string
}

var users = []User

result := db.Find(&users)

if (result.Error != nil) {
    panic()
}

for i := 0; i < len(users); i++ {
    user := users[i]
    fmt.Println(user.Name)
}
```

I hope this helps!

**Comment by jinzhu** [comment]
> I'm looking over the documentation at https://gorm.io/docs/ but I couldn't find this kind of example. Also, in StackOverflow all the questions rigth now are about the v1 of GORM.

There not much different when iterate with data with V2, you could use those examples and try to play them with gorm playground.
