### ISSUE TITLE
table prefix with many2many

### ISSUE THREAD

**Issue by ZeratulDev** [go-gorm/gorm#3625]
## Playground

on playground all goes fine, join table name as expected.

Problem when import into new project

https://gist.github.com/ZeratulDev/7835f29c3df1e747b26cd18f3c1bc750

## Description

Is this AutoMigrate issue? Or there another way mention many2many

**Table prefix** from **NamingStrategy**, not applied to 
> Models []Model \`gorm:"many2many:join_table_name"\`

`join_table_name` table will be created instead of `prefix_join_table_name`
 
## Note

switching to \`gorm:"many2many:ProjectGame"\` do naming with prefix

**Comment by jinzhu** [comment]
The latest master should fixed the issue.
