### ISSUE TITLE
Or() statement causes priority disorder

### ISSUE THREAD

**Issue by voe1999** [go-gorm/gorm#3627]
```
var friends []*models.Friend
if res := f.db().Debug().Model(&models.Friend{}).Where(&models.Friend{UserA: userID}).Or(models.Friend{UserB: userID}).Find(&friends); res.Error != nil {
	logger.Error(res.Error)
	return nil, queryErr
}
```
The code above executes the SQL as follows:
```
SELECT * FROM `friends` WHERE `friends`.`user_a` = 1 OR `friends`.`user_b` = 1 AND `friends`.`deleted_at` IS NULL
```
which obviously has priority issues. Although it could be easily avoided, IMO most use cases here are intended as "(XX OR XX) AND deleted_at IS NULL", otherwise the Or() API is less useful and will cause unintentional mistakes.

**Comment by jinzhu** [comment]
```sql
`friends`.`user_a` = 1 OR `friends`.`user_b` = 1 AND `friends`.`deleted_at` IS NULL
```

equals

```sql
(`friends`.`user_a` = 1 OR `friends`.`user_b` = 1) AND `friends`.`deleted_at` IS NULL
```

**Comment by voe1999** [comment]
> ```sql
> `friends`.`user_a` = 1 OR `friends`.`user_b` = 1 AND `friends`.`deleted_at` IS NULL
> ```
> 
> equals
> 
> ```sql
> (`friends`.`user_a` = 1 OR `friends`.`user_b` = 1) AND `friends`.`deleted_at` IS NULL
> ```

No, it does't.

**Comment by jinzhu** [comment]
Hi @voe1999 

Sorry for the issue, there was an issue when using soft delete with or conditions, just pushed a commit to fix the issue.

Thank you for your report.
