### ISSUE TITLE
Omit entire embedded struct fields

### ISSUE THREAD

**Issue by Pourqavam** [go-gorm/gorm#3632]
## Describe the feature

How omit or select **entire embedded struct** fields in a query (and prevent its **primaryKey (ID) returning**)?

The read write tags not work on the embedded struct.

**Comment by jinzhu** [comment]
need to set the read/write permission for each field's tag in the embedded struct.

**Comment by Pourqavam** [comment]
@jinzhu 
> need to set the read/write permission for each field's tag in the embedded struct.

Embedded struct used for other queries separately, it needs to be ignored only on embedding struct.
