### ISSUE TITLE
When use Pluck method with a struct slice, gorm can not fill the value into slice, but the slice struct element implemented sql.Scan

### ISSUE THREAD

**Issue by medivh-jay** [go-gorm/gorm#3633]
## Your Question

When use Pluck method with a struct slice, gorm can not fill the value into slice, but the slice struct element implemented sql.Scan 

## The document you expected this should be explained
Can you support this operation in later upgrades?

**Comment by jinzhu** [comment]
https://gorm.io/docs/advanced_query.html#Pluck

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/96532188-f09ef400-12bd-11eb-9fb1-476a769d5d80.png)

**Comment by jinzhu** [comment]
> When use Pluck method with a struct slice, gorm can not fill the value into slice, but the slice struct element implemented sql.Scan

Pluck need to scan each row to a struct and append it to the slice, it can't works with a scanner.
