### ISSUE TITLE
How to do in gorm like sql script `select * from table_name where func(column_name)=<the value you want>`

### ISSUE THREAD

**Issue by Xieyuschen** [go-gorm/gorm#3634]
I use a `aesGcm` algorithm to encrypt a user-email and store it in a table, but when I want to find all of rows where encrypted user-email, I found a trouble and stopped me to continue my application.
The most challenge is everytime the aesGcm gives a different output even with the same key and plaintext. That means I can't encrypt the plaintext-user-email and compare this result to which store in database. I must decrypt inside the database query because it's effective")
Assume that a plaintext which stands for a username is `Grillen` and in the database stores `1234567890`(this cipher just want to make my question more clear) in column `encrypted_name`. I can use `aesGcm` to decrypt `1234567890` but I can't encrypt `Grillen` again to get same cipher as `1234567890` because each time encryption gives a different output. My sql script may like this:`Select & from user_table where decrypt(encrypted_name)='Grillen'`

**Comment by jinzhu** [comment]
this link should help you

https://gorm.io/docs/data_types.html
