### ISSUE TITLE
Automagically add clauses for Company ID (multi tenancy models)

### ISSUE THREAD

**Issue by frederikhors** [go-gorm/gorm#3639]
In many `struct`s I have a `CompanyID` field.

Example:

```go
type Player struct {
  gorm.Model

  Name string
  
  CompanyID uint
  Company    Company
}
```

And I have a `Company` type like this:

```go
type Company struct {
  Name string
}
```

I would like to know if there is a way to automagically add a `Where` clause to my queries.

### Example

If I have this query

```go
var player Player
db.Where("name like ?", "fakeName").Find(&player)
```

that generates this:

```sql
SELECT * from players where name like 'fakeName'
```

it would be amazing to have something to detect if `Player` has `CompanyID` field on it and add a `Where` clause automatically which generates this:

```sql
SELECT * from players where (name like 'fakeName' AND company_id = 1)
```

Doing this manually to each query is error prone as you can imagine.

**Is there a way?**

What do you think about?

**Comment by frederikhors** [comment]
Please answer to this, @jinzhu.

**Comment by jinzhu** [comment]
You can write a callback to do the job, it doesn't make sense for GORM to do this automatically.

**Comment by gatspy** [comment]
you can use `db.WithContext`, pass `CompanyID` with context,  then write a callback work on `before_query`.
in BeforeQuery callback method, use `db.Statement.Context` get the `CompanyID` value.

### model callback
```golang
func (m *BaseModel) BeforeQuery(db *gorm.DB) error {
	tx := db.Session(&gorm.Session{})
	ctx := tx.Statement.Context
	itd := ctx.Value("CompanyID").(string)
	query := "company_id=?"
	if conds := tx.Statement.BuildCondition(query, itd); len(conds) > 0 {
		tx.Statement.AddClause(clause.Where{Exprs: conds})
	}
	return nil
}
```

### gorm callback

```golang
type IBeforeQuery interface {
	BeforeQuery(*gorm.DB) error
}

// BeforeQueryCallback 
func BeforeQueryCallback(db *gorm.DB) {
	tx := db.Session(&gorm.Session{})
	if db.Error == nil && db.Statement.Schema != nil {
	
		ibq := reflect.TypeOf((*IBeforeQuery)(nil)).Elem()
		vm := reflect.New(db.Statement.Schema.ModelType)
		if ok := vm.Type().Implements(ibq); ok {
			q := vm.Interface().(IBeforeQuery)
			q.BeforeQuery(tx)
		}
	}
}
```

### register callback

```golang
db.Callback().Query().Before("gorm:query").Register("td:before_query", callbacks.BeforeQueryCallback)
```

**Comment by frederikhors** [comment]
Thank you so much, @gatspy.

I am very sad to use `reflect`.

**Comment by james70s** [comment]
db.Callback().Query().Before("gorm:query").Register("td:before_query", beforeQuery)

func beforeQuery(db *gorm.DB) {
	if field := db.Statement.Schema.LookUpField("CompanyId"); field != nil {
		// db.Statement.Where("company_id", CurrentCompany)   // not work
		if cds := db.Statement.BuildCondition("company_id", CurrentCompany); len(cds) > 0 {
			db.Statement.AddClause(clause.Where{Exprs: cds})。// it‘s work
		}
	}
}
