### ISSUE TITLE
Failed, got error: ERROR: syntax error at or near "$2" (SQLSTATE 42601) but the query is right

### ISSUE THREAD

**Issue by frederikhors** [go-gorm/gorm#3641]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/186

## Description

I'm using this query (similar to this: https://github.com/go-gorm/gorm/issues/3631)

```go
package main

import (
	"testing"
	"strconv"
)

// GORM_REPO: https://github.com/go-gorm/gorm.git
// GORM_BRANCH: master
// TEST_DRIVERS: postgres

func TestGORM(t *testing.T) {
	user := User{Name: "jinzhu"}

	DB.Create(&user)

	var deletedUser User
	err := DB.
		Where("created_at < NOW() - INTERVAL ?", strconv.Itoa(10)+" hours").
		Delete(&deletedUser).Error
	
	if err != nil {
		t.Errorf("Failed, got error: %v", err)
	}
}
```

As you can see the test is failing but the query is **RIGHT!**: https://github.com/go-gorm/playground/pull/186/checks?check_run_id=1283912260#step:6:28

Error: `Failed, got error: ERROR: syntax error at or near "$2" (SQLSTATE 42601)`

**Comment by jinzhu** [comment]
Seems like the pgx's `PreferSimpleProtocol` mode support use `strconv.Itoa(10)+" hours"` as argument, but the default mode doesn't, so you need to initialize the db like:

```go
		db, err = gorm.Open(postgres.New(postgres.Config{
			DSN:                  dbDSN,
			PreferSimpleProtocol: true,
		}), &gorm.Config{})
```

**Comment by frederikhors** [comment]
What is the difference if I disable `PreferSimpleProtocol`?

I don't want to lose performance if this is - as it seems - a bug and not a feature.

**How can I alternatively solve?**

**Comment by jinzhu** [comment]
You can use `&gorm.Config{PrepareStmt: true})` to avoid the performance loss

**Comment by frederikhors** [comment]
Oh, now I'm really confused.

To understand if I understand:

1. Are the prepared statements of pgx the same as those of Gorm?

1. If I deactivate the pgx ones with `PreferSimpleProtocol: true` and activate the Gorm ones with `& gorm.Config {PrepareStmt: true})` do I get the same effect on my queries?

1. Is this a `pgx` problem then?

---

# UPDATE

I tried what you suggested: **it's the same**. The same errors.

Can we try it in Gorm Playground?

**Comment by jinzhu** [comment]
You need to use `PreferSimpleProtocol: true` with `gorm.Config {PrepareStmt: true})`

Looks like pgx's problem.

**Comment by frederikhors** [comment]
> You need to use PreferSimpleProtocol: true with gorm.Config {PrepareStmt: true})

Yes. I'm using it. Same problem. Same error.

Can you please re-open this until we fix.

**This is blocking us to switch from `go-pg` to `Gorm`.**

**Comment by frederikhors** [comment]
The error in console:

```
Oct 21 10:48:38 DBG C:/pkg/player/main.go:115 sql: expected 0 arguments, got 1
[10.998ms] [rows:0] DELETE FROM "players" WHERE created_at < NOW() - INTERVAL '10 hours'
Oct 21 10:48:38 PNC  error="sql: expected 0 arguments, got 1"
```

**Comment by jinzhu** [comment]
Confirmed `gorm.Config {PrepareStmt: true})` doesn't work either, then seems we can't make it works without using the `PreferSimpleProtocol: true` mode

**Comment by frederikhors** [comment]
Ok. Can you please re-open this until we found a fix? I opened this: https://github.com/jackc/pgx/issues/852.

**Comment by jinzhu** [comment]
> Ok. Can you please re-open this until we found a fix? I opened this: [jackc/pgx#852](https://github.com/jackc/pgx/issues/852).

Nothing can do in GORM side to fix the issue, maybe just track it using the pgx one? If it is fixed, then you could just upgrade your project's pgx driver to make it works with GORM.

**Comment by frederikhors** [comment]
Ok. Just one question.

If I NOT use `PreferSimpleProtocol: true` (**SO I DO NOT USE THE SIMPLE PROTOCOL**) with `gorm.Config {PrepareStmt: true})` is it something useful?

I mean, is this the same thing?

How they differ?

Is it suggested to use Gorm `PrepareStmt`?

Thanks for your answer.

**Comment by jinzhu** [comment]
I would suggest to use `PrepareStmt` over the default pgx mode, there are doing similar thing, but the GORM one provides more features, you could checkout GORM's document for details.
