### ISSUE TITLE
Automigrate: Change column size 

### ISSUE THREAD

**Issue by maeglindeveloper** [go-gorm/gorm#3645]
## Your Question

Hi everyone, 

I'm actually using the v2 of gorm. In the documentation, I found the following information

_**NOTE: AutoMigrate will create tables, missing foreign keys, constraints, columns and indexes, and will change existing column’s type if it’s size, precision, nullable changed, it WON’T delete unused columns to protect your data.**_

https://gorm.io/docs/migration.html

I tried to change the size of one column using `AutoMigrate` but it appears that it is not working.
First of all, before creating any BUG issue, I wanted to double check that it is doable ?

Here is my code:

```
type Module struct {
	gorm.Model
	Name  string `gorm:"size:36"`
}
```

I only changed the size from 128 to 36
But nothing changed on my `modules` table.

![image](https://user-images.githubusercontent.com/6367870/96699149-3cb96980-138e-11eb-9217-cfd5ccfa8109.png)

The driver is a mysql one.

Thanks in advance @jinzhu 👍

**Comment by maeglindeveloper** [comment]
EDIT: It seems that this issue is related as well
https://github.com/go-gorm/gorm/issues/3628
@jinzhu

**Comment by asmeikal** [comment]
@maeglindeveloper can confirm that it's related, the tests failing in [this PR](https://github.com/go-gorm/playground/pull/183) show that `mysql` does not have size information when calling `ColumnTypes` (used by `AutoMigrate`).

**Comment by jinzhu** [comment]
> @maeglindeveloper can confirm that it's related, the tests failing in [this PR](https://github.com/go-gorm/playground/pull/183) show that `mysql` does not have size information when calling `ColumnTypes` (used by `AutoMigrate`).

Hi @asmeikal, I have tested postgres with datatime, seem it save the precision information into `datetime_precision`, which doesn't work correctly, could you check it out?

**Comment by jinzhu** [comment]
I have updated tests to test this case  https://github.com/go-gorm/gorm/tree/smart_auto_migrate

**Comment by asmeikal** [comment]
Hi @jinzhu, I'm having some problems with `mysql`. I've fixed the datetime precision issue, but [this line](https://github.com/go-gorm/gorm/commit/7571baad25507f79aabf0c25a73001b39f86e2df#diff-23864390402317a89bc6a5197a8144403c082c4e2a3d0132bac131454831b5f9R88) fails with `mysql`.

The `salary` column is first created with data type `double` using [this version](https://github.com/go-gorm/gorm/commit/7571baad25507f79aabf0c25a73001b39f86e2df#diff-23864390402317a89bc6a5197a8144403c082c4e2a3d0132bac131454831b5f9R56) of the entity.

Then [the second version](https://github.com/go-gorm/gorm/commit/7571baad25507f79aabf0c25a73001b39f86e2df#diff-23864390402317a89bc6a5197a8144403c082c4e2a3d0132bac131454831b5f9R67) of the entity is not migrated correctly with `mysql`.

The desired type is `decimal(2, 0)` as returned by `m.DB.Migrator().FullDataTypeOf(field).SQL`, and the current data type is `double` as returned by `columnType.DatabaseTypeName()`. See the [beginning](https://github.com/go-gorm/gorm/blob/master/migrator/migrator.go#L362) of this function.

But the data type is not changed from `double` to `decimal(2, 0)`, so the `salary` test fails. I'm not sure how to solve this.

I opened [this PR](https://github.com/go-gorm/postgres/pull/16) for `postgres` and [this PR](https://github.com/go-gorm/mysql/pull/9) for `mysql` for the datetime precision issue.

**Comment by jinzhu** [comment]
> Hi @jinzhu, I'm having some problems with `mysql`. I've fixed the datetime precision issue, but [this line](https://github.com/go-gorm/gorm/commit/7571baad25507f79aabf0c25a73001b39f86e2df#diff-23864390402317a89bc6a5197a8144403c082c4e2a3d0132bac131454831b5f9R88) fails with `mysql`.
> 
> The `salary` column is first created with data type `double` using [this version](https://github.com/go-gorm/gorm/commit/7571baad25507f79aabf0c25a73001b39f86e2df#diff-23864390402317a89bc6a5197a8144403c082c4e2a3d0132bac131454831b5f9R56) of the entity.
> 
> Then [the second version](https://github.com/go-gorm/gorm/commit/7571baad25507f79aabf0c25a73001b39f86e2df#diff-23864390402317a89bc6a5197a8144403c082c4e2a3d0132bac131454831b5f9R67) of the entity is not migrated correctly with `mysql`.
> 
> The desired type is `decimal(2, 0)` as returned by `m.DB.Migrator().FullDataTypeOf(field).SQL`, and the current data type is `double` as returned by `columnType.DatabaseTypeName()`. See the [beginning](https://github.com/go-gorm/gorm/blob/master/migrator/migrator.go#L362) of this function.
> 
> But the data type is not changed from `double` to `decimal(2, 0)`, so the `salary` test fails. I'm not sure how to solve this.
> 
> I opened [this PR](https://github.com/go-gorm/postgres/pull/16) for `postgres` and [this PR](https://github.com/go-gorm/mysql/pull/9) for `mysql` for the datetime precision issue.

Just added a comment for the mysql driver.

**Comment by jinzhu** [comment]
Merged the PR, thank you for your awesome work ;)
