### ISSUE TITLE
如何使default的数据库函数的值不带引号

### ISSUE THREAD

**Issue by chengxiao** [go-gorm/gorm#3646]
```golang
type TbComment struct {
	ID string `gorm:"default:comment_seq.nextval;"` // 数据库函数
	Remark string
}

func (T TbComment) TableName() string {
	return "tb_comment"
}
```

```golang
var ss TbComment
ss.Remark = "Test"
Om.Table(ss.TableName()).Create(&ss)
```

comment_seq.nextval 是阿里云PolarDB-X的sequence取值函数，但是不支持用引号扩起来

默认生成的sql为：
> INSERT INTO `tb_comment` (`id`,`remark`) VALUES ('comment_seq.nextval','Test')

有什么配置是可以让生成的:comment_seq.nextval 不带引号的么？
既：

> INSERT INTO `tb_comment` (`id`,`remark`) VALUES (comment_seq.nextval,'Test')

**Comment by jinzhu** [comment]
can it be written like `comment_seq.nextval()`?

**Comment by chengxiao** [comment]
> can it be written like `comment_seq.nextval()`?

试了下，写成comment_seq.nextval()，但是执行后还是取不到值，被单引号包起来就不行

**Comment by jinzhu** [comment]
last insert id 不返回值，我也没办法。。。

**Comment by chengxiao** [comment]
> last insert id 不返回值，我也没办法。。。

没有方法让comment_seq.nextval 这个语句在生成的sql里不带引号么？
