### ISSUE TITLE
row and column alias for mysql 8.0.20

### ISSUE THREAD

**Issue by mukeshydv** [go-gorm/gorm#3649]
## Your Question

The use of `VALUES()` to refer to the new row and columns is deprecated beginning with MySQL 8.0.20, and is subject to removal in a future version of MySQL. Instead, use row and column aliases

Beginning with MySQL 8.0.19, it is possible to use an alias for the row, with, optionally, one or more of its columns to be inserted, following the VALUES or SET clause, and preceded by the AS keyword

```sql
INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6) AS new
  ON DUPLICATE KEY UPDATE c = new.a+new.b;
```

If, in addition, you use the column aliases m, n, and p, you can omit the row alias in the assignment clause and write the same statement like this: 

```sql
INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6) AS new(m,n,p)
  ON DUPLICATE KEY UPDATE c = m+n;
```

I'm have code something like this from here: https://gorm.io/docs/create.html#Upsert-On-Conflict)
```go
DB.Clauses(clause.OnConflict{
  Columns:   []clause.Column{{Name: "id"}},
  DoUpdates: clause.AssignmentColumns([]string{"name", "age"}),
}).Create(&users)
```

Is there a way to add alias to row?

Ref: [https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html)

**Comment by jinzhu** [comment]
we are not going to use the column alias unless most user's database support that

> Is there a way to add alias to row?

should implement it here https://github.com/go-gorm/mysql/blob/6dfb6027305a0e5d2bc584ef30f18bca58783487/mysql.go#L97
