### ISSUE TITLE
What's the difference between these two ways of query things?

### ISSUE THREAD

**Issue by frederikhors** [go-gorm/gorm#3652]
I'm using Postgresql.

I want to understand what the difference is between

1. this:

    ```go
    var name = "myName"
    var user User

    db.Where("user like ?", name).Find(&user)
    ```

1. and this:

    ```go
    var user User

    db.Where("user like " + name).Find(&user)
    ```

**The SQL query is the same.**

I mean, why do we use ORMs?

1. Can the #1 become a prepared statement?

1. Is the #1 "more optimized" than the #2?

1. What does it mean "more optimized"?

---

I'm asking this because of https://github.com/go-gorm/gorm/issues/3641.
To fix it I had to use a string concatenation in my `.Where()` clause, like the #2 of this question.

**Comment by jinzhu** [comment]
2 might cause sql injection
