### ISSUE TITLE
Error: Cannot encode model in simple protocol - model must implement driver.Valuer, pgtype.TextEncoder, or be a native type

### ISSUE THREAD

**Issue by frederikhors** [go-gorm/gorm#3654]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/187

## Description

I have these structs:

```go
type Player struct {
	Name string
  Bio *Bio `gorm:"type:jsonb"`
}

type Bio struct {
  Places []*Places
}

type Places struct {
  Address *string
}
```

If I create a `Player` using

```go
player := Player{Name: "jinzhu", Bio: &Bio{}}
DB.Create(&player)
```

I receive this error:

```
Cannot encode Bio in simple protocol - Bio must implement driver.Valuer, pgtype.TextEncoder, or be a native type
```

if I initialize Gorm with this code:

```go  
myDB := gorm.Open(postgres.New(postgres.Config{
  DSN:                  myDSN,
  PreferSimpleProtocol: true,
}), &gorm.Config{
  Logger:                 customLogger,
  SkipDefaultTransaction: true,
  PrepareStmt:            false,
})
```

**Why?**

I'm using `PreferSimpleProtocol: true` based on what we said here: https://github.com/go-gorm/gorm/issues/3641#issuecomment-713511783.

**What to do now?**

**Comment by frederikhors** [comment]
If I **DO NOT** use `PreferSimpleProtocol` and I use `PrepareStmt: true` it's wrong and unnecessary because I do the same thing twice, right?

**Comment by jinzhu** [comment]
Just as the error message says, the bio need to implement the `driver.Valuer`, `sql.Scanner`, nothing related to the mode.

**Comment by frederikhors** [comment]
Ok.

I am a very attentive reader of documentation. But this topic either escaped me or it is not clear enough.

In our projects we use `go-pg` which we would like to change and switch to using `Gorm`.

`go-pg` manages to "natively" transform all the structs it finds into JSONB, without even using the `struct tags`.

In the Gorm 2 documentation I can't find how to do it.

Can I or can't I easily use Postgresql's JSONB columns to save structs?

We have a lot of them and this is blocking the switch to Gorm.

Thanks for the reply.

**Comment by jinzhu** [comment]
https://gorm.io/docs/data_types.html
https://github.com/go-gorm/datatypes#json
https://www.alexedwards.net/blog/using-postgresql-jsonb
https://golang.org/pkg/database/sql/#Scanner
https://golang.org/pkg/database/sql/driver/#Valuer
