### ISSUE TITLE
In Mysql :SlowThreshold:100ms can represent slow query time?

### ISSUE THREAD

**Issue by lhypj** [go-gorm/gorm#3661]
## There are some slow logs in gorm. I found  
[`case elapsed > l.SlowThreshold && l.SlowThreshold != 0 && l.LogLevel >= Warn:`](https://github.com/go-gorm/gorm/blob/master/logger/logger.go#L148)
But Trace include:
0:log beginTime
1:build connection
2:read data
3:release conn
4:log endTime

As i known, slow log time should be equal to sql exec time.But the code in gorm makes me confused.
I should learn a new idea about gorm slow log or I lost sth?

**Comment by yrong** [comment]
you are hairsplitter
