### ISSUE TITLE
migrator.go:192:65: undefined: gorm.ColumnType

### ISSUE THREAD

**Issue by xs23933** [go-gorm/gorm#3665]
go version go1.15.2 darwin/amd64

gorm version gorm.io/gorm v1.20.4

报错
../../go/pkg/mod/gorm.io/driver/mysql@v1.0.3/migrator.go:192:65: undefined: gorm.ColumnType
../../go/pkg/mod/gorm.io/driver/mysql@v1.0.3/migrator.go:193:23: undefined: gorm.ColumnType

**Comment by jinzhu** [comment]
use gorm v1.20.5

**Comment by shyandsy** [comment]
same problem
