### ISSUE TITLE
Locking Clause Support for MySQL 5.7 and below

### ISSUE THREAD

**Issue by nightism** [go-gorm/gorm#3666]
## Describe the feature

Support `LOCK IN SHARE MODE` clause.

## Motivation

Currently, only two locking clauses are supported `FOR SHARE` and `FOR UPDATE`. However, in MySQL 5.7, `FOR SHARE` clause is not yet supported, instead `LOCK IN SHARE MODE` is used.

**Comment by nightism** [comment]
I can help to add in this feature and submit a pull request.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/mysql/blob/61d41cd294a4609e361e4e0815f2d1d8afe79db1/mysql.go#L96

You can implement it in the above link, if current mysql version doesn't support `FOR SHARE` (https://github.com/go-gorm/mysql/blob/61d41cd294a4609e361e4e0815f2d1d8afe79db1/mysql.go#L74) then use `LOCK IN SHARE MODE` instead

**Comment by nightism** [comment]
PR is in https://github.com/go-gorm/mysql/pull/11

**Comment by jinzhu** [comment]
Merged, thank you.
