### ISSUE TITLE
"invalid value" error

### ISSUE THREAD

**Issue by wodim** [go-gorm/gorm#3668]
I am getting the error "invalid value" from here: https://github.com/go-gorm/gorm/blob/db2630cb3a02edcc92678ed78e49d1e85d268224/callbacks.go#L100

Pointing to a line as simple as `db.Take(&user)`

There is absolutely no hint as to what the error could be or how to solve it.

**Comment by jinzhu** [comment]
user is nil pointer

**Comment by DeviaVir** [comment]
For others finding this error in the future, @jinzhu is correct.

I had this:
```
var user *User
db.Where().First(&user)
```

which makes `user`  a nil pointer. Instead, use:

```
user := User{}
db.Where().First(&user)
```

`user` now is no longer a nil pointer, if you need to return it as a pointer make sure to use `return &user`
