### ISSUE TITLE
gorm 日志打印问题

### ISSUE THREAD

**Issue by ruixule** [go-gorm/gorm#3669]
## Your Question

![image](https://user-images.githubusercontent.com/33270841/96958536-52ff2b00-1530-11eb-8e9d-e0a16d7727d8.png)

初始化了日志，但是sql 么有进行日志打印为什么

**Comment by ruixule** [comment]
func initClient() {

	var logFile *os.File
	fileName := "gorm.log"
	_, err2 := os.Stat(fileName)
	if err2 != nil {
		if os.IsNotExist(err2) {
			logFile, _ = os.Create(fileName)
		} else {
			logFile, _ = os.Open(fileName)
		}
	}
	ormLog := logger.New(
		log.New(logFile, time.Now().Format("2006-01-02 15:04:05"), log.Lshortfile),
		logger.Config{
			SlowThreshold: time.Second,   // 慢 SQL 阈值
			LogLevel:      logger.Silent, // Log level
			Colorful:      false,         // 禁用彩色打印
		},
	)
	var err error
	GormClient, err = gorm.Open(sqlite.Open("foo.db"), &gorm.Config{
		Logger: ormLog,
	})

	if err != nil {
		panic(err)
	}
}

**Comment by jinzhu** [comment]
Log Level
