### ISSUE TITLE
DB.FirstOrCreate throws `reflect: call of reflect.Value.Type on zero Value` error

### ISSUE THREAD

**Issue by hetjagani** [go-gorm/gorm#3671]
I have very basic model User class. And at the time of creating a user I am checking if the user with email already exist? If not it should create a user with the given email. For this I was using `FirstOrCreate` method. It was working fine in v1. But now in v2 it is throwing error `reflect: call of reflect.Value.Type on zero Value`.

### Code
```go
user := model.User{}
tx.FirstOrCreate(&user, model.User{
    Email: req.Email,
}
```

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
