### ISSUE TITLE
Small documentation update

### ISSUE THREAD

**Issue by petrjahoda** [go-gorm/gorm#3677]
## Describe the feature

When opening connection to a database a new goroutine is created. That is OK, if only one connection (or few) is used through the program. But in case the program has to be made a way, that a new connection is made on demand, the problem arise. 
With every new connection a new goroutine is created and another 8Kb of memory is consumed.

Because of that, maybe this  information can be added to https://gorm.io/docs/connecting_to_the_database.html

The obvious solution for those cases is simple:

**Original**
```
dsn := "user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
if err != nil {
   handleError()
}
```
**New:**
```
dsn := "user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
sqlDB, _ := db.DB()
defer sqlDB.Close()
if err != nil {
   handleError()
}
```

**Comment by jinzhu** [comment]
https://gorm.io/docs/generic_interface.html
