### ISSUE TITLE
When using query raw SQL with scan, will no error be returned when the record does not exist？

### ISSUE THREAD

**Issue by axiaoxin** [go-gorm/gorm#3678]
## Your Question

```
        sql := `select * tests_tb where id=?`
	err := db.Raw(sql, -1).Scan(&obj).Error
	if err != nil {
		return err
	}
```
id=-1 not exists, but err is nil, can't use IsRecordNotFoundError

## Expected answer

Can't use this method to judge errors when using raw scan？

**Comment by jinzhu** [comment]
We only raise ErrRecordNotFound error for `First`, `Last`, `Take`

**Comment by chowyu08** [comment]
how to judge no record?

**Comment by pieterclaerhout** [comment]
This seems to be a big difference compared with v1 (which does raise `ErrRecordNotFound` when using `db.Raw`).

Can this be reconsidered to make migration from version 1 to version 2 easier?
