### ISSUE TITLE
Custom data type question

### ISSUE THREAD

**Issue by boolangery** [go-gorm/gorm#3679]
Hi, I'm trying to figure out how to create a custom data type that would integrate with this library: https://github.com/graymeta/stow

This is a data storage library to store data in an Amazon S3 bucket for example.

I would like to store resource ID in the database and when this custom field is retrieved, compute its real URL.

I'm stuck on this point because to compute its real URL, I need a `Container` ref:

```go
type StowFileField struct {
    Container *Container
    Reader     io.Reader
    FileName string
}

func (f StowFileField) GormDataType() string {
   return "string"
}

func (f StowFileField) Value() (driver.Value, error) {
    // store the file in the container
    // here I can use f.Container because the user created a StowFileField with a Container ref
    return f.FileName, nil
}

func (f *StowFileField) Scan(v interface{}) error {
    // Scan a value into struct from database driver
    // Here StowFileField is created by Gorm and f.Container is nil
    // So I'm stuck because I need to retrieve file URL
}
```

So how I can in some way pass a Container ref to a StowFileField created by Gorm before calling Scan ?

Even with callback and plugin this does not seem possible to me.

Any help appreciated :)

**Comment by jinzhu** [comment]
I don't know where you can get the container, but please refer the https://github.com/qor/media it should do similar job but for GORM V1, you could get the basic idea and make it works with GORM V2
