### ISSUE TITLE
Why does it sometimes require `.Error` to get error, whereas othertimes it does not?

### ISSUE THREAD

**Issue by popey456963** [go-gorm/gorm#3680]
## Your Question

The following line:

	err := utils.DB.Model(&models.User{}).Association("Accounts").Find(&accounts)

Returns a type `error`.

Where, most other functions require `.Error` to be appended, aka:

	err := utils.DB.Where("account_id = ?", accountID).First(&merchant).Error

Why is there a difference between the two?

**Comment by jinzhu** [comment]
Chainable methods need to access the error message with `.Error`, association mode doesn't require it.
