### ISSUE TITLE
How should I upsert all columns?

### ISSUE THREAD

**Issue by dayeguilaiye** [go-gorm/gorm#3682]
I've read your docs, but still don't know how to upsert all columns.
I tried to do like this:

```
Db.Clauses(clause.OnConflict{
Columns: []clause.Column{{Name: "id"}},
DoUpdates: clause.AssignmentColumns([]string{"*"}),
}).Create(&users)
```

but get a "column excluded.* does not exist"

so how to do this?

**Comment by jinzhu** [comment]
Just use Save

**Comment by hbagdi** [comment]
@jinzhu I used save but it then creation time resets to zero value. Any way to work around it?
