### ISSUE TITLE
batch insert question

### ISSUE THREAD

**Issue by whmmm** [go-gorm/gorm#3685]
## Your Question

```go
// 批量插入 每次默认插入 1000 条 , 1000 条是一个保守值
//
// 这个方法的作用是 防止 mysql 1390 错误 (预处理语句占位符太多)   occur mysql 1390 error when list size is too big .
//
// db (*gorm.Db) 需要先调用 model 参数, 要不然 gorm 不知道 list 的类型！
func BatchInsert(db *gorm.DB, list interface{}, pageSize int) {
	if !val_util.IsSlicePtr(list) {
		panic("参数类型错误, list 参数必须是一个数组指针。")
	}
	objList := reflect.Indirect(reflect.ValueOf(list)).Interface()
	s := reflect.ValueOf(objList)
	var insertList = []types.Any{}
	for i := 0; i < s.Len(); i++ {
		any := s.Index(i).Interface()
		size := len(insertList)
		if size < pageSize {
			// do nothing
		} else if size == pageSize {
			db.Create(&insertList)
			// 清空数组  empty slice
			insertList = []types.Any{}
		}
		insertList = append(insertList, any)
	}
	if len(insertList) > 0 {
		db.Create(&insertList)
	}
}
```

go raise a error 
```
panic: reflect: call of reflect.Value.Field on interface Value [recovered]
	panic: reflect: call of reflect.Value.Field on interface Value
```
does interface{} can'not use reflect.Field ?
how can I dispose this question?

想写一个 通用的分页 入库的方法, 但是 go  interface{} 不支持 reflect.ValueOf ,如何处理这种情况? 每个 插入列表的地方都复制
粘贴这段代码吗？

**Comment by jinzhu** [comment]
reflect.New(reflect.SliceOf(type))
reflect.Append()

**Comment by whmmm** [comment]
// 经过修改，改成如下代码，测试可以通过


// 批量插入 每次默认插入 1000 条 , 1000 条是一个保守值
//
// 这个方法的作用是 防止 mysql 1390 错误 (预处理语句占位符太多)   occur mysql 1390 error when list size is too big .
//
// db (*gorm.Db) 需要先调用 model 参数, 要不然 gorm 不知道 list 的类型！
func BatchInsert(db *gorm.DB, list interface{}, pageSize int) {
	if !val_util.IsSlicePtr(list) {
		panic("参数类型错误, list 参数必须是一个数组指针。")
	}
	objList := reflect.Indirect(reflect.ValueOf(list)).Interface()
	s := reflect.ValueOf(objList)
	if s.Len() == 0 {
		return
	}
	var insertList = reflect.New(reflect.SliceOf(s.Index(0).Type())).Elem()

	for i := 0; i < s.Len(); i++ {
		any := s.Index(i).Interface()
		size := insertList.Len()
		if size < pageSize {
			// do nothing
		} else if size == pageSize {
			db.Create(insertList.Interface())
			// 清空数组  empty slice
			insertList = reflect.New(reflect.SliceOf(s.Index(0).Type())).Elem()
		}
		insertList = reflect.Append(insertList, reflect.ValueOf(any))
	}
	if insertList.Len() > 0 {
		db.Create(insertList.Interface())
	}
}
还想问下,  用了这么多反射, 是否会影响性能? 
这种 1390 错误 一般是如何处理的呢 ? ---
