### ISSUE TITLE
How about automatically skipping to generate FOR UPDATE clause when using SQLite3.

### ISSUE THREAD

**Issue by c-bata** [go-gorm/gorm#3687]
## Describe the feature

Hi. Thank you for creating this awesome library.
I've recently migrated to GORM v2 from v1 in my library. There are a lot of improvements and new features. Good work.

This issue is a feature request to automatically ignore FOR UPDATE clause when using SQLite3.

## Motivation

SQLite3 does not support `FOR UPDATE` clause. So it is required to write following code.

```go
if s.db.Dialector.Name() == "sqlite" {
	result = tx.First(&study, "study_id = ?", studyID)
} else {
	result = tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&study, "study_id = ?", studyID)
}
```

https://github.com/c-bata/goptuna/blob/9e9699a4394bf94f2a311ba4574a507ac833c824/rdb.v2/storage.go#L216-L224

From my investigation, famous Python ORM libraries (SQLAlchemy and Django ORM) automatically skip to generate `FOR UPDATE` clause when using SQLite3. So we don't need to write the code like above.

* SQLAlchemy: https://github.com/sqlalchemy/sqlalchemy/blob/a2e8e773c5d4b564a5a7a83711ae0378e2fbc6a0/lib/sqlalchemy/dialects/sqlite/base.py#L1032-L1034

I know this is a controversial behavior, but it's convenience for me.
If you don't like these behaviors, please feel free to close this issue.

**Comment by jinzhu** [comment]
Would you mind follow the link and create a pull request for sqlite?

https://github.com/go-gorm/mysql/blob/9c5ee1e3e2be6c29a7b3b34c20f5ff38245f73c1/mysql.go#L158

**Comment by c-bata** [comment]
Thank you! I'll open a pull request at https://github.com/go-gorm/sqlite!

**Comment by c-bata** [comment]
Thank you for merging the PR!
