### ISSUE TITLE
sql: scan error while inserting values when default:NULL is specified in model 

### ISSUE THREAD

**Issue by hetjagani** [go-gorm/gorm#3689]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/191

## Description

I have simple model class as follows:
```go
type User struct {
	gorm.Model
	Name string
	Age  uint `gorm:"default:NULL"`
	DOB  time.Time
}
```

Now while creating if I have Age 0 (i.e. `db.Create(&User{Name: "jinzhu",DOB:  time.Now(),Age:  0})`) then it throws error `ql: Scan error on column index 1, name "age": converting NULL to uint is unsupported`. Ideally it should not throw this error.

* Also, is there any way I can set a `uint` field to NULL while updating. Right now I am doing that by following query:
```go
db.Model(&User{}).Updates(map[string]interface{}{"age": nil})
```

**Comment by jinzhu** [comment]
use pointer or sql.NullUint

```go
type User struct {
	gorm.Model
	Name string
	Age  *uint `gorm:"default:NULL"`
	DOB  time.Time
}
```

**Comment by hetjagani** [comment]
I tried using pointer but for pointer I cannot set it to NULL in update. Because if I pass nil then it won't include in UPDATE query.

**Comment by jinzhu** [comment]
https://gorm.io/docs/update.html#Update-Selected-Fields

**Comment by MrWormHole** [comment]
why does this issue exist for uint default null in postgres? this uint thing works fine in sqlite with default NULL. Is this gorm issue or driver issue? i am willing to provide a pull request for this
