### ISSUE TITLE
DeletedAt marshal and unmarshal issue

### ISSUE THREAD

**Issue by amitbasuri** [go-gorm/gorm#3693]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/194
## Description

marshal DeletedAt which is invalid and then unmarshal it. Ideally, the result after unmarshaling should match but it is not.

```go
func TestDeletedAtUnMarshal(t *testing.T) {

	expected := &gorm.Model{}
	b, _ := json.Marshal(expected)

	result := &gorm.Model{}
	_ = json.Unmarshal(b, result)
	if result.DeletedAt != expected.DeletedAt {
		t.Errorf("Failed, result.DeletedAt: %v is not same as expected.DeletedAt: %v", result.DeletedAt, expected.DeletedAt)
	}
}
```

**Comment by amitbasuri** [comment]
@jinzhu In my opinion Marshaling Invalid DeletedAt to null is a better option. Then using null to figure out if it is invalid while unmarshaling.

**Comment by jinzhu** [comment]
> @jinzhu In my opinion Marshaling Invalid DeletedAt to null is a better option. Then using null to figure out if it is invalid while unmarshaling.

Did that, thank you for your suggestion.

**Comment by amitbasuri** [comment]
@jinzhu we also need to handle unmarshal null to invalid DeleatedAt https://github.com/go-gorm/gorm/pull/3695/files
