### ISSUE TITLE
Missing operator priority in method chaining / incomplete documentation

### ISSUE THREAD

**Issue by Gaadek** [go-gorm/gorm#3697]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/195

## Description
I'm using gorm and my business logic requires me to build the `where` clauses at run time.

To resume the situation, I provide a filter structure (which contains a set of attributes I can use to filter my query) and I add a `.Where` statement for non null filtering attributes : 
```
type User struct {
	gorm.Model
	Name string
	FirstName string
	Birthday  *time.Time
}

// I start here to build my query, just using the model
query := DB.Model(&User{})

// Add "Name" filter if not empty
if (filters.Name != "") {
  query = query.Where("name = ?", filter.Name)
}

// Add "Birthday" filter if not empty
if (filters.Birthdate != "") {
  query = query.Where("Birthday <= ?", filter.Birthday)
}
```
The example above works pretty well.
Unfortunately, I have a situation where I need to check 2 attributes of my model with the same filters, this requires me to combine `.where(...)` with `.Or(...)` like this:
```
type User struct {
	gorm.Model
	Name string
	FirstName string
	Birthday  *time.Time
}

// I start here to build my query, just using the model
query := DB.Model(&User{})

// Add "Name" filter if not empty
if (filters.Name != "") {
  query = query.Where("Name = ?", filter.Name).Or("FirstName = ?", filter.Name)
}

// Add "Birthday" filter if not empty
if (filters.Birthdate != "") {
  query = query.Where("Birthday <= ?", filter.Birthday)
}
```
Unfortunately, in such situation, this result in a non coherent query where clause: 
`SELECT * FROM `users` WHERE (name = "alice" OR firstname = "alice" AND Birthday <= "2020-09-29 00:00:00") AND `users`.`deleted_at` IS NULL`

Where I expected to get all users having their name or firstname = "alice", then  also their birthday before September 29th, 2020, I get all users having for name "alice" or those having firstname="alice" and birthday = 29SEP2020

OK, in **this** particular case, I could fix  that this way:
```
if (filters.Name != "") {
  query = query.Where("Name = ? or FirstName = ?", filter.Name, filter.Name)
}
```

However, my real case scenario is far more complex because I'm trying to do that for JSONB field types, with the use of jsonb operators and I cannot figure out how to achieve that alone...

Here is what I did so far:
```
// Base query
query := r.DB.Model(&models.MyModel{})

if filters.ProjectID != "" {
  // Expressions to look for ProjectID anywhere in details (a JsonB field). This is what is hard to combine with the statement after
  jsonbQuery := fmt.Sprintf("details @? '$.** ? (@.project_id == \"%s\")'", filters.ProjectID)

  // Look for records having project_id or referencing the project_id in their details
  query = query.Where("project_id = ?", filters.ProjectID).Or(jsonbQuery)
}

// Dates
if !filters.FromTSTime.IsZero() {
  query = query.Where("created_at >= ?", filters.FromTSTime)
}
```

The logic above is the issue, when I look for a specific project, with a created_date restriction, it returns in all cases **all** the records with project_id  == filters.ProjectID, whatever the creation date is.

But this is not what I want, I expect all the records where (project_id  == filters.ProjectID or details contains project_id) **and** created_at >= filters.FromTSTime

**Comment by jinzhu** [comment]
https://gorm.io/docs/advanced_query.html#Group-Conditions
