### ISSUE TITLE
Issue in #3640 has been pushed to indexes

### ISSUE THREAD

**Issue by endophage** [go-gorm/gorm#3698]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/185

## Description

I've confirmed the issue specifically referenced in #3640 is fixed but it has exposed the same issue when automigration attempts to create indexes. The `CREATE INDEX` query drops the schema name. I see:

```
CREATE TABLE the_schema.the_table ...

CREATE INDEX some_index ON the_table ...
```
With the `CREATE INDEX` statement producing the error `ERROR: relation "the_table" does not exist (SQLSTATE 42P01)`

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
