### ISSUE TITLE
Gorm Table API can't add Subquery arguments

### ISSUE THREAD

**Issue by petchnattkit** [go-gorm/gorm#3701]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/196

## Description

I'm doing a "from subquery" following by this [docs](https://gorm.io/docs/advanced_query.html#From-SubQuery)
but when I pass subquery arguments into table api, it result an error "too many arguments".

## Environments
	github.com/go-sql-driver/mysql v1.5.0
	github.com/jinzhu/gorm v1.9.16

**Comment by jinzhu** [comment]
The document is for GORM v2, GORM v1.9.16 is GORM V1
