### ISSUE TITLE
Proper way to delcare a one to many (hasOne?) relationship, whith composite primary keys

### ISSUE THREAD

**Issue by dmcbeing** [go-gorm/gorm#3703]
## Your Question

I need to create a one to many relationship but with tables having composite primary keys.
I have read the documents , but have not been able to make it work.
I also looked at the unit tests, but have only found one to many cases with simple/non-composite primary keys.
I have uploaded my attempt to do this in the playground:  https://github.com/go-gorm/playground/pull/193

## The document you expected this should be explained
https://gorm.io/docs/has_one.html

## Expected answer

Is it possible to do what i want in gorm?
If yes, then how?

Thank you

**Comment by jinzhu** [comment]
sqlite require TestFile contains a primary key, e.g:

```go
type TestFile struct {
	ProjName string `gorm:"primaryKey"`
	File string
}
```
