### ISSUE TITLE
hook func add context.Context parameter

### ISSUE THREAD

**Issue by coolyrat** [go-gorm/gorm#3705]
## Describe the feature

```go
func (u *User) BeforeCreate(ctx context.Context, tx *gorm.DB) (err error) {
  u.UUID = uuid.New()

  if !u.IsValid() {
    err = errors.New("can't save invalid data")
  }
  return
}
```

## Motivation

I want to use the hook functions for the operation log. Need to extract userId from the Context. Or is there a better way to save operation logs?

## Related Issues

Not found.

**Comment by jinzhu** [comment]
https://gorm.io/docs/context.html#Context-in-Hooks-Callbacks
