### ISSUE TITLE
Create Without Upserting Associations While Still Adding Many-To-Many References

### ISSUE THREAD

**Issue by asterikx** [go-gorm/gorm#3710]
## Your Question

What is the correct way to create a new entity with associations (many-to-many) with pre-existing entities? I do not want to upsert the pre-existing entities, but still, need to add entries to the many-to-many table.

I need to create a new `Project` and associate it with pre-existing `Tags` (many-to-many). I only know the tags’ IDs but not their respective author (see below).

```go
type Project struct {
	Model
	AuthorID uint
	Tags     Tag[]
}

type Tag struct {
	Model
	AuthorID uint
	Name     string
}
```

The following snippet will not work, since `AuthorID` will be upserted to `0` on `Tag`, resulting in foreign key constraint violations on the `author_id` field:

```go
tags := make([]Tag, len(tagIDs))
for i, tagID := range tagIDs {
	  tags[i] := Tag{Model: Model{ID: tagID}} // AuthorID is unknown here
}
project.Tags = tags
```

I want to avoid an extra roundtrip to fetch the tags from the database. Also, since the tags won't change, upserting them is redundant.

I also tried `Omit("Tags")`, but here, no entries will be added to the `project_tags` table, which is not what I want.

## The document you expected this should be explained

[Create-With-Associations](https://gorm.io/docs/create.html#Create-With-Associations)

## Expected answer

How do I avoid upserts on the `tags` table while making sure entries are added to the many-to-many `project_tags` table?

**Comment by jinzhu** [comment]
duplicated with #3605

**Comment by asterikx** [comment]
Aye, sorry!

**Comment by ItsLeeOwen** [comment]
#3605 looks like the opposite of what this issue is asking, no?
