### ISSUE TITLE
Primary key of embedded struct returned on insert

### ISSUE THREAD

**Issue by Pourqavam** [go-gorm/gorm#3716]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/198

## Description
Suppose we have two structs like this (**embedded struct also used for other queries separately**):
```go
type User struct {
	ID         int `gorm:"primaryKey"`
	Name       string
	CompanyID  int

	Company    *Company `gorm:"embedded;embeddedPrefix:com"`
}

type Company struct {
	ID        int `gorm:"primaryKey"`
	Name      string
}
```
There is two problems on insert, **first** Company fields included in insert, we can fix this with select fields but it's pain if the number of fields is large, **second**, insert statement returns two ids with "RETURNING "comid","id"" (ERROR: column "comid" does not exist)
As a suggestion if the entire of an inner struct can be ignored via Omit("Company") and even the fields of inner struct can be ignored like Omit("Company.Name"), it can solve multiple problems and its nice.

**Related issues:**
https://github.com/go-gorm/gorm/issues/3605
https://github.com/go-gorm/gorm/issues/3632

Please don't close the issue quickly :(

**Comment by jinzhu** [comment]
I have clearly told you use field permission to do the job, please read document

https://gorm.io/docs/models.html#Field-Level-Permission

**Comment by Pourqavam** [comment]
@jinzhu 
I have clearly told "embedded struct also used for other queries separately", i can't use field permissions on embedded struct fields.

**Comment by jinzhu** [comment]
So you `Company`'s `ID` field is useless for `User`, extract the common stuff, and embedded it into `User` and `Company`
