### ISSUE TITLE
Soft delete with Where and without PK updating soft deleted records

### ISSUE THREAD

**Issue by Hellysonrp** [go-gorm/gorm#3720]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/199

## Description

If we want to delete, for example, every `Pet` from a `User`, we'd do something like this:

```go
DB.Where(Pet{UserID: &user.ID}).Delete(Pet{})
```

The resulting SQL would be something like this:

```sql
UPDATE `pets` SET `deleted_at`="2020-11-04 11:28:09.499" WHERE `pets`.`user_id` = 1
```

Note that ALL pets with `user_id = 1` will have its `deleted_at` field updated, including already soft deleted records.
My suggestion is to add the `DeletedAt` in the `WHERE` clause, resulting in something like this:

```sql
UPDATE `pets` SET `deleted_at`="2020-11-04 11:28:09.499" WHERE `pets`.`user_id` = 1 AND `deleted_at` IS NULL
```

In my opinion, even if the primary key is informed, if the record is already soft deleted, the `deleted_at` field must not be updated.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
