### ISSUE TITLE
v2 Raw().Pluck() is not backward compatible with v1

### ISSUE THREAD

**Issue by ansel1** [go-gorm/gorm#3722]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/200

## Description

Pluck() seems to have a breaking change from v1 which is not mentioned in the release notes.  When using Raw(...).Pluck() into a slice of primitives, you now (in v2) must also use Model() or Table().  This was not required in v1.  And when using Table(), it doesn't seem to matter what value you use.  You can call Table() with a table name that doesn't exist, but it will still make the Pluck() work.

It would be good to either mention the breaking change in the release notes, or relax the requirements on Pluck() to work more like v1 (since it seems the table name isn't actually used in this case).

**Comment by jinzhu** [comment]
You can write it like `DB.Raw(`select name from users`).Scan(&names)` in v2, and honestly I don't expected user use `Raw` with `Pluck` in V1 ;(

**Comment by zenovich** [comment]
> You can write it like `DB.Raw(`select name from users`).Scan(&names)` in v2, and honestly I don't expected user use `Raw` with `Pluck` in V1 ;(

Probably it could be fixed by always setting clause.Column.Raw to true in Pluck().
Note it is very annoying and strange to write `Pluck("1 AS 1", ...)` instead of `Pluck("1", ...)` everywhere, especially when there are db mocks for each query... It's not obvious what was the idea, because "1 AS 1" stays unquoted while "1" becomes "`1`" :/

**Comment by zenovich** [comment]
@jinzhu

**Comment by zenovich** [comment]
Another possibility of fixing this would be accepting clause.Expr as the column name in Pluck()

**Comment by zenovich** [comment]
Also, it looks like the column name given to Pluck() is ignored if Select() is used in the chain.
