### ISSUE TITLE
Gorm returning deleted values for no reason

### ISSUE THREAD

**Issue by Ometecuthli** [go-gorm/gorm#3723]
I am using Gorm (Golang) and for some reason without making changes to my code, it starts returning  deleted rows along the not-deleted rows. I have searched on the internet for hours but I am unable to find a reason.

    err := db.Find(&subscribers).Error
    if err != nil {
        writer.WriteHeader(http.StatusBadRequest)
        return
    }

The above code will return deleted plus not-deleted users back. In the past, it would only return not-deleted users.

Can anyone explain to me what might be wrong or where to look?

I dont want to explicitly add .Where("deleted_at is null") to every query.

If I run my other projects, then this does **NOT** happen which is kinda strange right?

When I log my query it just says "SELECT * FROM "newsletter_subscribers"" without the "deleted_at" part.

**Comment by gostega** [comment]
Also having this issue, very frustrating. Adding ` .Where("deleted_at is null") ` seems to have no effect.
