### ISSUE TITLE
Logger is not completely replaceable

### ISSUE THREAD

**Issue by ansel1** [go-gorm/gorm#3724]
## Describe the feature

The gorm.io.gorm.logger package has three package variables: Discard, Default, and Recorder.  It doesn't seem to be possible to replace them all with custom loggers.  Discard and Default can be replaced, but Recorder can't be (it's a variable of a private type).  Recorder is initialized with a struct that wraps the logger in the Default variable, but it's not possible to replace Default before Recorder is initialized.

**Comment by jinzhu** [comment]
You should customize the logger like https://gorm.io/docs/logger.html, and just ignore the `Discard`, `Recorder`
