### ISSUE TITLE
Find query, consider deleted_at column in many_to_many association table. GORMv1

### ISSUE THREAD

**Issue by vaibhavkhl** [go-gorm/gorm#3726]
## I have a deleted_at column in association table as well. This table we have created and it wasn't created by gorm automatically. I am not able to exclude deleted at results from find query. Do I need to write custom query or is it possible using gorm methods?

```
type User struct {
	gorm.Model
         Languages []Language`gorm:"many2many:user_languages"`
}

// User struct as database table
type Langauge struct {
        Users []User`gorm:"many2many:user_languages" `
	DeletedAt *time.Time
}

// UserLanguage struct; many-to-many user-role mapping as database table
type UserLanguages struct {
	Id     uint `gorm:"primary_key" json:"id"`
	UserID string
	LangaugeID int
        DeletedAt *time.Time
}

//Query
s.db.Model(&user).Association("Languages").Find(&user.Languages)
```

## The document you expected this should be explained

https://v1.gorm.io/docs/associations.html

## Expected answer

Gorm query or do I need to write custom query?

**Comment by jinzhu** [comment]
override the join table handler
