### ISSUE TITLE
How to use FindInBatches to modify the query result?

### ISSUE THREAD

**Issue by NetLabFox** [go-gorm/gorm#3734]
[The PR for this issue](https://github.com/go-gorm/playground/pull/206)

## Your Question
```Go
var results []Ssldomainlist
result := db.Where("status = ?", 0).FindInBatches(&results, 100, func(tx *gorm.DB, batch int) error {	
		for i := range results {
                       // batch processing found records
			results[i].Status = 1
		}
		tx.Save(&results)
		fmt.Println(tx.RowsAffected) // number of records in this batch

		fmt.Println(batch) // Batch 1, 2, 3
		if tx.Error != nil {

			fmt.Println(tx.Error)
		}
		// returns error will stop future batches
		return nil
	})
	fmt.Println(result.Error)        // returned error
	fmt.Println(result.RowsAffected) // processed records count in all batches
```
I have 10000 records want to set status as 1 after some process.

I am curious why these parameter  **tx.RowsAffected as 200** and the **result.RowsAffected as 5000**.

I think tx.RowsAffected and result.RowsAffected should be 100 and 10000.

If i run these code again, the console will show the **result.RowsAffected as 2500**. 

This means that only half of all changes will take effect each time

## The document you expected this should be explained
Hope the Sample of FindInBatches can be more complete.

The following sample program is FindInBatches in the Advanced Query page
```Go
// batch size 100
result := db.Where("processed = ?", false).FindInBatches(&results, 100, func(tx *gorm.DB, batch int) error {
  for _, result := range results {
    // batch processing found records
  }

  tx.Save(&results)

  tx.RowsAffected // number of records in this batch

  batch // Batch 1, 2, 3

  // returns error will stop future batches
  return nil
})

result.Error // returned error
result.RowsAffected // processed records count in all batches

--



```
[https://gorm.io/docs/advanced_query.html#FindInBatches](url)

## Expected answer
Can anyone point out the bugs in my code?

**Comment by jinzhu** [comment]
Please submit a playground PR that could reproduce your issue, thank you.

**Comment by NetLabFox** [comment]
[The PR for this issue](https://github.com/go-gorm/playground/pull/206)

**Comment by jinzhu** [comment]
Hi @NetLabFox 

Fixed, thank you for your report.
