### ISSUE TITLE
Upsert/Save results in zero value for CreatedAt time

### ISSUE THREAD

**Issue by hbagdi** [go-gorm/gorm#3739]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/202

## Description

When doing upsert operations, CreatedAt field resets to zero value in the database. This happens only when the record was already present before performing a `db.Save()`.

**Comment by jinzhu** [comment]
`Save` save all fields by default https://gorm.io/docs/update.html#Save-All-Fields

**Comment by hbagdi** [comment]
@jinzhu In that case, how do you implement an upsert operation correctly?

**Comment by night-codes** [comment]
I want to note that this behavior completely breaks the meaning of using automatically set time parameters. If CreatedAt is initialized to time.Now() during the creation of a record with Save(), then this value must be saved if the record exists.

**Comment by ikbenben** [comment]
Hi had this same issue and adding the `gorm:"<-:created` to my CreatedAt timestamp worked around the issue

**Comment by fragoulis** [comment]
Hello, 

According to the documentation [1][2][3] `CreatedAt` is a special field, that is ignored on update, including `Save`.

I realize that this may not be the actual case, but shouldn't it be reflected to the documentation somehow?

From what I understand, passing a model into `Save` it will update all the fields (including `CreatedAt`) but the behavior is _hidden_.

[1] https://gorm.io/docs/update.html#Save-All-Fields
[2] https://gorm.io/docs/models.html#gorm-Model
[3] https://gorm.io/docs/models.html#Creating-x2F-Updating-Time-x2F-Unix-Milli-x2F-Nano-Seconds-Tracking
