### ISSUE TITLE
executes delete with incorrect table name after execute Session and InstanceSet.

### ISSUE THREAD

**Issue by soranoba** [go-gorm/gorm#3741]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/203

## Description

GORM executes delete with incorrect table name after execute Session and InstanceSet.

```go
// broken case
DB = DB.Session(&gorm.Session{})
DB = DB.InstanceSet("key", "value") 
```

```go
// correct case
DB = DB.Session(&gorm.Session{})
DB = DB.InstanceSet("key", "value") 
DB = DB.Debug()
```

```go
// correct case
DB = DB.Session(&gorm.Session{})
DB = DB.Debug()
```

I want to keep the value held in InstanceSet only after executing Session.
But when I do that I face this problem.

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety

**Comment by soranoba** [comment]
@jinzhu 
Thank you for the link. I didn't read it.

[The full list](https://github.com/go-gorm/gorm/blob/1e241aa6455fd821102bfce366d47a646b71161e/chainable_api.go) doesn't seem to contain InstanceSet. 
Is InstanceSet contain here?

**Comment by jinzhu** [comment]
Ah the list is not full enough, also refer https://github.com/go-gorm/gorm/blob/c1bb8e4551a5b371fbc637802a56e15b421f31f7/gorm.go#L224-L246

**Comment by soranoba** [comment]
Ok, I see.
Many thanks :)
