### ISSUE TITLE
batch update by object list

### ISSUE THREAD

**Issue by waiting0729** [go-gorm/gorm#3742]
## Your Question

gorm version: gorm.io/gorm v1.20.6

I want to batch update some fields of the object list. Like:
`model.objects.bulk_update(list, fields)`
in python, but I can't find a way in the documentation.
Can anyone help me? thank you very much

**Comment by jinzhu** [comment]
https://gorm.io/docs/create.html#Upsert-On-Conflict

the last example

**Comment by imthaghost** [comment]
Is this still a valid answer?
