### ISSUE TITLE
Get association objects with order from JoinTable 

### ISSUE THREAD

**Issue by EgorkZe** [go-gorm/gorm#3743]
## Your Question

I have two models

```
type Holder struct {
    OwnModel
    Title         string `json:"title"`
    Exercises []Exercise `json:"exercises" gorm:"many2many:holder_exercises_new;"`
}
```

```
type Exercise struct {
    OwnModel
    Title         string `json:"title"`
}
```
And join table

```
type HolderExercisesNew struct {
    OwnModel
    HolderID   int64 `json:"holder_id"`
    ExerciseID int64 `json:"exercise_id"`
    Order      int64 `json:"order"` // my custom param for ordering
}
```
I want to preload Exercises to Holders but ordered by "Order" param in join table. For example i have

```
holders := []models.Holder{}
database.Preload("Exercises").Find(&holders)
```
It gives me holders with embedded exercises but in random order. 

## Expected answer

Is there a way to get Exercises in order set in join table?

**Comment by BeanWei** [comment]
ha, i need it same with you! i think some association model should support it, hasmany、many2many

**Comment by EgorkZe** [comment]
I thought it is trivial task to get ordered associations. Maybe who knows other ways to reach expected result?

**Comment by EgorkZe** [comment]
@BeanWei I found temp solution. In my case i put new param to Holder model
`
ExercisesIDS pq.Int64Array `gorm:"type:integer[]" json:"exercises_ids"`
 `
And i save exercises ids to Holder. After that in my client i need make some mapping, i mean i reorder Exercises array based on ids array. 
But anyway i wish more native solution with gorm

**Comment by BeanWei** [comment]
@EgorkZe 
I think we should be able to write a callback to do a custom order, which feels weird to put `order:something` into gorm tag. I’m going to try that later. In my case, i maybe have many has-many association models, so i prefer to do this by writing a callback

**Comment by AlexandrMoshnyatsckyj** [comment]
@EgorkZe examle for this 
```
db.Preload("Orders", func(db *gorm.DB) *gorm.DB {
  return db.Order("orders.amount DESC")
}).Find(&users)
// SELECT * FROM users;
// SELECT * FROM orders WHERE user_id IN (1,2,3,4) order by orders.amount DESC;
```

**Comment by EgorkZe** [comment]
@AlexandrMoshnyatsckyj It is not answer for my question. In your case it is pretty easy to order by field in concrete model. So in my case i want to order by field in JoinTable

**Comment by AlexandrMoshnyatsckyj** [comment]
@EgorkZe 
db.Preload("Orders", func(db *gorm.DB) *gorm.DB {
  return db.Order("orders.{next_table}.{next_table}.{field} DESC") // so simple
}).Find(&users)

**Comment by EgorkZe** [comment]
@AlexandrMoshnyatsckyj Have you read my question?
For example again:

```
type User struct {
    OwnModel
    Orders []Order `gorm:"many2many:user_orders;"`
}
type Order struct {
    OwnModel
    Title         string `json:"title"`
}

type UserOrder struct {
    OwnModel
    UserID   int64 
    OrderID int64 
    Order      int64  // my custom param for ordering
}
```

So i need to get all Users with Orders in specified "order" from JoinTable

**Comment by AlexandrMoshnyatsckyj** [comment]
db.Preload("Orders", func(db *gorm.DB) *gorm.DB {
  return db.Order("user_orders.{field}")
}).Find(&users)

**Comment by EgorkZe** [comment]
@AlexandrMoshnyatsckyj It is not working, did you try it yourself?

**Comment by jinzhu** [comment]
Join the `join table` and order by its column.

**Comment by loeffel-io** [comment]
> Join the `join table` and order by its column.

this does not work in the following scenario:

I do have a query like with a `db.Preload(Permissions)` (many2many)

```sql
SELECT roles.updated_at,roles.rid,roles.project_rid,roles.display_name,roles.created_at,roles.id FROM `roles` WHERE (roles.project_rid,roles.rid) IN (('mindful','test')) ORDER BY `roles`.`id` LIMIT 1"
```

this auto generates the following query which make sense:

```sql
SELECT * FROM `role_permissions` WHERE `role_permissions`.`role_id` = 2
```

now i want to join the `join table` and order by its column and add the join to my `Permissions` preload

```sql
SELECT permissions.id,permissions.rid FROM `permissions` LEFT JOIN role_permissions ON role_permissions.permission_id = permissions.id WHERE `permissions`.`id` IN (1,2) ORDER BY role_permissions.order
```

the issue with this is that i need also add the `role_id = 2` to my join, otherwise i will get duplicates, BUT i never has access to `role_id = 2`.

How to solve this? @jinzhu
