### ISSUE TITLE
Default DB type for Go type

### ISSUE THREAD

**Issue by kkotowick** [go-gorm/gorm#3744]
## Your Question

Is there any way to modify the default DB type mapping with Go types? In GORM v1, `string` mapped to `VARCHAR(255)`, but it now appears to map to `LONGTEXT`. This is causing all sorts of issues in my migration, which consists of many models with hundreds of `string` fields.

I've seen the other issues with answers saying to use `gorm:"size:{number}"`, but I'd still like a way to set the default mapping.

## The document you expected this should be explained

[Customize Data Types](https://gorm.io/docs/data_types.html)

## Expected answer

Details on how to set the default Go/DB type mappings.

**Comment by BeanWei** [comment]
https://gorm.io/docs/connecting_to_the_database.html

` DefaultStringSize: 256, // default size for string fields` maybe you need

```go
db, err := gorm.Open(mysql.New(mysql.Config{
  DSN: "gorm:gorm@tcp(127.0.0.1:3306)/gorm?charset=utf8&parseTime=True&loc=Local", // data source name
  DefaultStringSize: 256, // default size for string fields
  DisableDatetimePrecision: true, // disable datetime precision, which not supported before MySQL 5.6
  DontSupportRenameIndex: true, // drop & create when rename index, rename index not supported before MySQL 5.7, MariaDB
  DontSupportRenameColumn: true, // `change` when rename column, rename column not supported before MySQL 8, MariaDB
  SkipInitializeWithVersion: false, // auto configure based on currently MySQL version
}), &gorm.Config{})
```
