### ISSUE TITLE
Composite primary key update failure when calling Save()

### ISSUE THREAD

**Issue by markvaltix** [go-gorm/gorm#3745]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/204

## Description

When a db model object has a composite primary key, db.Save() fails when trying to update an existing record if one of the primary keys has a default value. The gorm code seems to do create even if only one primary key has a zero value.

finisher_api.go - Save():

```
case reflect.Struct:
    if err := tx.Statement.Parse(value); err == nil && tx.Statement.Schema != nil {
        for _, pf := range tx.Statement.Schema.PrimaryFields {
            if _, isZero := pf.ValueOf(reflectValue); isZero {
                tx.callbacks.Create().Execute(tx)
                return
            }
        }
```

Gorm v1 does not have this issue.

**Comment by jinzhu** [comment]
I would suggest to use the Upsert feature, which sounds a better implementation

 https://gorm.io/docs/create.html#Upsert-On-Conflict

**Comment by markvaltix** [comment]
@jinzhu thanks, I will test Upsert in place of where I used to call Save. However, this Save behavior is a regression from v1, and I believe it is a valid issue.

**Comment by jinzhu** [comment]
> However, this Save behavior is a regression from v1, and I believe it is a valid issue.

I think the current behavior should be the correct one, a primary key should never be a zero value.

**Comment by phanirithvij** [comment]
@jinzhu but how to do it for associations?
