### ISSUE TITLE
Support for Nullable Unsigned 64 bits Integer (uint64)

### ISSUE THREAD

**Issue by Thor-x86** [go-gorm/gorm#3746]
## Describe the feature

Seems like GORM didn't support nullable uint64 fields because of `sql` module limitation. Consider add **preloaded nullable types**?

## Motivation

In some cases at production, number of rows can be astronomically huge. In order to prevent index overload, it would be best if GORM support nullable uint64.

## Related Issues

On previous issue, @andrei-dascalu asked for [nullable integer](https://github.com/go-gorm/gorm/issues/3561). However, `sql.NullInt64` only for signed integer, not unsigned.

**Comment by jinzhu** [comment]
Just write a Scanner/Valuer with uint64 support

**Comment by Thor-x86** [comment]
> Just write a Scanner/Valuer with uint64 support

I know you're going to say that 🙂 So I built nullable package that covers almost all Golang's data types.

https://github.com/Thor-x86/nullable

It's fully support GORM by the way. Let me know if you're interested to integrate it into GORM source code. Thanks!

**Comment by jinzhu** [comment]
> I know you're going to say that 🙂 So I built nullable package that covers almost all Golang's data types.

👍 

> It's fully support GORM by the way. Let me know if you're interested to integrate it into GORM source code. Thanks!

I would like to keep it as a separated  repo to make the GORM core tiny, thank you.
