### ISSUE TITLE
Automigrat hanges for large tables

### ISSUE THREAD

**Issue by khanakia** [go-gorm/gorm#3747]
I have users table and i added new column but it hangs and the reason for that `db.AutoMigrate(&User{})`  function runs the `select * from "users"` unnecessarily. Why migration needs to select all the records from the table ?

```
2020/11/14 03:13:42 /home/uxm/uxmgo/vendor/gorm.io/driver/postgres/migrator.go:105
[12.151ms] [rows:0] SELECT count(*) FROM information_schema.tables WHERE table_schema =  CURRENT_SCHEMA() AND table_name = 'users' AND table_type = 'BASE TABLE'

2020/11/14 03:13:42 /home/uxm/uxmgo/pkg/auth/auth.go:137
[2.482ms] [rows:0] select * from "users"

// KEEPS HANGING 
```

**Comment by khanakia** [comment]
@jinzhu This is how i fixed I modified this file `/gorm.io/gorm@v1.9.19/migrator/migrator.go`  I just changed the select * from query to `select * from ? Limit 1` so it will work for **big tables**. Can you process the same changes in the package so i do not have override the code manually everytime ? 
```
func (m Migrator) ColumnTypes(value interface{}) (columnTypes []*sql.ColumnType, err error) {
	err = m.RunWithValue(value, func(stmt *gorm.Statement) error {
                // rows, err := m.DB.Raw("select * from ?", clause.Table{Name: stmt.Table}).Rows()
                // New Code
		rows, err := m.DB.Raw("select * from ? Limit 1", clause.Table{Name: stmt.Table}).Rows()
		if err == nil {
			columnTypes, err = rows.ColumnTypes()
		}
		return err
	})
	return
}
```

**Comment by jinzhu** [comment]
You codebase is out of date, `v1.9.19` is rc release of gorm v2

**Comment by khanakia** [comment]
Is `gorm.io/gorm v1.20.6` is the latest v2 ? If not then how do i do update to the later v2 ?
