### ISSUE TITLE
record not found Error when using FirstOrCreate()

### ISSUE THREAD

**Issue by JeffPHP** [go-gorm/gorm#3748]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/205

## Description

In Gorm V2, when using FirstOrCreate(), Gorm will trigger an ErrRecordNotFound error and log it as an error, even if we catch it.

It should definitely not be considerer as an ERROR. At best a WARNING, of even just an INFO.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.

**Comment by JeffPHP** [comment]
Thanks!!

**Comment by JeffPHP** [comment]
Thanks again for this. 

At the moment, waiting for a new release, records are not inserted. Do you think a new version integrating this bug fix will be released soon or should I better change it everywhere in my code to a custom First + Create ?

**Comment by jinzhu** [comment]
It will be release in this week.
