### ISSUE TITLE
How to get PrimaryKeyValue since migration?

### ISSUE THREAD

**Issue by eloo** [go-gorm/gorm#3749]
## Your Question

Hi, 
i'm currently migration some code to the new version but i cant find the new feature to get the primary key value like it was done in the v1.

With v1 the code looked like this. 
``` 
tx.NewScope(currentUser).PrimaryKeyValue()
``` 

But with v2 i'm not sure how the get the primary key value.
I've already seen some hint to use 
`tx.Statement.Schema.PrioritizedPrimaryField` but at least its now working as expected.

Also the migration guide seems to lack this as an breaking change. 

## The document you expected this should be explained

I would expect to have the migration documentation from gorm.io to have this listed.

## Expected answer
How i can replace my "old" implementation with a proper gorm v2 call

Thanks

**Comment by jinzhu** [comment]
You can make it works like this:

`tx.Statement.Schema.PrioritizedPrimaryFiel.ValueOf(tx.Statement.Dest)`
