### ISSUE TITLE
Preload 参数如果指定不存在的关联关系时，报异常

### ISSUE THREAD

**Issue by decker502** [go-gorm/gorm#3750]
Playground测试过，必现步骤很简单，故没有提交 pr

## Description

Preload 参数如果指定不存在的关联关系时，报异常 （runtime error: invalid memory address or nil pointer dereference），按理解应该返回明确的错误才对

    var result User
	if err := DB.Preload("NotExist").First(&result, user.ID).Error; err != nil {
		t.Errorf("Failed, got error: %v", err)
	}

**Comment by jinzhu** [comment]
Fixed.
