### ISSUE TITLE
how to use mysql user variable in Exec()?

### ISSUE THREAD

**Issue by Nowher2** [go-gorm/gorm#3754]
## Your Question
My code is like db.Exec("INSERT INTO table1 (name) values ('test');SET @id=@@IDENTITY;INSERT INTO table2 (table1_id) values (@id)").
The question is symbol '@'   is a marker parameter,how can i avoid '@' being replaced?

**Comment by jinzhu** [comment]
Please create a PR that failed to pass tests

**Comment by Nowher2** [comment]
This is not a gorm bug .How can I keep the "@ "symbol in the final generated sql statement?

**Comment by jinzhu** [comment]
> This is not a gorm bug .How can I keep the "@ "symbol in the final generated sql statement? @jinzhu

I still don't get your idea, a pull request would be helpful for that.

**Comment by airani** [comment]
I have the same problem
For example @jinzhu  https://stackoverflow.com/questions/10485769/mysql-update-a-column-with-an-int-based-on-order

**Comment by Airmole** [comment]
所以这问题解决了吗？我也遇到了。。。

**Comment by aaronangxz** [comment]
For those that are seeing this, we can do this https://gorm.io/zh_CN/docs/sql_builder.html#%E5%91%BD%E5%90%8D%E5%8F%82%E6%95%B0
```
db.Where("name1 = @name OR name2 = @name", sql.Named("name", "jinzhu")).Find(&user)
// SELECT * FROM `users` WHERE name1 = "jinzhu" OR name2 = "jinzhu"
```
Took me a while to find this :')
