### ISSUE TITLE
1.20 on conflict 

### ISSUE THREAD

**Issue by legend9999** [go-gorm/gorm#3756]
## Your Question

dbResult := spotDBClient.Clauses(
		clause.OnConflict{
			Columns: []clause.Column{{Name: "account_id"}, {Name: "coin_code"}},
			DoUpdates: clause.Assignments(map[string]interface{}{
				"available_balance": "available_balance + " + balance.String(),
				"updated_at":        time.Now(),
			}),
		},
	)
 在1.20.1中我想实现在更新时 a= a+?的功能这个clause应该怎么写呢

**Comment by legend9999** [comment]
INSERT INTO "user_asset" ("app_id","account_id","coin_code","available_balance","freeze_vol","created_at","updated_at","remark","id") VALUES (2,2,'USDT','2','0','2020-11-17 09:55:44.004','2020-11-17 09:55:44.004','',6734403627597628122) ON CONFLICT ("account_id","coin_code") DO UPDATE SET "available_balance"='available_balance + 2',"updated_at"='2020-11-17 17:55:43.995' RETURNING "id"

我上边的代码生成的语句是这样的

**Comment by jinzhu** [comment]
https://gorm.io/docs/update.html#Update-with-SQL-Expression

**Comment by legend9999** [comment]
多谢，解决了
