### ISSUE TITLE
use offset ，but dont work

### ISSUE THREAD

**Issue by lucyandsandy** [go-gorm/gorm#3757]
## use offset before find method to skip some records ,but find all recoreds returned , use debug to print sql find no offset condition,here is some code and result printed on console
![image](https://user-images.githubusercontent.com/37739323/99469670-36fb7780-297e-11eb-8a4e-22c062cc4fb4.png)

what i expected is there is offset condition before find,like the document said ,but the result i got is different
here is the document said
![image](https://user-images.githubusercontent.com/37739323/99469828-893c9880-297e-11eb-98ef-2084da8e0d10.png)

**Comment by jinzhu** [comment]
Please use latest code
