### ISSUE TITLE
autoIncrement doesn't work with BIGINT Unsigned on MySQL 8

### ISSUE THREAD

**Issue by JeffPHP** [go-gorm/gorm#3761]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/207

## Description

uint64 primaryKey (BIGINT UNSIGNED) doesn't create AUTO_INCREMENT on MySQL 8.0 despite autoIncrement annotation (doesn't work with "auto_increment" key either).

The only way to make it AutoMigrate with AUTO_INCREMENT is to add this annotation :
ID uint64 gorm:"primaryKey;autoIncrement;column:id;type:bigint unsigned AUTO_INCREMENT;" json:"id"

But then, if any Association, it will fail with this error:
"error": "Error occurred when migrating Profile:Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key"

**Comment by jinzhu** [comment]
https://gorm.io/docs/models.html#Fields-Tags

![image](https://user-images.githubusercontent.com/6843/99504071-f7528100-29b9-11eb-969b-fa02ee28005a.png)
