### ISSUE TITLE
ignore autoCreate and autoUpdate fields when using FullSaveAssociations

### ISSUE THREAD

**Issue by minionsong** [go-gorm/gorm#3762]
## Your Question

Those are my example models 
```go
type Result struct {
	Uk        int     `gorm:"primary_key;not null;autoIncrement"`
	Contents  string   
	CreatedDt int64   `gorm:"autoCreateTime"`
	UpdatedDt int64   `gorm:"autoUpdateTime"`

        AnswerList []Answer `gorm:"references:uk;foreignKey:result_uk"`
}
type Answer struct {
	Uk        int       `gorm:"primary_key;not null;autoIncrement"`
	ResultUk  int     
	Contents  string   
	CreatedDt int64   `gorm:"autoCreateTime"`
	UpdatedDt int64   `gorm:"autoUpdateTime"`
}
```
and then, I update `Result` object after set the session with FullSaveAssociations like below
```go
// I never change and never set CreatedDt or UpdateDt fields
db.Session(&gorm.Session{FullSaveAssociations: true}).Save(&result)
```

I expected that CreatedDt and UpdatedDt should not be in `ON DUPLICATED KEY UPDATE` clause. But those are in generated SQL
even I didn't setup those values in `result` object.

if I want to update with totally same `Answer` object in there, it always updated without any change (gorm only changes updatedDt)

Am I doing wrong with the session or autoCreateTime Tag? 

## The document you expected this should be explained

[FullSaveAssociations](https://gorm.io/docs/session.html#FullSaveAssociations)

## Expected answer

Tell me the right way please!

**Comment by jinzhu** [comment]
It doesn't make sense to ignore `CreatedAt`, `UpdatedAt` column when doing a `FullSaveAssociations` , but you could omit the fields with `Omit` right now.

**Comment by jinzhu** [comment]
e.g:

```go
db.Omit("Answer.CreatedAt", "Answer.UpdatedAt").Create(&result)
```
