### ISSUE TITLE
Docs: Search bar does not work on https://v1.gorm.io/docs/: all search results redirect to https://gorm.io/docs

### ISSUE THREAD

**Issue by EmilLaursen** [go-gorm/gorm#3767]
## Description

Using the search bar on [v1 of the documentation](https://v1.gorm.io/docs/) does not work. Clicking any search result will redirect you to the v2 of the documentation.

**Comment by jinzhu** [comment]
Yes, this a known issue, the search is powered by algolia, we can't fixed that unless setup another account for V1.
