### ISSUE TITLE
Please bring back Session.WithConditions

### ISSUE THREAD

**Issue by audricschiltknecht** [go-gorm/gorm#3768]
## Your Question

During the update from gorm v1.20.6 to 1.20.7 which is considered a patch update the `Session`'s `WithConditions` struct member was removed (commit https://github.com/go-gorm/gorm/commit/26504f5caeb8c31dff62e8ddab68cee6b85a6580#diff-3133f5a3c5ce0087b14a818cff68c205e4aa03eb83b4f0f7f06137ae2b4351ec).

## Expected answer

I think this should *not* have been a patch release but rather a major release (backward incompatible change).

Or please state clearly that gorm does not adhere to semantic versioning (which is ok, but need to be advertised).

**Comment by jinzhu** [comment]
Hi @audricschiltknecht 

Yeah, sorry for the breaking changes,  we turn on the `WithConditions` option to default as received many reports because of  forgot to enable this option, so this changes is considered to make everything clear to fix the current situation.

**Comment by gatspy** [comment]
Is WithConditions the same as NewDB?

**Comment by audricschiltknecht** [comment]
From what I understand, you need to reverse the value, ie. `NewDb = !WithConditions`

**Comment by jinzhu** [comment]
> From what I understand, you need to reverse the value, ie. `NewDb = !WithConditions`

Yes, I think the `NewDB` should not been common used, and most likely only be used when writing some plugins, so it should not be the default option that can cause confusion.
