### ISSUE TITLE
Is the "Begin" method a "New Session Method" or not ? 

### ISSUE THREAD

**Issue by MaximeWeyl** [go-gorm/gorm#3771]
## Your Question

Is the *Begin* method a **New Session Method** or not ? 

## The document you expected this should be explained

https://gorm.io/docs/method_chaining.html#New-Session-Mode

## Expected answer

Should be documented. 
As far as I understand GORM2's code, I think it is a New Session Method as it uses the Session method : 

`		
tx  = db.Session(&Session{Context: db.Statement.Context})
`

**Comment by jinzhu** [comment]
Hello,

The `Begin` methods is a `New Session Method`, will update the document, thank you.

> As far as I understand GORM2's code, I think it is a New Session Method as it uses the Session method :

Yes.
