### ISSUE TITLE
rows.Close() returns error

### ISSUE THREAD

**Issue by johnnychhsu** [go-gorm/gorm#3774]
## Your Question
Usually we would like to call close with defer like this
```
rows, err := db.Rows()
defer rows.Close()
for rows.Next() {
// some works
}
```
However, the error returned by Close() is not handled in this manner, and will be warned by the compiler.
Why not just ignore the error and not return that from Close()?

## The document you expected this should be explained
The docs explain the usage well, just want to know why we need the error here

## Expected answer
Maybe we can remove the returned error and thus can called with defer

**Comment by jinzhu** [comment]
the error `rows.Error` is from package `database/sql`
