### ISSUE TITLE
How to update `Belongs To` field value

### ISSUE THREAD

**Issue by BeanWei** [go-gorm/gorm#3778]
## Your Question

CompanyID change `1`  to `2`, but no anything changed.

Model :
``` go
type User struct {
    ID        uint
    Name      string
    CompanyID uint
    Company   Company
}

type Company struct {
    ID   uint
    Name string
}

user := User{
    ID: 1,
    Name: "bean",
    CompanyID: 1,
}
db.Session(&gorm.Session{FullSaveAssociations: true}).Save(&user)

user := User{
    ID: 1,
    Name: "bean",
    CompanyID: 2,
}
db.Session(&gorm.Session{FullSaveAssociations: true}).Save(&user)

```

`I hope user.CompanyID  is 2, but it keep 1. how can i do?`

## The document you expected this should be explained

`https://gorm.io/zh_CN/docs/belongs_to.html`

**Comment by jinzhu** [comment]
User's has a `Company` and it will use its primary key to replace the `CompanyID` if it has value, you can change the `Company` to zero.
