### ISSUE TITLE
id suffix problem

### ISSUE THREAD

**Issue by n0izn0iz** [go-gorm/gorm#3779]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/209

## Description

A field with the last word ending in "-id" will produce a wrong column name

For example "FooCID" will become "foo_c_id" instead of "foo_cid"

This can be worked around with the "column" tag but it's annoying

**Comment by jinzhu** [comment]
GORM will use the common initialisms to format the column name, CID is not in the linter's list  https://github.com/go-gorm/gorm/blob/66e8a72bf1b04a6b256c94708da68ddab498a5aa/schema/naming.go#L82-L84

With the latest commit, you are allowed to support this by changing `NamingStrategy`'s `NameReplacer`
