### ISSUE TITLE
Do I misunderstand method chaining?

### ISSUE THREAD

**Issue by shibumi** [go-gorm/gorm#3780]
## Your Question
Hi,

Imagine the following postgres table called `user`:

| id | user |
|----|-------|
| 1 | foo |
| 2 | bar |
| 3 | baz |

Now I compose a raw query like this:

```
prepared =db.Raw("select * from user")
```

When I run prepared.Rows() on this it works as expected. Now Imagine I want to chain this:
```
prepared = prepared.Offset(0).Limit(4)
```

What I expect is that the following query will get constructed: `select * from user offset 0 limit 4;`
What actually happens is that I still get all results from the first query. Do you have any explanation for this?

## The document you expected this should be explained

I expected this explained here: https://gorm.io/docs/method_chaining.html
What I would like to see is more complicated examples with Raw statements. At first I even tried chaining pure Raw statements like this:
```
prepared =db.Raw("select * from user")
prepared = prepared.Raw("Order user desc")
```

but this didn't work at all and I got errors like this one here:
```
ERROR: syntax error at or near "ORDER" (SQLSTATE 42601)
[78.484ms] [rows:-] ORDER BY 'user' 'desc'
```

What I assume is that gorm tried to execute order as single query without chaining it to the first raw, but in your documentation you clearly say that raw methods are chainable.

## Expected answer

Raw chaining and chaining other methods should work as expected and as mentioned in the documentation.

**Comment by shibumi** [comment]
Ok,
I investigated this a little bit further. And what works is using gorm methods directly:

```
prepared = db.Table("user").Select("*")
prepared = prepared.Offset(0).Limit(4)
```

The above chain works. The following Chain does not work:

```
prepared = db.Raw("Select * from user")
prepared = prepared.Offset(0).Limit(1)
```

The above query does not work as expected. Instead of getting only 1 result I get all results. I see in prepared.Statement.Clauses that the limit got applied with values offset=0 and limit=1 + I see in the SQL statement string builder the query "Select * from user" but somehow only the string builder gets executed and everything else gets ignored.


What I conclude is:

1. Raw statements seem not to be chainable , although the documentation says otherwise
2. Mixing Raw and Clause methods is not possible at all.

**Comment by jinzhu** [comment]
Yes, `Raw` should only be used when your want to write everything in Plain SQL

**Comment by shibumi** [comment]
@jinzhu shouldn't the documentation changed then? Because right now it states that Raw() commands are chainable..
