### ISSUE TITLE
Add support for SQL UNION Operator

### ISSUE THREAD

**Issue by moneszarrugh** [go-gorm/gorm#3781]
## Describe the feature

Gorm currently has no support for SQL UNION Operator https://www.w3schools.com/sql/sql_union.asp
## Motivation

This makes it possible to combine results from multiple tables and apply conditions/ordering them. More examples can be found on w3schools link above.
## Related Issues
There are no related issues.

**Comment by jinzhu** [comment]
Hello @moneszarrugh 

The following code is preferred for `UNION` support 

```go
DB.Raw("? UNION ?", DB.Select("name").Model(&user), DB.Select("age").Model(&user)).Scan(&newData)
```

**Comment by zenovich** [comment]
Since Order() is ignored for raw queries, it seems that sorted unions are impossible for now.

**Comment by zenovich** [comment]
The following workaround allows ordering:
```
.Table("(?) AS union_table", subQuery1).
Joins("UNION (?)", subQuery2)
```
