### ISSUE TITLE
When i use the SQL Expression,gorm return an error 

### ISSUE THREAD

**Issue by Fury76** [go-gorm/gorm#3782]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/210

## Description
my golang version is 1.14
gorm version is 1.20.5 or 1.20.7

When i use the SQL Expression, like this:
db.Model(&group).UpdateColumn("left_value", gorm.Expr("left_value + ?", 2))

the gorm return a error:
sql: converting argument $1 type: unsupported type gorm.SqlExpr, a struct

I hope it can be solved as soon as possible

**Comment by jinzhu** [comment]
the error message is pretty clear

![image](https://user-images.githubusercontent.com/6843/99926346-5a5a6400-2d7c-11eb-8d6b-401f842cad40.png)
