### ISSUE TITLE
The same expression, gorm2.0 returns an error, but gorm1.0 executes successfully

### ISSUE THREAD

**Issue by spencerlee96** [go-gorm/gorm#3783]
I encountered a problem in gorm2.0, a query statement returned an error, but when I copied the statement printed by the default logger in the console to the command line of the database for execution, it was executed correctly. 

The code is like:

		type Res struct {
			Flag bool
		}
		var res Res
		q := "select ('1' = ?::text) as flag"
		if err := app.DB.Raw(q, 1).Scan(&res).Error; err != nil {
			fmt.Println(err)
		}

The error message is:

		cannot convert 1 to Text; cannot convert 1 to Text

**Comment by jinzhu** [comment]
Maybe the https://github.com/jackc/pgx driver doesn't support that, change it back to https://github.com/lib/pq or try `app.DB.Raw(q, "1").Scan(&res)`
