### ISSUE TITLE
About Upsert on Conflict in Gorm v2

### ISSUE THREAD

**Issue by Eriice** [go-gorm/gorm#3784]
## Your Question

If the record doest exist, add a record, otherwise update the value when face the duplicate

In Gorm v1, I can do it by
```go
db.Set("gorm:insert_option", "ON DUPLICATE KEY UPDATE value=value+1").Create(&user).
```
How can I implement this in Gorm v2?

**Comment by jinzhu** [comment]
https://gorm.io/docs/create.html#Upsert-On-Conflict
