### ISSUE TITLE
How to handle associations count error

### ISSUE THREAD

**Issue by henrylusjen** [go-gorm/gorm#3787]
## Your Question
what is the appropriate way to handle associations count error?

## The document you expected this should be explained

Count is a finisher method (https://github.com/go-gorm/gorm/blob/master/finisher_api.go).
But associations count (https://gorm.io/docs/advanced_query.html#Count) don't return error like other association methods?

## Expected answer

1.  Is the Count method really don't have error?
1.  How do I know the when it return 0 is actually no association, or an unhandled error?

**Comment by jinzhu** [comment]
check the invalid association error like `db.Model(&user).Association("Languages").Error`

In other cases, no unexpected error should happen unless there is a database connection issue.

**Comment by henrylusjen** [comment]
```
db = db.Debug()
ass := db.Model(provider).Association("Items")
count := ass.Count()
err := ass.Error
if err != nil {
    // handle error
}
```
It works, thanks a lot.
