### ISSUE TITLE
遇到一个问题，出现了unsupported relations。。

### ISSUE THREAD

**Issue by feige84** [go-gorm/gorm#3790]
```
db.Preload("User").Find(&list)
```
这样执行是正常的。

```
go func(){
	db.Preload("User").Find(&list)
}()
```
这样的话，偶尔会报错

```
User: unsupported relations
```

不知道是什么原因。有没有遇到过的告诉一下。是什么原因？？

**Comment by zhaozong** [comment]
升级到最新版本就解决了

**Comment by jrkeen** [comment]
并发执行的时候，必现这个问题，不知道是使用的方式不对还是什么。

**Comment by zhaozong** [comment]
> 并发执行的时候，必现这个问题，不知道是使用的方式不对还是什么。

之前版本会panic，新版本改成了返回error，主要是relation是空的，不知道为什么没有把他们之间的关系解析出来

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html 应该是这个问题

**Comment by zhaozong** [comment]
> https://gorm.io/docs/method_chaining.html 应该是这个问题

确定使用了新的Session，还是会返回error
db = db.Where("xxx")
tx := db.Session(&gorm.Session{})
go func(){
    // 这里err依然不是nil
    err:=tx.Preload("xxx").Find(XXX).Error
    }()

**Comment by jrkeen** [comment]
> > https://gorm.io/docs/method_chaining.html 应该是这个问题
> 
> 确定使用了新的Session，还是会返回error
> db = db.Where("xxx")
> tx := db.Session(&gorm.Session{})
> go func(){
> // 这里err依然不是nil
> err:=tx.Preload("xxx").Find(XXX).Error
> }()

我也试过了，难道是使用方式不对么

**Comment by jinzhu** [comment]
建个 playground 的 pull request 我这边看看？

**Comment by zhaozong** [comment]
[https://github.com/go-gorm/playground/pull/211](url)
@jinzhu 看一下，应该是DATA RACE造成的，在没有缓存relations的情况下，直接并发使用preload

**Comment by jinzhu** [comment]
en，我已经知道原因了，因为第一次缓存了 schema, 但实际关联解析部分未处理完 https://github.com/go-gorm/gorm/blob/557b874ee3c9a6df9ffc5cd4a4bf2d89d3e788d5/schema/schema.go#L222


这时候另一个 routinue 请求过来，会取出未处理完的 schema, 触发的这个问题，应该只是在程序刚开始的时候会有问题，后续就不会了，我看看修复一下

**Comment by jinzhu** [comment]
@feige84 @zhaozong @jrkeen 最新 master 已修复，感谢！

**Comment by feige84** [comment]
作者辛苦了。给大家提供这么好的gorm。非常感谢。祝你工作顺利！

**Comment by zhaozong** [comment]
> @feige84 @zhaozong @jrkeen 最新 master 已修复，感谢！

https://github.com/go-gorm/gorm/blob/557b874ee3c9a6df9ffc5cd4a4bf2d89d3e788d5/tests/tests_test.go#L36

单测我跑过了，去掉这一句还是有问题，单测能通过的原因就是这里已经在缓存过了，这一行去掉，单独跑这一个单测还是会报原来的错。

**Comment by jinzhu** [comment]
> 就是这里已经在缓存过了，这一行去掉，单独跑这一个单测还是会报原来的错。

你的那 个代码有问题，里面的 tx 改了全局变量，下面的加个 tx := 就好
![image](https://user-images.githubusercontent.com/6843/100426382-ba7a3e80-30cb-11eb-9c3a-c7acd9bbcd8b.png)

**Comment by zhaozong** [comment]
> > 就是这里已经在缓存过了，这一行去掉，单独跑这一个单测还是会报原来的错。
> 
> 你的那 个代码有问题，里面的 tx 改了全局变量，下面的加个 tx := 就好
> ![image](https://user-images.githubusercontent.com/6843/100426382-ba7a3e80-30cb-11eb-9c3a-c7acd9bbcd8b.png)

我跑的是master上你提交的单测，把上面我说的注释掉你多跑几次试试

**Comment by jinzhu** [comment]
> > > 就是这里已经在缓存过了，这一行去掉，单独跑这一个单测还是会报原来的错。
> > 
> > 
> > 你的那 个代码有问题，里面的 tx 改了全局变量，下面的加个 tx := 就好
> > ![image](https://user-images.githubusercontent.com/6843/100426382-ba7a3e80-30cb-11eb-9c3a-c7acd9bbcd8b.png)
> 
> 我跑的是master上你提交的单测，把上面我说的注释掉你多跑几次试试

确实这个测试不讲武德，我跑了几次都正常，还有个边缘情况有问题，刚刚也修复了

**Comment by zhaozong** [comment]
啪的一下就修复了，很快啊

**Comment by keonjeo** [comment]
@jinzhu 谢谢大佬修复这个问题。我也遇到了
