### ISSUE TITLE
并发查询 Preload 导致 unsupported relations ？

### ISSUE THREAD

**Issue by jrkeen** [go-gorm/gorm#3792]
数据库中存在uniqueId = id 的数据。
并发执行 db.Where("uniqid = ?", id).Preload("Model").First(&model) 出现报错 unsupported relations。
非并发执行不会出现问题。

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html

**Comment by jinzhu** [comment]
If you believe this is still a problem, please create a playground pull request

**Comment by jrkeen** [comment]
thanks
