### ISSUE TITLE
Adding stacktrace to the error on DB

### ISSUE THREAD

**Issue by pielambr** [go-gorm/gorm#3793]
## Describe the feature

It would be useful if with the help of the `pkg/errors`, there was a stack trace added to the errors produced by Gorm. Now in the logs, it just shows "row not found", which is not really helpful if you have a lot of database methods.

Either in the `AddError`, `errors.New` could be used, but this might be breaking, since comparing errors with `err == gorm.ErrRecordNotFound` would not work any longer (you would have to use `errors.Is(error, error) bool`).

Another way would be if there was an error handler that was defined on the DB object that would be called every time there was an error, bit like a callback. The error could then be wrapped/handled by the user itself.

## Motivation

It's currently a bit difficult to debug where errors originate from without wrapping them in every and each database function.

## Related Issues

No related issues found for v2

**Comment by jinzhu** [comment]
sorry, but not going to integrate it.
