### ISSUE TITLE
Order clauses not append

### ISSUE THREAD

**Issue by xXLokerXx** [go-gorm/gorm#3795]
## Description

I'm updating the version of gorm from v1 to v2, this cause me some issues at begining because i'm also use gorm.Scope to do some raw query from interfaces (i already support this), also problems with funcs like order the one of i made this issue:

When i try to use the function "Clauses" to do a custom order (`field REGEXP 'value' DESC`) works well, but the problem is when i want to add more than 1 because only takes the last one as order clausule.

How i did it in v1:

`query = query.Order(gorm.Expr(fmt.Sprintf("%s DESC", field), value))`

here i'm genering `field` and `value` automatic in `for`, in example the values could be: `name REGEXP ?` and value is: `carlos` then with the old version this create the order sentence correctly and if i do exec this lines several times the order clausule is create good

How i try to do it in v2:

```
query = query.Clauses(clause.OrderBy{Expression: clause.Expr{SQL: fmt.Sprintf("%s", field), Vars: []interface{}{value}}})
```

Here the values are creating automatic as well, and works well if i exec only one time, if i try to exec 2 or more times this won't work.

i also try to do it as:

```
query = query.Clauses(clause.OrderBy{Expression: clause.NamedExpr{SQL: "name_es", Vars: []interface{}{"llave"}}},
		clause.OrderBy{Expression: clause.NamedExpr{SQL: "`products`.`name_en` LIKE ?", Vars: []interface{}{"key"}}})
```

i hope you have time to review this and i want to say that the new version is so fucking good i love it (even when i need to change a lot of code) keep doing this awsome work.

**Comment by jinzhu** [comment]
I think you are facing this issue https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety

**Comment by xXLokerXx** [comment]
This is what i've looking for, thanks
