### ISSUE TITLE
How to make Preload Where or Associations find query

### ISSUE THREAD

**Issue by BellZaph** [go-gorm/gorm#3796]
## Your Question

If i can do something like this

`user` `:=` `User{Languages: []string{"EN", "PT"}, Name: "Name"}`
`db.Create(&user)`

How to find it by Where Clause? (find users who can speak on PT)

`var users []User`
`query := User{Languages: []string{"PT"}}`
`db.Where(&query).Find(&users)`

## The document you expected this should be explained
I couldn't find about it in [associations](https://gorm.io/docs/associations.html)

## Expected answer

`var users []User`
`query := User{Languages: []string{"PT"}}`
`db.Where(&query).Find(&users)`
something like this

**Comment by jinzhu** [comment]
Preload

**Comment by take** [comment]
@BellZaph were you able to find out the way using Preload? 👀 I read the document but couldn't find out 🤔 ref: https://gorm.io/docs/preload.html
