### ISSUE TITLE
Disable auto FK creation when migrating for specific fields only

### ISSUE THREAD

**Issue by zaharidichev** [go-gorm/gorm#3798]
So I understand that there is `DisableForeignKeyConstraintWhenMigrating`. I wonder however can we have it set to `false`, and only disable FK creation for a specific field. Namely: 

```
type User struct {
  gorm.Model
  Name      string
  CompanyID int
  Company   Company
  AddressID int
  Address   Address
}

type Company struct {
  ID   int
  Name string
}

type Address struct {
  ID   int
  Address string
}
```

So I want an automatic FK created for `Address` but not for `Company`. Is there a way to do that? 

## The document you expected this should be explained
Anywhere in the docs really...
## Expected answer
Yes (and if yes how) | No (and why not)

**Comment by jinzhu** [comment]
I would suggest you disable the default `DisableForeignKeyConstraintWhenMigrating` and create the foreign key you want manually, like:

https://github.com/go-gorm/gorm/blob/6950007d6a68f6e5bd3f2295152a0e8f148451cc/migrator/migrator.go#L119-L122
