### ISSUE TITLE
Automigrate all structs automatically

### ISSUE THREAD

**Issue by leebrooks0** [go-gorm/gorm#38]
Is it possible to automigrate all structs automatically?

Currently it seems like the name of each struct to migrate needs to be passed to this function https://github.com/jinzhu/gorm/blob/690cb1430c2e27011324c51826301a7daf728e65/main.go#L261

**Comment by zhangluwei1997** [comment]
Now, do you have a new method to solve it ? 
Thanks. @jinzhu
