### ISSUE TITLE
AfterCreate not firing when needed MySQL

### ISSUE THREAD

**Issue by AlessandroSechi** [go-gorm/gorm#3805]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/213

## Description

I expect
```
func (p *PersonAddress) AfterCreate(db *gorm.DB) error {
	db.Model(p).Where(p).Update("home", true)
	return nil
}
```
is executed after insert of `PersonAddress,` as documented [here](https://gorm.io/docs/hooks.html#Creating-an-object) but it is not what happens in MySQL. The query log is:

```
...

2020/11/28 19:27:23 /Users/alessandro/GolandProjects/playground2/main_test.go:50
[8.406ms] [rows:1] INSERT INTO `addresses` (`name`,`id`) VALUES ('First Address',1) ON DUPLICATE KEY UPDATE `id`=`id`

2020/11/28 19:27:23 /Users/alessandro/GolandProjects/playground2/main_test.go:34
[11.990ms] [rows:0] UPDATE `person_addresses` SET `home`=true WHERE `person_addresses`.`person_id` = 1 AND `person_addresses`.`address_id` = 1 AND `person_addresses`.`created_at` = '2020-11-28 19:27:23.207'

2020/11/28 19:27:23 /Users/alessandro/GolandProjects/playground2/main_test.go:50
[28.112ms] [rows:1] INSERT INTO `person_addresses` (`person_id`,`address_id`,`home`,`created_at`,`deleted_at`) VALUES (1,1,false,'2020-11-28 19:27:23.207',NULL) ON DUPLICATE KEY UPDATE `person_id`=`person_id`

2020/11/28 19:27:23 /Users/alessandro/GolandProjects/playground2/main_test.go:50
[66.557ms] [rows:1] INSERT INTO `people` (`name`,`id`) VALUES ('Joe',1)

...
```

**Comment by jinzhu** [comment]
I don't get your question, could you make the tests fail?

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/100688908-5eab0080-33be-11eb-92bf-1829378d7c9e.png)

Seems works for me, please create a failed PR if you believe there is any issue.

**Comment by AlessandroSechi** [comment]
> ![image](https://user-images.githubusercontent.com/6843/100688908-5eab0080-33be-11eb-92bf-1829378d7c9e.png)
> 
> 
> 
> Seems works for me, please create a failed PR if you believe there is any issue.

The `UPDATE` should be executed after the `INSERT`, as the hook used in my PR is `AfterCreate`

**Comment by jinzhu** [comment]
Oh, I see, the `UPDATE` SQL is actually executed *after* the `INSERT`, but the log's order is wrong.

The `INSERT`'s log is printed after finished all hooks methods.

**Comment by AlessandroSechi** [comment]
I updated my PR with proper tests. May you please look into it?

**Comment by AlessandroSechi** [comment]
Hey @jinzhu may you please look into it?
