### ISSUE TITLE
Value method in V2 not present

### ISSUE THREAD

**Issue by sebastianbuechler** [go-gorm/gorm#3806]
## Value method in V2

I am switching from GORM V1 to V2. When get a user record from the DB I used the Value method in order to return the value. However, this method is not available in V2.

My code looked like this (in combination with Fiber):
```
func UserGetByID(c *fiber.Ctx) error {
	id := c.Params("id")
	db := database.DBConn

	user := entities.User{}
	record := db.Preload("GeneralData").Find(&user, id)

	if record.Error != nil {
		return c.Status(500).SendString(record.Error.Error())
	}

      return c.JSON(record.Value)
}
```

What can I do to get this functionality in V2?

**Comment by jinzhu** [comment]
Just use the `user` here.

**Comment by sebastianbuechler** [comment]
I think this pattern does not work for cases like these:

```
func UserCreate(c *fiber.Ctx) error {
	db := database.DBConn

	user := &entities.User{}
	if err := c.BodyParser(user); err != nil {
		return c.Status(503).SendString(err.Error())
	}

	// Try to save the user in DB
	record := db.Create(&user)

	if record.Error != nil {
		return c.Status(404).SendString("User can not be saved in DB!")
	}
   return c.JSON(record.Value)
}
```
Why was the `Value `method removed? What can be used instead?

**Comment by jinzhu** [comment]
the `Value` is the value you passed in, here it is the `user`, if you don't want to use it, use the `result.Statement.Dest`

**Comment by sebastianbuechler** [comment]
Okay, thank you!
