### ISSUE TITLE
Can't get update dest struct info at BeforeSave hook function after v1.20.6

### ISSUE THREAD

**Issue by shintaro-uchiyama** [go-gorm/gorm#3807]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/214

## Description

I couldn't get db.Statement.Dest info at BeforeSave hook function when I call Updates function with struct.
It worked before gorm.io/gorm@v1.20.5.

I guess this change cause this issue.
https://github.com/go-gorm/gorm/commit/4009ec58163b97294633edc19f5d792546cd612c#diff-786fb85249356e0b2d6ef4efc0c31904c88bf8a9e63fc748493ad9c0aa82b7b6L11

Gorm set reflect value of db.Statement.Model at SetupUpdateReflectValue function, so we can't get reflect value of db.Statement.Dest at BeforeUpdate function.
https://github.com/go-gorm/gorm/blob/v1.20.6/callbacks/update.go#L15

**Comment by jinzhu** [comment]
Hello @shintaro-uchiyama 

Sorry for the problem, but I think the current behaviour sounds correct, for example, if you want to check current user's role has to been `admin` before change his role, then it should use the `model` value but not the updating value here, maybe you can use `AfterUpdate` or use db constraints https://gorm.io/docs/constraints.html or maybe check the updating attributes where get it.

Thank you.
