### ISSUE TITLE
About using v0.0.0 tag.

### ISSUE THREAD

**Issue by ngudeveloper** [go-gorm/gorm#3809]
## Your Question

I'm using `gorm.io/datatypes v0.0.0-20200806042100-bc394008dd0d`. It's working but after I upgraded to v1.0.0. I got an error `panic: interface conversion: driver.Value is string, not []uint8`. I'm trying to increase the version little by little to find out which commit is causing this error and then report a bug but how can I get those tags like `v0.0.0-20200806042100-bc394008dd0d`? I only saw v1.0.0.

```
	if v, _ := e.Value(); v != nil { // e is datatypes.JSON
		json.Unmarshal(v.([]byte), &xxxx)
	}
```

## Expected answer
How can I get those tags like `v0.0.0-20200806042100-bc394008dd0d`?

**Comment by jinzhu** [comment]
Please upgrade everything to latest, if it doesn't works, create a playground pull request.
