### ISSUE TITLE
Weird behaviour in transactions, it's not rolling back

### ISSUE THREAD

**Issue by anandsiddharth** [go-gorm/gorm#3811]
## Transactions are not working

I am trying to do a transaction and throw an error manually, still, the record is saved.
Go:1.15.5 darwin/amd64
Gorm: v1.20.7
Database: MySQL

## Code

```go
if err := db.Transaction(func(tx *gorm.DB) error {
	credit := &Transaction{
	     Amount:    t.Amount,
	     Type:      "cr",
	     Remarks:   "Refund issued: " + t.Reference,
	     Status:   "conf",
	     Reference: t.Reference + "_refund",
	     WalletID:  t.WalletID,
	}

        if err := db.Model(credit).Create(&credit).Error; err != nil {
		return err
	}

        return errors.New("mock error")

        // return nil
}); err != nil {
	return t, err
}
```
**I have returned mocked error just to test**

## Expected answer

Am I Doing something wrong? I believe that's what is in the documentation. Please let me know if I did it wrong.

**Comment by jinzhu** [comment]
```go
tx.Model(credit).Create(&credit)
```

**Comment by anandsiddharth** [comment]
oh thanks ❤️, silly mistake
