### ISSUE TITLE
SQLite using WAL and prepared statements

### ISSUE THREAD

**Issue by botastic** [go-gorm/gorm#3815]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/217

## Description

Expected Results the tests to run without errors when using prepared statements and setting the jornal mode to WAL

Enabling either prepared statements or WAL journal mode does work fine

**Comment by jinzhu** [comment]
Honestly I don't know what caused the problem, but I think this is not something could be resolved in GORM, maybe need to use some params to make it works.

Sorry for that.
