### ISSUE TITLE
GORM AutoMigrate forces a not null constraint on self-referencing foreign key in Postgres

### ISSUE THREAD

**Issue by prazeblaze** [go-gorm/gorm#3816]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/216

## Description

If a GORM model's primary key column type is one of the serial types and it has self-referencing foreign key, using GORM's AutoMigrate feature will force a not null constraint on the foreign key, even though the foreign key field isn't tagged with `not null`.

Using the AutoMigrate feature with this model will force a not null constraint on the `manager_id`, which results in Postgres throwing a not-null constraint error when inserting a new row with `null` `manager_id`:
```go
type User struct {
	ID        uint `gorm:"type:smallserial;primarykey"`
	Name      string
        ManagerID *uint
	Manager   *User
}
```

Changing the primary key's type to anything that isn't a `serial` type removes the forced not null constraint:
```go
type User struct {
	ID        uint `gorm:"type:smallint;primarykey"`
        ...
}
```

Edit:
Looking at the following generated SQL, I assume this is caused by GORM forcing the foreign key's column type to also be the exact same `serial` type instead of its `integer` equivalent. Tagging the `ManagerID` field with `type:smallint` does not have any effect on the generated SQL as the column type was still being forced as `smallserial`:
```sql
CREATE TABLE "users" ("id" smallserial,"name" text,"manager_id" smallserial,PRIMARY KEY ("id"),CONSTRAINT "fk_users_manager" FOREIGN KEY ("manager_id") REFERENCES "users"("id"))
```

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/100974152-c4da8380-3576-11eb-8629-56f7b705b19b.png)

Hi suggest you change the field's size to 16.

**Comment by jinzhu** [comment]
https://gorm.io/docs/models.html#Fields-Tags

**Comment by prazeblaze** [comment]
Thanks a lot for the help, you've pointed me in the right direction. Since I use an unsigned integer type I should change the field size `15` instead, based on [this line](https://github.com/go-gorm/postgres/blob/70e3bdf112557183a6c3caa831384f55445662c1/postgres.go#L118).
