### ISSUE TITLE
Method Chain Safety/Goroutine Safety not working

### ISSUE THREAD

**Issue by tsaikd** [go-gorm/gorm#3827]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/220

## Description

There are 2 test cases.

1. Query once to make sure query function is working.
2. Query multiple times in goroutines.

* Only sqlite3 passes all tests.
* mysql only passes the first test case
* postgres get panic

https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety

**Comment by jinzhu** [comment]
Seems not a GORM related issue, but nested transaction can't support goroutines.

![image](https://user-images.githubusercontent.com/6843/101269546-cee4c800-37aa-11eb-9858-bc5ee1279c52.png)
