### ISSUE TITLE
Large batch insert hangs with too many records in Postgres

### ISSUE THREAD

**Issue by rbren** [go-gorm/gorm#3828]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/221

Note the 10m timeout on Postgres.

## Description
When inserting a large number of records using batch insert, Gorm hangs for a long time. Not clear if it ever completes.

This can be averted using CreateInBatches, but it's unclear what a "good" batch size is. E.g. in my case, `100` works fine, but `1000` hangs. I have no way of knowing if a future PR (e.g. to add new columns) is going to tip me over a threshold and start hanging.

Previously, we'd been doing these inserts 1000 at a time using raw SQL, which worked well (we needed to limit to ~1000 due to the limit of 65535 max query parameters in a postgres query). But 1000 seems to be too much for Gorm.

**Comment by jinzhu** [comment]
https://gorm.io/docs/create.html#Batch-Insert set a batch size

**Comment by jinzhu** [comment]
> Previously, we'd been doing these inserts 1000 at a time using raw SQL, which worked well (we needed to limit to ~1000 due to the limit of 65535 max query parameters in a postgres query). But 1000 seems to be too much for Gorm.

The batch size based on your data size, there is no general rule

**Comment by rbren** [comment]
@jinzhu - I think this needs to stay open.

If the data size is too big for postgres to handle, at the very least, Gorm should return an error instead of hanging. This should be computable based on known limitations in Postgres.
