### ISSUE TITLE
Unable to use associations called the same way as a field in an embedded struct

### ISSUE THREAD

**Issue by k3a** [go-gorm/gorm#3829]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/222

## Description

Go makes it possible for a struct to embed another struct with the same field name but different type. Fields of the final struct type take precedence over fields inside structs that were embedded in the type.

See the playground example (valid Go code): https://play.golang.org/p/6dgHiKqZBXV

GORM should probably follow this mechanism.

Currently, if I annotate `XUserSpec`'s Languages as `gorm:"-"` and `XUser`'s Languages is annotated `many2many`, AutoMigrate works fine but many2many association doesn't work. Maybe other association types wouldn't work either (I tested many2many only).

If I used `Association("Languages").Replace(...)` instead of `Create`, GORM would work on the join table only half-way. It would  not make an `INSERT` statement. But it would still correnctly make DELETE statement similar to this one (deleting the complement of replaced languages):

```sql
DELETE FROM `x_user_speaks` WHERE `x_user_speaks`.`user_id` = "1" AND `x_languages`.`language_code` <> "en"
```

Without the missing INSERT, the association is not properly set up. It apparently ignores Languages because of `gorm:"-"` in the embedded struct `XUserSpec`.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
