### ISSUE TITLE
Linking 2 tables cause AutoMigrate in panic

### ISSUE THREAD

**Issue by shprotru** [go-gorm/gorm#3830]
## Your Question
I trying to use gorm and got a panic on AutoMigrate call, here is full [sample](https://gist.github.com/shprotru/772f61610fd19675f99e750b51692eb0)
Here is [no check](https://github.com/go-gorm/gorm/blob/master/schema/relationship.go#L443) for nil pointer on `primaryFields[idx]`

## The document you expected this should be explained
This [document](https://gorm.io/docs/many_to_many.html)

## Expected answer
Here is the error description you can put in PR where you can fix panic yourself: "error description".

**Comment by shprotru** [comment]
Reproducing: [go-gorm/playground#223](https://github.com/go-gorm/playground/pull/223)

**Comment by jinzhu** [comment]
invalid relation defined here, please refer  https://gorm.io/docs/many_to_many.html

![image](https://user-images.githubusercontent.com/6843/101277241-0759c580-37ee-11eb-9525-bfe43657f20e.png)


BTW, fixed the panic and returns an error now.
