### ISSUE TITLE
终于找到了组织，这数据库不用defer db.Close()？

### ISSUE THREAD

**Issue by zhangbest5** [go-gorm/gorm#3834]

**Comment by Xieyuschen** [comment]
个人猜测是`gorm`维护了一个连接池，初始化db之后所有的连接都由库来管理。所以不需要使用者手动关闭。但这个要看源码，我只是一个猜测。

**Comment by jinzhu** [comment]
> 个人猜测是`gorm`维护了一个连接池，初始化db之后所有的连接都由库来管理。所以不需要使用者手动关闭。但这个要看源码，我只是一个猜测。

是的

**Comment by zhangbest5** [comment]
感谢大神回复，感觉golang这些大神都能回复，真心佩服

**Comment by Xieyuschen** [comment]
拥抱社区，拥抱开源:)

**Comment by hessonsu** [comment]
所以 db,err:=gorm.Open(）  db 保存到单例就好了吗

**Comment by Xieyuschen** [comment]
> 所以 db,err:=gorm.Open(） db 保存到单例就好了吗

对，gorm维护了个连接池。注册单例之后就可以一直用。

**Comment by superDingda** [comment]
当程序退出是，gorm如何感知清理连接池的呢？

**Comment by kequeen** [comment]
原来如此
