### ISSUE TITLE
IsRecordNotFoundError not working as expected

### ISSUE THREAD

**Issue by dragonborngem** [go-gorm/gorm#3840]
## Your Question

I'm using Go 1.15.6 with gorm.io/gorm v1.20.6 .
A simple query such as 
`err := db.Where("tag_title = ?", conversationTagInput.TagTitle).First(&tag).Error`
My input will result "record not found" error,
But  gorm.IsRecordNotFoundError(err) return false. After look at source code, I found your lib compare 2 error instances
I tried 
`fmt.Println(errors.New("record not found") == errors.New("record not found"))`
But both return false on my machine and Go Playground. 

## Expected answer

So have I done anything wrong ? or this is problem with new go version or gorm ? . Tks

**Comment by jinzhu** [comment]
GORM doesn't provide the `IsRecordNotFoundError` method already.
