### ISSUE TITLE
Is it possible to dynamically group conditions?

### ISSUE THREAD

**Issue by pdavid31** [go-gorm/gorm#3842]
## Your Question

**Is it possible to dynamically group conditions?**

The Grouped Conditions in the documentation are hard coded, but this is not an option in my use case since the conditions are dependent on user input.

I tried using scopes, but this did not work.

```golang
type generalFilter struct {
	field     string
	operation string
	value     string
}

filters := []generalFilter{
	{
		field:     "call_sign",
		operation: "=",
		value:     "dh",
	},
	{
		field:     "channel",
		operation: "=",
		value:     "5k",
	},
}

var scopes []func(*gorm.DB) *gorm.DB

for _, f := range filters {
	scopes = append(scopes, func(filter generalFilter) func(*gorm.DB) *gorm.DB {
		return func(tx *gorm.DB) *gorm.DB {
			return tx.Where(filter.field+" "+string(filter.operation)+" ?", filter.value)
		}
	}(f))
}

return db.Where(db.Scopes(scopes...))
```

Output was:

```sql
SELECT * FROM x WHERE channel = '5k' AND call_sign = 'dh' AND (channel = '5k' AND call_sign = 'dh')
```

## The document you expected this should be explained

https://gorm.io/docs/advanced_query.html#Group-Conditions

## Expected answer

Expected output is:

```sql
SELECT * FROM x WHERE (call_sign = 'dh' AND channel = '5k')
```

**EDIT: Fixed scope creation in the loop**

**Comment by pdavid31** [comment]
Nevermind, I solved this problem.

The issue was in the code applying the scopes.

**Comment by rrupesh** [comment]
@pdavid31 could you please post a sample working code?

**Comment by pdavid31** [comment]
Hi @rrupesh,

I initially had some problems with scopes that where applied multiple times, so i just created an unscoped db session, applied the scopes to it and handed it to the Where clause.

This way it works, even though it's kinda hacky. Hope this helps you.

```go
scopes := []func(*gorm.DB) *gorm.DB{
	// ...
}

// create an unscoped session instance to apply the scopes separately
tx := db.Session(&gorm.Session{NewDB: true}).Unscoped()

// apply the scopes in a where clause
db.Where(tx.Scopes(scopes...))
```

**Comment by sergevonage** [comment]
Hi @pdavid31,

Interesting, I have same case and same problem, but your solution doesn't work me
```
func TestOR(t *testing.T) {
	db := dbSetup(t)
	dbOr1 := func(tx *gorm.DB) *gorm.DB {
		return tx.Or("id = ?", id1)
	}
	dbOr2 := func(tx *gorm.DB) *gorm.DB {
		return tx.Or("id = ?", id2)
	}
	var logs []models.Logs
	tx := db.Session(&gorm.Session{NewDB: true}).
		Unscoped()

	db.Where(tx.Scopes(dbOr1, dbOr2)).Find(&logs)
}

func dbSetup(t *testing.T) *gorm.DB {
...
        db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{
		Logger: newLogger,
	})
...
}
```
Produces just 
```
SELECT * FROM `logs`
```
instead of 
```
SELECT * FROM `logs`WHERE (id = '1111' OR id = '2222' )
```

**Comment by pdavid31** [comment]
@sergevonage
I see you found a solution in #5052, so since my workaround is now already one year old I should have a look at that one :sunglasses:

**Comment by rodrigovsilva** [comment]
Is there any example using old gorm `"github.com/jinzhu/gorm"`. Not even the basic example work with old version. It's a bit project and update to the newer version is a bit cumbersome at this moment.
