### ISSUE TITLE
Unique index breaking change

### ISSUE THREAD

**Issue by System-Glitch** [go-gorm/gorm#3846]
## Description

2416eabd3fd78eac5e5cfb549658109b4cdd356e

This commit changing "unique_index" to "uniqueIndex" is a breaking change. I would advise either a rollback of this change or supporting both syntax.

**Comment by shprotru** [comment]
Hi, @System-Glitch! It's `uniqueIndex` by [documentation](https://gorm.io/docs/models.html#Fields-Tags).

**Comment by System-Glitch** [comment]
@shprotru Oops sorry it looks like I haven't read the commit date properly.
