### ISSUE TITLE
GORM create's unneeded indexes on PK by default

### ISSUE THREAD

**Issue by shprotru** [go-gorm/gorm#3847]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/225

## Description

GORM, by default, always create unneeded indexes on primary key fields for postgres database tables, this should not be, because contradicts on good database design, primary keys already indexed by defaults.

**Comment by jinzhu** [comment]
this is the SQL created the Table, no index on primary key specified by GORM.

![image](https://user-images.githubusercontent.com/6843/101869779-32ac2e00-3bbb-11eb-95b4-759507fd0d93.png)
