### ISSUE TITLE
Error won't work on Find func

### ISSUE THREAD

**Issue by xXLokerXx** [go-gorm/gorm#3849]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/226

## Description

The error record not found is not working when `Find` func is used, also documentation says that this function will have it: https://gorm.io/docs/method_chaining.html#finisher_method

**Comment by jinzhu** [comment]
https://gorm.io/docs/query.html#Retrieving-a-single-object
`ErrRecordNotFound` only for `First`, `Last`, `Take`

**Comment by xXLokerXx** [comment]
thanks
