### ISSUE TITLE
new option for migrator: show upgrade plan without executing it

### ISSUE THREAD

**Issue by HurSungYun** [go-gorm/gorm#3851]
## Describe the feature

```
cfg := &gorm.MigratorConfig{
    PlanningMode: true,  // maybe other name 
}
m := db.Migrator(cfg)
if m.HasTable("users") {
    m.DropTable("users")
}

/*
    it prints upgrade plan (raw DDL query), but does not execute it.
*/
```

I can work on this when detail specification is confirmed

## Motivation

As disscussed in https://github.com/go-gorm/gorm/issues/3545

`DryRun` is not supported when using `Automigrate` or `migrator` because it does not support to fetch database information.

I believe many users don't want to run migration code without noticing what would be changed.

Adding new option similar to `DryRun` in migrator that supports to get a upgrade plan without executing it can be useful for these users.

## Related Issues

 https://github.com/go-gorm/gorm/issues/3545

**Comment by jinzhu** [comment]
Hello @HurSungYun 

Thank you for your suggestion, I was thinking the same thing recently, maybe we should follow this pattern to avoid the breaking changes.  https://www.sohamkamani.com/golang/options-pattern/

My main concern is does it make sense to make it to be a separate tool, then it can support more features like print auto migration SQL into a file or even manage migrations, converting SQL to struct... any idea?

**Comment by HurSungYun** [comment]
> Thank you for your suggestion, I was thinking the same thing recently, maybe we should follow this pattern to avoid the breaking changes. https://www.sohamkamani.com/golang/options-pattern/

Thanks. I'm gonna revise the interface later.

> My main concern is does it make sense to make it to be a separate tool, then it can support more features like print auto migration SQL into a file or even manage migrations, converting SQL to struct... any idea?

It makes sense migrator to be a separate tool. A javascript library can be [a good reference](http://knexjs.org/#Migrations-CLI). It supports CLI to manage migrations. Actually, I implemented something like that using GORM migrator to manage migrations.

`print auto migration SQL` and `manage migrations` are good features to support, but I doubt `converting SQL to struct` works well. It may have lots of stuffs to support all SQLs (Mysql, PostgreSQL, etc...) and I believe many extreme cases will be exists.

**Comment by HurSungYun** [comment]
Making a seperate tool can be useful for GORM users, but it's gonna be a huge feature :)

**Comment by jinzhu** [comment]
I am thinking which solution sounds better, if we provides an option for `Migrator`, maybe users need to keep changing the option in daily usage? if so, a separate tool sounds better, we could start from only support the `print auto migration SQL feature` .

**Comment by HurSungYun** [comment]
Like what you said, I prefer to make a separate tool. And I agree `print auto migration SQL` can be a good feature to start.

**Comment by jinzhu** [comment]
Cool, created repo https://github.com/go-gorm/cli and invited you, can you list some design details & development plans and we have a discussion later?

Thank you.

**Comment by HurSungYun** [comment]
Okay. I'll list them during holidays :)

**Comment by elliots** [comment]
This is what I put together to log (but not execute) the migration. Seems to work, but haven't looked very closely.

```golang
        tx := db.Begin()
	var statements []string
	tx.Callback().Raw().Register("record_migration", func(tx *gorm.DB) {
		statements = append(statements, tx.Statement.SQL.String())
	})
	if err := tx.AutoMigrate(model.Tables()...); err != nil {
		panic(err)
	}
	tx.Rollback()
	tx.Callback().Raw().Remove("record_migration")
	for _, s := range statements {
		fmt.Println(s)
	}
```

**Comment by c4s4** [comment]
> ```go
> tx.Callback().Raw().Remove("record_migration")
> ```

Note that this line raises a warning on PostgreSQL.
