### ISSUE TITLE
Problem with migrations while defining manually foreignKey and references

### ISSUE THREAD

**Issue by bgruszka** [go-gorm/gorm#3853]
## Your Question

I have three tables:

```go
type ShipmentProvider struct {
	ID   uint `gorm:"primaryKey"`
	Name string
	Code string
}
```

```go
type Shipment struct {
	SuborderID         uint `gorm:"primaryKey;autoIncrement:false"`
	Suborder           Suborder
	ShipmentProviderID uint `gorm:"not null;index"`
	ShipmentProvider   ShipmentProvider
	PickupPointID      sql.NullString
	AddressID          sql.NullInt32 `gorm:"index"`
	Address            Address
	LabelID            sql.NullInt32 `gorm:"index"`
	Label              *Label `gorm:"foreignKey:LabelID;references:ShipmentID"`
	State              ShipmentState
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          gorm.DeletedAt `gorm:"index"`
}
```

and 

```go
type Label struct {
	ShipmentID      uint     `gorm:"primaryKey"`
	Shipment        Shipment `gorm:"foreignKey:ShipmentID;references:SuborderID"`
	ParcelTracker   string
	ShipmentTracker string
	FileData        []byte `gorm:"type:bytea"`
}
```

and migrations defined for them:
```go
database.AutoMigrate(&model.ShipmentProvider{}, &model.Shipment{}, &model.Label{})

```

When I run to migrate these tables unfortunately I have an error:

> ERROR: relation "shipments" does not exist (SQLSTATE 42P01)
[21.950ms] [rows:0] CREATE TABLE "labels" ("shipment_id" bigserial,"parcel_tracker" text,"shipment_tracker" text,"file_data" bytea,PRIMARY KEY ("shipment_id"),CONSTRAINT "fk_labels_shipment" FOREIGN KEY ("shipment_id") REFERENCES "shipments"("suborder_id"))

## The document you expected this should be explained

https://gorm.io/docs/has_one.html
https://gorm.io/docs/belongs_to.html

## Expected answer

From what I understood with manually defining `foreignKey` and `references` on fields I should be able to do that and have it working, but unfortunately this doesn't work.

**Comment by adhip94** [comment]
@bgruszka Were you able to address this. Even I have one table already created in postgres DB and I am trying to insert a record in that table and I get the same error.

**Comment by Urento** [comment]
I have the same issue.

**Comment by rofleksey** [comment]
I have the same issue =)

**Comment by ilearnio** [comment]
Same here, happens when two table realte on each other

**Comment by ByPikod** [comment]
Same here

![model 1](https://github.com/go-gorm/gorm/assets/46069238/fc2741b9-dcb8-4c30-8b76-b72a7025b25c)
![model 2](https://github.com/go-gorm/gorm/assets/46069238/8674a9a3-92a2-4bb6-9362-bd12b7a726f2)

![error](https://github.com/go-gorm/gorm/assets/46069238/104dadb7-6f69-444d-8aad-6f254ea88068)

Is there any workaround or another valid issue about this topic?

**Comment by mftakhullaziz** [comment]
After i know this issue, i think java is better than golang
