### ISSUE TITLE
GORM not populating the `DeletedAt` field on calling object when SoftDelete

### ISSUE THREAD

**Issue by kevinkirkup** [go-gorm/gorm#3855]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/228

## Description

When deleting an object with DeletedAt field to soft delete it, the passing in object's `DeletedAt` field is not bing populated. The database is being updated correctly though.

### Expected behavior:
I would call `DB.Delete(&Something)` and `Something.DeletedAt` should have the value from the database.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
