### ISSUE TITLE
gorm.Expr() does not support subQuery

### ISSUE THREAD

**Issue by ban11111** [go-gorm/gorm#3857]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/230

## Description

When I use subQuery in Expr(), it throws me an error =====> sql: converting argument $2 type: unsupported type gorm.DB, a struct

**Comment by jinzhu** [comment]
Fixed, thank you for your report.

**Comment by Komorebi695** [comment]
Does that seem to be a problem?
