### ISSUE TITLE
在Create之后会产生两条SQL语句(INSERT与SELECT)

### ISSUE THREAD

**Issue by CyberLife-Markus** [go-gorm/gorm#3858]
## Your Question
Why do two SQL statements result from a single create operation?

## The document you expected this should be explained

```
db.Create(&data)
INSERT INTO....
SELECT ....
```
## Expected answer
How to make the select query not generated after create operation?
```
db.Create(&data)
INSERT INTO....
```

**Comment by jinzhu** [comment]
This is GORM V1's behaviour to preload default values, v2 has removed that. and you could disable it by remove the loading callback.
