### ISSUE TITLE
Deadlock occurs continuously when I batch insert

### ISSUE THREAD

**Issue by rickiey** [go-gorm/gorm#3862]
Deadlock occurs continuously when I batch insert

It's in a for loop,Approximately once a second, there are only a few data
```go
err := db.Conn.Clauses(clause.OnConflict{
		DoNothing: true,
	}).CreateInBatches(blks, 50).Error
	if err != nil {
		loggo.Error(err)
		return err
	}
```

log: 
{"level":"error","ts":"2020-12-16 17:12:54","file":"db_repository/messages.go:18","msg":"Error 1213: Deadlock found when trying to get lock; try restarting transaction"}

**Comment by rickiey** [comment]
sorry, I found that this is due to a database error caused by my concurrent insert. It's not gorm's error

**Comment by skyitachi** [comment]
> sorry, I found that this is due to a database error caused by my concurrent insert. It's not gorm's error

how to solve this problem, retry ?

**Comment by ss89** [comment]
@rickiey maybe also mentions which dbms was affected and in which version?
