### ISSUE TITLE
about sqlserver trigger

### ISSUE THREAD

**Issue by wikinleon** [go-gorm/gorm#3863]
hi :
when i use "updates"  the correct rowsAffected is not returned 

example:
tx:=db.Table("user").Where("id=?",100).updates(map[string]interface{}{"name","cloud"})

because of  trigger  rowsAffected return 4 but update is failed ,the return result is not what I expected, how to ignore trigger  execute result, thanks

## The document you expected this should be explained

i think  exec updates retrun 0 or 1  ignore trigger  rowsAffected

**Comment by jinzhu** [comment]
Please create a PR that can reproduce your issue.
