### ISSUE TITLE
"Type" tag is ignored when also a foreign key 

### ISSUE THREAD

**Issue by bokub** [go-gorm/gorm#3864]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/231

## Description

When doing the auto-migration of the following type (on MySQL)

```go
type User struct {
	gorm.Model
	Name      string `gorm:"type:varchar(64)"`
	CompanyID string `gorm:"type:varchar(64)"`
	Company   Company
}
```

The `name` field is created as a `varchar(64)`, as expected.

However, the `company_id` field, which has the exact same type / tag, is created as a `longtext` instead of a `varchar(64)`.

I guess it's because it's a foreign key.

More details in the playground PR

**Comment by jinzhu** [comment]
Hi,

Yes, it is by design, foreign key need to use the same data type of the referenced field's data type.

**Comment by jinzhu** [comment]
You can set company's primary key `ID`'s length to change the foreign key's data type.

**Comment by bokub** [comment]
That's right, using the tag `gorm:"size:64"` instead of `type` solves the problem :tada: 

Thanks a lot!
