### ISSUE TITLE
empty query results presented as error ("record not found")

### ISSUE THREAD

**Issue by noneymous** [go-gorm/gorm#3867]
Queries with 0 (zero) results are highlighted in red colors by GORM, similar to error messages. I find this quite annoying, as **it catches attention every time again** (though it's a totally legit result) and forces to verify time and again.

![grafik](https://user-images.githubusercontent.com/31357019/102506810-cd0ce580-4083-11eb-970f-bf3af23f2232.png)

**I believe only errors (independent of application semantics) should be highlighted in red!**

**I'm suggesting to:**
- change it to green colors (or maybe blue)
- but to leave the "record not found" text in purple. 

This way, it doesn't catch immediate attention, but can still be looked out for.

**Comment by noneymous** [comment]
This really doesn't need a playground link...

**Comment by jinzhu** [comment]
https://gorm.io/docs/query.html#Retrieving-a-single-object
