### ISSUE TITLE
transaction has already been committed or rolled back 

### ISSUE THREAD

**Issue by kobechen413** [go-gorm/gorm#3870]
## Expected answer

	tx := db.Begin()

	err := tx.Model(&user).Update("age = ?", 10).Error
	if err != nil {
         	tx.Rollback()
		return err
	}

	err = tx.Commit().Error
	if err != nil {
		return err
	}

	var user1 User
     
     // error = transaction has already been committed or rolled back 
	err = tx.Where("user_id = ?", user.UserID).Find(&user1).Error  
	if err != nil {
		fmt.Println("query err ", taskID, err)
		return err
	}

transaction has already been committed or rolled back

**Comment by jinzhu** [comment]
a transaction can be only used once
