### ISSUE TITLE
Inconsistent Timestamps

### ISSUE THREAD

**Issue by kevinkirkup** [go-gorm/gorm#3872]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/233

## Description

The timestamps that a returns on an object that is written to the database is inconsistent.
This includes all time fields including `CreatedAt, UpdatedAt, DeletedAt`.

It looks like the nanosecond precision is being truncated

**Comment by jinzhu** [comment]
database's time precision is not perfection

**Comment by kevinkirkup** [comment]
What!

**Comment by Lumexralph** [comment]
I am currently facing this issue, is there a way around it?

**Comment by pprishchepa** [comment]
It's because of minimum timestamp resolution, like 1 microsecond for PostgreSQL.
