### ISSUE TITLE
Polymorphism belongs to

### ISSUE THREAD

**Issue by remicaumette** [go-gorm/gorm#3877]
## Polymorphism belongs to

Hello, I try to have a polymorphic relation like that:

```go
TicketMessage struct {
  SenderType     string    `json:"senderType"`
  SenderID       uuid.UUID `json:"senderId"`
  AccountSender  *Account  `json:"sender,omitempty" gorm:"polymorphic:Sender;polymorphicValue:account"`
  CustomerSender *Customer `json:"sender,omitempty" gorm:"polymorphic:Sender;polymorphicValue:customer"`
}
```

But it's not working. I've checked in the documentation, nothing is said to do that.
There is a way to do this?
Thank you.

## The document you expected this should be explained

https://gorm.io/docs/belongs_to.html

## GORM Playground Link

https://github.com/go-gorm/playground/pull/234

**Comment by remicaumette** [comment]
https://github.com/go-gorm/playground/pull/234

**Comment by jinzhu** [comment]
this is not supported, you could only use polymorphism has one

**Comment by jinzhu** [comment]
After few days thought, not going to support this, hard to support the preloading feature for this kind of relationship, maybe you should define it in `polymorphism has one` style

**Comment by meruiden** [comment]
Im also looking for this functionality. instead of defining the polymorphic gorm attributes on the model without OwnerID and OwnerType I would like to  define this only on the model containing the OwnerID and OwnerType and not on the model it refers to.

**Comment by doganarif** [comment]
@meruiden Did you find solution like this?
