### ISSUE TITLE
Clause.In

### ISSUE THREAD

**Issue by sdghchj** [go-gorm/gorm#3881]
## Describe the feature

func (in IN) Build(builder Builder) {
	builder.WriteQuoted(in.Column)

	switch len(in.Values) {
	case 0:
		builder.WriteString(" IN (NULL)")
	case 1:
		if _, ok := in.Values[0].([]interface{}); !ok {

                        //此处通过反射判断如果是slice或者数组array，比如[]int  []string，需要能处理

			builder.WriteString(" = ")
			builder.AddVar(builder, in.Values[0])
			break
		}

		fallthrough
	default:
		builder.WriteString(" IN (")
		builder.AddVar(builder, in.Values...)
		builder.WriteByte(')')
	}
}

## Motivation

大多时候，集合元素类型是确定的，比如条件是某整数列里的值是否在[]int64中，希望Clause.In能直接处理。而不是要程序员每次都把确定类型的[]int64遍历转成[]interface{}

**Comment by jinzhu** [comment]
`[]interface{}{1}` generates SQL `id = 1`, `[]int{1}` will generate SQL like `id IN (1)`, it is a valid SQL, still works.
