### ISSUE TITLE
? in Select not be replaced to argument in v1.20.9

### ISSUE THREAD

**Issue by si9ma** [go-gorm/gorm#3889]
# GORM Playground Link
https://github.com/go-gorm/playground/pull/238

# Description
https://github.com/go-gorm/gorm/blob/ad8a5c0d1ace1b9608fdaaae920fe17ebb5cf32a/chainable_api.go#L96
In the v1.20.9, Select only replace ` ?` and `(?` to argument, this will cause some historical codes to not run correctly. 
eg. https://gorm.io/docs/query.html#Selecting-Specific-Fields. the `?` will not be replace to 42,  will cause a syntax error
```go
db.Table("users").Select("COALESCE(age,?)", "42").Rows()
// SELECT COALESCE(age,'42') FROM users;
```

I think it’s easy to ignore spaces when coding, only parse `?` is unreasonable

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
