### ISSUE TITLE
Incremental Counter for IDs

### ISSUE THREAD

**Issue by mr-northwatch** [go-gorm/gorm#3897]
## Describe the feature

A setting to disable the incremental counter for IDs, and instead use a UUID or a random number.

## Motivation

Incremental counters are bad for security because of enumeration, it would be helpful to not have to worry about that by having an easy way to switch to UUIDs or random numbers.

## Related Issues

https://github.com/go-gorm/gorm/pull/732

**Comment by jinzhu** [comment]
You can customize the db column type with tag `type`, also search issues for how to use uuid with GORM

**Comment by mr-northwatch** [comment]
Thanks, for anyone looking for this in the future I wound up with 
```
type Model struct {
    ID uuid.UUID `gorm:"primary_key;type:uuid;default:uuid_generate_v4()"`
}
```
