### ISSUE TITLE
How to define a marshal and unmarshal interface for a self-defined field type ?

### ISSUE THREAD

**Issue by sdghchj** [go-gorm/gorm#3898]
## Your Question

How to define a marshal and unmarshal interface for a self-defined field type

## The document you expected this should be explained

```
type Example struct {
	Env    json.RawMessage `gorm:"type:varchar(500)" json:"env,omitempty"`
}

```

I want to insert  a raw json text into a varchar(500) field, but failed.

**Comment by jinzhu** [comment]
refer https://github.com/go-gorm/datatypes as example.
