### ISSUE TITLE
SQL NullString in Where statement not being interpreted as <field> IS NULL in SQL.

### ISSUE THREAD

**Issue by omarhachach** [go-gorm/gorm#3899]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/242

## Description
When doing a Where clause with `sql.NullString` it will not add a `WHERE field IS NULL` to the query. I realize this is a limitation of you using zero/nil values to show a value doesn't exist in a field. But it would be nice to have a better way to have an IS NULL type kind of like what you have with the soft delete type `gorm.DeletedAt`

**Comment by omarhachach** [comment]
So I guess this a kind of feature request, because I understand this is a design limitation

**Comment by jinzhu** [comment]
Hello @omarhachach 

You could use map with a zero value, just make it works with `Valuer`

https://gorm.io/docs/query.html#Struct-amp-Map-Conditions

And will enhance the `Where` API to make it works like `Where(User{Nickname: sql.NullString{String: "Value", Valid: true}}, "Nickname")`

**Comment by jinzhu** [comment]
Added
```go
 Where(User{Nickname: sql.NullString{String: "Value", Valid: true}}, "Nickname")
```

**Comment by omarhachach** [comment]
The enhanced API would be great, since there 3 issues with using a map. The map won't have type safety, you can misspell the field, and it will do `field = NULL` not `field IS NULL` as is recommended in the SQL docs.

**Comment by jinzhu** [comment]
https://gorm.io/docs/query.html#Specify-Struct-search-fields

**Comment by omarhachach** [comment]
Oh, just in time! Very nice, thank you!

**Comment by omarhachach** [comment]
Do you have an ETA of when a tag including the new feature will be released?

**Comment by jinzhu** [comment]
About every 2 or 3 weeks
