### ISSUE TITLE
How to make a primary key field, readonly

### ISSUE THREAD

**Issue by gwuah** [go-gorm/gorm#3903]
## Your Question
How do i set a **primaryKey** field to also be **readonly**?
So I have a model where **ID** is my primary key.
```
type Category struct {
	ID        string     `json:"id" gorm:"primaryKey"`
	Name      string     `json:"name"`
	Desc      string     `json:"desc"`
}
``` 
But I also want to make the **ID** field readonly.
According to https://gorm.io/docs/models.html#Advanced, I'm supposed to use `gorm:"->"`
But when i do `gorm:"primaryKey,->"` or `gorm:"primaryKey;->"`, It doesn't work.

The "->" overwrites the "primarykey" field and as such, the ID isn't returned when you perform `db.Create(models.Category{})`

## The document you expected this should be explained
https://gorm.io/docs/models.html#Advanced

## Expected answer
I want a way to set a field to be both a primary key and readonly.

**Comment by jinzhu** [comment]
```go
db.Create(&models.Category{})
```
