### ISSUE TITLE
not use float64 query id

### ISSUE THREAD

**Issue by eudore** [go-gorm/gorm#3907]
## Your Question

golang: go version go1.15.1 linux/amd64
gorm: v1.20.7
database: pg10.5

```golang
type User struct {
	ID        int       `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
	var user User
	db.Model(&user).Where("id=?", float64(1)).Find(&user)
```

```bash
2020/12/31 02:39:43 /mnt/hgfs/golang/ctl.go:27 cannot convert 1 to Int8
[51.418ms] [rows:0] SELECT * FROM "users" WHERE id=1.000000
```
Use `SELECT * FROM "users" WHERE id=1.000000` to the results in navicat.

## Expected answer

Float64 type normal query results

**Comment by vzool** [comment]
@eudore I think with the new year of 2021 AD, you still like to watch "[A Horror Movie](https://www.sqltact.com/2015/05/fresh-new-horror-pk-on-float-data-type.html)" 🙃

**Comment by eudore** [comment]
I agree with float as the primary key id, security risks caused by precision. @vzool 

My primary key id is of type int, only float64 used for query.

I am very entangled in how to set it. The json library will use interface{} to receive int 2 and save it as a float64 type.

**Comment by jinzhu** [comment]
https://golang.org/pkg/encoding/json/#Decoder.UseNumber
