### ISSUE TITLE
MariaDB errors all become "commands out of sync" with MySQL driver

### ISSUE THREAD

**Issue by iangcarroll** [go-gorm/gorm#3909]
## GORM Playground Link

The playground doesn't support MariaDB.

## Description

Sorry that this is not the most easily reproduced issue; I'm not sure the playground easily supports MariaDB. When Gorm opens a connection to a MariaDB server and the connection fails, all errors are raised by Gorm as `commands out of sync`. This makes troubleshooting problematic as this is not actually the error returned. I most recently hit this by Gorm exceeding `max_connect_errors`, so all new connections failed, but the Gorm error did not match the issue/solution (`FLUSH HOSTS`). I have hit this with other distinct error types too, though.

I am not sure about the MySQL wire protocol details, but it would be nice if the real error message was accessible.

The offending code:
```
func newDB() *gorm.DB {
	config := &gorm.Config{
		Logger:                 logger.Default.LogMode(logger.Silent),
		SkipDefaultTransaction: true,
	}

	dsn := getDatabaseDsn()
	db, err := gorm.Open(mysql.Open(dsn), config)

	if err != nil {
		panic(err)
	}

	return db
}
```

Gorm error:
```
panic: commands out of sync. Did you run multiple statements at once?
goroutine 1 [running]:
main.newDB(0xf93220)
[...]
```

Traffic between MariaDB and Gorm:
```
$ sudo tcpdump tcp port 3306 -s 65535 -w ~/pcap
[...]
194 packets received by filter

$ cat ~/pcap
[...]Host '111.222.333.444' is blocked because of many connection errors; unblock with 'mariadb-admin flush-hosts'[...]
```

**Comment by jinzhu** [comment]
Hello @iangcarroll 

You should initialize a globally gorm.DB instance which hold a database connection pool, and use it in your application, for example:

```go
// config/db/db.go
package db

var DB *gorm.DB

func init() {
  var err error
  DB, err = gorm.Open(mysql.Open(dsn), config)
}

// handlers/xxx.go
import "xxx/config/db"

func ListUser() {
  db.DB.Find(&users)
}
```

Also refer https://gorm.io/docs/connecting_to_the_database.html#Connection-Pool

BTW, Thank you for your sponsorship ;)
