### ISSUE TITLE
Publishing GH Release

### ISSUE THREAD

**Issue by raphaelvigee** [go-gorm/gorm#3910]
## Your Question

Due to the relative high amount of updates to this library, it would be nice if actual Github releases were published when a `v*` tag is published, which would allow to properly use the "Watch Release" feature of github and make it easy to follow new updates, because at the moment the only way to be updated of changes is to subscribe to all changes (which creates way to much noise) or manually go and check the repo for new tags, which adds unnecessary manual work.

## Expected answer

The reason why this is not in place at the moment and whether or not this would be a nice to have.

**Comment by jinzhu** [comment]
thank you for your suggestion.

**Comment by raphaelvigee** [comment]
@jinzhu Is that a "thank you, but no" ? If it is a thank you but yes, I would be happy to make a PR

**Comment by jinzhu** [comment]
Pull request would be welcome!
