### ISSUE TITLE
I'm not sure if this is a bug

### ISSUE THREAD

**Issue by airplayx** [go-gorm/gorm#3912]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/243

## Description

![image](https://user-images.githubusercontent.com/8004501/103512427-9f0d0b00-4ea3-11eb-81cb-471f6ae9e29b.png)
![image](https://user-images.githubusercontent.com/8004501/103512431-a16f6500-4ea3-11eb-9db9-56ced5ff0938.png)

**Comment by jinzhu** [comment]
I don't get your issue, could you make it clearly?

**Comment by airplayx** [comment]
> I don't get your issue, could you make it clearly?
When not mounting the field name , the SQL contains ‘id = null‘ and Invalid search criteria .

**Comment by jinzhu** [comment]
Can you make a minimal example to explain it?

**Comment by airplayx** [comment]
> Can you make a minimal example to explain it?

here for test :
https://github.com/go-gorm/playground/pull/243

![image](https://user-images.githubusercontent.com/8004501/103628242-ac94c480-4f79-11eb-91b2-3ec95b71f261.png)

https://github.com/airplayx/playground

gorm version : 1.20.9
