### ISSUE TITLE
`Migrator.DropTable(...)` documentation doesn't reflect that it's a "drop if exists"

### ISSUE THREAD

**Issue by jimlambrt** [go-gorm/gorm#3914]
## Describe the feature

It would be great if the documentation reflected that `Migrator.DropTable(...)` is really an "drop if exists", especially given that Migrator is an interface. 

## Motivation

`Migrator.DropTable(...) ` actually does a "drop table if exists" which would seem to be a different operation, or at least a variation of dropping a table.  While I could check if the table exists before dropping it with `Migrator.HasTable(...)` that isn't really the same thing, since based on isolation the table might be created and/or deleted before the next statement is ran using `Migrator.DropTable(...)`.  

https://github.com/go-gorm/gorm/blob/60b769c2c8ab57eee310d86de11ec6c65b7b21d8/migrator/migrator.go#L242

**Comment by jinzhu** [comment]
https://gorm.io/docs/migration.html#Tables , As the document said, `DropTable` will drop table if it exists
