### ISSUE TITLE
sqlite for encryption

### ISSUE THREAD

**Issue by jaxsong** [go-gorm/gorm#3916]
## Describe the feature
is there any solution for sqlite encryption? 
how can i use gorm to encrypt sqlite ?
according to :https://stackoverflow.com/questions/5669905/sqlite-with-encryption-password-protection

**Comment by jinzhu** [comment]
It sounds like an question for sqlite driver, maybe https://github.com/xeodou/go-sqlcipher can help, also refer how to customize db driver for GORM.

**Comment by jaxsong** [comment]
thanks a lot~
