### ISSUE TITLE
Panic on a simple Delete with Where

### ISSUE THREAD

**Issue by Hellysonrp** [go-gorm/gorm#3920]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/244

## Description

![Screenshot_5](https://user-images.githubusercontent.com/5438762/103773616-19f03600-500a-11eb-98ab-a73dd39dea66.png)

**Comment by jinzhu** [comment]
`Delete(&Pet{})`

**Comment by Hellysonrp** [comment]
From [the docs](https://gorm.io/docs/delete.html#Batch-Delete), this should work.
It was working in v1.20.8.
Something broke it.
Besides, a panic is bad. In my honest opinion, it'd be better to add a validation.

**Comment by Hellysonrp** [comment]
@jinzhu 
Are you really not fixing this?
It is documented in this way, and it was working fine in v1.20.8.
For a documented behavior to just stop working is a really bad thing.

One of two things must be changed: the docs or the code.
Considering that it is documented in this way and that this is a panic, I really recommend you to add a validation to the code to prevent this problem.
