### ISSUE TITLE
How Do I Run a hook based on the changing of a specific column?

### ISSUE THREAD

**Issue by austincollinpena** [go-gorm/gorm#3923]
## Your Question

I have a specific column where, if modified, I need to make an update. Is this possible with Gorm?

The closest answers I got was [here](https://github.com/go-gorm/gorm/issues/3648).

If I have code like this:

```go
rootDomain = getRootDomain()
rootDomain.PlanType = planLevel
err = r.GDB.Save(&rootDomain).Error
```

I would expect a transaction to have information on the difference between the original object and the object that will be inserted.

Is there a way, even if it requires an additional query, to conditionally run a hook? Should I, in a beforeSave hook, just grab the ID, make another query, and then compare the desired fields that way?

## The document you expected this should be explained

[hooks](https://gorm.io/docs/hooks.html)

## Expected answer

I would expect an answer to be like:

"No, you have to re-query the desired object in a beforeSave/update to see if a change has occured."

or

"Yes, to find the diff, take a look at the transaction versus the ____.

**Comment by jinzhu** [comment]
Check out this doc https://gorm.io/docs/update.html#Check-Field-has-changed if it match your requirements, or you have to re-query it from database.

**Comment by austincollinpena** [comment]
I appreciate your help. Thank you!
