### ISSUE TITLE
Option to not ignore zero-value fields

### ISSUE THREAD

**Issue by yujiri8** [go-gorm/gorm#3924]
## Describe the feature

The docs say that for create and save operations, sub-structs with zero values are ignored rather than their values being set to zero in the database. I propose an option to disable this behavior. Could be a gorm.Config option, or something done around the Create/Save call.

## Motivation

We are migrating to GORM from a no-ORM system where a sub-struct of all zero values means that all its values in the database should be set to zero.

## Related Issues

None that I found.

**Comment by jinzhu** [comment]
The document told how to not ignore the zero-value fields, we won't provide other options.

**Comment by yujiri8** [comment]
I am not able to get those ways to work. The first thing I tried was calling Omit with no arguments, but zero-value substructs were still ignored. Then I tried calling Select on the substructs, but that seems to cause all fields to be ignored even if they are not zero valued. Finally, I tried Selecting some fields of the substructs with a dot notation (`Select("'Substruct.Field')`), but that had the same effect.

Are these methods known to work for substructs? Are they supposed to?

Question: when you said "we won't provide other options", do you only mean that you won't do the work, or would you reject a PR?

**Comment by jinzhu** [comment]
Are you using like this？ make sure you are using GORM V2

```go
// Select with Struct (select zero value fields)
db.Model(&user).Select("Name", "Age").Updates(User{Name: "new_name", Age: 0})
// UPDATE users SET name='new_name', age=0 WHERE id=111;

// Select all fields (select all fields include zero value fields)
db.Model(&user).Select("*").Update(User{Name: "jinzhu", Role: "admin", Age: 0})

// Select all fields but omit Role (select all fields include zero value fields)
db.Model(&user).Select("*").Omit("Role").Update(User{Name: "jinzhu", Role: "admin", Age: 0})
```

**Comment by yujiri8** [comment]
Yes, I'm using that pattern with the gorm.io/gorm import path (which is V2 if I'm not mistaken). I've added the `Select("*")` clause. Regardless of whether I pass the struct or laboriously convert it to a map, the substruct is not updated if it would be made all-zero.

None of your examples involve substructs. I think that's the difference, as it seems to work for me as long as there is only one level of struct. I have a model like this:

```
type Appointment struct {
   // fields ...
    AddressID int32
    Address Address
}
type Address struct {
    ID int32
    // fields ...
}
```
When I save the Appointment, the Address fields are updated as they should be, unless all the Address fields are zero-valued. None of the workarounds proposed have changed this.

**Comment by jinzhu** [comment]
https://gorm.io/docs/associations.html#Skip-Auto-Create-Update

**Comment by yujiri8** [comment]
I already read that page too, but none of the sub-structs are zero-valued.

**Comment by jinzhu** [comment]
I don't get your question, if you think this is any bug, create a reproducible playground pull request.
