### ISSUE TITLE
Joins 预加载 为啥是left join 是出于什么考虑吗

### ISSUE THREAD

**Issue by 2bu4** [go-gorm/gorm#3926]
db.Joins("Company").Find(&users)
// SELECT `users`.`id`,`users`.`name`,`users`.`age`,`Company`.`id` AS `Company__id`,`Company`.`name` AS `Company__name` FROM `users` LEFT JOIN `companies` AS `Company` ON `users`.`company_id` = `Company`.`id`;``

**Comment by jinzhu** [comment]
不会 left join 是出于什么考虑吗？
