### ISSUE TITLE
`sql: statement is closed` after upgrade to v1.20.9

### ISSUE THREAD

**Issue by zzjin** [go-gorm/gorm#3927]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/245/files

## Description
mysql will auto commit c-u-d actions, so we set:
```
PrepareStmt:            true
SkipDefaultTransaction: true
```
after upgrade to v1.20.9(include master branch) actions after transaction will throw error:
```
/home/runner/work/playground/playground/main_test.go:65 sql: statement is closed
```

same code with v1.20.8 work fine.

**Comment by jinzhu** [comment]
Fixed, thank you for your report! 💯
