### ISSUE TITLE
GORM2 Migration question - Partial Updates with ignored fields

### ISSUE THREAD

**Issue by cgcote** [go-gorm/gorm#3933]
## Your Question

Dear gorm team,

We encountered a behaviour change while migrating to gorm2 regarding partial updates.

type Test struct {
	ID    int  `json:"id"`
	Value string `json:"value" gorm:"-"`
}

func Test_PartialUpdate(t *testing.T) {

	test :=Test{ID: 1, Value: "value"}

	bytes, _ := json.Marshal(test)

	var rawObject map[string]interface{}
	json.Unmarshal(bytes, &rawObject)

	assert.Nil(t, db.Model(test).Updates(rawObject).Error)
}

With GORM1, the field "Value" is correctly discarded

[0m  UPDATE "tests" SET "id" = 1  WHERE "tests"."id" = 1  
[0 rows affected or returned ]
[0m {SELECT * FROM "tests"  WHERE "tests"."id" = ? [1]}

Gorm2 does not ignore the field and throws an error

[ERROR: column "value" of relation "tests" does not exist (SQLSTATE 42703)
[0m UPDATE "tests" SET "id"=1.000000,"value"='value' WHERE "id" = 1

## 

I don't know if it's a bug or just a behaviour change. If the latter, what would you suggest to do?

Thanks a lot!

**Comment by jinzhu** [comment]
Hi @cgcote 

You might want to use select fields w/o marshal to a map https://gorm.io/docs/update.html#Update-Selected-Fields

```go
db.Model(&test).Select("*").Update(test)
```

If you want to use map, you could disable the field's update permission like https://gorm.io/docs/models.html#Field-Level-Permission
