### ISSUE TITLE
Why does not it support beforeFind hook ?

### ISSUE THREAD

**Issue by brickzzhang** [go-gorm/gorm#3935]
## Your Question

Can't find beforeFind hook which might be useful for table separation scene. 

## Expected answer

The reason for beforeFind unsupported. Thanks.

**Comment by jinzhu** [comment]
It will call the `BeforeFind` based on a zero struct data, which usually doesn't make sense.

**Comment by mirusky** [comment]
I agree, but as we can pass values via context before hooks it can be a powerful tool to change some queries behaviours, like changing tenant (where tenant_id = ?), LazyCache and others.
