### ISSUE TITLE
How to use logrus with gorm? If that's possible

### ISSUE THREAD

**Issue by amitavaghosh1** [go-gorm/gorm#3936]
## Your Question
How do you use logrus for logging? Apart from having to re-implement the interface is there any easy way?

## The document you expected this should be explained

Previously in Gorm v1 , there was a very easy way to use logrus as Logger. I have tried something like this library https://github.com/onrik/gorm-logrus/blob/master/logger.go#L42 , but yeah the library doesn't work I fixed it. This functionality was much easier with the v1 version. And the new one doesn't have much documentation on logging.

## Expected answer

Is there an easier way to use logrus instance in gorm Logging.?

**Comment by jinzhu** [comment]
implement the logger interface
