### ISSUE TITLE
Is there a way to replace associations without the creation portion of upsert?

### ISSUE THREAD

**Issue by lianshen-vineti** [go-gorm/gorm#3937]
## The document you expected this should be explained

https://gorm.io/docs/associations.html#Replace-Associations

## Expected answer

Entity create/update operations have the option to skip auto create/update, and I was wondering if there was a way to do this for replacing associations.
Similar to 
```
db.Omit("Languages.*").Create(&user)
```
I'd like to be able to call something like
```
db.Model(&user).Association("Languages").Omit("Languages.*").Replace([]Language{languageZH, languageEN})
```
so that `INSERT INTO "languages"...` is not called.

Currently I see
1. `INSERT INTO "languages" (...) VALUES (...) ON CONFLICT DO NOTHING`
2. `INSERT INTO "user_languages" ("user_id","language_id") VALUES (...) ON CONFLICT DO NOTHING`
3. `DELETE from "user_languages" WHERE "user_id" = $1 AND "language_id" NOT IN (...)`

Ideally I would like to see only steps 2 and 3.

**Comment by knlambert** [comment]
Is this a design issue ? I have trouble to understand why the version 2 of GORM always try to insert stuffs with associations (I don't think it was doing that before).

If i take this example which is very similar to my use cases, most of the time the Language table items are created in a separate process, so I don't need to add them again each time I create a user :(

**Comment by alphachai** [comment]
Is there really no way to do this atm? I'm trying to avoid creating a many2many table manually and inserting those rows myself, but I feel like I'll have to if there's no way to "Omit" inserts when doing `Append` and `Replace`.

**Comment by jinzhu** [comment]
Already supported in latest release.

**Comment by jinzhu** [comment]
use it like:
```go
db.Model(&user).Omit("Languages.*").Association("Languages").Append(&langs)
```

**Comment by inliquid** [comment]
Thanks!

**Comment by yiannisccmath** [comment]
> use it like:
> 
> ```go
> db.Model(&user).Omit("Languages.*").Association("Languages").Append(&langs)
> ```

Might work with Append, but version 1.23.3 does not support this for `Replace` it still creates records in Languages table
