### ISSUE TITLE
BeforeSave Callback receives an empty Model

### ISSUE THREAD

**Issue by RobRoyd** [go-gorm/gorm#3938]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/248

## Description

```golang
var model = &Model{ID: 3, Title: "Hello World"}

...

DB.Model(&Model{}).Where("id = ?", model.ID).Updates(model)
```

When saving/updating a model with a `BeforeSave(db) error` callback the model on which the callback is executed is empty since version `1.20.6`.
In version `1.20.5` and before the model in this callback has been the model which is given in the `.Updates(model)` call. Now it seems it receives the model from the `.Model(&Model{})` call.

The expectation is, that the `BeforeSave` is called on the model instance which is given to the `Updates(...)` call and not to the empty model instance of the `Model(...)` call.

**Comment by jinzhu** [comment]
Call hook methods based on model value is expected, it was a bug before v1.20.5, you could use it like:

```go
db.Model(model).Where("id = ?", model.ID).Updates(model)
```
