### ISSUE TITLE
Lack of documentation from migrating from v1 to v2.

### ISSUE THREAD

**Issue by Tang8330** [go-gorm/gorm#3939]
Problem here is that we're using the v1 docs for `Jointable Foreign Key` https://v1.gorm.io/docs/many_to_many.html#Jointable-ForeignKey and there does not seem to be a clear path to have this supported in V2.

https://gorm.io/docs/many_to_many.html#Override-Foreign-Key

Can we have a clear description about these terminologies: `foreignKey, references, joinForeignKey, joinReferences`

**Comment by jinzhu** [comment]
Like https://gorm.io/docs/associations.html#tags ?
