### ISSUE TITLE
How can i specify different column type for same column in MySQL and PostgreSQL?

### ISSUE THREAD

**Issue by iredmail** [go-gorm/gorm#3941]
## Your Question

I need to specify different column type for same column in MySQL and PostgreSQL, how can i do that?

for example, i now use `type:VARBINARY(255)` in struct tag for MySQL, but PostgreSQL doesn't support `VARBINARY`, and i should use something like `BYTEA` instead.

## The document you expected this should be explained

https://gorm.io/docs/models.html#Fields-Tags

## Expected answer

Expect a field tag to specify column type for MySQL, and another for PostgreSQL.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/datatypes/blob/8a27b52fd85bbb4d9f614d55e75dea5d89a2fc4e/json.go#L68
