### ISSUE TITLE
Getting nested struct

### ISSUE THREAD

**Issue by juancer** [go-gorm/gorm#3944]
## Your Question

I have the following structs:

`
type Users struct {
	ID           int64            gorm:"id" json:"id"
	Name         int64           gorm:"name" json:"name"
	UserTypeID   int             gorm:"column:user_type_id" json:"-"
	UserType     BusinnesUserType gorm:"foreignKey:id;references:user_type_id" json:"user_type"
	LanguageID   int64            gorm:"column:language_id" json:"-"
	Language     Language         gorm:"foreignKey:ID;references:LanguageID" json:"language"
}
`

`
type BusinnesUserType struct {
	ID          int64           gorm:"id" json:"id"
	Description json.RawMessage gorm:"description" json:"description"
}
`

`
type Language struct {
	ID          int64           gorm:"id" json:"id"
	Description json.RawMessage gorm:"description" json:"description"
}
`
But I get the following json instead:

`
{
   "id":1,
   "name":"dd",
   "user_type":{
      "id":null,
      "description":null
   },
   "language":{
      "id":null,
      "description":null
   }
}
`

And this is my gorm query with mysql:
db.Preload("UserType").Preload("Language").Where("id=?",1).Find(&user)

If I use the Debug() option I see:

`
SELECT * FROM languages WHERE languages.id = 1 
`

`
SELECT * FROM business_user_types WHERE business_user_types.id = 1 
`

`
SELECT * FROM users WHERE id = 1 
`

## Expected answer

I'm trying to get something like:

`
{
   "id":1,
   "name":"dd",
   "user_type":{
      "id":1,
      "description":{
         "en":"admin"
      }
   },
   "language":{
      "id":1,
      "description":{
         "en":"English"
      }
   }
}
`

**Comment by jinzhu** [comment]
foreignKey should be LanguageID, UserTypeID

**Comment by juancer** [comment]
Hi Jinzhu, I already tried that option, same result.
I wrote before this question in StackOverflow, here is the link: [SO](https://stackoverflow.com/questions/65656283/getting-nested-struct)
Please, keep open the issue, because, maybe I have something wrong in my code, that could be possible, but, my error still happends

**Comment by jinzhu** [comment]
If you still have issue, create a reproducible Gorm playground PR.

**Comment by juancer** [comment]
Hi @jinzhu I found the solution:
```
result := db.Preload("UserType", "id=?", &user.UserTypeID).
		Preload("Language", "id=?", &user.LanguageID).
		Where("id=?", 1).Find(&user)
```
Regards,
