### ISSUE TITLE
Return data from cache in Callback

### ISSUE THREAD

**Issue by andreadragotta** [go-gorm/gorm#3952]
## Your Question

Hi, i've a custom gorm:query callback and i want to return the cached result if present.

This is my code: 

```
func QueryFromCache(db *gorm.DB) {
	if !db.DryRun && db.Error == nil {
		callbacks.BuildQuerySQL(db)
		cacheKey := GetCacheKey(db)

		foo, found := DataCache.Get(cacheKey)

		if found {
			log.Printf("=====GET FROM CACHE=====")
			// return code here
		} else {
	  		rows, err := db.Statement.ConnPool.QueryContext(db.Statement.Context, db.Statement.SQL.String(), db.Statement.Vars...)
			if err != nil {
				db.AddError(err)
				return
			}
			defer rows.Close()
			log.Printf("=====SAVE IN CACHE=====")
			gorm.Scan(rows, db, false)
			DataCache.Set(cacheKey, db.Statement.Dest, cache.DefaultExpiration)
	  	}
	}
}
```

## Expected answer

There are a method to return the response data get from cache?

**Comment by jinzhu** [comment]
Just return after get from cache should works? Hook methods should be invoked if it is defined.

**Comment by andreadragotta** [comment]
how i return the data after get from cache? In replace callback is not possibile to use return.

**Comment by jinzhu** [comment]
Update `db.Statement.ReflectValue`

**Comment by andreadragotta** [comment]
Is available any example? in documentation isn't present anything of that

Thank you!

**Comment by itgelo** [comment]
hi @andreadragotta
have you found a solution to this case?

**Comment by jinzhu** [comment]
Check the the query callback, after receive data from database, it will update the passed data, update the user in the following example.

```go
db.First(&user)
```

For your plugin, after receive data from cache store, just update the user, and that's it.

**Comment by andreadragotta** [comment]
but i need to use reflect because the output data could be Slice, Array, Int. 
Or is possible to make an assignment to a variable?

**Comment by jinzhu** [comment]
not possible, GORM also needs to use reflect.
