### ISSUE TITLE
How to hide logs from terminal even i have logging disabled

### ISSUE THREAD

**Issue by khanakia** [go-gorm/gorm#3953]
## Your Question
Gorm showing the Insert Query logs in terminal even i have logging disabled so how can i turn of the insert queries showing in terminal ?
```
db, err := gorm.Open(mysql.Open(dbDSN), &gorm.Config{
// Logger: logger.Default.LogMode(logger.Info),
})
```

<img width="940" alt="Screenshot 2021-01-16 at 10 51 06 AM" src="https://user-images.githubusercontent.com/2174170/104798011-f470e280-57e8-11eb-924c-e67fea52c407.png">

**Comment by labulaka521** [comment]
you can set logger level
```
db, err := gorm.Open(mysql.Open(dbDSN), &gorm.Config{
       Logger: logger.Default.LogMode(logger.Error),
})
```

**Comment by jinzhu** [comment]
Use level `Silent` to fully disable it.
