### ISSUE TITLE
db.AutoMigrate is not working as expected.

### ISSUE THREAD

**Issue by discovery-RaginiDhatric** [go-gorm/gorm#3961]
## Your Question

We are using the gorm package: "github.com/jinzhu/gorm" but noticed that db.AutoMigrate is not working as expected.
We noticed this when we tried to create two new columns example : 
1.  info string
2.  metrics map[string]float64

We are using the following code snippet:
transaction := db.Begin()  ---- We are using Postgres db
transaction.AutoMigrate(m...)
transaction.Commit()

Error: 
pq: Could not complete operation in a failed transaction

## Expected answer

We expect that AutoMigrate creates the two new columns in the table. But Instead we are facing the above error. Please assist if you have encountered such thing before.

Thanks in advance !

**Comment by jinzhu** [comment]
The error is pretty clear? and we don't handle GORM v1 issues here ;)

**Comment by discovery-RaginiDhatric** [comment]
Even without any transaction error occurring, we noticed that db.AutoMigrate(m...) is not creating the missing columns.
It would be of much help if you let us know on where can we raise gorm v1 issues. Thanks !!
