### ISSUE TITLE
Zero value struct find will build wrong sql.It's bug?

### ISSUE THREAD

**Issue by SmallTianTian** [go-gorm/gorm#3966]
## Your Question
When I find by struct, like this
```go
type User struct {
    Name string
    Age int
}

condition := &User{Name: ""}

var find User
gorm.DB.Find(&find, condition)
```
will build a wrong sql
```sql
SELECT * FROM user WHERE ;
```

## Expected answer
At first I thought it was a bug, but then I found it could protect my data. For example, when you take out of `where`, `delete` will be fatal. So, can you give me a suggest.

**Comment by jinzhu** [comment]
Hi @SmallTianTian 

yes, it is a bug, just fixed it.

we have the block global delete mode enabled by default, so it won't cause trouble when there are any bug https://gorm.io/docs/delete.html#Block-Global-Delete

**Comment by SmallTianTian** [comment]
Ok, thanks. It's so fast.🎉🎉🎉
