### ISSUE TITLE
Create cannot handle custom type?

### ISSUE THREAD

**Issue by KyleKotowick** [go-gorm/gorm#3969]
## Your Question

Say I have this model:
```
type Demo struct {
	MyTime time.Time
}
```

If I run
```
if err := db.AutoMigrate(&Demo{}); gerr != nil {
	panic(err)
}

if err := db.Create(&Demo{
	MyTime: time.Now(),
}).Error; err != nil {
	panic(err)
}
```
It produces the SQL statements (MySQL):
```
CREATE TABLE `demos` (`my_time` datetime(3) NULL)

INSERT INTO `demos` (`my_time`) VALUES ('2021-01-19 18:19:25.824')
```

Cool, this looks right. But if I change the model like so:
```
type CustomTime time.Time

type Demo struct {
	MyTime CustomTime
}
```

And run this code:
```
if err := db.AutoMigrate(&Demo{}); gerr != nil {
	panic(err)
}

if err := db.Create(&Demo{
	MyTime: CustomTime(time.Now()),
}).Error; err != nil {
	panic(err)
}
```

It runs the same statements:
```
CREATE TABLE `demos` (`my_time` datetime(3) NULL)

INSERT INTO `demos` (`my_time`) VALUES ('2021-01-19 18:25:18.495')
```

But it also outputs this error:
```
sql: converting argument $1 type: unsupported type CustomTime, a struct
```

Am I doing something wrong here? I would think that since `CustomTime` is based on `time.Time`, and `time.Time` is handled properly, it should handle this properly. I'm not sure if this is a bug, or is simply unsupported for some reason.

## The document you expected this should be explained

[Declaring Models](https://gorm.io/docs/models.html) maybe?

## Expected answer

A way to do this, or a reason it doesn't work.

**Comment by jinzhu** [comment]
https://gorm.io/docs/data_types.html

**Comment by KyleKotowick** [comment]
Thank you, that helps. Is there a way to set a function (perhaps in the config) that is used as a Scanner/Valuer for all custom types that can't be converted?

**Comment by jinzhu** [comment]
no, the scanner, valuer is required by database/sql
