### ISSUE TITLE
save方法hook重复调用

### ISSUE THREAD

**Issue by zzc9402** [go-gorm/gorm#3971]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/253
## Description
调用save方法时，若value 主键不为空，且数据库中没有该记录时，BeforeSave hook会调用两次

    func (user *User) BeforeSave(tx *gorm.DB) error {
        user.Age += 1
        return nil
    }

    user := User{Model: gorm.Model{
        ID: 1,
    },
        Name: "zzc9402",
    }

    DB.Save(&user)

    var result User
    if err := DB.First(&result, user.ID).Error; err != nil {
        t.Errorf("Failed, got error: %v", err)
    }

    if result.Age != 1 {
        t.Errorf("failed,age should be 1, not %d", result.Age)
    }

**Comment by jinzhu** [comment]
Hi @zzc9402 

If the user has primary key (ID = 1 in this example), GORM will try to update the user first, if failed, will insert the data into database, so the `BeforeSave` is expected to be called twice.

Suggest you use `Create` to insert the data and it will only call the `BeforeSave` once.

**Comment by zzc9402** [comment]
我看了代码，了解是先尝试更新，再执行创建。但是我理解 这个save方法应该是等同于upsert的操作，beforesave  应该是期望执行一次的操作，不应该执行两次 @jinzhu

**Comment by zzc9402** [comment]
> Hi @zzc9402
> 
> If the user has primary key (ID = 1 in this example), GORM will try to update the user first, if failed, will insert the data into database, so the `BeforeSave` is expected to be called twice.
> 
> Suggest you use `Create` to insert the data and it will only call the `BeforeSave` once.

我看了代码，了解是先尝试更新，再执行创建。但是我理解 这个save方法应该是等同于upsert的操作，beforesave 应该是期望执行一次的操作，不应该执行两次 @jinzhu
