### ISSUE TITLE
Batch insert fails to return correct auto-incremented primary key when auto_increment is set to 2 in mysql

### ISSUE THREAD

**Issue by balajikrishnanextreme** [go-gorm/gorm#3972]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/254/files

## Description
My mysql is configured with auto_increment_increment=2 for HA reasons.

When I attempt to insert multiple rows by passing an array of row objects to db.Create(...), I expect it to fill in the ID (primary-key) correctly in return. Though my db is updated correctly, the Create() is found to populate sequential ID value. This is wrong for all the newly added rows except the first one.

Am I missing anything in my code or is there a workaround I can use?

**Comment by jinzhu** [comment]
https://gorm.io/docs/models.html#Fields-Tags

Change tag `autoIncrementIncrement` to 2

**Comment by balajikrishnanextreme** [comment]
Can this be made a db open time global config, just like config in mysql? With 50+ tables, it is hard to update them all.

**Comment by jay-wlj** [comment]
> Can this be made a db open time global config, just like config in mysql? With 50+ tables, it is hard to update all the models

I have the same problem

**Comment by balajikrishnanextreme** [comment]
My deployment has both single node mode and in HA mode option, so I could not fix a number for this tag at compile time.

As a workaround, I have explicitly set a value of 2 in my model definition as well as in mysql configuration irrespective of my HA deployment option. This is a one time work, but it has been working fine so far.
