### ISSUE TITLE
Defining composite unique index in embedded struct

### ISSUE THREAD

**Issue by arcln** [go-gorm/gorm#3973]
## Your Question

```go
type Foo struct {
  IndexA int `gorm:"index:my_idx,unique"`
  IndexB int `gorm:"index:my_idx,unique"`
}

type Bar struct {
  Foo `gorm:"embedded"`
}
```

In this example, both structs can be used as models and have a unique composite index named "my_idx".
However, when running auto-migrate of both of them, I get the following error from postgres (and a similar one from sqlite) :

```
ERROR: relation "my_idx" already exists
[1.361ms] [rows:0] CREATE INDEX "my_idx" ON "bars" ("index")
```

Notice that the error only happens for the model that is auto-migrated last. I understand that I can't have two relations with the same name. How can I define a model with a composite unique index and use it both as is and as an embedded struct?

## The document you expected this should be explained

https://gorm.io/docs/indexes.html

## Expected answer

I believe this is expected and not handled by gorm because of the complexity and rarity of this use case.
Maybe you can suggest me a workaround? Thanks.

A "real" solution would be to prefix the index name with the table name. Not sure if this is complicated or will break anything.

**Comment by jinzhu** [comment]
You can make it works by changing the default `NamingStrategy` and change the generated index name.

**Comment by arcln** [comment]
Actually this didn't solve the problem, because of [schema/index.go:107](https://github.com/go-gorm/gorm/blob/35ebfe68740ef8d1ff3fde2037fbba34d802e287/schema/index.go#L107) not calling `IndexName()` if a name is specified for the index. From my understanding I _must_ supply a manual name in order to create a composite index.

Changing the behaviour of `IndexName()` would be a breaking change so I suppose it isn't really an option.

I could create a messy switch statement that handles every table and index cases to return fully generated indexes, but at this point it is easier to duplicate the indexing fields.
