### ISSUE TITLE
How to connect to CloudSQL

### ISSUE THREAD

**Issue by tiagomelo** [go-gorm/gorm#3981]
## Your Question

Hi, I'm trying to connect to CloudSQL but I'm having issues with it.

If I use this format `user:password@unix(/cloudsql/cloudsql-instance-name)/dbName?parseTime=true&timeout=60s&readTimeout=60s`, I get 

```
dial unix /cloudsql/nyt-inbox-dev:us-east1:consumer: connect: no such file or directory"
```

After searching a bit, seems like that the alternative way would be to use github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql, but I'm not sure how to combine it with Gorm.

Is this right?

```
import (
	"github.com/pkg/errors"
	"gorm.io/driver/mysql"
	_ "github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql"
	"gorm.io/gorm"
)

...

// DNS: user:password@cloudsql(cloudsql-instance-name)/dbName?parseTime=true&timeout=60s&readTimeout=60s
db, err := gorm.Open(mysql.New(mysql.Config{
		DriverName: "mysql",
		DSN:        dns,
	}), &gorm.Config{})
```

Thanks!

**Comment by jinzhu** [comment]
https://gorm.io/docs/connecting_to_the_database.html#Existing-database-connection
