### ISSUE TITLE
Gorm v2 Postgresql Connection Pool Migration

### ISSUE THREAD

**Issue by burdzand** [go-gorm/gorm#3984]
For some reason every time I run the application gorm try to apply the migration when I use gorm v2 with connection pool, it doesn't matter who many replicas I run each one will try to run migration and got a error.

`
db, _ := connectiondb.DB()
db.SetMaxIdleConns(25)
db.SetMaxOpenConns(50)
db.SetConnMaxLifetime(5 * time.Minute)

type User struct {
    ID   uint   `gorm:"primaryKey;autoIncrement"`
    Name string `gorm:"size:40;uniqueIndex:unique_index"`
}
connectiondb.AutoMigrate(&User{}))
`

Error:  
main.go:75 ERROR: relation "users" already exists (SQLSTATE 42P07)

gorm.io/driver/postgres@v1.0.1/migrator.go:79 ERROR: relation "unique_index" already exists (SQLSTATE 42P07)
[148.169ms] [rows:0] CREATE UNIQUE INDEX "unique_index" ON "users" ("name")

Am I missing any configuration?

Thanks.

**Comment by jinzhu** [comment]
Upgrade your driver
