### ISSUE TITLE
Is there a way to manually AddForeignKey like in v1?

### ISSUE THREAD

**Issue by nomex26** [go-gorm/gorm#3986]
Is there a way to manually `AddForeignKey` like in v1? I've followed the docs and disabled automigrate foreign key creation by setting `DisableForeignKeyConstraintWhenMigrating` to true. That worked. Now, I would like to continue manually adding foreign keys in migrations like `AddForeignKey` allowed in v1, but unfortunately that API is gone. Please don't just link me to the docs, I've read the docs, there is nothing there about manually adding foreign keys. It only talks about automigrate and how to disable it.

## The document you expected this should be explained

https://gorm.io/docs/migration.html#Migrator-Interface

## Expected answer

I would like an API similar to `AddForeignKey` in v1.

**Comment by nomex26** [comment]
This was a question, not a bug report. Reproduction steps were not requested...

**Comment by nomex26** [comment]
This is an unsolved question, it is not stale. Please re-open this.

**Comment by jinzhu** [comment]
Just updated the doc https://gorm.io/docs/migration.html#Constraints you could use it like this with the latest gorm and driver.
