### ISSUE TITLE
gorm v2 migrator not support add foregineKey and add unique index api!

### ISSUE THREAD

**Issue by lyouthzzz** [go-gorm/gorm#3989]
## Your Question
I want to AddForeignKey like in v1. But v2 api not supported. 

![image](https://user-images.githubusercontent.com/29134871/105620362-3fb57180-5e37-11eb-8dfa-6b4941d2dbcf.png)

**Comment by jinzhu** [comment]
Define the struct and create the index with the `index` name or `field` name, for example:

```go
type User struct {
  Name string `gorm:"uniqueIndex"`
}

db.Migrator().CreateIndex(&User{}, "Name")
```
