### ISSUE TITLE
db.AutoMigrate()里添加新的model，无法创建新表

### ISSUE THREAD

**Issue by thep0y** [go-gorm/gorm#3991]
## Your Question
文档和谷歌都没有找到解决方法。
程序第一次运行时，可以创建表
```go
        db.AutoMigrate(
		&models.SSE{},
		&models.SSEGuest{},
		&models.SSEAnswerOrSpeaking{},
       )
```
第二次运行前，加一个models，这个新加的model不会创建新表
```go
	db.AutoMigrate(
		&models.SSE{},
		&models.SSEGuest{},
		&models.SSEAnswerOrSpeaking{},
		&models.SSE413URL{},
        )
```

## The document you expected this should be explained
新添加的models应该自动完成迁移，如果无法自动完成迁移，请加后添加的Model创建表的方法写在文档里。
文档里关于迁移的介绍不能解决我遇到的问题

## Expected answer
请告诉我如何为新添加的Model创建新表。

**Comment by jinzhu** [comment]
It should works, if it doesn't, please create a gorm playground PR.
