### ISSUE TITLE
GORM Automigrate on two databases/Shared databases

### ISSUE THREAD

**Issue by anshuljhawar** [go-gorm/gorm#3992]
## Your Question

I am trying to implement very simple shard using GORM and DBResolver

Here is the code for it

```
func (mysqlDB *MySQLDB) InitDB() {

    dsn_master := "root:rootroot@tcp(127.0.0.1:3306)/workspace_master?charset=utf8mb4&parseTime=True&loc=Local"
    dsn_shard1 := "root:rootroot@tcp(127.0.0.1:3306)/workspace_shard1?charset=utf8mb4&parseTime=True&loc=Local"

    db, err := gorm.Open(mysql.Open(dsn_master), &gorm.Config{
        Logger: logger.Default.LogMode(logger.Info)})

    if err != nil {
        log.Println("Connection Failed to Open")
    } else {
        log.Println("Connection Established")
    }

    db.Use(dbresolver.Register(dbresolver.Config{
        Sources: []gorm.Dialector{mysql.Open(dsn_shard1)}},
        &models.WorkspaceGroup{}, "shard1"))

    db.AutoMigrate(&models.Workspace{}, &models.WorkspaceMember{})

    //db.AutoMigrate(&models.Workspace{}, &models.WorkspaceMember{}, &models.WorkspaceGroup{}, &models.GroupMember{})

    db.Clauses(dbresolver.Use("shard1")).AutoMigrate(&models.WorkspaceGroup{}, &models.GroupMember{})

    mysqlDB.Database = db
}
```

I am creating two databases `workspace_master` and `workspace_shard1`

Issue is that automigration is not working as expected. Shard Tables are not getting created in respective database. I have tried the commented code as well (automigrate having all the tables and setting db resolver earlier)

## The document you expected this should be explained

https://gorm.io/docs/dbresolver.html

## Expected answer

`Workspace` and `WorkspaceMember` will get created in `workspace_master` database 
`WorkspaceGroup` and `GroupMember` will get created in `workspace_shard1` database

## Current Result:

All tables are created in `workspace_master` database

However if I create `WorkspaceGroup` and `GroupMember` manually in `workspace_shard1`, any subsequent queries for create, select, delete etc is going correctly to `workspace_shard1`. So DBResolver seems to be working as expected.

Only issue is `db.AutoMigrate` is not working as expected. Can you please suggest how it can be achieved?

**Comment by jinzhu** [comment]
Should fixed, thank you for your report.

**Comment by anshuljhawar** [comment]
Thanks a lot .. @jinzhu!

**Comment by anshuljhawar** [comment]
@jinzhu Can you please update on when will it be available in release version?

**Comment by jinzhu** [comment]
Just released
