### ISSUE TITLE
GORM V2 Error Chaining Inspection (and IsRecordNotFoundError equivalency)

### ISSUE THREAD

**Issue by cameron-dunn-silo** [go-gorm/gorm#3993]
## GORM Playground Link

This behavior is straightforward to demonstrate in the plain Go playground, because it only depends on a small subset of the GORM codebase. I apologize for not having a Go Playground link -- I'm having an issue with my Go Path or package structure and cannot get the Playground setup (or something like that, I'm not totally sure, but I'll revisit).

[GORM V2 Behavior Demonstration](https://play.golang.org/p/d9EC3loVTm5)
[GORM V1 Behavior Demonstration](https://play.golang.org/p/QJbeRiFWWyA)

## Description

I am migrating a code base from GORM V1 to GORM V2. GORM V1 has a `gorm.IsRecordNotFoundError`, V2 does not. The GORM V2 release notes address this and say:

"and we have also removed method RecordNotFound in V2, please use errors.Is to check the error, e.g:"
```
err := db.First(&user).Error
errors.Is(err, gorm.ErrRecordNotFound)
```

I interpreted this to mean that `errors.Is(err, gorm.ErrRecordNotFound)` can be used for equivalent use cases as `gorm.IsRecordNotFoundError`

I also noticed that `GetErrors` has been removed and only `GetError` remains. My hope is that the intention is to continue to allow the inspection of all errors that were added to the DB.

### Issue

`errors.Is(err, gorm.ErrRecordNotFound)` will only successfully identify when a `ErrRecordNotFound` was the last error added using `GetError`. Based on the language from the release notes, I did not expect this and believe it may not be intended.

Usage of `GetError` does not allow using GO's normal error examination features to find any error type, if there is more than one error. A workaround demonstrated in the playground link is to inspect the string itself, but this approach may unreliable, and it is not extensible to non-static errors.

I think the simple explanation for this behavior is that `fmt.Errorf("%v; %w", db.Error, err)` does not result in `db.Error` (or a copy of it, or error of the same type, etc) wrapping `err`. Instead it results in an entirely new error which wraps `err`, and has a string value equivalent to that of `db.Error`. This new error cannot be usefully and safely inspected.

### Solution

If this is indeed unexpected behavior, I can think of a couple ways to potentially address it.

**Comment by jinzhu** [comment]
Hi @cameron-dunn-silo yes, this is not the expected behavior that should be fixed.

**Comment by cameron-dunn-silo** [comment]
Thank you @jinzhu 

One thing I'm unsure of is what conditions would actually lead to multiple errors, and particularly one of them being a `ErrRecordNotFound`. Knowing what sort of conditions would lead to this will help us understand the scope or impact of this issue.

**Comment by jinzhu** [comment]
Hello @cameron-dunn-silo 

From GORM side, it not likely to have multiple errors, but this possible happens in case of user add more errors in hooks methods (Before/After Create... methods)

**Comment by GiancarlosIO** [comment]
👀

**Comment by fstorfa** [comment]
Hi @jinzhu

Not sure if I should create a new issue, or ask here but I'm wondering if the issue I'm having is related to this one, or if it's a different one. I have been migrating from V1 to V2 and this works in V1, but when I'm trying to get the underlying error from the database driver(`lib/pq` in my case) it doesn't work on V2, but it worked fine before. Something similar to this is what I had working in V2:

```
if err = db.Create(ipems).Error; err != nil {
    var pqErr *pq.Error
    if errors.As(err, &pqErr) && pq.Err.Code == "23505" {
        // Handle duplicate key error
    }
}
```

In V1 this worked like a charm, but not in V2. Is there something I'm missing regarding handling of errors in V2 or is this the same, or similar bug as @cameron-dunn-silo is experiencing?

**Comment by jinzhu** [comment]
Hi @fstorfa 

It doesn't related to this one, we have change the postgres driver to pgx, should use pgx's error.

**Comment by jinzhu** [comment]
For this issue, I think this issue maybe don't need to fix.

In normal case, when there is an error happened, no GORM callback will run anymore, so users should be able to check the error is ErrRecordNotFound or not.
