### ISSUE TITLE
how can i scan protocol structs?

### ISSUE THREAD

**Issue by DongWenHu** [go-gorm/gorm#3994]
## Your Question
很抱歉前面我问题不够详细
我觉得使用Find, First, Scan查询限制了protobuf结构体的解析赋值

```
type TestResp struct {
	Code                 *uint32                `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}
```

当我使用scan进行查询赋值时，会有如下报错信息:
`invalid field found for struct main.TestResp's field XXX_NoUnkeyedLiteral, need to define a valid foreign key for relations or it need to implement the Valuer/Scanner interface`

XXX_NoUnkeyedLiteral 字段会被定义为关联字段，但是这个结构体是pb工具生成，我不能去添加tag和重写Scan

因为v1项目大量使用了赋值到pb结构体，升级到v2不得不使我去修改大量代码

## Expected answer
能够在不修改大量代码情况下适应这种查询

**Comment by jinzhu** [comment]
可以看看使用 `gorm:"-"` 忽略字段
