### ISSUE TITLE
Bulk insert with has many association

### ISSUE THREAD

**Issue by pioz** [go-gorm/gorm#3998]
## Your Question

I'm trying to perform a bulk insert with has many association, for example: author has many book. So what I do is:

```
for (...) {
  author := User{Name: "xxx"}
  author.Books = append(author.Book, &book1)
  author.Books = append(author.Book, &book2)
  authors = append(authors, author)
}
db.Create(authors)
```
The problem here is that Gorm tries to create the books before the authors so I get the error `Error 1452: Cannot add or update a child row: a foreign key constraint fails` because the `author_id` on the `books` table is `0`:
```
INSERT INTO `books` (`author_id`,`title`) VALUES (0,"Title 1"),(0,"Title 2");
```
Is there a way to achieve this? If yes how?

Thanks for the support.

**Comment by doppl-neal** [comment]
@pioz Quick question, are you using gorm.Model in your user struct?

**Comment by pioz** [comment]
> @pioz Quick question, are you using gorm.Model in your user struct?

No.

**Comment by doppl-neal** [comment]
how do you create the author id?

**Comment by pioz** [comment]
My models:
```
type Author struct {
	Id         	uint64
	Name		string
	CreatedAt	time.Time `gorm:"type:DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP"`
	UpdatedAt	time.Time `gorm:"type:DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"`
	Books		[]*Book
}

type Book struct {
	Id			uint64
	AuthorId	uint64	`gorm:"not null;index"`
	Name		string	`gorm:"size:255;not null;index"`
	Author		*Author	`gorm:"foreignkey:AuthorId;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
}
```

**Comment by doppl-neal** [comment]
from my understanding, you have to create the id somewhere, if you are not using gorm.Model.  
I have a beforecreate hook which I create a uuid.
Also, if you look in your db at your tables, is the Id of the Author table the primary key?

**Comment by pioz** [comment]
> from my understanding, you have to create the id somewhere, if you are not using gorm.Model.
> I have a beforecreate hook which I create a uuid.
> Also, if you look in your db at your tables, is the Id of the Author table the primary key?

Yes, the `Id` field is the primary key. As the doc says (https://gorm.io/docs/models.html#Conventions):
_GORM prefer convention over configuration, by default, GORM uses ID as primary key_

**Comment by doppl-neal** [comment]
You will still need to create the value of the id yourself. 
However, still a bit strange that you don't see a query trying to insert the Author.

**Comment by pioz** [comment]
I see the query.

I do not have the IDs value of the authors cause I'm trying to insert them in bulk. So the IDs do not exist yet. I can create the author before and then create the books with the `author_id` values, but I want to know if Gorm is able to manage the bulk insert with has many associations itself.

**Comment by doppl-neal** [comment]
Here is a tidbit of code I have in my application. I didnt use the gorm.Model cause at first I wasn't going to use UUIDs. 
func (base *BaseStruct) BeforeCreate(tx *gorm.DB) error {
	base.ID = base.createUuid()

	t := base.createUTCTime()
	base.CreatedAt = t
	base.UpdatedAt = t

	return nil
}

if you create a base struct and have all your struct use that struct. anytime one of those structs gets inserted, this code will run. 
Its a really nice hook.

There is a similiar one for update.
I am also going to add createdby and updatedby to this struct.

**Comment by pioz** [comment]
I don't know. Following this example in the doc https://gorm.io/docs/create.html#Create-With-Associations I shouldn't need hooks.

**Comment by jinzhu** [comment]
Try `db.Create(&authors)`, if it doesn't work, please create a reproducible GORM playground PR

**Comment by doppl-neal** [comment]
@pioz GORM will not create data for you, unless you use gorm.Model. If you are using your own primary key, they you need to create the data for the primary key for GORM. In those examples, you will notice those structs using gorm.Model
