### ISSUE TITLE
Updating Nested Data With GORM

### ISSUE THREAD

**Issue by doppl-neal** [go-gorm/gorm#4000]
This is an amazing library. It has saved me loads of hours. However, I am failing to understand how to updated nested data. Clearly I am doing something incorrect. Any help would be greatly appreciated.

## Your Question

I am trying to update data with GORM. I have multi-levels of data...eg
customers => customer_sites => customer_site_contacts
This application is a multi-tenant application, so when updating, to be safe, i add the tenant id in the where clause.

A json payload could look something like this.
{
    "id": "358d3a0b-1e25-49e5-9723-22d199b6ffcd",
    "clientId": "d97a96ca-6b05-423a-814c-7c4ba2a5ebe4",
    "name": "Test Update",
    "address": "test again",
    "lat": 0,
    "lon": 0,
    "sites": [
        {
            "id": "f971230f-cdc7-4a2a-a041-f163bc6e8a81",
            "name": "test site",
            "address": "site address",
            "lat": 21,
            "lon": -115,
            "radius": 0.25,
            "customerId": "358d3a0b-1e25-49e5-9723-22d199b6ffcd",
            "clientId": "d97a96ca-6b05-423a-814c-7c4ba2a5ebe4",
            "contacts": [
                {
                    "id": "3ec2d742-f11a-4370-a741-3ab5e8657950",
                    "name": "testy testerson",
                    "email": "testy@example.com",
                    "phone": "555-555-5555",
                    "contactType": 0,
                    "customerSiteId": "f971230f-cdc7-4a2a-a041-f163bc6e8a81",
                    "clientId": "d97a96ca-6b05-423a-814c-7c4ba2a5ebe4"
                }
            ]
        }
    ],
    "customerContacts": []
}

updateData is the struct version of the above payload.
I am using this call to update/create everything
DB.Debug().Session(&gorm.Session{FullSaveAssociations: true}).Where("client_id = ?, 'the client id').Save(updateData)
I also have create hooks where I create a uuid (column id) for any model being added to the database.

What is happening is that the site and contact are being re-inserted, and the customer is being updated.

## The document you expected this should be explained

https://gorm.io/docs/associations.html

## Expected answer

What I would expect to see is everything to be updated, instead of inserted.
If there are any nested objects without an id, those would end up being created.
If I use the the SkipHooks property, everything is updated, however, nothing will be created.

This question - [https://github.com/go-gorm/gorm/issues/3487](url) is basically exactly what I am trying to do, however, my nested data is being inserted instead of updated. Like these users, I cannot write specific code as I have written a generic GormRepo.

Thank You,
Neal

**Comment by jinzhu** [comment]
Hello @doppl-neal 

You should set site/customer's id to be unique, then it will be updated instead of to be reinserted.

**Comment by doppl-neal** [comment]
@jinzhu thank you for your response. I will try that, however, ID is set to be primary key so that implicitly states that it is unique.

**Comment by doppl-neal** [comment]
@jinzhu using a tag to set the id to be unique does not appear to work.

type Base struct {
	ID        string    `gorm:"primaryKey;unique;type:uuid;default:uuid_generate_v4();" json:"id"`
	CreatedAt time.Time `gorm:"type:timestamp without time zone;not null;"`
	UpdatedAt time.Time `gorm:"type:timestamp without time zone;not null;"`
}

Here is the payload for this update:
{
    "id": "358d3a0b-1e25-49e5-9723-22d199b6ffcd",
    "clientId": "d97a96ca-6b05-423a-814c-7c4ba2a5ebe4",
    "name": "Test Update",
    "address": "test again23",
    "lat": 0,
    "lon": 0,
    "customerContacts": [
        {
            "id": "05d7398d-edcf-4b89-9217-d52b43c5d022",
            "name": "check test",
            "email": "blha@blah.com",
            "phone": "555555555",
            "contactType": 0,
            "customerId": "358d3a0b-1e25-49e5-9723-22d199b6ffcd",
            "clientId": "d97a96ca-6b05-423a-814c-7c4ba2a5ebe4"
        }
    ]
}

Here is the log from GORM:
{"l":"debug","sha":"","t":1611676429,"caller":"/go/src/app/pkg/entity/dopplBaseEntity.go:35","m":"**** new UUID *** 663ba9a9-26d7-4e89-beba-c38f1c2c0200"}


2021/01/26 15:53:49 /go/src/app/pkg/providers/gormRepository.go:121

[0.615ms] [rows:1] **INSERT INTO "customer_contacts"** ("name","email","phone","contact_type_id","client_customer_id","created_at","updated_at","doppl_client_id","id") VALUES ('check test','blha@blah.com','555555555',0,'358d3a0b-1e25-49e5-9723-22d199b6ffcd','2021-01-26 15:53:49.478','2021-01-26 15:53:49.478','d97a96ca-6b05-423a-814c-7c4ba2a5ebe4','663ba9a9-26d7-4e89-beba-c38f1c2c0200') ON CONFLICT ("id") DO UPDATE SET "name"="excluded"."name","email"="excluded"."email","phone"="excluded"."phone","contact_type_id"="excluded"."contact_type_id","client_customer_id"="excluded"."client_customer_id","created_at"="excluded"."created_at","updated_at"="excluded"."updated_at","doppl_client_id"="excluded"."doppl_client_id" RETURNING "id"


2021/01/26 15:53:49 /go/src/app/pkg/providers/gormRepository.go:121

[2.296ms] [rows:1] UPDATE "client_customers" SET "name"='Test Update',"address"='test again23',"doppl_client_id"='d97a96ca-6b05-423a-814c-7c4ba2a5ebe4',"updated_at"='2021-01-26 15:53:49.478' WHERE doppl_client_id = 'd97a96ca-6b05-423a-814c-7c4ba2a5ebe4' AND "id" = '358d3a0b-1e25-49e5-9723-22d199b6ffcd'

**Comment by jinzhu** [comment]
Hello @doppl-neal 

Would you mind to create a reproducible GORM playground PR?
