### ISSUE TITLE
Transaction using DBResolver (two databases)

### ISSUE THREAD

**Issue by anshuljhawar** [go-gorm/gorm#4002]
## Your Question

I am trying to use transaction in a sharded database. So I have two databases `master` and `shard1`.

Following code is being used to start the transaction
```
// tx := repo.database.Begin() // transaction to be used for master database
tx := repo.database.Clauses(dbresolver.Use("shard1"), dbresolver.Write).Begin()
```

But still this transaction is creating entries in the `master` database. 

## The document you expected this should be explained
https://gorm.io/docs/dbresolver.html

## Expected answer
Transaction should be allowed separately for both `master` and `shard1`

Are transactions allowed only in one database? Or can we have transactions for any database, is there a different syntax/way to achieve this?

**Comment by jinzhu** [comment]
sorry, it is not supported now.

**Comment by anshuljhawar** [comment]
@jinzhu thanks! .. any plans to pick it up soon?

**Comment by SantoshSah** [comment]
@jinzhu Any update on this? Or any work around while using multiple databases and want to have transaction?

**Comment by anshuljhawar** [comment]
@jinzhu ... Looking at the code found this piece of code in plugin -> dbresolver-> callbacks.go

```
func (dr *DBResolver) switchSource(db *gorm.DB) {
	if !isTransaction(db.Statement.ConnPool) {
		db.Statement.ConnPool = dr.resolve(db.Statement, Write)
	}
}
```

Is there any specific reason why switching source is disabled during a transaction?

**Comment by bruce0205** [comment]
> @jinzhu Any update on this? Or any work around while using multiple databases and want to have transaction?

I used dblink as my work around solution for mysql.

```go=
tx := db.Begin()
if err := tx.Table(os.Getenv("app_db") + ".test").Create(&test1).Error; err != nil {
	tx.Rollback()
} else if err = tx.Table(os.Getenv("app_db") + ".test").Create(&test2).Error; err != nil {
	tx.Rollback()
}
tx.Commit()
```

**Comment by jinzhu** [comment]
this should be supported for a while.
