### ISSUE TITLE
Retrieving gorm object support pointer not only for struct

### ISSUE THREAD

**Issue by foreversmart** [go-gorm/gorm#4003]
## Describe the feature
GORM provides First, Take, Last method to retrieve a single object from the database. But only support struct or a Initialized pointer var like below:

``` go
var user User

// works
db.First(&user)
// SELECT * FROM `users` ORDER BY `users`.`id` LIMIT 1

// works
result := map[string]interface{}{}
db.Model(&User{}).First(&result)
// SELECT * FROM `users` ORDER BY `users`.`id` LIMIT 1

// doesn't work
result := map[string]interface{}{}
db.Table("users").First(&result)

// works with Take
result := map[string]interface{}{}
db.Table("users").Take(&result)

```
or

``` go
user := &User{}

// works
db.First(&user)
// SELECT * FROM `users` ORDER BY `users`.`id` LIMIT 1

// works
result := map[string]interface{}{}
db.Model(&User{}).First(&result)
// SELECT * FROM `users` ORDER BY `users`.`id` LIMIT 1

// doesn't work
result := map[string]interface{}{}
db.Table("users").First(&result)

// works with Take
result := map[string]interface{}{}
db.Table("users").Take(&result)
```

sometimes it's not convenient for use for large object. Most of the time our team use db model layer like below:
``` go
FindByUserID(uid uint32) (user *User, err error) {
	err = db.Where("uid = ? ", uid).First(&user).Error
	return
}
```
execute this code will get an "invalid value" error

so i want a feature can initialize the nil pointer var for retrieving gorm object. but i don't know whether this feature is permitted by the gorm design pattern. if permitted i'll make a pull request latter.

**Comment by jinzhu** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/6843/105820376-74baf300-5ff4-11eb-817c-487639875745.png">

https://gorm.io/docs/query.html#Retrieving-a-single-object

**Comment by foreversmart** [comment]
I know gorm only works when querying with struct or provides model value. my point is struct is not convenient for use for large object sometimes.

**Comment by foreversmart** [comment]
@jinzhu
