### ISSUE TITLE
Why my check not become effective?

### ISSUE THREAD

**Issue by Xsxdot** [go-gorm/gorm#4007]
## Your Question

Why my check not become effective?
![image](https://user-images.githubusercontent.com/24730668/105869298-0c8b0200-6032-11eb-833e-b974badba74f.png)

## The document you expected this should be explained

https://gorm.io/zh_CN/docs/constraints.html

## Expected answer

I want check string not ''

**Comment by Xsxdot** [comment]
Postgres

**Comment by jinzhu** [comment]
Don't get your question, if there are any issue, please create a playground PR.

**Comment by Xsxdot** [comment]
The constraints I set did not take effect. When I created the table using automatic migration, the constraints I set were not created

**Comment by Xsxdot** [comment]
type Category struct {
	commonModel.Model
	Name     string    `gorm:"type:varchar(20);not null;index;check:name_checker,name <> ''" json:"name"`
	Pid      int64     `gorm:"index;default:0" json:"pid"`
	Sort     int       `gorm:"default:100" json:"sort"`
	Products []Product `gorm:"ForeignKey:CateId" json:"products,omitempty"`
}

func (Category) TableName() string {
	return "css_category"
}

我想创建一个约束，让name不能为空，但是一直不生效，想请问一下是什么原因？用的postgres

**Comment by jinzhu** [comment]
the doc is for gorm v2
