### ISSUE TITLE
Parsing Error at DB Connection

### ISSUE THREAD

**Issue by mehmetkara5007** [go-gorm/gorm#4008]
> dsn := "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm"
> db, err := gorm.Open(sqlserver.Open(dsn), &gorm.Config{})

The above is connecting to DB.
My password  starts with/includes the character '@'.
The golang gives error because it parse the host name after '@'.

**This parsing structure should be change because the user name or password could include '@'.**

Thanks

**Comment by jinzhu** [comment]
GORM using driver github.com/denisenkom/go-mssqldb
