### ISSUE TITLE
Default value has no effect on UPDATE

### ISSUE THREAD

**Issue by f-blass** [go-gorm/gorm#4009]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/261

## Description

I annotated some columns in my model with e.g. gorm:"default:null" in my project.
This works great for INSERT with db.Save(), however if the entry already exists and GORM decides to perform an UPDATE the default value has no effect.

Expected: 
```sql
UPDATE `users` SET `created_at`="2021-01-27 14:36:37.253",`updated_at`="2021-01-27 14:36:37.254",`deleted_at`=NULL,`name`="f-blass",`age`=NULL,`birthday`=NULL,`company_id`=NULL,`manager_id`=NULL,`active`=false WHERE `id` = 1 
```

Got: 
```sql
UPDATE `users` SET `created_at`="2021-01-27 14:36:37.253",`updated_at`="2021-01-27 14:36:37.254",`deleted_at`=NULL,`name`="f-blass",`age`=0,`birthday`=NULL,`company_id`=NULL,`manager_id`=NULL,`active`=false WHERE `id` = 1
```

**Comment by doppl-neal** [comment]
if age is a nullable column in the db, you need to make it a pointer in your code.

**Comment by jinzhu** [comment]
use pointer or sql.NullInt64
