### ISSUE TITLE
Replace associations not working as expected

### ISSUE THREAD

**Issue by eloo** [go-gorm/gorm#4010]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/264

## Description
It looks like the association replace function is not working as expected as it was already mentioned 3 month ago into the docs comments
(http://disq.us/p/2cz6yps) 

So either its a bug or the documentation is not sufficient enough.

Maybe you can provide a proper example of how associations can be really replaced?

Thanks

**Comment by jinzhu** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/6843/106080171-8b2a9100-6151-11eb-863d-244ce09dcc2b.png">

if GORM doesn't works like as the document said, create a bug report.

**Comment by eloo** [comment]
@jinzhu  i guess i have created a bug report here? 
so why this closed? does seem to be fixed

**Comment by jinzhu** [comment]
I think this should works like the above document, a bug report have to follow the guide by having a reproducible playground PR. feel free to create a new one.

**Comment by eloo** [comment]
yep i know.. and also the guideline is that i have 2 days to provide this.. 
so please don't close my issue before these 2 days

**Comment by eloo** [comment]
playground link is now added

**Comment by jinzhu** [comment]
Hello, 

Association mode doesn't expect to update associations, it will use the `OnConflict` `DoNothing` mode.

Just added `FullSaveAssociations` support for Association mode, you could write it like below using the latest master.

```go
err = DB.Model(&user).Session(&gorm.Session{FullSaveAssociations: true}).Association("Pets").Replace(&pet2)
```

Thank you for your report.

**Comment by eloo** [comment]
@jinzhu 

Hi, 
okay just tested it and it looks promising 👍 
Do you mind to add this as an example to your docs?

Further i've seen that this will leave orphans in the database. Is there any way to get rid of orphans directly?

**Comment by aveyuan** [comment]
> @jinzhu
> 
> Hi,
> okay just tested it and it looks promising 
> Do you mind to add this as an example to your docs?
> 
> Further i've seen that this will leave orphans in the database. Is there any way to get rid of orphans directly?

Oh, I look you issue,Resolved a relationship saving error。


```
func TestGORM(t *testing.T) {
	toy1 := Toy{Name: "panda"}
	toy2 := Toy{Name: "dog"}
	user := User{Name: "jinzhu", Toys: []Toy{toy1, toy2}}

	DB.Create(&user)

	var result User
	if err := DB.First(&result, user.ID).Error; err != nil {
		t.Errorf("Failed, got error: %v", err)
	}

	// update username, save will update all toy,try it

	result.Name = "jinzhu2"
	DB.Save(result)
}
```

so， Now test is ok.

**Comment by Sh1d0w** [comment]
@jinzhu I second @eloo question. Why replacing model associations, does update set null on the foreign key of the rows, instead of deleting them? It just don't make sense. Furthermore `Replace` won't work if you set the models foreign key to not null, as it will fail to update the keys to null. This seems like a bug to me.

**Comment by dharkness** [comment]
Adding `Session(&gorm.Session{FullSaveAssociations: true})` did not solve the issue for me. The child records' foreign keys are set to `null` instead of being deleted. Why doesn't it delete the children, and how can I make it do so?
