### ISSUE TITLE
Preload nested struct associated with id stored in json field

### ISSUE THREAD

**Issue by PenF00k** [go-gorm/gorm#4011]
## Your Question
I have a Document struct with json field RefData. I want to preload File in Document like this
```
var rd RootDocument
db.Preload("Document.File").First(&rd)
```

I was able to preload it with AfterFind method where i set the FileID field by myself. But the v1.20.12 release broke this, i guess due to the order of Preload and AfterFind has changed.
Is there any other way or workaround how to preload nested struct based on id stored in json field (RefData)?
The structs I use
```
type RootDocument struct {
	ID                          int       `json:"id"`
	SortOrder                   float32   `json:"sortOrder"`
	DocumentID                  uuid.UUID `json:"documentId"`
	Document                    *Document `json:"document"`
}

type Document struct {
	ID                 uuid.UUID
	RefData            RefData
	FileID             *uuid.UUID
	File               *FileRecord
}

func (d *Document) AfterFind(tx *gorm.DB) (err error) {
	if d != nil {
		if fileID, err := uuid.Parse(d.RefData.RefID); err == nil {
			d.FileID = &fileID
		}
	}

	return
}

type RefData struct {
	Ref   string `json:"ref"`
	RefID string `json:"refId"`
}

func (rd RefData) Value() (driver.Value, error) {
	return json.Marshal(rd)
}

func (rd *RefData) Scan(value interface{}) error {
	bytes, ok := value.([]byte)
	if !ok {
		return errors.New(fmt.Sprint("Failed to unmarshal RefData json value:", value))
	}

	return json.Unmarshal(bytes, rd)
}

type FileRecord struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
}

Thank you for your great work!
```

## The document you expected this should be explained
https://gorm.io/docs/preload.html

## Expected answer
I expect that I can preload a struct which is associated with id stored in json field

**Comment by jinzhu** [comment]
This is not supported now, and the implementation sounds difficulty with a low profitability, so not going to support it.
