### ISSUE TITLE
Preloading all associations together with nested associations fails

### ISSUE THREAD

**Issue by asterikx** [go-gorm/gorm#4016]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/262

## Description

Since v1.20.12, preloading all associations together with nested associations (as also described in the [docs](https://gorm.io/docs/preload.html#Preload-All)) no longer works.

```
panic: assignment to entry in nil map
```

**Comment by LukeShay** [comment]
+1

**Comment by birdycn** [comment]
me too 

```
db.Preload(clause.Associations).Preload("ServiceProduct.ServiceType")
```
