### ISSUE TITLE
Append with unique index not failing for mysql

### ISSUE THREAD

**Issue by eloo** [go-gorm/gorm#4020]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/263

## Description
Hi,

i guess i've found a bug related to mysql and using a composite unique index (maybe also with other unique constraints).
When you append an entity with a composite unique index (combination of two column should be unique) the update on the database side is rejected or not saved but gorm is not responding with an error. 

It looks like this is only happening with mysql and not with sqlite or postgres.

best regards
eloo

**Comment by jinzhu** [comment]
Hi @eloo 

Thank you for your report, but seems database treat composited unique index on duplicated differently, don't think we can do anything for that? ;(

**Comment by eloo** [comment]
Hi, 
for me this looks like the created query is the problem
in mysql the query looks like this
```
 INSERT INTO `pets` (`created_at`,`updated_at`,`deleted_at`,`user_id`,`name`,`is_dog`,`id`) VALUES ('2021-01-29 09:04:18.471','2021-01-29 09:04:18.471',NULL,2,'Adjusted Pet2',false,4) ON DUPLICATE KEY UPDATE `user_id`=VALUES(`user_id`)
 ```
 
the stuff with "ON DUPLICATE" is swallowing the error. So IMHO this should be removed.

And please stop closing issues directly. this is actually not fixed or answered at the moment

**Comment by eloo** [comment]
Also for Save() its working as expected. So its not a problem in the database.
