### ISSUE TITLE
work with Postgres composite types

### ISSUE THREAD

**Issue by eureka101v** [go-gorm/gorm#4021]
## Your Question

I want to use the composite type feature of PostgreSQL in my code.And I found that grom's postgresql-driven pgx is  support composite type by defining DecodeBinary and EncodeBinary in pgtype interface (https://pkg.go.dev/github.com/jackc/pgtype#section-readme) .I want to know how can I use Gorm works with this interface

**Comment by jinzhu** [comment]
Define the scanner, valuer interface, and the `Value` method return itself
