### ISSUE TITLE
Different Query in Local and in Heroku

### ISSUE THREAD

**Issue by Vaerrwenn** [go-gorm/gorm#4022]
First of all, I'm sorry if I don't have the GORM Playground link.
So I have this problem where the Query in local and in Heroku are different despite having the same code.   
Here's the code:
```go
err = models.DB.Where(map[string]interface{}{"username": username}).First(&user).Error
```
So I tested in local (dev mode and prod mode) with random username and password, here's how the query looks like:
```sql
SELECT * FROM "users" WHERE "username" = 'wqeqweqwe' AND "users"."deleted_at" IS NULL ORDER BY "users"."id" LIMIT 1
```
But when in Heroku, this is how the query looks like:
```sql
SELECT * FROM "users" WHERE "username" = '123dawe213sada' AND "users"."deleted_at" IS NULL AND "users"."id" = 6 ORDER BY "users"."id" LIMIT 1
```
For some reason, it also search for a user ID where the ID = 6, but I didn't specify it anywhere in the code.
The DBString on local:
```go
dsn := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
		DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME)
db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
```
The DBString used on Heroku:
```go
db, err := gorm.Open(postgres.Open(os.Getenv("DATABASE_URL")), &gorm.Config{})
```
So my question is, is this a problem from my side (my code or my deployment) or is it from the GORM?
I hope that everything I gave can be helpful. If there's anything I can do to help, feel free to inform it to me.
Thank you for your assistance and attention!

**Comment by jinzhu** [comment]
Sounds like this issue https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety
