### ISSUE TITLE
random string "has" in code

### ISSUE THREAD

**Issue by genofire** [go-gorm/gorm#4024]
## Your Question
https://github.com/go-gorm/gorm/blob/7f198ead0e716265acd3491925e340bfae758e95/schema/relationship.go#L91

Where come this string "has" from? (and is it used anywhere else
Should it be a const?

## Expected answer
I make a const :+1: and here are the other places where it is used

----
I was just reading the your code, because i get a error on nested Preload - which not works, but step with Preload Works ;(

**Comment by jinzhu** [comment]
> I make a const 👍 and here are the other places where it is used

Fixed, the "has" is only for internal usage.

> I was just reading the your code, because i get a error on nested Preload - which not works, but step with Preload Works ;(

Could you make a reproducible PR for your issue?
