### ISSUE TITLE
I encountered a very strange query problem

### ISSUE THREAD

**Issue by 265525** [go-gorm/gorm#4025]
![FE0Y8 JY_M0%RH5N2O BZU1](https://user-images.githubusercontent.com/30653455/106281604-67af3580-627a-11eb-8928-6f920a5f0390.png)
![NTHR~C5TO9S9QI8P)EMG6C](https://user-images.githubusercontent.com/30653455/106281610-68e06280-627a-11eb-9b12-f8a5dd58d7d8.png)
![ON~9LDU%MO 0 43`)GNOHI8](https://user-images.githubusercontent.com/30653455/106281613-6978f900-627a-11eb-8aa8-3fa03b783315.png)
![4N47~(R`BA4CYY68$FV}) K](https://user-images.githubusercontent.com/30653455/106281712-8f9e9900-627a-11eb-81a4-f4c9d0866d2e.png)

Besides, I don't know how to get the result of SQL statement

**Comment by 265525** [comment]
result is nil

**Comment by 265525** [comment]
![2WVBQA{_V10G2BT{@OX1 JW](https://user-images.githubusercontent.com/30653455/106281950-e4421400-627a-11eb-8051-959ea8ca7460.png)

![N(C8@%ZTR C)OC7)(PQAW@E](https://user-images.githubusercontent.com/30653455/106281970-e99f5e80-627a-11eb-87f0-8bf4319a4e77.png)

**Comment by 265525** [comment]
I now construct my own SQL statement to solve this problem

**Comment by liuaiyuan** [comment]
```go
func (self *Order) GetOrder(orderid string)*Order{
  order := &Order{}
  Db.Model(&Order{}).Where("order_id = ?", orderid).First(order)
return order
}
```
OR

```go
func (self *Order) GetOrder(orderid string)(order Order){
  Db.Model(&Order{}).Where("order_id = ?", orderid).First(&order)
  return order
}
```
