### ISSUE TITLE
Select column for ST_AsBinary(location) as location

### ISSUE THREAD

**Issue by tabvn** [go-gorm/gorm#4031]
Hello all,

currently i have problem like this 

type Listing struct {
	Location      *Geo         `json:"location"`
}

so that is ok if i use this query db.Select("ST_AsBinary(location) as location").Find()....

but i would like there is way we can auto detect by column type and add wrapper ST_AsBinary(location) as location to select columns query.

Best regards,
Toan

**Comment by jinzhu** [comment]
refer https://gorm.io/docs/data_types.html#GormValuerInterface

**Comment by tabvn** [comment]
@jinzhu  could you give me a little details about select, it seem custom type is support for insert/update, but when we select 

there is custom type i did for location https://gist.github.com/tabvn/6db8f984c9f83e07ae26e5661f4ca858

insert, and update is ok, now there is way auto detect type and add wrap on preload, Join, and remove select * 

here is query 

```
SELECT ST_AsBinary(location) as location
```

so we need support wrap of column ST_AsBinary(col_name) as col_name 

Thank you
