### ISSUE TITLE
How do I define a one-to-one bidirectional reference?

### ISSUE THREAD

**Issue by songkang1993** [go-gorm/gorm#4036]
## Your Question
`
type Human struct {
	gorm.Model
	Name     string
	IDCardID int
	IDCard   IDCard
}

type IDCard struct {
	gorm.Model
	CardNO string
	Human Human
}
`

## The document you expected this should be explained

https://gorm.io/zh_CN/docs/belongs_to.html

## Expected answer
I want to get value by Human.IDCard and IDcard.Human.Is there any way to do it?

**Comment by jinzhu** [comment]
Don't really get your question, maybe you are asking `Preload`?
