### ISSUE TITLE
db.AutoMigrate with database schemas -> ERROR: syntax error at or near "$1" (SQLSTATE 42601)

### ISSUE THREAD

**Issue by edubudubolo** [go-gorm/gorm#4038]
## Description

I have been working during a personal project without problems. I created several tables with the customization of the name of the database schema, the tables are related to each other; the database is Postgresql. When executing the `go run main.go` command, the tables are created in the correct database schema with the correct relationships.

So I updated the GORM version and when I executed `go run main.go` I observed a syntax error when updating a CONSTRAINT in the DB. 

**Replicate the error:**

Create two related models

```go
type TableOne struct {
	ID       uint64 `json:"-" gorm:"primary_key;auto_increment"`
	TableTwo *TableTwo
}

type TableTwo struct {
	ID         uint64 `json:"-" gorm:"primary_key;auto_increment"`
	TableOneID uint64
}
```

Then TableName overrides the table to support the names of the database schemas. The name of the database schema is: "sujeto"
```go
func (TableOne) TableName() string {
	return "sujeto.table_one"
}

func (TableTwo) TableName() string {
	return "sujeto.table_two"
}
```

After making the configurations to the database, we proceed with the migration of the models to the DB.

```go
db.AutoMigrate(
	&entity.TableOne{}, &entity.TableTwo{},
)
```

The first time `go run main.go` is executed, it executes without errors and the tables are created in the DB with their relationships. But the next times `go run main.go` is executed, the following message will be displayed:

`ERROR: syntax error at or near "$1" (SQLSTATE 42601)
[0.138ms] [rows:0] ALTER TABLE '{"sujeto"."table_two" [] false}' ADD CONSTRAINT "fk_sujeto_table_one_table_two" FOREIGN KEY ("table_one_id") REFERENCES "sujeto"."table_one"("id")`

Could you tell me if things are being done correctly or in what way can we correct the syntax error?

**Comment by jkomericki** [comment]
@edubudubolo did you manage to solve this issue? Im having the same problem.

**Comment by edubudubolo** [comment]
No, this question was not answered. Before it worked perfectly now we must drag this error.

**Comment by jinzhu** [comment]
To report an issue, please create a reproducible playground PR.

**Comment by mateusscheper** [comment]
Playground runs under Docker and my environment doesn't support it because of my current settings (can't have Virtualbox and Docker at the same time).

I'm having the same problem.
Can anyone create a playground PR?
I really need this fixed :( 
```
type Device struct {
	ID               uint `gorm:"primaryKey"`
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             string
	OwnerID          uint   `gorm:"not null"`
	Version          string
	Updatable        bool          `gorm:"default:false"`
	Active           bool          `gorm:"default:true"`
	Charts           []charts.Line `gorm:"-"`
	ModelID          uint
	Sensors          []Sensor `gorm:"many2many:device_sensor;"`
}

func (Device) TableName() string {
	return "device.device"
}
```

```
type DeviceModel struct {
	ID        uint `gorm:"primaryKey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Version   string
	Active    bool     `gorm:"default:true"`
	Devices   []Device `gorm:"foreignKey:ModelID"`
}

func (DeviceModel) TableName() string {
	return "device.model"
}
```
```
if err := db.AutoMigrate(
		&entity.DeviceModel{},
		&entity.Device{},
                ...
	); err != nil {
		fmt.Println("Migration failed!")
		log.Fatal(err.Error())
	}
```

Error:
```
ALTER TABLE '{"device"."device" [] false}' ADD CONSTRAINT "fk_device_model_devices" FOREIGN KEY ("model_id") REFERENCES "device"."model"("id")
ERROR: syntax error at or near "$1" (SQLSTATE 42601)
```

**Comment by maxzaleski** [comment]
From the output @mateusscheper provided, it seems as though the structure `gorm.Expr` is substituted verbatim without adequately checking for empty fields.

After some debugging, I believe, although I can't be sure, that the issue resides in the structure's `Build` (see `finisher_api.go:640`) method which takes care of substituting the necessary bytes into the SQL statement before execution.

This issue also seems to be related to slices (and maps?) as I haven't encountered the issue using the `embedded` tag.

I would get started on implementing a solution, however, this seems like a much broader issue with larger ramifications. I don't believe to have a sufficient understanding of the codebase in order to propose a solution that will take into account the various different scenarios.

Perhaps @jinzhu or any other experienced contributor could investigate ahead of the next release? 🙏🏼  This is an application breaking bug and should be addressed ASAP.

My current workaround is disabling gorm on the field (`gorm:"-"`) and manually mapping the records through the driver's built-in `rows` method, although this defeats the purpose of an ORM entirely.

**Comment by maxzaleski** [comment]
Rolling back to `v1.20.8` fixed the issue for me.

**Comment by edubudubolo** [comment]
@maxzaleski yes your solution is the right, at least until @jinzhu  fixes it in the new version.

The command is:
```
go get gorm.io/gorm@v1.20.8  
```
Then the postgres dependency is downloaded automatically when executing the command:

```
go run main.go
```

**Comment by jinzhu** [comment]
I don't have any issue on my local with 

```go
	gorm.io/driver/sqlserver v1.0.6
	gorm.io/gorm v1.21.3
```

```go
type TableOne struct {
	ID       uint64 `json:"-" gorm:"primary_key;auto_increment"`
	TableTwo *TableTwo
}

type TableTwo struct {
	ID         uint64 `json:"-" gorm:"primary_key;auto_increment"`
	TableOneID uint64
}

func (TableOne) TableName() string {
	return "sujeto.table_one"
}

func (TableTwo) TableName() string {
	return "sujeto.table_two"
}

func TestGORM(t *testing.T) {
	fmt.Println(DB.Migrator().DropTable("sujeto.table_one"))
	fmt.Println(DB.AutoMigrate(&TableOne{}))
}
```

To report an issue, please create a reproducible playground PR.

**Comment by edubudubolo** [comment]
@jinzhu  Try the same example, but using a database in postgresql

**Comment by jinzhu** [comment]
> @jinzhu Try the same example, but using a database in postgresql

that's what I am doing.

**Comment by edubudubolo** [comment]
@jinzhu  I have done the tests with various combinations of libraries, and I have discovered that the problem is in the postgresql library, because I have tried with this configuration and I have obtained the error of the description.

```
gorm.io/driver/postgres v1.0.8
gorm.io/gorm v1.21.3
```

I have got the following error:
```
ERROR: syntax error at or near "$1" (SQLSTATE 42601)
[0.296ms] [rows:0] ALTER TABLE '{"sujeto"."table_two" [] false}' ADD CONSTRAINT "fk_sujeto_table_one_table_two" FOREIGN KEY ("table_one_id") REFERENCES "sujeto"."table_one"("id")
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
```

I have changed the postgresql library to a previous one and everything has worked fine, the configuration is
```
gorm.io/driver/postgres v1.0.6
gorm.io/gorm v1.21.3
```

It is evident that the problem is in the way the table name is built, I replaced the name this name '{"sujeto"."table_two" [] false}' by the name of the table to be affected and the command was executed fine.

Note that the error occurs the second time you run ```go run main.go```. The first time the tables are created correctly, the second time, when the two tables are already created in the DB, and still execute ```db.AutoMigrate(&entity.TableOne{}, &entity.TableTwo{})``` the error occurs
