### ISSUE TITLE
Preload nested children: New Release?

### ISSUE THREAD

**Issue by ChewbaccaCookie** [go-gorm/gorm#4040]
## Your Question

You have described in Issue #4027 that it's possible to preload nested children by using `"Whatever." + clause.Associations`.
If you now try to use this syntax with version 1.20.12 you run into the following panic:
```
panic: assignment to entry in nil map
```

If you now try to reproduce this error in gorm-playground all is working fine. But if you remove there the line
```
replace gorm.io/gorm => ./gorm
```
in go.mod you run in the same issue.
Is there the possibility to trigger a new Release with the fixed nested preloading?

## The document you expected this should be explained

None

## Expected answer

Is there the possibility to update the version?

**Comment by jinzhu** [comment]
yes, need to use the latest master or just initialize your data like:

```go
var data map[string]interface{} // no
var data = map[string]interface{}{} // yes
```
