### ISSUE TITLE
How to query users by count on a join sub table?

### ISSUE THREAD

**Issue by jinfagang** [go-gorm/gorm#4046]
Hi, I google 2 days and nowhere to go but ask this question here. I have two tables:

```
struct User {
UserName string
Tasks  Task[]
}

struct Task {
}
```
every User has many tasks, I want query users out by acending order with tasks num.

I think this is very common in real-life usage but I can not found a single golang code to do this. Anybody could help?

I tried this:

```golang
DB.Table("users").Order()
```

**Comment by jinzhu** [comment]
not really a GORM question, Select tasks count with SQL Expression with `gorm.Expr` and order by the field.
