### ISSUE TITLE
FirstOrCreate runs AfterFind hook and stops on error

### ISSUE THREAD

**Issue by abelseniorly** [go-gorm/gorm#4048]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/272

## Description
The FirstOrCreate should actually check if there are any rows in the db, and if it exists then run AfterFind else create the row first.

In my case however the function returns error because it runs AfterFind() before creating the row, and thus panics "Unknown related entity for entity task : "
It does not run BeforeCreate at all

**Comment by abelseniorly** [comment]
FYI... I think in FirstOrCreate the AfterFind is called even if there is no rows returned, and if we have any field updation on AfterFind() it gets done too : which gets reciprocated on BeforeCreate/BeforeSave.... I believe this is an unwanted behaviour @jinzhu

**Comment by abelseniorly** [comment]
https://github.com/go-gorm/playground/pull/272

**Comment by abelseniorly** [comment]
Firgured out this is a problem with Find as well as FirstOrCreate... Essentially AfterFind should not run if there are no rows affected after find query
@jinzhu

**Comment by abelseniorly** [comment]
https://github.com/go-gorm/playground/pull/272

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
