### ISSUE TITLE
Is it required to use Model() before query

### ISSUE THREAD

**Issue by lboquan** [go-gorm/gorm#4049]
## Your Question

I use GORM 2.x in my projects  for a few period; however, I am confused if I should use Model() before query or not.

## The document you expected this should be explained

https://gorm.io/docs/query.html

## Expected answer

For example, what's the difference below:

db.Model(&User{}).First(&user,1)
db.First(&user,1)

**Comment by jinzhu** [comment]
it's same. just use the last one is ok.

the `Model` methods is required when you are using a map or a different struct as result
