### ISSUE TITLE
Error Trace 支持问题

### ISSUE THREAD

**Issue by duguying** [go-gorm/gorm#4052]
## Your Question

通常业务逻辑层的逻辑层次非常复杂，可能在多出涉及到gorm相关的操作，例如一个请求中有多出涉及到`First()`查询，`First()`查询未找到数据时通常会报出`record not found`错误，或者其他的db操作也可能返回error，此处error通常直接逐层抛出到接口返回，但是一旦逻辑复杂了就不容易确定error是从哪一个gorm调用处抛出。因此，排查问题的时候十分复杂。

## The document you expected this should be explained

因此，希望能够在gorm层的error中包含error trace，这样一来就可以直接追踪出错位置，以方便排查。例如，我修改gorm底层error返回 （https://github.com/duguying/gorm/commit/8437348fb5004e64590ae235f7e07f5285d2bfbc），使用go-error包裹，这样就能在gin的action层接口中间件中批量定位error的位置。实际使用效果如图

![image](https://user-images.githubusercontent.com/3050360/106999343-fc58ec80-67c0-11eb-8d36-80ed08aaa3a9.png)

## Expected answer

@jinzhu 请问大佬gorm v2 中是否可以考虑支持 error trace ？

**Comment by jinzhu** [comment]
GORM already display the line raised the error, and I don't really want to integrate a third party errors lib. ;(

**Comment by duguying** [comment]
> GORM already display the line raised the error, and I don't really want to integrate a third party errors lib. ;(

那是否可以接受非第三方原生的 error trace 功能代码合并，如果可以的话，我可以原生实现 error trace 并发送 Pull Request 给您

**Comment by jinzhu** [comment]
建议先看看修改下 logger, 集成这个 error wrapper 应该可以满足需求.

我个人感觉没有必要对用户暴露 GORM 底层是那个文件暴露出的错误，实际价值不大，用户只需要是用户的代码里那一行出的错，这个的话通过 logger 就可以实现了

**Comment by duguying** [comment]
> 建议先看看修改下 logger, 集成这个 error wrapper 应该可以满足需求.
> 
> 我个人感觉没有必要对用户暴露 GORM 底层是那个文件暴露出的错误，实际价值不大，用户只需要是用户的代码里那一行出的错，这个的话通过 logger 就可以实现了

对，实际上也只是关注用户代码，并不关注gorm文件报错行。只是希望能trace所有的用户代码调用链，以便于调试。我研究一下gorm logger。多谢

**Comment by jinzhu** [comment]
如果 logger 里满足不了需求的话，考虑定制个callback, 判断下有 db.Error 的话，用 wrapper 修改一下就行
