### ISSUE TITLE
Append with unique index not failing for mysql

### ISSUE THREAD

**Issue by eloo** [go-gorm/gorm#4054]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/263

## Description
Hi,

i guess i've found a bug related to mysql and using a composite unique index (maybe also with other unique constraints).
When you append an entity with a composite unique index (combination of two column should be unique) the update on the database side is rejected or not saved but gorm is not responding with an error. 

It looks like this is only happening with mysql and not with sqlite or postgres.

best regards
eloo

---

Hi, 
for me this looks like the created query is the problem
in mysql the query looks like this
```
 INSERT INTO `pets` (`created_at`,`updated_at`,`deleted_at`,`user_id`,`name`,`is_dog`,`id`) VALUES ('2021-01-29 09:04:18.471','2021-01-29 09:04:18.471',NULL,2,'Adjusted Pet2',false,4) ON DUPLICATE KEY UPDATE `user_id`=VALUES(`user_id`)
 ```
 
the stuff with "ON DUPLICATE" is swallowing the error. So IMHO this should be removed.

And please stop closing issues directly. this is actually not fixed or answered at the moment

---

Also for Save() its working as expected. So its not a problem in the database.

**Comment by jinzhu** [comment]
MySQL doesn't think composited unique index on duplicated as an error, and to be honestly, I think this behavior sounds correctly to me, appending an existing association to a record should silently skip it, and return no error.

But Sqlite, Postgres does think this as an error, so GORM will returns the database error back to the client.

Not sure what kind of change do you want GORM to make?

**Comment by eloo** [comment]
The problem here i see is that the behaviour feels really inconsistant. 
1. The behaviour changes heavily depending on the used database
2. The behaviour changes on the same database for two different calls. With append we get no error but with save for the entity we get an error. This feels not really expectable because the operation to the database is mostly the same. 

So i think the best would be to make the append method constitant for the databases (no error) or related to the database action (error).

**Comment by jinzhu** [comment]
> The behaviour changes on the same database for two different calls. With append we get no error but with save for the entity we get an error. This feels not really expectable because the operation to the database is mostly the same.

If you are using `Save` with `OnConflict` clause, you should get the same behaviour

**Comment by eloo** [comment]
But thats NOT what i want. Currently i'm using the default methods and they behave differently.
Also when i use OnConflict with save it will still differ for the databases.

**Comment by jinzhu** [comment]
as the mysql server doesn't return an error in this case, so I think GORM can't help on that ;(

Maybe check the RowsAffected for how many records updated.
