### ISSUE TITLE
Please do not perform defer operation in for.

### ISSUE THREAD

**Issue by daheige** [go-gorm/gorm#4058]
https://github.com/go-gorm/gorm/blob/3d3208ed602cdf219cc0501a05bd9f00c6b4bd12/gorm.go#L111

In golang, the defer code block will add a function call to the function call list. This function call is not an ordinary function call, but a function call is added after the function returns normally, that is, after return. Therefore, defer is usually used to release function internal variables or release some resources, such as file closing, resource closing and so on.

Rule 1 When defer is declared, its parameters will be parsed in real time
Rule 2 The execution order of defer is first-in-last-out, please do not perform defer operations in for. When multiple defer code blocks are defined at the same time, the golang installation calls defer in the order of first definition and then execution.
Rule 3 Defer can read the well-known return value, and defer is executed after the return call.

**Comment by jinzhu** [comment]
yes, and the plugin need to be called after the initialization, and each plugin should be independent.
