### ISSUE TITLE
the exported function or method requires necessary comments 

### ISSUE THREAD

**Issue by daheige** [go-gorm/gorm#4060]
https://github.com/go-gorm/gorm/tree/master/clause

I have been doing a lot of work on the code specification to promote the entire team to do code cr/mr operations, so as to better improve the ability of each gopher in the team. The only purpose is code quality. Please take a look at some simple adjustments I made. I will gradually point out the irregularities in Gorm later, so that more developers will know that maybe this is a process of diss, but there is no good norms and habits. For an industry For libraries that are used frequently, I believe that more and more people will complain more to your gorm community. Please accept this fact. 
https://github.com/daheige/gorm/commit/418b9834a78f774557d6dd4803a0a4d8038d3914

There are two code bases below. As for code quality and code specifications, I am strict with the team and have unified specifications. 
https://github.com/daheige/gmicro
https://github.com/daheige/tigago

In the go standard code specification, necessary comments are required for the exported functions or methods, so that users can better understand what developers need to express for some libraries or components. Some tools have non-standard specifications when doing code scanning. It failed the test. I read a lot of gorm code and found that the code specification is not enough. I hope it can be improved later. I still stick to my point of view. The code is written for humans, not for machines. While ensuring quality, the link of code style is also indispensable. 

As a more public library used in the industry, we should pay more attention to code quality and code specifications, and hope that the gorm development team can do better in the future.
There are many code specifications in the industry. The Go code specifications of each company and team are different, but they are similar and similar. Good code specifications can not only help the team or developers better understand the intent of the code base, but also improve the work efficiency of developers and make the code more readable. 

For the code, you can see that many large companies in the industry have their own code specifications. For example, Alibaba, uber, facebook, and aws have their own set of code specifications.

**Comment by jinzhu** [comment]
This is some nice things to do, but I don't have the time recently. (and from my previous work experience on v1 by completing the document for each method, this doesn't provide much help...)

**Comment by daheige** [comment]
Maybe as you said, but as a component that is frequently used in the industry, it is suggested that these steps should not be omitted. If there is no time to deal with it, other gophers in the community can handle it, and then you are responsible for Cr / Mr. maybe this suggestion is OK?



发自我的iPhone


------------------ Original ------------------
