### ISSUE TITLE
support for hasMany relationship for primitive types (string, int)

### ISSUE THREAD

**Issue by prabhatsharma** [go-gorm/gorm#4070]
## Describe the feature

Currently hasMany works only for objects.

e.g.

This works

```
{
    "person": {
        "name": "Superman",
        "favoritecolors": [{
            "ID": 1,
            "color": "Black"
        },
        {
              "ID": 2,
              "color": "Blue"
          }]
      }
}

```
This does not

```
{
    "person": {
        "name": "Superman",
        "favoritecolors": ["Black", "Blue"]
    }
}
```

## Motivation

Many a times when we get data from external sources, we do not have control on data structure and this is pretty common.

**Comment by jinzhu** [comment]
Customize a datatype? and save them as string into database?

**Comment by prabhatsharma** [comment]
We won't be able to query them if stored as string. Also I will have to have an intermediate data type that first unmarshalls the data in original format and then convert it to the string format.

```
{
    "person": {
        "name": "Superman",
        "favoritecolors": "Black, Blue"
    }
}
```
