### ISSUE TITLE
Bug when using First(&model, id)

### ISSUE THREAD

**Issue by surya4crowde** [go-gorm/gorm#4071]
I use Soft Deletable feature in gorm and when running query to get data by id using `First(&model, id)` i got this error

```bash
Error 1054: Unknown column 'c9916c01' in 'where clause'
[0.409ms] [rows:0] SELECT * FROM `todo` WHERE c9916c01-5c0f-441d-83a6-b54ae1526d40 AND `todo`.`deleted_at` IS NULL ORDER BY `todo`.`id` LIMIT 1
```
SQL Genereration missing for `id` field

**Comment by jinzhu** [comment]
https://gorm.io/docs/query.html#Retrieving-objects-with-primary-key

<img width="813" alt="image" src="https://user-images.githubusercontent.com/6843/107327148-9a152a00-6ae7-11eb-8a60-cf4aa066fbbc.png">

**Comment by surya4crowde** [comment]
@jinzhu sorry for my mistake... for delete, can we use that way?
