### ISSUE TITLE
Improve adding empty array throws an error: empty slice found 

### ISSUE THREAD

**Issue by vikmeup** [go-gorm/gorm#4076]
## Describe the feature

Currently if you call `AddCars([]Cars{})` it will throw an error on DB layer, instead of success message, as this is command that resulted object might be empty, checking for `len(cars)` feels very redundant for each call

```
func AddCars(cars []Car) error {
	return DB.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "id"}},
		DoUpdates: clause.AssignmentColumns([]string{"updated_at"}),
	}).Create(&cars).Error
}
```

```
/cars.go:1 empty slice found
[0.027ms] [rows:0] INSERT INTO "cars" ("updated_at","id") VALUES  ON CONFLICT ("id") DO UPDATE SET "updated_at"="excluded"."updated_at"
```

## Motivation

Current workaround

```
func AddCars(cars []Car) error {
	if len(cars) == 0 {
		return nil
	}
	return DB.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "id"}},
		DoUpdates: clause.AssignmentColumns([]string{"updated_at"}),
	}).Create(&cars).Error
}
```

Any chance to improve this?

**Comment by jinzhu** [comment]
I would like to keep current behaviour, to make sure this is the expected situation.

**Comment by vikmeup** [comment]
> I would like to keep current behaviour, to make sure this is the expected situation.

Is it worth adding as customizable parameter into gorm config?

**Comment by wchargin** [comment]
> I would like to keep current behaviour, to make sure this is the expected situation.

Go proverbs say, "make the zero value useful". `slices.Sort([]int{})` doesn't panic. `buffer.Write([]byte{})` doesn't return an error. This choice just forces callers to make an extra check and breaks [long-standing API design principles][1] by introducing a removable discontinuity. Please reconsider.

[1]: https://www.infoq.com/articles/API-Design-Joshua-Bloch/
