### ISSUE TITLE
Has Many Association array gets created again on Updation

### ISSUE THREAD

**Issue by abelseniorly** [go-gorm/gorm#4079]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/276

## Description

I tried to update a model that has a 'Has Many' associated array inside it. Even though the association was once created, on the next update of User model, the array elements are being created again, and thereby calls BeforeCreate ...

**Comment by jinzhu** [comment]
duplicated with https://github.com/go-gorm/gorm/issues/4067.
