### ISSUE TITLE
[Help] Batch delete with same user_id

### ISSUE THREAD

**Issue by itzmanish** [go-gorm/gorm#4080]
## Your Question

How do I batch delete multiple ids(primary_key) which have same user_id given?

## What I did?
` ids = []uuid.UUID `

` res := p.db.Table("rooms").Delete(ids, &store.Room{UserID: uid}) `

## What I got?

It deletes every Room from DB .

## Expected result

This should delete only those with primary_key matched with id of ids array and those userid should be same as uid.

## Version 
GORM v1

**Comment by jinzhu** [comment]
maybe you should write it like :

```go
db.Delete(&Room{}, "user_id IN (?)", ids)
```

**Comment by itzmanish** [comment]
This is what I did 

`res := p.db.Where("user_id = ?", uid).Delete(&store.Room{}, ids)`

Is it optimal solution?
