### ISSUE TITLE
Bug with self-join preload

### ISSUE THREAD

**Issue by omarhachach** [go-gorm/gorm#4083]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/278

## Description

I wanted to self-join preload, but it panics. (It is a use case already covered in preload, just isn't included in `main_test.go`, even though it is included in the User model)

**Comment by jinzhu** [comment]
Join preload only works with `belongs to`, `has one`, but Team is a `has many` relationship

https://gorm.io/docs/preload.html#Joins-Preloading
