### ISSUE TITLE
Error Suggests Executing as a Prepared Statement

### ISSUE THREAD

**Issue by cameron-dunn-silo** [go-gorm/gorm#4084]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/280

I am not sure if this issue is specific to PostGres or not. Most of the tests are skipped because `SEQUENCE` doesn't seem to be supported for sqlite. I posted local run results for postgres.

Also the first commit (which doesn't use `SEQUENCE`) did pass for sqlite, but showed the correct error for postgres. The error shown for mysql I wasn't sure about.

## Description

Using `Raw` or `Exec` containing multiple valid SQL statements should be executable, as in GORM V1. When I tried to execute two statements with GORM V2, I see an error saying `ERROR: cannot insert multiple commands into a prepared statement (SQLSTATE 42601);` (postgres).

GORM has a Prepared Statement Mode and I would assume that when that is not enabled commands would not be executed as prepared statements.

I'm not totally sure if this is a bug, but the error mentioning a prepared statement is what confused me. That made me think this may be a larger issue where something is being executed as a prepared statement when it should not be.

**Comment by jinzhu** [comment]
Hello, we have changed the Postgres's driver to pgx in GORM V2, which will do the prepared stmt before executing SQL

You could use the `PreferSimpleProtocol` mode or keep use the old Postgres driver. 

Refer: https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL
