### ISSUE TITLE
GORM Is Reporting "Record Not Found" Despite Record Existing And Raw Query Working Through Postgresql Shell

### ISSUE THREAD

**Issue by bonedaddy** [go-gorm/gorm#4087]
For whatever reason I'm encountering a bug where GORM returns "record not found" despite the example query it shows working when executed against postgresql directly. As per the following screenshot, "record not found" is reported, but when running the query that it shows was ran through the postgresql shell it matches a record.

Version information (postgres driver): `gorm.io/driver/postgres v1.0.6`
Version information (gorm): `gorm.io/gorm v1.20.9`

![err-not-found](https://user-images.githubusercontent.com/17089485/107896923-abb76100-6f2f-11eb-8964-c907693b537c.png)

**Comment by bonedaddy** [comment]
appears to be a problem with my local computers docker networking

**Comment by jaimeteb** [comment]
@bonedaddy I'm experiencing the same issue with PostgreSQL on Docker Compose. How did you manage to solve this?
