### ISSUE TITLE
使用Create方法批量插入模型（结构体类型）时，若使用了Upsert 处理冲突，执行后，结构体列表中每个元素自动补充的自增主键的值可能是错的

### ISSUE THREAD

**Issue by Lyuaesop** [go-gorm/gorm#4093]
![image](https://user-images.githubusercontent.com/79134077/108033046-5c2b7f00-706e-11eb-865e-4af9b9c041ae.png)

![image](https://user-images.githubusercontent.com/79134077/108032579-ab24e480-706d-11eb-9627-fb0625b632b6.png)

![image](https://user-images.githubusercontent.com/79134077/108032855-11aa0280-706e-11eb-879f-6010183966ce.png)

注：这种情况发生在 批量插入的列表数据中有些记录在数据库中已存在，并且会执行更新操作
参考 https://dev.mysql.com/doc/refman/5.7/en/mysql-affected-rows.html

**Comment by chenlujjj** [comment]
碰到同样的问题了， 为啥要关掉呢。。。
