### ISSUE TITLE
charset设置无效

### ISSUE THREAD

**Issue by iHDJ** [go-gorm/gorm#4094]
## Your Question
gorm设置chatset=utf8mb4使用无效
dns参数为charset=utf8mb4&parseTime=True&loc=Local
然而在插入数据的时候仍然提示：Incorrect string value: '\xE9\xBB\x84\xE5\xBE\xB7...' for column 'name' at row 1
数据库版本:mysql5.7

**Comment by day112** [comment]
我也遇到了同样的问题，  通过gorm 会报同样的错误， 但是 把打印的sql 在 终端可以插入成功
