### ISSUE TITLE
Panic on using Omit with Update with map

### ISSUE THREAD

**Issue by itzmanish** [go-gorm/gorm#4098]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/282

## Description

When using Select Or Omit I get panic because stmt.Schema is nil and it performs stmt.Schema.LookUpField(column) in https://github.com/go-gorm/gorm/blob/73d44a4f97c1e7ed703ca16eeb589525f15decb8/statement.go#L612 

## Screenshot
![bitmap](https://user-images.githubusercontent.com/12438068/108165280-4d99a200-7118-11eb-86d1-f495b05bdece.png)

**Comment by itzmanish** [comment]
Any reason of this bug?

**Comment by jinzhu** [comment]
Should specify the `Model` value or the `Statement.Schema` is nil

**Comment by itzmanish** [comment]
So this doesn't work with using `Table` instead of `Model`
