### ISSUE TITLE
Driver for pure Go sqlite implimentation

### ISSUE THREAD

**Issue by amnonbc** [go-gorm/gorm#4101]
## Describe the feature
Driver for https://pkg.go.dev/modernc.org/sqlite

## Motivation
So that we can use a sqlite DB without needing CGO.
This makes cross compilation much easier.

## Related Issues

https://pkg.go.dev/modernc.org/sqlite

**Comment by yevgenypats** [comment]
@amnonbc here it is
https://github.com/cloudquery/sqlite

Note: the modernc.org sqlite client is not supporting a lot of features so it will work for very basic use-cases.

**Comment by amnonbc** [comment]
> @amnonbc here it is
> https://github.com/cloudquery/sqlite
> 
> Note: the modernc.org sqlite client is not supporting a lot of features so it will work for very basic use-cases.

Thanks @yevgenypats !
I tried this as a drop in replacement for gorm.io/driver/sqlite,
and everything except aggregates just works.

**Comment by notnil** [comment]
Can this be merged into Gorm itself?

**Comment by olliepotter** [comment]
Just pitching in and saying I would absolutely love this to be officially supported. Going to give this a try.

**Comment by cnmade** [comment]
The mattn/go-sqlite3 driver has a problem , which affect me ,  the string will sometime auto convert to Float.. very strange. 
So we shall official support pure golang driver for sqlite? i tested it , works as normal.

https://github.com/mattn/go-sqlite3/issues/970

**Comment by muety** [comment]
Just came across this post in search for a pure Go implementation of SQLite. From my understanding, [cznic/sqlite](https://gitlab.com/cznic/sqlite) is the only one currently. [glebarez/go-sqlite](https://github.com/glebarez/go-sqlite) then seems to build on top of that (what is the difference?) and [glebarez/sqlite](https://github.com/glebarez/sqlite) is the compatible GORM driver. Is that about correct? 

Is anyone using these "in production" in their projects? What is your experience with these? Can this be used as a fully-fledged drop-in replacement for [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3) + [go-gorm/sqlite](https://github.com/go-gorm/sqlite)?

**Comment by glebarez** [comment]
modernc.org/sqlite consists of:

pure go implementation of SQLite (original C codebase is regularly transpiled into Go with great tools from modernc.org
implementation for golang database/sql driver interface as described in https://pkg.go.dev/database/sql/driver
glebarez/go-sqlite:
is just a fork of modernc/sqlite with slight changes in the driver part (2), to behave more closely to mattn’s CGo version (https://github.com/mattn/go-sqlite3). this slight changes allowed it to be fully compatible with GORM (the GORM driver is in https://github.com/glebarez/sqlite)

**Comment by muety** [comment]
Thanks for clarifying!

**Comment by muety** [comment]
Is https://github.com/glebarez/sqlite actually being maintained still? There haven't been any commit for more than a year. Is it recommendable to switch to a different driver, if yes, what options do exist?
