### ISSUE TITLE
Struct tag introspector

### ISSUE THREAD

**Issue by maguro** [go-gorm/gorm#4102]
## Describe the feature

It would be nice to be able to, given a Gorm tagged struct, obtain the table name, columns, and indexes.

## Motivation

Sometimes SQL commands need to be crafted and sent to `Raw(...)`.  Having a facility to obtain Gorm's interpretation of a tagged struct would help generate the SQL commands in a robust way.

**Comment by jinzhu** [comment]
don't get it, can you make an example?
