### ISSUE TITLE
Aim of Statement.clone() method and DB.clone 

### ISSUE THREAD

**Issue by Xieyuschen** [go-gorm/gorm#4106]
## Your Question
I look into `chainable_api.go` to learn about chainable method like what happened when I call `db.Where(some-arugments..)`. 
Source code here:
```go
func (db *DB) Where(query interface{}, args ...interface{}) (tx *DB) {
	tx = db.getInstance()
	if conds := tx.Statement.BuildCondition(query, args...); len(conds) > 0 {
		tx.Statement.AddClause(clause.Where{Exprs: conds})
	}
	return
}
```
I know `tx = db.getInstance()` makes sure thread safe, but I'm confused to the `clone()` method in implement of `db.getInstance()`
```go
func (db *DB) getInstance() *DB {
	if db.clone > 0 {
		tx := &DB{Config: db.Config}
		if db.clone == 1 {
			// clone with new statement
			tx.Statement = &Statement{
				DB:       tx,
				ConnPool: db.Statement.ConnPool,
				Context:  db.Statement.Context,
				Clauses:  map[string]clause.Clause{},
				Vars:     make([]interface{}, 0, 8),
			}
		} else {
			// with clone statement
			tx.Statement = db.Statement.clone()
			tx.Statement.DB = tx
		}
		return tx
	}

	return db
}
```
I'm confused to why there is a clone in a DB,  and what a `clone` method do in short?

## The document you expected this should be explained
- something about `DB.clone`,method `clone()` and the `Statement`.
## Expected answer

- the aim of clone in `DB` struct
In `getInstance()` method code, I find `clone` is used as a condition.  So I guess `clone` constrict the db cloned by a transaction.
```go
type DB struct {
	*Config
	Error        error
	RowsAffected int64
	Statement    *Statement
	clone        int
}
```
- Why there is a `clone()` method

**Comment by jinzhu** [comment]
refer https://gorm.io/docs/method_chaining.html https://gorm.io/docs/hooks.html#Modify-current-operation

also checkout `*gorm.DB`'s `Session`, `getInstance` methods
