### ISSUE TITLE
Infinite loop and crash in self-associations

### ISSUE THREAD

**Issue by inliquid** [go-gorm/gorm#4108]
## GORM Playground Link

This is not possible to represent via gorm playground.

## Description

Imagine I want to add a friends of user via self assiciation:
```go
type User struct {
	ID      uint
	Name    string
	Friends []*User `gorm:"many2many:friends;association_jointable_foreignkey:friend_id"`
}
```

When I'm adding a `friend` to a `user`, it works. But when I'm trying to add a `user` as a friend of `friend`, so in reverse, this call falls into infinite loop.

EXAMPLE
```go
package main

import (
	"context"
	"flag"
	"time"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var (
	db    *gorm.DB
	newDB = flag.Bool("newDB", false, "Set this flag to create new DB.")
)

func init() {
	flag.Parse()

	var err error
	db, err = gorm.Open(postgres.Open("postgres://gorm:gorm@127.0.0.1/gorm?sslmode=disable"), &gorm.Config{
		Logger:                 logger.Default.LogMode(logger.Info),
		SkipDefaultTransaction: true,
	})
	panicErr(err)

	if *newDB {
		err = db.Migrator().DropTable(
			"friends",
			&User{},
		)
		panicErr(err)
	}

	err = db.Migrator().AutoMigrate(&User{})
	panicErr(err)
}

type User struct {
	ID      uint
	Name    string
	Friends []*User `gorm:"many2many:friends;association_jointable_foreignkey:friend_id"`
}

func main() {
	u := &User{Name: "User"}
	f := &User{Name: "Friend"}

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	// Add users
	err := db.WithContext(ctx).Create(u).Error
	panicErr(err)
	err = db.WithContext(ctx).Create(f).Error
	panicErr(err)

	// Add friends

	// THIS ONE WORKS FINE
	err = db.WithContext(ctx).
		Model(u).
		Association("Friends").
		Append(f)
	panicErr(err)

	// THIS ONE BREAKS INTO INFINITE LOOP
	err = db.WithContext(ctx).
		Model(f).
		Association("Friends").
		Append(u)
	panicErr(err)

}

func panicErr(err error) {
	if err != nil {
		panic(err)
	}
}

```

**Comment by inliquid** [comment]
I would add this to playground but app is crashing and should be stopped forcefully, so it's not possible to just put a code into some test.

**Comment by inliquid** [comment]
WTF

**Comment by inliquid** [comment]
@jinzhu this is very serious problem, please reopen. 

And, personally, I don't think that forcefully closing absolutely all bugs (when "bug" was selected by reporter!!!) in 2 days when people don't have enough time, efforts or skills to do all this fancy magic passes is misleading, and will make quality of library much less than it could be. This is disrespectful to reporters.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.

---
Sorry, rarely check those "type:missing reproduction steps" issues due to limited time, most of those kind issues usually are misusage, so the GitHub action really helped me to focus on high ROI issues.
