### ISSUE TITLE
AutoMigrate should add unique constraint 

### ISSUE THREAD

**Issue by gnuletik** [go-gorm/gorm#4110]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/285

## Description

When a user wants to add a unique constraint on a column, the unique constraint is not added by `AutoMigrate()`.
When creating a new table, the constraint is added.
When adding a unique index on an existing column, the migration is applied.

The `MigrateColumn` function do not seems to handle unique fields : https://github.com/go-gorm/gorm/blob/2ba612e80591c26ef512af629d2e1532fc48b5b9/migrator/migrator.go#L363-L404

Thanks !

**Comment by jinzhu** [comment]
auto migration will only migrate missing indexes, but not constraint currently.

**Comment by jinzhu** [comment]
Added its support in v1.23.1, thank you for your support.

**Comment by progmatic-99** [comment]
I first added the `unique` constraint on the column and migrated it, but then I removed the `unique` constraint. But the table doesn't reflect this change.
Any ideas??

**Comment by hinupurthakur** [comment]
@progmatic-99 Were you able to find an elegant way to do so?

> I first added the `unique` constraint on the column and migrated it, but then I removed the `unique` constraint. But the table doesn't reflect this change. Any ideas??

**Comment by Temptingashby** [comment]
https://scuffleles.github.io/BgaRwlbJ6DHGIh3BbEj7hkskLq4id4GaipJyyVItAnrr/



i identified the answer
