### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sneko** [go-gorm/gorm#4114]
## GORM Playground Link

No success to reproduce locally :( but interested to know if the following explanation speaks to you since it targets only your code @jinzhu (from what I understand).

## Description

In a environment with Golang program and the DB not on the same host (remote ones) I'm having a dereference error.

The context:
* I have a scheduler that triggers multiple DB transactions at once in separate goroutines
* Each goroutine (transaction) will make multiple record creation
* Once per hour, I get the following fatal error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7760e7]

goroutine 71398 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
database/sql.(*Tx).grabConn(0x0, 0x117b940, 0xc000144000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:2045 +0x57
database/sql.(*Tx).ExecContext(0x0, 0x117b940, 0xc000144000, 0xc00045f140, 0x69, 0xc000e94a80, 0x6, 0x8, 0xfbbe40, 0x7f0378dd0b48, ...)
	/usr/local/go/src/database/sql/sql.go:2271 +0x4c
gorm.io/gorm/callbacks.Create.func1(0xc00108f350)
	/go/pkg/mod/gorm.io/gorm@v1.20.6/callbacks/create.go:54 +0x33c
gorm.io/gorm.(*processor).Execute(0xc0004be380, 0xc00108f350)
	/go/pkg/mod/gorm.io/gorm@v1.20.6/callbacks.go:105 +0x224
gorm.io/gorm.(*DB).Create(0xc000f20b10, 0xef1fe0, 0xc000809c00, 0x0)
	/go/pkg/mod/gorm.io/gorm@v1.20.6/finisher_api.go:20 +0xa7
MYREPO/MYCLOSURE.func1(0xc000f20b10, 0x0, 0x0)
	/workspace/service/service.go:137 +0x202
gorm.io/gorm.(*DB).Transaction(0xc00048e4e0, 0xc000cfd240, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/gorm.io/gorm@v1.20.6/finisher_api.go:455 +0x13
```

Note: 99% of the time it works fine. As a workaround for now we set our own locker around the transaction. But it sounds really weird since the error comes from a locker from the sql driver.

Any thought would be appreciated :)

Thank you,

**Comment by jinzhu** [comment]
haven't check the error of `db.Begin()`

**Comment by sneko** [comment]
![image](https://user-images.githubusercontent.com/8195958/108846818-48889700-75df-11eb-8b6e-ffb380bc30f4.png)

@jinzhu according to your message I guess I need to check within my closure function something has been wrong in the hidden process init.

In the Gorm documentation I see no clear example this should be handled:
![image](https://user-images.githubusercontent.com/8195958/108846987-78d03580-75df-11eb-9e45-10c1cf58b4b5.png)

Did I miss a link targetting this needed check?

I guess I should do something like:
```
	err := s.db.GetORM().Transaction(func(tx *gorm.DB) error {
		if tx.Error != nil {
			return tx.Error
		}

		tx.Create(...)

		return nil
	})
```

**Comment by jinzhu** [comment]
The latest GORM has the error check.
