### ISSUE TITLE
How to make Migrator().HasTable() search table under a specific postgres schema ?

### ISSUE THREAD

**Issue by hwang63130** [go-gorm/gorm#4116]
## Your Question

My understanding is that by defining a struct's .TableName() method, gorm will create a sql table under a specific postgres schema. However, is there a way to make Migrator().HasTable() method look for the table under a specific schema as well?

## The document you expected this should be explained
```
type item struct {
	Name string
}

func (i *item)TableName() string {return "test.item"}	// specify schema name as "test"

func main(){
	dsn := "<POSTGRES DSN>" 
	db, _ := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	i := &item{"item_name"}
	fmt.Printf("before migration - table %s exists: %v", i.TableName(), db.Migrator().HasTable(i))	
	_ = db.AutoMigrate(i)
	fmt.Printf("after migration - table %s exists: %v", i.TableName(), db.Migrator().HasTable(i))
}
```

## The current running result
```
before migration - table test.item exists: false
after migration - table test.item exists: false
```

## The test environment
Go v1.5.8, gorm v1.20.12, PostgreSQL v12.5, Windows 10 Pro X64

## Expected answer
Is there a way to make Migrator().HasTable() search for the table under a specific schema name?

**Comment by jinzhu** [comment]
works for me with latest version.
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/6843/109285831-81816f80-785c-11eb-95e6-7421b7314c54.png">

**Comment by jinzhu** [comment]
maybe upgrade the postgres driver.
