### ISSUE TITLE
Model and clauses being passed even after newDB in transaction

### ISSUE THREAD

**Issue by abelseniorly** [go-gorm/gorm#4120]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/287

## Description

Continuation of https://github.com/go-gorm/gorm/issues/4117 ... I have updated the test to check again... Even though there is a `db.Session(&gorm.Session{NewDB:true}).Begin()` the model and where conditions are passed to transactions...

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
