### ISSUE TITLE
db.Callback().Raw().Before doesn't work

### ISSUE THREAD

**Issue by lihang212010** [go-gorm/gorm#4121]
Hello, when I use the Gorm to before, after method
		if err := idb.Callback().Create().Before("gorm:create").Register("trace:before", before); err != nil {
			return errors.Wrap(err, "grom create callback register tracer:before error")
		}
		if err := idb.Callback().Create().After("gorm:create").Register("trace:after", after); err != nil {
			return errors.Wrap(err, "grom create callback register tracer:after error")
		}
		if err := idb.Callback().Query().Before("gorm:query").Register("trace:before", before); err != nil {
			return errors.Wrap(err, "grom query callback register tracer:before error")
		}
		if err := idb.Callback().Query().After("gorm:query").Register("trace:after", after); err != nil {
			return errors.Wrap(err, "grom query callback register tracer:after error")
		}
		if err := idb.Callback().Delete().Before("gorm:delete").Register("trace:before", before); err != nil {
			return errors.Wrap(err, "grom delete callback register tracer:before error")
		}
		if err := idb.Callback().Delete().After("gorm:delete").Register("trace:after", after); err != nil {
			return errors.Wrap(err, "grom delete callback register tracer:after error")
		}
		if err := idb.Callback().Update().Before("gorm:update").Register("trace:before", before); err != nil {
			return errors.Wrap(err, "grom update callback register tracer:before error")
		}
		if err := idb.Callback().Update().After("gorm:update").Register("trace:after", after); err != nil {
			return errors.Wrap(err, "grom update callback register tracer:after error")
		}
These are valid, but if raw is used in a similar way, it will not enter the before and after methods, such as：
		if err := idb.Callback().Raw().Before("gorm:raw").Register("trace:before", before); err != nil {
			return errors.Wrap(err, "grom raw callback register tracer:before error")
		}
		if err := idb.Callback().Raw().After("gorm:raw").Register("trace:after", after); err != nil {
			return errors.Wrap(err, "grom raw callback register tracer:after error")
		}
	if err := r.db.Raw(" select * from users").Error; err != nil {
		return nil, errors.Wrapf(err, "find foo by ID error[id=%d]", ID)
	}
What is the reason？

https://github.com/lihang212010/gorm-jager

**Comment by reppard** [comment]
i am noticing the same behavior as @lihang212010

**Comment by reppard** [comment]
could we possible re-open this issue?
