### ISSUE TITLE
Omits and Selects not cleared on New Session

### ISSUE THREAD

**Issue by abelseniorly** [go-gorm/gorm#4125]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/289

## Description

Omits, Selects, Joins,  Models, Tables, etc should be cleared when someone is creating a new session with `DB.Session(&Session{NewDB: true})` . A the main use case of this function, is to get an entirely empty DB struct, with just the connection info... Having to take care of this is not a good approach.

**Comment by jinzhu** [comment]
Hi, Need to preload the Account

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/6843/109956456-a2473a80-7d1e-11eb-98bb-dd59b224b862.png">
