### ISSUE TITLE
POSTGRES How to check if error type is DUPLICATE KEY

### ISSUE THREAD

**Issue by khanakia** [go-gorm/gorm#4135]
@jinzhu 

OLD Ticket: https://github.com/go-gorm/gorm/issues/4037

I did not find any solution for postgres yet. I searched everywhere but still there is no way i found to check the duplicate key for postgres. @jinzhu Can you provide the PSQL example like you did for the Mysql in old ticket. Thanks

## Your Question

I have **unique index key** and when i try to insert duplicate record i get this error `ERROR: duplicate key value violates unique constraint "idx_itemid_partid" (SQLSTATE 23505)` but i want to show different message to the frontend based on ERROR TYPE but in gorm i do not see any Duplicate error type please check screenshot. How do i use the validation for duplicate error type
```
  if err != nil && errors.Is(err, gorm.ErrDuplicateKey) { // how do i do this ?
    fmt.Println("Duplicate key found.")
  }
```

<img width="787" alt="Screenshot 2021-02-01 at 4 20 21 PM" src="https://user-images.githubusercontent.com/2174170/106448898-631c9400-64a9-11eb-84ee-4de2790f6893.png">

## The document you expected this should be explained
N/A

## Expected answer

Should have error type duplicate

**Comment by spiside** [comment]
This [stackoverflow answer](https://stackoverflow.com/a/37560627) should provide some details on how errors are commonly caught using Postgres error codes. For your problem specifically, I think you can do the following:

```go
const (
    UniqueViolationErr = pq.ErrorCode("23505")
)

if err != nil && errors.Is(err, UniqueViolationErr) {
    fmt.Println("Duplicate key found.")
}
```

Here's [a list of all the SQLSTATE](https://www.postgresql.org/docs/current/errcodes-appendix.html) error codes that are used in Postgres. You'll see that `23505` is unique violation error.

**Comment by khanakia** [comment]
@spiside 
Your code is not working and giving error please check. 
FYI: I tried creating some custom errors already in the past with Error Interface those also did not work.

So can you please give some solid solution to these issue. Thanks

<img width="920" alt="Screenshot 2021-03-04 at 5 49 10 PM" src="https://user-images.githubusercontent.com/2174170/109963159-17604300-7d12-11eb-84fd-5a0709f150b9.png">

**Comment by spiside** [comment]
I was hoping `Is()` might do the heavy lifting here but this is how I've defined a function that checks postgres error codes:

```
const (
    UniqueViolationErr = pq.ErrorCode("23505")
)

func IsErrorCode(err error, errcode pq.ErrorCode) bool {
        if pgerr, ok := err.(*pq.Error); ok {
                return pgerr.Code == errcode
        }
        return false
}

if err != nil && IsErrorCode(err, UniqueViolationErr) {
    fmt.Println("Duplicate key found.")
}
```

`IsErrorCode()` casts the error to a `pq.Error`, and if it is, it will check the error code to see if it matches.

**Comment by khanakia** [comment]
@spiside 

Still returning false 
```
err = db.Save(&item).Error
fmt.Println(IsErrorCode(err, UniqueViolationErr)) // false
```


1. Also i tried the stackoverflow example and assertion is always false
```
err := db.Save(&item).Error
err, ok := err.(*pq.Error)
fmt.Println(ok) // false
```

2. Tried with Custom Error Interface
```
type PsqlError struct {
	Message string
}

func (me *PsqlError) Error() string {
	return "Some Error"
}

err = db.Save(&item).Error
var perr PsqlError
fmt.Println(errors.Is(err, &perr)) // false
```

**Comment by spiside** [comment]
That's odd, because the `pq.Error` struct defined here: https://pkg.go.dev/github.com/lib/pq#Error is the same as that struct. What do you get for: 

```go
var pqErr *pq.Error
if ok := errors.As(err, pqErr); ok && err.Code == UniqueViolationErr {
   fmt.Println("Worked!")
}
```

**Comment by khanakia** [comment]
@spiside 

It gives the error
<img width="825" alt="Screenshot 2021-03-04 at 6 30 25 PM" src="https://user-images.githubusercontent.com/2174170/109967659-b20f5080-7d17-11eb-8166-a24f8d986d08.png">

But anyway i figured it out i used the fmt.Println(reflect.TypeOf(err)) and it returns `*pgconn.PgError` it seems goorm uses pgconn package to connect to the Postgres

Then i used below code and it worked 💯 
```
var perr *pgconn.PgError
errors.As(err, &perr)
fmt.Println(perr.Code) // 23505
```

**Comment by khanakia** [comment]
@spiside 

I am using `gorm Datatypes` package and i just verified it's using the pgconn package 

<img width="919" alt="Screenshot 2021-03-04 at 6 35 44 PM" src="https://user-images.githubusercontent.com/2174170/109968279-804ab980-7d18-11eb-925e-11330ccf8f43.png">

**Comment by khanakia** [comment]
@spiside Thank for your great support along the way. I really appreciate it by heart. 👍

**Comment by akishek22** [comment]
Hey all, would it make more sense if gorm returned unique key violations as a standard gorm error?

**Comment by khanakia** [comment]
@akishek22 What do you mean by that ?

**Comment by akishek22** [comment]
@khanakia referencing your image below. For example, I want to keep my gorm db implementation separated from Postgres (flexibility to change DBs). However, when handling unique key errors, it's impossible to know it's a unique key error without knowing it's a Postgres unique key error. 

I was thinking of a general "gorm.ErrUniqueKeyViolation" like you referenced in your question. If it's not a good idea, just curious why not. 
![image](https://user-images.githubusercontent.com/1691252/114257670-896e1c80-998f-11eb-965d-7fe51fbe40e3.png)

**Comment by khanakia** [comment]
@akishek22 those errors are out of scope from the gorm packages as those errors are returned by native drivers itself such as mysql, pq etc.

**Comment by udaraliyanage** [comment]
This worked for me

`var duplicateEntryError = &pgconn.PgError{Code: "23505"}
		if errors.As(err, &duplicateEntryError) {
			return ItemAlreadyExistError
		}
`

**Comment by VerasThiago** [comment]
Here is how I use

```Go
func IsNotFoundError(err error) bool {
	return err == gorm.ErrRecordNotFound
}

func IsDuplicatedKeyError(err error) bool {
	var perr *pgconn.PgError
	if errors.As(err, &perr) {
		return perr.Code == DUPLICATED_KEY
	}
	return false
}

func HandleDuplicateError(err error) error {
	if err == nil {
		return err
	}

	if IsDuplicatedKeyError(err) {
		return GenericError{
			Code:    STATUS_BAD_REQUEST,
			Err:     err,
			Message: "Data already used",
		}
	}

	return err
}

func HandleDataNotFoundError(err error, dataName string) error {
	if err == nil {
		return err
	}

	if IsNotFoundError(err) {
		return GenericError{
			Code:    STATUS_NOT_FOUND,
			Err:     err,
			Message: fmt.Sprintf("%+v not found", dataName),
		}
	}

	return err
}
```

Example of usage:

```Go
func (p *PostgresRepository) DeleteUser(userID string) error {
	err := p.db.Where("id = ?", userID).Delete(&models.User{}).Error
	return errors.HandleDataNotFoundError(err, USER_DATA_NAME)
}

func (p *PostgresRepository) CreateUser(user *models.User) error {
	err := p.db.Create(user).Error
	return errors.HandleDuplicateError(err)
}
```

**Comment by shahzodsharifov** [comment]
I checked the error codes with pq library

err :=db.Create(&user).Error

if err !=nil {

if err.(*pq.Error).Code == "23505" {
fmt.Println("Username already exists")

}

}

**Comment by azmiadhani** [comment]
I can't assert the gorm error to`*pgconn.PgError`. `errors.As(err, &pgErr)` keep returning false. I wonder if anybody can help me with this one. Here is my code:
![image](https://user-images.githubusercontent.com/13920914/213910902-a1887697-97a2-4752-8db6-3aa78d80e7bc.png)
I'm using:
1. golang 1.19.
2. gorm.io/gorm v1.24.33. 
3. github.com/jackc/pgconn v1.13.0

**Comment by azmiadhani** [comment]
I've solved my previous problem. I get this to work by installing [`github.com/jackc/pgx`](https://github.com/jackc/pgx) instead of [`github.com/jackc/pgconn`](https://github.com/jackc/pgconn). I'm now using `*pgconn.PgError` from `github.com/jackc/pgx/v5/pgconn` import. See the image below. Hope it helps for anyone that got the same problem with mine.
![image](https://user-images.githubusercontent.com/13920914/213911340-757a9ffc-5a96-4860-8e8c-0cfe073802a4.png)

**Comment by d2jvkpn** [comment]
This problem occurs with 'gorm.io/driver/postgres v1.5.0' (gorm.io/gorm v1.25.1). To make the type assertion work as expected, downgrade the version of gorm.io/driver/postgres to 1.4.5.

**Comment by hijklmno** [comment]
> This problem occurs with 'gorm.io/driver/postgres v1.5.0' (gorm.io/gorm v1.25.1). To make the type assertion work as expected, downgrade the version of gorm.io/driver/postgres to 1.4.5.

this also happens with gorm.io/driver/postgres v1.4.8. i ran the following which fixed our unit tests that checks against postgres code:
`go get gorm.io/driver/postgres@v1.4.5`

**Comment by rhzs** [comment]
Since the error code is only representing unique violation. Checking code alone is not sufficient to determine the primary key violation. You need to check the error message for PRIMARY key violation error.

**Comment by ennnnzo** [comment]
> I've solved my previous problem. I get this to work by installing [`github.com/jackc/pgx`](https://github.com/jackc/pgx) instead of [`github.com/jackc/pgconn`](https://github.com/jackc/pgconn). I'm now using `*pgconn.PgError` from `github.com/jackc/pgx/v5/pgconn` import. See the image below. Hope it helps for anyone that got the same problem with mine. ![image](https://user-images.githubusercontent.com/13920914/213911340-757a9ffc-5a96-4860-8e8c-0cfe073802a4.png)

Thanks so much for your comment!! 
It helped me a lot !!

**Comment by AuroraTea** [comment]
For who come after:

```go
var pgErr *pgconn.PgError
if errors.As(err, &pgErr) {
	if pgErr.Code == "23505" {

	}
}
```

Or convenient but couldn't know which unique constraint it is. 👇

```go
DB, err = gorm.Open(
	postgres.Open(""),
	&gorm.Config{
		TranslateError: true,
	},
)

if errors.Is(err, gorm.ErrDuplicatedKey) {
	
}
```
