### ISSUE TITLE
AutoMigrate TableName Error 

### ISSUE THREAD

**Issue by zhtlvzwj** [go-gorm/gorm#4145]
I Want AutoMigrate Table ,The code is as follows：

`
  
    type Arcv struct {
	  ID     uint   `gorm:"primarykey"`
	  Code   string `json:"code" form:"code" gorm:"column:code;comment:;type:varchar(255);size:255;"`
	  Status int    `json:"status" form:"status" gorm:"column:status;comment:;type:int;size:10;"`
	  Suffix string `json:"suffix" form:"suffix" gorm:"-"`
    }

    func (a *Arcv) TableName() string {
	    if a.Suffix != "" {
	      return "arcv_" + a.Suffix
	    }
	    return "arcv"
    }
    
    arcv :=&Arcv{
		  Suffix: "test",
	  }

     db.AutoMigrate(arcv)
 
`
Expect auto create table "arcv_test" ,but found "arcv"

After tracking and debugging，I found 

https://github.com/go-gorm/gorm/blob/a948c846071f7e4fd264c6a95a81a0ef04293a28/schema/schema.go#L100

line 100 has a error

We can fix this with new code

`	if tabler, ok := dest.(Tabler); ok {
		tableName = tabler.TableName()
	}`

**Comment by labulaka521** [comment]
it's like you want use dynamic table name, but `TableName` do not support dynamic table name, maybe it can help you https://gorm.io/zh_CN/docs/conventions.html#TableName

**Comment by 00LT00** [comment]
@labulaka521 @jinzhu Hi. Maybe it was a bug.
```go
func main(){
        db := initDB()
	db = db.Scopes(UserTable())
	_ = db.AutoMigrate(&User{})
}

func UserTable() func (tx *gorm.DB) *gorm.DB {
	return func (tx *gorm.DB) *gorm.DB {
		return tx.Table("test")
	}
}
```
The result is that create a new table with "test" as tablename at least version 1.20.8.
But now, the result is "users"
![image](https://user-images.githubusercontent.com/47566260/110639896-33b91f80-81eb-11eb-993c-37b310c4fd66.png)

**Comment by jinzhu** [comment]
Hi @00LT00 

Sorry for the issue, fixed

**Comment by zhtlvzwj** [comment]
Thanks

**Comment by hsluoyz** [comment]
@jinzhu hi, can you make a new release for it?
