### ISSUE TITLE
dynamic table name for many2many relationship 

### ISSUE THREAD

**Issue by id1385** [go-gorm/gorm#4146]
hello
I'm creating an multi tenant app
my database is postgres and i use postgres database schema per app 
i use dynamic table of gorm ability to set table names like : 

> func UserTable() func(tx *gorm.DB) *gorm.DB {
	return func(tx *gorm.DB) *gorm.DB {
		dbSchema := tx.Statement.Context.Value("x-schema").(string)
		return tx.Table(dbSchema + ".users")
	}
}

i have **users** and **rules** and **users_rules** as pivot table
i define user has many rules and set pivot table name but it will get error 
_pq: column users_rules.id does not exist_
Because table name of users_rule dont set auto its static 

> type User struct {
	UserId    uint       `gorm:"primaryKey" json:"user_id"`
	Username  *string    `json:"username"`
	Password  string     `json:"-"`
	Mobile    string     `json:"mobile"`
	Rules []Rules `gorm:"many2many:users_rules"`
}

**so my question is how to set dynamic many2many Pivot Table Name (users_rules) ?**

**Comment by id1385** [comment]
I asked this question in more detail [here](https://stackoverflow.com/questions/66507405/how-to-set-dynamic-table-name-for-many2many-relationship-in-gorm)
Of course, no one has answered yet
I hope someone can help me...😢

**Comment by jinzhu** [comment]
Don't support this, but you can use double has many

**Comment by id1385** [comment]
what is `double has many` ?
