### ISSUE TITLE
Why does the Option interface need to be bound to the AfterInitialize method setting? 

### ISSUE THREAD

**Issue by daheige** [go-gorm/gorm#4148]
https://github.com/go-gorm/gorm/blob/a948c846071f7e4fd264c6a95a81a0ef04293a28/gorm.go#L79

I read about the option settings here. If the user only needs to change some options of Config, does he also need to implement the AfterInitialize method? I am more confused about this? If I only want to change the configuration of Config, does the AfterInitialize method only need to return nil? 
Maybe you can do better？

**Comment by jinzhu** [comment]
yes, needs to implement both the `Apply` and `AfterInitialize` methods, I think this should be fine as the config option usually implements once and share everywhere.

**Comment by daheige** [comment]
@jinzhu Maybe as you said, there is no problem at the moment, but I prefer Option interface to only do one thing and do it well.
