### ISSUE TITLE
update_at time is not consistent

### ISSUE THREAD

**Issue by AWaterColorPen** [go-gorm/gorm#4155]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/288

## Description

For example: 
when we call updates method, user.update_at is "2021-02-26 20:47:16.823720459Z" .
But the UPDATE sql uses "update_at"="2021-02-26 20:47:16.824Z",  and SELECT sql uses "update_at"="2021-02-26 20:47:16.823Z"

update_at is not consistent.

I think update_at should be consistent. And it should be no error for this case

**Comment by jinzhu** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/6843/110624844-b46f2000-81d9-11eb-9b73-6359eddbc0cc.png">

Should use `&user` to Update

**Comment by AWaterColorPen** [comment]
@jinzhu  hope reopen this issue.
Updated code.  and

**Comment by jinzhu** [comment]
because mysql's time's precision issue, you can change gorm.Config's NowFunc to `func() time.Time { return time.Now().Local().Round(time.Millisecond) }`

**Comment by AWaterColorPen** [comment]
Thanks for the solution.
BTW, is it possible to fix the mysql's time's precision issue at `gorm.io/driver/sqlite` by default? or set `func() time.Time { return time.Now().Local().Round(time.Millisecond) }` to `gorm.Config.NowFunc` by default when `dbType` is `mysql`?

**Comment by jinzhu** [comment]
Processed it by default, needs to use the latest GORM master and mysql v1.0.5
