### ISSUE TITLE
v2 版本 need to define a valid foreign key for relations or it need to implement the Valuer/Sc anner interface

### ISSUE THREAD

**Issue by 851091009** [go-gorm/gorm#4160]
`
type MenuInListStruct struct {
	Id                int64  `json:"id"`
	Title             string `json:"title" remark:"菜单名称"`
	MenuType          int    `json:"menu_type" remark:"菜单类型：分为模块、菜单、操作，默认是菜单"`
	MenuOperatingType int    `json:"menu_operating_type" remark:"操作类型"`
	Api               string `json:"api" remark:"连接地址"`
	Path              string `json:"path" remark:"连接地址"`
	Sort              int64  `json:"sort" remark:"连接地址"`
	ParentId          int64  `json:"parent_id" remark:"上级菜单"`
	Icon              string `json:"icon" remark:"icon图标"`
}

type MenuInListTreeStruct struct {
	MenuInListStruct
	Children []*MenuInListTreeStruct
}

// types 是判断是否取出菜单
func MenuInList(ids string, types bool) ([]*MenuInListTreeStruct, error) {
	var Lists []*MenuInListTreeStruct

	model := Orm.PGDB.Table(MenuTable).Select("id,title,api,path,menu_type,menu_operating_type,parent_id,sort").Where("id in (" + ids + ")").Where("status = 1")

	if types == true {
		model = model.Where("menu_type = 2")
	}

	err := model.Order("id desc").Find(&Lists).Error
	if err != nil {
		return nil, err
	}
	return Lists, err
}
`
我指定了 要取出的字段，现在报 下面的错误！
invalid field found for struct models.MenuInListTreeStruct's field Children, need to define a valid foreign key for relations or it need to implement the Valuer/Scanner interface
请解答一下，非常感谢！！！！！

**Comment by birdycn** [comment]
你好，怎么解决的
