### ISSUE TITLE
Ignored property in model leads to bug when creating record in v1.21.x

### ISSUE THREAD

**Issue by ruozhixian** [go-gorm/gorm#4161]
## Description
https://github.com/go-gorm/playground/pull/303

### model without ignored property
```
type Person struct {
	ID             int `gorm:"primaryKey"`
	SourcePersonID *int
	Friends        []Person `gorm:"foreignKey:SourcePersonID;references:ID"`
	//AnotherPro    interface{} `gorm:"-"`
}

func main() {
	//dbConn := GetDB()
	dbConn.Migrator().CreateTable(&Person{})
	tom := Person{
		ID: 1,
		Friends: []Person{
			{
				ID: 2,
				Friends: []Person{
					{
						ID: 3,
						Friends: []Person{
							{
								ID: 4,
							},
						},
					},
				},
			},
		},
	}
	dbConn.Create(&tom)
}
```
![image](https://user-images.githubusercontent.com/25141494/110430227-02efc200-80e7-11eb-9d25-ab01df8f7856.png)

"tom" is created in mysql correctly.

### model with ignored property
However, if there is an ingored property in model, model's deeper nested properties are abondan.
gorm v1.20.x doesn't have this problem.

```
type Person struct {
	ID             int `gorm:"primaryKey"`
	SourcePersonID *int
	Friends        []Person `gorm:"foreignKey:SourcePersonID;references:ID"`
	AnotherPro    interface{} `gorm:"-"`
}
```
![image](https://user-images.githubusercontent.com/25141494/110431920-64189500-80e9-11eb-82c8-ce0a5e6cac0f.png)

### what's more
How to preload all nested children?
#4027  with `"Whatever." + clause.Associations`， or more `"Whatever.Whatever.Whatever." + clause.Associations`, can preload deeper level nested children, but it's still limited.

**Comment by ruozhixian** [comment]
It seems like that the commit (https://github.com/go-gorm/gorm/commit/940da051a756e425d7069a51eec412835cb6bbb1) leads to this problem.

**Comment by jinzhu** [comment]
Hi @ruozhixian 

I don't get your issue, can you create a reproducible PR?

**Comment by ruozhixian** [comment]
> Hi @ruozhixian
> 
> I don't get your issue, can you create a reproducible PR?

hi, @jinzhu 
the playground has been added here https://github.com/go-gorm/playground/pull/303
