### ISSUE TITLE
Foreign key constraint not created when foreignKey field exists in target table as well.

### ISSUE THREAD

**Issue by alext** [go-gorm/gorm#4164]
## Description

I've found that gorm silently fails to create a foreign key constraint when using the `foreignKey` struct tag, and a field with that name exists in both the source and target tables, even though the field in the target table should be irrelevant to this relationship.

## Reproducer:

```go
package main

import (
	"log"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type Foo struct {
	ID int `gorm:"primaryKey"`

        // The foreign key constraint is created if this is commented out.
	OtherId *int
}

type Bar struct {
	ID      int `gorm:"primaryKey"`
	OtherId *int

	Foo *Foo `gorm:"foreignKey:OtherId"`
}

func main() {
	db, err := gorm.Open(postgres.Open("postgres:///test"), &gorm.Config{})
	if err != nil {
		log.Fatal(err)
	}

	err = db.Migrator().AutoMigrate(&Foo{})
	if err != nil {
		log.Fatal(err)
	}

	err = db.Migrator().AutoMigrate(&Bar{})
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Migrated")
}
```
Playground link: https://github.com/go-gorm/playground/pull/299

Result:
```
$ psql test -c '\d bars'
                             Table "public.bars"
  Column  |  Type  | Collation | Nullable |             Default              
----------+--------+-----------+----------+----------------------------------
 id       | bigint |           | not null | nextval('bars_id_seq'::regclass)
 other_id | bigint |           |          | 
Indexes:
    "bars_pkey" PRIMARY KEY, btree (id)
```

Expected output:

```
$ psql test -c '\d bars'
                             Table "public.bars"
  Column  |  Type  | Collation | Nullable |             Default              
----------+--------+-----------+----------+----------------------------------
 id       | bigint |           | not null | nextval('bars_id_seq'::regclass)
 other_id | bigint |           |          | 
Indexes:
    "bars_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "fk_bars_foo" FOREIGN KEY (other_id) REFERENCES foos(id)
```

If the `Foo.OtherId` field is commented out, the foreign key constraint gets created as expected.

**Comment by alext** [comment]
Playground PR added now.

**Comment by jinzhu** [comment]
It thoughts `Foo .OtherId` as the foreign key, so it will creates a references for table `foos`.

**Comment by alext** [comment]
I don't follow.  `Bar.OtherId` is the foreign key - it's referencing the ID column on Foo.  `Foo.OtherID` should not be considered in this situation at all.  (I'm not using a `references` clause in the association tag).

**Comment by jinzhu** [comment]
there are some misunderstanding here, the `foreignKey` tag doesn't means the the field belongs to current struct. GORM will use the specified field to guess relationships between the two struct (first guess belongs to, then has one/many).

So it is easier for developers to use for most cases (only need to use foreignKey, no bothered to think when to use the references tag), but I am afraid currently GORM can't works in your cases (having two fields with same name in those two structs).

Let me think how to resolve your issue, maybe `foreignKey:@OtherId` means the field belongs to current struct? any suggestions?

**Comment by alext** [comment]
Hmmm...  In this case, it is intended to be a belongs_to relationship, so given that belongs to is the first guess, I'd expect it to pick up Bar.OtherId as the foreign key pointing at Foo.

In actual fact, with this example, no foreign key constraints are created for either table.

I'm a little confused by the intended behaviour here - from the docs (https://gorm.io/docs/associations.html#tags):

> foreignKey	Specifies column name of the current model that is used as a foreign key to the join table

This suggests that `foreignKey` will always be specifying the column on the model containing the relationship...

Another example where this causes problems is when using a form of joined-table inheritance.  eg:

```go
type Foo struct {
	ID int `gorm:"primaryKey"`
}

type SpecificFoo struct {
        ID int `gorm:"primaryKey"`

        Foo Foo `gorm:"foreignKey:ID"`
}
```

We have another example in our codebase that has this issue, and again, no foreign key constrain is created by AutoMigrate.



Thinking about solutions if this is the intended behaviour: I wonder whether adding a field tag to explicitly specify the type of relationship would be a good idea. This would allow overriding the defaults in the case where gorm doesn't guess the relationship type correctly.

**Comment by jinzhu** [comment]
> In actual fact, with this example, no foreign key constraints are created for either table.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/6843/110633167-66f7b080-81e3-11eb-996d-8c60b22ea37f.png">

GORM suggest to follow the default naming conventions, which works best, or you could following those examples to define your structs. https://github.com/go-gorm/gorm/blob/master/utils/tests/models.go  https://github.com/go-gorm/gorm/blob/master/schema/relationship_test.go

> Thinking about solutions if this is the intended behaviour: I wonder whether adding a field tag to explicitly specify the type of relationship would be a good idea. 

Sounds good to me.

**Comment by jilleJr** [comment]
I experienced this issue now as well.

We have a convention to always use the table name in the primary key name, so the foreign key name and referenced column names always match up. But this behaviour of GORM hinders us from this.

If I understand this thread correctly, then it works like this

```go
type Foo struct {
    FooID uint `gorm:"primaryKey"`
}

type Moo struct {
    ID uint `gorm:"primaryKey"`
}

type Bar struct {
    BarID uint  `gorm:"primaryKey"`
    FooID *uint `gorm:"nullable;default:NULL"`
    Foo   Foo   `gorm:"foreignKey:FooID"` // here FooID refers to Foo.FooID
    MooID *uint `gorm:"nullable;default:NULL"`
    Moo   Moo   `gorm:"foreignKey:MooID"` // here MooID refers to Bar.MooID
}
```

So, if the referenced type has that key name, then GORM sets up an association from that key, while if it doesn't then the `foreignKey` tag looks inside the defining struct.

In my opinion it should not be an "if" statement in that tag's logic. It should only do one or the other things, and if it fails then error out instead of trying to "understand what the author maybe intended", leading to hard to track down bugs
