### ISSUE TITLE
LastInsertId for Sqlite returns int for the DEFAULT custom_function

### ISSUE THREAD

**Issue by majest** [go-gorm/gorm#4169]
I have created a model that uses cockroach as a database. ID uses uuid:

```
type Product struct {
	ID uuid.UUID  `gorm:"type:uuid;primaryKey;default:(gen_random_uuid())"`
	Test string
}
```

Registering custom function:

```
const CustomDriverName = "sqlite3_extended"
	const File = "./test.db"
	sql.Register(CustomDriverName,
		&sqliteGo.SQLiteDriver{
			ConnectHook: func(conn *sqliteGo.SQLiteConn) error {
				err := conn.RegisterFunc(
					"gen_random_uuid",
					func(arguments ...interface{}) (string, error) {
						return uuid.NewV4().String(), nil // Return a string value.
					},
					true,
				)
				return err
			},
		},
	)

	conn, err := sql.Open(CustomDriverName, File)
	if err != nil {
		panic(err)
	}

	db, err := gorm.Open(sqlite.Dialector{
		DriverName: CustomDriverName,
		DSN:        File,
		Conn: conn,
	}, &gorm.Config{
		Logger: logger.Default.LogMode(logger.Info),
		SkipDefaultTransaction: true,
		DisableNestedTransaction: true,
	})
```

Unfortunately, the output Id value from the create on the product is "00000000-0000-0000-0000-000000000000" even though it is CORRECTLY saved in the database.

`[{4c1e38e8-b700-46a6-9505-14d8ca913f9c test}] `

This is probably linked to how last inserted id is returned from the sqlite so might not be a Gorm problem but perhaps a workaround would be possible?

I tracked that lastInsertId here https://github.com/go-gorm/gorm/blob/master/callbacks/create.go#L86 is an integer on autoincrement

Full example here:

https://gist.github.com/majest/45de01524eb53477c517b43fc6f110ab

**Comment by jinzhu** [comment]
sqlite doesn't return the uuid back to GORM, so this won't works.

You need to assign the uuid in `BeforeCreate` hooks.
