### ISSUE TITLE
Ability to insert SQL comment at the end of all statements

### ISSUE THREAD

**Issue by pborzenkov** [go-gorm/gorm#4178]
First of all, thanks for such great project! Works really well. Also, sorry if this is already implemented and I just missed it while reading docs/code.

## Describe the feature

I'd like to propose a feature that will allow to add SQL comments at the end of all executed SQL statements. I looked through `gorm.io/hints` and it looks like each comment is tied to a particular SQL statement. What I'd like is to be able to add a comment at the end of every SQL statement regardless of its contents.

I'm not super familiar with the code, but I assume this can be quite easily achieved by passing additional "COMMENT" clause to every `Build()` call. Or, if hardcoding is not desired, allow users to specify additional clauses that need to be taken into account while building a final statement.

## Motivation

Google CloudSQL allows to pass tracing information with every SQL statement. Such information gets processed by their servers and added to traces/insights, etc. See: https://cloud.google.com/sql/docs/postgres/using-insights

Such information may include various tags as well as OpenTracing trace/span IDs. If the former are passed, Google's Cloud Trace viewer ties both application and DB traces into a single waterflow trace which makes analysing performance/latency issues much much easier.

**Comment by jinzhu** [comment]
Does it match your requirements? https://gorm.io/docs/hints

**Comment by pborzenkov** [comment]
> Does it match your requirements? https://gorm.io/docs/hints

Not really, as `hints.Comment()` needs a particular SQL statement it's gonna be attached to (either before or after). What I'd like to have is an ability to attach comments to any SQL expression no matter what its contents is.

One way I can currently implement it is to wrap `gorm.Config.ConnPool` with a wrapper that attaches required comments before passing the call down to real conn pool. Though, I'm afraid, this might break some of the functionality. For example, `gorm.DB.DB()` won't work anymore.

**Comment by jinzhu** [comment]
overwrite the db.ConnPool, refer `prepare_stmt.go`

**Comment by jinzhu** [comment]
>  For example, gorm.DB.DB() won't work anymore.

https://github.com/go-gorm/gorm/commit/a9fe025ef53b419ea5d6406f5f79a2bc7e52d71a

**Comment by pborzenkov** [comment]
Thanks!
