### ISSUE TITLE
In some cases, Gorm's default snakelike plural name rule doesn't work.

### ISSUE THREAD

**Issue by Liuism** [go-gorm/gorm#4179]
## Your Question

In some cases, Gorm's default snakelike plural name rule doesn't work.

## The document you expected this should be explained

I have defined a structure named `meta`. The table in the database is named `metas`. When using `meta` to query, it is the `meta` 
 table that is operated, resulting in an error: "the data table does not exist.". I didn't modify the default configuration of Gorm. When I used the example of the official website to test, I defined a structure named `product`, which can accurately operate the `products` table.

## Expected answer
Without any configuration, according to the official documents, I think the table name should be the serpentine plural of the structure name. Based on this, the data table operated by the `meta` structure should be `metas` instead of `meta`

**Comment by jinzhu** [comment]
Hello @Liuism 

GORM using https://github.com/jinzhu/inflection/ go generate plural name, maybe you can upgrade & config the inflection to fix the issue.

GORM itself won't change due to the compatibility reason.
