### ISSUE TITLE
db.HasTable doesn't work for models whose TableName() returns two level name like "schema.table"

### ISSUE THREAD

**Issue by aleksaan** [go-gorm/gorm#4184]
## Your Question

db.HasTable doesn't work for models whose TableName() returns two level name like "schema.table"

## The document you expected this should be explained

https://gorm.io/docs/conventions.html#Pluralized-Table-Name

## Expected answer

Is it a bug or a correct behavior?

**Comment by jinzhu** [comment]
should been fixed.

**Comment by aleksaan** [comment]
No fixed. I still get HasTable=False when table is exist
