### ISSUE TITLE
how to extract update/create info from statement

### ISSUE THREAD

**Issue by HuanGong** [go-gorm/gorm#4187]
## Your Question

Our team need record some db modify option（update/create）by install callback by Callback.update/create.after/brefore API, just like this:
```go
db.Callback().Create().After("gorm:after_create").Register(xxx, callbaclFunc)
```
how can we extract the change fields and values from the gorm.DB.statement
- field: after modify values

any example code will be great help, thanks.

**Comment by jinzhu** [comment]
refer the default callbacks/create.go callbacks/update.go code
