### ISSUE TITLE
How to drop gorm-generated join tables

### ISSUE THREAD

**Issue by appcypher** [go-gorm/gorm#4189]
## Your Question
I can drop a normal table like this:

```go
db.Migrator().DropTable(model)
```

But I don't know how to drop join tables associated with a model without specifying it as a string like this:

```go
db.Migrator().DropTable("users_x_workplaces")
```

## The document you expected this should be explained

the site.

## Expected answer

I want to be able to drop join tables associated with a model using the model itself instead of a string.

**Comment by jinzhu** [comment]
use this.
```go
db.Migrator().DropTable("users_x_workplaces")
```

**Comment by appcypher** [comment]
I'm asking it if there is a way to do it without specifying the tablename as a string.
Instead I want to be able to use the model object. Something like this:

```go 
db.Migrator().DropWithJoinTable(&User{})
```

or 

```go 
db.Migrator().DropTable(&User{}).WithJoinTable()
```

or something like that.

I have a use case where I want to demigrate all the tables and join tables generated by Gorm without having the user specifying the auto-generated join tables.
