### ISSUE TITLE
Invalid guess of relation

### ISSUE THREAD

**Issue by marvinwhite** [go-gorm/gorm#4192]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/306

## Description

BelongsTo relation guess is incorrect when explicit `foreignKey` tag used and not the default  field name if embedded struct  used for reference. It guesses `has` instead of  `BelongsTo`,

The sample code shows the working and the not working versions. 

Proposed fix could be something like this which assumes if the table is the same the schema is the same even though if the Struct is different 

[Difference between the two route when foreign key is explicit](https://github.com/go-gorm/gorm/blob/master/schema/relationship.go#L401)

[relationship.go](https://github.com/go-gorm/gorm/blob/master/schema/relationship.go#L357)

```golang
	if gl == guessGuess {
		if field.Schema == relation.FieldSchema || field.Schema.Table == relation.FieldSchema.Table {
			gl = guessBelongs
		} else {
			gl = guessHas
		}
	}
```

**Comment by jinzhu** [comment]
should be fixed by this PR https://github.com/go-gorm/gorm/pull/4801
