### ISSUE TITLE
Belongs to Association Reference not saved

### ISSUE THREAD

**Issue by abelseniorly** [go-gorm/gorm#4195]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/307

## Description

I have set the association struct field permission to read-only, since I dont want it to be created. However I want the association's reference value needs to be saved in the model before it is saved, if the association struct is not nil. This feature was available in gorm v1, even with association_autocreation:false.

**Comment by jinzhu** [comment]
current behaviour seems correct, if you mark the field as readonly, it should not be create-able. 

Maybe you could set the `user.CompanyID = company.ID` before save the user.
