### ISSUE TITLE
AutoMigrate a struct with DEFAULT:0 tag always alert table

### ISSUE THREAD

**Issue by jelech** [go-gorm/gorm#4198]
## Your Question

When I use AutoMigrate a struct with DEFAULT:0 tag, it will always ALTER TABLE when I restart the program.

```go
type TestTable struct {
	ID     uint
        Name string `gorm:"type:varchar(20);NOT NULL;DEFAULT:''"`
	UserID uint `gorm:"type:int;NOT NULL;DEFAULT:0"`
	Status uint `gorm:"type:tinyint;NOT NULL;DEFAULT:0"`
}
```

It will log this
```shell
***/vendor/gorm.io/driver/mysql/migrator.go:83
[140.971ms] [rows:0] ALTER TABLE `test_tables` MODIFY COLUMN `user_id` bigint NOT NULL DEFAULT 0
[174.141ms] [rows:0] ALTER TABLE `test_tables` MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 0
```
But it is in right state when I see the mysql table. And the 'Name' field DEFAULT:'', it wont ALTER table.

Did I use it wrong?

GORM.version: v1.20.5
GORM.driver.mysql.version: v1.0.3
GORM.datatypes.version: v1.0.0
mysql.version: 8.0.14

## The document you expected this should be explained

Not ALTER TABLE when restart program

## Expected answer

Is that a BUG? 

How do I use it?

**Comment by zhchbin** [comment]
We meet the same problem in our production environment, any progress?

**Comment by s-takehana** [comment]
Related to go-gorm/mysql#20.
Already fixed by 5973041.

**Comment by zhchbin** [comment]
@s-takehana 

Thanks for the information.
But now testing with the v1.21.10 version,  if the default value is 1, alert happens every auto migration.

Reproduce infos:
go.mod
```
gorm.io/gorm v1.21.10
```

```golang
package main

import (
	"fmt"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"log"
	"net/url"
)

type TestTable struct {
	ID     uint
	Status   uint   `gorm:"type:tinyint;NOT NULL;DEFAULT:1"`
}

func main() {
	dsn := fmt.Sprintf(
		"%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=%s&time_zone=%s",
		"root",
		"123456",
		"127.0.0.1",
		32000,
		"test",
		url.QueryEscape("Asia/Shanghai"),
		url.QueryEscape("'+8:00'"),
	)
	rds, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Panic(err)
	}
	rds = rds.Debug()
	err = rds.AutoMigrate(&TestTable{})
	if err != nil {
		log.Panic(err)
	}
}
```

**Comment by s-takehana** [comment]
@zhchbin I've reproduced it.
Sorry, I was only checking `DEFAULT:0`.

**Comment by Icety** [comment]
Also happening for postgres on:
gorm.io/driver/postgres v1.1.0
gorm.io/gorm v1.21.11

**Comment by s-takehana** [comment]
`comment` tag too.
I've confirmed the same behavior in MySQL.

```go
type User struct {
	gorm.Model
	Name   string `gorm:"comment:a1"`
	Status uint   `gorm:"comment:1"`
}
```

Please change the label to `type:with reproduction steps` from `type:question`.

**Comment by jelech** [comment]
> `comment` tag too.
> I've confirmed the same behavior in MySQL.
> 
> ```go
> type User struct {
> 	gorm.Model
> 	Name   string `gorm:"comment:a1"`
> 	Status uint   `gorm:"comment:1"`
> }
> ```
> 
> Please change the label to `type:with reproduction steps` from `type:question`.

Looks like i can't change the label.
