### ISSUE TITLE
how to save struct into mysql blob column

### ISSUE THREAD

**Issue by ayamzh** [go-gorm/gorm#4201]
## Your Question

if i want to save a struct like this, to insert or select from mysql table, table column type is  A BLOB, B BLOB, C varchar(255) text or json

type User struct{
    Id
    Afield   *A   `gorm:Type:Blob`
    Bfield   []*B   `gorm:Type:Blob`
   Cfield   *C    `gorm:Type:varchar`  or  `text`   or   `json`
}
type A struct{
}
type B struct{
}
type C struct{
}

what should i do?

**Comment by jinzhu** [comment]
I don't get why it doesn't work, if it doesn't, please create a reproducible PR.
