### ISSUE TITLE
Refactor and/or remove utils package

### ISSUE THREAD

**Issue by rokusei** [go-gorm/gorm#4202]
Thank you for all the work you've done on this package!

## Describe the feature

[Go documentation](https://blog.golang.org/package-names) recommends to **Avoid meaningless package names.** 

More specifically, it states:
`Packages named util, common, or misc provide clients with no sense of what the package contains. `

within the [utils/utils.go](https://github.com/go-gorm/gorm/blob/master/utils/utils.go) package there are a variety of different functions ranging from test, string, and misc database related functions. I propose moving these to a better location (potentially to the package to where they are used) and eliminating this entire package to avoid it's ambiguity.

## Motivation

Gorm seems to follow a lot of best practices for Go, but this specific example seems like a deviation so I felt like it was worth mentioning.

**Comment by rokusei** [comment]
I feel like most of the functions within [utils/utils.go](https://github.com/go-gorm/gorm/blob/master/utils/utils.go) could be moved to something like a _strings.go_ file within the root directory.

**Comment by rokusei** [comment]
I believe this ambiguity has lead to some confusion and duplication of code, for example:

The User struct has been duplicated:
https://github.com/go-gorm/gorm/blob/master/utils/tests/models.go#L14
https://github.com/go-gorm/gorm/blob/master/schema/model_test.go#L11

**Comment by jinzhu** [comment]
> The User struct has been duplicated:

not duplicated, it is on purpose

**Comment by jinzhu** [comment]
> Packages named util, common, or misc provide clients with no sense of what the package contains.

the `util` package is not expected to be used in user's projects, it is not moved to the internal because there are some gorm plugins might use it.
