### ISSUE TITLE
soft delete not working when join table, and how do it

### ISSUE THREAD

**Issue by MarsonShine** [go-gorm/gorm#4204]
ON'T CHANGE THE TEMPLATE -->

## Your Question
soft delete not working when join table

## The document you expected this should be explained
for example 

```go
type links struct {
	Id int32
	DeletedAt	gorm.Deleted_At
	...
}
type otherTable struct {
	...
	linkId int32
	...
}
```

and my query:

```go
type selectors struct {
    linkId int32
    ... // some specified fields
}
r.data.db.
		Table("links l").
		Select("l.Id,l.Name,l...").
		Joins("inner join otherTable p on p.linkId = l.Id").
		Where("l.Id = ?", id).
		Find(&selectors)
```

the generate sql : `select ... from links l inner join otherTable p on l.Id = p.linkId where l.Id = 3 `

## Expected answer
the print sql is `select ... from links l inner join otherTable p on l.Id = p.linkId where l.Id = 3 `
but i expected : `select ... from links l inner join otherTable p on l.Id = p.linkId where l.Id = 3 and l.DeleteAt is not null `
what should i do?

**Comment by MarsonShine** [comment]
gorm.io/gorm v1.21.3
go version go1.15.5 windows/amd64

**Comment by MarsonShine** [comment]
ok, i resolved
just append `Model` method : 
```go
r.data.db.Model(&links{}).
		Table("links l").
		Select("l.Id,l.Name,l...").
		Joins("inner join otherTable p on p.linkId = l.Id").
		Where("l.Id = ?", id).
		Find(&selectors)
```go

**Comment by MarsonShine** [comment]
i find another problem: when join operate，the main table and left join table, when these table Both have soft delete fields，only main table's soft delete is valide，other table's delete fields not working.
the couse unexpected errors, it brings gorm‘s inconsistency in behavior

**Comment by MarsonShine** [comment]
i know because Joins methd's paramter not struct type, so gorm don't know table's metedata,
so we can provider JoinModels api, tell gorm to generate right sql.
join operate is a very common and frequent operation

**Comment by jinzhu** [comment]
https://gorm.io/docs/many_to_many.html#Customize-JoinTable

**Comment by MarsonShine** [comment]
thanks a lot for reply
although this method doesn't work for us either，but it doesn't matter to gorm
