### ISSUE TITLE
GORM sql-injection

### ISSUE THREAD

**Issue by Hedgehogues** [go-gorm/gorm#4206]
## Your Question

I found a bug, I think. Maybe this is feature, check it, please: 

    err := db.Debug().Table("SELECT * FROM content").Find(model).Error

Response:

    SELECT * FROM SELECT * FROM content

For comparing:

    err := db.Debug().Table("content").Find(model).Error

Select:

    SELECT * FROM "content"

Table name is not escaping.

## The document you expected this should be explained

https://gorm.io/docs/query.html

I don't found any examples

## Expected answer

I want to make sure that this is really a bug.

**Comment by LonglyCode** [comment]
It is feature,check this:
https://gorm.io/docs/advanced_query.html#From-SubQuery

**Comment by jinzhu** [comment]
https://gorm.io/docs/security.html
