### ISSUE TITLE
Associations Append generated 'Merge Into' causes an invalid object name error with mssql

### ISSUE THREAD

**Issue by eaong07** [go-gorm/gorm#4207]
## Your Question

Hi, I encountered an issue when I used Associations Append on my project. It works fine on the initial insert since it includes the schema into the query; however, when Associations Append is applied on a record with ore-existing data the generated `Merge Into` query does not include the schema into the query, which causes an invalid object name error with mssql. 

My question is: Is there a method or function I have to add to my code to make sure the schema is always included into the generated query?

## The document you expected this should be explained

https://gorm.io/docs/associations.html

## Expected answer
A way to upsert associated tables

**Comment by jinzhu** [comment]
Can you create a reproducible PR?
