### ISSUE TITLE
onConflictOption DoUpdates should be aligned to refactored UpdateAll

### ISSUE THREAD

**Issue by zhangriyueming** [go-gorm/gorm#4216]
## Describe the feature

[This section
](https://github.com/go-gorm/gorm/blob/220349ccf2990c47988a54df94e838803829898c/callbacks/associations.go#L328) should be aligned to the changes of [this commit](https://github.com/go-gorm/gorm/commit/27bb9137d3ad1751e47ceb6e325fb5d17b0eb7aa)

## Motivation

As the same reason of the refactor UpdateAll, while the models are associations of the other models, we need to specify the conflict columns instead of using the primary keys.

## Related Issues

https://github.com/go-gorm/gorm/commit/27bb9137d3ad1751e47ceb6e325fb5d17b0eb7aa

**Comment by jinzhu** [comment]
When saving associations, it should not use the main object's `OnConflict` option.

**Comment by zhangriyueming** [comment]
> When saving associations, it should not use the main object's `OnConflict` option.

Of course it should not use the main object's `OnConflict` option, the issue is there should be a way to specify the `columns` in associations.

Imagine that a model which use the [refactored UpdateAll](https://github.com/go-gorm/gorm/commit/27bb9137d3ad1751e47ceb6e325fb5d17b0eb7aa), and another model have association with it. There is a necessary for `columns` specified, otherwise the refactored UpdateAll will be unnecessary too.

Let me try to clarify it more, let's say we have a situation we need to do something with 
`
type Bar struct {
    ID uint
    A string
    B string
    ....
}

item := model.Bar{}
db.Clauses(clause.OnConflict{
Columns:   []clause.Column{{Name: "a"}, {Name: "b}},
UpdateAll: true}).Create(&item)
`
Then of course we can predicable imagine we will have situation with
`
type Foo struct {
  BarID uint
  Bar *Bar
}
`
And we need to save the Bar respecting the constraints with 'a' and 'b' columns too. So we should have a proper way to implement that.

**Comment by zhangriyueming** [comment]
@jinzhu please check the update
