### ISSUE TITLE
 What is the difference between `Find` and `Scan`， Can I replace `Scan` with `Find` ？

### ISSUE THREAD

**Issue by machine3** [go-gorm/gorm#4218]

**Comment by abelseniorly** [comment]
Find is a gorm query function used to load the results into our struct. Find run all gorm hook functions. Scan however is similar to default sql library scan function, wherein you need to put in each column that you have to scan in.

**Comment by jinzhu** [comment]
Scan, Find using different callbacks, `Scan` won't call hooks methods.

**Comment by hoang6896vn0101** [comment]
thank you~~~
