### ISSUE TITLE
Does GORM support encrypted SQLite DB

### ISSUE THREAD

**Issue by jackfr0st13** [go-gorm/gorm#4227]
## Your Question

I would like to work with an encrypted SQLite DB whilst working with gorm so that the data is secure. How do I achieve this ?

## The document you expected this should be explained

https://gorm.io/docs/connecting_to_the_database.html

## Expected answer

I would like a way of achieving this or a work around for the same.

**Comment by oSethoum** [comment]
Is there an answer for this ?

**Comment by zyxk** [comment]
I want to connect to the encrypted SQLite dB. What should I do?
