### ISSUE TITLE
Generate markdown document of data model using mermaid diagrams

### ISSUE THREAD

**Issue by TJM** [go-gorm/gorm#4242]
## Describe the feature

It would be very useful to be able to generate a markdown document of the GORM data model using mermaid entity relationship diagrams.

## Motivation

Making documentation by hand sucks.

## Related Issues

REF: https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram

**Comment by TJM** [comment]
Example output:

```mermaid
erDiagram

User ||--|| Account : has-one
User ||--o{ Pet : has-many
User ||--o{ Toy : has-many-polymorphic
User |o..o| Company : belongs-to
User }o..o{ Language : speaks
User ||--o{ User : team
User ||--o| User : manager
User }o--o| User : friends


Pet ||--|| Toy : has-one-polymorphic



User {
    string Name
    uint Age
    time Birthday
    int CompanyID
    uint ManagerID
    bool Active
}

Account {
    NullInt64 UserID
    string Number
}

Pet {
    uint UserID
    string Name
}

Toy {
    string Name
    string OwnerID
    string OwnerType
}

Company {
    int ID
    string Name
}

Language {
    string Code
    string Name
}

```

**Comment by TJM** [comment]
NOTE: Also maybe "vote" for this feature: https://github.community/t/feature-request-support-mermaid-markdown-graph-diagrams-in-md-files/1922

Here is what it looks like in GitLab: https://gitlab.com/-/snippets/2099793

![Screen Shot 2021-04-02 at 11 19 22 AM](https://user-images.githubusercontent.com/1641316/113438205-54693500-93a5-11eb-9d24-061715667749.png)

**Comment by jinzhu** [comment]
It would be helpful if there is a gorm plugin to do the job, which could be hosted under github.com/go-gorm, but I think it should not part of gorm itself.
