### ISSUE TITLE
how to know `Upsert` is insert or update 

### ISSUE THREAD

**Issue by dandyhuang** [go-gorm/gorm#4245]
maybe i can Register Callback???

**Comment by keemyb** [comment]
I've not used Upsert, but say you have the model:
```
type Foo struct {
  gorm.Model

  FooID string
  OtherField string
}
```

You can achieve this by first doing an update with a where condition, then checking to see if the update affected anything. If it didn't you know you will have to insert a record:

```
func upsert(db *gorm.DB, foo *Foo) (wasUpdate bool, err error) {
	updates := db.Model(foo).
		Where("foo_id = ?", foo.FooID).
		Updates(foo)
	if updates.RowsAffected == 0 {
		err = db.Create(foo).Error
		if err != nil {
			return
		}
	} else {
                wasUpdate = true
        }
        return
}
```

**Comment by dandyhuang** [comment]
> I've not used Upsert, but say you have the model:
> 
> ```
> type Foo struct {
>   gorm.Model
> 
>   FooID string
>   OtherField string
> }
> ```
> 
> You can achieve this by first doing an update with a where condition, then checking to see if the update affected anything. If it didn't you know you will have to insert a record:
> 
> ```
> func upsert(db *gorm.DB, foo *Foo) (wasUpdate bool, err error) {
> 	updates := db.Model(foo).
> 		Where("foo_id = ?", foo.FooID).
> 		Updates(foo)
> 	if updates.RowsAffected == 0 {
> 		err = db.Create(foo).Error
> 		if err != nil {
> 			return
> 		}
> 	} else {
>                 wasUpdate = true
>         }
>         return
> }
> ```

Of course this can be achieved, but you must lock the table like `for update` to ensure atomic。 I test `upsert`,  when db.RowsAffected = 1 is insert,db.RowsAffected = 2 is update。 But I am not sure if it is correct

**Comment by jinzhu** [comment]
https://gorm.io/docs/create.html#Upsert-On-Conflict

**Comment by jaxsong** [comment]
use [xmax](https://stackoverflow.com/questions/38851217/postgres-9-5-upsert-to-return-the-count-of-updated-and-inserted-rows/38858662#38858662)
