### ISSUE TITLE
#3908 was regressed from 1.20.12 to 1.21.2

### ISSUE THREAD

**Issue by iwarapter** [go-gorm/gorm#4252]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/310

## Description

#3908 Seems to have been regressed from 1.20.12 to 1.21.x, you can see this from the latest dependabot pull requests

https://github.com/iwarapter/audited/issues?q=label%3Adependencies+gorm

**Comment by iwarapter** [comment]
go-gorm/playground#310

**Comment by jinzhu** [comment]
works for me, some wrong in your code.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/6843/114117028-618fa200-9918-11eb-82e4-8c12533dd539.png">
