### ISSUE TITLE
Is it possible to write shared db operations once, and reuse?

### ISSUE THREAD

**Issue by kuchaguangjie** [go-gorm/gorm#4262]
I have created a dao level to wrap the database operations, each table has its own dao type.

Now, each dao need to write a `Get()` method to get a record by id. And I have repeat that code for each new table.

Wondering is it possible to write a BaseDao in go, with a single Get() method, so that I don't have to write this code 2 times?

_(This is very common & easy in Java, due to its oo feature, since go is very different, I'm not sure is this possible)_

**Refer:**
- Question I have asked on SO: https://stackoverflow.com/questions/66996922

**Comment by NoSugarCoffee** [comment]
Maybe can't. Because go dose not support genrics before go 1.18.

I think extract `dao` layer maybe a anti-pattern if you want to use [hook](https://gorm.io/docs/hooks.html).

**Comment by kuchaguangjie** [comment]
But go 1.18 is here now.

**Comment by jinzhu** [comment]
yeah, so it is possible now, and nothing related to GORM?
