### ISSUE TITLE
Why is such weird pattern in documentation?

### ISSUE THREAD

**Issue by RadekD** [go-gorm/gorm#4264]
## Your Question
https://gorm.io/docs/transactions.html#A-Specific-Example
```go
  defer func() {
    if r := recover(); r != nil {
      tx.Rollback()
    }
  }()
  ```
Why is this weird pattern in documentation?
Why calling recover function when you can just `defer tx.Rollback()`? 

## The document you expected this should be explained

https://gorm.io/docs/transactions.html#A-Specific-Example

**Comment by jinzhu** [comment]
This is just an example, you can leave your transaction open when there is a panic happens.
