### ISSUE TITLE
Are Polymorphic many2many relationships possible

### ISSUE THREAD

**Issue by AlexThurston** [go-gorm/gorm#4270]
## Your Question

Is it possible to define models that have a polymorphic many2many relationship?  The simplest example would be the following:

```golang
type Label struct {
	LabeID             uint `gorm:"primarykey"`
        Name               string
}

type Fruit struct {
	gorm.Model
	Name   string
	Labels []*Label `gorm:"many2many:labels;polymorphic:Label"`
}

type Vegetable struct {
	gorm.Model
	Name   string
	Labels []*Label `gorm:"many2many:labels;polymorphic:Label"`
}
```

In this scenario, a single label (A) can belong to both a fruit and vegetable entry.  And both a fruit or vegetable can have many labels.

**Comment by jinzhu** [comment]
duplicated with https://github.com/go-gorm/gorm/issues/4004
