### ISSUE TITLE
How can I use “Custom Preloading SQL” in the "Nested Preloading"?

### ISSUE THREAD

**Issue by snowdream** [go-gorm/gorm#4274]
## Your Question

I can use "Nested Preloading", but i want just sereval fileds but not all.

So i think i should use “Custom Preloading SQL” in the "Nested Preloading".

How can i do that?

like this?
```
db.Preload("Order").Preload("Order.OrderItem", func(db *gorm.DB) *gorm.DB {
  return db.Select("orderitem.price")
}).Find(&users)
```

It‘s  my code :
```
	var data models.Machine

		err = servers.Db.Preload("Publisher").Preload("Publisher.Personal", func(db *gorm.DB) *gorm.DB {
			return db.Select("status")
		}).Where("id = ?", id).First(&data).Error

```

When i run it, i get errors:
```
invalid query condition: 0x1b2bbc0 
```

<img width="1341" alt="图片" src="https://user-images.githubusercontent.com/737958/114299921-5becb480-9af0-11eb-9349-d8620a481cbd.png">

## The document you expected this should be explained

https://gorm.io/docs/preload.html#Custom-Preloading-SQL
https://gorm.io/docs/preload.html#Nested-Preloading

## Expected answer

“Custom Preloading SQL” in the "Nested Preloading"

**Comment by jinzhu** [comment]
yes, if it doesn't work, provide a reproducible PR.
