### ISSUE TITLE
When not using gorm.Model, .First confuses the primaryKey

### ISSUE THREAD

**Issue by nicolasvac** [go-gorm/gorm#4275]
https://github.com/go-gorm/playground/pull/1

## Description

When not using gorm.Model as the base struct, the method First gets confused when no columns are specified.

The expected behavior should be that if an ID column exists, First should keep working like normal with the gorm.Model.
Instead it only works by specifing the column to search for.

I'm using gorm with the mysql driver, and the specified parameter is an UUID v4 generated from fiber.utils as a string.

```go
type BaseModel struct {
	ID        string `json:"ID" gorm:"primaryKey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

func (b *BaseModel) BeforeCreate(tx *gorm.DB) error {
	b.ID = utils.UUIDv4()

	return nil
}

type User struct {
	BaseModel
	Name         string        `json:"Name" gorm:"notnull"`
	Username     string        `json:"Username" gorm:"notnull;unique"`
	Email        string        `json:"-" gorm:"notnull;unique"`
}

---

func get() {
   var user User

   // doesnt'work
   database.DBConn.First(&user, "d2a5beec-7cc4-4671-881a-d7b28b2719c2")

   // works
   database.DBConn.First(&user, "id = ?", "d2a5beec-7cc4-4671-881a-d7b28b2719c2")
}
```

Error:

```
Error 1054: Unknown column 'd2a5beec' in 'where clause'
SELECT * FROM `users` WHERE d2a5beec-7cc4-4671-881a-d7b28b2719c2 AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1
```

**Comment by nicolasvac** [comment]
Issue is active.

**Comment by minayousseif** [comment]
I think it was mentioned in the docs [Retrieving-objects-with-primary-key](https://gorm.io/docs/query.html#Retrieving-objects-with-primary-key)

> Objects can be retrieved using primary key by using Inline Conditions if the primary key is a **number**, Be extra careful with strings to avoid SQL Injection, check out Security section for details

> If primary key is a string like uuid, need to write it like:
```go
db.First(&user, "id = ?", "1b74413f-f3b8-409f-ac47-e8c062e3472a")
// SELECT * FROM users WHERE id = "1b74413f-f3b8-409f-ac47-e8c062e3472a";
```

**Comment by LuisAntezana** [comment]
This also works if you don't want to use the SQL syntax:

```go
var user = User{ID: "1b74413f-f3b8-409f-ac47-e8c062e3472a"}
database.DBConn.First(&user)
```

**Comment by semmet95** [comment]
Thanks to @minayousseif and @LuisAntezana 
You guys saved me so much time.
