### ISSUE TITLE
V2: Preload on other than the default database connection

### ISSUE THREAD

**Issue by kitloong** [go-gorm/gorm#4279]
## Your Question

What is the recommended way to preload on other than the default DB connection?
Also possible to mix the usage with the transaction?

## The document you expected this should be explained

https://gorm.io/docs/dbresolver.html
https://gorm.io/docs/preload.html
https://gorm.io/docs/models.html

## Expected answer

```
db.Preload("Profile"). // Default connection, say: DB_A
    Preload("Orders"). // Second connection, say: DB_B, where DB_B is not replica of DB_A
    Preload("Orders.Items"). // DB_B
    Preload("Address") // DB_A
    First(&user, userID).
    Error
```
Or perhaps any way to define different DB connections per model?

> Transaction
> When using transaction, DBResolver will use the transaction and won’t switch to sources/replicas

Also, how to make the above preload works with DB transaction?
```
tx := db.Begin()
tx.Preload("Profile"). // Default connection, say: DB_A
    Preload("Orders"). // Second connection, say: DB_B
    ...
```

**Comment by jinzhu** [comment]
https://gorm.io/docs/dbresolver.html
