### ISSUE TITLE
不同版本调用create方法时报错

### ISSUE THREAD

**Issue by JasperMali** [go-gorm/gorm#4283]
## 数据库使用sqlite3,当我迁移gorm版本从v1.9.16到v1.21.7时，并发调用Create方法,在v1.21.7版本的代码中，gorm logger会提示`SLOW SQL >= 200ms` 和 `database is locked`, 但是在v1.9.16版本的代码中运行正常。

想知道时是v1.21.7的sql driver做了什么变动吗或者是要在打开数据库时设定一些选项才可以避免这样的错误吗？

**Comment by wxzcyy** [comment]
Do you have solved the problem?
