### ISSUE TITLE
PostgreSQL don't support add comment for column when create table !!!

### ISSUE THREAD

**Issue by GeekByte** [go-gorm/gorm#4285]
In the GORM documentation, it is possible to add `gorm:"comment:'xxxx'"` for table's column when creating them, but this is the way MySQL and Oracle databases write them, and PostgreSQL does not support it.

Therefore, do not use the GORM COMMENT tag when creating tables for PostgreSQL using GORM.

**Comment by jinzhu** [comment]
upgrade postgres driver.

**Comment by JoeyGaojingxing** [comment]
I use `gorm.io/driver/postgres v1.0.8` which is the latest version of postgres driver, but still cannot add comment to postgres @jinzhu
