### ISSUE TITLE
Statement clauses is sticky and keeps latest data in next call

### ISSUE THREAD

**Issue by jsaevitzon** [go-gorm/gorm#4287]
Been running into this issue. It began when using the scoping functionality. 
Version 1.20
Using go-sql/sqlx and postgres

envs := []Env{}
db.Where(map[string]interface{}{"Deleted": false}).Find(&envs)

Statement.Clauses output:
map[FROM:{FROM {[] []} } SELECT:{SELECT {false [] } } WHERE:{WHERE {[{Deleted false}]} }]
map[FROM:{FROM {[] []} } SELECT:{SELECT {false [] } } WHERE:{WHERE {[{Deleted false} {Deleted false}]} }]
map[FROM:{FROM {[] []} } SELECT:{SELECT {false [] } } WHERE:{WHERE {[{Deleted false} {Deleted false} {Deleted false}]} }]

every time exec the Statement.Clauses WHERE add a cond

### GORM Playground Link
go-gorm/playground#1

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html#New-Session-Mode
