### ISSUE TITLE
How to perform database methods in GORM? like regexp_replace

### ISSUE THREAD

**Issue by shivkumarsingh7** [go-gorm/gorm#4291]
How to use **regexp_replace** in  GORM? 
below is the raw query 

_SELECT * FROM posts where regexp_replace(content, E'<.*?>', '', 'g') like '%texttoserach%' ORDER BY created_at desc LIMIT 100_

How to convert this in gorm, I tried like below but it always consider **regexp** _?_ "question mark" as placeholder which breaks the query
err = p.db.WithContext(ctx).Where("regexp_replace(content, E'<.*?>', '', 'g') LIKE ?", fmt.Sprintf("%%%s%%", strings.ToLower(searchKeyword))).Order("created_at desc").Limit(count).Find(&us).Error

Is there any way to implement above select query in gorm?

**Comment by jinzhu** [comment]
use gorm.Expr
