### ISSUE TITLE
Support Update Return Selected Column

### ISSUE THREAD

**Issue by thaitanloi365** [go-gorm/gorm#4295]
## Describe the feature
```
UPDATE products SET price = price * 1.10
WHERE price <= 99.99
RETURNING name, price AS new_price;
```

Could we support returning data from Update Statement?

**Comment by pielambr** [comment]
Should already be supported with Raw + First

**Comment by ethanwu10** [comment]
Another usecase I ran into for this is retrieving UpdatedAt as represented in the database after executing `.Updates()`. GORM internally sets UpdatedAt to `time.Now()`, which can be higher precision than what is stored in the database; thus, strict equality from the updated model's `UpdatedAt` to that of a freshly-queried model fails.

**Comment by jinzhu** [comment]
https://gorm.io/docs/update.html#Returning-Data-From-Modified-Rows

**Comment by jinzhu** [comment]
added support for returning.
