### ISSUE TITLE
 In the new version, should we be using primary_key or primaryKey

### ISSUE THREAD

**Issue by praveenvaltix** [go-gorm/gorm#4299]
## Your Question

We use gorm to manage our MySQL based tables. We recently upgraded to new gorm version and noticed "unique_index" was not working. We fixed our code to change it to "uniqueIndex". At the same time, we noticed that "primary_key" was still working for our tables where we use composite primary keys.

## Expected answer

Please let us know is this expected, working accidentally and/or will be deprecated towards "primaryKey" in future?

**Comment by s-takehana** [comment]
Did you confirm below?

https://gorm.io/docs/v2_release_note.html#Tags

> GORM V2 prefer write tag name in camelCase, tags in snake_case won’t works anymore, for example: auto_increment, unique_index, polymorphic_value, embedded_prefix, check out Model Tags
