### ISSUE TITLE
Why logger ExplainSQL parameter case fmt.Stringer,this makes the log different from the actual

### ISSUE THREAD

**Issue by liov** [go-gorm/gorm#4303]
## Your Question

Why logger ExplainSQL parameter case fmt.Stringer,this makes the log different from the actual

## The document you expected this should be explained

 ```go
type Letter int

func (l Letter) String() string {
	switch l{
	case A:
		return "A"
	case B:
		return "B"
	default:
		return "C"
	}
}

const(
	A Letter= 1+iota
	B
	C
)
type Foo struct {
	Id int
	Letter Letter
}

func TestLogger(t *testing.T) {
	db:=gorm.DB{}
	var foos []Foo
	db.Where("letter=?",A).Find(&foos)
}  

```
```sql
# log
SELECT * FROM foo WHERE letter = 'A';
# actual
SELECT * FROM foo WHERE letter = 1;
```
## Expected answer

I don't understand why case fmt.Stringer here ，I want to make a PR to delete case fmt.Stringer,Is it possible？

**Comment by sawadyecma** [comment]
@jinzhu @liov 

I'm facing the problem that logging SQL doesn't match actual SQL.
It made my team confused.
May I make this issue again and fix it ?
