### ISSUE TITLE
Composite Primary Key Order or Priority

### ISSUE THREAD

**Issue by smadarasmi** [go-gorm/gorm#4305]
## Your Question

I couldn't find a way to declare composite primary key with ordering or priorities. Other types of indexing are supported with `priority` set: https://gorm.io/docs/indexes.html#Fields-Priority

I tried to do it in similar way to that for primary key but seems not supported
`gorm:"primaryKey,priority:1"`

Is there a different way to do this? The ordering of composite primary key is quite important and I'm not sure if I can/should rely on the ordering of my fields based on what is declared in the struct. 

## The document you expected this should be explained

https://gorm.io/docs/composite_primary_key.html

## Expected answer

A section with priority for composite primary key.

**Comment by smadarasmi** [comment]
I don't think this should be stale.. 

I would be happy to take on this but just wanted some input that you agree with this or whether there are some blockers for doing such things

**Comment by JonasDoe** [comment]
Maybe it's the same issue: I can't set the priority of an ordinary composite index with the GORM `v1.9.16`, which for some reason can only be found in a fork from @jinzhu . But anyway, the error seems to stem from [this](https://github.com/jinzhu/gorm/blob/master/scope.go#L1295) line, basically splitting the tag value by `,` and understanding each part as a index name. That way, `priority` is taken as an index name.

**Comment by jinzhu** [comment]
https://gorm.io/docs/indexes.html#Fields-Priority

**Comment by JonasDoe** [comment]
> 

Yes, this doesn't work as expected. Or what exactly am I missing in this link?

**Comment by jinzhu** [comment]
this only works with gorm.io/gorm, doesn't works for v1.9.16 https://gorm.io/docs/v2_release_note.html

**Comment by JonasDoe** [comment]
Ah, I see. The second link + the insight that there aren't any git releases for gorm v2 (but version tags nevertheless) finally helped me to understand this odd construction of gorm repos. Thank you!
