### ISSUE TITLE
panic in db.Statement.SetColumn  if Model is unaddressable by  update

### ISSUE THREAD

**Issue by liangzhiyang** [go-gorm/gorm#4306]
is this a bug? 
if i use  db.Statement.SetColumn("Name", "jinzhu")  in  callbacks
and 
i uss Updates like below

> // 根据 struct 更新
> db.Model(User{}).Where("role = ?", "admin").Updates(User{Name: "hello", Age: 18})
> // UPDATE users SET name='hello', age=18 WHERE role = 'admin;

it will be panic in https://github.com/go-gorm/gorm/blob/7701c885077051c864da309ed850631ada7d0eea/statement.go#L552
because of the  db.Statement.ReflectValue is not addressable

^_^

**Comment by jinzhu** [comment]
Fixed by https://github.com/go-gorm/gorm/commit/d327926425afecbe084997ba195497107cd71a92

Thank you for your report.
