### ISSUE TITLE
belongs_to and has_one reversed if field names are identical

### ISSUE THREAD

**Issue by SchiffFlieger** [go-gorm/gorm#4316]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/313

## Description
We recently updated gorm from `v1.20.12` to `v1.21.7` and noticed some issues with our migrations. I tracked it down and it seems like commit 628a0ae7 introduced a change in behavior for the *has_one* and *belongs_to* relations. 

We have two structs: 
```
type (
	Product struct {
		ProductID  string `gorm:"primaryKey"`
		MaterialID string
		SalesItem  SalesItem `gorm:"foreignKey:MaterialID"`
	}

	SalesItem struct {
		MaterialID string `gorm:"primaryKey"`
	}
)
```
As you can see, both struct have a field called `MaterialID`. Previously, this would result in the foreign key being placed on the products side. The `Product` *belongs to* one `SalesItem` or in other words the `SalesItem` *has one* `Product`. 

After commit 628a0ae7, the relation is now the other way round. Meaning the foreign key is now in the `SalesItem` table and the `SalesItem` *belongs_to* one `Product`.

I realized this is only the case because both struct have a field named `MaterialID`. If you rename the `SalesItem.MaterialID` to e. g. `SalesItem.ItemID`, then the relation is set correctly as before. Same thing happens if you rename the `Product.MaterialID` to e. g. `Product.SalesItemID` (and change the `foreignKey` struct tag).

Might be related to #4192

**Comment by paraswaykole** [comment]
Yes! I am facing a similar issue and tracked it down to commit [`628a0ae`](https://github.com/go-gorm/gorm/commit/628a0ae707f230c67bca2e632fb302037c707705), schema/relationship.go -> line 359,
which is checking for the condition:`field.Schema == relation.FieldSchema`. 

The `field.Schema` is not that of Field but of the parent struct. According to line 128 in schema/schema.go, `ParseField` function is called on schema of the parent struct.

So, logically we are checking if the parent struct schema is equal to field schema, which may not be the case.

**Comment by paraswaykole** [comment]
@jinzhu I have submitted a PR which solves this issue. I tested both the cases the one that I mentioned and the one mentioned by @SchiffFlieger, and It worked fine.

**Comment by SchiffFlieger** [comment]
@paraswaykole Just checked your fix, I can confirm that it solves both the minimalized example I gave and also my real-world use case (which is a bit more complex). Thank you for providing that fix! Hope it will be merged soon.

**Comment by paraswaykole** [comment]
@jinzhu May I ask why was this issue closed, updating gorm library is breaking migrations for us. This is a super critical issue. I please request you to open this issue.
