### ISSUE TITLE
GORM Changelog

### ISSUE THREAD

**Issue by JeffPHP** [go-gorm/gorm#4317]
## Your Question

Is there any changelog for Gorm? When I click on the version on the Docs, I go to "GORM 2.0 Release Note", but I would need more granular version changes because I am using v1.20.12 and I would like to know what changed up to v1.21.8.

## The document you expected this should be explained

https://gorm.io/docs/v2_release_note.html

## Expected answer

If possible, could you add a link to a changelog of minor versions (if it exists somewhere)? Thanks by advance

**Comment by s-takehana** [comment]
Maybe helpful.

https://github.com/go-gorm/gorm/releases
https://github.com/go-gorm/gorm/compare/v1.20.12...v1.21.8

**Comment by JeffPHP** [comment]
Thanks! There should be a link to this page from the documentation 😉
