### ISSUE TITLE
Functionality of querying.

### ISSUE THREAD

**Issue by darienmiller88** [go-gorm/gorm#4318]
## Your Question
So I am trying to do a simple search query using the code `db.Where(&models.User{Username: user.Username}).First(&user)` , and for some reason, whenever `user.Username`  (`user` being an instance of a `User` struct) is an empty string `""`, it returns the first  row in my database, but whenever I give `user.Username` a space `" "`, nothing is returned as expected. The SQL queries also look different, is this intended behavior? Or am I making a mistake in what value I'm passing to the methods? 

My "users" table looks  like this, with a single user "janedoe" in the database with the other fields filled out. 
```
type User struct{
	gorm.Model
	Username string `json:"username" gorm:"type:string; unique; not null"`
	Password string `json:"password" gorm:"type:string"`
	FavoriteFood string `json:"favorite_food" gorm:"type:string"`
}
```

SQL command for passing `user.Username` an empty string `""`
`SELECT * FROM "users" WHERE "users"."deleted_at" IS NULL ORDER BY "users"."id" LIMIT 1
`

SQL command for passing `user.Username` with a space, or any other character `" "`
`SELECT * FROM "users" WHERE "users"."username" = ' ' AND "users"."deleted_at" IS NULL ORDER BY "users"."id" LIMIT 1
`

Why does this happen?

## Expected answer
I would expect both `""` and `" "` to return 0 users found for the search query I tried above, but the empty string returns the first user, whereas any other character that doesn't match the username of the user I have in the table returns no users as it should. What should I change?

**Comment by s-takehana** [comment]
Please see this.
https://gorm.io/docs/query.html#Struct-amp-Map-Conditions
