### ISSUE TITLE
gorm preload : error : teacher_scores: unsupported relations for schema TeacherInfo 

### ISSUE THREAD

**Issue by day112** [go-gorm/gorm#4321]
## GORM Playground Link
![image](https://user-images.githubusercontent.com/10526728/115896919-7e86b200-a48e-11eb-9b91-493ad25fd896.png)
![image](https://user-images.githubusercontent.com/10526728/115896944-86465680-a48e-11eb-9bbb-335e168629b8.png)
![image](https://user-images.githubusercontent.com/10526728/115896966-8c3c3780-a48e-11eb-8984-714dfdaa3988.png)

https://github.com/go-gorm/playground/pull/1

## Description
when i use  gin, gorm preload function is ok, but  gqlgen  gorm preload : error : teacher_scores: unsupported relations for schema TeacherInfo 

versions
gqlgen version? v0.13.0
go version? 1.16.3
dep or go modules? go modules

**Comment by RajeshPaul38** [comment]
I am facing same issue. It is a genuine issue. Someone Pls help.

**Comment by a631807682** [comment]
If you encounter a bug in GORM, please report with the Playground Pull Request's link
https://github.com/go-gorm/playground

**Comment by a631807682** [comment]
use schema filed name, don't use table name in `Preload`

**Comment by RajeshPaul38** [comment]
Gorm official documentation says to use the association name itself right? Here's the link I'm refering to: https://gorm.io/docs/preload.html

**Comment by a631807682** [comment]
Use the associated name, which in this issues should be used `TeacherScores `

**Comment by RajeshPaul38** [comment]
I indeed used the association name itself. Still I am getting the same error.

**Comment by a631807682** [comment]
please report with the Playground Pull Request's link

**Comment by mnvx** [comment]
I hope the following answer will help: https://stackoverflow.com/a/78532448/1920758
