### ISSUE TITLE
Check-only foreign key without upserting 

### ISSUE THREAD

**Issue by zanlikealobster** [go-gorm/gorm#4322]
## Your Question

I have a simple model (let's say a tickets table) with a foreign key referencing another table (statuses). 
My reference table (statuses) is already populated. 
I would like to insert/update tickets with only existing values, validating my foreign key, without adding a new reference (status record) every time a correspondent key is not found (no upset on my reference table).
Is there any way to have this validated automatically?
Or should I validate my statuses manually before each insert/update of tickets (with a hook for example)?
Is the foreign key never validated? I'm using SQLLite.

Thank you!

**Comment by GiancarlosIO** [comment]
same question here :(

**Comment by jinzhu** [comment]
can you write reproducible playground, doesn't really understand that.
