### ISSUE TITLE
ERROR: missing FROM-clause entry for table (SQLSTATE 42P01)

### ISSUE THREAD

**Issue by turk** [go-gorm/gorm#4328]
## Your Question

I want to update data with a has-many relationship, but I receive an error ERROR: missing FROM-clause entry for table "pages" (SQLSTATE 42P01)

What is wrong with this code?

	tx := db.Conn.Begin()
	pages := make([]models.Page, 0, len(request.Translations))

	var category models.Category

	 tx = tx.
		Preload("Pages").
		Where("categories.id = ?", id).
		First(&category)

	if tx.Error != nil {
		return tx.Error
	}

	for _, t := range request.Translations {
		pages = append(pages, models.Page{
			LanguageID:  t.LangID,
			Title:       t.Title,
			Description: t.Description,
			Slug:        t.Slug,
		})
	}

	err := tx.Association("Pages").Replace(pages)
	if err != nil {
		fmt.Println(err)
		return err
	}

	tx.Commit()

**Comment by ccfish86** [comment]
我在没有在many2many表名前加`public.`时，也掉这个错误，不知道你是不这问题。其中前两句都是正常的，后面一句SQL，FROM表名不一致。

![image](https://github.com/go-gorm/gorm/assets/15622514/1e3557dd-c95c-478f-a4e9-cd95db46752e)
不加前：
![image](https://github.com/go-gorm/gorm/assets/15622514/51901bdc-3565-4fac-b2a5-22ad37c9b5fb)

加了后日志：

_[7.391ms] [rows:0] INSERT INTO "public"."sys_base_menus" ("updated_at","created_at","deleted_at","component","path","name","active_name","title","icon","keep_alive","default_menu","close_tab","sort","parent_id","menu_level","hidden","id") VALUES ('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/dashboard/index.vue','dashboard','dashboard','','仪表盘','odometer',false,false,false,1,0,0,false,1),('2024-02-22 15:32:52.08','2024-02-22 10:16:38.541',NULL,'view/app/collectFile/collect_file.vue','collectFile','collectFile','','媒体资源管理','aim',false,false,false,2,0,0,false,2009),('2024-03-16 09:55:40.697','2023-09-06 10:43:52.102',NULL,'view/mall/index.vue','mall','mall','','商城','aim',false,false,false,4,0,0,false,2001),('2023-06-16 18:51:36.893','2023-02-25 14:00:36.626',NULL,'view/mall/order/index.vue','order','order','','订单','shopping-bag',false,false,false,2,2001,0,false,41),('2023-07-18 16:16:18.189','2023-07-18 16:16:18.189',NULL,'view/mall/order/print/index.vue','order/print/','order/print/','','发货','printer',false,false,false,5,2001,0,false,964),('2024-05-06 14:25:52.315','2024-05-06 14:25:52.315',NULL,'view/mall/order/transfers/index.vue','transfers/index','transfers/index','','订单转账','money',false,false,false,26,2001,0,false,2026),('2023-06-16 18:50:35.544','2023-06-16 16:19:09.257',NULL,'view/mall/goods/skus/index.vue','mall/goods/skus','mall/goods/skus','','商品SKU库存','goods-filled',false,false,false,32,2001,0,false,945),('2023-06-16 18:50:20.388','2023-06-16 16:18:05.411',NULL,'view/mall/goods/index.vue','mall/goods','mall/goods','','商品基本信息','goods',false,false,false,33,2001,0,false,944),('2024-04-01 11:28:12.776','2024-04-01 11:28:12.776',NULL,'view/mall/goods/wholesales/index.vue','goods/wholesales','goods/wholesales','','商品批发价格','aim',false,false,false,36,2001,0,false,2018),('2024-04-01 11:28:52.848','2023-08-08 15:06:32.582',NULL,'view/mall/goods/supplies/index.vue','goods/supplies','goods/supplies','','店铺库存管理','aim',false,false,false,51,2001,0,true,979),('2024-04-01 11:30:38.262','2024-04-01 11:30:38.262',NULL,'view/mall/user/coins/index.vue','user/coins','user/coins','','用户铜币记录','coin',false,false,false,68,2001,0,false,2019),('2023-06-16 18:54:11.258','2023-06-16 16:17:22.082',NULL,'view/mall/specs/index.vue','mall/specs','mall/specs','','规格分类','folder',false,false,false,71,2001,0,false,943),('2023-06-16 18:53:59.729','2023-06-16 17:45:58.607',NULL,'view/mall/goods/categories/index.vue','mall/goods/categories','mall/goods/categories','','商品分类','fold',false,false,false,72,2001,0,false,946),('2023-06-16 18:52:47.22','2023-06-07 11:04:58.325',NULL,'view/mall/notices/index.vue','mall/notices','mall/notices','','商 
城公告','message',false,false,false,78,2001,0,false,44),('2023-06-16 16:20:31.025','2023-06-07 16:26:14.666',NULL,'view/mall/order/expresses/index.vue','order/expresses','order/expresses','','物流信息','aim',false,false,false,80,2001,0,false,36),('2023-06-16 18:52:14.607','2023-06-07 10:57:41.67',NULL,'view/mall/address/specs/index.vue','address/specs','address/specs','','特殊地址','location-information',false,false,false,81,2001,0,false,43),('2024-05-06 14:24:09.166','2023-06-07 15:24:36.987',NULL,'view/mall/user/addresses/index.vue','user/addresses','user/addresses','','用户收货地址','location',false,false,false,125,2001,0,false,35),('2023-09-06 10:44:23.602','2023-09-06 10:44:23.602',NULL,'view/mall/address/specs/index.vue','address/spec','address/spec','','特殊地址','aim',false,false,false,233,2001,0,false,2002),('2023-08-19 10:15:49.393','2023-08-19 10:15:49.393',NULL,'view/mall/payment/configs/index.vue','payment/configs','payment/configs','','支付配置','money',false,false,false,666,2001,0,false,985),('2024-03-01 09:39:59.476','2024-03-01 09:39:41.897',NULL,'view/app/colect/index.vue','collect','collect','','藏品管理','aim',false,false,false,5,0,0,false,2011),('2024-05-23 14:39:40.534','2024-03-01 09:41:08.139',NULL,'view/app/collect/coding/collect_coding.vue','collectCode/:id','collectCode','collects','编码管理-${id}','aim',false,false,false,1,2011,0,true,2013),('2024-05-30 16:46:49.44','2024-03-01 09:40:33.502',NULL,'view/app/collect/collects/collect.vue','collects','collects','','藏品管理','aim',false,false,false,2,2011,0,false,2012),('2024-03-04 16:02:10.964','2024-03-04 16:02:10.964',NULL,'view/app/collect/series/collect_series.vue','collectSeries','collectSeries','','系列管理','aim',false,false,false,3,2011,0,false,2014),('2024-05-30 16:47:56.669','2024-05-30 16:47:56.669',NULL,'view/app/collect/coding/visits/index.vue','coding/visits','coding/visits','','藏品访问记录','clock',false,false,false,12,2011,0,false,2027),('2024-05-30 16:51:08.088','2024-05-30 16:48:38.353',NULL,'view/app/collect/coding/binds/index.vue','coding/binds','coding/binds','','藏品绑定记录','clock',false,false,false,13,2011,0,false,2028),('2024-06-07 13:58:14.746','2024-06-07 13:58:14.746',NULL,'view/app/collect/coding/realpicture/records.vue','realpicture/records','realpicture/records','','实物图管理','picture',false,false,false,66,2011,0,false,2032),('2024-04-16 09:53:33.412','2024-04-16 09:50:40.416',NULL,'view/app/brand_auth/index.vue','brandAuth','brandAuth','','品牌授权','aim',false,false,false,6,0,0,false,2020),('2024-04-16 09:54:20.265','2024-04-16 09:54:20.265',NULL,'view/app/brand_auth/article/index.vue','brandArticle','brandArticle','','授权说明','aim',false,false,false,0,2020,0,false,2022),('2024-04-16 09:53:51.568','2024-04-16 09:51:33.696',NULL,'view/app/brand_auth/type/index.vue','authArticleType','authArticleType','','品牌类型','aim',false,false,false,0,2020,0,false,2021),('2024-04-18 17:11:14.401','2024-04-18 17:11:14.401',NULL,'view/app/company/index.vue','companyManager','companyManager','','合作企业','aim',false,false,false,6,0,0,false,2023),('2024-04-18 17:23:35.293','2024-04-18 17:12:20.163',NULL,'view/app/company/apply/index.vue','companyApply','companyApply','','申请','aim',false,false,false,1,2023,0,false,2024),('2024-04-20 16:17:40.258','2024-04-20 16:17:40.258',NULL,'view/app/company/info/index.vue','companyInfos','companyInfos','','企业信息','aim',false,false,false,1,2023,0,false,2025),('2023-08-29 09:28:39.525','2023-08-08 18:26:26.819',NULL,'view/mall/index.vue','aftersales','aftersales','','商城售后','service',false,false,false,7,0,0,false,981),('2023-08-08 18:27:42.494','2023-08-08 18:27:42.494',NULL,'view/mall/aftersales/requests/index.vue','aftersales/requests','aftersales/requests','','售后申请','service',false,false,false,6,981,0,false,982),('2023-08-10 13:51:59.742','2023-08-10 13:51:59.742',NULL,'view/mall/order/reviews/index.vue','order/reviews','order/reviews','','订单评价','notebook',false,false,false,8,981,0,false,983),('2024-04-11 
10:59:39.459','2023-07-28 09:27:19.131',NULL,'view/mall/refund/reasons/inde.vue','refund/reasons','refund/reasons','','退货原因','aim',false,false,false,22,981,0,false,974),('2024-03-27 11:43:45.153','2024-03-27 11:42:56.946',NULL,'view/app/index.vue','collectHall','collectHall','','展馆','aim',false,false,false,9,0,0,false,2015),('2024-03-27 11:45:05.431','2024-03-27 11:45:05.431',NULL,'view/app/collectHall/collect_hall.vue','collectHall/collect_hall','collectHall/collect_hall','','用户展馆','aim',false,false,false,1,2015,0,false,2016),('2024-03-27 15:02:04.385','2024-03-27 15:02:04.385',NULL,'view/app/collectHallHistories/collect_hall_histories.vue','collectHallHistories','collectHallHistories','','收益记录','aim',false,false,false,5,2015,0,false,2017),('2024-03-27 11:45:52.657','2023-02-18 14:40:57.111',NULL,'view/forum/index.vue','forum','forum','','社区','aim',false,false,false,10,0,0,true,37),('2023-09-04 09:44:41.911','2023-03-14 11:46:24.29',NULL,'view/forum/article/index.vue','article','article','','社区','comment',false,false,false,2,37,0,false,904),('2023-09-04 09:45:56.739','2023-05-09 14:00:32.278',NULL,'view/forum/comments/index.vue','forum/comment','forum/comment','','社区回复','chat-line-square',false,false,false,3,37,0,false,928),('2023-03-14 11:43:35.141','2023-02-18 14:42:14.884',NULL,'view/forum/subject/index.vue','subject','subject','','分类','aim',false,false,false,9,37,0,false,38),('2023-07-20 16:17:13.006','2023-07-20 16:16:05.737',NULL,'view/audit/index.vue','audit','audit','','审核','view',false,false,false,16,0,0,false,967),('2023-07-20 16:17:20.009','2023-05-05 16:03:30.439',NULL,'view/audit/audit/index.vue','audit/realtime','audit/realtime','','实时审核','timer',false,false,false,1,967,0,false,925),('2023-07-20 16:17:49.513','2023-07-20 16:17:01.504',NULL,'view/audit/records/index.vue','records','records','','审核纪录','checked',false,false,false,3,967,0,false,968),('2023-08-15 10:22:41.159','2023-08-15 10:22:41.159',NULL,'view/audit/medias/index.vue','audit/medias/','audit/medias/','','媒体文件审核','monitor',false,false,false,5,967,0,false,984),('2023-07-20 16:45:03.337','2023-07-20 16:45:03.337',NULL,'view/audit/auditors/index.vue','auditors','auditors','','审核人员','user',false,false,false,7,967,0,false,969),('2023-03-28 16:55:15.51','2023-03-04 18:38:21.967',NULL,'view/app/index.vue','report','report','','举报处理','aim',false,false,false,18,0,0,false,55),('2023-03-23 11:15:58.547','2023-03-13 11:29:05.922',NULL,'view/app/report/user/index.vue','report/user','report/user','','举报用户','aim',false,false,false,3,55,0,false,902),('2023-03-23 11:16:12.147','2023-03-04 18:45:49.281',NULL,'view/app/report/dict/index.vue','report/dict','report/dict','','举报字典','aim',false,false,false,6,55,0,false,56),('2023-03-23 11:19:05.667','2023-03-23 11:19:05.667',NULL,'view/app/report/publish/index.vue','report/publish','report/publish','','社区举报','aim',false,false,false,6,55,0,false,909),('2023-03-28 16:54:41.891','2023-02-09 14:21:27.476',NULL,'view/app/index.vue','app','app','','基础信息','aim',false,false,false,19,0,0,false,31),('2023-03-18 15:05:43.875','2023-03-18 15:05:43.875',NULL,'view/app/users/index.vue','app/user','app/user','','用户管理','aim',false,false,false,1,31,0,false,905),('2023-03-18 15:06:02.265','2023-03-07 13:42:03.639',NULL,'view/app/feedback/index.vue','feedback','feedback','','意见反馈','aim',false,false,false,3,31,0,false,57),('2023-05-18 15:04:24.393','2023-05-18 15:04:24.393',NULL,'view/app/user/blocks/index.vue','user/blocks','user/blocks','','用户封禁','aim',false,false,false,4,31,0,false,930),('2023-07-20 17:15:03.633','2023-07-20 17:15:03.633',NULL,'view/app/weather/alarms/index.vue','weather/alarms','weather/alarms','','气象预警','warning',false,false,false,38,31,0,false,970),('2023-05-30 10:07:02.935','2023-05-30 10:07:02.935',NULL,'view/app/push/index.vue','push','push','','推送','aim',false,false,false,50,31,0,false,932),('2023-04-14 15:06:36.32','2023-04-14 15:06:36.32',NULL,'view/app/system/message/index.vue','system/messages','system/messages','','系统消息','aim',false,false,false,62,31,0,false,923),('2024-06-04 16:19:07.157','2024-06-04 16:19:07.157',NULL,'view/app/user/shares/index.vue','shares/index','shares/index','','用户分享','aim',false,false,false,101,31,0,false,2029),('2024-06-04 16:19:32.929','2024-06-04 16:19:32.929',NULL,'view/app/user/shares/clicks/index.vue','shares/clicks','shares/clicks','','分享点击','aim',false,false,false,103,31,0,false,2030),('2023-03-21 13:41:01.755','2023-03-21 13:40:44.588',NULL,'view/app/log/index.vue','user/log','user/log','','用户操作日志','aim',false,false,false,990,31,0,false,908),('2023-04-14 15:01:31.971','2023-04-14 15:01:18.41',NULL,'view/app/index.vue','app/basic','app/basic','','基础配置','aim',false,false,false,22,0,0,false,922),('2023-05-06 16:31:46.371','2023-05-06 16:29:12.748',NULL,'view/app/official/concatas/index.vue','official/concats','official/concats','','官方电话','aim',false,false,false,1,922,0,false,927),('2023-05-11 13:48:18.008','2023-05-11 13:48:18.008',NULL,'view/app/sensitiveWords/index.vue','app/sensitiveWords','app/sensitiveWords','','敏感词配置','aim',false,false,false,6,922,0,false,929),('2023-04-14 15:02:35.975','2023-02-09 14:22:07.595',NULL,'view/app/version/index.vue','version','version','','应用升级','aim',false,false,false,9,922,0,false,32),('2023-04-14 15:02:18.918','2023-03-14 10:31:37.131',NULL,'view/app/problem/index.vue','problem','problem','','常见问题','aim',false,false,false,19,922,0,false,903),('2023-04-14 15:01:49.996','2023-03-18 15:40:51.971',NULL,'view/app/manuals/index.vue','manual','manual','','规则说明','aim',false,false,false,20,922,0,false,906),('2023-04-14 15:02:05.539','2023-04-03 10:39:56.688',NULL,'view/app/task/serials/index.vue','task/serial','task/serial','','任务配置','aim',false,false,false,880,922,0,false,920),('2023-02-11 10:32:21.431','2023-01-24 09:32:22.008',NULL,'view/superAdmin/index.vue','admin','superAdmin','','超级管理员','user',false,false,false,23,0,0,false,3),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/superAdmin/authority/authority.vue','authority','authority','','角色管理','avatar',false,false,false,1,3,0,false,4),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/superAdmin/dictionary/sysDictionaryDetail.vue','dictionaryDetail/:id','dictionaryDetail','dictionary','字典详情-${id}','list',false,false,false,1,3,0,true,9),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/superAdmin/menu/menu.vue','menu','menu','','菜单管理','tickets',true,false,false,2,3,0,false,5),('2023-02-25 
13:46:44.291','2023-01-24 09:32:22.008',NULL,'view/superAdmin/api/api.vue','api','api','','接口管理','platform',true,false,false,3,3,0,false,6),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/superAdmin/user/user.vue','user','user','','用户管理
','coordinate',false,false,false,4,3,0,false,7),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/superAdmin/dictionary/sysDictionary.vue','dictionary','dictionary','','字典管理','notebook',false,false,false,5,3,0,false,8),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/superAdmin/operation/sysOperationRecord.vue','operation','operation','','操作历史','pie-chart',false,false,false,6,3,0,false,10),('2023-06-21 14:52:38.024','2023-01-24 14:19:27.766',NULL,'view/superAdmin/region/region.vue','system/region','system/region','','省市县设置','add-location',false,false,false,9,3,0,false,30),('2023-02-11 10:32:52.923','2023-01-24 09:32:22.008',NULL,'view/systemTools/index.vue','systemTools','systemTools','','系统工具','tools',false,false,false,25,0,0,false,16),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/systemTools/autoCode/index.vue','autoCodeEdit/:id','autoCodeEdit','','自动化代码-${id}','magic-stick',false,false,false,0,16,0,true,21),('2023-07-26 10:36:38.168','2023-07-26 10:36:38.168',NULL,'view/public/file/exports/index.vue','file/exports','file/exports','','我的文件夹','aim',false,false,false,0,16,0,false,973),('2024-06-05 17:27:28.706','2024-06-05 17:27:28.706',NULL,'view/public/file/generates/index.vue','generates/index','generates/index','','卡片生成','edit',false,false,false,2,16,0,false,2031),('2024-06-05 17:27:40.262','2023-01-24 09:32:22.008',NULL,'view/systemTools/autoPkg/autoPkg.vue','autoPkg','autoPkg','','自动化package','folder',false,false,false,6,16,0,false,22),('2023-07-26 
10:36:05.464','2023-01-24 09:32:22.008',NULL,'view/systemTools/autoCode/index.vue','autoCode','autoCode','','代码生成器','cpu',true,false,false,10,16,0,false,17),('2023-07-26 10:35:58.897','2023-01-24 09:32:22.008',NULL,'view/systemTools/autoCodeAdmin/index.vue','autoCodeAdmin','autoCodeAdmin','','自动化代码管理','magic-stick',false,false,false,11,16,0,false,20),('2023-07-26 10:35:54.933','2023-01-24 09:32:22.008',NULL,'view/systemTools/formCreate/index.vue','formCreate','formCreate','','表单生成器','magic-stick',true,false,false,12,16,0,false,18),('2023-07-26 10:35:50.665','2023-01-24 09:32:22.008',NULL,'view/systemTools/system/system.vue','system','system','','系统配置','operation',false,false,false,13,16,0,false,19),('2023-04-26 13:54:52.485','2023-01-24 09:32:22.008',NULL,'view/routerHolder.vue','plugin','plugin','','插件系统','cherry',false,false,false,26,0,0,true,25),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/systemTools/installPlugin/index.vue','installPlugin','installPlugin','','插件安装','box',false,false,false,1,25,0,false,27),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/systemTools/autoPlug/autoPlug.vue','autoPlug','autoPlug','','插件模板','folder',false,false,false,2,25,0,false,28),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'plugin/email/view/index.vue','plugin-email','plugin-email','','邮件插件','message',false,false,false,3,25,0,false,29),('2023-03-18 15:41:41.941','2023-01-24 09:32:22.008',NULL,'https://plugin.gin-vue-admin.com/','https://plugin.gin-vue-admin.com/','https://plugin.gin-vue-admin.com/','','插件市场','shop',false,false,false,89,25,0,false,26),('2023-07-04 18:37:16.123','2023-06-26 14:19:01.337',NULL,'view/public/system/index.vue','public/system','public/system','','企业','aim',false,false,false,33,0,0,false,953),('2023-06-26 16:35:07.399','2023-06-26 16:34:42.284',NULL,'view/public/system/clerks/index.vue','system/clerks','system/clerks','','员工管理','user',false,false,false,2,953,0,false,955),('2023-08-03 10:35:08.398','2023-08-03 10:35:08.398',NULL,'view/public/addresses/index.vue','public/addresses','public/addresses','','发货地址','add-location',false,false,false,6,953,0,false,978),('2023-06-26 16:35:50.676','2023-06-26 14:20:06.488',NULL,'view/public/system/companies/index.vue','system/companies','system/companies','','企业管理','school',false,false,false,6,953,0,false,954),('2023-05-04 16:12:04.62','2023-01-24 09:32:22.008',NULL,'view/example/index.vue','example','example','','示例文件','management',false,false,false,87,0,0,false,12),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/example/upload/upload.vue','upload','upload','','媒体库（上传下载）','upload',false,false,false,5,12,0,false,13),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/example/breakpoint/breakpoint.vue','breakpoint','breakpoint','','断点续传','upload-filled',false,false,false,6,12,0,false,14),('2023-01-24 09:32:22.008','2023-01-24 09:32:22.008',NULL,'view/example/customer/customer.vue','customer','customer','','客户列表（资源示例）','avatar',false,false,false,7,12,0,false,15),('2023-02-09 14:25:16.992','2023-01-24 09:32:22.008',NULL,'view/system/state.vue','state','state','','服务器状态','cloudy',false,false,false,98,0,0,false,24),('2023-06-29 18:25:28.778','2023-01-24 09:32:22.008',NULL,'view/person/person.vue','person','person','','个人信息','message',false,false,false,999,0,0,true,11) ON CONFLICT DO NOTHING RETURNING "id"

2024/06/07 14:25:48 D:/git/chemen-collect/server/service/system/sys_authority.go:199
[1.655ms] [rows:0] INSERT INTO "public"."sys_authority_menus" ("sys_authority_authority_id","sys_base_menu_id") VALUES (888,1),(888,2009),(888,2001),(888,41),(888,964),(888,2026),(888,945),(888,944),(888,2018),(888,979),(888,2019),(888,943),(888,946),(888,44),(888,36),(888,43),(888,35),(888,2002),(888,985),(888,2011),(888,2013),(888,2012),(888,2014),(888,2027),(888,2028),(888,2032),(888,2020),(888,2022),(888,2021),(888,2023),(888,2024),(888,2025),(888,981),(888,982),(888,983),(888,974),(888,2015),(888,2016),(888,2017),(888,37),(888,904),(888,928),(888,38),(888,967),(888,925),(888,968),(888,984),(888,969),(888,55),(888,902),(888,56),(888,909),(888,31),(888,905),(888,57),(888,930),(888,970),(888,932),(888,923),(888,2029),(888,2030),(888,908),(888,922),(888,927),(888,929),(888,32),(888,903),(888,906),(888,920),(888,3),(888,4),(888,9),(888,5),(888,6),(888,7),(888,8),(888,10),(888,30),(888,16),(888,21),(888,973),(888,2031),(888,22),(888,17),(888,20),(888,18),(888,19),(888,25),(888,27),(888,28),(888,29),(888,26),(888,953),(888,955),(888,978),(888,954),(888,12),(888,13),(888,14),(888,15),(888,24),(888,11) ON CONFLICT DO NOTHING

2024/06/07 14:25:48 D:/git/chemen-collect/server/service/system/sys_authority.go:199
[42.905ms] [rows:1] UPDATE "public"."sys_authorities" SET "updated_at"='2024-06-07 14:25:48.454' WHERE "authority_id" = 888       

2024/06/07 14:25:48 D:/git/chemen-collect/server/service/system/sys_authority.go:199
[2.278ms] [rows:0] DELETE FROM "public"."sys_authority_menus" WHERE "public"."sys_authority_menus"."sys_authority_authority_id" = 
888 AND "public"."sys_authority_menus"."sys_base_menu_id" NOT IN (1,2009,2001,41,964,2026,945,944,2018,979,2019,943,946,44,36,43,35,2002,985,2011,2013,2012,2014,2027,2028,2032,2020,2022,2021,2023,2024,2025,981,982,983,974,2015,2016,2017,37,904,928,38,967,925,968,984,969,55,902,56,909,31,905,57,930,970,932,923,2029,2030,908,922,927,929,32,903,906,920,3,4,9,5,6,7,8,10,30,16,21,973,2031,22,17,20,18,19,25,27,28,29,26,953,955,978,954,12,13,14,15,24,11)
[GIN] 2024/06/07 - 14:25:48 | 200 |     63.6326ms | 192.168.124.189 | POST     "/mnt/menu/addMenuAuthority"_
