### ISSUE TITLE
A question about db.Find()

### ISSUE THREAD

**Issue by LemonLzy** [go-gorm/gorm#4331]
## Describe
when i use db.Find() to get some records, the console shows the "record not found" for me.

## The document you expected this should be explained
It's my code:
```go
type User struct {
	gorm.Model
	Name string
	Age int64
}

func main() {
	...
	var user User
	db.Debug().Where("name = ?", "lzy").First(&user)
	fmt.Printf("user:%#v\n", user)
}
```

The console:
```shell
2021/04/28 20:14:40 main.go:57 record not found
[0.513ms] [rows:0] SELECT * FROM `users` WHERE name = 'lzy' AND `users`.`deleted_at` IS NULL AND `users`.`id` = 1 ORDER BY `users`.`id` LIMIT 1
```

## Expected answer
Why the condition of sql has `users.id` = 1?
where is it from?
i just expect:
```sql
SELECT * FROM `users` WHERE name = 'lzy' limit 1.
```

**Comment by yin528** [comment]
你这个问题 就是要看...这里你做了什么操作了，你是不是给user.id 赋值了

**Comment by bestgopher** [comment]
Maybe the `user.id` had no-zero value 1 before `First`.
Like this:
```
var user User
user.ID = 1
db.Debug().Where("name = ?", "lzy").First(&user)
```
