### ISSUE TITLE
memory leak with "FirstOrCreate"

### ISSUE THREAD

**Issue by aj3423** [go-gorm/gorm#4334]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/314

## Description

`.FirstOrCreate()` causes memory leak, after called 10000 times, the *pprof* shows there're about 50 heap leaks.
Same problem with functions `.First()` 

To reproduce:
1. Run `go test`
2. Open this URL in browser: http://localhost:3344/debug/pprof
3. Check the heap number, click it for the detail
4. There are many leaks  from *gorm.io/gorm.(DB).FirstOrCreate+0x147......

From the stacktrace, some leak points to *mattn/go-sqlite3/sqlite3.go*, but some points to code of *gorm*.

How to fix it? Thanks for the great library.

**Comment by jinzhu** [comment]
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/6843/117245803-fe892080-ae6d-11eb-8231-7c27894a1c22.png">
No leak, maybe caused by https://golang.org/doc/go1.16#runtime this change.
