### ISSUE TITLE
Foreign key and references clash

### ISSUE THREAD

**Issue by pielambr** [go-gorm/gorm#4339]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/315

## Description

The preload in the example on the 'Created' field fails in the last version of Gorm. It can be fixed in that version by using `references:CreatedBy;foreignKey:PK` as the tag, otherwise it will try to join on the `CreatedBy` field of Account instead of the `PK field.

This used to work in version 1.20.7. Is this supposed to be like this?

**Comment by jinzhu** [comment]
seems works with latest version.
