### ISSUE TITLE
SetColumn with batch insert regression

### ISSUE THREAD

**Issue by System-Glitch** [go-gorm/gorm#4340]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/316

## Description

d327926425afecbe084997ba195497107cd71a92 breaks `tx.SetColumn()` when using batch inserts, and always causes `invalid value, should be pointer to struct or slice`. The code submitted in the PR is working as expected with v1.20.8, but doesn't work with v1.20.9.

See `models.go:32` in my PR.

**Comment by astronaut1712** [comment]
I got the same error 😢

**Comment by System-Glitch** [comment]
Looks like it's working again with v1.21.11.
