### ISSUE TITLE
Canno retrieve tx data on join table model hook

### ISSUE THREAD

**Issue by gabriel376** [go-gorm/gorm#4344]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/317

## Description

I would like to add more columns to the JoinTables, such as CreatedAt and CreatedBy.
To do that, I am using `SetupJoinTable()` to create the JoinTable with a custom Model.
The columns values are set using hooks `BeforeCreate()` and `BeforeSave()`. For some values, I need to pass data via `DB.Set()` and retrieve it with `tx.Get()` inside the hook. This works of all cases, except for the JoinTable Model hooks.

What am I doing wrong?

**Comment by jinzhu** [comment]
Hello @gabriel376 

https://gorm.io/docs/many_to_many.html#Composite-Foreign-Keys Maybe you can use the composite foreign key, define multiple foreign keys between users and user_languages table.
