### ISSUE TITLE
Cannot update Model inside BeforeDelete

### ISSUE THREAD

**Issue by gabriel376** [go-gorm/gorm#4347]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/318

## Description

I want to make some modifications to the Model inside the `BeforeDelete` hook. For example, to set the value of column `DeletedBy` and keep the normal behavior of `gorm` to update the `DeletedAt` (soft delete). However, I can't find a way to do this. I tried many approaches and combinations and tried to copy some code from `SoftDeleteDeleteClause.ModifyStatement()`, but nothing worked for me. 

I expect `BeforeDelete`  to behave similar to how `BeforeCreate` or `BeforeUpdate` works:
```go
func (u *User) BeforeDelete(tx *gorm.DB) error {
    u.DeletedBy = "gabriel" // Model should be updated here for all records in this transaction
    return nil
}
```

**Comment by s-takehana** [comment]
There may be a better way.

```go
package main

import (
	"fmt"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type User struct {
	gorm.Model
	Name      string
	DeletedBy string
}

func (u *User) BeforeDelete(tx *gorm.DB) (err error) {
	curTime := tx.Statement.DB.NowFunc()
	deletedBy := "User0"

	tx.Statement.AddClause(clause.Update{})

	tx.Statement.AddClause(clause.Set{
		{Column: clause.Column{Name: "deleted_at"}, Value: curTime},
		{Column: clause.Column{Name: "deleted_by"}, Value: deletedBy},
	})

	tx.Statement.SetColumn("deleted_at", curTime)
	tx.Statement.SetColumn("deleted_by", deletedBy)

	tx.Statement.AddClause(clause.Where{Exprs: []clause.Expression{
		clause.Eq{Column: clause.PrimaryColumn, Value: u.ID},
	}})

	tx.Statement.Build(
		clause.Update{}.Name(),
		clause.Set{}.Name(),
		clause.Where{}.Name(),
	)

	return
}

func main() {
	dsn := "host=postgres user=postgres password=***** dbname=postgres port=5432"
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}

	db.AutoMigrate(&User{})

	user := User{Name: "User1"}

	db.Debug().Create(&user)

	db.Debug().Delete(&user)

	fmt.Printf("\n%+v\n", user)
}
```

```
2021/06/09 20:30:50 /workspace/main.go:54
[2.915ms] [rows:1] INSERT INTO "users" ("created_at","updated_at","deleted_at","name","deleted_by") VALUES ('2021-06-09 20:30:50.216','2021-06-09 20:30:50.216',NULL,'User1','') RETURNING "id"

2021/06/09 20:30:50 /workspace/main.go:56
[3.011ms] [rows:1] UPDATE "users" SET "deleted_at"='2021-06-09 20:30:50.219',"deleted_by"='User0' WHERE "users"."id" = 1

{Model:{ID:1 CreatedAt:2021-06-09 20:30:50.2166119 +0000 UTC UpdatedAt:2021-06-09 20:30:50.2166119 +0000 UTC DeletedAt:{Time:2021-06-09 20:30:50.2197581 +0000 UTC Valid:true}} Name:User1 DeletedBy:User0}
```

**Comment by KiddoV** [comment]
Solution https://github.com/go-gorm/gorm/issues/4347#issuecomment-858081913 above is just a work around, is there any plan to make it more like `BeforeCreate` or `BeforeUpdate` hook?

**Comment by chenlujjj** [comment]
Agree with @KiddoV , the work around is a bit complicated ..

**Comment by chenlujjj** [comment]
@jinzhu @s-takehana  can you reopen the issue ?

**Comment by chenlujjj** [comment]
The workaround seems not work with soft delete

**Comment by s-takehana** [comment]
There's another way to do it in #6558.
I do wish there was a `BeforeSoftDelete` hook to do it.

**Comment by s-takehana** [comment]
I've done some research and I think [this feature](https://github.com/go-gorm/soft_delete?tab=readme-ov-file#mixed-mode-with-delete-id-field) would be a good one to use.

go-gorm/soft_delete#18

**Comment by s-takehana** [comment]
nvm.
I don't think it can be used as `deleted_by`.

**Comment by ukclivecox** [comment]
I think this issue should be reopened as at least for me it was unexpected that you can't modify fields in BeforeDelete hook. At least the documentation should be updated to clarify this. The only solution for me with soft delete is to save before (soft) delete.
