### ISSUE TITLE
Using Hooks During Batch Update

### ISSUE THREAD

**Issue by sushinoya** [go-gorm/gorm#4349]
## Your Question

When I run a batch query such as `db.Create(&users)`, the `AfterSave` hook is called after every individual `User`'s creation.

## The document you expected this should be explained

https://gorm.io/docs/hooks.html

## Expected answer

I need a solution that would run the hook only once at the end of the transaction when all the users have been added.

**Comment by jinzhu** [comment]
Use callbacks, and write a wrapper for the batch creating func.

**Comment by sushinoya** [comment]
Callbacks also have the same issue of slowing down batch inserts to a point of unusability. I can write a wrapper for batch inserts but there are a lot of models and a lot of code will have to be duplicated. 

```golang
db = proxy.NewRequest(context.Background())
_ = db.Callback().Create().After("gorm:commit_or_rollback_transaction").
Register("update_last_updated_timestamp", updateLastUpdatedTimestamp)

func updateLastUpdatedTimestamp(tx *gorm.DB) {
	fmt.Println("Updating timestamp")
}
```
