### ISSUE TITLE
Will "PrepareStmt: true" create "Prepared statement" to avoid sql injection ?

### ISSUE THREAD

**Issue by kuchaguangjie** [go-gorm/gorm#4354]
When open connection, if I set `PrepareStmt: true,` does it means all sql executed by this connection (pool) later will be `Prepared statement` ?

**e.g**
```
    db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
        PrepareStmt: true,
    })
```
After reading https://gorm.io/docs/session.html#PrepareStmt , still not 100% sure about the behavior.
I ask this to confirm the behavior, so that my app will avoid sql injection, thanks.

**Comment by jinzhu** [comment]
It will avoid sql injection and increase performance.

**Comment by w1ndyz** [comment]
> It will avoid sql injection and increase performance.

if database like doris not support prepareStmt, what should i do?
