### ISSUE TITLE
[Bug] Migrator not recognizing data type change

### ISSUE THREAD

**Issue by sujit-baniya** [go-gorm/gorm#4371]
Initial Migration has following struct

```go
type ProviderRoute struct {
	*gorm.Model
	Test           int   `gorm:"test" json:"test" form:"test" query:"test"`
	Priority             int    `gorm:"priority" json:"priority" form:"priority" query:"priority"`
}
```

Then I changed the data type of `Test ` to `string` and tried to migrate again. The migrator this time is not updating the data type

**Comment by s-takehana** [comment]
Similar to #4308 .
Maybe GORM can't do it.

https://gorm.io/docs/migration.html#Auto-Migration
> It will change existing column’s type if its size, precision, nullable changed.

https://github.com/go-gorm/gorm/blob/a480bd85450d444d2526a309f2ecae07cac814c0/migrator/migrator.go#L371-L414

**Comment by yungsem** [comment]
I meet the same problem. Can it be solved?

**Comment by sujit-baniya** [comment]
It seems for reliable migrations, we can't use Gorm migrator.
