### ISSUE TITLE
Updation question for custom time field

### ISSUE THREAD

**Issue by wk30** [go-gorm/gorm#4373]
Hey, guys. I am using the custom time field, found some problems with the model defination `autoUpdateTime`. Here is my code. 

The pkgs version I'm using.
golang version: 1.16.3
gorm.io/gorm 1.21.9
gorm.io/driver/mysql v1.0.6
gorm.io/driver/sqlite v1.1.4

[https://play.golang.org/p/jXqL446v8yF](https://play.golang.org/p/jXqL446v8yF)

What I really need is the custom time string not the timestamp.

![image](https://user-images.githubusercontent.com/18651103/118104126-50511e00-b40d-11eb-83cb-f27d66cfa68d.png)

The data `id = 1` is created first then updated and the data is not ok for the updated_at field.
The data `id = 2` is just created.

When using sqlite not found error, but the data in table is not correct.
When using mysql error occured, eg:
`Error 1292: Incorrect datetime value: '1620889489' for column 'updated_at' at row 1`

It's strange beacuse the creation is ok, while the updation is bad.

**Comment by wk30** [comment]
I have another question, as my goal is to define a custom field, seems that it's not offically supported and I'm confused about the field (eg: `CuDateTime`) method with `Scan` and `Value`. The situation is that the creation always invoke `Scan` and `Value` method, while the updation invoke `Scan` and not always invoke `Value`. Is there anything I missed?

**Comment by KiddoV** [comment]
I still have the same error.
The fields `autoCreateTime` always giving the correct timestamp format, but the fields with `autoUpdateTime` give me the timestamp as number instead.
