### ISSUE TITLE
does gorm v2 not support sql tags?

### ISSUE THREAD

**Issue by duguying** [go-gorm/gorm#4376]
## Your Question

```go
MaxLocationNum       int    `json:"max_location_num" sql:"comment:'最多规则数';default:1800"`
```

the default value has no effect. but i change to `gorm` tag, it works.

```go
MaxLocationNum       int    `json:"max_location_num" gorm:"comment:'最多规则数';default:1800"`
```

## The document you expected this should be explained

i used gorm v2 with sqlite. go.mod list
```
gorm.io/driver/mysql v1.0.3
gorm.io/driver/sqlite v1.1.4
gorm.io/gorm v1.20.8
```

## Expected answer

is it that `sql` tags not support in gorm v2 ?

**Comment by jinzhu** [comment]
no, only support `gorm` tag.
