### ISSUE TITLE
拼接sql语句1=1不支持

### ISSUE THREAD

**Issue by duguying** [go-gorm/gorm#4377]
## Your Question

用的gorm v2，从v1升级过来的，拼接sql语句1=1报错，日志如下
```log
[0.036434] [rows:1] SELECT count(1) FROM `t_sparta_migrates` WHERE 1=1 AND `t_sparta_migrates`.`deleted_at` IS NULL
/root/go/src/ias/ias-admin/modules/db/sparta_migrate.go:115 no such column: 1=1
```

## The document you expected this should be explained

```go
	total64 := int64(0)
	list = []*dbmodels.SpartaMigrate{}

	where := "export_sparta_config like ? "
	params := []interface{}{fmt.Sprintf("%%%s%%", user)}
	if UserIsSuperAdmin(user) {
		where = "1=1"
		params = []interface{}{}
	}

	// count
	err = g.Db2.Model(&dbmodels.SpartaMigrate{}).Where(where, params...).Count(&total64).Error
	if err != nil {
		return 0, nil, errors.New(err)
	}

```

## Expected answer

麻烦看下是否sql解析有bug

**Comment by sam-mix** [comment]
that is ok with Mysql 5.7:
```sh
git clone https://github.com/sam-mix/playground.git where-true
cd $_
make up
make where-true
```

**Comment by duguying** [comment]
> that is ok with Mysql 5.7:
> 
> ```shell
> git clone https://github.com/sam-mix/playground.git where-true
> cd $_
> make up
> make where-true
> ```

用 true 也是一样报错`no such column: true`

**Comment by duguying** [comment]
这个where语句1=1或者true，什么时候能支持一下呢？ @jinzhu

**Comment by sam-mix** [comment]
> > that is ok with Mysql 5.7:
> > ```shell
> > git clone https://github.com/sam-mix/playground.git where-true
> > cd $_
> > make up
> > make where-true
> > ```
> 
> 用 true 也是一样报错`no such column: true`

gorm v1.21.10
mysql 5.7 
我这里测试是可以的
![image](https://user-images.githubusercontent.com/73999058/119174373-15995680-ba9b-11eb-9b07-a0ca2ee658f7.png)
你能给一个完整的demo吗， 让我们也好复现你说的问题

**Comment by duguying** [comment]
> > > that is ok with Mysql 5.7:
> > > ```shell
> > > git clone https://github.com/sam-mix/playground.git where-true
> > > cd $_
> > > make up
> > > make where-true
> > > ```
> > 
> > 
> > 用 true 也是一样报错`no such column: true`
> 
> gorm v1.21.10
> mysql 5.7
> 我这里测试是可以的
> ![image](https://user-images.githubusercontent.com/73999058/119174373-15995680-ba9b-11eb-9b07-a0ca2ee658f7.png)
> 你能给一个完整的demo吗， 让我们也好复现你说的问题

我这边是用的sqlite跑单元测试的时候报错了，测试代码片段在问题主干里有提供，就是where语句拼接

**Comment by sam-mix** [comment]
这是使用 sqlite , 除了 `1` = `1` 这种情， 一切正常
```
git clone https://github.com/sam-mix/playground.git sqlite-where-true
cd $_
make up
make sqlite
```

**Comment by duguying** [comment]
> 这是使用 sqlite , 除了
> 
> ```sql
> `1` = `1` 
> ```
> 
> 这种情， 一切正常
> 
> ```
> git clone https://github.com/sam-mix/playground.git sqlite-where-true
> cd $_
> make up
> make sqlite
> ```

知道原因了，是我list查询参数的问题，手误忘记展开params了，修正后正常了。多谢
![image](https://user-images.githubusercontent.com/3050360/119361718-8da38e80-bcde-11eb-94cc-18aa2930a001.png)
