### ISSUE TITLE
The problem of split table

### ISSUE THREAD

**Issue by golandscape** [go-gorm/gorm#4378]
## Your Question

The implementation of the **Tabler**`(func(u *User)TableName()string)` is called by an empty instance.
Because we have a large amount of data, if we need to take a field of the structure as the basis of dividing tables, then the current method is more difficult.

Like: 
```
func (u *User) TableName() string {
	return fmt.Sprintf("%v_%02d", "user", u.UserID%100)
}
```
But the `u.UserID` is empty

---
Now my temporary solution is
```
func (u*User) BeforeCreate(tx *gorm.DB) (err error) {
	tx.Statement.Table = u.TableName()
	return
}
func (u*User) BeforeSave(tx *gorm.DB) (err error) {
	tx.Statement.Table = u.TableName()
	return
}
...
...
```

## Expected answer

Can get userid or other simplified split table mode

**Comment by sam-mix** [comment]
给个实际例子

**Comment by golandscape** [comment]
> 给个实际例子

就是执行TableName的实例是个空值，已经说明清除了

**Comment by golandscape** [comment]
> 给个实际例子

就是执行TableName是个零值实例，已经说明清楚了

**Comment by jinzhu** [comment]
use Scopes to set table

```go
// 使用传入数据分表
func TableOfYear(user *User, year int) func(db *gorm.DB) *gorm.DB {
  return func(db *gorm.DB) *gorm.DB {
		tableName := user.TableName() + strconv.Itoa(year)
		return db.Table(tableName)
  }
}

DB.Scopes(TableOfYear(user, 2019)).Find(&users)
// SELECT * FROM users_2019;
```
