### ISSUE TITLE
使用DB.exec() 执行SQL语句失败

### ISSUE THREAD

**Issue by oneweek20169902** [go-gorm/gorm#4381]
传进exec方法的SQL语句
![image](https://user-images.githubusercontent.com/19389964/118402667-7a207400-b69d-11eb-80e3-a430f891653f.png)
exec 返回的 SQL语句
![image](https://user-images.githubusercontent.com/19389964/118402678-8ad0ea00-b69d-11eb-936b-e378eb445d31.png)
入参
![image](https://user-images.githubusercontent.com/19389964/118402682-94f2e880-b69d-11eb-9192-cb6c969f2dc0.png)

**Comment by sam-mix** [comment]
看了你的问题完全不知道你在说什么，就有些着急，让想帮助你的人不不知道怎么办。
