### ISSUE TITLE
Using DB.WithContext with Scopes causes unexpected result

### ISSUE THREAD

**Issue by zeeshen** [go-gorm/gorm#4383]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/328

## Description

If new DB instances created during the Scopes call(like what `DB.WithContext` does), all following codes executed after [`processor. Execute`](https://github.com/go-gorm/gorm/blob/master/callbacks.go#L77-L83) will be using a legacy DB instance.

Take `Count` for example:

https://github.com/go-gorm/gorm/blob/master/finisher_api.go#L431-L434

After ` tx.callbacks.Query().Execute(tx)`, the `tx.RowsAffected` will be read to cal count. If the db instances is assigned with a new value during the `Execute`, the `RowsAffected` here will always be zero. As a result, the count result will always be zero.

You can reproduce the example described with the playground code.

**Comment by jinzhu** [comment]
Fixed in https://github.com/go-gorm/gorm/commit/92c3ba9dccd65f41652baa4d51e4c82af5496eec thank you for the report.
