### ISSUE TITLE
Why does gorm attempt to update an artist instead of insert it?

### ISSUE THREAD

**Issue by ewollesen** [go-gorm/gorm#4390]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/329

## Description

I expect my test case to successfully perform an INSERT, because the `artist` instance has an `ID` of 0. What I observe is an UPDATE being performed, and failing due to a lack of WHERE clause.

I'm upgrading some code from v1.9.10 where this worked fine, but with v1.21.10 it fails.

Is there some configuration tweak I need to make?

**Comment by jinzhu** [comment]
double pointer of a value, use `err = tx.Save(artist).Error`

But Save is not recommend, use `Create`
