### ISSUE TITLE
无法通过Save方法讲model保存到数据库

### ISSUE THREAD

**Issue by lcl1024** [go-gorm/gorm#4391]
```go
type BlockInfo struct {
	NetworkId uint64 `gorm:"column:network_id;primaryKey"` // 主键
	BlockNum  uint64
	SourceUrl string
}

func (b *BlockInfo) TableName() string {
	return "t_listen_block_info"
}

func InsertBlockInfo(tx *gorm.DB, b *BlockInfo) error {
	err := tx.Model(&BlockInfo{}).Save(b).Error
	return err
}
```
我尝试通过Save方法讲一个完整的BlockInfo保存到数据库中，然后我得到了下面的报错
```sh
........: WHERE conditions required
```

**Comment by lcl1024** [comment]
将查询方法改成了
```go
err := tx.Save(b).Error
```
or
```go
err := tx.Model(&BlockInfo{}).Where("network_id").Save(b).Error
```
结果能够Save成功了

**Comment by lcl1024** [comment]
#  Playground Pull Request
https://github.com/go-gorm/playground/pull/330

**Comment by jinzhu** [comment]
When using with `Model` , the model has to have a primary key to save current data.

**Comment by lcl1024** [comment]
> When using with `Model` , the model has to have a primary key to save current data.

I knew and did so, look at the test cases, `user` has `id` when `create user` in line 14, then save failed. Why, i can't understand.
