### ISSUE TITLE
If the primary key is not a number the delete by PK fails silently with invalid error

### ISSUE THREAD

**Issue by huberts90** [go-gorm/gorm#4393]
## GORM Playground Link

[go-playground](https://github.com/go-gorm/playground/pull/331)

## Description

If the primary key is not a number the delete fails silently with invalid error:
> `DELETE FROM languages WHERE pl-PL`:
> `main_test.go:17: Failed, got error: no such column: pl`

That behaviour carries on dangerous of unpredictable actions.
## Expected value
Correct error if PK is not number

**Comment by jinzhu** [comment]
https://gorm.io/docs/query.html#Retrieving-objects-with-primary-key
