### ISSUE TITLE
where之类的条件, 可以支持多一个用于判断的参数吗

### ISSUE THREAD

**Issue by zohar-soul** [go-gorm/gorm#4395]
## Expected answer

```
db.table(logger)
  .where("1 = 1")
  .andIf(log_date > 0, "log_date = ?", log_date)
```
类似于这样

**Comment by duguying** [comment]
我觉得这个and条件自己手打更好

**Comment by zohar-soul** [comment]
> 我觉得这个and条件自己手打更好

@duguying 自己打也不是不行, 但是支持这种写法的orm还蛮多的

**Comment by smilexu** [comment]
it does support.   .where().where()  is condition1 AND condition2. You can also use .Or()

**Comment by almas1992** [comment]
自己可以用scope封装一下
