### ISSUE TITLE
many to many joinForeignKey auto formated

### ISSUE THREAD

**Issue by to2false** [go-gorm/gorm#4396]
## Your Question

Is there a way to limit `foreignKey `, `joinForeignKey` to auto camelcase?

## The document you expected this should be explained

I want to use associations many to many, I declare `joinForeignKey:xxxYYY` to overwrite key, it auto converted to `xxx_yyy`.
Due to historical reasons, there are different field formats in the database, eg`xxxYYY`, `xxx_yyy`, `xxxyyy`

## Expected answer

A way to let  `joinForeignKey:xxxYYY` keeps the statement as it is

**Comment by jinzhu** [comment]
https://gorm.io/docs/gorm_config.html#NamingStrategy
