### ISSUE TITLE
How to get the query statement

### ISSUE THREAD

**Issue by luqmansen** [go-gorm/gorm#4397]
## Your Question

`db.Statement.SQL.String()` and `db.Statement.Vars` is always empty, is there any way I could get the raw statement of my query,  I need to pass this query for my custom tracer

## The document you expected this should be explained

Somewhere around this docs [https://gorm.io/docs/logger.html](https://gorm.io/docs/logger.html)

## Expected answer

The example of custom logger implementation with tracer should be included on logger documentation

**Comment by jinzhu** [comment]
https://gorm.io/docs/sql_builder.html#ToSQL

**Comment by chumaumenze** [comment]
Use this.

```golang
drySession := &gorm.Session{
    SkipDefaultTransaction: true,
    DryRun: true,
}
stmt = db.Session(drySession).Create(&model).Statement
fmt.Printf("SQL: %s\nVars: %v\n", stmt.Statement.SQL.String(), stmt.Vars)
```
