### ISSUE TITLE
OnConflict + Create does not work with sqlite

### ISSUE THREAD

**Issue by semtexzv** [go-gorm/gorm#4398]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/333

## Description

When using OnConflict clause to preserve unique column constraint, the `Create` sets object primary keys to invalid values if these objects were only updated (not inserted). The inserted values have correct primary keys returned.

The expectation is that the Create method returns valid primary keys into all objects.  

## Usecase
This limitation blocks our usecase for inserting values with associations to deduplicated columns. Eg:

```sql
CREATE TABLE packages (id primary key not null, descr TEXT NOT NULL)
```
is modified into
```sql
CREATE TABLE packages (id primary key not null, descr_id INT NOT NULL REFERENCES text(id))
CREATE TABLE text (id primary key not null, text TEXT  NOT NULL UNIQUE)
```
and then the usecase is to use following model

```go
type Package struct {
    ID   int `gorm:"primarykey"`
    Text string
}
```
is modified to be:
```go
type Package struct {
    ID     int `gorm:"primarykey"`
    TextID int
    Text   Text
}

type Text struct {
    ID   int `gorm:"primarykey"`
    Text string
}
```

The expectation is that when running something like this:
```
var packages []Package
DB.Create(&packages)
```

Gorm would correctly save the `Text` association, update primary keys, and save modified `packages` with correct foreign key ID referencing the `text` table. However, since the nested `Create` operation returns wrong primary keys for the update rows in the `text` table, the outer `Create` operation does not correct foreign keys, and then fails with a foreign key error.

**Comment by jinzhu** [comment]
not fixable due to sqlite's limitation.
