### ISSUE TITLE
Why Find method does not return ErrorOnNotFound? 

### ISSUE THREAD

**Issue by xesai** [go-gorm/gorm#4400]
## Your Question

Why Find method does not return ErrorOnNotFound in finisher_api.go ?

## Expected answer

Need to add tx.Statement.RaiseErrorOnNotFound = true

**Comment by drlogout** [comment]
Thanks @xesai! 
I migrated from v1.9.16 to v1.21.11. 
With tx.Statement.RaiseErrorOnNotFound = true I could restore the original behaviour.

**Comment by drlogout** [comment]
I have to correct myself. With `tx.Statement.RaiseErrorOnNotFound = true` I also get ErrorOnNotFound if I call tx.Find() with a slice, which I would not expect. Here I would expect to get an empty slice.

```go
users := []models.User{}

tx.Find(users, "first_name = ?", name).Error // does return ErrorOnNotFound
```

With `tx.Statement.RaiseErrorOnNotFound = false` using tx.Find(users) and tx.First(user) works like I would expect.

```go
user := models.User{}

tx.First(user, "email = ?", ).Error 
```
