### ISSUE TITLE
Gorm: Too many connection

### ISSUE THREAD

**Issue by cesc1802** [go-gorm/gorm#4403]
## I faced with issue TOO MANY CONNECTION when use gorm v2?

I use lib as orm for my application, but now I cannot found functions 

```golang
// SetMaxIdleConns sets the maximum number of connections in the idle connection pool.
sqlDB.SetMaxIdleConns(10)

// SetMaxOpenConns sets the maximum number of open connections to the database.
sqlDB.SetMaxOpenConns(100)

// SetConnMaxLifetime sets the maximum amount of time a connection may be reused.
sqlDB.SetConnMaxLifetime(time.Hour)
```

## Expected answer

Can help me handle when I have an issue about TOO MANY CONNECTION

**Comment by ahKevinXy** [comment]
怎样关闭连接 ,有close 方法吗

**Comment by Girein** [comment]
https://gorm.io/docs/connecting_to_the_database.html#Connection-Pool

defer sqlDB.Close()
