### ISSUE TITLE
Order Using GBK perform not well in Gorm

### ISSUE THREAD

**Issue by janebt** [go-gorm/gorm#4404]
## Your Question

I want to order the column key "title" using GBK in MYSQL(v8.0.21), but I perform well in terminal / dataGrip, but it doesn't work in GORM(v1.20.5), i don't know why it doesn't work 

The command perform well is:  
`select * from Table order by convert(title using GBK)`

In gorm is:
`db.Exec("select * from Table order by convert(title using GBK)")`

**Comment by jack-yi** [comment]
@jinzhu  跟楼主问题类似， gorm版本(v1.9.16)，mysql(5.6) 直接报sql
`Error 1105: parse sql "SELECT * FROM `table_name`  ORDER BY convert(display_name using GBK) LIMIT 20 OFFSET 0" error`

`SELECT * FROM `Table`   ORDER BY convert(display_name using GBK) LIMIT 20 OFFSET 0`

**Comment by jinzhu** [comment]
order with sql expr https://gorm.io/docs/query#Order
