### ISSUE TITLE
dynamic create table name?

### ISSUE THREAD

**Issue by codingismyAll** [go-gorm/gorm#4409]
## Your Question
i use this function: db.Scopes(UserTable(&cm)).Create(&ConfigurationModel), but not success, the error is relation "usersddd" does not exist (SQLSTATE 42P01)

**Comment by ka1i** [comment]
you can change this code like this:
```
db.Scopes(UserTable(&cm)).AutoMigrate(&ConfigurationModel)
```
this way can be createtable,but in my way,i found some issue.

**Comment by jinzhu** [comment]
https://gorm.io/docs/scopes.html#Dynamically-Table
