### ISSUE TITLE
Password renewal implementation

### ISSUE THREAD

**Issue by Kantonov** [go-gorm/gorm#4414]
## Your Question
How to approach password renewal, IAM authentication?

The current approach for Postres:
Alter the dialector's `Initialize(db *gorm.DB) (err error)` where the `db.ConnPool` returned is through a custom function. This function returns a wrapper of the pgx and is a driver connector. Here's the relevant part the wrapper `Connect(ctx context.Context) (driver.Conn, error)` function, which is used to open new connections:
```Golang
func (config *IamAuthDbDriver) Connect(ctx context.Context) (driver.Conn, error) {
    // fetch a fresh token with IAM connection string, from AWS
    dsn, err := GetIAMConnString()
    // err check
    
    pgxDriver := &stdlib.Driver{}
    connector, err := pgxDriver.OpenConnector(dsn)
    // err check
    
    return connector.Connect(ctx)
}
```

With some soft tests, this worked as expected. However, when tested on a service with a high volume of SQL transactions, with three different databases, I am getting this error, at random time intervals (the exact statement name varies):
```
ERROR: prepared statement "lrupsc_17_0" does not exist (SQLSTATE 26000)
```
I am investigating this problem further, along with the option to `sql.register(MyIAMDriver)` and pass the name to the gorm dialector's config.

## The document you expected this should be explained
[official documents site](https://gorm.io)

## Expected answer
What to fix in the current approach to prevent missing prepared statements from occurring randomly, or suggestion of a different approach - register custom driver or other.

**Comment by cgetzen** [comment]
Hi @Kantonov, curious if you ever figured out what this error was.
