### ISSUE TITLE
多对多, 如何在中间关系表中加条件查询?

### ISSUE THREAD

**Issue by weidongbcn** [go-gorm/gorm#4420]
## Your Question

我有一个团队表,一个成员表, 一个团队成员关系表.
关系表中有个字段status用来确定成员是否还在.(我不知道这个字段是否可以用?)
现在我要查询某现有团队现有人员, 怎么查询?
我要查询团队拥有过的所有成员怎么查询?
当然纯 sql语句我会搞, 用gorm v2怎么做?
请大家指教....(这个中间表有必要存在吗?)

**Comment by socylx** [comment]
解决了吗，似乎没有解决方案？

**Comment by a631807682** [comment]
https://gorm.io/docs/many_to_many.html#Customize-JoinTable
https://github.com/go-gorm/gorm/blob/master/tests/joins_test.go#L270

**Comment by Ystars** [comment]
请问解决的了吗？

**Comment by socylx** [comment]
使用gorm gen生成的实例来进行查询

如何在使用Preload查询多对多的数据时，对中间表添加查询条件？
