### ISSUE TITLE
FullSaveAssociations always Trigger BeforeCreate Hooks

### ISSUE THREAD

**Issue by hellodit** [go-gorm/gorm#4426]
## Your Question
I have 2 models that connected to each other I also using BeforeCreate Hooks to perform hooks that fill `created_at` and `updated_at` column. my problem is when I performing an update using `gorm.Session{FullSaveAssociations: true}` as mentioned in Documentation here [FullSaveAssociations](https://gorm.io/docs/session.html#FullSaveAssociations) the `BeforeCreate` Hooks also executed. it breaks my `created_at` and `updated_at`. 

My question is how to perform  FullSaveAssociations on update in the relational table without executing  `BeforeCreate` hooks 
Here is a snippet of my code 

```
MembersOnline struct {
	ID         uint64    `gorm:"primaryKey column:id" json:"ID"`
	NickName   string    `json:"nick_name" gorm:"column:NickName"`
	Email      string    `json:"email" gorm:"column:Email"`
	MemberNo   string    `json:"member_no" gorm:"column:NoAnggota"`
	CreateDate time.Time `json:"create_date" gorm:"column:CreateDate"`
	UpdateDate time.Time `json:"update_date" gorm:"column:UpdateDate"`
	Member     Members   `gorm:"foreignKey:MemberNo;references:NoAnggota" json:"member,omitempty"`
}


Members struct {
	ID                 uint64                `json:"ID"`
	MemberNo           string                `gorm:"column:MemberNo;primaryKey" json:"member_no,omitempty"`
	FullName           string                `json:"full_name,omitempty" gorm:"column:Fullname"`
	Phone              string                `json:"phone,omitempty" gorm:"column:Phone; default:null"`
	CreateDate         time.Time             `json:"create_date" gorm:"column:CreateDate"`
	UpdateDate         time.Time             `json:"update_date" gorm:"column:UpdateDate"`
}

func (u *Members) BeforeCreate(tx *gorm.DB) (err error) {
	u.CreateDate = time.Now()
	u.UpdateDate = time.Now()
	return
}


##Update function 
DB.WithContext(ctx).Session(&gorm.Session{FullSaveAssociations: true}).Updates(memberOl)
```

**Comment by hellodit** [comment]
I just found solutions by adding conditional check-in if the variable with zero value or not

**Comment by doppl-neal** [comment]
I believe, the way GORM works is it always tries to insert before updating. If you use the.debug() command the database, you can see exactly what GORM is querying.  This got me at first as well.
