### ISSUE TITLE
Default value given as input to Order or Limit functions

### ISSUE THREAD

**Issue by KLIM8D** [go-gorm/gorm#4429]
## Describe the feature

Order and Limit should behave like gorm v1, where given an empty string or zero, it just ignores and return immediately. Now when the type's default value is given, invalid SQL is generated.

## Motivation

Easier for the user of the library and makes chaining functions possible, like it was in v1.

```
c := conn.Set("gorm:auto_preload", true).
	Where(params.FilterExp, params.FilterArgs...)

if params.Limit > 0 {
	c = c.Limit(params.Limit)
}

if params.Sort != "" {
	c = c.Order(params.Sort)
}

return c.First(out).Error
```

vs

		

```
return conn.Set("gorm:auto_preload", true).
    Where(params.FilterExp, params.FilterArgs...).
    Limit(params.Limit).
    Order(params.Sort).
    First(out).Error
```

**Comment by wfscheper** [comment]
My team is trying to add support for gorm.io/gorm to our internal libraries, and restoring the behavior of `DB.Order` from the original gorm API would be really appreciated. I'm willing to write the PR, since it should be relatively simple.
