### ISSUE TITLE
关闭慢查询报告

### ISSUE THREAD

**Issue by always-waiting** [go-gorm/gorm#4430]
## Your Question
查询数据库时，报告了慢查询。但是相同的sql在mysql中执行，速度很快。因此想要关闭这个功能。请问有什么方式吗？

## The document you expected this should be explained
![image](https://user-images.githubusercontent.com/8566918/120259281-3eed8a00-c2c6-11eb-950e-7193065c61a8.png)
上图时程序返回的结果，显示查询时间为3945.662ms

![image](https://user-images.githubusercontent.com/8566918/120259423-84aa5280-c2c6-11eb-8de5-27ff3fa393d6.png)
上图是在mysql中的查询结果，显示的时间为0.32秒

因此想要关闭这个功能。

## Expected answer

1. 这个3秒多的时间是如何计算的
2. 如何使得程序不报这种慢查询错误（最好不要使用提高SlowThreshold的方式）

**Comment by always-waiting** [comment]
@jinzhu 还请大神能帮忙解答一下，谢谢啦

**Comment by almas1992** [comment]
调整日志级别，仔细看一下文档
