### ISSUE TITLE
how to update  one column in many records without for loop?

### ISSUE THREAD

**Issue by xiongdi9456** [go-gorm/gorm#4441]
## Your Question
how to update  one column in many records without for loop?
Example: I have 10 records from ID 1 to 10 and a column named `sort` from 1 to 10, I want to update their sort values from '1 to 10' to ' 10 to 1'  without for loop, could you tell me what's the best solution? Thank you

如何不使用for循环来批量更新多条记录的同一个字段为不同值？

比如mysql 有10条记录， Id是1到10，有个sort字段的值也是1到10，我通过前端排序获得了新的序列，比如10~1,   如何不使用for来逐条执行Update而使用一条语句完成呢？谢谢

**Comment by huacnlee** [comment]
看起来是排序功能设计的问题。跟 Gorm 无关。

你试试 https://github.com/griffinqiu/go-nested-set
