### ISSUE TITLE
Scan sometimes logs an error but does not return it

### ISSUE THREAD

**Issue by kapvode** [go-gorm/gorm#4447]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/338

## Description

When we mistakenly pass an entire struct, which has a map as one of its fields, as the `Scan` destination, `Scan` logs an error, but does not return it.

```
[error] unsupported data type: &map[]
```

**Comment by kapvode** [comment]
A related issue is that the error is logged even when the logger is configured to be silent.

**Comment by jinzhu** [comment]
the error should be returned in latest version.

the parse struct error is logged with logger.Default to notice there are something wrong in your code which should not be ignored. (you can ignore the field with a `gorm:"-"` tag)
