### ISSUE TITLE
Preload and join with nested

### ISSUE THREAD

**Issue by wregis** [go-gorm/gorm#4463]
## Your Question

I have this association

    [A] 1-1 [B] 1-* [C]

I want all **A** with its **B** and every **C** for each **B** and tried with the following:

```go
result := db.WithContext(ctx).
    Joins("B").
    Preload("B.C").
    Take(&A)
```

The thing is GORM makes 3 queries (`A join B`, `B`and `C`), but B was already loaded. Is this somehow expected? 

## The document you expected this should be explained

https://gorm.io/docs/preload.html#nested_preloading

## Expected answer

How to avoid unecessary queries to database for already loaded data.

**Comment by ccakes** [comment]
Having a similar problem, would like to be able to eagerly fetch multi-layer nested objects without database round trips 👍

**Comment by wregis** [comment]
I wish I could better understand GORM sources, maybe I will find the time to do so in the future, for now I still would like to confirm this is not an intentional feature.

**Comment by jinzhu** [comment]
Just use nested Preload, not going to support this for Join

**Comment by NilsJPWerner** [comment]
Are you still against implementing this feature?

**Comment by jinzhu** [comment]
pull request is welcome
