### ISSUE TITLE
How to prevent creating a row that includes a value of soft-deleted foreign key ?

### ISSUE THREAD

**Issue by orionlu0916** [go-gorm/gorm#4470]
## Your Question

I have two tables with the following gorm model definitions:
```
 struct User type{
   gorm.Model
   RoleID  uint 
   Role Role `gorm:"foreignKey:RoleID;"`
}

 struct Role type{
   gorm.Model
   Name string
}
```
Gorm will allow me to create an User when assigning the RoleID with a soft deleted role_id
Is there an existing method in gorm can make this kind of  "foreign key constraint(with the soft deleted foreign data)" works?
or I must have to implement the related logic code by my own?

## The document you expected this should be explained

https://gorm.io/docs/belongs_to.html

## Expected answer

Wondering  if anyone has dealt with similar problems and the idea of solution

**Comment by mirusky** [comment]
I believe you need to implement the logic by yourself. Like check if role still valid before creating a user

**Comment by jinzhu** [comment]
use unique index
