### ISSUE TITLE
Is it possible to get the SQL generated by gorm somehow without using DryRun ?

### ISSUE THREAD

**Issue by eduardo-mior** [go-gorm/gorm#4475]
Is it possible to get SQL run by Gorm without using DryRun?
I would like to run the SQL, and if this SQL error I would like to record it in a LOG along with several other information. Is there any way I can retrieve this executed SQL?

**Comment by huacnlee** [comment]
Rewrite ConnPool and replace db.ConnPool, db.Statement.ConnPool.

Then, you can get SQL query in yours ConnPool implementation.

**Comment by eduardo-mior** [comment]
This seems to me to be very difficult.
Are there any examples of how to do this? Or some other way to do?
I would like something simple like:
```
sql := db.SQL 
```
or 
```
err := db.Error
errGorm := err.(gorm.CustomError)
sql := errGorm.SQL
```

**Comment by huacnlee** [comment]
How about DryRun

https://gorm.io/docs/session.html#DryRun

**Comment by eduardo-mior** [comment]
DryRun does not run SQL. I need to run SQL and if any error occurs then saving SQL wue caused the error.

**Comment by eduardo-mior** [comment]
Does anyone have any ideas?

**Comment by zfha** [comment]
mark

**Comment by huacnlee** [comment]
> DryRun does not run SQL. I need to run SQL and if any error occurs then saving SQL wue caused the error.

@eduardo-mior There is no completed run SQL at Gorm runtime, even in ConnPool implementation.

https://github.com/go-gorm/gorm/blob/v1.21.12/prepare_stmt.go#L83

```go
func (db *PreparedStmtDB) ExecContext(ctx context.Context, query string, args ...interface{}) (result sql.Result, err error) {
	// 👹 At this time query is: 
        // INSERT INTO "posts" ("user_id", "title", "id") VALUES ($1, $2, $3) RETURNING "id" 
}
```

**Comment by eduardo-mior** [comment]
In GormV1 I forked the project and simply added a field called SQL in Struct gorm.DB.
This SQL field has the last SQL executed by GORM. 


Worked perfectly.


In GormV2 I don't want to make a Fork as this project is active and is receiving a lot of updates, however it would be interesting if this functionality existed.
 
  
My Fork on GormV1 only added 7 lines of code. It's ridiculous. It is an extremely simple implementation. Just create a field called SQL inside the struct gorm.DB and fill this field before the SQL is executed.
  
  
I wonder if there's any reason the developers haven't implemented this.

**Comment by eduardo-mior** [comment]
> > DryRun does not run SQL. I need to run SQL and if any error occurs then saving SQL wue caused the error.
> 
> @eduardo-mior There is no completed run SQL at Gorm runtime, even in ConnPool implementation.
> 
> https://github.com/go-gorm/gorm/blob/v1.21.12/prepare_stmt.go#L83
> 
> ```go
> func (db *PreparedStmtDB) ExecContext(ctx context.Context, query string, args ...interface{}) (result sql.Result, err error) {
> 	// 👹 At this time query is: 
>         // INSERT INTO "posts" ("user_id", "title", "id") VALUES ($1, $2, $3) RETURNING "id" 
> }
> ```

@huacnlee I created a CustomLogger and managed to solve the problem. It wasn't easy. It was a gambiarra. I wish there was a better way to do this. My code got extremely dirty and duplicated.

**Comment by jinzhu** [comment]
https://gorm.io/docs/sql_builder.html#ToSQL
