### ISSUE TITLE
How to use two fields to union unique ??

### ISSUE THREAD

**Issue by DasyDong** [go-gorm/gorm#4481]
## Your Question
How to use two fields to union unique ??

## The document you expected this should be explained
Eg:
```

type Role struct {
    ID             string         `gorm:"id;primaryKey"`  
    Name           string          
    Alias          string               
}

```

## Expected answer

After inserting values (name : test , alias : test ) successful, if we insert same values (name : test , alias : test ) again,
the db should return  conflicted

The two fields name with alias should unique_together like Django Orm

**Comment by s-takehana** [comment]
Try this:

```go
type Role struct {
	ID    string `gorm:"id;primaryKey"`
	Name  string `gorm:"index:idx_name,unique"`
	Alias string `gorm:"index:idx_name,unique"`
}
```

https://gorm.io/docs/indexes.html

**Comment by DasyDong** [comment]
Cool Man !  @s-takehana 
i took mine by mistake this `gorm:"index:idx_name;unique"` , actually is `gorm:"index:idx_name,unique"` .
HaHa

**Comment by serious-snow** [comment]
thanks.You helped me a lot.
