### ISSUE TITLE
`Updates` method with `BeforeUpdate` hook

### ISSUE THREAD

**Issue by HuihuangZhang** [go-gorm/gorm#4486]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/345

## Description

https://github.com/go-gorm/gorm/blob/master/callbacks/update.go#L12
When calling `Updates` with `struct` parameter, `BeforeSave` hook would get `Model` parameter, but `Updates` parameter is expected.

**Comment by jinzhu** [comment]
this is the expected behaviour
