### ISSUE TITLE
DB.Omit(clause.Associations) causes the statement part of DB to not reset.

### ISSUE THREAD

**Issue by HlynurX** [go-gorm/gorm#4488]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/346

## Description

Good day,

We're in the middle of upgrading from Gorm v1 to Gorm v2 and we're facing issues with the statement struct in the Gorm not clearing itself at all. The same statement hangs until we use the following session method .Session(&gorm.Session{NewDB: true}). We've narrowed it down to the fact that we're omitting Associations due to not wanting to have associations change during create, save and delete functions 

The way we connect to the database is with the following code where we wrap the logger in order to add a few key things to the output.

```
nowFunc := func() time.Time {
	return time.Now().UTC()
}

newLogger := logger.New(&gormWriter{traceLog: log.NewCustomLevelTrace(log.NewSystemTrace(), log.DebugLevel)}, logger.Config{LogLevel: logger.Info})
db, err := gorm.Open(dialecter, &gorm.Config{
	NamingStrategy: schema.NamingStrategy{
		SingularTable: true,
	},
	SkipDefaultTransaction:   true,
	PrepareStmt:              false,
	Logger:                   newLogger,
	NowFunc:                  nowFunc,
	FullSaveAssociations:     false,
})

db = db.Omit(clause.Associations) // We've also tried using it without reassigning the db which resulted in the same error as not using it at all.
```

**What errors are we seeing?**

When using db = db.omit(Clause.Assocation):

We run some manual migrations to make sure that the database is looking correct, we then run through the db.AutoMigrate and then we run into the error. 

> err="Error 1072: Key column 'svm_id' doesn't exist in table" rows=0 sql="ALTER TABLE `migration` ADD CONSTRAINT `fk_data_lif_svm` FOREIGN KEY (`svm_id`) REFERENCES `svm`(`id`)"

The query above should be querying against the table Data_Lif but when we have Clause.Association enabled the statement of the DB object never changes from the initial Statement unless we run .Session(&gorm.Session{NewDB: true}) when querying.

When Clause.Association is not omitted everything runs smoothly until we try to create, save or delete something we get the following error:

> err="Error 1471: The target table mount_point_view of the INSERT is not insertable-into" rows=0 sql="INSERT INTO `mount_point_view` (`fqdn`,`ip_address`,`volume_id`) VALUES ('','172.31.42.198',738) ON DUPLICATE KEY UPDATE `volume_id`=VALUES(`volume_id`)"

The query above shows that due to association being enabled we're now trying to insert into a view table which it shouldn't be doing but does due to it being a member of the volume table as seen below.

```
type Volume struct {
	BaseModel
	DisplayName           string           `json:"displayName"`
	MountPoints           []MountPointView `json:"-"`
}

type MountPointView struct {
	FQDN string        `json:"FQDN" gorm:"column:fqdn"`
	IPAddress     string        `json:"ipAddress"`
	VolumeID      sql.NullInt64 `json:"-"`
}
```

Is there a better way to Omit the clause.Associations than the db.Omit?

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety
