### ISSUE TITLE
incorrect where clause generated for joined table if clause is provided in struct form

### ISSUE THREAD

**Issue by ekovacs** [go-gorm/gorm#4490]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/347

## Description

gorm v2 will incorrectly generate a `where` clause for joined tables when they are provided as a model struct. it will generate the where clause against the current table, instead of taking the model's type into account.

current workaround is to specify that `where` clause explicitly, in string form.

**Comment by jinzhu** [comment]
Join preloading like? https://gorm.io/docs/preload.html#Joins-Preloading
