### ISSUE TITLE
Is there a way to escape `?` in Gorm?

### ISSUE THREAD

**Issue by KolorowyAleksander** [go-gorm/gorm#4491]
## Your Question

Postgres uses the character `?` as an operator for [hstore](https://www.postgresql.org/docs/9.1/hstore.html). Unfortunately seems like when using a query with Gorm, e.g. `.Where(table.hstore_cloumn ? @key, sql.Named("key", "someValue"))` like so, Gorm seems to read the `?` even though named arguments are used, therefore rendering the query invalid. 
Is there maybe a workaround for this case?

## The document you expected this should be explained
Maybe in the docs under [conventions](https://gorm.io/docs/conventions.html) or in the [builder/named arguments](https://gorm.io/docs/sql_builder.html#Named-Argument) section.

## Expected answer
Either a way to escape the `?` when using `sql.Named` or another workaround. If there is none available, then just a no is fine.

If there is no possibility for this, and maybe improving `Gorm` to allow the possibility to use the `?` operator with `hstore` wouldn't be too complicated, I'm willing to do so, so any suggestions will be appreciated.
Cheers!

**Comment by florianhidayat** [comment]
@KolorowyAleksander sort of... just wrap it inside a gorm expression, e.g.:
`linksNotNullExpr := gorm.Expr("jsonb_path_query_array(jsonb_build_array(links), '$.values[*] ? (@ != null)')")`
then you can just insert that as a value parameter in your query.

**Comment by jinzhu** [comment]
refer https://gorm.io/docs/data_types.html#Clause-Expression
