### ISSUE TITLE
[feat] BeforeFind hook

### ISSUE THREAD

**Issue by benmccann** [go-gorm/gorm#4493]
## Describe the feature

There is an `AfterFind` hook: https://gorm.io/docs/hooks.html#Querying-an-object

It would be nice to have a `BeforeFind` hook as well

## Motivation

I would like to have a timer start in `BeforeFind` and end in `AfterFind` and create a total of how long it took all queries to run for instrumentation purposes.

## Related Issues

I saw this requested in https://github.com/go-gorm/gorm/issues/3935, but am not sure the response applies here. If I understood the response there correctly, it was being said that such a hook would not be useful since there is no data yet. However, for my use case, I do not need to access any data in the hook and so it would still be helpful to have such a hook.

**Comment by stephanebruckert** [comment]
That would be useful to measure the time the DB query takes

**Comment by jinzhu** [comment]
not going to support this by default, but you can write a plugin for it.
