### ISSUE TITLE
Naming strategy on-the-fly?

### ISSUE THREAD

**Issue by mirusky** [go-gorm/gorm#4510]
## Your Question

It's possible to change naming strategy on-the-fly / at runtime ?

## The document you expected this should be explained

GORM allow user to create a custom [NamingStrategy](https://gorm.io/docs/gorm_config.html#NamingStrategy), but seems it only is used when opening connection with database:

```go
db, err := gorm.Open(sqlite.Open("gorm.db"), &gorm.Config{
  NamingStrategy: schema.NamingStrategy{
    TablePrefix: "t_",   // table name prefix, table for `User` would be `t_users`
    SingularTable: true, // use singular table name, table for `User` would be `user` with this option enabled
    NameReplacer: strings.NewReplacer("CID", "Cid"), // use name replacer to change struct/field name before convert it to db name
  },
})
```

## Expected answer

A way to change naming strategy after open connection.

Maybe in session could pass a new config.

**Comment by eduardobcolombo** [comment]
Hi @mirusky 

It depends on what are you looking for and how is your architecture, but You can change the default table name by implementing the [Tabler interface](https://gorm.io/docs/conventions.html#TableName), for example:

```go 
type Tabler interface {
  TableName() string
}

// TableName overrides the table name used by User to `profiles`
func (User) TableName() string {
  return "profiles"
}
```

You can also temporarily specify a name, like:
```go 
// Create table `deleted_users` with struct User's fields
db.Table("deleted_users").AutoMigrate(&User{})
```

I hope it can help you.
Cheers

**Comment by mirusky** [comment]
Hello @eduardobcolombo about what you said

> [...] You can change the default table name by implementing the [Tabler interface](https://gorm.io/docs/conventions.html#TableName)

By convension the [TableName](https://gorm.io/docs/v2_release_note.html#Table-Name) will not allow changes, because it cache the table name, so it's not possible to change table at runtime anymore like in Gorm V1.

> You can also temporarily specify a name, like: 
> `db.Table("deleted_users").AutoMigrate(&User{})`

Sure, but it will not allow to use Relationships in the right way. 

I'm looking for a way to change the prefix of the table at runtime. I'm using postgres and I want to change the DB schema depending on biz rules

**Comment by jinzhu** [comment]
https://gorm.io/docs/scopes.html#Dynamically-Table
