### ISSUE TITLE
Proper snake-case for OAuth

### ISSUE THREAD

**Issue by viomckinney** [go-gorm/gorm#4512]
## Describe the feature

Currently, OAuth snake-cases to `o_auth`, e.g. `UserOAuthConnection` -> `user_o_auth_connection`. Instead, it would be nice to have it snake-case to `oauth`, e.g. `UserOAuthConnection` -> `user_oauth_connection`.

## Motivation

Users can fix this per-field and per-table, but considering some other values such as UUID are corrected in naming, I think it'd be helpful to add OAuth.

**Comment by mirusky** [comment]
@violetwtf maybe you could change [NamingStrategy](https://gorm.io/docs/gorm_config.html#NamingStrategy), and use a new set with the specified rules. Like in NameReplacer put a function to return a Replacer of OAuth to Oauth, since the default name strategy is snake_case.

**Comment by violetwtf** [comment]
> @violetwtf maybe you could change [NamingStrategy](https://gorm.io/docs/gorm_config.html#NamingStrategy), and use a new set with the specified rules. Like in NameReplacer put a function to return a Replacer of OAuth to Oauth, since the default name strategy is snake_case.
> 
> ```go
> db, err := gorm.Open(sqlite.Open("gorm.db"), &gorm.Config{
>   NamingStrategy: schema.NamingStrategy{
>     NameReplacer: strings.NewReplacer("OAuth", "Oauth"), // use name replacer to change struct/field name before convert it to db name
>   },
> })
> ```

Definitely a good temporary solution - will be using thanks :+1:. However, I still think it'd be helpful if it were implemented into Gorm by default. I don't know if this is out-of-scope or anything, so sorry if this is a silly request.

**Comment by mirusky-enube** [comment]
I don't think it's a good idea to put specific table conventions into gorm naming strategy. It's kind of weird, because table names is specific for each case.

**Comment by violetwtf** [comment]
> I don't think it's a good idea to put specific table conventions into gorm naming strategy. It's kind of weird, because table names is specific for each case.

I'm not aware of anyone who stylizes it as "o_auth." Additionally, Gorm already **does** put specific conventions in by default. For example, changing UUID from "u_u_i_d" to "uuid." I don't see how this is much different.

**Comment by viomckinney** [comment]
Still interested in this -- please don't mark it stale.

**Comment by jinzhu** [comment]
not going add the rule by default as it will introduce breaking changes.
