### ISSUE TITLE
Where() method fails with a trivial condition

### ISSUE THREAD

**Issue by zenovich** [go-gorm/gorm#4514]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/351

## Description

I expect ```DB.Table("users").Where("1").Scan(&result)``` to produce something like ```SELECT * FROM `users` WHERE 1```, but currently it produces ```SELECT * FROM `users` WHERE `users`. = "1"``` which is an incorrect statement failing with a syntax error.

**Comment by jinzhu** [comment]
write it like `	if err := DB.Table("users").Where(gorm.Expr("1")).Scan(&result).Error; err != nil {`
