### ISSUE TITLE
Add RollbackUnlessCommitted method to prevent leaking transactions

### ISSUE THREAD

**Issue by ultd** [go-gorm/gorm#4518]
## Describe the feature
Add a method to DB which can rollback a transaction only in the case it has not already been committed called `RollbackUnlessCommitted`

## Motivation
I think this is a very much needed feature in the case of this code:

```go
   tx := DB.Begin()

   err1 := someFunc1()
   if err1 != nil {
      tx.Rollback()
      return err1
   }

   err2 := someFunc2()
   if err2 != nil {
      tx.Rollback()
      return err2
   }

   err3 := someFunc3()
   if err3 != nil {
                           // <------- oops forgot to call tx.Rollback() here
      return err3
   }

   tx.Commit()
   return nil
```

It would be VERY helpful to have this method:

```go
   tx := DB.Begin()
   defer tx.RollbackUnlessComitted() // <---- Only need to call once

   err1 := someFunc1()
   if err1 != nil {
      return err1
   }

   err2 := someFunc2()
   if err2 != nil {
      return err2
   }

   err3 := someFunc3()
   if err3 != nil {
      return err3
   }

   tx.Commit()
   return nil
```

## Related Issues

This was previously mentioned in this [PR](https://github.com/go-gorm/gorm/pull/3876) but was rejected. I think the motivation behind it wasn't so clear & that's why it was rejected. This would be a very helpful feature and would prevent end users of Gorm from accidentally leaking transactions by forgetting to call `tx.Rollback()` (has happened to me several times).

**Comment by ultd** [comment]
Just wanted to understand why this was closed/rejected? Is it a personal preference that you don't think this method is needed? If so, that's fine just wondering.

**Comment by jinzhu** [comment]
won't add this, and this has been discussed many times already.
