### ISSUE TITLE
Pluck() fails on trying to fetch a nullable column

### ISSUE THREAD

**Issue by zenovich** [go-gorm/gorm#4533]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/355

## Description

When the table is empty, the following code
```
	var ids []*int64
	DB.Model(&User{}).Pluck("MAX(id)", &ids)
```
should return a result with only ONE value and the value should be NULL. No errors should be raised.
Instead, the call fails with an error "converting NULL to int64 is unsupported".

(I believe this bug should be fixed because fetching into pointers is a widely used approach for getting values of nullable columns.)

**Comment by zenovich** [comment]
The cause of the issue is here (callbacks.go):
```
		for stmt.ReflectValue.Kind() == reflect.Ptr {
			if stmt.ReflectValue.IsNil() && stmt.ReflectValue.CanAddr() {
				stmt.ReflectValue.Set(reflect.New(stmt.ReflectValue.Type().Elem()))
			}

			stmt.ReflectValue = stmt.ReflectValue.Elem()
		}
```
It should be 'if', not 'for'

**Comment by jinzhu** [comment]
not going to support this as little gain with big/bad changes.

For struct we already support this, in this case, maybe just use `sql.NullInt64`
