### ISSUE TITLE
how can i only create a new table, not update or add fields

### ISSUE THREAD

**Issue by HelloHaiGG** [go-gorm/gorm#4536]
## how can i only create a new table, not update or add fields

how can i only create a new table, not update or add fields

**Comment by HelloHaiGG** [comment]
@jinzhu

**Comment by eduardobcolombo** [comment]
Hi @HelloHaiGG 

I usually do it using [AutoMigrate](https://gorm.io/docs/migration.html)
You can just create your type like below: 
```go
type User struct {
	ID                  uint   `gorm:"primary_key"`
	FirstName           string `gorm:"size:255; index:idx_users_first_name_last_name_email"`
	LastName            string `gorm:"size:255; index:idx_users_first_name_last_name_email"`
	Email               string `gorm:"size:255; index:idx_users_first_name_last_name_email"`
	CreatedAt           time.Time  `gorm:"type:datetime;not null"`
	UpdatedAt           time.Time  `gorm:"type:datetime"`
	DeletedAt           *time.Time `gorm:"type:datetime"`
}
```

Then you can call the AutoMigrate right after you DB connection.

```go 
db.Set("gorm:table_options", "ENGINE=InnoDB AUTO_INCREMENT=1 CHARSET=utf8mb4").AutoMigrate(&User{})
``` 

You can also use some strategy like create a function DBMigrate and right there you can add all you migrations, like:

```go
func DBMigrate(db *gorm.DB) *gorm.DB {

	db.Set("gorm:table_options", "ENGINE=InnoDB AUTO_INCREMENT=1 CHARSET=utf8mb4").AutoMigrate(&User{})
	populateDBWithDefaultData(db)

	return db
}

func populateDBWithDefaultData(db *gorm.DB) {
	usr := User{}
	db.First(&usr, 1)
	if settings.ID < 1 {
		db.Exec("REPLACE INTO `users` (`id`,`first_name`,`last_name`,`email`,`created_at`,`updated_at`,`deleted_at`) VALUES (1,'Eduardo','Colombo','email@gorm.com','2021-07-16 16:54:02',NULL,NULL);")
	}
}

```

If you would like just to create a table you can use 
```go
 CreateTable(dst ...interface{}) error
``` 
or even 
```go
db.Set("gorm:table_options", "ENGINE=InnoDB").Migrator().CreateTable(&User{})
```

Which is provided by the Migrator interface. 
You can find more information about it in the lib [documentation](https://gorm.io/docs/migration.html).

I hope it can help you.

**Comment by HelloHaiGG** [comment]
Thank you! 
Through your answers, I understand how use AutoMigrate , but this does not meet my expectations. 
What I hope is that through configuration or special settings, AutoMigrate will only be created when the table does not exist, adding a field or updating a field type will not operate on the table structure. In this case, it should be carried out offline by R&D or operation and maintenance. @eduardobcolombo

**Comment by mirusky-enube** [comment]
@HelloHaiGG what about [Migrator](https://gorm.io/docs/migration.html#Migrator-Interface)`?


```go
type User struct {
	ID                  uint   `gorm:"primary_key"`
	FirstName           string `gorm:"size:255; index:idx_users_first_name_last_name_email"`
	LastName            string `gorm:"size:255; index:idx_users_first_name_last_name_email"`
	Email               string `gorm:"size:255; index:idx_users_first_name_last_name_email"`
	CreatedAt           time.Time  `gorm:"type:datetime;not null"`
	UpdatedAt           time.Time  `gorm:"type:datetime"`
	DeletedAt           *time.Time `gorm:"type:datetime"`
}

db.Migrator().CreateTable(&User{})

// SQL: CREATE TABLE users [...]
```
