### ISSUE TITLE
Foreign key name format seems different between gorm v1 and gorm v2 causing duplicate foreign keys

### ISSUE THREAD

**Issue by eoinmcq** [go-gorm/gorm#4537]
## Your Question

When moving from gormv1 to gorm v1 and using auto migration new foreign keys are created duplicating existing foreign keys. Gorm v1 and gorm v1 seem to have different naming standards.

Is there a way around this? Ideally the foreign keys I defined in gorm v1 I would expect to be retained and the only new foreign keys would be ones that were added.

## The document you expected this should be explained
Possibly here:

https://gorm.io/docs/associations.html#tags

## Expected answer
Ideally there would be a switch where we could use the old naming convention or even recognise it exists and migrate old foreign key names to new foreign key names and replace. If not a tag in the struct which would override the foreign key name would be ideal. I may be missing the obvious but it looks like I would need too drop all the foreign keys temporarily during migration?

**Comment by eoinmcq** [comment]
I should also add this is in Postgres.

gormv1 naming conventions ended in _foreign whereas gormv1 starts in fk_

**Comment by s-takehana** [comment]
How about `DisableForeignKeyConstraintWhenMigrating` option?

https://gorm.io/docs/migration.html#Auto-Migration
https://github.com/go-gorm/gorm/issues/4336#issuecomment-832842853

**Comment by jinzhu** [comment]
works as exptected.
