### ISSUE TITLE
Is there a way to manually specify the name of a foreign key in go-gorm?

### ISSUE THREAD

**Issue by duong2179** [go-gorm/gorm#4539]
## Your Question

I have two tables named `chapter_reward_resource_attribute_values` and `chapter_reward_resources` and a `belongs-to` foreign key constraint between the two

    type ChapterRewardResource struct { ... }
    type ChapterRewardResourceAttributeValue struct {
	  ChapterRewardResource   ChapterRewardResource
      ChapterRewardResourceID uint
      ...
    }

`go-gorm` was supposed to auto create a foreign key named `fk_chapter_reward_resource_attribute_values_chapter_reward_resource` but the name length exceeds 64 characters -- which is a hard limit of MySQL -- so the creation failed with error:

    2021/07/17 00:50:21 /data/github/test-comlibs/models/migrate.go:148 Error 1300: Invalid utf8mb4 character string: 'fkchapter_reward_resource_attribute_valueschapter_reward\xDE\...'
    [0.119ms] [rows:0] ALTER TABLE `chapter_reward_resource_attribute_values` ADD CONSTRAINT `fkchapter_reward_resource_attribute_valueschapter_reward<DE>^C<8B><92><9D>^XͿ` FOREIGN KEY (`chapter_reward_resource_id`) REFERENCES `chapter_reward_resources`(`id`)

I tried with shorter names for the tables and saw the success of the creation. However, I would like to keep the names unchanged for consistency. Is there a way that I can manually specify name for a foreign key constraint?

**Comment by sebastianbuechler** [comment]
Are you looking for this?

Use a tag for this where references let's you define the forgein key name: 

```
type User struct {
  gorm.Model
  Name       string     `gorm:"index"`
  CreditCard CreditCard `gorm:"foreignkey:UserName;references:name"`
}

type CreditCard struct {
  gorm.Model
  Number   string
  UserName string
}
```

https://gorm.io/docs/has_one.html#Override-References

**Comment by jinzhu** [comment]
the issue should be fixed on latest version.
