### ISSUE TITLE
count error

### ISSUE THREAD

**Issue by tfhappy** [go-gorm/gorm#4540]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/358
## Description
I am very puzzled about how to count the total number of records while paging query.
The code works in V1.
 ```
var result []User
db := DB.Where("age>?", 10)

// SELECT * FROM `users` WHERE age>10 AND `users`.`deleted_at` IS NULL LIMIT 10 OFFSET 10
db.Limit(10).Offset(10).Find(&result).
	
var total int64
// SELECT count(*) FROM `users` WHERE age>10 AND `users`.`deleted_at` IS NULL LIMIT 10 OFFSET 10
db.Count(&total) // how to count total user where age > 10 ?
```
Can anyone help me?

**Comment by mirusky** [comment]
Hello @tfhappy 

Looks like you are migrating from V1 to V2. In Gorm V2 we have the following [Method Chaining](https://gorm.io/docs/method_chaining.html) definition.

In gorm v1 everything could be chained, bringing some complications of performance and security. So in gorm v2 we have [Finishers](https://gorm.io/docs/method_chaining.html#Finisher-Method) that generate and execute SQL, also creates new `Statement`. 

So if you want to reuse the Where, Limit and Offset I strongly recomend you to use [Session Mode](https://gorm.io/docs/method_chaining.html#New-Session-Mode) the second example, like:


```go
tx := DB.Where("age>?", 10).Limit(10).Offset(10)
// `Where("age>?", 10)` is the first method call, it creates a new `Statement` and adds conditions
// `.Limit(10)` REUSES above `Statement`, and adds conditions to the `Statement`
// `.Offset(10)` REUSES above `Statement`, and adds conditions to the `Statement`

var users []User
tx.Find(&users)
// Since tx has a the Statement with Where, Limit, Offset whe just need to call Find.
// `Find(&users)` is a finisher, it executes registered Query Callbacks, generates and runs the following SQL:
// SELECT * FROM `users` WHERE age>10 LIMIT 10 OFFSET 10

var total int64
tx.Count(&total)
// Since tx has a the Statement with Where, Limit, Offset whe just need to call Count.
// `Count(&users)` is a finisher, it executes registered Query Callbacks, generates and runs the following SQL:
// SELECT Count(*) FROM `users` WHERE age>10 LIMIT 10 OFFSET 10

```

**Comment by tfhappy** [comment]
got it ,thanks!
