### ISSUE TITLE
Wrong Statement - Many Drivers

### ISSUE THREAD

**Issue by mirusky** [go-gorm/gorm#4541]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/359

## Description

Some drivers wrong statement when a infinite number is used as value in a float64. Driver specific error, for example postgres: "+Inf is not a number".

## My Case

I have a table with some fields that could be infinite numbers. Golang represent it by "+Inf". So when I try to save my struct I recive an error from database that reports "+Inf is not a number" postgres driver need to handle it.

Minimal Example:

```go

type Dumb struct{
    Field float64
}

infiniteFloat, _ := strconv.ParseFloat("Inf", 64)

db.Create(&Dumb{Field: infiniteFloat})

// INSERT INTO dumbs (field) VALUES (+Inf)
// +Inf is not a number
```

**Comment by jinzhu** [comment]
Maybe create an issue for those drivers?
