### ISSUE TITLE
多个count计数错误

### ISSUE THREAD

**Issue by pylist** [go-gorm/gorm#4542]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

```
tx.Where("status IN ?", []int{10, 20}).Count(&pendingOrders)
tx.Where("status = ?", 30).Count(&toPrinted)
tx.Where("status = ?", 40).Count(&printed)
tx.Where("status = ?", 50).Count(&delivery)
```
上面的我希望每个status的状态不受到干扰, 但是执行了`Count`方法之后, 他会把status的条件带到下一次的Count计数中
通过`Debug()`方法看到的sql语句
```
SELECT count(1) FROM `orders` WHERE `orders`.`deleted_at` IS NULL AND status IN (10,20)
SELECT count(1) FROM `orders` WHERE `orders`.`deleted_at` IS NULL AND status IN (10,20) AND status = 30
SELECT count(1) FROM `orders` WHERE `orders`.`deleted_at` IS NULL AND status IN (10,20) AND status = 30 AND status = 40
```

**Comment by mirusky** [comment]
@pylist could you put it in english to more people get engaged?

**Comment by pylist** [comment]
> @pylist could you put it in english to more people get engaged?
> 
> Also refer to [Method Chaining](https://gorm.io/docs/method_chaining.html), looks like the `Statement` is reused because you are using session mode [Session Mode](https://gorm.io/docs/method_chaining.html#New-Session-Mode)

Thank you. Your answer solved my question
