### ISSUE TITLE
HasTable undefined (type *gorm.DB has no field or method HasTable)

### ISSUE THREAD

**Issue by YuGuorong** [go-gorm/gorm#4545]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

import "github.com/jinzhu/gorm"
func (db *QdDB) CreateTbl(cls interface{}) {
	if !db.dbSQL.HasTable(cls) {
		db.dbSQL.CreateTable(cls)
	}
}
passed!

but improt "gorm.io/gorm" 
report:
c:\Users\\go\src\mtest\gortest.go:128:14: db.dbSQL.HasTable undefined (type *gorm.DB has no field or method HasTable)
c:\Users\\go\src\mtest\gortest.go:129:11: db.dbSQL.CreateTable undefined (type *gorm.DB has no field or method CreateTable)

WHY?

**Comment by ekovacs** [comment]
check the migrator: https://github.com/alpacahq/gobroker/blob/225f16e1facd307390217f5c09f8171536ca04ad/vendor/gorm.io/gorm/migrator.go#L55
