### ISSUE TITLE
How to Order on Nested/Associated tables

### ISSUE THREAD

**Issue by tab08j9** [go-gorm/gorm#4548]
## How to Order on Nested/Associated tables after Preload

Hello support team,

I'm attempting to orderBy on nested fields of a struct. For example 
```
type FooHolder struct {
	ID strfmt.UUID `json:"id" gorm:"primary_key"`

	OneFooID strfmt.UUID `json:"one_foo_id" 

	OneFoo Foo `json:"foo" gorm:"foreignKey:OneFooID"`

        TwoFooID strfmt.UUID `json:"two_foo_id" 

	TwoFoo Foo `json:"foo" gorm:"foreignKey:TwoFooID"`
         
        BarID strfmt.UUID `json:"bar" 

	Bar Bar `json:"bar" gorm:"foreignKey:BarID"`
 
}
```

```
type Foo struct {
	ID strfmt.UUID `json:"id" gorm:"primary_key"`

         NestedID strfmt.UUID `json:"nested_id"`

	Nested Nested `json:"nested" gorm:"foreignKey:nestedID"`

	OneFooHolder []FooHolder `json:"one_foo_holder" gorm:"foreignKey:OneFooID"`

        TwoFooHolder []FooHolder `json:"two_foo_holder" gorm:"foreignKey:TwoFooID"`
}
```

```
type Bar struct {
	ID strfmt.UUID `json:"id" gorm:"primary_key"`
}
```

```
type Nested struct {
	ID strfmt.UUID `json:"id" gorm:"primary_key"`
       
       Name string `json:"name" gorm:"unique;not null"`
}
```

How would you expect to list FooHolder and order on associated tables? In this example order on `Foo.Name`

I list in the below manner
```
var fooHolders []FooHolder

	err := vd.DB.Debug().
		Preload("OneFoo").
		Preload("OneFoo.Nested").
                Preload("TwoFoo").
		Preload("TwoFoo.Nested").
                Preload("Bar").
		Offset(offset).
		Limit(limit).
		Find(&fooHolders).Error
```

## The document you expected this should be explained

https://gorm.io/docs/query.html#Order
## Expected answer

I tried a couple different methods on the list above, but would usually get an error because the preloads would occur after the order by select call.  I would expect some versions of the below to work
```
     Order("one_foo.nested.name ASC")
```
```
     Order(`one_foo->'nested'->>`name' ASC`)
```

```
     Order(`"foo_holders"."one_foo"->'nested'->>`name' ASC`)
```

**Comment by mirusky** [comment]
I don't tested it but could you try to pass order in [Nested Preload](https://gorm.io/docs/preload.html#Nested-Preloading) method?

Something like:

```go
vd.DB.Debug().Preload("OneFoo", "order by", "column1")
```

**Comment by tab08j9** [comment]
Debugging the above it looks like it does the below. It orders the `nested` names. So if that was an array it would order those within `foo_holders` but not order the `foo_holder` return itself

```
SELECT * FROM "foo_holders"  WHERE "foo_holders"."deleted_at" IS NULL
SELECT * FROM "one_foo"  WHERE "one_foo"."deleted_at" IS NULL
SELECT * FROM "nested"  WHERE "nested"."deleted_at" IS NULL ORDER BY name DESC 
```

In the end I solved this by doing a`.Join("left join (select nested as nested_name, one_foo.id as one_foo_id from nested left join one_foo on one_foo.nested_id = nested.id) n ON (n.one_foo_id = one_foo_id).Order("n_name desc)...`

**Comment by tab08j9** [comment]
Wondering if gorm could be updated to do the above  without the join and just `.Order(OneFoo.Nested.name ASC)` or something of that nature
