### ISSUE TITLE
For `time.Time` values, is the timezone information passed onto the database query?

### ISSUE THREAD

**Issue by philoj** [go-gorm/gorm#4552]
## Your Question
The `time.Time` values are not passing the timezone information onto the postgres db query.

When the go environment is running in a local timezone, say `Asia/Kolkata` and the postgres database is in `UTC`, the time.Time values from a `time.Now().UTC()` call get interpreted by postgres as time in local timezone of the connected client. This results in the final stored value being incorrect. I am posting this as a question but believe it might be a bug.

## The document you expected this should be explained

https://gorm.io/docs/conventions.html#Timestamp-Tracking

## Expected answer

I would like to confirm if this is indeed a bug or is there something else I'm missing.

**Comment by jinzhu** [comment]
yes.
