### ISSUE TITLE
BeforeCreate is called even if we won't create the object

### ISSUE THREAD

**Issue by GYovchev** [go-gorm/gorm#4553]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/363

## Description

BeforeCreate is called even if we won't create an object. 
I have an embedded struct that is responsible for injecting a new UUID, every time a new object is created. When I create the object and then append it to some other object, Gorm is calling `BeforeCreate` for the already created object. That mutates my passed struct and the UUID property now differs from the one in the DB. That sounds like a bug to me since I expect my structs to be the same as their values in the DB. One solution would be to make Gorm run queries with `RETURNING` and then update the passed struct with the received column values.

**Comment by jinzhu** [comment]
this works as expected, you should check the uuid before set its value. this is caused by when creating the second user, it will try to create its associations.
