### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by devdammit** [go-gorm/gorm#4557]
## Describe the feature

Adding a dark theme with the ability to switch to a light one. By default, the selected system theme is expected

## Motivation

I, like many other programmers, use a dark theme in development and surfing. I think that many people will be grateful to read the documentation in a convenient environment for them

**Comment by devdammit** [comment]
I can help with this if there is any help with the design or other help :)

**Comment by s-takehana** [comment]
👍 
GORM official site repository is
https://github.com/go-gorm/gorm.io

**Comment by devdammit** [comment]
@s-takehana, I close the issue here and open it in the correct repository [#issue](https://github.com/go-gorm/gorm.io/issues/441)
