### ISSUE TITLE
How can I count groups?

### ISSUE THREAD

**Issue by ngau66** [go-gorm/gorm#4560]
## Your Question
I just wanna exec a SQL like "select count(*) from (select count(*) from students group by class)". The only way I found is as follows:
```golang
db.Table("student").Group("class").Find(&rs)
len(rs)
```
The quantity of rs can be enormous, so I do not want to list them all.
Are there any way else to count the groups?

**Comment by douchunrong** [comment]
try this:

dbResult := db.Table("student").Group("class").Find(&rs)
count := dbResult.RowsAffected

**Comment by ngau66** [comment]
> try this:
> 
> dbResult := db.Table("student").Group("class").Find(&rs)
> count := dbResult.RowsAffected

It will take a lot of time to query all record.
I figure it out that `distinct` is a better way.
```golang
db.Distinct('class').Count(&totalCount)
```

**Comment by LebronKodan** [comment]
Actually, the [docs](https://gorm.io/docs/advanced_query.html#Count) provide a way to count with group:
```
users := []User{
  {Name: "name1"},
  {Name: "name2"},
  {Name: "name3"},
  {Name: "name3"},
}

db.Model(&User{}).Group("name").Count(&count)
count // => 3
```
but in practice, there is a bug when all data in 1 group:
```
users := []User{
  {Name: "name1"},
  {Name: "name1"},
  {Name: "name1"},
  {Name: "name1"},
}

db.Model(&User{}).Group("name").Count(&count)
```
count will be 4 instead of 1.

**Comment by gatspy** [comment]
Count method when rowsAffected equals 1, use count(1) value.

```go
tx.Statement.Dest = count
tx.callbacks.Query().Execute(tx)
if tx.RowsAffected != 1 {
    *count = tx.RowsAffected
}
````

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/pull/4885
