### ISSUE TITLE
in orm parent and children is same type, how to use gorm preload? and  how to declaring model?

### ISSUE THREAD

**Issue by dybxin** [go-gorm/gorm#4567]
## Your Question

in orm parent and children is same type, how to use gorm preload? and  how to declaring model?

i declaring model likely the following, is correct? and in query how to preload Children?
type Authority struct {
        ID  uint
	CreatedAt       time.Time      
	UpdatedAt       time.Time    
	DeletedAt       *time.Time     `sql:"index"`
	Name   string         `json:"name"`
	ParentID        string         `json:"parent_id"` 
	Children        []Authority `json:"children" gorm:"-"`
}

## Expected answer

i expected correct declaring model and query correct.

**Comment by jinzhu** [comment]
refer Self-Referential 

https://gorm.io/docs/has_one.html#Self-Referential-Has-One
