### ISSUE TITLE
MySQL doesn't return ID field sometimes

### ISSUE THREAD

**Issue by osamaadam** [go-gorm/gorm#4569]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/364

## Description
Trying to create the same record twice within the same session leads to _MySQL_ not returning the updated ID after updating the second time. This runs fine in _Postgres_.

### Expected output
At the end of the second loop iteration I expect _product.ID_ to be the same as the ID from the first iteration.
### Actual output
The product in the second iteration has an ID of 0, meaning the result wasn't returned from the database since an ID of 0 isn't possible in _MySQL_.

**Comment by jinzhu** [comment]
this works as expected as the MySQL server doesn't return the value, so GORM can't help on that ;(
