### ISSUE TITLE
How to get LastInsertId when Create with map?

### ISSUE THREAD

**Issue by greensea** [go-gorm/gorm#4573]
## Your Question

The docs says now it is able to Create() from map

```
db.Model(&User{}).Create(map[string]interface{}{"Name": "jinzhu", "Age": 18})
```

But how can I get LastInsertId?
I try put an id key in the map, but after created, the id is still nil. So how can I get LastInsertId?

I know I can use User{} model to insert data and get LastInsertId, but there is some reason that I have to insert with a map, and get the LastInsertedId.

## The document you expected this should be explained

Add an example of getting LastInsertId after create with map.

## Expected answer

Get LastInsertId after Create() with map

**Comment by yangwawa0323** [comment]
When you create the `User` struct embedded the `gorm.Model`
```go
 type User struct{
   gorm.Model
   Name string
   Age int
}
```
You would got a primary key `id` by default. After the new user is committed by gorm, the user has been injected with `id`, `create_at`, `update_at` and `delete_at` attributes, So. You can change the code as following:
```go
   user := &User{"Name": "jinzhu", "Age": 18}
  db.Create(user)
  fmt.Printf("User id: %s", user.id)
```
