### ISSUE TITLE
Update associations

### ISSUE THREAD

**Issue by shanehughes1990** [go-gorm/gorm#4575]
## Your Question

I have read the docs through and through been through some issues, I for the life of me cannot get gorm to cooperate when updating an association table. 

```
db.Model(&models.Agency).Where("name =? ", input.name).Updates(&model)
```

Is what I am told according to docs to auto magically update the associations if model has information regarding that table. Along with FullSaveAssociations true. But whenever I attempt to do so it only updates the agency table Not the relative address table that is part of the model. The only way I was able to get it to update was by doing this

```
db.Model(&models.Agency).Assotiations("Address").Append(&model.Address)
```

Apologies if it's a little off I am on mobile, but there has to be a better way without explicitly forcing an append? According to the docs anyway, from what I make out of it.

**Comment by mathieuHa** [comment]
I encountered the same issue, and haven't been able to find a workaround.
