### ISSUE TITLE
prevent SQL injection with Order, support ? syntax

### ISSUE THREAD

**Issue by finnigantime** [go-gorm/gorm#4579]
## Describe the feature

prevent SQL injection with Order, support ? syntax.

Expected: `db = db.Order("? ASC", *orderBy)` works, supports the `?` wildcard character and additional args. Sanitizes the arg values.
Actual: gives "too many arguments" error

## Motivation

See https://github.com/go-gorm/gorm/issues/997. This was never implemented for `Order` AFAICT.

Also not sure if there's a good workaround for lack of this support? I don't want to write my own sanitizer method.

## Related Issues

https://github.com/go-gorm/gorm/issues/997

**Comment by xwjdsh** [comment]
I found this example in the document,
```
db.Clauses(clause.OrderBy{
  Expression: clause.Expr{SQL: "FIELD(id,?)", Vars: []interface{}{[]int{1, 2, 3}}, WithoutParentheses: true},
}).Find(&User{})
// SELECT * FROM users ORDER BY FIELD(id,1,2,3)
```

**Comment by finnigantime** [comment]
Hi @xwjdsh , that makes sense and I saw that as well, but I want to be able to use the much simpler syntax `db.Order("? ASC", *orderBy)` and not have to build up a clause that way. This simpler syntax is more approachable for me and my team. This syntax is supported for `db.Where` but not `db.Order`.

**Comment by jinzhu** [comment]
MySQL doesn't support pass order as params, so we need to make the user clearly know that, or it might cause SQL injection
