### ISSUE TITLE
为gorm.Model基础模型ID字段添加json标签，方便模型参与数据的json序列化

### ISSUE THREAD

**Issue by li1234yun** [go-gorm/gorm#4580]
## Describe the feature
很多时候我们需要将序列化的模型数据返回给前端，而前端很多情况下json字段名是帕斯卡类型命名的，还有protobuf字段也是帕斯卡类型命名，为了直接可以使用模型进行序列化返回，建议添加ID字段的json标签。

```golang
type Model struct {
	ID        uint `gorm:"primarykey" json:"id,omitempty"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt DeletedAt `gorm:"index"`
}
```

## Motivation
便于模型直接参与数据json序列化

**Comment by almas1992** [comment]
这个可以自行重新Model结构体实现，一般不会直接把model转成JSON返回前端，都进行一层转换的，根据需求场景做一些字段过滤，加工这类的。

**Comment by lazy2b** [comment]
type OrmModel struct {
	gorm.Model `json:"-"`
	ID        uint           `gorm:"primarykey" json:"id"`
}
