### ISSUE TITLE
why use “for” here

### ISSUE THREAD

**Issue by difficultwork** [go-gorm/gorm#4589]
## Your Question

File：gorm/schema/schema.go
Line: 81
Code: for modelType.Kind() == reflect.Slice || modelType.Kind() == reflect.Array || modelType.Kind() == reflect.Ptr { 

## Expected answer

there is no loop here, why use "for" instead of "if"?

thx for  explaining

**Comment by Hellysonrp** [comment]
AFAIK this is to prevent silly mistakes like passing a pointer to a pointer to a struct i.e. imagine you have an variable `user` with the value `&User{}` (a point to a `User` struct), you might execute something like `tx.Create(&user)` without worrying about `user` already being a pointer or not.

**Comment by difficultwork** [comment]
> AFAIK this is to prevent silly mistakes like passing a pointer to a pointer to a struct i.e. imagine you have an variable `user` with the value `&User{}` (a point to a `User` struct), you might execute something like `tx.Create(&user)` without worrying about `user` already being a pointer or not.

thank u very much, explained very clearly!
