### ISSUE TITLE
如何设置ID自增的起始位

### ISSUE THREAD

**Issue by ggdream** [go-gorm/gorm#4593]
## Expected answer

请问如何设置ID自增的起始位？

**Comment by almas1992** [comment]
ID自增的起始位不应该数DB中配的麽？gorm都是插入数据后获取生成的自增ID，批量插入时也是获取第一条数据ID再根据步长计算其他项的ID。

**Comment by ggdream** [comment]
> ID自增的起始位不应该数DB中配的麽？gorm都是插入数据后获取生成的自增ID，批量插入时也是获取第一条数据ID再根据步长计算其他项的ID。

谢谢你的答疑。不过我的本意是利用gorm的自动迁移创建不存在的表，gorm不存在相关的hooks吗？我查阅了文档，并没有发现相关的介绍。
如果想达到我想要的效果，只能在连接数据库后再调用`db.Exec`修改ID起始值了吗？

**Comment by almas1992** [comment]
> > ID自增的起始位不应该数DB中配的麽？gorm都是插入数据后获取生成的自增ID，批量插入时也是获取第一条数据ID再根据步长计算其他项的ID。
> 
> 谢谢你的答疑。不过我的本意是利用gorm的自动迁移创建不存在的表，gorm不存在相关的hooks吗？我查阅了文档，并没有发现相关的介绍。
> 如果想达到我想要的效果，只能在连接数据库后再调用`db.Exec`修改ID起始值了吗？

不好意思哈，现在才明白你的意思。
可以通过添加table_options实现，比如：
```golang
db.Set("gorm:table_options", "AUTO_INCREMENT=100")
```

**Comment by ggdream** [comment]
> > > ID自增的起始位不应该数DB中配的麽？gorm都是插入数据后获取生成的自增ID，批量插入时也是获取第一条数据ID再根据步长计算其他项的ID。
> > 
> > 
> > 谢谢你的答疑。不过我的本意是利用gorm的自动迁移创建不存在的表，gorm不存在相关的hooks吗？我查阅了文档，并没有发现相关的介绍。
> > 如果想达到我想要的效果，只能在连接数据库后再调用`db.Exec`修改ID起始值了吗？
> 
> 不好意思哈，现在才明白你的意思。
> 可以通过添加table_options实现，比如：
> 
> ```go
> db.Set("gorm:table_options", "AUTO_INCREMENT=100")
> ```

没有没有，是我没描述清楚想法
谢谢啦，那我就关掉这个啦

**Comment by stairclimber** [comment]
> > > > ID自增的起始位不应该数DB中配的麽？gorm都是插入数据后获取生成的自增ID，批量插入时也是获取第一条数据ID再根据步长计算其他项的ID。
> > > 
> > > 
> > > 谢谢你的答疑。不过我的本意是利用gorm的自动迁移创建不存在的表，gorm不存在相关的hooks吗？我查阅了文档，并没有发现相关的介绍。
> > > 如果想达到我想要的效果，只能在连接数据库后再调用`db.Exec`修改ID起始值了吗？
> > 
> > 
> > 不好意思哈，现在才明白你的意思。
> > 可以通过添加table_options实现，比如：
> > ```go
> > db.Set("gorm:table_options", "AUTO_INCREMENT=100")
> > ```
> 
> 没有没有，是我没描述清楚想法 谢谢啦，那我就关掉这个啦

可以给某个表单独设置这个属性吗？
