### ISSUE TITLE
relation ship

### ISSUE THREAD

**Issue by LibenHailu** [go-gorm/gorm#4599]
## Your Question

	Receiver uint            `gorm:"not null",json:"receiver"`
	Sender   uint            `gorm:"not null",json:"sender"`
	User     User            `gorm:"foreignKey:Receiver,Sender"

my model loos like this  and sender and reciver refers to user model when i migrate it throughs an error how do i solve that

**Comment by Urento** [comment]
could you show me the error and the other structs? And the Steps to reproduce it.
