### ISSUE TITLE
Feature Request: BIGINT support

### ISSUE THREAD

**Issue by mohamedmansour** [go-gorm/gorm#4600]
## Describe the feature

Would love to see BIGINT support for SQLite.

## Motivation

When dealing with ethereum, cryptocurrencies projects, we need large numbers, and sqlite supports BIGINT with native support. It can do aggregation, selections, conversions. 

BIGINT maps to *big.Int 

## Related Issues

#1844

**Comment by YamiOdymel** [comment]
Since the problem was not solved, use [github.com/shopspring/decimal](github.com/shopspring/decimal) might be one of the solution.

Change the `*big.Int` to `decimal.Decimal` and it will be parsed as `LONGTEXT` in Gorm, to use it as a `*big.Int`, simply call `.BigInt()` of the `Decimal` value.

```go
type MyWallet struct {
    Balance decimal.Decimal // Gorm supported, hurray! 
}

func Check() {
    var wallet MyWallet
    fmt.Println(wallet.BigInt())
}
```

**Comment by jinzhu** [comment]
github.com/shopspring/decimal is perfered
