### ISSUE TITLE
Parameter placeholder conflict   参数占位符冲突

### ISSUE THREAD

**Issue by piyongcai** [go-gorm/gorm#4610]
# GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

在postgresql jsonb查询中，问好（？）是一个查询表达式，如下：
in postgresql jsonb query，question mark (?)  is Expression symbol。eg：

```sql
 select * from asset_place where true  and jsonb_path_exists(attributes, '$[*].BizID ? (@ == $id)', '{"id":1}') and (pinyin like @place or code like @place or name like @place) and status=@status
```

第一个问号（？）就是查询表达式
the first char ? is express .

这个问号会被解析为参数。
This question mark (?) is resolved to parameters.

即使我使用命名参数，使用map对象来设置参数，第一个问号（?）都会被解析为参数。

Even if I use naming parameters and the map object to set the parameters, the first question mark (?) All are resolved to parameters.

**Comment by piyongcai** [comment]
这个问题，可以优先安排吗？ @jinzhu 
在json使用中，有很多的问题。

除开问号（?）的问题外，还有其他符号，如  : * @ 等符号

**Comment by drakkan** [comment]
as workaround I used I used `@>` instead of `?`, a way to escape the question mark would be useful, thank you

**Comment by jinzhu** [comment]
https://gorm.io/docs/data_types.html#Clause-Expression
