### ISSUE TITLE
Where condition Map Security

### ISSUE THREAD

**Issue by pnshiralkar** [go-gorm/gorm#4611]
## Is SQL injection handled when using `map[string]interface{}` in `Where()`?

E.g.: 

```go
db.Where(map[string]interface{}{"Name": userInput, "Age": userInput})
``` 

(where userInput is input from user, which may be unsanitized/dangerous)

## The document you expected this should be explained
[https://gorm.io/docs/security.html](https://gorm.io/docs/security.html)

This document explains how to handle security when using string input in `Where()`, but not for map.

## Expected answer

Whether input sanitization is handled in the case mentioned? (Yes/ No)
Thanks!

**Comment by jincheng9** [comment]
@pnshiralkar you can refer to [gen](https://github.com/go-gorm/gen). gen is a safer orm based on gorm and is designed to handle security things, such as sql injection.
