### ISSUE TITLE
How can I close the connection created using gorm.Open

### ISSUE THREAD

**Issue by pwli0755** [go-gorm/gorm#4613]
## How can I close the connection created using gorm.Open
Hi, thanks for your great work!
I‘m using SQLite these days and there are many .db files of SQLite type in different directories, I wanna close each opened database when I finished some query/updates, how can I achieve that? Note that there are so many db files, so I want to find a way to release some memory for the process.  

## The document you expected this should be explained
close the opened .db files and destroy the database connection(I can re-create them using gorm.Open if I need)

## Expected answer
any suggestions?

**Comment by dumindu** [comment]
https://gorm.io/docs/generic_interface.html

```
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})

sqlDB, err := db.DB()
sqlDB.Close()
```
