### ISSUE TITLE
Data is inserted into wrong table under many2many relationship in MySQL

### ISSUE THREAD

**Issue by haozhou** [go-gorm/gorm#4619]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/367/

## Description

The issue is firstly noticed in `v1.21.12` and can be reproduced in `v1.21.13` (latest release)
However, the codes works fine under playground.

Here's the simplified model.

```
type MyUser struct {
	gorm.Model
	Name string `gorm:"type:varchar(20)"`
	Languages []MyLanguage `gorm:"many2many:user_languages;"`
}

type MyLanguage struct {
	gorm.Model
	Name string
}
```

A `MyUser` can have multiple `MyLanguages`. 
The test case creates two languages `zh` and `en` and then create `MyUser` that `has` those two languages. 

The issue is if the `DB.Find(&languages)` occurs before the creation of `MyUser`, GORM would insert `test_user` into `my_language` table instead of `my_user` table. 

```
var languages []MyLanguage
DB.Find(&languages)
fmt.Println(languages)

user := MyUser{
Name: "test_user",
Languages: languages,
}
DB.Debug().Create(&user)
```

Here's the SQL it generates under `v1.21.13`
```
[60.221ms] [rows:1] INSERT INTO `my_languages` (`created_at`,`updated_at`,`deleted_at`,`name`) VALUES ('2021-08-16 16:08:58.745','2021-08-16 16:08:58.745',NULL,'test_user')
```

Same test case running under playground
```
[1.157ms] [rows:1] INSERT INTO `my_users` (`created_at`,`updated_at`,`deleted_at`,`name`) VALUES ("2021-08-16 16:15:53.877","2021-08-16 16:15:53.877",NULL,"test_user")
```

**Comment by haozhou** [comment]
After more tests, I think it's related with the database driver.

If I use `gorm.io/driver/sqlite v1.1.4` the SQL statement is generated properly (like the one in playground PR link)
If I use `gorm.io/driver/mysql`, the SQL statement is wrong

**Comment by haozhou** [comment]
I tried different version of `gorm.io/driver/mysql` from 1.0.6 to 1.1.2, the issue is reproducible in these versions.

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/143825623-abfec553-e583-497d-b99e-17872169a983.png)

seems to work on the latest version with latest driver
