### ISSUE TITLE
Secondary query error

### ISSUE THREAD

**Issue by qm012** [go-gorm/gorm#4627]
1. When you do a second query, you do not need to carry the query criteria of the first request
2. Requires a function for deep copy

```go
func (db *DB) Copy() (tx *DB) {

}
```

![image](https://user-images.githubusercontent.com/67568757/130317956-7849d344-1593-457c-9ced-c93803205df2.png)

**Comment by qm012** [comment]
The same DB in the same function query will carry the SELECT field to the next query condition
I don't need the last one for the next one
What should I do? But providing a deep copy does
![image](https://user-images.githubusercontent.com/67568757/130318126-001c3b9a-5406-4afc-aa54-72465e0dc633.png)

**Comment by qm012** [comment]
@jinzhu Each time, the previous query condition is brought with it

![image](https://user-images.githubusercontent.com/67568757/130341409-1988bb5f-9c02-474b-905a-5862985d71fb.png)

**Comment by Akaame** [comment]
Hello,

I do not think anyone can help you without seeing a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) of your problem first. Please create a simple repository or a playground PR that showcases the issue you are having.

Cheers.
