### ISSUE TITLE
postgres/cockroach: insert's `RETURNING` clause fields does not preserve insertion order

### ISSUE THREAD

**Issue by wojciechbator** [go-gorm/gorm#4643]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/369

## Description

Use case:

- using postgres DB and gorm
- set default jsonb value on one of model fields
- strict checking queries and responses - using `sqlmock` library to check that given query produces given results (checking exact query with RETURNING part)

Problem:
https://github.com/go-gorm/gorm/blob/master/callbacks/create.go#L134 <- range over the map does not guarantee ordered processing, thus leading to non deterministic behaviour of sql `RETURNING` clause. In my playground example, I added jsonb field which, along with `id` field is present in `RETURNING` clause. Run tests a few times and check that insert statement returns random `RETURNING` fields list. Once it's `"id","address"`, next time it's `"address","id"`. The problem is with it being undeterministic and hard to test using `sqlmock`.

Solution idea:
Preserve insertion order for default columns and avoid range over golang map, or sort it according to insertion order.

Expectation:
I would expect that this query always provides `RETURNING "id","address"` part, never the opposite way around.

**Comment by stoffeastrom** [comment]
Range over map seems to come from -> from https://github.com/go-gorm/gorm/blob/master/schema/schema.go#L204-L208
which appends to the `schema.FieldsWithDefaultDBValue` which is used in the `CreateWithReturning`
