### ISSUE TITLE
Update only if existed in the DB 

### ISSUE THREAD

**Issue by rnd-debug** [go-gorm/gorm#4652]
## Your Question
(probably an extremely simple question. Sorry)
I would like to `update` an object only if its ID exists in DB.
```
obj := MyStruct{
   ID: "111", Name: "initial",
   ModifiedAt: time.Now().UTC(),
}
func (a *MyStruct) BeforeUpdate(tx *gorm.DB) error {
   a.ModifiedAt = time.Now().UTC()
   return 
}
db.Create(&obj) => ok, saved
obj.Name = "different"
db.Save(&obj) => ok, updated, with new value

notStored := MyStruct{ID: "911", Name: "should not be created"}
db.Save(&notStored) => KO for my usage: a new object is created in the DB, but I would like to NOT create it (because this ID hasn't existed in DB previously
```
This behavior seems to be implemented in [https://github.com/go-gorm/gorm/blob/master/finisher_api.go#L105](https://github.com/go-gorm/gorm/blob/master/finisher_api.go#L105)

I tried to play with `db.Model(&MyStruct{}).Where("id = ?", notStored.ID).Updates(&notStored)`, BUT here it looks like the `BeforeUpdate` is not applied.
```
db.Model(&MyStruct{}).Where("id = ?", notStored.ID).Updates(&notStored)  => ok, returns error
db.Model(&MyStruct{}).Where("id = ?", obj.ID).Updates(&obj)  => KO, the ModifiedAt is not updated
```

Another idea: have 2 separate gorm calls, one for "find object by ID" and if not found, return error. 
=> but is there a gorm way of doing this?

[Additional info: I am using sqlite with [go-sqlite3](https://github.com/mattn/go-sqlite3) and a in-memory DB]
## The document you expected this should be explained
- A remark that a new object will be created here: [https://gorm.io/docs/update.html](https://gorm.io/docs/update.html)

## Expected answer
A short example. And I can eventually create a MR for the update of the docs.

**Comment by rnd-debug** [comment]
Related: #3568

**Comment by jinzhu** [comment]
FirstOrInit + Assign
