### ISSUE TITLE
Should I not use methods Scopes and Where at the same query?

### ISSUE THREAD

**Issue by munenari** [go-gorm/gorm#4662]
## Your Question

Can I use 'scopes' and 'or' both?

```go
var x interface{}
db.Scopes(some1, some2).Or("col1", "foo").Find(&x).Error
```

The output of this query is different from 1.20.12. I used to evaluate expressions each time, so the order of scopes and or was the same, but from some point scopes are lazily evaluated. For this reason, the way the or query expression is applied has changed, and the same query results as before cannot be obtained.

## The document you expected this should be explained

https://gorm.io/docs/scopes.html

## Expected answer

Unless you are supposed to use scopes and evaluation expressions at the same time
I want to insert an expression in scopes to accommodate it.
I want to know what the author thinks.

Thank you for reading this question.

**Comment by longlihale** [comment]
@munenari  hello,can you provide a demo in https://github.com/go-gorm/playground/ ?

**Comment by jinzhu** [comment]
closing as no response.
