### ISSUE TITLE
编写插件时，给一个字段设置值，其他字段会变成默认零值

### ISSUE THREAD

**Issue by funianwuxin** [go-gorm/gorm#4665]
## 在注册 callback 至 callbacks 时， 给其中的一个字段设置值，其他字段会变成默认零值

`
## code
global.DB.Callback().Create().Before("gorm:create").Register("update_created_at", db.UpdateTimeStampCreateCallback)

func UpdateTimeStampCreateCallback(db *gorm.DB) {  

	if db.Error == nil {    
		if db.Statement.Schema != nil {
			createdOnField := db.Statement.Schema.LookUpField("CreatedOn")
			if !createdOnField.NotNull {
				_ = createdOnField.Set(db.Statement.ReflectValue, time.Now().Unix())
			}
		}
	 }
 }

`

注册前 
` INSERT INTO `t_tags` (`created_by`,`modified_by`,`created_on`,`modified_on`,`deleted_on`,`is_del`,`name`,`state`) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,'python9',9)`

 注册后
 `INSERT INTO `t_tags` (`created_by`,`modified_by`,`created_on`,`modified_on`,`deleted_on`,`is_del`,`name`,`state`) VALUES ('','',1630525559,0,0,0,'python9',9)`

## Expected answer

怎么让其他字段保持NULL

**Comment by daheige** [comment]
please see gorm doc.
