### ISSUE TITLE
How to create different table names for one struct?

### ISSUE THREAD

**Issue by seaguest** [go-gorm/gorm#4670]
Hello,

I have a user model, I want to split it in 10 tables user_0, user_1,...user_9

```
type User struct {
	Id        uint32    `gorm:"primary_key" json:"id"`
	Name      string    `gorm:"size:64" json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func UserTable(u *User) func(tx *gorm.DB) *gorm.DB {
	return func(tx *gorm.DB) *gorm.DB {
		return tx.Table(fmt.Sprintf("user_%d", u.Id%10))
	}
}
```

I use Scopes to specify table name for query 
```
  u := &User{Id: 100}
  db.Scopes(UserTable(u)).Create(u)
```

However I am wondering how to create table with dynamic names? I want to create table user_0, user_1,...user_9 together, not to change TableName() each time, is there any elegant way?

**Comment by leafney** [comment]
How to solve the same need? So why closed?

**Comment by stonecool** [comment]
You can specify the table name before the operation `db.Table("table_name")`
