### ISSUE TITLE
AutoMigrate forces a not null constraint on self-referencing foreign key in Postgres

### ISSUE THREAD

**Issue by tfonfara** [go-gorm/gorm#4673]
While searching my issue I found #3816, which describes 100% my issue, so I'll not duplicate the description.

I understood that gorm forces the foreign key's column type to exactly match the primary's key column type. However, how can I create a "has one" relationship that is optional? In my use case I'm also having self-referencing models, that might or might not point to another row in the table. My primary key is of `type:VARCHAR(36) NOT NULL` so gorm always adds the `NOT NULL` to the foreign key column as well. How to prevent this?

Setting explicitly the foreign key column to `NULLABLE` will be ignored same as `sql.NullString`, only thing that works is to manually execute `ALTER TABLE table ALTER COLUMN column DROP NOT NULL`.

Thanks in advance!

https://github.com/go-gorm/playground/pull/373

**Comment by jinzhu** [comment]
https://gorm.io/docs/models.html#Fields-Tags

![image](https://user-images.githubusercontent.com/6843/143833018-f5b89c29-04fc-42c3-8840-27425767e593.png)


or you can skip the foreign key when migrating the table.
