### ISSUE TITLE
Why struct field changed even though RowsAffected is 0 ?

### ISSUE THREAD

**Issue by tidyoux** [go-gorm/gorm#4685]
## Your Question

```go
type Role struct {
	gorm.Model
	Name    string
}

var r Role
db = db.Model(&r).Where("id=? and name=?", r.ID, "invalid_name").Updates(M{
	"name": "hello++",
})
fmt.Printf("affectedRows: %d, err: %v, name: %s\n", db.RowsAffected, db.Error, r.Name)
```

Output:
```
affectedRows: 0, err: <nil>, name: hello++
```

Why r.Name changed?

## The document you expected this should be explained

https://gorm.io/docs/update.html

**Comment by jinzhu** [comment]
works as expected.

**Comment by updogliu** [comment]
Why "works as expected"? Do you mean the `name` column in the DB already has the value "hello++" before the update?

**Comment by jinzhu** [comment]
the model's value would be updated before sending data to the db.

**Comment by updogliu** [comment]
Oh, I was asking about the RowsAffected. Seems that there was one row changed in the DB, but got RowsAffected = 0. Unless the name column in the DB already has the value "hello++" before the update.

**Comment by jinzhu** [comment]
If you are reporting any issue, please create an issue with playground PR link
