### ISSUE TITLE
进行数据更新操作出现不一致问题

### ISSUE THREAD

**Issue by yaooort** [go-gorm/gorm#4688]
## 问题是这样的 并发操作用户余额变化需要一致性，一致性问题可以通过锁，但是会出现后续不能使用Save

https://github.com/go-gorm/playground/pull/376

## Description

> 问题1. 	main.go //  TODO  1
> 如果在事务中进行记录创建，修改数据就会不准确，这个问题可能是由于我这边操作造成的
> 问题2.  main.go //  TODO  2
> 如果加锁在事务中进行处理，事务结束会出现不能进行保存操作。只要有Save方法就会出现问题，具体原因目前我不知道，希望大佬能帮忙看看，

**Comment by yaooort** [comment]
demo https://github.com/yaooort/playground

**Comment by jinzhu** [comment]
use `select for update` and update with SQL expr
