### ISSUE TITLE
Unable to create FULLTEXT index for SQLite 

### ISSUE THREAD

**Issue by BogdanJava** [go-gorm/gorm#4689]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/375

## Description
`FULLTEXT` indexes cannot be created when using `sqlite`. Returns the following error:

```
2021/09/09 15:18:21 /Users/bahdan.shyshkin/go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:242 near "FULLTEXT": syntax error
[0.019ms] [rows:0] CREATE FULLTEXT INDEX `idx_toys_name` ON `toys`(`name`)
2021/09/09 15:18:21 Failed to auto migrate, but got error near "FULLTEXT": syntax error
FAIL    gorm.io/playground      3.458s
FAIL
```

**Comment by tanqiangyes** [comment]
@BogdanJava Hi, according to my experiment, sqlite itself should not support FULLTEXT, can you please try to remove FULLTEXT? My experimental data is as follows：
```
`sqlite> .schema users
CREATE TABLE users(name text PRIMARY KEY, age integer);
sqlite> CREATE FULLTEXT INDEX `users_age` ON `users` (`age`);
Error: near "FULLTEXT": syntax error
sqlite> .schema users
CREATE TABLE users(name text PRIMARY KEY, age integer);
sqlite> CREATE INDEX `users_age` ON `users` (`age`);
sqlite> .schema users
CREATE TABLE users(name text PRIMARY KEY, age integer);
CREATE INDEX `users_age` ON `users` (`age`);`
```
You can also get a tutorial on sqlite from [sqlitetutorial](https://www.sqlitetutorial.net/sqlite-index/) ， tks.

**Comment by BogdanJava** [comment]
@tanqiangyes I know that it does not support the `FULLTEXT` keyword, but that's not an excuse because sqlite *does* support this feature. https://www.sqlite.org/fts5.html

**Comment by BogdanJava** [comment]
That's why ORM libraries have different drivers, right? Because SQL implementations are not the same.

**Comment by tanqiangyes** [comment]
@BogdanJava Right, I know what you mean. But in the case of FTS5, it is a virtual table, and then it implements FULLTEXT, so the regular create index statement is not available for it. Also FTS5 support doesn't seem to be implemented yet.  I found some people need this feature, I believe @jinzhu  will consider if it should be implemented.
