### ISSUE TITLE
computed fields are a problem

### ISSUE THREAD

**Issue by ciokan** [go-gorm/gorm#4698]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/377

## Description

I have some fields that are computed by queries such as the following:

```
SELECT 
  u.*, 
  (
    case when exists(
      SELECT 
        1 
      FROM 
        `user_blocked_users` 
      WHERE 
        blocked_user_id = u.id
    ) then 'true' else 'false' end
  ) as is_blocked 
FROM 
  users u
```

`is_blocked` is needed when pulling users but `is_blocked` is not needed as a column inside the table `users` since it's a field that gets the value when querying for it.

I managed to overcome that by specifying `gorm:"->;-:migration"` when I declared it inside the `User` model:

```
IsBlocked bool `gorm:"->;-:migration"`
```

Searching for the user via `Find`, `First` or `Select` seems to work. `Scan` always seems to produce default value on the field (`false`) regardless of the data inside the database (sql against the database confirms it) - so it doesn't complain about missing column but it totally ignores the field and fails to assign to it the right value.

Pulling the users out of an association however returns with an error: ` no such column: users.is_blocked`

```
usersAssoc := DB.Model(chat).Association("Users")
if err := usersAssoc.Find(&chatUsers); err != nil {
	t.Errorf("error pulling chat users: %v", err)
}
```

**Comment by jinzhu** [comment]
maybe create another struct to query the computed SQL？
