### ISSUE TITLE
Support for custom primitive types?

### ISSUE THREAD

**Issue by leebrooks0** [go-gorm/gorm#47]
I tried the following:

``` go
type Role string

const (
    Customer   Role = "CUSTOMER"
    Instructor Role = "INSTRUCTOR"
    Admin      Role = "ADMIN"
    SuperAdmin Role = "SUPERADMIN"
)

type User struct {
    Id             int64
    Email        string    
    Role          Role //Falls over if not string    
}
```

I kept getting the error below:

``` sh
goroutine 38 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc210043ef0, 0x8598e0, 0x2, 0xc210000a08, 0x2)
    /home/lee/Code/gocode/src/github.com/jinzhu/gorm/utils.go:17
created by github.com/jinzhu/gorm.toSnake
    /home/lee/Code/gocode/src/github.com/jinzhu/gorm/utils.go:50 +0x219
```

Is it not possible to support custom primitives, and if not, is it possible to give a more detailed error message, it was difficult to try and work out what was wrong from that error message.

**Comment by chen-tam** [comment]
missing  Value method

**Comment by wisecsj** [comment]
```
import database/sql/driver

func (role Role) Value() (driver.Value, error) {
return string(role), nil
}
func (role *Role) Scan(value interface{}) error {
value,_ = value.(string)
*role = Role(string(value))
}
```

More Complete

**Comment by qmn1711** [comment]
It only works in golang, but in postgresql the **role** column is still defined as a text when I run `db.CreateTable(&User{})` 

Then I tried to define the custom type for **role** column
```
type User struct {
	Id    int64
	Email string
	Role  Role `gorm:"type:role"`
}
```
This time an error will be thrown: `pq: type "role" does not exist`

Is it a bug or gorm haven't covered it?

**Comment by zapkub** [comment]
@qmn1711 you should provide a correct data type for gorm 
```
type User struct {
	Id    int64
	Email string
	Role  Role `gorm:"type:VARCHAR"`
}
```
assume as your `Role` valuer return `string`
