### ISSUE TITLE
How to handle additional data insert in many2many jointable?

### ISSUE THREAD

**Issue by ihulsbus** [go-gorm/gorm#4702]
## Your Question

Background information: 

I searched the web and this repo for a few hours but could not find an earlier question/answer, but I have two tables with a many2many relation (Recipe and Ingredient), linked through a custom jointable (Recipe_Ingredient) that contains extra metadata: 

models:
```golang
type Recipe struct {
	ID          int           `gorm:"primaryKey;serial;unique;not null;autoIncrement" json:"id"`
	Title       string        `gorm:"not null" json:"title"`
	Description string        `gorm:"not null" json:"description"`
	Method      string        `gorm:"not null" json:"method"`
	Ingredients []Ingredients `gorm:"not null" json:"ingredients"`
}

type Ingredients struct {
	ID   int    `gorm:"primaryKey;serial;unique;not null;autoIncrement" json:"id"`
	Name string `gorm:"not null" json:"name"`
}

type Recipe_Ingredient struct {
	RecipeID     int    `gorm:"primaryKey" json:"recipeid"`
	IngredientID int    `gorm:"primaryKey" json:"ingredientid"`
	Amount       int    `gorm:"not null" json:"amount"`
	Unit         string `gorm:"not null" json:"unit"`
}
```
main.go:
```golang
func initDatabase(host string, username string, password string, database string, timezone string) *gorm.DB {
	dsn := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=5432 sslmode=disable TimeZone=%s", host, username, password, database, timezone)
	log.Debugf(dsn)

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Fatalf("Unable to connect to the database. Exiting..\n%v\n", err)
	}

	if err := db.SetupJoinTable(&models.Recipe{}, "recipe_ingredient", &models.Recipe_Ingredient{}); err != nil {
		log.Error("error setting up jointable for recipe/ingredient link")
	}

	err = db.AutoMigrate(
		&models.Recipe{},
		&models.Ingredients{})

	if err != nil {
		log.Errorf("Error while migrating database models: %s", err.Error())
	}

	return db
}
```

I managed to create the tables just fine, but I can't seem to figure out how to insert that metadata. I was looking at the BeforeCreate and BeforeSave, but that does not seem to work. I am currently working with an json input such as: 
```json
{
  "Title": "title",
  "Description": "description",
  "Method": "lots of text",
  "Ingredient": [{"id": 1, "amount": 20, "unit": "grams"}, {"id": 2, "amount": 10, "unit": "mililiters"}]
}
```

My current insert is limited to the following, which works to insert into the recipe table and the ID's in the jointable, but I'm stuck figuring out the metadata insert (amount and unit in the ingredient input):
```golang
// Create new recipe
func (r gormProductRepository) Create(recipe m.Recipe) (*m.Recipe, error) {
	//...

	err := r.db.Transaction(func(tx *gorm.DB) error {
		// Create recipe record
		if err := tx.Create(&recipe).Error; err != nil {
			return err
		}

		return nil
	})

	if err != nil {
		return nil, err
	}

	return &recipe, nil
}
```

I'm currently thinking about a two stage insert where I first insert the recipe and jointable ID's, and then based on the returned recipeID add the correct values in the jointable, but if there is a way to do this in one go then that would have my preference.

## The document you expected this should be explained
https://gorm.io/docs/many_to_many.html

Potentially:
https://gorm.io/docs/hooks.html or https://gorm.io/docs/transactions.html

## Expected answer

A nudge in the right direction on how to handle metadata insert :)

Thanks!

**Comment by ianprogrammer** [comment]
The only way that I found to do this was using the before save hook, the problem is that the before hook can't (or I don't know how) handle the data that came from your `&recipe` pointer because it capture only the value of the keys of the join table, for you to add the data from your `&recipe` input you have to pass a context 

```go
tx.WithContext(context.WithValue(context.Background(), "RecipeKey", recipe)).Create(&recipe)
 ```

and in your before save hook you can access this value from your context using

```go 
func (t *Recipe_Ingredient) BeforeSave(tx *gorm.DB) error {
      values, ok := tx.Statement.Context.Value("RecipeKey").(Recipe)
}
```

**Comment by jinzhu** [comment]
https://gorm.io/docs/many_to_many.html#Customize-JoinTable
