### ISSUE TITLE
Inserting in an in-memory sqlite DB using goroutines

### ISSUE THREAD

**Issue by mrbeepot** [go-gorm/gorm#4708]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/378

## Description

Hello, I am trying to insert multiple rows in a sqlite DB (in-memory).
I am trying to do this asynchronously using goroutines.
I am fairly new to Golang ecosystem.
The `main.go` has a function which inserts the row and publishes errors (if any) on a channel.

This logic is being called using goroutines for an array of dummy data I have setup in `main_test.go`

Can someone please tell me what I am doing wrong here?
Is this a problem with Sqlite DB itself?

Thanks in advance.

**Comment by longlihale** [comment]
hello, you can look here [here here here ](https://github.com/go-gorm/playground/pull/378/files) @mrbeepot
