### ISSUE TITLE
Is there a way to get the executed SQL statement directly?

### ISSUE THREAD

**Issue by zhangxuanru** [go-gorm/gorm#4709]
## Your Question

For example:
    models.db.save (& user)      I want to get the executed SQL statement. Is there any way to get it?

**Comment by shprotru** [comment]
Hi, @zhangxuanru, is `models.db.Debug().Save(&user)` that you expect for? You can setup [logger](https://gorm.io/docs/logger.html) and do whatever you want with the executed SQL statements.

**Comment by zhangxuanru** [comment]
Is there a function or method that can get SQL directly?

**Comment by zhangxuanru** [comment]
> Hi, @zhangxuanru, is `models.db.Debug().Save(&user)` that you expect for? You can setup [logger](https://gorm.io/docs/logger.html) and do whatever you want with the executed SQL statements.

Is there a function or method that can get SQL directly?

**Comment by shprotru** [comment]
@zhangxuanru there is no method to get SQL directly, because that's impossible and that's why: GORM SQL queries building is based on fetched data, so it can execute by one request several SQL queries. Use custom logging mechanism and get them all.

**Comment by longlihale** [comment]
you can use the following code to get SQL statement , It is usually used in the gorm's plugin @zhangxuanru  <br> 
```sql := db.Dialector.Explain(db.Statement.SQL.String(), db.Statement.Vars...)```

**Comment by sudopower** [comment]
> you can use the following code to get SQL statement , It is usually used in the gorm's plugin @zhangxuanru 
> 
> `sql := db.Dialector.Explain(db.Statement.SQL.String(), db.Statement.Vars...)`

thanks !
