### ISSUE TITLE
Get fully updated model instead of partials

### ISSUE THREAD

**Issue by mirusky** [go-gorm/gorm#4711]
## How do I get the fully updated model ?

For example if a made an Update I just received the fields that were updated, not the full model updated.

## The document you expected this should be explained

As reference API I'm using the [Updates multiple columns](https://gorm.io/docs/update.html#Updates-multiple-columns)

## Expected answer

Retrive the fully updated model after a update, not just the updated fields ( partial )

```go
type User struct{
  ID uint
  Name string
  Age uint
  IsVerified bool
}

// P.S: the user Name is "User"
user := User{ID: 3}

db.Model(&user).Updates(User{Age: 18, IsVerified: true})

// As I just provided the ID, Age and IsVerified it will be my return
// here the user variable will become: User{ ID: 3 Name: "" Age: 18 IsVerified: true} ( partial return )
// instead of User{ ID: 3 Name: "User" Age: 18 IsVerified: true} ( full return )
```

**Comment by mirusky** [comment]
I've used the question template...

**Comment by hellodit** [comment]
How about this now, it's been implemented?

**Comment by mirusky** [comment]
I'm using a workaround, using chain principle to update and then get the model updated. 

```go
db.Model(&user).Updates(User{Age: 18, IsVerified: true}).Find(&user)
```

in that way is possible to get all columns
