### ISSUE TITLE
Goroutines & DB.Transactions

### ISSUE THREAD

**Issue by cabelitos** [go-gorm/gorm#4713]
## Your Question

Hello everyone, I would like to know if it's save to use goroutines inside a DB transaction.

Something like
```golang
db.Transaction(func (tx *gorm.DB) error {
  go tx.Exec("SELECT. ....")
  go tx.Exec("INSERT .....")
  go tx.Raw("DELETE ...")
})
```

I read the https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety, however looking at the code it looks like that all commands running inside the transaction uses the same Session. But I wanted to be
Is this safe?

Thank you.

## The document you expected this should be explained

The https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety should be more clear about 
goroutines & transactions.

## Expected answer

A simple yes or no would satisfy me.

**Comment by longlihale** [comment]
it is not safe, because the same connection cannot write SQL concurrently. @cabelitos
