### ISSUE TITLE
How to make the IN Clause typesafe ?

### ISSUE THREAD

**Issue by khanakia** [go-gorm/gorm#4716]
## Your Question
I want to make the Where query `TYPE SAFE`.
`db.Model(&connect_type.Category{}).Where("id IN ?", ids).Scan(&categories).Error`

## Expected answer

How do i pass the `IN` query without hardcoding ?

**Comment by longlihale** [comment]
If only use  `id(Primary Key)` to query , you can  look the following code 

``db.Where([]int64{20, 21, 22}).Find(&users)
// SELECT * FROM users WHERE id IN (20, 21, 22);
``
[reference doc ](https://gorm.cn/docs/query.html#Struct-amp-Map-Conditions)

If you don't want to use `Primary Key`, you can  look the following code
`
db.Where("name IN ?", []string{"jinzhu", "jinzhu 2"}).Find(&users)
// SELECT * FROM users WHERE name IN ('jinzhu','jinzhu 2');`
[reference doc ](https://gorm.cn/docs/query.html#String-Conditions)

Unfortunately the functions for IN operations without hardcoding  does not exist yet,but you can Wrap one yourself.

**Comment by techuxm** [comment]
@longlihale I do not want to use the primary key. and the second example you showed it's not typesafe.

You have hardcoded the `name` in `db.Where("name IN ?", []string{"jinzhu", "jinzhu 2"}).`

I want to use something like this `db.WhereIn(user{Name: []string{"jinzhu", "jinzhu 2"}})`

**Comment by longlihale** [comment]
It does not seem to be supported now. @techuxm

**Comment by longlihale** [comment]
@techuxm @khanakia  I am sorry for the wrong answer yesterday, you can look the following code.
`db.Model(&model.DemoModel{}).Where(map[string]interface{}{"name": []string{"jinzhu","kinggo"}}).Debug().Find(&demoList)
 // SELECT * FROM `demo` WHERE `name` IN ("jinzhu","hale")
`
It may meet your needs , **the new version of grom** supports this use.

**Comment by techuxm** [comment]
@longlihale But still where is the type safety? You still hardcoded the name field

**Comment by longlihale** [comment]
@techuxm  look the following code.

``` 
type DemoModel struct {
	Name       string    `gorm:"column:name" json:"name"`
	Age        int       `gorm:"column:age" json:"age"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
}

func (m DemoModel) TableName() string {
	return "demo"
}


type User struct {
	Age interface{} `gorm:"type:'-'" json:"age"`
}

func Find() error {
	db := GetDBConnection()
	demoList := make([]*model.DemoModel, 0)
	db.Model(&model.DemoModel{}).Where(User{Age: []int{1, 2, 3}},
	).Debug().Find(&demoList)
	return nil
}
// [0.067ms] [rows:0] SELECT * FROM `demo` WHERE `demo`.`age` IN (1,2,3)

```
  It is important to note that **User's Gorm Tag** **type** is set to **-**
