### ISSUE TITLE
Tracing Support

### ISSUE THREAD

**Issue by 1995parham** [go-gorm/gorm#4718]
## Describe the feature

Support tracing with opentracing. Right now we have context and if we can create spans in the SQL functions we can add more detail into applications that have tracing.

We can do the tracing when we have context and if we don't have any context we ignore the span creation. what is your opinion about having PR for this?

**Comment by longlihale** [comment]
you can look here [gorm-opentracing](https://github.com/go-gorm/opentracing) @1995parham

**Comment by 1995parham** [comment]
oh, I didn't see that, what do you think about using [opentelemetry](https://github.com/open-telemetry/opentelemetry-go)?

**Comment by longlihale** [comment]
> oh, I didn't see that, what do you think about using [opentelemetry](https://github.com/open-telemetry/opentelemetry-go)?


[gorm-opentracing](https://github.com/go-gorm/opentracing) can support the use of customized tracer instead of opentracing.GlobalTracer() which is default, you can use the option WithTracer(yourTracer) for  [opentelemetry](https://github.com/open-telemetry/opentelemetry-go)  @1995parham
