### ISSUE TITLE
How to not add constraint for many2many?

### ISSUE THREAD

**Issue by seaguest** [go-gorm/gorm#4721]
## Your Question

Since gorm2.0, it add constraint automatically for many2many, however I don't want to use foreign keys, is there any way not to add them at creation time?

## The document you expected this should be explained

skip foreign key not mentioned.
https://gorm.io/docs/many_to_many.html

## Expected answer

I don't want foreign key constraints in many2many related tables.

**Comment by aigoya** [comment]
we hope to get an answer for our question.

**Comment by jinzhu** [comment]
https://gorm.io/docs/gorm_config.html#DisableForeignKeyConstraintWhenMigrating
