### ISSUE TITLE
when i use procedure。 use out param， how can i get this param value after procedure ending？ 

### ISSUE THREAD

**Issue by echobygo** [go-gorm/gorm#4722]

**Comment by longlihale** [comment]
You can say more carefully, where the parameters are used? @echobygo

**Comment by echobygo** [comment]
foreg:
the proceduce context:
 make @flag="hell world"

when i use gorm.raw(
call ***@***.***) )
how can i get the @flag value
error cmd:
gorm.raw("call ***@***.***) )'; select @flag as flag")
if you when get the flag value, you must use the same session, once you call proceduce,you must run exec: select @flag;



________________________________
寄件者: kinnggo ***@***.***>
寄件日期: 2021年9月24日 上午 11:15
收件者: go-gorm/gorm ***@***.***>
副本: echobygo ***@***.***>; Mention ***@***.***>
主旨: Re: [go-gorm/gorm] when i use procedure。 use out param， how can i get this param value after procedure ending？ (#4722)


You can say more carefully, where the parameters are used? @echobygo<https://github.com/echobygo>
