### ISSUE TITLE
Is it possible for gorm to support MongoDB(NoSQL)

### ISSUE THREAD

**Issue by myeung18** [go-gorm/gorm#4727]
## Your Question

Is it possible for gorm to support MongoDB(NoSQL)

**Comment by longlihale** [comment]
you can look it. [doc](https://github.com/grails/gorm-mongodb)

**Comment by longlihale** [comment]
It  is possible, but currently there is no driver for MongoDB [doc](https://gorm.cn/docs/write_driver.html) @myeung18

**Comment by hadifarnoud** [comment]
you can use [mgm](https://github.com/Kamva/mgm) instead
