### ISSUE TITLE
The Question About Joins

### ISSUE THREAD

**Issue by Mrmurong** [go-gorm/gorm#4728]
## Your Question
```
type User struct {
	ID       int32  `gorm:"primary_key,AUTO_INCREMENT:true,column:id"`
	UserId   int    `gorm:"column:user_id"`
	UserName string `gorm:"column:user_name"`
	RoleId   int    `gorm:"column:role_id"`
	Role     Role   `gorm:"foreignkey:RoleId"`
}

func (s *User) TableName() string {
	return "user"
}
type Role struct {
	RoleId   int    `gorm:"primary_key,AUTO_INCREMENT:false,column:role_id"`
	RoleName string `gorm:"column:role_name"`
}

func (s *Role) TableName() string {
	return "user_role"
}
```
When I use 
```
moduleUser := make([]*dbmodel.ModuleUser, 0)
s.db.Debug().Joins("Role").Find(&moduleUser)
```
The Program Print This:
```
SELECT `user`.`id`,`user`.`user_id`,`user`.`user_name`,`user`.`role_id`,`Role`.`role_id` AS `Role__role_id`,`Role`.`role_name` AS `Role__role_name` FROM `user` LEFT JOIN `user_role` `Role` ON `user`.`id` = `Role`.`role_id`
```
It seems wrong
Why?

**Comment by longlihale** [comment]
hello , you can try to look following code . @Mrmurong 
```
type User struct {
	ID       int32  `gorm:"primary_key,AUTO_INCREMENT:true,column:id"`
	UserId   int    `gorm:"column:user_id"`
	UserName string `gorm:"column:user_name"`
	RoleId   int    `gorm:"column:role_id"`
	Role     Role   `gorm:"ForeignKey:role_id;references:role_id"`
}

func (s *User) TableName() string {
	return "user"
}


type Role struct {
	RoleId   int    `gorm:"primary_key,AUTO_INCREMENT:false,column:role_id"`
	RoleName string `gorm:"column:role_name"`
}

func (s *Role) TableName() string {
	return "user_role"
}
```

- **foreignKey** should name the model-local key field that joins to the foreign entity.
- **references** should name the foreign entity's primary or unique key.

**Comment by Mrmurong** [comment]
> hello , you can try to look following code . @Mrmurong
> 
> ```
> type User struct {
> 	ID       int32  `gorm:"primary_key,AUTO_INCREMENT:true,column:id"`
> 	UserId   int    `gorm:"column:user_id"`
> 	UserName string `gorm:"column:user_name"`
> 	RoleId   int    `gorm:"column:role_id"`
> 	Role     Role   `gorm:"ForeignKey:role_id;references:role_id"`
> }
> 
> func (s *User) TableName() string {
> 	return "user"
> }
> 
> 
> type Role struct {
> 	RoleId   int    `gorm:"primary_key,AUTO_INCREMENT:false,column:role_id"`
> 	RoleName string `gorm:"column:role_name"`
> }
> 
> func (s *Role) TableName() string {
> 	return "user_role"
> }
> ```
> 
> * **foreignKey** should name the model-local key field that joins to the foreign entity.
> * **references** should name the foreign entity's primary or unique key.
> 
> SQL print this.
> 
> ```
> SELECT `user`.`id`,`user`.`user_id`,`user`.`user_name`,`user`.`role_id`,`Role`.`role_id` AS `Role__role_id`,`Role`.`role_name` AS `Role__role_name` FROM `user` LEFT JOIN `user_role` `Role` ON `user`.`role_id` = `Role`.`role_id`
> ```

**Comment by Mrmurong** [comment]
@longlihale  Thx ! get it!
