### ISSUE TITLE
Pluck doesn't support dynamic table name

### ISSUE THREAD

**Issue by MittWillson** [go-gorm/gorm#4730]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/381

## Description

https://github.com/go-gorm/gorm/blob/5202529ea147916a5b6e331c5d39f60859df2360/finisher_api.go#L486-L488

This condition will make an error that will ignore the scopes for the dynamic table name

check table name after scopes executed

**Comment by MittWillson** [comment]
@longlihale  Before upgrade gorm, we followed the docs using Scope to set the dynamic table name, after upgrading it's broken

**Comment by longlihale** [comment]
@MittWillson  Hello, can give me a demo to see?

**Comment by MittWillson** [comment]
@longlihale https://github.com/go-gorm/playground/pull/381 this may be working on gorm v1.20.9

**Comment by longlihale** [comment]
@MittWillson  Already fixed.
