### ISSUE TITLE
Create Table should not check IgnoreMigration

### ISSUE THREAD

**Issue by MittWillson** [go-gorm/gorm#4732]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/382

## Description

https://github.com/go-gorm/gorm/blob/6864a241504bc251b249c9bd3b85c803b0df90ce/migrator/migrator.go#L170-L175

In Migrator, create table shouldn't check the IgnoreMigration cause it will never create columns

**Comment by longlihale** [comment]
@MittWillson  hello, you can look the commit [Fix create with ignore migration](https://github.com/go-gorm/gorm/pull/4571)

**Comment by MittWillson** [comment]
@longlihale If a column has tag ignoreMigration for ignore type changed, will it create in createTable

**Comment by MittWillson** [comment]
@longlihale If a column is string and add tag `ignoreMigration`, it still will `alterColumn` cause `field.IgnoreMigration` is false

**Comment by MittWillson** [comment]
@longlihale I checked the code, is `ignoreMigration` tag deprecated?

**Comment by longlihale** [comment]
> @longlihale I checked the code, is `ignoreMigration` tag deprecated?

@MittWillson  hello, you can look here [#4028](https://github.com/go-gorm/gorm/pull/4028#issuecomment-774577865)

 Maybe we could have different permission level like the` ->`, `<-` one, `-` means disable read/write by default, `-:all` means disable read/write & migration, `-:migration` means only disable the migration?

**Comment by MittWillson** [comment]
@longlihale but also will wrong with `-:migration` cause the CreateTable using `Field.IgnoreMigration`, it may will not create the column, I will confirm it in playground and send a demo here

**Comment by MittWillson** [comment]
@longlihale https://github.com/go-gorm/playground/pull/382 here is demo

**Comment by longlihale** [comment]
> @longlihale Already confirmed it and exists, [go-gorm/playground#382](https://github.com/go-gorm/playground/pull/382) here is demo

@MittWillson  hello,I commented the code. go-gorm/playground#382

**Comment by MittWillson** [comment]
@longlihale is there has a way to Migration the struct but skip alter column when it exists, cause in production, change column type will pay much, but Migrator() are not useful for creating table manually

**Comment by MittWillson** [comment]
Maybe we should add an option for adding a column but never change it for security reasons

**Comment by MittWillson** [comment]
@longlihale https://github.com/itering/gorm/commit/c3db379c901140acaeb75c730fec16e661fdcfb6 option like this may help

**Comment by longlihale** [comment]
> @longlihale [itering@c3db379](https://github.com/itering/gorm/commit/c3db379c901140acaeb75c730fec16e661fdcfb6) option like this may help

thanks.we'll discuss.
