### ISSUE TITLE
Save: WHERE conditions required, if primary key is not Updatable

### ISSUE THREAD

**Issue by 4ega** [go-gorm/gorm#4734]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/383

## Description

If model primary key can be updated only on create (<-:create) and a pointer to a model is passed (DB.Save(&result)) into Save function, this will result in a "WHERE conditions required" error

**Comment by longlihale** [comment]
hello, looked at the comments for Save().
```
// Save update value in database, if the value doesn't have primary key, will insert it
```

**Comment by longlihale** [comment]
@4ega hello, you can  look Save() for comment,
`Save update value in database, if the value doesn't have primary key, will insert it`
It seems to be normal to return an error.

**Comment by 4ega** [comment]
But it has primary key, check my playgroud MR:
```
ID        uint `gorm:"primaryKey;<-:create"`
```
And this is not gorm error, it is error from Postgres saying that SQL missing WHERE conditions, because gorm failed generating it. And it fails in specific circumstances, that was not the case in version  v1.21.14. Bug was introduced in this commit https://github.com/go-gorm/gorm/commit/ba16b2368f253572195de14fef62272a752595ef, in version 1.21.15

**Comment by longlihale** [comment]
already fix but need wait merge. @4ega

**Comment by andig** [comment]
This still seems to be an issue:

```go
type meter struct {
	Meter     int       `json:"meter" gorm:"column:meter;uniqueIndex:meter_ts"`
	Timestamp time.Time `json:"ts" gorm:"column:ts;uniqueIndex:meter_ts"`
	Value     float64   `json:"val" gorm:"column:val"`
}

	return db.Instance.Save(&meter{
		Meter:     1,
		Timestamp: ts.Truncate(15 * time.Minute),
		Value:     value,
	}).Error
```

will produce the same error. It seems the documentation is wrong:

> Save update value in database, if the value doesn't have primary key, will insert it

I'm happy with the value being inserted, but instead it errors. Since this table does imho not need a PK this is a bug.
