### ISSUE TITLE
Can not preload associations when updating a record

### ISSUE THREAD

**Issue by emaincourt** [go-gorm/gorm#4736]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/384

## Description

Preloading does not seem to be working when updating a record. Please find the PR to reproduce my case with a nested association. Basically the following does not populate the `Friends` field of `User`, nor the `Languages` array.

```go
var updated User
if err := DB.Preload("Friends.Languages").Updates(user).Scan(&updated).Error; err != nil {
	t.Errorf("Failed, got error: %v", err)
}
```

However, the exact same syntax seems to be working when getting a record.

Am I doing something wrong here ?

Thanks in advance

**Comment by massimo-gollo** [comment]
Using this issue to note a point. 

If  ancestor's entity to update has new child (e.g updated User has new Friends or want to updated also existing Friends), Is it possible do it through  update function?
```
 DB.Preload("Friends.Languages").Updates(user).Scan(&updated)
 ```

**Comment by jinzhu** [comment]
Update is not expected to works with `Preload`
