### ISSUE TITLE
Adding a new column to an existing table and updating the existing composite primary key

### ISSUE THREAD

**Issue by manalivaltix** [go-gorm/gorm#4742]
## Your Question
I have a table - that has a composite primary key, comprising of 3 columns. Now, I need to add one more column to this table, (the newly added column has a default value), and also update the composite primary key to use this newly added column.

After running AutoMigrate on this new table, I noticed that though the GORM layer adds the new column, it does not update the composite Primary Key to include this newly added column. 

## Expected answer

How can I use GORM AutoMigrate function calls to update the existing Composite Primary Key of a table, to add a newly added column of the table?

**Comment by jinzhu** [comment]
migrating a composite primary key should not work.
