### ISSUE TITLE
Previously a zero value will not updated, but it will also update zero value after I upgrading, how to not update

### ISSUE THREAD

**Issue by luoxi001713** [go-gorm/gorm#4744]
## 
Code:

Config.DB.Model(&member).Select("Name", "RoleID").Updates(Member{
		Name:       member.Name,
		RoleID:     member.RoleID}).Error; err != nil {
		return err
}

sometimes I just want to update the Name, so if the RoleID is zero, It will neglect. But after I upgrading it will also update the RoleID to 0, this is not what I want. So how to easy to neglect it? Because there are a lot of these methods in my project.

**Comment by longlihale** [comment]
@luoxi001713  hello, can you provide a demo in [here](https://github.com/go-gorm/playground) and specify version ?

**Comment by luoxi001713** [comment]
> @luoxi001713 hello, can you provide a demo in [here](https://github.com/go-gorm/playground) and specify version ?

Thanks for your replaying

import "gorm.io/gorm"  
can't see the version, I guess it should be 2.0


type TeamMember struct {
	ID            int64     `gorm:"primaryKey"`
	Name       string    `db:"name" json:"name"`
	RoleID      int64     `db:"role_id" json:"role_id"`
}

func UpdateMember(member TeamMember)(err error){

  Config.DB.Model(&member).Select("Name", "RoleID").Updates(Member{
  Name: member.Name,
  RoleID: member.RoleID}).Error; err != nil {
  return err
  }
}

var member TeamMember
member.ID = 1
member.Name = "Test"
UpdateMember(member)

I just want to update the name here, so the RoleID is 0, but after I run, the roleID also updated to 0, previously when I used 1.0 version, it will not update.

**Comment by longlihale** [comment]
@luoxi001713  hello,you can look this doc https://gorm.cn/docs/update.html#Updates-multiple-columns, you use `Select`  and contains   `RoleID`  cause update to 0 when you use  `gorm v2`.
