### ISSUE TITLE
Count breaks Joins Preloading

### ISSUE THREAD

**Issue by knoebber** [go-gorm/gorm#4746]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/385

## Description

After upgrading to `v1.21.15` from `v1.20.12`, I noticed queries that use [Joins Preloading](https://gorm.io/docs/query.html#Joins-Preloading) were returning incorrect results.  I found that it only happens when `.Count` is called on the gorm db variable before the final `.Find` call. Doing this causes the select clause to be 'SELECT *', which is incorrect as both tables can contain columns with the same name.

**Comment by longlihale** [comment]
@knoebber  hello, this issue already fixed.

**Comment by knoebber** [comment]
@longlihale thank you!

**Comment by longlihale** [comment]
> @longlihale thank you!

In fact,  maybe  use`Session` to solve this problem.
```
func TestGORM(t *testing.T) {
	companyA := Company{Name: "A"}
	companyB := Company{Name: "B"}
	DB.Create(&companyA)
	DB.Create(&companyB)

	user := User{Name: "jinzhu", CompanyID: &companyB.ID}
	DB.Create(&user)

	query := DB.Model(&User{}).Joins("Company").Session(&Session{}) // use session

	// Bug happens when .Count is called on a query.
	// Removing the below two lines or downgrading to gorm v1.20.12 will make this test pass.
	var total int64
	query.Count(&total)

	var result User

	// Incorrectly generates a 'SELECT *' query which causes companies.id to overwrite users.id
	if err := query.First(&result, user.ID).Error; err != nil {
		t.Errorf("Failed, got error: %v", err)
	}

	if result.ID != user.ID {
		t.Errorf("result's id, %d, doesn't match user's id, %d", result.ID, user.ID)
	}
}
```
