### ISSUE TITLE
Broken Pipe issues seen with Postgres connection in Golang

### ISSUE THREAD

**Issue by AnkitNassa** [go-gorm/gorm#4749]
## Your Question
Hi, 

I am trying to create a *gorm.DB connection using jinzhu/gorm repo. Here is how i am creating the connection: 
```
dbDSN := fmt.Sprintf("host=%v user=%v password=%v dbname=%v port=%v sslmode=%v", os.Getenv("PGHOST"), os.Getenv("PGUSER"), os.Getenv("PGPASSWORD"),  os.Getenv("PGDATABASE"),  os.Getenv("PGPORT"), os.Getenv("PGSSLMODE"))
DBConn, err = gorm.Open("postgres, dbDSN);
```

We are running a http server which on coming up keeps this DBConn and keep it till the lifecylce of the server.
I see that intermittently  on invoking any kind of queries (insert/select)  we get
 :write tcp xx.xx.xx.xx:40968->xx.xx.xx.xx:5432: write: broken pipe errors.
 
 This http server is running on a k8 pod. the container has psql installed and we can connect to psql commandline but when we server http requests we get this error. Could you please let us know if this have been seen earlier or not?

**Comment by tuwid** [comment]
Keep in mind that transient issues can also be mitigated by setting this parameter `SetConnMaxLifetime` to make sure the connections are recycled
