### ISSUE TITLE
Extending a structure attribute after embedding it with another structure with user defined data type

### ISSUE THREAD

**Issue by KBA07** [go-gorm/gorm#4751]
## Your question 
Is there any way to embed and extend a struct attribute with another structure attribute with user-defined data types?

Currently, I see that this is possible in Gorm using primitive data types. For example, if I use the code below

```
type Base struct {
	Name  string
	Limbs int
	Check string
}

type Animal struct {
	Base
	Uuid  string `gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	Types string
	Check int
}

err := db.AutoMigrate(Animal{})
	if err != nil {
		log.Error("error occurred")
	}
	
err := db.AutoMigrate(Base{})
	if err != nil {
		log.Error("error occurred")
	}
```
This would generate a table of something given below
```
platform=# \d bases 
               Table "public.bases"
 Column |  Type  | Collation | Nullable | Default 
--------+--------+-----------+----------+---------
 name   | text   |           |          | 
 limbs  | bigint |           |          | 
 check  | text   |           |          | 

platform=# \d animals
                   Table "public.animals"
 Column |  Type  | Collation | Nullable |      Default       
--------+--------+-----------+----------+--------------------
 name   | text   |           |          | 
 limbs  | bigint |           |          | 
 check  | bigint |           |          | 
 uuid   | uuid   |           | not null | uuid_generate_v4()
 types  | text   |           |          | 
```
However, I have a struct with no primitive data type and try to embed that with another struct and override certain attributes. I get issues at the time of table creation.

Attaching the reference code, error logs

```
type IetfInterfacesInterfacesInterface struct {
	VlanId int32 `json:"vlan-id,omitempty"`

	DisplayName string `json:"display-name,omitempty"`

	VlanTagging bool `json:"vlan-tagging,omitempty"`

	LinkUpDownTrapEnable *IetfInterfacesLinkUpDownTrapEnableEnumeration `json:"link-up-down-trap-enable,omitempty"`
	LowerLayerIf []string `json:"lower-layer-if,omitempty"`
	LastChange string `json:"last-change,omitempty"`

	OperStatus *IetfInterfacesOperStatusEnumeration `json:"oper-status,omitempty"`
	Description string `json:"description,omitempty"`
	Type_ string `json:"type,omitempty"`
	Speed int32 `json:"speed,omitempty"`
	Enabled bool `json:"enabled,omitempty"`

	AdminStatus *IetfInterfacesAdminStatusEnumeration `json:"admin-status,omitempty"`
	PhysAddress string `json:"phys-address,omitempty"`
	Name string `json:"name,omitempty"`
	HigherLayerIf []string `json:"higher-layer-if,omitempty"`
	IfIndex int32 `json:"if-index,omitempty"`

	Statistics *IetfInterfacesInterfacesInterfaceStatistics `json:"statistics,omitempty"`
}

type TestInterface struct {
	IetfInterfacesInterfacesInterface
	Uuid                 string `gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	LinkUpDownTrapEnable string
	OperStatus           string
	AdminStatus          string
	Statistics           string
	LowerLayerIf         string
	HigherLayerIf        string
}

log.Info("migrating test interface table")
	err := db.AutoMigrate(TestInterface{})
	if err != nil {
		log.Error("error occurred")
	}
```
Error Logs

[error] unsupported data type: &[]

[error] failed to parse value main.TestInterface{IetfInterfacesInterfacesInterface:IetfInterfacesInterfacesInterface{VlanId:0, DisplayName:"", VlanTagging:false, LinkUpDownTrapEnable:(*IetfInterfacesLinkUpDownTrapEnableEnumeration)(nil), LowerLayerIf:[]string(nil), LastChange:"", OperStatus:(*IetfInterfacesOperStatusEnumeration)(nil), Description:"", Type_:"", Speed:0, Enabled:false, AdminStatus:(*IetfInterfacesAdminStatusEnumeration)(nil), PhysAddress:"", Name:"", HigherLayerIf:[]string(nil), IfIndex:0, Statistics:(*IetfInterfacesInterfacesInterfaceStatistics)(nil)}, Uuid:"", LinkUpDownTrapEnable:"", OperStatus:"", AdminStatus:"", Statistics:"", LowerLayerIf:"", HigherLayerIf:""}, got error unsupported data type: &[]

[error] unsupported data type: &[]

[error] unsupported data type: &[]

[error] failed to parse value main.TestInterface{IetfInterfacesInterfacesInterface:IetfInterfacesInterfacesInterface{VlanId:0, DisplayName:"", VlanTagging:false, LinkUpDownTrapEnable:(*IetfInterfacesLinkUpDownTrapEnableEnumeration)(nil), LowerLayerIf:[]string(nil), LastChange:"", OperStatus:(*IetfInterfacesOperStatusEnumeration)(nil), Description:"", Type_:"", Speed:0, Enabled:false, AdminStatus:(*IetfInterfacesAdminStatusEnumeration)(nil), PhysAddress:"", Name:"", HigherLayerIf:[]string(nil), IfIndex:0, Statistics:(*IetfInterfacesInterfacesInterfaceStatistics)(nil)}, Uuid:"", LinkUpDownTrapEnable:"", OperStatus:"", AdminStatus:"", Statistics:"", LowerLayerIf:"", HigherLayerIf:""}, got error unsupported data type: &[]

[error] unsupported data type: &[]

## Expected answer
Is this currently supported, Or are there any plans to support this in the future. Or is there any alternative to achieve this without touching the original struct.

**Comment by longlihale** [comment]
gorm support Customize Data Types [doc](https://gorm.cn/docs/data_types.html)

**Comment by jinzhu** [comment]
no, doesn't support this.
