### ISSUE TITLE
How to retrive column names on the scopes?

### ISSUE THREAD

**Issue by mosleim** [go-gorm/gorm#4753]
## How to retrive column name on the scopes?
i need checking column name on the scopes. but, i get schema always nil.
```
func checkUserID(db *gorm.DB) *gorm.DB {
	isHaveUserID := false
	schema := db.Statement.Schema
	if schema == nil {
		println("schame always nil")
		return db
	}
	for _, v := range db.Statement.Schema.Fields {
		if v.Name == "UserID" {
			isHaveUserID = true
		}
	}
	if isHaveUserID {
		db.Where("user_id=1")
	}
	return db
}

```
use the scopes:
```
db.Scopes(checkUserID).Find(&user)

```

but, the Schema is always nil.

**Comment by longlihale** [comment]
@mosleim  This does not seem to work, because get schema in `find -> excute` after scopes.
https://github.com/go-gorm/gorm/blob/b46e2afc4a5fca825c959545b92eef9cd8c83d53/callbacks.go#L105

**Comment by longlihale** [comment]
@mosleim  you can try to plugin, but not recommended to use schema to  implemente business logic
