### ISSUE TITLE
Gorm V2 - Adding Hooks for callback before/after database connection

### ISSUE THREAD

**Issue by mayuragarwal24** [go-gorm/gorm#4756]
## Describe the feature

Current gorm v2 literary only supports before/after callback for DB CRUD operations. Wondering if Gorm can provide hooks for before/after database connection. 

## Motivation

I would like to add tracing/metrics for how long the connect operation takes to debug performance issues.

## Related Issues
https://github.com/go-gorm/gorm/issues/3904

**Comment by longlihale** [comment]
@mayuragarwal24  hello, conn's creation  is done by the driver, so gorm do this thing is not very suitable. you can refer to https://github.com/go-gorm/gorm/issues/3904 's recommendation.
