### ISSUE TITLE
onConflictOption UpdateAll but not update datetime

### ISSUE THREAD

**Issue by qianxiansheng90** [go-gorm/gorm#4759]
gorm version: v1.21.13
mysql version:5.7.18-15-29.20-log
table:create table t(id varchar(100) primary key,name varchar(10),d  datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3));

代码：
```go
type TblTaskLock struct {
	ID   string          `gorm:"not null;type:varchar(512);default:'';primaryKey;comment:全局唯一索引"`
	Name string          `gorm:"not null;default:'';comment:名"`
	D    time.Time       `gorm:"not null;default:current_timestamp(3);comment:时间"`
}

var t = TblTaskLock{
	ID:   "1",
	Name: "1",
	D:    time.Date(2021,9,9,10,10,10,0,time.Now().Location()),
}
if err=dbDefaultConn.Clauses(clause.OnConflict{
	OnConstraint: "PRIMARY KEY",
	UpdateAll:    true,
}).Create(&t).Error;err != nil{
	fmt.Println(err)
	return
}
fmt.Println("before:",t.D)
t.Name="2"
t.D=t.D.Add(100 * time.Second)
if err=dbDefaultConn.Clauses(clause.OnConflict{
	OnConstraint: "PRIMARY KEY",
	UpdateAll:    true,
}).Create(&t).Error;err != nil{
	fmt.Println(err)
	return
}
fmt.Println("expect:",t.D)

if err= dbDefaultConn.Where("id = 1").First(&t).Error;err != nil{
	fmt.Println(err)
	return
}
fmt.Println("after:",t.D)

```

结果：
before: 2021-09-09 10:10:10 +0800 CST
**expect: 2021-09-09 10:11:50 +0800 CST**
**after: 2021-09-09 10:10:10 +0800 CST**

**Comment by qianxiansheng90** [comment]
if err=dbDefaultConn.Clauses(clause.OnConflict{
	OnConstraint: "PRIMARY KEY",
	DoUpdates: clause.AssignmentColumns([]string{"name", "d"}),
}).Create(&t).Error;err != nil{
	fmt.Println(err)
	return
}
目前可以通过这种方式解决这个问题。请帮忙看一下原因

**Comment by longlihale** [comment]
@qianxiansheng90  hello, can you provide a demo in https://github.com/go-gorm/playground/ ?

**Comment by qianxiansheng90** [comment]
> @qianxiansheng90 hello, I run normal and you can try to upgrade gorm's version to solve this issues.
> 
> ```
> before: 2021-09-09 10:10:10 +0800 CST
> expect: 2021-09-09 10:11:50 +0800 CST
> after: 2021-09-09 10:11:50 +0800 CST
> ```
> 
> * gorm‘s version v1.21.15

ok
