### ISSUE TITLE
Autoincrement is not enabled in SQLite when used with AutoMigrate

### ISSUE THREAD

**Issue by iSLC** [go-gorm/gorm#4760]
## Description

Very simple use case:
```go
package main

import (
	"log"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

type User struct {
	ID   int64  `gorm:"primaryKey;autoIncrement;not null"`
	Name string `gorm:"unique;not null"`
	Mail string `gorm:"unique;not null"`
	Pass string `gorm:"unique;not null"`
}

func main() {
	con, err := gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
	if err != nil {
		log.Panic(err)
	}
	con.AutoMigrate(User{})
}
```

The database and table is created. Everything else is fine. Except `AUTOINCREMENT` is not enabled on primary key. What am I doing wrong here? (_~~I have not tried with other drivers~~_) (_just tried on mysql and works fine there_)

This is the DDL of the generated table:
```sql
CREATE TABLE users (
    id   INTEGER NOT NULL,
    name TEXT    NOT NULL
                 UNIQUE,
    mail TEXT    NOT NULL
                 UNIQUE,
    pass TEXT    NOT NULL
                 UNIQUE,
    PRIMARY KEY (
        id
    )
);
```

OS: Windows x64
GO: 1.17.2 (_fresh installation. just began learning go_)

**Comment by longlihale** [comment]
@iSLC  a field declared as INTEGER PRIMARY KEY will automatically add [doc](https://www.sqlite.org/autoinc.html?http://www.sqlite.org/faq.html)

**Comment by longlihale** [comment]
> @longlihale ~So basically i only need to specify `autoIncrement` without `primaryKey`? At least that's what I can infer from the code at first glance.~ nvm I just read it wrong.
> 
> ```go
> case schema.Int, schema.Uint:
> 		if field.AutoIncrement && !field.PrimaryKey {
> 			// https://www.sqlite.org/autoinc.html
> 			return "integer PRIMARY KEY AUTOINCREMENT"
> 		} else {
> 			return "integer"
> 		}
> ```
> 
> I'll have to look more into it when I get home. Thanks for the reply.

yes,because

**Comment by longlihale** [comment]
> @longlihale ~So basically i only need to specify `autoIncrement` without `primaryKey`? At least that's what I can infer from the code at first glance.~ nvm I just read it wrong.
> 
> ```go
> case schema.Int, schema.Uint:
> 		if field.AutoIncrement && !field.PrimaryKey {
> 			// https://www.sqlite.org/autoinc.html
> 			return "integer PRIMARY KEY AUTOINCREMENT"
> 		} else {
> 			return "integer"
> 		}
> ```
> 
> I'll have to look more into it when I get home. Thanks for the reply.

OK

**Comment by yqchilde** [comment]
If you want to set the auto-increment on the ID field, using the `autoIncrement` tag alone does not take effect, because the `primaryKey` is added to the ID by default, which makes it impossible to set the auto-increment on the ID field anyway.

**Comment by Binary-Eater** [comment]
> If the AUTOINCREMENT keyword appears after INTEGER PRIMARY KEY, that changes the automatic ROWID assignment algorithm to prevent the reuse of ROWIDs over the lifetime of the database. In other words, the purpose of AUTOINCREMENT is to prevent the reuse of ROWIDs from previously deleted rows. 

The above is from the SQLite docs. I think, given the docs, the logic in `go-gorm/sqlite3` should be `field.AutoIncrement && field.PrimaryKey` instead of [what it is currently](https://github.com/go-gorm/sqlite/blob/9ec45b1aed33c835d720916bb46a6aa0c131ab9e/sqlite.go#L168-L174).

**Comment by Binary-Eater** [comment]
Actually, one can use `autoIncrement` -> `INTEGER PRIMARY KEY AUTOINCREMENT` with sqlite3, so the current behavior makes sense to me.

**Comment by onlyshow** [comment]
How was it finally resolved?
