### ISSUE TITLE
How to end manually after using `Or()`? The SQL statement generated by the system is not the expected result

### ISSUE THREAD

**Issue by lixh00** [go-gorm/gorm#4761]
## Your Question
After I use `Or()`, the SQL generated by the splicing conditions is not the expected result. How should I deal with this problem?

当我使用了`Or()`之后，后面拼接的条件所生成的SQL并非预期想要的结果，请问我应该怎么处理这个问题？

Code:
```
conn := MySQLConn
conn.Where("email = ?", param.Username).Or("mobile_phone = ?", param.Username)
if param.Status != "" {
    conn.Where("status = ?", param.Status)
}
```
SQL generated:
```
SELECT count(*) FROM `t_admin_user` WHERE (email = 'lxh@cxh.cn' OR mobile_phone = 'lxh@cxh.cn' AND status = 'NORMAL') AND `t_admin_user`.`deleted_at` IS NULL 
```

I expected:
```
SELECT count(*) FROM `t_admin_user` WHERE (email = 'lxh@cxh.cn' OR mobile_phone = 'lxh@cxh.cn') AND status = 'NORMAL' AND `t_admin_user`.`deleted_at` IS NULL
```

**Comment by longlihale** [comment]
> Ok,Thx

Example:
```
func Find() {
	//var users []*User
	DB := GetDBConnection()
	subQ:=DB.Or("email = ?", 1).Or("mobile_phone = ?", 2)
	DB.Where(subQ).Where("status = 1").Debug().Find(&model.User{})
	// [0.085ms] [rows:0] SELECT * FROM `users` WHERE (email = 1 OR mobile_phone = 2) AND status = 1
}
```

**Comment by AllCute** [comment]
> > Ok,Thx
> 
> Example:
> 
> ```
> func Find() {
> 	//var users []*User
> 	DB := GetDBConnection()
> 	subQ:=DB.Or("email = ?", 1).Or("mobile_phone = ?", 2)
> 	DB.Where(subQ).Where("status = 1").Debug().Find(&model.User{})
> 	// [0.085ms] [rows:0] SELECT * FROM `users` WHERE (email = 1 OR mobile_phone = 2) AND status = 1
> }
> ```

I first read this, but I used it wrong, resulting in duplication of the generated SQL. Later, I changed the usage.

我最开始看了这个的，但是用错了，导致生成的SQL有重复，后来换了个用法就对了
