### ISSUE TITLE
postgre  ::dataType Question：Joins character varying = uuid

### ISSUE THREAD

**Issue by lifegit** [go-gorm/gorm#4768]
## Your Question

example:
```
type MktLocals struct {     	
	ID        string    		`gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	Road	  models.MktRoads 	
	RoadID    string   			 `gorm:"type:character;"`
	Name      string    		
}
type MktRoads struct {
	ID        string    `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" form:"id" json:"id"`
	Name      string 
}
```

gorm:
```tx.Model(MktLocals{}).Joins(Road).Find(&[]MktLocals{})```
sql: 
```SELECT "mkt_locals"."id","mkt_locals"."road_id","mkt_locals"."name","Road"."id" AS "Road__id","Road"."name" AS "Road__name" FROM "mkt_locals" LEFT JOIN "mkt_roads" "Road" ON "mkt_locals"."road_id" = "Road"."id"```

### Gorm
Gorm is excellent in MySQL. But in PostgreSQL not ideal! 
because try error: `operator does not exist: character varying = uuid`
Although this is indeed the mechanism of PostgreSQL.
But orm positioning is a simple tool. Gorm supports this function better.

### java-jdbc
java-jdbc use `stringtype=unspecified` to deal with the [problem](https://blog.csdn.net/londa/article/details/109073570). Unfortunately, I didn't find the corresponding solution in Gorm

## Expected answer

According to tag Automatic increase type:

```SELECT "mkt_locals"."id","mkt_locals"."road_id","mkt_locals"."name","Road"."id" AS "Road__id","Road"."name" AS "Road__name" FROM "mkt_locals" LEFT JOIN "mkt_roads" "Road" ON "mkt_locals"."road_id" = "Road"."id"::character```

**Comment by jinzhu** [comment]
define a UUID struct like https://gorm.io/docs/data_types.html#Clause-Expression also refer datatypes https://github.com/go-gorm/datatypes
