### ISSUE TITLE
The function db.Update() can't return RowsAffected

### ISSUE THREAD

**Issue by Artanis-c** [go-gorm/gorm#4777]
## When I execute the 'db.Update()' function to update a record ,the returned value of RowsAffected is 0

My Code
db.Model(&models.SgrTenant{}).Where("id=?", id).Update("status", 1)

This is the gorm generated SQL

 UPDATE `sgr_tenant` SET `status`=1 WHERE id=1

When I put this SQL in the database for execution ,it returns rows affected is 1

So I think there must be something wrong with my configuration,please tell me what should  I do

**Comment by Artanis-c** [comment]
hello,I find the cause of the problem,if the value is the same as the in database ,the RowsAffected will be 0.
but i am puzzled why the SQL clinet shows that number of affected rows is 1
------[success]------
[SQL]:  UPDATE `sgr_tenant` SET `status`=1 WHERE id=1
[time consuming]: 51 (ms)
[affected rows ]: 1

**Comment by longlihale** [comment]
gorm's code that judge `update_at` :
https://github.com/go-gorm/gorm/blob/9a5ba376042427be60899f5f93ccdaf0b5a0ef83/schema/field.go#L254
