### ISSUE TITLE
Is there a way to do batch upsert while ignoring zero values?

### ISSUE THREAD

**Issue by dgunay** [go-gorm/gorm#4780]
## Your Question

When using [Upsert/On-Conflict](https://gorm.io/docs/create.html#Upsert-On-Conflict) with AssignmentColumns, it will replace the given values in the columns even if they are zero-valued.

If my batch updates are mixed (each struct may have different zero value fields that I don't want to update), is that supported by the upsert/on-conflict?

```go
type MyModel {
    ID int
    a int
}

// For the sake of the example, lets say both of these entities already
// exist in the DB and their `a` value is 3.
updates := []MyModel {
    { 1, 5 }, // I want this to update to 5
    { 2, 0 }, // I don't want this update to 0
}

_ := d.DB.Clauses(clause.OnConflict{
		Columns: []clause.Column{
			{Name: "a"},
		},
		DoUpdates: clause.AssignmentColumns([]string{"a"}),
	}).Create(&updates)
// `a` will be 0 for the second struct
```

**Comment by jinzhu** [comment]
no, it is not possible.
