### ISSUE TITLE
migrating a GORM v1 project heavily based off "StructField" & "ModelStruct" to v2

### ISSUE THREAD

**Issue by ntswamp** [go-gorm/gorm#4781]
## Your Question
as the title suggests,  i can say the whole cache layer in our project is built on "StructField" and "ModelStruct"--which are no longer existing in GORM v2. essentially we are acquiring some meta info about model struct from these two.
![Screenshot 2021-10-16 180156](https://user-images.githubusercontent.com/50705651/137581592-5ac1594b-f5b0-44b0-b0b6-07329c18674d.jpg)
I know there definitely are ways to achieve this in V2, but also listening to the original author's opinions would be even better or safe.

**Comment by jinzhu** [comment]
those data are cached with `schema.Schema`
