### ISSUE TITLE
When struct's field type is interface{}, the result is wrong while Where("status = 1"), but Where("status = ?", 1) is ok

### ISSUE THREAD

**Issue by qizhangfang** [go-gorm/gorm#4782]
type result struct {
    // Value int // it's always ok
    Value interface{} `gorm:"type:bytes"` // not ok with Where("status = 1"), but ok with Where("status = ?", 1)
    Label string
}
var results []result
db = model.DB.Select("id AS value", "name AS label")
db = db.Table("org")
// db = db.Where("status = ?", 1)  // it's always ok
db = db.Where("status = 1") // not ok with Value interface{}
db.Scan(&results)
byteData, _ := json.Marshal(results)
fmt.Println(string(byteData))

when db.Where("status = 1")  app log, it's ok :
[59.883ms] [rows:2] SELECT id AS value,name AS label FROM `org` WHERE status = 1
[{"Value":"MQ==","Label":"AA公司"},{"Value":"NTA=","Label":"BB公司"}]

when db.Where("status = ?", 1)  app log, it's not ok:
[50.002ms] [rows:2] SELECT id AS value,name AS label FROM `org` WHERE status = 1
[{"Value":123,"Label":"AA公司"},{"Value":124,"Label":"BB公司"}]

the value 123 is right, "MQ==" is what ?

**Comment by longlihale** [comment]
@qizhangfang  can you provice a demo in https://github.com/go-gorm/playground?

**Comment by longlihale** [comment]
I try to run reappear it , but it is normal.
```
type result struct {
	// Value int // it's always ok
	Value interface{} `gorm:"type:bytes"`
	Label string
}

func TestGORM(t *testing.T) {
	user := User{Name: "jinzhu"}

	DB.Create(&user)
	var results []result
	if err := DB.Select("id AS value", "name AS label").Model(&User{}).Where("active = 1").Find(&results).Error; err != nil {
		t.Errorf("Failed, got error: %v", err)
	}
}
```

debug:
```
[0.180ms] [rows:0] SELECT id AS value,name AS label FROM `users` WHERE active = 1 AND `users`.`deleted_at` IS NULL
--- PASS: TestGORM (0.00s)
PASS
```
