### ISSUE TITLE
AutoMigrate failed (type "bigserial" does not exist)

### ISSUE THREAD

**Issue by enzofoucaud** [go-gorm/gorm#4792]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/391

Existing database without using GORM : 
```
DROP TABLE IF EXISTS "events";
DROP SEQUENCE IF EXISTS events_id_seq;
CREATE SEQUENCE events_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;
CREATE TABLE "public"."events" (
    "id" integer DEFAULT nextval('events_id_seq') NOT NULL,
    "town" text NOT NULL,
    "latitude" real NOT NULL,
    "longitude" real NOT NULL,
    "kind" text NOT NULL,
    "species" text NOT NULL,
    "description" text NOT NULL,
    "user_publisher" integer NOT NULL,
    "time" timestamp NOT NULL,
    "disabled" integer NOT NULL,
    "report" integer NOT NULL,
    CONSTRAINT "events_pkey" PRIMARY KEY ("id")
) WITH (oids = false);
```

Model used with GORM : 
```
type Event struct {
	gorm.Model
	Town           string    `gorm:"not null"`
	Latitude       float64   `gorm:"not null"`
	Longitude      float64   `gorm:"not null"`
	Kind           string    `gorm:"not null"`
	Species        string    `gorm:"not null"`
	Description    string    `gorm:"not null"`
	User_Publisher int       `gorm:"not null"`
	Time           time.Time `gorm:"not null"`
	Disabled       int       `gorm:"not null"`
	Report         int       `gorm:"not null"`
}
```

Function that opens the database and migrates the data : 
```
func (store PostgresRepository) Open(dsn string) (*PostgresRepository, error) {
	// Open database
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return nil, err
	}
	log.Info().Msg("Connected to db")

	// Create the new SQLite repository
	sql := NewPostgresRepository(db)

	// Migration database
	if err := db.AutoMigrate(&Event{}); err != nil {
		return nil, err
	}

	return sql, nil
}
```

Error : 2021/10/19 15:14:19 /home/enzo/go/pkg/mod/gorm.io/driver/postgres@v1.1.2/migrator.go:252 ERROR: type "bigserial" does not exist (SQLSTATE 42704)

## Description

Before using GORM I was using pgxscan and doing automatic migrations via a script.
Recently I switched to GORM which is more efficient but I get this error during the migration.

Why do I get this error?

Same problem here #4765

**Comment by enzofoucaud** [comment]
Hello, any news about this issue ?

**Comment by Hanggi** [comment]
Any updates or work around? It seems to cause auto migration fail.

**Comment by longlihale** [comment]
I see see....:sob:

**Comment by enzofoucaud** [comment]
> I see see....😚

Thanks, because I want to launch my app in prod :)

**Comment by mehdipourfar** [comment]
I'm also facing this problem after updating gorm

**Comment by enzofoucaud** [comment]
> I'm also facing this problem after updating gorm

Which version ?

I'm using v1.21.16

**Comment by mehdipourfar** [comment]
> > I'm also facing this problem after updating gorm
> 
> Which version ?
> 
> I tested v1.22.2 & v1.21.16

After this updates in dependencies:

-       gorm.io/driver/postgres v1.1.0  ----> gorm.io/driver/postgres v1.2.1
-       gorm.io/gorm v1.21.13 ----> gorm.io/gorm v1.22.2

**Comment by benjamineskola** [comment]
I’ve had this issue too and found that overriding the type of the primary key works as a workaround:

```
type Something struct {
    ID                uint `gorm:"type:integer”`
   …
}
```

**Comment by jpmeijers** [comment]
Also being affected here after upgrading from jinzhu/gorm to gorm/gorm. Tables in the database were created with the earlier version, now the new version's migration is trying to update them, but fails with this error message:
`Unable autoMigrateDB - ERROR: type "bigserial" does not exist (SQLSTATE 42704)`

**Comment by jinzhu** [comment]
upgrade postgres driver should fix the issue.
