### ISSUE TITLE
default field tag with sequence, postgres

### ISSUE THREAD

**Issue by mjgabriel** [go-gorm/gorm#4793]
## Your Question

I have a table defined with a column and its default value is set to a sequence

```
CREATE TABLE orders (
    id UUID PRIMARY KEY,
    order_id VARCHAR(64) DEFAULT NEXTVAL('order_number'),
    ...
  );
```

And in my Go struct

```
type Order struct {
        ...
	OrderId string `gorm:"->;default:nextval()"`
}
```

Notice I used `nextval()`. No matter what I put here, as long as it has `()` (e.g., I could set it like so `default:pizza()` or simply as `default:()`) then when I call the `gorm.DB.Create` func passing an `Order` the insert/create succeeds and `Order.OrderId` comes back populated with the next value in the sequence. 

`OrderId` has not been set in code and I had to set the struct field to `readonly` so that an empty string isn't set as part of the `INSERT` performed by `gorm.DB.Create`

Now, if I completely omit the `default` tag definition, the `OrderId` field of the passed in `Order` to `gorm.DB.Create` does not come back populated with the defaulted value of the `order_id` column (via `DEFAULT NEXTVALUE('order_number')`). Though in the table the field has been filled/set by the default definition on the column.

## The document you expected this should be explained

I do not find any documentation addressing the use of Postgres sequence as default field tag value.

## Expected answer

What I would like to know is how to properly use the `default` tag specifying a sequence if that is possible. What I have works but should it work? Can sequence be used with the `default` tag or is this not a supported use case.

**Comment by jinzhu** [comment]
Can you create a reproducible PR?
