### ISSUE TITLE
postgre composite type how to be safe scan to struct ?

### ISSUE THREAD

**Issue by lifegit** [go-gorm/gorm#4794]
## Your Question

repo: [playground](https://github.com/lifegit/playground/blob/master/main_test.go#L75)

## The document you expected this should be explained

How to be safe scan to struct ?
example code, describe column is very dangerous.
I don't know what to do, I hope to get your help.

**Comment by longlihale** [comment]
@lifegit  hello, I didn't understand why you said describe column is dangerous???

**Comment by mirusky-enube** [comment]
Why you denormalized your data like saving everthing in one column?

**Comment by lifegit** [comment]
use 

> 为什么您将数据非规范化，例如将所有内容保存在一列中？

postgre use  [composite type](https://www.postgresql.org/docs/13/rowtypes.html)

**Comment by jinzhu** [comment]
refer https://gorm.io/docs/data_types.html and https://github.com/go-gorm/datatypes
