### ISSUE TITLE
Customize JoinTable on column other than ID

### ISSUE THREAD

**Issue by duhruh** [go-gorm/gorm#4798]
## Your Question

It's very possible I missed something in the docs but, how do you setup Custom Join Table with differently named fields

```
type User struct {
  gorm.Model
  UUID      uuid.UUID `gorm:"type:uuid;primaryKey"`
  Favorites []Blog`gorm:"many2many:favorites;"`
}

type Blog struct {
  gorm.Model
  UUID      uuid.UUID `gorm:"type:uuid;primaryKey"`
}

type Favorite struct {
  UserUUID  uuid.UUID `gorm:"type:uuid;primaryKey"`
  BlogUUID uuid.UUID `gorm:"type:uuid;primaryKey"`
}

err = db.SetupJoinTable(&models.User{}, "Favorites", &models.Favorite{})
if err != nil {
  fmt.Printf("failed to migrate favorites: %v\n", err)
}

err = db.AutoMigrate(
  &models.User{},
  &models.Blog {},
  &models.Favorite{},
)
if err != nil {
  fmt.Printf("failed to migrate: %v\n", err)
}
```

I've tried many different ways to make this work and all of them came with different errors, when i tried to add a `joinForeignKey`  on the user struct i get a duplicate field `UserUUID` if i leave it out i get `user_id` not defined. 

## The document you expected this should be explained

https://gorm.io/docs/many_to_many.html#Customize-JoinTable
https://gorm.io/docs/many_to_many.html#Override-Foreign-Key

## Expected answer

A simple way to setup a join table with primary id columns by a different name. Ideally I would like the favorites table to simply look like

```
Favorites
user_uuid references user.uuid
blog_uuid references blog.uuid
```

**Comment by jinzhu** [comment]
document under https://gorm.io/docs/many_to_many.html#Override-Foreign-Key?
```go
type User struct {
  gorm.Model  Profiles []Profile gorm:"many2many:user_profiles;foreignKey:Refer;joinForeignKey:UserReferID;References:UserRefer;joinReferences:ProfileRefer"`
 Refer    uint      `gorm:"index:,unique"`
}
```
