### ISSUE TITLE
GORM不支持 bigquery datasets 名称大大写，无法通过Name strategy 修改

### ISSUE THREAD

**Issue by DarcyNing** [go-gorm/gorm#4799]
## Describe the feature

GORM不支持 bigquery datasets 名称大大写，无法通过Name strategy 修改，之前创建的issues好像不知道为啥被关闭了

## Motivation

因为我们有时候有需求需要连接不是由我们创建的dataset，人家采用全部大写的命名方式。
我想请教下我们这个有无支持计划？

**Comment by jinzhu** [comment]
why it doesn't work?
