### ISSUE TITLE
Doesn't execute hook functions when using find to map

### ISSUE THREAD

**Issue by athenakia** [go-gorm/gorm#4800]
## Your Question

When using find to map, AfterFind isn't triggered.

## The document you expected this should be explained

 My codes are as followed:

```golang
type Goods struct {
        Name    string  `gorm:"default:'';varchar(100);not null" json:"name"`
        Price     float32 `gorm:"default:0;type:int;not null" json:"price"`
        Label    []GoodsLabel `gorm:"foreignKey:GoodsId;references:Id" json:"labels"` // hasMany
}

func (goods *Goods) AfterFind(tx *gorm.DB) (err error) {
	goods.Price = goods.Price / 100
	return
}

db.Model(&model.Goods{}).Preload("Label").Where("id = ?", id).First(&goods)
db.Model(&model.Goods{}).Where("id = ?", id).First(&goodsResp)
var label = make([]uint, 0)
for _, item := range goods.Label {
	label = append(label, item.LabelId)
}
goodsResp["labels"] = label
```
I want to modify labels field of goods to another type but it's not supported. So I use "find to map" of GORM to get data in map[string]interface{}, but when I use "find to map", the AfterFind hook isn't triggered. What should I do? Any better idea?

## Expected answer

Way to modify labels field of goods to another type or trigger AfterFind hook when using "find to map".

**Comment by jinzhu** [comment]
works as expected.
