### ISSUE TITLE
will gorm support tidb auto_random ?

### ISSUE THREAD

**Issue by dovefi** [go-gorm/gorm#4803]
## Describe the feature

support `auto_random` tag

## Motivation

tidb use primary key with `AUTO_RANDOM` tag to avoid hot spot, but gorm doesn't seem to support it！

## Related Issues
- [tidb auto-random](https://docs.pingcap.com/zh/tidb/stable/auto-random)

**Comment by jinzhu** [comment]
just customize sql type to `auto_random` should works? also refer https://gorm.io/docs/data_types.html#GormDataTypeInterface
