### ISSUE TITLE
incorrect DB.count() return in statement with 'GROUP BY'

### ISSUE THREAD

**Issue by wanghuixia** [go-gorm/gorm#4809]
## Describe the feature.      
 
when the sql statement include **'GROUP BY'** and just **return one row affected**, then using the gorm-io's COUNT() function will return wrong count value back . for example,
"Department" table like:  
---------------------------------------------
|    departmentID.    |       employID             |
|           88                   |        1001                    |
|           88                   |        1002                    |
|           88                   |        1003                    |
|           99                   |        2001                    |
|           99                  |         2002                    |
---------------------------------------------
**Case1(correct count value)**: so when you use below gorm-io as below, the count value will be 2:
```
DB.Group("departmentID").Count(&total)
```
 here finally total will be 2, the gorm-io send sql is : select count(*) from department, and executed result as below:
-------------------
|    count(*).          |       
|           3                |      
|           2                |       
-------------------

**Case2(incorrect count value)**:but so when you use below gorm-io as below, the count value will be 3:
```
DB.Where("departmentID = ?", 88)Group("departmentID").Count(&total)
```
 here finally total will be 3, the gorm-io send sql is : select count(*) from department, and executed result as below:
-------------------
|    count(*).          |       
|           3                |          
-------------------

## Motivation

The root cause is below code in **COUNT()** function to calculate the count value as below:
```
	tx.Statement.Dest = count
	tx = tx.callbacks.Query().Execute(tx)
	**if tx.RowsAffected != 1 {** // when the rowsAffected =1 in group by cases, it would not to use the RowsAffected value
		*count = tx.RowsAffected
	}
```

so the I suggested fixed solution: add checking statement include 'group by' or not, then to decide use the RowsAffected as count or not, detail fixed  code as below:
```
	tx.Statement.Dest = count
	tx = tx.callbacks.Query().Execute(tx)
	**_,isGroupBy := db.Statement.Clauses["GROUP BY"] // 加上是否是group by的判断**
	if tx.RowsAffected != 1 || **(tx.RowsAffected == 1 && isGroupBy)**{
		*count = tx.RowsAffected
	}
```

**Comment by tritueviet** [comment]
same issue

**Comment by jinzhu** [comment]
Fixed by https://github.com/go-gorm/gorm/pull/4885
