### ISSUE TITLE
migrate  not found column when use dbresolver 

### ISSUE THREAD

**Issue by nzlov** [go-gorm/gorm#4811]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/394

## Description

When using `dbresolver` to connect to `postgresql` to initialize the project, `automigrate` does not switch the database.
当使用`dbresolver`连接`postgresql`，进行项目初始化,`automigrate`没有切换数据库.

**Comment by jinzhu** [comment]
works as expected, it is not expected to auto migrate the replica db currently.
