### ISSUE TITLE
column reference is ambiguous when use gorm.Expr of OnConflict

### ISSUE THREAD

**Issue by nzlov** [go-gorm/gorm#4812]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/395

## Description

在`psql`里用多个字段约束进行`upsert`。
问题一：无法有效的绑定多个字段为约束
问题二：使用`gorm.Expr`进行增量更新时，出现字段无效

Use multiple field constraints for `upsert` in `psql`.
Problem 1: Cannot effectively bind multiple fields as constraints
Problem 2: When using `gorm.Expr` for incremental update, the field is invalid

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/143855296-57a26017-4f91-48eb-9064-b495fddc232f.png)
