### ISSUE TITLE
Whether to consider implementing a result set cache similar to mybatis

### ISSUE THREAD

**Issue by Junjiayy** [go-gorm/gorm#4813]
## Describe the feature

Cache the query result set and read data from the cache to reduce interaction with the database and improve performance

## Motivation

Using caching at the database layer can greatly improve business performance. I have tried to integrate and replace it with a plug-in, but what is frustrating is that I can only pass my parameters through `db.Set` or `context`. Obviously this is Very incorrect approach, does the gorm team consider implementing result set caching to make it easier for developers to use

**Comment by jinzhu** [comment]
you can implement this with callbacks, but GORM is not going to support this by default as it would be fragility
