### ISSUE TITLE
Connection leak on transactions

### ISSUE THREAD

**Issue by dmarkhas** [go-gorm/gorm#4818]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/396

## Description

When an error occurs in `FirstOrCreate` (for example, querying a non-existent table, but possibly in other scenarios such as invalid credentials, etc.) the connection never gets released which causes a massive leak of connections.

In `finisher_api.go:289`:

```go
	if tx = queryTx.Find(dest, conds...); queryTx.RowsAffected == 0 {
		if c, ok := tx.Statement.Clauses["WHERE"]; ok {
			if where, ok := c.Expression.(clause.Where); ok {
				tx.assignInterfacesToValue(where.Exprs)
			}
		}

		// initialize with attrs, conds
		if len(tx.Statement.attrs) > 0 {
			tx.assignInterfacesToValue(tx.Statement.attrs...)
		}

		// initialize with attrs, conds
		if len(tx.Statement.assigns) > 0 {
			tx.assignInterfacesToValue(tx.Statement.assigns...)
		}

		return tx.Create(dest)
	}
```

If `queryTx.Find()` encounters an error, that error is propagated over `tx.Error` into `BeginTransaction` in `transaction.go:7`:

```go
func BeginTransaction(db *gorm.DB) {
	if !db.Config.SkipDefaultTransaction {
		if tx := db.Begin(); tx.Error == nil {
			db.Statement.ConnPool = tx.Statement.ConnPool
			db.InstanceSet("gorm:started_transaction", true)
		} else if tx.Error == gorm.ErrInvalidTransaction {
			tx.Error = nil
		} else {
			db.Error = tx.Error
		}
	}
}
```

In this code, `db.Begin` does not return any error since starting a transaction succeeds (creating a new DB connection in the process), however `tx.Error` is not-nil from the `Find` step, so it never sets the "gorm:started_transaction" property, even though a transaction was in fact started.  
As a result, `CommitOrRollbackTransaction` assumes no transaction has been started, leading to no Commit / Rollback happening. 
Meanwhile, the transaction is still active in the DB and the connection is never getting released.

**Comment by longlihale** [comment]
@dmarkhas  thanks, already fixed it.
