### ISSUE TITLE
Save time.Time type data(local time) with pg timestamp(without timezone) type，fetched data is not correct(force marked as UTC)

### ISSUE THREAD

**Issue by FORWAARD** [go-gorm/gorm#4834]
## Your Question

when insert time.Time（with client timezone） data into pg timestamp(without timezone) column，then fetch it，get wrong data with UTC timezone 

## The document you expected this should be explained
I'm using  gorm v2 with postgresql 
```
go.mod
gorm.io/driver/postgres v1.1.2
gorm.io/gorm v1.21.16
```
and in application, I use timestamp (without timezone) to store data, like created_at,updated_at ...
the problme is: when fetch records from table, timestamp columns data force UTC.

example:
a 'users' table, insert a record in '2021-11-01 15:04:05'(client timezone Aisa/Shanghai), then fetch record, it become "2021-11-01 15:04:05 +0000 UTC" 

same question like this https://github.com/jackc/pgx/issues/924

env:
```
client:timezone Asia/Shanghai
dsn: "host=xxxx user=xxx password=xxx dbname=xxx search_path=xxxx port=xxx sslmode=disable TimeZone=Asia/Shanghai"
db:
SELECT current_setting('TIMEZONE')
------
Asia/Shanghai
```

```
type User struct {
	ID        int       `json:"id" gorm:"primarykey"`
	Name      string    `json:"name" gorm:"column:name"`
	CreatedAt time.Time `json:"created_at" gorm:"column:created_at"`
	UpdatedAt time.Time `json:"updaed_at" gorm:"column:updated_at"`
}
...
db.First(&user)
...
fmt.Println(user.CreatedAt)

actual: 2021-11-01 15:04:05 +0000 UTC
expect: 2021-11-01 15:04:05 +0800 CST (Asia/Shanghai)
```

## Expected answer

how to deal with this situation，any best practise？

**Comment by mkyc** [comment]
Can you try if providing `NowFunc` helps?

```golang
db, err := gorm.Open(connection, &gorm.Config{
	Logger: logger.Default.LogMode(logger.Info),
	NowFunc: func() time.Time {
		ti, _ := time.LoadLocation("Asia/Shanghai")
		return time.Now().In(ti)
	},
})
```

I used it in some other case and it helped me at least in tests.

**Comment by jackwootton** [comment]
@longlihale Why did you close this issue?

**Comment by longlihale** [comment]
@jackwootton  :astonished: sorry,because I saw that there was an answer and no reply, so  I thought this issue had been resolved :relieved:.  open it～

**Comment by FORWAARD** [comment]
@mkyc thx, very good solution :thumbsup:. I'll try in my next project ☺️

**Comment by rhuanpk** [comment]
I know this topic is already closed but... I really had a hard time figuring out how this was all working and finding a nice solution.

Finally, looking at the [GORM documentation](https://gorm.io/docs/connecting_to_the_database.html) I saw that it had [this link](https://github.com/go-sql-driver/mysql#loc) where we can pass the `loc` parameter in the connection string to set its default timezone.

Anyway, I hope this can still be useful to someone.

**Comment by bernardolm** [comment]
> postgres

Hi @rhuanpk! The issue was opened with a question about postgres timezone and the solution in your commented links is about a MySQL solution. :)

**Comment by rhuanpk** [comment]
Hi @bernardolm!

Ok that was a pretty embarrassing mistake, sorry. LOL!

But as I already said, I hope this helped someone, even if it was just an idea of how to proceed. :)
