### ISSUE TITLE
gorm  create 函数参数传递非指针bug

### ISSUE THREAD

**Issue by qifengzhang007** [go-gorm/gorm#4838]
###  GORM BUG  文件位置
> gorm/callbacks/create.go   111 行之前  

### 问题描述
```code
 
// bug 描述：用户调用 Create 函数插入数据时，如果传递的不是结构体指针，这里没有任何判断拦截，直接导致程序在后面的代码处赋值时发生panic
// 如果开发者没有自定义 recover  拦截中间件，程序直接奔溃。
// 不知道官方怎么看这个bug

//  111 行
switch db.Statement.ReflectValue.Kind() {

//   ***省略无关代码**

case reflect.Struct:
  _, isZero := db.Statement.Schema.PrioritizedPrimaryField.ValueOf(db.Statement.ReflectValue)
  if isZero {
	  db.Statement.Schema.PrioritizedPrimaryField.Set(db.Statement.ReflectValue, insertID)
  }
}

}



```

**Comment by GodYao1995** [comment]
> ### GORM BUG 文件位置
> > gorm/callbacks/create.go   111 行之前
> 
> ### 问题描述
> ```
>  
> // bug 描述：用户调用 Create 函数插入数据时，如果传递的不是结构体指针，这里没有任何判断拦截，直接导致程序在后面的代码处赋值时发生panic
> // 如果开发者没有自定义 recover  拦截中间件，程序直接奔溃。
> // 不知道官方怎么看这个bug
> 
> //  111 行
> switch db.Statement.ReflectValue.Kind() {
> 
> //   ***省略无关代码**
> 
> case reflect.Struct:
>   _, isZero := db.Statement.Schema.PrioritizedPrimaryField.ValueOf(db.Statement.ReflectValue)
>   if isZero {
> 	  db.Statement.Schema.PrioritizedPrimaryField.Set(db.Statement.ReflectValue, insertID)
>   }
> }
> 
> }
> ```

官方倒立看

**Comment by longlihale** [comment]
@qifengzhang007  这需要判断用户的model有没有主键/创建时间/更新时间这些字段,因为这些字段要回写回去,如果不是指针类型的就会panic～
