### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [go-gorm/gorm#4840]
## Your Question

Hi folks - we're happy users of gorm. There are new releases every now and then, but we're having a hard time understanding what changed. Are there any official release notes?

Currently, for example, we're thinking about upgrading from v1.21.13 to v1.22.2.

## The document you expected this should be explained

We found older release notes in two distinct documents:
- https://github.com/go-gorm/gorm/releases or https://github.com/go-gorm/gorm/tags
- https://gorm.io/docs/v2_release_note.html

Both of these pages are not maintained anymore. 

We could resort to reading the [code diffs](https://github.com/go-gorm/gorm/compare/v1.22.2..v1.21.13), but it's almost impossible for us to figure out what of it is breaking/bugfix/feature improvement.

There is also an issue raising the same question - https://github.com/go-gorm/gorm/issues/4317 - but the answers, pointing to the links above, are not maintained.

The sub-projects https://github.com/go-gorm/postgres and https://github.com/go-gorm/prometheus do also not have release notes.

## Expected answer

Any pointers to release notes or how we can figure out what changed in a new version.

**Comment by jinzhu** [comment]
Hello @MatthiasWinzeler

Thank you for your report, sorry for lacking the minor releases changelog, we don't have one mostly because of lacking of time ;(

Anyway, usually a new release like this won't introduce any breaking changes, and we should added all new features to our documents http://gorm.io

And yes, the changelog should be important, we will increase its priority in the future. 

Thank you.

**Comment by MatthiasWinzeler** [comment]
@jinzhu Thanks for your response!

FWIW, I think we're fine with figuring out _new features_ from the changelog. 

What we're afraid of is breaking changes that are introduced while upgrading a minor or patch version and we have no way to figure out.

I think if you highlight breaking changes somewhere (i.e. in the Github tag or release description) that would already serve the users a lot :)

**Comment by jinzhu** [comment]
In general, GORM provides go1 like compatibility promise, and won't provide breaking changes w/o API changes. (unless you are relying on a bug ;)

**Comment by MatthiasWinzeler** [comment]
@jinzhu that's great news, thanks!
