### ISSUE TITLE
updating boolean field

### ISSUE THREAD

**Issue by mehdipourfar** [go-gorm/gorm#4842]
https://github.com/go-gorm/playground/pull/398

Gorm does not include false booleans in queries when calling first or create

**Comment by jinzhu** [comment]
https://gorm.io/docs/update.html#Updates-multiple-columns

**Comment by mehdipourfar** [comment]
@jinzhu Doesn't first or create supposed to do the same thing? I want insert or update. And how is that FirstOrCreate works as expected on all the other fields except false booleans?

**Comment by mehdipourfar** [comment]
@jinzhu And also updates has the same bug.
