### ISSUE TITLE
Gorm crashes with two related tables. 

### ISSUE THREAD

**Issue by ori-amizur** [go-gorm/gorm#4843]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/399

## Description
Expect gorm not to crash and not have any errors (please look at the PR https://github.com/go-gorm/playground/pull/399)

The following is the result of the test:

./test.sh
git clone --depth 1 -b master https://github.com/go-gorm/gorm.git
Cloning into 'gorm'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 164 (delta 14), reused 35 (delta 4), pack-reused 0
Receiving objects: 100% (164/164), 175.97 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (14/14), done.
testing sqlite...
2021/11/08 14:54:57 testing sqlite3...
=== RUN TestGORM

2021/11/08 14:54:57 /home/oamizur/gorm/playground/main_test.go:15
[0.174ms] [rows:0] SELECT * FROM parents WHERE parents.deleted_at IS NULL
--- FAIL: TestGORM (0.00s)
panic: reflect: Field index out of range [recovered]
panic: reflect: Field index out of range

goroutine 10 [running]:
testing.tRunner.func1.2(0xd5d440, 0xed5100)
/usr/local/go/src/testing/testing.go:1144 +0x49f
testing.tRunner.func1(0xc000093980)
/usr/local/go/src/testing/testing.go:1147 +0x695
panic(0xd5d440, 0xed5100)
/usr/local/go/src/runtime/panic.go:971 +0x499
reflect.Value.Field(0xda9c40, 0xc000177400, 0x199, 0x4, 0x5, 0x7f136c89f278, 0x0)
/usr/local/go/src/reflect/value.go:854 +0x345
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func4(0xda9c40, 0xc000177400, 0x199, 0x0, 0x0, 0x531800)
/home/oamizur/gorm/playground/gorm/schema/field.go:450 +0xf7
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func16(0xda9c40, 0xc000177400, 0x199, 0xdfce40, 0xc00000fe90, 0x199, 0xc00000da40)
/home/oamizur/gorm/playground/gorm/schema/field.go:829 +0x488
gorm.io/gorm.(*Statement).SetColumn(0xc0004e9180, 0xc0001ef1f0, 0xa, 0xdfce40, 0xc00000fe90, 0xc0004fd5ed, 0x1, 0x1)
/home/oamizur/gorm/playground/gorm/statement.go:575 +0x83f
gorm.io/gorm.SoftDeleteDeleteClause.ModifyStatement(0xc0004bc000, 0xc0004e9180)
/home/oamizur/gorm/playground/gorm/soft_delete.go:135 +0x3b0
gorm.io/gorm.(*Statement).AddClause(0xc0004e9180, 0xee9578, 0xc0004bc000)
/home/oamizur/gorm/playground/gorm/statement.go:251 +0x99
gorm.io/gorm/callbacks.Delete.func1(0xc0004e68d0)
/home/oamizur/gorm/playground/gorm/callbacks/delete.go:123 +0x209
gorm.io/gorm.(*processor).Execute(0xc0001ec460, 0xc0004e68d0, 0xe06762)
/home/oamizur/gorm/playground/gorm/callbacks.go:130 +0x38f
gorm.io/gorm.(*DB).Delete(0xc0004e68d0, 0xd73420, 0xc000177400, 0xc0001bbe60, 0x1, 0x1, 0xc0004e68d0)
/home/oamizur/gorm/playground/gorm/finisher_api.go:365 +0x185
gorm.io/playground.TestGORM(0xc000093980)
/home/oamizur/gorm/playground/main_test.go:19 +0x34c
testing.tRunner(0xc000093980, 0xe29888)
/usr/local/go/src/testing/testing.go:1194 +0x203
created by testing.(*T).Run
/usr/local/go/src/testing/testing.go:1239 +0x5d8
FAIL gorm.io/playground 0.045s
FAIL

Crash happens when trying to delete from the table without soft delete

**Comment by jinzhu** [comment]
write it like:

```go
func TestGORM(t *testing.T) {
	db := DB.Clauses(clause.Locking{Strength: "UPDATE"}).Session(&gorm.Session{})
	var parents []*Parent
	err := db.Preload("Children").Find(&parents).Error
	if err != nil {
		t.Errorf("Failed, got error: %v", err)
	}
	err = db.Delete(&Child{}, "parent_id = 5").Error
	if err != nil {
		t.Errorf("Failed, got error: %v", err)
	}
}

```

refer https://gorm.io/docs/method_chaining.html
