### ISSUE TITLE
dsn parse error

### ISSUE THREAD

**Issue by nymbian** [go-gorm/gorm#4845]
When use sqlserver with password "E3pl2021#@!" report error:
failed to initialize database, got error parse "sqlserver://sa:E3pl2021": invalid port ":E3pl2021" after host

`dsn := "sqlserver://sa:E3pl2021#@!@" + host + ":1433?database=" + database`

**Comment by cute-angelia** [comment]
!!!  怎么解决

**Comment by yuangu** [comment]
我也遇到了，好像密码里有#就会有问题

I have also encountered it. It seems that there will be problems if there is # in the password。And The common special point is that all problems occur in MSSQL

The following is an example code:

```
    host:="sqlserver://sa:E3pl2021#@!@:localhost:1433"
	db, err = gorm.Open(sqlserver.Open(host), &gorm.Config{
			
		})

	if err != nil {
		log.Fatalf("Dbhost: %v, initDB failed：%s", host, err)
		return err
	}
```
