### ISSUE TITLE
Customized Time can not be saved into db #4848

### ISSUE THREAD

**Issue by jinfagang** [go-gorm/gorm#4853]
Customized Time can not be saved into db #4848

**Comment by jinfagang** [comment]
/ another Time, for json marshal unix timestamp
type Time time.Time

func (t *Time) UnmarshalJSON(data []byte) (err error) {
	num, err := strconv.Atoi(string(data))
	if err != nil {
		return err
	}
	// (todo) many this is UnixMilli 13 not 10
	*t = Time(time.Unix(int64(num), 0))
	return
}

func (t Time) MarshalJSON() ([]byte, error) {
	// return ([]byte)(strconv.FormatInt(time.Time(t).UnixMilli(), 13)), nil
	return ([]byte)(strconv.FormatInt(time.Time(t).UnixNano()/1e6, 10)), nil
}

// Value insert timestamp into mysql need this function.
func (t Time) Value() (driver.Value, error) {
	var zeroTime time.Time
	if time.Time(t).UnixNano() == zeroTime.UnixNano() {
		return nil, nil
	}
	return t, nil
}

// Scan valueof time.Time
func (t *Time) Scan(v interface{}) error {
	value, ok := v.(time.Time)
	if ok {
		*t = Time(value)
		return nil
	}
	return fmt.Errorf("can not convert %v to timestamp", v)
}
I have a Time for better serialized in json (client need this format)

So, made it, but it can not saved to DB;

type PresenceSession struct {
	// gorm.Model
	Id           string
	UserId       string
	Presence     string
	LastPresence Time
	LastUpdate   Time
}

**Comment by jinfagang** [comment]
It doesn't solved yet.

**Comment by Heliner** [comment]
> It doesn't solved yet.
看起来只是一个使用方式上面的问题，应该是`gorm`代码的关系不大。
`callbacks.go` 下第97行的`processor`执行时会调用reflect.ValueOf获取对应对应的值，包装对象Time获取的值和原始的time.Time获取的值时不同的（见代码output），可能你需要把`Time`强制转化为`time.Time`类型（想下面代码里面写的一样），然后再执行`update`等方法（不确定`gorm`是不是只支持基础的几个数据类型插入到数据库中）。
这里也是很奇怪，gorm好像当传入的类型有错误的时候不会返回对应的err，只是在表现上看不到数据库中记录的变化而已。
```golang
package main

import (
	"database/sql/driver"
	"fmt"
	"reflect"
	"strconv"
	"time"
)

type Time time.Time

func (t *Time) UnmarshalJSON(data []byte) (err error) {
	num, err := strconv.Atoi(string(data))
	if err != nil {
		return err
	}
	// (todo) many this is UnixMilli 13 not 10
	*t = Time(time.Unix(int64(num), 0))
	return
}

func (t Time) MarshalJSON() ([]byte, error) {
	// return ([]byte)(strconv.FormatInt(time.Time(t).UnixMilli(), 13)), nil
	return ([]byte)(strconv.FormatInt(time.Time(t).UnixNano()/1e6, 10)), nil
}

// Value insert timestamp into mysql need this function.
func (t Time) Value() (driver.Value, error) {
	var zeroTime time.Time
	if time.Time(t).UnixNano() == zeroTime.UnixNano() {
		return nil, nil
	}
	return t, nil
}

// Scan valueof time.Time
func (t *Time) Scan(v interface{}) error {
	value, ok := v.(time.Time)
	if ok {
		*t = Time(value)
		return nil
	}
	return fmt.Errorf("can not convert %v to timestamp", v)
}

//I have a Time for better serialized in json (client need this format)
//So, made it, but it can not saved to DB
type PresenceSession struct {
	// gorm.Model
	Id           string
	UserId       string
	Presence     string
	LastPresence Time
	LastUpdate   Time
}

func main() {
	timeWrapper := Time(time.Unix(int64(123809809), 0))
	timeWrapperTransfer := time.Time(timeWrapper)
	timeOrigin := time.Unix(int64(123809809), 0)
	fmt.Println(fmt.Sprintf("reflect:timeWrapper:%v,\ntimeWrapperTransfer:%v,\ntimeOrigin:%v\n", reflect.ValueOf(timeWrapper),
		reflect.ValueOf(timeWrapperTransfer), reflect.ValueOf(timeOrigin)))
}



// output ---------------
reflect:
timeWrapper:{0 62259406609 0xd6d660},
timeWrapperTransfer:1973-12-04 07:36:49 +0800 CST,
timeOrigin:1973-12-04 07:36:49 +0800 CST
// ----------------------
```

**Comment by jinfagang** [comment]
@Heliner 你好，你的意思是我代码不用改，只是我再存入数据库的时候强制的把Time转成time.Time？
但是这不行啊，因为gorm存入的就是：

db.Save(&Session)

而我session定义的是Time类别，没有办法强制转成time.Time

那么它到底为什么不能存入数据库呢？我想知道要改哪里使得他可以存入, 同时能兼顾我的自定义json需求

**Comment by longlihale** [comment]
https://github.com/go-gorm/datatypes
try to look it ?

**Comment by Heliner** [comment]
> session

可以给这个对象多定义一个`PresenceSessionGorm struct`，并且给`PresenceSession`添加一个`toGromObj()(PresenceSessionGorm)`方法，这样虽然不优雅，但是能够解决现在的问题，因为gorm框架本身是通过`reflect.ValueOf()`获取值的并没有留下任何类型转化的插槽，或者也可以看一下longlihale的解决方式，不过它的这种方式好像也需要你使用刚才的方法才能解决掉，因为你需要给这个struct新增自己的方法

```golang
type PresenceSessionGorm struct {
	// gorm.Model
	Id           string
	UserId       string
	Presence     string
	LastPresence time.Time
	LastUpdate   time.Time
}

func(session* PresenceSession) toGromObj()(PresenceSessionGorm){
......
}

// save session
psGorm := session.toGromObj()
db.save(&psGorm)
// 
```

**Comment by jinfagang** [comment]
@Heliner 那这个又怎么和我的自定义化json结合起来呢
