### ISSUE TITLE
how to set deleted_at is nil?

### ISSUE THREAD

**Issue by dybxin** [go-gorm/gorm#4855]
## Your Question

in  gorm v2 : how to  set deleted_at field is nil? is difflent in v1.

## The document you expected this should be explained

https://gorm.io/docs/delete.html

## Expected answer

i expected set deleted_at is nil.

**Comment by Kisesy** [comment]
https://gorm.io/docs/delete.html#Soft-Delete

**Comment by longlihale** [comment]
> ## Your Question
> in gorm v2 : how to set deleted_at field is nil? is difflent in v1.
> 
> ## The document you expected this should be explained
> https://gorm.io/docs/delete.html
> 
> ## Expected answer
> i expected set deleted_at is nil.
```
type DeletedAt sql.NullTime

// Scan implements the Scanner interface.
func (n *DeletedAt) Scan(value interface{}) error {
	return (*sql.NullTime)(n).Scan(value)
}

// Value implements the driver Valuer interface.
func (n DeletedAt) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return n.Time, nil
}
```
if ` !n.Valid ` will return nil
