### ISSUE TITLE
Query with an empty slice of primary keys

### ISSUE THREAD

**Issue by jackwootton** [go-gorm/gorm#4857]
## Describe the feature

The Gorm documentation for [Struct & Map Conditions][1] provides the following snippet for querying a table with a slice of primary keys

```go
// Slice of primary keys
db.Where([]int64{20, 21, 22}).Find(&users)
// SELECT * FROM users WHERE id IN (20, 21, 22);
```

However, if the slice is empty then all records are returned. Looking at the [source code][2] for the `Find` function I can see conditions are only added if `len(conds) > 0`

```go
// Find find records that match given conditions
func (db *DB) Find(dest interface{}, conds ...interface{}) (tx *DB) {
	tx = db.getInstance()
	if len(conds) > 0 {
		if exprs := tx.Statement.BuildCondition(conds[0], conds[1:]...); len(exprs) > 0 {
			tx.Statement.AddClause(clause.Where{Exprs: exprs})
		}
	}
	tx.Statement.Dest = dest
	return tx.callbacks.Query().Execute(tx)
}
```

This is the opposite of what my SQLite command line returns. If the condition is empty then no records are returned (because they all have a primary key)

```sql
-- no records returned
SELECT * FROM my_table WHERE id IN ();
```

  [1]: https://gorm.io/docs/query.html#Struct-amp-Map-Conditions
  [2]: https://github.com/go-gorm/gorm/blob/33bc56cbb5916173c670d28fb7fcf6a2bbd0b185/finisher_api.go#L157

## Motivation

I think it's more intuitive if Gorm mirrors the high-level behavior of basic SQL statements.

**Comment by jinzhu** [comment]
use `.Where("id IN ?", ids)` in that case.

**Comment by jackwootton** [comment]
Having looked into [including zero values](https://gorm.io/docs/query.html#Struct-amp-Map-Conditions) one big drawback is that the _literal_ field names are used and cannot be checked at compile time. Using `gorm.Model` structs ensures that any changes to the model are caught at compile time. 

Perhaps using a Go type alias will help making checking this easier

```go
type Condition map[string]interface{}

db.Where(models.Condition{"user": user, "id": id}).Updates(graph)
```

Then at least it's easier to find all uses of `Condition` and check they're updated if the underlying database changes.
