### ISSUE TITLE
use function FirstOrCreate(), always happened Duplicate entry error

### ISSUE THREAD

**Issue by sunnyyellow** [go-gorm/gorm#4859]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

my code like this：
`insertMysqlRes := mysqlHandler.
		Where(
			"uid=? and app_id=? and feature=?",
			featureStruct.UID,
			featureStruct.AppID,
			featureStruct.Feature).
		Assign(
			featureDao.FeatureStruct{
				Status:        featureStruct.Status,
				FeatureState:  featureStruct.FeatureState,
				FeatureExtend: featureStruct.FeatureExtend,
				UpdateTime:    featureStruct.UpdateTime}).
		FirstOrCreate(&featureStruct)`
the error is：
Duplicate entry '3694361011111111-60004-101_0001' for key 'uniq_feature'

**Comment by longlihale** [comment]
@sunnyyellow  hello,can you provide a demo in https://github.com/go-gorm/playground ?
