### ISSUE TITLE
Why doesn't 'Updates' update associations?

### ISSUE THREAD

**Issue by ReeceXW** [go-gorm/gorm#4860]
## Your Question

I'm trying to use the Updates method to update the current model and it's associations.
For example, I have a Client with one Address. I want to change the Client's Name field and the Address' Postcode field

```
type Client struct {
	gorm.Model

	Name    string
	Address Address
}
```
`map[Address:map[Postcode:Example] Name:etc]`
```
services.DB.Session(&gorm.Session{
    FullSaveAssociations: true,
}).Model(&Client{}).Where("id", c.Params("id")).Updates(values)
```

This only changes the fields in Client, not it's associated Address

## The document you expected this should be explained

https://gorm.io/docs/update.html

## Expected answer

This is how you update associations with Updates...

**Comment by longlihale** [comment]
hello, can you provide a demo in https://github.com/go-gorm/playground?
