### ISSUE TITLE
How to set the OnDelete constraint to an FK (1:M) for Composite Keys

### ISSUE THREAD

**Issue by allidoisace** [go-gorm/gorm#4873]
## Your Question

How to set the OnDelete CASCADE constraint to an FK (1:M) for Composite Keys?
Currently if the ParentObject is soft deleted, the ChildObject still exists.

```
type ParentObject struct {
  ID        int64 `gorm:"primarykey"`
  VID       int64     `gorm:"primaryKey;default:1"`
  
  ChildObjects        *[]*ChildObject  `gorm:"ForeignKey:ParentObjectID,ParentObjectVID;References:ID,VID;constraint:OnDelete:CASCADE;"`
}

type ChildObject struct {
  ID        int64 `gorm:"primarykey"`
  VID       int64     `gorm:"primaryKey;default:1"`

  ParentObjectID           *int64
  ParentObjectVID          *int64
}
```

## The document you expected this should be explained

https://gorm.io/fr_FR/docs/constraints.html

## Expected answer

When the ParentObject is soft deleted, the ChildObject should also be soft deleted.

**Comment by jinzhu** [comment]
`constraint:OnDelete:CASCADE` doesn't work with soft delete.
