### ISSUE TITLE
How do you copy a DB object?

### ISSUE THREAD

**Issue by seanballais** [go-gorm/gorm#4881]
## Your Question
How do you copy a `DB`? I tried doing the following:

```go
q := db.Model(&Model{}).Select("*")
r := q.Session(&gorm.Session{})
```

However, whenever I change `q` by adding additional clauses, `r` gets modified as well. Is there a way to do what I wanted to do? Or is this by design?

## The document you expected this should be explained

This should be explained in the [Sessions](https://gorm.io/docs/session.html) page of the official documentation website.

## Expected answer

I would like to know how to copy another `DB` object without having the original object affecting the copy.

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html

**Comment by psahni** [comment]
Hello 
I have same question
this is not solved

**Comment by davidlbudiman** [comment]
@psahni Jinzhu has posted the article to copy DB object without affecting the original object. Just read through it first.

**Comment by zyb-992** [comment]
Does `r := q.Session(&gorm.Session{NewDB: true})` solve your problem?

**Comment by Hello-World-0X** [comment]
tx1 := db.Model(&Model{}).Where(a=a1)
tx2 := tx1.Session(&gorm.Session{})
tx1 = tx1.Where(b=b1)


if i use tx2 , tx2  = tx2.Where(c=c1).Select(xx).Error 
it will be SELECT * from xxx WHERE a =a1 and b=b1 and c=c1   
tx1's condition after tx2 session will be add to tx2
