### ISSUE TITLE
关于创建记录零值的文档说明疑惑

### ISSUE THREAD

**Issue by itmisx** [go-gorm/gorm#4892]
```
插入记录到数据库时，默认值 会被用于 填充值为 零值 的字段。

注意 像 0、''、false 等零值，不会将这些字段定义的默认值保存到数据库。您需要使用指针类型或 Scanner/Valuer 来避免这个问题
```

关于文档中创建数据的说明，感觉很困惑。第一句话是说，定义的default会填充零值字段。第二句又说不能。如果第二句是说`default:0`等零值类型的默认值定义不能保存到数据库的话，我试过是可以的。
如定义：
```
type A struct{
   id int
   DeletedAt  int64   `gorm:"column:deleted_at;type:bigint DEFAULT NULL;default:0;comment:删除时间"``
}
```
创建操作：
```
Create(&A{
     DeletedAt:0
})
```
是可以保存到数据库的，DeletedAt成功保存为0。
所以一直没搞清楚，
```
注意 像 0、''、false 等零值，不会将这些字段定义的默认值保存到数据库。您需要使用指针类型或 Scanner/Valuer 来避免这个问题
```
这句的意思。

**Comment by Anveena** [comment]
我猜测:
DeletedAt  int64   `gorm:"column:deleted_at;type:bigint DEFAULT NULL;default:0;comment:删除时间"``
这里的default你定义的是0所以保存的是0
int,string,float无法用!=nil判断是否进行过set的,
如果不按gorm实现.会出现大混乱.
举个例子
type A struct{
   id int
   count int
}
你刚好有个count:0要插入,但是你A{}之后的count也是0
如果判断你的count==0则写入默认值(default字段定义的,未必是0),那你要写的0就会被这个默认值覆盖
如果不这么判断 就只能通过ptr != nil 来分析你是否对这个值set过,所以您需要使用指针类型或 Scanner/Valuer 来避免这个问题

**Comment by latiao17** [comment]
我也很奇怪，只说create方法调用的时候
insert into会怎么样

```go

type User struct {
  ID   int64
  Name string
  Age  int64
}

db.Create(&User{})

会产生insert into (name, age) values ('', 0)

```

```go

type User struct {
  ID   int64 
  Name string
  Age  int64 `gorm:"column:age;default:0"`
}

db.Create(&User{})

会产生insert into (name, age) values ('', 0)

```

<img width="797" height="106" alt="Image" src="https://github.com/user-attachments/assets/2aad1e3b-5fef-432a-981b-c81cbf22b558" />

其实还是不理解，为什么。

insert的时候，基本类型不管你string是""还是int是0，还是default定义了0或''，一样insert
