### ISSUE TITLE
简单的添加一个表名和struct映射关系.

### ISSUE THREAD

**Issue by Anveena** [go-gorm/gorm#4893]
## Describe the feature

判断表是否存在以及创建表时,是否可以再次在内部调用Tabler.TableName()

## Motivation

我们的实际场景是每天会产生一张表记录当天的一些归档数据,比如一些弹幕/日志之类.
所以需要0点更新结构体对应的表.

当我们0点调用表是否存在/创建表时,都不能满足需求.
现有的方式不管是Scopes还是db.Table,都不太适合对应的场景.

**Comment by Anveena** [comment]
也许能加这么一个简单的函数.也不会破坏现有结构的完整性.
func (db *DB) ResetTable(dest interface{}) {
	value := reflect.ValueOf(dest)
	if value.Kind() == reflect.Ptr && value.IsNil() {
		value = reflect.New(value.Type().Elem())
	}
	modelType := reflect.Indirect(value).Type()
	db.cacheStore.Delete(modelType)
}
请您告诉我这样做是否不会引发其他的问题,如果不会的话,我可以先fork一个使我们的项目可用.测试了一下,觉得gorm比xorm方便很多,所以安排把所有xorm的代码都改了.结果这里出现了问题,比较着急解决.所以无论您是否打算加入这个功能,都请告知下这样做是否有其他风险

**Comment by jinzhu** [comment]
我感觉 Scope 应该可以解决你的问题，可以参考下  https://gorm.io/docs/scopes.html#Dynamically-Table，我们也有类似的场景。

你这样子有个风险就是如果这个Model有关联的话，就会有问题。

**Comment by Anveena** [comment]
> 我感觉 Scope 应该可以解决你的问题，可以参考下 https://gorm.io/docs/scopes.html#Dynamically-Table ，我们也有类似的场景。
> 
> 你这样子有个风险就是如果这个Model有关联的话，就会有问题。

我尝试了Scope,但是如果用Scope的话 每次操作都需要调用Scope的那个函数,作为日志/弹幕这种表,基本上每天都2 3亿条记录.感觉实在是影响性能..
