### ISSUE TITLE
Save() 会覆盖软删除

### ISSUE THREAD

**Issue by Aoang** [go-gorm/gorm#4894]
### 描述
问题比较简单，数据库中某条记录被软删除，如果使用 Save() 保存数据，会恢复软删除。

场景出现在多协程中，某个协程删除了一条记录，另一个协程在没有使用事务的情况下（执行时间比较长）保存数据。

按照行为来定义的话，Save() 应该会报错，而不是直接保存。

### Code
```go

type Model struct {
	ID        uint64         `gorm:"primaryKey" json:"id" `
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
}

type Port struct {
	Model

	Name     string    `json:"name"`
}


var db *gorm.DB

func main() {
	p := &Port{Name: "name"}
	if err := db.Create(p).Error; err != nil {
		fmt.Println(err)
	}
	if err := db.Delete(&Port{Model: Model{ID: p.ID}}).Error; err != nil {
		fmt.Println(err)
	}
	if err := db.Save(p).Error; err != nil {
		fmt.Println(err)
	}
	fmt.Println(p)
}
```

### 逻辑
1. 创建一条记录
2. 删除这条记录
3. 使用 Save() 保存数据

预期：报错，提示数据不存在
结果：数据保存成功，且软删除无了

**Comment by longlihale** [comment]
https://gorm.cn/zh_CN/docs/update.html#%E4%BF%9D%E5%AD%98%E6%89%80%E6%9C%89%E5%AD%97%E6%AE%B5
Save 是保存数据,如果数据存在就会更新,不存在就会创建.传递的p里面的Del的标示位还是未删除～

**Comment by Aoang** [comment]
> https://gorm.cn/zh_CN/docs/update.html#%E4%BF%9D%E5%AD%98%E6%89%80%E6%9C%89%E5%AD%97%E6%AE%B5 Save 是保存数据,如果数据存在就会更新,不存在就会创建.传递的�P里面的Del的标示位还是未删除～

看了看 Save() 的行为，的确会在不存在的情况下创建。但是我说的问题依旧存在。

-------

软删除的行为定义下，数据被软删除之后，ORM 应当认定为不存在此条数据，Save() 的行为应该是

1. 尝试更新数据，找不到对应的记录
2. 尝试创建记录，主键冲突

-------

但目前的行为是

1. 尝试更新数据，找到对应的被软删除的记录
2. 更新记录。此时因为传递给 Save() 的参数中 DeletedAt 为 nil，导致软删除的记录被恢复了

如果 Save() 能在不覆盖 DeletedAt 的情况下更新数据倒是符合需求，但是不符合 Save() 的定义了。

**Comment by longlihale** [comment]
@Aoang already fix, thank you.
