### ISSUE TITLE
Is it possible to nest transactions in gorm Begin()?

### ISSUE THREAD

**Issue by DaisukeMatsumoto0925** [go-gorm/gorm#4898]
## Your Question

Is it possible to nest transactions in gorm Begin()?

I would like to reset the DB after running the API for integration testing.

In the API, transactions are used.

That is, the Begin() method is opened twice.

A simple reproduction of it is as follows.

```go
    db := rdb.NewRDB()
    tx := db.Begin()
    if err := tx.Begin().Error; err != nil {
        fmt.Println(err)
    }
```

The result will output the following error

```go
no valid transaction
```

Is it possible to use Begin() multiple times to nest transactions?

## The document you expected this should be explained

Expected no error and when I used by TestHelper like below

```go
func SetupRDB(t *testing.T) *gorm.DB {
	t.Helper()
	db := rdb.NewRDB()
	tx := db.Begin()
	t.Cleanup(func() {
		fmt.Println("Rollback!!")
		tx.Rollback()
	})
	return tx
}
```

it is expected rollback all query .

## Expected answer

How to rollback for test DB or Please Answer Can We nest transaction by `Begin()` instead of  `db.Transaction(func(tx *gorm.DB) error {` .

**Comment by jinzhu** [comment]
Use `SavePoint`
