### ISSUE TITLE
person struct生成people表？

### ISSUE THREAD

**Issue by zhongsdjn** [go-gorm/gorm#4905]
你好！请问使用gorm 定义了type Person struct {Name string} 其它没什么指定  为什么AutoMigrate后生成的表是people呢？  看介绍说是默认为复数形式  不过虽然people符合person的复数形式  但感觉这样不可预料了！

Hi！Why define a struct `type Person struct {Name string}` ,AutoMigrate table is people?

**Comment by jinzhu** [comment]
https://gorm.io/docs/gorm_config.html#NamingStrategy
