### ISSUE TITLE
在大规模批量插入数据到数据库的时候注意到下行带宽比上线带宽还要大

### ISSUE THREAD

**Issue by longrbl** [go-gorm/gorm#4910]
## Your Question
我在本地或线上进行大规模的批量插入数据，我注意到我的带宽显示 下行数据比上行数据还要大
下面是我连接数据库的配置
`
db, err := gorm.Open(mysql.Open("root:*****@tcp(*****:3306)/tets?charset=utf8mb4&parseTime=True&loc=Local"), &gorm.Config{
		SkipDefaultTransaction: true,
		PrepareStmt:            true,
		NamingStrategy: schema.NamingStrategy{
			SingularTable: false,
		},
		DisableAutomaticPing:                     true,
		DisableForeignKeyConstraintWhenMigrating: false,
	})
	db.Use(dbresolver.Register(dbresolver.Config{}). //连接池
		SetConnMaxIdleTime(time.Hour).
		SetConnMaxLifetime(24 * time.Minute).
		SetMaxIdleConns(100).
		SetMaxOpenConns(200))
这里是我插入数据库的格式和执行语法
var data =make([]user,0)
生成要写入的逻辑代码
db.Table("yii_client_users_subarea").Create(&data )

`

是不是在成功写到数据内mysql服务器会返回大量的数据包导致？
![image](https://s3.bmp.ovh/imgs/2021/12/8a2897e665b7235e.png)

**Comment by jinzhu** [comment]
> 是不是在成功写到数据内mysql服务器会返回大量的数据包导致?

maybe debug by yourself... I don't think this is a question for GORM.
