### ISSUE TITLE
Is there an an Include function (opposite of Omit) ?

### ISSUE THREAD

**Issue by 1mike12** [go-gorm/gorm#4912]
## Your Question

Is there an opposite to Omit?  Pretty much every server will have a User model with a password field. Usually we would write something like :

```go
type User struct {
	Id                          string            `json:"id,omitempty" gorm:"primary_key"`
	Password                    string            `json:"password,omitempty" gorm:"-"`
}
```

But in the times that you actually need to compare the password on logins or to update the password on password change, how would we do that? Right now it seems like i would need to write omit everywhere on user queries except for the 2 places where I actually want it included. 

## Expected answer

Write something like `db.Include("password").First(&user)`

**Comment by longlihale** [comment]
https://gorm.io/zh_CN/docs/update.html#%E6%9B%B4%E6%96%B0%E9%80%89%E5%AE%9A%E5%AD%97%E6%AE%B5

**Comment by jinzhu** [comment]
Select
