### ISSUE TITLE
postgresql: reset schema name

### ISSUE THREAD

**Issue by MariaOrbitsoft18** [go-gorm/gorm#4913]
## GORM Playground Link

https://github.com/MariaOrbitsoft18/playground/pull/1 (this link for bot only)

0. Playground doesn't work:
After cloning the report and upping the docker container, I launched the ./test.sh as it was written.
```
$ ./test.sh
git clone --depth 1 -b master https://github.com/go-gorm/gorm.git
Cloning into 'gorm'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 164 (delta 13), reused 40 (delta 4), pack-reused 0
Receiving objects: 100% (164/164), 176.93 KiB | 2.56 MiB/s, done.
Resolving deltas: 100% (13/13), done.
# gorm.io/playground
./db.go:73:4: unknown field 'DefaultTableNameHandler' in struct literal of type gorm.Config
```
## Description

1. The main issue was with schemas in postgresql (I'm not able to show the playground URL).
```go
// table_name.go

type Model struct {
    // Fields list
}
func (m *Model) TableName() string {
    return "table_name"
}
```
GORN config contains:
```go
&gorm.Config{
    // ...
    NamingStrategy: schema.NamingStrategy{
        TablePrefix: "my_schema.",
        SingularTable: true,
    },
}
```

Everything is ok (???).

Now, https://github.com/go-gorm/gorm/blob/master/schema/schema.go#L124
This line returns right value "my_schema.table_name".
https://github.com/go-gorm/gorm/blob/master/schema/schema.go#L125
This condition is true because the model contains the "TableName" method.
https://github.com/go-gorm/gorm/blob/master/schema/schema.go#L126
This line reset table name to table name without schema name:
```go
tableName = tabler.TableName()
```

I spent a lot of time searching for the right solution to specifying schema name and thinking where I did a mistake.
It is not a my decision of models naming, I just continue developing of the project. Sure, I can just rename table models name and do not use the "TableName" method. But fix this on your side too.

GORM: 1.22.4

**Comment by MariaOrbitsoft18** [comment]
https://github.com/MariaOrbitsoft18/playground/pull/1 (this link for bot only)
I can't send you real PR cause of the test.sh failed.

**Comment by magicMustard** [comment]
@jinzhu - Sorry to tag you, but this has been closed where I don't agree that it should've been.

If calling the Table Name func above is resetting the output it needs to be investigated.

**Comment by MariaOrbitsoft18** [comment]
> 

Then, the TableName should return table name with schema name? Why?
The Type Name and the Table Name are in the same file. They have the same rights and should with the same way, correct? The Table Name shouldn't return table name with schema name. The schema name should be specified in the Config.
