### ISSUE TITLE
or condition in one condition  sql error

### ISSUE THREAD

**Issue by qianweirong** [go-gorm/gorm#4914]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/411

## Description

or condition在只有一个条件的情况下，生成SQL存在问题。

```
func TestGORMorCondition(t *testing.T) {
	user := User{Name: "jinzhu"}
	DB.Create(&user)

	ret := make([]*User, 0)
	id := []uint32{1}
	db := DB
	for _, id := range id {
		db = db.Or("id = ?", id)
	}
	db.Find(&ret)
}
```

生成的执行SQL如下:
![image](https://user-images.githubusercontent.com/14146197/145511291-d8d60757-44e8-41b2-96ed-34f887058113.png)

 
这段代码在判断or条件时，是否存在问题
![image](https://user-images.githubusercontent.com/14146197/145511090-6412950c-393b-4e03-9272-4c06d42dc2c7.png)

**Comment by longlihale** [comment]
https://gorm.cn/zh_CN/docs/advanced_query.html#Group-%E6%9D%A1%E4%BB%B6

**Comment by qianweirong** [comment]
这不符合预期吧。正常的语句应该是deleted_at IS NULL and id = 1。deleted_at是软删除标志位，如果条件变成deleted_at IS NULL or id = 1，那不是表中任意一条没有删除的数据都可以满足需求了。而且，在v1版本中，生成的SQL就是deleted_at IS NULL and id = 1。
