### ISSUE TITLE
DB.Set() doesn't work with associations

### ISSUE THREAD

**Issue by awmcclain** [go-gorm/gorm#4919]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/413
## Description

The docs (https://gorm.io/docs/settings.html) explicitly recommend using `DB.Set()` in order to pass data to hooks for association. It doesn't work -- the Statement pointer is still duplicated so Get() always fails with associations.

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/154808695-03adb41f-3864-4f30-880c-e5c105d60dc0.png)

works for me, seems there is an typo in the PR.

**Comment by awmcclain** [comment]
@jinzhu I updated the playground code -- I thought this was more general but it seems like it only affects custom join tables.
