### ISSUE TITLE
gorm cant detect proper foreign key in case of field embedding

### ISSUE THREAD

**Issue by gstarikov** [go-gorm/gorm#4920]
https://github.com/go-gorm/playground/pull/414

Hi, gorm cant detect proper foreign key in case of field embedding.
How to fix it?
```
type A struct {
	ID uint
}

type B struct {
	A `gorm:"embedded"`
}

type C struct {
	ID uint
	B  B
}

func Migrate(db *gorm.DB) error {
	return db.AutoMigrate(
		B{},
		C{},
	)
}

...

invalid field found for struct models.C's field B: define a valid foreign key for relations or implement the Valuer/Scanner interface
panic: interface conversion: interface {} is models.C, not string [recovered]
	panic: interface conversion: interface {} is models.C, not string
```

**Comment by jinzhu** [comment]
Hi @gstarikov 

In your issues, the problem is not caused by embedding, but B, C doesn't have a valid foreign key definition. 

Checkout how to define a valid belongs to, has one association from https://gorm.io/docs/has_one.html
