### ISSUE TITLE
List 3rd-party pure-Go SQLite driver in GORM docs

### ISSUE THREAD

**Issue by glebarez** [go-gorm/gorm#4922]
## Describe the feature

I am maintaining a fully-tested pure-Go SQLite driver for GORM (https://github.com/glebarez/sqlite)
The driver's CI pipeline dynamically embeds latest test-base (12k+ tests) of GORM to ensure compatibility. Testing is run against two latest major releases of Go (currently 1.16, 1.17) in following environments:
	•	Linux
	•	Windows
	•	MacOS

I also provide a technical PR proving test compatibility: https://github.com/go-gorm/gorm/pull/4921
@jinzhu, may I kindly ask you to list it as a compatible cgo-free Sqlite driver for GORM in docs?

## Motivation

This has been already requested multiple times in different issues.

## Related Issues

- https://github.com/go-gorm/gorm/issues/4101
- https://github.com/go-gorm/gorm/issues/4173

**Comment by Banyc** [comment]
@glebarez your driver works perfectly for me! This driver should be chose as default.
