### ISSUE TITLE
达梦数据库建表语句中添加不了注释，需要像建索引需要一个变量判断建表后添加注释

### ISSUE THREAD

**Issue by xiyichan** [go-gorm/gorm#4923]
## Describe the feature
我目前在开发达梦数据库的驱动，需要添加注释的时候报错，看说明书时发现达梦数据库不能在建表语句中增加注释，
需要像源码中像创建索引的时候需要一个变量判断。

**Comment by jinzhu** [comment]
Does it support create index when creating table? if yes, write the driver like the postgres one?

**Comment by xiyichan** [comment]
> Does it support create index when creating table? if yes, write the driver like the postgres one?

不支持建表语句里面建立索引，我尝试用postgres的createtable尝试，并不能运行。

**Comment by xiyichan** [comment]
目前已经解决了列注释了

**Comment by jinzhu** [comment]
还有问题么？

**Comment by xiyichan** [comment]
> 还有问题么？

目前没有，我关闭issue吧
