### ISSUE TITLE
中文文档中，curd接口的查询，指定结构体查询字段，注释可能写错了

### ISSUE THREAD

**Issue by Frequency-Melody** [go-gorm/gorm#4927]
## Your Question
中文文档中，curd接口的查询，指定结构体查询字段，注释可能写错了
文档：
```
db.Where(&User{Name: "jinzhu"}, "name", "Age").Find(&users)
// SELECT * FROM users WHERE name = "jinzhu" AND age = 0;
```
注释中写到 `AND age = 0` 应该不是`age = 0`，而且零值会忽略的。

## The document you expected this should be explained
有空可以看看是不是有问题，修改一下。
希望文档可以加一个评论功能（不过也不太可能，哈哈哈）

**Comment by Frequency-Melody** [comment]
主要是我不知道在哪里反馈文档的问题，在这里反馈可能打扰了。

**Comment by jinzhu** [comment]
The document is correct, the latest version support this syntax.
