### ISSUE TITLE
Circular reference in model causes app freeze

### ISSUE THREAD

**Issue by LouisSayers** [go-gorm/gorm#4935]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/420

## Description
Hey there! I've just started using Gorm and finding it really great, but I quickly ran into the following issue:

I have two models that reference each other (A -> B and B -> A).

The database modelling supports this, however when my models are configured in this way, a save on the model ends up causing the app to freeze.

## Expected result
The model that is being saved is indeed saved, and the application does not freeze.

Thanks for your help!

**Comment by awmcclain** [comment]
We're running into the same issue. Super frustrating.

**Comment by jinzhu** [comment]
Fixed in PR #5140
