### ISSUE TITLE
当表无索引，Preload大量数据时，会很慢-比直接查询赋值慢

### ISSUE THREAD

**Issue by eyouhi** [go-gorm/gorm#4942]
```go
tx.Debug().where("addr in ?","Peking").Preload("House").Find(&users)
```
mssql驱动，当users数量大于8000时，花费了超过50秒。
然而，直接查询相应的House花费时间小于200毫秒
自己赋值用时不超过200毫秒

**Comment by longlihale** [comment]
这种情况可以先用 
- gorm 的 open-tracing 看下 SQL 执行的情况,确定一下是不是SQL 执行的慢还是 Gorm 慢
- 然后再用 pprof 二次确定一下 .
