### ISSUE TITLE
How to JSON type field with MSSQL

### ISSUE THREAD

**Issue by Peelz** [go-gorm/gorm#4947]
## Your Question

How to use JSON field with MSSQL database

## The document you expected this should be explained

https://gorm.io/docs/v2_release_note.html#DataTypes-JSON-as-example

## Expected answer

Plugin, Solution, or it does not work with Gorm.

**Comment by longlihale** [comment]
https://github.com/go-gorm/datatypes#json, It is not supported by MSSQL, you can try to define a custom json type.
