### ISSUE TITLE
mysql decimal save accuracy problem

### ISSUE THREAD

**Issue by LFXiaoFei** [go-gorm/gorm#4954]
## Your Question

go code:
`tx.Model(order).Debug().Updates(map[string]interface{}{"orderhy_fundrate": gorm.Expr("orderhy_fundrate + ?", lastFundRate), "orderhy_frtime": lastFundRateTime})`

sql debug:
`UPDATE `order` SET `orderhy_frtime`=1640332800000,`orderhy_fundrate`=orderhy_fundrate + 0.000100 WHERE `order_id` = 13`

column:
`orderhy_fundrate` decimal(60,20) NOT NULL

mysql data:
orderhy_fundrate: 0.00030000000000000000 => 0.00039999999999999996

Execute in MySQL is ok,but exec in go code is not ok?

## Expected answer

mysql data:
orderhy_fundrate: 0.00030000000000000000 => 0.00040000000000000000

**Comment by longlihale** [comment]
@LFXiaoFei hello, can you provide a demo in https://github.com/go-gorm/playground ？

**Comment by LFXiaoFei** [comment]
> @LFXiaoFei hello, can you provide a demo in https://github.com/go-gorm/playground ？

DB is MySQL，Tables is created by gotm.AutoMigrate.

go codes:
`
// model
type Order struct {
	OrderID         int64   `gorm:"column:order_id;not null;PRIMARY_KEY;AUTO_INCREMENT;index:order_id_idx;"` // order id
	OrderHYFundRate float64 `gorm:"column:orderhy_fundrate;type:decimal(60,20);not null"`                    // 合约订单资金费用合计
	OrderHYFRTime   int64   `gorm:"column:orderhy_frtime;type:bigint(20);not null"`   
}

// update model row
tx.Model(order).Debug().Updates(map[string]interface{}{"orderhy_fundrate": gorm.Expr("orderhy_fundrate + ?", lastFundRate), "orderhy_frtime": lastFundRateTime})
`
orderhy_fundrate old value is 0.00030000000000000000
Exec in Navicat is 0.00040000000000000000,but with gorm in the code,the value is 0.00039999999999999996

**Comment by halfcrazy** [comment]
```go
package main

import (
	"fmt"
	"math/big"
)

func main() {
	var (
		a float64
		b float64
		c float64
	)
	a = 0.00030000000000000000
	b = 0.000100
	c = a + b
	a1 := big.NewFloat(a)
	fmt.Println(a, a1)
	b1 := big.NewFloat(b)
	fmt.Println(b, b1)
	a1.Add(a1, b1)
	fmt.Println(c, a1.String())
}
```
Looks like result overflow.

**Comment by jinzhu** [comment]
float should not be used for in this case, and GORM can't help on that.
