### ISSUE TITLE
Callback return error and stop the flow

### ISSUE THREAD

**Issue by haijianyang** [go-gorm/gorm#4955]
## Your Question

Now,  when I use callback I don't know how to stop the db session if there is error. 

```go

//  I want stop insert sql to db when callback has error
db.Create(&Account{})

// Before create.
pg.Callback().Create().Before("gorm:create").Register("iam:before_create", func BeforeCallback(db *gorm.DB) {
	//  Do something

	// When there is error I want to return the error and stop this db session.
});
```

If not, what other ways can I achieve this demand.

**Comment by longlihale** [comment]
> ## Your Question
> Now, when I use callback I don't know how to stop the db session if there is error.
> 
> ```go
> //  I want stop insert sql to db when callback has error
> db.Create(&Account{})
> 
> // Before create.
> pg.Callback().Create().Before("gorm:create").Register("iam:before_create", func BeforeCallback(db *gorm.DB) {
> 	//  Do something
> 
> 	// When there is error I want to return the error and stop the this db session.
> });
> ```
> 
> If not, what other ways can I achieve this demand.

```
db.AddError(err)
return 
```
because  have err, other callback will not run.
