### ISSUE TITLE
sqlite  AutoMigrate时报错converting argument $1 type: unsupported type clause.Expr, a struct 

### ISSUE THREAD

**Issue by Refuel-ZL** [go-gorm/gorm#4960]
## Description
在v1.22.4报错：gorm.io/driver/sqlite@v1.1.4/migrator.go:108 sql: converting argument $1 type: unsupported type clause.Expr, a struct
降到v1.22.3正常的

```
CREATE TABLE `tb_sys_menu` (
  "id" integer primary key autoincrement,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` integer NOT NULL DEFAULT 0,
  `updated_by` integer NOT NULL DEFAULT 0,
  `status` tinyint(1) NOT NULL,"memo" varchar(64),
  `parent_id` integer NOT NULL,
  "url" varchar(72),
  `name` text NOT NULL,
  `sequence` integer NOT NULL,
  `menu_type` tinyint(1) NOT NULL,
  `code` text NOT NULL,
  "icon" varchar(32),
  "operate_type" varchar(32) NOT NULL 
)
```
执行AutoMigrate动作：
![image](https://user-images.githubusercontent.com/22957560/147452852-9c25050d-d9dc-4dd4-b447-4b878f3dce72.png)

在执行"INSERT INTO `tb_sys_menu__temp` ...."时 
![image](https://user-images.githubusercontent.com/22957560/147453056-0f5695dd-147c-4847-80e7-264d288a0e09.png)
使用了并不需要的clause.Expr Vars 导致出错
![image](https://user-images.githubusercontent.com/22957560/147453098-cb06a6d2-8b33-4a5c-8ab6-89f059769df0.png)

**Comment by longlihale** [comment]
提了一个可以复现的demo 放在 https://github.com/go-gorm/playground 吧～

**Comment by unknwon** [comment]
For anyone comes here, update github.com/go-gorm/sqlite to 1.3.2 fixes this.
