### ISSUE TITLE
What are the differences between pointer types and normal types

### ISSUE THREAD

**Issue by fncolon** [go-gorm/gorm#4965]
## Your Question

From https://gorm.io/docs/models.html#Declaring-Models as we see Name have a string types but Email have a *string types, but what is the difference technically?

## The document you expected this should be explained

https://gorm.io/docs/models.html#Declaring-Models

## Expected answer

Technical differences

**Comment by Asteriskdev** [comment]
In GO a pointer can be nil but a string cannot.  GORM translates nil values to NULL when inserting, updating, etc.  It appears the email field in this struct is meant to represent a value that can be NULL in the model's corresponding column in the Users table.

**Comment by fncolon** [comment]
Thank you @Asteriskdev
