### ISSUE TITLE
Create View feature is missing, kind of very important

### ISSUE THREAD

**Issue by aukgit** [go-gorm/gorm#4966]
# Create View feature with Gorm

## Describe the feature

```
  db.
   View.
    CreateOrUpdate().
    Tables(....tables Names ). // strings
    Entities(....tables Names ). // interfaces 
    Select(columNames...). // 5 or 6 columns it is optional
    Join(joinClause).
    Alias(Entity, map[string]string{})
    Where(...., ...).
    ViewName("Give it a name"). // Optional, could come from tables or be placed
    Compile() // finisher method, builder, ends the chain
```

## Motivation

Database views are easily queried on compiled join queries. Currently, the framework doesn't support joins properly. It supports but requires manual work. If we have a view creation option it will reduce the work and query execution and improve the performance

## Related Issues

- [how to use gorm to create mysql view? · Issue #4617 · go-gorm/gorm](https://github.com/go-gorm/gorm/issues/4617)

## Tags

@riadevatix

## Keywords

View, ViewCreation, JoinFeauture, SqlInjection

**Comment by longlihale** [comment]
thanks, It's a good idea, but maybe need to think about how to support it. :stuck_out_tongue:

**Comment by nafeem-evatix** [comment]
@jinzhu and @ghost This should be a priority

**Comment by sulthonzh** [comment]
Absolutely cannot wait for these features!

**Comment by loeffel-io** [comment]
+1

**Comment by devav2** [comment]
Please prioritize this for the upcoming releases.

**Comment by egandro** [comment]
Is there any progress on this?

**Comment by a631807682** [comment]
Already implemented in https://github.com/go-gorm/gorm/pull/6097
