### ISSUE TITLE
FindInBatches does not work on []map[string]interface{} objects

### ISSUE THREAD

**Issue by mikhail-bigun** [go-gorm/gorm#4967]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/422
## Description
Originally encountered such misfunctionality using Postgres. But playground showed that it is not a db dependent issue.

I had such case:

Given we have N rows in a DB.
We need to select those object rows in batches using undeclared struct by passing []map[string]interface{} to FindInBatches() function signature.
Expect: rows correctly scanned and mapped in []map[string]interface{}
Received: error "model value required"

**Comment by longlihale** [comment]
hello, `FindInBatches ` need  use `primaryKey` sort . if only use `Table()`, it can't sort, so return err `model value required`.

**Comment by longlihale** [comment]
you can use `find` to instead it.

**Comment by mikhail-bigun** [comment]
ok, got it, sadly that it is not working out of the box, but anyway, thanks for a response!
