### ISSUE TITLE
How to implement where clause "WHERE MONTH(created_at) BETWEEN '10' AND '11' AND YEAR(r.created_at) = '2021'"

### ISSUE THREAD

**Issue by muh-hizbe** [go-gorm/gorm#4970]
## Your Question

How to implement `WHERE MONTH(created_at) BETWEEN '10' AND '11' AND YEAR(r.created_at) = '2021'` using GORM ?

**Comment by longlihale** [comment]
- Elegant solution: you can self define clause to solve it.https://gorm.io/docs/sql_builder.html#Advanced

- Common solution: 
```
.Where(`MONTH(created_at) BETWEEN ? AND ?`,a,b).Where(`YEAR(r.created_at) = ?`,c)
```

**Comment by muh-hizbe** [comment]
awesome, thanks.
