### ISSUE TITLE
unanticipated error with context canceled

### ISSUE THREAD

**Issue by huanlingkeji** [go-gorm/gorm#4974]
in gorm v1.22.4 , stress test my services.
it still reutrn unanticipated error when context canceled, such
sql: transaction has already been committed or rolled back
sql: statement is closed
driver: bad connection

and I try in unitest
![image](https://user-images.githubusercontent.com/43662114/147813137-b0daeeb1-1a16-4d07-a81d-925d1476cc8e.png)

## The document you expected this should be explained
https://gorm.io

## Expected answer

why?

**Comment by longlihale** [comment]
https://github.com/go-gorm/gorm/issues/3836

**Comment by huanlingkeji** [comment]
@longlihale it is not i need answer,thanks

**Comment by jinzhu** [comment]
SQL takes too much time, connection killed by mysql server will cause the bad connection issue.
