### ISSUE TITLE
Can not use gorm sqlite with tdlib in one project

### ISSUE THREAD

**Issue by borzovplus** [go-gorm/gorm#4983]
Hello!
I have golang application with:
go-tdlib
gorm.io/gorm
gorm.io/driver/sqlite

And if I specify tdlibparams:
UseMessageDatabase: true,
UseFileDatabase: true,
UseChatInfoDatabase: true,

Then get errors:

Destroy bad SQLite database because of [Error : 0 : [query:SELECT sqlcipher_export('encrypted')] to database "/go-telegram/accounts-data/89166459517/tdlib-db/db.sqlite" failed: no such function: sqlcipher_export]

If I remove grom from project, then error disappears
Or if I change tdlibparams database:false, then also error disappears.

But I need use tdlib databases and I need use gorm in one project please help me =)

**Comment by longlihale** [comment]
Hello, Is it possible that the problem is with the sqlite3 version ?  Can you provide a demo in https://github.com/go-gorm/playground ?
