### ISSUE TITLE
关于CreatedAt和UpdatedAt自动更新

### ISSUE THREAD

**Issue by smdzz** [go-gorm/gorm#4995]
看好多人都说以前gorm是有"gorm:update_time_stamp"这个callback方法的,但是我在源码里没有找到这个回调方法,是在最新版本移除了吗?

**Comment by jwrookie** [comment]
use schema instead in v2

**Comment by smdzz** [comment]
Thank you for your answer.

**Comment by yangcheng** [comment]
just search for "UpdatedAt" in the repo, the only non-test reference is at 

https://github.com/go-gorm/gorm/blob/e5894ca44951fecc3b3f31f1aa46df7de6024b04/schema/field.go#L266

> Thank you for your answer.
