### ISSUE TITLE
A bug report of range query 

### ISSUE THREAD

**Issue by JOJO0527** [go-gorm/gorm#5008]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
![image](https://user-images.githubusercontent.com/33695125/150168051-2d321ba5-2f12-48f6-b7ea-e77c64295e7e.png)
这样使用范围查询打印的Sql居然是这样的:
'''
SELECT count(*) FROM `coupon_record`  WHERE (coupon_id IN '1001','1') LIMIT 10 
'''
这是有问题的，官网的例子也是错误的，很怀疑你们的例子有没有真实去跑过
![image](https://user-images.githubusercontent.com/33695125/150168712-e9781447-679d-4837-9d18-f4b7d81b5e59.png)

正确的使用是这样
![image](https://user-images.githubusercontent.com/33695125/150168512-09b74b56-d52e-4c08-806f-8df2269d87ba.png)
希望你们能对官网的例子进行修改，不要再继续误导新人

**Comment by li-jin-gou** [comment]
> ## GORM Playground Link
> [go-gorm/playground#1](https://github.com/go-gorm/playground/pull/1)
> 
> ## Description
> ![image](https://user-images.githubusercontent.com/33695125/150168051-2d321ba5-2f12-48f6-b7ea-e77c64295e7e.png) 这样使用范围查询打印的Sql居然是这样的: ''' SELECT count(*) FROM `coupon_record` WHERE (coupon_id IN '1001','1') LIMIT 10 ''' 这是有问题的，官网的例子也是错误的，很怀疑你们的例子有没有真实去跑过 ![image](https://user-images.githubusercontent.com/33695125/150168712-e9781447-679d-4837-9d18-f4b7d81b5e59.png)
> 
> 正确的使用是这样 ![image](https://user-images.githubusercontent.com/33695125/150168512-09b74b56-d52e-4c08-806f-8df2269d87ba.png) 希望你们能对官网的例子进行修改，不要再继续误导新人

你好,看了一下运行的效果发现你应该使用的 `gorm v1` , 但是看的文档是 `gorm v2` 的文档.

- `gorm v1` : https://github.com/jinzhu/gorm  文档:https://v1.gorm.io/zh_CN/docs/query.html
- `gorm v2` : https://github.com/go-gorm/gorm 文档: https://gorm.io/zh_CN/docs/query.html

v1 和 v2 这里的用法是不一样的:kissing_heart: 推荐使用 `gorm v2`
