### ISSUE TITLE
教学

### ISSUE THREAD

**Issue by 1511563371** [go-gorm/gorm#5018]
## Your Question
作为GORM初学者在使用帮助文档时，发现文档逻辑混乱。

## Expected answer
希望作者能自己重新书写文档或者直接使用视频教学进行项目的推广

**Comment by jinzhu** [comment]
https://gorm.io/zh_CN/contribute.html

**Comment by 1511563371** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
