### ISSUE TITLE
db.Session set `PrepareStmt: false` is invalid

### ISSUE THREAD

**Issue by Mr-houzi** [go-gorm/gorm#5026]
## Your Question

```golang
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
    PrepareStmt: true, 
})

newDb := db.Session(&gorm.Session{
		PrepareStmt: false,
})
```

db.Session set `PrepareStmt: false` is invalid，newDb PrepareStmt is still `true`

## The document you expected this should be explained

[Performance - GORM - The fantastic ORM library for Golang, aims to be developer friendly.](https://gorm.io/docs/performance.html#Caches-Prepared-Statement)

## Expected answer

I think newDb PrepareStmt should is  `false`

**Comment by li-jin-gou** [comment]
hello @Mr-houzi  you can look this doc https://gorm.cn/docs/session.html#PrepareStmt

**Comment by Mr-houzi** [comment]
> hello @Mr-houzi you can look this doc https://gorm.cn/docs/session.html#PrepareStmt

I looked it。

## case 1

```golang
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
    PrepareStmt: false,  // look it
})

newDb := db.Session(&gorm.Session{
		PrepareStmt: true,
})
```

## case 2

```golang
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
    PrepareStmt: true, 
})

newDb := db.Session(&gorm.Session{
		PrepareStmt: false,
})
```

case 1 is valid, (PrepareStmt from false to true), case 2 is invalid (PrepareStmt from true not to false)
@li-jin-gou

**Comment by li-jin-gou** [comment]
@Mr-houzi  the same issue is  https://github.com/go-gorm/gorm/issues/4991
