### ISSUE TITLE
The result of FindInBatches is incorrect when used with order.

### ISSUE THREAD

**Issue by 00LT00** [go-gorm/gorm#5027]
## Description
I'm not sure that is a bug. Now I have a table and the primary key is `ip`. I want to do batch execution in the order of `updated_at`.
```go
result := mysql.DB.Order("updated_at").FindInBatches(&ipLocations, 20,
		func(tx *gorm.DB, batch int) error {
		//xxxxxx
	})
```
But I found that the primary key is used by default in `FindInBatches` to build SQL. 
```sql
SELECT * FROM `ip_locations` ORDER BY updated_at,`ip_locations`.`ip` LIMIT 20

SELECT * FROM `ip_locations` WHERE `ip_locations`.`ip` > 'xxx' ORDER BY updated_at,`ip_locations`.`ip` LIMIT 20

SELECT * FROM `ip_locations` WHERE `ip_locations`.`ip` > 'xxx' ORDER BY updated_at,`ip_locations`.`ip` LIMIT 20
```
It is expected to be executed in batches through the `updated_at` field.

**Comment by adamqazi** [comment]
@00LT00 i am currently facing a similar issue, how were you able to work around this?

**Comment by rayjanoka** [comment]
I think I'm running into this with a uuid primary key

**Comment by nutchanon-c** [comment]
Did you finally find a solution or workaround for this? I see that order by PK is hardcoded in FindInBatches()
