### ISSUE TITLE
批量upsert, 某个字段如何在原有基础上增加新值?

### ISSUE THREAD

**Issue by ZhangHu1225** [go-gorm/gorm#5032]
## Your Question

批量upsert, count如何在原有基础上增加新值
<img width="486" alt="image" src="https://user-images.githubusercontent.com/37826977/151343940-2f516c76-3b61-4a20-85dd-a369e19c560a.png">

**Comment by starryrbs** [comment]
可以使用 `gorm.Expr` 
```
var products = []Product{{
	Price: 100,
	Code:  "240",
}}
db.Clauses(clause.OnConflict{
	Columns: []clause.Column{
		{Name: "Code"},
	},
	DoUpdates: clause.Assignments(map[string]interface{}{"Price": gorm.Expr("price + ?", 1)}),
}).CreateInBatches(&products, 1000)
```

**Comment by ZhangHu1225** [comment]
我想加的值是每个结构体内的count的值, 而不是固定的值.

**Comment by starryrbs** [comment]
没理解你的需求，可以写一下sql语句吗

**Comment by ZhangHu1225** [comment]
循环遍历的写法,  我是觉得循环遍历有点费数据量资源, 就想改为批量的写法.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/37826977/151662701-5f7a915e-b180-4c79-9f2c-98066b74919b.png">

**Comment by starryrbs** [comment]
可以试试 case when语法
```
var products = []Product{{
	Price: 100,
	Code:  "240",
}, {
	Price: 100,
	Code:  "240",
}}
id := 1
db.Clauses(clause.OnConflict{
	Columns: []clause.Column{
		{Name: "Code"},
	},
	DoUpdates: clause.Assignments(map[string]interface{}{"Price": 
		gorm.Expr(" case `id` when ? then price + ? end", id, 3)}),
}).CreateInBatches(&products, 1000)
```

**Comment by Aimmit** [comment]
DoUpdates: clause.Assignments(map[string]interface{}{"count": gorm.Expr("count+ VALUES(count)")})
