### ISSUE TITLE
unsupported Scan, storing driver.Value type []uint8 into type *time.Time

### ISSUE THREAD

**Issue by xuweijie4030** [go-gorm/gorm#5033]
### 问题描述
`unsupported Scan, storing driver.Value type []uint8 into type *time.Time`
### 问题原因
当`Mysql`的字段类型为`time`时，即使在`dns`中添加`parseTime=true`参数，查询数据也会报这个错，后来我改成`datetime`后可以正常查询，这个是解析的问题还是我不应该将`MySql`的`time`类型映射为`golang`的`time.Time`？

**Comment by li-jin-gou** [comment]
https://github.com/go-gorm/datatypes/blob/master/time.go  用这个～

**Comment by congjunhua** [comment]
兄弟解决了吗

**Comment by ZoftTy** [comment]
> 兄弟解决了吗

上面那位同学已经给出了解决方法啦

> https://github.com/go-gorm/datatypes/blob/master/time.go 用这个～

```go
import (
    "gorm.io/datatypes"
)


type TestModel struct {
    TestTime datatypes.Time `gorm:"column:test_time"`
}

```

如果你是用 gorm gen 来生成模型或许可以这样子

```go
	dataMap := map[string]func(columnType gorm.ColumnType) (dataType string){
		"time": func(columnType gorm.ColumnType) (dataType string) { return "datatypes.Time" },
	}

	// 要先于`ApplyBasic`执行
	g.WithDataTypeMap(dataMap)
```

**Comment by congjunhua** [comment]
> @congjunhua
> 
> > 兄弟解决了吗
> 
> 上面那位同学已经给出了解决方法啦
> 
> > https://github.com/go-gorm/datatypes/blob/master/time.go 用这个～
> 
> ```go
> import (
>     "gorm.io/datatypes"
> )
> 
> 
> type TestModel struct {
>     TestTime datatypes.Time `gorm:"column:test_time"`
> }
> ```
> 
> 如果你是用 gorm gen 来生成模型或许可以这样子
> 
> ```go
> dataMap := map[string]func(columnType gorm.ColumnType) (dataType string){
> "time": func(columnType gorm.ColumnType) (dataType string) { return "datatypes.Time" },
> }
> 
> // 要先于`ApplyBasic`执行
> g.WithDataTypeMap(dataMap)
> ```

好吧，还是要引`gorm.io/datatypes`这个包。
