### ISSUE TITLE
连表查询如何统计总数?

### ISSUE THREAD

**Issue by ZhangHu1225** [go-gorm/gorm#5039]
## Your Question

<img width="732" alt="image" src="https://user-images.githubusercontent.com/37826977/151662477-a7e259d4-6af2-4d04-9d59-0e6c6e3a976a.png">
`

	db.Model(model.Banners{}).Count(&total)         //这么写的话会报 s.* 字段不存在

	s.data.DB.Model(&model.Banners{}).Count(&total) //这么写的话统计出来的就不是连表后的总数了`

**Comment by Heliner** [comment]
尝试一下实用原生 sql + count 语句的形式来实现
https://gorm.io/zh_CN/docs/sql_builder.html
