### ISSUE TITLE
Exist query

### ISSUE THREAD

**Issue by theprobugmaker** [go-gorm/gorm#5054]
## Your Question

Is there an `exist` query like `xorm`?

```
exists, err = db.Exist(&RecordExist{
   Name: "test1",
})
```

Thank you.

**Comment by li-jin-gou** [comment]
> ## Your Question
> Is there an `exist` query like `xorm`?
> 
> ```
> exists, err = db.Exist(&RecordExist{
>    Name: "test1",
> })
> ```
> 
> Thank you.

hello @theprobugmaker  it is none ~

**Comment by theprobugmaker** [comment]
@li-jin-gou It would be nice to have a `exists` query as it would be executed on the database side instead of waiting for the return to judge based on rows affected.
I'd be happy to create a PR for that (if possible). I will study a little bit more the gorm code tho.
Thank you very much for answering.

**Comment by li-jin-gou** [comment]
> @li-jin-gou It would be nice to have a `exists` query as it would be executed on the database side instead of waiting for the return to judge based on rows affected. I'd be happy to create a PR for that (if possible). I will study a little bit more the gorm code tho. Thank you very much for answering.

 :heart:

**Comment by zcyc** [comment]
@theprobugmaker hi, have you pr for this issue?
