### ISSUE TITLE
verifying module: gorm.io/gorm@v1.22.5: reading https://gosum.io/lookup/gorm.io/gorm@v1.22.5: 404 Not Found         server response: Not Found

### ISSUE THREAD

**Issue by chenxi2015** [go-gorm/gorm#5057]
When I exec the command line 
`
go get -u gorm.io/gorm
`
then can't download. Can you help me ?
![image](https://user-images.githubusercontent.com/13269485/152797731-ae885e41-8332-48ff-82fc-1548ab35ea0f.png)

**Comment by li-jin-gou** [comment]
> When I exec the command line `go get -u gorm.io/gorm` then can't download. Can you help me ? ![image](https://user-images.githubusercontent.com/13269485/152797731-ae885e41-8332-48ff-82fc-1548ab35ea0f.png)

重新设置一下 go mod 参考 https://goproxy.cn/

**Comment by shtrih** [comment]
looks like similar problem here: https://github.com/go-gorm/gorm/issues/6040
