### ISSUE TITLE
batch update not support

### ISSUE THREAD

**Issue by wintrysky** [go-gorm/gorm#5059]
I find that gorm has [Upsert / On Conflict] feature, but that means "create NEW and update if exists", it will create new record.
BUT I only  want to update the existed record and ignore the one that not exist, e.g.

update table1 
 set address = case id
      when 1 then 'xxx'
end
where id in (1,2,3)

**Comment by li-jin-gou** [comment]
hello, you can use `SQL Expression` to solve it.
doc: https://gorm.cn/docs/update.html#Update-with-SQL-Expression

**Comment by wintrysky** [comment]
> hello, you can use `SQL Expression` to solve it. doc: https://gorm.cn/docs/update.html#Update-with-SQL-Expression

I dont think SQL Expression can resolve it, for example,

I have 100 rows need to update whith the column "address" :
addr1 = "sz"
addr2 = "sh"
addr3 = "123"
addr4 = "#$%^"
that means there no rule to set the Expression 

update table1
set address = case id
when 1 then 'sz'
when 2 then 'sh'
when 3 then '123'
when 4 then '#$%^'
end
where id in (1,2,3,4)
