### ISSUE TITLE
Add `embeddedIndexPrefix` in addition to `embeddedPrefix`

### ISSUE THREAD

**Issue by dorfire** [go-gorm/gorm#5060]
## Describe the feature

Currently, GORM supports embedding structs, which prepends a prefix to all COLUMN names.
I'd like to be able to embed a struct and also utilize its indices.

## Motivation

I'd like to also create multiple indices from the embedded struct, for each table, **but keep all column names identical**.

**Comment by ronisec** [comment]
Any update on this?

**Comment by jinzhu** [comment]
end up with https://github.com/go-gorm/gorm/pull/5269
