### ISSUE TITLE
panic: query after update

### ISSUE THREAD

**Issue by ChinaRedArmy1930** [go-gorm/gorm#5064]
## Your Question

if I call like this :
![image](https://user-images.githubusercontent.com/18543437/153530204-2cb9f748-8090-4b86-92fd-932bf7aeb214.png)
(update(XXX).First())

it will panic:
![image](https://user-images.githubusercontent.com/18543437/153530352-049e5876-43c9-427e-9cd1-0de68ace9bbc.png)

when I debug code:
error will return in here:
![image](https://user-images.githubusercontent.com/18543437/153530616-e93b9af8-15eb-4aa1-b62f-5142743601bb.png)
![image](https://user-images.githubusercontent.com/18543437/153530793-d9ab8fdc-529f-4fcb-958c-6fb0ea97a47e.png)

`stmt.Schema` continue nil 
 
it's ok so far

but here:
![image](https://user-images.githubusercontent.com/18543437/153531031-229417ae-88f3-41a8-a522-fc516fcd6593.png)

i think it  will come in this if, call  `db.AddError(xxxx)`, but it not

so it wil panic at here:
![image](https://user-images.githubusercontent.com/18543437/153531305-6e819a7d-e1ad-459e-8b1c-3eef8792cf70.png)
(db.Statement.Schema is nil)

it sames like a bug? 

if I call llike this :
![image](https://user-images.githubusercontent.com/18543437/153531561-dc460a61-e412-4743-baad-9bfe4e579cc3.png)

it will achieve my purpose , get the real data after update

gorm version is :
`gorm.io/gorm v1.22.3`

## Expected answer

I think  do not hang up under any circumstances

**Comment by li-jin-gou** [comment]
参考一下这个文档吧 https://gorm.cn/docs/method_chaining.html
gorm v2 会复用 `statment`,造成条件污染,你这个case里面 `statement.Model` 被污染了.

**Comment by ChinaRedArmy1930** [comment]
谢谢 ，学习到了
