### ISSUE TITLE
gormV2版本怎么没有beforeFind了呀   看代码和文档只有queryCallback.Register("gorm:after_query", 

### ISSUE THREAD

**Issue by LouisYYY** [go-gorm/gorm#5065]
## Describe the feature
查询之前，加上钩子  before_query

## Motivation
beforeFind  before_query这个钩子比较重要，可以在查询前通过钩子查询是不是需要访问缓存

**Comment by li-jin-gou** [comment]
因为在查询前目标数据一般都为空,并且很容易被用错,所以没有支持. 这里可以使用 `plugin` 实现.
