### ISSUE TITLE
指教下会话模式的用法

### ISSUE THREAD

**Issue by AnkoGo123** [go-gorm/gorm#5069]
https://gorm.io/zh_CN/docs/context.html

能说下会话模式的用法吗？以及什么场景下使用会话模式？如果不使用会话模式难道就会引发并发安全问题吗?

**Comment by li-jin-gou** [comment]
可以看下这个
- 会话的用法:https://gorm.io/zh_CN/docs/session.html
- V2复用Statemnt存在的问题: https://gorm.io/zh_CN/docs/method_chaining.html#%E6%96%B9%E6%B3%95%E9%93%BE%E5%92%8C%E5%8D%8F%E7%A8%8B%E5%AE%89%E5%85%A8
