### ISSUE TITLE
How can set SQLITE_LIMIT_VARIABLE_NUMBER to resolve too many SQL variable?

### ISSUE THREAD

**Issue by xxz199539** [go-gorm/gorm#5071]
Hi
I got 'too many SQL variable error' when i want to insert to 1000000 rows to my sqlite。The go-sqlite has merged the request to support sqlite3_limit to get/set the value of run-time limit.
so, if can i set the value with gorm?

**Comment by li-jin-gou** [comment]
you can use generic_interface～ https://gorm.cn/docs/generic_interface.html

**Comment by SpongeManiac** [comment]
> you can use generic_interface～ https://gorm.cn/docs/generic_interface.html

Your link has a chinese domain. I do not trust like that, and if I could, I would report this. Please use the official documentation link.
