### ISSUE TITLE
1.22.4版本按照文档软删除失效，反而是硬删除

### ISSUE THREAD

**Issue by AnkoGo123** [go-gorm/gorm#5081]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

**Comment by li-jin-gou** [comment]
在 playground 提供一个可复现的demo吧～

**Comment by AnkoGo123** [comment]
不好意思哈，是我这边个人的原因，因为我这个项目包含了2个gorm版本，一个是最新的版本，一个是以前的1.9版本，导包语句goland错误的引入为"github.com/jinzhu/gorm"
