### ISSUE TITLE
软删除之后的行还可以被设置值

### ISSUE THREAD

**Issue by AnkoGo123** [go-gorm/gorm#5082]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
软删除之后的行还可以通过以下的方式设置值 db.Model(b).Update("PId", newPId)；
这是gorm没做限制吗？

**Comment by li-jin-gou** [comment]
正常是不会的,可以提个可复现的demo在playground上。

**Comment by AnkoGo123** [comment]
1.22.4版本

**Comment by li-jin-gou** [comment]
嗯....这个不完整....还是在 playground 放个复现的demo吧

**Comment by AnkoGo123** [comment]
> 嗯....这个不完整....还是在 playground 放个复现的demo吧

你说的playground是哪里？

**Comment by AnkoGo123** [comment]
> 嗯....这个不完整....还是在 playground 放个复现的demo吧

我觉得你们按照我上面的api来调用下即可复现，很容易复现我觉得，。。。

**Comment by AnkoGo123** [comment]
```
func TestSetAndGetPIdFriend(c *gin.Context) {
	var p = Friend{
		Model: gorm.Model{ID: 1},
	}
	fmt.Println("p:", p)
	err := p.SetPIdFriend("299")
	fmt.Println("p:", p)
	if err != nil {
		Result.NewResult(c).Error(404, err.Error())
	} else {
		nickName := p.GetPIdFriend()
		fmt.Println("NickName:", nickName)
		Result.NewResult(c).Success(map[string]interface{}{"data1": p})
	}
}

func (b *Friend) SetPIdFriend(newPIdFriend string) error {
	err := DB.DBLink.Model(b).Where("1=?", 1).Update("PIdFriend", newPIdFriend).Error//注意关注这行代码
	return err
}


```
像上面这样会生成的sql语句是：**UPDATE `friends` SET `PIdFriend`='299',`updated_at`='2022-02-18 20:14:14.524' WHERE 1=1 AND `friends`.`deleted_at` IS NULL AND `id` = 1**
但是如果去除代码中的.Where("1=?", 1)则sql语句是： **UPDATE `friends` SET `PIdFriend`='299',`updated_at`='2022-02-18 20:17:53.454' WHERE `id` = 1**
通过对比上下2条sql语句可以很明显的发现只有在使用.where()方法来限制条件的情况下才会生成**AND `friends`.`deleted_at` IS NULL AND `id` = 1**，这是非常不合理的，望及时修复，我之前并未使用过gorm，我以为质量很好，通过使用我发现一些非常基础的bug都可以犯。。真的是很“国人”，之前我使用sqlx，现在看来这个orm并不怎么实用

**Comment by li-jin-gou** [comment]
@AnkoGo123  这个问题 在 https://github.com/go-gorm/gorm/pull/4897 被修复 可以更新 `gorm` 版本到 `1.22.5`
