### ISSUE TITLE
gorm.io/gorm v1.23.0使用plugin/soft_delete报错

### ISSUE THREAD

**Issue by doufujushi** [go-gorm/gorm#5090]
go.mod:
	gorm.io/driver/mysql v1.3.0
	gorm.io/gorm v1.23.0
	gorm.io/plugin/soft_delete v1.0.5

go build:
# gorm.io/plugin/soft_delete
/Users/aqi/go/pkg/mod/gorm.io/plugin/soft_delete@v1.0.5/soft_delete.go:155:54: not enough arguments in call to schema.GetIdentityFieldValuesMap
	have (reflect.Value, []*schema.Field)
	want (context.Context, reflect.Value, []*schema.Field)
/Users/aqi/go/pkg/mod/gorm.io/plugin/soft_delete@v1.0.5/soft_delete.go:163:54: not enough arguments in call to schema.GetIdentityFieldValuesMap
	have (reflect.Value, []*schema.Field)
	want (context.Context, reflect.Value, []*schema.Field)

**Comment by doufujushi** [comment]
![image](https://user-images.githubusercontent.com/13195119/154797065-5718bcb5-fd28-41c5-b0ba-9e8a7512c377.png)
gorm.io/gorm v1.22.5出现的

**Comment by jinzhu** [comment]
Please upgrade soft_delete to v1.1.0 , thank you for your report.

**Comment by doufujushi** [comment]
高效
