### ISSUE TITLE
uniqueIndex 标签出错无效

### ISSUE THREAD

**Issue by AnkoGo123** [go-gorm/gorm#5093]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
![image](https://user-images.githubusercontent.com/84855094/154812774-07cda3f9-eefa-46b2-a7fe-89488c6dfd54.png)

**Comment by li-jin-gou** [comment]
hello @AnkoGo123  
应该不会无效,因为有相关的单测保障。
可以在提一个可复现demo 在 https://github.com/go-gorm/playground 上复现一下.看下是不是写的有问题 🤨

**Comment by AnkoGo123** [comment]
> hello @AnkoGo123 应该不会无效,因为有相关的单测保障。 可以在提一个可复现demo 在 https://github.com/go-gorm/playground 上复现一下.看下是不是写的有问题 🤨

过于麻烦，暂未发现是我这边的原因，如果你那边没复现那就没办法了，改天我找时间做更全面的测试，目前没时间提交什么playground，而且playground这东西这么麻烦，不看好

**Comment by jinzhu** [comment]
We don't fix ANY BUG REPORT w/o reproducible playground PR unless you are a contributor
