### ISSUE TITLE
gorm.io/driver v1.23.1 Error

### ISSUE THREAD

**Issue by oneinstack** [go-gorm/gorm#5096]
# gorm.io/driver/sqlserver
vendor/gorm.io/driver/sqlserver/create.go:55:33: not enough arguments in call to field.ValueOf
        have (reflect.Value)
        want (context.Context, reflect.Value)
vendor/gorm.io/driver/sqlserver/create.go:61:35: not enough arguments in call to field.ValueOf
        have (reflect.Value)
        want (context.Context, reflect.Value)
# gorm.io/driver/postgres
vendor/gorm.io/driver/postgres/migrator.go:337:24: cannot use column (type Column) as type gorm.ColumnType in append:
        Column does not implement gorm.ColumnType (missing AutoIncrement method)

**Comment by jinzhu** [comment]
Hi, please upgrade both driver and gorm to the latest version.

**Comment by oneinstack** [comment]
Hi jinzhu:
It's the latest version error: 
go.mod version:
```
gorm.io/driver/mysql v1.2.3
gorm.io/gorm v1.22.5
```
However the following version is fine:
```
gorm.io/driver/mysql v1.2.3
gorm.io/gorm v1.22.5
```

**Comment by JianingWang43** [comment]
I have faced a similar problem.
Fixed when I change gorm version from 1.23.1 to 1.22.5 and mysql driver version to 1.2.2

**Comment by hielfx** [comment]
I was facing the issue after executing `go mod tidy` but once I updated all my dependencies with `go get -u ./...` it started working again

**Comment by oneinstack** [comment]
I update the latest gorm module with the following command:
```
rm -rf go.mod go.sum
go mod init "panel"
go mod tidy
go mod vendor
```
After running the error, the replacement version is fine.
```
go mod edit -require=gorm.io/driver/mysql@v1.2.3
go mod edit -require=gorm.io/gorm@v1.22.5
go mod vendor
```

**Comment by huuhait** [comment]
another error
Column does not implement gorm.ColumnType (missing AutoIncrement method

**Comment by tanteng** [comment]
> another error Column does not implement gorm.ColumnType (missing AutoIncrement method

how to solve it?

I have solved it by using previous history version, e.g. gorm.io/gorm v1.22.4

**Comment by a2htray** [comment]
version conflict. Need to downgrade gom to v1.22.x

**Comment by a2htray** [comment]
version conflict. Need to downgrade gom to v1.22.x

**Comment by a2htray** [comment]
version conflict. Need to downgrade gom to v1.22.x
