### ISSUE TITLE
提一个通过where api查询全部数据的刚需

### ISSUE THREAD

**Issue by AnkoGo123** [go-gorm/gorm#5099]
## Describe the feature
DB.DBLink.Where(query, args...).Find(dest)，
因为个人习惯问题，不习惯在find中写query, args，喜欢通过where来写条件，所以希望当在使用where时候也可以提供一种方式来查询全部的数据，而不是强制我们必须采用find() api来查询全部的数据，比如这样使用是查询全部的数据：
DB.DBLink.Where(“*”).Find(dest)
望加进去，

**Comment by li-jin-gou** [comment]
看了一下文档,应该可以做到. https://gorm.cn/zh_CN/docs/query.html#%E6%A3%80%E7%B4%A2%E5%AF%B9%E8%B1%A1
```
// 获取全部记录
result := db.Find(&users)
// SELECT * FROM users;
result.RowsAffected // 返回找到的记录数，相当于 `len(users)`
result.Error        // returns error
```
