### ISSUE TITLE
How to make .Exec(Raw SQL) also update autoUpdateTime field ?

### ISSUE THREAD

**Issue by xlidh** [go-gorm/gorm#5100]
## Your Question

I defined a struct with autoUpdateTime field [as here](https://gorm.io/docs/models.html). It works when calling .Update() method.
In my case, some complex json structure field would require .Exec(Raw SQL) to partial update, like JSON_SET, JSON_REMOVE. But this way, the autoUpdateTime field will not be updated.

## Expected answer

Is it possible to fix this problem? Like add a hook only to Exec() function?
Thanks in advance!

**Comment by jinzhu** [comment]
Maybe create a database on update constraint, not possible when executing raw SQL with GORM.
