### ISSUE TITLE
find方法必须使用指针，即使对象已经是指针

### ISSUE THREAD

**Issue by AnkoGo123** [go-gorm/gorm#5103]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

```
var destFan orm.Fan
xx.find( &destFan )
```
这样可以
```
var destFan *orm.Fan
xx.find( destFan )
```
这样生成的sql语句会出错

**Comment by doufujushi** [comment]
var destFan *orm.Fan  默认值是nil；
xx.find( nil )

**Comment by AnkoGo123** [comment]
> var destFan *orm.Fan 默认值是nil； xx.find( nil )

竟然犯了最低级的错误。。捂脸
