### ISSUE TITLE
同样一份SQL，代码生成出来会报错，但是手动复制生成的SQL用Raw执行就正常

### ISSUE THREAD

**Issue by lixh00** [go-gorm/gorm#5110]
生成代码如下:  
![image](https://user-images.githubusercontent.com/72033265/155487848-357b8e0b-c687-4612-becb-d063268f00ce.png)
错误信息: `Error 1055: Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gtest_hyxc.t_evaluation.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

<hr>

直接执行效果如下:  
![image](https://user-images.githubusercontent.com/72033265/155488031-06574de3-21be-4d16-8dce-cc703ea3bed1.png)

**Comment by lixh00** [comment]
只贴了直接运行的图，使用gorm调用Raw的图没贴，但是效果是一致的

**Comment by crazygit** [comment]
今天遇到一样的现象了,不晓得是不是日志里打印的SQL和实际执行的SQL语句不一样导致的
