### ISSUE TITLE
迁移的时候，怎么添加表注释

### ISSUE THREAD

**Issue by yaobg** [go-gorm/gorm#5112]
大家好，迁移数据的时候，如何添加表注释，在文档里面只找到了字段注释，没有找到表的注释，谢谢

**Comment by li-jin-gou** [comment]
hello @speauty @yaobg   可以使用下面这种方式添加表级别的注释
```
db.Set("gorm:table_options", "ENGINE=InnoDB").Migrator().CreateTable(&User{})
```
https://gorm.io/zh_CN/docs/migration.html#%E8%A1%A8
