### ISSUE TITLE
TTL or soft delete in the future

### ISSUE THREAD

**Issue by oxyii** [go-gorm/gorm#5116]
## Describe the feature

I think it would be more logical to use `NOW()` check for `deleted_at` field instead of `NULL` only check

```sql
SELECT ... WHERE ... AND (deleted_at IS NULL OR deleted_at > NOW())
```

## Motivation

In this case `deleted_at` field can be used as TTL for table row. For example, I need a table row for 1 day only. I can create it:

```sql
INSERT INTO table (created_at, deleted_at) VALUES (NOW(), NOW() + INTERVAL('1 day'))
```

then this row will exists in all `SELECT` requests while `deleted_at > NOW()`

PS sorry for my bad english. I hope you can understand me

**Comment by oxyii** [comment]
something like this

```diff
diff --git a/soft_delete.go b/soft_delete.go
index 6d6462880..07dd7d2d7 100644
--- a/soft_delete.go
+++ b/soft_delete.go
@@ -78,7 +78,10 @@ func (sd SoftDeleteQueryClause) ModifyStatement(stmt *Statement) {
 		}
 
 		stmt.AddClause(clause.Where{Exprs: []clause.Expression{
-			clause.Eq{Column: clause.Column{Table: clause.CurrentTable, Name: sd.Field.DBName}, Value: nil},
+			clause.Or(
+				clause.Eq{Column: clause.Column{Table: clause.CurrentTable, Name: sd.Field.DBName}, Value: nil},
+				clause.Gt{Column: clause.Column{Table: clause.CurrentTable, Name: sd.Field.DBName}, Value: stmt.DB.NowFunc()},
+			),
 		}})
 		stmt.Clauses["soft_delete_enabled"] = clause.Clause{}
 	}
```

**Comment by a631807682** [comment]
They are only associated by `Interface`, just define your CustomSoftDeleteClause and CustomDeletedAt to do that,。

**Comment by jinzhu** [comment]
Hello @oxyii 

Not going to support this in GORM to make sure don't hurt performance by default. but glad to accept contributions as a plugin.

Thank you.
