### ISSUE TITLE
Conditionally add index using gorm tags

### ISSUE THREAD

**Issue by dpkahuja-jg** [go-gorm/gorm#5127]
Hi, i want to add unique index on two fields but only if one of them is available.

for example:

```
for a model with email and network field:

@Index(['email', 'network'], {
  unique: true,
  where: 'account.email IS NOT NULL',
})
```
Only create this composite unique index if email is not null. 

Expected from documentation here:

[https://gorm.io/docs/indexes.html](https://gorm.io/docs/indexes.html)

Do we have this feature or not?
How can i go about it?

**Comment by jinzhu** [comment]
https://gorm.io/docs/indexes.html#Index-Tag

**Comment by jinzhu** [comment]
use same index name for two fields with the where tag.
