### ISSUE TITLE
在代码中怎么判断 Duplicate Entry error ？

### ISSUE THREAD

**Issue by zhengm-hub** [go-gorm/gorm#5144]
在代码中怎么判断 Duplicate Entry error ？

_Originally posted by @Jimwi in https://github.com/go-gorm/gorm/issues/3821#issuecomment-1050138287_

**Comment by Heliner** [comment]
gorm not support in the return args error Error,  

but you can do something temporarily， 
when the create model but primary key is unique , I use user.id as primary key， when i insert two model which `id` both `1` , get an error “UNIQUE constraint failed: users.id”，so
```
        err := db.Create(User).Error
        errStr:= err.Error()
        if 	strings.HasPrefix(errStr, "UNIQUE constraint failed:") {
         // add your self code when get depliute key error str
}else if ... other error{
}

```

https://github.com/go-gorm/playground/runs/5522344797?check_suite_focus=true

<img width="827" alt="image" src="https://user-images.githubusercontent.com/32272517/158022639-98f94f1b-1d4e-4bd4-81d9-f64857a4aadd.png">

**Comment by xdxiaodong** [comment]
```go
import mysql2 "github.com/go-sql-driver/mysql"

var (
	// ErrDuplicateEntryCode 命中唯一索引
	ErrDuplicateEntryCode = 1062
)

// MysqlErrCode 根据mysql错误信息返回错误代码
func MysqlErrCode(err error) int {
	mysqlErr, ok := err.(*mysql2.MySQLError)
	if !ok {
		return 0
	}
	return int(mysqlErr.Number)
}

if db.MysqlErrCode(err) == db.ErrDuplicateEntryCode {

}
```

上面的代码是你要的

**Comment by Jimwi** [comment]
> ```go
> import mysql2 "github.com/go-sql-driver/mysql"
> 
> var (
> 	// ErrDuplicateEntryCode 命中唯一索引
> 	ErrDuplicateEntryCode = 1062
> )
> 
> // MysqlErrCode 根据mysql错误信息返回错误代码
> func MysqlErrCode(err error) int {
> 	mysqlErr, ok := err.(*mysql2.MySQLError)
> 	if !ok {
> 		return 0
> 	}
> 	return int(mysqlErr.Number)
> }
> 
> if db.MysqlErrCode(err) == db.ErrDuplicateEntryCode {
> 
> }
> ```
> 
> 上面的代码是你要的

thanks
