### ISSUE TITLE
The default value is - 1, and the inserted value 0 is - 1， Both V1 and V2 have problems. 0 cannot be inserted

### ISSUE THREAD

**Issue by xutao123777** [go-gorm/gorm#5146]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

Both V1 and V2 have problems. 0 cannot be inserted

**Comment by xutao123777** [comment]
package main

import (
	"time"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

type Product struct {
	gorm.Model
	Code    string
	Price   uint
	IsImput int `gorm:"type:int(2);not null;default:-1;index;"`
}

func main() {
	dsn := "root:root@tcp(127.0.0.1:3306)/blog?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})

	// 连接池 V2相对v1多出的连接池功能
	// 获取通用数据库对象 sql.DB ，然后使用其提供的功能
	sqlDB, err := db.DB()

	// SetMaxIdleConns 用于设置连接池中空闲连接的最大数量。
	sqlDB.SetMaxIdleConns(10)

	// SetMaxOpenConns 设置打开数据库连接的最大数量。
	sqlDB.SetMaxOpenConns(100)

	// SetConnMaxLifetime 设置了连接可复用的最大时间。
	sqlDB.SetConnMaxLifetime(time.Hour)

	if err != nil {
		panic("failed to connect database")
	}
	// defer db.Close()

	// Migrate the schema
	db.AutoMigrate(&Product{})

	var isImput int

	isImput = 0 // v2 版本也存在此问题  不需要归集   巨坑: 字段默认值 IsImput 为 -1 (负数 -2 )  插入 0  插入的值仍然为 -1 (-2)

	// Create
	db.Create(&Product{Code: "L1212", Price: 1000, IsImput: isImput})
	/*
		// Read
		var product Product
		db.First(&product, 1)                   // find product with id 1
		db.First(&product, "code = ?", "L1212") // find product with code l1212

		// Update - update product's price to 2000
		db.Model(&product).Update("Price", 2000)

		// Delete - delete product
		db.Delete(&product)
	*/
}

**Comment by xutao123777** [comment]
Cannot insert 0 value problem

**Comment by Heliner** [comment]
https://gorm.io/docs/create.html#Default-Values  see the document
