### ISSUE TITLE
版本号作为查询条件

### ISSUE THREAD

**Issue by steve7688** [go-gorm/gorm#5166]
表中有一列放的是版本号，格式是三段式，例如：1.2.21

现在想要根据这一列来进行查询，例如：查询版本号大于1.0.5的所有记录，数据库是MySQL8.0+，请问使用gorm应该如何实现，谢谢

**Comment by steve7688** [comment]
@jinzhu 呼叫柱哥😁

**Comment by jinzhu** [comment]
https://stackoverflow.com/questions/34876711/mysql-query-compare-version-numbers
