### ISSUE TITLE
many2many 的连接表不支持驼峰表名称，自动进行转换为蛇形

### ISSUE THREAD

**Issue by ophioglossum** [go-gorm/gorm#5181]
![image](https://user-images.githubusercontent.com/61675623/159471579-4a97dcd7-de80-46bc-abf7-03743211330f.png)
![image](https://user-images.githubusercontent.com/61675623/159471651-9901ea09-b30e-4c81-bfc1-cd7466ed3224.png)
![image](https://user-images.githubusercontent.com/61675623/159471832-fd675e39-5c6d-4017-8242-5829946695b1.png)
![image](https://user-images.githubusercontent.com/61675623/159471690-81cd7ac4-5b9d-4cb9-98e0-75cf580a32aa.png)
![image](https://user-images.githubusercontent.com/61675623/159471780-d42dcf2a-ee09-4c6d-8894-80e246cbdc38.png)

**Comment by jinzhu** [comment]
If it doesn't follow the convention, you can overwrite the NamingStrategy: https://gorm.io/docs/gorm_config.html#NamingStrategy

Or https://gorm.io/docs/many_to_many.html#Customize-JoinTable
