### ISSUE TITLE
Repeat AutoMigrate on MariaDB cause String field default NULL value

### ISSUE THREAD

**Issue by newro** [go-gorm/gorm#5188]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/453

## Description

AutoMigrate do every time causing by string, datetime default null value field.
This symptom occurs on mariadb.
sql.NullString returns `NULL` string from information_schema.columns.
but, mysql DB returns "" empty string.

**Comment by newro** [comment]
I've solved with default:NULL tag.

**Comment by muety** [comment]
Please open again.
