### ISSUE TITLE
Do we need call tx.Rollback() after tx.Commit() got error?

### ISSUE THREAD

**Issue by codeboytj** [go-gorm/gorm#5191]
## Your Question

Do we need call tx.Rollback() after tx.Commit() got error? According to examples in https://gorm.io/docs/transactions.html, it seems like we don't need call tx.Rollback() after tx.Commit() got error? 

## The document you expected this should be explained

https://gorm.io/docs/transactions.html

## Expected answer

I want to know if we need call tx.Rollback() after tx.Commit() got error?

**Comment by codeboytj** [comment]
![image](https://user-images.githubusercontent.com/18275952/159886316-12f6c4d8-a126-42a0-a408-e6248b2a6a5b.png)

Just return when error occur according to the example

**Comment by a631807682** [comment]
This should be required, I think we can just use `defer` to rollback nomatter commited or error or painc .
Because if `tx` is done, rollback will do nothing.
https://pkg.go.dev/database/sql#example-Tx.Prepare
https://github.com/golang/go/blob/master/src/database/sql/sql.go#L2305

**Comment by jinzhu** [comment]
Suggest to just use the `Transaction` method
