### ISSUE TITLE
如何使用Map条件进行模糊查询

### ISSUE THREAD

**Issue by JmyFilm** [go-gorm/gorm#5199]
## 问题实例

例如代码
`db.Where(map[string]interface{}{"name": "jinzhu", "age": 20}).Find(&users)`

得到的SQL是
`SELECT * FROM users WHERE name = "jinzhu" AND age = 20;`

## 期望的SQL语句
`SELECT * FROM users WHERE name LIKE "jinzhu" AND age LIKE 20;`

如何让里面的 `=` 变成 `LIKE`，我想要执行模糊查询。

**Comment by jinzhu** [comment]
We don't support this currently.
