### ISSUE TITLE
 Column does not implement gorm.ColumnType (missing AutoIncrement method)

### ISSUE THREAD

**Issue by MasterKenway** [go-gorm/gorm#5202]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

go.mod are discribed as below 
```
gorm.io/driver/mysql v1.2.3
gorm.io/gorm v1.23.0
```
when compile binary, i got 

```
# gorm.io/driver/mysql
vendor/gorm.io/driver/mysql/migrator.go:224:24: cannot use column (type Column) as type gorm.ColumnType in append:
        Column does not implement gorm.ColumnType (missing AutoIncrement method)
```

after deleting go.sum and drop gorm version to 1.22.4, then rerun go mod vendor, this error vanish

Hoping get some ideas from devs

**Comment by jinzhu** [comment]
upgrade mysql drivers

**Comment by EsonChurch** [comment]
I solve it by update all relative package，it works：

```
go get gorm.io/gorm
go get gorm.io/driver/mysql
go get gorm.io/driver/sqlserver
go get gorm.io/driver/postgres

go mod vendor
```
