### ISSUE TITLE
gorm.io文档与实际效果有差异

### ISSUE THREAD

**Issue by grzeng-go** [go-gorm/gorm#5205]
## Your Question
db.Delete(&User{}, 10)
官方文档：DELETE from user where id = 10;
实际效果：DELETE from user where 10;

First方法也有类似问题。

另外计数方法，会抛异常，但是返回合计数又是正确的，代码如下：
db.Model(user).Scopes(scopes...).Count(&page.Total)
执行语句为：SELECT BYNAME, USERID, USERNAME FROM user WHERE username like '%g%'
抛出异常为：sql: expected 3 destination arguments in Scan, not 1; sql: expected 3 des
tination arguments in Scan, not 1

## Expected answer

希望能更新下文档，还有就是说下Count异常要怎么解决

**Comment by grzeng-go** [comment]
count的问题，我找到原因了，我在scope中调用了select方法导致的，这个问题可以忽略

**Comment by Heming9** [comment]
> count的问题，我找到原因了，我在scope中调用了select方法导致的，这个问题可以忽略

如果scope里面不可避免的会调select方法，有什么解决方案避免count报错吗？
