### ISSUE TITLE
primary key is uuid convert fail on v1.23.3

### ISSUE THREAD

**Issue by truyetnm** [go-gorm/gorm#5211]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
I'm using gorm v1.21.xx with postgres. I have a model definition:
```
type Data struct {
	gorm.Model
	ID          *uuid.UUID `gorm:"primaryKey;type:uuid;default:uuid_generate_v1()"`
}
```
It's working ok, when I update to v1.23.3, I received error when create query:
```
sql: Scan error on column index 1, name \"id\": converting driver.Value type string (\"2876842a-b0d2-11ec-9fb1-0242ac110003\") to a uint64: invalid syntax
```

**Comment by jinzhu** [comment]
don't embed `gorm.Model`

**Comment by abc1236762** [comment]
Why embed `gorm.Model` don't work after v1.23.3?
