### ISSUE TITLE
为啥无法创建多个字表

### ISSUE THREAD

**Issue by shig-cn** [go-gorm/gorm#5216]
func (Animal) TableName() string {
	return "test_" + strconv.Itoa(index)
}
func main() {

	//连接数据库gorm.io/gorm
	db, err := gorm.Open(mysql.New(mysql.Config{
		DriverName: "mysql",
		DSN:        "root:123456@(127.0.0.1:3306)/gomicro_test?charset=utf8mb4&parseTime=True&loc=Local",
	}))
	if err != nil {
		panic(err)
	}

	// 自动迁移,创建表

	for i := 0; i < 20; i++ {
		index = i
		db.AutoMigrate(&Animal{})
	}
}

**Comment by jinzhu** [comment]
https://gorm.io/docs/v2_release_note.html#Table-Name
