### ISSUE TITLE
feat: use action to manage issues not in English

### ISSUE THREAD

**Issue by a631807682** [go-gorm/gorm#5228]
## Describe the feature
Although we remind users to use English when creating issues, many users still use their own language.
This gave us trouble in dealing with the problem. We handle some issues in issues in some languages, but we can't search for related issues when users in other languages ask the same question.

I try to add more descriptions https://github.com/go-gorm/.github/pull/3 , but there are already a lot of them.
So I created an action to translate those non-language issues https://github.com/a631807682/issues-translator.
I'm not sure this is a good approach, and gorm has used a lot of actions to manage issues, which may bring more notifications.
If this is not a good way, please close this issue directly.

## Motivation
Make issues easy to search

**Comment by jinzhu** [comment]
Actually I would like to detect and close... Usually those issues don't follow official rules are low quantity that don't make much sense.
