### ISSUE TITLE
gorm.io\driver\sqlserver@v1.2.1\create.go:55:33: not enough arguments in call to field.ValueOf

### ISSUE THREAD

**Issue by coolops-cn** [go-gorm/gorm#5233]
# gorm.io/driver/sqlserver
D:\my-dev\pkg\mod\gorm.io\driver\sqlserver@v1.2.1\create.go:55:33: not enough arguments in call to field.ValueOf
        have (reflect.Value)
        want (context.Context, reflect.Value)
D:\my-dev\pkg\mod\gorm.io\driver\sqlserver@v1.2.1\create.go:61:35: not enough arguments in call to field.ValueOf
        have (reflect.Value)
        want (context.Context, reflect.Value)
# gorm.io/driver/postgres

---

**Comment by a631807682** [comment]
Pass the pointer to `Create`
https://github.com/go-gorm/gorm/issues/5197

**Comment by AWaterColorPen** [comment]
compile failed
	gorm.io/driver/mysql v1.3.3
	gorm.io/driver/postgres v1.3.4
	gorm.io/driver/sqlite v1.3.1
	gorm.io/gorm v1.23.4

**Comment by AWaterColorPen** [comment]
@coolops-cn  update to gorm.io/driver/sqlserver v1.3.2 // indirect  can resolve

**Comment by AWaterColorPen** [comment]
@jinzhu BTW, I only use  mysql /  postgres / sqlite . why it is need gorm.io/driver/sqlserver // indirect?

**Comment by pylist** [comment]
哥们, 知道原因了么, 我只用mysql, 也给我爆错了

**Comment by AWaterColorPen** [comment]
@pylist 

> @coolops-cn update to gorm.io/driver/sqlserver v1.3.2 // indirect can resolve

**Comment by pylist** [comment]
> gorm.io/driver/sqlserver v1.3.2

确实是解决了, 但是我也没用sqlserver, 为啥需要下载他, 很好奇这个问题
