### ISSUE TITLE
朱建ID 查询用什么 ？First（）？？有bug  后面会跟上 ORDER BY `bv`.`id` LIMIT 1

### ISSUE THREAD

**Issue by icetech233** [go-gorm/gorm#5240]
d := new(BVData)
	err := gormDB.First(d, id).Error
生成的 sql 

WHERE `bv`.`id` = '10180827' ORDER BY `bv`.`id` LIMIT 1

有没有考虑单独搞个 朱建的查询写法

**Comment by Kisesy** [comment]
多看文档 https://gorm.io/zh_CN/docs/query.html 可以用 `Take()`

**Comment by icetech233** [comment]
> 多看文档 https://gorm.io/zh_CN/docs/query.html 可以用 `Take()`

ok 我试试看
