### ISSUE TITLE
Named Arguments w/ d.Raw(), SQL Injection Safe?

### ISSUE THREAD

**Issue by kaizenlabs** [go-gorm/gorm#5254]
I have a query similar to the one below, slightly different than the example for Named Arguments in the GORM documentation:

```
db.Raw("SELECT * FROM users WHERE (name1 ILIKE @Name AND name3 ILIKE @Name) AND name2 ILIKE @Name2",
   NamedArgument{Name: "jinzhu", Name2: "jinzhu2"}).Find(&user)
```

I searched around but couldn't find an answer, are Named Arguments with db.Raw() sql injection safe or parametrized? Is there anything else I need to do to make this more secure if the input is coming from a user input?

**Comment by a631807682** [comment]
> GORM uses the database/sql‘s argument placeholders to construct the SQL statement, which will automatically escape arguments to avoid SQL injection

`NamedArg` is injection safe
https://github.com/go-gorm/gorm/blob/master/clause/expression_test.go#L85
https://gorm.io/docs/security.html#Query-Condition
