### ISSUE TITLE
想问一下，当定义指针类型的struct变量，查不到数据，是否不用将变量初始化成 empty struct

### ISSUE THREAD

**Issue by CsongSY** [go-gorm/gorm#5275]
想问一下，当定义指针类型的struct变量，查不到数据，是否不用将变量初始化成 empty struct。empty struct和查不到数据是两个概念。
比如定义 var s *struct
Find在查不到数据的时候会返回empty struct并且不报错，这种情况应该是s == nil   err == nil
如果定义var s struct
Find在查不到数据的时候会返回empty struct并且不报错，这种情况应该是err == ErrRecordNotFound.

盼回复，多谢。

**Comment by a631807682** [comment]
Only the `First/Take/Last` api will return `ErrRecordNotFound` as they obviously only return one data.

**Comment by udoless** [comment]
同样的问题，很不方便。这是个很细节但很重要的点，也容易引起bug的一个点。

**Comment by feileb** [comment]
https://segmentfault.com/a/1190000021363996

```go
err := db.Model(user).Where("id = ?", 1).First(&users).Error
fmt.Println(err, user)

err = db.Model(user).Where("id = ?", 1).Find(user).Error
fmt.Println(err, user)

<nil> &{0  }
record not found &{0  }
```
传入接收结果集的变量只能为Struct类型或Slice类型，当传入变量为Struc类型时，如果检索出来的数据为0条，会抛出ErrRecordNotFound错误，当传入变量为Slice类型时，任何条件下均不会抛出ErrRecordNotFound错误
