### ISSUE TITLE
在clause.select中指定expression, 导致指定的[]column被忽略

### ISSUE THREAD

**Issue by hezhuolun** [go-gorm/gorm#5276]
开发者你好：

我在使用clause.select{}构建一个左连接的查询语句的时候，将clause.from{}作为expression传入select中构建查询条件

但在clause/Select.MergeClause(clause *Clause)中对于select.expression的处理会导致select.Clomns被忽略，导致生成的sql语句不正确

![截屏2022-04-20 16 55 09](https://user-images.githubusercontent.com/43540165/164194150-209c788b-e801-4e8d-91e8-a21c3957d7ca.png)

传入的Select{}:
![截屏2022-04-20 16 55 40](https://user-images.githubusercontent.com/43540165/164194225-3c4d6634-7877-4483-aaa1-9ef874ab1ec2.png)

据此生成的Statement.Clauses：
![截屏2022-04-20 16 57 17](https://user-images.githubusercontent.com/43540165/164194250-e744f12e-0012-4468-9c85-6c66736a463f.png)

**Comment by mimicode** [comment]
遇到同样的问题
