### ISSUE TITLE
Question: How do I use Changed in BeforeUpdate to track changes on a field in an embedded struct?

### ISSUE THREAD

**Issue by DestroyerAlpha** [go-gorm/gorm#5279]
## Question
How do I use Changed in BeforeUpdate to track changes on a field in an embedded struct? I tried Changed("field1->>'field2'") and it did not work.

## The document you expected this should be explained
[Check if field has changed](https://gorm.io/docs/update.html#Check-Field-has-changed)

## Expected Answer
Yes, or no if this is supported. If yes, how would one do it.

**Comment by a631807682** [comment]
it's not support
