### ISSUE TITLE
How to join nested tables

### ISSUE THREAD

**Issue by sintanial** [go-gorm/gorm#5280]
## Your Question

I have models like this:

```golang
package models

type ItemAsset struct {
	ID int32 `gorm:"primary_key;AUTO_INCREMENT;column:id;type:int;" json:"id"`
	ItemID string `gorm:"column:item_id;type:varchar;size:36;" json:"item_id"`
}

type ItemSet struct {
	ID uint32 `gorm:"primary_key;AUTO_INCREMENT;column:id;type:uint;" json:"id"`
}

type Item struct {
	ID int32 `gorm:"primary_key;AUTO_INCREMENT;column:id;type:int;" json:"id"`
	ItemID string `gorm:"column:item_id;type:varchar;size:36;" json:"item_id"`
	SetID null.Int `gorm:"column:set_id;type:uint;" json:"set_id"`
}

type PlayerItem struct {
	ID int32 `gorm:"primary_key;AUTO_INCREMENT;column:id;type:int;" json:"id"`
	PlayerID string `gorm:"column:player_id;type:varchar;size:128;" json:"player_id"`
	ItemID string `gorm:"column:item_id;type:varchar;size:36;" json:"item_id"`
	ItemLevelID null.Int `gorm:"column:item_level_id;type:uint;" json:"item_level_id"`
}

type ItemLevel struct {
	ID uint32 `gorm:"primary_key;AUTO_INCREMENT;column:id;type:uint;" json:"id"`
	ItemID string `gorm:"column:item_id;type:varchar;size:36;" json:"item_id"`
}
```

And then i have another structure which combine all structure with relations

```golang
package entity

type Item struct {
	models.Item
	ItemAsset *models.ItemAsset `gorm:"foreignKey:ItemID;references:item_id" json:"item_asset"`
	ItemSet   *models.ItemSet          `gorm:"foreignKey:ID;references:set_id" json:"item_set"`
}

type PlayerItem struct {
	models.PlayerItem
	Item      Item       `gorm:"foreignKey:ItemID;references:item_id" json:"item"`
	ItemLevel *models.ItemLevel `gorm:"foreignKey:ItemLevelID;references:id" json:"item_level"`
}
```

So my question is, how can i join nested models when i fetch ```entity.PlayerItem``` ? 

Query like this is not working :( 
```
db.
		Joins("ItemLevel").
		Joins("Item").
		Joins("Item.ItemAsset").
		Joins("Item.ItemSet").
		Find(&items).
```

Yes, of course i know about Preload ! But it's generate separate query, but i want to join nested structure by LEFT JOIN query !

**Comment by lisandromdc** [comment]
I also needing the same feature. A simple Joins("Item.ItemAsset") like the Preload, but using LEFT JOIN

**Comment by 0xdeface** [comment]
+1. i also

**Comment by PQMISSCMP** [comment]
JOIN no work for me  ._.

**Comment by d-baranowski** [comment]
Hate to be the "me too" guy... but me too :(

**Comment by MateuszKepczynski** [comment]
Try by adding tag `gorm:"embedded"`:
```
type PlayerItem struct {
	models.PlayerItem gorm:"embedded"
	Item      Item       `gorm:"foreignKey:ItemID;references:item_id" json:"item"`
	ItemLevel *models.ItemLevel `gorm:"foreignKey:ItemLevelID;references:id" json:"item_level"`
}
```

**Comment by TobiasGrether** [comment]
I believe you can use `.Preload("Item.ItemAsset")` if you want to load it. At least that works for me, maybe you should try that.

**Comment by 4ND3R50N** [comment]
This is definatly a necessary feature for some users. We started using gorm, but recently discovered that there is no possibility to use JOIN with 1:N relations. 

This is a hard drawback, hopefully there is some feedback if this is getting implemented in the future :-)

**Comment by bcbill** [comment]
why cant we just preload and join the same table?? Preload the nested data we want to get, and then use Join for conditions

**Comment by bcbill** [comment]
> When will this feature release?

@KiddoV already released last week

**Comment by codingamir** [comment]
I also need this feature desperately. Thank god it is released. Unable to find any documentation for it. Can someone please mention the link to it? Thanks.

**Comment by KiddoV** [comment]
What version is the latest for Gorm? Kinda confused the latest one was released 2 years ago  🤔

**Comment by a631807682** [comment]
There is no documentation at present, you can refer to [unit test](https://github.com/go-gorm/gorm/blob/master/tests/joins_test.go#L329), I will add it to the documentation this month, if anyone is willing to help add documentation, please commented in https://github.com/go-gorm/gorm/issues/6226

The latest version is [v1.25.0](https://github.com/go-gorm/gorm/releases/tag/v1.25.0)

**Comment by codingamir** [comment]
Thanks @a631807682 . I tried and it's working for nested structs but only where there is 1:1 relationship. Like 

                 ```
                DB.
		Joins("Manager").
		Joins("Manager.Company").
		Joins("Manager.NamedPet").
		Joins("NamedPet").
		Joins("NamedPet.Toy")
```

All these relationships are 1:1, i.e Manager has only one company, NamedPet etc.

But it is failing where we have 1:N relationship. i.e it will fail in the following scenario (as Manager/User has 1:N relationship with Pets):

                 ```
                DB.
		Joins("Manager").
		Joins("Manager.Pets")
OR
             DB.
            Joins("User.Pets")
```

Is there any alternative of it other than Preload? Though It works well with Preload, but it will cost network latency as it creates separate queries (for 1:N relationship it makes almost 4 to 5 queries).

**Comment by a631807682** [comment]
Join will not handle 1:N relationship.
1. Join from native sql will not handle 1:N relationship. When API and sql have the same syntax, we must ensure that their meanings are also similar.
2. When using Join, we cannot actually determine the ownership of the collection. Take the pseudo code below as an example. If there are two users with different ids but the same name, how do we determine which user the pet belongs to?
```go
DB.Select("User.Name, Pets.Name").Joins("Pets").Find(&user)
```

**Comment by loeffel-io** [comment]
We would love to use the Nested Joins feature but we don't want the auto select for all fields - why does a nested join auto add all columns @a631807682 @jinzhu

**Comment by theorem4** [comment]
@KiddoV https://klaussnot9.github.io/modem/
