### ISSUE TITLE
[Aliyun ADB MySQL] Unsupported column type: 245

### ISSUE THREAD

**Issue by eric-chao** [go-gorm/gorm#5298]
[ADB MySql]

adb mysql version: 3.1.3.8

mysql column type: json array, e.g. ["basketball", "football"]

sdk: golang gorm

ERROR:

Error 1815: [9001, 2022042418393617201618417503453302922] Unsupported column type: 245

But on Aliyun RDS MySQL works well.

![image](https://user-images.githubusercontent.com/13026384/165280300-69aa8889-2387-4a35-b4d5-0c58f786c914.png)

![image](https://user-images.githubusercontent.com/13026384/165280344-aed59ec8-40d6-4132-b9b4-e91ee4519d2d.png)

**Comment by fifsky** [comment]
https://help.aliyun.com/document_detail/129838.html?spm=5176.smartservice_service_chat.help.dexternal.187e3f1b1ya0S2

add DSN param    `&interpolateParams=true` can solve this problem
