### ISSUE TITLE
db.First 生成错误的SQL

### ISSUE THREAD

**Issue by hagbei** [go-gorm/gorm#5312]
```
type User struct {
    ID string
}
```

如下代码生成的SQL：
```
user := &User{}
db.First(user, "123456")
```
```
SELECT * FROM `user` WHERE `user`.`id` = '123456' ORDER BY `user`.`id` LIMIT 1
```

如下代码生成的SQL：
```
user := &User{}
db.First(user, "16E88674CFB58578")
```
```
SELECT * FROM `user` WHERE 16E88674CFB58578 ORDER BY `user`.`id` LIMIT 1
```
这样的SQL错误了。

**Comment by a631807682** [comment]
Seems to be a doc error, when the id is of type string, we don't know if it's an primary key value or a query.
```go
user := &User{ID: "16E88674CFB58578"}
db.First(user)
// or 
user := &User{}
db.First(user, "id = ?","16E88674CFB58578")
```

**Comment by li-jin-gou** [comment]
@hagbei  hello  可以参考一下文档 :kissing_heart:
https://gorm.cn/zh_CN/docs/query.html#%E6%A0%B9%E6%8D%AE%E4%B8%BB%E9%94%AE%E6%A3%80%E7%B4%A2
<img width="840" alt="image" src="https://user-images.githubusercontent.com/97824201/166412878-9510b4fc-5f1b-480d-8163-d524e7f5e773.png">
