### ISSUE TITLE
ScyllaDB support

### ISSUE THREAD

**Issue by kubakl** [go-gorm/gorm#5314]
## Describe the feature
It could be really nice if there were a driver for ScyllaDB

## Motivation
Right now I'm using postgres but looking for better performance and I would love to use Scylla

**Comment by punitdarira** [comment]
I am working on this one

**Comment by jinzhu** [comment]
Sorry, I currently don’t have the capacity to implement support for ScyllaDB. However, I’d be happy if the community could take on this effort. The implementation can either be maintained under the GORM organization or independently. We will add relevant links to recommend it.
