### ISSUE TITLE
How Many To Many Preload performs conditional query on the intermediate table?

### ISSUE THREAD

**Issue by OneSeven** [go-gorm/gorm#5321]
## Your Question
How Many To Many Preload performs conditional query on the intermediate table?

## The document you expected this should be explained
```sql
db.Preload("role","type = ?",1)->Find(&user);
The above query, prompts an error,
The output is: select * from role where type=1
But I want to be able to do where on the intermediate table somehow
select * from user_role where type=1;

```

## Expected answer
Is there an API implementation that I don't know about?
Or how to achieve this effect in other way

**Comment by saeidee** [comment]
Have you tried this? https://gorm.io/docs/preload.html#Custom-Preloading-SQL

**Comment by saeidee** [comment]
For now, you can use it like this:

<img width="1394" alt="image" src="https://github.com/go-gorm/gorm/assets/29974712/597d8443-ce41-41d4-8548-6c592f40f1c7">

**Comment by saeidee** [comment]
Based on your issue description, you mentioned querying not updating intermediate table.
>
```go
db.Preload("role","type = ?",1)->Find(&user);
The above query, prompts an error,
The output is: select * from role where type=1
But I want to be able to do where on the intermediate table somehow
select * from user_role where type=1;
```

.

**Comment by mostafa-binesh** [comment]
i have this problem too
@saeidee dude, the op wanted to have some condition in the .preload() function not with where() function
in your example it would be sth like this
```go
DB.Model(&user).Preload("Roles","some_field = ?","foo").find(&user)
```
but it doesn't work in gorm and instead of searching in "user_roles" table, it searches in "roles" table

**Comment by mostafa-binesh** [comment]
because this issue was closed i opened another one 
#5321

**Comment by jackbaron** [comment]
I have same the problem. Any solution for this?. I want add cinditional query for intermediate table. But I not found the solution on document
