### ISSUE TITLE
 Unknown prepared statement handler (401) given to mysqld_stmt_execute

### ISSUE THREAD

**Issue by panqiang199** [go-gorm/gorm#5342]
## Your Question

 Unknown prepared statement handler (401) given to mysqld_stmt_execute  . 

func UserGet(where string, args ...interface{}) (*User, error) {
	var lst []*User
	err := DB().Where(where, args...).Find(&lst).Error
	if err != nil {
		return nil, err
	}

	if len(lst) == 0 {
		return nil, nil
	}

	lst[0].RolesLst = strings.Fields(lst[0].Roles)
	lst[0].Admin = lst[0].IsAdmin()

	return lst[0], nil
}

## Expected answer

why this code sometimes report err.  the err msg is :Unknown prepared statement handler (401) given to mysqld_stmt_execute  .

**Comment by saeidee** [comment]
This is related to the MySQL engine, not GORM.
