### ISSUE TITLE
连表统计总数,生成sql报错.

### ISSUE THREAD

**Issue by tangqiu0205** [go-gorm/gorm#5358]
## Description
**之前在select里加上w.id 就能生成count(*),但是更新框架后就报错了**

![$A07QT)8W)A4C5Y38I__UHK](https://user-images.githubusercontent.com/37826977/169637638-46e2034e-956f-4275-a883-c150cbc7a229.jpg)

![%6`UN%P}N_Q5(ZD~)60X$CT](https://user-images.githubusercontent.com/37826977/169637644-276263d6-0e5d-4d8e-a13b-d497dcd71b4e.jpg)

如果不加w.id 还是会报错
![~R@{HDT@FN_925@MRLSAJF0](https://user-images.githubusercontent.com/37826977/169637694-ff904bf5-3a63-4621-b3e3-975f3178ab15.jpg)

**解决方法是select放在count之后, 这也太反人类了.**
![4}OYU@${KCUKK{2QK GIJQT](https://user-images.githubusercontent.com/37826977/169637735-76780469-299d-46ce-bcb1-6ee1dbed852c.jpg)

**Comment by a631807682** [comment]
> After a Chain method, Finisher Method, GORM returns an initialized *gorm.DB instance, which is NOT safe to reuse anymore, you should use a New Session Method to mark the *gorm.DB as shareabl

https://gorm.io/docs/method_chaining.html#New-Session-Method

**Comment by tangqiu0205** [comment]
用了Session 还是不行, Select 必须放在Count 后面才行吗?
<img width="779" alt="image" src="https://user-images.githubusercontent.com/37826977/169640621-4bddb083-dc10-4bed-ba01-fb1b82aeec23.png">

**Comment by tangqiu0205** [comment]
连表查询如果不写select, find或者scan在两张表内有相同字段情况下能正确赋值吗,

**Comment by a631807682** [comment]
Please take a look at the `code example` and the code comments explaining why this happens and how to fix it.
```go
tx := db.Where("name = ?", "jinzhu").Session(&gorm.Session{})

// good case
tx.Where("age = ?", 18).Find(&users)
// SELECT * FROM users WHERE name = 'jinzhu' AND age = 18
```

**Comment by tangqiu0205** [comment]
我就是照着这个地方改的.
1:先拼接where条件
2:使用session让其可复用
3:查询s表数据
4:统计总数
哪里出现问题了?

**Comment by a631807682** [comment]
```go
db = db.Session(&gorm.Session{})
```
