### ISSUE TITLE
表关联

### ISSUE THREAD

**Issue by xrl12** [go-gorm/gorm#5362]
我创建了一个模型类，希望可以希望可以和其他表关联起来。我的字段名创建的是***Id
<img width="893" alt="截屏2022-05-22 上午2 40 09" src="https://user-images.githubusercontent.com/53255548/169665075-f947fe45-1c07-4242-96ed-91c3599105de.png">
,但是在通过这个字段查询的时候，是查不到了，会提示 **Error 1054: Unknown column 'user_permissions.UserId' in 'where clause'**

**Comment by resokou** [comment]
检查在线文档 https://gorm.io/zh_CN/docs/belongs_to.html

如果UserId是一个foreign key (User)，那么它需要被命名为User**ID**，并且还需要添加User struct。

```go
type User struct {
    ID ...
}

type UserPermission struct {
    ...
    UserID ...
    User User
}
```

**Comment by xrl12** [comment]
我想在UserID存放用户id，但是我不希望使用外键进行关联

**Comment by xrl12** [comment]
我希望UserId来存放用户id，但是并不希望使用外建进行关联
