### ISSUE TITLE
many2many 关系表， 在Preload的时候，没有使用中间表的deleted_at

### ISSUE THREAD

**Issue by orinchen** [go-gorm/gorm#5378]
## Your Question
类似如下三张表
type User struct{
  gorm.Model
  Resources [] Resource `gorm:"many2many:user_languages" `
}

type Resource struct{
  gorm.Model
  Name string
}

type UserResource struct {
  gorm.Model
  UserId uint
  ResourceId uint
}

//Query
s.db.Model(&user).Preload("Resources").First(&user)

这种情况下 怎么使 UserResource表中的delete_at 生效

**Comment by a631807682** [comment]
https://gorm.io/docs/many_to_many.html#Customize-JoinTable

use `SetupJoinTable`
