### ISSUE TITLE
After update, the value of the ignored field gorm:"-" in struct is not updated

### ISSUE THREAD

**Issue by XBreath** [go-gorm/gorm#5386]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/480

## Description

In gorm V1 , the value of the ignored field gorm:"-" will changed after update.
In gorm V2 now , the value will not changed.
Is this behavior change a bug ?
If not , is there a writing style to get results like V1 ?
Thanks so much !

**Comment by a631807682** [comment]
https://gorm.io/docs/models.html#Fields-Tags

<table>
<tr>
	<td> Tag Name
	<td>Description
<tr>
	<td><-	
	<td>set field’s write permission, <-:create create-only field, <-:update update-only field, <-:false no write permission, <- create and update permission
</table>

**Comment by XBreath** [comment]
@a631807682 Thanks for the reply !
But it doesn't work.  'age' does not exist in table.
if use '<-:false', will got same results(not updated).
if use '<-create' or '<-update', the sql execution will failed.
`ERROR: column "age" of relation "user" does not exist (SQLSTATE 42703)`

**Comment by a631807682** [comment]
you should set read permission

<table>
<tr>
	<td>Tag Name
	<td> Description
<tr>
	<td>->
	<td>set field’s read permission, ->:false no read permission
</table>

**Comment by XBreath** [comment]
@a631807682 Thanks for the reply !!
I have try the read permission tags '->' and '->:false'.
but it doesn't work. the value in struct is not updated.

**Comment by a631807682** [comment]
```go
	...
	Age       uint `gorm:"->:false;<-:update"`
```
doesn't this work?

**Comment by XBreath** [comment]
> ```go
> ```go
> 	...
> 	Age       uint `gorm:"->:false;<-:update"`
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> doesn't this work?
> ```

The value of Age in struct have changed after Update().
But the sql execution will failed.
`ERROR: column "age" of relation "user" does not exist (SQLSTATE 42703)`
 `[rows:0] UPDATE "user" SET "updated_at"='2022-05-30 19:10:01.058',"age"=18 WHERE "id" = 453`

**Comment by a631807682** [comment]
@XBreath  The problem here is age not exists in table, you are not using `AutoMigrate`? you need to create this field on the database

**Comment by XBreath** [comment]
yes, not using AutoMigrate() in my test.
But in V1 , using `gorm: "-"`, will not create this field in table. 
so age not exists in table. now v1 need to upgrade to V2.  
using AutoMigrate() and `gorm:"->:false;<-:update"` will create this field in table.
Is there a way without creating ignored field like "Age"? @a631807682

**Comment by XBreath** [comment]
use this like https://github.com/go-gorm/playground/pull/480, the value of age in struct will not update after use Update().
Is this a problem?
