### ISSUE TITLE
gorm v1 and v2 is incompatible (db=db.Where())

### ISSUE THREAD

**Issue by liu-xuewen** [go-gorm/gorm#5387]
## Your Question
v1:
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/29445066/170963667-34747518-74b4-4471-8d6f-c5bd742ed09b.png">

v2: 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/29445066/170964744-888024a5-cdcf-464e-a82d-5df1bad8c7bb.png">

v2 result:
{"level":"DEBUG","time":"2022-05-30 17:40:29","caller":"mysql/user.go:17","message":"Database Query","sql":"SELECT * FROM `users` WHERE 1 = 1  AND 1 = 2 ","time":"47.249ms","rows":0}
{"level":"DEBUG","time":"2022-05-30 17:40:29","caller":"mysql/user.go:20","message":"Database Query","sql":"SELECT * FROM `users` WHERE 1 = 1  AND 1 = 2  AND 2 = 3 ","time":"46.799ms","rows":0}

**Comment by li-jin-gou** [comment]
可以参考 https://gorm.cn/zh_CN/docs/method_chaining.html#%E6%96%B9%E6%B3%95%E9%93%BE%E5%92%8C%E5%8D%8F%E7%A8%8B%E5%AE%89%E5%85%A8
```
 GORM 复用 Statement 这可能会引发预期之外的问题
```
