### ISSUE TITLE
clause.OnConflict{UpdateAll: true}   不会更新 update_time

### ISSUE THREAD

**Issue by qianxiansheng90** [go-gorm/gorm#5389]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/481
## Description

`
package main

import (
	"fmt"
	"time"

	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type TT struct {
	ID         int       `gorm:"not null;primaryKey;comment:id"`
	Name       string    `gorm:"not null;default:'';comment:任务名"`
	UpdateTime time.Time `gorm:"not null;default:current_timestamp(3);index:idx_update_time;comment:更新时间"`
	CreateTime time.Time `gorm:"not null;default:current_timestamp(3);comment:创建时间"`
}

func main() {
	var dsn = "xx:xx@tcp(xx:xx)/test?autocommit=true&charset=utf8mb4,utf8&loc=Local&parseTime=true&writeTimeout=30s&readTimeout=60s&timeout=10s"
	dbConn, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		fmt.Println(err)
		return
	}
	if err := dbConn.AutoMigrate(&TT{}); err != nil {
		fmt.Println(err)
		return
	}
	var t = TT{
		ID:         1,
		Name:       "a",
		CreateTime: time.Now(),
		UpdateTime: time.Now(),
	}
	if err = dbConn.Clauses(clause.OnConflict{UpdateAll: true}).Create(&t).Error; err != nil {
		fmt.Println(err)
		return
	}
	t.UpdateTime = time.Now().Add(10 * time.Second)
	if err = dbConn.Clauses(clause.OnConflict{UpdateAll: true}).Create(&t).Error; err != nil {
		fmt.Println(err)
		return
	}
	var t2 TT
	if err = dbConn.First(&t2).Error; err != nil {
		fmt.Println(err)
		return
	}
	if t2.UpdateTime.Format("2006-01-02 15:04:05") != t.UpdateTime.Format("2006-01-02 15:04:05") {
		fmt.Printf("expect %s but %s", t.UpdateTime.Format("2006-01-02 15:04:05"), t2.UpdateTime.Format("2006-01-02 15:04:05"))
	}
}
`

数据库中的表结构
`
CREATE TABLE `tts` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` varchar(191) NOT NULL DEFAULT '' COMMENT '任务名',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4
`

结果：
<img width="799" alt="image" src="https://user-images.githubusercontent.com/9649317/171156708-2279ab25-ffd3-448d-b24b-2f6a746afbd3.png">

update_time字段并没有被更新

**Comment by qianxiansheng90** [comment]
go 1.8
gorm：v1.23.5

**Comment by jinzhu** [comment]
will update those fields with `default` tag.
