### ISSUE TITLE
Preloading with inner join with condition on nested table

### ISSUE THREAD

**Issue by arvidfm** [go-gorm/gorm#5392]
## Your Question

I have the following nested structure (simplified for clarity; I'm not actually dealing with fruits): A main `Fruit` table with a reference to a `FruitData` table that holds additional data about each fruit, which in turn has an optional `AppleData` table which holds additional data specific to apples.
```go
type Fruit struct {
	gorm.Model
	FruitData FruitData
	FruitType int
}

type FruitData struct {
	gorm.Model
	FruitID       uint
	SourceCountry string
	AppleData     *AppleData
}

type AppleData struct {
	gorm.Model
	FruitDataID uint
	Seeds       int
}
```

I want to get a list of **all apples with more than 4 seeds**, while also preloading `FruitData` and `FruitData.AppleData`.

I could do it like this:
```go
var fruits []Fruit
db.
    Joins("JOIN fruit_datas ON fruit_datas.fruit_id = fruits.id").
    Joins("JOIN apple_datas ON apple_datas.fruit_data_id = fruit_datas.id AND apple_datas.seeds > 4").
    Preload("FruitData").
    Preload("FruitData.AppleData").
    Find(&fruits)
```

However, this requires doing both joins **and** preloading, which is wasteful. Is there any way to do the same thing **without having to use both `Joins` and `Preload`** for the same tables?

## The document you expected this should be explained

https://gorm.io/docs/advanced_query.html
https://gorm.io/docs/preload.html

## Expected answer

An example on how to get the requested preloaded entries without unnecessary queries.

**Comment by saeidee** [comment]
There are no unnecessary queries, the joins that you are using are part of the fetch Fruits query, and preloads are for preloading the relations.  

_**With joins (3 queries)**_

<img width="1476" alt="image" src="https://github.com/go-gorm/gorm/assets/29974712/8f39cb4a-ff44-4bb7-9967-7d174f0cd1b2">


_**Without joins (3 queries)**_

<img width="1486" alt="image" src="https://github.com/go-gorm/gorm/assets/29974712/f9d796be-10e8-4651-b5ae-b7321644f0f3">
