### ISSUE TITLE
Update的时候，如果指定了model，不能根据主键生成where条件

### ISSUE THREAD

**Issue by QianChenglong** [go-gorm/gorm#5396]
v1.23.5

```
func Test_update_where(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("panic", r)
		}
	}()

	err := db.Create(&Product{
		Code: time.Now().String(),
	}).Error
	if err != nil {
		fmt.Println(err)
	}

	err = db.Model(&Product{}).Updates(&Product{
		Model: gorm.Model{
			ID: 2,
		},
		Code: "D43",
	}).Error
	if err != nil {
		fmt.Println(err)
	}
}
```

Update的时候，如果指定了model，不能根据主键生成where条件
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/1881126/171993853-62f2737b-b4c1-469b-99c7-cf10bfbcfaf3.png">

<img width="785" alt="image" src="https://user-images.githubusercontent.com/1881126/171993767-45ed70f1-d6c7-4cda-8352-ad9428d01210.png">

stmt.ReflectValue这里变成了零值，可能是其他地方被重置了
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/1881126/171993829-74ae5bcf-c7dc-4e3a-bf63-fc5915ec214c.png">

Execute的时候是有初始化的
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/1881126/171994180-821f34e0-09a9-4615-a603-05104f84c659.png">

**Comment by holicc** [comment]
直接用`Save` 或者

**Comment by QianChenglong** [comment]
> 直接用`Save` 或者 `db.Model(&Product{Model: gorm.Model{ID: 2}}).Updates(&Product{ Code: "D43"})`

绕开没问题，想看下这个是feature还是bug？

**Comment by a631807682** [comment]
It by design, `Model` means which record you want to update and `Updates` means which field you want to update
