### ISSUE TITLE
Api实现脏读语法，比如sqlserver：select * from table with(nolock)

### ISSUE THREAD

**Issue by cnwangfei** [go-gorm/gorm#5397]
## Describe the feature

Api实现脏读语法，比如sqlserver：select * from table with(nolock)

**Comment by li-jin-gou** [comment]
https://gorm.io/zh_CN/docs/sql_builder.html#%E5%AD%90%E5%8F%A5%E6%9E%84%E9%80%A0%E5%99%A8 参考
