### ISSUE TITLE
Support `unique` and `uniqueIndex` together on the same field.

### ISSUE THREAD

**Issue by ihucos** [go-gorm/gorm#5401]
## Describe the feature

Allow uniqueIndex and index struct tags to be used at the time. At the moment it seems I can do one or the other, but not both.

## Motivation

SQL supports this, so I expect gorm to support it. I need it for my software.

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/issues/6381#issuecomment-1929427042
