### ISSUE TITLE
通过 DSN 设置 readTimeout 无法生效

### ISSUE THREAD

**Issue by rason** [go-gorm/gorm#5403]
## Your Question

出发点是想设置全局的查询超时时间

看了 https://github.com/go-sql-driver/mysql#readtimeout 这里的介绍，我在 DSN 中参入了 &readTimeout=1ms&writeTimeout=6ms 来测试验证超时，但是经验证并没有生效。

## The document you expected this should be explained

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/1102051/172347301-c4208fe9-61c3-413b-ab9a-121e898c3da1.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/1102051/172347486-6b84e79a-23f1-4274-ac22-4097b13f1cbc.png">
超过了 1ms 的查询，并没有出现查询超时异常

## Expected answer

看了 gorm 的 mysql driver 依赖的是 github.com/go-sql-driver/mysql ，理论上应该是能生效才对，请问是不是有 bug？

或者说，gorm 有没有其他的方式来设置全局的查询超时时间？

**Comment by a631807682** [comment]
1. The time of the log print is not the time of the actual query.
2. Each data queried by mysql will be returned immediately, all records are completed by waiting on the client side.

you can use `DB.Raw("select sleep(1)")` to test it.

**Comment by rason** [comment]
> DB.Raw("select sleep(1)")

I tried this and readTimeout didn't work.

**Comment by chengjk** [comment]
> > DB.Raw("select sleep(1)")
> 
> I tried this and readTimeout didn't work.

DB.Raw("select sleep(1)").Scan(nil)

**Comment by whling** [comment]
How to resolve it finally?
