### ISSUE TITLE
When I only need to query one field，I want user `Scan()` to receive result by an array of underlying variable types

### ISSUE THREAD

**Issue by view6view** [go-gorm/gorm#5405]
## Describe the feature

当我使用gorm查询返回某一个字段结果时候，我希望用一个int数组或者string数组进行直接接收，而不是需要定义一个结构体数组获取返回结果

## Motivation

查询统计数据的时候会很需要这样的功能，能减少代码的开发

**Comment by jinzhu** [comment]
use `Pluck`
