### ISSUE TITLE
how to set "user defined variables" per connections

### ISSUE THREAD

**Issue by wydszqd** [go-gorm/gorm#5406]
## 
tidb has user defined variables tidb_batch_insert, how to set variable per connection?
right now i exec 
	db.Exec("set @@session.tidb_batch_insert=1")
before a insert expression.
This is to wasty, how to set variable per connection?

**Comment by li-jin-gou** [comment]
https://gorm.io/zh_CN/docs/sql_builder.html#Connection @wydszqd
