### ISSUE TITLE
Find() uses values from the previous row in 1.23.6

### ISSUE THREAD

**Issue by ov** [go-gorm/gorm#5415]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/485

## Description

It looks like `DB.Model().Find()` use values from the previous row if the current one has `NULL` in the cell that has `default:NULL`. This happens with SQLite driver and Gorm 1.23.6. Rolling back to 1.23.5 fixes the problem.

**Comment by cburgmer** [comment]
We can reproduce with Postgres.

**Comment by jamiekurtz** [comment]
we're seeing the same in Postgres, as well

**Comment by hungcs** [comment]
still seeing this with:



gorm.io/datatypes           v1.0.7
gorm.io/driver/postgres   v1.3.8
gorm.io/gorm                   v1.23.8
