### ISSUE TITLE
How to set charset for a new PostgreSQL database?

### ISSUE THREAD

**Issue by alexkmbk** [go-gorm/gorm#5418]
## Your Question

How to set charset (encoding) for a new PostgreSQL database?

## The document you expected this should be explained

https://gorm.io/de_DE/docs/connecting_to_the_database.html

**Comment by saeidee** [comment]
You may try this:

```go
dsn := "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai options='--client_encoding=UTF8'"
 ```
