### ISSUE TITLE
HasMany自引用相关问题 ？

### ISSUE THREAD

**Issue by CurrentIndex** [go-gorm/gorm#5420]
## Your Question
我的Author有多个Movie，Movie是自引用 Movie记录Author的ID和父Movie的ID，在我尝试插入到数据库的时候遇到了这个问题

错误！！
Error 1452: Cannot add or update a child row: a foreign key constraint fails (`close`.`movies`, CONSTRAINT `fk_authors_movies` FOREIGN KEY (`author_id`) REFERENCES `authors` (`id`))

![80d0e840e6c415f3b02ddd33c0e676f](https://user-images.githubusercontent.com/59065234/173234625-3fcc26f0-d79d-4bb9-adbb-3764c7051474.png)
![adc66bd388c0421858b3608ae0eb32c](https://user-images.githubusercontent.com/59065234/173234637-907f97ed-b6db-4673-8b68-b9415f4eacb4.png)
![fb4826a93954252563d945559590f88](https://user-images.githubusercontent.com/59065234/173234641-f0186093-1e95-4623-bd02-d4e446e9753b.png)
![da071e3bcfe902267eb4d6b2653081b](https://user-images.githubusercontent.com/59065234/173234647-682ff296-74ec-449e-a27d-8e123b59a1e1.png)

可能是写法问题,我在文档没有找到解释

## The document you expected this should be explained

HasMany自引用

## Expected answer

正确的使用方法

**Comment by AceCodeE** [comment]
不管children的外键写不写都在报错，是我模型定义有问题吗，是我模型定义有问题吗？？谢谢！
@jinzhu

**Comment by CurrentIndex** [comment]
for range下操作元素不会修改切片元素的字段!!

**Comment by jiugemei** [comment]
跟你同样的问题

**Comment by jiugemei** [comment]
![image](https://user-images.githubusercontent.com/13929377/207485943-aacdc20b-901b-47c5-b8d6-8fa4f65b9015.png)

**Comment by atheima** [comment]
同样的问题，最后怎么解决？

**Comment by CurrentIndex** [comment]
> 同样的问题，最后怎么解决？

过了一段时间，我是自己写法问题，以下for range导致的。

> for range下操作元素不会修改切片元素的字段!!

**Comment by atheima** [comment]
> > 同样的问题，最后怎么解决？
> 
> 过了一段时间，我是自己写法问题，以下for range导致的。
> 
> > for range下操作元素不会修改切片元素的字段!!
> 
> 

我没有for range的问题，但同样有外键的问题，我的TreeNode结构体，到底是哪里错了？![20240509_191317.jpg](https://github.com/go-gorm/gorm/assets/144667892/92ba06a7-ffa5-44b6-a216-79fcf661d767)
