### ISSUE TITLE
`Scan` does not return `RowsAffected` when update

### ISSUE THREAD

**Issue by NoWait126** [go-gorm/gorm#5422]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

version
`	gorm.io/driver/mysql v1.1.2
	gorm.io/gorm v1.21.16`

I use `raw()` to update mysql and want to get how many rows I have updated like this

    tasks := my_table{}
        
    updateSql := "update my_table set status = 1 where status = 0 LIMIT 1"

	tx := db.Conn.Raw(updateSql).Scan(&tasks)

	fmt.Printf("%d\n", tx.RowsAffected)
I always get 0， whether or not a row was actually modified, where did i write wrong?

**Comment by a631807682** [comment]
Use `Exec`, you are not querying anything so RowsAffected is 0
