### ISSUE TITLE
Trino support

### ISSUE THREAD

**Issue by rimolive** [go-gorm/gorm#5426]
## Describe the feature
It would be nice if GORM supports Trino

## Motivation
Trino is an MPP (Massive Parallel Processing) database that supports connecting to a variety of data sources like Relational Databases, NoSQL, and endpoints like Kafka Topics or Prometheus. This can be a really good addition for Analytical tasks using the Go language.

**Comment by li-jin-gou** [comment]
It's a good idea :stuck_out_tongue:

**Comment by jinzhu** [comment]
We are not going implement officially support for Trino, but contributions welcome ;)
