### ISSUE TITLE
Saving preload object re creates entires for all preloaded associations 

### ISSUE THREAD

**Issue by viveksyngh** [go-gorm/gorm#5429]
## GORM Playground Link
For exam

https://github.com/go-gorm/playground/pull/1

## Description

What is happening?

I have a `Quiz` model which has a list `Questions` of questions as an association and when I get a Quiz by preloading all its Questions and then save the Quiz. It creates new question records ( = number of questions already existing). 

```go
       r := database.DBInstance.Preload("Questions").Where("id = ? ", quizID).First(&quiz)
	if r.Error != nil {
		ctx.JSON(http.StatusInternalServerError, gin.H{"error": r.Error.Error()})
		return
	}


        quiz.Published = true
	r = database.DBInstance.Save(&quiz)
	if r.Error != nil {
		ctx.JSON(http.StatusInternalServerError, gin.H{"error": r.Error.Error()})
		return

```

I expect this to not create new rows for Questions when I save the Quiz.

**Comment by a631807682** [comment]
> If you want to update associations’s data, you should use the FullSaveAssociations mode:

https://gorm.io/docs/associations.html#Auto-Create-x2F-Update

more usage
https://gorm.io/docs/associations.html#Association-Mode
