### ISSUE TITLE
查询"timestamp"时间类型,时区丢失问题

### ISSUE THREAD

**Issue by PL-Joe** [go-gorm/gorm#5432]
**大背景: java改go**

数据库时间类型"timestamp", 存储为当地时间(没有带时区, 且没有做时区偏移处理) : 数据如下
![image](https://user-images.githubusercontent.com/107296968/173984347-d25d8c7c-b66c-4676-ac62-447524249585.png)

**实现:**  java接口不变, impl由go提供。java使用Date，go使用time.Time接收时间类型。 

**问题：**
1. gorm查询出来的时间是带时区的结构：‘2022-06-15 05:15:28.367 +0000’ 
![image](https://user-images.githubusercontent.com/107296968/173982024-453fdaa1-f855-4cee-a29d-71681601193a.png)
2. 在go time.Time严谨的结构来看，原先由java程序存储下来的时间字段值就显得"‘不准确"或者说"不正确"。
3. 将时间字段值 ‘2022-06-15 15:08:00.367 +0000’  传递给java程序端时，java接收到的字段值是 ： “2022-06-15 23:08:00”，自动根据当地的时区做了时区偏移，加了8个小时 ：
![image](https://user-images.githubusercontent.com/107296968/173983074-86e5e09f-adcd-49cd-8c1d-6f7826d2cc6b.png)

**提问 ：** 有没有办法在go端处理时区的问题？（去掉时区，或者手动给时间类型字段设置当地的时区）

**注 ：** 目前找到一个“能用但不好用”的办法，需要改动sql查询语句， 在sql查询时指定时区：
```
SELECT create_time AT TIME ZONE 'PRC' create_time, update_time AT TIME ZONE 'PRC' update_time FROM table WHERE id = ?;
```

**Comment by a631807682** [comment]
> NOTE:
To handle time.Time correctly, you need to include parseTime as a parameter. ([more parameters](https://github.com/go-sql-driver/mysql#parameters))
To fully support UTF-8 encoding, you need to change charset=utf8 to charset=utf8mb4. See [this article](https://mathiasbynens.be/notes/mysql-utf8mb4) for a detailed explanation

https://gorm.io/docs/connecting_to_the_database.html#MySQL
