### ISSUE TITLE
Pluck Scan called without calling Next

### ISSUE THREAD

**Issue by liyuan1125** [go-gorm/gorm#5434]
```go

	var username string
	db.Model(&model.User{}).
		Where("id = @id", sql.Named("id", 10000)).
		Limit(1).
		Pluck("username", username)
```

**Comment by xpume** [comment]
need `&` before `username`
```go
	var username string
	db.Model(&model.User{}).
		Where("id = @id", sql.Named("id", 10000)).
		Limit(1).
		Pluck("username", &username)
```

**Comment by dablelv** [comment]
GORM version is v1.25.0.

I encountered the same error when I use the Pluck to get single column value. My code as follow:
```go
func GetModelStatus(id uint64) (status constants.ModelStatus, err error) {
	err = Db.Model(&model.Model{}).Where("id = ?", id).Pluck("status", &status).Error
	return
}
```
The type constants.ModelStatus defined as follow:
```go
type ModelStatus int
```
Can anyone help me, thx.

**Comment by dablelv** [comment]
I found taht in the low version, such as 1.24.1, the Pluck no problem.

In desperation, I use Scan indtead of Pluck to get single column value and succeeded.

**Comment by RaphaelLuizPH** [comment]
Old thread but if anyone comes across this in the future:

If you're using a custom type alias for a primitive type, do not use it in the Pluck function. Use the primitive, and cast is to your custom type after if needed.
