### ISSUE TITLE
Range query using map condition

### ISSUE THREAD

**Issue by MisAudrey** [go-gorm/gorm#5441]
Can I pass in a map in gorm to support range query for numeric or time-based values? Like, if I have a column named mileage, make `WHERE mileage BETWEEN 100 AND 200` into a map and let gorm do `db.Where(map).Find(&cars)`

**Comment by li-jin-gou** [comment]
refer to https://gorm.cn/docs/query.html#String-Conditions
```
// BETWEEN
db.Where("created_at BETWEEN ? AND ?", lastWeek, today).Find(&users)
// SELECT * FROM users WHERE created_at BETWEEN '2000-01-01 00:00:00' AND '2000-01-08 00:00:00';

```
