### ISSUE TITLE
read: connection timed out

### ISSUE THREAD

**Issue by counten** [go-gorm/gorm#5442]
## Your Question

gorm.io/gorm v1.21.10 ，Postgresql，read tcp sourceIP:12480->targetIP:5432: read: connection timed out，This problem occurs occasionally, sometimes every few hours.

## The document you expected this should be explained

github issue

## Expected answer

Possible Check Directions

**Comment by jinzhu** [comment]
Use SetConnMaxLifetime to set the max life time to a reasonable time like 5min
