### ISSUE TITLE
使用presto数据库时Limit和Offset的顺序

### ISSUE THREAD

**Issue by EastMacro2020** [go-gorm/gorm#5444]
## Describe the feature
使用presto作为gorm的dialector，执行同时带有limit和offset的语句报错。

实际验证后发现是presto服务端要求offset必须出现在limit子句之前。

希望最终生成的SQL语句中limit和offset的顺序能够调换一下

**Comment by li-jin-gou** [comment]
在 `dialector` 层可以做处理哈
