### ISSUE TITLE
'AfterDelete' Hook does not triggered in Batch Delete

### ISSUE THREAD

**Issue by mdanialr** [go-gorm/gorm#5445]
## Your Question

It seems `AfterDelete` hook does not triggered when using Batch Delete.
Example: `tx.Model(&User{}).Where(condition).Delete(&[]User{}).Error`
but it does triggered if i delete them one by one using for loop with `tx.Delete(&user)`

## The document you expected this should be explained

[Docs](https://gorm.io/docs/hooks.html#Deleting-an-object)

## Expected answer

Hook `AfterDelete` could be triggered with both way, deleting in Batch or One by one.

**Comment by a631807682** [comment]
It is work for me, can you reproduced on [go-gorm/playground](https://github.com/go-gorm/playground)?

**Comment by mdanialr** [comment]
@a631807682 i also read this in the [docs](https://gorm.io/docs/delete.html#Delete-Hooks). `'...those methods will be called when deleting a record...'`. whats the word `deleting a record` means?

**Comment by jinzhu** [comment]
```go
tx.Model(&User{}).Where(condition).Delete(&[]User{}).Error
```

In your case, the after delete method will called for each record of `&[]User{}`, as the slice is empty, so no one will be called.

We don't query out all matched data before deleting, so we can't call the method for all data deleted, but using the data you passed in.
