### ISSUE TITLE
Scan进行扫描为null数据结果非预期

### ISSUE THREAD

**Issue by strive1216** [go-gorm/gorm#5448]
## Your Question
使用Scan 进行扫描后：行数据内email 为null的情况下，将会被上一个email有值的数据覆盖

## The document you expected this should be explained

数据表 数据如图：
<img width="419" alt="image" src="https://user-images.githubusercontent.com/22957560/175195184-f74742ba-129b-41ab-a80b-0a5680fa6d4a.png">

```
// model
type User struct {
    Name     string     `gorm:"column:user_name"`
    Email        *string `gorm:"column:email"`                
}
```

```
type userInfo struct {
     Name     string     `gorm:"column:user_name"`
     Email      string     `gorm:"column:email"`                   
}
```

使用Scan 进行扫描后：行数据内email 为null的情况下，将会被上一个email有值的数据覆盖：
```
      db.DB.Model(User{}).Where(where).Scan(&[]userInfo)
```
<img width="342" alt="image" src="https://user-images.githubusercontent.com/22957560/175195865-72131606-e857-45d6-a1c0-c45dde8d2127.png">

解决办法：
把 email 设置为指针变量即可

**Comment by Merry74751** [comment]
一定要设置成指针才行吗，没有其他解决方案吗

**Comment by a631807682** [comment]
duplicate of https://github.com/go-gorm/gorm/issues/5415
