### ISSUE TITLE
v1.23.6 Find数据行错误

### ISSUE THREAD

**Issue by cqlmq** [go-gorm/gorm#5450]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

使用FIND查询数据到结构数组时，数据行错乱。第一行的数据可能填充到第三行了。恢复到v1.23.5 问题消失

**Comment by cqlmq** [comment]
HJDZ   BaseAddress   `gorm:"embedded;embeddedPrefix:HJDZ_"`                // 户籍地址

**Comment by a631807682** [comment]
duplicate of https://github.com/go-gorm/gorm/issues/5415
