### ISSUE TITLE
支持自定义表名或者可以通过ctx构建schema.table的表名形式

### ISSUE THREAD

**Issue by notech** [go-gorm/gorm#5459]
## Describe the feature
通过ctx构建schema.table的表名形式

## Motivation
在开发多租户的系统时使用PG数据库， 此时通过schema应用租户隔离， 这时tableName不支持动态改变， 只能使用table方法临时指定，临时指定的表名无法参与诸如 Joins 的sql语句的构建。

是否有类似的实现思路或者改造思路？

**Comment by li-jin-gou** [comment]
https://gorm.cn/zh_CN/docs/scopes.html 使用 `Scope` 扩展修改 tableName

**Comment by notech** [comment]
scope 扩展不支持Joins 等多表操作啊
