### ISSUE TITLE
AutoMigrate runs ALTER COLUMN TYPE smallint when such type is already existed

### ISSUE THREAD

**Issue by viatoriche** [go-gorm/gorm#5464]
Hello everyone, I have found a bug and written some unittest #5463 which presents what is wrong with AutoMigrate and Migrator().MigrateColumn on postgres.

**Steps to reproduce:**

1. Make model with field int8
2. Run AutoMigrate on postgres - table is created with field: smallint
3. Run AutoMigrate again

**Expected result:**

Migration skips the field

**Actual result:**

Migration runs ALTER TABLE table ALTER COLUMN field TYPE smallint again and again.

**Note: For huge databases it is very dangerous and can take minutes to do unneeded operation.**

**Comment by a631807682** [comment]
related to https://github.com/go-gorm/postgres/pull/111

**Comment by vic220309** [comment]
同样遇到这个问题 ， 修改了字段类型，会一直执行 ALTER TABLE `config` MODIFY COLUMN `name` varchar(255) NOT NULL
