### ISSUE TITLE
关于结构体零值不更新问题

### ISSUE THREAD

**Issue by dackh** [go-gorm/gorm#5474]
现在对于结构体零值不更新的问题，官方好像给的说法只能用map，但是个人觉得map代码的可读性没有用结构体看起来工整，还需要自己定义对应的字段名字符串，这个有比较合适的解决方案吗。

个人觉得这里不应该通过零值去判断是否，考不考虑引入指针，通过指针是否为nil判断是否修改。

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/4297
