### ISSUE TITLE
AutoMigrate: Syntax error at or near "NOT" (SQLSTATE 42601)

### ISSUE THREAD

**Issue by tfonfara** [go-gorm/gorm#5478]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/489

## Description

Since v1.23.7 of gorm.io/gorm AutoMigrate method fails for some type specifications. See Playground for reproduction, run with postgres dialect. Issue does not happen with v1.23.6

**Comment by a631807682** [comment]
```go
-	Array  []string `gorm:"type:TEXT[] NOT NULL"`
+	Array  []string `gorm:"type:TEXT[];NOT NULL"`
```
