### ISSUE TITLE
中文表头错误乱码

### ISSUE THREAD

**Issue by qq547176052** [go-gorm/gorm#5482]
https://blog.csdn.net/qq_39611230/article/details/121436439?app_version=5.6.0&csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22121436439%22%2C%22source%22%3A%22QiongJiShengBian%22%7D&ctrtid=kNapw&utm_source=app
![image](https://user-images.githubusercontent.com/26636842/177044523-917e419b-b505-4a76-b03c-ed1a148ad97a.png)

**Comment by li-jin-gou** [comment]
设置一下编码～
