### ISSUE TITLE
sqlserver 查询出的guid 与数据库中的guid存在字节顺序不对的问题

### ISSUE THREAD

**Issue by iwaters-yyj** [go-gorm/gorm#5488]
这是我的字段定义
type StationInfo struct {
	Id   uuid.UUID `gorm:"column:id;type:char(36)"`
	Name string `gorm:"column:name"`
	Dtu  string `gorm:"column:DTU_id"`
}

数据库中的ID字段值为：5208cffa-7943-11ea-bc53-005056c00008
而通过gorm查询出的ID字段值为：facf0852-4379-ea11-bc53-005056c00008

**Comment by iwaters-yyj** [comment]
数据库驱动为：gorm.io/driver/sqlserver

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/5419

**Comment by hugh2632** [comment]
`import (
"database/sql/driver"
mssql "github.com/microsoft/go-mssqldb"
)

type Guid struct {
guid mssql.UniqueIdentifier
}

func (j *Guid) Scan(value interface{}) error {
return j.guid.Scan(value)
}

func (j Guid) Value() (driver.Value, error) {
return j.guid.Value()
}

func (j Guid) String() string {
return j.guid.String()
}

func (j Guid) MarshalText() ([]byte, error) {
return []byte(j.guid.String()), nil
}`
This works for me. Substitute uuid.UUID with this Guid struct.
