### ISSUE TITLE
Find To Map do not support .First on .Table

### ISSUE THREAD

**Issue by borisjcli** [go-gorm/gorm#5491]
gorm tag 1.23.6
when i use like this:
record:=map[string]interface{}{}
db.Table("xxx").First(&record,"id=?",1), it returns error "model value required"

finally i find code blow works:
records:=map[string]interface{}{}
db.Table("xxx").Where("id=?",1).Find(&records)

is it a bug?

## The document you expected this should be explained
https://gorm.io/id_ID/docs/v2_release_note.html#Find-To-Map

**Comment by a631807682** [comment]
Use `Model(...)` or `Limit(1).Find(...)` instead, `Take/First` should specify order which not parseable by `map` and `Table`
