### ISSUE TITLE
The AUTOUPDATETIME does not go through the driver.Valuer during an UPDATE SET or ON CONFLICT statement

### ISSUE THREAD

**Issue by jsgoupil** [go-gorm/gorm#5494]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/490

## Description

The goal is to change the `time.Time` to another object. It works great during the `Create` scenario, but during a `Save`, I would expect the object to flow properly down the SQL handler and call the driver.Valuer. But in this case, I can't make it keep the correct type.

In the playground I made it fail by looking at the type. But basically it failed during the SET, but would fail in a ON CONCLICT as well.
For instance this:
https://github.com/go-gorm/gorm/blob/ea8509b77704b152380f8097c59e5ae3b57428bb/callbacks/create.go#L307-L317

Is a different path taken during the Create
https://github.com/go-gorm/gorm/blob/ea8509b77704b152380f8097c59e5ae3b57428bb/schema/field.go#L890

Then in the driver `callValuerValue`, the correct Value would be called.

**Comment by a631807682** [comment]
We don't know the actual type, if the `GormDataType` you specify is not in our enum, we can only default to a certain precision.
https://github.com/go-gorm/gorm/blob/master/schema/field.go#L275
https://github.com/go-gorm/gorm/blob/master/schema/field.go#L298
