### ISSUE TITLE
FindInBatches fail when using composite primary key

### ISSUE THREAD

**Issue by fanlvG** [go-gorm/gorm#5495]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/491

## FindInBatches reports "primary key required" due to this bug.
FindInBatches works depends on sorting primaryKey.
when model has more primaryKeys, FindInBatches should use first primaryKeys as sort condition.
reference: https://gorm.io/docs/write_plugins.html

while in schema/schema.go:217. set `PrioritizedPrimaryField` has bug.
```
if schema.PrioritizedPrimaryField == nil && len(schema.PrimaryFields) == 1 {
	schema.PrioritizedPrimaryField = schema.PrimaryFields[0]
}
```

in gorm.io docs. `PrioritizedPrimaryField` described as:

>  // Prioritized primary key field: field with DB name `id` or the first defined primary key

in "Write Plugins" chapter. 

please check this out.

correct code should be like:
```
if schema.PrioritizedPrimaryField == nil && len(schema.PrimaryFields) >= 1 {
	schema.PrioritizedPrimaryField = schema.PrimaryFields[0]
}
```

**Comment by a631807682** [comment]
In the composite primary key case, the primary key is not only the sorting keyword, but also the starting condition of the next query. We cannot use prioritized primary key to implement batch query in this case.
Maybe we need to use subqueries for this case.

**Comment by fanlvG** [comment]
oh I see. If in previous query we couldn't select all records with same primaryKey1, In next query we can't use less condition to select the rest records with primaryKey1 value. So maybe FindInBatches() use ORDER BY OFFSET LIMIT will be better? 
That can handle most batch query situation. I think.

**Comment by a631807682** [comment]
@fanlvG If using offset directly will have performance issues with large data volumes, I will try to fix it later.

**Comment by tuhaolam** [comment]
It seems that the bug has not been fixed, I reproduces this bug on latest version v1.25.8.

**Comment by kawhicurry** [comment]
same issue on v1.25.12
