### ISSUE TITLE
大批量插入数据时使用sql拼装效率非常低 

### ISSUE THREAD

**Issue by MyZafkiel** [go-gorm/gorm#5501]
在大批量插入时执行sql可能只要几百ms 但是sql生成时间可能要几秒钟,由于sql生成时间也是计算在执行时间里面的那么打印慢sql日志的时候又会再次生成双倍耗时

**Comment by MyZafkiel** [comment]
`// Create create hook
func Create(config *Config) func(db *gorm.DB) {
	supportReturning := utils.Contains(config.CreateClauses, "RETURNING")

	return func(db *gorm.DB) {
		if db.Error != nil {
			return
		}

		if db.Statement.Schema != nil {
			if !db.Statement.Unscoped {
				for _, c := range db.Statement.Schema.CreateClauses {
					db.Statement.AddClause(c)
				}
			}

			if supportReturning && len(db.Statement.Schema.FieldsWithDefaultDBValue) > 0 {
				if _, ok := db.Statement.Clauses["RETURNING"]; !ok {
					fromColumns := make([]clause.Column, 0, len(db.Statement.Schema.FieldsWithDefaultDBValue))
					for _, field := range db.Statement.Schema.FieldsWithDefaultDBValue {
						fromColumns = append(fromColumns, clause.Column{Name: field.DBName})
					}
					db.Statement.AddClause(clause.Returning{Columns: fromColumns})
				}
			}
		}

		if db.Statement.SQL.Len() == 0 {
			db.Statement.SQL.Grow(180)
			db.Statement.AddClauseIfNotExists(clause.Insert{})
			db.Statement.AddClause(ConvertToCreateValues(db.Statement))

			db.Statement.Build(db.Statement.BuildClauses...)
		}

		isDryRun := !db.DryRun && db.Error == nil
		if !isDryRun {
			return
		}

		ok, mode := hasReturning(db, supportReturning)
		if ok {
			if c, ok := db.Statement.Clauses["ON CONFLICT"]; ok {
				if onConflict, _ := c.Expression.(clause.OnConflict); onConflict.DoNothing {
					mode |= gorm.ScanOnConflictDoNothing
				}
			}

			rows, err := db.Statement.ConnPool.QueryContext(
				db.Statement.Context, db.Statement.SQL.String(), db.Statement.Vars...,
			)
			if db.AddError(err) == nil {
				defer func() {
					db.AddError(rows.Close())
				}()
				gorm.Scan(rows, db, mode)
			}

			return
		}
                //生成SQL的地方 看的出来是个公用代码 
		result, err := db.Statement.ConnPool.ExecContext(
			db.Statement.Context, db.Statement.SQL.String(), db.Statement.Vars...,
		)
		if err != nil {
			db.AddError(err)
			return
		}

		db.RowsAffected, _ = result.RowsAffected()
		if db.RowsAffected != 0 && db.Statement.Schema != nil &&
			db.Statement.Schema.PrioritizedPrimaryField != nil &&
			db.Statement.Schema.PrioritizedPrimaryField.HasDefaultValue {
			insertID, err := result.LastInsertId()
			insertOk := err == nil && insertID > 0
			if !insertOk {
				db.AddError(err)
				return
			}

			switch db.Statement.ReflectValue.Kind() {
			case reflect.Slice, reflect.Array:
				if config.LastInsertIDReversed {
					for i := db.Statement.ReflectValue.Len() - 1; i >= 0; i-- {
						rv := db.Statement.ReflectValue.Index(i)
						if reflect.Indirect(rv).Kind() != reflect.Struct {
							break
						}

						_, isZero := db.Statement.Schema.PrioritizedPrimaryField.ValueOf(db.Statement.Context, rv)
						if isZero {
							db.AddError(db.Statement.Schema.PrioritizedPrimaryField.Set(db.Statement.Context, rv, insertID))
							insertID -= db.Statement.Schema.PrioritizedPrimaryField.AutoIncrementIncrement
						}
					}
				} else {
					for i := 0; i < db.Statement.ReflectValue.Len(); i++ {
						rv := db.Statement.ReflectValue.Index(i)
						if reflect.Indirect(rv).Kind() != reflect.Struct {
							break
						}

						if _, isZero := db.Statement.Schema.PrioritizedPrimaryField.ValueOf(db.Statement.Context, rv); isZero {
							db.AddError(db.Statement.Schema.PrioritizedPrimaryField.Set(db.Statement.Context, rv, insertID))
							insertID += db.Statement.Schema.PrioritizedPrimaryField.AutoIncrementIncrement
						}
					}
				}
			case reflect.Struct:
				_, isZero := db.Statement.Schema.PrioritizedPrimaryField.ValueOf(db.Statement.Context, db.Statement.ReflectValue)
				if isZero {
					db.AddError(db.Statement.Schema.PrioritizedPrimaryField.Set(db.Statement.Context, db.Statement.ReflectValue, insertID))
				}
			}
		}
	}
}`

**Comment by MyZafkiel** [comment]
一千条数据插入sql生成需要2s 加上日志耗时2s 要4s mysql执行200ms左右,差距特别大

**Comment by li-jin-gou** [comment]
使用 pprof/trace  排查一下哈
```
result, err := db.Statement.ConnPool.ExecContext(
		db.Statement.Context, db.Statement.SQL.String(), db.Statement.Vars...,
	)
```
这里是包括 生成SQL -> 获取连接 -> 执行SQL 的时间哈

**Comment by MyZafkiel** [comment]
> 使用 pprof/trace 排查哈一下
> 
> ```
> result, err := db.Statement.ConnPool.ExecContext(
> 		db.Statement.Context, db.Statement.SQL.String(), db.Statement.Vars...,
> 	)
> ```
> 
> 这里是包含生成SQL -> 获取连接 -> 执行SQL 的时间哈

抱歉,我是go新手我不会使用pprof/trace 我只能通过现有数据进行分析
![1657443339851](https://user-images.githubusercontent.com/105144634/178138148-c59aed79-f373-4ea6-8160-0f4557dfde06.png)
上面的是在DataGrip上执行的一条插入一千条数据的执行结果

![1657443443704](https://user-images.githubusercontent.com/105144634/178138196-3da7bc49-4284-49a7-94de-b660518940b5.png)
这是在gin框架中使用gorm执行插入一千条数据的使用情况,我也曾经怀疑过是mysql的原因但是这个数据告诉我应该是sql生成的时候很慢

![1657443556249](https://user-images.githubusercontent.com/105144634/178138242-5ce37355-10d1-4520-a3f3-81b941713c28.png)
这一块日志打印也执行了很长的时间

**Comment by MyZafkiel** [comment]
哦不 很抱歉在日志执行的时候好像并没有执行很长的时间那就应该可以判断是否不是sql生成的问题

**Comment by MyZafkiel** [comment]
我暂时没能理解是因为什么导致了执行时间过长

**Comment by li-jin-gou** [comment]
GORM Log 打印的时间包含：网络连接时间+ SQL 执行时间＋ Go 代码时间 + 可能的重试时间＋从连接池获取连接时间 @MyZafkiel  这些环节有问题，时间都会变长哈
- 网络连接时间:
  - 可以 ping 数据库地址测试
- SQL 执行时长
  - 理论上与数据库执行时长相同
- Go 代码时间包含
  - decode 数据库包的时间
  - 可能的 hooks 执行时间，例如保存关联的时间，可以尝试通过参数关闭 SkipHooks
- 可能的重试时间
  - 如果 dsn 的 timeout 相关参数设置过短，或者连接因为各种原因被断开
  - database/sql 会默认重试，共会重试3次
 - 从连接池获取连接时间
   -  GORM 默认开启的连接池，在连接池使用满载的情况下，尤其是压测时， SQL 会等待有可用连接后执行，等待时间包含在上述时间中
   -   - 可以通过打印 db.Stats 校验是否该情况，参考：https://gorm.io/docs/generic_interface.html

**Comment by MyZafkiel** [comment]
您好,我介绍一下我使用的环境我是本地测试环境 所有的环境的都是在本地环境运行的包括mysql 按道理连接和执行方面不会导致耗时过长而且插入一千条我都是单次测试并没有进行压力测试 而且经过几次请求都是4m以上我觉得不存在于其他意外因素

**Comment by MyZafkiel** [comment]
> GORM Log 打印的时间包含：网络连接时间+ SQL 执行时间＋ Go 代码时间 + 可能的重试时间＋从连接池获取连接时间 @MyZafkiel 这些环节有问题，时间都会变长哈
> 
> * 网络连接时间:
>   
>   * 可以 ping 数据库地址测试
> * SQL 执行时长
>   
>   * 理论上与数据库执行时长相同
> * Go 代码时间包含
>   
>   * decode 数据库包的时间
>   * 可能的 hooks 执行时间，例如保存关联的时间，可以尝试通过参数关闭 SkipHooks
> * 可能的重试时间
>   
>   * 如果 dsn 的 timeout 相关参数设置过短，或者连接因为各种原因被断开
>   * database/sql 会默认重试，共会重试3次
> * 从连接池获取连接时间
>   
>   * GORM 默认开启的连接池，在连接池使用满载的情况下，尤其是压测时， SQL 会等待有可用连接后执行，等待时间包含在上述时间中
>   * * 可以通过打印 db.Stats 校验是否该情况，参考：https://gorm.io/docs/generic_interface.html

我经过调试断点的方式我已经确定执行耗时的地方了 就是这块代码函数
`result, err := db.Statement.ConnPool.ExecContext(
		db.Statement.Context, db.Statement.SQL.String(), db.Statement.Vars...,
	)`
