### ISSUE TITLE
哪位大佬实现一下这个自增id的pr吧

### ISSUE THREAD

**Issue by jimmyduang** [go-gorm/gorm#5505]

**Comment by wxy2077** [comment]
这个应该是 gorm model迁移产生的问题，对吧？

如果不是可以忽略我这个回答。

如果是的话，我建议可以使用 第三方工具来管理表迁移相关操作，比如[`sql-migrate`](github.com/rubenv/sql-migrate), 使用例子可以参考我这个[仓库](https://github.com/wxy2077/gorm-example/blob/main/02_migrate/README.md) 。

**Comment by jimmyduang** [comment]
> 这个应该是 gorm model迁移产生的问题，对吧？
> 
> 如果不是可以忽略我这个回答。
> 
> 如果是的话，我建议可以使用 第三方工具来管理表迁移相关操作，比如[`sql-migrate`](github.com/rubenv/sql-migrate), 使用例子可以参考我这个[仓库](https://github.com/wxy2077/gorm-example/blob/main/02_migrate/README.md) 。

不是的哈，是[gen](gorm.io/gen) 生成model中包含tag:autoIncrement;但是之后反向migrate的时候，并没有生成自增id，
不过这里有个pr，但是现在没人审阅

**Comment by ancheGT** [comment]
我感觉可能是 postgres 的原因,只要insert语句里指定了id,那么seq的自增就会有问题,它没有跟随insert时指定的id增加,还是之前的值,我的id有很多都不是连续的,用postgres的所谓自增会出现不少问题,估计我得用回mysql了,尴尬

**Comment by a631807682** [comment]
Done https://github.com/go-gorm/postgres/pull/121 https://github.com/go-gorm/mysql/pull/83
