### ISSUE TITLE
can i use association feature without create foreignkey?

### ISSUE THREAD

**Issue by MarsonShine** [go-gorm/gorm#5506]
## Your Question

can i use association feature without create foreignkey?
eg: [Auto Create/Update](https://gorm.io/docs/associations.html#Auto-Create-x2F-Update)、[Eager Loading](https://gorm.io/docs/has_many.html#Eager-Loading)

## The document you expected this should be explained

most of time we don't explicity create foreignkey, for convenient

**Comment by MarsonShine** [comment]
sorry, i use wrong template

**Comment by MarsonShine** [comment]
someone reply that?

**Comment by a631807682** [comment]
https://gorm.io/docs/gorm_config.html#DisableForeignKeyConstraintWhenMigrating

**Comment by MarsonShine** [comment]
> https://gorm.io/docs/gorm_config.html#DisableForeignKeyConstraintWhenMigrating

no，this question not for migration.
i want to use this feature: https://gorm.io/docs/preload.html without foreignkey

**Comment by a631807682** [comment]
You defined the relationship and then you can use it without actually creating the foreign key

**Comment by MarsonShine** [comment]
thanks，i'll try it
