### ISSUE TITLE
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time (SQLSTATE 21000)

### ISSUE THREAD

**Issue by jolienai** [go-gorm/gorm#5527]
Hi guys, today I am testing gorm (gorm.io/gorm v1.23.8 // indirect) upsert and getting this error below. Is this fixed already? How can avoid it?

ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time (SQLSTATE 21000)

My code
`	err := database.db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "sku"}, {Name: "country"}},
		DoUpdates: clause.AssignmentColumns([]string{"quantity"}),
	}).CreateInBatches(&products, 5000).Error`

`type Product struct {
	gorm.Model
	Sku      string `gorm:"index:,unique,composite:myname"`
	Country  string `gorm:"index:,unique,composite:myname"`
	Name     string
	Quantity int
}`

**Comment by jolienai** [comment]
Never mind, just removed duplicated values from array

**Comment by allidoisace** [comment]
@jolienai How did you end up removing the duplicate values?

**Comment by jolienai** [comment]
I just write the deduplicated method here  https://github.com/jolienai/go-products-api/blob/main/cmd/app/jobs/product_bulk_job.go#L60
