### ISSUE TITLE
default value for slice

### ISSUE THREAD

**Issue by nikhrom** [go-gorm/gorm#5529]
## Default value for slice

Is there a way to declare a default value for slice like this?
```
type SoftwareComponent struct {
	Id             int                      `json:"id"`
	Name           string                   `json:"name"`
	Version        string                   `json:"version"`
	Licenses       dbtypes.StringSlice      `gorm:"default:['UNKNOWN']"`    // <-----  ???
}
```

Remark: dbtypes.StringSlice is []string with implemented `Value() (driver.Value, error)` and `Scan(val interface{}) error`

**Comment by a631807682** [comment]
```go
( ... ) Value() (driver.Value, error) {
	// set value if fieldValue is null or empty
}
```

**Comment by nikhrom** [comment]
but then the default value will be the same for all structures that use fields with the dbtypes.StringSlice type.  And it is necessary that it be possible to assign a default value for a specific field

**Comment by a631807682** [comment]
parse `field.DefaultValue` from string to string slice yourself

**Comment by nikhrom** [comment]
Wouldn't it be difficult to show how to do it? I can't figure out exactly how to get the DefaultValue and where to parse it.

Thank you for your time

**Comment by a631807682** [comment]
```go
type struct .. {
	Licenses  dbtypes.StringSlice      `gorm:"default:['UNKNOWN']"`
}
func (StringSlice) Value(ctx context.Context, field *Field, dst reflect.Value, fieldValue interface{}) (interface{}, error) {
	// now field.DefaultValue is "['UNKNOWN']"
	
	// pseudo code, please use reflect
	if fieldValue == nil {
		return []string{"UNKNOWN"}, nil
	}
}
	
```

**Comment by nikhrom** [comment]
Thanks!!!
