### ISSUE TITLE
Default value with slice

### ISSUE THREAD

**Issue by nikhrom** [go-gorm/gorm#5530]
## Your Question

Is there a way to declare a default value for slice like this?
```
type SoftwareComponent struct {
	Id             int                      `json:"id"`
	Name           string                   `json:"name"`
	Version        string                   `json:"version"`
	Licenses       dbtypes.StringSlice      `gorm:"default:['UNKNOWN']"`    // <-----  ???
}
```

Remark: dbtypes.StringSlice is []string with implemented `Value() (driver.Value, error)` and `Scan(val interface{}) error`

## Expected answer

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/5529

**Comment by nikhrom** [comment]
but then the default value will be the same for all structures that use fields with the dbtypes.StringSlice type.  And it is necessary that it be possible to assign a default value for a specific field
