### ISSUE TITLE
How to update the connection string for new connection in the conn pool?

### ISSUE THREAD

**Issue by Shubham510** [go-gorm/gorm#5531]
## Your Question
How to update the connection string for new connection in the conn pool?

## The document you expected this should be explained
I am trying to use AWS IAM authentication for the connection to RDS instance. The auth token provided by i9t is only valid for 15 mins and any attempt to open new connection after that fails. Is there a way to update the connection string for the new connections being added to the connection pool by checking if the token has expired?

## Expected answer
I want to be able to update the connection string, if the token has expired.

**Comment by a631807682** [comment]
You can customize the timer and replace `db` or `db.ConnPool` after locking

**Comment by Shubham510** [comment]
> You can customize the timer and replace `db` or `db.ConnPool` after locking

How do I put a lock and apply the change in a thread safe way. From what I have read so far, on changing the value for `db`, the old connection remain in an open state and are not closed.

**Comment by a631807682** [comment]
https://gorm.io/docs/generic_interface.html#content-inner

**Comment by ploynomail** [comment]
I also encountered this problem when using vault to dynamically obtain the mysql password in the gorm framework. Is there a solution? @Shubham510

**Comment by uded** [comment]
```
	pgxConfig, err := pgx.ParseConfig(dsn)
	if err != nil {
		panic()
	}

	optBeforeConnect := stdlib.OptionBeforeConnect(func(ctx context.Context, connConfig *pgx.ConnConfig) error {
		var err error
		connConfig.Password = token
		connConfig.Database = database
		connConfig.Host = host
		connConfig.Port = port
		connConfig.User = user
		connConfig.Password = token
		connConfig.Password = token
		connConfig.SSLMode = sslMode

		return err
	})

	sqlDB := stdlib.OpenDB(*pgxConfig, optBeforeConnect)
```

There is no need to write your driver. All components are already there from `pgx` package...
