### ISSUE TITLE
How to insert field in custom join table ?

### ISSUE THREAD

**Issue by wavemoroc001** [go-gorm/gorm#5563]
## Your Question
Hi, there I have following models accounts, class_members and classes.

**Business logic**
 if student (account has role student) want to join class. They need to send request and wait teacher to approve to join class.
My question is how to edit `status` field in associate table for stamp request status like approved, requested, denied

**Relationship** 

<img width="778" alt="Screenshot 2565-08-02 at 00 27 11" src="https://user-images.githubusercontent.com/56395197/182207471-43928b33-7b9a-4c0c-a95d-b2f1c6c8c572.png">

- account (role student) can join many class
- class can own by account (role teacher)

**This is Models**

```go
type Account struct {
	gorm.Model
	Title     string
	Fname     string `gorm:"column:fname"`
	Lname     string `gorm:"column:lname"`
	StudentNo string
	Email     string  `gorm:"unique"`
	Classes   []Class `gorm:"many2many:class_members"`
	School    School
	SchoolID  *uint
	Role      Role
	RoleID    uint
	Password  string
}
```

```go 
type Class struct {
	gorm.Model
	ClassName    string
	ClassType    string
	ExpireAt     time.Time
	ClassCode    string    `gorm:"size:6"`
	Participants []Account `gorm:"many2many:class_members"`
	Owner        Account
	OwnerID      uint
}
```

```go 
type ClassMember struct {
	Status    string
	AccountID uint `gorm:"primaryKey"`
	ClassID   uint `gorm:"primaryKey"`
	CreatedAt time.Time
	DeletedAt gorm.DeletedAt
}
```

## The document you expected this should be explained

I have searched follow thees link but I  still not sure how to edit the `status` field in associate table. I think it should explain in  associations page

https://gorm.io/docs/many_to_many.html
https://gorm.io/docs/associations.html

## Expected answer

Cloud you give some solution to edit `status` field ?

**Comment by a631807682** [comment]
https://gorm.io/docs/many_to_many.html#Customize-JoinTable

**Comment by wavemoroc001** [comment]
@a631807682  Cloud you give some detail to stamp `status` in class member table ?

**Comment by a631807682** [comment]
This design means that status is neither account status nor class status, we can't read status from anywhere and populate it, I don't know if [hook](https://gorm.io/docs/hooks.html#content-inner) or [callback](https://gorm.io/docs/write_plugins.html#Register-Callback) are useful to you, if not you can only insert each table yourself

**Comment by alfman99** [comment]
Whats the way to pass a custom value you want for the custom field to the BeforeCreate hook, as it cannot receive parameters?

**Comment by wavemoroc001** [comment]
@a631807682  
Maybe it need to change relationship from `many2many` to `one to many` in go models  is that right ? 
and mange table by myself

**Comment by a631807682** [comment]
@alfman99  use settings or context  https://gorm.io/docs/settings.html#content-inner

@wavemoroc001 If this can meet your needs, of course. in fact, our `association` operation is also implemented based on ordinary api, you can also implement it according to your own needs.

**Comment by alfman99** [comment]
> @alfman99 use settings or context https://gorm.io/docs/settings.html#content-inner

Yes, this solves my problem, do you know if this solution its thread safe? 

Thanks!
