### ISSUE TITLE
Create with non-zero defaults ignores values being inserted

### ISSUE THREAD

**Issue by jlagermann** [go-gorm/gorm#5576]
When a struct has gorm default set to a non-zero value, if the value being created is a zero value, it will be ignored and the default will be used.

```
type Source struct {
  gorm.Model
  Name             string
  URL                string `gorm:"unique;unique_index"`
  Cache             bool  `gorm:"default:true"
}

source := Source{
	Name: "Test",
	URL:    "https://test.com",
	Cache: false,
}

db.Create(&source)
```

The output:
```
[5.831ms] [rows:1] INSERT INTO `sources` (`created_at`,`updated_at`,`deleted_at`,`name`,`url`,`cache`) VALUES ("2022-08-04 14:26:16.065","2022-08-04 14:26:16.065",NULL,"Test","https://test.com",true) RETURNING `id`
```

The expected behavior should be:
```
[5.831ms] [rows:1] INSERT INTO `sources` (`created_at`,`updated_at`,`deleted_at`,`name`,`url`,`cache`) VALUES ("2022-08-04 14:26:16.065","2022-08-04 14:26:16.065",NULL,"Test","https://test.com",false) RETURNING `id`
```

**Comment by jlagermann** [comment]
After some additional testing, I changed the description.
_When a struct has gorm default set to a non-zero value, if the value being created is a zero value, it will be ignored and the default will be used._

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/5541

**Comment by jlagermann** [comment]
This is similar to #5541 but not a duplicate.  #5541 only addresses `bool` values.  The issue is related to creating a record with a zero value that has a non-zero default.

**Comment by a631807682** [comment]
> If a value is zero, there is no way to tell whether it is a default value or a user-specified value. You can also use *bool to tell us it is specified value

The reason here also applies to other zero-value types

**Comment by jlagermann** [comment]
Is there a way to force it to create with the zero value?  I can update with zero values with `db.Select("*").Updates(&source)`.  Is there a similar method for Create()?

**Comment by a631807682** [comment]
Not currently supported, are you interested in creating a PR for this?

**Comment by jlagermann** [comment]
I would be interested if I understood all the pieces that need to be updated to support this.  I'm using sqlite3.

Without this capability, the gorm defaults don't really work.  The idea with defaults is to provide a value when the input does not provide one.  In the current implementation, the default value is used unless the input provides another non-zero value.

If you set the default for a `bool` to `true`, it will be created as `true` 100% of the time.
If you set a `string` default to some value, it can never be created with a zero value.
