### ISSUE TITLE
How to clear previous query criteria

### ISSUE THREAD

**Issue by iwanzhang** [go-gorm/gorm#5587]
In one method, I need to query different tables. How to clear the previous query criteria

**Comment by ehabterra** [comment]
I have found that some properties are not getting reset after executing the query. The workaround is to try to empty the cached table name property to be able to specify another table. Here is an example of how to do that:
```go
var db  *gorm.DB

// First query execution
...

// Reset table name
db.Statement.Table = ""

// Second query execution
...
```

**Comment by a631807682** [comment]
https://gorm.cn/docs/method_chaining.html#New-Session-Mode
