### ISSUE TITLE
mysql 连接池设置了连接可复用最大时间时，超出时间的连接并没有被close掉

### ISSUE THREAD

**Issue by Orange-Yellow** [go-gorm/gorm#5594]
`

// 获取通用数据库对象 sql.DB ，然后使用其提供的功能
sqlDB, err := db.DB()

// SetMaxIdleConns 用于设置连接池中空闲连接的最大数量。
sqlDB.SetMaxIdleConns(10)

// SetMaxOpenConns 设置打开数据库连接的最大数量。
sqlDB.SetMaxOpenConns(100)

// SetConnMaxLifetime 设置了连接可复用的最大时间。
sqlDB.SetConnMaxLifetime(time.Minute)
`
![image](https://user-images.githubusercontent.com/40858423/184053788-7aacde80-63fe-40ef-a81c-6f626502ddea.png)

连接时长超过设置的最大时间了，连接没有被关掉，而且也不能复用。导致链接数一直在增加，达到最大连接数时导致整个服务阻塞掉了

**Comment by WEIR-ZHONG** [comment]
> 

这个问题解决了吗

**Comment by Orange-Yellow** [comment]
> > 
> 
> 这个问题解决了吗

没有。。。

**Comment by Orange-Yellow** [comment]
问题解决了，是开启事务后没有关掉事务，导致连接数一直增加。
