### ISSUE TITLE
How do we store and read ip addresses inet datatypes with GORM and PostgreSQL?

### ISSUE THREAD

**Issue by encryptblockr** [go-gorm/gorm#5606]
How do we insert and select from a table with `inet` datatype using GORM?

here is my model

```
import (
    "github.com/jackc/pgtype"
)

...
ClientIp     pgtype.Inet `json:"client_ip" gorm:"type:inet;not null"`
...
```

I am trying to parse the ip address which is in string format to type `pgtype.Inet` in postgresql database
like this when inserting into the database

```
import (
    "net"
)

...
ClientIp:     net.ParseIP(c.IP()),
...
```

we are told to [parse the ip using `net` package][1] but this is error from that

```
cannot use net.ParseIP(c.IP()) (type net.IP) as type pgtype.Inet in field value
```

  [1]: https://github.com/jackc/pgtype/blob/master/inet.go#L52

I have also tried using `net` package for the model 

```
import (
    "net"
)

...
ClientIp     net.IP `json:"client_ip" gorm:"type:inet;not null"`
...
```

but kept getting this error

```
sql: Scan error on column index 16, name "client_ip": unsupported Scan, storing driver.Value type string into type *net.IP
```

I am able to insert the data but when i try to run select query on the table, i can the scan error above

How do we insert and select from a table with `inet` datatype using GORM?

**Comment by encryptblockr** [comment]
seriously need help with this, please

**Comment by encryptblockr** [comment]
@jinzhu 

i added reproduction steps

why is this labelled unfairly?

**Comment by ralfonso-directnic** [comment]
@encryptblockr you need to use the pgtype.Inet methods, ie 

```
var myip pgtype.Inet

myip.Set("127.0.0.1")

~~~~

ClientIP:   myip 
````
The error says it right there, net.ParseIP(c.IP()) returns a net.IP but ClientIP is of type pgtype.Inet
