### ISSUE TITLE
Inconsistent results were detected using the same SQL

### ISSUE THREAD

**Issue by Jacky-YC** [go-gorm/gorm#5617]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/505

###
Test Data
```csv
start_time,end_time,id
2022-06-24 10:18:03,2022-06-24 10:18:03,4
2022-07-01 00:00:00,2022-07-01 01:00:00,6
2022-07-01 05:00:00,2022-08-01 00:00:00,10
```

gorm result: 1
```shell
2022/08/16 20:41:10 test.go:57
[0.219ms] [rows:1] SELECT * FROM `test` WHERE start_time >= "2022-07-01 00:00:00"
```

sqlite teminal result: 2
```shell 
sqlite> SELECT * FROM `test` WHERE start_time >= "2022-07-01 00:00:00";
2022-07-01 00:00:00|2022-07-01 01:00:00|6
2022-07-01 05:00:00|2022-08-01 00:00:00|10
```

gorm result: 3
```shell
[0.195ms] [rows:3] SELECT * FROM `test` WHERE e_time < "2022-08-01 00:00:00"
```

sqlite terminal result: 2
```shell
sqlite> SELECT * FROM `test` WHERE e_time < "2022-08-01 00:00:00";
2022-06-24 10:18:03|2022-06-24 10:18:03|4
2022-07-01 00:00:00|2022-07-01 01:00:00|6
```

Inconsistent results were detected using the same SQL

sqlite> .version
SQLite 3.39.2 2022-07-21 15:24:47 698edb77537b67c41adc68f9b892db56bcf9a55e00371a61420f3ddd668e6603
zlib version 1.2.12
gcc-5.4.0 20160609

go version
go version go1.19 linux/amd64

gorm.io/driver/sqlite v1.3.6
gorm.io/gorm v1.23.8
github.com/mattn/go-sqlite3 v1.14.14

**Comment by Jacky-YC** [comment]
![image](https://user-images.githubusercontent.com/42370375/185039330-efaac913-60a6-43c1-b4bc-bf04edad1bac.png)



使用golang原生的sql查询 结果与预期相符；所以确定问题是由gorm导致的

**Comment by Jacky-YC** [comment]
sqlite 查询time.Time 被转为：”2022-07-01 00:00:00+00:00“ 串，查出结果与”2022-07-01 00:00:00“ 结果不一致
![image](https://user-images.githubusercontent.com/42370375/185085189-6027c68a-8e82-4209-9f73-350aaa00f7e3.png)

**Comment by a631807682** [comment]
It's a time zone issue, it has nothing to do with gorm, even if you use other drivers, it only depends on whether you use the interpolate params or not.
