### ISSUE TITLE
bug: update sql does't return error in myql5.7 

### ISSUE THREAD

**Issue by feiyangbeyond** [go-gorm/gorm#5631]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/509

## Description

see pr⬆️

**Comment by a631807682** [comment]
```diff
- update users set name = ? and age = ? where id = ?
+ update users set name = ?, age = ? where id = ?;
```

**Comment by feiyangbeyond** [comment]
> ```diff
> - update users set name = ? and age = ? where id = ?
> + update users set name = ?, age = ? where id = ?;
> ```

I mean it should return an error. but worked. 
 
In latest mysql, gorm return an error

**Comment by a631807682** [comment]
I can't use mysql 5.7 image in mac m1, gorm will not change raw sql, you can try to use https://github.com/go-sql-driver/mysql to compare different versions
