### ISSUE TITLE
There is a problem with SQL injection when querying with SELECT

### ISSUE THREAD

**Issue by 2292384454** [go-gorm/gorm#5632]
## GORM Playground Link

I created a `Device` model and automatically generated the table, then used the `Select` method to query its fields and the results were stored in a `map[string]interface{}`. But the `set` field threw an error because sql injection happened.

https://github.com/go-gorm/playground/pull/511

## Description

I created a `Device` model and automatically generated the table, then used the `Select` method to query its fields and the results were stored in a `map[string]interface{}`. But the `set` field threw an error because sql injection happened.

```go
/* models */
type Device struct {
	Host     string  `gorm:"column:host"`
	Set      string  `gorm:"column:set"`
	CpuUsage float64 `gorm:"column:cpu_usage"`
}
```

```go
/* main_test */
func TestGORM(t *testing.T) {
	device := Device{Host: "111.111.111.111", Set: "NY14536", CpuUsage: 6.31}

	DB.Create(&device)

	var result []map[string]interface{}
	fields := []string{"host", "cpu_usage", "set"}
	if err := DB.Debug().Table("devices").Select(fields).Find(&result).Error; err != nil {
		t.Errorf("Failed, got error: %v", err)
	}
}
```
<img width="2055" alt="企业微信20220823-122136@2x" src="https://user-images.githubusercontent.com/30790929/186069111-16f8030d-eece-480a-8d63-6cf975b0bbe9.png">

**Comment by a631807682** [comment]
https://gorm.io/docs/security.html#SQL-injection-Methods
