### ISSUE TITLE
Please add support Fiber.Map for parameter and result

### ISSUE THREAD

**Issue by tercnem** [go-gorm/gorm#5653]
## Describe the feature

make fiber.Map for parameter and result rather than write result := map[string]interface{}{} example : 
```
func GetUserAdmin()fiber.Map{
  param := fiber.Map{"username":"admin"}
  result :=fiber.Map{}
  db.Raw("select * from user where username = @username", param).Scan(&result)
  return result
}
```

## Motivation

make it more simple and more easier when used with fiber.

**Comment by li-jin-gou** [comment]
@tercnem  Won't use a three-way library
