### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hktalent** [go-gorm/gorm#5669]
step1:
```
x1 = dbCC.WithContext(context.Background()).Model(&mode).Limit(nPageSize).Offset(Offset*nPageSize).Order("updated_at DESC").Find(&aRst, conds...)
defer func() {
		if nil != x1 {
			if r, err := x1.Rows(); nil == err {
				r.Close()
			} else if nil != x1.Statement {
				if r, err := x1.Statement.Rows(); nil == err {
					r.Close()
				}
			}
		}
	}()
```
reflect.unsafe_NewArray
step2:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/18223385/188066039-cf8ce677-5aa5-4e45-b0ba-a405fe114326.png">
step3:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/18223385/188052283-c107982f-6bea-455d-977a-732d208c020d.png">

**Comment by hktalent** [comment]
logfile 
[pprof.zbserver_linux_amd64.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz](https://github.com/go-gorm/gorm/files/9475091/pprof.zbserver_linux_amd64.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz)

**Comment by frank0r** [comment]
same here.

**Comment by starryrbs** [comment]
same here.

**Comment by joe991** [comment]
same here.

**Comment by ningzio** [comment]
got same issue here.

**Comment by qiu260028891** [comment]
same issue here

**Comment by a631807682** [comment]
If you still encounter this problem, please provide the reproduction code.

**Comment by oneart-dev** [comment]
Same issue, leaking very badly. Same heap allocation with unsafe_NewArray

**Comment by ManyakRus** [comment]
I have big memory leak too
WithContext() - have big memory leak,
when i delete this method - no memory leak
