### ISSUE TITLE
How can I change the character set of a field in Fields Tags

### ISSUE THREAD

**Issue by Gpihuier** [go-gorm/gorm#5675]
### something like this

```go
type Tag struct {
  gorm.Model
  TagName string `gorm:"CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"`
}
```
### or 
```go
type Tag struct {
  gorm.Model
  TagName string `gorm:"character_set:utf8mb4;collate:utf8mb4_bin"`
}
```
### but no effect

**Comment by a631807682** [comment]
We do not support for column, you can set the encoding of db.
https://gorm.io/docs/connecting_to_the_database.html#MySQL

**Comment by Gpihuier** [comment]
> We do not support for column, you can set the encoding of db. https://gorm.io/docs/connecting_to_the_database.html#MySQL

thanks
