### ISSUE TITLE
使用了 DBResolver 读写分离怎么获取对应的数据库连接地址 和 DB.Stats()

### ISSUE THREAD

**Issue by JellyZero** [go-gorm/gorm#5678]
使用了 DBResolver 读写分离怎么获取对应的数据库连接地址 和 DB.Stats()

**Comment by li-jin-gou** [comment]
@JellyZero  思路是遍历 `Gorm` 的 `Plugin`, 获取到 `DBResolver`,这样就可以对应所有的数据库连接，从而获取 DB.Stats()

@zstone12  https://github.com/go-gorm/opentelemetry 看看是否需要适配这个场景

**Comment by JellyZero** [comment]
> DBResolver

获取 链接dns 呢？我尝试过反射获取不到，能贴一下代码吗

**Comment by JellyZero** [comment]
> @JellyZero 思路是遍历 `Gorm` 的 `Plugin`, 获取到 `DBResolver`,这样就可以对应所有的数据库连接，从而获取 DB.Stats()
> 
> @zstone12 https://github.com/go-gorm/opentelemetry 看看是否需要适配这个场景

获取 链接dns 呢？我尝试过反射获取不到，能贴一下代码吗

**Comment by li-jin-gou** [comment]
> > @JellyZero 思路是遍历 `Gorm` 的 `Plugin`, 获取到 `DBResolver`,这样就可以对应所有的数据库连接，从而获取 DB.Stats()
> > @zstone12 https://github.com/go-gorm/opentelemetry 看看是否需要适配这个场景
> 
> 获取 链接dns 呢？我尝试过反射获取不到，能贴一下代码吗

gorm 没有提供获取 DSN 的接口并且不会提供，用户如果想要获取的话可以自行获取

**Comment by JellyZero** [comment]
> 没有提供获取 DSN 的接口并且不会提供，用户如果想要获取的话可以自行获取

咋获取呢？没有这种需求吗？使用了读写分离插件就不知道是哪个连接在操作啊

**Comment by li-jin-gou** [comment]
使用反射
