### ISSUE TITLE
Count function not use TableName method

### ISSUE THREAD

**Issue by lightnine** [go-gorm/gorm#5697]
## Your Question
![image](https://user-images.githubusercontent.com/16683968/190150815-f05120f5-0480-421a-b9d7-29ee39f2b34b.png)
if i use the CountRoleByIds function, then report 
`unsupported data type: 0x1400003a688: Table not set, please set it like: db.Model(&user) or db.Table`
but when i use the GetRoleByIds function, it's ok. 
**why Count not use the TableName**

**Comment by a631807682** [comment]
Because we have no way to get the table name
