### ISSUE TITLE
sqlite3: collate nocase in where condition

### ISSUE THREAD

**Issue by donnol** [go-gorm/gorm#5712]
I have a table:

```sql
create table test
(
  field  text
);

insert into test values ('A');
```

I want to use `select * from test where field = ? collate nocase`, so no matter input 'a' or 'A' will get the row.

 Can that work with gorm?

**Comment by li-jin-gou** [comment]
A not-so-good idea is `Db.***.Where("field = ? collate nocase").Find()`

**Comment by li-jin-gou** [comment]
There is another option to consider  https://gorm.cn/docs/sql_builder.html#Clauses and you need define a self-custom clause.
