### ISSUE TITLE
AutoMigrate重复创建唯一索引？

### ISSUE THREAD

**Issue by congjunhua** [go-gorm/gorm#5715]
## Your Question

```
type User struct {
    gorm.Model
    PublicID uint `gorm:"type:char(10);not null;unique"`
}

db.AutoMigrate(&User{})
```

为什么这样子写法每次重新运行程序时`MySQL`都会增加一个键和索引呢？

```mysql
-- key
public_id
public_id_1
public_id_2
public_id_3
...

-- unique
public_id
public_id_1
public_id_2
public_id_3
...
```

直到报`Error 1069: Too many keys specified; max 64 keys allowed`错误。

**Comment by CharellKing** [comment]
老铁，我也遇到这样的问题，你是怎么解决的

**Comment by congjunhua** [comment]
> 老铁，我也遇到这样的问题，你是怎么解决的

将 `unique` 换成 `uniqueIndex` 。

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/issues/6381#issuecomment-1929427042
