### ISSUE TITLE
skip updating created_at column while using gorm Update with associations

### ISSUE THREAD

**Issue by hemantsr** [go-gorm/gorm#5724]
**Background**
We are using [gorm association](https://gorm.io/docs/associations.html) as we have nested hierarchy. We are using [Create()](https://gorm.io/docs/create.html#Create-Record) for creation of records across multiple tables and Updates opeartion for updating the records.

**Issue**
During the update we do not want to change the created_at timestamp. 
For top level struct/ record, this is working fine and created_at column is not updated. However, for nested records created_at timestamp is changed always on performing update operation. On update, we just want to update the updated_at column and keep created_at intact. 

Structs:

   

     

        struct A { 
          ID                     string          `gorm:"column:id;type:char(36); not null;primary_key"`
          B                      []*B            `gorm:"foreignKey:AID;references:ID"`
          CreatedAt              time.Time       `gorm:"column:created_at;type:timestamp; not null"`
          UpdatedAt              time.Time       `gorm:"column:updated_at;type:timestamp; not null"`
        }
             
            
        struct B {
          ID                       string     `gorm:"column:id;type:char(36); not null;primary_key"`
          AID                      string     `gorm:"column:aid;type:char(36); not null"`
          C                        []*C       `gorm:"foreignKey:BID;references:ID"`
          CreatedAt                time.Time  `gorm:"column:created_at;type:timestamp; not null"`
          UpdatedAt                time.Time  `gorm:"column:updated_at;type:timestamp; not null"`
       }
        
       struct C {
          ID                       string     `gorm:"column:id;type:char(36); not null;primary_key"`
          BID                      string     `gorm:"column:bid;type:char(36); not null"`
          CreatedAt                time.Time  `gorm:"column:created_at;type:timestamp; not null"`
          UpdatedAt                time.Time  `gorm:"column:updated_at;type:timestamp; not null"`
     }

Below is the snippet of code how we are updating the records:

``` 
txn.Session(&gorm.Session{Context: ctx, FullSaveAssociations: true}).
		Updates(record)
```

**Things tried:**
1. Omit: we have tried using db.omit("B.CreatedAt, B.C.CreatedAt"). However, this is not working.
2. <-:create: This leads to failure in Unit tests with reason: there is a remaining expectation which was not matched. Essentially, nested records are not persisted.

**Comment by daolis** [comment]
@hemantsr, @ankit16-19 
I had the same issue:
Fixed it by adding `gorm:"<-:create"` to CreatedAt and CreatedBy
