### ISSUE TITLE
dbresolver v1.2.3编译错误

### ISSUE THREAD

**Issue by zsy619** [go-gorm/gorm#5743]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

go.mod引用：
```go
	gorm.io/gorm v1.24.0
	gorm.io/plugin/dbresolver v1.2.3
```
编译出现如下错误：
```shell
2022/10/08 10:15:38 ERROR    ▶ 0006 Failed to build the application: # gorm.io/plugin/dbresolver
/go/pkg/mod/gorm.io/plugin/dbresolver@v1.2.3/dbresolver.go:139:18: 
cannot use map[string]gorm.Stmt{} (value of type map[string]gorm.Stmt) as type map[string]*gorm.Stmt in struct literal
```
截图如下：
![image](https://user-images.githubusercontent.com/6278792/194683335-b93addb1-15bc-4022-a840-42293c2f1d77.png)

**Comment by jinzhu** [comment]
Fixed that,please upgrade dbresolver to latest version.

Thank you for your report.

**Comment by zsy619** [comment]
> Fixed that,please upgrade dbresolver to latest version.
> 
> Thank you for your report.

dbresolver 最新版本是v1.2.3，更新之后还是不行？还需要如何操作
gorm v1.24.0这个版本有问题，降级到 v1.23.0 可以编译通过

**Comment by zsy619** [comment]
看了下gen项目，引用的gorm.io/plugin/dbresolver v1.2.2
