### ISSUE TITLE
FirstOrCreate is not thread safe

### ISSUE THREAD

**Issue by Mevaser** [go-gorm/gorm#5803]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/536

## Description
Calling FirstOrCreate from multiple gouroutines for the same object results in a `UNIQUE constraint failed` error.

### Note
Maybe FirstOrCreate is not supposed to be safe by choice, i couldn't find any mention of that except this https://github.com/go-gorm/gorm/issues/2760, if it is by design maybe mention that in the documentation? i found in [v1 docs](https://v1.gorm.io/docs/method_chaining.html#Thread-Safety) that "GORM is safe for concurrent use by multiple goroutines."

**Comment by a631807682** [comment]
Errors can occur as long as the operation is not atomic for database, it has nothing to do with thread safety. The database may be changed by any process, you need to avoid it by locking.

Refer to the following pseudo code:
```
  app1.Find
  app2.Delete
  app1.Update // throw err, record has been deleted
```

For gorm you can use `OnConflict` but it won't solve all problems.
```go
tx := DB.Clauses(clause.OnConflict{
		UpdateAll: true,
})
tx.FirstOrCreate(&languageCopy)
```
