### ISSUE TITLE
Is gorm really supports SQL views?

### ISSUE THREAD

**Issue by fatihatessofttech** [go-gorm/gorm#5806]
## Your Question

I found a couple of view related issues but they don't meet my request either.  

I want to manage my views through Migrator. But I couldn't get a result on a docs/tests/gitter for this. So, Is gorm supports SQL Views?

## The document you expected this should be explained

I am here because there is no link.

## Expected answer

I am expecting a document or if it does not support, I would like help on how to proceed with the views.

**Comment by a631807682** [comment]
please move to https://github.com/go-gorm/gorm/issues/4966
