### ISSUE TITLE
How can I use ForceIndex with Join or left join

### ISSUE THREAD

**Issue by burtgithub** [go-gorm/gorm#5808]
## GORM Playground Link

when use  use Index or Force index  this tag is add before the where  
just like

DB.Clauses(hints.ForceIndex("user_name")).Joins("b").Find(&A{})

select a.* from a join b on(a.id=b.id) Force Index ("user_name")   where a.id>0

this sql is error

need after from  

how can i use it  

looking forward to a reply

## Description

DB.Clauses(hints.ForceIndex("user_name")).Joins("b").Find(&A{})

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/5808
move there to discuss
