### ISSUE TITLE
Error "WHERE conditions required" when chaingin Model() and Save()

### ISSUE THREAD

**Issue by lindroth** [go-gorm/gorm#5817]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/538
## Description
When chaining `Model()` and `Save()` on a model where the primary key can be updated only on create (<-:create) and a pointer to a model is passed this will result in a `WHERE conditions required` error.

**Comment by a631807682** [comment]
https://gorm.io/docs/update.html#Update-single-column
> When updating a single column with Update, it needs to have any conditions or it will raise error ErrMissingWhereClause, checkout [Block Global Updates](https://gorm.io/docs/update.html#block_global_updates) for details.
When using the Model method and its value has a primary value, the primary key will be used to build the condition, for example:

`Save` is the same
