### ISSUE TITLE
How can i close rows from DB.Raw().Scan()?

### ISSUE THREAD

**Issue by KrullBorg** [go-gorm/gorm#5820]
## Your Question

i'm using postgresql and using DB.Raw().Scan() gorm creates a lot of connections... i had the same problem without gorm, but i solved closing Rows just after the use. How can i do the same thing with gorm?

**Comment by li-jin-gou** [comment]
refer to https://github.com/go-gorm/gorm/blob/master/finisher_api.go#L513 and It should be closed.
