### ISSUE TITLE
gen生成的代码，可以不定条件查询吗？

### ISSUE THREAD

**Issue by lxyer** [go-gorm/gorm#5823]
使用gorm是可以这样的：当使用struct查询时，GORM只对非零字段进行查询，也就是说如果你的字段的值是0，''，false或其他[零值](https://tour.golang.org/basics/12)，它将不会被用来建立查询条件。
如果我使用gen的写法支持吗？

**Comment by li-jin-gou** [comment]
我认为这个 issue 可以提在 gen 的仓库下.
