### ISSUE TITLE
Escape LIKE parameters containing wildcard characters like % (and _)

### ISSUE THREAD

**Issue by ju-popov** [go-gorm/gorm#5828]
## Your Question

In [GORM documentation][1] there is an example how to use LIKE conditions:

    // LIKE
    db.Where("name LIKE ?", "%jin%").Find(&users)
    // SELECT * FROM users WHERE name LIKE '%jin%';

The problem that I have with this approach is that if `jin` is user input variable it can contain wildcard symbols like `%`. How can I escape such wildcard symbols?

For me these symbols must be used in the left part like:

    db.Where("name LIKE %?%", "jin").Find(&users)

OR

    db.Where("name LIKE '%' || ? || '%'", "jin").Find(&users)

and the ORM should escape automatically the parameter, but this is not how it behaves.

What is the right solution?

  [1]: https://gorm.io/docs/query.html#String-Conditions

## The document you expected this should be explained

https://gorm.io/docs/query.html#String-Conditions

## Expected answer

Probably some postgresql function should be called to escape the input variable or this should be done by GORM

**Comment by li-jin-gou** [comment]
refer to https://gorm.cn/docs/security.html
