### ISSUE TITLE
Use of a table alias does not work with soft delete

### ISSUE THREAD

**Issue by robhafner** [go-gorm/gorm#5840]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/541

## Description

Our REST API supports an expression filter parameter which is parsed and turned into generated sql code using table aliases. This works fine as long as the model doesn't support soft deletes. If the model supports soft delete the query fails due to the generated is null clause for the soft delete column being generated with as "[table-name]".[soft-delete-column]".

**Comment by robhafner** [comment]
Linking to PR with fix:
https://github.com/go-gorm/gorm/pull/5841

**Comment by yaofeng-wang** [comment]
Hi @robhafner, may I ask if you are still working on this issue? If not, I would like to work on it.

**Comment by robhafner** [comment]
Hi @yaofeng-wang, feel free to work on it as I have not had time lately to take another look at it. Thanks!
