### ISSUE TITLE
cannot use map[string]gorm.Stmt{} (value of type map[string]gorm.Stmt) as type map[string]*gorm.Stmt in struct literal

### ISSUE THREAD

**Issue by EduFriendChen** [go-gorm/gorm#5850]
## Your Question
![55ff592410550d1473845c22e3e6890](https://user-images.githubusercontent.com/78396698/201289095-d6a63ae1-6c7e-41f8-a3c8-0c54c382f5a2.jpg)

同一项目不同框架开发下，其中一种报以下错误！

\# gorm.io/plugin/dbresolver  ..\..\pkg\mod\gorm.io\plugin\dbresolver@v1.1.0\dbresolver.go:139:18: cannot use map[string]gorm.Stmt{} (value of type map[string]gorm.Stmt) as type map[string]*gorm.Stmt in struct literal
\# github.com/henrylee2cn/ameda
..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows)
..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)
\# github.com/glebarez/sqlite
..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:101:22: cannot convert 0 (untyped int constant) to *int
..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:102:24: cannot convert 0 (untyped int constant) to *int
..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:103:21: cannot use -1 (untyped int constant) as *int value in assignment
..\..\pkg\mod\github.com\glebarez\sqlite@v1.4.3\sqlite.go:106:39: cannot use limit.Limit (variable of type *int) as type int in argument to strconv.Itoa

非常抱歉占用贵开发团队宝贵的时间，如有冒犯希望视为不见，感谢！

**Comment by EduFriendChen** [comment]
解决

**Comment by XieWeiXie** [comment]
> 解决

如何解决的？
