### ISSUE TITLE
Print DB Connection that resolver resolves to

### ISSUE THREAD

**Issue by jasonzbao** [go-gorm/gorm#5862]
## Is it possible to print the DB connection that the resolver is using under the hood.

Reproduction steps:

I'm doing a 

```INSERT ... ON CONFLICT DO NOTHING;```

followed by a 

```SELECT ... ```

on the item that I inserted. I am getting a record not found and am guessing it is because of replication lag? However, I added:

```
tx = tx.Clauses(dbresolver.Write)
```

but am still getting the error. Therefore, to sanity check, I want to make sure the DB connection that is being hit is indeed the primary and not the replica with some sort of print statement.

## The document you expected this should be explained

https://gorm.io/docs/dbresolver.html

## Expected answer

How do I debug this issue?

**Comment by a631807682** [comment]
We can use [Connection](https://gorm.io/docs/sql_builder.html#Connection) to check whether the problem is caused by the master-slave database.
Looks like we need to support this feat https://github.com/go-gorm/dbresolver/issues/75
