### ISSUE TITLE
Struck when setting maxOpenConnection on db

### ISSUE THREAD

**Issue by golthitarun** [go-gorm/gorm#5866]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

Hi I tried setting the following db configuration 
`pgDb.SetConnMaxLifetime(time.Duration(2* time.Minute)
pgDb.SetConnMaxIdleTime(2 * time.Minute)
pgDb.SetMaxIdleConns(25)
pgDb.SetMaxOpenConns(25)  `

I was able to debug that the code is struck at this point https://cs.opensource.google/go/go/+/master:src/database/sql/sql.go;l=1323, 
Not sure what I am doing wrong here? Is that not how DB settings need to be configured?

**Comment by li-jin-gou** [comment]
refer to https://gorm.cn/docs/generic_interface.html#Connection-Pool and you should set it when init gorm db.
