### ISSUE TITLE
[新手提问]如果使用Migrator创建带有租户ID的表名的表

### ISSUE THREAD

**Issue by zhanjunjie2019** [go-gorm/gorm#5869]
我定义的模型代码是这样的：
`
type User struct {
	gorm.Model
	TenantID string `json:"tenantID" gorm:"-"`
	UserName string `json:"userName" gorm:"column:user_name;comment:用户名;size:64;"`
	Password string `json:"password" gorm:"column:password;comment:密码;size:64;"`
}

func (u User) TableName() string {
	return "users_" + u.TenantID
}
`

当我执行：
`
DB.AutoMigrate(po.User{TenantID:“123”}）
`

创建的表名却是：
“users_”

为什么TableName()方法的User结构体中TenantID为“”？

**Comment by a631807682** [comment]
> NOTE TableName doesn’t allow dynamic name, its result will be cached for future, to use dynamic name, you can use Scopes

https://gorm.io/docs/conventions.html#TableName
