### ISSUE TITLE
goland 控制台输出的sql日志问题

### ISSUE THREAD

**Issue by chenzhaonian** [go-gorm/gorm#5870]
goland 控制台输出的sql日志无法直接点击进行跳转
原打印样式（蓝色链接点击可跳转到sql源代码处）：
<img width="821" alt="微信截图_20221117170426" src="https://user-images.githubusercontent.com/58129713/202609322-73249352-45eb-461f-82b5-8276bd7ab064.png">
现打印样式（绿色链接不可点击）：
<img width="1072" alt="微信截图_20221117170445" src="https://user-images.githubusercontent.com/58129713/202609359-739f0254-60a4-4c3f-b336-27c61bff7238.png">

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/pull/5844

**Comment by dreamlu** [comment]
this bug again in the latest version:
```
gorm.io/driver/mysql v1.5.1
gorm.io/driver/postgres v1.5.2
gorm.io/driver/sqlserver v1.5.1
gorm.io/gorm v1.25.4
```
![image](https://github.com/go-gorm/gorm/assets/21306894/d142e193-1da4-48d9-9506-fdba5c0b3ad7)
