### ISSUE TITLE
How to desensitize mail, mobile, and name data 【如何让mail、mobile、name数据脱敏】

### ISSUE THREAD

**Issue by HalcyonDaysssss** [go-gorm/gorm#5877]
**Is it possible to add a certain parameter in the struct so that the data can be encrypted and obtained, for example, the mobile phone number, 13588888888, becomes 135****8888？**

> **是否可以在struct里面加上某个参数使得数据能够加密获取，例如手机号码，13588888888，变成135****8888？**

**Comment by a631807682** [comment]
https://gorm.io/docs/serializer.html#Customized-Serializer-Type
