### ISSUE TITLE
create batch returning

### ISSUE THREAD

**Issue by wunengbiao** [go-gorm/gorm#5881]
`
err := tx.Clauses(
		clause.Returning{Columns: []clause.Column{{Name: "user_group_id"}}},
		clause.OnConflict{
			Columns:   []clause.Column{{Name: "device_group_id"}, {Name: "user_group_id"}},
			DoNothing: true},
	).CreateInBatches(items, 10).Error
`

sql generated by this segment code is correct, how can I get the returning result?

**Comment by li-jin-gou** [comment]
Returning will assign the field back to the structure.  refer to https://gorm.io/zh_CN/docs/update.html#%E8%BF%94%E5%9B%9E%E4%BF%AE%E6%94%B9%E8%A1%8C%E7%9A%84%E6%95%B0%E6%8D%AE
