### ISSUE TITLE
Gorm docs search cannot search through code snippets

### ISSUE THREAD

**Issue by 1Mark** [go-gorm/gorm#5890]
Gorm docs search cannot search through code snippets.

E.g search for `db.exec` no luck  but it's present on this page https://gorm.io/docs/sql_builder.html

**Comment by li-jin-gou** [comment]
![image](https://user-images.githubusercontent.com/97824201/206753323-4e653c34-dfce-4819-bb4f-90120a3fdb85.png)
not support search code block
