### ISSUE TITLE
Update Joins support

### ISSUE THREAD

**Issue by loeffel-io** [go-gorm/gorm#5891]
MySQL
Joins are not supported while Updating - Join statement is missing

```
	return campaign, tx.
		Debug().
		Model(campaign).
		Joins("LEFT JOIN portfolios ON portfolios.id = campaigns.portfolio_id").
		Where("portfolios.authentication_id = ?", parentId.String()).
		Updates(updateIndex).
		Error`
```

```
UPDATE `campaigns` SET `acos_goal`=50,`updated_at`='2022-11-28 11:54:31.697' WHERE portfolios.authentication_id = 'afe86891-86f6-4710-b9b0-c50792af8a44' AND `id` = 'aa65a014-9470-4be3-9bf7-83720c147417'
```

**Comment by loeffel-io** [comment]
any information here @jinzhu? 🙏

**Comment by Nomango** [comment]
Same issue

**Comment by loeffel-io** [comment]
bump <3

**Comment by mariano-willdom** [comment]
a little workaround specifying join conditions, 'set' and 'where' in a raw query and repeating them on the update sentence

`q := "update table1 t1 "
q += "left join table2 t2 on t2.field_a = t1.field_b "
q += "set t1.field_x = ? "
q += "where t2.field_y = ? "

db.Raw(q, foo, bar).Where("t2.field_y = ?", bar).Updates(map[string]interface{}{"t1.field_x": foo})`

**Comment by nybblex** [comment]
a little workaround specifying join conditions, 'set' and 'where' in a raw query and repeating them on the update sentence

```
q := "update table1 t1 "
q += "left join table2 t2 on t2.field_a = t1.field_b "
q += "set t1.field_x = ? "
q += "where t2.field_y = ? "

db.Raw(q, foo, bar).Where("t2.field_y = ?", bar).Updates(map[string]interface{}{"t1.field_x": foo})
```

**Comment by dhalturin** [comment]
https://github.com/go-gorm/gorm/issues/4248#issuecomment-1986139639

**Comment by loeffel-io** [comment]
> [#4248 (comment)](https://github.com/go-gorm/gorm/issues/4248#issuecomment-1986139639)

this do not look like a clean solution imo @jinzhu

**Comment by mtsoltan** [comment]
I'd like for this to be re-opened.

**Comment by In-July** [comment]
Have a solution？

**Comment by Alex41** [comment]
bump <3

**Comment by amanangira** [comment]
Bump  :')
