### ISSUE TITLE
建议加入乐观锁功能

### ISSUE THREAD

**Issue by it512** [go-gorm/gorm#5892]
乐观锁是一个有用且常用的功能  ， 建议GORM 加入此功能

建议将 https://github.com/go-gorm/optimisticlock 整合。

另外：也建议 在软删除上增加 使用 0，1 表示是否删除（整合 https://github.com/go-gorm/soft_delete 的 gorm:"softDelete:flag"功能 ）
谢谢！

**Comment by icpd** [comment]
现在这样子有什么不好吗

**Comment by li-jin-gou** [comment]
already implemented in the extension library.
