### ISSUE TITLE
Hello,Query list report: "reflect: call of reflect.Value.Elem on zero Value;"，The code view is as follows

### ISSUE THREAD

**Issue by pangxianfei** [go-gorm/gorm#5894]
1.This is the model
![图片](https://user-images.githubusercontent.com/9346931/204615279-b148a0cf-2075-40d0-bac3-bdffe5437d55.png)

2.Data table recording
![图片](https://user-images.githubusercontent.com/9346931/204615648-3c3770f9-eb7a-485f-93b5-babec9348dbc.png)

3.Query List
![图片](https://user-images.githubusercontent.com/9346931/204615815-78337844-bbf7-4119-9501-5f1acb6490f3.png)

4.Get a list of result sets
![图片](https://user-images.githubusercontent.com/9346931/204616385-73fed0c1-26ab-4088-8084-e6d2e9505810.png)

5.warning
![图片](https://user-images.githubusercontent.com/9346931/204616514-8215a202-51f9-4edf-b85f-1cc40f63f138.png)

Under the condition of not taking up working time, I hope the author can analyze the cause when he is free. Thank you

**Comment by li-jin-gou** [comment]
same to https://stackoverflow.com/questions/72728791/panic-reflect-call-of-reflect-value-interface-on-zero-value-on-gorm-create
