### ISSUE TITLE
SET Variables for the Session

### ISSUE THREAD

**Issue by erikkvale** [go-gorm/gorm#5896]
## Your Question

I am trying to determine how best to set a variable for AWS Aurora (MySQL) when configuring GORM that would be valid for the entire session, basically running this ```SET aurora_replica_read_consistency="SESSION"```. Looked at plugins, but that seems to run for every query or I am not understanding them correctly. Is there a way to initialize and SET a variable like this for the duration of the session?

## The document you expected this should be explained

https://gorm.io/docs/session.html

## Expected answer

Advice on how to do this in GORM or direction on pursuing it at the driver level.

**Comment by li-jin-gou** [comment]
use DB.Connection and it  ensures that all your database operations are performed using the same connection.
go uses connection pooling to manage connections at the bottom.

**Comment by erikkvale** [comment]
Ok, can you please provide a code example of running a SET using DB.Connection as you describe? Or the relevant link in the documentation? It's not clear from your documentation or code that this is supported.
