### ISSUE TITLE
gorm/gen默认生成的结构体gorm tag增加comment

### ISSUE THREAD

**Issue by zhangdaogui** [go-gorm/gorm#5897]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

默认生成的结构体，注释在字段的后面，以//字段名，这样的话，我们使用autoMigrate生成的数据表，就不会有comment,反向再生成的时候，就会丢失comment

建议在tbl_column文件的buildGormTag方法中，加一个
````go
if c, ok := c.Comment(); ok {
    if c != "" {
	buf.WriteString(fmt.Sprintf(";comment:%s", c))
    }
}
````

**Comment by li-jin-gou** [comment]
you can make a pull request in https://github.com/go-gorm/gen
