### ISSUE TITLE
Association doesn't replace the entities with new ones and throw an error.

### ISSUE THREAD

**Issue by MuhmdHsn313** [go-gorm/gorm#5899]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/548

## Description

I have two tables Item and ItemContent:
```golang
type Item struct {
	gorm.Model
	Logo        string                `json:"logo" gorm:"not null;type:varchar(50)"`
	Contents    []ItemContent       `json:"contents" gorm:"foreignKey:ItemID"`
}

type ItemContent struct {
	gorm.Model
	ItemID   uint     `json:"item_id" gorm:"not null"`
	Name       string   `json:"name" gorm:"not null;type:varchar(50)"`
	LanguageCode string   `json:"language_code" gorm:"not null;type:varchar(2)"`
}
```
I tried to insert a new Item and ItemContent into the SQLite database: 
```golang
item := model.Item{
		Logo: "logo",
		Contents: []model.ItemContent{
			{
				LanguageCode: "en",
				Name:       "name",
			},
			{
				LanguageCode: "ar",
				Name:       "الاسم",
			},
		},
	}
db.Create(&item)
```

after creating a new Item I needed to replace the contents with new contents using `Association` in gorm, I wrote this code for replacing by calling` Association.Replace` method. It should remove the previous contents and set these new contents:

```golang
db.Model(&item).Association("Contents").Replace([]model.ItemContent{
		{
			LanguageCode: "en",
			Name:       "updated name",
		},
		{
			LanguageCode : "ar",
			Name:       "الاسم المحدث",
		},
		{
			LanguageCode : "fr",
			Name:       "le nom",
		},
	})
```

but there is an error occurred when I call the `Association.Replace` code:
```
sqlite3.Error{
    code: 19,
    extendedCode: 1299,
    systemErrno: golang.org/x/sys/windows.ERROR_SUCCESS (0),
    err: NOT NULL constraint failed: vendor_contents.vendor_id
}
```

after that I opened the sqlite3 database and I find a new 3 rows has been added into `item_contents` table without removing the previous 2 rows, so there is 5 rows in the table. I expected that the `Association.Replace` removed the existing 2 rows and add the new 3 rows.

**Comment by MuhmdHsn313** [comment]
I added the playground examples and test.

**Comment by MuhmdHsn313** [comment]
@jinzhu any update?

**Comment by black-06** [comment]
Replace will set old associations's foreign key to null, but you set `not null` at [ItemContent.ItemID](https://github.com/go-gorm/playground/pull/548/files#diff-72487d6e423e37c0af7994baddca95c1e2acc7e7ca51b8d13d03caa8e4485a16R15).

And Gorm recorded an error on your [playground](https://github.com/go-gorm/playground/pull/548/checks#step:5:50)

Remove `grom:"not null"` to fix it :)

**Comment by black-06** [comment]
Keep checking errors in your code, such as [here](https://github.com/go-gorm/playground/pull/548/files#diff-79ce3229c13921b79b1175dcb211336aaf84dfd8edcf19c07698934d4fe70e5eR27)

```go
err = DB.Model(&item).Association("Contents").Replace(...)
assert.Nil(t, err)
```

**Comment by MuhmdHsn313** [comment]
I think the best approach is to delete the old associations and add new ones. Also, I try to use `Association("Contents").Delete(...)
` but nothing happened.

**Comment by black-06** [comment]
Maybe we can perform different deletions on Association, just like `Unscoped`?  @jinzhu

**Comment by MuhmdHsn313** [comment]
any updates? @black-06 @jinzhu

**Comment by black-06** [comment]
> any updates? @black-06 @jinzhu

Nothing, we need @jinzhu or @a631807682 's advice to avoid ineffective work

**Comment by a631807682** [comment]
I think it is a very good suggestion to add a similar API to the `Association` to allow users to choose to `delete records` or `set foreign key to null`. In fact, we have many similar issues.

**Comment by a631807682** [comment]
@WinXaito Please create another issue in gorm/gen
