### ISSUE TITLE
bug ??

### ISSUE THREAD

**Issue by letian-tang** [go-gorm/gorm#5925]
## GORM Playground Link

module gorm-test

go 1.19

require (
	github.com/go-sql-driver/mysql v1.7.0 // indirect
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/jinzhu/now v1.1.5 // indirect
	gorm.io/driver/mysql v1.4.4 // indirect
	gorm.io/gorm v1.24.2 // indirect
)

## Description

![image](https://user-images.githubusercontent.com/9101213/208040765-ee2521ff-8291-481b-bd37-e2a5020d4ccd.png)

**In Mysql id =3, id=5 "submit_at" is null , But the query shows that there is a value and it is the previous one**

![image](https://user-images.githubusercontent.com/9101213/208042195-7b477526-957f-4623-ac50-ef8258a367e3.png)

**Comment by yyoshiki41** [comment]
It is probably that embedded value bugs.
This bugs was fixed by below.

https://github.com/go-gorm/gorm/pull/5901
