### ISSUE TITLE
i want ask can clear where condition. this like session NewDb

### ISSUE THREAD

**Issue by Gpihuier** [go-gorm/gorm#5926]
### I have a piece of code, looking that this like 
```go

fieldDb := db.Model(&MyModel{}).Select("first_field, second_field, ...")

for _, id := range ids {
    var data Date
    err := fieldDb.Where("id = ?", id).First(&data)
    if err != nil {
        return
    }
    ......
}

```

**Comment by 0x2d3c** [comment]
I don't know why your code was written like that

i think this way will be better
```go
var res []Data
if err := db.Model(&MyModel{}).Select("first_field, second_field, ...").Where("id IN (?)",ids).Find(&res).Err(); err!=nil {
  return err
}
```

**Comment by Gpihuier** [comment]
This is just pseudo code. I just want to know whether there is a function of clearing conditions separately, or whether there is a support plan in the future

**Comment by 0x2d3c** [comment]
i don't know if there is a way for you, but DB struct has Statement field,
you need self definition impl feature

Gpihuier ***@***.***> 于2022年12月19日周一 14:23写道：

**Comment by Gpihuier** [comment]
thank you. I'm ready to close issues

**Comment by Gpihuier** [comment]
I tried to write some code, although I know it is not strict
but it fulfilled my original requirements
The code looks like this

```go
package db

import (
    "gorm.io/gorm"
    "gorm.io/gorm/clause"
)

db.Statement.RemoveClause(clause.Where{}, clause.OrderBy{})

// write in gorm.statement.go
// RemoveClause remove clause
func (stmt *Statement) RemoveClause(clauses ...clause.Interface) {
	for _, v := range clauses {
		name := v.Name()
		stmt.Clauses[name] = clause.Clause{}
	}
}

```

**Comment by a631807682** [comment]
https://gorm.io/docs/method_chaining.html#New-Session-Method
