### ISSUE TITLE
gorm 添加外键和引用 就不能 自动迁移（迁移就报错）

### ISSUE THREAD

**Issue by dbsgw** [go-gorm/gorm#5939]
![K8F EPDY)((AXTNY$RW7IHR](https://user-images.githubusercontent.com/69408664/209418874-c2ede3f5-28c1-4575-8d53-d88b7a661408.png)

报错如下：
 define a valid foreign key for relations or implement the Valuer/Scanner interface

**Comment by dbsgw** [comment]
？？？？？

**Comment by dbsgw** [comment]
https://github.com/go-gorm/playground  这库 以看 ，只看到重写 外键， 没看到 外键 引用一起的场景

**Comment by Nomango** [comment]
报错信息写的挺明确的，foreignKey写的有问题，也有可能因为User没有用指针
