### ISSUE TITLE
clause.OnConflict Columns 是不是加不加、联合唯一键加不加测试都一样

### ISSUE THREAD

**Issue by zhongsdjn** [go-gorm/gorm#5955]

**Comment by zhongsdjn** [comment]
err = db.Debug().Clauses(
    clause.OnConflict{
	    Columns:   []clause.Column{{Name: "author"}, {Name: "title"}},  // 加不加 or Name: "id" 测试都一样
	    DoUpdates: clause.AssignmentColumns([]string{"sale_num", "updated_at"}),
}).Create(&a).Error

**Comment by jinzhu** [comment]
`Columns` doesn't work with mysql driver, it will use all unique indexes by default.
