### ISSUE TITLE
JSON serializer doesn't work in last version (json: unsupported value: encountered a cycle via *schema.Schema)

### ISSUE THREAD

**Issue by LaGregance** [go-gorm/gorm#5960]
## GORM Playground Link

Sorry I didn't use the official playground since there is no model that use the json serializer. You can still find a repo to reproduce here: https://github.com/LaGregance/gorm-save-bug

## Description

After upgrading GORM to last version (v1.24.3), I cannot save my model anymore if there include a json field that use the json serializer.
I get the following error when saving:
```
failed to encode args[1]: unable to encode &schema.serializer{Field:(*schema.Field)(0xc0002b65a0), Serializer:schema.SerializerInterface(nil), SerializeValuer:schema.JSONSerializer{}, Destination:reflect.Value{typ:(*reflect.rtype)(0x1584920), ptr:(unsafe.Pointer)(0xc000245470), flag:0x199}, Context:(*context.emptyCtx)(0xc00009c000), value:interface {}(nil), fieldValue:(*database.UserMetadata)(0xc00027acf0)} into text format for jsonb (OID 3802): json: unsupported value: encountered a cycle via *schema.Schema
```

Not that the json field is of type UserMetadata like that : 
```go
type UserMetadata struct {
	Hello string
	World uint
	Big   *big.Int
}
```
So I add a big.Int because it's my case in production, but I got the same error if I remove this field and only keep the string & uint ones.
I use postgresql 13.7

Thanks.

**Comment by bastengao** [comment]
I have the same issue on 1.24.3, and i got error 

```
failed to encode args[9]: unable to encode &schema.serializer{Field:(*schema.Field)(0x1400089e000), Serializer:schema.SerializerInterface(nil), SerializeValuer:schema.JSONSerializer{}, Destination:reflect.Value{typ:(*reflect.rtype)(0x1066b8020), ptr:(unsafe.Pointer)(0x1400093cdd0), flag:0x199}, Context:(*context.emptyCtx)(0x14000058190), value:interface {}(nil), fieldValue:map[string]interface {}(nil)} into text format for json (OID 114): json: unsupported value: encountered a cycle via *schema.Schema
```

```go
type Activity struct {
	ID            int64
        // 10th column
	Parameters    map[string]any `gorm:"serializer:json"`
}
```

**Comment by wdmcode** [comment]
I also encountered the same problem. I spent a day checking it, thinking that I used it in an incorrect way. Finally I downgraded it to 1.23.0

**Comment by a631807682** [comment]
This is caused by upgrading from pgx@v4.x.x to pgx@v5.x.x.
We will fix or give feedback to pgx later.
I don't have enough time to solve it at the moment, I will mark the cause of the problem for the time being, and we will fix it or give feedback to pgx later.
We would be happy if someone would like to create a PR for this or follow it up in pgx.

https://github.com/jackc/pgx/blob/e66ad1bcecedaa3032a16f0f71b1878502f9cb8b/extended_query_builder.go#L76
https://github.com/jackc/pgx/blob/e66ad1bcecedaa3032a16f0f71b1878502f9cb8b/extended_query_builder.go#L126

**Comment by deefdragon** [comment]
For anyone else encountering this, Downgrading to the following versions in go.mod worked for me. (tho I did have to go through and delete some indexes to get migration to work properly)

```
gorm.io/driver/postgres v1.4.5
gorm.io/gorm v1.24.4
```

**Comment by fabstu** [comment]
Had a similar issue with `time.Time`, I downgraded aswell.

**Comment by a631807682** [comment]
pgx v5.3.0 was released
> go get -u gorm.io/driver/postgres
