### ISSUE TITLE
Has many relation using two columns for foreign key

### ISSUE THREAD

**Issue by comsma** [go-gorm/gorm#5965]
## Your Question

I'm trying to link two tables together with a one to many relationship and I do not see documentation for linking two columns in the references.  Both tables have two unique columns and can't be linked on just one.

## The document you expected this should be explained

[Has Many](https://github.com/go-gorm/gorm.io/blob/master/pages/docs/has_many.md)

## Expected answer

`gorm:"foreignKey:customer_id,company_id;references:customer_id,company_id"`

**Comment by comsma** [comment]
so I tried it out the way I expected to assign my columns and get the following query from it 

``` sql
SELECT * FROM "oe_hdr" WHERE ("oe_hdr"."customer_id","oe_hdr"."company_id") IN ((100000,'MRS'))
```
It seems to generate a query alright but mssql doesn't like the fact that i'm passing two columns into the where clause.
A valid query in mssql would be 

```sql
 SELECT *
 FROM "oe_hdr"
 WHERE ("oe_hdr"."customer_id") IN (100000) AND ("oe_hdr"."company_id") IN ('MRS')
```

Is there a way I can get gorm to generate the query in that format?

**Comment by Roldification** [comment]
im having this trouble also in mssql. i hope this can be solved soon ^_^

**Comment by Roldification** [comment]
> 

Have you find solution for this?

**Comment by saeidee** [comment]
Closing this issue since there is a feature request reported here https://github.com/go-gorm/gorm/issues/6441.
