### ISSUE TITLE
Why Update Column skip hooks

### ISSUE THREAD

**Issue by folospace** [go-gorm/gorm#5978]
//origin code
func (db *DB) UpdateColumn(column string, value interface{}) (tx *DB) {
	tx = db.getInstance()
	tx.Statement.Dest = map[string]interface{}{column: value}
	tx.Statement.SkipHooks = true // ?
	return tx.callbacks.Update().Execute(tx)
}

Why not just call this method  "UpdateSkipHooks"

**Comment by a631807682** [comment]
https://gorm.io/docs/update.html#Without-Hooks-x2F-Time-Tracking
