### ISSUE TITLE
Error sql syntax RETURNING in MariaDB

### ISSUE THREAD

**Issue by init-database** [go-gorm/gorm#5980]
> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version 
> for the right syntax to use near 'RETURNING

go-gorm version 1.24.3

suddenly the error pops up after updating from 1.23.10 to 1.24.3

Why would you add RETURNING clause in MariaDB version below 10.5.0?

make this lib smart dude

**Comment by jinzhu** [comment]
upgrade MySQL driver dude
