### ISSUE TITLE
how  about   adding    the  driver  for   china's    Dameng8   database?

### ISSUE THREAD

**Issue by goodve** [go-gorm/gorm#5987]
## Describe the feature
to add    the  driver  for   china's     dameng   database

## Motivation
DM8 is a new generation of self-researched database launched by Dameng on the basis of summing up the R&D and application experience of DM series products and adhering to the concept of open innovation, simplicity and practicality. The diversified architecture fully meets the needs of different scenarios, supports ultra-large-scale concurrent transaction processing and transaction-analysis hybrid business processing, and dynamically allocates computing resources to achieve more refined resource utilization and lower cost investment. One database, to meet the multiple needs of users, so that users can focus more on business development.

https://www.dameng.com/

**Comment by a631807682** [comment]
Does it differ from the existing driver's sql syntax?

**Comment by goodve** [comment]
> Does it differ from the existing driver's sql syntax?
The syntax is 96%+ similar to Oracle sql and can be considered as a dialect of Oracle.
Meanwhile, the Chinese kingbase8 database is based on pg12 development, I tested it and I can use the pg driver to connect to kingbase8.

**Comment by goodve** [comment]
Go Programming Guide  for  Dm8

```go

import (
"database/sql"
_ "dm"
)
db, err := sql.Open("dm", "dm://SYSDBA:SYSDBA@localhost:5236?autoCommit=true")

var username string
err := db.QueryRow("select name from TEST where id=?", 10).Scan(&username)
```

**Comment by a631807682** [comment]
As you said, they are similar, we didn't find it necessary to implement it, and you are welcome to create a driver for it, we will add a link to it in https://gorm.io/community.html
