### ISSUE TITLE
Rename index creates new but not delete old

### ISSUE THREAD

**Issue by ex0hunt** [go-gorm/gorm#6022]
Hi! I found some problem with indexes in PostgreSQL. For example, you have some table

```
type USER struct {
	gorm.Model
	Name       string `json:"name" gorm:"type:varchar(64);not null"`
	Country   string `json:"country" gorm:"index:idx_country"`
}
```
and you want to change name for Country index, like a idx_country -> idx_country_name. 

```
...
	Country   string `json:"country" gorm:"index:idx_country_name"`
...
```
After AutoMigration you see DB has two indexes _idx_country_ and _idx_country_name_. Sometimes its broke app logic: if you remove uniq from code it's doesn't remove uniq from DB.

Affected versions
gorm.io/driver/postgres v1.4.6
gorm.io/gorm v1.24.3

**Comment by OscarMoya** [comment]
Hi, I found a similar issue with Automigrate and Posgres that may be related to this one. 
The problem I found was not related with renaming, but with removing the index. I tried to submit a PR in gorm-playground here: https://github.com/go-gorm/playground/pull/562

Hope it depicts the problem I face correctly and helps to solve this issue.

**Comment by OscarMoya** [comment]
@ex0hunt Would it be possible to add the PR I added (provided is OK with you) to the description so the Issue is marked as `withReproduceSteps`? 

Thank you

**Comment by a631807682** [comment]
> It WON’T delete unused columns to protect your data.

index is the same
https://gorm.io/docs/migration.html#Auto-Migration

**Comment by OscarMoya** [comment]
> > It WON’T delete unused columns to protect your data.
> 
> index is the same, you can remove it yourself using
> 
> ```
> 	// Indexes
> 	CreateIndex(dst interface{}, name string) error
> 	DropIndex(dst interface{}, name string) error
> 	HasIndex(dst interface{}, name string) bool
> 	RenameIndex(dst interface{}, oldName, newName string) error
> 	GetIndexes(dst interface{}) ([]Index, error)
> ```
> 
> https://gorm.io/docs/migration.html#Auto-Migration

The bug here reported, is that AutoMigrate does not drop the indexes automatically. if removed, should this supported? or is to be done Manually?
