### ISSUE TITLE
type标签无法指定time类型？

### ISSUE THREAD

**Issue by congjunhua** [go-gorm/gorm#6033]
通过`type`标签指定`At`为`Time`类型：
```go
type Test struct {
	At string `gorm:"type:time"`
}
```
但`AutoMigrate`时却使用了`datetime`类型：
```sh
[3.979ms] [rows:0] CREATE TABLE `tests` (`at` datetime(3) NULL)
```

**Comment by congjunhua** [comment]
临时解决方案：

```go
db.AutoMigrate(&model. Test{})

db.Exec("alter table expresses modify collect_at time null")
```

望修复。

**Comment by a631807682** [comment]
https://github.com/go-gorm/datatypes#time

**Comment by congjunhua** [comment]
> 

为了这个小问题再引入一个自定义类型的包我感觉是不合适的，因为本质上标签无法指定`time`类型这个问题并没有解决。

同时，`date`没问题，`time`却有问题，为什么不一致？

我认为应该从造成这种不一致的原因的地方去尝试解决。

```go
type Test struct {
    Date time.Time `gorm:"type:date;not null"`
    Time time.Time `gorm:"type:time;not null"`
}
```

```sh
CREATE TABLE `hellos` (`date` date NOT NULL,`time` datetime(3) NOT NULL)
```

**Comment by a631807682** [comment]
Bug due to no distinction between gorm type `time.Time` and tag `type:time`
https://github.com/go-gorm/mysql/blob/master/mysql.go#L356

**Comment by black-06** [comment]
These jobs are all the same :( 

Or do we change `schema.Time` from "time" to "go_time"?
The downside is that the old version of the drivers cannot work with the modified gorm
