### ISSUE TITLE
Document batch delete by providing slice of structs

### ISSUE THREAD

**Issue by jpmeijers** [go-gorm/gorm#6035]
## Describe the feature

When doing a db.Delete and passing a slice of structs, GORM will do a batch delete of all elements in the slice. This is not clearly documented. Let's add this to the documentation for clarity.

See: https://stackoverflow.com/q/75362946/5343140

## Motivation

The documentation is not clear on this.

**Comment by a631807682** [comment]
Welcome to create a PR for it.
https://github.com/go-gorm/gorm.io

**Comment by dogenkigen** [comment]
Seems like the documentation is clear about it now: https://gorm.io/docs/delete.html#Batch-Delete
