### ISSUE TITLE
Automigrate with uniqueIndex error on 1.24.5

### ISSUE THREAD

**Issue by ekawas-td** [go-gorm/gorm#6039]
DB: Postgresql

## Description

Looks like gorm 1.24.5 has an issue if you create a model with uniqueIndex attribute. Looks like previous versions of gorm did a "create unique index xxx" previously and now are using table constraints (e.g. "alter table add constraint ..." and these 2 things butt heads. Deleting the index and letting gorm recreate works as a workaround but isn't ideal.

## Model example

```
type Teacher struct {
	ID      string   `gorm:"primaryKey;type:varchar(25)"`
	Subject string   `gorm:"uniqueIndex"`
}
```

Using auto migrate on the above model with a version of Gorm less than 1.24.3 will throw an error after upgrading to v1.24.5

```
relation \"idx_teacher_subject\" already exists (SQLSTATE 42P07)
```

**Comment by axiangcoding** [comment]
I already created a related issue here: https://github.com/go-gorm/gorm/issues/6026

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/6026

**Comment by athoscouto** [comment]
https://github.com/go-gorm/gorm/issues/6026 refers specifically to `postgres`. 
The fix looks like it is specific to `postgres`. 
Is it?

I'm also facing this problem with `sqlite`.


https://github.com/go-gorm/gorm/issues/6026#issuecomment-1421532811 seems to point the root cause.

**Comment by axiangcoding** [comment]
> #6026 refers specifically to `postgres`. The fix looks like it is specific to `postgres`. Is it?
> 
> I'm also facing this problem with `sqlite`.

It is specific to postgres.
I can't reproduce sqlite error in https://github.com/go-gorm/playground/pull/561, maybe you can provide a PR to https://github.com/go-gorm/playground?

**Comment by golfapipol** [comment]
same issue
