### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by ryuan1990** [go-gorm/gorm#6040]
go: gorm.io/gorm@v1.24.5: verifying module: gorm.io/gorm@v1.24.5: checking tree#15345421 against tree#15425001: reading https://goproxy.io/sumdb/sum.golang.org/tile/8/1/234: 404 Not Found

**Comment by Ltd5552** [comment]
在项目中使用导入`go get -u gorm.io/gorm`，出现问题
 ```
go: downloading gorm.io/gorm v1.24.5
go: gorm.io/gorm@v1.24.5: verifying module: gorm.io/gorm@v1.24.5: checking tree#15383238 against tree#15425001: reading https://goproxy.io/sumdb/sum.golang.org/tile/8/1/234: 404 Not Fo
und
        server response: not found
```
@jinzhu

**Comment by shtrih** [comment]
https://github.com/go-gorm/gorm/issues/6040
