### ISSUE TITLE
How much data a Scan() call can return

### ISSUE THREAD

**Issue by nbajaj90** [go-gorm/gorm#6062]
## Your Question
Wanted to check how much data a single Scan() call could return.
Assuming there are 0.1 million matching rows in DB, all rows would be returned or there is some default limit (number of rows returned or on size of data returned)? Or will return any error?

## Expected answer
A Scan() call would return, for example max 10k rows or 10MB data out of 0.1 million rows, etc.

**Comment by a631807682** [comment]
gorm has no restrictions on this.
