### ISSUE TITLE
Modification of string fields to LONGTEXT without a length..

### ISSUE THREAD

**Issue by AAlvarez90** [go-gorm/gorm#6064]
## GORM Playground Link
https://go.dev/play/p/qkJo3hCfVBN
The link above is created to appease the bot.

https://github.com/go-gorm/playground/pull/1

## Description
After updating to the latest GORM yesterday, I am having this error on my email field which looks like this:
```
type User struct {
	ApplicationModel
	Email               string         `gorm:"not null;uniqueIndex,length:200" json:"email" validate:"required,email"`
         .... other fields ....
}
```
This field should be a varchar(200).

Here is the error message:
**panic: Error 1170: BLOB/TEXT column 'email' used in key specification without a key length [recovered]
	panic: Error 1170: BLOB/TEXT column 'email' used in key specification without a key length**

I can also that these two fields have different data types in the Database even though they have been defined identically except for the semi colon between `not null and size`
```
	FirstName           string         `gorm:"not null;size:30" json:"firstName" validate:"required,lt=30"`
	LastName            string         `gorm:"not null,size:30" json:"lastName" validate:"required,lt=30"`
```
First Name is a varchar with length 30 and Lastname is a long text.

**Comment by a631807682** [comment]
> This field should be a varchar(200).

```diff
type User struct {
	ApplicationModel
-	Email               string         `gorm:"not null;uniqueIndex,length:200" json:"email" validate:"required,email"`
+	Email               string         `gorm:"not null;uniqueIndex;size:200" json:"email" validate:"required,email"`
         .... other fields ....
}
```
> First Name is a varchar with length 30 and Lastname is a long text.
```diff
	FirstName           string         `gorm:"not null;size:30" json:"firstName" validate:"required,lt=30"`
-	LastName            string         `gorm:"not null,size:30" json:"lastName" validate:"required,lt=30"`
+	LastName            string         `gorm:"not null;size:30" json:"lastName" validate:"required,lt=30"`
```
