### ISSUE TITLE
Gorm MSSQL conditional unique index not working

### ISSUE THREAD

**Issue by jozephp** [go-gorm/gorm#6070]
##Description 
As per the documentation on https://gorm.io/docs/indexes.html#Index-Tag gorm supports conditional indexing using a where condition. But it seems to be not respected in MSSQL / TSQL 

##Steps to reproduce 
https://github.com/go-gorm/playground/pull/570
```
type User struct {
    ID string `gorm:"primaryKey"`
    IssuerID string `gorm:"index:unique_issuer,class:UNIQUE,where: issuer_id IS NOT NULL"`
}
```
the above code results in the following error when creating the columns using the code 
```
mssql: The CREATE UNIQUE INDEX statement terminated because a duplicate key was found for the object name 'dbo.abc' and the index name 'unique_issuer'. The duplicate key value is (<NULL>).
[5.309ms] [rows:0] CREATE UNIQUE INDEX "unique_issuer" ON "abc"("issuer_id")
time="2023-02-17T15:19:23+05:30" level=fatal msg="an error 'mssql: The CREATE UNIQUE INDEX statement terminated because a duplicate key was found for the object name 'dbo.abc' and the index name 'unique_issuer'. The duplicate key value is (<NULL>).' was not expected when opening a database connection"
exit status 1
```

on MSSQL / TSQL the following code works seamlessly CREATE UNIQUE INDEX unique_issuers ON abc(issuer_id) where issuer_id IS NOT NULL

this means the gorm is unable to translate the go struct format to the native sql commands

**Comment by black-06** [comment]
This problem is not due to grom.
Because [UNIQUE Constraints](https://learn.microsoft.com/en-us/sql/relational-databases/tables/unique-constraints-and-check-constraints?view=sql-server-ver16#Unique) in MS SQL Server.

**Comment by black-06** [comment]
> Unlike PRIMARY KEY constraints, UNIQUE constraints allow for the value NULL. However, as with any value participating in a UNIQUE constraint, only one null value is allowed per column.

So `where: issuer_id IS NOT NULL` is invalid actually.

**Comment by jozephp** [comment]
MSSQL / TSQL supports conditional unique indexes as documented [here](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver16#syntax-for-sql-server-azure-sql-database-azure-sql-managed-instance ) & [here](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver16#where-filter_predicate) 
It does accepts WHERE for UNIQUE INDEX

**Comment by black-06** [comment]
I'm sorry, I'm not familiar with mssql. 
I'll try it later, and try to fix it if possible.

**Comment by black-06** [comment]
Yes you are right, `where` is unimplemented.
At present, you can replace it with `option`.
```go
type User struct {
    ID string `gorm:"primaryKey"`
    IssuerID string `gorm:"index:unique_issuer,class:UNIQUE, option: where issuer_id IS NOT NULL"`
}
```
```sql
CREATE UNIQUE INDEX "unique_issuer" ON "users"("issuer_id") where issuer_id IS NOT NULL
```

**Comment by jozephp** [comment]
Thanks @black-06 for suggesting the fix and also raising the PR to fix the where condition

**Comment by black-06** [comment]
It's my pleasure

**Comment by pradnyoday** [comment]
Hi @black-06 , 
We are encountering same issue as this.
We have raised https://github.com/go-gorm/gorm/issues/6597 this issue.
Can you please look into it?
