### ISSUE TITLE
Preload nested with reference to parent

### ISSUE THREAD

**Issue by uded** [go-gorm/gorm#6078]
I would like to use preload with reference to the parent, but it seems impossible. 

So I got something like this, nothing fancy. I know only `UserID` (param `id`) on the function entry:

```query = query.Joins("ActiveOrganization").
    Preload("ActiveOrganization.OrganizationUsers", "user_id = ?", id).
    Preload("ActiveOrganization.Data").
```

And this works fine. Except, I strongly believe that I cannot filter on the level of `ActiveOrganization.Data` referring back to the `ActiveOrganization`. `Data`, which I should add, is a many-to-many relationship. And, as far as I can see, the query to fetch it is simple to select with params `IN ?` listing all keys from the parent.

Am I correct to assume that there is no way to propagate/use as a condition `ActiveOrganization.ID` down to `.Preload("ActiveOrganization.Data")` so I can do some custom filtering there?

**Comment by a631807682** [comment]
> Am I correct to assume that there is no way to propagate/use as a condition ActiveOrganization.ID down to .Preload("ActiveOrganization.Data") so I can do some custom filtering there?

https://github.com/go-gorm/gorm/blob/master/tests/preload_suits_test.go#L1062
