### ISSUE TITLE
How increment column version on each modify model via hook?

### ISSUE THREAD

**Issue by alexpts** [go-gorm/gorm#6079]
Hi, I have model and `BeforeSave` hook

```
func (m *User) BeforeUpdate(tx *gorm.DB) (err error) {
	tx = tx.UpdateColumn("_ver", gorm.Expr("_ver + ?", 1))
	return tx.Error
}
```

And save method in repository

```
func (repo *Repo) Save(model *User) (*User, int64, error) {
	gormDb = repo.Db // *gorm.DB
        tx := gormDb.Debug().Save(model)
	return model, tx.RowsAffected, tx.Error
}
```

I want save/update/persist model and apply increment for column `_ver` (version) on each modify.

Hook not overlap value from model now.

Expected SQL is ` UPDATE "users" SET "up_at"='2023-02-19 13:54:01.912',"_ver"=ver + 1,"name"='alex4' WHERE "id" = 2`

Actual SQL is ` UPDATE "users" SET "up_at"='2023-02-19 13:54:01.912',"_ver"=23,"name"='alex4' WHERE "id" = 2`

**Comment by a631807682** [comment]
https://github.com/go-gorm/optimisticlock

**Comment by alexpts** [comment]
@a631807682 I don`t undestand how optimisticklock help me in my case. I need generate sql expression via gorm hooks.
[optimisticlock](https://github.com/go-gorm/optimisticlock) has not example with hook. Expression sql on Update work correct in native gorm.

**Comment by alexpts** [comment]
Please, repopen issue

**Comment by a631807682** [comment]
```go
tx.Statement.SetColumn("_ver", clause.Expr{SQL: tx.Statement.Quote("_ver") + "+1"}, true)
```
https://github.com/go-gorm/optimisticlock/blob/master/version.go#L160

**Comment by alexpts** [comment]
@a631807682 this example not work for my case.

Debug sql log:
UPDATE "users" SET "up_at"='2023-02-23 23:40:38.722', "_ver"=**0**, "name"='bob' WHERE "id" = 2

See full code from my first post.
I assume that their hook changes are ignored and data for SET is taken from the `.Save(model)`.

**Comment by a631807682** [comment]
In fact, the setting of `BeforeUpdate` will be overwritten when `Update` later, because `Save` will save all values, including zero values. We can only build the complete clause through hacks.
Why do you need to refer to `optimisticlock.Version`, because it contains custom data types and custom Clauses implementations.
https://gorm.io/docs/serializer.html#content-inner
https://gorm.io/docs/sql_builder.html#StatementModifier

```go
func (m * User) BeforeUpdate(tx *gorm.DB) (err error) {
	dbname := "_ver"

	stmt := tx.Statement
	dv := reflect.ValueOf(stmt.Dest)
	if reflect.Indirect(dv).Kind() == reflect.Struct {
		selectColumns, restricted := stmt.SelectAndOmitColumns(false, true)

		sd, _ := schema.Parse(stmt.Dest, &sync.Map{}, stmt.DB.NamingStrategy)
		d := make(map[string]interface{})
		for _, field := range sd.Fields {

			if field.DBName == dbname || field.DBName == stmt.Schema.PrioritizedPrimaryField.DBName {
				continue
			}

			if v, ok := selectColumns[field.DBName]; (ok && v) || (!ok && (!restricted || !stmt.SkipHooks)) {
				if field.AutoUpdateTime > 0 {
					continue
				}

				val, isZero := field.ValueOf(stmt.Context, dv)
				if (ok || !isZero) && field.Updatable {
					d[field.DBName] = val
				}
			}
		}

		stmt.Dest = d
	}

	stmt.SetColumn(dbname, clause.Expr{SQL: stmt.Quote(dbname) + "+1"}, true)
	return tx.Error
}
```

**Comment by alexpts** [comment]
Thanks!
