### ISSUE TITLE
Does gorm support pgxpool?

### ISSUE THREAD

**Issue by syed-shah-zepto** [go-gorm/gorm#6091]
The default driver used by gorm for Postgres is pgx as per this doc: https://gorm.io/docs/connecting_to_the_database.html

Is it possible to use pgxpool instead of this?

**Comment by a631807682** [comment]
No such plan, gorm conn pool is based on `sql.DB`

**Comment by pitabwire** [comment]
@syed-shah-zepto actually you can do it like this https://github.com/pitabwire/frame/blob/v1.63.1/datastore/pool/connection.go#L46-L91
