### ISSUE TITLE
.Pluck() to log correct number of rows returned

### ISSUE THREAD

**Issue by vrangasam** [go-gorm/gorm#6103]
## Describe the feature

.Pluck()  should return correct number of rows returned from DB

## Motivation

In the debug logs of query execution, .Pluck() is always printing [0 rows affected or returned ] even though there are matching records. But the records are returned correctly.

for e.g.,
```
scopedQuery.Pluck("profiles.id", &profileIDs)
``` 
will always print `[0 rows affected or returned ]` even if there are 100 profiles matching the scope and are returned correctly.

This causes confusion atleast during debugging phase.

## Related Issues

N/A

**Comment by a631807682** [comment]
`[0 rows affected or returned ]`
gorm doesn't print such logs, check your own logging implementation, and this is not a feature request.
