### ISSUE TITLE
many2many 指定大写的表名无效，关联查询时候自动转换为带下划线的表名

### ISSUE THREAD

**Issue by ophioglossum** [go-gorm/gorm#6106]
![image](https://user-images.githubusercontent.com/61675623/221749324-f5bf98e3-a3e4-4a5a-97cb-19b43ab8ea57.png)
![image](https://user-images.githubusercontent.com/61675623/221749344-03c23c8f-7407-4773-8249-38ba84ca584d.png)
而我实际生成环境的数据库已有的表名是residentOrgs

**Comment by black-06** [comment]
see [GORM Config #NamingStrategy](https://gorm.io/docs/gorm_config.html#NamingStrategy).
You can use `NoLowerCase: true` to skip the snake_casing of names
