### ISSUE TITLE
A bug about updates and select

### ISSUE THREAD

**Issue by wojiukankan** [go-gorm/gorm#6130]
I have a struct
 ``` 
type User struct { 
    Name string
    Sex bool
    Age int
}
```

if i want to query name and age，`db.Select("name,age").Find(&users)`，I can combine the name and age into a string and pass it into 'select'，and I can get the correct result。

but when i want to update name and age，`db.Select("name,age").Updates(&users)`，He will treat "name,age" as one  field。This won't match the fields in my struct

**Comment by a631807682** [comment]
gorm does not parse sql in select, and only uses the original string , and select is not an update syntax, it just determines the string to be updated through logic, so it will not support it.
