### ISSUE TITLE
Feature: Support GORM elasticsearch driver?

### ISSUE THREAD

**Issue by daidai21** [go-gorm/gorm#6140]
## Describe the feature
Support GORM [elasticsearch](github/go-gorm/elasticsearch) driver?

like:
* https://github.com/go-gorm/clickhouse
* https://github.com/go-gorm/sqlite

## Motivation

CRUD on ES.

## Related Issues

None

**Comment by jinzhu** [comment]
Sorry, I currently don’t have the capacity to implement support for elasticsearch. However, I’d be happy if the community could take on this effort. The implementation can either be maintained under the GORM organization or independently. We will add relevant links to recommend it.
