### ISSUE TITLE
gorm通过Raw查询，然后Scan到[]map[string]interface{} 字段名转驼峰，通过NamingStrategy可以实现吗

### ISSUE THREAD

**Issue by puzhengwu** [go-gorm/gorm#6151]
![image](https://user-images.githubusercontent.com/4401394/225195644-dad48f10-6933-400a-81a2-982bded5a1e2.png)

package main

import (
	"log"

	"github.com/iancoleman/strcase"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

type CamelCaseNamingStrategy struct {
	schema.NamingStrategy
}

func (s CamelCaseNamingStrategy) ColumnName(tableName, fieldName string) string {
	return strcase.ToLowerCamel(fieldName)
}

func (s CamelCaseNamingStrategy) TableName(className string) string {
	return strcase.ToSnake(className)
}

func main() {
	db, err := gorm.Open(
		mysql.Open("dev:dev@tcp(192.168.10.1:3306)/3t_dev?charset=utf8&parseTime=True&loc=Local"),
		&gorm.Config{
			PrepareStmt: true,
		},
	)
	if err != nil {
		log.Fatal(err)
	}

	db.NamingStrategy = CamelCaseNamingStrategy{}

	var m []map[string]interface{}
	db.Raw("select * from user limit 1").Scan(&m)

	for _, item := range m {
		for k, v := range item {
			log.Println(k, v) //  希望 field:user_name  to  UserName，但是并没有转换
		}
	}
}

**Comment by a631807682** [comment]
It's funny, but it's lying and doesn't actually support
