### ISSUE TITLE
Automatically execute ALTER TABLE MODIFY COLUMN ，But I didn't write such code 

### ISSUE THREAD

**Issue by chun222** [go-gorm/gorm#6155]
## GORM Playground Link
 [https://github.com/go-gorm/playground/pull/1](https://github.com/go-gorm/playground/pull/1)
## Description
I didn't write such business in the code：
```sql
ALTER TABLE 'mes mat main' MODIFY COLUMN 'mat code' varchar(50) NOT NULL COMMENT 'material code'
```
It seems to be executing automatically, resulting in locking the table
And the fields are of uniqueIndex or index unique type

**Comment by a631807682** [comment]
Use `AutoMigrate` with caution in production unless you know exactly how it works.
Like now you need to disable it.

**Comment by chun222** [comment]
> Use `AutoMigrate` with caution in production unless you know exactly how it works. Like now you need to disable it.

我没有在代码里写这个AutoMigrate业务呢  我怎么彻底关掉它

**Comment by a631807682** [comment]
@chun222 检查一下有没有使用Migrator或者AutoMigrate，如果都没有就跟我们无关。

**Comment by chun222** [comment]
> @chun222 检查一下有没有使用Migrator或者AutoMigrate，如果都没有就跟我们无关。

您看下 这个issue：     [https://github.com/go-gorm/gorm/issues/5957](https://github.com/go-gorm/gorm/issues/5957)   有没有可能是这个原因！

**Comment by chun222** [comment]
@a631807682 您看下 这个issue： https://github.com/go-gorm/gorm/issues/5957 有没有可能是这个原哦

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/issues/6155#issuecomment-1471559148

已经说得很清楚了，你自己看下issue代码
