### ISSUE TITLE
How to get the number of affected rows actually inserted when using the FirstOrCreate method

### ISSUE THREAD

**Issue by AzraelJi** [go-gorm/gorm#6175]
V1.24.6
	result := db.Where(entity.SysClientUser{Email: "sun"}).FirstOrCreate(&entity.SysClientUser{Email: "test"})
result.Created?
result.RowsAffect,but it return tx's rows through read source code

**Comment by AzraelJi** [comment]
who can answer？Thanks！

**Comment by a631807682** [comment]
This is a combined method, if you want to know if data was inserted, you can implement it by yourself.

**Comment by AzraelJi** [comment]
> This is a combined method, if you want to know if data was inserted, you can implement it by yourself.

Can you give an example？

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/blob/master/finisher_api.go#L348
