### ISSUE TITLE
Postgresql Arrays

### ISSUE THREAD

**Issue by ghost** [go-gorm/gorm#62]
Hello, what about postgresql arrays? As I understand if the type of field is slice - gorm interprets it like associations. And if it's []string for example there is go panic: "reflect.Value.FieldByName on string Value"

I know MySQL don't have an array type (and this is very strange I think), but Postgresql uses it heavily.

**Comment by wenweih** [comment]
```"github.com/lib/pq"``` can add array datatype feature to gorm  

something like that:
```golang
import (
  ...
  "github.com/lib/pq"
  ...
)

...
type Block struct {
	gorm.Model
        .....
	Tx                pq.StringArray `gorm:"type:varchar(100)[]"`
}

```

**Comment by challarao** [comment]
Is there a similar thing for UUID array?
