### ISSUE TITLE
Checking which key is duplicate, in case of a ErrDuplicateKey error

### ISSUE THREAD

**Issue by AnshVM** [go-gorm/gorm#6213]
## Your Question

Is there a way to check which key was duplicate, in case of a ErrDuplicateKey error?

## The document you expected this should be explained

[Gorm error handling docs](https://gorm.io/docs/error_handling.html)

**Comment by a631807682** [comment]
Currently not supported, you can convert errors by yourself without using ErrDuplicateKey
https://github.com/go-gorm/postgres/pull/162#discussion_r1138089642
