### ISSUE TITLE
Schema based multi-tenancy

### ISSUE THREAD

**Issue by parmarsan** [go-gorm/gorm#6245]
## Your Question

Schema based multi-tenancy
======================
Does GORM support schema based multi-tenancy? 

https://sultanov.dev/blog/schema-based-multi-tenancy-with-spring-data/

Thanks for your help.

**Comment by saeidee** [comment]
Multi-tenancy mostly relies on application business logic and switching the schema for each tenant on the application level, GORM gives handy options like creating a new session to be able to implement multi-tenancy; For more details, you can have a look at this issue and see how others implemented multi-tenancy https://github.com/go-gorm/gorm/issues/3975.
