### ISSUE TITLE
批量插入不成功，也没收到提示，这方面是否可以优化。

### ISSUE THREAD

**Issue by moipa-cn** [go-gorm/gorm#6257]
使用postgreSQL15数据库，go环境是1.20.3批量生成测试数据，代码如下，发现生成1000条的时候插入可以成功，但循环一万次的时候，并没有数据插入，也没有提示插入失败。
我不知道是postgreSQL15单次插入有数量上限，还是gorm的问题。
=====================================================================
type User struct {
	gorm.Model
	Name     string
	Age      int
	Birthday time.Time
	Sex      string
}
func main(){
var users []User
	for i := 0; i < 10000; i++ {
		user := User{Name: RandomString(6, defaultLetters), Sex: RandomString(1, drune), Age: rand.Intn(100), Birthday: randate()}
		users = append(users, user)
	}
	db.Create(&users)
}
====================================================================
以上代码是伪代码，主要是随机生成一些数据。
如果是gorm的问题，是否在无法插入的时候能够提供err信息，感谢

**Comment by labulakalia** [comment]
@moipa-cn 
```
type User struct {
gorm.Model
Name string
Age int
Birthday time.Time
Sex string
}
func main(){
var users []User
for i := 0; i < 10000; i++ {
user := User{Name: RandomString(6, defaultLetters), Sex: RandomString(1, drune), Age: rand.Intn(100), Birthday: randate()}
users = append(users, user)
}
err := db.Create(&users).Error
if err != nil {
    // check err
}
}
```
