### ISSUE TITLE
Error 1062 (23000): Duplicate entry 'xx' for key 'PRIMARY'

### ISSUE THREAD

**Issue by duxin40** [go-gorm/gorm#6261]
在并发多协程调用gorm的Create方法时，会对主键报错误：
Error 1062 (23000): Duplicate entry 'xx' for key 'PRIMARY'
求问这是为什么？

gorm版本：master最新
go版本：1.17

**Comment by a631807682** [comment]
Concurrency can occur as long as it exists, and you need to choose which locks your business needs
