### ISSUE TITLE
如果我想要多级关联的话我应该怎么做？

### ISSUE THREAD

**Issue by chen-mou** [go-gorm/gorm#6262]
## 如果我想要多级关联的话我应该怎么做？

假设我有个文件表
![image](https://user-images.githubusercontent.com/42209673/233844149-3b838389-7266-46c2-8418-27b0cd41befb.png)
又有一个文件数据表他与文件表是多对一的关系并且文件数据表为多
![image](https://user-images.githubusercontent.com/42209673/233844201-28e7670f-45bf-4c65-9ae5-4eeaa7b23906.png)
这个时候业务通常是通过关联文件数据表来获取文件的uri。例如用户有一个头像。这时如果我想通过查询用户同时将用户头像的uri查询出来我该如何调用方法

## The document you expected this should be explained
https://gorm.io/zh_CN/docs/associations.html
[](https://gorm.io/zh_CN/docs/associations.html)

## Expected answer

请告诉具体的调用方法的方式，谢谢

**Comment by chen-mou** [comment]
我使用的gorm版本为v8

**Comment by a631807682** [comment]
From your description you can see that you need to define as has many and query through Preload
https://gorm.io/zh_CN/docs/many_to_many.html#Many-To-Many
https://gorm.io/docs/preload.html#Preload
