### ISSUE TITLE
升级以后，插入数据以后自增主键id未返回

### ISSUE THREAD

**Issue by LiveAlone** [go-gorm/gorm#6267]
## https://github.com/LiveAlone/playground

grom 版本升级 1.21.13 升级到 1.24.6 版本时候， 发现Insert 返回主键Id 不对。 

我的model 定义
```
type User struct {
	ID   ID `gorm:"primaryKey;column:id" json:"id"`
	Name string
}

type ID int64

func (i ID) GormDataType() string {
	return "int64"
}

func (i ID) Value() (driver.Value, error) {
	return int64(i), nil
}

func (i ID) Int64() int64 {
	return int64(i)
}
```
发现执行Create 以后 int64 id 类型没有返回，debug 发现版本主键类型解析有问题。
老版本没问题
![image](https://user-images.githubusercontent.com/20422416/234331699-3e5d0214-b73f-45b2-a928-d8ea3b971de0.png)

新版本 GORMDataType 竟然解析成 int64 (GormDataType 自定义类型)
![image](https://user-images.githubusercontent.com/20422416/234332004-bf10dc71-f628-4ec1-8300-18467fa00877.png)

翻看代码，/Users/zyb/go/pkg/mod/gorm.io/gorm@v1.21.13/schema/field.go:76 这个方法

老版本解析类型，立即赋值给 GORMDataType 
![image](https://user-images.githubusercontent.com/20422416/234332783-c967c1b1-688f-4565-8d0b-9a5f66e15077.png)

新版本这行被删除了
![image](https://user-images.githubusercontent.com/20422416/234333029-e9a790af-ffe5-4958-bf0e-e1f425df7ab0.png)

导致GORMDataType 不对。
![image](https://user-images.githubusercontent.com/20422416/234333099-56ea0edc-62d9-40f9-bdc5-7cd114efa50b.png)

后面由于GROM 类型不对， 未识别自增主键， 没有赋值自增id
![image](https://user-images.githubusercontent.com/20422416/234333505-494f0017-f9ed-4e15-ad72-f420f2c66118.png)

```
type GormDataTypeInterface interface {
	GormDataType() string
}

type DataType string

const (
	Bool   DataType = "bool"
	Int    DataType = "int"
	Uint   DataType = "uint"
	Float  DataType = "float"
	String DataType = "string"
	Time   DataType = "time"
	Bytes  DataType = "bytes"
)
```
所以这个接口， 约定返回DataType , 是不是定义返回类型 DataType 而不是string 更明确一点。

**Comment by a631807682** [comment]
GormDataType refers to the database type and should not be `int64`. Of course, such a type definition may still not conform to DataType (Int/Uint), such as the alias `integer` of `int` in mysql, but the behavior here is only used to guess whether the primary key is self-incrementing. You It can be specified directly through `autoIncrement`.
```diff
type User struct {
-	ID   ID `gorm:"primaryKey;column:id" json:"id"`
+ 	ID   ID `gorm:"primaryKey;column:id;autoIncrement" json:"id"`
	Name string
}
```
