### ISSUE TITLE
supports batch insertion of any model

### ISSUE THREAD

**Issue by zhanghuizong** [go-gorm/gorm#6271]
# code

```go
var dataList []any
m1 := model.Province{}
m1.Code = 65
m1.Name = "新疆维吾尔自治区"
dataList = append(dataList, m1)

m2 := model.Province{}
m2.Code = 41
m2.Name = "河南省"
dataList = append(dataList, m2)

bootstrap.Db.Create(dataList)
```

# err msg

```
Table not set, please set it like: db.Model(&user) or db.Table("users")
```

# end

Can you support the above writing method?

**Comment by a631807682** [comment]
Not supported, you can support it yourself via Scanner/Valuer

https://gorm.io/docs/data_types.html#Implements-Customized-Data-Type

**Comment by zhanghuizong** [comment]
Is there any consideration or support for this feature in the later stage?

**Comment by a631807682** [comment]
This feat will not be supported. First, you can implement it by yourself. Second, any can have multiple layers of wrap. It does not make much sense to guess the model used by recursive unwrap.
