### ISSUE TITLE
Correct conversion of type aliases

### ISSUE THREAD

**Issue by GGXXLL** [go-gorm/gorm#6297]
## Your Question

I an using this code. The generated sql is ```SELECT * FROM `modules` WHERE status="1" ORDER BY `modules`.`status` LIMIT 1```

```go
package db_test

import (
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

type StatusEnum int64

const (
	StatusEnumEnable StatusEnum = iota
	StatusEnumDisable
)

var StatusEnumMap = map[StatusEnum]string{
	StatusEnumEnable:  "Enable",
	StatusEnumDisable: "Disable",
}

//func (e StatusEnum) String() string {
//	if v, ok := StatusEnumMap[e]; ok {
//		return v
//	}
//	return "unknown"
//}

type module struct {
	Status StatusEnum
}

func TestEnum(t *testing.T) {
	db, _ := gorm.Open(sqlite.Open(":memory:"))

	db.AutoMigrate(&module{})

	db.Model(&module{}).Create(&module{Status: StatusEnumDisable})

	var out *module
	// SELECT * FROM `modules` WHERE status=1 ORDER BY `modules`.`status` LIMIT 1
	db.Debug().Model(&module{}).Where("status=?", StatusEnumDisable).First(&out)

	t.Log(out)
	//t.Logf("status value: %d, status string: %s", out.Status, out.Status)
}

```

## Expected answer

The generate sql condition should be `status=1` instead of `status="1"`.

**Comment by a631807682** [comment]
You can use [Scanner / Valuer](https://gorm.io/docs/data_types.html#Scanner-x2F-Valuer)

```go
func (s StatusEnum) Value() (driver.Value, error) {
	return int64(s), nil
}
```

**Comment by GGXXLL** [comment]
But I see mysql general_log. The execute sql is `status=1`. The debug log info is mislead.
<img width="924" alt="image" src="https://user-images.githubusercontent.com/35254251/236389466-00f70d7d-08ab-4e3a-a21f-0d871df88704.png">

**Comment by a631807682** [comment]
What gorm prints is not the real log. In fact, the log can only be obtained in the driver. Gorm cannot obtain the actual execution sql log. For example, the acquisition of the value depends on the [database/sql/convert.go](https://github.com/golang/go/blob/master/src/database/sql/convert.go#L108) , but as a log, I think it is not necessary.
