### ISSUE TITLE
希望支持 指针表字段形式查询，无需再担心表字段 写错或重命名

### ISSUE THREAD

**Issue by rbtyang** [go-gorm/gorm#6300]
## Describe the feature
希望支持 指针表字段形式查询，无需再担心表字段 写错或重命名
例如 query.Where(&person.Id, 123).Where(&person.Name, "张三")

## Motivation

参考：https://github.com/acmestack/gorm-plus
参考：https://github.com/tangpanqing/aorm

**Comment by a631807682** [comment]
gorm-plus works by creating objects and associating pointers and field names.
aorm stores the correspondence between object pointers and field names, which means that if we want to use a new object, we need to re-store it.
Like gormx, they provide more gorm syntax, but at the same time, they also pay a certain price. It is a good way to provide third-party reference, and we will not support it in gorm.
