### ISSUE TITLE
AutoMigrate will create many indexes of the same field

### ISSUE THREAD

**Issue by lixh00** [go-gorm/gorm#6304]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

AutoMigrate会创建很多个同字段的索引，如下图所示
AutoMigrate will create many indexes of the same field, as shown in the figure below

![image](https://user-images.githubusercontent.com/72033265/236979085-aaa57ee4-a3f3-4bcc-a413-4b4f0e74b623.png)

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/6224

**Comment by lixh00** [comment]
> duplicated of #6224

The maximum number of MySQL single-table indexes is 64. This BUG will keep creating until all quotas are used up and AutoMigrate can no longer be used.

MySQL单表索引数最大为64个，这个BUG会一直创建，直到用完所有额度导致无法再AutoMigrate。
