### ISSUE TITLE
When creating some data with associations, the foreign key of the associated struct sometimes would be zero

### ISSUE THREAD

**Issue by dhhua** [go-gorm/gorm#6309]
type Parent struct {
    ID int64,
    AppId int,
   Sons []Son `gorm:"foreighKey:app_id,parent_id"`
}
type Son struct {
    ParentId int64,
    AppId int
}

**Comment by saeidee** [comment]
Please add more detail about the issue as well as steps to reproduce; You may open a PR here https://github.com/go-gorm/playground on how to reproduce the issue.

**Comment by saeidee** [comment]
Closing the issue since there is no detail and reproduction step provided.
