### ISSUE TITLE
CreateInBatches is not running inside Transactions

### ISSUE THREAD

**Issue by timo-klarshift** [go-gorm/gorm#6310]
I would expect code like this

```go
return d.table().Clauses(clause.OnConflict{DoNothing: true}).CreateInBatches(records, 2000).Error
```

to execute wrapped in a transaction. this is not the case. I can observe this by inspecting the query log.

Judging from the code and how it is documented, it gives the impression that it should run inside a transaction.

**Comment by rahmatrhd** [comment]
@timo-klarshift I faced the same issue and solved by using session
```go
db.Session(&gorm.Session{CreateBatchSize: 2000}).Create(records)
```
