### ISSUE TITLE
Column name isn't trimmed

### ISSUE THREAD

**Issue by rickyManalo** [go-gorm/gorm#6313]
That's it. Gave me a bit of a rage tbh, but was a small issue nonetheless. It's probably written in the docs, or not in the docs(docs is quite sparse in terms of samples which is infuriating tbh. I quite like documentations that doesn't make me assume stuff) to not put a space between the semi-colon after a tag and the value, but I thought it would look pretty to do that and that caused the issue, for MySQL at least.

So if you did something like ```gorm:"column: status"```, it would take the space in front as well and use that as your column name. Removing that or not adding it in the first place fixes the issue.

**Comment by saeidee** [comment]
Golang's core libraries like `encoding/json` is also behaving the same(you can see it is not trimming the field name https://go.dev/play/p/F1aQtJHV_zX).

However, feel free to add open a PR in the documentation https://github.com/go-gorm/gorm.io
