### ISSUE TITLE
support dynamic sql with xml like mybatis

### ISSUE THREAD

**Issue by timandy** [go-gorm/gorm#6314]

**Comment by saeidee** [comment]
Could you please add a brief motivation/use case with an example?

**Comment by jinzhu** [comment]
Gen should fits your requirements https://gorm.io/gen/dynamic_sql.html

**Comment by timandy** [comment]
Editing XML can use the editor's automatic completion feature, but editing comments can not.

**Comment by jinzhu** [comment]
sorry, but not going to support xml for now.

**Comment by timandy** [comment]
It's OK, I use go-mybatis implemented it.
