### ISSUE TITLE
Adding retries for an error for all DB calls

### ISSUE THREAD

**Issue by nbajaj90** [go-gorm/gorm#6315]
In application, observing intermittent failures for "hostname resolving error" (Works most of the time, but seeing intermittent failures). Is there any way to add retries for this error? So that if the error happens for any DB call, it retries implicitly before failing with this error.

**Comment by a631807682** [comment]
database/sql will retry when it receives an ErrBadConn error. If you need to support more retry strategies, you can use [Plugin](https://gorm.io/docs/write_plugins.html#Plugin) Or [Customize-Driver](https://gorm.io/docs/connecting_to_the_database.html#Customize-Driver) to customize your own retry strategy
