### ISSUE TITLE
about sql parsed

### ISSUE THREAD

**Issue by xiaoL1211** [go-gorm/gorm#6317]
## Your Question

SQL parsed by Gorm : SELECT * FROM \`admin\` ORDER BY \`admin\`.\`id\` LIMIT 1;

Carrying backquotes in SQL.

## Expected answer

I want  SQL : SELECT * FROM admin ORDER BY admin.id LIMIT 1

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/6316
