### ISSUE TITLE
Unnecessary ALTER TABLE during migration

### ISSUE THREAD

**Issue by marius-xentral** [go-gorm/gorm#6320]
## Description

Here's my model 
```
type SalesOrderItems struct {
	ID            uint      `json:"id" gorm:"primaryKey"`
	ItemId        uint      `json:"itemId" gorm:"not null;uniqueIndex:unique_soi;"`
	OrderId       uint      `json:"orderId" gorm:"not null;index:combi_soi_order_license_idx;"`
	LicenseId     string    `json:"licenseId" gorm:"not null;index:combi_soi_order_license_idx;uniqueIndex:unique_soi;"`
	ProductId     uint      `json:"productId;" gorm:"not null;"`
	Quantity      float32   `json:"quantity" gorm:"scale:2;not null"`
	NetPrice      float32   `json:"netPrice" gorm:"scale:2;not null"`
	Discount      float32   `json:"discount" gorm:"scale:2;default:0"`
	BaseDiscount  float32   `json:"baseDiscount" gorm:"scale:2;default:0"`
	PurchasePrice float32   `json:"purchasePrice" gorm:"scale:2;default:0"`
	Tax           float32   `json:"tax" gorm:"scale:4;not null;"`
	CreatedAt     time.Time `json:"createdAt" gorm:"not null;"`
	UpdatedAt     time.Time `json:"updatedAt" gorm:"not null;"`
}
```

When I run the migration during start up `db.DB.AutoMigrate(models...)` where &SalesOrderItems is an element of models gorm always executes a ALTER TABLE command on the discount column and tries to set it to 0.0000.

1. the default value is already set
2. the table is enormous and that command shuts down the whole DB ... as a workaround I had to exclude this table from the auto migration

![image](https://github.com/go-gorm/gorm/assets/88558774/a2ce7e56-09cc-4431-bac1-90dd254cec95)

**Comment by saeidee** [comment]
Please create a playground pull request since it is not reproducible with the details you provided, also you mentioned the default value is already set, what is it? Is it (0.000000) or (0.00000) if it is

**Comment by saeidee** [comment]
It could be related to your database/table setup for the floating points([link](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html)) which is different from the float32 for Golang (it is 6 digit floating point like this: 0.000000).

**Comment by marius-xentral** [comment]
no I am actually using `gorm.io/driver/postgres`

**Comment by marius-xentral** [comment]
@saeidee that sounds like there is a problem within this section [here](https://github.com/go-gorm/gorm/blob/f5837deef3d0c8edc881ca24b992689c71a5cc06/migrator/migrator.go#L498)

**Comment by saeidee** [comment]
Could you please create a PR with steps to reproduce it in https://github.com/go-gorm/playground?

**Comment by marius-xentral** [comment]
I upgraded the repo from go1.19 to go1.20 and updated gorm. the issue seems to be resolved as far as I can tell for now.
