### ISSUE TITLE
Rename License to LICENSE

### ISSUE THREAD

**Issue by d1ss0nanz** [go-gorm/gorm#6331]
## Describe the feature

Rename the license file from License to LICENSE

## Motivation

LICENSE is the standard. A lot of tooling is building on this convention.
For example SBOM generation and license management tools.

## Related Issues

N/A

**Comment by Avinaba-Bhattacharjee** [comment]
Hey, @jinzhu, I was looking for a good first issue to make a contribution. Could this still be assigned to me?

**Comment by Avinaba-Bhattacharjee** [comment]
Feature added and PR made, waiting for review
