### ISSUE TITLE
mysql  query error

### ISSUE THREAD

**Issue by wms3001** [go-gorm/gorm#6332]
{"time":"2023-05-19T10:02:32.4227988+08:00","level":"-","prefix":"echo","file":"recover.go","line":"113","message":"[PANIC RECOVER] runtime error: index out of range [0] with length 0 goroutine 5 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1()\n\tC:/Users/Administrator/go/pkg/mod/github.com/l
abstack/echo/v4@v4.10.2/middleware/recover.go:93 +0x14e\npanic({0x1083080, 0xc000020f18})\n\tC:/Program Files/Go/src/runtime/panic.go:884 +0x213\nwork/service.GetO
rderById({0x11e10c8, 0xc000070a00})\n\tC:/Users/Administrator/go/src/work/service/order.go:77 +0x132f\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x11e10c8, 0x
c000070a00})\n\tC:/Users/Administrator/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/echo.go:575 +0x51\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.f
unc1.1({0x11e10c8, 0xc000070a00})\n\tC:/Users/Administrator/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/middleware/recover.go:119 +0xfe\ngithub.com/labstack/ech
o/v4/middleware.LoggerWithConfig.func2.1({0x11e10c8, 0xc000070a00})\n\tC:/Users/Administrator/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/middleware/logger.go:1
26 +0xe2\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000296000, {0x11d88a0?, 0xc00034e000}, 0xc0002a0700)\n\tC:/Users/Administrator/go/pkg/mod/github.com/lab
stack/echo/v4@v4.10.2/echo.go:662 +0x3d1\nnet/http.serverHandler.ServeHTTP({0xc000340210?}, {0x11d88a0, 0xc00034e000}, 0xc0002a0700)\n\tC:/Program Files/Go/src/net
/http/server.go:2936 +0x316\nnet/http.(*conn).serve(0xc000288360, {0x11d8eb8, 0xc000340120})\n\tC:/Program Files/Go/src/net/http/server.go:1995 +0x612\ncreated by 
net/http.(*Server).Serve\n\tC:/Program Files/Go/src/net/http/server.go:3089 +0x5ed\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x1b36c6d9ba8, 0x72)\n
\tC:/Program Files/Go/src/runtime/netpoll.go:306 +0x89\ninternal/poll.(*pollDesc).wait(0x0?, 0x0?, 0x0)\n\tC:/Program Files/Go/src/internal/poll/fd_poll_runtime.go
:84 +0x32\ninternal/poll.execIO(0xc00033e018, 0xc00007fa98)\n\tC:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xf7\ninternal/poll.(*FD).acceptOne(0xc0003
3e000, 0x1a4, {0xc000334780?, 0x0?, 0xc00007fc84?}, 0x0?)\n\tC:/Program Files/Go/src/internal/poll/fd_windows.go:936 +0x6d\ninternal/poll.(*FD).Accept(0xc00033e000
, 0xc00007fc70)\n\tC:/Program Files/Go/src/internal/poll/fd_windows.go:970 +0x1d6\nnet.(*netFD).accept(0xc00033e000)\n\tC:/Program Files/Go/src/net/fd_windows.go:1
39 +0x65\nnet.(*TCPListener).accept(0xc0000087e0)\n\tC:/Program Files/Go/src/net/tcpsock_posix.go:148 +0x25\nnet.(*TCPListener).AcceptTCP(0xc0000087e0)\n\tC:/Progr
am Files/Go/src/net/tcpsock.go:284 +0x3d\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0x9a2960?})\n\tC:/Users/Administrator/go/pkg/mod/github.com/labs
tack/echo/v4@v4.10.2/echo.go:982 +0x1d\nnet/http.(*Server).Serve(0xc000294000, {0x11d8300, 0xc00000a5e0})\n\tC:/Program Files/Go/src/net/http/server.go:3059 +0x385
\ngithub.com/labstack/echo/v4.(*Echo).Start(0xc000296000, {0x10c495b, 0x5})\n\tC:/Users/Administrator/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/echo.go:679 +0
xce\nmain.main()\n\tC:/Users/Administrator/go/src/work/main.go:48 +0x31e\n\ngoroutine 19 [select]:\ndatabase/sql.(*DB).connectionOpener(0xc0002780d0, {0x11d8e10, 0
xc000240a00})\n\tC:/Program Files/Go/src/database/sql/sql.go:1218 +0x8d\ncreated by database/sql.OpenDB\n\tC:/Program Files/Go/src/database/sql/sql.go:791 +0x18d\n
\ngoroutine 21 [select]:\ngithub.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()\n\tC:/Users/Administrator/go/pkg/mod/github.com/go-sql-driver/mysql@v1.7
.0/connection.go:614 +0xaa\ncreated by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher\n\tC:/Users/Administrator/go/pkg/mod/github.com/go-sql-driver/mysql
@v1.7.0/connection.go:611 +0x10a\n\ngoroutine 6 [IO wait]:\ninternal/poll.runtime_pollWait(0x1b36c6d9ab8, 0x72)\n\tC:/Program Files/Go/src/runtime/netpoll.go:306 +
0x89\ninternal/poll.(*pollDesc).wait(0xc00005eb40?, 0x11d8e10?, 0x0)\n\tC:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.execIO(0xc
00033e298, 0x1124018)\n\tC:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xf7\ninternal/poll.(*FD).Read(0xc00033e280, {0xc000340221, 0x1, 0x1})\n\tC:/Program Files/Go/src/internal/poll/fd_windows.go:436 +0x2b8\nnet.(*netFD).Read(0xc00033e280, {0xc000340221?, 0x60?, 0x15cb0e0?})\n\tC:/Program File\n"}

**Comment by saeidee** [comment]
Please create a PR in https://github.com/go-gorm/playground with steps to reproduce it, it is hard to understand the issue with the details you give.

**Comment by saeidee** [comment]
Closing the PR since no details provided.
