### ISSUE TITLE
Updating nested struct ID on Save

### ISSUE THREAD

**Issue by byroncoetsee** [go-gorm/gorm#6334]
I'm trying to save a new object to my database. For the sake of this example, I will use the following:

```
type TimeStamps struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	... a few other fields
}

type OrderBase struct {
	TimeStamps
	ID        uint       `json:"id,omitempty" gorm:"primarykey"`
	... a few other fields
}

type Order struct {
	OrderBase
	Reference               string    `json:"reference,omitempty"`
}

newOrder := Order{...filled order...}
db.Save(&newOrder)
```

What I'm expecting to happen, and what did happen when the ID field lived directly within the Order struct, is after the save I can call `newOrder.ID` and have the latest ID value (no longer the default 0).

What I'm seeing now is, the order is saved to the DB however when I call `newObject.ID`, it's still 0.

From what I can tell after doing a lot of research, it looks like there is no way to get around this and the only way to get the result I want is to specify ID, createdAt and updatedAt in each of my structs individually. Is this the case?

I'm happy to use small workarounds like putting code in BeforeSave or AfterSave (which actually shows the updated value!).

Thanks

**Comment by byroncoetsee** [comment]
That's a well structured question and was marked as reproduce steps missing (they're there) and stale because I haven't linked to a playground, which requires all kinds of setups and new programs like Docker, which I don't use. Just to ask a question which is very easy to understand...

**Comment by black-06** [comment]
https://github.com/go-gorm/playground/pull/600

But It works.
