### ISSUE TITLE
Test: Complementary unit tests for new features

### ISSUE THREAD

**Issue by a631807682** [go-gorm/gorm#6345]
## Describe the feature

We need to add more unit tests for new features

## Motivation

We have added some new features in recent versions, but currently there is not enough test coverage, we need some tests to clarify the behavior of these features in the driver, and to avoid being broken.

The following tasks are open (welcome to add more)
- [x] Test for [ErrDuplicatedKey](https://github.com/go-gorm/gorm/pull/6004) @saeidee
- [ ] Test for [TableType](https://github.com/go-gorm/gorm/pull/6225) @saeidee 
- [x] Test for [ErrForeignKeyViolated](https://github.com/go-gorm/gorm/pull/6329) (Incomplete, need to add driver implementation) @saeidee

If anyone is interested in the above tasks, please leave a message in the comments

**Comment by saeidee** [comment]
I will be able to add the tests on drivers for https://github.com/go-gorm/gorm/pull/6004 and https://github.com/go-gorm/gorm/pull/6329 as well as the implementation for https://github.com/go-gorm/gorm/pull/6329.

**Comment by a631807682** [comment]
@saeidee thank you

**Comment by saeidee** [comment]
@a631807682 shall we write the tests in each driver repository or gorm repository?

**Comment by a631807682** [comment]
> shall we write the tests in each driver repository or gorm repository?
> Also, you can assign the TableType test to me as well.


You can test in gorm to avoid a lot of repetitive testing code

**Comment by saeidee** [comment]
@a631807682 shall we close this issue?
