### ISSUE TITLE
how to delete object with self-referenced objects

### ISSUE THREAD

**Issue by pplmx** [go-gorm/gorm#6346]
### Discussed in https://github.com/go-gorm/gorm/discussions/6344

<div type='discussions-op-text'>

<sup>Originally posted by **pplmx** May 22, 2023</sup>
if there is a struct like this: 
```go
type Task struct {
    ID       uint
    PrevDeps []*Task `gorm:"many2many:task_depends;joinForeignKey:NextID;joinReferences:PrevID"`
    NextDeps []*Task `gorm:"many2many:task_depends;joinForeignKey:PrevID;joinReferences:NextID"`
}
```

Using this sentence to delete, which can only delete task(ID=1) and cannot delete NextDeps
```go
var t Task
t.ID = 1
db.Select("NextDeps").Delete(&t).Error
```
</div>

**Comment by saeidee** [comment]
You can delete it using Clear with Unscope function.
<img width="707" alt="image" src="https://github.com/go-gorm/gorm/assets/29974712/0e1e1226-d0ce-41be-9260-51e0f498dee7">

**Comment by pplmx** [comment]
```
	gorm.io/driver/mysql v1.5.0
	gorm.io/gorm v1.25.0
```

1. My Association object has no Unscoped func.
2. I want to soft delete, unscoped clear is a real deletion

**Comment by pplmx** [comment]
> My Association object has no Unscoped func.
Upgrade to gorm 1.25.1, the func is found.

**Comment by pplmx** [comment]
> I want to soft delete, unscoped clear is a real deletion

According to [this doc](https://gorm.io/zh_CN/docs/associations.html#%E5%B8%A6-Select-%E7%9A%84%E5%88%A0%E9%99%A4), it should delete a record with its relations when using `select`.

Actually, it only works fine on two different objects relationship.

**Comment by pplmx** [comment]
Hi, @saeidee 

I push a PR [here](https://github.com/go-gorm/playground/pull/601)

**Comment by pplmx** [comment]
Is it a bug?

**Comment by saeidee** [comment]
Added comment in your PR.

**Comment by pplmx** [comment]
Summary for the above:
Three Scenario:
- `A has many B`: deleting A, B also can be deleted
- `A has many Prev-A and many Next-A`: deleting A, many Next-A can be deleted
- `A has many B, B has many C`: deleting A, B and C also can be deleted

**Comment by saeidee** [comment]
Closing the issue since commented in the playground PR https://github.com/go-gorm/playground/pull/601.

**Comment by pplmx** [comment]
Can you answer this case: 
> A has many B, B has many C

Thanks a lot.
