### ISSUE TITLE
TestDialectorWithErrorTranslatorSupport fatal message error

### ISSUE THREAD

**Issue by GGXXLL** [go-gorm/gorm#6347]
## Description

Hi, Maybe the fatal message is error?

https://github.com/go-gorm/gorm/blob/001738be49d26d341f88377d6006356573c9d045/tests/error_translator_test.go#L19

I think should be 

```
if !errors.Is(err, untranslatedErr) {
	t.Fatalf("expected err: %v got err: %v", untranslatedErr, err)
}
```
or 

```
if errors.Is(err, translatedErr) {
	t.Fatalf("expected err: %v got err: %v", untranslatedErr, translatedErr)
}
```

**Comment by saeidee** [comment]
Closing the issue since there is an open PR to refactor it https://github.com/go-gorm/gorm/pull/6350
