### ISSUE TITLE
Support deleting Object with Self-Reference(Many-to-many) by cascade

### ISSUE THREAD

**Issue by pplmx** [go-gorm/gorm#6358]
## Describe the feature

`Model A` has many `Prev-Model-A` and many `Next-Model-A`, e.g. `Task`, `PrevTasks`, `NextTasks`

If `Task` was `deleted`, `NextTasks` should `be able to be deleted by cascade`.

## Related Issues

#6346, #6344, [go-orm/playground PR](https://github.com/go-gorm/playground/pull/601#discussion_r1206942654)

**Comment by pplmx** [comment]
# FYI.
Here is [demo](https://github.com/pplmx/orm-demo) implemented by `Spring JPA`, which implements the above requirement.

**Comment by Shahriar-Sazid** [comment]
You can use AfterDelete hook to implement this.

```
func (t *Task) AfterDelete(tx *gorm.DB) (err error) {
	tx.Clauses(clause.Returning{}).Where("prev_id = ?", t.ID).Delete(&TaskDepends{})
	return
}
```

**Comment by pplmx** [comment]
Hi, @Shahriar-Sazid 
Sorry for the  late reply.
1. It seems that the function you supply only deletes the TaskDepends Record, while its next_deps in Task table don't be deleted, Right?
2. You use TaskDepends struct, which is not defined in my code, so I use this solution to clear the relationship(It still cannot delete the records in Task)
```go
func (t *Task) AfterDelete(tx *gorm.DB) (err error) {
	if err = tx.Model(t).Association("PrevDeps").Clear(); err != nil {
		return
	}
	if err = tx.Model(t).Association("NextDeps").Clear(); err != nil {
		return
	}
	return
}
```

**Comment by Shahriar-Sazid** [comment]
I think your attached snippet worked properly. Right?

**Comment by pplmx** [comment]
> I think your attached snippet worked properly. Right?

Yes

**Comment by pplmx** [comment]
FYR. https://github.com/go-gorm/gorm/issues/6357#issuecomment-1639161159
