### ISSUE TITLE
AutoMigrate creating different unique Index on subsequent runs

### ISSUE THREAD

**Issue by cabeedelhertz** [go-gorm/gorm#6378]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/608

## Description

I have an existing database and consistently run `Automigrate` but after upgrading my gorm version from 1.28.3, the automigrate is creating different unique indexes than the ones I have defined and already exist in my database.

To reproduce, pull this branch and run `GORM_DIALECT=postgres go test`. This should work and pass tests. But if you run it again, it will fail to make migrations because it is trying to create a uniqueIndex and uniqueConstraint that doesn't have the same `name` or `where` clause as the unique index that I defined:
`ERROR: could not create unique index "idx_users_description" (SQLSTATE 23505)`

After the initial run of `AutoMigrate` the unique indexes that I defined are correctly created:
<img width="500" alt="image" src="https://github.com/go-gorm/playground/assets/60052974/c2c1b06a-119d-4940-9fe3-345a0403bd23">

But after the next time I run `AutoMigrate`, it created new unique indexes with a different name and without the where clause:
<img width="500" alt="image" src="https://github.com/go-gorm/playground/assets/60052974/b58cf2b0-c873-4fc2-a0ab-ac2fc8e19538">

I can only get to the state of the second picture if I don't have any data that conflicts the `where` clause of the unique index of the `description` column. In my use case, I have a table with a unique index with a `where deleted_at is NULL` condition but now that my `AutoMigrate` behaves differently, I cannot run migrations.

Did something change with how `AutoMigrate` handles unique indexes?

**Comment by a631807682** [comment]
What version of postgres are you using? This seems to be an error caused by the handling of the index name, but in fact I cannot reproduce the wrong creation of this index from the link you provided.

**Comment by cabeedelhertz** [comment]
> What version of postgres are you using? This seems to be an error caused by the handling of the index name, but in fact I cannot reproduce the wrong creation of this index from the link you provided.

using `gorm.io/driver/postgres v1.5.2`

**Comment by cabeedelhertz** [comment]
> fact I cannot reproduce the wrong creation of this index from the link you provided.

And yeah sorry with the given tests you can't actually create the wrong index because the tests insert conflicting data. But you should see errors that it is failing to create those indexes. I just included the "wrong" index in the description to show what `autoMigrate` is _trying_ to create

**Comment by a631807682** [comment]
refer to https://github.com/go-gorm/gorm/issues/6381#issuecomment-1580164621
At present, the redundant index can only be deleted manually.
```go
if DB.Migrator().HasIndex(&User{}, "users_description_key") {
	DB.Exec(`ALTER TABLE ? DROP CONSTRAINT ?`,
		clause.Expr{SQL: "users"},
		clause.Expr{SQL: "users_description_key"},
	)
}
```

**Comment by cabeedelhertz** [comment]
Yeah that is what I've been doing to fix it but gorm shouldn't be creating that index in the first place. Do we know why it gets created and can we get a fix the next release?

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/issues/6381#issuecomment-1929427042
