### ISSUE TITLE
我在获取sql server的uniqueidentifier类型的数据时，乱码了

### ISSUE THREAD

**Issue by mengyan258** [go-gorm/gorm#6379]
我在获取sql server的uniqueidentifier类型的数据时，乱码了，我go的接收数据类型是[]byte，接收到了后转为string类型时，乱码！以下是乱码信息：Db\u000b��C.A�E\u0005QǪWB，实际上应该是5CD6C26F-DD9E-4713-BBA2-0028E0F8DF47这种样子才对，试过很多转的方法，都没用

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/5419
