### ISSUE TITLE
too much time cost for a simple sql

### ISSUE THREAD

**Issue by ThanksSirAlex** [go-gorm/gorm#6384]
## Your Question
A very simple sql cost too many time when limit >= 85. Any idea on why? 10 times longer than when limit < 85. And I am sure it is not a slow sql. gorm ver 1.24.0

## Expected answer
just want to know why

**Comment by black-06** [comment]
Maybe related to https://github.com/go-gorm/gorm/issues/6292#issuecomment-1534487259

**Comment by ThanksSirAlex** [comment]
Is there any way that can help me track where these time were spent.

**Comment by ThanksSirAlex** [comment]
> Maybe related to [#6292 (comment)](https://github.com/go-gorm/gorm/issues/6292#issuecomment-1534487259)

Not sure. It's super weird. I'm going to try more.

**Comment by aohanhongzhi** [comment]
> 

like

**Comment by ThanksSirAlex** [comment]
Close this issue. Because it turn out to be a mysql bug. When using `prepared statement` Mysql could chose wrong index.  Fixed in Mysql 8.0.26.
<img width="1154" alt="MicrosoftTeams-image" src="https://github.com/go-gorm/gorm/assets/22314407/f7764276-8e11-4563-a92f-871544a1f8dd">
