### ISSUE TITLE
Preload与Select冲突？

### ISSUE THREAD

**Issue by congjunhua** [go-gorm/gorm#6400]
## Your Question

刚刚发现只要通过Select()选择特定字段，Preload()就不生效。

通过`Debug`稳定复现。

## The document you expected this should be explained

https://gorm.io/zh_CN/docs

## Expected answer

请问这是为何？是我的用法有问题吗🤔️

**Comment by a631807682** [comment]
Please provide reproducible code

**Comment by jinzhu** [comment]
You need to include foreign fields in the selected columns.
