### ISSUE TITLE
Creating unique indexes with naming and where condition in postgres will create redundant error indexes

### ISSUE THREAD

**Issue by moluuser** [go-gorm/gorm#6407]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/616

## Description
For this field:
https://github.com/go-gorm/playground/pull/616/files#diff-79ce3229c13921b79b1175dcb211336aaf84dfd8edcf19c07698934d4fe70e5eR32

The index named `uidx_user_with_unique_indices_token` is expected to be created, but the index named `idx_user_with_unique_indices_token` is created incorrectly at the same time.
 
The error occurred after upgrading gorm, it was working normally in v1.24.2. And in my testing, only postgres will appear.

**Comment by a631807682** [comment]
One of the cases of https://github.com/go-gorm/gorm/issues/6381

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/issues/6381#issuecomment-1929427042
