### ISSUE TITLE
Is gorm still maintained?

### ISSUE THREAD

**Issue by YuZongYangHi** [go-gorm/gorm#6409]
Is gorm still maintained? Why don't many of the many table query questions about many2many mentioned above have a best answer?

**Comment by YuZongYangHi** [comment]
https://github.com/go-gorm/gorm/issues/3287

**Comment by YuZongYangHi** [comment]
@jinzhu

**Comment by jinzhu** [comment]
I answered it in https://github.com/go-gorm/gorm/issues/3287#issuecomment-676184642 and there are working code examples in the following threads.

Please don't ask any meanless & duplicated questions to waste others' time, search before asking.
