### ISSUE TITLE
Many2Many Multi-table query using Join Table error: Unknown column

### ISSUE THREAD

**Issue by YuZongYangHi** [go-gorm/gorm#6410]
I have two tables doing many2many, but when I try to join the query, he always reports that the column cannot be found

```
type MenuRole struct {
	Id          int64     `json:"id"`
	Name        string    `gorm:"column:name;unique;not null" json:"name"`
	Menus       []*Menu   `gorm:"many2many:rbac_menu_role_binding_menu;joinForeignKey:role_id;joinReferences:menu_id" json:"menus"`
}

type Menu struct {
	Id          int64       `json:"id"`
	Name        string      `gorm:"column:name" json:"name"`
	Roles       []*MenuRole `gorm:"many2many:rbac_menu_role_binding_menu;joinForeignKey:menu_id;joinReferences:role_id" json:"roles"`
}

type MenuRoleBindingMenu struct {
	Id         int64     `json:"id"`
	RoleId     int64     `gorm:"primaryKey;column:role_id" json:"roleId"`
	MenuId     int64     `gorm:"primaryKey;column:menu_id; not null;" json:"menuId"`
	CreateTime time.Time `json:"createTime"`
	UpdateTime time.Time `json:"updateTime"`
}
```

**Comment by YuZongYangHi** [comment]
Rewrite intermediate table steps:
```
db.SetupJoinTable(&MenuRole{}, "Menus", &MenuRoleBindingMenu{})
db.SetupJoinTable(&Menu{}, "Roles", &MenuRoleBindingMenu{})
```

**Comment by YuZongYangHi** [comment]
@jinzhu

**Comment by YuZongYangHi** [comment]
@black-06

**Comment by black-06** [comment]
See doc [Joins Perloading](https://gorm.io/docs/preload.html#Joins-Preloading)

> **NOTE** Join Preload works with one-to-one relation, e.g: has one, belongs to

So you may need to join manually

**Comment by YuZongYangHi** [comment]
> See doc [Joins Perloading](https://gorm.io/docs/preload.html#Joins-Preloading)
> 
> > **NOTE** Join Preload works with one-to-one relation, e.g: has one, belongs to
> 
> So you may need to join manually

For my current situation, can the problem be solved only by using native left sql in Joins?

**Comment by YuZongYangHi** [comment]
@a631807682  @black-06

I have gone through a lot of issues. This kind of problem has been there since 2 years ago, but I haven’t gotten an answer. If the many2many query can’t use __ to split like beego, but use the original inner, then I think it will be very complicated.

**Comment by YuZongYangHi** [comment]
> 
query a lot of issues, many people have the same problem as me.

**Comment by a631807682** [comment]
> > > See doc [Joins Perloading](https://gorm.io/docs/preload.html#Joins-Preloading)
> > > > **NOTE** Join Preload works with one-to-one relation, e.g: has one, belongs to
> > > 
> > > 
> > > So you may need to join manually
> > 
> > 
> > For my current situation, can the problem be solved only by using native left sql in Joins?
> 
> I am not sure. Cc @a631807682

> NOTE Join Preload works with one-to-one relation, e.g: has one, belongs to

This sentence is ambiguous, we just won't integrate multiple (seemingly identical) records into one record, we should still allow users to use join in many-to-many situations.

The error stems from the many-to-many relationship not being declared explicitly, so it should be treated specially.
https://github.com/go-gorm/gorm/blob/master/callbacks/query.go#L132
https://github.com/go-gorm/gorm/blob/master/callbacks/query.go#L149

**Comment by a631807682** [comment]
Sorry, the above comment is problematic, in fact, we cannot use many-to-many relationship in join because of the inability to aggregate multiple records into one.
It's not that queries can't be generated, it's that they can't receive.
refer to https://github.com/go-gorm/gorm/issues/5280#issuecomment-1514225741

@YuZongYangHi  You said beego can do it, can you provide a link? Documentation or example links are fine

**Comment by YuZongYangHi** [comment]
> Sorry, the above comment is problematic, in fact, we cannot use many-to-many relationship in join because of the inability to aggregate multiple records into one. It's not that queries can't be generated, it's that they can't receive. refer to [#5280 (comment)](https://github.com/go-gorm/gorm/issues/5280#issuecomment-1514225741)
> 
> @YuZongYangHi You said beego can do it, can you provide a link? Documentation or example links are fine

beego orm many2many example
```
type RoleBinding struct {
	ID      int64      `orm:"pk;auto; column(id)" json:"id"`
	Groups  []*Group   `orm:"rel(m2m);rel_table(ks_rbac_role_binding_groups)" json:"groups"`

type Group struct {
	Id          int64     `orm:"pk;auto; column(id)" json:"id"`
	Name        string    `json:"name"`

var rb RoleBinding
err := Orm().QueryTable(TableNameRoleBinding).
Filter("groups__ks_group_id", group.Id). # cross-table query
One(&rb)
```
@a631807682

**Comment by YuZongYangHi** [comment]
@a631807682 
If I want to query data through many2many, is there a recommended query method?
Is it only possible to use Joins("inner xxx")?

**Comment by a631807682** [comment]
> @a631807682 If I want to query data through many2many, is there a recommended query method? Is it only possible to use Joins("inner xxx")?

I'd look into beego's implementation, usually the Preload api is recommended for many-to-many relationships

**Comment by a631807682** [comment]
> > Sorry, the above comment is problematic, in fact, we cannot use many-to-many relationship in join because of the inability to aggregate multiple records into one. It's not that queries can't be generated, it's that they can't receive. refer to [#5280 (comment)](https://github.com/go-gorm/gorm/issues/5280#issuecomment-1514225741)
> > @YuZongYangHi You said beego can do it, can you provide a link? Documentation or example links are fine
> 
> beego orm many2many example
> 
> ```
> type RoleBinding struct {
> 	ID      int64      `orm:"pk;auto; column(id)" json:"id"`
> 	Groups  []*Group   `orm:"rel(m2m);rel_table(ks_rbac_role_binding_groups)" json:"groups"`
> 
> type Group struct {
> 	Id          int64     `orm:"pk;auto; column(id)" json:"id"`
> 	Name        string    `json:"name"`
> 
> # center table ks_rbac_role_binding_groups
> ks_rbac_role_binding_id 
> ks_group_id 
> 
> # query 
> var rb RoleBinding
> err := Orm().QueryTable(TableNameRoleBinding).
> Filter("groups__ks_group_id", group.Id). # cross-table query
> One(&rb)
> ```
> 
> @a631807682

I tried this code, it returns
``` log
table `role_binding` already exists, skip
table `group` already exists, skip
table `ks_rbac_role_binding_groups` already exists, skip
panic: unknown field/column name `groups__ks_group_id`
```
Am I missing something? Or can you provide a link to an executable code repository?

**Comment by YuZongYangHi** [comment]
> > > Sorry, the above comment is problematic, in fact, we cannot use many-to-many relationship in join because of the inability to aggregate multiple records into one. It's not that queries can't be generated, it's that they can't receive. refer to [#5280 (comment)](https://github.com/go-gorm/gorm/issues/5280#issuecomment-1514225741)
> > > @YuZongYangHi You said beego can do it, can you provide a link? Documentation or example links are fine
> > 
> > 
> > beego orm many2many example
> > ```
> > type RoleBinding struct {
> > 	ID      int64      `orm:"pk;auto; column(id)" json:"id"`
> > 	Groups  []*Group   `orm:"rel(m2m);rel_table(ks_rbac_role_binding_groups)" json:"groups"`
> > 
> > type Group struct {
> > 	Id          int64     `orm:"pk;auto; column(id)" json:"id"`
> > 	Name        string    `json:"name"`
> > 
> > # center table ks_rbac_role_binding_groups
> > ks_rbac_role_binding_id 
> > ks_group_id 
> > 
> > # query 
> > var rb RoleBinding
> > err := Orm().QueryTable(TableNameRoleBinding).
> > Filter("groups__ks_group_id", group.Id). # cross-table query
> > One(&rb)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @a631807682
> 
> I tried this code, it returns
> 
> ```
> table `role_binding` already exists, skip
> table `group` already exists, skip
> table `ks_rbac_role_binding_groups` already exists, skip
> panic: unknown field/column name `groups__ks_group_id`
> ```
> 
> Am I missing something? Or can you provide a link to an executable code repository?

Wait a mininute

**Comment by YuZongYangHi** [comment]
> 

see: [my blog example](https://igolang.cn/category/Golang/article/26)

**Comment by YuZongYangHi** [comment]
> > @a631807682 If I want to query data through many2many, is there a recommended query method? Is it only possible to use Joins("inner xxx")?
> 
> I'd look into beego's implementation, usually the Preload api is recommended for many-to-many relationships

This preload method only means that the data of other tables is filtered, and the main table still cannot be filtered, which does not meet our usual needs for inner join....

**Comment by a631807682** [comment]
> > 
> 
> @a631807682 see: [my blog example](https://igolang.cn/category/Golang/article/26)

Your example means that you only need to match certain conditions through the intermediate table, instead of querying the data of RoleBinding.Users or RoleBinding.Groups through join while querying RoleBinding?

**Comment by YuZongYangHi** [comment]
> > > 
> > 
> > 
> > @a631807682 see: [my blog example](https://igolang.cn/category/Golang/article/26)
> 
> Your example means that you only need to match certain conditions through the intermediate table, instead of querying the data of RoleBinding.Users or RoleBinding.Groups through join while querying RoleBinding?

@a631807682  That's how it's related
```
var result []models.RoleBinding
_, err := models.Orm().QueryTable("role_binding").
    Filter("Users__user_id", 1).
    Filter("Groups__group_id", 1).
    All(&result)

if err == nil {
    for _, r := range result {
	models.Orm().LoadRelated(&r, "Groups")
	models.Orm().LoadRelated(&r, "Users")
    }
}
```

**Comment by YuZongYangHi** [comment]
> > > > 
> > > 
> > > 
> > > @a631807682 see: [my blog example](https://igolang.cn/category/Golang/article/26)
> > 
> > 
> > Your example means that you only need to match certain conditions through the intermediate table, instead of querying the data of RoleBinding.Users or RoleBinding.Groups through join while querying RoleBinding?
> 
> @a631807682 That's how it's related,  The query of beego is a table query, and the bottom layer is join, but the preload of gorm should not meet this situation.
> 
> ```
> var result []models.RoleBinding
> _, err := models.Orm().QueryTable("role_binding").
>     Filter("Users__user_id", 1).
>     Filter("Groups__group_id", 1).
>     All(&result)
> 
> if err == nil {
>     for _, r := range result {
> 	models.Orm().LoadRelated(&r, "Groups")
> 	models.Orm().LoadRelated(&r, "Users")
>     }
> }
> ```

**Comment by a631807682** [comment]
gorm does not have a Filter api to handle conditions in relationships (the Where api does not handle association relationships).

The Joins api does not process many-to-many relationships, it is used to query data, the specified join table data needs to be accepted (beego Filter does not accept the specified join table data, it needs to use LoadRelated, Similar to https://gorm.io/docs/associations.html#Find-Associations).

The Preload/Association api allows you to specify query criteria, but only for the specified table, you can filter for User or Group, but you still cannot join multiple tables as filter criteria like the Filter api.

The current api is not suitable for such a scenario, and such a scenario is not suitable for the above api, the current possible approach is to use a lower dimension clause api encapsulation.

**Comment by YuZongYangHi** [comment]
> gorm does not have a Filter api to handle conditions in relationships (the Where api does not handle association relationships).
> 
> The Joins api does not process many-to-many relationships, it is used to query data, the specified join table data needs to be accepted (beego Filter does not accept the specified join table data, it needs to use LoadRelated, Similar to https://gorm.io/docs/associations.html#Find-Associations).
> 
> The Preload/Association api allows you to specify query criteria, but only for the specified table, you can filter for User or Group, but you still cannot join multiple tables as filter criteria like the Filter api.
> 
> The current api is not suitable for such a scenario, and such a scenario is not suitable for the above api, the current possible approach is to use a lower dimension clause api encapsulation.

can you give an example of gorm based on my above example, thank you very much

**Comment by a631807682** [comment]
I don't have enough time at the moment, I will add an example (or a detailed description of the implementation process) to the comments later, maybe next week, you can also refer to  https://github.com/go-gorm/gorm/blob/master/association.go#L558 .

**Comment by YuZongYangHi** [comment]
> https://github.com/go- gorm/gorm/blob/master/association.go#L558

looking forward to your reply

**Comment by ankit16-19** [comment]
@YuZongYangHi did you find any way to implement this in gorm?

@a631807682 can you please give some example.
