### ISSUE TITLE
Gorm how to set field allowing to be null in model definition?

### ISSUE THREAD

**Issue by dablelv** [go-gorm/gorm#6422]
In model definition, I set a field not allowed to be null before. 

```go
type Dataset struct {
    MD5         string                  `gorm:"type:string;size:32;not null"`
}
```

But now I want to set field allowing to be null in the model definition.

I do as follow but it doesn't work.
```go
type Dataset struct {
    MD5         string                  `gorm:"type:string;size:32;null"`
}

// or
type Dataset struct {
    MD5         string                  `gorm:"type:string;size:32"`
}
```
So how to remove the not null property? thx.

**Comment by yousifnimah** [comment]
You can use ```sql.NullString``` as a field type. it accepts nil or string

1- Import "database/sql"
2- Change the type to sql.NullString 

Example:

```
 type Dataset struct {
    MD5    sql.NullString   `gorm:"type:string;size:32;null"`
}
```

and for NullInteger : 

```
  type Dataset struct {
    MD5    sql.NullInt32   `gorm:"type:string;size:32;null"`
}
```
