### ISSUE TITLE
Unable to preload many2many entities when id=0

### ISSUE THREAD

**Issue by MattKetmo** [go-gorm/gorm#6423]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/623 (tested with `GORM_DIALECT=postgres`)

## Explain your user case and expected results

Here is a many2many table relationship between 2 entities `foo` & `bar`:

| foo_id | bar_id |
|--------|--------|
| 0 | 0 |
| 0 | 1 |
| 1 | 0 | 
| 1 | 1 |
| 1 | 2 |

When I fetch the `Foo` entity & Preload all its `Bar`, the relationship is broken when `foo_id=0` or `bar_id=0`

expected:
- foo 0 has 2 bars
- foo 1 has 3 bars

actual result:
- foo 0 has 0 bar
- foo 1 has 2 bars

```
--- FAIL: TestGORM (0.02s)
    main_test.go:36: Failed for FooID=0, expected 2 bars, but got 0
    main_test.go:36: Failed for FooID=1, expected 3 bars, but got 2
```

**Comment by MattKetmo** [comment]
Note that using something else than a int or uint (which default value is not 0) can be a work around (waiting for proper fix)

For instance a [decimal.Decimal](https://github.com/shopspring/decimal) or even a pointer `*int` / `*uint`

**Comment by saeidee** [comment]
Zero is not a common ID that should be used as a foreign key, it often denotes an empty field / NULL value.

**Comment by MattKetmo** [comment]
Yes I know 0 is not a "common" ID but in my case this is the reference of an item outside my app so it makes sense I import as is. To denote an empty value I would have used a NULLable column, which is not the case here.

Joining using 0 as id is not a db issue, only an gorm issue. 

For now I got around it using a `decimal.Decimal` instead of uint.

**Comment by MattKetmo** [comment]
ok so no proper fix possible except using a workaround by not using integers?

**Comment by saeidee** [comment]
> Yes I know 0 is not a "common" ID but in my case this is the reference of an item outside my app so it makes sense I import as is.

This is specific to your application's business logic, however, feel free to have open a fix PR.
