### ISSUE TITLE
Documentation: Create From Map is incorrect

### ISSUE THREAD

**Issue by jessdwitch** [go-gorm/gorm#6427]
## Your Question

The **NOTE** at the bottom of [Create From Map](https://gorm.io/docs/create.html#Create-From-Map) is incorrect. The code provided *will* attempt to backfill primary keys. To prevent backfilling, a map has to be used as input *and* `Table` has to be used instead of `Model`.

## The document you expected this should be explained

[Create From Map](https://gorm.io/docs/create.html#Create-From-Map)

## Expected answer

The documentation should be updated.

**Comment by black-06** [comment]
Thanks for your feedback, but in fact, it didn't backfill, see https://github.com/go-gorm/playground/pull/624.
