### ISSUE TITLE
GORM may not respond for a long time after a certain period of time ,GORM隔一段时间后，就会长时间不响应 

### ISSUE THREAD

**Issue by aohanhongzhi** [go-gorm/gorm#6432]
## Your Question

GORM隔一段时间后，就会长时间不响应

GORM may not respond for a long time after a certain period of time

## The document you expected this should be explained

前端取消请求后

After the front-end cancels the request

![image](https://github.com/go-gorm/gorm/assets/37319319/f08b0661-7316-4632-bac6-c92e501cbd85)

后端的数据库查询直接cancel了

The backend database query was directly cancelled

![image](https://github.com/go-gorm/gorm/assets/37319319/d6dad467-2546-494e-8b7b-38cd91e9be24)

查看数据库的连接正常

Check if the connection to the database is normal

![image](https://github.com/go-gorm/gorm/assets/37319319/4ebfd8a9-0594-41b4-8be8-16bd782842db)

## Expected answer

gorm正常查询数据库

Gorm queries the database normally

**Comment by black-06** [comment]
> Check if the connection to the database is normal

Excuse me, how do you check the db connection?

**Comment by aohanhongzhi** [comment]
> > Check if the connection to the database is normal
> 
> Excuse me, how do you check the db connection?

I dont know, but I found the problem is cause by redis ,not grom
