### ISSUE TITLE
give a choice tag use

### ISSUE THREAD

**Issue by blight19** [go-gorm/gorm#6433]
## Describe the feature
this feature comes from the django orm,when i want made a model that have col  of several choices,i want give a uint8 ,it will hard in gorm.
i wonder if it is possible to give a gorm tag to do this.
```golang
type User struct{
   ...
   Sex string  `gorm:"type:int;choice:male,femle,unknown" `
}
```

## Motivation
in many projects ,even though we have one to many or many to one relations,but often, we don't want the choices become a table in databases, because it only have less to 5 choices.   
and this will be useful.

**Comment by black-06** [comment]
You mean, you want to store a small number of enums in uint8 / tinyint?

**Comment by jinzhu** [comment]
GORM won't include data validator, checkout https://github.com/qor/validations for how to create one by yourself.

**Comment by blight19** [comment]
> You mean, you want to store a small number of enums in uint8 / tinyint?
in database backend,it can be a intger,and in golang,it reflect to a string.i think it will save space and improve proformance

**Comment by blight19** [comment]
> You mean, you want to store a small number of enums in uint8 / tinyint?
yes,the data will store in db as int,and when use in golang ,it reflect to string,i think it is very useful to save storage and improve proformance.

**Comment by black-06** [comment]
> > You mean, you want to store a small number of enums in uint8 / tinyint?
>
> yes,the data will store in db as int,and when use in golang ,it reflect to string,i think it is very useful to save storage and improve proformance.

This should not be part of ORM. What you need is probably a golang enum.
For example:
```go
type BodyPart int

const (
    Head BodyPart = iota // Head = 0
    Shoulder             // Shoulder = 1
    Knee                 // Knee = 2
    Toe                  // Toe = 3
)

func (bp BodyPart) String() string {
    return []string{"Head", "Shoulder", "Knee", "Toe"}[bp]
}
```

**Comment by mahesh-riddles** [comment]
> > > You mean, you want to store a small number of enums in uint8 / tinyint?
> > 
> > 
> > yes,the data will store in db as int,and when use in golang ,it reflect to string,i think it is very useful to save storage and improve proformance.
> 
> This should not be part of ORM. What you need is probably a golang enum. For example:
> 
> ```go
> type BodyPart int
> 
> const (
>     Head BodyPart = iota // Head = 0
>     Shoulder             // Shoulder = 1
>     Knee                 // Knee = 2
>     Toe                  // Toe = 3
> )
> 
> func (bp BodyPart) String() string {
>     return []string{"Head", "Shoulder", "Knee", "Toe"}[bp]
> }
> ```

I tried this.. 
Why those fields, which I wanted to be int are now big int?
