### ISSUE TITLE
Duplicated key test introduced in #6389 fails if key already exists

### ISSUE THREAD

**Issue by ncruces** [go-gorm/gorm#6435]
## Description

The test introduced in #6389 fails if the key already exists.

For instance, this fails for SQLite on a *second run* if the database is not deleted.

Failure:
https://github.com/go-gorm/gorm/blob/206613868439c5ee7e62e116a46503eddf55a548/tests/error_translator_test.go#L53

Database created here, survives over multiple runs:
https://github.com/go-gorm/gorm/blob/206613868439c5ee7e62e116a46503eddf55a548/tests/tests_test.go#L92

It passes in CI because `os.TempDir` is reset between runs.

**Comment by ncruces** [comment]
Steps to reproduce:

```sh
git clone https://github.com/go-gorm/gorm.git
cd gorm/tests
echo "update SQLite driver to support error translation"
go get -u gorm.io/driver/sqlite
go mod tidy
echo "delete the temp db"
rm $TMPDIR/gorm.db
echo "first run passes, count=1 avoids caching"
go test . -count=1
echo "second run fails, count=1 avoids caching"
go test . -count=1
```

**Comment by saeidee** [comment]
Thanks for pointing it out @ncruces, this PR has the fixes the https://github.com/go-gorm/gorm/pull/6403.
