### ISSUE TITLE
How return RowsAffectred for delete `Association`?

### ISSUE THREAD

**Issue by alexpts** [go-gorm/gorm#6450]
## Your Question
How return `rowsAffected` for `Association`?

I have 6 record in many2many table.
I remove many2many connection via code
```
db.Model(m).Association("Rel").Delete([]models)
```

Actual:
db.RowsAffected is 0

I see correct SQL:
`DELETE FROM 'many2many_table` WHERE (some condition)` 

## The document you expected this should be explained
Expected:
db.RowsAffected is 6

How I can count deleted rows from many2many tables? Do you can show example for this case, which return  `RowsAffected` for removed `Association`?

**Comment by saeidee** [comment]
You may use hooks.

**Comment by rrab-0** [comment]
Can you provide me an example please
