### ISSUE TITLE
Option to ignore write permissions of model fields?

### ISSUE THREAD

**Issue by cmdv3** [go-gorm/gorm#6451]
## Your Question
It is possible to ignore write permission of model fields ? Already exists .Omit() that ignores specific columns when updating. 
But is there any option to ignore write permissions of field?

I mean ignore write ignore flags (or tags).
```go
struct {
    Name string `gorm:"<-:false"`
}
```

## The document you expected this should be explained
I expect it at this page: [Documentation](https://gorm.io/docs/models.html#Fields-Tags)

## Expected answer

Of course it is possible. (Similiar as .Omit() method) or something like that.

**Comment by saeidee** [comment]
If you want to ignore write permission then why do you strict it by default? You may not strict it by default and manage the write permission on your application level (you may check hooks).
