### ISSUE TITLE
`gorm:primaryKey` ignores the structure field type and set only int8

### ISSUE THREAD

**Issue by AlexKenbo** [go-gorm/gorm#6456]
## Description

```go
type Account struct {
	AccountID    uint `gorm:"primaryKey"`
	CurrencyCode string
	// .. other fields

	CurrencyRef    Currency       `gorm:"foreignKey:CurrencyCode"`
}

type Currency struct {
	CurrencyCode string `gorm:"primaryKey"`
	CurrencyType string
}
```

### The table Currencies is created in the database with PK - "int8", structure type "string" is ignored:

<img width="671" alt="image" src="https://github.com/go-gorm/gorm/assets/14903011/7129a499-be66-439c-8090-1c8a9bb4ee60">
<img width="551" alt="image" src="https://github.com/go-gorm/gorm/assets/14903011/e83ed6ea-11aa-4fe6-86e0-43e223274fb3">

**Comment by saeidee** [comment]
This is not reproducible, please try to reproduce it with a PR here https://github.com/go-gorm/playground.
<img width="585" alt="image" src="https://github.com/go-gorm/gorm/assets/29974712/f2efc971-55cd-4e59-8480-08b429f1d038">
