### ISSUE TITLE
can we make an error code like ErrRecordNotFound not arrays as well. 

### ISSUE THREAD

**Issue by anishjain94** [go-gorm/gorm#6459]
## Describe the feature
Just like ErrRecordNotFound works for "First" queries, can we make it work for "Find" queries as well. 

## Motivation

Had to write separate logic to handle "Find" queries element not found. so I was thinking that we can do something similar for arrays as well.

**Comment by saeidee** [comment]
You can enable the _RaiseErrorOnNotFound_ flag before query:

```go
db.Statement.RaiseErrorOnNotFound = true
err := db.Where("name = ?", "foobar").Find(&r).Error // err will be ErrRecordNotFound
```
