### ISSUE TITLE
How to declare foreign key and references for child if it has the same field as the parent does

### ISSUE THREAD

**Issue by ronannnn** [go-gorm/gorm#6463]
## Your Question
https://github.com/go-gorm/playground/pull/628
```
type MyModel struct {
	Id        uint `gorm:"primaryKey"`
	CreatedBy uint
}

type User struct {
	MyModel
	Name string
}

type Store struct {
	MyModel
	Name     string
	Products []Product `gorm:"foreignKey:StoreId"`
}

type Product struct {
	MyModel
	StoreId uint
	Name    string
	OwnerId uint
	// Owner   User `gorm:"foreignKey:OwnerId;references:Id"` // this works
	Owner User `gorm:"foreignKey:CreatedBy;references:Id"` // this does't work, CreatedBy here should belong to Product, not User
}
```

## The document you expected this should be explained
https://gorm.io/docs/belongs_to.html

## Expected answer
According to the doc, `User` and `Product` have the same key `CreatedBy`, so `references` should be used. But it fails in my case. I'm wondering whether `foreign key` and `references` can be used together. Thank you in advanced!

**Comment by jinzhu** [comment]
It doesn't work with the same field names, you have to use a different one for foreign keys.

btw, you can use `gorm:"column:xxx"` to rename a field's column name.
