### ISSUE TITLE
Support special charactors in column name

### ISSUE THREAD

**Issue by BigBunnie** [go-gorm/gorm#6465]
Hi Team,
Need special character support in column name conversion, Like there would be new flag SkipConversionRule. Which disable the general conversion rules and simple make gorm:"column:ac/no. old" to exact column name  "ac/no. old" instead of separating it to "ac/no"."" 

This feature will resolve the Ms sql column name issues. Some time special character comes in column name as DB  also support.

none.

**Comment by jinzhu** [comment]
Maybe you can overwrite the default `NamingStrategy`
