### ISSUE TITLE
为什么golang作为一种静态语言，但是它的类库基本上实现的风格都是动态语言那套，写个字段都要拼接字符串

### ISSUE THREAD

**Issue by ideaviewes** [go-gorm/gorm#6473]
为什么golang作为一种静态语言，但是它的类库基本上实现的风格都是动态语言那套，写个字段都要拼接字符串
难道不应该是这样的吗？
![image](https://github.com/go-gorm/gorm/assets/5431843/d1c3de87-f13f-4e47-bf58-bd5645b9a120)
怎么都是这种风格
![image](https://github.com/go-gorm/gorm/assets/5431843/9b027b1d-afc3-478b-a81d-94cbb9303f66)
这样完全失去了静态语言类型提示的优点

**Comment by jinzhu** [comment]
try gorm.io/gen/index
