### ISSUE TITLE
模拟数据库稳定性需求

### ISSUE THREAD

**Issue by imiskolee** [go-gorm/gorm#6474]
Hi，Team:

目前我们在考虑如何模拟gorm的稳定性问题，用以针对应用的代码逻辑的测试。我们假设了如下的方式：

```
db := gorm.Open(...)
db = db.SetErrorFactor(0.3) //30%几率返回固定错误  gorm.ErrorDirectlyFailed
```

或者是否有其他的方案可以实现

**Comment by jinzhu** [comment]
Write a plugin and overwrite DB's `ConnPool` and return errors randomly.
