### ISSUE TITLE
How to preload in many to many with the condition 

### ISSUE THREAD

**Issue by mostafa-binesh** [go-gorm/gorm#6479]
## Your Question
let me explain the problem with an example
i have user and course in many to many relationship. every user can buy many courses and a course can belong to many users
every bought course has a expiration date on many to many relationship
```go
type User struct {
	...
	Courses     []*Course     `gorm:"many2many:course_user;"`
}
type Course struct {
	...
	Users              []*User    `json:"-" gorm:"many2many:course_user;"`
}
type CourseUser struct {
	// the gorm:foreignKey just creates a relationship between tables and works just fine
	UserID         int `gorm:"foreignKey:ID"`
	CourseID       int `gorm:"foreignKey:ID"`
	ExpirationDate time.Time
}
```
it works in preload like this:
```go
D.DB().Model(&user).
		Preload("Courses").
		Find(&user)
```
and returns the user with all of bought courses
but when i want to preload only courses that their expiration_date is > now i like this i get error:
```go
D.DB().Model(&user).
		Preload("Courses", "expiration_date > ?", time.Now()).
		Find(&user)
```
error:
```sql
ERROR: column "expiration_date" does not exist (SQLSTATE 42703)
SELECT * FROM "courses" WHERE "courses"."id" = 69 AND expiration_date > '2023-07-23 23:59:41.564'
```
## Expected answer
preload all user's courses with many to many expiration_date > now with sql like this
```sql
SELECT * FROM "course_user" WHERE "course_user"."user_id" = 9 AND expiration_date > '2023-07-23 23:59:41.564'
```

**Comment by saeidee** [comment]
You have to use join and perload together.

**Comment by mostafa-binesh** [comment]
> You can use join and perload together.

Can you give me the code based on my example

**Comment by shanel262** [comment]
@mostafa-binesh Did you ever find an answer to this? It still isn't properly documented and I've been searching for a solution all morning

**Comment by tomassommareqt** [comment]
@mostafa-binesh same here.

**Comment by michalko** [comment]
you'd have to do something like:

```
.Preload("Courses", func(db *gorm.DB) *gorm.DB {
		return db.Joins("INNER JOIN course_user ON course_user.user_id = user.id").
			Where("course_user.expiration_date > '2023-07-23 23:59:41.564'").
			Table("courses")
	})
```

**Comment by fari-99** [comment]
@mostafa-binesh so it didn't use preload at all? but you collect the course id first, then on preload you put that on the conditions preload? seems strange to me, why we cant add conditions to preload many2many for that join table.
