### ISSUE TITLE
Why does open PrepareStmt perform Prepare in advance

### ISSUE THREAD

**Issue by demoManito** [go-gorm/gorm#6493]
## Your Question

<img width="919" alt="image" src="https://github.com/go-gorm/gorm/assets/27986239/b2f0d255-34cd-4b55-8f52-22c6dbddde24">

```go
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		PrepareStmt: true,
	})
```

gorm 开启 PrepareStmt，会在执行之前多执行一次 Prepare？想问下多执行一次 Prepare 和在 Execute 之前执行的 Prepare 有什么区别，这么做的目的是什么

**Comment by demoManito** [comment]
@jinzhu @a631807682

**Comment by a631807682** [comment]
PrepareStmt is to support https://pkg.go.dev/database/sql#Conn.PrepareContext
But the driver may implement prepare at the time of query, which may cause duplication.

**Comment by demoManito** [comment]
> PrepareStmt is to support [pkg.go.dev/database/sql#Conn.PrepareContext](https://pkg.go.dev/database/sql#Conn.PrepareContext) But the driver may implement prepare at the time of query, which may cause duplication.

明白了，感谢大佬
