### ISSUE TITLE
The primary key field will be automatically appended

### ISSUE THREAD

**Issue by tinnkai** [go-gorm/gorm#6515]
## Description
When the field is a primary key but not self increasing, using create will automatically append the primary key field, resulting in a statement error

## Screenshot
![image](https://github.com/go-gorm/gorm/assets/2200272/8006f71d-1ca1-4589-87d0-7780bb48cbd5)
![image](https://github.com/go-gorm/gorm/assets/2200272/e643d895-1ecd-4dc5-8c27-e8cd61b33bbc)
![image](https://github.com/go-gorm/gorm/assets/2200272/6f49e808-d61e-47b2-bee2-0fff569727ec)

**Comment by tcrold** [comment]
let GORM know this is not an auto increment property

**Comment by tinnkai** [comment]
> let GORM know this is not an auto increment property
I clearly informed him that it is a primary key, not a self increasing primary key, but he did not consider whether the primary key is self increasing
