### ISSUE TITLE
How create mysql8 Multi-Valued Indexes in gorm?

### ISSUE THREAD

**Issue by yimingsir** [go-gorm/gorm#6526]
## Your Question
``` sql
CREATE TABLE customers (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    custinfo JSON,
    INDEX zips( (CAST(custinfo->'$.zipcode' AS UNSIGNED ARRAY)) )
    )
```
https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-multi-valued

how  i can create mysql8 Multi-Valued Indexes in gorm?

**Comment by keyvangholami** [comment]
Creating MySQL 8 Multi-Valued Indexes is a specific feature that not be directly supported by GORM. However, you can still achieve this by using raw SQL queries in GORM.
