### ISSUE TITLE
日志中的sql和实际执行的不一致

### ISSUE THREAD

**Issue by scrawld** [go-gorm/gorm#6533]
## GORM Playground Link

https://github.com/go-gorm/gorm/tree/v1.25.3

## Description

表结构
```
CREATE TABLE `user1` (
  `uid` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `create_date` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `num` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`,`create_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;
```

伪造数据
```INSERT INTO `test`.`user1` (`uid`, `create_date`, `num`) VALUES ('zzz', '2023-08-18', 1);```

查询
```
m := map[string]interface{}{}
db.Table("user1").Where("create_date=?", time.Unix(1692288000, 0)).Take(&m)
fmt.Println(m)
```

日志中打印出来的sql
```
[0.332ms] [rows:1] SELECT * FROM `user1` WHERE create_date='2023-08-18 00:00:00' LIMIT 1
```

实际执行的sql
```SELECT * FROM `user1` WHERE create_date='2023-08-18' LIMIT 1```

**Comment by LYQlemon** [comment]
I think you can solve your problem by adding .Format("2006-04-02") after the time.Unix method
