### ISSUE TITLE
go build fail UnsafePointer

### ISSUE THREAD

**Issue by maranqz** [go-gorm/gorm#6546]
### Discussed in https://github.com/go-gorm/gorm/discussions/6538

<div type='discussions-op-text'>

<sup>Originally posted by **SunnyDate** August 22, 2023</sup>
go version
go version go1.17 linux/amd64

go build
# gorm.io/gorm
./gorm.go:382:64: reflect.ValueOf(tx).Elem().FieldByName("db").UnsafePointer undefined (type reflect.Value has no field or method UnsafePointer)</div>

UnsafePointer was added in go 1.18. https://pkg.go.dev/reflect@go1.18.10#Value.UnsafePointer

In go 1.16 and 1.17, there is not UnsafePointer. https://pkg.go.dev/reflect@go1.16.15#Value.UnsafePointer

Problem was happened after https://github.com/go-gorm/gorm/pull/6535

To reproduce, run `go build` gorm v1.25.4 in go version 1.16 or 1.17.

@qqxhb, could you fix it or bump up go version in go.mod?

fyi @jinzhu

**Comment by alwaysbana** [comment]
Did you solve the problem
