### ISSUE TITLE
gorm.io/gorm v1.25.4 在Go1.17环境中不可用

### ISSUE THREAD

**Issue by caoyanyan37** [go-gorm/gorm#6551]
```
package main

import (
	gorm.io/driver/mysql v1.5.1
	gorm.io/gorm v1.25.4
)
	dsn := "root:root@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	fmt.Println(db, err)
```
在go1.17.7 windows/amd64环境下运行报错
reflect.ValueOf(tx).Elem().FieldByName("db").UnsafePointer unde...
只有降低gorm版本才可用
以下是当前运行环境下可以使用的gorm版本
    gorm.io/driver/mysql v1.3.5
    gorm.io/gorm v1.23.8

**Comment by jinzhu** [comment]
Yes, v1.25.4 requires >= 1.18, and not going to support old versions.
