### ISSUE TITLE
how to update one more column when I use the soft-delete method

### ISSUE THREAD

**Issue by jianjianxu** [go-gorm/gorm#6558]
## Your Question

Useing the soft delete, gorm can only update one column like deleted_at or flag.

But now, I alse need to update the deleted_by column. I want to record the user who operated this.

How can I do this?

Thank you.

**Comment by jianjianxu** [comment]
意思就是gorm执行软删除的时候，执行的是update set deleted_at=当前时间。

有没有什么方法，让调用delete操作的时候，最终执行的是

update set deleted_at=当前时间 and deleted_by=操作人id。

**Comment by xuxing421** [comment]
Actually gorm soft delete is update operation, how about creating a function like this

func DeleteWithOperator(db *gorm.DB, operator string) *gorm.DB {
	return db.
		Update("deleted_at,", time.Now().Format("2006-01-02 15:04:05")).
		Update("operator", operator)
}

Then you can use Scope call the function
err := db.Where("id = ?  ", teacherId).Scopes(DeleteWithOperator).Error

**Comment by a631807682** [comment]
You can achieve this through custom types

https://github.com/go-gorm/gorm/blob/master/soft_delete.go

**Comment by Dan6erbond** [comment]
@a631807682 it would be great to get a more complete example of how to create a `DeletedBy` custom type because looking at `soft_delete.go` this is what I have:

```go
type DeletedBy uuid.UUID

func (DeletedBy) DeleteClauses(f *schema.Field) []clause.Interface {
	return []clause.Interface{DeletedByDeleteClause{Field: f}}
}

type DeletedByDeleteClause struct {
	Field *schema.Field
}

func (db DeletedByDeleteClause) Name() string {
	return ""
}

func (db DeletedByDeleteClause) Build(clause.Builder) {}

func (db DeletedByDeleteClause) MergeClause(*clause.Clause) {}

func (db DeletedByDeleteClause) ModifyStatement(stmt *gorm.Statement) {
	//nolint:nestif
	if !stmt.Statement.Unscoped {
		if userID := authctx.UserIDFromContext(stmt.Context); userID != nil {
			stmt.AddClause(clause.Set{{Column: clause.Column{Name: db.Field.DBName}, Value: userID}})
			stmt.SetColumn(db.Field.DBName, userID, true)

			stmt.AddClauseIfNotExists(clause.Update{})
			stmt.Build(stmt.DB.Callback().Update().Clauses...)
		}
	}
}
```

And unfortunately this generates incorrect SQL:

```sql
UPDATE "leads"
SET "deleted_at" = '2025-07-08 08:21:11.09'
WHERE "leads"."id" = '34b6d371-3439-4c63-bb18-ed250dfa2bc2'
  AND "leads"."deleted_at" IS NULLUPDATE "leads"
SET "deleted_by_id" = '2ba973f9-b178-4e68-b1f6-314db8f0930b'
WHERE "leads"."id" = '34b6d371-3439-4c63-bb18-ed250dfa2bc2'
  AND "leads"."deleted_at" IS NULL
```
