### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by xu-mengnan** [go-gorm/gorm#6576]
I want to query database data to the map [string] interface {}. The total amount of data is approximately 170w, with a total data size of 800M. However, during the query process, the memory may increase to 16GB, for unknown reasons.

sql：
```
	var dataMapTmp []map[string]interface{}
	err := mysql.Db.Table(m.TableName()).Offset(i).Limit(step).Find(&dataMapTmp).Error
```

pprof:

<img width="821" alt="图片" src="https://github.com/go-gorm/gorm/assets/36294047/e3f00552-76e7-4e0f-b364-4b09db40e930">

**Comment by voodoo-dn** [comment]
@xu-mengnan Hi. What is your version of Gorm?

Today I've experienced OOM Kill by Kubernetes during load on DB, usually it's "read" load to replica. Think maybe this is the same issue.

Because usually container uses ~36mb, but killed after reaching 512mb.

**Comment by xu-mengnan** [comment]
> @xu-mengnan Hi. What is your version of Gorm?
> 
> Today I've experienced OOM Kill by Kubernetes during load on DB, usually it's "read" load to replica. Think maybe this is the same issue.
> 
> Because usually container uses ~36mb, but killed after reaching 512mb.

My import version is the following content:
- gorm.io/driver/mysql v1.4.7
- gorm.io/gorm v1.24.6

**Comment by atghw** [comment]
Had a similar issue with the following:

```
    type Settings struct {
	Instance      string `json:"instance" gorm:"primaryKey"`
	ExtId uint   `json:"ext_id" gorm:"primaryKey"`
        ... somesthing ..
    }
    
    var settings []Settings

    db := GetDB()
    for _, info := range infos {
	db = db.Or(
		db.Where("ext_id = ?", info.ExtId).Where("instance = ?", info.Instance),
	)
    }
    result := db.Find(&campaignSettings) // <--- Problem
```
    
Problem: The call to `db.Find()` didn't returned and memory allocation of the process increased to endless.

I tried to rewrite the query and used `db.Rows() `with the same condition, but it failed too. I ended up in a loop to fetch them one-by-one. My import versions:

- 	gorm.io/driver/mysql v1.5.7
- 	gorm.io/gorm v1.25.11

I cross-compiled on macOS for linux/amd64.
