### ISSUE TITLE
Custom error message on validation

### ISSUE THREAD

**Issue by stevenwr92** [go-gorm/gorm#6595]
Custom error message on validation

Hi i would like to know if there is a workaround for custom error message so front end can read the error message more clearly field name included. Right now the error message was duplicated key not allowed.

this is the current code i am working on and i have no idea how to get the fieldname and which field violating the unique constraint.

`if err := models.DB.Create(&product).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			fmt.Println("Name Already Exist")
			fmt.Println("Email Already Exist")
		}
}`

expected message: 

`{
"error" : [
                  Email already exist"
                  ]
}`

**Comment by saeidee** [comment]
There is no such feature yet, however, if you want you can use dialect err casting and disable the gorm err translation, so that way you will get more details on error.
