### ISSUE TITLE
Can't insert array []string into PostgresDB with GORM

### ISSUE THREAD

**Issue by khiem20tc** [go-gorm/gorm#6599]
![image](https://github.com/go-gorm/gorm/assets/53548789/888df194-c5fe-496f-880b-60e5cf6bbded)

Why is GORM not built-in to insert an array of strings into PostgresDB?

**Comment by saeidee** [comment]
Check https://github.com/go-gorm/datatypes

**Comment by chjiyun** [comment]
我也是折腾这个一个晚上了，官网文档没看到还有这个库，无语
