### ISSUE TITLE
How to define decimal precision using gorm & postgres?

### ISSUE THREAD

**Issue by rngallen** [go-gorm/gorm#6612]
## Your Question
How can I implement precision on decimals(float) using gorm?

type Abc struct {
FieldOne float64 `gorm:"precision(8,2)` // eight digits with 2 decimal places 
}

**Comment by akshay-pj-open** [comment]
Use column type as numeric(8,2) // Eight digits and Two decimal places.

Example:
```
type Abc struct {
FieldOne   float64  `gorm:"type:numeric(16,4)"`
}
```

**Comment by ravenrich** [comment]
how to define decimal(32,16)?
