### ISSUE TITLE
sqlite test (1.19 in ubuntu:latest) : table xxx has more than one primary key

### ISSUE THREAD

**Issue by zhtiyissr** [go-gorm/gorm#6628]
# GORM PR Link
 https://github.com/go-gorm/gorm/pull/6627

# Description
i want to make PR to add some config for migrator, it has only minimal code changes. But the checks failed, here is details: https://github.com/go-gorm/gorm/actions/runs/6448509357/job/17505845740?pr=6627

I don't think this is caused by me, because when I comment out my changes, the problem still occurs. 
here is the other test details: https://github.com/go-gorm/gorm/actions/runs/6448558597/job/17505952191?pr=6627

who can fix it?

**Comment by mykbas** [comment]
It seems that the problem with this driver `gorm.io/driver/sqlite`.
This `github.com/glebarez/sqlite` works well.

**Comment by zhtiyissr** [comment]
@mykbas 
the test file use gorm.io/driver/sqlite v1.5.3, the problem still occurs.

see https://github.com/go-gorm/gorm/blob/master/tests/go.mod  line11

**Comment by minchenzz** [comment]
same, v1.5.3 run ok

**Comment by zhtiyissr** [comment]
> same, v1.5.3 run ok

@minchenzz   look my PR file changed, i changed nothing, but test failed. hhhhh...

https://github.com/go-gorm/gorm/pull/6627/files

**Comment by sluedecke** [comment]
Error disappears after downgrading to `gorm.io/driver/sqlite v1.5.3`.

**Comment by jinzhu** [comment]
how about gorm v1.25.5?

**Comment by zhtiyissr** [comment]
> 测试在这个版本时未报错
> 
> ```
> gorm.io/driver/sqlite v1.5.4
> gorm.io/gorm v1.25.3
> ```
> 
> 当`gorm.io/gorm v1.25.4` 出现报错

@saltyfishyu  you are right, but when i use gorm v1.25.3, mysql, mariadb have other problems. sqllite is ok.

https://github.com/go-gorm/gorm/pull/6627

**Comment by zhtiyissr** [comment]
The conclusion is when you only use sqlite , using ```gorm.io/driver/sqlite v1.5.3``` or ```gorm.io/gorm v1.25.3``` may solve the problem.

But I think there are unstable test cases in ```https://github.com/go-gorm/gorm/tree/master/tests```. Because my PR changed nothing, but the test failed. Moreover, the test results are different at different times. Now I do not encounter the problem of sqlite test failure, but mysql, tidb, mariadb test failure.

Even if I use the same version number in the current master branch ```https://github.com/go-gorm/gorm/tree/master/tests/go.mod```, the test still failed. I don’t know how other PRs are merged. Hope someone can fix these issues.
