### ISSUE TITLE
gorm cannot reuse connection before created

### ISSUE THREAD

**Issue by Karrrrrrrr** [go-gorm/gorm#6633]
When I use gorm v2, I find that the connection life of v2 seems to be only 1 second, and when a connection is not used for more than 1 second, it will be destroyed, so it seems time-consuming to create a connection each time, and it takes about 100ms to create a connection. Can you solve this problem through configuration?
None of the following configurations worked for me
```go
s, err := db.DB()
s.SetMaxOpenConns(100)
s.SetMaxIdleConns(100)
s.SetConnMaxIdleTime(time.Hour)
s.SetConnMaxLifetime(time.Hour)
````
But I did not find this problem in the gorm-v1, v1 can reuse the previous connection, will not destroy the connection after a second
The specific code is shown below

The first image is gorm v1, this query just use little time.

![image-20231009213631808](https://github.com/go-gorm/gorm/assets/61825259/6d4a82b2-2b96-4da1-965d-47181a40c5f3)

The second diagram shows that connections can be reused when I use an interval of 0.5 seconds

![image-20231009213852519](https://github.com/go-gorm/gorm/assets/61825259/b53635a0-0666-47fd-bcfa-657e233aaa83)

The third diagram shows that when I use the 1 second interval, I can't reuse the connection, and gorm helps me re-create the connection

![image-20231009213914754](https://github.com/go-gorm/gorm/assets/61825259/c01510bf-4f80-4ed2-a1e6-d19f684ce9a4)

The fourth diagram shows that the configuration does not work

![image-20231009214111460](https://github.com/go-gorm/gorm/assets/61825259/0ea3123d-46e0-4635-a6bc-2fef7228e409)

**Comment by deepak8988** [comment]
@Karrrrrrrr  Even with gorm v1, this issue exists. we were using **gorm.io/gorm v1.25.1** and all hell broke loose on application.
Had to migrate to older version(**gorm.io/gorm v1.23.6**), but not before wasting lot of time.
