### ISSUE TITLE
59640 这个参数是有什么问题吗？

### ISSUE THREAD

**Issue by zobx** [go-gorm/gorm#6647]
![image](https://github.com/go-gorm/gorm/assets/28089614/1538c1c2-8615-4749-99c4-2bfecac8a24f)

sql命令行执行也是很快 就是传参数很慢

**Comment by ivila** [comment]
建议检查一下MySQL服务端的配置以及资源信息。
然后可以看看Prepared Statement相关的内容。
我觉得可能是你的MySQL服务端处理Prepared Statement时效率较低导致。

**Comment by zobx** [comment]
很奇怪 就这个59640有问题 别的都很快
