### ISSUE TITLE
How to solve the problem that gorm efficiency is too low

### ISSUE THREAD

**Issue by mcmy** [go-gorm/gorm#6657]
Why is the native method significantly faster than GORM in my tests? With GORM, I noticed that it initially performs quite well with 2 milliseconds response times for 1000 users and 100,000 requests. However, as the request load increases, the response time grows to 6 seconds. In contrast, when using sql.DB, the performance remains consistent, and this seems to be because sql.DB implicitly calls the db.Close() method, which allows it to maintain a much faster response time. However, I couldn't find any code in GORM to manually release connections back to the pool.

![image](https://github.com/go-gorm/gorm/assets/54695595/723f73dd-c887-43f7-8188-049a73cf9d4d)
![image](https://github.com/go-gorm/gorm/assets/54695595/9c278c79-10d3-4dbe-b666-40eb2e97332c)

![image](https://github.com/go-gorm/gorm/assets/54695595/bd64f9f8-79c2-4d92-89a8-0bd633eebe48)
![image](https://github.com/go-gorm/gorm/assets/54695595/4a8a4bba-5453-4f90-9eff-c6ed5219eba5)

**Comment by GP-JVM** [comment]
你这个界面的数据是用什么工具跑出来的

**Comment by mcmy** [comment]
> 你这个界面的数据是用什么工具跑出来的

wrk或者apache bench，现在解决了，是代码问题，当时忽略了报错
