### ISSUE TITLE
Bad insertion IDs when doing a bulk Upsert

### ISSUE THREAD

**Issue by jeffphp** [go-gorm/gorm#6663]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/658

## Description

When bulk inserting rows with a OnConflict / DoUpdates clause, generated IDs are wrong if the saved items are a mix of existing and new items.

The  submitted PR case shows how to reproduce this.

**Comment by iangcarroll** [comment]
Might be related to #6027, seems like we still see this on latest Gorm version. We have been stuck on `v1.24.3` for a while now as a result

**Comment by a631807682** [comment]
move to https://github.com/go-gorm/gorm/issues/6047
