### ISSUE TITLE
Batch update functionality using gorm.DB.Save() is not working 

### ISSUE THREAD

**Issue by ahmedBahossain** [go-gorm/gorm#6669]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

There is an issue with batch update functionality using gorm.DB.Save(). It occurs when we try to insert into SQL server DB. As you can see in the image below, passing an array of objects to Save() function will be translated to SQL query as MERGE statement.  The error message clearly describes the root case "the table name is missing schema". Save() function works correctly using an object instead of an array.

![Screenshot 2023-11-01 at 8 58 03 PM](https://github.com/go-gorm/gorm/assets/105207132/628f5cd8-c210-4cda-9f05-cd4712b1159f)

**Comment by saeidee** [comment]
Please submit a correct Plaground PR as your linked PR is not correct.
