### ISSUE TITLE
The return values of the framework and the results of MySQL's internal command-line execution are inconsistent.

### ISSUE THREAD

**Issue by shig-cn** [go-gorm/gorm#6672]
Challenges encountered when using Sharding-Proxy for database sharding and table partitioning

screenshot：
![image](https://github.com/go-gorm/gorm/assets/86032486/5eec5908-8fae-40fa-a7b5-7e8c34b319d1)
![image](https://github.com/go-gorm/gorm/assets/86032486/28fcd710-0ab4-414d-8295-8dfee4f50a1c)

result:
gorm return: 0
mysql return: 1

**Comment by ivila** [comment]
@shig-cn please show us a demo, or paste your full codes here, or no one else know what exactly going on with your scenario.
