### ISSUE TITLE
[Belongs-to with overide foreignKey not work]

### ISSUE THREAD

**Issue by khiem20tc** [go-gorm/gorm#6681]
Hi team, I would like to raise a bug not supporting in `belongs-to` with the case using `overide-foreigner`. Many A belongs to B.

```
type A struct {
	ID string `gorm:"size:14" json:"id"`

	Currency string `json:"currency"`
	B    model.B`gorm:"foreignKey:Currency;references:Currency" json:"token"`
}

type B struct {
        ID string `gorm:"size:14" json:"id"`

	Currency string `json:"currency"`
}
```

The error return `ERROR: insert or update on table violates foreign key constraint`

**Comment by saeidee** [comment]
Please submit a plaground PR with to reproduce the issue.
