### ISSUE TITLE
Add YDB support

### ISSUE THREAD

**Issue by dumindu** [go-gorm/gorm#6684]
## Describe the feature

Add support for YDB

- [YDB](https://ydb.tech) is a versatile open source Distributed SQL Database that combines high availability and scalability with strong consistency and ACID transactions 
- YDB comes with a pure Go native and `database/sql` driver ; https://github.com/ydb-platform/ydb-go-sdk

**Comment by jinzhu** [comment]
Sorry, I currently don’t have the capacity to implement support for YDB. However, I’d be happy if the community could take on this effort. The implementation can either be maintained under the GORM organization or independently. We will add relevant links to recommend it.
