### ISSUE TITLE
sqlx和Gorm相比，sqlx性能更好一点，使用Gorm仅仅是为了预防sql注入嘛

### ISSUE THREAD

**Issue by fineCoderWithLove** [go-gorm/gorm#6688]
通过查看这个文章得到的问题:https://cloud.tencent.com/developer/article/2056863

**Comment by jinzhu** [comment]
Try changing the order of sqlx and gorm to see the performance difference. I remember from performance tests that gorm is somewhat better than sqlx. Also, you can try https://github.com/go-gorm/orm-benchmark. However, in actual use, performance doesn't really have much impact, as the bottleneck is usually in the database.

**Comment by fineCoderWithLove** [comment]
ok，我明白了，感谢您的回复




长安少年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-gorm/gorm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午3:30
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [go-gorm/gorm] sqlx和Gorm相比，sqlx性能更好一点，使用Gorm仅仅是为了预防sql注入嘛 (Issue #6688)





 
Try changing the order of sqlx and gorm to see the performance difference. I remember from performance tests that gorm is somewhat better than sqlx. Also, you can try https://github.com/go-gorm/orm-benchmark. However, in actual use, performance doesn't really have much impact, as the bottleneck is usually in the database.
