### ISSUE TITLE
Gen 根据  PostgreSQL 数据库表生成 model 的时候，有指定空字符串默认值的字段，生成的 gorm 标签有问题。

### ISSUE THREAD

**Issue by panjunjie** [go-gorm/gorm#6691]
比如某个article表的title标题字段，数据库指定空字符串默认值，Gen 生成 model 的时候，gorm 标签如下：
Title        string         `gorm:"column:title;type:character varying(120);default:''::character varying";comment:标题" json:"title"`
这个看起来似乎没有问题，但是实际使用的时候，title 字段如果不赋值，数据库插入的默认值是：::character varying 字符串，并不是预期的空字符串。

我不知道这个算不算 bug，我每次生成 model 之后，都需要把 default:''::character varying 批量替换成 default:'' 才达到预期效果。

请你们有空验证一下，不胜感激。

**Comment by okki-op** [comment]
遇到同款bug
