### ISSUE TITLE
数据库有记录为啥报 record not found 

### ISSUE THREAD

**Issue by liu-cn** [go-gorm/gorm#6699]
![image](https://github.com/go-gorm/gorm/assets/56096275/2791f959-9065-4ace-a3ea-a51e420d72bf)
![image](https://github.com/go-gorm/gorm/assets/56096275/e2f0bcba-8409-4cac-a9f8-2e1b1b7cc159)

![image](https://github.com/go-gorm/gorm/assets/56096275/00672b3f-f2e4-4a46-870d-6674f49576e0)
![image](https://github.com/go-gorm/gorm/assets/56096275/5a0bd731-e491-4df9-8e2a-78edb73a9afe)

**Comment by liu-cn** [comment]
gorm v1.25.5

**Comment by liu-cn** [comment]
go 1.21.0

**Comment by liu-cn** [comment]
gorm.io/driver/mysql v1.5.2

**Comment by liu-cn** [comment]
用原生语句就可以查到
![image](https://github.com/go-gorm/gorm/assets/56096275/a8bfea53-8ed2-460b-93ac-a48bdae1c238)

**Comment by GP-JVM** [comment]
你查不到是100%查不到还是说大部分查不到，

**Comment by liu-cn** [comment]
> 你查不到是100%查不到还是说大部分查不到，

大部分吧

**Comment by GP-JVM** [comment]
> > 你查不到是100%查不到还是说大部分查不到，
> 
> 大部分吧

你这个打印一下SQL，我也是大部分查不到，设置了gorm的最大空闲连接数和最大连接数，总是查着查着就出错

**Comment by withSunday** [comment]
![image](https://github.com/go-gorm/gorm/assets/39394654/b505825a-be33-4644-add0-5d4f60dc6c82)

**Comment by liu-cn** [comment]
> ![image](https://private-user-images.githubusercontent.com/39394654/285371086-b505825a-be33-4644-add0-5d4f60dc6c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4OTYwNDUsIm5iZiI6MTcwMDg5NTc0NSwicGF0aCI6Ii8zOTM5NDY1NC8yODUzNzEwODYtYjUwNTgyNWEtYmUzMy00NjQ0LWFkZDAtNWQ0ZjYwZGM2YzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA3MDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiODMxZjk4M2VkYTYyZDRlZjM2NWMwNjM2YjNkMjdjZmE5MmMyZDI2NDFhMDM3MTVhZmNkNTIwMzY4OGU4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ba_TG9JHBxNX3A3NLCtQn4InS8IJpFFcvUWin6r9Oxw)

可能不是这个原因，我新创建个连接，没设置最大空闲连接之类的参数，只有连接字符串，然后就不会报错了

**Comment by Shineloner** [comment]
老哥定位到原因了吗？我这里也出现了，也是改成用原生sql就正常
