### ISSUE TITLE
run with linux-arm,goarm is arm5

### ISSUE THREAD

**Issue by cuican6** [go-gorm/gorm#6702]
,my app run with windows,its success.when my app run with goarm=arm5,panic is this
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2c pc=0x3faeac]

goroutine 6 [running]:
modernc.org/sqlite/lib.Xsqlite3WhereBegin(0x1cfc820, 0xae5008b0, 0xad50b2b8, 0x0, 0xad50b0b8, 0xad507548, 0xad50b038, 0x0, 0x140)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:106300 +0xd20
modernc.org/sqlite/lib.Xsqlite3Select(0x1cfc820, 0xae5008b0, 0xad50b038, 0xae500f00)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:92009 +0x19fc
modernc.org/sqlite/lib.yy_reduce(0x1cfc820, 0xae5009f0, 0x54, 0x1, {0xad50b466, 0x0}, 0xae5008b0)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:111851 +0x10d4
modernc.org/sqlite/lib.Xsqlite3Parser(0x1cfc820, 0xae5009f0, 0x1, {0xad50b466, 0x0})
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:113411 +0xb8
modernc.org/sqlite/lib.Xsqlite3RunParser(0x1cfc820, 0xae5008b0, 0xad50b438)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:114134 +0x32c
modernc.org/sqlite/lib.sqlite3Prepare(0x1cfc820, 0xadb00018, 0xad50b438, 0xffffffff, 0x80, 0x0, 0xae500890, 0xae500894)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:85921 +0x338
modernc.org/sqlite/lib.sqlite3LockAndPrepare(0x1cfc820, 0xadb00018, 0xad50b438, 0xffffffff, 0x80, 0x0, 0xae500890, 0xae500894)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:86004 +0x150
modernc.org/sqlite/lib.Xsqlite3_prepare_v2(...)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:86071
modernc.org/sqlite/lib.Xsqlite3_exec(0x1cfc820, 0xadb00018, 0xad50b438, 0x68fda8, 0xae500858, 0x0)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:80623 +0x218
modernc.org/sqlite/lib.Xsqlite3InitOne(0x1cfc820, 0xadb00018, 0x0, 0xae500054, 0x0)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:85545 +0x850
modernc.org/sqlite/lib.Xsqlite3Init(0x1cfc820, 0xadb00018, 0xae500054)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:85622 +0x70
modernc.org/sqlite/lib.Xsqlite3ReadSchema(0x1cfc820, 0xae500050)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:85649 +0x50
modernc.org/sqlite/lib.Xsqlite3LocateTable(0x1cfc820, 0xae500050, 0x0, 0xad50b738, 0x0)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:68135 +0xa8
modernc.org/sqlite/lib.Xsqlite3LocateTableItem(0x1cfc820, 0xae500050, 0x0, 0xad50b8c0)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:68192 +0x60
modernc.org/sqlite/lib.selectExpander(0x1cfc820, 0xae500790, 0xad50b4b8)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:90568 +0x330
modernc.org/sqlite/lib.Xsqlite3WalkSelect(0x1cfc820, 0xae500790, 0xad50b4b8)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:54992 +0x70
modernc.org/sqlite/lib.sqlite3SelectExpand(0x1cfc820, 0xae500050, 0xad50b4b8)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:90856 +0xf8
modernc.org/sqlite/lib.Xsqlite3SelectPrep(0x1cfc820, 0xae500050, 0xad50b4b8, 0x0)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:90931 +0x50
modernc.org/sqlite/lib.Xsqlite3Select(0x1cfc820, 0xae500050, 0xad50b4b8, 0xae5006a0)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:91558 +0x1d4
modernc.org/sqlite/lib.yy_reduce(0x1cfc820, 0xae500190, 0x54, 0x1, {0xad9004d0, 0x0}, 0xae500050)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:111851 +0x10d4
modernc.org/sqlite/lib.Xsqlite3Parser(0x1cfc820, 0xae500190, 0x1, {0xad9004d0, 0x0})
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:113411 +0xb8
modernc.org/sqlite/lib.Xsqlite3RunParser(0x1cfc820, 0xae500050, 0xad900490)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:114134 +0x32c
modernc.org/sqlite/lib.sqlite3Prepare(0x1cfc820, 0xadb00018, 0xad900490, 0xffffffff, 0x80, 0x0, 0xae300058, 0xae300060)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:85921 +0x338
modernc.org/sqlite/lib.sqlite3LockAndPrepare(0x1cfc820, 0xadb00018, 0xad900490, 0xffffffff, 0x80, 0x0, 0xae300058, 0xae300060)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:86004 +0x150
modernc.org/sqlite/lib.Xsqlite3_prepare_v2(...)
	D:/GOProject/pkg/mod/modernc.org/sqlite@v1.23.1/lib/sqlite_linux_arm.go:86071
github.com/glebarez/go-sqlite.(*conn).prepareV2(0x1d04960, 0x1c35978)
	D:/GOProject/pkg/mod/github.com/glebarez/go-sqlite@v1.21.2/sqlite.go:1275 +0x17c
github.com/glebarez/go-sqlite.(*stmt).query(0x1d1e9c8, {0x72bb28, 0xa87af8}, {0x1cc79e0, 0x1, 0x1})
	D:/GOProject/pkg/mod/github.com/glebarez/go-sqlite@v1.21.2/sqlite.go:605 +0x134
github.com/glebarez/go-sqlite.(*conn).query(0x1d04960, {0x72bb28, 0xa87af8}, {0x1c19f40, 0x40}, {0x1cc79e0, 0x1, 0x1})
	D:/GOProject/pkg/mod/github.com/glebarez/go-sqlite@v1.21.2/sqlite.go:1519 +0x100
github.com/glebarez/go-sqlite.(*conn).QueryContext(0x1d04960, {0x72bb28, 0xa87af8}, {0x1c19f40, 0x40}, {0x1cc79e0, 0x1, 0x1})
	D:/GOProject/pkg/mod/github.com/glebarez/go-sqlite@v1.21.2/sqlite_go18.go:38 +0x54
database/sql.ctxDriverQuery({0x72bb28, 0xa87af8}, {0xae90b9e0, 0x1d04960}, {0x0, 0x0}, {0x1c19f40, 0x40}, {0x1cc79e0, 0x1, ...})
	C:/Program Files/Go/src/database/sql/ctxutil.go:48 +0x94
database/sql.(*DB).queryDC.func1()
	C:/Program Files/Go/src/database/sql/sql.go:1748 +0x178
database/sql.withLock({0x72b19c, 0x1d142a0}, 0x1c35bb8)
	C:/Program Files/Go/src/database/sql/sql.go:3502 +0x84
database/sql.(*DB).queryDC(0x1c7eb40, {0x72bb28, 0xa87af8}, {0x0, 0x0}, 0x1d142a0, 0x1d1e9c0, {0x1c19f40, 0x40}, {0x1d1e988, ...})
	C:/Program Files/Go/src/database/sql/sql.go:1743 +0x174
database/sql.(*DB).query(0x1c7eb40, {0x72bb28, 0xa87af8}, {0x1c19f40, 0x40}, {0x1d1e988, 0x1, 0x1}, 0x1)
	C:/Program Files/Go/src/database/sql/sql.go:1726 +0xe4
database/sql.(*DB).QueryContext.func1(0x1)
	C:/Program Files/Go/src/database/sql/sql.go:1704 +0x6c
database/sql.(*DB).retry(0x1c7eb40, 0x1c35cc0)
	C:/Program Files/Go/src/database/sql/sql.go:1538 +0x78
database/sql.(*DB).QueryContext(0x1c7eb40, {0x72bb28, 0xa87af8}, {0x1c19f40, 0x40}, {0x1d1e988, 0x1, 0x1})
	C:/Program Files/Go/src/database/sql/sql.go:1703 +0x9c
database/sql.(*DB).QueryRowContext(0x1c7eb40, {0x72bb28, 0xa87af8}, {0x1c19f40, 0x40}, {0x1d1e988, 0x1, 0x1})
	C:/Program Files/Go/src/database/sql/sql.go:1804 +0x54
gorm.io/gorm/callbacks.RowQuery(0x1d05620)
	D:/GOProject/pkg/mod/gorm.io/gorm@v1.25.2/callbacks/row.go:18 +0x208
gorm.io/gorm.(*processor).Execute(0x1cdcb40, 0x1d05620)
	D:/GOProject/pkg/mod/gorm.io/gorm@v1.25.2/callbacks.go:130 +0x3ec
gorm.io/gorm.(*DB).Row(0x1d05620)
	D:/GOProject/pkg/mod/gorm.io/gorm@v1.25.2/finisher_api.go:502 +0x94
github.com/glebarez/sqlite.Migrator.HasTable.func1(0x1c7ce00)
	D:/GOProject/pkg/mod/github.com/glebarez/sqlite@v1.9.0/migrator.go:33 +0x94
gorm.io/gorm/migrator.Migrator.RunWithValue({{0x1, 0x1d05600, {0x72c698, 0x1cc79c8}}}, {0x618860, 0x1c6ac80}, 0x1c35e90)
	D:/GOProject/pkg/mod/gorm.io/gorm@v1.25.2/migrator/migrator.go:62 +0x144
github.com/glebarez/sqlite.Migrator.HasTable({{{0x1, 0x1d05600, {0x72c698, 0x1cc79c8}}}}, {0x618860, 0x1c6ac80})
	D:/GOProject/pkg/mod/github.com/glebarez/sqlite@v1.9.0/migrator.go:32 +0x90
gorm.io/gorm/migrator.Migrator.AutoMigrate({{0x1, 0x1d05160, {0x72c698, 0x1cc7710}}}, {0x1d1e550, 0x1, 0x1})
	D:/GOProject/pkg/mod/gorm.io/gorm@v1.25.2/migrator/migrator.go:111 +0x198

**Comment by ivila** [comment]
@cuican6 can you provide a reproduction steps? For example, some runable codes.
And I suggest you should just raise a issue at https://gitlab.com/cznic/sqlite, because what I currently found out, the reason of the panic should be their side, they use a pointer and convert it to a (*WhereLevel) value, and the FpWLoop field of this value is null, and the codes wants to convert the null pointer to a WhereLoop value(https://gitlab.com/cznic/sqlite/-/blob/v1.23.1/lib/sqlite_linux_arm.go?ref_type=tags#L106300)
