### ISSUE TITLE
Gorm - AutoMigrate creates duplicate Unique Keys

### ISSUE THREAD

**Issue by Placeblock** [go-gorm/gorm#6739]
## Your Question

I have the following Struct/Model

```
type TestTable struct {
    ID      uint `gorm:"unique;autoIncrement"`
    QuoteID uint `gorm:"primaryKey"`
}
```

If I auto migrate it with gorm wierd things happen: At first the auto migration doesn't work at all: "there can be only one auto column and it must be defined as a key". Gorm tries to set both columns to autoIncrement. As far as I know this shouldn't happen? I fixed this issue by setting autoIncrement to false on QuoteID. Everything seems to work fine, but now gorm alters the table on every migration and creates a new unique key every time. id_1, id_2, id_3, and so on.
I  reported this as a question because I am not sure if this is intended or not.

## The document you expected this should be explained

I would expect it to be explained there: [https://gorm.io/docs/models.html#Fields-Tags](https://gorm.io/docs/models.html#Fields-Tags) 

## Expected answer
I would expect from gorm to create only one autoIncrement column and don't create multiple unique keys.

Help is appreciated! Have a great day :)

**Comment by Placeblock** [comment]
"Solved" it by using sql:"AUTO_INCREMENT" and not gorm:"autoIncrement"

It looks like gorm skips some internal logic if I specify the auto increment in the sql tag.

**Comment by Placeblock** [comment]
Still a Problem. Tried some stuff but nothing helped much.

**Comment by Sherlock-HJ** [comment]
me too

**Comment by llqhy** [comment]
me too

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/pull/6386
