### ISSUE TITLE
where can I find gorm release note

### ISSUE THREAD

**Issue by gitouyoung** [go-gorm/gorm#6746]
I want to upgrade gorm, but the [change log](https://gorm.io/docs/changelog.html) is out-dated.

**Comment by ivila** [comment]
@gitouyoung Maybe see this: https://github.com/go-gorm/gorm/tags

**Comment by gitouyoung** [comment]
> @gitouyoung Maybe see this: https://github.com/go-gorm/gorm/tags

okay. Thanks for your comment.  Maybe it's better to display in docs
