### ISSUE TITLE
Column struct tag for jsonb fields support

### ISSUE THREAD

**Issue by SunatSS** [go-gorm/gorm#6763]
## Describe the feature
Is it possible for make such syntax work?
```Go
type Example type {
   NameRu string `gorm:"column:name->>'ru'"
}
```

## Motivation
It is good for using Find and Take methods with custom defined response structs without declaring select query

**Comment by jinzhu** [comment]
You can customize a serializer interface, referring to the implementation here [https://gorm.io/docs/serializer.html#Customized-Serializer-Type], and then implement the related functionality in Scan through the field's tag.

**Comment by SunatSS** [comment]
@jinzhu yes, I can, and I'll try to do this for my project, but what about adding this feature to gorm lib for making this possible without customization?

**Comment by jinzhu** [comment]
We can implement a default solution if it could support create/update/query operations for all drivers, but it's not an easy task. We would be happy to accept a pull request for this. It could be registered in a way similar to serializers like json/gob/unixtime
