### ISSUE TITLE
(v1.25.5) Why `gorm:"uniqueIndex:idx_xxx"` generate two unique index "idx_xxx" and "xxx" ? 

### ISSUE THREAD

**Issue by xiaoz194** [go-gorm/gorm#6770]
## Your Question

My model: 
```
type ToolRelation struct {
	gorm.Model
	TeamId     int64
	ProjectId  int64
	DepotId    int64  `gorm:"index:idx_depot_id"`
	ToolId     int64  `gorm:"uniqueIndex:idx_tool_id"`
	CreatorId  int64
	ModifierId int64
	DeletorId  int64
}
```
why generate 2 unique index "idx_tool_id" and "tool_id"?  (This is first migration)
And when I delete "idx_tool_id", such as : 
```
ToolId     int64  `gorm:"uniqueIndex"`
```
 it also generate 2 unique index "idx_tool_id" and "idx_tca_tool_relation_tool_id",is it a Bug?

<img width="449" alt="image" src="https://github.com/go-gorm/gorm/assets/39124498/58d8df18-d863-4e0a-87b1-c9cea875e2cf">

**Comment by klipach** [comment]
Have the same issue after the update to v1.25.5, using PostgreSQL:

The following model tries to create `idx_point_of_interest_iata_code` index on migration - `ALTER TABLE "point_of_interest" ADD CONSTRAINT "idx_point_of_interest_iata_code" UNIQUE("iata_code"`)
```
type PointOfInterest struct {
	IataCode   string `gorm:"uniqueIndex:idx_point_of_interest_iata_unique,where:enabled=true AND iata_code != ''"`
	Enabled    bool
}
```

**Comment by a631807682** [comment]
https://github.com/go-gorm/gorm/issues/6381#issuecomment-1929427042

**Comment by xiaoz194** [comment]
> [#6381 (comment)](https://github.com/go-gorm/gorm/issues/6381#issuecomment-1929427042)

Thank u very much!
