### ISSUE TITLE
VAPID 字段被自动识别为 v_api_d

### ISSUE THREAD

**Issue by greensea** [go-gorm/gorm#6773]
## Description

定义如下模型：

```
type VAPID struct {
    ID int
    VAPID string
}
```

然后调用 `AutoMigrate(&VAPID{})` 自动迁移，结果数据库中出现的字段名为为 `v_api_d`，而非 `vapid`。

可能是 gorm 内部对 `api` 这个字符串做了特别处理？

附：VAPID 常在 WebPush 中使用，全称 Voluntary Application Server Identification

**Comment by dextercai** [comment]
```
type VAPID struct {
    ID int 
    VAPID string `gorm:"column:vapid;" 
}
```
