### ISSUE TITLE
使用Debug打印时Group Where失效

### ISSUE THREAD

**Issue by Madou-Shinni** [go-gorm/gorm#6778]
### 使用Debug打印时Group Where失效
我的链式调用如下，使用了Group Where来编写复杂的sql
`
err := db.Where(
		db.Where("channel = ?", constants.CouponChannelShop).
			Or("channel = ?", constants.CouponChannelCash), // 现金
	).
		Where("id in ?", couponIds).
		Count(&count).Error
`
![image](https://github.com/go-gorm/gorm/assets/91399492/9c46d6e0-6a0f-482e-8b7c-ca5b94894a37)
然而我在使用Debug是出现了问题,Count似乎是忽略了Group Where
`
err := db.Debug().Where(
		db.Where("channel = ?", constants.CouponChannelShop).
			Or("channel = ?", constants.CouponChannelCash), // 现金
	).
		Where("id in ?", couponIds).
		Count(&count).Error
`
![20240105-154142](https://github.com/go-gorm/gorm/assets/91399492/9f5114b4-4b39-4e31-a19c-255bfb7834cc)

**Comment by iTanken** [comment]
这样试一下：

```go
db = db.Debug()
err := db.Where( db.Where("channel = ?", constants.CouponChannelShop). Or("channel = ?", constants.CouponChannelCash), // 现金 ). Where("id in ?", couponIds). Count(&count).Error
```

**Comment by Madou-Shinni** [comment]
> 这样试一下：
> 
> ```go
> db = db.Debug()
> err := db.Where( db.Where("channel = ?", constants.CouponChannelShop). Or("channel = ?", constants.CouponChannelCash), // 现金 ). Where("id in ?", couponIds). Count(&count).Error
> ```

也许这看起来不怎么遍历，但这确实是一种有效的方式，他解决了Debug Group Where消失的问题
