### ISSUE TITLE
 generate struct from table fail: ERROR: relation "user" does not exist (SQLSTATE 42P01)

### ISSUE THREAD

**Issue by SherryDongCN** [go-gorm/gorm#6808]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
It is reporting the error as the title describing when use gen tool to generate structs from database
Steps to reproduce:
1. install the gen tool
` go install gorm.io/gen/tools/gentool@latest`
3. generate

`  gentool -dsn "postgres:password@tcp(127.0.0.1:6432)/service_backend?charset=utf8mb4&parseTime=true&loc=Local" -tables "user" -db postgres -outPath "./internal/data/repository/tenant" -modelPkgName "user" -outFile "user.go" -withUnitTest true
`

**Comment by ccfish86** [comment]
我现在遇到了这问题，以下是出问题的地方，在Window开发环境下正常，Linux下编译运行后，报错


'''
// GetWebsiteInfo 获取网站信息
func (siteConfigService *SiteConfigService) GetWebsiteInfo() (result ofcparam.WebsiteInfoResp, err error) {
	err = global.GVA_DB.Model(&official.SiteConfig{}).Order("id").Limit(1).Find(&result).Error
	return
}

// SiteConfig 结构体
type SiteConfig struct {
	global.GVA_MODEL
	SiteName           string `json:"siteName" form:"siteName" gorm:"column:site_name;comment:网站名;size:100;"`
	AboutUs            string `json:"aboutUs" form:"aboutUs" gorm:"column:about_us;comment:关于我们;size:2000;"`
	Address            string `json:"address" form:"address" gorm:"column:address;comment:地址;size:200;"`
	AddressMap         string `json:"addressMap" form:"addressMap" gorm:"column:address_map;comment:地图位置;size:255;"`
	OfficialPhone      string `json:"officialPhone" form:"officialPhone" gorm:"column:official_phone;comment:联系电话;size:200;"`
	OfficialPhoneImage string `json:"officialPhoneImage" form:"officialPhoneImage" gorm:"column:official_phone_image;comment:联系电话图;size:255;"`
	OfficialEmail      string `json:"officialEmail" form:"officialEmail" gorm:"column:official_email;comment:联系邮箱;size:255;"`
}

// TableName SiteConfig 表名
func (SiteConfig) TableName() string {
	return "official.site_configs"
}

'''

以下是日志部分
'''
May 21 11:49:36 localhost server: [GIN] 2024/05/21 - 11:49:36 | 200 |     961.093µs |     172.17.0.10 | GET      "/web/api/official/website/info"
May 21 11:49:37 localhost server: 2024/05/21 11:49:37 #033[31;1m/var/jenkins_home/workspace/weihuaqua-test-server/server/service/official/site_configs.go:72 #033[35;1mERROR: relation "official.site_configs" does not exist (SQLSTATE 42P01)
May 21 11:49:37 localhost server: #033[0m#033[33m[0.882ms] #033[34;1m[rows:0]#033[0m SELECT "site_configs"."site_name","site_configs"."about_us","site_configs"."address","site_configs"."address_map","site_configs"."official_phone","site_configs"."official_email" FROM "official"."site_configs" WHERE "site_configs"."deleted_at" IS NULL ORDER BY id LIMIT 1

'''
