### ISSUE TITLE
gorm v1.25.6 : Create error when using map[string]interface{} with Postgres

### ISSUE THREAD

**Issue by magellancl** [go-gorm/gorm#6812]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/685

## Description

Related to https://github.com/go-gormigrate/gormigrate/issues/217

This library is using customizable table and column name, so Create is used this way :
```
	columnName := "name"
	user := map[string]interface{}{columnName: "id"}
	err := DB.Table("users").Create(user).Error
```

which return the error "LastInsertId is not supported by this driver", instead of creating the record

**Comment by oxyno-zeta** [comment]
If this won't be patched, do you have a solution in order to patch the library?

**Comment by thesiti92** [comment]
this error is preventing me from upgrading my service! any help would be greatly appreciated
