### ISSUE TITLE
feat: all APIs support context

### ISSUE THREAD

**Issue by a631807682** [go-gorm/gorm#6824]
## Describe the feature

Currently, some APIs lose context, which may cause context-based functions to fail in this part of the API, such as trace.

https://github.com/go-gorm/gorm/blob/master/finisher_api.go#L530

## Motivation

Make sure WithContext is working properly in the finisher API and add relevant test cases.

**If anyone is interested in the above tasks, please leave a message in the comments.**

**Comment by premkirank** [comment]
@a631807682 I am interested in this. Can I take this up? Would require some help to get started

**Comment by a631807682** [comment]
> @a631807682 I am interested in this. Can I take this up? Would require some help to get started

Assign to you, thank you.

**Comment by jinzhu** [comment]
use `WithContext ` for now

**Comment by jinzhu** [comment]
use `WithContext ` for now
