### ISSUE TITLE
I have a problem with the 1.25.7 vesion.

### ISSUE THREAD

**Issue by bearatol** [go-gorm/gorm#6832]
Hello. We use the AutoMigrate() function in our project. But we have a problem with the error: "insufficient arguments". The problem appeared with version 1.25.7. We were forced to roll back to an earlier version 1.25.6.

Our data for example:
```
// models
type RiverEdge struct {
	ParentPortID uint32  `json:"parent_port_id"`
	ChildPortID  uint32  `json:"child_port_id"`
	Cost         float64 `json:"cost"`
}

type RiverPort struct {
	ID   uint32 `json:"id,omitempty"`
	Name string `json:"name"`
}

// calling
func Run(db *gorm.DB, riverStore dao.RiverStore) error {
	if err := db.AutoMigrate(&model.RiverPort{}, &model.RiverEdge{}); err != nil {
		return err // insufficient arguments
	}
        // other code
}
```

**Comment by bastianccm** [comment]
Hi, I am experiencing the same on a postgres DB, it works fine with sqlite. I can't reproduce it yet on the gorm-playground :(

**Comment by bastianccm** [comment]
Hey, tracked it down, upgrading `gorm.io/driver/postgres` to `v1.5.6` worked for me (it was broken in `v1.5.4`).
@bearatol can you verify if that fixes it for you too?

**Comment by cylussec** [comment]
For me, I got it working with the following versions:

```
	gorm.io/driver/postgres v1.5.6
	gorm.io/gorm v1.25.7-0.20240204074919-46816ad31dde
```

**Comment by bearatol** [comment]
@bastianccm Oh, thank you! I'll know that, but I've already changed my solution.

**Comment by Hareis** [comment]
i have a some problem
