### ISSUE TITLE
 Custom Naming Strategy - not unique table names

### ISSUE THREAD

**Issue by f3oall** [go-gorm/gorm#6833]
## Your Question

When I implement custom `Namer` interface for [NamingStrategy ](https://gorm.io/docs/gorm_config.html#NamingStrategy)
```go
type Namer interface {  
  TableName(table string) string   
  SchemaName(table string) string  
  ColumnName(table, column string) string  
  JoinTableName(table string) string 
  RelationshipFKName(Relationship) string  
  CheckerName(table, column string) string  
  IndexName(table, column string) string
}
```

`table` parmater is a type name without the package prefix (e.g. `User` instead of `users.User`), so how should I distinguish one table from another?

Also when trying to override table name manually during the query:
```go
db.Table("test").First(&User{})
```
The `table` param is `User` and not the `test`. Is it an expected behaviour?

**Comment by jinzhu** [comment]
> The table param is User and not the test. Is it an expected behaviour?

No, it should be `test`

> table parmater is a type name without the package prefix (e.g. User instead of users.User), so how should I distinguish one table from another?

We don't care which package is it from, if package distinction is important in your case, perhaps you want to refer to https://gorm.io/docs/conventions.html#TableName

**Comment by f3oall** [comment]
> No, it should be test

Should I open a bug report then?
