### ISSUE TITLE
Unexpected Unscoped behavior

### ISSUE THREAD

**Issue by ksrnnb** [go-gorm/gorm#6847]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/697
## Description

I would like to hard delete if the flag is true, as in the code below, but the second Delete statement does not work correctly.
Why is this happening?　What can I do to avoid this?
### code
```go
if tc.shouldHardDelete {
	tx = tx.Unscoped()
}

// delete pets separately to delete pets' association
if err := tx.Select(clause.Associations).Delete(&user.Pets).Error; err != nil {
	t.Errorf("Failed, got error: %v", err)
}

if err := tx.Select(clause.Associations).Delete(&user).Error; err != nil {
	t.Errorf("Failed, got error: %v", err)
}
```

**Comment by a631807682** [comment]
https://gorm.io/docs/method_chaining.html#Reusability-and-Safety
```go
tx = tx.Unscoped().Session(&gorm.Session{})
```
