### ISSUE TITLE
gorm 分页10,10 查询出的数据 与sql查询出来的数据不一样

### ISSUE THREAD

**Issue by 669514210** [go-gorm/gorm#6857]
![image](https://github.com/go-gorm/gorm/assets/84845924/e46169d7-2c6c-43b8-aec2-52963097597b)
![image](https://github.com/go-gorm/gorm/assets/84845924/37d259c6-dc49-4a45-b22f-73a42dca8d5e)
![image](https://github.com/go-gorm/gorm/assets/84845924/abc651d5-6826-4172-a650-a8040e654235)
好几种方式都用过了， 查询结果就是有问题

**Comment by jasonchuan** [comment]
try to add order by  field.  or  use  Limit(XX) and   Offset(XX)

**Comment by songhaozhan** [comment]
我也遇到可这种问题，怎么解决

**Comment by jasonchuan** [comment]
排序了么？

**Comment by songhaozhan** [comment]
> > 我也遇到可这种问题，怎么解决
> > "github.com/jinzhu/gorm"
> > _ "github.com/jinzhu/gorm/dialects/mysql"
> 
> ![image](https://private-user-images.githubusercontent.com/84845924/328775175-ce6eb17d-b37f-428a-b16d-b1ce4fec5a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjg2NzYsIm5iZiI6MTcxODI2ODM3NiwicGF0aCI6Ii84NDg0NTkyNC8zMjg3NzUxNzUtY2U2ZWIxN2QtYjM3Zi00MjhhLWIxNmQtYjFjZTRmZWM1YTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA4NDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNWNkOWJlNTY0ZmE1MDFiZGE2YzQwNzM0YTE2Y2NiZDgxYmFhNWViNDBhOWY3MTBkYjRjMTBmYmMzNWI5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IEp_KDQvK30IJz36lh3ubeXpB6EwNObRwV9j7MERbHY) 安装旧版本的， 不要用gorm官网的

你的是哪个版本

**Comment by 669514210** [comment]
> > > 我也遇到可这种问题，怎么解决
> > > "github.com/jinzhu/gorm"
> > > _ "github.com/jinzhu/gorm/dialects/mysql"
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/84845924/328775175-ce6eb17d-b37f-428a-b16d-b1ce4fec5a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjg2NzYsIm5iZiI6MTcxODI2ODM3NiwicGF0aCI6Ii84NDg0NTkyNC8zMjg3NzUxNzUtY2U2ZWIxN2QtYjM3Zi00MjhhLWIxNmQtYjFjZTRmZWM1YTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA4NDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNWNkOWJlNTY0ZmE1MDFiZGE2YzQwNzM0YTE2Y2NiZDgxYmFhNWViNDBhOWY3MTBkYjRjMTBmYmMzNWI5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IEp_KDQvK30IJz36lh3ubeXpB6EwNObRwV9j7MERbHY) 安装旧版本的， 不要用gorm官网的
> 
> 你的是哪个版本

"github.com/jinzhu/gorm"
_ "github.com/jinzhu/gorm/dialects/mysql"
安装这两个就可以
