### ISSUE TITLE
Upgrade 1.25.5->1.25.7: AutoMigrate returns the error "insufficient arguments"

### ISSUE THREAD

**Issue by todeadarius** [go-gorm/gorm#6886]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

**Comment by ReeseWang** [comment]
I'm using the postgres backend and ran into this error. Updating `gorm.io/driver/postgres` from `v1.5.4` to `v1.5.7` seems to resolve the issue.

**Comment by zieen** [comment]
> v1.5.7

gorm.io/driver/postgres v1.5.9
gorm.io/gorm v1.25.12

Here is my version, and it still has this error  pq: got 2 parameters but the statement requires 1
