### ISSUE TITLE
Support duckdb

### ISSUE THREAD

**Issue by CC-Cheunggg** [go-gorm/gorm#6896]
## Support duckdb
Support duckdb

**Comment by HudsonAfonso** [comment]
news?

**Comment by muety** [comment]
Would love to see a DuckDB integration for GORM!

**Comment by fnicastri** [comment]
I agree

**Comment by lllwan** [comment]
+10000000000

**Comment by jinzhu** [comment]
We would be glad to support this database if someone can take responsibility for maintaining the corresponding driver. Unfortunately, I don’t have the bandwidth to implement this support myself.

**Comment by lllwan** [comment]
@jinzhu There seems to be a good implementation here：https://github.com/greysquirr3l/gorm-duckdb-driver
The author hopes to become an official driver。Can you provide support and accelerate progress
