### ISSUE TITLE
GORM save to map causes crash when model type includes primary key field (solution shown)

### ISSUE THREAD

**Issue by ccrenshawSSS** [go-gorm/gorm#6903]
When using the save to map feature, and specifying a model type that includes the table's PK, the code always panics.
When the model type does not include the PK column, it works.
<br>
Line 234 in FindInBatches() executes code to deal with the PK, calling line 462 in setupValuerAndSetter().
Line 462 in setupValuerAndSetter() is the culprit. It invokes v.Field() assuming v is the struct instance being populated, but in this case v is the map (see the three attached screen shots).
Line 1278 in reflect.Field() is being asked to look at a field in the provided struct, but it's not a struct, it's a map.
<br>
This fails (after returning from the anonymous function and landing back in FindInBatches):
<code>
    type Id struct {
        Id string  // This maps to the table PK
     }
     db.Model(&**Id**{}).Table("table_with_id_as_pk").Where(find).FindInBatches(&rows, 500, 
        func(db *gorm.DB, batchID int) error {
             for _, row := range rows {
                 ...
             }
             return nil
        })
</code>
This works:
<code>
     type OtherCol struct {
        OtherCol string
     }
    db.Model(&**OtherCol**{}).Table("table_with_id_as_pk").Where(find).FindInBatches(&rows, 500, 
        func(db *gorm.DB, batchID int) error {
                for _, row := range rows {
                    ...
                }
                return nil
        })
</code>
As identified in a separate ticket is the apparent bug that requires any model object at all, when a map is used as a destination.
Screenshots:
<img width="974" alt="Screen Shot 2024-03-15 at 8 19 31 AM" src="https://github.com/go-gorm/gorm/assets/119428464/bd126fcb-8aef-4f14-8c93-9b831a874278">

<img width="633" alt="Screen Shot 2024-03-15 at 8 06 33 AM" src="https://github.com/go-gorm/gorm/assets/119428464/708179c5-9bef-4879-a2d7-9d69f6166b9a">

<img width="486" alt="Screen Shot 2024-03-15 at 8 07 01 AM" src="https://github.com/go-gorm/gorm/assets/119428464/1ab505b5-35ec-4c6b-979a-72cb6d10e6bd">

**Comment by philhuan** [comment]
I don't see the operation of save to map in the demo? @ccrenshawSSS
