### ISSUE TITLE
Why does db.RowsAffected return 0 after the data is updated?

### ISSUE THREAD

**Issue by Fantomo** [go-gorm/gorm#6912]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

### After successfully updating data using Updates, RowsAffected returns 0
```go
db := mysql.DB.Model(&User{}).Where("deleted = 0 and id = ?", id).Updates(map[string]interface{}{"updated_time": time.Now()})
db.RowsAffected
```

**Comment by gg1229505432** [comment]
I try this func, I made it.  this is func:

type User struct {
	ID          uint
	Name        string
	UpdatedTime time.Time `json:"updated_time"`
}

func main() {
	// 设置数据库连接信息
	dsn := "root:pwd@tcp(localhost:3306)/meeting_as?charset=utf8mb4&parseTime=True&loc=Local"

	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}

	fmt.Println("Database connected successfully!")

	err = db.AutoMigrate(&User{})
	if err != nil {
		panic("failed to migrate database")
	}

	tx := db.Model(&User{}).Where("id = ?", 2).Updates(map[string]interface{}{"updated_time": time.Now()})
	affected := tx.RowsAffected
	fmt.Println(affected)
}

**Comment by Fantomo** [comment]
> I try this func, I made it. this is func:
> 
> > type User struct {
> > ID          uint
> > Name        string
> > UpdatedTime time.Time `json:"updated_time"`
> > }
> 
> > func main() {
> > dsn := "root:pwd@tcp(localhost:3306)/meeting_as?charset=utf8mb4&parseTime=True&loc=Local"
> > db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
> > if err != nil {
> > panic("failed to connect database")
> > }
> > fmt.Println("Database connected successfully!")
> > err = db.AutoMigrate(&User{})
> > if err != nil {
> > panic("failed to migrate database")
> > }
> > tx := db.Model(&User{}).Where("id = ?", 2).Updates(map[string]interface{}{"updated_time": time.Now()})
> > affected := tx.RowsAffected
> > fmt.Println(affected)
> > }

Thanks, the problem has been solved.

**Comment by Fantomo** [comment]
> maybe your column name is wrong ( updated_time but update_time ) mybe your column type is not time.Time

Thanks, the problem has been solved.

**Comment by Fantomo** [comment]
not a bug
