### ISSUE TITLE
升级gorm 使用postgres后报错 LastInsertId is not supported by this driver

### ISSUE THREAD

**Issue by 943885179** [go-gorm/gorm#6926]
原来使用正常，版本为
gorm.io/gorm v1.23.8
gorm.io/driver/postgres v1.3.9
升级后
gorm.io/gorm v1.25.8
gorm.io/driver/postgres v1.5.7
就报错了LastInsertId is not supported by this driver，
无法插入数据

**Comment by 943885179** [comment]
https://github.com/go-gorm/playground/issues/708

**Comment by jinzhu** [comment]
Upgrade GORM to v1.25.9

**Comment by 943885179** [comment]
![image](https://github.com/go-gorm/gorm/assets/27066652/f659673a-6ad6-4b79-9426-7faffc97cf56)
create 正常可以了，但是先求和再更新还是存在问题，可以看https://github.com/go-gorm/playground/issues/708复现

**Comment by adon68** [comment]
如果使用的是 Postgresql  检查是否设置 WithoutReturning  true   这回导致插入记录后  不会返回生成ID,导致插入失败.

这是我遇到的LastInsertId 问题
