### ISSUE TITLE
postgres use gorm v1.25.9   生成的update语句有误

### ISSUE THREAD

**Issue by 943885179** [go-gorm/gorm#6929]
升级1.25.9后，还存在先求数量再更新生成的sql异常情况，案例请看问题二
https://github.com/go-gorm/playground/issues/708
最终生成的sql为
UPDATE "test" SET "a"='222' FROM "test" WHERE a ='111'
ERROR: table name "test" specified more than once (SQLSTATE 42712)

**Comment by a631807682** [comment]
https://gorm.io/docs/method_chaining.html#New-Session-Methods

**Comment by Hareis** [comment]
请问一下你是怎么解决的 @a631807682

**Comment by 943885179** [comment]
使用 db = db.Session(&amp;bgorm.Session{}) 在执行count()或者其他查询操作前，设置session就可以了&nbsp;


暧昧…无言以对
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月10日(星期三) 中午12:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [go-gorm/gorm] postgres use gorm v1.25.9   生成的update语句有误 (Issue #6929)














 
请问一下你是怎么解决的 @a631807682
