### ISSUE TITLE
Support cloudflare D1 database

### ISSUE THREAD

**Issue by iflamed** [go-gorm/gorm#6940]
## Describe the feature

Cloudflare D1 is GA now, could support it ?

## Motivation

Cloudflare D1 is Sqlite based, and have api to access it.
D1: https://developers.cloudflare.com/d1/
D1 API: https://developers.cloudflare.com/api/operations/cloudflare-d1-create-database

## Related Issues

Not found any issue.

**Comment by kofj** [comment]
I implement a driver https://github.com/kofj/gorm-driver-d1

**Comment by jinzhu** [comment]
Hi @kofj 

Thank you for your contribution, you can add it to the list https://gorm.io/community.html#Open-Sources
