### ISSUE TITLE
Unexpected SQL Query Generation with Consecutive First Calls

### ISSUE THREAD

**Issue by SolisAmicus** [go-gorm/gorm#6964]
## Description
I am encountering an issue where consecutive calls to the First method generate a SQL query with duplicated conditions. This seems to happen under specific circumstances described below.

## Steps to Reproduce

1. Perform a First call with an integer parameter:
```go
db.First(&user, 1)
log.Println(user)
```
2. Immediately after, perform another First call with a string parameter:
```go
db.First(&user, "1")
log.Println(user)
```
3. Observe the generated SQL for the second call.

## Expected Behavior
I expect each call to First to generate an independent SQL query, specifically:
The first call should generate:
```sql
SELECT * FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` LIMIT 1
```
The second call should generate:
```sql
SELECT * FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` LIMIT 1
```

## Actual Behavior
The second First call generates a SQL query with duplicated conditions:
```sql
SELECT * FROM `users` WHERE `users`.`id` = 1 AND `users`.`id` = 1 ORDER BY `users`.`id` LIMIT 1
```

## Additional Context

- GORM: 1.25.9
- MySql: 8.0.36 for Win64 on x86_64
- Go: 1.20.6

## Potential Causes
I suspect there might be a bug in how GORM handles or caches query parameters, especially when different types of parameters are used consecutively. It's unclear why the condition would duplicate in the query builder.

## Request
I would appreciate any insights or suggestions on whether this is expected behavior under certain conditions or if it's indeed an issue that needs addressing. Thank you for your assistance!

**Comment by ivila** [comment]
Maybe is work as expected?
add one line between the two calls will solve your `Immediately after` problem:
```golang
user.ID = 0
```

**Comment by SolisAmicus** [comment]
```go
db.First(&user, 1)
log.Println(user)
user.ID = 0
db.First(&user, "1")
log.Println(user)
```

Indeed get the expected results

Reason: When executing a query like db.First(&user, 1), the field ID of the user structure is filled with values retrieved from the database. If the same user instance is used again in consecutive queries without resetting its state, such as if user.ID has been set to a specific non-zero value, GORM may treat this ID value as an implicit query condition.

Thank you！

**Comment by SolisAmicus** [comment]
> Maybe is work as expected? add one line between the two calls will solve your `Immediately after` problem:
> 
> ```go
> user.ID = 0
> ```

```go
db.First(&user, 1)
log.Println(user)
user.ID = 0
db.First(&user, "1")
log.Println(user)
```
Indeed get the expected results！

Reason: When executing a query like db.First(&user, 1), the field ID of the user structure is filled with values retrieved from the database. If the same user instance is used again in consecutive queries without resetting its state, such as if user.ID has been set to a specific non-zero value, GORM may treat this ID value as an implicit query condition.

Thank you!
