### ISSUE TITLE
GetIndexes not implemented

### ISSUE THREAD

**Issue by newtonnthiga** [go-gorm/gorm#6975]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/720

## Description
Hello

`GetIndexes` method on `Migrator()` always returns and error `not support` and looking at https://github.com/go-gorm/gorm/blob/d0b4ceb726f254599c250df2eb7ee9bb86d8a68a/migrator/migrator.go#L983-L986 it doesn't look like it's implemented. Is this functionality offered anywhere else? 

Thank you

**Comment by newtonnthiga** [comment]
Thanks for the quick reply. I am currently using [go-gorm-spanner](https://github.com/googleapis/go-gorm-spanner), does this then mean that GetIndexes is not implemented in go-gorm-spanner?

**Comment by gg1229505432** [comment]
emmmm, I don't know because I didn't use it. 
A new open source code maybe have many bugs that will be happend while running code.

**Comment by gg1229505432** [comment]
@jinzhu you can close this issues
