### ISSUE TITLE
查找不到数据的时候，err与gorm.ErrRecordNotFound比较的结果是false

### ISSUE THREAD

**Issue by kkb-1** [go-gorm/gorm#6980]
当我查找不到数据的时候，这里的err变量打印出来的信息是"record not found"，但是为什么err与gorm.ErrRecordNotFound比较的结果是false，求解答
func (u User)Exist(username string) (bool, error) {
	err := db.Where("username = ?", username).Not("level = ?", -1).First(&User{}).Error
	if err != nil {

		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, nil
		}
		
		return false, err
	}

	return true, nil
}

**Comment by gg1229505432** [comment]
I test, the code : 
`errors.Is(err, gorm.ErrRecordNotFound)`
is true

**Comment by TENX-S** [comment]
Same issue here
