### ISSUE TITLE
Disturbing interface

### ISSUE THREAD

**Issue by fulldump** [go-gorm/gorm#7022]
Redefine the extremely wide used `Writer` interface does not make the best of the experiences for the developer:

```go
type Writer interface {
	Printf(string, ...interface{})
}
```
https://github.com/go-gorm/gorm/blob/master/logger/logger.go#L49-L53

Any plans to have a simpler logger constructor? or even use the most recent structured log from stdlib?

**Comment by ivila** [comment]
@fulldump You can just redefined the whole logger and replace the default one.

The logger must match the interface defined here: https://github.com/go-gorm/gorm/blob/5e599a07ec6aacd85b7806805908c4a78fa0e5ce/logger/logger.go#L63

You can set your own logger by setting the Logger value in gorm.Config: https://github.com/go-gorm/gorm/blob/5e599a07ec6aacd85b7806805908c4a78fa0e5ce/gorm.go#L30

**Comment by loeffel-io** [comment]
The logger interface design is disadvantageous. I don't want to rewrite the whole logger logic only to add some logger fields.
It would be really helpful to update the Writer interface to something like

Writer 
    Info(ctx, ...)
    Warn(ctx, ...)

and call the correct log level writer methods with the logger ctx
