### ISSUE TITLE
Error: simple protocol queries must be run with client_encoding=UTF8

### ISSUE THREAD

**Issue by titogeorge** [go-gorm/gorm#7043]
We have a one-time query failure with an error - `simple protocol queries must be run with client_encoding=UTF8`
Query is `SELECT * FROM "configs" LIMIT 1`

The query is generated from the gorm's AutoMigrate method. Has anyone faced this? This happened only once, it is not reproducible in the same system. Also note that before this error, AutoMigrate created a few tables successfully. 

Versions: 
	gorm.io/driver/postgres v1.5.7
	gorm.io/gorm v1.25.10

postgres - 16.3.0

**Comment by 100yang** [comment]
@titogeorge hello,I have also encountered this problem. the simplest way is to add ` client_encoding=UTF8`, But i would like to ask if you have solved this problem and found the cause ?
