### ISSUE TITLE
Alias for AutoMigrate

### ISSUE THREAD

**Issue by BreathXV** [go-gorm/gorm#7048]
## Describe the feature
Have another alias for `AutoMigrate` to make it easier to understand what the function does for newcomers. Having an alias such as `SyncSchema`.

## Motivation
Was recently working on a project and despite following the documentation posted, it was confusing seeing `AutoMigrate` being used but as it does not have any hint that it creates the tables, it left me baffled for a while.

## Related Issues
N/A

**Comment by jinzhu** [comment]
Let's work together to improve the documentation. More APIs are not necessarily better for the project's development and can be ambiguous.
