### ISSUE TITLE
Release Savepoint 

### ISSUE THREAD

**Issue by Asarew** [go-gorm/gorm#7049]
## Your Question

Why doesn't gorm support `RELEASE SAVEPOINT`? it allows the DB to free up resources by rolling the changes into the parent transaction/savepoint. As gorm implements nested transaction with the use of savepoints i think it's highly advisable to automatically release a nested savepoint in [*DB.Transaction](https://pkg.go.dev/gorm.io/gorm#DB.Transaction) logic.

## Expected answer
I expected to have automatic savepoint release functionality inside the transaction handler or atleast to have a method `Release(name string) *DB`.

**Comment by Asarew** [comment]
@jinzhu if you would agree i can attempt to make a PR for this

**Comment by jinzhu** [comment]
It seems like a valuable feature. Thank you for your contribution.

**Comment by Asarew** [comment]
> It seems like a valuable feature. Thank you for your contribution.

i also didn't see this comment for some reason so if this is actually still open, i can try to create a PR. lmk.
