### ISSUE TITLE
duplicate join clause when using scan() + count(), find() + count() is normal

### ISSUE THREAD

**Issue by Cirooo** [go-gorm/gorm#7079]
## Description
```go
        var count int64
	var tempList []int
	test := global.GetTransaction().Table(e.TableName() + " as sr").Joins("left join table_s_m sm on sr.s_id = sm.s_id ")
	err2 := test.Distinct("sr.s_id ").Order("sr.s_id desc").Offset((current - 1) * pageSize).Limit(pageSize).Find(&tempList).Offset(-1).Limit(-1).Count(&count).Error
``` 
In the example above, it is **Find(), and it's normal**, but it **fails** if I replace it with **Scan()** and it would be this SQL statement: 
SELECT COUNT(DISTINCT(`sr`.`s_id`)) FROM table_s_r as sr left join table_s_m **sm** on sr.s_id= sm.s_id left join table_s_m **sm** on sr.s_id= sm.s_id 
And you can notice that there's a duplicate 'left join' in it. 
Then mysql throws an error:  [1066] [42000]: Not unique table/alias: 'sm'

**Comment by prabalbansal6183** [comment]
yeah i also started facing this same issue after upgrading gorm, it used to work fine before. 
I am not sure why it's happening but (find + count) works fine while (scan + count) don't. 
here are my package versions (if of any help):- 
gorm.io/driver/postgres v1.5.6
gorm.io/gorm v1.25.11
