### ISSUE TITLE
sql server中使用Count函数报语法错误

### ISSUE THREAD

**Issue by GoldBaby5511** [go-gorm/gorm#7087]
你好，我的使用方式如下
err = e.Orm.Debug().Model(&data).
		Scopes(
			cDto.MakeCondition(c.GetNeedSearch()),
			cDto.Paginate(c.GetPageSize(), c.GetPageIndex()),
			actions.Permission(data.TableName(), p),
		).
		Find(list).Limit(-1).Offset(-1).
		Count(count).Error
	if err != nil {
		e.Log.Errorf("Service GetSysApiPage error:%s", err)
		return err
	}
在最后统计Count时最终的执行语句是：SELECT count(*) FROM "sys_api" WHERE "sys_api"."deleted_at" IS NULL ORDER BY "id" 
这在mysql上是可以执行通过的，但是在sql server上报错：“ORDER BY 子句中的列 "sys_api.id" 无效，因为该列没有包含在聚合函数或 GROUP BY 子句中。”，如果没有 ORDER BY 的话在两种数据库上都是可以通过，这个要怎么处理
谢谢

**Comment by Cirooo** [comment]
gorm不会无端加入这个order字句，你应该检查自己的调用链。

**Comment by GoldBaby5511** [comment]
> gorm不会无端加入这个order字句，你应该检查自己的调用链。

我对gorm还不是很熟悉，order字段可能是 Limit(-1).Offset(-1) 内加入的，关键是最终的sql语句 SELECT count(*) FROM "sys_api" WHERE "sys_api"."deleted_at" IS NULL ORDER BY "id" mysql下是可以执行的，mssql不行，是不是应该对不同数据库做个适配区分一下语法
