### ISSUE TITLE
How to modify sql before execute it and after build it?

### ISSUE THREAD

**Issue by QeelinDarly** [go-gorm/gorm#7092]
## Your Question
I want to modify sql which created by gorm before executed. How can I do?

I tried to create a "before" callback method, but it will be executed before create sql. I can't get sql from "originalSQL := db.Statement.SQL.String()". If you have any idea, please help.

**Comment by a631807682** [comment]
use `Dialector` interface
refer to https://github.com/go-gorm/sharding
