### ISSUE TITLE
AutoMigrate method creates incorrect index name

### ISSUE THREAD

**Issue by y-okuno** [go-gorm/gorm#7100]
## Description:
I encountered an issue with GORM's `AutoMigrate` function when upgrading to the latest versions.

**Successful migration with:**
- `gorm.io/driver/postgres v1.4.8`
- `gorm.io/gorm v1.25.5`

**Failed migration with:**
- `gorm.io/driver/postgres v1.5.9`
- `gorm.io/gorm v1.25.10`

In the latest version, it seems that the index name specified in the model is not being respected. The `AutoMigrate` function creates an incorrect index name which leads to a migration failure.

### Steps to Reproduce

1. Use the following versions:
   - `gorm.io/driver/postgres v1.5.9`
   - `gorm.io/gorm v1.25.10`

2. Define the model as follows:
   ```go
   type Master struct {
       ID         uint32 `gorm:"primaryKey"`
       IPv4Prefix string `gorm:"uniqueIndex"`
   }

3. Create the table in PostgreSQL with the following SQL:
```sql
CREATE TABLE public.masters (
    id bigserial NOT NULL,
    ipv4_prefix text NULL,
    CONSTRAINT idx_masters_ipv4_prefix UNIQUE (ipv4_prefix)
);
```

4. Execute AutoMigrate method with the above model.

5. Also tried with the following model definition, but the result was the same:
```go
type Master struct {
    ID         uint32 `gorm:"primaryKey"`
    IPv4Prefix string `gorm:"uniqueIndex:idx_masters_ipv4_prefix"`
}
```

### Expected Behavior
The migration should succeed without errors.

### Actual Behavior
The migration fails with the following error:
```
ERROR: constraint "uni_masters_ipv4_prefix" of relation "masters" does not exist (SQLSTATE 42704)
```

It appears that AutoMigrate is attempting to create a constraint named `uni_masters_ipv4_prefix` instead of respecting the specified `idx_masters_ipv4_prefix` .

### Environment
- GORM version: v1.25.10
- GORM Postgres driver version: v1.5.9
- PostgreSQL version: 13.4
- Go version: 1.21.1

### Additional Context
This issue does not occur with the following versions:

- gorm.io/driver/postgres v1.4.8
- gorm.io/gorm v1.25.5

It seems that the index name specified in the struct tag is not being applied correctly in the latest version.

Thank you for your attention to this issue. Please let me know if you need any further information or assistance in reproducing the issue.

**Comment by dashrews78** [comment]
My team just experienced the same problem.

The constraint is not present because GORM is calculating the name wrong.  I'm also wondering if the dropping of the constraint shouldn't also have `IF EXISTS` as that would have stopped the migration from failing.
