### ISSUE TITLE
Gorm cann't connect Doris

### ISSUE THREAD

**Issue by Cookiery** [go-gorm/gorm#7102]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

Gorm cann't not connect Doris

## Gorm version: 
gorm.io/driver/mysql v1.5.7
gorm.io/gorm v1.25.10
gorm.io/plugin/dbresolver v1.5.0

## example code:
```
Settings.Doris.DSN = fmt.Sprintf(`%v:%v@tcp(%v)/%v?charset=utf8mb4&parseTime=True&loc=Local`,
		Settings.Doris.UserName, Settings.Doris.Password, Settings.Doris.Host, Settings.Doris.DBName)

var DorisDB *gorm.DB
log.Infof("Init doris connection...")
DorisDB, err = gorm.Open(mysql.Open(config.Settings.Doris.DSN), &gorm.Config{Logger: newLogger})
if err != nil {
    return fmt.Errorf("connect doris fail: %s", err.Error())
}
```

error: error connect doris fail: invalid connection

**Comment by n3s0** [comment]
Maybe try taking a look at the mysql driver to see if there's anything missing from this.

https://github.com/go-gorm/mysql
