### ISSUE TITLE
BUG：`PrepareStmt：true` 在 SQL 执行时错误 `PreparedSQL` 会内存泄露

### ISSUE THREAD

**Issue by FreeMasonGalaxy** [go-gorm/gorm#7137]
#### BUG 原因
>**开启预编译后，gorm `(db *PreparedStmtDB) prepare` 会拿预编译语句先到 stmts 查找是否存在预编译 (stmt) 对象，有则直接返回 stmt 对象，无则缓存预编译对象，再缓存预编译语句，`(db *PreparedStmtDB) ExecContext` 有报错则 `delete(db.Stmts, query)` 删除预编译对象，但未删除缓存预编译语句，会造成 gorm 发送预编译通过但 SQL 执行时错误(如不可重复) PreparedSQL 一直增长未释放数据**

#### 版本
+ go：1.22
+ gorm：1.25.8

#### 复现
1. gorm 配置
```go
DB, _= gorm.Open(mysql.New(conf), &gorm.Config{
		PrepareStmt: true,
	})
```
2. 调用创建方法
```go
database.DB.Create(&m)
```

3. 报错
```go
 Duplicate entry
```

#### Gorm 预编译源码

```go
type Stmt struct {
	*sql.Stmt
	Transaction bool
	prepared    chan struct{}
	prepareErr  error
}

type PreparedStmtDB struct {
	Stmts       map[string]*Stmt
	PreparedSQL []string
	Mux         *sync.RWMutex
	ConnPool
}

func NewPreparedStmtDB(connPool ConnPool) *PreparedStmtDB {
	return &PreparedStmtDB{
		ConnPool:    connPool,
		Stmts:       make(map[string]*Stmt),
		Mux:         &sync.RWMutex{},
		PreparedSQL: make([]string, 0, 100),
	}
}

func (db *PreparedStmtDB) GetDBConn() (*sql.DB, error) {
	if sqldb, ok := db.ConnPool.(*sql.DB); ok {
		return sqldb, nil
	}

	if dbConnector, ok := db.ConnPool.(GetDBConnector); ok && dbConnector != nil {
		return dbConnector.GetDBConn()
	}

	return nil, ErrInvalidDB
}

func (db *PreparedStmtDB) Close() {
	db.Mux.Lock()
	defer db.Mux.Unlock()

	for _, query := range db.PreparedSQL {
		if stmt, ok := db.Stmts[query]; ok {
			delete(db.Stmts, query)
			go stmt.Close()
		}
	}
}

func (sdb *PreparedStmtDB) Reset() {
	sdb.Mux.Lock()
	defer sdb.Mux.Unlock()

	for _, stmt := range sdb.Stmts {
		go stmt.Close()
	}
	sdb.PreparedSQL = make([]string, 0, 100)
	sdb.Stmts = make(map[string]*Stmt)
}

func (db *PreparedStmtDB) prepare(ctx context.Context, conn ConnPool, isTransaction bool, query string) (Stmt, error) {
	db.Mux.RLock()
	if stmt, ok := db.Stmts[query]; ok && (!stmt.Transaction || isTransaction) {
		db.Mux.RUnlock()
		// wait for other goroutines prepared
		<-stmt.prepared
		if stmt.prepareErr != nil {
			return Stmt{}, stmt.prepareErr
		}

		return *stmt, nil
	}
	db.Mux.RUnlock()

	db.Mux.Lock()
	// double check
	if stmt, ok := db.Stmts[query]; ok && (!stmt.Transaction || isTransaction) {
		db.Mux.Unlock()
		// wait for other goroutines prepared
		<-stmt.prepared
		if stmt.prepareErr != nil {
			return Stmt{}, stmt.prepareErr
		}

		return *stmt, nil
	}
	_, ok := db.Stmts[query]

	// cache preparing stmt first
	cacheStmt := Stmt{Transaction: isTransaction, prepared: make(chan struct{})}
	// 设置缓存
	db.Stmts[query] = &cacheStmt
	db.Mux.Unlock()
	_, ok = db.Stmts[query]
	// prepare completed
	defer close(cacheStmt.prepared)

	// Reason why cannot lock conn.PrepareContext
	// suppose the maxopen is 1, g1 is creating record and g2 is querying record.
	// 1. g1 begin tx, g1 is requeue because of waiting for the system call, now `db.ConnPool` db.numOpen == 1.
	// 2. g2 select lock `conn.PrepareContext(ctx, query)`, now db.numOpen == db.maxOpen , wait for release.
	// 3. g1 tx exec insert, wait for unlock `conn.PrepareContext(ctx, query)` to finish tx and release.
	stmt, err := conn.PrepareContext(ctx, query)
	if err != nil {
		cacheStmt.prepareErr = err
		db.Mux.Lock()
		delete(db.Stmts, query)
		db.Mux.Unlock()
		return Stmt{}, err
	}
	db.Mux.Lock()
	cacheStmt.Stmt = stmt
	// 设置缓存 SQL
	db.PreparedSQL = append(db.PreparedSQL, query)
	db.Mux.Unlock()

	return cacheStmt, nil
}

func (db *PreparedStmtDB) ExecContext(ctx context.Context, query string, args ...interface{}) (result sql.Result, err error) {
    stmt, err := db.prepare(ctx, db.ConnPool, false, query)
    if err == nil {
       result, err = stmt.ExecContext(ctx, args...)
       if err != nil {
          db.Mux.Lock()
          defer db.Mux.Unlock()
          go stmt.Close()
		  // 删除缓存
          delete(db.Stmts, query)
       }
    }
    return result, err
}
```

**Comment by a631807682** [comment]
`PreparedSQL` stores the key of `Stmts`, which gorm uses only when `PreparedStmtDB Close`.
It is an exported field, is it used elsewhere? Can we remove it? @jinzhu 

https://github.com/go-gorm/gorm/commit/c7667e9299134799da6f16e19eaf50cb8419736f

**Comment by ivila** [comment]
> `PreparedSQL` stores the key of `Stmts`, which gorm uses only when `PreparedStmtDB Close`. It is an exported field, is it used elsewhere? Can we remove it? @jinzhu
> 
> [c7667e9](https://github.com/go-gorm/gorm/commit/c7667e9299134799da6f16e19eaf50cb8419736f)

I think he uses this just trying to avoid deleting keys while iterating, in my opinion, removing the PreparedSQL field and using two iteration is better, just like the following:
```
// and PreparedStmtDB.PreparedSQL should be removed
func (db *PreparedStmtDB) Close() {
	db.mux.Lock()

	keys := make([]string, 0, len(db.Stmts))
	for key := range db.Stmts {
		keys = append(keys, key)
	}
	for _, key := range keys {
		if stmt, ok := db.Stmts[key]; ok {
			delete(db.Stmts, key)
			stmt.Close()
		}
	}

	db.mux.Unlock()
}
```
Should we? @jinzhu @a631807682

**Comment by a631807682** [comment]
> > `PreparedSQL` stores the key of `Stmts`, which gorm uses only when `PreparedStmtDB Close`. It is an exported field, is it used elsewhere? Can we remove it? @jinzhu
> > [c7667e9](https://github.com/go-gorm/gorm/commit/c7667e9299134799da6f16e19eaf50cb8419736f)
> 
> I think he uses this just trying to avoid deleting keys while iterating, in my opinion, removing the PreparedSQL field and using two iteration is better, just like the following:
> 
> ```
> // and PreparedStmtDB.PreparedSQL should be removed
> func (db *PreparedStmtDB) Close() {
> 	db.mux.Lock()
> 
> 	keys := make([]string, 0, len(db.Stmts))
> 	for key := range db.Stmts {
> 		keys = append(keys, key)
> 	}
> 	for _, key := range keys {
> 		if stmt, ok := db.Stmts[key]; ok {
> 			delete(db.Stmts, key)
> 			stmt.Close()
> 		}
> 	}
> 
> 	db.mux.Unlock()
> }
> ```
> 
> Should we? @jinzhu @a631807682

Are you interested in creating a PR for it?

**Comment by ivila** [comment]
Sure, just wait for hours, I will write a PR for it.

**Comment by ivila** [comment]
@a631807682 during my coding, I see another potential bug in the Reset function: https://github.com/go-gorm/gorm/blob/4a50b36f638c6899089e6e3457425528ce693933/prepare_stmt.go#L59-L69
while we prepare a new statement, the new Stmt register itself to the db.Stmt map (with sql.Stmt* field value nil), and unlock the mutex: https://github.com/go-gorm/gorm/blob/4a50b36f638c6899089e6e3457425528ce693933/prepare_stmt.go#L96-L104

which result in a nil pointer error at Reset function call:
```golang
 func (sdb *PreparedStmtDB) Reset() { 
 	sdb.Mux.Lock() 
 	defer sdb.Mux.Unlock() 
  
 	for _, stmt := range sdb.Stmts { 
                // stmt could be nil here
 		go stmt.Close() 
 	} 
 	sdb.PreparedSQL = make([]string, 0, 100) 
 	sdb.Stmts = make(map[string]*Stmt) 
 } 
```
but as what I said, it is just a potential bug(people not likely call Reset and exec SQL concurrently).

**Comment by aveyuan** [comment]
如果你是gorm1迁移到gorm2 PrepareStmt 并没有带来多少速度提升,相反，它带来了内存泄露prepare会在db中一直增长。因为这个开关，导致了我们2次线上故障，建议进行关闭。

**Comment by jinzhu** [comment]
> 如果你是gorm1迁移到gorm2 PrepareStmt 并没有带来多少速度提升,相反，它带来了内存泄露prepare会在db中一直增长。因为这个开关，导致了我们2次线上故障，建议进行关闭。

最新版本的 prepare stmt 带 LRU 的支持，不会无限制的增长

**Comment by ivila** [comment]
> 如果你是gorm1迁移到gorm2 PrepareStmt 并没有带来多少速度提升,相反，它带来了内存泄露prepare会在db中一直增长。因为这个开关，导致了我们2次线上故障，建议进行关闭。

这东西其实主要还是考虑安全性的，跟速度没有关系。

**Comment by aveyuan** [comment]
> > 如果你是gorm1迁移到gorm2 PrepareStmt 并没有带来多少速度提升,相反，它带来了内存泄露prepare会在db中一直增长。因为这个开关，导致了我们2次线上故障，建议进行关闭。
> 
> 这东西其实主要还是考虑安全性的，跟速度没有关系。

GORM1没有批量插入功能得，改造的过程中，肯定是先跑起来，所以GORM1的批量插入会有大量的拼接SQL

**Comment by aveyuan** [comment]
> > 如果你是gorm1迁移到gorm2 PrepareStmt 并没有带来多少速度提升,相反，它带来了内存泄露prepare会在db中一直增长。因为这个开关，导致了我们2次线上故障，建议进行关闭。
> 
> 最新版本的 prepare stmt 带 LRU 的支持，不会无限制的增长

好的，感谢，目前我们先关闭了这个特性，先观望
