### ISSUE TITLE
Joins 必须要写sql语句？好呆的设计啊

### ISSUE THREAD

**Issue by chenyu1990** [go-gorm/gorm#7156]
`db.Joins("Company", db.Where(&Company{Alive: true})).Find(&users)`
的输出结果是 `select ... from sometable Company`

查了不少文章，chatgpt也试试了
有效果的就是 `db.Joins("LEFT JOIN Company ON ...")`
这个好呆
1、Company用字符串输入本身就很呆，不是应该用模型去解析表名吗？
2、ON里的字段不是应该用.Where()方法来拼吗？用字符串来写，还不如.Raw()呢！！！

**Comment by zzhaoh** [comment]
https://gorm.io/zh_CN/docs/preload.html
如果希望使用gorm的join自动拼接，需要你的相关表结构体有关联关系

**Comment by kuangshp** [comment]
> `db.Joins("Company", db.Where(&Company{Alive: true})).Find(&users)` 的输出结果是 `select ... from sometable Company`
> 
> 查了不少文章，chatgpt也试试了 有效果的就是 `db.Joins("LEFT JOIN Company ON ...")` 这个好呆 1、Company用字符串输入本身就很呆，不是应该用模型去解析表名吗？ 2、ON里的字段不是应该用.Where()方法来拼吗？用字符串来写，还不如.Raw()呢！！！

你也可以用`gen`来实现，我代码里面就直接这样干过去
![d16c9489d8fd020ae8a9a76c0bf7937d](https://github.com/user-attachments/assets/7b49e38a-01da-410d-a54e-f8073a5d9064)
