### ISSUE TITLE
gorm gen 生成的 entity, 应该怎么写 hooks 呢?

### ISSUE THREAD

**Issue by seth-shi** [go-gorm/gorm#7161]
* 用了 gen 之后现在生成的目录如下

- do
- entity

* 如果我要写 hooks, 怎么在 entity 目录之外写 hooks 呢

**Comment by seth-shi** [comment]
我是要针对 entity 下的某个模型, 创建的时候要生成 uuid

**Comment by kuangshp** [comment]
> 我是要针对 entity 下的某个模型, 创建的时候要生成 uuid

你那边处理了吗,我也遇到这样的，但是最后用全局插件写的

**Comment by seth-shi** [comment]
没找到解决方法

**Comment by paradox-lab2** [comment]
这在go语言层面上就不支持实现吧，结构体方法只能定义在同一个包内

**Comment by seth-shi** [comment]
> 这在go语言层面上就不支持实现吧，结构体方法只能定义在同一个包内

很多种方式可以实现, 比如提供一个注册方法

```golang


gorm.RegisterHooks(&Model{}, "created", func (m Model) {
      // xxxx
})


gorm.RegisterHooks(&Model{}, func (m Model) {
      m.Saving(function () {
             // xxxx
       })
})

```
