### ISSUE TITLE
How to select all the columns in Join query?

### ISSUE THREAD

**Issue by VetchM** [go-gorm/gorm#7176]
Let's say I want to join query this two tables:

```go
type A struct{
  Name string
  Age int64
}

type B struct{
  Name string
  Email string
}
```

How do I write a join query that returns all columns in both table A and table B without manually selecting all columns myself? I tried this but it only return column in table A:

```go
query.A.WithContext(ctx).LeftJoin(query.B, query.A.Name.EqCol(query.B.Name)).Scan(&infos)
```

**Comment by zcyc** [comment]
@VetchM you can do it like this:
```go
query.A.WithContext(ctx).
  LeftJoin(query.B, query.A.Name.EqCol(query.B.Name)).
  Select(query.A.ALL, query.B.ALL).
  Scan(&infos)
```

**Comment by VetchM** [comment]
> ```go
> type A struct{
>   Name string
>   Age int64
> }
> 
> type B struct{
>   Name string
>   Email string
> }
> 
> type C struct{
>   Name string
>   Age int64
>   BName string
>   Email string
> }
> ```
> 
> @VetchM you can do it like this:
> 
> ```go
> var c C
> query.A.WithContext(ctx).
>   LeftJoin(query.B, query.A.Name.EqCol(query.B.Name)).
>   Select(query.A.ALL, query.B.ALL).
>   Scan(&c)
> ```
> 
> if you need query two name, you can set alias like this:
> 
> ```go
> var c C
> query.A.WithContext(ctx).
>   LeftJoin(query.B, query.A.Name.EqCol(query.B.Name)).
>   Select(query.A.ALL, query.B.Name.As("BName")).
>   Scan(&c)
> ```

Thanks! Close this issue now
