### ISSUE TITLE
Join clause does not implement the clause interface

### ISSUE THREAD

**Issue by gregorgebhardt** [go-gorm/gorm#7188]
## GORM Playground Link

I tried to but running the test.sh in the playground repo returns the error:
```
go: gorm.io/playground imports
        gorm.io/gen/examples: cannot find module providing package gorm.io/gen/examples
```

## Description

When trying to add a join clause to my query via `clause.Join{...}` and later

```
sqlQuery := db.WithContext(ctx).Model(...)
sqlQuery.Clauses(joinClause)
```

The join ends up in a WHERE condition. The problem is that within the function `func (db *DB) Clauses(conds ...clause.Expression) (tx *DB)`, there is a type switch on the elements in `conds`. But since `clause.Join` neither implements the `clause.Interface` nor the `StatementModifier`, it will be put into the `whereConds` slice and ends up in the WHERE conditions...

**Comment by the-maldridge** [comment]
A review bot strikes again...

I ran into this same issue and it was very unclear why it was winding up in where conditions.  For anyone else hitting this there is a specific element in `clause.From` that expects to receive the joins, but this is not obvious from documentation or test cases.
