### ISSUE TITLE
连接PgSql时，DisableAutomaticPing设置为true，但还是会触发--ping命令，并且连接不断开，导致连接数一直在增加

### ISSUE THREAD

**Issue by meichuanneiku** [go-gorm/gorm#7196]
场景：
在使用go-kratos框架中实现一个定时任务，该任务会查询pgsql中的数据，因此会在项目启动时创建pgsql的连接，在连接的配置信息中DisableAutomaticPing设置为true，企图关闭自动ping的功能

问题：
但在运行一段时间（大概1天），发现pg数据库无法连接，就查询数据库的连接状态，发现--ping命令的连接未断开并且数量还一直在增加。之后就尝试修改连接池的数量，不管修改多少，问题仍然存在

使用版本：
go：1.22.4
gorm： 1.25.12

查询数据库连接状态截图：

<img width="601" alt="联想截图_20240918101050" src="https://github.com/user-attachments/assets/485979c9-6677-4b9c-a16c-3f5372968f8f">
<img width="608" alt="联想截图_20240918101418" src="https://github.com/user-attachments/assets/2d7a1d3b-95de-40a3-a08b-40a184b9f64c">

示例代码项目：
https://github.com/meichuanneiku/connentgorm.git

**Comment by meichuanneiku** [comment]
实现了一个测试demo
https://github.com/meichuanneiku/connentgorm.git

**Comment by meichuanneiku** [comment]
项目最终是打包成docker，上传至内网服务器的，截图的内容也是查询服务器地址所得，目前在本地跑了一上午结果并没有ping的命令，那难道会和docker有关系吗？

**Comment by ivila** [comment]
@meichuanneiku 你这样提issue的方式是不正确的，你提的demo也应该是**纯**gorm就可以复现的问题，而不是给出一个使用复杂的巨型框架的demo代码（并且里面还没有明显的gorm是如何连接的说明）。
你应该给出一个**纯**gorm就可复现的demo，这样大家才能快速地帮你找到问题并解决，而不是先浪费时间去找你的一大堆信息里面有哪些是有用的（更别说你的demo里面还引入了一大堆额外变量）
