### ISSUE TITLE
 add partition Error 1564 (HY000): This partition function is not allowed

### ISSUE THREAD

**Issue by wangsiqi2015** [go-gorm/gorm#7197]

**Comment by wangsiqi2015** [comment]
version：gorm.io/gorm v1.25.12
sql：alter table instance  ADD PARTITION (PARTITION yyy VALUES IN ('yyy') ENGINE = InnoDB);
comment：this sql can execute on dbeaver，but cannot be execute by gorm

**Comment by jinzhu** [comment]
the error was happened on the db side.
