### ISSUE TITLE
MariaDB database batch insert incompatibility issue

### ISSUE THREAD

**Issue by Heir-o** [go-gorm/gorm#7203]
MariaDB database is fully compatible with MySQL sql, but there will be problems when doing batch insert Create. It seems that sql will splice  RETURNING `primary key` after sql. It will not appear in MySQL database, but will report an error in MariaDB database. By default, there is   RETURNING `primary key`

**Comment by Heir-o** [comment]
![PixPin_2024-09-23_20-23-13](https://github.com/user-attachments/assets/53b1ab13-2de3-42fc-9e7f-1e97715bfad9)
![PixPin_2024-09-23_20-24-07](https://github.com/user-attachments/assets/5bb7186e-4f51-4be5-9636-763a1483d049)

**Comment by ivila** [comment]
@Heir-o Try updating the version of your mariadb server, the **returning** phase was added in [MariaDB 10.5.0](https://mariadb.com/kb/en/insertreturning/)
