### ISSUE TITLE
Add support for suppressing logs due to context cancellation

### ISSUE THREAD

**Issue by kodowerd** [go-gorm/gorm#7218]
## Describe the feature

Logs due to context cancellation are currently logged at error level.
As a consequence of this, our logs get full due to query cancellation by web clients.
Can we have a flag that disables err logs triggered due to conext cancellation.
Alternatively, is there a way to  suppress these on my end? Thanks!

## Motivation

Reference to our error sentries for the kind of errors I'm trying to suppress
![sentries](https://github.com/user-attachments/assets/d5d36d73-13e9-4f4e-88a3-4368947b95e4)

**Comment by ivila** [comment]
@kodowerd I think you put the issue in wrong place, you should raise the issue at https://github.com/moul/zapgorm2
