### ISSUE TITLE
Save issue 

### ISSUE THREAD

**Issue by hn-n** [go-gorm/gorm#7219]
## Description

Unexpected behavior from `Save`

### Code: case 1
```
result := Db.Save(&services[i])
if result.Error != nil {
    fmt.Println("Error:", result.Error)
    return
}
```
### Result
results: it inserts a new record while the ID is not null.

### Code: case 2
```
result :=Db.Save([]Services{service[i]})
if result.Error != nil {
    fmt.Println("Error:", result.Error)
    return
}

### Result
```
it updates, but when updating the struct as a slice, it resets the `created_at` of the record `0001-01-01 03:06:52+03:06:52`

i'd like to help with this issue!

**Comment by franciscocpg** [comment]
I have the same issue.

The first call to Save, sets the `created_at` and `updated_at`, but the second call changes `created_at` with a null value. The second call should not add the `created_at` field to the update selections.
