### ISSUE TITLE
How to write group by for multiple fields

### ISSUE THREAD

**Issue by wlbwlbwlb** [go-gorm/gorm#7245]
## The document you expected this should be explained

like this?
`db.Group("age,score")`

**Comment by alex-guoba** [comment]
Group belongs to Chaining Method.

` db.Group("age").Group("score") `

**Comment by sandeepchowdary7** [comment]
Hello @wlbwlbwlb 

GORM's Group method allows grouping by multiple fields by passing a comma-separated string of field names. Here's an example:

```
var results []YourModel
db.Model(&YourModel{}).
    Select("field1, field2, COUNT(*) as count").
    Group("field1, field2").
    Find(&results)
```
In this query, field1 and field2 are the fields you want to group by, and count will hold the count of records for each group.

Cheers!!
