### ISSUE TITLE
postgreSQL Insert []string construct insert statement failed：INSERT INTO "tags" ("tag_names") VALUES (('tag1','tag2','tag3')) RETURNING "id"，It should be:INSERT INTO "tags" ("tag_names") VALUES (ARRAY['tag1', 'tag2', 'tag3']) RETURNING "id";

### ISSUE THREAD

**Issue by zyylhn** [go-gorm/gorm#7250]
`type Tag struct {
	ID       uint     `gorm:"primaryKey"`
	TagNames []string `gorm:"type:text[]"` // 指定为 PostgreSQL 的文本数组类型
}

tag := Tag{
		TagNames: []string{"tag1", "tag2", "tag3"},
	}

	result := db.Create(&tag)
	if result.Error != nil {
		t.Fatalf("failed to create tag: %v", result.Error)
	}

output:

[1.699ms] [rows:0] INSERT INTO "tags" ("tag_names") VALUES (('tag1','tag2','tag3')) RETURNING "id"
    scan_result_test.go:101: failed to create tag: ERROR: column "tag_names" is of type text[] but expression is of type record (SQLSTATE 42804)
--- FAIL: TestTest (0.00s)
`

**Comment by aleimu** [comment]
import (
  "github.com/google/uuid"
  "github.com/lib/pq"
)

type Post struct {
  ID     uuid.UUID `gorm:"type:uuid;default:uuid_generate_v4()"`
  Title  string
  Tags   pq.StringArray `gorm:"type:text[]"`
}


use pq.StringArray!
