### ISSUE TITLE
When using the "gen" to generate the code, problem occurred. seems the version problem

### ISSUE THREAD

**Issue by abanban999** [go-gorm/gorm#7258]
## Description

I use the "gen" to generate the code about accessing to the database.

But when execute the "gen", problem occurred:

```
pkg/mod/gorm.io/plugin/dbresolver@v1.5.0/dbresolver.go:147:5: unknown field PreparedSQL in struct literal of type gorm.PreparedStmtDB
```

construct "gorm.PreparedStmtDB" with field "PreparedSQL"
but in my version there's no field name "PreparedSQL" in "gorm.PreparedStmtDB"

here's my version number in trouble
gorm.io/gen v0.3.26
gorm.io/gorm v1.25.12

And after  I change the gorm version into v1.25.9, problem solved.

**Comment by wangxin688** [comment]
i met the same issue when update gorm to v1.25.11, when I downgrade version to 1.25.10, issue was resolved. but it can not be reproduced again after upgrade back to v1.25.11 
working fine with following version dependencies
	gorm.io/driver/postgres v1.5.9
	gorm.io/gen v0.3.26
	gorm.io/gorm v1.25.11
	gorm.io/plugin/dbresolver v1.5.0
