### ISSUE TITLE
操作达梦数据库插入数据报错不存在IDENTITY列

### ISSUE THREAD

**Issue by YiTianChiSiDun1** [go-gorm/gorm#7260]
## Your Question
操作达梦数据库插入数据报错不存在IDENTITY列，但是这个表中并没有自增字段。而且为什么他会自动执行 ：SET IDENTITY_INSERT "device_group" ON;

Error -2717: 第1 行附近出现错误: 表[device_group]不存在IDENTITY列

**Comment by YiTianChiSiDun1** [comment]
目前的话只有执行原生sql才能避免这个问题

**Comment by YiTianChiSiDun1** [comment]
找到了一种比较好的解决办法，就是给字段 tag 加上 autoIncrement:false强制给他关了就不会报错了

**Comment by mimicode** [comment]
https://github.com/go-gorm/gorm/issues/7246
原因是这个

**Comment by jinzhu** [comment]
可以修改下达梦 diver 来适配一下达梦的逻辑
