### ISSUE TITLE
GORM GaussDB Driver

### ISSUE THREAD

**Issue by okyer** [go-gorm/gorm#7270]
## Describe the feature

我实现了GORM适配GaussDB数据库的驱动，欢迎大家使用。[gorm4gaussdb](https://github.com/okyer/gorm4gaussdb)

## Motivation

[华为云数据库 GaussDB](https://support.huaweicloud.com/gaussdb/index.html) 是华为自主创新研发的分布式关系型数据库。该产品具备企业级复杂事务混合负载能力，同时支持分布式事务，同城跨AZ部署，数据0丢失，支持1000+的扩展能力，PB级海量存储。同时拥有云上高可用，高可靠，高安全，弹性伸缩，一键部署，快速备份恢复，监控告警等关键能力。

[GORM开源软件For Huawei开发任务的心得体会](https://bbs.huaweicloud.com/blogs/439075)

**Comment by jinzhu** [comment]
Hi @okyer 

Thank you for your contribution, you can create a PR to update this page https://gorm.io/community.html#Open-Sources

Thank you.
