### ISSUE TITLE
OpenGauss DB support

### ISSUE THREAD

**Issue by XujiaFu-0609** [go-gorm/gorm#7307]
Hi,at present, our projects using gorm need to use Huawei OpenGauss db, but there is no official driver supporting OpenGauss at present, is there any chance to support it? Looking forward to your reply

**Comment by jinzhu** [comment]
Sorry, I currently don’t have the capacity to implement support for OpenGauss. However, I’d be happy if the community could take on this effort. The implementation can either be maintained under the GORM organization or independently. We will add relevant links to recommend it.

**Comment by southwolf** [comment]
@XujiaFu-0609 I believe OpenGauss should be basically compatible with PostgreSQL, have you ever tried to set it up as PG? Did you encounter any errors or failures?
