### ISSUE TITLE
json type in postgresql

### ISSUE THREAD

**Issue by ghost** [go-gorm/gorm#82]
Hi, can you please suggest me the correct way to declare a field in a struct that is of  `json` type in postrgresql?

Thank you

**Comment by collinglass** [comment]
the example @thrisp used is not a valid example of this working. JSON/JSONB fields are used for structs , maps, slices and not as a string. I think this should be looked at more.

The way I do it in my code using raw golang sql package:

```
tagsJSON, err := json.Marshal(moment.Tags)
if err != nil {
	return context.NewErrorJSON(ds.Col(), err)
}

// Update the database
err = stmt.QueryRow(
	moment.Id,
	...
	tagsJSON,
}
```

**Comment by rookie7799** [comment]
+1

**Comment by wenweih** [comment]
Like that:
```golang
type BtcVin struct {
	gorm.Model
	Txid             string `gorm:"type:varchar(100);not null"`
	vout             int32
	Sequence         int32
	Witness          pq.StringArray  `gorm:"type:varchar(200)[]"`
	ScriptSig        json.RawMessage `sql:"type:json"`
	BtcTransactionID int             `gorm:"index"`
}

func GetBtcVin(vin btcjson.VinM) *LtcVin {
	scriptSig, _ := json.Marshal(vin.ScriptSig)

	mTxVin := BtcVin{
		Txid:      vin.Txid,
		vout:      int32(vin.Vout),
		Sequence:  int32(vin.Sequence),
		Witness:   vin.Witness,
		ScriptSig: scriptSig,
	}

	return &mTxVin
}
```
**ScriptSig** in BtcVin struct is a json column , and  **json.RawMessage** is an **[]byte** datatype.  

We should note that, When new a BtcVin strcut object, the **ScriptSig** field should full fill a** []byte** object.  

As **json.Marshal(v interface{})** take any type object and return **[]byte** err, so we can get ```scriptSig, _ := json.Marshal(vin.ScriptSig)``` and assign the scriptSig to **ScriptSig** field.  

Argument value in ```Marshal``` method(vin.ScriptSig) is an pointer to a struct object
