### ISSUE TITLE
Allow Arguments For Group

### ISSUE THREAD

**Issue by RichardKnop** [go-gorm/gorm#928]
Would be nice to be able to pass arguments to `Group` method.

Because doing this:

```
dateTrunc := "hour"
query.Group(fmt.Sprintf("date_trunc('%s', timestamp)", dateTrunc))
```

Is not very safe and could lead to SQL injection if not careful.

**Comment by pedromorgan** [comment]
Labelled as a feature.. we need some more sponsors and a patch
