### ISSUE TITLE
The gorm way to select a column

### ISSUE THREAD

**Issue by ghost** [go-gorm/gorm#94]
Hi,
I would like to select a column from a table and extract only this.
I tryed with the pluck method but doesn't work.

The query I would like to do is:

``` sql
SELECT "from" FROM blacklist WHERE "to" = 1
```

The "from" field is a int64. I need a way to extract a []int64.

Is there a fast way to do this or I have to do

``` go
db.Find(&bl, &Blacklist{to: tovariable})
```

And than iterate through bl and manually create the slice of "from" ?

**Comment by luaxlou** [comment]
ref:
https://github.com/jinzhu/gorm/issues/2044#issuecomment-496182903
